### ISSUE TITLE
[FEATURE] Upload to pastebin with hidden sensitive info

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1001]
```
./gameserver details-share
./gameserver ds
```

Or

```
/gameserver details-support
./gameserver ds
```

Or

```
./gameserver post-details
./gameserver pd
```

Or

```
./gameserver details-post
./gameserver dp
```

How to upload
https://gist.github.com/yevgenko/1803605

`details-share` could use the same function as `details`but with an `if`statement for sensitive info.

**Comment by UltimateByte** [comment]
0:41 - CedarLUG: http://steamcommunity.com/groups/linuxgsm/discussions/0/412448792353031314/#c412448792353224827

**Comment by cedarlug** [comment]
- password
- gslt
- steamuser
- steampass
- pushbullettoken
- authkey
- rcon_password
- rcts_strAdminPassword (SSam)
- sv_password
- zmq_stats_password
- zmq_rcon_password
- pass (Terraria)
- rconServerPassword (Starbound)
- IP Address (this actually comes in really handy for debugging, but could be stripped)
- ???

What else should be sanitized?

**Comment by UltimateByte** [comment]
I think you pretty much nailed it :o))

**Comment by cedarlug** [comment]
[Teaser](http://pastebin.com/71ynisvw)
I believe I have all of the items enumerated above, except IP addresses, able to be stripped.

**Comment by UltimateByte** [comment]
You've coded it ?

**Comment by cedarlug** [comment]
On my fork.

**Comment by UltimateByte** [comment]
Lol, "pd", is a french word for pédéraste, which means basically, "gay".
I'm already laughing thinking about asking people to run ./gameserver pd :o))

Good job btw..

Something cool would be to mask off the user only if it's something different than anonymous. That way we'd know if the user tries to login to steam while it's unnecessary.

Does it mask off info from fn_parms already ? 
Did you try pastebin upload ?

**Comment by cedarlug** [comment]
Good progress  on this - need some input though.

I have it so that steamuser=anonymous and steampass empty are reported rather than stripped.

What would you like to see for the scenario where the rustserver has default CHANGE_ME password?

Currently there's a warning output in the details output.  Should that be reported in the details that we ask users to post, or stripped because it's a default password used for rcon on someone's server?

**Comment by cedarlug** [comment]
... and yes, I've worked the curl to pastebin in.

**Comment by UltimateByte** [comment]
> What would you like to see for the scenario where the rustserver has default CHANGE_ME password?

You're going really deep into it :o))
I wouldn't worry about checking this, just mask off the password in any case. There is already a warning for it. :)

**Comment by cedarlug** [comment]
I've only tested the pull request on Rust and several hl2 games.  If you get a chance, could you roll #1037 into your local codebase and see if it works as expected?

I'm just using one fn_print_warn, as the output from postdetails is mainly just the link.

**Comment by dgibbs64** [comment]
I would like to roll logs in to this output as well. See an email alert for an example

**Comment by cedarlug** [comment]
Pastebin branch created, populated, and provisionally tested (with csgoserver and rustserver).

A couple of development/debugging tips:

- pastebin limits guest posts (the type implemented in this branch) to 10 per day per IP address. So the travis builds might run into some issues.
- a hastebin option will be added shortly.

**Comment by cedarlug** [comment]
@dgibbs64 & @UltimateByte - I'd like you to put eyes on the pastebin branch if you have a moment.

I've rolled in hastebin posting (the default), and everything should be reasonably up to date with origin.

The modifications do not effect e-mail notices, but are easily adapted to do so.

[hastebin example](http://www.hastebin.com/kicitujaye)
[pastebin example](http://pastebin.com/4Z7Gg336)

To change from one to the other, change the definition of POSTTARGET  in command_postdetails.sh

**Comment by UltimateByte** [comment]
Upvote for hastebin :)
Maybe you can pr so that we can easilly see modified files ?

**Comment by UltimateByte** [comment]
[  OK  ] Update LGSM gmod-server: Updating functions
gmodprobuild@game:~$ ./gmodserver pd
    fetching command_postdetails.sh...OK
[  OK  ] Postdetails gmod-server: Posting details to hastbin.com for 1W
  * url: http://hastebin.com/ifaloravaf


"hastbin.com", fail :p

**Comment by UltimateByte** [comment]
Well, this is merged, we can close !
