### ISSUE TITLE
'missing dependencies' even though they're installed

### ISSUE THREAD

**Issue by shavitush** [GameServerManagers/LinuxGSM#1004]
`[ERROR ] Starting css-server: Checking dependencies: missing: curl wget ca-certificates file bsdmainutils util-linux python bzip2 gzip lib32gcc1 libstdc++6:i386 lib32tinfo5`

I am running CentOS6 and I verified everything is installed. The server starts, but those errors are very misleading!

**Comment by UltimateByte** [comment]
I don't have  a CentOS 6 machine to try diagnosing stuff on it.
Can you please input this and share the output ?

```
command -v yum
command -v dpkg-query
```

If this is allright, i might ask you for some more. Unless a CentOS expert comes up before. :o)) 

Function to check : https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/check_deps.sh
CentOS important part : https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/check_deps.sh#L195

**Comment by dgibbs64** [comment]
I have never had this sort of issue before. Need to find out whats different.

**Comment by shavitush** [comment]
@UltimateByte 

```
[cssserver@gilgames ~]$ logout
[root@gilgames ~]# command -v yum
/usr/bin/yum
[root@gilgames ~]# command -v dpkg-query
/usr/bin/dpkg-query

```

Would also like to note this is what I'm getting:

```
Warning! cssserver does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt-get install curl wget ca-certificates file bsdmainutils util-linux python bzip2 gzip lib32gcc1 libstdc++6:i386 lib32tinfo5

```

`apt-get` is clearly for Ubuntu (or also Debian? I'm not sure!) and I think it detects the wrong distro

**Comment by UltimateByte** [comment]
```
command -v dpkg-query
/usr/bin/dpkg-query
```
To me it means that you got apt & yum installed which messes up with how lgsm detects your package management system and checks for installed packages. It takes the first one that is checks which is apt and then considers your distro to be a debian based.

We might need an additional check.

**Comment by shavitush** [comment]
Are you sure?

```
[root@gilgames ~]# apt
-bash: apt: command not found

[root@gilgames ~]# apt-get
-bash: apt-get: command not found
```

**Comment by UltimateByte** [comment]
Well maybe not apt, but least you got the dpkg system, which, it seems, is unusual for CentOS as you're the first one showing up with this issue :o))

**Comment by dgibbs64** [comment]
Yes its odd that you have dpkg-query on your system.

**Comment by UltimateByte** [comment]
@dgibbs64 How should we deal with it ?
Check with distroname rather than by yum/dpkg installed ?
Add a distroname check but geek the current check ?

**Comment by jaredballou** [comment]
/etc/redhat-release will tell you that you're on a RHEL family distro. I believe Ubuntu has a similar file. Probably better than relying upon the package manager existing, I have built RPMs in Debian and Apt packages from CentOS.

**Comment by dgibbs64** [comment]
Thr fix to this is to detect apt-get rather than dpkg-query

**Comment by shavitush** [comment]
This is actually not fixed yet, can you re-open please?

```
[cssserver@gilgames ~]$ ./cssserver start
[ERROR ] Starting css-server: Checking dependencies: missing: bsdmainutils util-linux lib32gcc1 libstdc++6:i386 lib32tinfo5

Warning! cssserver does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt-get install bsdmainutils util-linux lib32gcc1 libstdc++6:i386 lib32tinfo5

[  OK  ] Log-Manager css-server: Starting
[ INFO ] Log-Manager css-server: Removing logs older than 7 days
[  OK  ] Log-Manager css-server: Removed 283 log files
[  OK  ] Starting css-server: bhop.online ~ whitelisted auto

```

**Comment by DigitalFriends** [comment]
Hi, thanks. 

Workaround is still to remove dpkg.

**Comment by rokam** [comment]
python shown as missing, although it's installed
`$ yum -q list installed python*
Installed Packages
python26.x86_64                                                   2.6.9-2.88.amzn1                         @amzn-main
python26-libs.x86_64                                              2.6.9-2.88.amzn1                         @amzn-main
python27.x86_64                                                   2.7.12-2.120.amzn1                       installed
python27-PyYAML.x86_64                                            3.10-3.10.amzn1                          installed
python27-babel.noarch                                             0.9.4-5.1.8.amzn1                        installed
python27-backports.x86_64                                         1.0-3.14.amzn1                           installed
python27-backports-ssl_match_hostname.noarch                      3.4.0.2-1.12.amzn1                       installed
python27-boto.noarch                                              2.42.0-1.1.amzn1                         installed
python27-botocore.noarch                                          1.4.86-1.62.amzn1                        installed
python27-chardet.noarch                                           2.0.1-7.7.amzn1                          installed
python27-colorama.noarch                                          0.2.5-1.7.amzn1                          installed
python27-configobj.noarch                                         4.7.2-7.15.amzn1                         installed
python27-crypto.x86_64                                            2.6.1-1.12.amzn1                         installed
python27-daemon.noarch                                            1.5.2-1.5.amzn1                          installed
python27-dateutil.noarch                                          2.1-1.3.amzn1                            installed
python27-devel.x86_64                                             2.7.12-2.120.amzn1                       installed
python27-docutils.noarch                                          0.11-1.15.amzn1                          installed
python27-ecdsa.noarch                                             0.11-3.3.amzn1                           installed
python27-futures.noarch                                           3.0.3-1.3.amzn1                          installed
python27-imaging.x86_64                                           1.1.6-19.9.amzn1                         installed
python27-iniparse.noarch                                          0.3.1-2.1.9.amzn1                        installed
python27-jinja2.noarch                                            2.7.2-2.15.amzn1                         installed
python27-jmespath.noarch                                          0.9.0-1.11.amzn1                         installed
python27-jsonpatch.noarch                                         1.2-2.5.amzn1                            installed
python27-jsonpointer.noarch                                       1.0-3.4.amzn1                            installed
python27-kitchen.noarch                                           1.1.1-5.6.amzn1                          installed
python27-libs.x86_64                                              2.7.12-2.120.amzn1                       installed
python27-lockfile.noarch                                          0.8-3.5.amzn1                            installed
python27-markupsafe.x86_64                                        0.11-4.6.amzn1                           installed
python27-paramiko.noarch                                          1.15.1-1.5.amzn1                         installed
python27-pip.noarch                                               6.1.1-1.23.amzn1                         installed
python27-ply.noarch                                               3.4-3.12.amzn1                           installed
python27-pyasn1.noarch                                            0.1.7-2.9.amzn1                          installed
python27-pycurl.x86_64                                            7.19.0-17.12.amzn1                       installed
python27-pygpgme.x86_64                                           0.3-9.12.amzn1                           installed
python27-pyliblzma.x86_64                                         0.5.3-11.6.amzn1                         installed
python27-pystache.noarch                                          0.5.3-2.8.amzn1                          installed
python27-pyxattr.x86_64                                           0.5.0-1.6.amzn1                          installed
python27-requests.noarch                                          1.2.3-5.10.amzn1                         installed
python27-rsa.noarch                                               3.4.1-1.8.amzn1                          installed
python27-setuptools.noarch                                        12.2-1.32.amzn1                          installed
python27-simplejson.x86_64                                        3.6.5-1.12.amzn1                         installed
python27-six.noarch                                               1.8.0-1.23.amzn1                         installed
python27-urlgrabber.noarch                                        3.9.1-9.13.amzn1                         installed
python27-urllib3.noarch                                           1.8.2-1.5.amzn1                          installed
python27-virtualenv.noarch                                        12.0.7-1.13.amzn1                        installed
`

**Comment by UltimateByte** [comment]
@rokam Distro ?
apt or dpgk installed on top of yum ?

**Comment by ChaosMTA** [comment]
Reopen the issue if you have additional information for us @rokam
