### ISSUE TITLE
Dependency Check blocks for deps that aren't required

### ISSUE THREAD

**Issue by Mviner04** [GameServerManagers/LinuxGSM#1005]
Thanks for this tool, I was completely stuck trying to get a new Starbound server setup on my Ubuntu server and wouldn't have been able to get it running without LGSM. However, on Ubuntu 14.04 64-bit running on Intel processors you cannot install lib32gcc1. Installing all the variants I could find via Google still did not solve the issue of this missing dependency.

After hours of googling I gave up and decided I would just see if I disabled the dependency check, if the server would run. Long story short, disabled the check for dependencies in check.sh and the game runs fine without it. So a prompt to give us the option to continue running the command(s) even with missing dependencies via the cli may be a simple solve to this. Or better detection around what dependencies are actually needed may be necessary. 

Either way, lib32gcc1 was not needed to run starbound_server.

**Comment by UltimateByte** [comment]
Hi,
Let's try to understand your machine first.

I'd need some outputs.
Please, run those as root : 

```
apt-get install lib32gcc1 libstdc++6 libstdc++6:i386 
dpkg-query -W -f='${Status}' libc6; echo ""
dpkg-query -W -f='${Status}' lib32gcc1; echo ""
dpkg-query -W -f='${Status}' libstdc++6:i386; echo ""
```
(the echo "" is just so that it is more readable)

**Comment by jaredballou** [comment]
Isn't there something that one has to do on Ubuntu to add i686 support? I recall having to run something before apt-get to set up my Ubuntu server a ways back. Or, perhaps some other package has provided the dependency another way?

**Comment by UltimateByte** [comment]
Well, for now, this kind of commands to add packages is only known to be necessary for Debian.

**Comment by UltimateByte** [comment]
Fix : `dpkg --add-architecture i386; apt-get update`
Related (still to solve) : https://github.com/GameServerManagers/LinuxGSM/issues/771

Closing
