### ISSUE TITLE
CounterStrikeSource GSLT

### ISSUE THREAD

**Issue by rusty1506** [GameServerManagers/LinuxGSM#1006]
Counter Strike Source needs to also start the GSLT token you can install the in the Counter Strike Source scripts ??

MfG
Rusty

**Comment by UltimateByte** [comment]
What ?
Can you reformulate ?

**Comment by dgibbs64** [comment]
Do you mean that GSLT is now available on Counter Strike: Source? 

Is is optional or required?

**Comment by rusty1506** [comment]
Counter Strike: Source is now required of GSLT

**Comment by dgibbs64** [comment]
Thanks. WIll need to update the script :)

**Comment by rusty1506** [comment]
Thanks sorry for my bad english come also Germany

**Comment by dgibbs64** [comment]
Done :). Thanks
