### ISSUE TITLE
Steam group user access control

### ISSUE THREAD

**Issue by easyas12pc** [GameServerManagers/LinuxGSM#1007]
As part of the "standard" rust server it is possible to limit login by means of a steam group. Is this possible in Linux game server manager and if not can it be implemented?

**Comment by jach11** [comment]
That goes deeper than what lgsm is intended to do, that's probably possible to be done via rust's config files. Doing a quick google of "rust steam group whitelist" showed this as the first result. http://rust-essentials.wikia.com/wiki/Whitelisting_your_Server_with_a_Steam_Group

**Comment by easyas12pc** [comment]
Thanks but I already tried entering the commands into the LGSM server.cfg file as the server.ini file is not present. Attempting to enter the same command into the Bash script will not work either. Many of the Rcon commands do not work or are not found when entering on the server using Rusty Rcon Application.  I was hoping that either the devs or more learned members of this Git could point me to the correct location to enter the commands (as you linked) or request that it is included in future LGSM versions.

**Comment by easyas12pc** [comment]
closed in error

**Comment by jach11** [comment]
I just tested the server myself, everything seems to be working fine while using rusty. In your `~/serverfiles/server/rust-server/cfg` directory open up `server.cfg` and on a new line set `server.steamgroup "STEAMGROUPID"`. For example `server.steamgroup "103582791437373633"` would only allow LGSM group members to join. In rusty does it say your're connecting successfully to your server at the bottom? If you enter `find .` as an rcon command does it return a full list of available commands on the server?

**Comment by easyas12pc** [comment]
I have entered all the information as shown in the original linked document again. I am unable to test tonight but I will do again when my friend aka Guinea pig :) is available. Rusty connects without issue but some commands do not work if teleport.player. States no command found. I will investigate this further at the same time as testing server access.

**Comment by jach11** [comment]
Right, because teleport.player isn't an actual available command on the server.
Doing `find teleport` returns the following available results:

- global.teleport( void ) no description
- global.teleport2me( void ) no description
- global.teleportany( void ) no description
- global.teleportpos( void ) no description

**Comment by cedarlug** [comment]
+1 on the "...pretty big mess." @jach11

**Comment by UltimateByte** [comment]
I guess this is to be closed.
If further help is needed, i suggest posting on oxide forums or into our steam group.
Cheers ;)
