### ISSUE TITLE
Arma 2 / A2 DayZ server

### ISSUE THREAD

**Issue by AlucardVoss** [GameServerManagers/LinuxGSM#1020]
Is it possible to make an Arma 2 / DayZ server in Linux ? My small gaming community always uses LSM for their servers. I tried following the guides on BI forum but failed.

**Comment by dgibbs64** [comment]
Haha yes BI and good guides don't go together :-P. Honest answer is I don't know but we can take a look.

**Comment by marvinl97** [comment]
ARMA2 could work (#926) but vanilla DayZ probably not because there isn't a Linux version of the HiveExt. Atleast I didn't find one. You will need wine and a X server.

**Comment by dgibbs64** [comment]
Closing related to #926 

DayZ looks like its probably not possible
