### ISSUE TITLE
[L4D2] Segmentation faults even after new distro and reinstall

### ISSUE THREAD

**Issue by sdf3333** [GameServerManagers/LinuxGSM#1021]
I had the GSM installed for my Debian server for Left 4 Dead 2, and kept getting segmentation fault errors when loading new maps or loading into a game. I read that a lot of people were mentioning debian in regards to the issue so I switched to CentOS and did a clean install of L4D2 with the GSM. The only changes made were to install Metamod and Sourcemod (no mods installed inside them).

I thought it was okay because it was working for a while, but when I left and started a new game in my server a bunch of times to see if it was completely fixed it got a segmentation fault again.

The CentOS install has more information in the server console when it happens than Debian

`(SKIN) SetCharacter: Survivor Tom chose character Gambler(0) from model models/survivors/survivor_gambler.mdl`
`./srcds_run line 312: 6347 Segmentation fault     $HL_CMD`

Then it says there will be a server restart in 10 seconds

I'm at a loss as to what is causing this, the closest thing related to this I could find is someone having segmentation faults [here](https://steamcommunity.com/groups/linuxgsm/discussions/0/360672383114891662/) at sort of the same place in L4D2, but I haven't edited or changed the autoexec file. The crash happens when switching maps or loading a game from the lobby, when the game is almost fully loaded to the client. It always happens **right after** it says my character chose a skin.

**Comment by UltimateByte** [comment]
Hi,

Changing Debian for CentOS because of segfaults. What a bad idea, lol.
Sefgaults can have numerous reasons, but usually, it's either due to a bad addon's binary, or, a wrong glibc version, or, a wrong glibc fix. Let's try to see if LGSM installed a glibc fix : 
`ls ~/lgsm`
`ls ~/lgsm/lib`
`ls ~/lgsm/bin`
(i'm not sure if it's in lib or bin, seen it once only :p )

**Comment by sdf3333** [comment]
http://pastebin.com/f2LDyPEU Here is my l4d2-server.cfg
There is no autoexec.cfg, I didn't make any and the program never made one

Here is my ./l4d2server details
http://pastebin.com/sFebtbMA

There is no lib or bin folder in the lgsm folder, only 'functions' and 'tmp'. The temp has a steamcmd_linux.tar.gz file inside, and the functions folder has the following http://pastebin.com/Cb1HqFXp

> Ultimately, is there a special context where segfaults happen ?

On new maps, very often after a full game has been completed and a new game is being loaded. The segfaults happen right after lines such as this 

`(SKIN) SetCharacter: Survivor Tom chose character Gambler(0) from model models/survivors/survivor_gambler.mdl`

Directly after it says I chose a character (spawned/loaded into the game)

**Comment by sdf3333** [comment]
Just did another fresh install, this is not related to Sourcemod or Metamod since they aren't installed. Segfaults still happening right after the Survivor gets assigned a character. Not every time, the segfaults happen about 10% of the time I try to load in to the server, but when they do happen they happen at the exact same time.

From the new debug.log

```
----------------------------------------------
CRASH: Wed Aug 24 12:23:52 EDT 2016
Start Line: ./srcds_linux -game left4dead2 -strictportbind -ip (IP removed) -port 27015 +clientport 27005 +m$
[New LWP 12159]
[New LWP 12319]
[New LWP 12173]
[New LWP 12317]
[New LWP 12323]
No symbol table info available.
eax            0x1      1
ecx            0xb6e11e8c       -1226760564
edx            0xb6c9a128       -1228299992
ebx            0xa5ab83f4       -1515486220
esp            0xbf8dcab0       0xbf8dcab0
ebp            0xbf8dcaf8       0xbf8dcaf8
esi            0x1      1
edi            0x1      1
eip            0xad9a7d09       0xad9a7d09
eflags         0x210282 [ SF IF RF ID ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x0      0
gs             0x63     99
End of Source crash report
----------------------------------------------
```

**Comment by dgibbs64** [comment]
I have had set faults because not enough ram. But that's just a guess

**Comment by jach11** [comment]
Was going to mention it might be worth posting what kind of hardware this is being run on, especially if you're getting seg faults on a clean install.

**Comment by sdf3333** [comment]
512 RAM / 256 MB swap, 2 Cores (Intel E3) VZ SSD VPS

While games are loading and when I am playing I am only using about 160MB of the 512, Swap is using about 20MB/256MB, CPU % shows if generally under 8% with some minor spikes while loading

**Comment by UltimateByte** [comment]
> On new maps, very often after a full game has been completed and a new game is being loaded. The segfaults happen right after lines such as this

Could cause a RAM usage peak then force close.

I'd put more swap considering you got only 512MB RAM, but i can't be sure this is the cause.
I would also have suspected Tmux 1.8 to be the issue, but since you had the same issue with Debian, it's probably not the cause.

Since it happens while loading game files, maybe it's because of currupted gamefiles ? In this case, this would help : 
`./l4d2server validate`

Glibc 2.17 is good enough. Usually, it works or it doesn't, but i've never seen a case where it only works partially... yet.

**Comment by jach11** [comment]
I'd put the issue on his VPS not having enough ram. He would most likely have to upgrade it, depending on his host solution.

**Comment by sdf3333** [comment]
Even during successful loads and gameplay the RAM usage is under 160MB and I've never seen the entire system use more than 200MB while monitoring, if the process crashes it just shows it going from ~25% of the system RAM usage to nothing because the process disappears. The RAM usage doesn't spike at all during successful loads, and it doesn't show it spiking during crashes either.

**Comment by UltimateByte** [comment]
Maybe it tries to allocate RAM even though you don't see it happening. 
The game itself required min Windows XP with 1GB RAM at launch, so... It's kinda sad if this is the case because i'd love seing this running on modest configs.

Otherwise i got no clue other than what i already said.
Maybe a bad kernel, a CPU interruption... Don't know.
`uname -a` to see your kernel.

**Comment by jach11** [comment]
What host are you currently using if you don't mind me asking? If it's a host that also allows hourly usage i would try to upgrade the VPS to something with 1GB of ram and test that to see if the issue still persists.

**Comment by sdf3333** [comment]
I am switching hosts entirely to see if it fixes the problem, and will update when I find out what happens and if the problem persists.

**Comment by UltimateByte** [comment]
Awaiting for feedback then. :)

**Comment by sdf3333** [comment]
I had Ramnode but just tested this on a new VPS with 1GB RAM from Serverhub. Same problem, crashed at the same point on the 3rd attempt at starting games. (Start game from lobby, success, leave and repeat until the crash)

```
L 08/24/2016 - 16:13:57: SetModelFromClass: Survivor Tom changed model from  to models/survivors/survivor_mechanic.mdl via SetModelFromClass
L 08/24/2016 - 16:13:57: (SKIN) SetCharacter: Survivor Tom chose character Mechanic(3) from model models/survivors/survivor_mechanic.mdl
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed Aug 24 16:13:57 EDT 2016: Server restart in 10 seconds
```

Debian 8 install, the only thing I did was to apt-get update/upgrade, then followed the instructions on the install page for the l4d2 server manager. No problems, it took about 20 minutes to install, then I typed in the server name and rcon password when asked. Started the server, watched the console until the segfault showed up, there was literally nothing done on the server besides what I mentioned.

**Comment by jach11** [comment]
I will test it myself when i get back home

**Comment by sdf3333** [comment]
I don't know if this is confirmation bias or not but this only seems to happen if I connect via the lobby. I tried connecting directly via IP address (connect IP address), leave, and reconnecting that way about 30 times and it never got the segfault. Then on about 20 attempts via lobby Realism games 4 segfaults. So I connect via having mm_dedicated_force_servers set to my server's IP in my clientside autoexec.cfg

I'll update this if I can ever get it to crash via 'connect' in client console instead of joining from the lobby

**Comment by jach11** [comment]
Just tested it on a VPS with bhyve
Debian 9 w/4.6.0-1-amd64
2 Cores (Intel 1230v2)
4GB RAM
50GB Storage

Packages:
lib32gcc1 - v1:6.1.1-11
libstdc++6:i386 - v6.1.1-11
python - v2.7.11-2
tmux - v2.2-3

http://pastebin.com/raw/j22DUK5K
No seg faults at all.

**Comment by dgibbs64** [comment]
FYI I recommend using OVH (Kimsufi), Digital Ocean or Vultr. OVH being my favorite :)

**Comment by JimTR** [comment]
I do hope you have gone through the same bug pattern as the op just firing a server up there and it works is not what is required here surly you need to work out if its a game fault , script fault or hardware fault rather than saying 'it works'

**Comment by sdf3333** [comment]
I just wiped again and am reinstalling after doing a dist upgrade to Debian 9 as well, so I should have the same packages as you. If I am still getting the segfaults after should I try to contact valve instead? I know it's probably almost impossible they will respond to me in any way)

Is there some way to rule out if GSM is causing this, for example would starting the server via ./srcds_run be representative of doing a normal install without GSM or would it cause potential issues with config files it created?

**Comment by dgibbs64** [comment]
Seg faults are generated by the binary file e.g srcds_linux. Seg faults are not an LGSM issue and will happen even without LGSM. LGSM is simply a very clever bash script that tells the server binary to run. 

Seg faults are commonly caused when the binary has some issue with the OS or hardware. The problem is that seg faults are vague and dont tell you what the issue actually is.

Hope this helps.

**Comment by jach11** [comment]
@JimTR Would you like me to record myself going through the process of connecting to the server and loading each chapter of the game? It was actually a very boring and slow process, especially with the laptop that i'm forced to use right now. 

@sdf3333 
You can load the server manually if you'd like to, but i doubt it's an issue with LGSM.

**Comment by sdf3333** [comment]
Thanks for the help, sorry for wasting all your time then. I guess I'll have to wait and see if valve responds.

**Comment by UltimateByte** [comment]
NP, you can't know before you ask, and you asked nicely :p 
The only thing you can hopefully do to understand the issue is to get Valve to interpret your core dump, which isn't easy.

Otherwise, find another provider, becauce there might be something wrong with how it works, sometimes they provided modified distros, and make really crappy stuff, especially on VPS. Could still be a RAM issue though.

Wish you'll solve your issue ! Don't hesitate to report back, even though the issue is closed. ;)

**Comment by JimTR** [comment]
@jach11  no would I ask that. I just mentioned did you follow the OP's bug trace exactly I.e followed the same process if you did not there is the point that you may have missed an issue within the game/hardware if you did there is a script issue simple process of elimination surly ?

**Comment by jach11** [comment]
@JimTR I did exactly what OP was doing. You're right, if i hadn't followed the same process then i could have missed an issue, but that's not the case.
