### ISSUE TITLE
Way to install steamcmd

### ISSUE THREAD

**Issue by hyperbolic2346** [GameServerManagers/LinuxGSM#1022]
I run linuxgsm in a docker container and my server is in a volume. This means that I don't always run install, which seems to be the only way to get steamcmd downloaded. I'm leaving linuxgsm in the container itself and just let it download commands, but without a way to tell it to download steamcmd I'm stuck curling it myself in my Dockerfile. Is there any chance you would be willing to expose this functionality?

**Comment by Scarsz** [comment]
Run `./lgsm/functions/install_steamcmd.sh` manually

**Comment by UltimateByte** [comment]
Dockers are neither supported or recommended. However, some people already tried it, and i guess some of them got it working, so you might find some more help if needed on the appropriate general support locations which are Discord and the Steam Group. 
https://discordapp.com/channels/127498813903601664/127498813903601664
http://steamcommunity.com/groups/linuxgsm/discussions/0/

Cheers. ;)
