### ISSUE TITLE
Permission issues : Add link to the wiki

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1023]
While the error message is being displayed, add a link to the wiki at the bottom

https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#-fail--starting-game-server-permissions-issues-found

**Comment by UltimateByte** [comment]
I'm done reworking it a bit
Demo http://imgur.com/a/wa2d5

**Comment by UltimateByte** [comment]
PS : Noticed functions folder wasn't checked for ownershop, so i added it with a slight rework on the checking logic.
We might add more, such as : 
log
lgsm
backups

**Comment by jach11** [comment]
Very nice work, although i suspect a lot of users will still probably be posting about this issue, it should help cut down on the amount of them, if they know how to read.

**Comment by UltimateByte** [comment]
Thanks

> if they know how to read
Lol, there will still be some lame ducks :p
