### ISSUE TITLE
[Website] Missing space in Debian dependencies

### ISSUE THREAD

**Issue by jach11** [GameServerManagers/LinuxGSM#1025]
Debian 64Bit
Tmux is currently connected to lib32gcc1
https://gameservermanagers.com/lgsm/l4d2server/
`sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install mailutils postfix ca-certificates curl wget file gzip bzip2 bsdmainutils python util-linux tmuxlib32gcc1 libstdc++6 libstdc++6:i386`

This is corrected
`sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install mailutils postfix ca-certificates curl wget file gzip bzip2 bsdmainutils python util-linux tmux lib32gcc1 libstdc++6 libstdc++6:i386`

**Comment by hurdad** [comment]
I can fix this

**Comment by jach11** [comment]
Thnx

**Comment by hurdad** [comment]
what version of debian are you using? 8/8.5?

**Comment by jach11** [comment]
I thought this was something that @dgibbs64 has to fix?

**Comment by UltimateByte** [comment]
I think Hurdad is missing the point here, otherwise he wouldn't ask. :p 
The title is misleading btw, i'll edit it

**Comment by hurdad** [comment]
oh you want wiki updated. my bad.

**Comment by UltimateByte** [comment]
The website actually. Title was mindfucking, edited. :)

**Comment by jach11** [comment]
My bad guys, i should of used a better title.

**Comment by UltimateByte** [comment]
That's fine, Daniel will probably fix it tomorrow, as he's the only one having access to the website, i think.

**Comment by UltimateByte** [comment]
Closing this one, as a more complete issue has just been opened.
