### ISSUE TITLE
[mcserver] Do NOT attempt to install default-jdk if existing Java installation is found

### ISSUE THREAD

**Issue by Scarsz** [GameServerManagers/LinuxGSM#1027]
Wastes time and **_will**_ lead to problems with conflicting Java versions

**Comment by UltimateByte** [comment]
Ideas on implementation of that one ?
check_deps.sh isn't really designed that way for now.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/check_deps.sh

**Comment by JimTR** [comment]
perhaps this helps 
`
if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable  in JAVA_HOME     
    _java="$JAVA_HOME/bin/java"
else
    echo "no java"
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"

fi

`

**Comment by JimTR** [comment]
you could try this
``` dpkg -l "*openj*" |grep ii```
seems to work on ubuntu 14.04/16.04 ...  The code  returns nothing if no java is intalled   or returns

> 

 **ii  openjdk-7-jre:amd64                 7u111-2.6.7-0ubuntu0.14.04.3     amd64        OpenJDK Java runtime, using Hotspot JIT**

**ii  openjdk-7-jre-headless:amd64        7u111-2.6.7-0ubuntu0.14.04.3     amd64        OpenJDK Java runtime, using Hotspot JIT (headless)** 
if installed , from that it wont be an issue extracting the string **openjdk-x-jre** from the output x being the version number

**Comment by cedarlug** [comment]
If you install the official Java packages (built from Oracle sources) using java-package in Debian/Ubuntu,  you'll have the situation where your grep expression above would return nothing, but a default and valid Java is installed on the system
```root@vps5:~# dpkg -l | grep jdk```
```ii  oracle-java8-jdk                               8u92                       amd64        Java™ Platform, Standard Edition 8 Development Kit```

**Comment by JimTR** [comment]
so the command 
```dpkg -l "*jdk*" | grep "ii " ```
returns installed jre 
and ```dpkg -l "*jdk*" | grep "un "```

returns uninstalled versions what is the difference ?

**Comment by dgibbs64** [comment]
I am looking at this now :)

**Comment by JimTR** [comment]
@cedarlug  just been thinking of this ... and possible flaws how many people will build from Oracle Sources ? I would most would just use what dpkg has to offer ... unless there is a trick I've missed

**Comment by dgibbs64** [comment]
Added fix to the development branch. Please take a look and if happy I will merge

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/1054
