### ISSUE TITLE
[Website] Typos

### ISSUE THREAD

**Issue by marvinlehmann** [GameServerManagers/LinuxGSM#1028]
First of all something different. I experienced strange caching issues. Sometimes old pages were shown, where Fedora wasn't included and server/game names weren't written out and sometimes the new ones.

And almost always my Chrome can't finish loading sites. It definitely works if I open a new incognito page and load a page/visit your website for the first time.
## General Pages:

https://gameservermanagers.com/:
<strike>\- `to get there server working` -> `to get their server working`</strike>
<strike>\- `Waffle (Github Dashboard)` links to https://waffle.io/dgibbs64/linuxgsm instead of https://waffle.io/GameServerManagers/LinuxGSM</strike>
<strike>\- `most sucessful project` -> `most successful project`</strike>

https://gameservermanagers.com/features/:
<strike>\- `Including downloading applying fixes and loading a basic config.` -> `Including downloading and applying fixes or loading a basic config.`</strike>
## Server Pages:

**Common:**
Wouldn't be unifying the case of the command headers in the "Basic Usage"-section more beautiful?
The use of header texts and command names is inconsistent e.g. when there is just one child command.

<strike>I'm not sure about the `glibc =>`. Should it be dynamic or just a link? Some servers are missing the version.</strike>

<strike>**\- Debian 64-bit: `tmuxlib32gcc1` -> `tmux lib32gcc1`** ( #1025 - not only L4D2, almost all servers)<strike>

<strike>https://gameservermanagers.com/lgsm/bb2server/ &
https://gameservermanagers.com/lgsm/dstserver/:
- Ubuntu 64-bit: `libstdc++6:i386libcurl4-gnutls-dev:i386` -> `libstdc++6:i386 libcurl4-gnutls-dev:i386`
- Ubuntu 32-bit: `libstdc++6libcurl4-gnutls-dev` -> `libstdc++6 libcurl4-gnutls-dev`
- Debian 32-bit: `libstdc++6libcurl4-gnutls-dev` -> `libstdc++6 libcurl4-gnutls-dev`
- CentOS 64-bit & Fedora 64-bit: `libstdc++.i686libcurl.i686` -> `libstdc++.i686 libcurl.i686`
- CentOS 64-bit & Fedora 32-bit: `libstdc++libcurl` -> `libstdc++libcurl`</strike>

<strike>https://gameservermanagers.com/lgsm/dstserver/:
- `See further notes for setup and configuration: https://github.com/dgibbs64/linuxgsm/wiki/Don%E2%80%99t-Starve-Together` - page doesn't exist</strike>

<strike>https://gameservermanagers.com/lgsm/ccserver/ &
https://gameservermanagers.com/lgsm/cssserver/ &
https://gameservermanagers.com/lgsm/gmodserver/ &
https://gameservermanagers.com/lgsm/nmrihserver/:
- Ubuntu 64-bit: `libstdc++6:i386lib32tinfo5` -> `libstdc++6:i386 lib32tinfo5`
- Ubuntu & Debian 32-bit: `libstdc++6lib32tinfo5` -> `libstdc++6 lib32tinfo5`
- CentOS & Fedora 64-bit: `libstdc++.i686ncurses-libs.i686` -> `libstdc++.i686 ncurses-libs.i686`
- CentOS & Fedora 32-bit: `libstdc++ncurses-libs` ->  `libstdc++ ncurses-libs`</strike>

https://gameservermanagers.com/lgsm/mumbleserver/:
<strike>\- Fedora is missing if it isn't a caching error.</strike>

<strike>https://gameservermanagers.com/lgsm/ns2cserver/ & https://gameservermanagers.com/lgsm/ns2server/:
- Ubuntu 64-bit: `libstdc++6:i386speex:i386` -> `libstdc++6:i386 speex:i386`
- Ubuntu & Debian 32-bit: `libstdc++6speex` -> `libstdc++6 speex`
- CentOS & Fedora 64-bit: `libstdc++.i686speex.i686` -> `libstdc++.i686 speex.i686`
- CentOS & Fedora 32-bit: `libstdc++speex`</strike>

<strike>https://gameservermanagers.com/lgsm/pzserver/:
- Ubuntu 64-bit: `libstdc++6:i386default-jre` -> `libstdc++6:i386 default-jre`
- Ubuntu & Debian 32-bit: `libstdc++6default-jre` -> `libstdc++6 default-jre`
- CentOS & Fedora 64-bit: `libstdc++.i686java-1.8.0-openjdk` -> `libstdc++.i686 java-1.8.0-openjdk`
- CentOS & Fedora 32-bit: `libstdc++java-1.8.0-openjdk` -> `libstdc++ java-1.8.0-openjdk`</strike>

<strike>https://gameservermanagers.com/lgsm/sdtdserver/:
- Ubuntu 64-bit: `libstdc++6:i386telnet` -> `libstdc++6:i386 telnet`
- Ubuntu 32-bit: `libstdc++6telnet` -> `libstdc++6 telnet`
- Debian 32-bit: `libstdc++6telnet` -> `libstdc++6 telnet`
- CentOS & Fedora 64-bit: `libstdc++.i686telnet` -> `libstdc++.i686 telnet`
- CentOS & Fedora 32-bit: `libstdc++telnet` -> `libstdc++ telnet`</strike>

</strike>https://gameservermanagers.com/lgsm/ss3server/:
- Ubuntu 64-bit: `libstdc++6:i386libxrandr2:i386` -> `libstdc++6:i386 libxrandr2:i386`
- Ubuntu 32-bit: `libstdc++6libxrandr2` -> `libstdc++6 libxrandr2`</strike>

</strike>https://gameservermanagers.com/lgsm/ut2k4server/:
- Ubuntu 64-bit: `libstdc++6:i386libsdl1.2debian` -> `libstdc++6:i386 libsdl1.2debian`
- Ubuntu & Debian 32-bit: `libstdc++6libsdl1.2debian` -> `libstdc++6 libsdl1.2debian`
- CentOS & Fedora 64-bit: `libstdc++.i686compat-libstdc++-33.i686` -> `libstdc++.i686 compat-libstdc++-33.i686`
- CentOS & Fedora 32-bit: `libstdc++compat-libstdc++-33` -> `libstdc++ compat-libstdc++-33`</strike>

</strike>https://gameservermanagers.com/lgsm/ut99server/:
- Ubuntu 64-bit: `libstdc++6:i386libsdl1.2debian` -> `libstdc++6:i386 libsdl1.2debian`
- Ubuntu & Debian 32-bit: `libstdc++6libsdl1.2debian` -> `libstdc++6 libsdl1.2debian`
- CentOS & Fedore 64-bit: `libstdc++.i686SDL.i686` -> `libstdc++.i686 SDL.i686`
- CentOS & Fedora 32-bit: `libstdc++SDL` -> `libstdc++ SDL`</strike>

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/1025

**Comment by dgibbs64** [comment]
Thanks. Im working on the site currently. So this is really useful! AS you can probably tell my spelling is not the best :P

**Comment by dgibbs64** [comment]
Im going to edit your commend as I fix things

**Comment by marvinl97** [comment]
You hate these poor spaces! :)

**Comment by UltimateByte** [comment]
As you're in there, you can also solve this one : ubuntu dpkg --add-architecture i386 required
https://github.com/GameServerManagers/LinuxGSM/issues/771

Ubuntu needs to
