### ISSUE TITLE
[mcserver] Debian/Ubuntu x64: Further dependencies are missing

### ISSUE THREAD

**Issue by Sebi94nbg** [GameServerManagers/LinuxGSM#1029]
> Checking Dependencies
> =================================
> tmux
> curl
> wget
> ca-certificates
> file
> bsdmainutils
> util-linux
> python
> bzip2
> gzip
> lib32gcc1
> libstdc++6:i386
> default-jdk
> [ERROR ] Install mc-server: Checking dependencies: missing: lib32gcc1 libstdc++6:i386

Please add these two packages to the list of required packages in your [installation documentation](https://gameservermanagers.com/lgsm/mcserver/?platform=hootsuite#gettingstarted): lib32gcc1 libstdc++6:i386

**Comment by Sebi94nbg** [comment]
I've just updated the title, because I can't say, if they're also required on a x86 server or only on a x64 server, due of that, that I've just tested it on x64. But I think, that you need the package _lib32gcc1_ at least also on x86 servers.

**Comment by Sebi94nbg** [comment]
Updated title, because the same dependencies are missing on Ubuntu x64.

**Comment by UltimateByte** [comment]
I guess they shouldn't be checked as not needed for minecraft. 
Will check the code.

**Comment by UltimateByte** [comment]
OK, i guess i found the issue
There's an || check instead of && i think, will ask for confirmation.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/check_deps.sh#L222

**Comment by UltimateByte** [comment]
Allright, it should be fixed now, update your LGSM with 
`./mcserver uf`
or the long version : 
`./mcserver update-functions`

**Comment by Sebi94nbg** [comment]
Yes, I can confirm that.
```
mcserver@lgsm-debian8:~$ ./mcserver uf
    fetching command_update_functions.sh...OK
[ .... ] Update LGSM mc-server: Updating functions
    checking check_config.sh...OK
    checking check_deps.sh...UPDATE
    fetching check_deps.sh...OK
    checking check_glibc.sh...OK
    checking check_ip.sh...OK
    checking check_logs.sh...OK
    checking check_permissions.sh...UPDATE
    fetching check_permissions.sh...OK
    checking check_root.sh...OK
    checking check.sh...OK
    checking check_status.sh...OK
    checking check_system_dir.sh...OK
    checking check_system_requirements.sh...OK
    checking command_details.sh...OK
    checking command_install.sh...OK
    checking command_start.sh...OK
    checking command_stop.sh...OK
    checking command_update_functions.sh...OK
    checking core_dl.sh...OK
    checking core_exit.sh...OK
    checking core_functions.sh...OK
    checking core_getopt.sh...OK
    checking core_messages.sh...OK
    checking core_trap.sh...OK
    checking fix.sh...OK
    checking info_config.sh...OK
    checking info_distro.sh...OK
    checking info_glibc.sh...OK
    checking info_parms.sh...OK
    checking install_complete.sh...OK
    checking install_config.sh...OK
    checking install_header.sh...OK
    checking install_logs.sh...OK
    checking install_minecraft_eula.sh...OK
    checking install_server_dir.sh...OK
    checking install_server_files.sh...OK
    checking logs.sh...OK
    checking update_minecraft.sh...OK
[  OK  ] Update LGSM mc-server: Updating functions
mcserver@lgsm-debian8:~$
mcserver@lgsm-debian8:~$ ./mcserver start
[ WARN ] Starting mc-server: Check RAM: 1G required, 986M available
        * Minecraft server may fail to run or experience poor performance.
[  OK  ] Starting mc-server:
mcserver@lgsm-debian8:~$
```
Thanks!
