### ISSUE TITLE
[mcserver] Incorrect or missing output by starting?

### ISSUE THREAD

**Issue by Sebbo94BY** [GameServerManagers/LinuxGSM#1030]
I've just noticed, that after each colon is something written like "OK". If you start the mcserver, it seems like, that there is a message/output missing:

> mcserver@lgsm-debian8:~$ ./mcserver start
> [ WARN ] Starting mc-server: Check RAM: 1G required, 986M available
>         \* Minecraft server may fail to run or experience poor performance.
> [  OK  ] Starting mc-server:
> mcserver@lgsm-debian8:~$

Shouldn't be there an "OK" or something like that? If not, I would like to suggest, to remove this colon to prevent irritated users.

**Comment by UltimateByte** [comment]
@dgibbs64 Told ya ! :p

**Comment by dgibbs64** [comment]
Blame Mi extract not having a server name like every other game server

**Comment by UltimateByte** [comment]
So...
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/info_config.sh#L71

Easy fix is to add
`servername=Minecraft Server`

Should we do it ?

**Comment by cedarlug** [comment]
I'm not one to encourage defining variables that are exposed at the top level way down deep in the functional plumbing. 

A reasonable approach would be to set
```: ${servername:="Minecraft Server"}```
so that if there ever was a way to set servername in the top-level script, this assignment under-the-hood would be ignored.

**Comment by Sebi94nbg** [comment]
I'm not sure, but as far as I can remember myself, the _motd_ variable is used as servername. If you search for your server, you'll see that message, the counter of max. players and the status of this server. 

``motd=A Minecraft Server

However, this value could ne used instead of displaying nothing or setting a static variable somewhere.

**Comment by UltimateByte** [comment]
There was a "server-name" settings in MC classic, but seems there is not anymore.
"motd" isn't a servername, and can take up to two lines using `\n`, which wouldn't be adapted.

**Comment by UltimateByte** [comment]
`servername=${servername:-"Minecraft Server"}`

Or

`servername=${servername:-"Generic Minecraft Servername as Minecraft doesn't allow to set a server name, sorry, there's nothing we can do about it, blame Minecraft, sorry again lololol"}`

**Comment by Sebi94nbg** [comment]
lol. Clearly the second one! :+1:

**Comment by JimTR** [comment]
Just an odd point with minecraft motd the gameq php lib returns the motd as the server name and to a degree so does the minecraft interface 
![mc1](https://cloud.githubusercontent.com/assets/4038510/18019929/71c0bb10-6bd6-11e6-83ea-65d7a9562b3f.png)
and gameq
![gameq](https://cloud.githubusercontent.com/assets/4038510/18019936/801e76ac-6bd6-11e6-92a6-b2af9fa3a00b.png)
so it may be worth considering it

**Comment by marvinl97** [comment]
Then what about:

`servername=$(grep "motd=" "${servercfgfullpath}" | sed 's/motd=//g' | tr -d '=\";' | sed 's/\\n/ /g')`
(replace linebreaks with spaces)
or
`servername=$(grep "motd=" "${servercfgfullpath}" | sed 's/motd=//g' | tr -d '=\";' | sed 's/\\n.*//g')`
(only use first line)

**Comment by UltimateByte** [comment]
I'd go for first line only, otherwise it could be too long.
Let's add it :D

**Comment by JimTR** [comment]
There is also the point that if the install routine shuts motd to one line there is a chance it will be buried in server.properties & get forgotten

**Comment by Sebi94nbg** [comment]
Just a bit shorter:
`grep "motd=" "${servercfgfullpath}" | cut -d '=' -f 2 | sed 's/\\n/ /g'`

**Comment by UltimateByte** [comment]
Went for the one line !
@Sebi94nbg Let's stick with set | tr for coherence with other ones. :o))

Look how beautiful it is ! :o)) 
![Image of mcserver](http://image.noelshack.com/fichiers/2016/34/1472248463-mcserver-has-a-name.png)

**Comment by UltimateByte** [comment]
Well, everyone can now run ./mcserver uf and go home :o))
Bar is closing, cya ! :o))

**Comment by JimTR** [comment]
oddly if you add /n to produce a second line gameq ignores it & makes it a one liner but the minecraft interface adds the line break so I guess you need to make people aware on install as to the different properties ... but I guess one line is good
