### ISSUE TITLE
[dstserver] Complete overhaul needed

### ISSUE THREAD

**Issue by marvinl97** [GameServerManagers/LinuxGSM#1032]
## Current dev branch: [dstserver-new](https://github.com/GameServerManagers/LinuxGSM/tree/dstserver-new) ([compare to develop branch](https://github.com/GameServerManagers/LinuxGSM/compare/develop...dstserver-new))

Problems:
- server structure changed: the server is a "cluster" which contains maps ("shards"); a vanilla server should consist of a overworld "shard "(usually named "Master") and a cave "shard" (usually named "Caves")
- each "shard" has to be an own server - "shards" are connected by sinkholes/stairs in the map
- there are cluster and "server/shard" configs - what about servercfgdir/information/...?

In the end these files have to be created:
`
~\.klei\DoNotStarveTogether\MyDediServer\cluster.ini
~\.klei\DoNotStarveTogether\MyDediServer\Master\server.ini
~\.klei\DoNotStarveTogether\MyDediServer\Caves\server.ini
~\.klei\DoNotStarveTogether\MyDediServer\Caves\worldgenoverride.lua
`
And two servers have to be started.

Config path structure: `/home/dstserver/<persistent_storage_root>/<conf_dir>/<cluster>/<shard>`
* directories are changeable by identically named cmdline parameters
Should we create variables for cluster and shard? Should the other variables be changeable too?

Guides / Documentations:
[Quick Setup](http://forums.kleientertainment.com/topic/64441-dedicated-server-quick-setup-guide-linux/)
[Server Settings](http://forums.kleientertainment.com/topic/64552-dedicated-server-settings-guide/)
[Command Line Options](http://forums.kleientertainment.com/topic/64743-dedicated-server-command-line-options-guide/)
[Understanding Shards and Migration Portals](http://forums.kleientertainment.com/topic/59174-understanding-shards-and-migration-portals/)

I also want to note that [this dontstarve.wikia.com setup guide](http://dontstarve.wikia.com/wiki/Guides/Don%E2%80%99t_Starve_Together_Dedicated_Servers) is outdated.

I don't know where to start. I already read much and tried a bit but everything seems complicated and dirty. I need someone who pushes me into the right direction. I can't decide which paths to set to what and if there should be script copies for each shard (would be annoying when installing the server; idk how it should be realized)?

I have to update the wiki page too: https://github.com/GameServerManagers/LinuxGSM/wiki/Don't-Starve-Together

I'll likely improve this post over time. I probably forgot some things.

I'll probably create a new branch to play a bit around tomorrow.

**Comment by dgibbs64** [comment]
Im starting to regret supporting this server. The devs keep making big changes to the server. This will be the second time now that the server has broken because of the devs changing stuff.

**Comment by marvinl97** [comment]
I would like to have someone who could review and test my stuff so we can make the last changes/optimizations/cleanup to finally move it to the master branch. For me it seems to be working but this server is also affected by #957.

[/LinuxGSM/tree/dstserver](https://github.com/GameServerManagers/LinuxGSM/tree/dstserver)
[/LinuxGSM/compare/dstserver](https://github.com/GameServerManagers/LinuxGSM/compare/dstserver)
[/LinuxGSM/wiki/Don't-Starve-Together](https://github.com/GameServerManagers/LinuxGSM/wiki/Don%27t-Starve-Together) (I'm not that good at explaining things.)

**Comment by marvinl97** [comment]
Just leaving this as a note here:

> **bind_ip** (set as start parameter, in cluster.ini or server.ini)
> **Default**: 127.0.0.1
> **Required**: If shard_enabled = true and is_master = true
> This is the network address the master server will listen on for other shard servers to connect to. Set this to 127.0.0.1 if all of your servers in your cluster are on the same machine, or 0.0.0.0 if the servers in your cluster are on different machines. This only needs to be set for the master server, either in cluster.ini, or the master server's server.ini.

#1120

**Comment by marvinl97** [comment]
Current dev branch: [dstserver-new](https://github.com/GameServerManagers/LinuxGSM/tree/dstserver-new)
ToDo:

- [ ] bind_ip as config setting or start paramter? (see previous comment)
- [ ] standardize fn_dstconfig() in install_config.sh

..

**Comment by marvinl97** [comment]
Fixed with r161125 (9e21a76a3421ff63680781d6a4c746cb697f29a6)
