### ISSUE TITLE
[arma3server] Spaces are removed from servername

### ISSUE THREAD

**Issue by Sebbo94BY** [GameServerManagers/LinuxGSM#1033]
You can set a servername like "Arma 3 server", which will be displayed in the Arma 3 server list too, but if you start the server using LGSM, the servername is displayed without spaces:

```
arma3server@lgsm-debian8:~$ ./arma3server start
[ WARN ] Starting arma3-server: Check RAM: 1G required, 986M available
        * ARMA 3 server may fail to run or experience poor performance.
[  OK  ] Starting arma3-server: Arma3server
arma3server@lgsm-debian8:~$
```

**Comment by UltimateByte** [comment]
There is no reason for LGSM to affect how the config file is handled.
The only thing LGSM does, is read the hostname set in config file https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/info_config.sh#L155

However, if the text editor you're using is messing up with the text encoding, that could explain your removed spaces.

**Comment by Sebi94nbg** [comment]
Your mentioned line does remove **all** spaces due of this command:
`tr -d '=\"; '`

``tr`` isn't able to work with regex. Due of that, I would solve it by using this command:
`grep "hostname" "${servercfgfullpath}" | grep -v "//" | sed 's/\<hostname\>//g' | tr -d '=\";' | sed 's/^\s*//g;'`

Or even better:
`grep "hostname" "${servercfgfullpath}" | grep -v "//" | cut -d "=" -f 2 | sed 's/\"//g; s/;//g; s/^ //g;'`

**Comment by UltimateByte** [comment]
> You can set a servername like "Arma 3 server", which will be displayed in the Arma 3 server list too, but if you start the server using LGSM, the servername is displayed without spaces

To me sounded like "if you start the server using LGSM, the servername is displayed without spaces INTO THE SERVER LIST"

You're right then.

**Comment by Sebi94nbg** [comment]
Oh, ok. Sorry for this missunderstanding. :D

**Comment by UltimateByte** [comment]
NP, thanks for reporting in the first place. :)

Or even shorter :
`grep "hostname" "${servercfgfullpath}" | grep -v "//" | awk -F '"' '{print $2}'`

Need to ask back other devs to remind me if there is a counter indication for using awk.

**Comment by UltimateByte** [comment]
Should be solved. Thanks again for reporting. :)

**Comment by Sebi94nbg** [comment]
No problem. ;)

Has been fixed:

```
arma3server@lgsm-debian8:~$ ./arma3server start
[ WARN ] Starting arma3-server: Check RAM: 1G required, 986M available
        * ARMA 3 server may fail to run or experience poor performance.
[  OK  ] Starting arma3-server: Arma 3 server
arma3server@lgsm-debian8:~$
```
