### ISSUE TITLE
Arma 3 Exile Server

### ISSUE THREAD

**Issue by he4dspark** [GameServerManagers/LinuxGSM#1034]
Having the following issue:

$ ./arma3server start
[ FAIL ] Starting arma3-server: Unable to start [He4dSpark]ExileServer
[ FAIL ] Starting arma3-server: Unable to start [He4dSpark]ExileServer: Tmux error:
# Command

tmux new-session -d -s "arma3-server" "./arma3server -netlog -ip=109.228.52.242 -port=2302 -cfg=/home/arma3server/serverfiles/cfg/arma3-server.network.cfg -config=/home/arma3server/serverfiles/cfg/arma3-server.server.cfg -mod=\@Exile -servermod=\@ExileServer -bepath= -autoinit -loadmissiontomemory"
# Error

sessions should be nested with care, unset $TMUX to force
# Fix

No known fix currently. Please log an issue.
https://gameservermanagers.com/issues
# Fix

No known fix currently. Please log an issue.
https://gameservermanagers.com/issues

Are you able to please help,

thank you

**Comment by he4dspark** [comment]
Occurred after following this guide:
https://github.com/GameServerManagers/LinuxGSM/wiki/Upgrading-installing-latest-tmux-from-source-on-CentOS-7

I had an issue Getting tmux source

•Grabbing the tmux source

1.git clone https://github.com/tmux/tmux.git 
2.cd tmux
3.sh autogen.sh
4../configure
5.make
6.sudo make install


the server saying git clone wasn't a valid command.

**Comment by UltimateByte** [comment]
Because you need the gît package maybe...

**Comment by UltimateByte** [comment]
Congrats for having searched through the wiki.
Not congrats for not outputting a ./gameserver details, at the very least, and not using pastebin to output stuff.
Here what you got is a distro package issue.

Github is for bug report or suggestions. 
So if you need more support, please use Discord or the Steam group.
https://discord.gg/0i9cmXVacvXicNl7
https://steamcommunity.com/groups/linuxgsm/discussions

**Comment by UltimateByte** [comment]
Might have been a tmuxception in the end or maybe a ghost tmux session preventing from starting the new one. Mods settings were bad as well.
@he4dspark I've been a bit cold on this one, i apologize.
Also, the wiki has evolved with more information about mods since it's asked all the time. https://github.com/GameServerManagers/LinuxGSM/wiki/Arma-3
