### ISSUE TITLE
Universal header for interactive prompts

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1035]
After discussing, it would be good  to keep kind of a menu pattern for interactive actions.
And add a header to core_messages.sh that matches the pattern : 

```
 ${servername} ${commandaction}
=============================================
```

The backup function needs to be reworked accordingly.

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/commit/34c88b5f17873aec849b27915e03b60f40451cac

**Comment by UltimateByte** [comment]
![Proposition4](http://image.noelshack.com/fichiers/2016/34/1472388043-console-proposition-4.png)
 ?

**Comment by UltimateByte** [comment]
After discussing, it would be good  to keep kind of a menu pattern for interactive actions.
And add a header to core_messages.sh that matches the pattern : 

```
 ${servername} ${commandaction}
=============================================
```

**Comment by UltimateByte** [comment]
fn_print_header was added by dgibbs, now need to make sure it's used in every interactive command.

**Comment by UltimateByte** [comment]
Added to 3 missing ones.
Ready for merge into develop, will come on next release.
Closing to clear my todo list.
