### ISSUE TITLE
check_tmux.sh missing from ../master/lgsm/functions/check_tmux.sh

### ISSUE THREAD

**Issue by gjdunga** [GameServerManagers/LinuxGSM#1040]
Just as it says, as of this posting the check_tmux.sh is missing from the download when one force updates functions. 

full error: 
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/lgsm/functions/check_tmux.sh
(Error 404) 
![tmuxfail](https://cloud.githubusercontent.com/assets/527080/18043716/efcc301e-6d86-11e6-8ab9-4fa067571832.png)

**Comment by dgibbs64** [comment]
Run it again will work a second time

**Comment by gjdunga** [comment]
I assume it was a commit change. Ahh! Found it..  Commit 24b625c9b  

Will run update ..

**Comment by gjdunga** [comment]
Update ran, issue resolved.
