### ISSUE TITLE
Install should fail if dependencies for SteamCMD are not met

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1042]
if the dependencies for SteamCMD are not met then the installer should fail at check_deps. As the installer will not be able to complete if the server requires SteamCMD

**Comment by UltimateByte** [comment]
What are the effects if those dependencies are not installed ?
SteamCMD loop ? Would explain some issues people had with it. :)

**Comment by dgibbs64** [comment]
This has now been added. Installer will fail as SteamCMD would simply loop 10 times and fail
