### ISSUE TITLE
[Server Request] San Andreas Multiplayer

### ISSUE THREAD

**Issue by xFirez** [GameServerManagers/LinuxGSM#1047]
Please add support for San Andreas Multiplayer, would be nice to use this for that.

http://sa-mp.com/download.php

**Comment by UltimateByte** [comment]
I wanted to have a look at this one at some point. Seems to be a mess to deploy, but would be cool.

**Comment by xFirez** [comment]
@UltimateByte: Make sure these commands get executed if you plan on making it.

sudo apt-get update
sudo apt-get install ia32-libs

**Comment by dgibbs64** [comment]
@xFirez ia32-libs is no longer used. https://danielgibbs.co.uk/2013/11/steamcmd-64-bit-ubuntu-13-10ubuntu-12-04/

**Comment by hurdad** [comment]
Here is PR https://github.com/GameServerManagers/LinuxGSM/pull/1116

**Comment by UltimateByte** [comment]
@hurdad OMG nice ! :D

**Comment by xFirez** [comment]
When will this be implemented?

**Comment by UltimateByte** [comment]
@xFirez soon enough

**Comment by angryce** [comment]
Any news about this feature?
