### ISSUE TITLE
Monitor will fail if permissions issues

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1048]
The server will fail to reboot if a permissions issue occurs.

**Comment by UltimateByte** [comment]
Should fail on start but not on stop :)

**Comment by dgibbs64** [comment]
the problem here is that if someone causes a permissions issue. If the server then crashes it wont come back online. What needs to happen is that the server comes back online but warns via alert of the permissions issue. If the server admin is not around to fix the issue the server will remain offline.

**Comment by UltimateByte** [comment]
So in the end, it needs to alert if a permission issue is found.
But should it start the server back if permission issues are found, i would say no.

**Comment by dgibbs64** [comment]
The server should start back up.  A permissions issue mostly will not effect the operation of the server. I will make adjustments for check_perms.sh to not exit if using monitor and add an alert for permissions issues. 

I don't use the game server user to upload files and do sometimes forget to sort permissions. I dont thinks its a good idea for the server to stop functioning because I forgot to chance the user of a few sourcemod files. If is a good idea to alert.

**Comment by dgibbs64** [comment]
This has not been resolved. The monitor is bypassed for permissions checking this allows the monitor to alert of an issue. The server will still fail to start however but the admin is made aware of the issue rather than get no warning of it
