### ISSUE TITLE
Tmux error

### ISSUE THREAD

**Issue by avendretter** [GameServerManagers/LinuxGSM#1050]
Hi guys,

I did an update from tmux 1.8 to 2.0.1 today to see get some logs.

but unfortunally the server is not starting anymore :/

```
ark@v22016071295136217:~$` ./arkserver st
[  OK  ] Update ark-server: Checking for update: SteamCMD: No update available
 
No update available:
         Current version: 1305177
         Available version: 1305177
         https://steamdb.info/app/376030/
 
 protocol version mismatch (client 8, server 7)
 [ FAIL ] Starting ark-server: Unable to start
 [ FAIL ] Starting ark-server: Unable to start : Tmux error:
 
 Command
 =================================
 tmux new-session -d -s "ark-server" "./ShooterGameServer TheCenter?listen?ultiHome=XXX.XXX.XX.XX?SessionName=?MaxPlayers=15?QueryPort=27015?RCONPort=?Port=7778 -UseBattleye"
 
 Error
 =================================
 protocol version mismatch (client 8, server 7)
 
 Fix
 =================================
 No known fix currently. Please log an issue.
 https://gameservermanagers.com/issues
```

the user ark should have all rights he should need to run the server. 

```
 ark@v22016071295136217:~$ grep tty /etc/group
 tty:x:5:ark
```

any ideas?

Best,
Aven

**Comment by UltimateByte** [comment]
Non script issue until proven otherwise.
Please, post your issue to the appropriate place, wether it's the Steam group's forum or Discord.

https://gameservermanagers.com/support/

**Comment by UltimateByte** [comment]
PS : 10 seconds of googleing : http://unix.stackexchange.com/questions/122238/protocol-version-mismatch-client-8-server-6-when-trying-to-upgrade

**Comment by avendretter** [comment]
well I had a tmux session opened but couldnt close it. a serverrestart helped me out.

**Comment by UltimateByte** [comment]
Allright :+1: 

Good luck with your server then !
If you're new to LGSM, i can only advise to have a look at the wiki, you might find things you wouldn't have think of !

**Comment by avendretter** [comment]
Oki ty =) you can close the issue for good =))))

**Comment by UltimateByte** [comment]
Was already there https://github.com/GameServerManagers/LinuxGSM/wiki/Tmux#note-on-live-servers
But i added 3 lines https://github.com/GameServerManagers/LinuxGSM/wiki/Tmux#possible-problems
