### ISSUE TITLE
[Insurgency] monitor not working

### ISSUE THREAD

**Issue by PhilPhonic** [GameServerManagers/LinuxGSM#1052]
Hi,

the monitor function isnt working anymore:
> [ERROR ] Monitor ins-server: SteamCMD is currently checking for updates

steam is definately NOT looking for updates at the moment. I have multiple insurgency servers and all show this behaviour

**Comment by dgibbs64** [comment]
```ps -ef|grep "${selfname} update"|grep -v grep|wc -l```

This is the code that checks for this. I bet that if you do ```ps -ef|grep update``` you will see there are update commands running for some reason

**Comment by PhilPhonic** [comment]
damn, you are right..
i think the update function crashed somehow.
thanks
