### ISSUE TITLE
MCServer Multiple active network interfaces

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#1053]
When I run the server I see this 
![screenshot from 2016-09-01 23-36-22](https://cloud.githubusercontent.com/assets/4038510/18205008/a30a49e8-7117-11e6-8f37-6089eab8a0d6.png)

but there is no options to in the script to set this ... however there is in server.properties, which I duly set, but of course the script hit the error ... perhaps add the variable to the MC Script so it passes the check but make the user aware that server.properties needs updating.

before anyone points out that Centos is running in a Vbox and this is causing the issue ... it's not as I have run it in the parent OS and hit the same problem

**Comment by dgibbs64** [comment]
This needs fixing

**Comment by dgibbs64** [comment]
This has been fix now :)

```[ FAIL ] Starting mc-server: Check IP: Multiple active network interfaces found.
Information! Specify the IP you want to use within the server config file server.properties.
/home/lgsm/mcserver/serverfiles/server.properties
Set server-ip to one of the following:
138.138.157.111
10.16.0.7
https://gameservermanagers.com/network-interfaces```
