### ISSUE TITLE
Don't Starve Together cluster tokens

### ISSUE THREAD

**Issue by dittoslash** [GameServerManagers/LinuxGSM#1055]
Running the actual server via the binary works.
Running the LinuxGSM script dosen't.
Same config, same cluster token location, but running it with LGSM dosen't seem to be able to find it.
(Token is in ~/.klei/DoNotStarveTogether/Cluster_1/cluster_token.txt)

**Comment by marvinl97** [comment]
The script for Don't  Starve Together in the master branch is broken. A new version is currently under development: https://github.com/GameServerManagers/LinuxGSM/tree/dstserver

**Comment by dittoslash** [comment]
is it usable yet?

**Comment by marvinl97** [comment]
I can't say for sure but it seems to be working for now. I'm still testing but you could give it a try.

**Comment by UltimateByte** [comment]
@dittoslash If you're trying it, don't forget to change the githubbranch to githubbranch="dstserver", and to switch back to "master" once it's released.

**Comment by marvinl97** [comment]
Fixed with r161125 (9e21a76a3421ff63680781d6a4c746cb697f29a6)
