### ISSUE TITLE
Strange Crash Segmentation Fault Never Sow CS 1.6

### ISSUE THREAD

**Issue by ChrysUk** [GameServerManagers/LinuxGSM#1057]
Hy guys, i got an server on my VPS and i`m facing a problem in the last couple of days, my server gets crash with s trange error witch i never sow it before, can someone explain what is it or how to fix this.
---

CRASH: Sat Sep 3 23:068 EEST 2016
Start Line: ./hlds_linux -console +ip xxxxx +port 27015 -game cstrike -pingboost 1 +map de_dust2 -debug +maxplayers 32 +exec server.cfg +fps_max 1000 +alias fps_max wait +sys_ticrate 1000 +alias sys_ticrate wait +sv_visiblemaxplayers 32 +alias sv_visiblemaxplayers wait -pidfile hlds.2094.pid
[New Thread 20939]
[New Thread 20940]
[New Thread 20944]
[New Thread 21283]
[New Thread 20947]
Core was generated by `./hlds_linux -console +ip xxxxxx +port 27015 -game cstrike -pingboost 1 +m'.
Program terminated with signal 11, Segmentation fault.
#0 0x00000000 in ?? ()
#0 0x00000000 in ?? ()

No symbol table info available.
From To Syms Read Shared Object Library
0xb7782830 0xb779a5cf Yes (_) /lib/ld-linux.so.2
(_): Shared library is missing debugging information.
Stack level 0, frame at 0xbfee3b50:
## eip = 0x0; saved eip End of crash report

Thank you.
---

All The Best !

**Comment by UltimateByte** [comment]
Hi,

We want to help out server admins as best we can. However, our time is limited which is best spent on developing LGSM. Patience is also wearing thin on unhelpful posts. So please help us by providing the following information when posting to help us to resolve YOUR issue.

- Your Linux distro and version (e.g Ubuntu 16.04).
- Any useful logs in /home/gameserver/logs (use pastebin or equivalent).
- The output of ./gameserver details (remove passwords. Use pastebin or equivalent).
- Any solutions you have already tried.
- Any other useful or relevant information you think will help (such as installed mods).

Thanks in advance.

**Comment by ChrysUk** [comment]
Hy,
The game server is on an OpenVZ.

CentOS 6.8 x86_64 Minimal
We use AmxModx 1.8.2 & MetaMod v1.21p37

The logs i get is those ones from debug.log cuz i got the servers installed on custom folder: cs because we use GameCP Basic to manage ower server better and because i`m not the only one who have acces to the servers in case they crash to restart them.

We play on the server and sometimes the latency start to be like 4k and the server crash with theath error.

On the VPS / OpenVZ we got more gameservers CS 1.6 and Cs:GO but not so manny, 3 CS 1.6 and 1 CS:GO, on an 4Cores 3Ghz, 6GB Ram and the usage is still low.

Thank you.

**Comment by UltimateByte** [comment]
The issue with segaults is that it can be caused by many things.

Usual causes from the most common to the least:
1) Lack of dependencies, or wrong binaries version, the server won't even start
2) Addon crashing the game randomly
3) The game server crashing 

Maybe, a wrong glibc version could cause the game to randomly crash. There might be an issue with an LGSM glibcfix as well, that needs investigation.

Can you please output a ./gameserver details , as asked ? So that we know more about your config, especially your installed glibc version.

**Comment by systemcrash** [comment]
selinux? (I set mine to permissive and it fixed a segfault I was seeing)
Could be worth trying.

**Comment by UltimateByte** [comment]
We're un novembre, ni answer from OP, we van close.
