### ISSUE TITLE
Mods Loading in 'debug'-mode, but not with 'start'

### ISSUE THREAD

**Issue by curiousfREAk** [GameServerManagers/LinuxGSM#1059]
Following Issue:
If i start the Server with "arma3server debug ("takes 1'15'' until connected to steam servers), the Mods are loading.
Starting it up with "arma3server start" only the first mod is loading .....
The mods-Parameter didn't work in with the Syntax from the the Example ( mods/\@CBA_A3\;mods/\@task_force_radio ...)
My Mod-Line Syntax is:
mods="mods/@cup_terrains;mods/@ace;mods/@alive;mods/@burnes..."
 serverfiles/mods/\* is 775 for the arma3server user ...

.... anyone else?

best regards

fREAk

**Comment by UltimateByte** [comment]
Hi,

I've seen topics/issues about people having the syntax working either in debug or normal start.
This needs investigation, maybe we could fix it with some sed && || some good plays with single and double quotes.
However, the most important for you would be to have it working in normal mode for now.
Relevant things that might help : 
https://github.com/GameServerManagers/LinuxGSM/issues/739
https://github.com/GameServerManagers/LinuxGSM/issues/651

**Comment by cedarlug** [comment]
I'll take a crack at figuring out what's going on.

**Comment by cedarlug** [comment]
@curiousfREAk  Would you please enumerate a full list of your mods?  I'd like to test with everything that you're currently using.

**Comment by curiousfREAk** [comment]
This was faulty diagnosed by, sorry.
So here we are now: Once i load one mod with :: mods="mods/@cba_a3" the mod is loaded correctly, ...
DEBUG => `
13:45:42                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
13:45:42 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13:45:42                       Community Base Addons v3.0.0 |              @cba_a3 |      false |             GAME DIR | 5e4d58da7d3525e9089577880a322b2e9ccf1767 |  dc1227b1 | /home/arma3server/serverfiles/mods/@cba_a3
13:45:42                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
13:45:42                                        Arma 3 Apex |            expansion |       true |             GAME DIR | 3b262d55f1bf131ac7ba7e8f52db442675e78deb |  734697dd | /home/arma3server/serverfiles/expansion
13:45:42                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 6dc590a2267497ee172fb435fd058519f25cd960 |  64a11e26 | /home/arma3server/serverfiles/mark
13:45:42                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 3ec66916054a5a3b6d08c28574e57d1a20a88796 |  fa82f9ff | /home/arma3server/serverfiles/heli
13:45:42                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 908c532399962c4c773274261398903a3ceaed91 |  688e112f | /home/arma3server/serverfiles/kart
13:45:42                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 5b1a121146e2ea4de6e30f2052c2a7b85f1c9ae3 |   31955d5 | /home/arma3server/serverfiles/curator
13:45:42                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
13:45:42 ==========================================================================================================================================================================================================
`
Now i try to load it with the "correct" notation: mod="mods/\@cba_a3", ... as you can see cba_a3 is not loading correctly anymore, ....

`
13:48:54                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
13:48:54 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13:48:54                       Community Base Addons v3.0.0 |              @cba_a3 |      false |            NOT FOUND |                                          |           | mods//@cba_a3
13:48:54                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
13:48:54                                        Arma 3 Apex |            expansion |       true |             GAME DIR | 3b262d55f1bf131ac7ba7e8f52db442675e78deb |  734697dd | /home/arma3server/serverfiles/expansion
13:48:54                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 6dc590a2267497ee172fb435fd058519f25cd960 |  64a11e26 | /home/arma3server/serverfiles/mark
13:48:54                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 3ec66916054a5a3b6d08c28574e57d1a20a88796 |  fa82f9ff | /home/arma3server/serverfiles/heli
13:48:54                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 908c532399962c4c773274261398903a3ceaed91 |  688e112f | /home/arma3server/serverfiles/kart
13:48:54                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 5b1a121146e2ea4de6e30f2052c2a7b85f1c9ae3 |   31955d5 | /home/arma3server/serverfiles/curator
13:48:54                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
13:48:54 ==========================================================================================================================================================================================================
`
Now, lets load three mods with the first notation ::mods="mods/@cba_a3\;mods/@ace\;mods/@acex" ...
Now the last one is loaded correctly, second got a wrong PATH, first is ignored, ...
`13:53:17                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
13:53:17 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13:53:17           Advanced Combat Environment Extras 3.0.0 |                @acex |      false |             GAME DIR | ea9bd8aadc2f87d98946ddf598b286af8d00c1d6 |   5372088 | /home/arma3server/serverfiles/mods/@acex
13:53:17                  Advanced Combat Environment 3.7.0 |                      |      false |            NOT FOUND |                                          |           | mods/@ace/
13:53:17                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
13:53:17                                        Arma 3 Apex |            expansion |       true |             GAME DIR | 3b262d55f1bf131ac7ba7e8f52db442675e78deb |  734697dd | /home/arma3server/serverfiles/expansion
13:53:17                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 6dc590a2267497ee172fb435fd058519f25cd960 |  64a11e26 | /home/arma3server/serverfiles/mark
13:53:17                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 3ec66916054a5a3b6d08c28574e57d1a20a88796 |  fa82f9ff | /home/arma3server/serverfiles/heli
13:53:17                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 908c532399962c4c773274261398903a3ceaed91 |  688e112f | /home/arma3server/serverfiles/kart
13:53:17                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 5b1a121146e2ea4de6e30f2052c2a7b85f1c9ae3 |   31955d5 | /home/arma3server/serverfiles/curator
13:53:17                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
13:53:17 ==========================================================================================================================================================================================================`
 Now do the same with the "correct" notation: :: mods="mods/\@cba_a3\;mods/\@ace\;mods/\@acex"
Again, first mod is ignored, second and third are trying to start, but with wrong PATH, ...

`
13:57:48                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
13:57:48 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13:57:48           Advanced Combat Environment Extras 3.0.0 |                @acex |      false |            NOT FOUND |                                          |           | mods//@acex
13:57:48                  Advanced Combat Environment 3.7.0 |                      |      false |            NOT FOUND |                                          |           | mods//@ace/
13:57:48                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
13:57:48                                        Arma 3 Apex |            expansion |       true |             GAME DIR | 3b262d55f1bf131ac7ba7e8f52db442675e78deb |  734697dd | /home/arma3server/serverfiles/expansion
13:57:48                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 6dc590a2267497ee172fb435fd058519f25cd960 |  64a11e26 | /home/arma3server/serverfiles/mark
13:57:48                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 3ec66916054a5a3b6d08c28574e57d1a20a88796 |  fa82f9ff | /home/arma3server/serverfiles/heli
13:57:48                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 908c532399962c4c773274261398903a3ceaed91 |  688e112f | /home/arma3server/serverfiles/kart
13:57:48                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 5b1a121146e2ea4de6e30f2052c2a7b85f1c9ae3 |   31955d5 | /home/arma3server/serverfiles/curator
13:57:48                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
13:57:48 ==========================================================================================================================================================================================================
`
Finall i'll start it manually by moving into serverfiles/ and starting the arma3server executeable as follows:
./arma3server -port=2302 -cfg=cfg/arma3-server.network.cfg -config=cfg/arma3-server.server.cfg -mod=mods/@cba_a3\;mods/@ace\;mods/@acex -autoinit

`14:01:50                                               name |               modDir |    default |               origin |                                     hash | hashShort | fullPath
14:01:50 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14:01:50           Advanced Combat Environment Extras 3.0.0 |                @acex |      false |             GAME DIR | ea9bd8aadc2f87d98946ddf598b286af8d00c1d6 |   5372088 | /home/arma3server/serverfiles/mods/@acex
14:01:50                  Advanced Combat Environment 3.7.0 |                 @ace |      false |             GAME DIR | a89149f8dd8f94b96fd06c2d4ba9e93c1be67e7d |  fb6d4808 | /home/arma3server/serverfiles/mods/@ace
14:01:50                       Community Base Addons v3.0.0 |              @cba_a3 |      false |             GAME DIR | 5e4d58da7d3525e9089577880a322b2e9ccf1767 |  dc1227b1 | /home/arma3server/serverfiles/mods/@cba_a3
14:01:50                                  Arma 3 DLC Bundle |            dlcbundle |       true |            NOT FOUND |                                          |           |
14:01:50                                        Arma 3 Apex |            expansion |       true |             GAME DIR | 3b262d55f1bf131ac7ba7e8f52db442675e78deb |  734697dd | /home/arma3server/serverfiles/expansion
14:01:50                                    Arma 3 Marksmen |                 mark |       true |             GAME DIR | 6dc590a2267497ee172fb435fd058519f25cd960 |  64a11e26 | /home/arma3server/serverfiles/mark
14:01:50                                 Arma 3 Helicopters |                 heli |       true |             GAME DIR | 3ec66916054a5a3b6d08c28574e57d1a20a88796 |  fa82f9ff | /home/arma3server/serverfiles/heli
14:01:50                                       Arma 3 Karts |                 kart |       true |             GAME DIR | 908c532399962c4c773274261398903a3ceaed91 |  688e112f | /home/arma3server/serverfiles/kart
14:01:50                                        Arma 3 Zeus |              curator |       true |             GAME DIR | 5b1a121146e2ea4de6e30f2052c2a7b85f1c9ae3 |   31955d5 | /home/arma3server/serverfiles/curator
14:01:50                                             Arma 3 |                   A3 |       true |            NOT FOUND |                                          |           |
14:01:50 ==========================================================================================================================================================================================================`

As we see, everything is loading corectly. All mods are lowercased and 775ed. Works fine in "manual mode"

so long,

curiousfREAk

**Comment by cedarlug** [comment]
Perfect @curiousfREAk  -- thanks.

**Comment by cedarlug** [comment]
Issue found. Workaround forthcoming.

**Comment by cedarlug** [comment]
Using your mods as prototypes, I have success running under tmux with the line:
`mods="mods/@ace\;mods/@acex\;mods/@cba_a3"`
All mods are found, loaded, and hashed.

To run outside of tmux in lgsm's debug mode, `./arma3server debug` required the modules line:
`mods="mods/@ace;mods/@acex;mods/@cba_a3"`

Note the lack of escaped semicolons.  So the fix/workaround in the #1077 affirms the format in the `arma3server` script and adjusts the parameters passed to the executable when invoked in debug mode.

**Comment by cedarlug** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Arma-3

All works as it should.  Confirmed with @XxROBOTICSxX  today, walking him through the process.
