### ISSUE TITLE
[Arma 3] Ownership issues found Problem.

### ISSUE THREAD

**Issue by melihbudak** [GameServerManagers/LinuxGSM#1060]
I wanted a "@Life_Server" mod. But ./arma3server script output : "Ownership issues found". 

This is issues: [http://prntscr.com/cfse1s](http://prntscr.com/cfse1s)

How to install Arma 3 mod for server? Please help me.

**Comment by dgibbs64** [comment]
```chown -R arma3server:arma3server /home/arma3server```

I recommend learning about Linux user file permissions

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Step_by_Step_Guide/s1-navigating-ownership.html

**Comment by melihbudak** [comment]
Thank you so much @dgibbs64.

Mmm... But not loading mods. How to enable customMods ?

This is image: http://prntscr.com/cfsm0d
