### ISSUE TITLE
CSGO failed to update

### ISSUE THREAD

**Issue by xFirez** [GameServerManagers/LinuxGSM#1064]
Failed to update: https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/lgsm/functions/check_tmux.sh

How can I fix this?

**Comment by UltimateByte** [comment]
Run ./gameserver update-functions
Twice
If it still doesn't work, remove your lgsm folder, it will re-download automatically.
If it still doesn't work, update your "game"server script.

**Comment by UltimateByte** [comment]
I'll close this issue, but please, report back to let us know if your server is going allright :)
(you can still comment if it's closed)
