### ISSUE TITLE
Pushbullet integration

### ISSUE THREAD

**Issue by RussianRonin** [GameServerManagers/LinuxGSM#1067]
I was wondering if you could integrate pushbullet into LGSM. Was looking at your blog and saw this.

https://danielgibbs.co.uk/2016/06/send-pushbullet-message-from-bash/

Messages on crashes and restarts and what not.

**Comment by cedarlug** [comment]
Pushbullet has been added. I'm using it presently.

If you don't see the option for the pushbullet token in your script, update your scripts.

If it's more than an oversight of finding it already in the script or not updating your script., reopen.
