### ISSUE TITLE
Debian 8 running gmod server. Console freezes

### ISSUE THREAD

**Issue by ltwilliams** [GameServerManagers/LinuxGSM#1068]
Hi all I would greatly appreciate it if anyone could help me or point me in the right direction.

I am running a garrysmod server, everything works fine and I previously ran the exact same server files with a different host and ran smooth.

However now im using debian 8 installed and running the same server it all runs fine for a period of time and then the server just freezes. The server console just freezes and nothing happens causing the server to be shutdown. The process is still running so after accessing ssh again i can see the server console there but it is just frozen.

Does anyone know why this is? I'm using LGSM (linux game server manager) to run the garrysmod server

**Comment by UltimateByte** [comment]
As CedarLUG said on Steam, you need to provide relevant information in order for us to check the basics first and be able to point to the right direction to solve your issue.

Closing as duplicated from Steam forum and probably non-script issue.
Please, continue the discussion here, providing more details : 
http://steamcommunity.com/groups/linuxgsm/discussions/0/350541595121307856/
