### ISSUE TITLE
ARK-Server "session failed: ./ShooterGameServer : No such file or directory"

### ISSUE THREAD

**Issue by FarmersSohn** [GameServerManagers/LinuxGSM#1070]
Hello, I have installed Linux ARK-GameServerManager on a new Ubuntu 16.04 Linux Server. But if I want to start the ARK-Server I get this error: 
Error
=================================
create session failed: ./ShooterGameServer "TheIsland?listen?MultiHome=176.31.156.43?SessionName=ark-server?MaxPlayers=50?QueryPort=27015?RCONPort=32330?Port=7778?ServerAdminPassword=": No such file or directory

If I launch the server in debug mode the server starts. I think the path is the problem. But how can I fix this issue?
Sorry for my bad english I'm 14 and from Germany :)

**Comment by cedarlug** [comment]
You cannot run arkserver on a 32-bit system.  If you are running on a 64-bit system, please reopen and provide the output of `arkserver details` to pastebin (without your passwords)
