### ISSUE TITLE
TeamSpeak Update says SteamCMD

### ISSUE THREAD

**Issue by James76931** [GameServerManagers/LinuxGSM#1074]
Just a very minor bug, but I thought I'd point this out.

When you type **./ts3server**, the commands list menu has this description this for the update command: "Checks and applies updates from **SteamCMD**."

I'm pretty sure that should say teamspeak.com instead of SteamCMD :P

_- James_

**Comment by UltimateByte** [comment]
100% right, thanks for reporting

@marvinl97 
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/core_getopt.sh#L128

**Comment by UltimateByte** [comment]
Fixed
https://github.com/GameServerManagers/LinuxGSM/commit/05700a0a925fe7f486990100c3091830486b576a
