### ISSUE TITLE
Logs to be rotated with monitor feature

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1075]

**Comment by UltimateByte** [comment]
Seems like my cron fu don't rotate logs as well. This one needs to be cofirmed.

**Comment by UltimateByte** [comment]
Well, after testing, monitor actually rotates logs. I tried with the /dev/null and a logdays of -2 to force the rotation to occur and make sure redirecting output didn't prevent rotation to happen.

`./gameserver monitor > /dev/null 2>&1`

However, log rotation didn't occur on update, so i just added logs.sh to command_update.sh.

Fixed on next merge.
