### ISSUE TITLE
Steam API future request.

### ISSUE THREAD

**Issue by Graymanflo** [GameServerManagers/LinuxGSM#1078]
Good evening everyone.

I figured most people here are used to the "SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed." error however me on the other hand would love to get rid of it. I've been stumbling around the Steam API for a very long time now and I sadly can't figure out any working method to launch it in Linux.

On Windows it is possible to launch and authorize into Steam to fix the above issue. Having this eliminated in Linux would be trutly unique for this script.

I would highly appreciate if this could be put into consideration. Thanks.

**Comment by UltimateByte** [comment]
Hi,

Why not, but is it worth it ? What would be the benefits ? What could you do without this error that you can't already ?
On the other hand, i think nobody has a damn clue on how to fix it. The only way would be, i think, to make Valve fix it.

**Comment by Graymanflo** [comment]
Thanks for coming back @UltimateByte.

I'm certainly unsure which features this would allow the developers to access if the actual API was being ran, althought the API wouldn't be implamented if it wasn't for a good reason. However, as I mentioned above the solution to Steam API init error can be solved by running Steam.exe with a authorized account.

**Comment by UltimateByte** [comment]
If we don't know what the API provides and have no doc about it, i see no point in trying to fix it, as we couldn't use it anyways.
However, i agree that this error is quite boring, and maybe we should try to contact Valve about it. But you know Valve... Chances are they ignore this thing.

**Comment by Graymanflo** [comment]
Hey again @UltimateByte.

Solving the error would be more of an cosmetic change in log entries rather than a useful resource as I sadly can't find any correct info as what this API is exactly used for.

**Comment by dgibbs64** [comment]
Closing. Would add no benefit apart from getting rid of an error. Maybe valve will fix it one day.....but dont hold your breath.
