### ISSUE TITLE
CODENAME CURE server shown as dead on GAMETRACKER

### ISSUE THREAD

**Issue by MAJIC1** [GameServerManagers/LinuxGSM#1079]
Looks like some setting changed somewhere, I dont know if you are concerned about it or not, but the Players and server Data isnt being forwarded to them anymore.

Just wanted to give you a heads up.

**Comment by UltimateByte** [comment]
Talking about LGSM servers ?

**Comment by dgibbs64** [comment]
This is an issue for the CODENAME CURE devs rather than LinuxGSM I think. Thank you
