### ISSUE TITLE
7DTD - server startup issues

### ISSUE THREAD

**Issue by Maygus** [GameServerManagers/LinuxGSM#1080]
Hi - 2 issues.

1: Following the web-page for setting up 7DTD I got a message that sdtd-config.xml doesn't exist (IE: serverconfig)
- To work-around this I change serverconfig.xml and then copy it to sdtd-config.xml
  2: Cannot run 'monitor' as there is no "port" specific
  - [ FAIL ] Monitor sdtd-server: Querying port: 52.**_.**_.***:27018: : 6/1 : ERROR: No port supplied.^C

I cannot get around this error.
You'll see that it has a port in the code above, but the previous attempt it was just the IP. I edited sdtdserver start-up file and added the port onto the IP line, no difference.

Advice?

**Comment by Maygus** [comment]
Further reviewing - the server is actually failing to start... I've redone the installation steps to no avail. Same result.

**Comment by dgibbs64** [comment]
I don't understand why there is an issue. I recommend posting more info to hopefully give us an idea of what might be happening. I would suggest maybe a coding issue however I think you are the first the report this.
Use this link to provide the info we require. Thanks 👍 

https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Maygus** [comment]
Well I tried again and now server starts. But monitor still fails to connect. Server is at least running.
