### ISSUE TITLE
[ut99] - select different versions on ut99 on install

### ISSUE THREAD

**Issue by Chamberly** [GameServerManagers/LinuxGSM#1083]
Request: I would like to know how to modify the script to download just v436 instead of v451, and skipping the extra bonuses.
## I'm new to linux/ubuntu so I think it's a barrier that I couldn't find it.

Can't find where or what to edit the commandline for UT99 and I've been looking for hours with no hope. Like I'd want to edit the commandline and add something like this to it: 

`ucc server DM-Deck16][?game=Botpack.DeathMatchPlus ini=server.ini -log=server.log copy server.log servercrash.log`

Unless the commandline editor is not available, but it is rather needy for server admin use.

**Comment by UltimateByte** [comment]
@dgibbs64 is hosting the game server. I believe he's currently hosting the last version only. So there is no current way of installing another version for now, as far as i know. 
However, if @dgibbs64 agrees, we might add a way to select server version, but i cannot answer this for him.

For start parameters, do you have a doc for ut99 ?
I can see LGSM already set the default .cfg to be expected to: serverfiles/ut99-server.ini
Nothing about log and crash in start parameters, but if the server console is giving outputs, then you should find logs in log/console/*

**Comment by Chamberly** [comment]
The server config (UT.ini aka UT99-server.ini) isn't the same as setting start parameters/commandline. Normally in windows, the commandline will be configured in RunServer.bat.

... Let's see if I can throw out some example. I don't think many would understand yet.
https://wiki.beyondunreal.com/Legacy:Running_A_Dedicated_Server_With_UCC
http://forums.gameservers.com/viewtopic.php?t=19622
I've tried looking for that file, didn't find one.^
Screenshot of a custom script: https://i.gyazo.com/53bdf95894f68cf94351b8b64699955f.png
(Credit: Thanks to ~V~ for providing.)
Hopefully this bring light to what I'm looking for.

**Comment by UltimateByte** [comment]
Can you please try this piece of code ?

````
# Start Variables
defaultmap="DM-Deck16]["
ip="0.0.0.0"
gametype="Botpack.DeathMatchPlus""
mutators="MapVoteLA13.DBDMapVote"

fn_parms(){
parms="server ${defaultmap}.unr ini=${servercfgfullpath} game=${gametype} mutator=${mutators} "
}
````

(Protip about Github (took me a while to figure this out): To allow line jumps for code, you need to have : 
four simple back quotes
then your code on the next lines
then on the next line:
four simple back quotes to close it)

**Comment by Chamberly** [comment]
Still can't get mutator to work based off from this. I did changed something, server starts and all.

`# Start Variables
defaultmap="DM-Deck16]["
ip="45.55.170.206"
gametype="Botpack.DeathMatchPlus"
mutator="MapVoteLA13.DBDMapVote"

fn_parms(){
parms="server ${defaultmap}.unr?Game=${gametype}?Mutator=${mutator} ini=${servercfgfullpath}"
}`

**Comment by UltimateByte** [comment]
(still didn't get the "four single back quote before and after your code" stuff :p 

So variables works with your last test ?

**Comment by Chamberly** [comment]
Nope.

**Comment by UltimateByte** [comment]
Crap.

**Comment by Chamberly** [comment]
Saw something so I'm gonna give this a try when I get home later from work. This usually depends on XC_Engine, which I'm trying to work without due to anti-cheat testing in favor.

````
# CACUS STUFF
gametype=?Game=SiegeIV_0026.SiegeGI
mutatorlist=?Mutator=NoMapProtection.NoMapProtection,CacusMapVote.CacusMapVote

fn_parms(){
parms="XC_Server ${defaultmap}.unr${gametype}${mutatorlist} ini=${servercfgfullpath}"
}
````

**Comment by Chamberly** [comment]
Bump. I had the wrong command to load the mapvote. It works successfully now! So mutator command does work.

MapvoteLA13.BDBMapvote instead of DBD. DUH Why have I not noticed?

I still request to have v436 instead of v451 though. :smile:

**Comment by dgibbs64** [comment]
Sorry for the delay. Is there any particular reason why you want v436 over v451? Also you can just download v436 yourself and uncompress in to the `serverfiles` dir that will allow it to work

**Comment by Chamberly** [comment]
I prefer v436 with XC_Engine because v451 is just a bunch of crap and can't really fulfill the work as I want the engine modified in a way that I can work on the game (with XC_Engine). & It's all for my choice, and for other who want it as well.

Now, I didn't expect that kind of feedback (telling me to go out and download it myself - I'm new to linux and this doesn't help much). I was told that there is a way to modify the script of your so I can skip downloading v451 and other stuff that comes with it.

**Comment by dgibbs64** [comment]
I would have to investigate allowing different versions of the server to be downloaded. Something that LinuxGSM does not yet do and would require quite a bit of work to complete.  So I will add it as a feature request.

If I was you I would run the default install and remove the contents of serverfiles dir (keeping the config). Then download the version of UT you require and untar it to the serverfiles.

**Comment by Chamberly** [comment]
I guess that's the only option for time being. Let me know when you have a v436 ready!

**Comment by dgibbs64** [comment]
relevent https://github.com/GameServerManagers/LinuxGSM/pull/2352

**Comment by Chamberly** [comment]
Note: UT99 v469 is coming out soon as well.

**Comment by ctannurella** [comment]
> Note: UT99 v469 is coming out soon as well.

would be cool if v469 might be implemented in LinuxGSM 👍

**Comment by Chamberly** [comment]
> > Note: UT99 v469 is coming out soon as well.
> 
> would be cool if v469 might be implemented in LinuxGSM

I'll be making a new enhancement issue about this when it comes out.

Will be stepping in to test out the changes.

**Comment by dgibbs64** [comment]
#2961 v469 is not yet available but I have created an issue for it.

I have decided that this particular issue has a very specific use case, benefiting very few people and with a higher level of complexity to develop. Because of this I will not be developing this feature.
