### ISSUE TITLE
[GoldenEye Source] Missing ldap dependency

### ISSUE THREAD

**Issue by cedarlug** [GameServerManagers/LinuxGSM#1085]
The shared library in the game tarball "server_i486.so" has a libldap dependency.  Without the ldap library, the game enters into a segfault death spiral.

On Debian amd64, it required `libldap-2.4-2:i386`

Ref: http://steamcommunity.com/groups/linuxgsm/discussions/0/350542683193084815/

**Comment by UltimateByte** [comment]
Now we know this isn't restricted to Debian and Ubuntu requires the same. :)

**Comment by cedarlug** [comment]
Anyone have a quick answer to the RPM-based distribution packages that contain the ldap libs?  If not, I'll deploy and diagnose.

**Comment by cedarlug** [comment]
`yum install openldap.i686`  <-- CentOS fix.

**Comment by cedarlug** [comment]
So do these go on gameservermangers.com instruction pages as dependencies?  Or, part of the lgsm dependency list?

**Comment by UltimateByte** [comment]
Maybe both ?
