### ISSUE TITLE
Monitoring broke?

### ISSUE THREAD

**Issue by shavitush** [GameServerManagers/LinuxGSM#1086]
My servers don't go up back after crashing, I realized monitoring broke for me since the latest CS:GO update?

```
root@csgo:~# su - jail
jail@csgo:~$ ./csgoserver monitor
[ERROR ] Monitor csgo-server: SteamCMD is currently checking for updates
```

Tried running `update-functions`, no help :(

Running Ubuntu 16.04LTS

Sorry for not providing logs, I have disabled logging because I run many servers and they ended up ripping apart my SSD space. I'd be glad to enable logging for a day or so if you guys can tell me which files exactly to send!

**Comment by UltimateByte** [comment]
Hey,

Well, i had this issue recently, that due to myself having a wrongly set cronjob that would check for updates every minute instead of every 30 minutes. 
So make sure what's going on, please check the last script log.

`cat /home/csgo/log/script/csgo-server-script.log`

Please, paste the output here. 
You can also provide a copy of your cronjobs so that we can check them.
That way we will know if the server is actually really checking for an update.

**Comment by shavitush** [comment]
```
Sep 23 08:20:02 csgo-server: MONITOR: INFO: Checking session: CHECKING
Sep 23 08:20:03 csgo-server: MONITOR: PASS: Checking session: OK
Sep 23 08:20:03 csgo-server: MONITOR: INFO: Querying port: gsquery.py enabled
Sep 23 08:20:04 csgo-server: MONITOR: INFO: Querying port: ser.ver.add.ress:27110 : 1 : QUERYING
Sep 23 08:20:05 csgo-server: MONITOR: PASS: Querying port: ser.ver.add.ress:27110 : 1 : OK
Sep 23 08:20:05 csgo-server: MONITOR: PASS: monitor_gsquery.sh exiting with code: 0
Sep 23 08:25:03 csgo-server: MONITOR: INFO: Checking session: CHECKING
Sep 23 08:25:04 csgo-server: MONITOR: PASS: Checking session: OK
Sep 23 08:25:04 csgo-server: MONITOR: INFO: Querying port: gsquery.py enabled
Sep 23 08:25:05 csgo-server: MONITOR: INFO: Querying port: ser.ver.add.ress:27110 : 1 : QUERYING
Sep 23 08:25:06 csgo-server: MONITOR: PASS: Querying port: ser.ver.add.ress:27110 : 1 : OK
Sep 23 08:25:06 csgo-server: MONITOR: PASS: monitor_gsquery.sh exiting with code: 0
Sep 23 08:30:01 csgo-server: UPDATE: INFO: Checking for update: Server logs
Sep 23 08:30:02 csgo-server: MONITOR: ERROR: SteamCMD is currently checking for updates
Sep 23 08:30:03 csgo-server: MONITOR: ERROR: command_monitor.sh exiting with code: 2
Sep 23 08:30:03 csgo-server: UPDATE: INFO: Checking for update: SteamCMD
Sep 23 08:31:08 csgo-server: UPDATE: PASS: Checking for update: SteamCMD
Sep 23 08:31:09 csgo-server: UPDATE: PASS: Checking for update: SteamCMD: No update available
Sep 23 08:31:09 csgo-server: UPDATE: INFO: Current build: 1346753
Sep 23 08:31:09 csgo-server: UPDATE: INFO: Available build: 1346753
Sep 23 08:31:09 csgo-server: UPDATE: PASS: command_update.sh exiting with code: 0
Sep 23 08:35:02 csgo-server: MONITOR: INFO: Checking session: CHECKING
Sep 23 08:35:03 csgo-server: MONITOR: PASS: Checking session: OK

```

Basically like this (since the issue started)

crontab:

```
*/5 * * * * /home/jail/csgoserver monitor >/dev/null 2>&1
*/30 * * * * /home/jail/csgoserver update >/dev/null 2>&1
```

**Comment by UltimateByte** [comment]
Well, most functions will stop if the server is checking for update, since if there is an update, the server will restart anyways.
You just happened to have the monitor at the exact same time as update check, as the message said in the first place.
Is that a big deal ?

**Comment by shavitush** [comment]
Not really a big deal, I'm not necessarily asking for something like it to be done withing LGSM of course :)

Thanks

**Comment by UltimateByte** [comment]
There are sometimes improvements that we could not figure out without somebody asking, that's why i asked it to you if it was a big deal for ya !

I'm glad that was nothing bad in the end :)

Have fun with LGSM, feel free to come back if you see anything that seems abnormal ! :)
