### ISSUE TITLE
Team Fortress Classic installer keeps looping the SteamCMD download

### ISSUE THREAD

**Issue by James76931** [GameServerManagers/LinuxGSM#1087]
Title pretty much says it all, when I try to install a TFC server - the installer keeps looping the download and trying to update it.

**Comment by James76931** [comment]
My mistake, the installer does finish - it just looks like it's looping.

Sorry about that. :P

**Comment by marvinl97** [comment]
> Goldsource servers commonly fail to download all the server files required.

No problem.
