### ISSUE TITLE
Let config variables from csgoserver script be in separated file

### ISSUE THREAD

**Issue by gorgitko** [GameServerManagers/LinuxGSM#1088]
When you update csgoserver script, I must manually rewrite the config variables. If they are in separated file, it will save a boring work. Thank you!

**Comment by UltimateByte** [comment]
This has been discussed a lot. 

The csgoserver script is rarely updated, and when it is, it's usually minor additions.

You can however update LGSM's core with the update-functions command (uf). 

We're thinking about something even bigger for separated config files.
https://github.com/GameServerManagers/LinuxGSM/pull/525

**Comment by gorgitko** [comment]
OK, thanks.

**Comment by UltimateByte** [comment]
Thanks for your suggestion. I've been myself asking this feature for a while. But we need to find a smart way to implement it first.
