### ISSUE TITLE
CoD1 + UO support

### ISSUE THREAD

**Issue by kekeN7** [GameServerManagers/LinuxGSM#1089]
I can see that Enemy Territory and Quake 3 are being added in the next release, could you guys add support for CoD1 + UO  in the near future as well? Please? It runs on the same engine (Q3), so it shouldn't be much different. I personally don't care about the rest of the CoD games, but CoD1 support would be very much appreciated. It's not dead by any means:
http://codlist.tk/
https://cod1.eu/master/

Thank you very much in advance.

**Comment by hurdad** [comment]
i dont see any linux dedicated servers avaiable for CoD1

**Comment by kekeN7** [comment]
You mean server files? [Right here](https://www.opferlamm-clan.de/call-of-duty-linux-server-files.html)

**Comment by hurdad** [comment]
cool. I will take a look

**Comment by kekeN7** [comment]
Yay! Thanks. Just noticed that there are readme files below the download links as well.

**Comment by hurdad** [comment]
Which versions are you interested in? the latest? 
The latest versions seem to be -> CoD1 - 1.5b, CoD UO - 1.51b

**Comment by kekeN7** [comment]
That would be perfect. (at least for me)

**Comment by UltimateByte** [comment]
So 1.51b I guess

**Comment by kekeN7** [comment]
Just like hurdad said: 1.5b for CoD1, 1.51b for CoDUO

**Comment by UltimateByte** [comment]
So both i guess then. Sorry i read hurdad's post a bit too fast on my phone.

**Comment by hurdad** [comment]
so it looks like the server files I downloaded don't contain all of the .pak files that you need to run the dedicated server. I can create one big bz2 with all of the other files from steam, and that should work.

**Comment by kekeN7** [comment]
Huh, you're right. I thought this pack has everything. And also the other localization paks and the .dlls in the are unnecessary. (I think)

**Comment by hurdad** [comment]
I just did a PR for Call of Duty. @kekeN7 can you give this a try? https://github.com/GameServerManagers/LinuxGSM/blob/cod1/CallOfDuty/codserver

```
./codserver auto-install
./codserver start
```

**Comment by kekeN7** [comment]
Well, this is my first time using linux ever, but yeah, the server appears to be running without any errors. However, I have yet to find a way to connect to it. :D That must be some port forwarding or network related issue, plus the server is running on virtualbox. Question: the filename the script has downloaded was "cod-lnxded-1.5-large.tar.bz2", is that intentional or just a typo? (The last version is 1.5b -> cod-lnxded-bins-1.5b.tar.bz2)

**Comment by hurdad** [comment]
This is how I tested it on virtualbox:
- Set Network Adapter to 'Bridged Adapter' mode. Reboot to get IP from your local network
- In codserver replace params ' +set net_ip ${ip}' with '+set net_ip 0.0.0.0'. This will allow it to show up in COD lan browser.

So I 'rebundled' the server files into one 'master' archive and uploaded it to s3 https://s3.amazonaws.com/linuxgsm/cod-lnxded-1.5b-full.tar.bz2

This archive contains:
- pak files from steam
- cod-lnxded-1.5-large.tar.bz2
- cod-lnxded-bins-1.5b.tar.bz2

**Comment by kekeN7** [comment]
Thanks, the Bridged Adapter mode did the trick.
Does it show ip in the server browser for you? Mine doesn't, I can connect from console though.

Also thanks for your "custom" bz2.

**Comment by hurdad** [comment]
Yes, I set browser to LAN  and  '+set net_ip 0.0.0.0'

**Comment by hurdad** [comment]
@kekeN7 CODUO is ready also, try this:

https://github.com/GameServerManagers/LinuxGSM/blob/coduo/CallOfDutyUnitedOffensive/coduoserver

**Comment by kekeN7** [comment]
Same for CoDUO - works great, but won't show up in the browser. (tried the net_ip thingy)
Although my windows-hosted dedicated server shows up in the lan list.

A small thing: the motd message command is scr_motd instead of g_motd.

**Comment by hurdad** [comment]
try running this command, you should see this output
```
$>netstat -ln | grep 28960
udp        0      0 0.0.0.0:28960           0.0.0.0:*   
```

ok I will update the motd.

**Comment by kekeN7** [comment]
That's exactly what I see, but the port is red. (not sure if that matters or not)

**Comment by hurdad** [comment]
red that is ok, check iptables (firewall)
```
$sudo iptables -L
[sudo] password for user: 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination     
```

**Comment by kekeN7** [comment]
It's the same here.

**Comment by hurdad** [comment]
well, thats all I can think of...

**Comment by kekeN7** [comment]
It's all good, I'm sure I'm gonna find a way somehow. :)

**Comment by dgibbs64** [comment]
This is now merged YAY!!!
