### ISSUE TITLE
[Insurgency] graceful rcon quit not working

### ISSUE THREAD

**Issue by PhilPhonic** [GameServerManagers/LinuxGSM#1090]
hi,

graceful rcon quit does not work with all of my Insurgency servers. I have to wait 30 seconds until it fails and performs a "hard shutdown".

any suggestions?

**Comment by dgibbs64** [comment]
I think that insurgency might just do a reboot with the quit command. Some server do this. So when LGSM sends the quit command it simply reboots the server. So it has to wait then force the shtdown. You can check by entering quit in the console

**Comment by PhilPhonic** [comment]
You are so right!

> quit
[PartyTeamMgr] Grace period started.
L 09/28/2016 - 18:13:05: [META] Loaded 0 plugins (1 already loaded)
L 09/28/2016 - 18:13:05: "BOT Vuk<9><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Valdis<8><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Thiago<7><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Stephen<6><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Rense<5><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Mike<4><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Michael<3><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: "BOT Matthias<2><BOT><>" disconnected (reason "Server shutting down")
L 09/28/2016 - 18:13:05: server_message: "quit"
L 09/28/2016 - 18:13:05: Log file closed
L 09/28/2016 - 18:13:05: server_message: "restart"
L 09/28/2016 - 18:13:05: Log file closed.
L 09/28/2016 - 18:13:05: Error log file session closed.
Killed
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed Sep 28 18:13:05 CEST 2016: Server restart in 10 seconds

Do you think it would be a good workaround to just skip the "rcon quit" if the game is Insurgency?
If yes, I could try to implement this.

**Comment by dgibbs64** [comment]
I think probably not as using quit is still a graceful shutdown. Maybe shorten the shutdown time to something around  10 seconds may help. So the wait isnt so long maybe

**Comment by PhilPhonic** [comment]
I'm not sure if reducing the shutdown time to 10 seconds. This only speeds up the shutting down, this doesn't resolve the problem.
It would tell the server to quit (then automatically restart) and then while restarting, rcon quit will still fail and kill the server.

In my opinion, adding "-norestart" is the better solution.

**Comment by dgibbs64** [comment]
I was un aware of the -norestart option. If that will prevent the server from starting back up then that should be implemented since LGSM is designed to handle the restart rather than the server.

**Comment by PhilPhonic** [comment]
okay, so i think you just didn't see my edit in my earlier posts ;-)
I'll add that to the startup line and give a pull request

**Comment by dgibbs64** [comment]
Yup I missed it
