### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by DaviSeremeta** [GameServerManagers/LinuxGSM#1091]
I use: 
wget https://gameservermanagers.com/dl/rustserver

And get this:

--2016-09-30 19:59:48--  https://gameservermanagers.com/dl/rustserver
Resolving gameservermanagers.com... 104.31.92.238, 104.31.93.238
Connecting to gameservermanagers.com|104.31.92.238|:443... connected.
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
Unable to establish SSL connection.

-
Centos7.

**Comment by UltimateByte** [comment]
Either the server is faulty or this is a server issue. 
Can you try wget from git hub raw script ? If you can't download it, then check jour TLS certificates authority. (In debian is ca-certificates,, don't know for centos)

**Comment by DaviSeremeta** [comment]
I changed for Debian, now are ok.

**Comment by UltimateByte** [comment]
Good idea :)
