### ISSUE TITLE
Help using crontab in Ubuntu

### ISSUE THREAD

**Issue by DaviSeremeta** [GameServerManagers/LinuxGSM#1096]
I need use crontab in my server of rust, i put:

crontab -e
0 5 * * * su - rustserver -c '/home/rust/rustserver restart' > /dev/null 2>&1

But the root say to me:
?

I repeat
0 5 * * * su - rustserver -c '/home/rust/rustserver restart' > /dev/null 2>&1

And he say to me:
?

And not save that config...

**Comment by UltimateByte** [comment]
I didn't know that root was a person.

**Comment by DaviSeremeta** [comment]
This was a way of saying, because when I press enter with the crontab, appears "?" the next line.

**Comment by UltimateByte** [comment]
Can you please make a screenshot ?
BTW, non script issues are supposed to be answered on Discord or Steam group.

**Comment by DaviSeremeta** [comment]
See:
http://imgur.com/wYGy5DN

**Comment by cedarlug** [comment]
This is not an LGSM issue.  This is also not a Rust issue, so closing this with an answer:

Your editor isn't set.

```bash
apt-get install nano-tiny
export EDITOR=/bin/nano
crontab -e
```
If you don't like nano, then modify accordingly.

**Comment by DaviSeremeta** [comment]
Thank you.
