### ISSUE TITLE
failed to connect to server: Connection refused

### ISSUE THREAD

**Issue by testler2** [GameServerManagers/LinuxGSM#1100]
Hello, What is the cause of the problem?

[ OK ] Debug rust-server: Starting debug
 /home/rustserver/lgsm/functions/command_debug.sh: line 103: ./RustDedicated: No such file or directory
 rustserver@server:~$

**Comment by UltimateByte** [comment]
Hi,

First, make sure your LGSM is up to date
`./ruststerver uf` (for update functions)
Then share us safely the output of defails with
`./rustserver pd` (post details).
This will help us to know more.

**Comment by cedarlug** [comment]
WAG: Trying to run Rust on a 32-architecture.

**Comment by UltimateByte** [comment]
There should be a warning for that.

**Comment by testler2** [comment]
I found the problem, the problem x86_64

**Comment by testler2** [comment]
The problem I found the written after 10 minutes

**Comment by cedarlug** [comment]
Close?
