### ISSUE TITLE
[Dependencies] Ubuntu and libldap

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1101]
According to Shanekilz on Discord, this dependency is required at least for Goldeneye Source.
This would need to be double checked.

`apt-get install libldap-2.4-2:i386`

> Shanekilz - Today at 5:46 AM
> Having issues with GES server. Will add information as I gather it. Console states it's getting a Segmentation Fault (core dumped)
> Keeps restarting and getting no where really
> updating game and all functions to double check if it's our fault
> GoldenEye: Source Debug
> =================================
> 
> Distro: Ubuntu 15.04
> Arch:   x86_64
> Kernel: 3.19.0-61-generic
> tmux:   tmux 1.9
> Avg Load:       1.02, 0.85, 0.79
> Free Memory:    219M
> Free Disk:      155G
> GLIBC required: 2.15
> 
> Start parameters:
> ./srcds_run -game gesource -strictportbind -ip ###.###.###.### -port 27018 +client port 27008 +tv_port 27023 +map ge_archives +servercfgfile ges-server.cfg -maxplayers 16 -debug(edited)
> Shanekilz - Today at 6:22 AM
> Hey @UltimateByte You around
> Found the issue
> So we're on linux 15.04(edited)
> and we were missing a key library for the server to run correctly
> apt-get install libldap-2.4-2:i386
> ^ Since we were missing that, we were getting core dumps, installing that fixed it
> Worth double checking the lgsm install script to make sure it checks it. It might already, but Ehhh

**Comment by Shanekilz** [comment]
First a few things,
This may be an isolated incident due to our use of 15.04, rather than using 14.04 or 16.04.
This is entirely based on LDD of the server .sc file located in gesource bin. Before it was installed we had a Segmentation fault (core dumped) error, after installing, the issue was fixed. If you require any additional information please let me know.

**Comment by cedarlug** [comment]
Dupe #1085

**Comment by UltimateByte** [comment]
Thx @cedarlug Thought it was only a steam forum issue, didn't remember the github one.
