### ISSUE TITLE
Adding support for pushing to Channels with Pushbullet.

### ISSUE THREAD

**Issue by JATO457** [GameServerManagers/LinuxGSM#1102]
Some of us that use LGSM have more than one person running the back-end, and it'd be nice to have the option of having Pushbullet alerts sent to a channel, so more than one person can see them.

I've done a bit of testing, and it'd only require a couple of lines of code.

First would be added to the gameserver scripts, under Advanced Variables:

`channeltag=""`

The second would be added to alert_pushbullet.sh, inside of the curl command.

`-d channel_tag="${channeltag}"`

If the string is empty when the push is created, it will ignore it, and move on.

I've attached the modified tf2server script, as well as the modified alert_pushbullet.sh script for further clarification, if desired.
[alert_pushbullet.sh.txt](https://github.com/GameServerManagers/LinuxGSM/files/511858/alert_pushbullet.sh.txt)
[tf2server.sh.txt](https://github.com/GameServerManagers/LinuxGSM/files/511859/tf2server.sh.txt)

**Comment by dgibbs64** [comment]
Good bit of research. I will look at adding this for you :)

**Comment by JATO457** [comment]
Good to hear! I look forward to being able to use it as part of the official code, rather than editing every server we have each time we install a new one.

**Comment by dgibbs64** [comment]
This feature has now been developed https://github.com/GameServerManagers/LinuxGSM/releases/tag/161118
