### ISSUE TITLE
gsquery.py failed to query: ERROR: Unable to receive

### ISSUE THREAD

**Issue by silelmot** [GameServerManagers/LinuxGSM#1103]
Today it seemed, there was installed an update of the ins-server files,
but since then i get an error on one of my servers, running this:

gsquery.py failed to query: ERROR: Unable to receive

Distro Details
=================================
Distro: Debian GNU/Linux 8.6 (jessie)
Arch: x86_64
Kernel: 3.16.0-4-amd64
Hostname: server
tmux: tmux 1.9
GLIBC: 2.19

i tested with ports 27016 and  27017, both the same, but running on 27015 the monitoring is working
the servers are running since several months with no errors, just since the update...
any idea what to do, what could help?
thank you very much!

**Comment by dgibbs64** [comment]
./gameserver pd
also coudl use some log files that will help figure out the issue :)

**Comment by Maygus** [comment]
I am getting this on my 7dtd server
http://hastebin.com/evifoxobaj

Which log files will you require for investigation?

**Comment by UltimateByte** [comment]
"Change ports by editing the parameters in:
UNKNOWN"

It'as a least enought to explain why LGSM will only be able to monitor on port 27015.
Config file location or name changed ?

**Comment by Maygus** [comment]
I configured my port in the sdtdserver file and it's trying to connect to server. But failing. Tried setting it to 27018 as well as my telnet port to see if it made a difference.

**Comment by silelmot** [comment]
any solution yet?

**Comment by UltimateByte** [comment]
@Maygus @silelmot 
No solution without your config file output, that is most likely the issue here, as i suggested with my previous post.
We also need to know your config file name and location. As i said, your config file is not being recognized by LGSM, and you're both the only ones complaining about such an issue. So LGSM can't know what port to check for listening.

So until proven otherwise, it's a user based issue.

**Comment by UltimateByte** [comment]
Closing as no feedback.

**Comment by UltimateByte** [comment]
Not a user issue, see https://github.com/GameServerManagers/LinuxGSM/issues/1139 for more.
