### ISSUE TITLE
[ARK] Duplicate parameters | Server config files are overwritten at every server restart.

### ISSUE THREAD

**Issue by adgriff2** [GameServerManagers/LinuxGSM#1104]
All files in these locations are overwritten at every server start:
/home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/
/home/arkserver/serverfiles/ShooterGame/Saved/Config/CleanSourceConfigs/

`arkserver@Server01:~/serverfiles/ShooterGame/Saved/Config/LinuxServer$ stat GameUserSettings.ini`
  File: ‘GameUserSettings.ini’
  Size: 2916            Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 394032      Links: 1
Access: (0600/-rw-------)  Uid: ( 1003/arkserver)   Gid: ( 1003/arkserver)
Access: 2016-10-06 00:25:36.020873072 -0400
Modify: 2016-10-06 00:39:19.087156534 -0400
Change: 2016-10-06 00:39:19.087156534 -0400
Birth: -
`arkserver@Server01:~/serverfiles/ShooterGame/Saved/Config/LinuxServer$ ~/arkserver start`
[  OK  ] Starting ark-server: ark-server
`arkserver@Server01:~/serverfiles/ShooterGame/Saved/Config/LinuxServer$ stat GameUserSettings.ini`
  File: ‘GameUserSettings.ini’
  Size: 2916            Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 394032      Links: 1
Access: (0600/-rw-------)  Uid: ( 1003/arkserver)   Gid: ( 1003/arkserver)
Access: 2016-10-06 00:41:25.573665726 -0400
Modify: 2016-10-06 00:41:25.577665678 -0400
Change: 2016-10-06 00:41:25.577665678 -0400
 Birth: -

I've even tried deleting the entire contents of both folders. The files get recreated and any config changes made are overwritten.

**Comment by Smile42RU** [comment]
@adgriff2 As far as I know usage correct encoding of the file will help solve the problem. Try UTF-16 LE.

**Comment by UltimateByte** [comment]
@Smile42RU Thanks for the hand, i got no clue about this.
If this is the actual issue, you can also edit your config with nano or vi instead of with an FTP and a windows editor, since they should preserve the formatting.

**Comment by adgriff2** [comment]
I've been running an ark server on this same box for around a year with my own (quite humble) steamcmd script and never had a config encoding issue, odd. My backup configs are all ascii. This is the first time I've tried LGSM.

That said, I used iconv to change the encoding to UTF-16LE. This had no effect and was overwritten as soon as the server was started.

**Comment by adgriff2** [comment]
It appears that some options are defined in the startup parms and also in the config file. Maybe these are in conflict?

**Comment by UltimateByte** [comment]
Well spotted, it could be !
Can you try removing them from the config file and see ?

**Comment by adgriff2** [comment]
I've reverted to using my previous script for the time being. I'll try to schedule some downtime at some point to play with it.

**Comment by UltimateByte** [comment]
We had several people complaining about this recently. So we need to get our hands in it i guess anyways.

**Comment by cedarlug** [comment]
From what I find, this is what Ark does with a config file with an error.
Ref: https://github.com/FezVrasta/ark-server-tools/issues/367 
Ref: http://survivetheark.com/index.php?/forums/topic/1614-gameini-wont-save-and-gets-blank-on-server-start/&do=findComment&comment=47538
Ref: https://github.com/FezVrasta/ark-server-tools/issues/260

My recommendation is to put all of your settings in the `arkserver` script.

**Comment by Maygus** [comment]
Are you generating your gameusersettings.ini and copy/pasting it in?
I ended up taking my generated .ini file and retyping the settings in manually and it worked.

**Comment by adgriff2** [comment]
> Are you generating your gameusersettings.ini and copy/pasting it in?
I ended up taking my generated .ini file and retyping the settings in manually and it worked.

At first I was, but then I deleted all the configs and let the starting server recreate them. I then restarted the server without altering the configs. The starting server overwrote the configs it had just created. This seems to confirm that the problem isn't linked to a user altering them.

**Comment by adgriff2** [comment]
Here's what I currently use that doesn't have the config overwriting problem. It's just a small script I wrote to stop the server via systemd, forceupdate it, then start it back up via systemd. Below that is the systemd 'script' that contains the startup command that works. It's much more abbreviated than the one used in LGSM. I'm thinking the LGSM startup command may be the problem.
`adgriff2@Server01:~/scripts$ cat updateArk.sh`
#!/bin/bash
sudo systemctl stop ark-dedicated.service \
&& /home/steamuser/steamcmd/steamcmd.sh \
+login anonymous \
+force_install_dir /home/steamuser/steamcmd/Ark \
+app_update 376030 \
+quit \
&& sudo systemctl start ark-dedicated.service
`adgriff2@Server01:~/scripts$ cat /etc/systemd/system/ark-dedicated.service`
[Unit]
Description=ARK: Survival Evolved dedicated server
Wants=network-online.target
After=syslog.target network.target nss-lookup.target network-online.target

[Service]
ExecStart=/home/steamuser/steamcmd/Ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?SessionName=GriffinArk -server -log
LimitNOFILE=100000
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
User=steamuser
Group=steamuser

[Install]
WantedBy=multi-user.target

**Comment by adgriff2** [comment]
Changing the '#parms variable in arkserver.sh to be more like my old startup command seems to have fixed the problem. I removed args for MultiHome, MaxPlayers, QueryPort, RCONPort, Port, and ServerAdminPassword. I think these are taken care of in the config.

**Comment by UltimateByte** [comment]
BTW we have to chose anyways if we put stuff inside the .ini or start parameters in LGSM. There are currently some duplicate parameters.
This needs to be addressed.

**Comment by UltimateByte** [comment]
I'm on it.
Ark don't give a crap about ports set within cfg file. So we'd rather get them only into start parameters.

**Comment by UltimateByte** [comment]
So, here is what config looks like now
https://github.com/GameServerManagers/Game-Server-Configs/commit/3ff04eadc7c5b76c9fbe9ffee79fd8e6401bec61#diff-4ca2a40fe9ae60534d8ed66ed8a843ce

> SessionName & ServerAdminPassword are set using .ini file.
> Leaving RCONPort since Ark will recreate it anyways, at least it'll be in the right location.
> Ports/maxplayers/IP are set within start parms; however maxplayers will show up in .ini after starting the server but can't seem to be set within .ini file, resets to 70 no matter what.

Pull-requesting for a main script fix soon.

**Comment by UltimateByte** [comment]
This has been merged.
Advised:
- Updating `arkserver` script
- Running `./arkserver uf`; 
- Grabbing the newest config file (renaming the older will do the trick, newest will be downloaded).

**Comment by jkdoug** [comment]
I'm having this issue myself, using the latest and greatest arkserver scripts. Nothing I've tried so far has stopped my config from being overwritten every time I start the server.

The weird thing is that I see no message echo'd, and my default config, which I edited, remains intact. I don't know where it's even getting the config file it's using or where in the code it's doing this.

**Comment by UltimateByte** [comment]
@jkdoug What are you editing your config with ? Are you sure you're putting settings at the right location ? Are you editing config files while the server is off ? (you should)

**Comment by jkdoug** [comment]
Yes, I stopped the server, edited serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini with vi, and started the server again.

I tried editing arkserver to use the develop branch. It seems that the features are not merged into the master very often.

**Comment by UltimateByte** [comment]
@jkdoug Once a week. Changes mentioned here are already implemented.

**Comment by jkdoug** [comment]
Well, I'm sorry, but the changes are not fixing anything for me. Maybe I'll try deleting everything and starting over.

**Comment by UltimateByte** [comment]
@jkdoug Any mistake in Ark's config file will make it overwritten. LGSM part about it has been fixed unless proven otherwise.
