### ISSUE TITLE
[Ark: Survival Evolved] Much prozesses after start

### ISSUE THREAD

**Issue by Tealk** [GameServerManagers/LinuxGSM#1105]
Is it corret that the server show me after the start so many prozesses?
![image](https://cloud.githubusercontent.com/assets/12276250/19144624/fa2ffb52-8baa-11e6-8bdd-522807b84c17.png)

**Comment by UltimateByte** [comment]
That's cool bro. Now either you follow our recommendations to provide help and we're glad to try to help you, or you don't and we close this irrelevant issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Tealk144** [comment]
i dont know what you want for aditional information?
I start the server with your script and get many prozesses.

The Game is ark like you see in screen
Debian GNU/Linux 8.6 (jessie)
there are no useful logs they only say the server is started

**Comment by UltimateByte** [comment]
The point is: Not every helper here use Ark. So we need to really know what you're talking about to help you. I personally won't make an Ark server to enlight your point, otherwise if i did that for every issue with too few info, i couldn't use the time i'm allocating to LGSM to help as many people as i would like.
  
This might just be normal. Your screenshot isn't full and it could lack some informations.
Also, if you input ./arkserver details, you'll get a useful command to diagnose what's listening at the bottom of it. Would be relevant to do it as well. 
Also, no need to screenshot code, you can just paste it in plain text. In SSH with putty, you just need to select the text so that it gets copied.

**Comment by Tealk144** [comment]
if u use htop as pozess monitor i cant copy it as plain text
here the "arkserver dt"
https://paste.anzah.network/paste.php?id=13

**Comment by UltimateByte** [comment]
Thanks man. 
Now
netstat -atunp | grep ShooterGame
And we're all set.
I gotta go right now, i know @cedarlug will have a look at your issue. Ttyl, good luck with it, but i think it definitely could be a non-issue. ^^

**Comment by Tealk144** [comment]
steam@anzahserver:~$ netstat -atunp | grep ShooterGame
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 176.9.90.67:27020       0.0.0.0:*               LISTEN      18461/ShooterGameSe
udp        0      0 172.17.0.1:38003        0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 176.9.90.67:7778        0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 172.17.0.1:57328        0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 172.17.0.1:58148        0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 176.9.90.67:27015       0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 172.17.0.1:49957        0.0.0.0:*                           18461/ShooterGameSe
udp        0      0 172.17.0.1:53457        0.0.0.0:*                           18461/ShooterGameSe

**Comment by UltimateByte** [comment]
I bet on one process per port + one process per IP.
*fly back away*
:p

**Comment by Tealk144** [comment]
i have 8 lines from netstat and 14 prozesses

**Comment by UltimateByte** [comment]
The first question is should have asked is : Is your server working properly ? Or are we just curious about why it's acting this way ?

**Comment by cedarlug** [comment]
Finally getting to a console after a day of distractions.   Will check on this and the other Ark issue posted shortly.

**Comment by cedarlug** [comment]
Your pastebin output shows that you're binding to the 176.9.90.67 Ip address, but your netstat command show ShooterGame *ALSO* listening on the private172.17.0.1 address.  

Your startup command uses the multihome parameter correctly to bind to the 176.9.90.67 address, so there shouldn't be anything listening on the private 172.17.0.1 address.  Looks like it's time to break out "killall -KILL ./ShooterGameServer" and start fresh.

To your initial concern - yes, it runs multiple threads.  Mine runs about 10 threads on 2 cores.

**Comment by Tealk144** [comment]
ok, if this is normally its all fine. I notice that after a server crash and a member have start the server again, after that there was 30+ threds and the server had lags

i have kill all "shootergameserver" threads but after i start the server i have there the 172.17.0.1 again

@UltimateByte yes the Server run fine, most time^^ ark have some bugs

**Comment by UltimateByte** [comment]
So is this a recurring issue or can we close this ?

**Comment by cedarlug** [comment]
Reopen if questions remain.
