### ISSUE TITLE
grep reports issue, server starts but with dependency issues

### ISSUE THREAD

**Issue by AxFalcon** [GameServerManagers/LinuxGSM#1107]
Thanks in advance :) AWESOME PROGRAM BTW!!!! I really, Really appreciate this work, You've saved me hours. Thanks :)!

So on centos this csserver installed with no trouble. However on debian the server starts but after re-downloading dependencies and checking things and all this other stuff.

I've tried to update grep but I don't know how to replace it properly however, I don't think that's the issue. 
I've tried to chmod permissions so that my user can use grep/dependencies but this doesn't seem to have any effect atm. 

System is:
3.6Ghz Intel i386 
DebianRT 3.2.81-rt117
1Gb RAM etc
csserver package downloaded this week, upgraded and validated. Does run server but after heaps of errors. 

This is what we get when server starts:

`./csserver start`
`[ .... ] Starting cs-server: grep: support for the -P option is not compiled into this --disable-perl-regexp binary`

`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`
`grep: support for the -P option is not compiled into this --disable-perl-regexp binary`

`[ERROR ] Starting cs-server: Checking dependencies: missing: wget ca-certificates file bsdmainutils util-linux python bzip2 gzip lib32gcc1 libstdc++6:i386
[sudo] password for user1:`

...and as you can see if asks me for a sudo password. The user1 has sudo, tty and ftpaccess privileges and I have chmod 777 to /home/user1 all files and folders so that the server runs correctly. 

Any ideas? Thanks  :)

**Comment by UltimateByte** [comment]
Dependency issue causes by a weird distro i think.
Why don't yoy use debian 8 standard ?

**Comment by AxFalcon** [comment]
Couldn't find a good PREEMPT RT for it (keen on 1000fps server). So does this error mean that "grep" is in error or that perl-regxp is in error or something else? How would the bug testing go from here?

**Comment by UltimateByte** [comment]
1000 fps servers are pointless in my opinion. Tick 128 is useful though and can be achieved easily.
However, if you wish to achieve 1000fps, i heard any distro you can work as long as you change the system timer. 

BTW, the issue here, if you're saying that you installed dependency packages already, is probably that LGSM is unable to detect your package manager. LGSM tries to sudo in order to install the packages, but if it is trying to run an apt-get when it doesn't exist, then it can't work out.

What's your package manager ?

**Comment by AxFalcon** [comment]
If you're referring to `apt-get`, `dpgk` or `grep` -I have all of these installed and I used the root user account to install them to wherever they installed to by default.  

I also tried installing all the packages from the `user1` that has sudo account privileges but it said 
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.` as all the packages were already installed. 

Do I have to do something to LGSM or perhaps my package manager?

**Comment by UltimateByte** [comment]
By any means, do you have yum installed as well ?
That's the main thing that could fuckup the detection on a debian based distro i see.

**Comment by AxFalcon** [comment]
neg :)

**Comment by UltimateByte** [comment]
Well, as usuall, my first read was bad.

grep: support for the -P option is not compiled into this --disable-perl-regexp binary

Your issue probably for grep missing the -P option, that seem to require perl.
Can you try installing perl ?

**Comment by cedarlug** [comment]
Your original post is lacking some of the key system attributes.  Can you please post the output from:
```bash
  ./csserver postdetails
```
You're running debian, but what version?  Is the kernel i386-only?  Your OP represents a very bizarre system configuration.  Is it a container? OpenVZ, LXC, ???

In addition, please post:
```bash
which wget
which python
which bzip2
which gzip
dpkg -l | grep ca-certificates
dpkg --print-architecture
dpkg --print-foreign-architectures
```
Please post the output of the commands above to pastebin.

**Comment by AxFalcon** [comment]
**Answer cedarlug:** It is a VPS from VULTR.com that had the only RT kernel I could find for kernel 3.2, applied to it. 

output is follows: 

`./csserver postdetails`
    `fetching command_postdetails.sh...OK`
    `fetching command_details.sh...OK`
`[  OK  ] Postdetails cs-server: Posting details to hastebin.com for 1W`
  `* url: http://hastebin.com/loqacureje`

**Answer UltimateByte:** Perl seems to be installed as follows: 

`perl --version`
`This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi`

Thanks.

**Comment by cedarlug** [comment]
@AxFalcon 
... and the other stuff that was requested?

**Comment by AxFalcon** [comment]
From OP: 

System is:
3.6Ghz Intel i386 
DebianRT 3.2.81-rt117
1Gb RAM etc

Debian 7 64bit and yes it's a container if I have that correct. It is a VPS from VULTR.com. The other stuff I wouldn't know sorry I only just started using debian a few days ago.

**Comment by AxFalcon** [comment]
In another request, would anyone happen to know which distro below has completely minimal cpu usage and services running that'd be good for just running this gameserver? Here are the choices I have (and I'll try find PREEMPT RT for your suggestions x)

`CentOS 6 x64, CentOS 6 i386, CentOS 5 x64, CentOS 5 i386, CentOS 7 x64, Ubuntu 12.04 x64, Ubuntu 12.04 i386, Ubuntu 14.04 x64, Ubuntu 14.04 i386, Ubuntu 16.04 x64, Ubuntu 16.04 i386, Debian 7 x64 (wheezy), Debian 7 i386 (wheezy), Debian 8 x64 (jessie), Debian 8 i386 (jessie), FreeBSD 10 x64, CoreOS Stable, Fedora 24 x64,`

**Comment by cedarlug** [comment]
Closing   

Your OP "details" isn't helpful. Reopen if you can post the following requested information:

Output of./csserver pd, NOT RUN AS ROOT

The output @UltimateByte requested regarding yum

The output of running these commands.
which wget
which python
which bzip2
which gzip
dpkg -l | grep ca-certificates
dpkg --print-architecture
dpkg --print-foreign-architectures

None of this is particularly difficult to generate, and all of it relates to your circumstance.
