### ISSUE TITLE
ocomposer problem

### ISSUE THREAD

**Issue by testler2** [GameServerManagers/LinuxGSM#1108]
Hello, what is the cause of this problem?
PHP Parse error:  syntax error, unexpected '[' in /usr/bin/ocomposer on line 89

Ubuntu

**Comment by dgibbs64** [comment]
What is ocomposer? I have no idea what you are talking about

**Comment by testler2** [comment]
Oxidemod plugin auto installer

**Comment by dgibbs64** [comment]
Probably best ask on the oxide mod forums. As is not an LGSM issue.

**Comment by UltimateByte** [comment]
Hi, if we start giving support for other scripts, we're gonna get into trouble.
Ask the plugin auto installer dev ;)
