### ISSUE TITLE
[LGSM] Add error handing to postdetails for when it's run as root

### ISSUE THREAD

**Issue by cedarlug** [GameServerManagers/LinuxGSM#1109]
Need to die early with an error message when someone tries to run `./scriptname pd` as root.

**Comment by UltimateByte** [comment]
The root detection could be into the main script to prevent lgsm from downloading any function as root though. What do you think ?

**Comment by UltimateByte** [comment]
Maybe this more audacious one instead ?
https://github.com/GameServerManagers/LinuxGSM/issues/1121
Would address your issue and some more.

**Comment by cedarlug** [comment]
Indeed it would

**Comment by UltimateByte** [comment]
Close then ?
