### ISSUE TITLE
Unhandled single quotes in config

### ISSUE THREAD

**Issue by hatbocs** [GameServerManagers/LinuxGSM#1111]
Found when configuring my csgo server.

> // Server Name
hostname "Ba-loo's Comp Server"

When restarting the server I get errors.

> csgoserver@baloomain:~$ ./csgoserver restart
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
[ .... ] Stopping csgo-server: NOT SETxargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
[ERROR ] Stopping csgo-server: Graceful: rcon quit: FAIL
[  OK  ] Stopping csgo-server: NOT SET
[ .... ] Starting csgo-server: NOT SETxargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
[  OK  ] Starting csgo-server: NOT SET

Removing the single quote in the hostname will correct this. `hostname "Ba-loos Comp Server"`

I traced this back to /lgsm/functions/info_config.sh and added a bit to the servername line. Note `-e "s/'//g"` which removes stray single quotes.

> servername=$(grep "hostname" "${servercfgfullpath}" | sed -e 's/^[ \t]*//g' -e '/^\//d' -e "s/'//g" -e 's/hostname//g' | tr -d '=\";,:' | xargs

Not ideal, I think but the only work around I have right now since I'm not great with bash scripting.

I haven't had this issue until a week ago, or so.

**Comment by UltimateByte** [comment]
We need to reproduce. If you're right, then it's a global bug that needs to be fixed.

**Comment by hatbocs** [comment]
Thank you much.

Oddly enough, I'm pretty sure some older version of the scripts were handling it just fine because I could have sworn I was using an apostrophe/single quote in the hostname this whole time. The only thing that would have changed was finally getting the newest version of the csgoserver script. The one I was using before was still looking for dgibbs64, if that helps.

**Comment by UltimateByte** [comment]
Error reproduced on a gmod server, confirmed.
Every source game is concerned, maybe more.
If you put two single quotes the error doesn't happen.

Key to fix it : So the best way would be to set this variable in a way that accepts single quotes... Can't think of one for now, would need some research. Or, using a special sed as suggested. 

> The only thing that would have changed was finally getting the newest version of the csgoserver script. 

Nope, as you said previously, it's not csgoserver itself but info_config.sh. Unless you're talking about a very old time where everything was contained into one single script. :p

**Comment by cedarlug** [comment]
Try adding `-e 's/0x27/\\\'/g' `into the expression (if you want to preserve the tick/apostrophe).

(This is off the top of my head - I'll check to see what that does here in a moment.)

**Comment by cedarlug** [comment]
Are either/both of you getting a message about xargs with the single tick?  If so, I think that I have the global fix.

**Comment by hatbocs** [comment]
The quote I had in the first post was exactly what the script was spitting out to console when I first reported the issue (before attempting to fix). So in short, yes.

**Comment by cedarlug** [comment]
```bash
./csgoserver uf
sed -i 's/xargs)$/xargs -0)/g' lgsm/functions/info_config.sh
./csgoserver details
```
Please try.

**Comment by cedarlug** [comment]
Oh - but if you edited the file first, then probably the full shabang is necessary:
```bash
rm lgsm.functions/info_config.sh                             #remove whatever is there, changes and all
./csgoserver details 2>&1 > /dev/null                        # forces it to be re-downloaded
sed -i 's/xargs)$/xargs -0)/g' lgsm/functions/info_config.sh #fixes the pristine source
./csgoserver details                                          # All good?

**Comment by hatbocs** [comment]
Worked for me.

Now to figure out why rcon won't gracefully quit. And why my server doesn't show up in the server browser.

**Comment by UltimateByte** [comment]
@hatbocs Start by watching your console logs. Those two errors might be related. I bet on a GSLT issue.

**Comment by hatbocs** [comment]
Of course, the logs! For some reason I didn't look through them. And there's a segmentation fault as it's starting the server. I'll have to tackle that one later on today.

Thanks for the help @UltimateByte and @cedarlug

**Comment by UltimateByte** [comment]
@hatbocs If you're using sourcemod/metamod, the last csgo update broke it. You need to update your addons. Watch out your config files, don't overwrite them. :)

**Comment by UltimateByte** [comment]
Merged, we can close now.
To get the update : ./gameserver uf
Thanks for reporting.

**Comment by hatbocs** [comment]
Awesome, thanks for the heads up.
