### ISSUE TITLE
save directoy

### ISSUE THREAD

**Issue by Slyvester1** [GameServerManagers/LinuxGSM#1113]
I was thinking of changing my save directory for my ark server to a separate disk. Wouldn't this prevent lag on autosaves? If this is possible, how do i go about changing the save directory to a separate disk?

**Comment by cedarlug** [comment]
In theory, but only if your game is thrashing the disk while this is going on.  If that's the case, then offloading the save to another disk might cause even more delay.

How use a different disk?  The easiest ways: Mount the target as an NFS mount point, a bind mount point, or as a symlink to another directory on a different disk.

**Comment by UltimateByte** [comment]
Most game servers will just stop working during saves, whatever the disk is.
Possible bottlenecks are CPU and HDD speed. That's the main reason why you see game servers with ssds now. 
Also you can in applicable, you can try to make sure that your server isn't saving a bunch of useless stuff every time. For example with Rust you can use constructions decay.

**Comment by Slyvester1** [comment]
I'm on an ssd, but I'm pretty sure its the processor like you said. Im using it as a dedicated server with just ark and have Xeon 1220 v3 processor. It just lags for maybe 5 seconds then its fine afterwords. I have ran a rust server on the same machine in the past and this doesn't happen (no lag whatsoever. Then again, I think Ark is not as polished Rust.

**Comment by Slyvester1** [comment]
It could be mods too, but I'm not sure. I run only 10 mods max.

**Comment by UltimateByte** [comment]
I've been told it was "normal" for an ark server to have some rollbacks... I guess the only thing left is to yell at Ark's devs.

**Comment by UltimateByte** [comment]
I'll have to close this since it's a non script issue. However, if you think there is more to do, is suggest coming to discord & or steam group forum. 
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#general-support
