### ISSUE TITLE
 can not se server in lan-liste (solution)

### ISSUE THREAD

**Issue by digimon-dk** [GameServerManagers/LinuxGSM#1114]
I had trouble seeing my game server on lan-list. but could join them via the console by typing connect (ip: port).

in ./csgoserver file deleted I the deleted I **-IP $ {ip**} and it worked on Ubuntu 16.04 Server

 parms= "- game csgo -usercon -strictportbind **-IP $ {ip}** port $ {port} + client port $ {client port} + tv_port $ {sourcetvport} + sv_setsteamaccount $ {} gslt -tickrate $ {} tic rate + map $ { defaultmap} + servercfgfile $ {servercfg} -maxplayers_override $ {maxplayers} + mapgroup $ {mapgroup} + game_mode $ {game mode} + game_type $ {game type} + host_workshop_collection $ {ws_collection_id} + workshop_start_map $ {ws_start_map} -authkey $ {authkey} "

**Comment by UltimateByte** [comment]
Hi,
Please, happen ./csgoser PD
And provide the generated link.
Don't delete variables, set IP to the interface address.

**Comment by digimon-dk** [comment]
thanks I have overlooked this feature :)

**Comment by UltimateByte** [comment]
And the output is... ?

**Comment by jach11** [comment]
Have you tried changing `sv_lan 0` to `sv_lan 1`?

**Comment by cedarlug** [comment]
Since the OP's "solution" isn't actually posted here, I'm closing this as user-error-now-has-been fixed.

**Comment by kekeN7** [comment]
I'm a newbie, so this could be an user error, but I'm having the same issue. 
Can join via console, but server is not visible in the server browser menu.
(different game though)

Here's my output @UltimateByte asked for
http://hastebin.com/urusivupus

**Comment by UltimateByte** [comment]
@kekeN7 Your ports are not properly set. 
RCON and stats ports shows "0".
Also, port 28960 is far from the standard 27015, csgo might refuse to listen to this port. 
Ultimately, make sure your GSLT is properly set.

This entire page might help as well.
https://github.com/GameServerManagers/LinuxGSM/wiki/Ports

**Comment by kekeN7** [comment]
But it's not csgo. (CoD:UO)

**Comment by UltimateByte** [comment]
@kekeN7 Then what are you complaining about ? This script isn't released yet.

**Comment by kekeN7** [comment]
I know - I know, I wasn't complaining. :)

**Comment by UltimateByte** [comment]
I mean you dont have the same issue at all so please don't report issues on non released scripts, it's common sense.

**Comment by dgibbs64** [comment]
@kekeN7 yeah this is an unreleased script that I have not yet fully tested @hurdad Has created it but its not yet fully integrated in to LGSM. Best thing to do is contact him about it. You can raise an separate issue and just put @hurdad to get his attention :).

**Comment by kekeN7** [comment]
Yeah, we have already discussed this with him (https://github.com/GameServerManagers/LinuxGSM/issues/1089), and sorry guys, I wasn't meant to be impatient, just found this issue with the same title as my problem and then commented, that's all.

**Comment by dgibbs64** [comment]
@kekeN7 no worries :)

**Comment by hurdad** [comment]
To get your server to show up in lan browser you have to set -ip 0.0.0.0.

However, if you set ip = 0.0.0.0 in the script, check_ip.sh changes it to your actual IP...

```
if [ "${ip}" == "0.0.0.0" ]||[ "${ip}" == "" ]; then
```

So, what I do is replace '-IP ${ip}' with '-IP 0.0.0.0'

**Comment by cmavromichalis** [comment]
Hey, this issue seems to have resurfaced. I have tried the advice above and it worked for CSGO but not for TF2.
