### ISSUE TITLE
Review if certain servers require the ip= var

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1120]
I belive some servers have the ip= var that may not require it. Testing of all these servers will be required. This can then be removed as required.

**Comment by dgibbs64** [comment]
After review LGSM itself requires ip= anyway. so All servers should really be using it.

**Comment by UltimateByte** [comment]
Well, some servers like teamspeak don't need an ip variable at all and LGSM gets it from config file.
