### ISSUE TITLE
Quake Live is broken with Tmux

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1122]
For some reason quake live is not playing well with tmux after testing with CentOS and Ubunutu. In ubuntu I get the error 

```[ .... ] Starting ql-server: no server running on /tmp/tmux-1000/default```

The quake live proccess appears to break out of the tmux session and continue to run even if tmux fails. It s a very odd issue. I am not sure on a fix for this. Quake live still works in debug mode but not with tmux.

**Comment by hurdad** [comment]
interesting!

**Comment by UltimateByte** [comment]
It does the same error as for Ralph on Discord.
We weren't sure about what the actual issue was since it self solved. But @cedarlug had an idea.

> Sounds like Ralph has an lxc container without a devpts automounted.
> A test would be if when you can't enter tmux, you then ssh into localhost and then suddenly everything works.

**Comment by cedarlug** [comment]
It looks like this is a different issue.

Try simply removing the "<" and ">" for the default hostname and rcon password (2 locations) in `serverfiles/baseq3/ql-server.cfg`

Those are interfering with the tmux session creation command.

**Comment by UltimateByte** [comment]
@cedarlug I think those are removed on installation, with fn_set_config_vars in install_config.sh
Fresh install : 
`set sv_hostname "LinuxGSM"`
`set zmq_rcon_password "adminzxi5MfqE"`

Cannot reproduce the issue on my debian install, seems to be working flawlessly.

**Comment by cedarlug** [comment]
@UltimateByte - Reworked by @dgibbs64 in [install_config.sh](https://github.com/GameServerManagers/LinuxGSM/commit/5f461b14a4ac93a6ca95cd99db24aba0f517e24f#diff-a827ecc5680e4f8b88a20803ab45835f)

Can close.
