### ISSUE TITLE
Server issue ^^

### ISSUE THREAD

**Issue by Jean92160** [GameServerManagers/LinuxGSM#1126]
Hey,
So i made one server : it's okay
I try to make an other server but  I get this error : 
Couldn't change active gamemode - 'Poudlard' not found
Usage: sv_setsteamaccount <login_token>
WARNING: NNET_OpenSocket: bind: Cannot assign requested address
Couldn't allocate any server IP port
Couldn't allocate any server IP port
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
dimanche 16 octobre 2016, 15:05:25 (UTC+0200): Server restart in 10 seconds

So even if try to change the port to somethink like 27017 it's not working.
How could i fix this please ? :)
Thanks,

**Comment by marvinl97** [comment]
Could you please run "./yourserver pd" for both servers and post the link here?

I don't know which game it is but it seems that you didn't set the GSLT. You need one per server. https://steamcommunity.com/dev/managegameservers

**Comment by Jean92160** [comment]
It's a gmodserver :)
http://hastebin.com/xeyanefazi.sql

**Comment by UltimateByte** [comment]
You're doing multiple servere wrong. Have some read and you'll be good to go. The issue here is obvious, I'm pretty sure this will allow you to find out why :
https://github.com/GameServerManagers/LinuxGSM/wiki/Ports

**Comment by marvinl97** [comment]
And your gamemode contains a space.

**Comment by UltimateByte** [comment]
@cedarlug Tickrate 16 is normal for gmod servers with shitload of addons, props and players everywhere. :o))

**Comment by Jean92160** [comment]
it's not working, even if i set a new IP :/

**Comment by UltimateByte** [comment]
@Jean92160 If this IP is within the same range, or is still banned 4players, then that's expected.
What you can do however is manually install ts3 in serverfiles, then LGSM will handle server management, except auto update won't be possible.

**Comment by marvinl97** [comment]
@UltimateByte Did you respond to the wrong issue? :D

**Comment by Jean92160** [comment]
So what can i do ? :/
Maybe in french ? lol x)

**Comment by UltimateByte** [comment]
@marvinl97 Yeah i've been mixing issues, i thought it was the person blocked from 4players website who tried with a new IP, sorry. 
@Jean92160 It's never been about IP, it's about ports. You're trying to use already bound ports for your second server, and obviously, ports can't overlap. I you don't know that, then i'd be astonished if you know how to properly use multiple IPs on a single machine. You need to set all the 3 ports to different ports. I thought the wiki page was pretty clear, isn't it ?

**Comment by Jean92160** [comment]
well maybe i am like a noob :/ But i still not understand or still can't make it work //

**Comment by UltimateByte** [comment]
```
WARNING: NNET_OpenSocket: bind: Cannot assign requested address
Couldn't allocate any server IP port
Couldn't allocate any server IP port
```

This means either you chosed an invalid IP, or an already used port.

To know if a port is already used : 
`netstat -atunp | grep PORTNUMBER`

Inputting `./gameserver details` on a game will give you port settings of the gameserver. For source games, there are usually 3. Each server needs to use 3 different ports than other ones.

If you can't figure stuff out with those info + the wiki (that says the exact same thing in the end) i'm sorry but i don't see how i could help more. By the way, user issue should not be seen on github, but rather on discord or steam group, so i'm gonna have to close this. https://github.com/GameServerManagers/LinuxGSM/wiki/Support#where-to-get-support
