### ISSUE TITLE
Murmur invalid output on start/stop

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1130]
```
[  OK  ] Starting mumble-server: Mumble Port 64738
# Amount of users with Opus sup needed to force Opus usage in percent.
# 0  Always enable Opus 100  enable Opus if it's suped by all clients.
ultimatebyte@game:~$ ./mumbleserver stop
[ .... ] Stopping mumble-server: Stopping Mumble Port 64738
# Amount of users with Opus sup needed to force Opus usage in percent.
[ .... ] Stopping mumble-server: Mumble Port 64738
# Amount of users with Opus sup needed to force Opus usage in percent.
[  OK  ] Stopping mumble-server: Mumble Port 64738
# Amount of users with Opus sup needed to force Opus usage in percent.
# 0  Always enable Opus 100  enable Opus if it's suped by all clients.
```

Details is broken as well

**Comment by UltimateByte** [comment]
Fixed it in devbranch, however i need to figure out why IP doesn't get set as it should within details. I suspect check_up.

**Comment by UltimateByte** [comment]
Will continue checking this tonight, feel free to see it while i'm away @dgibbs64 especially since you reworked some stuff, i'm gonna have to talk to you anyways to save some time.

**Comment by dgibbs64** [comment]
There are changes in how IP address checing works. The new method is. If the IP is set in the parms it uses ip= however if the ip is set in the config is uses that. 

What was happening was some used parms others used configs and some used ip= and with configs. Was confusing I may of misssed mumble. 

Last change removed ip=
https://github.com/GameServerManagers/LinuxGSM/commits/master/Mumble/mumbleserver

So this is probably the issue

**Comment by UltimateByte** [comment]
Well @dgibbs64 not solved.
I'm on it.

**Comment by UltimateByte** [comment]
Output fixed with awk. Feel free to correct the sed / tr if you wish, until then, it's better off this way !
Now let's see another issue with mumble... hopefully it's not a mumble issue.
