### ISSUE TITLE
Problem with steamcmd.sh

### ISSUE THREAD

**Issue by AwesomeGeeky** [GameServerManagers/LinuxGSM#1131]
Hi, I have a problem with my pleasant surprise when I want to restart, stop...and validate my CSGO server's

I have this that appears: 
> ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD can not be preloaded (wrong ELF class: ELFCLASS64): ignored.
> /home/csgo/csgo-d2/steamcmd/steamcmd.sh: line 38: 3936 Segmentation fault $ DEBUGGER "$ STEAMEXE" "$@"

my file attached seal part is what I have in steamcmd.sh line 38
![ss 2016-10-18 at 10 25 35](https://cloud.githubusercontent.com/assets/22202399/19495100/43de9958-9582-11e6-9a33-d5d0f1b6cb41.png)

I need help guys, i looked if my dedicated server or my script had a default but I do not have to feel

**Comment by UltimateByte** [comment]
Hi,
First line is a non-error everyone has it. 
Second one is a segfault see if this link helps. Also make sure you're not using an unsupported architecture such as ARM or unsupported shell such as anything else than bash.

https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#segmentation-fault

Without more info (what you gave is too poor to  desirve being on github to be honest) I cannot help more.

**Comment by FlashModz** [comment]
steam was down yesterday, it completely wrong for everyone :)
if not try the install process from the official website steamcmd Valve.
her to solve my problem

**Comment by UltimateByte** [comment]
If my servers are OK, I'll try a fresh install.

**Comment by UltimateByte** [comment]
Nice info. Maybe just try again then, cleaning previous installs, especially steam and steamcmd.

**Comment by UltimateByte** [comment]
Can't reproduce issue, i think it was a temporary one due to steam.
LD_PRELOAD error is a non critical message, just a warning that won't prevent a successful installation.

Please re-open if you still have this issue.
