### ISSUE TITLE
Logs Broken

### ISSUE THREAD

**Issue by FlashModz** [GameServerManagers/LinuxGSM#1132]
Débian 8 Stable Jessie.
All Package Are OK.

Server is On and Functionnals.

Problems : 

[http://pastebin.com/vMn6S5Ak](url)

Logs console are completly broken.
No Error / All Package are Up to Date / No Addons  / No GameMode

Thanks for your help

**Comment by UltimateByte** [comment]
Can you please put that log to pastebin or equivalent, make sure your lgsm is up to date, and add the output of /game server pd ? 
I'll check mine when I get home but I'd be stunnished if it was a script issue, I think it's rather a Gmod issue. What do console and debug commands give as an output ?

**Comment by FlashModz** [comment]
TMUX : tmux 2.3
Debug Logs : http://pastebin.com/B8uZQN83
LGSM Details : http://pastebin.com/JJ2Z5Y1E
Reinstall Not solve the problems.
Apt-get update & Upgrade All Ok and not solve the problems.

**Comment by UltimateByte** [comment]
Thanks.
So debug output is fine, then it's an issue with tmux. Will check my gmod servers when I get back home in a couple of hours. I got the same distro, so if it's a global issue I should have it as well.

**Comment by FlashModz** [comment]
Ok thanks Bro :)

**Comment by UltimateByte** [comment]
Well I SSHed with my phone, no issue with an updated lgsm. 
Will try installing a fresh Gmod server still with the phone. :o)))

**Comment by FlashModz** [comment]
Ok x) good Luck :p

**Comment by UltimateByte** [comment]
Well except that some port was already used since I don't have my server excel handy, logs were fine. So distro issue ? I see no obvious reason for this to happen, maybe your tmux took some pot or something.

**Comment by FlashModz** [comment]
Purge and reinstall tmux not solved the problems :/

**Comment by FlashModz** [comment]
Error Postfix is possible ?

E: Package 'postfix' has no installation candidate

**Comment by FlashModz** [comment]
Package : 

curl est déjà la plus récente version disponible.
tmux est déjà la plus récente version disponible.
gzip est déjà la plus récente version disponible.
lib32tinfo5 est déjà la plus récente version disponible.
file est déjà la plus récente version disponible.
bzip2 est déjà la plus récente version disponible.
wget est déjà la plus récente version disponible.
libstdc++6 est déjà la plus récente version disponible.
libstdc++6:i386 est déjà la plus récente version disponible.
bsdmainutils est déjà la plus récente version disponible.
python est déjà la plus récente version disponible.
util-linux est déjà la plus récente version disponible.
lib32gcc1 est déjà la plus récente version disponible.
Le paquet suivant a été installé automatiquement et n'est plus nécessaire :
  python-support
Veuillez utiliser « apt-get autoremove » pour le supprimer.

**Comment by FlashModz** [comment]
Yes :)

deb-src http://httpredir.debian.org/debian/ jessie main
# Debian Jessie, dépôt principal
deb http://security.debian.org/ jessie/updates main
# Debian Jessie, mises-à-jour "volatiles"
deb http://httpredir.debian.org/debian/ jessie-updates main
# Debian Jessie, dépôt de rétroportages ("backports")
deb http://httpredir.debian.org/debian jessie-backports main
deb [arch=amd64,i386] http://mariadb.cu.be/repo/10.1/debian jessie main
# deb-src [arch=amd64,i386] http://mariadb.cu.be/repo/10.1/debian jessie main

**Comment by UltimateByte** [comment]
Mine for comparison
```
terageek@webserver:~/public_html/wp-includes$ cat /etc/apt/sources.list
#deb http://debian.mirrors.ovh.net/debian/ jessie main
#deb-src http://debian.mirrors.ovh.net/debian/ jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb http://debian.mirrors.ovh.net/debian/ jessie-updates main
deb-src http://debian.mirrors.ovh.net/debian/ jessie-updates main

# jessie-backports, previously on backports.debian.org
deb http://debian.mirrors.ovh.net/debian/ jessie-backports main
deb-src http://debian.mirrors.ovh.net/debian/ jessie-backports main

deb http://debian.mirrors.ovh.net/debian/ jessie main contrib non-free
deb-src http://debian.mirrors.ovh.net/debian/ jessie main contrib non-free


# Webmin
deb http://download.webmin.com/download/repository sarge contrib

```

**Comment by UltimateByte** [comment]
Fixed with proper repos.
Debian 8 is supposed to be tmux 1.9, not 2.3.
