### ISSUE TITLE
Error installing Arma 3 server

### ISSUE THREAD

**Issue by yololetsplay** [GameServerManagers/LinuxGSM#1135]
Hey there :]

I get the following issue if I try to install arma3server using your script.

[arma3_error.txt](https://github.com/GameServerManagers/LinuxGSM/files/539616/arma3_error.txt)

Please help me :]

Greetz,
yololetsplay

**Comment by yololetsplay** [comment]
Well, the script doesn't aborted working....it still do something.
I'll update this asap.

**Comment by yololetsplay** [comment]
Well, it finally installed everything, it was my bad.

**Comment by UltimateByte** [comment]
And according to your logs, you just had to wait.
