### ISSUE TITLE
cached is now missing in details

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1143]
It looks like the free command has changed as the cached option is now missing. I am not sure why this is. 
```
Mem:       total   used   free   cached
Physical:  992M    492M   100M
Swap:      0B      0B     0B
```

A typical output of free -h now read like so

```
lgsm@ubuntu-1604-lgsm-dev:~/ns2server$ free -h
              total        used        free      shared  buff/cache   available
Mem:           992M        490M         96M        3.1M        405M        344M
Swap:            0B          0B          0B
```

I can simply remove the cached option or look at adding the buff/cache and available option

**Comment by UltimateByte** [comment]
Got the right output with Debian.
Need to find out an universal way.

```
Mem:       total   used   free     cached
Physical:  31G     29G    1.7G     19G
Swap:      1.0G    292M   729M
```

**Comment by dgibbs64** [comment]
fixed by @UltimateByte

**Comment by UltimateByte** [comment]
@dgibbs64 Without a merge it's not fixed :)

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/1144
