### ISSUE TITLE
[RUST] Bad Git repo address after running rustserver update-functions?

### ISSUE THREAD

**Issue by gleepwurp** [GameServerManagers/LinuxGSM#1148]
Hi,

ran runserver update-functions yesterday, and it seems to have change the URL to download any future files afterwards it tries to pull code from this github repo that doesn't seem to exist:

https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/core_functions.sh

Execution log below:

rustserver@rustsrv:~$ ./rustserver update-functions
[ .... ] Update LGSM rust-server: Updating functions
removed '/home/rustserver/functions/core_functions.sh'
removed directory: '/home/rustserver/functions/'
    checking alert.sh...OK
    checking check.sh...UPDATE
    fetching check.sh...OK
    checking check_config.sh...OK
    checking check_deps.sh...OK
    checking check_glibc.sh...OK
    checking check_ip.sh...UPDATE
    fetching check_ip.sh...OK
    checking check_logs.sh...OK
    checking check_permissions.sh...UPDATE
    fetching check_permissions.sh...OK
    checking check_root.sh...OK
    checking check_status.sh...UPDATE
    fetching check_status.sh...OK
    checking check_steamcmd.sh...OK
    checking check_system_dir.sh...OK
    checking check_system_requirements.sh...UPDATE
    fetching check_system_requirements.sh...OK
    checking command_console.sh...OK
    checking command_details.sh...UPDATE
    fetching command_details.sh...OK
    checking command_monitor.sh...OK
    checking command_restart.sh...OK
    checking command_start.sh...OK
    checking command_stop.sh...UPDATE
    fetching command_stop.sh...OK
    checking command_update.sh...OK
    checking command_update_functions.sh...OK
    checking core_dl.sh...OK
    checking core_exit.sh...OK
    checking core_functions.sh...UPDATE
    fetching core_functions.sh...OK
    checking core_getopt.sh...UPDATE
    fetching core_getopt.sh...OK
    checking core_messages.sh...OK
    checking core_trap.sh...OK
    checking fix.sh...OK
    checking fix_glibc.sh...OK
    checking fix_steamcmd.sh...OK
    checking gsquery.py...OK
    checking info_config.sh...UPDATE
    fetching info_config.sh...OK
    checking info_distro.sh...OK
    checking info_glibc.sh...UPDATE
    fetching info_glibc.sh...OK
    checking info_parms.sh...UPDATE
    fetching info_parms.sh...OK
    checking logs.sh...UPDATE
    fetching logs.sh...OK
    checking monitor_gsquery.sh...OK
    checking update_steamcmd.sh...OK
[  OK  ] Update LGSM rust-server: Updating functions

**The error that begins afterwards:**

rustserver@rustsrv:~$ ./rustserver update  
    fetching functions/core_functions.sh...FAIL

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/core_functions.sh

rustserver@rustsrv:~$ 

Thanks!

G.

**Comment by dgibbs64** [comment]
there was a ddos attack yesterday. might be related

**Comment by gleepwurp** [comment]
Hmm, I'm getting to the website ok, doesn't find the gdibbs64 folder, or user for that matter, and they say the DNS matter was resolved 15 hours ago, according to the https://www.dynstatus.com/incidents/nlr4yrr162t8 status page...  

I'll wait for a bit longer and give it another go...  

Thx!

G.

**Comment by UltimateByte** [comment]
It would be a good idea to use the new rustserver script though. 
You can remove the lgsm/functions folder as well if some of your functions are broken or something, since it will be downloaded again automatically.

**Comment by gleepwurp** [comment]
Hi,

Downloaded new version of the rustserver script and deleted the old functions directory as you suggested, and everything works fine now... It's not using the "gdibbs64" github directory but the "https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/" github instead... 

My version was probably too old and pointing to an older repo.

Thanks for all the help, looks good now!

G.

**Comment by UltimateByte** [comment]
Actually dgibbs64 github should point to LinuxGSM, it's kindov a mirror, unless the mirror doesn't work anymore, or currently beacause github is in a pain, which might explain your issue. Other issue could be that your repo is gdibbs64 instead of dgibbs64 :p

**Comment by gleepwurp** [comment]
hehe, sorry, dyslexia poking through my typing... :)  

Probably the mirroring not working with the issues caused by the DDoS yesterday, like you said..

G.
