### ISSUE TITLE
7 Days to Die Config issues

### ISSUE THREAD

**Issue by killerty69** [GameServerManagers/LinuxGSM#1150]
Config is missing this at the end of the file
```xml
</ServerSettings>
```

Friendlyfire option needs to be removed and replaced with new A15 version

```xml
<property name="PlayerKillingMode" value="3" />
<- Player Killing Settings (0 = No Killing, 1 = Kill Allies Only, 2 = Kill Strangers Only, 3 = Kill Everyone) -->
```

**Comment by killerty69** [comment]
I went ahead and submitted a pull request on the config repo so this can be closed whenever that is merged.

**Comment by UltimateByte** [comment]
Hey, there, your fixes has been merged, thanks for your contribution :)
