### ISSUE TITLE
Issue with emailfrom

### ISSUE THREAD

**Issue by Technoblazed** [GameServerManagers/LinuxGSM#1152]
I've been using LGSM for a while as well as the newly introduced emailfrom without any issues, however over the last few days I've been getting an error when sending emails with the emailfrom field. 

```
csgo@ca-dedi:~/surf-testing$ ./csgoserver test-alert
[ .... ] Alert csgo-server: Sending alert: mypersonalemail@gmail.com From: test@mysendingdomain.ext: No such file or directory
[ FAIL ] Alert csgo-server: Sending alert: mypersonalemail@gmail.com
[ WARN ] Alert csgo-server: Pushbullet alerts not enabled
csgo@ca-dedi:~/surf-testing$
```

I've tried finding what's causing the issue, but have no idea. Any clues?

EDIT: Also, it is not mail server related, it works fine without the emailfrom variable set.

**Comment by Technoblazed** [comment]
Having looked into this further, Line 234 in alert_email.sh currently reads:

```
mail -s "${alertsubject}" -a "From: ${emailfrom}" "${email}" < "${emaillog}"
```

`-a` is no longer the correct method for my OS - Ubuntu 16.04. This `-a` is used for attachments. Not sure if this is the same on other distros, but the correct format should now be:

```
mail -s "${alertsubject}" -r "${emailfrom}" "${email}" < "${emaillog}"
```

**Comment by UltimateByte** [comment]
Hi,
Thanks for reporting.

Here is my --help output on Debian. 
http://hastebin.com/subizucezo.sql

Can you please post yours on Ubuntu 16.04 ?

**Comment by Technoblazed** [comment]
```
csgo@ca-dedi:~$ mail --help
 Synopsis:
  mail -h | --help
  mail [-BDdEFintv~] [-A account]
         [-a attachment] [-b bcc-address] [-c cc-address]
         [-q file] [-r from-address] [-S var[=value]...]
         [-s subject] [-X cmd] [-.] to-address... [-- mta-option...]
  mail [-BDdEeHiNnRv~#] [-A account]
         [-L spec-list] [-r from-address] [-S var[=value]...]
         [-X cmd] -f [file] [-- mta-option...]
  mail [-BDdEeHiNnRv~#] [-A account]
         [-L spec-list] [-r from-address] [-S var[=value]...]
         [-u user] [-X cmd] [-- mta-option...]
csgo@ca-dedi:~$
```

**Comment by UltimateByte** [comment]
Ubuntu... Come on !

Can you please post the output of `dpkg-query -l '*' | grep mail` so that i can see what mail senders you got ?

**Comment by Technoblazed** [comment]
http://hastebin.com/ocezowayeq.swift

**Comment by UltimateByte** [comment]
You're pretty fast. :)
Here is mine on Debian 8 for comparison. 
http://hastebin.com/wufuyirawa.swift

Maybe install mailx ?

**Comment by Technoblazed** [comment]
I already have mailx ._.

**Comment by UltimateByte** [comment]
I'm not sure, emails are still kinda mystic to me, just trying to see if it's a user issue rather than GSM/Distro one. @dgibbs64 @cedarlug might know more than i do about it. :)
Seems to me like mailx isn't installed:   
`un  mailx                             <none>                            <none>       (no description available)`

`-r `wouldn't work on Debian though, so a more universal solution would be great.
Gotta go, catch you later on that (in 5-6 hours or so).

**Comment by Technoblazed** [comment]
```
mailx available at /usr/bin/mailx
```

And later :D

**Comment by UltimateByte** [comment]
Ubuntu... Brrrr ! I guess i'm becoming a Debian elitist !
Feel free to try stuff other than -r, you got my Debian --help output, if we cannot find a solution, we're gonna have to use a conditional check to send the mail :) Cya !

**Comment by cedarlug** [comment]
Could you both (@UltimateByte & @Technoblazed) post the results of:
```bash
which sendmail
ls -l $(which sendmail)
readlink -f $(which sendmail)
grep $(readlink -f $(which sendmail) ) /var/lib/dpkg/info/*.list
```
In almost every distribution, the real mail program is a symlink to sendmail.  And when invoked as sendmail, adheres to the sendmail syntax regardless of what it really is (exim4, mailx, ...).

My take would be that if you convert the mail command to the sendmail equivalent and invoke sendmail to send your message, it will work on almost every platform.

**Comment by Technoblazed** [comment]
`readlink -f $(which sendmail)` was incorrect, following output below:

```
csgo@ca-dedi:~$ which sendmail
csgo@ca-dedi:~$ ls -l $(which sendmail)
total 16
-rw-r--r-- 1 csgo csgo 5451 Oct 24 14:33 maps.txt
drwxrwxr-x 8 csgo csgo 4096 Oct 24 15:21 Steam
drwxrwxr-x 6 csgo csgo 4096 Oct 24 15:13 surf-testing
csgo@ca-dedi:~$ readlink -f $which sendmail
/home/drive-2/csgo/sendmail
csgo@ca-dedi:~$ grep $(readlink -f $which sendmail ) /var/lib/dpkg/info/*.list
csgo@ca-dedi:~$
```

**Comment by cedarlug** [comment]
There goes my theory.

**Comment by Technoblazed** [comment]
I know it works on 16.04 using the current method. Something must have changed in 16.10 though :/

**Comment by UltimateByte** [comment]
@cedarlug Output not very relevant for me 

```
csgoserver@webserver:~$ which sendmail
csgoserver@webserver:~$ ls -l $(which sendmail)
total 52
-rwxr-xr-x 1 csgoserver csgoserver 5174 Oct 24 01:16 csgo-classic-casu
-rwxr-xr-x 1 csgoserver csgoserver 5188 Oct  7 03:21 csgo-competitive
-rwxr-xr-x 1 csgoserver csgoserver 5191 Oct  7 03:23 csgo-deathmatch
-rwxr-xr-x 1 csgoserver csgoserver 5193 Oct  7 03:23 csgo-demolition
drwxr-xr-x 4 csgoserver csgoserver 4096 Oct 24 00:46 lgsm
drwxr-xr-x 4 csgoserver csgoserver 4096 Oct  7 00:56 log
drwxr-xr-x 7 csgoserver csgoserver 4096 Oct  7 15:20 serverfiles
drwxr-xr-x 8 csgoserver csgoserver 4096 Oct 25 02:01 Steam
drwxr-xr-x 5 csgoserver csgoserver 4096 Oct 25 02:00 steamcmd
csgoserver@webserver:~$ readlink -f $(which sendmail)
readlink: missing operand
Try 'readlink --help' for more information.
csgoserver@webserver:~$ readlink -f $which sendmail
/home/csgoserver/sendmail
csgoserver@webserver:~$ grep $(readlink -f $(which sendmail) ) /var/lib/dpkg/info/*.list
readlink: missing operand
Try 'readlink --help' for more information.
```

**Comment by UltimateByte** [comment]
So any key to make this more universal ?

**Comment by JimTR** [comment]
the command (ran from the base directory e.g cd /) as root only returns -
``root@vps99696888:/# ls -l $(which sendmail)
-rwxr-xr-x 1 root root 26648 Apr 13  2016 /usr/sbin/sendmail
root@vps99696888:/# ``

the read link command also returns the same, just wondering how you manage to get 52 results back ?

**Comment by Technoblazed** [comment]
@JimTR We ran in game directories, not root.

**Comment by JimTR** [comment]
Ok I don't understand I have also ran the same command as a user same result ... I am wondering why you have so many entries ?

**Comment by Technoblazed** [comment]
Not certain, but it's irrelevant none the less.

**Comment by cedarlug** [comment]
@JimTR Their results are just the directory entries, because `$(which sendmail)` returns empty.  As a result, they're just getting the output of `ls -l`for the current directly.

A system lacking a symlink to sendmail wasn't at all what I expected for a modern Linux deployment.

**Comment by UltimateByte** [comment]
Makes sense now, but doesn't solve the actual issue !

**Comment by dgibbs64** [comment]
I can confirm that -r works on some distros and doesnt on others. However i believe that -r is probably more common. I will update the email from to use -r instead.
