### ISSUE TITLE
LGSM recently blocks nested sessions

### ISSUE THREAD

**Issue by CasperAlant** [GameServerManagers/LinuxGSM#1154]
I run multiple LGSM servers on the same machine. I create a tmux session for each user and login with that user account and run LGSM as a nested session.

I've been doing this for more than a year now and it has worked flawlessly. I installed a new server on 2016-10-13 with no problem. When I did the same today, I got the following errors: 

[ FAIL ] Install csgo-server: tmuxception error: Sorry Cobb you cannot start a tmux session inside of a screen session.
Information! LGSM creates a tmux session when starting the server.

Tmux allows nested sessions.

**Comment by CasperAlant** [comment]
I bypassed the error by commenting out the following lines in ~/lgsm/functions/check_tmuxception.sh:
fn_check_is_in_tmux
fn_check_is_in_screen

**Comment by dgibbs64** [comment]
How are you running LGSM within a tmux session? Unless you are only using debug mode

**Comment by CasperAlant** [comment]
1. I ssh and login to my machine with my admin account.
2. I create a tmux session.
3. In the tmux session, I login with one of the LGSM user accounts I created.
4. I run LGSM like normal (./csgoserver *command*). No debug mode.

The only funny part is when I run ./csgoserver console, the server console is a nested tmux session. So you need to double Ctrl+B to control the inner session.

**Comment by UltimateByte** [comment]
How come does it even work ? Other people got errors all around. What's the point of nesting tmux sessions ?

**Comment by CasperAlant** [comment]
I've never received any errors doing this. The only problem I can recall is to give LGSM user accounts permission to usermod -a -G tty *user*.

My reason for doing this is so that I don't need to login to the LGSM user account every time I want to change or do something on a server.

I have an open tmux session for every server like this:
casper@***host-machine***:~$ tmux list-sessions
csgo_prac_server_1: 1 windows (created Tue Oct 25 06:53:32 2016) [204x61]
csgo_server_1: 1 windows (created Tue Oct 11 06:26:34 2016) [204x61]
csgo_server_2: 1 windows (created Tue Oct 11 06:39:57 2016) [204x61]
csgo_server_3: 1 windows (created Tue Oct 11 06:41:49 2016) [204x61]
csgo_server_4: 1 windows (created Tue Oct 11 06:43:03 2016) [204x61]
csgo_server_5: 1 windows (created Tue Oct 11 06:44:31 2016) [204x61]
csgo_server_6: 1 windows (created Tue Oct 11 06:45:33 2016) [204x61]
csgo_server_7: 1 windows (created Tue Oct 11 06:55:44 2016) [204x61]
csgo_server_8: 1 windows (created Tue Oct 11 06:56:50 2016) [204x61]

Each of the sessions is logged into a user account with the same name. Those user accounts are my LGSM accounts, each running a game server.

I'm running Ubuntu Server 15.10 with tmux 2.0.

**Comment by UltimateByte** [comment]
Well, issues happen with tmux < 2.0 for sure, debian 8 for example uses tmux 1.9 and this fails. 

Here is for example the output people will usually got when trying to nest tmux sessions together:

```
ultimatebyte@game:~$ ./gmodserver start
[ INFO ] Starting gmod-server: Steam login not set. Using anonymous login.
session not found: gmod-server
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "gmod-server" "./srcds_run -game garrysmod -strictportbind -ip 164.132.201.49 -port 27015 -tickrate 66 +host_workshop_collection  -authkey  +clientport 27005 +tv_port 27020 +gamemode sandbox +map gm_construct +sv_setsteamaccount  +servercfgfile gmod-server.cfg -maxplayers 16 +r_hunkalloclightmaps 0"

Error
=================================
sessions should be nested with care, unset $TMUX to force

Fix
=================================
ultimatebyte is not part of the tty group.

        tty:x:5:

Run the following command with root privileges.

        usermod -G tty ultimatebyte

https://gameservermanagers.com/tmux-op-perm
```

So i'm personally OK to allow tmux inside tmux (even if i think it's incredibly stupid) if we can find the condition that determines if it will work or not. My guess is that it's not as simple as checking tmux version, but i could be wrong.

**Comment by cedarlug** [comment]
I believe the distinction here is that we want to prevent the end-user of lgsm from running tmux inside of tmux.

But what @CasperAlant wants to do is to run tmux as the super-lgsm user where he then su's to the actual lgsm end-user.

So if the the TMUX environment is set, but the tmux pts isn't owned by the current user (owned by lgsm instead of csgoserver, for example), then allow it?

**Comment by CasperAlant** [comment]
Yes, @cedarlug, that is how I run my lgsm servers.

I just did a test where I logged in as a LGSM user, started a tmux session as that user and ran *./csgoserver start*. In this case, it does indeed throw an error as @UltimateByte described:
```
[  OK  ] Console csgo-server: Starting
sessions should be nested with care, unset $TMUX to force
```

**Comment by cedarlug** [comment]
@CasperAlant - do you `sudo su csgo_server_1` or ???

You shouldn't have any errors if you included the dash: `sudo su - csgo_server_1` and then start the game as usual.

How do you switch to your sub accounts?

**Comment by dgibbs64** [comment]
@CasperAlant It would be a good idea if you could work with us to ensure that we can still prevent users from starting LGSM within a tmux session but still being able to achieve your goal. Since @cedarlug appears to know what you need to do it would be great if you guys could collaborate on this and put forward a fix for this. I'm am happy to accept a pull requests for this issue

**Comment by UltimateByte** [comment]
Well in your case it's not a stupid usage at all but rather a controlled and clever way, so don't take account for what i said before.
So @CasperAlant @cedarlug feel free to pull request (to devbranch) needed changes so that this usage is allowed.
https://github.com/GameServerManagers/LinuxGSM/blob/development/lgsm/functions/check_tmuxception.sh

**Comment by CasperAlant** [comment]
I log in using `su` as you described. With or without the dash, ${TERM} is still set to "screen" which caused *fn_check_is_in_screen* to trigger. The last commit I made allows checking for a screen session without this issue.

**Comment by UltimateByte** [comment]
This has been merged to master. Please re-open if it's not fixed, but should be fine;
