### ISSUE TITLE
CentOS 6.5 Tmux Issues

### ISSUE THREAD

**Issue by alperkavak** [GameServerManagers/LinuxGSM#1155]
Okay, so, hey, I am having some issues by installing the CS 1.6 server on CentOS 6.5 32-Bit (Web Server) using this guide: https://gameservermanagers.com/lgsm/csserver/

Problem is tmux can't be installed. As in, it says it is installing missing dependencies, and fails to do so. And tells me to log an issue. Any ideas?

**Comment by UltimateByte** [comment]
Hey there,

Non-script issue obviously, so please use Discord or Steam group for this kind of issues, providing enough info, and we'll be glad to help.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
