### ISSUE TITLE
Ark Server query

### ISSUE THREAD

**Issue by hirsty** [GameServerManagers/LinuxGSM#1159]
Maybe use arkmanager to sort of sub manage the ark server?

**Comment by UltimateByte** [comment]
Maybe hello.
Maybe no because it doesn't fit lgsm behavior currently and we got other ideas for multiple servers.
Maybe we're not on twitter and you can write more than one line to express an idea.

**Comment by hirsty** [comment]
My apologies :) No need to be cocky - was just a quick thought - i guess "quick" feedback isnt appreciated. Thinking of moving to LGSM, currently using arkmanager but planning to go multiserver - how is the cron  job ast handling updates? does it warn players? but now hey - we are going beyond the needs for this card, i guess im going to get a slap on the wrist for that too

**Comment by dgibbs64** [comment]
This is how LGSM works currently https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Servers

This is how others setup there servers. So it might work for you :)

**Comment by UltimateByte** [comment]
My answer was short as well, i wasn't home. What bothered me a bit was the lack of link between server query and what you asked, combined with a small comment with no courtesy, was a bit too much. This issue wasn't a "quick feedback" but rather an unhelpful post. I think posting a one liner issue on a script that you seem to not be using while obviously not having read the documentation is quite prompt to "cocky" answers.

If what you wanna do is just multiple servers, then this is easy and handled by LGSM and the link provided will help.
If you need more, we'll be happy to examine your suggestions as long as they are just a bit elaborated.
