### ISSUE TITLE
Support for ETLegacy

### ISSUE THREAD

**Issue by MattiGB** [GameServerManagers/LinuxGSM#1164]
Hi,
as I mentioned on DISCORD, it would be great if you add support for ETLegacy.
More info about this project: https://www.etlegacy.com/

ETLegacy brings a lot of fixes in Enemy Territory. It's still in development.

**Comment by dgibbs64** [comment]
I think the best way to implement this would be as its own server. It should jut be a case of copying Enemy Territory everything ET: Legacy and changing the download.

**Comment by dgibbs64** [comment]
https://dev.etlegacy.com/boards/1/topics/2935

**Comment by dgibbs64** [comment]
Looking at how the installation works a mod might actually be the best fit @UltimateByte  what do you think?

**Comment by UltimateByte** [comment]
Well, mods-install can easily install any zip files, so as long as it's a link to the latest zip, support ils just a line un mods_list.sh. Might require some modifications for updates though since it seems to be done through a server console command.

**Comment by dgibbs64** [comment]
@UltimateByte the issue I saw is that the files are not stored on the top level but in a directory. Worse case is that I would re crease the archive with the files in the top level....but if I get details of the auto updater it wont really matter.

**Comment by UltimateByte** [comment]
Not sure how it looks like, do you have a link of the zip with instructions on how to use it?

Anyhow...
![unix_desktop_1440x900_wallpaper-331531](https://user-images.githubusercontent.com/8805941/37623927-ae410ef8-2bc6-11e8-87b1-ac02a9f287d1.jpg)

**Comment by dgibbs64** [comment]
https://dev.etlegacy.com/boards/2/topics/3362

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/commit/a1f2c7d56f9186b8bea9140f90df17ec116d1bac ready for release
