### ISSUE TITLE
[ FAIL ] Starting jc2-server: Unable to start

### ISSUE THREAD

**Issue by NiKunHax** [GameServerManagers/LinuxGSM#1166]
I try to start my JC2Server and he say:
[ .... ] Starting jc2-server: no server running on /tmp/tmux-1001/default
[ FAIL ] Starting jc2-server: Unable to start Minelost Network - JC2MP

Linux: Debian 8

Please, Help Me

**Comment by NiKunHax** [comment]
If i do Debug he say: [ INFO ] Debug jc2-server: Stopping any running servers
[ INFO ] Stopping jc2-server: Minelost Network - JC2MP is already stopped
[  OK  ] Debug jc2-server: Starting debug
/home/jc2server/lgsm/functions/command_debug.sh: line 106: ./Jcmp-Server: No such file or directory
jc2server@HoneyHosting:~$

**Comment by UltimateByte** [comment]
Hi,
I personally don't know much about jc2. 

Is your lgsm script up to date ?
append ./gameserver uf (replace "gameserver with your actual script)

**Comment by JimTR** [comment]
line 106 runs ``${executable} ${parms}`` 
you may notice that the start script is jc2-server and debug is trying to run **Jcmp-Server** surly this should be jc2-server ?

**Comment by dgibbs64** [comment]
Looks to me like the server has not downloaded correctly. So I think its a failed install. I use JC2 all the time for testing.

**Comment by NiKunHax** [comment]
All Updated. i have founded the error 
=================================
mkdir: cannot create directory '/home/jc2server/log': File exists
mkdir: cannot create directory '/home/jc2server/log/script': File exists
mkdir: cannot create directory '/home/jc2server/log/console': File exists

Checking Dependencies
=================================
tmux
wget
ca-certificates
file
bsdmainutils
util-linux
python
bzip2
gzip
lib32gcc1
libstdc++6:i386

Installing SteamCMD
=================================
Information! SteamCMD is already installed...OK

Installing Just Cause 2 Server
=================================
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Redirecting stderr to '/home/jc2server/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --

Now the istallation stop and i click ctrl + c to exit or putty crash.

**Comment by UltimateByte** [comment]
@dgibbs64 It appears that this one requires steam login.
Maybe probably owning the game on the steam account:
"section_type	ownersonly"
https://steamdb.info/app/261140/

I got it removed since it appeared as

```
# Steam login
steamuser="anonymous"
steampass=""
```

@NiKunHax do you have a "No subscription" error at some point ?

**Comment by dgibbs64** [comment]
Just tested a fresh install with no issues. I recommend doing a fresh install and trying again.

**Comment by UltimateByte** [comment]
So no steam login required ? Fine.

**Comment by NiKunHax** [comment]
i have reinstalled that 5 times.  if i write Steam login, quit or ever word it don't found. please send me a server pre-installed or help me with installing.

**Comment by NiKunHax** [comment]
i have this error when i install: ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

is normal?

**Comment by UltimateByte** [comment]
LD_PRELOAD message is a non-issue, just an info. This message will disappear on next merge from develop branch to master.
When we say "reinstall", it means: remove anything from your user folder. Which isn't the case on your previous post, otherwise you wouldn't have messages as: "mkdir: cannot create directory '/home/jc2server/log': File exists".

**Comment by UltimateByte** [comment]
BTW, i just realized that jc2server is the one used for all travis-ci tests, so if it didn't work we'd know. 
For now i assume it's a non-script issue.

**Comment by UltimateByte** [comment]
No feedback.
