### ISSUE TITLE
Starting gmod-server: Unable to start LinuxGSM [GMOD Server don't want to start

### ISSUE THREAD

**Issue by BestOfFoxy** [GameServerManagers/LinuxGSM#1173]
Hello, i have problem with the gmod server that i installed. I use the future from GamerServerManagers today and i can't start the gmod server , Error Code : Starting gmod-server: Unable to start LinuxGSM.

I hope someone can help me.

P.S sry for my bad english , i coming from germany

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
