### ISSUE TITLE
Rust Modded make

### ISSUE THREAD

**Issue by testler2** [GameServerManagers/LinuxGSM#1174]
Hi, How can I make rust modded server?
Server Linux ubuntu 14 64 bit

**Comment by UltimateByte** [comment]
Hi. Please use github for bug report and feature request only. Also, please use your eyes and available documentation.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support#documentation
https://github.com/GameServerManagers/LinuxGSM/wiki/Rust
