### ISSUE TITLE
Server is not online

### ISSUE THREAD

**Issue by fpaschuini** [GameServerManagers/LinuxGSM#1175]
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.

Unhandled Exception: System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.AssetBundle:Unload (bool)
  at FileSystem_AssetBundles.Finalize () [0x00000] in <filename unknown>:0 
Unity Technologies
AudioManager: Using Unknown: NoSound Driver
Begin MonoManager ReloadAssembly
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.West.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/I18N.West.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/LZ4n.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/LZ4n.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/RustBuild.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/RustBuild.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll into Unity Child Domain
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll (this message is harmless)
Loading /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll into Unity Child Domain
- Completed reload, in  0.051 seconds
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.dll (this message is harmless)
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Core.dll (this message is harmless)
OnLevelWasLoaded was found on LeanTween
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 375)

UnloadTime: 2.370000 ms
System
	Name: ubuntu
	OS:   Linux 4.8 Ubuntu 16.04 64bit

CPU
	Model:  Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
	Cores:  6
	Memory: 12012 MB

GPU
	Model:  Null Device
	API:    NULL 1.0 [1.0]
	Memory: 128 MB
	SM:     30

Memory
	Private:     0 MB
	Working Set: 0 MB

Process
	Priority: 0
	Threads:  0
	Memory:   74 MB
	Peak:     76 MB

Mono
	Collects: 4
	Memory:   0 MB

 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/Mono.Security.dll (this message is harmless)
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Configuration.dll (this message is harmless)
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Xml.dll (this message is harmless)
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Runtime.Serialization.dll (this message is harmless)
Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Xml.Linq.dll (this message is harmless)
server.ip: "45.79.223.204"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.hostname: "Rust"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.seed: "1222"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.worldsize: "3500"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.ip: "45.79.223.204"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.port: "28016"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.password: "123456654321"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Command Line: "./RustDedicated" "-batchmode" "+server.ip" "45.79.223.204" "+server.port" "28015" "+server.tickrate" "30" "+server.hostname" "Rust" "+server.identity" "rust-server" "+server.seed" "1222" "+server.maxplayers" "50" "+server.worldsize" "3500" "+server.saveinterval" "300" "+rcon.ip" "45.79.223.204" "+rcon.port" "28016" "+rcon.password" "******" "-logfile" "gamelog-2016-11-05-02-04-24.log" 
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.ip: "45.79.223.204"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.hostname: "Rust"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.seed: "1222"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.worldsize: "3500"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.ip: "45.79.223.204"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.port: "28016"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.password: "123456654321"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Server Config Loaded
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
Unloading 5 Unused Serialized files (Serialized files now loaded: 70)
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
UnloadTime: 8.559000 ms
Generating terrain of size 3500 with seed 1222
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Floating point textures aren't supported on this device (Main Camera (UnityStandardAssets.CinematicEffects.TonemappingColorGrading))
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[AmplifyOcclusion] Null graphics device detected. Skipping effect silently.
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Unloading 7444 unused Assets to reduce memory usage. Loaded Objects now: 8224.
Total: 140.297989 ms (FindLiveObjects: 1.281000 ms CreateObjectMapping: 1.695000 ms MarkObjects: 11.802000 ms  DeleteObjects: 125.517998 ms)

The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

RCon Started on 28016
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[8.1s] HEIGHT MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[2.7s] MOUNTAINS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.4s] BIOME MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[2.2s] TOPOLOGY MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.7s] SPLAT MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
[10.4s] LARGE MONUMENTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[1.2s] MEDIUM MONUMENTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[1.6s] SMALL MONUMENTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[6.8s] RIVER LAYOUT
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.5s] RIVER OBJECTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[8.2s] ROAD LAYOUT
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[2.0s] ROAD OBJECTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.6s] POWERLINE LAYOUT
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[1.1s] POWERLINE OBJECTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.6s] FIELD ROCKS 1/2
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.7s] FOREST ROCKS 1/2
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.7s] FOREST ROCKS 2/2
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.3s] CLIFFS 1/2
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[1.8s] MICRO CLIFFS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.3s] LIGHTHOUSES
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.3s] FORMATION ROCKS 1/2
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[9.2s] TERRAIN MESH
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.8s] CLIFF SPLAT
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[2.6s] PROCEDURAL OBJECTS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.9s] CLIFF TOPOLOGY
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[66.6s] Procedural Generation
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Loaded database server/rust-server/user5.db ( 0 entries)
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Couldn't load server/rust-server/proceduralmap.3500.1222.138.sav - file doesn't exist
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain Blend (Specular setup)' - All passes removed
AngryAnt Behave version 2.5 (d859964) - Copyright (C) Emil Johansen - AngryAnt 2015
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Map Spawned 14670 entities
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Missing EnvSync - creating
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Initializing 14691 entity links
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Initializing 99 stability supports
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Fallback handler could not load library /home/rustserver/rust/serverfiles/RustDedicated_Data/Mono/x86_64/libsteam_api64.so
Fallback handler could not load library /home/rustserver/rust/serverfiles/RustDedicated_Data/Mono/x86_64/libsteam_api64.so
Couldn't initialize Steam Server (760209356)
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Server startup complete
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Platform assembly: /home/rustserver/rust/serverfiles/RustDedicated_Data/Managed/System.Data.dll (this message is harmless)
NullReferenceException: Object reference not set to an instance of an object
  at ServerMgr+<UpdateInventoryFromSchema>c__Iterator1E.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 7fab423a4700 -> priority: 1 
EasyAntiCheat Shutting Down
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[Raknet] Server Shutting Down (Shutting Down)
Steamworks Shutting Down
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

NullReferenceException: Object reference not set to an instance of an object
  at ServerMgr.OnDisable () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by MelvynSaytek** [comment]
I have the same problem !

**Comment by UltimateByte** [comment]
Well, i got issues with your issue:

- User doesn't know how to talk
- User don't know how to use pastebin or hastebin
- User is not polite or whatsoever and makes me feel like i'm his dog or something
- User didn't read wiki: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
- User didn't bother reading latest issues (this current one i'm posting on might be just another duplicate) https://github.com/GameServerManagers/LinuxGSM/issues/1171
- This issue is helpess with no more details
- Diagnosing listening issues: https://github.com/GameServerManagers/LinuxGSM/wiki/Ports#diagnosing-server-accessibility
- If it's not an LGSM issue it has nothing to do on github, but you'd rather use our Discord or our Steam Group given in /Support wiki page & here  https://gameservermanagers.com/support/
