### ISSUE TITLE
Steamclient.so

### ISSUE THREAD

**Issue by melvinlemoine** [GameServerManagers/LinuxGSM#1176]
Hello,

My Rust server can't start and the log say us : 

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
eac_server.so [x64] :: OnLoad()

Unhandled Exception: System.NullReferenceException: 
  at (wrapper managed-to-native) UnityEngine.AssetBundle:Unload (bool)
  at FileSystem_AssetBundles.Finalize () [0x00000] in <filename unknown>:0 
1faee5ea97)
Forcing GfxDevice: Null
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
AudioManager: Using Unknown: NoSound Driver
Begin MonoManager ReloadAssembly
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.West.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/I18N.West.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/LZ4n.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/LZ4n.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/RustBuild.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/RustBuild.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll into Unity Child Domain
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll (this message is harmless)
Loading /home/apocalypse/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll into Unity Child Domain
- Completed reload, in  0.053 seconds
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/System.dll (this message is harmless)
Platform assembly: /home/apocalypse/serverfiles/RustDedicated_Data/Managed/System.Core.dll (this message is harmless)
OnLevelWasLoaded was found on LeanTween
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed

**Comment by UltimateByte** [comment]
Hi,

Please see this: https://github.com/GameServerManagers/LinuxGSM/issues/1171
Chances are your issue is exactly the same. And please use this 1171 issue for Rust issues due to the latest crappy game update. Ultimately, blame facepunch.

**Comment by MelvynSaytek** [comment]
Thank you
