### ISSUE TITLE
TS3Server - code to using teamspeak.gameserver.gamed.de

### ISSUE THREAD

**Issue by Titou74** [GameServerManagers/LinuxGSM#1180]
Hello,
I tried to install TS3 Server on my VPS, but I realized that my host is blacklisted by 4players.de ... so I edit "update_ts3.sh" to use "teamspeak.gameserver.gamed.de" mirror.

What change ?
- Link : from "http://dl.4players.de/ts/releases/" to "http://teamspeak.gameserver.gamed.de/ts3/releases/"
- Regex to match versions : from '_<a href=\\".\*\\/\\">.\*\\/<\\/a>_'  to  '_<a href=\\".\*\\/\\">.\*<\\/a>_'

Complete file [update_ts3 for teamspeak.gameserver.gamed.de.zip](https://github.com/GameServerManagers/LinuxGSM/files/576331/update_ts3.for.teamspeak.gameserver.gamed.de.zip)

**Comment by UltimateByte** [comment]
Hey there.

Please use
https://github.com/GameServerManagers/LinuxGSM/issues/1180

See you there :p

**Comment by Titou74** [comment]
It's #1124 : #1180 is this issue ;-)

Thank's up, I didn't see #1124 :-D

**Comment by UltimateByte** [comment]
Sorry for the wrong link ^^
