### ISSUE TITLE
Core Issues 

### ISSUE THREAD

**Issue by digimon-dk** [GameServerManagers/LinuxGSM#1181]
i get this after uf update. :s 

csgoserver2@ubuntu:~$ ./csgoserver2
    fetching functions/core_functions.sh...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/core_functions.sh

**Comment by UltimateByte** [comment]
Too old version, sorry.
Update main script, put back your settings, problem solved.
