### ISSUE TITLE
Project Zomboid hangs on Ubuntu because of missing package 'rng-tools'

### ISSUE THREAD

**Issue by Bullace** [GameServerManagers/LinuxGSM#1182]
On a clean minimal Ubuntu installation, a Project Zomboid server installed with LGSM will hang on the message "SteamUtils initialised successfully". I'm not sure why but installing the package rng-tools fixes everything. So a simple fix would be to add that to the installation instructions on the website.

**Comment by UltimateByte** [comment]
Our packages requirement don't take account of minimal install, since nobody should install that in 2016. However, i see many people doing it anyways, so... Maybe we should add some requirements for them.

**Comment by UltimateByte** [comment]
Well, I don't see the problem with adding requirements for minimal installs, it would prevent many issues ^^

**Comment by dgibbs64** [comment]
I have no way to detect to confirm or detect the requirements

**Comment by UltimateByte** [comment]
Maybe with the upcoming partner we will have an option for minimal installs ? ^^

**Comment by Bullace** [comment]
Oh hello. Just wanna say I had this happen on a Vultr Ubuntu 16.04 VPS as well. No clue if 18.04 hosted there would have this issue.

**Comment by dgibbs64** [comment]
Interesting. The final question we need to confirm is if its just Project Zomboid or are other server affected

**Comment by dgibbs64** [comment]
Research suggests its a PZ issue.

**Comment by dgibbs64** [comment]
rng-tools is now a requirement of PZ
