### ISSUE TITLE
Travis Tests failing

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1186]
Looking in to the issue of why travis is failing. I believe it might be due to a recent update to Just Cause 2 server at a guess

	Not Found
	=================================
	/home/travis/build/GameServerManagers/LinuxGSM/tests/serverfiles/Jcmp-Server
		liblua.so => not found
		libsteam_api.so => not found
	/home/travis/build/GameServerManagers/LinuxGSM/tests/serverfiles/libvstdlib_s.so
		libtier0_s.so => not found

I believe the server is not starting because of a dependency issue

here is a working setup

		ldd
		=================================
        linux-gate.so.1 =>  (0xf77c1000)
        liblua.so => ./liblua.so (0xf778b000)
        librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf777b000)
        libsteam_api.so => ./libsteam_api.so (0xf776a000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf774d000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7748000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf76f3000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf753d000)
        /lib/ld-linux.so.2 (0x565a8000)
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf73c5000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf73a8000)

**Comment by dgibbs64** [comment]
I can confirm that re running tests on passing builds are now failing. I am unsure if there is anything I can do to fix this currently

**Comment by UltimateByte** [comment]
Travis output:

```
Command: ./jc2server start
    fetching check_status.sh...OK
Required status: OFFLINE
Current status:  OFFLINE
New status:  OFFLINE
Test starting:
[ .... ] Starting jc2-server:     fetching check_logs.sh...OK
    fetching check_ip.sh...OK
    fetching check_config.sh...OK
    fetching fix_steamcmd.sh...OK
[  OK  ] Fix jc2-server: Applying steamclient.so general fix: Just Cause 2
    fetching info_config.sh...OK
    fetching logs.sh...OK
failed to connect to server: Connection refused
[ FAIL ] Starting jc2-server: Unable to start JC2-MP Server
command_start.sh exiting with code: 1
```

My output (reproducing the exact some test as Travis)

```
ultimatebyte@game:~$ ./jc2server start
[ .... ] Starting jc2-server:     fetching check_logs.sh...OK
    fetching check_ip.sh...OK
    fetching info_config.sh...OK
    fetching check_config.sh...OK
    fetching check_status.sh...OK
    fetching fix_steamcmd.sh...OK
    fetching logs.sh...OK
[  OK  ] Starting jc2-server: JC2-MP Server

command_start.sh exiting with code: 0
```

My guess is that there is an issue with `Fix jc2-server: Applying steamclient.so general fix: Just Cause 2` for jc2 into the travis test. I'll have a closer look at the fix to see if any other idea comes out.

**Comment by dgibbs64** [comment]
I think its something to do with an update to jc2mp recently that is causing the problem. However I am unsure what they have done that would cause the issue. Travis runs Ubuntu trusty for its tests. So might be worth testing out on trusty ourselves.

**Comment by UltimateByte** [comment]
We need to figure this out.

**Comment by cedarlug** [comment]
(Ref PR  #1249) 
Is making sudo required an acceptable fix?  My original guess didn't pan out to be the issue, but in the process it turned out simply changing `sudo` from `false` to `required` allows just cause test 3.1 to complete correctly.

If that's not the fix, I can dig deeper into the crux of the issue.

**Comment by UltimateByte** [comment]
Why?!

**Comment by UltimateByte** [comment]
Well, @cedarlug fixed it! Good job!
