### ISSUE TITLE
Check if executable exists

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1187]
For whatever reason, a user had a missing srcds_linux on his gmod server. He was unable to understand why.
There is already a check to know if an executable is executable https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/check_permissions.sh#L84-L127
We can add an "else" to `if [ -f "${executabledir}/${execname}" ]; then` in order to make LGSM fail with a proper output to give to the user. :)

**Comment by dgibbs64** [comment]
Makes sense. Get a branch up and running to merge in to develop

**Comment by UltimateByte** [comment]
Current output:

ultimatebyte@game:~$ ./gmodserver start
[ .... ] Starting gmod-server: failed to connect to server: Connection refused
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM


Will work on that right away on my current devbranch.

**Comment by UltimateByte** [comment]
New output:

ultimatebyte@game:~$ ./gmodserver start
[ FAIL ] Starting gmod-server: Executable srcds_run was not found

**Comment by UltimateByte** [comment]
Actually, saw that Connection refused error quite a few times without knowing one of the issues could be a missing executable.

Merged soon: Closing.
