### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peterkristel** [GameServerManagers/LinuxGSM#1196]
LD_LIBRARY_PATH=/home/csgoserver/serverfiles/bin:/home/csgoserver/serverfiles:/home/csgoserver/serverfiles/bin:
#
#Console initialized.
Setting breakpad minidump AppID = 740
#Using breakpad minidump system 740/13557.394.DC
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Particles: Missing 'particles/money_fx.pcf'
No web api auth key specified - workshop downloads will be disabled.
maxplayers set to 64
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
Setting mapgroup to 'random_classic'
Usage: host_workshop_collection <fileid>
Usage: workshop_start_map <fileid>
ConVarRef demo_quitafterplayback doesn't point to an existing ConVar
---- Host_NewGame ----
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Sat Nov 19 18:29:50 CET 2016: Server restart in 10 seconds

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by peterkristel** [comment]
I don't understand ...

**Comment by UltimateByte** [comment]
Not the right place, irrelevant title, lacking info, and why the heck would you have the LD_LIBRARY tgi g for CSGO...
