### ISSUE TITLE
LGSM Games that require Steam login fail when password includes $

### ISSUE THREAD

**Issue by Haun1400** [GameServerManagers/LinuxGSM#1203]
Hello! After trying to install a 7 Day to Die server today, I found out that the reason the install script kept failing was because of a randomly generated password I was using the included a $. 

A simple fix for this problem would be to change the quotes on the variable in the install script from " to '. 

Thanks!

**Comment by dgibbs64** [comment]
This is now in the development branch and will be fixed with next release. Thank you
