### ISSUE TITLE
Stopping Minecraft servers via "/stop" (instead of just "stop") is unsupported with some servers

### ISSUE THREAD

**Issue by stere0123** [GameServerManagers/LinuxGSM#1204]
I have noticed that some Minecraft server versions do not support [the "/stop" command issued by the command_stop.sh function](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_stop.sh#L152) (or any commands with a leading slash, for that matter), but rather they only support "stop", which causes the script to wait 30 seconds before terminating the process since it uses "/stop" and gets no response.

All Minecraft servers do support commands without a leading slash, so it seems like a simple fix. It is also [officially recommended](http://minecraft.gamepedia.com/Commands) not to use leading slashes on commands via the Minecraft server console.

Examples:
Minecraft 1.10: ["/stop" does not work but "stop" works](http://i.imgur.com/DuC0y63.png)
Minecraft 1.5.2: ["/stop" works](http://i.imgur.com/1csCPRP.png) and ["stop" works](http://i.imgur.com/pgB73OZ.png)

**Comment by dgibbs64** [comment]
Thanks for letting us know, that's a easy fix. I will pop that in the next release :).
