### ISSUE TITLE
CSGO: update-restart restarts the server when no update is available

### ISSUE THREAD

**Issue by gorgitko** [GameServerManagers/LinuxGSM#1206]
Why `csgoserver update-restart` stops the server, then steamcmd find out that CS:GO server is up-to-date and then is CS:GO server started again? In past it had worked fine -- what has changed?

EDIT: I am using latest `csgoserver` script from GitHub and I deleted the `lgsm/functions` directory in order to let `csgoserver` script download latest functions.

**Comment by dgibbs64** [comment]
you are looking for `./csgoserver update` as it will only restart if there is an update available. `./csgoserver update-restart was depreciated a long time ago as is no longer used.

**Comment by UltimateByte** [comment]
Update-restart is now force-update.
And +1 to @dgibbs, you're looking for "update" command.

**Comment by gorgitko** [comment]
OK, thanks! Maybe you should add info about `update-restart` to wiki, because I didn't found any info about it.

**Comment by UltimateByte** [comment]
You're right, I'll do it. I reopen your issue as a reminder.

**Comment by UltimateByte** [comment]
Done.
https://github.com/GameServerManagers/LinuxGSM/wiki/force-update
