### ISSUE TITLE
With Sourcemod the server gets an error when restarting

### ISSUE THREAD

**Issue by Dreizehnt** [GameServerManagers/LinuxGSM#1208]
Hi, I noticed that after installing SourceMod all the action from the terminal go awry.

Rebooting with an error:
![untitled](https://cloud.githubusercontent.com/assets/20403024/21076101/0f11124c-bf34-11e6-9d26-d479550423a4.png)

After upgrading the server crashes. Have to do is "validate", but it helps not for long. I did not understand what the problem is, please tell me.

I have installed Ubuntu 16.04, nginx.

**Comment by UltimateByte** [comment]
Hi, 

Non script issues should be solved on Steam forum or Discord.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
I'll have to close this unless it appears that it is an LGSM issue.
