### ISSUE TITLE
The message is in the French [ Gmod server problem ] Use google translate

### ISSUE THREAD

**Issue by LiamGamer30** [GameServerManagers/LinuxGSM#1209]
Bonjour , je démare mon serveur gmod et dans la console sa m'affiche could not establish connection to steam servers. (result = 3) SVP aidé moi !

**Comment by UltimateByte** [comment]
Your french isn't even right, how could somebody translate it ? Also with too few info, we cannot help.
Users issues are not solved on discord.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Use google translate.
