### ISSUE TITLE
Unable to start LinuxGSM

### ISSUE THREAD

**Issue by krfcm** [GameServerManagers/LinuxGSM#1212]
can't create socket: Permission denied
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "gmod-server" "./srcds_run -game garrysmod -strictportbind -ip 176.31.124.93 -port 27015 -tickrate 66 +host_workshop_collection  -authkey  +clientport 27005 +tv_port 27020 +gamemode sandbox +map gm_construct +sv_setsteamaccount  +servercfgfile gmod-server.cfg -maxplayers 16 +r_hunkalloclightmaps 0"

Error
=================================
can't create socket: Permission denied

Fix
=================================

http://hastebin.com/sulupumoqe

I change user but still i have this same error. I add user to group tty.

gmodserver is not part of the tty group.

        tty:x:5:garry

Run the following command with root privileges.

        usermod -G tty gmodserver

https://gameservermanagers.com/tmux-op-perm

**Comment by dgibbs64** [comment]
The solution is right in the error

``usermod -G tty gmodserver``

**Comment by krfcm** [comment]
gru 18 00:47:42 gmod-server: START: FATAL: Unable to start LinuxGSM
gru 18 00:47:44 gmod-server: START: FATAL: Unable to start LinuxGSM: Tm$tmux new-session -d -s "gmod-server" "./srcds_run -game garrysmod -stri$can't create socket: Permission denied
gru 18 00:47:44 gmod-server: START: INFO: No known fix currently. Pleas$gru 18 00:47:44 gmod-server: START: INFO: https://gameservermanagers.co$gru 18 00:47:44 gmod-server: START: FATAL: command_start.sh exiting wit$

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by krfcm** [comment]
Which game server you are running (e.g Rust/CS:GO). Garry's Mod
The outputted link of ./gameserver postdetails command. http://hastebin.com/sayavoreza
Any useful log in /home/gameserver/logs (use pastebin or equivalent). http://pastebin.com/pBUK3w0d
Your Linux distro and version (e.g Ubuntu 16.04). Debian 8.6
Any useful screenshot. - 
Your basic server hardware (CPU/RAM/Storage/Bandwidth). http://screenshot.sh/owpewXNDsqXjb
Any test you have already tried. Reinstall script
Any other useful or relevant information you think will help. -

**Comment by UltimateByte** [comment]
Did you do anything fancy to `tmux` or had issues upgrading it or something ?
Did you `apt update && apt upgrade` ?
Can you try to start with `./gmodserver debug` ?

**Comment by krfcm** [comment]
I did apt update && apt upgrade. I try ./gmodserver debug server starts.  I don't have any error when i updating system.

**Comment by UltimateByte** [comment]
What listen to your port 80 and LGSM is not related. So nginx is not the issue here.
The issue comes from your tmux that is not able to work properly for some reason. Since you're using Debian and have a proper tmux version, i got no clue why it would happen. I'd try to use tmux without LGSM to try diagnose it. I'd also try to put an original Debian kernel rather than yours.
I gotta close this since github is for script development rather than solving user issues. However, you can post on the Steam forum or Discord (relating this issue) if you need more help.
