### ISSUE TITLE
[ CsGo ] Tmux Error

### ISSUE THREAD

**Issue by Prixix** [GameServerManagers/LinuxGSM#1218]
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM
[ FAIL ] Starting csgo-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip 84.200.206.251 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount HEY HERE IS MY TOKEN! -tickrate 128 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 10 +mapgroup random_classic +game_mode 1 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "

Error
=================================
tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968

Fix

How can i update or change to UTF-8 (Ive got Debian 8)

**Comment by cedarlug** [comment]
```
apt-get install locales
dpkg-reonfigure locales
```
