### ISSUE TITLE
Rust-Server bin/df2 permission denied

### ISSUE THREAD

**Issue by Briariuss** [GameServerManagers/LinuxGSM#1219]
Hello dear LGSM team.
Have the following problem if i start the Rust-Server.
It always comes this message: bin/df2 permission denied
The Server is starting and Online but if i stop the server the message is reflected: bin/df2 permission denied
Have changed the right but if i start the Server. It changes the right back and returns the same message.
I dont know what df2 is ????
Have test it on a fresh root server i got the same with the df2 and if i googel it i dont find somthing....

With best regards
Briariuss

**Comment by UltimateByte** [comment]
Hey there.

Without real details we can't help.
Also, user issues are not solved on Github but rather on Discord or Steam forum.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Briariuss** [comment]
https://hastebin.com/iyibaloqut
http://www.bilder-upload.eu/show.php?file=319669-1483185475.png
Server-Hardware
CPU: 8 x 4GHz / Intel®Core™ i7 6700K
RAM: 64GB / DDR4-RAM INFINEON®
Mainboard: ASUS
Harddisk: 240GB / HGST SSD 800MB/s r/w
