### ISSUE TITLE
[l4d] Falled to run the server after the install 

### ISSUE THREAD

**Issue by thumsoul** [GameServerManagers/LinuxGSM#1222]
Hi,

Here is my debug pastebin : https://hastebin.com/vetadotifu.sql

Can you help me ?

Best regards.

**Comment by UltimateByte** [comment]
Hi,

https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#segmentation-fault
Also, this is a user based issue, so it won't be solved on Github but rather on Steam forum or Discord.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

Cheers and good luck !

**Comment by thumsoul** [comment]
Ok, no problem thank you anyway UltimateByte.

Best regards.

**Comment by thumsoul** [comment]
Result after test : its work on wheezie but not on Jessie
