### ISSUE TITLE
Installing teamspeak3 freezes/fails

### ISSUE THREAD

**Issue by R0GGER** [GameServerManagers/LinuxGSM#1232]
Installing teamspeak3 fails... 
After step **fetching update_ts3.sh...OK** it stops.

```
Installing TeamSpeak 3 Server
=================================
    fetching update_ts3.sh...OK
```

Screencast: https://imgurl.nl/f/r/46JELK.mp4

Please your help.

**Comment by dgibbs64** [comment]
How odd. Never seen this before. I have just tested this without an issue on my end. Maybe its related to issue #1124. switch on ./ts3server dev-debug it will create a file in the main dir called dev-debug.log run the command again and send us the output. It should help identify where its getting stuck.

**Comment by UltimateByte** [comment]
We should add an echo before LGSM actually tries to get version info. It's probably hanging at this.

To know if you're banned from 4players, try this from your server:
`wget http://dl.4players.de/ts/releases/3.0.19.4/TeamSpeak3-Client-linux_amd64-3.0.19.4.run`

**Comment by R0GGER** [comment]
> To know if you're banned from 4players, try this from your server:
wget http://dl.4players.de/ts/releases/3.0.19.4/TeamSpeak3-Client-linux_amd64-3.0.19.4.run

Yup... I guess this is why it's not downloading.
It hangs on...
```
--2017-01-07 16:55:32--  http://dl.4players.de/ts/releases/3.0.19.4/TeamSpeak3-Client-linux_amd64-3.0.19.4.run
Resolving dl.4players.de (dl.4players.de)... 85.25.26.27, 85.25.26.26, 85.25.26.25
Connecting to dl.4players.de (dl.4players.de)|85.25.26.27|:80...
```
Why am I banned?

**Comment by UltimateByte** [comment]
I don't know, follow the other issue then, the whole process we understood this and workaround is in it :)

**Comment by R0GGER** [comment]
Why closing this issue?
Workaround here http://imgurl.nl/f/r/update_ts3.sh

**Comment by UltimateByte** [comment]
Because it's duplicate. We're already aware that some people are banned from 4players.de
Also everything has been said into the other topic isn't it ?

**Comment by UltimateByte** [comment]
I'll have a look at your code though :)
