### ISSUE TITLE
update-functions to check for a new default-config

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1233]
update functions to check for a new default config from the configs repo and update it locally plus send notification

**Comment by UltimateByte** [comment]
Good idea. Is the default config downloaded to lgsm folder already?
It should be kept somewhere since we can't compare user config and LGSM default config directly.

**Comment by dgibbs64** [comment]
Yeah its kept in the lgsm/default-config dir. I would work exactly the same as updating functions

**Comment by UltimateByte** [comment]
It won't have to alter user config, right? Just the default-config one, for the user to have it if needed?

**Comment by dgibbs64** [comment]
you got it. do the touch the user config. only the default

**Comment by dgibbs64** [comment]
This was implemented a while ago. Closing
