### ISSUE TITLE
Find a workaround for Ark config file

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1235]
The file is located in serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
Problem is: the Saved directory doesn't exist until you start the server. So config file cannot be copied to this location.

So either it has to create parent directories first (then config file might be erased upon first start), or, it has to start/stop then replace default config file for LGSM one, then end the install process.

Or maybe you'll find a better solution? Discussion is open.

**Comment by ChaosMTA** [comment]
You can simply call this function in `install_config.sh` before creating the default config file no?
https://github.com/GameServerManagers/LinuxGSM/blob/34d2c96becbe3d7a0c81688ead460cdba17abac9/lgsm/functions/install_config.sh#L39-L46

Many other servers use the same approach and my current pull request uses it and it works fine for Multi Theft Auto.

**Comment by UltimateByte** [comment]
"So either it has to create parent directories first **(then config file might be erased upon first start)**"

**Comment by UltimateByte** [comment]
Assigning, will try stuff after work in around 10 hours if I'm still able to use my fingers. :o))

**Comment by ReDSkiZZeM** [comment]
Any good news?

**Comment by UltimateByte** [comment]
Went back home a few hours ago. Just made a branch, will try stuff.
BTW, if my workaround i told you about on Discord didn't work, then your issue is probably not just the config file.

**Comment by UltimateByte** [comment]
Well, config file is manage kinda weirdly with Ark. But I figured it out. Creating the full path is enough to solve the issue. However, admin password and servername are set within start parameters, so i gotta remove their edition by LGSM.

**Comment by UltimateByte** [comment]
Port values might need to be removed from default config file since they are ignored and start parameters are used instead,. On top of that, those are not changed upon server shutdown to match start parameters, so in the end, if they're not used, they can be misleading.

Any enlightened thought about that?

**Comment by UltimateByte** [comment]
Merged to develop. Closing.
