### ISSUE TITLE
[ARK] check update of mods

### ISSUE THREAD

**Issue by morno** [GameServerManagers/LinuxGSM#1237]
hello id like to make the ./arkserver u also update mods. i cant seem to set a steam login that has subscribed to the mods i wanna download and install.

please enable this support :) keep up the good work

**Comment by UltimateByte** [comment]
Hi.
Well, why not, but do you have any relevant documentation to provide?

**Comment by UltimateByte** [comment]
This issue is actually duplicate.
Closing
https://github.com/GameServerManagers/LinuxGSM/issues/802
