### ISSUE TITLE
Validate function is not able to login to steam due to bad password

### ISSUE THREAD

**Issue by FliesWithWind** [GameServerManagers/LinuxGSM#1239]
In /lgsm/functions/command_validate.sh

Lines 27 and 29

'${steampass}' needs to be changed to "${steampass}"

Otherwise you won't login to steamcmd due to bad password.

**Comment by UltimateByte** [comment]
We just changed it the other way a few days ago to solve an issue with passwords containing a $ sign in it.
So a dev need to figure this out.

**Comment by akaxiv** [comment]
'${steampass}' needs to be changed to "${steampass}" but on this file:

/lgsm/functions/check_steamcmd.sh

Thank you for your help

**Comment by dgibbs64** [comment]
Maybe this might work ```'\"${steampass}\"'``` if not I will revert to the previous method

**Comment by UltimateByte** [comment]
I don't know, but if this issue is global, then it is critical to fix it.

**Comment by UltimateByte** [comment]
````
ultimatebyte@game:~/toast$ test="$there"; echo '$test'
$test
````

Of course it doesn't work!

This works:
````
ultimatebyte@game:~/toast$ test='$there'; echo "$test"
$there
````

We need to revert last change, and put steampass in single quotes though gameserver scripts.

**Comment by UltimateByte** [comment]
Tested working OK with normal passwords, and probably fixing passwords containing "$" as well.
Awaiting for merge.

**Comment by UltimateByte** [comment]
Allright everyone, 
you can all run `./gameserver uf`
And if your password contains a dollar in it, you can just use `steampass='my$password'`, or redownload the main script if you're afraid, will fix it for you.
