### ISSUE TITLE
What's up with Arma3 ports?

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1240]
Since only one is required and is set with start parms, then why are they into the cfg file?
And especially, why `ERROR! Missing/commented ports in arma3-server.server.cfg` error message even exists, since this is absolutely normal for them to be commented?

First time I'm looking into it, and I feel confused, maybe I'm missing something.
So does this guy with this error message http://steamcommunity.com/groups/linuxgsm/discussions/0/144513128846028225/

https://github.com/GameServerManagers/Game-Server-Configs/blob/master/Arma3/server.cfg#L14
https://github.com/GameServerManagers/LinuxGSM/blob/master/Arma3/arma3server#L31
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_details.sh#L521

At first glanc,e I guess port info should come from the main port and some additions set here
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/info_config.sh#L335

**Comment by dgibbs64** [comment]
Ideally parms should not be used and instead the config should be used. I recommend testing arma 3 with the port being using from the config and remove the parms ```port="2302"```

We should only use parms if we have no choice. Make things less complicated

**Comment by UltimateByte** [comment]
OK, thx, will test it right now.

**Comment by UltimateByte** [comment]
So test 1) Remove port start parameter, and start with default commented config
````
23:44:55 Game Port: 2302, Steam Query Port: 2303
23:44:55 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303
Arma 3 Console version1.66.139586  : port 2302
````

Test 2) Try altering config file:

````
// Server Port
serverport=2310;

// Steam Master Port
steamport=2320;

steamqueryport=2330;
````
Result:
````
23:47:18 Game Port: 2302, Steam Query Port: 2303
23:47:18 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303
Arma 3 Console version1.66.139586  : port 2302
````

Arma3 don't care about ports set withing config files.

Test 3) Remove anything about ports in cfg file, and try with port start parms

````
23:49:13 Game Port: 2330, Steam Query Port: 2331
23:49:13 Initializing Steam server - Game Port: 2330, Steam Query Port: 2331
Arma 3 Console version1.66.139586  : port 2330
````

Conclusion: Sadly, we have to remove port config from config file and use start parameters only.

**Comment by UltimateByte** [comment]
Also, port info is broken atm.

````
ERROR! Missing/commented ports in arma3-server.server.cfg.

DESCRIPTION              DIRECTION  PORT  PROTOCOL
> Game                   INBOUND    2302  udp
> Steam: Query           INBOUND    udp
> Steam: Master traffic  INBOUND    udp
````

Will be a hotfix, since it's quite critical for ARMA IMO, and also, because we need to make sure to alter cfg file at the  same time as the master commit.

**Comment by UltimateByte** [comment]
Proper output:
````
Ports
==================================================================================================
Change ports by editing the parameters in:
arma3server

Useful port diagnostic command:
netstat -atunp | grep arma3server

DESCRIPTION              DIRECTION  PORT  PROTOCOL
> Game                   INBOUND    2310  udp
> Steam: Query           INBOUND    2311  udp
> Steam: Master traffic  INBOUND    2312  udp
> Undocumented Port      INBOUND    2313  udp
````

Awaiting merge.
