### ISSUE TITLE
Settings to disable sleeps and prompts

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1242]
`skipsleeps="on"` parameter would disable sleeps in LGSM. Less readable, but faster.
Code wise: Replace any sleep into LGSM by `fn_sleep x` with x being the desired duration. Then fn_sleep would check for the config variable before applying any kind of a sleep.

`skipprompts="on"` parameter would disable any kind of prompt in LGSM.
Code wise: Prepare some prompt functions with different layouts. Then call it with `fn_prompt_whatever "Message goes here" "Text Option A" "Text Option B" "Action option A" "Action option B" "Invalid option message" "Default Option"`. Of course, this function would check for the config variable as well. Not really sure how to implement this one though, but would be really cool.

Would be lovely IMO, and make LGSM so much faster for experienced users!

Thoughts?

**Comment by ChaosMTA** [comment]
Would be kind of annoying to add this setting to every server file no? Additionally if we go this route every time we want to add a configurable feature to LGSM you'd have to edit EVERY server file in LGSM.

Should maybe be something when running the install, like `./mtaserver install --skip-sleeps`

**Comment by UltimateByte** [comment]
Thanks for sharing your thoughts.

> Would be kind of annoying to add this setting to every server file no?

Well, after this https://github.com/GameServerManagers/LinuxGSM/releases/tag/161030 I'm not affraid about it. :p 
The feature would apply to newer "gameserver" scripts and not break existing installations.

> Should maybe be something when running the install, like ./mtaserver install --skip-sleeps

For some reason, @dgibbs64 said it's impossible to combine two arguments. A global setting would be more enjoyable anyways, I think.

**Comment by ChaosMTA** [comment]
I don't think the implementation for that backup even makes sense on its own. If you plan to make LGSM sustainable and organized while still adding configurable scripts, having a separate file that is fetched that is specifically for configuring LGSM would be more ideal imo.

Keep server files for server configuration, have a separate file for LGSM configuration, notifications, backups, skipping sleep etc. That way you have 1 file to update on GitHub, and 1 file for the client to fetch in order to configure.

**Comment by UltimateByte** [comment]
That is a project already. I can't wait to see this coming.
https://github.com/GameServerManagers/LinuxGSM/issues/344

**Comment by JimTR** [comment]
referencing something dated Apr 2015 ... I still think add this stuff to a database rather than a file so it can be read via any platform that can access it
