### ISSUE TITLE
Auto-restart issue

### ISSUE THREAD

**Issue by PichotM** [GameServerManagers/LinuxGSM#1244]
Hi, I've followed these instructions: http://steamcommunity.com/groups/linuxgsm/discussions/0/458605613414424931/#c458606248614821764

but I get an error "failed to connect to the server"
Thanks

**Comment by cedarlug** [comment]
This is not an autostart issue, nor is it an LGSM issue.  Please use discord or steam discussion for assistance, and cite more details regarding your situation (what gameserver are you even running?).
