### ISSUE TITLE
New server: CSGO - Classic Offensive mod

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1245]
Let's see what we can do about it.
We first need to see if it's gonna be a built in option for csgoserver or a totally separated executable.

http://www.moddb.com/mods/counter-strike-classic-offensive/news/counter-strike-classic-offensive-whats-that
http://steamcommunity.com/groups/classicoffensive

Won't be an easy one. I personally didn't test the mod already.

**Comment by GreYzZ** [comment]
@UltimateByte 
any updates so far on that? Pretty excited tho

**Comment by UltimateByte** [comment]
@GreYzZ It's at the stage of project. I'm busy  finishing adding mods install/update/remove to LGSM for now :o))

**Comment by DigitalFriends** [comment]
Waiting for this! Would be awsome!

**Comment by GreYzZ** [comment]
@UltimateByte 
any updates on that so far? Very excited to see that coming because it makes the server installation for a CSCO Server ways easier than it is right now

**Comment by zunnu** [comment]
Hello, I have made installer for csco server https://github.com/zunnu/CSCO-server-installer
This script is partly made from very old LGSM script.

**Comment by UltimateByte** [comment]
Thanks @zunnu , you rock! It will definitely help !

**Comment by hurdad** [comment]
added to dev branch https://github.com/GameServerManagers/LinuxGSM/tree/develop/CounterStrikeClassicOffensive

**Comment by GreYzZ** [comment]
Does this also check for new CSCO Updates?

**Comment by hurdad** [comment]
negative, you must manually install zip until they get it greenlight on steam.

**Comment by UltimateByte** [comment]
So, mods-install / update / remove are made. Time to dig into this.

**Comment by hurdad** [comment]
let me know if you have any questions/issues

**Comment by UltimateByte** [comment]
@hurdad Thanks. Well actually, the first question i'll need to answer to achieve this is: Can we just install this as a mod? Or should we make a dedicated installer? And are there any start parameters or config files that need to be changed?

**Comment by hurdad** [comment]
so it requires CS:GO, and you install the 'csco' folder into the serverfiles directory for CSGO then add '-game csco' in start parameters.

**Comment by UltimateByte** [comment]
Well, i'll add this to mods-install then add a warning saying to edit ${selfname} script this way.

**Comment by UltimateByte** [comment]
Wait, they're gonna have their standalone game, it's a thing! Is it still worth adding the mod then?
http://steamcommunity.com/groups/classicoffensive#announcements/detail/261609914167592577
http://steamcommunity.com/groups/classicoffensive#announcements/detail/261610548105148734

**Comment by hurdad** [comment]
yes, should be on steam as standalone game soon...

**Comment by UltimateByte** [comment]
http://steamcommunity.com/groups/classicoffensive#announcements/detail/261611816902425719

> Hello !
> 
> We're having troubles getting dedicated servers working and it's preventing release, but we're trying to find a workaround as soon as possible.
> 
> Just wanted to let you know.
> 
> Cheers, 
> - dayik.

**Comment by Bara20** [comment]
I've asked ZooL, we need first a csgo server as base server and then we can install csco as second server. We start the server with "csco" as game. To update: Update csgo server after this we update our csco server/files.

I hope that's helpful, but that's the current status.

**Comment by UltimateByte** [comment]
@Bara20 Any deadline for the final game release ?

**Comment by Bara20** [comment]
We try to find and fix the last bugs as closed beta. Maybe to summer or later we don't know.

**Comment by UltimateByte** [comment]
@Bara20 Thanks. :) So it's worth waiting for the final release, I suppose :)

**Comment by Bara20** [comment]
- login name...
- force_install_dir /path/to/server/
- app_update 740 #csgo server
- app_update 600380 #csco files

I mean that's all to install a csco server except the change of "game".

**Comment by UltimateByte** [comment]
@Bara20 Except adding a second appid to LGSM is a though modification since it's not meant to work this way at all.

**Comment by Bara20** [comment]
Yeah, that problem have now all scripts and webintefaces.

**Comment by dgibbs64** [comment]
Sadly LinuxGSM is not designed to use more than one appid since it has never been required. However there is nothing wrong with manually downloading using steamcmd and running the server using LinuxGSM by tweaking the params etc. So I would recommend creating a little update bash script for the two appids. I assume that once the game is more complete the there will be one appid for the server download?

**Comment by dgibbs64** [comment]
Another note I look forward to this being released and are happy to create a LinuxGSM script for CSCO when the servers are complete and ready. until then feel free to use CSGO script as a base as im guessing it wont be very different 👍

**Comment by Bara20** [comment]
I'll try my luck.

**Comment by dgibbs64** [comment]
There is a working version of coserver but not yet official released. When the dedicated server is fully released then it will become available to general use. This issue will be closed until that time @Bara20 please inform us when coserver is fully release.

**Comment by Bara** [comment]
@dgibbs64 Classic Offensive is currently unsupported until Release on Steam. Remove it if you want, I'll rewrite it again with Release on Steam.
