### ISSUE TITLE
Update functions fail (dgibbs64/linuxgsm) repo

### ISSUE THREAD

**Issue by maximelafarie** [GameServerManagers/LinuxGSM#1258]
I get the following error with `./myuser uf` : 
```sh
fetching functions/update_functions.sh...FAIL
0curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/update_functions.sh
```
How can i fix this error ?

**Comment by ChaosMTA** [comment]
Link is working properly for me, command is working properly on my server. Cannot reproduce.

**Comment by UltimateByte** [comment]
Link is 404 for me as well at the moment. Could be related to Github having issues recently, and not redirecting the old repo to the new one properly.
Try to change repos into the main script to use the new one, as in newer scripts
https://github.com/GameServerManagers/LinuxGSM/blob/master/7DaysToDie/sdtdserver#L74-L79

BTW if you're sitll on dgibbs64, with your main scripts, then they must be very old, and it's probably time to update them.

**Comment by UltimateByte** [comment]
Well, actually i didn't notice at first glance, but master/functions/update_functions.sh don't exist anymore. Retro-compatibility has been removed after months of support. 
Not it'd be like master/lgsm/functions/*
So yeah, update your main scripts and enjoy newer LGSM. ;)

**Comment by maximelafarie** [comment]
Thanks a lot my friend! 😄
