### ISSUE TITLE
Server Stopping after 5-6 games

### ISSUE THREAD

**Issue by atehaa** [GameServerManagers/LinuxGSM#1259]
Hi,

Firstly thank you for this easy management tool. I have problem with it. Server works fine there is no lag or high ping so system requirements are good enough. But after 5-6 games (or map) I find always stopped insserver :) Server is usually full and there is no problem about it.

I tried to find log files and I found some there is no explanation. Can you help me guys? Players liked server but they angry :)

Thanks !

**Comment by dgibbs64** [comment]
Its difficult to say. It could be anything. Could be a mod or something wrong with the distro. Im afraid without any logs or details we cannot help.

**Comment by atehaa** [comment]
Hey @dgibbs64 
I am not good at this stuff maybe I couldn't see the problem. Can you say which log files should I check and where them are?

**Comment by dgibbs64** [comment]
sure read this and post the info http://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/

I also the steam group is normally the best place to post about issues that are not related to LinuxGSM but rather the server itself

**Comment by atehaa** [comment]
Ok thank you very much :)
