### ISSUE TITLE
command: ./rustserver wipe 

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1260]
Server wipe means clear game data. This task is usually required after monthly updates. 
Since some patches don't require a wipe, we cannot add an option for automatic wipes upon updates.
Would be a nice addition for Rust server owners to have a command for that.

````bash
./rustserver wipe
````

Update: There is now only one file to wipe.
Example: proceduralmap.3000.736413606.140.sav

So basically, this is gonna be like:
````bash
rustwipemaps="$(find "${serveridentitydir}" -name "proceduralmap.*.sav)"
if [ -n "${rustwipemaps}" ]; then
	echo "These file(s) will be removed:"
	echo "${rustwipemaps}"
	echo "Continue ? y/n"
	rm "${serveridentitydir}/proceduralmap.*.sav"
else
	echo "Nothing to wipe"
fi
````

**Comment by ChaosMTA** [comment]
Easily implemented then

**Comment by UltimateByte** [comment]
@ChaosMTA Yep. Only annoying thing is to make an OPT just for Rust because of a single command addition.
That's why... https://github.com/GameServerManagers/LinuxGSM/issues/1261

**Comment by UltimateByte** [comment]
So, there is also a "storage" dir that contains at least paintings.
I know there is another one, but i couldn't make it popup yet. Maybe related to blueprints if it's still a thing.

**Comment by ChaosMTA** [comment]
Should note that I've heard from people in discord that this issue also affects CS:GO servers. Might be something we should just do as an LGSM pre_req test for all servers.

**Comment by UltimateByte** [comment]
Merged, closing.
