### ISSUE TITLE
Code review required

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1264]
A general code review to ensure that the same standards of code are being followed across the board.

For example there are several types of if statement variations being used. These should be the same across the board

if [ "${var}" == "${var}" ]
if [[ "${var}" -eq "${var}" ]]
if [ "${var}" -eq 0 ]

A good idea woudl be to start a wiki page with the standards expected to ensure all developers use the same code across the board.

**Comment by UltimateByte** [comment]
if [[ "${var}" -eq "${var}" ]]
if [ "${var}" -eq 0 ]

Those are arithmetic comparisons. For that reason, ${var} should be a numeric value, making the double quotes unnecessary.

So my question is: is this more about the look and preventing mistakes then? (Trying to understand the reason for this)

That's a good idea to add an entry for that onto the wiki.

Other rules i can think of atm:

- Variables are lowercase regular characters only
- Additional information messages are given in the form of `echo " * Message here"`

Huh, there are probably plenty more of them, need to fill up a list. :o))

**Comment by dgibbs64** [comment]
Yup this is something to build on over time. Its mainly for look and consistency to reduce errors. Something I take extra time to ensure however with there being multiple contributors I cannot always check all the code and will miss stuff somtimes. 

These notes will also be useful for me to reference myself when vetting code as I myself forget which way is the standard way somtimes

**Comment by UltimateByte** [comment]
Made a base page to start with

https://github.com/GameServerManagers/LinuxGSM/wiki/Syntax-&-Conventions

**Comment by ChaosMTA** [comment]
This can probably be closed, we have a contributing guide and have started works on a wiki page to solve this issue.
@UltimateByte @dgibbs64

**Comment by UltimateByte** [comment]
Yeah I think so, we can still improve the wiki over time though.
We got some nice doc for new contributors now already. I've seen some people coming, saying they want to learn bash, and saying they want to help with LGSM recently, which was kinda rare before, so it looks like it's having some effects already.
