### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by law159** [GameServerManagers/LinuxGSM#1267]
after running ./rustserver start and ./rustserver details the Status says Online but I cant connect to my server when I try and open rust and run connect with my ip and port number. 
I am running it on OS ubuntu 16 server with an internal IP address and an associated floating ip address. I have tried using both ip addresses in the server.ip field but cannot connect. 
./rustserver m gives me Error: Unable to receive
the ip tables are set not to block traffic in and out

The game log is attached
[names.txt](https://github.com/GameServerManagers/LinuxGSM/files/722417/names.txt)

**Comment by UltimateByte** [comment]
Your game log looks perfectly fine.
This obviously isn't an LGSM issue.

Here is some guidance to solve your issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Ports

If you can't figure it out, then here is how to get support
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
