### ISSUE TITLE
bug intalation ts3

### ISSUE THREAD

**Issue by hugolafougere** [GameServerManagers/LinuxGSM#1269]
There an installation bug at the time it install teamspeak 3 server

**Comment by JimTR** [comment]
and that is ......

**Comment by ChaosMTA** [comment]
Need additional details.

**Comment by cedarlug** [comment]
Closing.  Re-open when you can justify your statements with logs additional information.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
