### ISSUE TITLE
[Server Request] Avorion

### ISSUE THREAD

**Issue by joecasanova** [GameServerManagers/LinuxGSM#1271]
Avorion released steam on January 23rd.

Steamdb links:
Game:  https://steamdb.info/app/445220/
Dedicated Server:  https://steamdb.info/app/565060/

Avorion Wiki Entry on setting up dedicated server:  http://wiki.avorion.net/index.php?title=Setting_up_a_server

**Comment by UltimateByte** [comment]
Wow, no info about start parms into their wiki. Their .cfg file better be rich in settings then.

**Comment by joecasanova** [comment]
It's a custom engine.  Here is what the server.ini looks like:

`[Game]
Seed=2BzFa0CqBw
Difficulity=0
InfiniteResources=false
CollisionDamage=1
LootDiminishingFactor=0.00499999989
ResourceDropChance=0.400000006
TurretDropChanceFromTurret=0.0250000004
TurretDropChanceFromCraft=0.25
TurretDropChanceFromBlock=0.00499999989
SystemDropChanceFromCraft=0.200000003
SystemDropChanceFromBlock=0.00499999989
ColorDropChanceFromCraft=0.0500000007
ColorDropChanceFromBlock=0.00249999994
sameStartSector=true
startUpScript=data/scripts/server/server.lua
startSectorScript=startsector
[System]
saveInterval=600
sectorUpdateTimeLimit=300
emptySectorUpdateInterval=0.5
workerThreads=1
weakUpdate=true
[Networking]
port=27000
broadcastInterval=5
isPublic=true
isListed=true
useSteam=true
[Administration]
maxPlayers=10
name=Avorion Server
description=Avorion Server
accessListMode=Blacklist
`

It seems that currently only the core game data port is configurable.  The steam networking port.  See the server output:

`avorion@APP02:~/avorion$ ./server.sh
Avorion server Beta 0.10.1 r7302 running on Ubuntu 16.04.1 LTS starting up in "/home/avorion/.avorion/galaxies/avorion_galaxy"
CPU: Intel(R) Xeon(R) CPU           E5420  @ 2.50GHz 4 Cores
name: The Lone Gamers
seed: 2BzFa0CqBw
port: 27500
max online players: 500
save interval: 600
broadcast interval: 5
max loaded sector time: 300
weak update: yes
worker threads: 1
difficulty: Veteran
infiniteResources: no
collision: 1
access list: Blacklist
public: yes
listed: yes
steam networking & authentication: yes
administrators: 'avorion'
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 445220
Game Port: 27000
Steam Port: 27021
Steam Query Port: 27020
Polling Port: 27003

Server startup complete.
Server connected to Steam successfully
Server is VAC Secure!
Game Server Steam ID: 90106509840367617`

**Comment by UltimateByte** [comment]
This config file looks like Unity3D. Hope non configurable ports are outgoing...

**Comment by SkippTekk** [comment]
we have a page that may have more information. not sure as i dont do coding. http://stonelegion.com/Avorion/Documentation/

**Comment by nthirtyone** [comment]
It is scripting API Documentation @SkippTekk.
Anyway, from today's [patch (0.10.2)](http://www.avorion.net/forum/index.php/topic,896.msg4104):

> All server ports are now configurable via command line

Command line parameters are visible with `--help`.

> --port arg  listening port of the server
> --query-port arg  internal game query port of the server, default: 27003
> --steam-query-port arg steam query port of the server, default: 27020
> --steam-master-port arg  steam master server port of the server, default: 27021

**Comment by Zorrototo** [comment]
Just in case someone comes here for this last post which is really helpful, here is a bug regarding modification of polling port http://www.avorion.net/forum/index.php?topic=973.0

**Comment by UltimateByte** [comment]
Documentation
http://avorion.gamepedia.com/Setting_up_a_server#Starting_the_server_.28Linux.29

**Comment by Maygus** [comment]
Thanks @UltimateByte I should have searched first (my bad).

**Comment by m3ch-mania** [comment]
FYI: I was able to pull the following parameters from `{AvorionInstallPath}/bin/AvorionServer --help`

```
Allowed options:
  --help                         show help message
  --version                      print out version and exit
  --port arg                     listening port of the server
  --query-port arg               internal game query port of the server, 
                                 default: 27003
  --steam-query-port arg         steam query port of the server, default: 27020
  --steam-master-port arg        steam master server port of the server, 
                                 default: 27021
  --ip arg                       binds the server to a specific IP (steam 
                                 networking only)
  --max-players arg              maximum number of online players
  --save-interval arg            timestep between savings
  --server-name arg              server name, will be displayed when queried
  --pausable arg                 whether or not the server can be paused by 
                                 admins when there's only a single player 
                                 online
  --galaxy-name arg              galaxy name, appended to datapath, final path 
                                 will be [datapath]/[galaxyname]
  --datapath arg                 folder the galaxies will be stored in, will be
                                 prepended to galaxy name
  --admin arg                    steam id(s) of the administrator(s) to add to 
                                 the server
  --seed arg                     seed of the server
  --difficulty arg               difficulty of the server, allowed values are: 
                                 -3, -2, -1, 0, 1, 2, 3
  --infinite-resources arg       enable infinite resources for all players
  --collision-damage arg         amount of damage done to an object on 
                                 collision, from 0 to 1. 0: no damage, 1: full 
                                 damage. default: 1
  --same-start-sector arg        indicate if all players should start in the 
                                 same sector
  --alive-sectors-per-player arg the amount of sectors with player property 
                                 that are simulated in addition to that 
                                 player's current sector
  --safe-player-input arg        enable to guarantee more cheat-safety, but 
                                 players may experience more lag
  --threads arg                  specifies the number of threads used to update
                                 the sectors
  --generator-threads arg        specifies the number of threads used to 
                                 generate sectors
  -t [ --trace ] arg             tracing options. Can be more than one. Allowed
                                 values are: network scripting threading io 
                                 database input error warning exception user 
                                 game system debug sound gl all
  --exit-on-last-admin-logout    shut down when last administrator logs out
  --stderr-to-log                redirect std error output from console to log 
                                 file
  --stdout-to-log                redirect std console output from console to 
                                 log file
  --public arg                   indicate if the server should allow other 
                                 players to join
  --listed arg                   indicate if the server should show up on 
                                 public server lists
  --authentication arg           enables authentication of players
  --use-steam-networking arg     use steam networking and authentication (if 
                                 enabled) for users
  --immediate-writeout arg       immediately write player data to disk when it 
                                 changes. decreases performance during sector 
                                 changes, but makes server data more consistent
                                 on crash.
  --max-logs arg                 maximum number of logs to keep around, 0 for 
                                 infinite, default: 15
  --rcon-ip arg                  binds the rcon server to a specific IP
  --rcon-port arg                rcon port, default: 27015
  --rcon-password arg            sets the password for the rcon interface. 
                                 without password, rcon is disabled.
  --send-crash-reports arg       when enabled, the server will send anonymous 
                                 system specs and a crash report when it 
                                 crashes.

```

**Comment by h3o66** [comment]
Can someone test this connected pull request, please ?
