### ISSUE TITLE
fast-dl function requires UI overhaul

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1272]
Requires a Ui overhaul to bring it in line with other functions. This should look much like the new mods-update function

**Comment by ChaosMTA** [comment]
I know there were some major changes to fast-dl, is this done @UltimateByte

**Comment by UltimateByte** [comment]
Yes. Now i'd just lile to make the compression output fit the estimation & copy and it'll be good.

**Comment by dgibbs64** [comment]
see #2614
