### ISSUE TITLE
Ark Not Starting

### ISSUE THREAD

**Issue by testler2** [GameServerManagers/LinuxGSM#1273]
Hello, How can I solve this problem?

[  OK  ] Debug ark-server: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 402 6
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
^CCtrlCHandler: Signal=2
/home/arkserver1/lgsm/functions/command_debug.sh: line 107: 29308 Aborted                 ${executable} ${parms}

**Comment by UltimateByte** [comment]
Game is probably not installed.
./arkserver validate

Also, that's neither the right place or the right way to submit such an issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by testler2** [comment]
Hello, not solved problem

ark-server-console.log

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by ChaosMTA** [comment]
As UltimateByte said this is not an LGSM bug, but rather an issue with your SteamCMD or configuration.

**Comment by testler2** [comment]
Hello, How do I know how to set it?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
