### ISSUE TITLE
[REQUEST] Space Engineers Dedicated Server

### ISSUE THREAD

**Issue by FlashModz** [GameServerManagers/LinuxGSM#1274]
Hello All,

Possibility to Add Space Engineers ?
Steam Links : http://store.steampowered.com/app/244850/

Linux if possible ? Yes
Link to Devs Games : http://www.spaceengineersgame.com/dedicated-servers.html

Thanks for all :)

**Comment by UltimateByte** [comment]
Not compatible with Linux
https://steamdb.info/app/298740/

**Comment by FlashModz** [comment]
Sorry, Official Forums ==> http://forum.keenswh.com/threads/tutorial-dedicated-server-on-ubuntu-13-10-using-wine.6922069/

**Comment by UltimateByte** [comment]
Using wine to run windows stuff in Linux is not considered as "supported".
We're not adding wine stuff to LGSM.
