### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by telazorn** [GameServerManagers/LinuxGSM#1276]
[sdtdserver@dreamblock_ind ~]$ ./sdtdserver start
[ FAIL ] Starting sdtd-server: Unable to start LinuxGSM
[ FAIL ] Starting sdtd-server: Unable to start LinuxGSM: Tmux error:

Command
=================================
tmux new-session -d -s "sdtd-server" "./7DaysToDieServer.x86 -logfile /home/sdtdserver/log/server/output_log__2017-01-27__18-59-52.txt -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtd-server.xml"

Error
=================================
create session failed: ./7DaysToDieServer.x86 -logfile /home/sdtdserver/log/server/output_log__2017-01-27__18-59-52.txt -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtd-server.xml: Operation not permitted

Fix
=================================
No known fix currently. Please log an issue.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
https://github.com/GameServerManagers/LinuxGSM/wiki/Diagnosing-Protocol

**Comment by UltimateByte** [comment]
Also, might be relevant for your case, but since no actual details were provided i cannot tell.
https://github.com/GameServerManagers/LinuxGSM/wiki/Tmux
