### ISSUE TITLE
[New server] Conan Exiles

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1284]
This server is available
https://steamdb.info/app/443030/info/

Requested here
http://steamcommunity.com/groups/linuxgsm/discussions/0/135507780429304937/

Doc:
https://survivalservers.com/wiki/index.php?title=How_to_Create_a_Conan_Exiles_Dedicated_Server_Guide

I personally don't own the game.

**Comment by zewm** [comment]
Developers have stated that no Linux support (server) for Early Access release. Dedicated servers are only available through Windows platform currently.

**Comment by UltimateByte** [comment]
Source?

**Comment by zewm** [comment]
Funcom community manager made a post on reddit regarding it.

https://www.reddit.com/r/ConanExiles/comments/5npw9b/conan_exiles_dev_blog_8_servers_and_mods/dcdltp9/

**Comment by UltimateByte** [comment]
lol, I enjoyed reading other comments.
Thanks for info.
Well, too bad. Let's close this until it's really supported...

**Comment by c0reTV** [comment]
http://steamcommunity.com/app/440900/discussions/0/133256240745218195/

**Comment by UltimateByte** [comment]
@c0reTV From our last testing, Linux server packages are empty at the moment.

**Comment by c0reTV** [comment]
@UltimateByte ye the Linux ist empty but you need windows files if no won´t using wine then try with mono

**Comment by UltimateByte** [comment]
LGSM only supports native Linux servers. Wine is a mess and it's not to our liking to run Windows stuff on our Linux machines.
However, we tolerate servers that integrate mono libraries on their own, otherwise we couldn't support unity engine servers.

**Comment by dgibbs64** [comment]
Happy to reopen this when Linux support is ready

**Comment by c0reTV** [comment]
@dgibbs64 please make script thanks!

**Comment by dgibbs64** [comment]
https://steamdb.info/app/443030/depots/ there is a Linux server depot however I dont think there is a linux binary yet

**Comment by dgibbs64** [comment]
Correction there looks like a binary is available. Please can someone confirm Linux is now available
ConanSandbox\Binaries\Linux\ConanSandboxServer

**Comment by RobethX** [comment]
@dgibbs64 I downloaded appid 443030 on my Linux server and it seems to be empty. Where did you see the binary? I can take a look and test it out.

**Comment by UltimateByte** [comment]
It appears that there are now actual depots for Linux !
https://steamdb.info/app/443030/depots/

**Comment by Shiryu75** [comment]
I also noticed the presence of Linux binary. However, when i try to start it, it speaks of a missing libsteam_api.so that i cannot find anywhere :( Any ideas ?

**Comment by UltimateByte** [comment]
@Shiryu75 This is a common error that LGSM fixes :)
See how it's doing and adapt the command to your case: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/fix_steamcmd.sh#L26

**Comment by RobethX** [comment]
@Shiryu75 I downloaded libsteam_api.so from the [Steamworks.NET](https://github.com/rlabrecque/Steamworks.NET/tree/master/Plugins/x86_64) repo and ran the ConanSandboxServer binary with it, but I got this error: `Using jemalloc.
Disabling core dumps.
Preparing to exit.Shutting down and abandoning module NetworkFile (4)Shutting down and abandoning module StreamingFile                         (3)Shutting down and abandoning module SandboxFile (2)Shutting down and abandoning module PakFile (1)Exiting.Exiting ab                        normally (error code: 1)`

**Comment by Shiryu75** [comment]
Thank you Ultimate. I'm afraid I can't use that trick because i'm personnaly using Windows and it's just my remote dedicated server that's on Linux. I've always used it for creating server. I think since it's not my OS, i can't use that fix.

Yeah i'm having the exact same error RobethX. Either we lack something to run the server, or the binairy isn't working yet.

**Comment by RobethX** [comment]
@Shiryu75 I was looking for some more evidence on it, but I was drawing the same conclusion that the depot is incomplete. I was going to try using the content from the windows depot with with the binaries from the linux depot just to see if I can manage to get it running.

**Comment by Shiryu75** [comment]
@RobethX haha we had the same idea then :) i'm currently downloading the windows one to get the content. I'm at 72% right now. Updates soon.

**Comment by Shiryu75** [comment]
It seems to be a lot better mixing windows and linux depots : Windows to get the content and Linux to get the proper binaries. However I still get lots of errors about missing things :

```
[2017.03.09-09.04.52:481][  0]LogPaths:Warning: No paths for game localization data were specifed in the game configuration.
[2017.03.09-09.04.52:481][  0]LogInit:Warning: No paths for engine localization data were specifed in the engine configuration.
[2017.03.09-09.04.52:482][  0]LogSlate:Warning: FCoreStyle assets not detected, skipping FCoreStyle initialization

```
then
```
1001[2017.03.09-09.04.52:716][  0]LogLinker:Warning: Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
[2017.03.09-09.04.52:716][  0]LogUObjectGlobals:Warning: Failed to load '/Engine/EngineDamageTypes/DmgTypeBP_Environmental': Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
1001[2017.03.09-09.04.52:716][  0]LogLinker:Warning: Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
[2017.03.09-09.04.52:716][  0]LogUObjectGlobals:Warning: Failed to load '/Engine/EngineDamageTypes/DmgTypeBP_Environmental': Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
[2017.03.09-09.04.52:716][  0]LogUObjectGlobals:Warning: Failed to find object 'Class /Engine/EngineDamageTypes/DmgTypeBP_Environmental.DmgTypeBP_Environmental_C'
-09.04.52:716][  0]LogLinker:Warning: Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
[2017.03.09-09.04.52:716][  0]LogUObjectGlobals:Warning: Failed to load '/Engine/EngineDamageTypes/DmgTypeBP_Environmental': Can't find file '/Engine/EngineDamageTypes/DmgTypeBP_Environmental'
[2017.03.09-09.04.52:716][  0]LogUObjectGlobals:Warning: Failed to find object 'Class /Engine/EngineDamageTypes/DmgTypeBP_Environmental.DmgTypeBP_Environmental_C'

```

i tried to look for those files :
```
$ locate EngineDamageTypes
/home/steam/Steam/conan/Engine/Content/EngineDamageTypes
/home/steam/Steam/conan/Engine/Content/EngineDamageTypes/DmgTypeBP_Environmental.uasset
```
It found something but the path is different from the error (my locate has found a "Content/" between Engine/ and EngineDamageTypes/)

Then more error 

```
[2017.03.09-08.51.05:981][  0]LogUObjectGlobals:Error:  Can't find 'engine-ini:/Script/Engine.Engine.DefaultMaterialName' in configuration file section=/Script/Engine.Engine key=DefaultMaterialName ../../../ConanSandbox/Saved/Config/LinuxServer/Engine.ini 
[2017.03.09-08.51.05:981][  0]LogUObjectGlobals:Error:  Can't find 'engine-ini:/Script/Engine.Engine.DefaultMaterialName' in configuration file section=/Script/Engine.Engine key=DefaultMaterialName ../../../ConanSandbox/Saved/Config/LinuxServer/Engine.ini 
```

`[2017.03.09-08.51.05:981][  0]LogUObjectGlobals:Warning: Failed to find object 'Material None.'
`
This is getting quite messy and complicated, reinforcing the idea of incomplete depot :(

**Comment by jaredballou** [comment]
FYI: Having worked on a Windows game server manager script for Conan, I can say this game is a hot mess. There are piles of unsolved bugs, console warning spam that fills up disks, and outright wrong documentation or broken/missing features. I'd be cautious to take this on unless it comes with a disclaimer that it's going to be a bumpy ride :)

**Comment by dgibbs64** [comment]
@jaredballou sounds like rust server then ;-P. Thanks for the heads up

**Comment by gormieNO** [comment]
There have been some changes to the Linux Dedicated server for Conan. Not sure if you guys have had the time to look into this or done any test yet? But still, looks like "rust" in logs, but better running. 
Last changes was yesterday, ref. the URL : https://steamdb.info/depot/443032/history/

**Comment by dgibbs64** [comment]
I am unable to find any details about a non wine version of Conan Exiles server. I will close this issue until a stable Linux version is released
