### ISSUE TITLE
Minecraft server not starting up

### ISSUE THREAD

**Issue by KillerAntMC** [GameServerManagers/LinuxGSM#1285]
Hello, I wanted to use LGSM for my minecraft server so I started testing it on a VPS. I went through the install process and tried to startup the server but I received this error:

> [ FAIL ] Starting mc-server: Executable java -Xmx1024M -jar minecraft_server.jar was not found

I checked in the serverfiles folder and the default jar it generates was right there. I figured if I did the debug command, it would show me what was wrong. Instead, the server actually started up. My VPS is running debian 8. What could be the issue? This is the whole log from the finished installation to it running with debug mode: [http://pastebin.com/Ptjn11s4](url)

**Comment by ChaosMTA** [comment]
This is what my PR resolves
https://github.com/GameServerManagers/LinuxGSM/pull/1283

**Comment by ChaosMTA** [comment]
@KillerAntMC Please change the line in your mcserver file:
`executable="java -Xmx${javaram}M -jar minecraft_server.jar"`

To:
`executable="java -Xmx${javaram}M -jar ${filesdir}/minecraft_server.jar"`

Does it resolve the issue for you?

**Comment by KillerAntMC** [comment]
It works now, thanks!

**Comment by UltimateByte** [comment]
Fix merged
