### ISSUE TITLE
ARMA 3 Server to Client bikey issue

### ISSUE THREAD

**Issue by whoathere** [GameServerManagers/LinuxGSM#1292]
When I try to connect to my Arma3 server I get the following error:
![img_1388](https://cloud.githubusercontent.com/assets/24444421/22556351/6ec64fe6-e92c-11e6-8628-563f8edf3170.JPG)

The bottom of the error states that the server fails my clients pbo's of the mod because it doesnt have the correct key for the mod, but other servers with the mod dont complain about my clients content and I downloaded the epoch0400.bikey from epochs web site and place it in the serverfiles/keys directory.

**Comment by whoathere** [comment]
Ok. It required a server restart and now it recognizes the pbo's. Is there a way to change the profile? specifically the .arma3profile file?

**Comment by UltimateByte** [comment]
I got no clue about this and this is obviously not an LGSM issue. Github is used for development.
See on our Discord & Steam group, you got way more chances to get help there. https://github.com/GameServerManagers/LinuxGSM/wiki/Support
