### ISSUE TITLE
Server Request: Ballistic Overkill

### ISSUE THREAD

**Issue by ptrj** [GameServerManagers/LinuxGSM#1293]
Another multiplatform FPS shooter

Game:
http://store.steampowered.com/app/296300/
https://steamdb.info/app/296300/

Dedicated server: 
https://steamdb.info/app/416880/

Thanks you

**Comment by UltimateByte** [comment]
Official doc (pretty poor): http://www.ballisticoverkill.com/game-guides/how-to-download-and-update-ballistic-overkill-dedicated-server.html

**Comment by hurdad** [comment]
added to dev branch https://github.com/GameServerManagers/LinuxGSM/tree/develop/BallisticOverkill

**Comment by dgibbs64** [comment]
Now merged in to develop and complete ready for release
