### ISSUE TITLE
goldsource cfg files are ignored

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1296]
There are no start parameter .cfg file reference for goldsource engine servers (verrified for hldmserver and csserver). I don't know if they support it, but before, server.cfg used to be edited to be `exec game-server.cfg` as well, so that was fine. But according to NeoMaat on Discord, this isn't the case at the moment.

**Comment by hurdad** [comment]
goldsource doesn't like the '-' hypen in filenames. It works if you change it to underscore '_'

**Comment by UltimateByte** [comment]
A user tested `exec hldm-server.cfg` into server.cfg and it worked for him.
But that isn't the point.

**Comment by hurdad** [comment]
ahh yes I understand this issue now

**Comment by hurdad** [comment]
@UltimateByte have you tried '+servercfgfile server.cfg' ?
I know it works for svencoop..
https://www.joe.to/cstrike/ents/command_line_options.html

**Comment by UltimateByte** [comment]
Thanks @hurdad , this needs to be added to goldsource servers.

**Comment by hurdad** [comment]
so for counter-strike beta, which is an super old version of half life, it doesn't support '+servercfg' so I added this in the fix file 
echo "exec ${servercfg}" > "${servercfgdir}/${servercfgdefault}"
like you said in your first post.
-alex
