### ISSUE TITLE
SteamCMD Error 0x602 or 0x202

### ISSUE THREAD

**Issue by Edou68FR** [GameServerManagers/LinuxGSM#1298]
Hello, firstly, don't be afraid if i do some mistakes is english (i'm french) :) 
Ok so i have a problem with SteamCMD and LGSM too : I tried to install CS:GO server with lgsm script, i have done everything fine, after `./csgoserver install` it downloads everything, and when it comes to steamcmd installation parts (only app_update commmand) it firstly write error 0x202 and then lgsm redo the same things, and secondly it write 0x602 after about 60% of download. And then it restart the download again and again always with this error 0x602. 

**Specs** : 
_Debian 8 Kernel_ : 3.16.0-4-amd64 
I'm running **Proxmox** for creating **VM**, and i use **port forwarding** with 1 ip, the VM is actually at 12 GB of ram and 10GB of disk.

Something strange is that i can install TF2 server on an other VM wich is just a copy, and it works actually. Strange Strange...

I can give more info if you wan't, feel free to ask, i will answer :p

**Comment by UltimateByte** [comment]
Hi,

Wrong place to ask, please follow this guide
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
