### ISSUE TITLE
Need General Info Regarding dedicated game servers

### ISSUE THREAD

**Issue by SCH94** [GameServerManagers/LinuxGSM#1299]
Whats the system requirements to run game servers ? can i host dedicated game server on this server?

My server specifications :   

OS :	ubuntu-14.04-x86_64.tar.gz
RAM: 3.46GB / 4GB
Space : 147.88GB / 350GB
Bandwidth : 113591MB / 2000000MB

Note : there is already a torrent site hosted on my server

**Comment by UltimateByte** [comment]
Totally irrelevant server specs + you obviously didn't read our guide on how to get help. This is the wrong place man, github is for development.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
Ultimately, Rust won't require the same resource as an 1.6 server so... This question, asked this way, is totally irrelevant as well.
