### ISSUE TITLE
Addition of Stripper:Source for mods installation

### ISSUE THREAD

**Issue by Technoblazed** [GameServerManagers/LinuxGSM#1300]
Seems like having an easy install for Stripper:Source the same way as metamod and sourcemod are installed would be pretty useful.

**Comment by UltimateByte** [comment]
No problem for me to add. But link, doc?

**Comment by Technoblazed** [comment]
Latest linux download: http://www.bailopan.net/stripper/snapshots/1.2/stripper-1.2.2-git125-linux.tar.gz (Will never be updated)
Guide: http://www.bailopan.net/stripper/snapshots/1.2/

**Comment by UltimateByte** [comment]
Guide link is wrong. I guess it's this one: http://www.bailopan.net/stripper/
Not updated anymore ? How do you know ? Works with all Source Servers ?

**Comment by Technoblazed** [comment]
Works with css and csgo at least, not really had the need to test any others. It basically just allows entity changes on maps and removing items that can cause server crashes.

**Comment by UltimateByte** [comment]
Could be very useful for gmod as well if it works. :)
If it works with css and csgo, it probably also works with tf2 and other source engine servers.
For advanced users though. Implementation should be easy, 3 or 4 lines of code, with the framework that i made already, including one line to prevent metamod dir from being removed upon uninstall. :)

**Comment by Technoblazed** [comment]
It works for Half-Life 1, so I'm GONNA ASSUME.

**Comment by Technoblazed** [comment]
https://i.tech-no.me/040217112302.png

All the games it supports.

**Comment by UltimateByte** [comment]
Perfect, good to know.
Did you see this ?
https://github.com/GameServerManagers/LinuxGSM/wiki/mods-install-update-remove#how-does-it-work

**Comment by h3o66** [comment]
The latest build is currently this one:
http://www.bailopan.net/stripper/snapshots/1.2/stripper-1.2.2-git129-linux.tar.gz

They also moved the source code a while ago to github, but the builds are still on the original server:
https://github.com/alliedmodders/stripper-source

**Comment by h3o66** [comment]
Done in Release 20.6.0
