### ISSUE TITLE
backups directory to be moved to lgsm dir

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1301]
Backups dir is currently located in rootdir. This should be moved to lgsmdir

**Comment by UltimateByte** [comment]
should we move logs as well ?

**Comment by dgibbs64** [comment]
@UltimateByte logs is already in the lgsmdir. It states in the wiki doc that backups are located in lgsmdir/backups however in reality they are located in rootdir/backups

**Comment by UltimateByte** [comment]
Nope, logs are in ${rootdir] currently, that's why i'm asking.

```bash
scriptlogdir="${rootdir}/log/script"
consolelogdir="${rootdir}/log/console"
```

**Comment by dgibbs64** [comment]
I have decided to leave these dirs where they are.
