### ISSUE TITLE
Missing line jump for tmux 1.8 error message in logs

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1307]
Minor display bug in logs.

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_start.sh#L92-L96

Sample output:
![tmux bug](https://cdn.discordapp.com/attachments/135126471319617536/279245074859294720/Y8Q92g5.png)

May the next one comitting something assign to this issue and address it :)

**Comment by dgibbs64** [comment]
I am not sure of the reason for this issue. Very odd

**Comment by UltimateByte** [comment]
This issue is due to `echo >>` that doesn't jump lines.
Easy fix would be to make a multiple line echo.

```bash
echo "Console logging disabled: Bug in tmux 1.8 breaks logging
https://gameservermanagers.com/tmux-upgrade
Currently installed: $(tmux -V)" > "${consolelog}"
```

**Comment by UltimateByte** [comment]
Fixed. Ready to merge.
Closing to clean my tasks list.
