### ISSUE TITLE
Arma 3 Server dont start.

### ISSUE THREAD

**Issue by BlutwurstPro** [GameServerManagers/LinuxGSM#1311]
When i try to start my Arma3 Server there is the following error:

>   ./arma3server: line 164: syntax error near unexpected token `)'
> 
>  ./arma3server: line 164: `      curlpaths="$(command -v curl 2>/dev/null) $(which curl >/dev/null 2>&1) /usr/bin/curl /bin/curl /usr/sbin/curl /sbin/curl)"'

At line 164 is a comma too much. 
If i remove the comma, there comes another Error

> ./arma3server: line 208: unexpected EOF while looking for matching `"'
> ./arma3server: line 220: syntax error: unexpected end of file

How can i fix this?

**Comment by UltimateByte** [comment]
You messed up your script syntax. Download it again and don't ruin it again.
Protip: Edit it with nano or vi, not with a windows text editor with a useless FTP for that purpose.
Protip 2: User issues are not solved on github, github is for development.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
