### ISSUE TITLE
Ark Server Require Minimum RAM requirements

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1312]
I am looking to find out the minimum RAM requirements for ARK to warn users with insufficient RAM the server wiki page states a min of 6GB. Is this correct?

**Comment by UltimateByte** [comment]
![ARK RAM](http://i.imgur.com/LWnW5jv.jpg)
![ARK RAM DETAILS](http://i.imgur.com/C1NE04v.jpg)

**Comment by UltimateByte** [comment]
So, takes around 3GB or so for an empty server. I assume with some SWAP, 4GB RAM would be enough.

**Comment by dgibbs64** [comment]
brilliant! I will get that added. I think it might be a good idea to go though as many servers as possible to  add these in. Im going to look in to getting one server with all servers installed.

**Comment by SkullMasher** [comment]
Can confirm. 1 year old empty ark server here. 
![ark_memory_usage](https://cloud.githubusercontent.com/assets/4488386/22855086/3ff7ad36-f07a-11e6-9c48-8ebd34631d5c.png)
I have other lgsm game server in production if you want some ram usage.
