### ISSUE TITLE
Update: Handle case when current build version not found

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1315]
If a user has updateonstart=on on a non steamcmd server and the server was never started before, it will fail to start. If current build is not found, it should warn about it, then go on to other operations.

**Comment by dgibbs64** [comment]
not sure why the user would have this in the first place.

**Comment by UltimateByte** [comment]
User sets up gameserver settings, with updateonstart on, then installs the server, then won't be able to start. It did happen.

**Comment by UltimateByte** [comment]
(teamspeak should allow reproducing the issue)

**Comment by dgibbs64** [comment]
Yup i understand now :)
