### ISSUE TITLE
[Server Request] Killing Floor 2

### ISSUE THREAD

**Issue by cedarlug** [GameServerManagers/LinuxGSM#1316]
From today's posting on the hlds_linux mailing list:

> We are working on Linux servers for Killing Floor 2, and they are getting
> close. We'll have more info soon.
>
> John Gibson
> President
> Tripwire Interactive
 >www.tripwireinteractive.com

**Comment by hurdad** [comment]
nice!

**Comment by cedarlug** [comment]
Rumor is that it will be released tomorrow.

**Comment by DigitalFriends** [comment]
Awsome, following..

**Comment by SkullMasher** [comment]
Damn my email as been received loud and clear ! AWESOME news. I'm still hosting 2 popular KF1 server with LGSM.
I'm in love with your quick reaction as well. Let's keep it up.

**Comment by cedarlug** [comment]
It's one day after the presumptive release.  

I attempted to just fetch the files from steam to see if there was anything in the Linux archive, but one needs to be authorized (own the game) in order to access the repo.

Anyone with game ownership care to see if the repo is populated?
appid: 232130 (Is the [posted Windows appid](https://developer.valvesoftware.com/wiki/Dedicated_Servers_List) )

**Comment by dgibbs64** [comment]
https://steamdb.info/search/?a=app&q=killing+floor+2

**Comment by cedarlug** [comment]
appid 232090 then?

**Comment by dgibbs64** [comment]
There is a sub id for dedicated servers in the KF2 game appid. However not sure if thats what you are after
https://steamdb.info/app/232090/subs/

**Comment by cedarlug** [comment]
Yep  - 232090 is the actual game...I read the top of the link too quickly.  My eyes focused on the "Updated 2 hours ago" entry. 

It still shows no repo update for the dedicated server for 27 days.

**Comment by cedarlug** [comment]
A short update from the devs:
```
Hey Cedar,

The linux server is in test now.  We hope to have it ready for the next content patch.

Cheers,
Andrew
```

**Comment by cedarlug** [comment]
Released?
https://steamdb.info/app/232130/

**Comment by cedarlug** [comment]
Looks to be true!  Needs to have game ownership to download though, otherwise you get "No Subscription" when attempting to acquire.

**Comment by Twonkk** [comment]
would enjoy seeing this as a LGSM supported game server. Few friends an myself have been playing the "free" weekend of KF2 and enjoy it quite a bit over the 1st. will keep tabs on this =D

**Comment by USSpectre1** [comment]
So it looks as though the dedicated server files for Linux have been released for this, can we hope to see a LGSM script for this soon?

**Comment by dgibbs64** [comment]
I am working on a major update to LGSM currently. I will release it as part of or just after the major update

**Comment by USSpectre1** [comment]
@dgibbs64 You're awesome, thanks man! Happy Easter!

**Comment by PeterFour** [comment]
@cedarlug Did you manage to have access ? I tried using the appid you linked but nothing, even using my personal account in where I have the game

**Comment by cedarlug** [comment]
@PeterFour - unknown status.  I'll look into it to see if it ever materialized.

**Comment by dgibbs64** [comment]
Yup still no sign of this server.  Being available. This issue may have to be closed until it is actually released

**Comment by PeterFour** [comment]
Looks like server is now available with appid 232130.
Testing it as we speak

**Comment by SkullMasher** [comment]
That is indeed a beta linux server that just got release, let's test that. Quoting from the mailing list.

> Hey Everyone,
> 
> A new server build is now available for Killing Floor 2.  The client will go live at 1 pm eastern time.  This build also includes a beta version of the Linux dedicated server which can be downloaded from Steam CMD using the same appid and command.  To see more information on The Summer Sideshow visit the announcement page here.
> 
> Cheers,
> Andrew
>

**Comment by PeterFour** [comment]
I have an instance running, I'll see in a few days how it behaves

**Comment by YellowOnion** [comment]
@PeterFour I can't find the binary anywhere, just Win64, and a few .so files.

**Comment by PeterFour** [comment]
@YellowOnion Binaries are located in `/Binaries/Win64/KFGameSteamServer.bin.x86_64`.

It has been reported to the mailing list that it doesn't make any sense for now, so it may or may not move later. But now at least you can launch the server :)

**Comment by dementedusa** [comment]
I was wondering if any headway has been made to this?  I was looking around and found instructions to running a kf2 server on linux    https://wiki.tripwireinteractive.com/index.php?title=Dedicated_Server_(Killing_Floor_2)#Linux

**Comment by dgibbs64** [comment]
Sadly not yet. I am away currently so development is difficult. KF2 will be a priority when I get back.
