### ISSUE TITLE
CSGO source mod how to make yourself mod using cmd?

### ISSUE THREAD

**Issue by troublishone** [GameServerManagers/LinuxGSM#1319]
I'm going to start this by saying i'm using **_PuTTY_**, so all I have to work with is a _cmd_, but with the help of **LGSM** I managed to get my CS server up and running, and it works great. Great! Next step I installed the only available mods: source mod and metamod... **Annnnnnd** have no clue how to give myself admin. how do I do that? I see that there are tons of sites/videos telling you how you just need to edit the text file, but I dunno how i'm supposed to do that with the _cmd_? I could legit just be the stupidest human being to walk the earth on this one, but some help would still be really nice.

**Comment by marvinl97** [comment]
Github is for development and not for user/non-script issues.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

Do yourself a favor and learn the basics of Linux if you want to administrate a server.
LGSM isn't a replace for that. https://wiki.alliedmods.net/Adding_Admins_(SourceMod)

**Comment by SkullMasher** [comment]
Go to or create your/server/folder/csgo/addons/configs/admins.cfg and provide one of these information.
```
Admins
{
	"Admin Name"
	{
		"auth"		"[steam|name|ip]"
		"identity"	"[unique id]"
		"[option1]"	"[value1]"
		"[option2]"	"[value2]"
		/* .... */
	}
}
```

**Comment by marvinl97** [comment]
@SkullMasher I think he doesn't know how to do that. (vi, nano, cd, ...). He has to learn the basics.
