### ISSUE TITLE
Teamspeak keeps updating Versions again

### ISSUE THREAD

**Issue by J3n50m4t** [GameServerManagers/LinuxGSM#1320]
`./ts3server update`  keeps updating version `3.0.12.4 amd64 ` to `3.0.13.6 amd64` everytime the script runs.

The server updates successfully, but the script always finds outdated versions 
![image](https://cloud.githubusercontent.com/assets/13681191/23058598/0dc644d2-f4f6-11e6-8a61-93f55a915505.png)

**Comment by ChaosMTA** [comment]
The script checks your console logs to find out your current version. Does this continue to happen after the server runs in normal operation for awhile?

**Comment by UltimateByte** [comment]
Also, the script checks current version from latest log, so if you changed your server time at some point, could explain the issue. Try clearing your ts3 logs, then restart the server, and try to update again.

**Comment by J3n50m4t** [comment]
The server keeped updating for 3 days with every from job. 
I now cleared the logs. Will see if it updates tonight

**Comment by UltimateByte** [comment]
Go clear serverfiles/logs as well.

Since i don't have the issue, must be something wrong on your side.

```
ts3terageek@webserver:~$ ./ts3server update
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

No update available:
        Current version: 3.0.13.6
        Available version: 3.0.13.6

[  OK  ] Update ts3-server: No update available
```

**Comment by J3n50m4t** [comment]
Didn't work as well. 
I also tried to delete everything and started new install but I run into the same problem. Are there may any other logs? 

```
ts3server@server:~$ ./ts3server stop
[  OK  ] Stopping ts3-server: TeamSpeak 3 Server
ts3server@server:~$ rm serverfiles/logs/*
ts3server@gspserver:~$ ./ts3server update
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.12.4 amd64
        Available build: 3.0.13.6 amd64


Applying update...
extracting teamspeak3-server_linux_amd64-3.0.13.6.tar.bz2...OK
copying to /home/ts3server/serverfiles...OK
[  OK  ] Starting ts3-server: TeamSpeak 3 Server
[  OK  ] Stopping ts3-server: TeamSpeak 3 Server
[  OK  ] Alert ts3-server: Sending Pushbullet alert
```

**Comment by J3n50m4t** [comment]
After second update it works. Thanks @UltimateByte

**Comment by JimTR** [comment]
just a thought why would you need to do the above ? it looks like the script is not keeping up to date

**Comment by J3n50m4t** [comment]
I had a new fresh install with no changes at all (Ubuntu 16.04)
Updated successfully to latest version but the script wasn't able to check correctly
It works now, will have to wait for next update to check if it bugs again

**Comment by UltimateByte** [comment]
Something went wrong on the machine that i can't figure out. 
update_ts3.sh script finds latest logs by searching in ts3server*_0.log
Maybe for some reason your latest log was named ts3server*_1.log, and that's my only guess for now.

I can't either figure it out or reproduce with the few info that was given, and never had the issue even though i've been running several ts3servers using LGSM during the last years.

So unless something changes about this issue, the current status is:  
`cannot reproduce`

**Comment by J3n50m4t** [comment]
I already have 2 logs with same stamp again
I can't provide more informations for now. Sorry 

```
ts3server@server:~/serverfiles/logs$ ls
ts3server_2017-02-18__15_10_51.508109_0.log  ts3server_2017-02-18__15_10_51.508109_1.log 
```

# 0.log


```
2017-02-18 15:10:51.508163|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.0.13.6 (2016-11-08 08:48:33)
2017-02-18 15:10:51.508270|INFO    |ServerLibPriv |   |SystemInformation: Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 Binary: 64bit
2017-02-18 15:10:51.508306|INFO    |ServerLibPriv |   |Using hardware aes
2017-02-18 15:10:51.509119|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
2017-02-18 15:10:51.509166|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
2017-02-18 15:10:51.509381|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
2017-02-18 15:10:51.526117|WARNING |Accounting    |   |Unable to find valid license key, falling back to limited functionality
2017-02-18 15:10:52.017941|INFO    |              |   |Puzzle precompute time: 465
2017-02-18 15:10:52.018118|INFO    |FileManager   |   |listening on 0.0.0.0:30033, :::30033
2017-02-18 15:10:52.038274|INFO    |CIDRManager   |   |updated query_ip_whitelist ips: 127.0.0.1/32, ::1/128,
```

# 1.log

```
2017-02-18 15:10:52.038062|INFO    |VirtualServer |1  |listening on 0.0.0.0:9987, :::9987
2017-02-18 16:05:26.985979|INFO    |PktHandler    |1  |Dropping client 6 because of ping timeout 19 0 0
2017-02-18 17:57:35.961463|INFO    |PktHandler    |1  |Dropping client 8 because of ping timeout 19 0 0
```

**Comment by cedarlug** [comment]
I copied your ts3server....0.log file from your posting above and placed it locally.

When I parse your 0.log with the updatescript version snarf (line 51), it pulls out the correct value:

```bash
currentbuild=$(cat $(find ./* -name 'ts3server*_0.log' 2> /dev/null | sort | egrep -E -v '${rootdir}/.ts3version' | tail -1) | egrep -o 'TeamSpeak 3 Server ((\.)?[0-9]{1,3}){1,3}\.[0-9]{1,3}' | egrep -o '((\.)?[0-9]{1,3}){1,3}\.[0-9]{1,3}' | sort -V | tail -1)
gamer@cryptbookpro:/tmp$ echo $currentbuild
3.0.13.6
```
So --- You LIKELY have another log file somewhere that's being pulled in.
What does just this yield:
```bash
find ./* -name 'ts3server*_0.log' 
```

**Comment by J3n50m4t** [comment]
As I wrote it now works I can't help to reproduce, sorry. 
I deleted all logs but still here. 
```
ts3server@server:~$ find ./* -name 'ts3server*_0.log'
./serverfiles/logs/ts3server_2017-02-18__15_10_51.508109_0.log
```
