### ISSUE TITLE
[Alerts] New Notification platforms

### ISSUE THREAD

**Issue by NickParks** [GameServerManagers/LinuxGSM#1321]
Im Hijacking this post to list the work being done on alerts. @dgibbs64

The following alert systems are being added

Working on now:
- [x] Pushbullet
- [x] Email
- [x] IFTTT
- [x] Discord
- [x] Telegram
- [x] Pushover
- [x] Email API (MailGun)
- [x] Rocket.chat
- [x] Slack
Ones being looked in too:
- [ ] Syslog
- [ ] SNMP
- [ ] Trello
- [ ] Cachet
- [ ] Sendgrid

Hello,

So I was looking at the monitor functions and noticed it only has push bullet & email support. 

These are perfectly fine and usable, but I was thinking that it would be nice to also include support for Telegram or Discord?

Obviously both would take extra configurations and such just like the rest but I feel it would make life a lot easier for people (especially the Discord one considering how many people are starting to transfer over to discord).

I understand these would take time and there's higher up things on the priority, but just a thought :)

And if it's not too much of a hassle would it be difficult to add a method to send a POST request to a specified URL? Could include data like server name/details/etc. Personally I would find this super useful as a replacement for my current monitoring system.

~ Nick

**Comment by UltimateByte** [comment]
Sweet ideas. Telegram API seems to be pretty similar to Pushbullet. A post to an URL shouldn't be that hard to implement. As for Discord, i don't know about their API, but it seems to be pretty well elaborated, so seems doable.

**Comment by dgibbs64** [comment]
Yeah this is a great idea. I think discord support would be really great. @Scarsz I think might be the best person for this one

**Comment by Xseba360** [comment]
Integration with Discord seems to be very easy as well :)
https://support.discordapp.com/hc/en-us/articles/228383668
https://discordapp.com/developers/docs/resources/webhook
It can also be made compatible with Slack, which makes it automatically compatible with Discord.

**Comment by UltimateByte** [comment]
To sum up, requested platforms are:

- Discord
- Slack
- Telegram
- Pushover 
- More... ?

Rework to alert functions will probably be required.

**Comment by SirNickParks** [comment]
Little late to reply. 

But yes, basically the most used gaming services which are Discord, Telegram, etc. As well whatever the staff/development team may use which is slack/telegram.

And if possible to add a straight up POST mechanic into it, it may not work with all services but it definitely opens the door for more possibilities without having to have you guys add them for us.

**Comment by faflfama** [comment]
Could give you a little bash script for discord+Webhook if you are interested and didnt already work that one out^^

**Comment by dgibbs64** [comment]
@faflfama Yeah that would be great. Im working on other areas currently so haven't had a chance to look in to this yet. So any exmaples would be awesome 👍

**Comment by faflfama** [comment]
Put in in here, hope its readable^^

https://pastebin.com/ieFTUr8V

**Comment by dgibbs64** [comment]
@faflfama just tested it and it works!! Thank you

**Comment by dgibbs64** [comment]
Telegram is now up and running https://github.com/GameServerManagers/LinuxGSM/wiki/Telegram

It will be available next release

**Comment by MarkL4YG** [comment]
I'd like to throw in "Cachet" into the list.

**Comment by dgibbs64** [comment]
Added more info abot what system are being worked on above

**Comment by jimwald1221** [comment]
It's a bit corporate but HipChat would be nice as well.

**Comment by TheUdK** [comment]
Any chance for Slack in the foreseeable future?

**Comment by dgibbs64** [comment]
#2543

**Comment by dgibbs64** [comment]
Re-opening to add new
