### ISSUE TITLE
Add option to remove non-compressed files when using FastDL

### ISSUE THREAD

**Issue by NickParks** [GameServerManagers/LinuxGSM#1322]
While it doesn't matter much, it would be a nice option that if the user is using bzip2 compression when generating FastDL files, to remove the original file that is not compressed.

Not too sure if GMOD/Source will download both files or take only the compressed one (haven't tested it myself tbh). But either way it can't hurt to have the option :)

~ Nick

**Comment by UltimateByte** [comment]
I think I had a good reason for not removing them, because I remember myself having the same idea as you. I would have to dig back into it to see if it was really a good reason or not. :o))

**Comment by UltimateByte** [comment]
![option fastdl gmod](http://i.imgur.com/stc2ZA6.jpg)

**Comment by UltimateByte** [comment]
Will be added upon next merge

**Comment by UltimateByte** [comment]
Closing to clean my tasks list.
Code is ready to be merged into develop branch for next release.

**Comment by UltimateByte** [comment]
Just a follow up: FastDL will change a lot. And actually, uncompressed files will be removed automatically since they are not necessary.
