### ISSUE TITLE
New dependencies coming for TF2

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1328]
Announcement: https://www.reddit.com/r/tf2/comments/5v7s6y/server_operators_heads_up_updated_system/

Errors when you don't have dependencies: https://hastebin.com/zugexitosu.sql

Confirmation that it will be coming to master TF2: https://i.imgur.com/NTx2NEl.png

Thanks @BurningSmile

**Comment by dgibbs64** [comment]
Added libcurl to the dependencies for next release
