### ISSUE TITLE
Update how you grab latest Teamspeak 3 version

### ISSUE THREAD

**Issue by phit** [GameServerManagers/LinuxGSM#1330]
Teamspeak now offers a json endpoint to check for the latest version, might be a good idea to switch to that to check for a new version.
http://forum.teamspeak.com/threads/128910-Website-amp-Forum-Updates
https://www.teamspeak.com/versions/server.json

**Comment by dgibbs64** [comment]
This is brilliant. Will need to get on this asap

**Comment by UltimateByte** [comment]
Thanks for the info. We need to keep taking care of outdated TS3 that don't support the json yet as well, but to start by a check for this file. :)

**Comment by dgibbs64** [comment]
Looking at this it appears that using the jq command is the better option however it is not available in older distros. this means I would have to increase the minimum requirements for teamspeak. I would like to avoid this and use a method that does not require a dependency if possible. 

a sed guru might be best suited to see if they can filter out the version numbers correctly without requiring jq.

for now the current method still works. However updating is a good idea

**Comment by dgibbs64** [comment]
I have come up with a solution. Kept the old code available and added the option to use the json file if jq is installed.

ada3909e6c7835dc7ebb32d2debc0f9624402bd7
