### ISSUE TITLE
[Rust] Random seed on wipe feature

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1332]
New variable:

`randomseedonwipe="on/off"`

Upon wipe, if `[ "${randomseedonwipe}" == "on" ]; then`
wipe the server
generate `randomseed `within the supported range
apply `seed="rand"`
edit `${rootdir}/${selfname}` and apply `seed="rand"`
`fi`

**Comment by ppedro1** [comment]
Anything being done on this? This feature is kind of important on my current rustserver project.

**Comment by ppedro1** [comment]
If someone is wondering about this/having the same problem that I am (the seed not being random). I resolved this by having my wipe bashscript replace the seed="" with a random number generated by bash.

RDM="$(( ( RANDOM % 2147483647 ) + 1 ))"
sed -i -- 's/^seed=.*/seed="'$RDM'"/g' /path/to/rustconfig.cfg

**Comment by YouMustNot** [comment]
will this get done?

**Comment by spaceneenja** [comment]
At this point it's probably on one of us to make a PR

**Comment by dgibbs64** [comment]
I will be doing this for the next release

**Comment by dgibbs64** [comment]
closing this as a duplicate using issue #2915
