### ISSUE TITLE
Ark server shutdown error

### ISSUE THREAD

**Issue by spannerman79** [GameServerManagers/LinuxGSM#1335]
`lgsm/functions/command_stop.sh: line 275: [: missing `]'`
When running ./arkserver stop

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_stop.sh#L275

**Comment by SkullMasher** [comment]
I can confirm.

**Comment by UltimateByte** [comment]
Easy fix with:

`if [ "${pid}" -gt 1 ]&&[ "${pid}" -le "$(cat /proc/sys/kernel/pid_max)" ]; then`

**Comment by Twonkk** [comment]
can confirm, fix works.  does look like graceful shit down fails, but it should stop after...

**Comment by UltimateByte** [comment]
Yeah, during my testing, I noticed that you need to wait for the server to be started in order for it to stop clean and fast.
Next release will fix this issue.
