### ISSUE TITLE
[Enhancement] ARK server auto manage workshop mods

### ISSUE THREAD

**Issue by spannerman79** [GameServerManagers/LinuxGSM#1336]
As per patch [244.3](http://ark.gamepedia.com/244.3) you can have the server auto manage workshop mods.

Just add `-automanagedmods` to https://github.com/GameServerManagers/LinuxGSM/blob/master/ARKSurvivalEvolved/arkserver#L34

Read the patch notes for more information.

This can be added to the LGSM wiki as well as there is more information about how to manually add workshop mods and referencing the older method of adding workshop mods over the current accepted method

**Comment by UltimateByte** [comment]
Just like Garry's mod, that's awesome !

**Comment by spannerman79** [comment]
> Just like Garry's mod, that's awesome !

I'm having a bad day @UltimateByte lol, I assume to add the switch I change L34 to `parms="\"TheIsland?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}?\"" to `parms="\"TheIsland?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}?\" -automanagedmods"` (added onto the end

**Comment by UltimateByte** [comment]
@spannerman79 You need to add this before `\"`

**Comment by CamaroKing59** [comment]
so what should the line look like?

**Comment by UltimateByte** [comment]
@CamaroKing59 As I said, I assume what would work is what @spannerman79 said, but ending with `Port=${port}? -automanagedmods\""`

**Comment by philippemarlin** [comment]
i have change the line in arkserver but when i do ./arkserver mi it's always show that is fail to install mods :(

**Comment by spannerman79** [comment]
> i have change the line in arkserver but when i do ./arkserver mi it's always show that is fail to install mods :(

Read the patch notes which I supplied.
mi is not for ark but for games like garrys mod, etc

**Comment by UltimateByte** [comment]
@philippemarlin https://github.com/GameServerManagers/LinuxGSM/wiki/mods-install-update-remove
This was never intended for any kind of workshop addons.

**Comment by philippemarlin** [comment]
@UltimateByte ok thanks. I see. @spannerman79 ok, so how i can do for ark mod ? i have search a little but only somes said manually

**Comment by philippemarlin** [comment]
My tests :
♦ have put line command with automanagedmods and add mod in /worshop/content/346XXX/ with workshop_download_item 346110 XXXXX validate commands scripted (server launch but mod no actived)
♦ i have try to drag and drop in /serverfiles/ShooterGame/Content/Mods (server launch but mod no actived)
♦ i have try to had too the lines to explain manually in /serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini  + mods folders in /serverfiles/ShooterGame/Content/Mods (server launch but mod no actived)
and to finish /serverfiles/ShooterGame/Saved/Config/LinuxServer/Game.ini(have a error for this one, server dont start. So it sure, its not the solution)
result :
server working but always without mods

**Comment by philippemarlin** [comment]
Solved ! have let the mods in serverfiles folder and add [ARK-MOD-ID].mod from my local server test

**Comment by CamaroKing59** [comment]
i'm confused what did you do

**Comment by philippemarlin** [comment]
finaly mods not working

**Comment by jakepbrown27** [comment]
Hate to ask, anyone got this working? I checked out the patch notes and if I add the
[ModInstaller]
ModIDS=123456567 

The server won't actually start, if I take it out and leave -automanagemods it will, not quite sure where to go at this point as I am pretty new to the linux scene :S

**Comment by spannerman79** [comment]
Seeing as there are two issues here that need to be addressed I'll address the first

---
@UltimateByte using `-automanagedmods` is **incompatable** with the current way that a simple ark server manager should work. 

What `./ShooterGameServer` does when the switch `-automanagedmods` is active is that is spawns a second steamcmd command to download and check the workshop items that have been set in `GameUserSettings.ini`  However LGSM monitors it doesn't accept that extra text output and fails, effectively killing the PID.  

To replicate this is easy - create a new SteamCMD instance by hand, add a workshop mod into `GameUserSettings.ini` and start the server manually without LinuxGSM.  It works correctly **and** downloads the workshop mod.

---

@philippemarlin & @CamaroKing59 & @jakepbrown27 - if you three **actually read the release notes** in particular to what was stated after "On Linux Servers..." on the patch notes you would have at least *some* idea. 

Furthermore if you read the patch notes further onward's you would have read the requirement for workshop mods was changed from `Game.ini` to `GameUserSettings.ini`

**Comment by UltimateByte** [comment]
Thing to check:
https://steamcommunity.com/app/346110/discussions/0/358417008719184407/#c359543542236866883

**Comment by spannerman79** [comment]
> Thing to check:
> https://steamcommunity.com/app/346110/discussions/0/358417008719184407/#c359543542236866883

This is **already** explained in Patch Note [244.3](http://ark.gamepedia.com/244.3) that I **already** stated in my [OP](https://github.com/GameServerManagers/LinuxGSM/issues/1336#issue-210197094)

Seeing as people are too lazy to read actual patch notes

> Windows & Linux Dedicated Servers now support automatic mod download/installation/updating! Just add `-automanagedmods` to your launch commandline and it will do so before the server launches (note for Maps this will not work unless you're specifying the Workshop ID to load a Mod Map). **On Linux Servers, you need to run this script (included with the ARK dedicated server files) once to install SteamCMD: `\SteamCMDInstall.sh`**

**Comment by UltimateByte** [comment]
@spannerman79 To people's defense, patch notes aren't as good as a wiki.
Would you be kind enough to add an entry to the wiki, since you know exactly how to do work with it ?
https://github.com/GameServerManagers/LinuxGSM/wiki
(I already added Ark to the menu, just click it and it will prompt for page creation)

**Comment by spannerman79** [comment]
@UltimateByte seems that you don't read either.

If I add an entry it would be the following

> Because people can't/too lazy/cbf'ed to read https://github.com/GameServerManagers/LinuxGSM/issues/1336#issuecomment-284598650 I highly suggest that you use https://github.com/FezVrasta/ark-server-tools instead for ARK

**Comment by UltimateByte** [comment]
Seems that i read this a while ago and was too busy to re read everything atm I posted. I just put the link as a reminder in case if it was useful.

**Comment by UltimateByte** [comment]
The process to solve this is summed up here
https://github.com/GameServerManagers/LinuxGSM/issues/1401

**Comment by spannerman79** [comment]
> The process to solve this is summed up here
> #1401

Incorrect again

Contents of `SteamCMDInstall.sh` that I mentioned *again* via https://github.com/GameServerManagers/LinuxGSM/issues/1336#issuecomment-291754995

```
#!/bin/bash
# SteamCMD installer

sudo apt-get install lib32gcc1
cd Engine
cd Binaries
mkdir ThirdParty
cd ThirdParty
mkdir SteamCMD
cd SteamCMD
mkdir Linux
cd Linux
wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar -xf steamcmd_linux.tar.gz
```
Correct SteamCMD downloaded for linux - issue #1401 is incorrect and FUD/BS

**Comment by UltimateByte** [comment]
That's exacly what he said.
Exept this would be more relevant as for the dir creation.
````
mkdir -p "Engine/Binaries/ThirdParty/SteamCMD/Linux" && cd "Engine/Binaries/ThirdParty/SteamCMD/Linux"
````
His SteamCMD link and yours are resulting in the exact same file, and your dirs are identical unless i'm blind.

**Comment by spannerman79** [comment]
> That's exacly what he said.

Nope and I'll quote;
> The standard setup process here: https://gameservermanagers.com/lgsm/arkserver/ installs a version of SteamCMD. This version does not support the July2016 automanagedmods functionality from Wildcard in the sense that the **piece of SteamCMD it uses only has the Windows dependencies by default**.

FUD/BS

**Comment by UltimateByte** [comment]
Alllright, I'll just let your pointless debate with yourself going on and keep doing my life.

**Comment by cedarlug** [comment]
@spannerman79 I understand that you're trying to be helpful, but your condescension is getting in the way of your articulation. 

Personally it would seem to me to be helpful if you would take a moment to clarify your points.  You might be completely correct in what you're saying, but you're not conveying your synopsis of the situation well at all. 

Highlighting an unclear point in bold is equivalent to SHOUTING IN ALL CAPS.

**Comment by spannerman79** [comment]
> I understand that you're trying to be helpful, but your condescension is getting in the way of your articulation.

That happened after [this](https://github.com/GameServerManagers/LinuxGSM/issues/1336#issuecomment-292041063) reply. When replies are made to comments indifferent to context you cause confusion and miscommunication.  Doing it several times is inexcusable.



> Personally it would seem to me to be helpful if you would take a moment to clarify your points. You might be completely correct in what you're saying, but you're not conveying your synopsis of the situation well at all.

That was made clear [here](https://github.com/GameServerManagers/LinuxGSM/issues/1336#issuecomment-284598650)



> Highlighting an unclear point in bold is equivalent to SHOUTING IN ALL CAPS.

[Usage of bold](https://www.fonts.com/content/learning/fontology/level-2/text-typography/bold-type-in-text) is emphasising a point - not shouting.

**Comment by cedarlug** [comment]
Closing as unresponsive.

**Comment by Rayzos** [comment]
Hello, do you have to set [ServerSetting] after adding steamcmd in "Engine / Binaries / ThirdParty / SteamCMD / Linux /"?

I think it's a good idea for me ...
