### ISSUE TITLE
how can i get admin's password and  privatekey

### ISSUE THREAD

**Issue by kevinzu007** [GameServerManagers/LinuxGSM#1337]
i have install LinuxGSM on Centos7 x64
./ts3server  start
i don't know  how to get   admin's password and  privatekey
where is it?

**Comment by UltimateByte** [comment]
`./ts3server install`

Then read what's displayed.

Nothing to do on github, closing.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
