### ISSUE TITLE
[SERVER REQUEST] Battlefield Revive

### ISSUE THREAD

**Issue by jenkk** [GameServerManagers/LinuxGSM#1338]
There are Linux Server files available for BF2 under the Revive Project.

With 2142 support coming soon, I'd personally love to see this being available with LGSM.

The Downloads can be found here: https://battlelog.co/downloads.php#server

Once again I would like to thank you all for your great work and making my admin responsibilities much easier 😄

**Comment by hurdad** [comment]
Added Battlefield 2 

- https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/feature/bf2/Battlefield2/bf2server

**Comment by dgibbs64** [comment]
Sadly Battlefield Revive was shutdown by EA. So there are no options for Battlefield 2 Revive. However there are instuctions on the old style server
http://tutorials.section6.net/home/how-to-set-up-a-dedicated-battlefield2-server

**Comment by jrmain** [comment]
Dang, I had no idea. EA wants so desperately to maintain its 'most hated game company' status they'll stop at nothing apparently.

**Comment by dgibbs64** [comment]
Closing this issue as Battlefield Revive is DEEEDD!!

**Comment by sandisk3gb** [comment]
But bf2hub is alive.

**Comment by dgibbs64** [comment]
@sandisk3gb please raise a new issue if bf2servers can be installed still
