### ISSUE TITLE
Running more than 5 servers TF2/Debian

### ISSUE THREAD

**Issue by Gnomesenpai** [GameServerManagers/LinuxGSM#1339]
Hey guys, im currently setting up my new server to deploy out and im having a strange issue when booting servers if i start ./mvmx10_1-5 they all start fine and dandy, but on the 6-8 they get stuck on this:
![image](https://cloud.githubusercontent.com/assets/26032518/23335625/ea20cfa4-fbb0-11e6-92f5-d924706c3af9.png)
The console is giving me no information to what is happening, any suggestions?

**Comment by Gnomesenpai** [comment]
Nevermind, issue was maplists, man im stupid

**Comment by UltimateByte** [comment]
Also, non script issues don't go on github.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
