### ISSUE TITLE
[HELP] Fetching failed 

### ISSUE THREAD

**Issue by PopcornG3** [GameServerManagers/LinuxGSM#1340]
Hi when i try to install my server i have this error for all files .sh 

csgoserver@PixelTeam:~$ ./csgoserver install
    fetching core_dl.sh...FAIL
    fetching core_dl.sh...FAIL

etc ..

**Comment by dgibbs64** [comment]
try ```ping github.com``` see what you get

**Comment by PopcornG3** [comment]
csgoserver@PixelTeam:~$ ping github.com
PING github.com (192.30.253.113) 56(84) bytes of data.
64 bytes from 192.30.253.113: icmp_seq=1 ttl=48 time=90.7 ms
64 bytes from 192.30.253.113: icmp_seq=2 ttl=48 time=90.7 ms
64 bytes from 192.30.253.113: icmp_seq=3 ttl=48 time=90.7 ms
64 bytes from 192.30.253.113: icmp_seq=4 ttl=48 time=90.8 ms
64 bytes from 192.30.253.113: icmp_seq=5 ttl=48 time=91.7 ms
64 bytes from 192.30.253.113: icmp_seq=6 ttl=48 time=90.7 ms

**Comment by UltimateByte** [comment]
This doesn't seem to be an issue with LGSM.
Come on Discord or Steam group so we can help you. Github is for development.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

@dgibbs64 Maybe we should check for Curl and other main requirements within `gameserver `scripts so that this kind of issues doesn't occur.

**Comment by dgibbs64** [comment]
``` curl -s --fail -o core_dl.sh "https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/functions/core_dl.sh"```

this is the command that runs so try this and see what happens

**Comment by PopcornG3** [comment]
same error

**Comment by dgibbs64** [comment]
whats the output of the command? as it wont look the same

**Comment by UltimateByte** [comment]
Promper curl -V:

```
root@game:/data# curl -V
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

His curl -V:
```
csgoserver@PixelTeam:~$ curl -V
curl 7.36.0 (x86_64-unknown-linux-gnu) libcurl/7.36.0
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp
Features: IPv6 Largefile
```

**Comment by UltimateByte** [comment]
So, issue is: For some reason, his curl doesn't have the ability to get files from https because of missing features such as TLS-SRP.
Non-script issue. Fix remains unknown.
