### ISSUE TITLE
ARK: SE Ridiculous ram usage

### ISSUE THREAD

**Issue by ssamjh** [GameServerManagers/LinuxGSM#1341]
My server idles at 6GB without any players or mods.

Is this normal? If it is, how is this acceptable!

https://steamcommunity.com/app/346110/discussions/0/133258092250571805/

**Comment by cedarlug** [comment]
Why are you asking *US*?

- We didn't make the game
- We don't tweak the game
- You already know the answer
- Github is for script-related issues

**Comment by ssamjh** [comment]
I was just seeing if anyone knew anything about how to optimize it, maybe tweak some config options. But nevermind.

**Comment by UltimateByte** [comment]
Well, GitHub is a development place, so you need to have something real and relevant to propose.
For issues about the game itself (and I agree that it takes way too much resources than it should), reach game devs.
