### ISSUE TITLE
Missing functions files on local installation

### ISSUE THREAD

**Issue by gabrielfgularte** [GameServerManagers/LinuxGSM#1344]
Hi, first of all, your work is amazing!

If I check my functions folder on a new fresh Lgsm installation (CSGO) I'll find that some files are missing from https://github.com/GameServerManagers/LinuxGSM/tree/master/lgsm/functions here.

I want to install some SourceMod plugins, and I've noticed that the master folder has files like `mods_core` and `mods_list` that I don't have in my local installation. Why is that? There's something wrong that I'm doing on my installation? I've followed the site tutorial: https://gameservermanagers.com/lgsm/csgoserver/#gettingstarted

Thanks!

**Comment by cedarlug** [comment]
Functions are installed on-demand when missing.

**Comment by gabrielfgularte** [comment]
@cedarlug That is what I thought, but in my local installation, there are many missing functions. And doesn't matter how many times I run `./csgoserver update-functions`.

Here's a list of my functions folder:

```
alert.sh
check.sh
check_config.sh
check_deps.sh
check_executable.sh
check_glibc.sh
check_ip.sh
check_logs.sh
check_permissions.sh
check_root.sh
check_status.sh
check_steamcmd.sh
check_system_dir.sh
check_system_requirements.sh
check_tmuxception.sh
command_console.sh
command_details.sh
command_install.sh
command_monitor.sh
command_restart.sh
command_start.sh
command_stop.sh
command_update.sh
command_update_functions.sh
core_dl.sh
core_exit.sh
core_functions.sh
core_getopt.sh
core_messages.sh
core_trap.sh
f_list.txt
fix.sh
fix_csgo.sh
fix_steamcmd.sh
gsquery.py
info_config.sh
info_distro.sh
info_glibc.sh
info_parms.sh
install_complete.sh
install_config.sh
install_gslt.sh
install_header.sh
install_logs.sh
install_server_dir.sh
install_server_files.sh
install_steamcmd.sh
logs.sh
monitor_gsquery.sh
update_steamcmd.sh
```

**Comment by gabrielfgularte** [comment]
Just for clarify, the gameserver works fine. I've tested it and it works. But I can't install any SourceMod plugin because of missing mods functions/commands files.

**Comment by cedarlug** [comment]
You're missing the "on-demand" adjective's contribution there.

They're downloaded when you actually do something that  requires them.  The functions that you're missing have not yet been required in your deployment. They'll be brought over when they're needed.

**Comment by gabrielfgularte** [comment]
> They're downloaded when you actually do something that requires them.

What do I need to do to require these functions? Because I need to install a SourceMod plugin, and I don't know how. =/

**Comment by cedarlug** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/mods-install-update-remove

**Comment by gabrielfgularte** [comment]
THANK YOU!
