### ISSUE TITLE
mv: cannot stat '/home/rustserver/log/console/rust-server-console.log': No such file or directory

### ISSUE THREAD

**Issue by Owned67** [GameServerManagers/LinuxGSM#1345]
Hello,

rustserver@localhost:~$ ./rustserver
Usage: ./rustserver [option]
Rust - Linux Game Server Manager - Version 170219
https://gameservermanagers.com/rustserver

Commands
start             st |Start the server.
stop              sp |Stop the server.
restart           r  |Restart the server.
update            u  |Checks and applies updates from SteamCMD.
force-update      fu |Bypasses the check and applies updates from SteamCMD.
update-functions  uf |Removes all functions so latest can be downloaded.
validate          v  |Validate server files with SteamCMD.
monitor           m  |Checks that the server is running.
test-alert        ta |Sends test alert.
details           dt |Displays useful information about the server.
postdetails       pd |Post stripped details to pastebin (for support)
backup            b  |Create archive of the server.
console           c  |Console allows you to access the live view of a server.
debug             d  |See the output of the server directly to your terminal.
install           i  |Install the server.
auto-install      ai |Install the server, without prompts.
mods-install      mi |View and install available mods/addons.
mods-update       mu |Update installed mods/addons.
mods-remove       mr |Remove installed mods/addons.
wipe              wi |Wipe your Rust server.
rustserver@localhost: 
./rustserver st
[  OK  ] Log-Manager rust-server: Starting
[ INFO ] Log-Manager rust-server: Removing logs older than 7 days
[  OK  ] Log-Manager rust-server: Removed 4 log files
**mv: cannot stat '/home/rustserver/log/console/rust-server-console.log': No such file or directory**
[  OK  ] Starting rust-server: Rust

**Comment by UltimateByte** [comment]
Interesting. Can you please post your matching lines from your Rustserver script ?
https://github.com/GameServerManagers/LinuxGSM/blob/master/Rust/rustserver#L118-L142

**Comment by Owned67** [comment]
It's your server script, don't modified

**Comment by UltimateByte** [comment]
`./rustserver postdetails`

**Comment by Owned67** [comment]
I get this error then first time start server (sorry for my bad english)

https://hastebin.com/tesuqenaqi.sql

and i add this bug, on filezilla, i can't open file rust-server-script-2017-03-01-00:36:10.log

**Comment by cedarlug** [comment]
2GB of ram isn't going to work for a Rust server.

**Comment by UltimateByte** [comment]
If 4 logs got removed, i doubt the was on first start.
2GB of RAM isn't enough for Rust, for sure.

However, there are files getting moved upon server start, that should have an if `[ - f "${file}" ]` before moving them in order to make sure to avoid (harmless) error messages. 

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_start.sh

**Comment by Owned67** [comment]
i know for memory, it's just a test for choose a really dedicated server ^^
