### ISSUE TITLE
[ts3server]Can't change the ServerAdmin Password

### ISSUE THREAD

**Issue by kradosser** [GameServerManagers/LinuxGSM#1346]
After many times trying to change the password of the ServerAdmin by using the **`./ts3server.sh pw`** command, nothing changed. Here are my script logs:

`Mar 01 12:25:27 ts3-server: START: PASS: Started TeamSpeak 3 Server`
`Mar 01 12:25:27 ts3-server: TS3-CHANGE-PASS: PASS: New ServerAdmin password applied`
`Mar 01 12:25:29 ts3-server: TS3-CHANGE-PASS: INFO: Restarting server normally`
`Mar 01 12:25:39 ts3-server: STOP: PASS: Stopped TeamSpeak 3 Server`
___
After:
`Mar 01 12:25:48 ts3-server: START: PASS: Started TeamSpeak 3 Server`
`Mar 01 12:25:48 ts3-server: START: PASS: command_start.sh exiting with code: 0`
___
Server Logs after the change:

`2017-03-01 18:05:50.701284|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.0.13.6 (2016-11-08 08:48:33)`
`2017-03-01 18:05:50.701611|INFO    |ServerLibPriv |   |SystemInformation: Linux 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 Binary: 64bit`
`2017-03-01 18:05:50.749756|INFO    |DatabaseQuery |   |dbPlugin name:    MariaDB plugin, version 3, (c)TeamSpeak Systems GmbH`
`2017-03-01 18:05:50.749869|INFO    |DatabaseQuery |   |dbPlugin version: 2`
`2017-03-01 18:05:50.775543|WARNING |Accounting    |   |Unable to find valid license key, falling back to limited functionality`
`2017-03-01 18:05:51.784187|INFO    |              |   |Puzzle precompute time: 928`
`2017-03-01 18:05:51.785406|INFO    |FileManager   |   |listening on 0.0.0.0:30033, :::30033`
`2017-03-01 18:05:51.955672|INFO    |CIDRManager   |   |updated query_ip_whitelist ips: 127.0.0.1/32, ::1/128, `
`2017-03-01 18:05:51.956145|INFO    |Query         |   |listening on 0.0.0.0:10011, :::10011`
___
But every time i try to connect:
`2017-03-01 18:05:53.881704|INFO    |Query         |   |query from 36 149.131.129.275:59342 attempted to login with account "serveradmin" and failed!`
___
I'm using CentOS7 and also YaTQA to connect, but like this Query App's error message says, it's an error by the server...

**Comment by UltimateByte** [comment]
This is a command to help gain some time, but you can try to do it manually as well.
https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/326/26/how-do-i-change-or-reset-the-password-of-the-serveradmin-server-query-account

We need `./ts3server postdetails` output to help though.
I'll try to reproduce your issue. It's not impossible that latest ts3 updates broke the feature.

**Comment by kradosser** [comment]
Here is my postdetails output:
https://hastebin.com/ofewegewir

**Comment by UltimateByte** [comment]
I'm testing on my own atm. First thing i can say is: serveradmin password isn't displayed upon install anymore. So this needs to be fixed. However, you can still find the privilege key in logs.
Then i tried to change the serveradmin password, and then I could successfully connect and query the server, as serveradmin user.

For your part:
Weird name for a kernel.
Unset IP could be the cause as well. Try to set the IP to your interface IP in your .ini file.
Using mariadb, might be a cause for your issue if improperly set, who knows.
Also, what's the home dir of your ts3 user? `eval echo ~ts3`
Also, maybe it's the way you're trying to connect that is wrong. Could you share the exact output you're using (except for the password ofc)?

**Comment by UltimateByte** [comment]
Allright, i get why it didn't show the password. It's the prompt for mariadb that is inverted. You gotta answer "no" instead of "yes". Fixing this ASAP.

**Comment by UltimateByte** [comment]
Fixed.
https://github.com/GameServerManagers/LinuxGSM/pull/1348

If it's a new install, i suggest removing: serverfiles and lgsm directories, then run the installer again. If not using mariadb, then answer "N" as you should. ;)

**Comment by UltimateByte** [comment]
Please, if the issue persists, come find us on Discord or the Steam Group, I'll be glad to help.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
