### ISSUE TITLE
[TeeWorld Server, Linux CentOS] Start Error

### ISSUE THREAD

**Issue by iVenom999** [GameServerManagers/LinuxGSM#1349]
When trying to start twserver I get an error, that the server fails to start. If I try to start the binary, I get this error:

```
[twserver@localhost teeworlds-0.6.4-linux_x86_64]$ ./teeworlds_srv 
./teeworlds_srv: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./teeworlds_srv)
```

GLIBC info
```
[root@localhost lib64]# strings libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

CXXABI info
```
[root@localhost lib64]# strings libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```

OS info
```
[root@localhost lib64]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

twserver debug and server details will be added a bit later.

This link works https://heinrich5991.de/teeworlds/temp/temp2/teeworlds-0.6.4-linux_x86_64.tar.gz

Almost the same issue as https://github.com/GameServerManagers/LinuxGSM/issues/1280, but the distro there is Debian and here is CentOS/RHEL.

**Comment by UltimateByte** [comment]
Your report was perfect.
However, there is already an issue for this as you said.
https://github.com/GameServerManagers/LinuxGSM/issues/1280
To sum up: This is nothing LGSM can help with, and Heinrich needs to merge this to the game server libs so that it can be fixed.
Only workaround for now: Latest Ubuntu, that has updated libs to work with it.

**Comment by UltimateByte** [comment]
Update: Debian will work as well, a first fix was already pushed that fixes it for Debian 8. Follow the other issue to see if it will be fixed for CentOS 7 or not :)

**Comment by heinrich5991** [comment]
Mh. Not sure in which issue to comment. You say my temporary upload at https://heinrich5991.de/teeworlds/temp/temp2/teeworlds-0.6.4-linux_x86_64.tar.gz works? Could you give us the `sha256sum`s of the teeworlds_srv gotten from heinrich5991.de and the one from Steam?

**Comment by iVenom999** [comment]
[twserver@steamsrv]:~$ ./twserver debug  
```
Teeworlds Debug
=================================

Distro: CentOS Linux 7 (Core)
Arch:   x86_64
Kernel: 3.10.0-229.11.1.el7.x86_64
Hostname:       steam
tmux:   tmux 2.4
Avg Load:       0.81, 0.74, 0.65
Free Memory:    157M
Free Disk:      48G
GLIBC required: 2.3
Server IP:      192.168.0.208:8303
Server password:        <password>
```

**Comment by iVenom999** [comment]
Currently not working in CentOS

[root@steamsrv tw]# sha256sum teeworlds_srv 
1ce85a09849d548ca319e28566dba6d1a9513e030a5656046bfaa60a2f9e3c8a  teeworlds_srv

The file from your archive (https://heinrich5991.de/teeworlds/temp/temp2/teeworlds-0.6.4-linux_x86_64.tar.gz) which works

[root@steamsrv teeworlds-0.6.4-linux_x86_64]# sha256sum teeworlds_srv 
2f9be69a7f2efa5dea470119ef58b411685486a9eae380ceccb8cc3befcd103e  teeworlds_srv

Haven't tried the version from Steam. If you need to - I can try.

**Comment by UltimateByte** [comment]
The version from the archive should now be the version from SteamCMD.
So what version doesn't work if you didn't try the Steam version ?

**Comment by iVenom999** [comment]
Ok, I will do a fresh install from Steam and check, if it works or no. And will give some feedback. The version which I downloaded some time ago from Steam. It has this checksum:

[root@steamsrv tw]# sha256sum teeworlds_srv 
1ce85a09849d548ca319e28566dba6d1a9513e030a5656046bfaa60a2f9e3c8a  teeworlds_srv

**Comment by heinrich5991** [comment]
Seems like an update from Steam fixed it: https://github.com/GameServerManagers/LinuxGSM/issues/1280#issuecomment-284034934.

**Comment by iVenom999** [comment]
Yes, updated version from Steam now works flawless.

**Comment by iVenom999** [comment]
Fresh install works flawless!!! Good job!

Checksum from fresh Steam install is

```
[twserver@steamsrv]:~/serverfiles/tw$ sha256sum teeworlds_srv 
2f9be69a7f2efa5dea470119ef58b411685486a9eae380ceccb8cc3befcd103e  teeworlds_srv
```

**Comment by iVenom999** [comment]
You can close this issue, it's solved.
