### ISSUE TITLE
Pushbullet and Server monitor

### ISSUE THREAD

**Issue by FilipK-CZ** [GameServerManagers/LinuxGSM#1352]
It is possible easy edit pushbullet messages? Example: For Minecraft server i have many java arguments and if server fall down pushbullet get long message.

**Comment by UltimateByte** [comment]
Not it's not. 
https://github.com/GameServerManagers/LinuxGSM/wiki/Pushbullet

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
