### ISSUE TITLE
Error when downloading CS:GO $DEBUGGER "$STEAMEXE" "$@"

### ISSUE THREAD

**Issue by vkopanja** [GameServerManagers/LinuxGSM#1356]
I have a Centos 7 x64 server on DigitalOcean, and have a partition mounted at `/mnt/volume-far1-01` (I have rwx rights with my steam user), but I keep getting this error when I try downloading CS:GO server:

![Error loop](http://image.prntscr.com/image/eed869633c0a4910b3a2685fb2a47abe.png)

And it just goes on and on like that.

Any ideas? I think similar (or might be 100% the same, can't remember) error happened when I tried running SteamCMD manually from Steam site.

**Comment by cedarlug** [comment]
Out of disk space?

**Comment by vkopanja** [comment]
@cedarlug Nope, 30 GB free, CS:GO server is like 21-23 GB, it fails at like 2-3% or earlier.

**Comment by UltimateByte** [comment]
Not an LGSM issue.
If you wanna post on this github for a non script issue, please consider at least providing expected information as: 
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by cedarlug** [comment]
Output speaks wonders.  @vkopanja It's not that I don't believe you (okay, I don't believe you), but I will believe the output from the details command from @UltimateByte's link and the output of:
`df -h`

Without those two items, you'll soon find your ticket closed.

**Comment by vkopanja** [comment]
I'll be editing this post in the morning with all that data, it's getting late here, and I have work tomorrow :(...

Thanks for helping out guys!

**Comment by UltimateByte** [comment]
1) Make sure your current shell is bash: echo $0
2) CSGO won't run with 512MB RAM and no swap

For further assistance, please use other ways we provide: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
