### ISSUE TITLE
7dtd Error on update mod oxide

### ISSUE THREAD

**Issue by txandy** [GameServerManagers/LinuxGSM#1358]
**I write:**
 
./sdtdserver mu
>  INFO ] Mods Update sdtd-server: Update addons/mods: 1 addons/mods will be updated
> 	* Oxide for 7 Days To Die (overwrite)
> 
> ==> Updating Oxide for 7 Days To Die
> clearing mod download directory /home/txandy/lgsm/mods/tmp...OK
> creating mod download directory /home/txandy/lgsm/mods/tmp...OK
> downloading Oxide-7DaysToDie_Linux.zip...
> **curl: (22) The requested URL returned error: 404 Not Found**
> downloading Oxide-7DaysToDie_Linux.zip...OK
> Failure! An issue occurred downloading Oxide for 7 Days To Die

**Comment by UltimateByte** [comment]
Oxide link changed. We corrected it on day 0. Just update your LGSM.
`./sdtdserver uf`
