### ISSUE TITLE
CSGO server starts but can't connect (Reservation cookie 0)

### ISSUE THREAD

**Issue by gabrielfgularte** [GameServerManagers/LinuxGSM#1359]
Hi, I've started a csgo server on a cloud host (aws). When the client tries to connect, it shows a "Finding" and the gameserver console triggers a "Round_Start". Then, the client says in the "Finding" window: "Failed to join game".

The server logs this on console (./csgoserver console):

```
...
L 03/07/2017 - 04:15:33: World triggered "Round_Start"
-> Reservation cookie 0:  reason reserved(yes), clients(no), reservationexpires(0.00)
```

What I'm doing wrong?

**Comment by UltimateByte** [comment]
Hi,
Sorry, this is the wrong place to ask. See other ways to get help here:
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
