### ISSUE TITLE
Problem when i install a Teamspeak server

### ISSUE THREAD

**Issue by Nicolas-Alvarez1** [GameServerManagers/LinuxGSM#1362]
Hello,

Have got a problem when i install a teamspeak server.

I thinks it's the same problem of they ticket: #1232 and #1124 but they don't resolved my problem .. :/

Do you have something idea ?

Thanks you very much

Nico.

**Comment by UltimateByte** [comment]
I dont has something idea.
Please, idea use right place for post issue is very better good.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
