### ISSUE TITLE
[Rust]server.salt parameter

### ISSUE THREAD

**Issue by nadal28** [GameServerManagers/LinuxGSM#1364]
Like server.seed, server.salt is generated by rand() if this parameter is not specified.

server.seed = visual map generation.
server.salt = resource map, for quarrys and ores.

For example, if you use a backup of your server you would use the same server.seed, same map size, and then you believe you have the same map, but not, quarrys will not produce the same resources, ores will spawn in different zones, causing players get annoyed by this, and all because the resource map (server.salt) is not the same.

**Comment by UltimateByte** [comment]
Good idea, thanks for the suggestion, it will be added.

In the meantime, if you're in a hurry for this, you can already add yourself to your Rust, following this guidance: https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters#additional-parameters

**Comment by UltimateByte** [comment]
By the way, do you know the value range for `server.salt` start parameter ?

**Comment by nadal28** [comment]
No sorry, I couldn't find that :(
Maybe the same range that server.seed but Im not sure

**Comment by UltimateByte** [comment]
Yeah, that's my guess as well, but it seems like it's not documented.
