### ISSUE TITLE
fetching install_server_files.sh...FAIL

### ISSUE THREAD

**Issue by Speddy** [GameServerManagers/LinuxGSM#1365]
Installing SteamCMD
=================================
Information! SteamCMD is already installed...OK
    fetching install_server_files.sh...FAIL
https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/functions/install_server_files.sh

    fetching core_exit.sh...OK

**Comment by cedarlug** [comment]
Please follow [these instructions for seeking help](https://github.com/GameServerManagers/LinuxGSM/wiki/Support), starting with the very first bullet - What game server are you even running?

It's likely that the [steam discussion](https://gameservermanagers.com/steam) area will be better suited to help you.
