### ISSUE TITLE
[RUST] Inform the players and update within x minutes whenever an update is available

### ISSUE THREAD

**Issue by Snake4life** [GameServerManagers/LinuxGSM#1367]
hi,

I have set up a cronjob that checks every 30minutes for an new rust update. 

`./rustserver update`

The problem: Server goes down immediately whenever an update is out, Players have no time to get into their Base to logoff and the biggest problem, the RUST client gets its updates way later than the server, which means everyone that is outside of the Base dies.

Please Implement a function that delays the available update for x minutes and sends an update message to all players ?via the console window?

**Comment by UltimateByte** [comment]
Duplicate.
https://github.com/GameServerManagers/LinuxGSM/issues/299

Supporting RCON isn't an easy task. Feel free to work on it if you really wish to see this implemented any time soon.
