### ISSUE TITLE
Stopping with errors

### ISSUE THREAD

**Issue by fearrr** [GameServerManagers/LinuxGSM#1369]
I use `stop` command
```
...
[ .... ] Stopping csgo-surfrpg: Graceful: sending "quit": 21
[ .... ] Stopping csgo-surfrpg: Graceful: sending "quit": 22
[ .... ] Stopping csgo-surfrpg: Graceful: sending "quit": 23
[ .... ] Stopping csgo-surfrpg: Graceful: sending "quit": 24
...
[ERROR ] Stopping csgo-surfrpg: Graceful: sending "quit": FAIL
```
slow stopping the server's, and gives an error

**Comment by dgibbs64** [comment]
For some reason the quit command is not working on your server. Meaning your server cannot do a graceful shutdown. The console log will give you more info

**Comment by fearrr** [comment]
Thx, this problem is actual for all my servers. 
I'll try to find a common problem in the console logs and report this additionally

**Comment by jaredballou** [comment]
Do you have SourceMod installed, with the cURL library? I notice that many of my server instances which fail to quit are waiting for cURL threads to terminate, and they never do.
