### ISSUE TITLE
Waiting on Steam Verification

### ISSUE THREAD

**Issue by GoZippy** [GameServerManagers/LinuxGSM#1370]
Centos 7
I installed 7days using instructions on your site.
Server starts and appears to be running fine - however when anyone tries to connect we get past the connection part in game and then it hangs on "Waiting for steam verification" and that is it. 

I am wondering if this has anything to do with issue 579 and two factor auth. When I use steamcmd I was prompted to use emailed code to login fully - which I did and was allowed to. The game installed fine. I can see the server running using TOP and sdtdserver details command

What am I missing? I am fairly positive all my UDP ports needed are wide open.

Do I need to modify anything for working with two factor auth to get game to validate with steam?

**Comment by UltimateByte** [comment]
If it can save you some time: it probably has nothing to do with 2 factor auth, which is just a SteamCMD game download thing, while you issue is a game server one.
Github is for development. Please, come on Discord or post this on the steam group (try to provide some logs and `./sdtdserver postdetails` if you want to be helped as per https://github.com/GameServerManagers/LinuxGSM/wiki/Support )
