### ISSUE TITLE
Is there anyone who can help?

### ISSUE THREAD

**Issue by woshihandsome** [GameServerManagers/LinuxGSM#1371]
I use Linux CentOS system set up the dodserver, but there is always an error, as shown, I would like to ask how to solve, I am a novice! Thanks
![qq 20170316151033](https://cloud.githubusercontent.com/assets/26453872/23985710/7f966c3e-0a5b-11e7-9ba4-04a8a13e865e.png)

**Comment by woshihandsome** [comment]
My mail  
cnddodgame@gmail.com

**Comment by reesey275** [comment]
The error is stated clearly in your message.  The account does not have sudo access.

**Comment by woshihandsome** [comment]
Thank you. I'll try

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by faflfama** [comment]
@reesey275 Just that I dont understand it wrong, isnt the error that TMUX isnt installed? Sudo is just optional to make it "easier".

**Comment by marvinl97** [comment]
@faflfama The error is there because tmux isn't installed and the warning because the current user doesn't have sudo access to install it. ;)

**Comment by UltimateByte** [comment]
`yum install tmux bc`
Problem solved.

**Comment by faflfama** [comment]
@marvinl97 Thats what I meant :) Just sounded like you "need" sudo for especially this account to make it work.
