### ISSUE TITLE
[Dependency] "bc" package

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1372]
`bc` package is needed for some commands to work properly. This one isn't installed on minimal distros.
Would be nice to start taking take care of required packages that might not be default installed on minimal distros, since people using them don't always know how to figure out missing packages.
![pic](http://i.imgur.com/0B6oQft.png)

**Comment by dgibbs64** [comment]
we can get this added in.

**Comment by UltimateByte** [comment]
Another one to add: `binutils`
Required for `strings` command. used between other things into `install_config.sh`

**Comment by dgibbs64** [comment]
All added
