### ISSUE TITLE
Server fail to start after upgrading tmux from 1.8 to 2.3

### ISSUE THREAD

**Issue by Sil3ntPr0digy** [GameServerManagers/LinuxGSM#1375]
Just as my titles says, I updated tmux via tarball from 1.8 to 2.3 and now servers continually fail to start.

Any ideas?

**Comment by Sil3ntPr0digy** [comment]
here is the output from my arkserver, https://hastebin.com/kuxukabisu it states online, but that is definitely not the case, server is not joinable and only change was updating tmux.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
