### ISSUE TITLE
Host multiple csgo servers on 1 machine

### ISSUE THREAD

**Issue by joepvand** [GameServerManagers/LinuxGSM#1381]
i want to host multiple csgo servers on 1 machine.
1 retake server
1 vanilla
1 1v1 server
Not at the same time but like switch between them
is this possible?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Servers
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
