### ISSUE TITLE
[New Server] Squad

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1382]
As per
http://steamcommunity.com/groups/linuxgsm/discussions/0/135512625247624380/

Seems to be available for Linux.
https://steamdb.info/app/403240/

I'll update this post with doc if any when some research has been done.

Edit:
Thanks @OverVolts on Steam forum
Linux install guide
http://forums.joinsquad.com/topic/26351-squad-server-installation-on-linux/

Server config guide
http://squad.gamepedia.com/Server_Configuration

_You need Squad developers approved license to be able to install the dedicated server_
**License is optional**
http://forums.joinsquad.com/topic/16519-server-licensing-general-info/

**Comment by Odinthewanderer** [comment]
You won't need the license to install the server. It just governs which server browser you will appear under (standard or custom).

**Comment by Scarsz** [comment]
Thanks to the good folks at Offworld Industries (including @Odinthewanderer), we've been provided with a couple keys to help in development for this.

**Comment by Scarsz** [comment]
Made an implementation of this on `feature/squadserver`, PR #1449. Give some feedback on the pull request with results. Works good for me on my Debian 8 x64 server.

**Comment by UltimateByte** [comment]
It is released, just remains to add it to the website.

**Comment by dgibbs64** [comment]
This has not been releases in the latest update
