### ISSUE TITLE
Server Start but FPS problem

### ISSUE THREAD

**Issue by fuuuchs** [GameServerManagers/LinuxGSM#1383]
At the first, sry for my bad english!.
My Server's starting and working! But on playrust.io i have no > FPS on my servers.
All my Vanilla-Server have no FPS but the Modded have fps. whats the problem?!

I have Ubuntu 14.04.5 LTS (GNU/Linux 3.14.32-xxxx-grs-ipv6-64 x86_64)

I send a Pic from playrust.io
[http://www.bilder-upload.eu/show.php?file=a2e124-1490689347.png](http://www.bilder-upload.eu/show.php?file=a2e124-1490689347.png)

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by fuuuchs** [comment]
Game: RUST
DETAILS: ./rustserver details LINK >> [http://www.bilder-upload.eu/show.php?file=f3fff5-1490701703.jpg](http://www.bilder-upload.eu/show.php?file=f3fff5-1490701703.jpg)
VERSION: 14.04.5 LTS Ubuntu

I INSTALL THE PARAMETER:

> sudo dpkg --add-architecture i386; sudo apt-get update;sudo apt-get install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux tmux lib32gcc1 libstdc++6 libstdc++6:i386

and by the STEp "Postfix Configuration" i tipp (Internet site) is this real?

and than install server > start server, the server is only but no "FPS" on playrust.io

Can u help? Thanks

**Comment by UltimateByte** [comment]
Wrong place to ask
