### ISSUE TITLE
Rust FPS Problem by playrust.io

### ISSUE THREAD

**Issue by fuuuchs** [GameServerManagers/LinuxGSM#1387]
Hello Guys, my english is not so good but i try it.
My steps:

I Install the Game Rust on my Dedicated Server with Version **Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-113-generic x86_64)**

1. Install the packages with (root):
`sudo dpkg --add-architecture i386; sudo apt-get update;sudo apt-get install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux tmux lib32gcc1 libstdc++6 libstdc++6:i386`
   and by the Step "Postfix Congifuration" is Set it on "No Konfiguration"
[Postfix Bild](http://www.bilder-upload.eu/show.php?file=688ff6-1490704902.jpg)

2. Adduser rustserver > Login, Downloading (rustserver script) and Install the rustserver with ./rustserver install

3. nano rustserver > Set Hostname + IP and more!
[Rustserver Config](http://www.bilder-upload.eu/show.php?file=3a3ba4-1490705573.jpg)

4. Start server with ./rustserver start
[GameserverLog](http://www.bilder-upload.eu/show.php?file=871930-1490705663.jpg)

Now the server is Online, and have a Steam Connection! This is fine, but i look on playrust.io, and search this server. i found it, but the server have "no FPS"
[Playrust.io Screenshot](http://www.bilder-upload.eu/show.php?file=0a2aa1-1490706096.jpg)

the Command postdetails:
[https://hastebin.com/cibiqiqume](https://hastebin.com/cibiqiqume)

i hope u can help me, thanks!

**Comment by UltimateByte** [comment]
For fuck sake, github is a development place. This isn't even an LGSM issue.
https://github.com/GameServerManagers/LinuxGSM/issues/1383
