### ISSUE TITLE
Pushover notifications 

### ISSUE THREAD

**Issue by r3n00** [GameServerManagers/LinuxGSM#1388]
Can pushover notifications be added to the notification list ?

**Comment by UltimateByte** [comment]
Can you follow the guidance and ask this somewhere where it makes sense ?
https://github.com/GameServerManagers/LinuxGSM/wiki/Support


We're not on Twitter, this is a development place.

On top of that, the wiki tells everything you need to know about alerts.
https://github.com/GameServerManagers/LinuxGSM/wiki/Email
https://github.com/GameServerManagers/LinuxGSM/wiki/Pushbullet

**Comment by dgibbs64** [comment]
Push over is an alternative to push bullet. It could be possible to add t

**Comment by UltimateByte** [comment]
Grouping all notifications/alerts to one thread:
https://github.com/GameServerManagers/LinuxGSM/issues/1321

**Comment by Z0uZOU** [comment]
Hi,
you forget parameters "pushoveruserkey" in config file.

**Comment by dgibbs64** [comment]
@Z0uZOU 

```
# Pushover Alerts | https://github.com/GameServerManagers/LinuxGSM/wiki/Pushover
pushoveralert="off"
pushovertoken="accesstoken"
```
