### ISSUE TITLE
[Gmod] Unable to start LinuxGSM, create session failed

### ISSUE THREAD

**Issue by arrow556** [GameServerManagers/LinuxGSM#1389]
Hey guys,

after a successful installation of the gmodserver I get this error message when I try to start the server: 

Error
=================================
create session failed: ./srcds_run -game garrysmod -strictportbind -ip [CENSORED] -> followed by the usual start script so nothing special.

Fix 
=================================
No known fix currently. Please log an issue.

I also get this at the beginning befor the other error message:
=================================
[ .... ] Starting gmod-server: failed to connect to server: Connection refused
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM
[ FAIL ] Starting gmod-server: Unable to start LinuxGSM: Tmux error:

any ideas how to fix this problem?
Thanks!

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
No idea because of no relevant info and support guidance not followed.
+ It is the wrong place to ask.

**Comment by arrow556** [comment]
lol. Thanks. By the way, the ERROR message is telling me to post it HERE. But ok :)
