### ISSUE TITLE
[Website] glibc requirement has changed! (CentOS 6 can no longer be used to host a TF2 server)

### ISSUE THREAD

**Issue by kamild1996** [GameServerManagers/LinuxGSM#1390]
I've learned that the hard way, sadly.
Looks like we missed the fact that Valve updated the libraries used by the game and by the server. The main page for tf2server manager (https://gameservermanagers.com/lgsm/tf2server/) still mentions "glibc => 2.3.6" is required. Suggested by that, I installed the game server on a VPS that had CentOS 6 already installed by default, so I didn't bother upgrading to 7. And that was a big mistake - the server won't start on CentOS 6 because of the following error:
`Failed to open dedicated_srv.so (/lib/libm.so.6: version 'GLIBC_2.15' not found (required by bin/dedicated_srv.so))`
And the latest version of glibc available for CentOS 6 is 2.13. It's a problem because:
- Updating glibc to an even later version than officially available is not advised and breaks the system
- Upgrading CentOS 6 to 7 is not officially possible (there's a certain tool, but the upgrade breaks a lot of things in the system - again)

So all I got left is to... reinstall to the latest version. Because most (if not all) guides have outdated information about such requirements.
Can someone please revise the requirements to make sure it's not the case with older versions of Ubuntu/Fedora/Debian as well?

**Comment by dgibbs64** [comment]
Thanks for the details. I will get everything updated. I was aware that TF2 was broken on CentOS currently but we are looking in to this. I hope that Valve resolve the issue.

**Comment by zcythe** [comment]
I use the gmod trick to fix this issue.

cd /home/tf2server/bin
wget https://github.com/GameServerManagers/LinuxGSM/raw/master/lgsm/lib/ubuntu12.04/i386/libstdc++.so.6
wget https://github.com/GameServerManagers/LinuxGSM/raw/master/lgsm/lib/ubuntu12.04/i386/libc.so.6
wget https://github.com/GameServerManagers/LinuxGSM/raw/master/lgsm/lib/ubuntu12.04/i386/libm.so.6
wget https://github.com/GameServerManagers/LinuxGSM/raw/master/lgsm/lib/ubuntu12.04/i386/libpthread.so.0


References:
https://danielgibbs.co.uk/2014/08/garrys-mod-linux-server-glibc_2-15/

**Comment by dgibbs64** [comment]
@zcythe I am unable to get tf2 working on centos 6 currently even with the fix in place

```
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
Server will auto-restart if there is a crash.
Using Breakpad minidump system. Version: 3920631 AppID: 232250
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Loaded 7640 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 7640 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 1095 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1095 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1805 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1805 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1805 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 449 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 449 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/platform/platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/linuxgsm/tf2server/serverfiles/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
Could not load: replay_srv.so
Could not load: replay_srv.so

Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
./srcds_run: line 324: 24111 Segmentation fault      (core dumped) $HL_CMD
Missing separate debuginfo for /home/linuxgsm/tf2server/serverfiles/srcds_linux
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/a0/d4a4df9a1844d398fb95feda6f6ba99aa3c5eb.debug
BFD: Warning: /home/linuxgsm/tf2server/serverfiles/core is truncated: expected core file size >= 199737344, found: 1245184.
Cannot access memory at address 0xb77218e8
Cannot access memory at address 0xb77218e8
Cannot access memory at address 0xb77218e8
Failed to read a valid object file image from memory.
Cannot access memory at address 0xbff41e70
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
```

**Comment by thesweetiger** [comment]
I have the same error on ubuntu 16.04.2 LTS fresh install 
i have a csgo server and this one work fine

ldd on server_srv.so return that

`       linux-gate.so.1 =>  (0xe42cd000)
        libtier0_srv.so => not found
        libvstdlib_srv.so => not found
        libsteam_api.so => not found
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xe2a53000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xe2a4e000)
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xe28d7000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xe28ba000)
        /lib/ld-linux.so.2 (0xe42ce000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xe2703000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xe26e6000)
`
This the server I use
https://www.soyoustart.com/ca/en/offers/142sys5.xml

**Comment by dgibbs64** [comment]
All is now working
