### ISSUE TITLE
[EMERGENCY] Convert LGSM to Windows Batch

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1391]
It's a shame that we leave Windows server owners on their own. Windows is such a great server OS, we cannot just ignore it as if it wasn't making Billion dollars every year and wasn't used by so many companies and users. 

An open source project HAS to be universal and work on EVERY distro, including Windows.

I request @dgibbs64 and @cedarlug you work on a Windows version of Linux Game Server Managers right away, so that I can finally move all my Minecraft servers that I host on CentOS to Windows XP Server 2011.

Thank you.

Edit:
Protip from Discord

> xFaNaTiix - Today at 4:12 PM
> Simple fix. We drop Linux support. Who the hell even uses that crap? Managing machines with command lines? Are we in the stone age? gaaawd

**Comment by cedarlug** [comment]
I use [url=https://github.com/PowerShell/PowerShell]powershell[/url] on linux because it's so wonderful.
Will whip up a solution for you immediately.

**Comment by UltimateByte** [comment]
Thanks @cedarlug !
When will it be ready? I can't wait!

**Comment by UltimateByte** [comment]
Well, after a discussion with Steve Jobs through a prayer, I think this isn't a good idea.
DO NOT RELEASE

**Comment by cedarlug** [comment]
(Prayer isn't a way to talk with Jobs.  He isn't "up there.")

**Comment by UltimateByte** [comment]
(You mean he's in hell, he's not dead, or that prayer /paradise are fake pieces of **** ?)
