### ISSUE TITLE
Issues with curl & non ASCII characters

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1393]
I'll check if i can reproduce this.
![pic](https://cdn.discordapp.com/attachments/135126471319617536/298824202302128139/unknown.png)
![pic](https://cdn.discordapp.com/attachments/298791834438729728/298803447464067082/unknown.png)

Postdetails: https://hastebin.com/kuqusofito

**Comment by UltimateByte** [comment]
All I can say after trying to reproduce is that the hostname causes the issue.
`ORANGE/FUN MAPS 100% TWEAKED CRITS <[Kapiszony.pl]>`
However, if notifications aren't sent, I'm not getting any fancy output, it just won't be sent.
Digging a bit deeper.

**Comment by UltimateByte** [comment]
Issue is that the % sign gets interpreted in the following command:

`curl --silent -u o.g6et5OUAPI: -d channel_tag= -d type=note -d 'body=LinuxGSM test alert, how you read?' -d 'title=LinuxGSM - Test Alert - ORANGE/FUN MAPS 100% TWEAKED CRITS <[Kapiszony.pl]>' https://api.pushbullet.com/v2/pushes`

**Comment by UltimateByte** [comment]
I'm trying to reach Pushbullet team to submit this bug.

Example output with stripped personal info

Not working because of "%" sign:

````bash
ultimatebyte@game:~$ curl --silent -u o.API: -d channel_tag= -d type=note -d 'body=LinuxGSM test alert, how you read?' -d 'title=LinuxGSM - Test Alert - ORANGE/FUN MAPS 100% TWEAKED CRITS <[Kapiszony.pl]>' https://api.pushbullet.com/v2/pushes

{"error":{"code":"invalid_request","type":"invalid_request","message":"Failed to decode urlencoded POST form body.","cat":"~(=^‥^)ノ"},"error_code":"invalid_request"}
````

Working: 
````bash
ultimatebyte@game:~$ curl --silent -u o.API: -d channel_tag= -d type=note -d 'body=LinuxGSM test alert, how you read?' -d 'title=LinuxGSM - Test Alert - ORANGE/FUN MAPS 100 TWEAKED CRITS <[Kapiszony.pl]>' https://api.pushbullet.com/v2/pushes

{"active":true,"iden":"API","created":1.4913303674548767e+09,"modified":1.4913303674905274e+09,"type":"note","dismissed":false,"direction":"self","sender_iden":"API","sender_email":"r@gmail.com","sender_email_normalized":"r@gmail.com","sender_name":"R","receiver_iden":"API","receiver_email":"r@gmail.com","receiver_email_normalized":"r@gmail.com","title":"LinuxGSM - Test Alert - ORANGE/FUN MAPS 100 TWEAKED CRITS \u003c[Kapiszony.pl]\u003e","body":"LinuxGSM test alert, how you read?"}
````

**Comment by ChaosMTA** [comment]
This is not a Pushbullet bug, this is how bash works on Linux. You would have no luck contacting them to fix a bug that doesn't exist

**Comment by UltimateByte** [comment]
Thanks @jenK from Discord, we now know that this is actually a curl issue.
Converting the % sign to ASCII solves the issue.
Which means: change `%` to `%25`.

A good measure would be to convert anything sent using curl to ASCII.

**Comment by dgibbs64** [comment]
Looking at a way to do this

**Comment by UltimateByte** [comment]
Good job @dgibbs64
