### ISSUE TITLE
[FEATURE REQUEST] RUST Server announcements

### ISSUE THREAD

**Issue by kossamuno** [GameServerManagers/LinuxGSM#1398]
For server admins who would like to keep their server as a "Community server" we are unable to use the functionalities of Oxide when the server is about to restart/shutdown/update.

As a server admin I know you are loosing new players (and new to Rust) when the server shuts down to update on wipe day for example. This perhaps not a very big issue but I do not think it would be big thing to add server announcements to the rustserver script. So when the server is about to update, like Oxide, there is a countdown that the server will update and restart in x minutes/x seconds.

And with that functionality it would also be nice to use the same script to schedule other custom made server messages, such as a MOTD or "Please visit the server website @ xxxx".

I would also like to use this opportunity to say thank you for a great tool!

**Comment by UltimateByte** [comment]
If you got a good idea on how to implement the various RCON protocols to LGSM, please share. This idea is as old as LGSM is.
https://github.com/GameServerManagers/LinuxGSM/issues/299

**Comment by kossamuno** [comment]
I am not a programmer but a simple server admin. I was in contact yesterday with the creator of:
https://github.com/kirbo/rust-server-cli-rcon

And within a few hours he whipped up this:
https://github.com/kirbo/rust-server-cli-rcon-scheduler

It will allow me to atleast schedule server message without having to mod my server. Look at his work for ideas, perhaps even contact him?
