### ISSUE TITLE
[RUST-SERVER]Problem to Start the Server

### ISSUE THREAD

**Issue by ChaosToaster** [GameServerManagers/LinuxGSM#1400]
Hello dear Support,

i´ve a Problem, for a few Minutes i updated my Rustserver. Update works fine, but after the Update, the Server dont Start. I look every 10 Seconds in my RustAdmin Tool, but there cant connect too.

In Log i dont get anything, complete empty. The Command `./rustserver console` works but console is empty and the Command `./rustserver monitor` dont works because query Port fail connect.

**This Following Steps is do:**
1. Make the Update -> `./rustserver update`
2. Update is done, check the Logs -> 1 Log found, empty
3. RustAdmin Tool check -> Dont work, cant connect
4. Console check -> `./rustserver console`, empty
5. Monitor Check -> Dont work, query fail connect
6. Server shutdown ->` ./rustserver stop`
7. Update LGSM ->` ./rustserver uf`
8. LGSM Update done and sucessfull
9. Do Steps 1-5 again -> No changes, Server dont start
10. PD List Message create -> `./rustserver pd`
11. Server shutdown -> `./rustserver stop`
12. Hanging out here, search my fuk´n Bear and type this shit :P 

So Guys, iám sure, i havnt make wrong, so pls Guys, can u help me?

Thanks and have a nice Day :) <3

**Comment by UltimateByte** [comment]
Hi,
This is the wrong place to post, since it's not an LGSM issue (as per https://github.com/GameServerManagers/LinuxGSM/wiki/Support ) but since you're kind and did some effort i'll point you to the right direction.

> Console check -> ./rustserver console, empty  

Console is always empty for Rust in Linux, blame Facepunch.

> check the Logs -> 1 Log found, empty  

Look at the right directory > `log/server` or `serverfiles/game*.log` depending on your LGSM main script version. 

> PD List Message create -> ./rustserver pd

So, where is the output link to share to support ?

You didn't try to validate your game files. https://github.com/GameServerManagers/LinuxGSM/wiki/Update#validate
And you didn't mention if using Oxide or not, so I assume you don't.
Hopefully you can get it working. Otherwise, feel free to come on Discord or the Steam forum, places used to solve this kind of issues. https://gameservermanagers.com/support/

Cheers.

**Comment by ChaosToaster** [comment]
Ah sry, i forgot the PD-Link -.-

PD: https://hastebin.com/fuyolefizu
Validate sucessfull
Oxide newest Version and Plugins newest Version

Logfile from /log/server
`eac_server.so [x64] :: OnLoad()
ustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated
Mono path[0] = '/home/rustserver/serverfiles/RustDedicated_Data/Managed'
Mono path[1] = '/home/rustserver/serverfiles/RustDedicated_Data/Mono'
Mono config path = '/home/rustserver/serverfiles/RustDedicated_Data/Mono/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api64.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
	libRenderer.so
Player data archive not found at `/home/rustserver/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystemInitialize engine version: 5.6.0f3 (497a0f351392)
Forcing GfxDevice: Null
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
AudioManager: Using Unknown: NoSound Driver
Begin MonoManager ReloadAssembly
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Analytics.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Analytics.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.West.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.West.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/LZ4.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/LZ4.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Global.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Workshop.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Steamworks.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexAI.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexAI.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexSerialization.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexSerialization.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexShared.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/ApexShared.dll into Unity Child Domain
- Completed reload, in  0.019 seconds
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Core.dll (this message is harmless)
OnLevelWasLoaded was found on LeanTween
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 376)

Shader 'Nature/Terrain/Diffuse': dependency 'AddPassShader' shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
Shader 'Hidden/TerrainEngine/Splatmap/Specular-AddPass': fallback shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
Shader 'Hidden/TerrainEngine/Splatmap/Standard-AddPass': fallback shader 'Hidden/TerrainEngine/Splatmap/Diffuse-AddPass' not found
UnloadTime: 0.819000 ms
Bootstart Startup
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

System
	Name: Debian-86-jessie-64-LAMP
	OS:   Linux 3.16 Debian 8.7 64bit

CPU
	Model:  Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz
	Cores:  8
	Memory: 64392 MB

GPU
	Model:  Null Device
	API:    NULL 1.0 [1.0]
	Memory: 128 MB
	SM:     30

Memory
	GC.GetTotalMemory:     0 MB

Process
	Priority: 0
	Threads:  0
	Memory:   109 MB
	Peak:     131 MB

Mono
	Collects: 9
	Memory:   0 MB



 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Runtime.Serialization.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Xml.Linq.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Xml.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Data.dll (this message is harmless)
The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'mp5.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'ak47u.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'crossbow.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'v_semi_pistol') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'semi_auto_rifle.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'rocket_launcher.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'double_shotgun.viewmodel') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour is missing!
 
(Filename:  Line: 1514)

The referenced script on this Behaviour (Game Object 'v_waterpipe_shotgun') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'v_eoka_pistol') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'v_smg') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'v_rocketlauncher') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'v_thompson') is missing!
 
(Filename:  Line: 1743)

The referenced script on this Behaviour (Game Object 'v_sawnoffshogun') is missing!
 
(Filename:  Line: 1743)

Command Line: "./RustDedicated" "-batchmode" "+server.ip" "88.99.105.93" "+server.port" "28015" "+server.tickrate" "30" "+server.hostname" "GER/EN | TWITCHARMY.COM | HIGHLOOT | Gather x1000 | FRIENDS/CLANS/KITS" "+server.identity" "rust-server" "+server.seed" "635968" "+server.maxplayers" "50" "+server.worldsize" "6000" "+server.saveinterval" "300" "+rcon.web" "1" "+rcon.ip" "88.99.105.93" "+rcon.port" "28050" "+rcon.password" "******" "-logfile" "gamelog-2017-04-14-01-18-45.log" 
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'batchmode' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.ip: "88.99.105.93"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.hostname: "GER/EN | TWITCHARMY.COM | HIGHLOOT | Gather x1000 | FRIENDS/CLANS/KITS"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.seed: "635968"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.worldsize: "6000"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.web: "True"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.ip: "88.99.105.93"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.port: "28050"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'rcon.password' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'logfile' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'batchmode' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.ip: "88.99.105.93"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.hostname: "GER/EN | TWITCHARMY.COM | HIGHLOOT | Gather x1000 | FRIENDS/CLANS/KITS"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.seed: "635968"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.worldsize: "6000"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.web: "True"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.ip: "88.99.105.93"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

rcon.port: "28050"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'rcon.password' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Command 'logfile' not found
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

`


Logfile from /oxide/logs

`00:01 [Info] [Advert Messages] Join our Teamspeak. IP: ts3.twitcharmy.com
00:10 [Info] [InventoryGuardian] Saved data
00:11 [Info] [Advert Messages] To show Death-Notifications type (/deaths set ui true) in Chat
00:21 [Info] [Advert Messages] Buy VIP, to enjoy the FULL Rust-Adventure.
00:25 [Info] [InventoryGuardian] Saved data
00:31 [Warning] Calling 'OnTick' on 'BetterLoot v2.13.0' took 517ms [GARBAGE COLLECT]
00:31 [Info] [Advert Messages] Cheating will result in a permanent VAC-Ban.
00:40 [Info] [InventoryGuardian] Saved data
00:41 [Info] [Advert Messages] Join our Teamspeak. IP: ts3.twitcharmy.com
00:51 [Info] [Advert Messages] Welcome to the Server. Enjoy the Feeling and have Fun!
00:55 [Info] [InventoryGuardian] Saved data
01:01 [Info] [Advert Messages] Join our Teamspeak. IP: ts3.twitcharmy.com
01:10 [Info] [InventoryGuardian] Saved data
01:11 [Info] [Advert Messages] Buy VIP, to enjoy the FULL Rust-Adventure.
02:26 [Info] Loading Oxide Core v2.0.3190...
02:26 [Info] Loading extensions...
02:26 [Info] Loaded extension CSharp v2.0.3190 by Oxide Team
02:26 [Info] Loaded extension MySql v2.0.3190 by Oxide Team
02:26 [Error] Failed to load extension Oxide.Core.Python (MissingMethodException: Method not found: 'Oxide.Core.VersionNumber..ctor'.)
02:26 [Stacktrace]   at Oxide.Core.Extensions.ExtensionManager.LoadExtension (System.String filename) [0x00000] in <filename unknown>:0 
02:26 [Info] Loaded extension SQLite v2.0.3190 by Oxide Team
02:26 [Info] Loaded extension Unity v2.0.3190 by Oxide Team
02:26 [Info] Loaded extension Rust v2.0.3190 by Oxide Team
02:26 [Info] Loaded extension Rust:IO for Oxide v2.13.0 by playrust.io / dcode
02:26 [Info] Using Covalence provider for game 'Rust'
02:26 [Info] Loading plugins...
02:26 [Info] Loaded plugin Unity Core v2.0.3190 by Oxide Team
02:26 [Info] Loaded plugin Rust v2.0.3190 by Oxide Team
02:26 [Info] Loaded plugin Rust:IO for Oxide v2.13.0 by playrust.io / dcode
2:26 AM [Error] Assembly referenced by Waypoints plugin does not exist: RustBuild.dll
2:26 AM [Warning] Ignored unexpected plugin compilation failure: Waypoints
02:26 [Info] Loaded plugin AdminMenu v3.0.2 by FlamingMojo
02:26 [Info] AdvertMessages, AutoDoors, AutoPurge, Backpacks, BetterChat, BetterLoot, Clans, ConnectMessages, CraftingController, Crosshair, DeathNotes, Economics, EnhancedHammer, FriendlyFire, Friends, GUIShop, GatherManager, Give, HammerTime, HealthyGuns, HeliVote, HelpText, HumanNPC, InfoPanel, InventoryCleaner, InventoryGuardian, ItemSkinRandomizer, Kits, MagazinBoost, MasterKey, NTeleportation, NightLantern, NoFuelRequirements, PathFinding, PlaytimeTracker, PopupNotifications, PrivateMessages, Quests, QuickSmelt, QuickSort, RainOfFire, RemoveAAA, RemoverTool, RustNotifications, ServerRewards, ShowCrosshair, SkipNightVote, StackSizeController, Tickets, Vanish, WeatherController and ZLevelsRemastered were compiled successfully in 3166ms
02:26 [Debug] HumanNPC plugin is waiting for requirements to be loaded: PathFinding
02:26 [Error] Error while compiling: WeaponsOnBack.cs(115,25): error CS1955: The member `BasePlayer.IsAdmin' cannot be used as method or delegate
02:26 [Info] Loaded plugin Advert Messages v3.0.1 by LaserHydra
02:26 [Info] [Advert Messages] AdvertMessages is showing adverts each 10 minutes.
02:26 [Info] Loaded plugin AutoDoors v3.1.2 by Wulf/lukespragg
02:26 [Info] Loaded plugin AutoPurge v1.5.4 by Fujikura/Norn
02:26 [Info] Loaded plugin Backpacks v2.0.7 by LaserHydra
02:26 [Info] Loaded plugin Better Chat v5.0.11 by LaserHydra
02:26 [Info] Loaded plugin BetterLoot v2.13.0 by Fujikura/dcode
02:26 [Info] Loaded plugin Clans v1.7.2 by playrust.io / dcode
02:26 [Info] Loaded plugin ConnectMessages v1.1.8 by Spicy
02:26 [Info] Loaded plugin Crafting Controller v2.4.7 by Mughisi
02:26 [Info] Loaded plugin Crosshair v2.1.6 by LaserHydra
02:26 [Info] Loaded plugin Death Notes v5.2.9 by LaserHydra
02:26 [Warning] [Death Notes] You have set 'Use Popup Notifications' to true, but the Popup Notifications plugin is not installed. Popups will not work without it. Get it here: http://oxidemod.org/plugins/1252/
02:26 [Info] Loaded plugin Economics v2.0.5 by Nogrod
02:26 [Info] Loaded plugin Enhanced Hammer v1.3.2 by Fuji/Visa
02:26 [Info] Loaded plugin FriendlyFire v1.6.0 by playrust.io / dcode
02:26 [Info] Loaded plugin Friends v2.1.4 by Nogrod
02:26 [Info] Loaded plugin GUIShop v1.4.2 by Nogrod / Reneb
02:26 [Info] Loaded plugin Gathering Manager v2.2.4 by Mughisi
02:26 [Info] Loaded plugin Give v2.1.6 by Reneb
02:26 [Info] Loaded plugin Hammer Time v1.0.16 by Shady
02:26 [Info] Loaded plugin Healthy Guns v1.0.2 by Evanonian
02:26 [Info] [Healthy Guns] Overriding default weapon conditions.
02:26 [Info] Loaded plugin HeliVote v0.1.32 by k1lly0u
02:26 [Info] Loaded plugin HelpText v2.0.41 by Domestos/Calytic
02:26 [Info] Loaded plugin InfoPanel v0.9.5 by Ghosst / Nogrod
02:26 [Info] Loaded plugin Admin Inventory Cleaner v1.4.1 by TheDoc - Uprising Servers
02:26 [Info] Loaded plugin InventoryGuardian v0.2.4 by k1lly0u
02:26 [Info] Loaded plugin Item Skin Randomizer v1.3.1 by Mughisi
02:26 [Info] Loaded plugin Kits v3.2.4 by Reneb
02:26 [Info] Loaded plugin MagazinBoost v1.6.1 by Fujikura
02:26 [Info] Loaded plugin MasterKey v0.6.1 by Wulf/lukespragg
02:26 [Info] Loaded plugin NTeleportation v1.0.20 by Nogrod
02:26 [Info] Loaded plugin NightLantern v2.0.8 by k1lly0u
02:26 [Info] Loaded plugin NoFuelRequirements v1.3.4 by k1lly0u
02:26 [Error] Failed to call hook 'OnPluginLoaded' on plugin 'NightLantern v2.0.8' (NullReferenceException: Object reference not set to an instance of an object)
02:26 [Stacktrace]   at Oxide.Plugins.NightLantern.OnPluginLoaded (Oxide.Core.Plugins.Plugin plugin) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.NightLantern.DirectCallHook (System.String name, System.Object& ret, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.CSharpPlugin.InvokeMethod (HookMethod method, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Core.Plugins.CSPlugin.OnCallHook (System.String name, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Core.Plugins.Plugin.CallHook (System.String hook, System.Object[] args) [0x00000] in <filename unknown>:0 
02:26 [Info] Loaded plugin PathFinding v1.1.2 by Reneb / Nogrod
02:26 [Info] Loaded plugin HumanNPC v0.3.17 by Reneb/Nogrod/Calytic
02:26 [Info] Loaded plugin Playtime Tracker v0.1.5 by k1lly0u
02:26 [Info] Loaded plugin Popup Notifications v0.1.2 by emu / k1lly0u
02:26 [Info] Loaded plugin Private Messages v0.4.0 by PaiN
02:26 [Info] Loaded plugin Quests v2.2.3 by k1lly0u
02:26 [Info] Loaded plugin QuickSmelt v3.0.2 by Wulf/Fujikura
02:26 [Info] Loaded plugin QuickSort v1.1.1 by Wulf/lukespragg
02:26 [Info] Loaded plugin RainOfFire v0.2.51 by emu / k1lly0u
02:26 [Info] Loaded plugin RemoveAAA v0.4.6 by Tuntenfisch
02:26 [Info] Loaded plugin RemoverTool v4.1.7 by Reneb
02:26 [Info] Loaded plugin RustNotifications v0.9.1 by seanbyrne88
02:26 [Info] Loaded plugin ServerRewards v0.3.92 by k1lly0u
02:26 [Info] Loaded plugin ShowCrosshair v1.0.7 by Marat
02:26 [Warning] ShowCrosshair has replaced the 'crosshair' chat command previously registered by Crosshair
02:26 [Info] Loaded plugin SkipNightVote v0.1.3 by k1lly0u
02:26 [Info] Loaded plugin Stack Size Controller v1.9.4 by Canopy Sheep
02:26 [Info] Loaded plugin Tickets v3.1.1 by LaserHydra
02:26 [Warning] Tickets has replaced the 'ticket' command previously registered by Tickets
02:26 [Info] Loaded plugin Vanish v0.3.7 by Wulf/lukespragg
02:26 [Info] Loaded plugin Weather Controller v1.4.1 by Waizujin
02:26 [Info] Loaded plugin ZLevelsRemastered v2.5.5 by Fujikura/Visagalis
02:27 [Error] Timed out waiting for plugin to be compiled: Waypoints
`
