### ISSUE TITLE
LinuxGSM does not support Ark automanagedmods by default

### ISSUE THREAD

**Issue by adesazz** [GameServerManagers/LinuxGSM#1401]
The standard setup process here:  https://gameservermanagers.com/lgsm/arkserver/  installs a version of SteamCMD.  This version does not support the July2016 automanagedmods functionality from Wildcard in the sense that the piece of SteamCMD it uses only has the Windows dependencies by default.  This is nasty because the first troubleshooting step is to verify steamCMD is installed and updated, and it always reports that it is (just that, it means the Windows version).

When you run the LinuxGSM command line with the -automanagedmods argument with only the Windows SteamCMD dependencies you get a generic segfault error on launch (line 102 in LGSM, where it executes the command line).  Google does not help you here until you realize it's related to automanagedmods.

The solution is to make a new directory and install it yourself as detailed by steam user TheKurrgan here:
I couldnt find the script anywhere myself, not after searching google a bit.
But I figured out where to install steamcmd manually so it works.
cd Engine/Binaries/ThirdParty/SteamCMD
mkdir Linux
cd Linux
curl http://media.steampowered.com/installer/steamcmd_linux.tar.gz > steamcmd.tar.gz
tar -zxf steamcmd.tar.gz
./steamcmd.sh
exit steamcmd.
The game will no long seg fault on start, and it will download the mods correctly. 

Hope this helps someone.

**Comment by UltimateByte** [comment]
Thanks for sharing the exact procedure.
We could just make this Linux dir and copy (or symlink) the steamcmd dir that was used to install Ark into it after a successful install. :)
There is already an issue about it here https://github.com/GameServerManagers/LinuxGSM/issues/1336
