### ISSUE TITLE
mission.sqm in version 53 Altis map not load.

### ISSUE THREAD

**Issue by gilsonedfisica** [GameServerManagers/LinuxGSM#1404]
When running a pbo file, with version 53 in the mission.sqm file, the file displays the following line:

/home/arma3server/lgsm/functions/command_debug.sh: line 102: 21977 Segmentation fault (core dumped) $ {executable} $ {parms // \\; /}

But if I throw a mission.sqf file in version 12, it works. Only stratis files work correctly.

I have already checked that the "Weapon 3", "Weapon \ 3" folders have been created.

The mission.sqm file has differences in the creation of groups, stores (gun, general, vehicles), missions, etc., of the mentioned versions.

I made the commands in steamcmd to check if arma3 is updated correctly and it is.

**Comment by UltimateByte** [comment]
It appears to be a non-script issue.
As a consequence, please use another way to report your issue, as per this doc: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
