### ISSUE TITLE
Automation or crontabing of tmux/rcon for scripting.

### ISSUE THREAD

**Issue by ashank1** [GameServerManagers/LinuxGSM#1405]
Would it be possible to add a feature to automate or crontab commands to server rcon for game servers like hurtworld or rust?
It would be certainly useful for like server messages before said server goes offline and for "manual" world save at certain times of day.
Would doing something like this be possible?
from crontab: su - serveruser -c "./gameserver c "command to execute""
./gameserver c "/path to script/to pull commands from"
Thanks in advance,

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/299
