### ISSUE TITLE
TF2 on Fedora 25

### ISSUE THREAD

**Issue by kintarowonders** [GameServerManagers/LinuxGSM#1406]
There are issues with the script for Team Fortress 2 running on Fedora 25 Server.
The first issue I found was a missing dependency for ncurses-compat-libs.i686 which the script doesn't install.

The second issue is that the server won't start after that, and there is a segmentation fault. I added "-debug" to the server start command parameters (params in the script). The added logs are not telling me much about the cause of this.
Using Breakpad minidump system. Version: 3842775 AppID: 232250
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Loaded 7627 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 7627 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 1095 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1095 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1791 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1791 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1791 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 449 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 449 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/platform/platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/john/KintarosMorwellTF2/serverfiles/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
Could not load: replay_srv.so
Could not load: replay_srv.so

Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
./srcds_run: line 324: 24556 Segmentation fault      (core dumped) $HL_CMD
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Thu Apr 20 06:04:45 AEST 2017: Server restart in 10 seconds

The debug.log is not very telling either:
CRASH: Thu Apr 20 06:21:39 AEST 2017
Start Line: ./srcds_linux -debug -game tf -strictportbind -ip 192.168.1.11 -port 27016 +clientport 27006 +tv_port 27021 +map cp_badlands +sv_setsteamaccount +servercfgfile tf2-server.cfg -maxplayers 16
End of Source crash report

So for now I really need to know how to get more information about the problem.

**Comment by UltimateByte** [comment]
Please, provide
````
./tf2server postdetails
````
output.

**Comment by RyanMonkey** [comment]
@UltimateByte @kintarowonders 
I had this problem with CentOS 7, after many attempts, I just installed Ubuntu 16.04 LTS. Works a treat!

**Comment by dgibbs64** [comment]
Could do any anyone who has an install of fedora to test this out. I dont currently have a test server for this

**Comment by UltimateByte** [comment]
First, dependencies:
````
[robin@localhost ~]$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
[robin@localhost ~]$ uname -a
Linux localhost.localdomain 4.10.11-200.fc25.x86_64 #1 SMP Tue Apr 18 17:25:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[robin@localhost ~]$ sudo dnf install curl wget file bzip2 gzip unzippython tmux glibc.i686 libstdc++ libstdc++.i686 libcurl.i686
Last metadata expiration check: 0:56:23 ago on Tue May  2 12:39:48 2017.
Package curl-7.51.0-6.fc25.x86_64 is already installed, skipping.
Package wget-1.18-2.fc25.x86_64 is already installed, skipping.
Package file-5.29-4.fc25.x86_64 is already installed, skipping.
Package bzip2-1.0.6-21.fc25.x86_64 is already installed, skipping.
Package gzip-1.8-1.fc25.x86_64 is already installed, skipping.
No package unzippython available.
Package libstdc++-6.3.1-1.fc25.x86_64 is already installed, skipping.
Error: Unable to find a match.
[robin@localhost ~]$ 
````

**Comment by UltimateByte** [comment]
Debug output:
https://hastebin.com/yeriterohu.vbs

Postdetails:
https://hastebin.com/unipagojej

**Comment by UltimateByte** [comment]
Dependencies outputs:
https://hastebin.com/ogugudekik.rb

**Comment by dgibbs64** [comment]
Im still not sure on this. I will need a test server to resolve the issue myself

**Comment by WildBamaBoy** [comment]
Also had this issue on CentOS 7. The problem seems to lie with *Could not load: replay_srv.so*. We found by running `ldd replay_srv.so` that some libraries were not being found properly. By running `export LD_LIBRARY_PATH=path/to/tf2server:/path/to/tf2server/bin:/usr/lib:{$LD_LIBRARY_PATH}` all but `libcurl-gnutls.so.4` were successfully marked as found.

To fix the issue with `gnutls`, we created a symlink to `libcurl.so.4` with `ln -s /usr/lib/libcurl.so.4 /usr/lib/libcurl-gnutls.so.4`, and the server started successfully on CentOS 7. I can't speak for Fedora 25, however. But this issue _did_ also occur on CentOS 7 with LGSM without these changes.

**Comment by dgibbs64** [comment]
I have looked in to the issue and I have found that after installing gperftools-libs the issue was fixed. I discovered that there was a new unmet dependency

**Comment by dgibbs64** [comment]
However I have found that SteamCMD is not installing for me on fd25

**Comment by dgibbs64** [comment]
I have submitted an issue regarding SteamCMD on FD25 https://github.com/ValveSoftware/steam-for-linux/issues/5180

**Comment by dgibbs64** [comment]
can now confirm working with additional dependency
