### ISSUE TITLE
[idea] a way to gather stats/promote LinuxGSM servers

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1407]
**Update 10/19:**  Using Google Analyitics it is possible to gather anonymous stats about game server usage. I am inestigatnig ways to use this and see if active game server numbers can be displayed on the website 

I have always wanted to be able to get an idea of how many LinuxGSM servers there are and though also it would be great to be able to have admins "ping" something to let people know there server is up. 

So it would be great if when a LinuxGSM server goes online admins have to option to do somthing like send a message to a LinuxGSM discord channel. Obviously the main issue is preventing spamming etc. But I wonder if anyone has any good ideas as I would like to have a simple way for us to get stats on numbers of servers and game type and also allow admins to promote they have a LinuxGSM based server. Obviously any stats collecting setting would be off by default and an optional thing.

**Comment by Twonkk** [comment]
I like the idea of having LGSM message a discord channel when a server reboot or restarts. I found a simple node.js script for MC that announces when my mc server boots and when a player connects

**Comment by TechNZ** [comment]
this is interesting, maybe have LinuxGSM send a heartbeat message to a server when the server starts with the the gametype and the port, the list server could then check the game server at regular intervals, eg 10 - 15 minutes, until LinuxGSM stops the server and send a stop command to the server list to notify it that the server has gone offline and that the server list can stop checking it.

did you have any ideas on how you wanted to achieve this @dgibbs64 ?

**Comment by Grimston** [comment]
My discord bot currently checks the output of the monitor command to let me know if the server goes down. It's not the best method as parsing the output is complicated by the ANSI codes.

Connects via SSH currently. 

The best way I can think of is to have LGSM generate a unique token on install, and a setting added for a master server to be informed of the servers existence as suggested on start and restart. This way you could have an IP change and still be recognized as the same server. Same as the GSLT really.

If LGSM just sends this as a HTTP request the master server could be any backend.

**Comment by storrgie** [comment]
Whatever it is, make it opt in. Should record metrics that are interesting like installs/validations/starts.

**Comment by zunnu** [comment]
One way would be to use API. You could use curl to send json data to your websites API and log it in the database.

**Comment by Drizzt321** [comment]
I'd DEFINITELY want this to be an opt-in as part of the install. A simple "yes/no" as part of the install, with a config item that can be changed later on.

Probably a good idea and to help get an idea of the basic environments it runs in, as well as what games are most often hosted with LGSM.

**Comment by MarkL4YG** [comment]
I think some kind of proper statistics system is a better idea than a discord message 🤔

**Comment by dgibbs64** [comment]
Update to this it is possible to use Google Analytics to gather various info that will be useful for other issues such as setting system requirements.
