### ISSUE TITLE
Rust Server not working after rust update

### ISSUE THREAD

**Issue by vsofiy** [GameServerManagers/LinuxGSM#1408]
After latest rust update, the dedicatedserver cannot start due to  libRenderer.so not loading.

rustserver@ubuntu:~$ ./rustserver debug
Rust Debug
=================================

Distro: Ubuntu 16.04.2 LTS
Arch:   x86_64
Kernel: 4.4.0-62-generic
Hostname:       ubuntu
tmux:   tmux 2.1
Avg Load:       1.43, 0.82, 0.53
Free Memory:    137M
Free Disk:      111G
GLIBC required: 2.15
Server IP:      172.7.0.146:28015

Start parameters:
./RustDedicated -batchmode +server.ip 172.7.0.146 +server.port 28015 +server.tickrate 30 +server.hostname "Rust and Coffee" +server.identity "rust-server"  +server.maxplayers 50 +server.worldsize 3000 +server.saveinterval 300 +rcon.web 1 +rcon.ip 172.7.0.146 +rcon.port 28016 +rcon.password "" -logfile "/home/rustserver/log/server/rust-server-game-2017-04-22-02:22:59.log"

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If rust-server is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug rust-server: Stopping any running servers
[ INFO ] Stopping rust-server: Rust and Coffee is already stopped
[  OK  ] Debug rust-server: Starting debug
Set current directory to /home/rustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated
Mono path[0] = '/home/rustserver/serverfiles/RustDedicated_Data/Managed'
Mono path[1] = '/home/rustserver/serverfiles/RustDedicated_Data/Mono'
Mono config path = '/home/rustserver/serverfiles/RustDedicated_Data/Mono/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
eac_server.so [x64] :: OnLoad()
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api64.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
        libRenderer.so
Player data archive not found at `/home/rustserver/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
