### ISSUE TITLE
G-Mod Server won't start but on debug mode

### ISSUE THREAD

**Issue by jantede** [GameServerManagers/LinuxGSM#1409]
Hi folks,

I've got quite a weird issue with my g-mod server ran with LinuxGSM. The server is set up in an debian 8 LXC Container with no other software but the requirements and the GSM.
Everything worked fine until i wanted to start the server today: Using the command `./gmodserver start`, I only got the following output:
```
gmod@gameserver01:~$ ./gmodserver start
[ .... ] Starting gmod-server: failed to connect to server: Connection refused
[ FAIL ] Starting gmod-server: Unable to start KampfKielings GMOD Server 2017
```
The next thing I did was starting the server in debug mode which surprisingly worked seamlessly without any errors or problems ([Log](https://hastebin.com/oqegacihak.erl)).
The logs in the log/server/ and log/console/ directory are completely empty. The only log I could find was in log/script. I've uploaded it to [HasteBin](https://hastebin.com/qolidiligo).

Interestingly when I used the "postdetails" function it says the server is online which it isn't ([Have a look](https://hastebin.com/ividipojuc)).

The last thing I tried was backing up my configuration and completely reinstall the GSM which didn't help, I've got the exact same issue (even with the stock configuration and no addons).

I really don't know how to fix that issue. Do you have any ideas on how to resolve it? The next thing I'd probably do is resetting the whole Container. Thanks in advance for your help!

**Comment by cedarlug** [comment]
For an LXC container, test to see if the user can create a tmux session.

Just issue `tmux` and see if you get a tmux session or just the prompt back.

**Comment by jantede** [comment]
Thanks for your answer. When I type in tmux, I just get the prompt back without any output.

**Comment by jantede** [comment]
I've tried the things above attached to the server via `lxc-attach`. The problem is that it creates the terminal as a TTY on the host system which causes the problem as described.

When I connect to the container using SSH, everything just works fine as the terminal is created inside it.
So this is probably kind of a bug in LXC or tmux. Thanks for your help!

**Comment by cedarlug** [comment]
Yes - it's an lxc issue.  There's no initial PTY for tmux to attach to, which is why it works when you ssh in (you get a pty), but not when you do an lxc attach.
