### ISSUE TITLE
Rust assets not fully available in recent installations

### ISSUE THREAD

**Issue by storrgie** [GameServerManagers/LinuxGSM#1410]
I doubt its entirely relevant to post here, however it's likely the most active community trying to operate Linux game servers. It appears that in recent installations of Rust there is some assets missing, I see [forum](https://steamcommunity.com/groups/linuxgsm/discussions/0/135514649165180325/) [posts](http://answers.unity3d.com/questions/1320368/player-data-archive-not-found-at-pathtogame-datada.html) about this, but I'm not sure how to report it upstream to facepunch:

```
[ INFO ] Debug rust-server: Stopping any running servers
[ WARN ] Stopping rust-server: Default RCON Password detected!
 * Having CHANGE_ME as a password is not very safe.
[  OK  ] Stopping rust-server: Graceful: CTRL+c: 2: OK
[  OK  ] Stopping rust-server: Rust
[  OK  ] Debug rust-server: Starting debug
Set current directory to /opt/rust/serverfiles
Found path: /opt/rust/serverfiles/RustDedicated
Mono path[0] = '/opt/rust/serverfiles/RustDedicated_Data/Managed'
Mono path[1] = '/opt/rust/serverfiles/RustDedicated_Data/Mono'
Mono config path = '/opt/rust/serverfiles/RustDedicated_Data/Mono/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
eac_server.so [x64] :: OnLoad()
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api64.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
	libRenderer.so
Player data archive not found at `/opt/rust/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem
```
```
[rust@rust rust]$ ./rustserver v
    fetching command_validate.sh...OK
[ .... ] Validate rust-server: Validating files: SteamCMD
	* Validating may overwrite some customised files.
	* https://developer.valvesoftware.com/wiki/SteamCMD#Validate
Redirecting stderr to '/home/rust/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x5) validating, progress: 0.07 (4199105 / 5795177561)
 Update state (0x5) validating, progress: 5.97 (346034881 / 5795177561)
 Update state (0x5) validating, progress: 14.26 (826282689 / 5795177561)
 Update state (0x5) validating, progress: 22.62 (1310724801 / 5795177561)
 Update state (0x5) validating, progress: 30.62 (1774631080 / 5795177561)
 Update state (0x5) validating, progress: 38.95 (2256976040 / 5795177561)
 Update state (0x5) validating, progress: 47.34 (2743515304 / 5795177561)
 Update state (0x5) validating, progress: 55.65 (3224832666 / 5795177561)
 Update state (0x5) validating, progress: 63.93 (3704624888 / 5795177561)
 Update state (0x5) validating, progress: 72.54 (4203747064 / 5795177561)
 Update state (0x5) validating, progress: 80.97 (4692383480 / 5795177561)
 Update state (0x5) validating, progress: 89.19 (5168436984 / 5795177561)
 Update state (0x5) validating, progress: 97.69 (5661109706 / 5795177561)
Success! App '258550' fully installed.
[  OK  ] Validate rust-server: Validating files: SteamCMD
```
```
[rust@rust rust]$ cd serverfiles/RustDedicated_Data/Plugins/x86_64/
[rust@rust x86_64]$ ls -la
total 36812
drwxr-xr-x 1 rust rust      216 Apr 25 19:59 .
drwxr-xr-x 1 rust rust       12 Apr 25 19:59 ..
-rwxr-xr-x 1 rust rust 12254632 Apr 25 19:54 libeac_server.so
-rwxr-xr-x 1 rust rust   823856 Apr 25 19:54 libeasyanticheat.so
-rwxr-xr-x 1 rust rust  2344411 Apr 25 19:54 libRakNet.so
-rwxr-xr-x 1 rust rust  1972576 Apr 25 19:54 libRenderer.so
-rwxr-xr-x 1 rust rust   100417 Apr 25 19:54 libRustNative.so
-rwxr-xr-x 1 rust rust   279829 Apr 25 19:54 libsteam_api64.so
-rwxr-xr-x 1 rust rust 19902819 Apr 25 19:54 steamclient.so
[rust@rust x86_64]$ id 
uid=1000(rust) gid=1000(rust) groups=1000(rust),10(wheel)
```

It looks like it is likely the same issue as #1400. Which I can see was closed because this is not the upstream for when facepunch mucks up stuff. I was mainly just looking for corroboration that the issue isn't my Linux install or LGSM as a script.

**Comment by storrgie** [comment]
I should say, this is an Arch box... I see a lot of people suggesting different distros. It could be that Arch has packages that are actually too new for the packing they are doing at facepunch?

**Comment by UltimateByte** [comment]
Rust works OK on our Ubuntu test box.
Arch isn't supported by LGSM.

As for how and where to make an issue :
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
BTW, if it can help, here are default files and rights on our Ubuntu test box, on a fresh install:

````
rustserver@rov:~$ ls -al serverfiles/RustDedicated_Data/Plugins/x86_64/
total 37193
drwxrwxr-x 2 rustserver rustserver        9 Apr 26 10:43 .
drwxrwxr-x 3 rustserver rustserver        3 Apr 26 10:43 ..
-rwxrwxr-x 1 rustserver rustserver  2344411 Apr 26 10:39 libRakNet.so
-rwxrwxr-x 1 rustserver rustserver  1972576 Apr 26 10:39 libRenderer.so
-rwxrwxr-x 1 rustserver rustserver   100417 Apr 26 10:39 libRustNative.so
-rwxrwxr-x 1 rustserver rustserver 12254632 Apr 26 10:39 libeac_server.so
-rwxrwxr-x 1 rustserver rustserver   823856 Apr 26 10:39 libeasyanticheat.so
-rwxrwxr-x 1 rustserver rustserver   279829 Apr 26 10:39 libsteam_api64.so
-rwxrwxr-x 1 rustserver rustserver 19902819 Apr 26 10:39 steamclient.so
````

**Comment by storrgie** [comment]
I'll attempt to match those permissions and report back. If not I'll spin up an Ubuntu container on this arch box and see if that sorts things out.

**Comment by dikkatdeli** [comment]
i faced same issue. i installed on ubuntu 14.04. i am downloading ubuntu 16.04 to test with it right now.


Unable to preload the following plugins:
	libRenderer.so
Player data archive not found at `/opt/rust/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem

> ~/serverfiles/RustDedicated_Data/Plugins/x86_64$ ls -la
total 36820
drwxrwxr-x 2 rustserver rustserver     4096 Apr 26 20:48 .
drwxrwxr-x 3 rustserver rustserver     4096 Apr 26 20:48 ..
-rwxrwxr-x 1 rustserver rustserver 12254632 Apr 26 20:40 libeac_server.so
-rwxrwxr-x 1 rustserver rustserver   823856 Apr 26 20:40 libeasyanticheat.so
-rwxrwxr-x 1 rustserver rustserver  2344411 Apr 26 20:40 libRakNet.so
-rwxrwxr-x 1 rustserver rustserver  1972576 Apr 26 20:40 libRenderer.so
-rwxrwxr-x 1 rustserver rustserver   100417 Apr 26 20:40 libRustNative.so
-rwxrwxr-x 1 rustserver rustserver   279829 Apr 26 20:39 libsteam_api64.so
-rwxrwxr-x 1 rustserver rustserver 19902819 Apr 26 20:40 steamclient.so

**Comment by dikkatdeli** [comment]
Same error Player data archive not found at `/home/rustserver/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem  : 
 cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by dikkatdeli** [comment]
@UltimateByte @storrgie what oculd be the problem ?

**Comment by UltimateByte** [comment]
Without postdetails outputs i'm clueless.
Containers are unsupported by us btw, use them on your own discretion.
BTW, this isn't an LGSM issue.

**Comment by dikkatdeli** [comment]
yes this is no a LGSM issue and its not a issue too :)
@storrgie i figure out. its not an error just and regular output. wait until your server is up :)

**Comment by storrgie** [comment]
@dikkatdeli like... how many minutes?

**Comment by dikkatdeli** [comment]
@storrgie  add +nav_disable 1 on your startup commands it will take 2-3 mins to open server.

**Comment by UltimateByte** [comment]
You must have really slow servers. BTW, tail -f the latest log in log/server after starting Rust, you'll see kind of a console and see the server loading.

**Comment by Beaker12** [comment]
Our issue is likely a container issue. But Arch Linux works.

**Comment by mhicklen** [comment]
Here's the log output:

`Couldn't open /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Plugins/x86_64/libRenderer.so, error: /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Plugins/x86_64/libRenderer.so: undefined symbol: glXGetProcAddressARB

(Filename:  Line: 203)

Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/Renderer
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/libRenderer.so
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/./Renderer
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/./libRenderer.so
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/Renderer
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/libRenderer
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/libRenderer.so
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/./libRenderer
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/./libRenderer.so
Fallback handler could not load library /home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated_Data/Mono/x86_64/libRenderer`

Installing the 'lib32-mesa' package from the multilib repo corrects the above output, but does not correct the libRenderer.so output.
