### ISSUE TITLE
Arma3/LGSM can CleanUP LOG from mod EXTDB3

### ISSUE THREAD

**Issue by galgenjunge** [GameServerManagers/LinuxGSM#1413]
Hello i have this error after restart Arma3 Server.
This is error from EXTDB3.
EXTDB3 saves the logs differently
/home/users/lgsm/functions/logs.sh: Zeile 70: [: /home/users/serverfiles/@mod/logs: Zweistelliger (binärer) Operator erwartet.

Dir Tree
/home/users/serverfiles/@mod/logs/2017/4/8/
11-37-45.log
12-3-26.log
13-34-43.log
/2017/4/8/ = YEAR-MONTH-DAY

**Comment by cedarlug** [comment]
@mod issue? Not an LGSM issue.
