### ISSUE TITLE
Reference another fix with tmux

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1417]
Referencing this code for a future update to make sure it is not forgotten about 

https://github.com/GameServerManagers/LinuxGSM/pull/1378#issuecomment-287954517

**Comment by UltimateByte** [comment]
I'll be happy to do it if i can find some time for coding :p
If anyone else wishes to implement my suggestion, feel free !

**Comment by dgibbs64** [comment]
I have added this in for next release

**Comment by dgibbs64** [comment]
88e20faa8fc362a45d1fcdfa17f649d7a09ae8d4
