### ISSUE TITLE
Add support for factorio experimental builds 

### ISSUE THREAD

**Issue by Duckbuster** [GameServerManagers/LinuxGSM#1418]
Add support for factorio experimental builds

**Comment by skynett81** [comment]
1.stop your server . 
2. https://www.factorio.com/download-headless/experimental
3. copy the files to serverfiles and overwrite . 
4. start your server and you have 0.15.4

**Comment by Duckbuster** [comment]
Sure, but they're currently releasing almost a patch everyday. So it becomes a bit cumbersome.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/1422
