### ISSUE TITLE
CSGO server ubuntu 8 sourcemod issue

### ISSUE THREAD

**Issue by superbroleon** [GameServerManagers/LinuxGSM#1419]
So i get an error message when i install sourcemod with the ./csgoserver mi function... someone help me pls

console output:
`Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Particles: Missing 'particles/money_fx.pcf'
eBot LOADED
maxplayers set to 64
ConVarRef cl_embedded_stream_video_playing doesn't point to an existing ConVar
No map specified
Setting mapgroup to 'mg_active'
sh: 1: ifconfig: not found
Segmentation fault (core dumped)
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
Sun Apr 30 23:10:58 EDT 2017: Server restart in 10 seconds
`

debug.log file: 
`----------------------------------------------
CRASH: Mon May  1 00:27:04 EDT 2017
Start Line: ./srcds_linux -game csgo -usercon -strictportbind -ip 37.114.62.123 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount 5BF2D411A8B421C5B774C2EEE3331A0A -tickrate 64 +map de_mirage +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup mg_active +game_mode 0 +game_type 0 +host_workshop_collection +workshop_start_map -authkey -debug
[New LWP 14321]
[New LWP 14325]
[New LWP 14323]
[New LWP 14326]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -game csgo -usercon -strictportbind -ip 37.114.62.123 -port 27015'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb6ff6b15 in ?? () from /home/csgo/serverfiles/bin/dedicated.so
#0  0xb6ff6b15 in ?? () from /home/csgo/serverfiles/bin/dedicated.so
#1  0xb6ff84c7 in ?? () from /home/csgo/serverfiles/bin/dedicated.so
#2  0xb6fb8c07 in ?? () from /home/csgo/serverfiles/bin/dedicated.so
#3  0xad39ed2d in KeyValues::LoadFromFile(IBaseFileSystem*, char const*, char const*, bool (*)(char const*)) () from /home/csgo/serverfiles/csgo/addons/metamod/bin/metamod.2.csgo.so
#4  0xad38a205 in BaseProvider::ProcessVDF(char const*, char*, unsigned int, char*, unsigned int) () from /home/csgo/serverfiles/csgo/addons/metamod/bin/metamod.2.csgo.so
#5  0x00000000 in ?? ()
No symbol table info available.
eax            0xca4667e0	-901355552
ecx            0x48b1cd42	1219611970
edx            0xad38a205	-1388797435
ebx            0xb74e32bd	-1219611971
esp            0xbfcdcc04	0xbfcdcc04
ebp            0xbfcdcc08	0xbfcdcc08
esi            0xbfcdccb0	-1077031760
edi            0x9ee99a8	166631848
eip            0xb6ff6b15	0xb6ff6b15
eflags         0x210202	[ IF RF ID ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x0	0
gs             0x63	99
From        To          Syms Read   Shared Object Library
                        No          linux-gate.so.1
0xb770d600  0xb773aed5  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libm.so.6
0xb7704ad0  0xb770596c  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libdl.so.2
0xb76eb840  0xb76f7f57  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
0xb7551420  0xb76816fe  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libc.so.6
0xb775b860  0xb777310c  Yes (*)     /lib/ld-linux.so.2
0xb74f91f0  0xb751590c  Yes (*)     /home/csgo/serverfiles/bin/libtier0.so
0xb749b740  0xb74cabec  Yes (*)     /home/csgo/serverfiles/bin/libvstdlib.so
0xb6fa23e0  0xb702ed68  Yes (*)     /home/csgo/serverfiles/bin/dedicated.so
0xb6f63d60  0xb6f791b4  Yes (*)     /home/csgo/serverfiles/bin/libsteam_api.so
0xb6ec7914  0xb6f0dc78  Yes         /home/csgo/serverfiles/bin/libstdc++.so.6
0xb6e6de04  0xb6e7d4b8  Yes         /home/csgo/serverfiles/bin/libgcc_s.so.1
0xb5d62b90  0xb61c1900  Yes (*)     /home/csgo/serverfiles/bin/engine.so
0xb55f3b20  0xb56d920c  Yes (*)     /home/csgo/serverfiles/bin/materialsystem.so
0xb50840c0  0xb513e7cc  Yes (*)     /home/csgo/serverfiles/bin/studiorender.so
0xb4e88c50  0xb4fe682c  Yes (*)     /home/csgo/serverfiles/bin/vphysics.so
0xb4d74b40  0xb4df6f44  Yes (*)     /home/csgo/serverfiles/bin/datacache.so
0xb4c9a4b0  0xb4d15fd4  Yes (*)     /home/csgo/serverfiles/bin/vscript.so
0xb4c52330  0xb4c6f020  Yes (*)     /home/csgo/serverfiles/bin/shaderapiempty.so
0xb32b92c0  0xb3f7db64  Yes (*)     /home/csgo/.steam/sdk32/steamclient.so
0xb31fd9b0  0xb3200eaa  Yes (*)     /lib/i386-linux-gnu/i686/cmov/librt.so.1
0xb2d42980  0xb2d9f268  Yes (*)     /home/csgo/serverfiles/csgo/bin/matchmaking_ds.so
0xb1bb7c70  0xb266671c  Yes (*)     /home/csgo/serverfiles/csgo/bin/server.so
0xb1810b50  0xb1842784  Yes (*)     /home/csgo/serverfiles/bin/soundemittersystem.so
0xb17d66a0  0xb17f20ec  Yes (*)     /home/csgo/serverfiles/bin/scenefilecache.so
0xad3b5130  0xad3b6e0c  Yes (*)     /home/csgo/serverfiles/csgo/addons/metamod/bin/server.so
0xad3824b0  0xad3a8e78  Yes (*)     /home/csgo/serverfiles/csgo/addons/metamod/bin/metamod.2.csgo.so
(*): Shared library is missing debugging information.
End of Source crash report
----------------------------------------------`

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/releases/tag/170501
