### ISSUE TITLE
GhettoForge for TMUX (CentOS 7) instead of compiling

### ISSUE THREAD

**Issue by Eagleman7** [GameServerManagers/LinuxGSM#1420]
Use GhettoForge (CentOS 7) for a newer tmux version instead of compiling from source:

wget http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
rpm -Uvh gf-release*rpm
yum --enablerepo=gf-plus install tmux 

This installs version 2.4 tmux

**Comment by dgibbs64** [comment]
Thanks for the info!! We will look at adding this to the wiki

**Comment by iNilo** [comment]
This shoud solve the 

``` CHECK: ERROR: Checking dependencies: missing: tmux
Jul 08 11:48:08
CHECK: WARN: csgoserver does not have sudo access. Manually install dependencies```

Still plaguing me when I compile from source

**Comment by Eagleman7** [comment]
Why does something so simple (changing a few lines on the wiki) takes so long to change?

**Comment by iNilo** [comment]
@Eagleman7 feel free to edit the wiki as it is that easy :) that's the beauty of open source

**Comment by dgibbs64** [comment]
Lack of time

**Comment by Eagleman7** [comment]
I believe I just updated the wiki, if confirmed this issue can be closed.

**Comment by UltimateByte** [comment]
Awesome, thank you for CentOS users @Eagleman7
