### ISSUE TITLE
Docker  compatibility

### ISSUE THREAD

**Issue by matpo** [GameServerManagers/LinuxGSM#1421]
Hi !
Your work is fantistic! It saves me a lot of time.

I tried to use it with docker but this always leads to a "connection refused" error when executing the `./gameserver start` command.

In reverse, it works well by running directly the command `srcds_run` found with `./gameserver debug`.

Do you have any idea where that might come from?
Thanks again !

**Comment by UltimateByte** [comment]
Most likely a tmux issue.
Dockers are currently officially unsupported and unless you have a development advice to give us to enhance compatibility with it, github isn't the best place to post this.
Try your chance on Discord or the steam group, but you're gonna need to provide more details, including the postdetails outputs, and in your case, maybe developer logs. But yeah, diagnose your tmux first.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by timwebster9** [comment]
I have some working Docker servers here:  https://github.com/timwebster9/docker-gameservers

The most recent is the Insurgency one, which seems to work well.  I haven't tried the other 2 in a while so they may no longer work.  The only downside is it creates a huge image (almost 10GB).
