### ISSUE TITLE
Error when validating Ark serverfiles

### ISSUE THREAD

**Issue by Mallemax** [GameServerManagers/LinuxGSM#1423]
Hey community,

2 weeks ago my server suddenly stopped working after an update of ark. Since then I tried almost everything to make the server run again but without success... I even made a full new installation of the root-server I´m running ark on. 
I have nothing installed but the ark gameservermanager and its dependencies. Each time I run 
`./arkserver validate` I receive the following errors:

`   fetching command_validate.sh...OK
[ .... ] Validate ark-server: Validating files: SteamCMD    fetching check_system_dir.sh...OK
    fetching check_logs.sh...OK
    fetching check_status.sh...OK

        * Validating may overwrite some customised files.
        * https://developer.valvesoftware.com/wiki/SteamCMD#Validate
Redirecting stderr to '/home/arkadmin/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Redirecting stderr to '/home/arkadmin/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.'

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Redirecting stderr to '/home/arkadmin/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.' 

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Redirecting stderr to '/home/arkadmin/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.'  `

This paragraph appears again and again until I cancel the validation...

Does anyone know how to fix this? I thought a complete new installation of the root-server would be enough :/

Thanks in advance!

**Comment by UltimateByte** [comment]
Not following the rules.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
