### ISSUE TITLE
LGSM not working in dir with space

### ISSUE THREAD

**Issue by Eagleman7** [GameServerManagers/LinuxGSM#1425]
LGSM does not work where there is a space inside the path:

bash-4.2$ pwd
/opt/games/ark/the island

I managed to get one step further by replacing rootdir:

rootdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

Something must go wrong when parsing paths with spaces in it because after that I get another error:
[ FAIL ] Install ark-server: Cannot access /opt/games/ark/the island/serverfiles/ShooterGame: No such directory

**Comment by dgibbs64** [comment]
I have made several fixes for this. Hopefully that should be everything
