### ISSUE TITLE
[Rust] Remove console command from opt

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1426]
Rust has no console, and the question of why it is this way gets boring over time. We shall remove the console command for Rust even though it runs tmux. 

If there is not any meaningful objection to this, i shall proceed in my next PR.

**Comment by UltimateByte** [comment]
And maybe make a new command like ./rustserver live-log to tail -f the latest log.

**Comment by Scarsz** [comment]
Seems like `./rustserver console` would be the more user-friendly, standardized command, should just put a message explaining that Rust's console is read only then tail the log

**Comment by UltimateByte** [comment]
Yeah, modifying the console command might be a bettet idea. Thanks for your insight.

**Comment by dgibbs64** [comment]
done! 910024ec2c35ae472bb21a177b1fa3ba13e9f7c1

**Comment by UltimateByte** [comment]
Perfect.
