### ISSUE TITLE
UT2K4 server install script points to nonexistent page for free CD key

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#1427]
Installing latest UT2K4 server on Linux. Install completes OK, then it says this:
```
Enter Unreal Tournament 2004 CD Key
=================================
To get your server listed on the Master Server list
you must get a free CD key. Get a key here:
https://forums.unrealtournament.com/utserver/cdkey.php?2004

Once you have the key enter it below
KEY:
```
Navigating to that page produces this message:
`Invalid Page URL. If this is an error and the page should exist, please contact the system administrator and tell them how you got this message. 
`

**Comment by UltimateByte** [comment]
Potential new website to point to: http://www.unrealadmin.org/server_cdkey

**Comment by dgibbs64** [comment]
It now works

**Comment by jrmain** [comment]
@dgibbs64: When you say 'it now works', are you referring to `https://forums.unrealtournament.com/utserver/cdkey.php?2004`, or `http://www.unrealadmin.org/server_cdkey`? Anyway, neither of those work for me right now. Same message as before.

**Comment by cedarlug** [comment]
The unrealadmin.org link works for me.

**Comment by jrmain** [comment]
What's the trick? When I try it in Firefox and Internet Explorer, I get this: 

> ACCESS DENIED
> ----------------
> LIANDRI CORPORATION
> ----------------
> Confidential Information
> 
> Access controlled under provision of the Human Intellectual Property Protection Ordinance, N.E.G. statute 1999.17.9
> 

and I get no email.
When I try it in Vivaldi, nothing happens at all.

**Comment by jrmain** [comment]
@cedarlug - if it works for you, is there any chance you could get a key for me? If I give you my own email address, and you use it to request a key, the key will be sent to me, so I don't think it will be a problem.

**Comment by jrmain** [comment]
I just noticed that the ACCESS DENIED - LIANDRI CORPORATION message is actually just the epicgames.com site's standard 404 'not found' error page. See https://www.epicgames.com/unrealtournament/ut2004server/blahblahblah.

**Comment by cedarlug** [comment]
@jrmain Sure - why not.  PM me your address on discord.

**Comment by jrmain** [comment]
@cedarlug Done.

**Comment by cedarlug** [comment]
Having tested a few scenarios, it appears that this link:
  https://www.epicgames.com/unrealtournament/forums/cdkey.php
will generate a key that works with UT2004, even though it proclaims UT2003 everywhere.

Unfortunately, I have not received any e-mail confirmation from the above link for any of the e-mail addresses that I tried with the site.  One will need to copy-and-paste the page output into the cdkey file.

**Comment by jrmain** [comment]
Confirmed. That link (https://www.epicgames.com/unrealtournament/forums/cdkey.php), unlike the others I've tried, actually works for me (I don't get a 404 error). However, I also never received any email.

The tool is labeled as a key generator for UT2003 servers, but once I added the generated key to my UT2004 server (./ut2k4server server-cd-key) and restarted it, the server started appearing in the in-game list of Internet servers.

Thanks for the assistance!

**Comment by dgibbs64** [comment]
I have just checked this now and the link is working again

**Comment by mindlesstux** [comment]
Looks like the links are not working again.

"Could not connect to database server." - when entering an email address.

**Comment by UltimateByte** [comment]
Confirmed. None of the links work. I don't know if there's anything to do about it.

**Comment by Grimston** [comment]
Untested but, taking the claim that you can use the key for as many servers as you want I found this key on the epic forums

`SRVER-9YPA9-FUPRA-8T3DQ`

Source: https://forums.epicgames.com/unreal-tournament-2003-2004/server-administration/122464-ut2004-server-key-generator?p=1840288#post1840288
