### ISSUE TITLE
Checking dependencies: missing: libsdl1.2debian

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#1428]
I've just installed ut99server on my Ubuntu 14.04 server, and although it seems to run okay, whenever I stop or start it, I see these messages:

	[ERROR ] Starting ut99-server: Checking dependencies: missing: libsdl1.2debian
	Warning! ut99server does not have sudo access. Manually install dependencies.
	sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install libsdl1.2debian

I checked whether the 'missing' package is in fact installed, and it does seem to be:
```
$ sudo dpkg -s libsdl1.2debian
Package: libsdl1.2debian
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 484
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: libsdl1.2
Version: 1.2.15-8ubuntu1.1
Replaces: libsdl1.2debian-all, libsdl1.2debian-alsa, libsdl1.2debian-esd, libsdl1.2debian-nas, libsdl1.2debian-oss, libsdl1.2debian-pulseaudio
Depends: libasound2 (>= 1.0.16), libc6 (>= 2.15), libcaca0 (>= 0.99.beta17-1), libpulse0 (>= 1:0.99.1), libx11-6 (>= 2:1.4.99.1), libxext6
Pre-Depends: multiarch-support
Conflicts: libsdl1.2, libsdl1.2-all, libsdl1.2-esd, libsdl1.2-nas, libsdl1.2-oss, libsdl1.2debian-all, libsdl1.2debian-alsa, libsdl1.2debian-esd, libsdl1.2debian-nas, libsdl1.2debian-oss, libsdl1.2debian-pulseaudio

```
If I try to install **libsdl1.2debian**, Linux tells me 'libsdl1.2debian is already the newest version.'

If I try the suggested command from the error message (`sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install libsdl1.2debian`), Linux tells me 'libsdl1.2debian is already the newest version.'

What functionality is provided by **libsdl1.2debian** that I may be missing? If it's actually working, does that mean there's a problem in how ut99server is detecting **libsdl1.2debian**?

Let me know if there's any more diagnostic information I can provide.

Update: I just installed ut2k4server, and although it seems to run fine, I get the same messages about **libsdl1.2debian** when I stop or start the server.

**Comment by Grimston** [comment]
Try this to enable support for 32 bit libraries.
```BASH
sudo dpkg --add-architecture i386
sudo apt-get update
````

Then force it to install the 32bit version
```BASH
sudo apt-get install libsdl1.2debian:i386
```

**Comment by jrmain** [comment]
That sounded promising, but when I try to install `libsdl1.2debian:i386`, I get this: `libsdl1.2debian:i386 is already the newest version.`

**Comment by jrmain** [comment]
I think I found the problem. The command in check_deps.sh that checks for the existence of libsdl1.2debian is `dpkg-query -W -f='${Status}' libsdl1.2debian`. When I run that command on my server, I get this: `install ok installedinstall ok installed`. The script is looking for `install ok installed` on a line by itself, which it's not seeing. I think I'm getting the response I am because both the 32-bit and 64-bit versions of libsdl1.2debian are installed. Anyway, I changed the script to look for `install ok installed` at the start of a line, and I no longer see the dependency warnings. libsdl1.2debian is a requirement for the UT99 and UT2K4 servers, and it is installed, it just wasn't being detected properly by the gameservers script.

**Comment by dgibbs64** [comment]
can you post your updated code and I will look at adding a fix for this thanks. Good investigation 👍

**Comment by jrmain** [comment]
check_deps.sh
Line 22
Change:
		`dpkg-query -W -f='${Status}' ${deptocheck} 2>/dev/null | grep -q -P '^install ok installed$'`
To:
		`dpkg-query -W -f='${Status}' ${deptocheck} 2>/dev/null | grep -q -P '^install ok installed'`

**Comment by dgibbs64** [comment]
@jrmain thanks. This is fixed now.

**Comment by jrmain** [comment]
Cool! When will the change appear? I mean, if I run update-lgsm now, will I get the fix?

**Comment by dgibbs64** [comment]
Next release :)

**Comment by jrmain** [comment]
Confirmed fixed in latest release. Thanks!
