### ISSUE TITLE
Half-Life Deathmatch server installation failing

### ISSUE THREAD

**Issue by execut4ble** [GameServerManagers/LinuxGSM#1431]
Been trying to install a Half-Life Deathmatch server on two machines recently, both of the times it has failed. Seems like SteamCMD does not download all the files anymore for some reason, stopping at like 6%. 

Used to work fine in the past.

**Comment by UltimateByte** [comment]
Reproduced.
Seems like it installs just fine, but for some reason, a validate occurs and just loops.
Output: https://hastebin.com/eveseqerey.sql

**Comment by UltimateByte** [comment]
Well noes, this is the expected behavior.

> Information! Goldsource servers commonly fail to download all the server files required. Validating a few of times may reduce the chance of this issue.

So... Just wait a bit and it should be fine.

End of install: https://hastebin.com/zopapebuqo.pas

**Comment by execut4ble** [comment]
I get pretty much the same output during the installation. It shows that everything has been installed, but it's actually missing a lot of the server files. If you try to start the server, the console will throw errors about missing files which were never downloaded.

I have attempted to launch and retry the installation multiple times but none of them have actually finished a proper installation. 

Might actually be a SteamCMD issue and not LGSM itself.

**Comment by execut4ble** [comment]
https://forums.alliedmods.net/showthread.php?t=303364

Possible solution?

**Comment by dgibbs64** [comment]
Relevent? https://github.com/dgibbs64/HLDS-appmanifest
