### ISSUE TITLE
Bug commands to start (Garry'sMod)

### ISSUE THREAD

**Issue by Arezox** [GameServerManagers/LinuxGSM#1432]
Hello, yesterday i get this error : 

/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
/home/gmodserver/lgsm/functions/core_getopt.sh: line 135: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 136: ((: cmdindex <= : syntax error: operand expected (error token is "<= ")
Unknown command: ./gmodserver start
Usage: ./gmodserver [option]

Garry's Mod - Linux Game Server Manager - Version 170501
https://gameservermanagers.com/gmodserver

Commands
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
/home/gmodserver/lgsm/functions/core_getopt.sh: line 155: awk: command not found
    | Start the server.
    | Stop the server.
    | Restart the server.
    | Check server status and restart if crashed.
    | Send a test alert.
    | Display server information.
    | Post details to hastebin (removing passwords).
    | Check and apply any updates.
    | Bypass update check and apply any updates.
    | Validate server files with SteamCMD.
    | Update LinuxGSM functions.
    | Create backup archives of the server.
    | Access server console.
    | Start server directly in your terminal.
    | Build a FastDL directory.
    | View and install available mods/addons.
    | View and remove an installed mod/addon.
    | Update installed mods/addons.
    | Install the server.
    | Install the server without prompts.
    | Enable developer Mode.

Can you help me please ? (I'm on a VPS linux debian 8)

**Comment by UltimateByte** [comment]
Don't install minimal distro when you're a noob.
Thanks.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
