### ISSUE TITLE
[hwserver] binutils missing dependency on Debian

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [GameServerManagers/LinuxGSM#1435]
After installation by instruction, point by point, received a warning on start about the missing dependency `binutils` on Debian 8.

p.s. Sorry for my English

```
Checking Dependencies
=================================
tmux
wget
ca-certificates
file
bsdmainutils
util-linux
python
bzip2
gzip
unzip
binutils
lib32gcc1
libstdc++6:i386
[ERROR ] Install hurtworld-server: Checking dependencies: missing: binutils

Warning! hwserver does not have sudo access. Manually install dependencies.
	sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install binutils
```

**Comment by Khelgar1** [comment]
`sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install binutils`

The error even tells you what to do

**Comment by Jonathan-Rosewood** [comment]
Yep, but it still is missing dependency in tutorial.

**Comment by Jonathan-Rosewood** [comment]
Also there is a problem with the work of the compiler in the oxide...
In the script there is a functional setting for this mod, but it will not work for all.

`apt-get install lib32z1`
This package required by CSharpCompilier in Hurtworld Oxide Mod.

**Comment by Drizzt321** [comment]
The website as well is missing this information, for me with ARK, https://gameservermanagers.com/lgsm/arkserver/, if you go down to Dependencies it doesn't list binutils under the Dependencies Debian tab.

**Comment by UltimateByte** [comment]
@dgibbs64 I added binutils & lib32z1 to Debian Glibc deps fileds on gameservermanagers.com, however it doesn't seem to show up, even though i cleared the cache.

**Comment by dgibbs64** [comment]
Addresses these issues on the website
