### ISSUE TITLE
Better handling of x64 binarys

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1436]
There are currently 5 servers that have x64 binary available 2 which require x64. I want to improve the handling of this as no doubt in the future x64 will be more common. Ideals auto-selecting the arch when possible giving an error message is the distro does not support x64 and a manual switch should x64 be under development.

* Hurtword currently manual select as x64 is experimental
* Multi Theft auto is x64 only
* Factorio is x64 only
* TS3 auto selects the correct arch
* Quake live auto selects arch
* Natural Selection 2 x64 only
* 7 Days to Die autoselect

**Comment by marvinlehmann** [comment]
If I'm not mistaken, Starbound is also x64 only since version 1.0.

**Comment by marvinlehmann** [comment]
Apparently 7 Days to Die also has both archs available (7DaysToDieServer.x86 | 7DaysToDieServer.x86_64).
#1532

**Comment by dgibbs64** [comment]
Natural Selection 2 is also now x64 ONLY. I need to do some work on this issue

**Comment by UltimateByte** [comment]
Also: #1896
