### ISSUE TITLE
ARK engramm points

### ISSUE THREAD

**Issue by sunnus01** [GameServerManagers/LinuxGSM#1440]
After last update cant learn any of engramms, is this game issue ?

**Comment by sunnus01** [comment]
Looks like issue is only on Linux Servers, All you have to do is add some random mod to server and launch server with this mod, it does not matter what mod.

**Comment by SkullMasher** [comment]
Hello. Issue got fixed on ARK side not an LGSM issue.

https://steamcommunity.com/app/346110/discussions/0/594820656447032287/

Thanks for posting i'll be careful when updating later today.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
