### ISSUE TITLE
Arma 3 Server after Update cant start anymore.

### ISSUE THREAD

**Issue by Joxiii** [GameServerManagers/LinuxGSM#1441]
I updated my Arma3 Server a hour ago for the new Jets Update.

Every time i want to start the Server it say : [  OK  ] Starting XXXXX
but everytime the Server Crash or cant start properly .

This Error comes in logs.
Host identity created.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.

I also installed a fresh server and it have the same error!

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

> Personal server issues on Github will be closed without a kiss.

**Comment by gouglhupf** [comment]
Actually I would take a closer look at it. It seems with the new Arma update a running Steam install is required. Only installing Steam does not help. The steampipe mite related to that. @UltimateByte

**Comment by Joxiii** [comment]
fixed it from copy the steamclient.so from the steamcmd folder. old was not working!

**Comment by Joxiii** [comment]
thank to a nice guy who add me on steam ! he told me that fix named @Marcin648

**Comment by Marcin648** [comment]
For others with a similar problem:
http://steamcommunity.com/groups/linuxgsm/discussions/0/2741975115083366267/
