### ISSUE TITLE
save command ? save on stop ?

### ISSUE THREAD

**Issue by netfab** [GameServerManagers/LinuxGSM#1443]
Hi,

I setted up a terraria local server thanks to LGSM.
I was surprised after restarting it that the world file was not saved when stopping the server.

When connecting to the terraria console, we can use two commands \:
> exit            Shutdown the server and save.
> save            Save the game world.

Before using LGSM, I wrote my own script (with screen instead of tmux) to manage this server.
I used the -X screen parameter to send the « exit » command to the terraria console to save and shutdown the server. Is there any way to do the same with LGSM ? How the server is stopped when running the stop command ?

For now the only way I found to workaround this is to manually connect to the terraria console and save the world before shutting down the server. Thanks.

**Comment by marvinlehmann** [comment]
It's currently only implemented in the dev branch. (8008501f5ad22c7172dd23c5c255212320e312a0)
It'll be available in the next release.

**Comment by netfab** [comment]
Excellent. I guess I can close this issue then. Thank you.
