### ISSUE TITLE
Server crash after start GMOD

### ISSUE THREAD

**Issue by tivson** [GameServerManagers/LinuxGSM#1445]
Hey, yesterday i bought vps server(first time) Debian 8 but everytime im launching server it crashed after 5 sec.
http://imgur.com/a/1eWCJ

**Comment by Grimston** [comment]
First off, that is not very helpful, you need to provide logs from the server and the result of: 
`./gmodserver pd`

Second, since I also provide the same VPS control panel for my clients... those details are messed up, 8TB Memory and a negative bandwidth allocation? I think something is very wrong with the VPS setup...

**Comment by tivson** [comment]
https://hastebin.com/uyerajabov

**Comment by tivson** [comment]
@Grimston https://hastebin.com/uyerajabov

**Comment by Grimston** [comment]
Start the server with

`./gmodserver debug`

I still think it's the VPS setup that's an issue....

**Comment by tivson** [comment]
@Grimston 
Continue? [Y/n] Y
[ INFO ] Debug gmod-server: Stopping any running servers
[ INFO ] Stopping gmod-server: LinuxGSM is already stopped
[  OK  ] Debug gmod-server: Starting debug
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
./srcds_run: 1: ./srcds_run: gdb: not found
WARNING: Please install gdb first.
        goto http://www.gnu.org/software/gdb/
Server will auto-restart if there is a crash.
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
WS: No +host_workshop_collection or it is invalid!
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
"host_workshop_collection" = ""
 game
Usage: sv_setsteamaccount <login_token>
Network: IP 188.116.46.165, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
/home/garrysmod/lgsm/functions/command_debug.sh: line 102:  6634 Terminated              ${executable} ${parms} -debug

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#bugsfeature-requests
