### ISSUE TITLE
UT2K4 server adds Escape characters to server config

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#1448]
The ut2k4server script is adding Escape characters to parts of the main server config (serverfiles/System/ut2k4-server.ini). For example:
`[DefaultDM MaplistRecord]`

I tried replacing all of those Escape characters with spaces, and when I restarted the server, they came back immediately.

Any idea why? Are they somehow intentional, in which case, wat?

**Comment by jrmain** [comment]
It's also adding weird characters to the server name (eg. JDRGamingÂ UT2004Â Coop), although I can't see those characters in the settings files. They do appear in some server lists, like Qtracker.

**Comment by MarkL4YG** [comment]
@jrmain check if setting UT2K4 to UTF-8 mode fixes your problem.

**Comment by jrmain** [comment]
@MarkL4YG Are you talking about the LinuxGSM fix_ut2k4.sh function? If not, how would I go about changing UT2K4 to UTF-8 mode?

**Comment by MarkL4YG** [comment]
@jrmain I guess you will have to google that. I did some quick searches and read about ppl switching to UTF locales fixing similar issues. [Take a look here for example](https://forums.tripwireinteractive.com/forum/killing-floor/technical-support-aa/dedicated-server-support-aa/32610-webadmin-fixes)

**Comment by jrmain** [comment]
@MarkL4YG That does seem to be a related issue. But the setting in question was already UTF-8 on my server. I'll try changing it to iso-8859-1.

This does seem to be an issue with the UT2004 server itself. I've also noticed a few other servers with the same problem. Clearly the web admin interface is adding the weird characters.

In the meantime, I changed the MOTD and ServerName settings with a text editor, and they seem fine.

I also wonder about the LinuxGSM fix_ut2k4.sh function, which alters that same setting: when does that script run?

**Comment by MarkL4YG** [comment]
@jrmain You could run a search through the script files to see when it's called.

**Comment by jrmain** [comment]
According to functions/fix.sh, that particular script only runs during installation. So if I switch back to iso-8859-1 I don't have to worry about it getting switched back automatically.

**Comment by MarkL4YG** [comment]
If that file fixes your problem you could also periodically run it.

**Comment by jrmain** [comment]
It doesn't. The setting was already UTF-8, and was probably set that way by the fix script when I installed the server. I'll switch back to iso-8859-1 as a test.

**Comment by jrmain** [comment]
I changed the setting in serverfiles/System/UWeb.int from 'utf-8' to 'iso-8859-1' and restarted the server. It didn't seem to have any effect at all. Regardless of the setting, the MOTD string gets messed up when I edit it in web admin (unicode characters are added). Weirdly, I'm no longer seeing any issues with ServerName.

**Comment by jrmain** [comment]
I recently reinstalled my UT2K4 server from scratch. The problem with garbage characters appearing in the server name and map lists in the game server configuration file happpened again.

I noticed that the file (serverfiles/System/ut2k4server.ini) was in Ansi mode. I converted it to UTF-8 and saved the file, and this seems to have fixed the problem.

I edited the server settings using the UT2K4 web UI, and the file was updated, but stayed UTF-8, and no garbage characters appeared.

I'm not sure how that config file is created during LinuxGSM server install, or if it's just a copy of one of the files in the official UT2K4 server distribution, but it does seem to start out as ANSI.

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/Game-Server-Configs/blob/master/UnrealTournament2004/UT2004.ini 

It copied from there so it might just need converting. I will look in to this as it wont take long.

**Comment by dgibbs64** [comment]
I have updated the .gitatributes file https://github.com/GameServerManagers/Game-Server-Configs/blob/master/.gitattributes hopfully it has fixed the issue. Please can you test for me.

**Comment by jrmain** [comment]
I installed a new UT2K4 server as a test, and after the install, the file (serverfiles/System/ut2k4server.ini) is UTF-8. Seems fixed.
