### ISSUE TITLE
Ports are closed?

### ISSUE THREAD

**Issue by Imadlekal** [GameServerManagers/LinuxGSM#1451]
Here is the thing, If I type
`./csserver details`

It will tell me that the server is online, however when I check the game, I have this:
![server not responding](http://i.imgur.com/V7KgzHg.png)

I also tried the monitor command I got these results:

![Monitor issue](http://i.imgur.com/8Do2iZ2.png)

I opened the ports using this command:

`iptables -A INPUT -p udp -m udp --sport 27000:27030 --dport 1025:65355 -j ACCEPT
iptables -A INPUT -p udp -m udp --sport 4380 --dport 1025:65355 -j ACCEPT`

I'm not sure but I believe It has something to do with the ports. I tried to run 

`nmap ip_address `

and the output was the following:
![Monitor issue](https://i.stack.imgur.com/Tj5dX.png)

so from the nmap command, I'am assuming the ports are not open, but why since I opened them?

**Comment by UltimateByte** [comment]
Rules
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
