### ISSUE TITLE
Problem with Rust: "Player data archive not found at /../data.unity3d`, using local filesystem"

### ISSUE THREAD

**Issue by Xohoo** [GameServerManagers/LinuxGSM#1452]
I installed rust on a esxi vm os: Ubuntu 17.04
https://hastebin.com/apubozofuf

Problem: Server does not start
I am happy for any help 

==> Logfile: https://pastebin.com/fg3ksUiX
==> Console Log
```
rust@rust-server:~$ ./rustserver debug
/home/rust/lgsm/functions/check_system_requirements.sh: Zeile 34: [: : Ganzzahliger Ausdruck erwartet.

Rust Debug
=================================

Distro: Ubuntu 17.04
Arch:   x86_64
Kernel: 4.10.0-19-generic
Hostname:       rust-server
tmux:   tmux 2.3
Avg Load:       0,54, 1,38, 1,30
Free Memory:
Free Disk:      Verf.
19G
GLIBC required: 2.15
Server IP:      192.168.178.85:28015

Start parameters:
./RustDedicated -batchmode +server.ip 192.168.178.85 +server.port 28015 +server.tickrate 30 +server.hostname "Rust" +server.identity "rust-server"  +server.maxplayers 50 +server.worldsize 3000 +server.saveinterval 300 +rcon.web 0 +rcon.ip 192.168.178.85 +rcon.port 28016 +rcon.password "******" -logfile "/home/rust/log/server/rust-server-game-2017-05-29-21:27:53.log"

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If rust-server is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug rust-server: Stopping any running servers
[ INFO ] Stopping rust-server: Rust is already stopped
[  OK  ] Debug rust-server: Starting debug
Set current directory to /home/rust/serverfiles
Found path: /home/rust/serverfiles/RustDedicated
Mono path[0] = '/home/rust/serverfiles/RustDedicated_Data/Managed'
Mono path[1] = '/home/rust/serverfiles/RustDedicated_Data/Mono'
Mono config path = '/home/rust/serverfiles/RustDedicated_Data/Mono/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
eac_server.so [x64] :: OnLoad()
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api64.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
        libRenderer.so
Player data archive not found at `/home/rust/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem
```

**Comment by UltimateByte** [comment]
Bugs/Feature Requests

You can submit any bug and feature suggestion or code to Github.
Personal server issues on Github will be closed without a kiss.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

BTW, start by using a stable OS.

**Comment by MarkL4YG** [comment]
@UltimateByte While I do also prefer to use stable systems and English as system language I do think that there're less offensive sounding ways to tell other ppl about that.

---
@Xohoo working from the top ``/home/rust/lgsm/functions/check_system_requirements.sh: Zeile 34: [: : Ganzzahliger Ausdruck erwartet.`` (Integer expected) points to [this line](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/check_system_requirements.sh#L34) where I guess ${physmemtotalmb} is null, unset, NaN or even a decimal.
If you could insert ``echo "${physmemtotalmb} is my physmem" just before the inner if-statement we're able to take a look at what value this variable evaluates to.

Additionally check if the data archive exists and if the server has r/w permissions on it.

**Comment by UltimateByte** [comment]
There might be a little bash error probably due to the language being used but that isn't his issue.
Even though i give a thumbs up for the postdetails and debug outputs, this is not an LGSM issue unless proven otherwise, therefore it has no place on this git.

As for being offensive, i guess answering this post made at the wrong place is nice already, and i'm pretty sure most people will see the friendly attitude from the "you foolish beta tester". I got no time to lose to pseudo-kindness, we're here to develop, not to fool around.

**Comment by Xohoo** [comment]
ok, understood thanks anyway
