### ISSUE TITLE
Terraria World Saves

### ISSUE THREAD

**Issue by wheeler9691** [GameServerManagers/LinuxGSM#1454]
Can someone please help me find my save files?  I know they are supposed to be located in ~/.local/share/Terraria/Worlds/ but they aren't.  At first my server would autocreate a new world each time it restarted.  Now it says "Loading World Data" in console so it's reading a .wsd file from somewhere, but I have no idea where.

The world= and worldpath= both reference ~/.local/share/Terraria/Worlds/ but there is nothing there.  There wasn't even a "Worlds" folder until I created one.  Could it be a permissions problem?

I've been at this for a few hours.
Thanks

**Comment by UltimateByte** [comment]
Github = development
Thanks.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by wheeler9691** [comment]
My apologies, I'm relatively new.

**Comment by MarkL4YG** [comment]
@wheeler9691 there're commands in linux that tell you which files are opened. You may use them to find out whats wrong.

**Comment by wheeler9691** [comment]
Thanks for the suggestion.  I used lsof -p pid and none of the files are world files so I'm not sure what to do.

**Comment by wheeler9691** [comment]
We got it.  Just in case you guys are curious.  The actual file path is...

/home/terraria/serverfiles/~/.local/share/Terraria/Worlds/

So cd ~/.local/share/Terraria/Worlds/ is the wrong place.
cd ~/serverfiles/~/.local/share/Terraria/Worlds/ is where they are.

I didn't know there was a relative path.  My mistake.

**Comment by UltimateByte** [comment]
Thanks for googlers for sharing the answer.

**Comment by wheeler9691** [comment]
Google had nothing to do with it.  I figured this out on my own.

**Comment by cedarlug** [comment]
@wheeler9691 - he meant those that would search for the answer on Google will find the answer here.

**Comment by wheeler9691** [comment]
I see, my mistake.  I was frustrated and had some preconceived notions when I read that.
