### ISSUE TITLE
Server Gmod hacked ...

### ISSUE THREAD

**Issue by JaunBios4** [GameServerManagers/LinuxGSM#1455]
Here the loading screen ... http://image.noelshack.com/fichiers/2017/22/1496480798-screen.png

But the url its the same in gmod-server.cfg, and when i put the URL on my navigator, its work

I don't understand what happened, no leaks, i have CAC anti cheat, i change all my passwords (and RCON).

It's the second time, for the first time, we reinstalled all the server, and then, again, the same problem, the loading screen is redirected, i try to see my console, (client-server), dans nothing !

In game, the players can't connect, because there are disconnected for a mistake reason. 

I check the logs, but always nothing!
I have many servers on the same virtual server, (by OVH), and just this only one is down!
How i can resolve this problem ?

**Comment by MarkL4YG** [comment]
I guess your server lacks proper security. Oh and also: The GitHub-Issues are meant for reporting bugs, unexpected behavior and similar stuff directly connected to the project. Not any personal support for properly configuring (game)servers. If you guess gmod to be at fault, ask in their forums.

**Comment by cedarlug** [comment]
Git hub is for LinuxGSM development.
