### ISSUE TITLE
ARK - Automanagedmods

### ISSUE THREAD

**Issue by JRNetwork** [GameServerManagers/LinuxGSM#1456]
While I have seen some very old tickets about this I don't think anything was done on this?

Is it completely not possible that we can get LGSM to update our ARK workshop mods on server boot? and if not why not? I'm just interested because I have 5 ARK servers on a linux , ubuntu 14.04 server and it can be a pain in the back side to update the modifications when there is so many updates to ARK all the time. 

With the fact that most game servers run linux its a myth to me that something hasn't been done to sort the issue.

Looking forward to seeing if this is possible once and for all as I love using LGSM, I run all my servers using LGSM currently.

Thanks guys!
Jamie

**Comment by Twonkk** [comment]
i don't think its an LGSM issue, i think its an Ark/linux issue... i ran into the same issue with running ark VIA steamcmd and doing automanagemods... i just went back to my windows script to update mods and just SFTP them when updates are needed.. its a slight hassle but eh it is what it is.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/1336
