### ISSUE TITLE
cs 1.6 bad installs

### ISSUE THREAD

**Issue by Twonkk** [GameServerManagers/LinuxGSM#1457]
as with issue #1450, getting the same with 1.6.. debug log as follows

`cs@ubuntu:~/cs$ ./csserver d

Counter-Strike 1.6 Debug
=================================

Distro: Ubuntu 16.04.2 LTS
Arch:   x86_64
Kernel: 4.4.0-78-generic
Hostname:       ubuntu
tmux:   tmux 2.1
Avg Load:       0.00, 0.00, 0.00
Free Memory:    6.3G
Free Disk:      45G
GLIBC required: 2.3.4
Server IP:      192.168.1.12:27015
Server password:        NOT SET

Start parameters:
./hlds_run -game cstrike -strictportbind +ip 192.168.1.12 -port 27015 +clientport 27005 +map de_dust2 -maxplayers 16 -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If cs-server is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug cs-server: Stopping any running servers
[ INFO ] Stopping cs-server: LinuxGSM is already stopped
[  OK  ] Debug cs-server: Starting debug
Enabling debug mode
Auto-restarting the server on crash

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad
email debug.log to linux@valvesoftware.com
Sat Jun  3 11:58:27 CDT 2017: Server restart in 10 seconds`

have tried it on 3 different OS's (Ubuntu 16, Debian 8, CentOS 7

**Comment by UltimateByte** [comment]
Thanks. Let's group with #1450 then.
