### ISSUE TITLE
[Server Request] Wurm Unlimited

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#1460]
requesting a wurm unlimited LGSM server. I am willing to create this, I just need some guidance.

**Comment by UltimateByte** [comment]
Guidance is on the wiki if you want to go through this on your own.
Though it should be noted that LinuxGSM team is currently focused on reworking the main code.

https://github.com/GameServerManagers/LinuxGSM/wiki/Developing-LGSM
https://github.com/GameServerManagers/LinuxGSM/wiki/Development-Workflow
https://github.com/GameServerManagers/LinuxGSM/wiki/Syntax-%26-Conventions
https://github.com/GameServerManagers/LinuxGSM/wiki/LGSM-Exit-Codes
https://github.com/GameServerManagers/LinuxGSM/wiki/Branching
https://github.com/GameServerManagers/LinuxGSM/wiki/Developer-Commands

Ultimately, any proper server request should come with server documentation, unless you're 100% sure you can handle everything yourself.

Found this
http://www.wurmpedia.com/index.php/Server_administration_(Wurm_Unlimited)

**Comment by dgibbs64** [comment]
User on Discord requested this server today

**Comment by interstate420productions** [comment]
Best tutorial I have found to date. I got my server up and running ONE time with this tutorial.  I can't get it to go again... :(  Frustrating.

**Comment by dgibbs64** [comment]
I could really do with a poll to find out which servers people want the most

**Comment by interstate420productions** [comment]
easy enough plenty of free ones on the web that are supposedly easy to embed in a site

**Comment by interstate420productions** [comment]
I found this for you perhaps this will be of some use... it's supposed to be a completely automated script.. But it's not working for me.   https://github.com/jonsjava/wurm_unlimited_server
