### ISSUE TITLE
|CSGO] -nobreakpad as default?

### ISSUE THREAD

**Issue by spot88** [GameServerManagers/LinuxGSM#1462]
Distro:    Ubuntu 14.04.5 LTS
Arch:      x86_64
Kernel:    3.19.0-58-generic

**postdetails:** 
https://hastebin.com/ibafoxodif.sql

**Console Error:**
https://hastebin.com/sixobehoku.lua

**Ufw status:**
https://hastebin.com/akecokosin

**Comment by spot88** [comment]
**Solution:**
add: -nobreakpad in the startup parms in the csgoserver script. 

Might be a good ide to check why this happends, and if it's needed add -nobreakpad as default when server is installed.

**Comment by UltimateByte** [comment]
Yeah, i'm wondering the same. There seem to be many people out there with that issue.

**Comment by dgibbs64** [comment]
Since the hastebin has now gone please can you give details of the error and why we need to add  -nobreakpad. Thank you

**Comment by UltimateByte** [comment]
To sum up, some people can't start csgo server if there isn't -nobreakpad start parameter.

**Comment by dgibbs64** [comment]
I have added the option now
