### ISSUE TITLE
Factorio - check for latest autosave upon restart

### ISSUE THREAD

**Issue by Maygus** [GameServerManagers/LinuxGSM#1464]
My server had a recent hiccup and upon restart was loading a blank map as if no builds had happened.

For whatever reason the server.zip map file was not being updated, can you add a check (flag toggle?) that it will check for most recent autosave and if newer than server.zip file replace it upon restart?

**Comment by camwheeler** [comment]
Had this same issue. As a workaround until this gets implemented I have the following line for my savefile variabe:
`savefile="$(ls -t ${filesdir}/saves/ | head -n1)"`

**Comment by Digital-Storm** [comment]
This sounds like a bug with the factorio, not LGSM.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
