### ISSUE TITLE
MTA - Unable to find updated builds

### ISSUE THREAD

**Issue by braunsonm** [GameServerManagers/LinuxGSM#1466]
Server seems to be unable to find new updates recently.
http://i.imgur.com/BbudDDB.png

Not sure what has changed. Let me know if I can help, I don't have the time right now to go full out.

**Comment by UltimateByte** [comment]
Isn't it that they switched to https ?
https://linux.mtasa.com/

**Comment by ChaosMTA** [comment]
Should automatically redirect though
