### ISSUE TITLE
Where can i find/edit the LinuxGSM Ark Commandline?

### ISSUE THREAD

**Issue by JohnJohnJohnJohnJohnJohn** [GameServerManagers/LinuxGSM#1468]
It seems to be partially overridden by the GameUserSettings.ini (As far as the server name goes, the player count remains weirdly unchanged even though i edited it to lower the player amount.) 

Also, i'd like to know where/how i can add mods (Game.ini or GameUserSettings.ini?). 

Thanks!

**Comment by marvinlehmann** [comment]
ARK is very weird when it comes to the server config and parameters.
You can set the parameters in the "arkserver" file you downloaded.

For mods you have to add `ActiveMods=<mod_workshop_id>,...` to GameUserSettings.ini.
You can find many tutorials on the internet.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by JohnJohnJohnJohnJohnJohn** [comment]
@marvinlehmann Thanks for your help bro! By the way, do you have discord or any other means of communication? I'd love to ask some questions.

**Comment by marvinlehmann** [comment]
https://gameservermanagers.com/discord
