### ISSUE TITLE
SteamCMD now available in repos

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1469]
I have seen that you can now install steamcmd from apt for ubuntu and debian. 

It would be a good idea to migrate to using steamcmd in a repo rather than manual install.

As of 16.10 for Ubuntu
https://packages.ubuntu.com/yakkety/steamcmd

and debian testing and unstable
https://packages.debian.org/search?keywords=steamcmd&searchon=names&suite=all&section=all

**Comment by UltimateByte** [comment]
Nice, would be awesome :)

**Comment by UltimateByte** [comment]
We also gotta check if steamcmd package is installed or not.
https://github.com/GameServerManagers/LinuxGSM/issues/1510

**Comment by MarkL4YG** [comment]
It may be possible to use the package repositories if available. APT for example supports that using ``apt-cache search --names-only '^steamcmd*'``

**Comment by UltimateByte** [comment]
We got kind of an api for package detection already.

**Comment by dgibbs64** [comment]
Ubuntu and Debian fully support this. However, CentOS and Fedora do not have an rpm package. OpenSuse does have an rpm. Ideally, if we can get a SteamCMD rpm into rpm fusion that would be awesome. If there is a developer who wants to build and get an rpm package distributed that would be great
