### ISSUE TITLE
Can LGSM be used on an existing server?

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1472]
For example, we have an existing CS:GO server and want to use LGSM, is there a way to install it on there?

**Comment by popey456963** [comment]
Wow, impressive it's so simple.

Thank-you so much for putting so much work into these scripts, they have saved me so many countless hours of work.

**Comment by UltimateByte** [comment]
I shall use this issue to add info about upgrading LGSM to the latest version.

**Comment by UltimateByte** [comment]
This is now done:
https://github.com/GameServerManagers/LinuxGSM/wiki/Server-Migration
