### ISSUE TITLE
Managing all installed game servers as root

### ISSUE THREAD

**Issue by p0thi** [GameServerManagers/LinuxGSM#1473]
I want to make a simple web interface to start/stop/update all servers.
Is there a good way to manage all installed game servers as root? Something like running commands with su or su -

Thank you!

**Comment by MarkL4YG** [comment]
You could write a script to run all other scripts for that. You wouldn't need to run that as root though. Using sudo it would suffice to have the privileges correctly set up.

**Comment by p0thi** [comment]
Wouldn't running this script as root throw an error, because the server scripts can't be run as root?

**Comment by UltimateByte** [comment]
Don't ever run game servers as root if you care about your system and its security.

**Comment by p0thi** [comment]
@UltimateByte i dont want to run the scripts as root. I just want to manage all servers as root. That was my question: Is there a way to "tell" the server owner users to execute server commands. Or something similar.

**Comment by UltimateByte** [comment]
I would look into suPHP & suEXEC stuff, though i don't know of anybody who's done it, so you'll have to figure it out.

**Comment by p0thi** [comment]
Thank you. I will have a look at it.
