### ISSUE TITLE
Factorio Matching server connection

### ISSUE THREAD

**Issue by Nebri** [GameServerManagers/LinuxGSM#1475]
Hey everyone,

trying to solve this in my Factorio server setup: 

   1.252 Error ServerMultiplayerManager.cpp:592: Matching server connection failed: Error when creating server game: Missing token.

full log below. Anybody able to help diagnosis? my game is not showing up in the public games list.

`0.000 2017-06-18 12:44:41; Factorio 0.14.23 (build 25374, linux64, headless)
   0.048 Operating system: Linux (Ubuntu 16.04)
   0.048 Program arguments: "./factorio" "--start-server" "/home/factorio/serverfiles/save1.zip" "--server-settings" "/home/factorio/serverfiles/data/fctr-server.json" "--port" "34197" "--rcon-port" "34198" "--rcon-password" "CHANGE_ME"
   0.048 Read data path: /home/factorio/serverfiles/data
   0.048 Write data path: /home/factorio/serverfiles
   0.048 Binaries path: /home/factorio/serverfiles/bin
   0.056 System info: [CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz, 1 core, RAM: 983MB]
   0.056 Running in headless mode
   0.058 Loading mod core 0.0.0 (data.lua)
   0.061 Loading mod base 0.14.23 (data.lua)
   0.124 Checksum for core: 1291735968
   0.125 Checksum for mod base: 786624017
   0.435 Info PlayerData.cpp:55: Local player-data.json available, timestamp 1497804199
   0.435 Info PlayerData.cpp:62: Cloud player-data.json unavailable
   0.441 Custom inputs active: 0
   0.441 Factorio initialised
   0.442 Info ServerSynchronizer.cpp:27: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   0.442 Info ServerMultiplayerManager.cpp:658: mapTick(-1) changing state from(Ready) to(PreparedToHostGame)
   0.442 Info ServerMultiplayerManager.cpp:658: mapTick(-1) changing state from(PreparedToHostGame) to(CreatingGame)
   0.447 Loading map /home/factorio/serverfiles/save1.zip
   0.447 Error FileUtil.cpp:284: Can't remove /home/factorio/serverfiles/temp/currently-playing: No such file or directory
   0.471 Info Scenario.cpp:152: Map version 0.14.23-0
   0.559 Checksum for script /home/factorio/serverfiles/temp/currently-playing/control.lua: 1057114497
   0.559 Info UDPSocket.cpp:27: Opening socket at (0.0.0.0:34197)
   0.560 Hosting game at 0.0.0.0:34197
   0.560 Info HttpSharedState.cpp:44: Downloading https://auth.factorio.com/generate-server-padlock
   1.037 Info HttpSharedState.cpp:111: Status code: 200
   1.037 Info AuthServerConnector.cpp:106: Obtained serverPadlock for serverHash (vQgGBsSwGuNBufiqLK3ByAD7bSEDoi7i) from the auth server.
   1.037 Info ServerMultiplayerManager.cpp:658: mapTick(1230) changing state from(CreatingGame) to(InGame)
   1.037 Info ServerRouter.cpp:604: Asking pingpong servers (pingpong1.factorio.com:34197, pingpong2.factorio.com:34197) for own address
   1.080 Info UDPSocket.cpp:39: Opening socket for broadcast
   1.101 Info RemoteCommandProcessor.cpp:97: Starting RCON interface at port 34198
   1.235 Info ServerRouter.cpp:497: Own address is 207.210.1.145:34197
   1.252 Error ServerMultiplayerManager.cpp:592: Matching server connection failed: Error when creating server game: Missing token.
`

**Comment by MarkL4YG** [comment]
1. The message tells you exactly what your problem is
2. Please format logs || Better use hastebin/pastebin
3. ``/home/factorio/serverfiles/data/fctr-server.json`` look through there search for a property where it would be appropriate to enter the token
4. If you haven't: Remember to set your RCON-Password
5. The issues aren't intended for server support - They're there for bug reports such as crashes and hangs during installation where LGSM actually does something.

**Comment by MarkL4YG** [comment]
From Factorio forums:

>How to List Your Server-Hosted Game on the Matching Server
>In order to publish the game to the matching server, Factorio needs to be given some more information than just the save file location. These information are provided in a server settings file.
>
>To create a server settings file, look at the example file located in data/server-settings.example.json in the Factorio Application Directory. The recommended way is to make a copy of this example file and edit the copy.
>
>The following values can be changed:
>
>Name: This will be the name under which the server will be listed in the server browser
>Description: A brief description of your server
>Tags: A list of game tags
>Max Players: Allows you to limit the number of players that can be connected to the server at the same time. If you want no limit, just set max_players to 0.
>Visibility for server browser: May be either public, lan or hidden.
>Public: The server will appear in the public server list. This requires the login credentials below to be filled in.
>LAN: The server will not appear in the public server list, but will be available through the Play On LAN button
Hidden: Clients will have to connect using the server's IP address
User credentials using a username and password or authentication token: These are necessary if you wish to make the server public. Otherwise, they can be left empty.
For security reasons it is recommended to use authentication token as this document is stored as plaintext. Though it should be noted that an authentication token is a sensitive piece of information as well, and you are well-advised to keep it secret.
Server Password
Field name is game_password
Whether to verify user identity

**Comment by UltimateByte** [comment]
Missing token says it all.
You need to register your game server.
