### ISSUE TITLE
Travis needs to be adapted to the latest LGSM

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1479]
Title says it all. Didn't dig into it yet.
Any volunteer is welcome.

**Comment by marvinlehmann** [comment]
https://github.com/GameServerManagers/LinuxGSM/tree/feature/marvin-travis

I need confirmation if it's OK. Sadly it's based on the master branch because I wanted to ensure successful builds with @UltimateByte's hotfixes. Please don't punch me.

**Comment by UltimateByte** [comment]
Cool you could do that. Your fixes should be pushed to master & dev when you're done :)

**Comment by dgibbs64** [comment]
Merged. Thank you !!!!!
