### ISSUE TITLE
Bug install steamcmd

### ISSUE THREAD

**Issue by Minikeysi** [GameServerManagers/LinuxGSM#1480]
Logs script : 
juin 19 21:06:02 ark-server: INSTALL: INFO: Logs installed
juin 19 21:06:02 ark-server: INSTALL: PASS: Downloading check_deps.sh: OK
juin 19 21:06:09 ark-server: INSTALL: PASS: Downloading install_steamcmd.sh: OK
juin 19 21:06:10 ark-server: INSTALL: PASS: Downloading check_steamcmd.sh: OK
juin 19 21:06:10 ark-server: INSTALL: PASS: Downloading install_server_files.sh: OK
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 2
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 3
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 4
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 5
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 6
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 7
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 8
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 9
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, retrying: Attempt 10
juin 19 21:06:11 ark-server: INSTALL: SteamCMD did not complete the download, too many retrys

Console : 

arkever2@ns3006395:~$ ./arkserver2 install
    fetching core_dl.sh...OK
    fetching core_functions.sh...OK
    fetching core_legacy.sh...OK
    fetching core_messages.sh...OK
    fetching core_trap.sh...OK
    fetching core_getopt.sh...OK
    fetching command_install.sh...OK
    fetching check.sh...OK
    fetching check_root.sh...OK
    fetching check_tmuxception.sh...OK
    fetching check_permissions.sh...OK
    fetching check_glibc.sh...OK
    fetching info_glibc.sh...OK
    fetching info_distro.sh...OK
    fetching check_system_requirements.sh...OK
    fetching install_header.sh...OK
=================================
ARK: Survival Evolved
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================
    fetching install_server_dir.sh...OK

Server Directory
=================================
/home/arkever2

Continue? [Y/n] Y
mkdir: création du répertoire « /home/arkever2/serverfiles »
    fetching install_logs.sh...OK

Creating log directories
=================================
installing log dir: /home/arkever2/log...OK
installing LinuxGSM log dir: /home/arkever2/log/script...OK
creating LinuxGSM log: /home/arkever2/log/script/ark-server-script.log...OK
installing console log dir: /home/arkever2/log/console...OK
creating console log: /home/arkever2/log/console/ark-server-console.log...OK
installing game log dir: /home/arkever2/serverfiles/ShooterGame/Saved/Logs...OK
creating symlink to game log dir: /home/arkever2/log/server -> /home/arkever2/serverfiles/ShooterGame/Saved/Logs...OK
    fetching check_deps.sh...OK

Checking Dependencies
=================================
tmux
wget
ca-certificates
file
bsdmainutils
util-linux
python
bzip2
gzip
unzip
binutils
lib32gcc1
libstdc++6:i386
    fetching install_steamcmd.sh...OK

Installing SteamCMD
=================================
    fetching check_steamcmd.sh...OK
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: erreur de syntaxe près du symbole inattendu « else »
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: `            else'
    fetching install_server_files.sh...OK

Installing ARK: Survival Evolved Server
=================================
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 84: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 2
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 84: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 3
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 84: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 4
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 84: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 5
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 6
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Removing
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: erreur de syntaxe près du symbole inattendu « else »
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: `            else'
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: erreur de syntaxe près du symbole inattendu « else »
/home/arkever2/lgsm/functions/check_steamcmd.sh: ligne 23: `            else'
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 97: ./steamcmd.sh: Aucun fichier ou dossier de ce type
/home/arkever2/lgsm/functions/install_server_files.sh: ligne 51 : cd: /home/arkever2/steamcmd: Aucun fichier ou dossier de ce type
Failure! SteamCMD did not complete the download, too many retrys

**Comment by b3none** [comment]
Also getting this issue

**Comment by MarkL4YG** [comment]
Please provide the logs using pastebin/hastebin and English as system language. That makes reading them way easier for everyone.

**Comment by Kavex** [comment]
same error when it gets to install steamCMD using sbsserver https://pastebin.com/EK4ELf2V

**Comment by NichoTheMan** [comment]
Same issue with rustserver on ubuntu 16.04
https://pastebin.com/UbPhdFJM

**Comment by b3none** [comment]
The issue is with the installation of Steam CMD.

**Comment by fightmaxime** [comment]
Same error with me.. 
Debian 8

**Comment by Lines08** [comment]
Same here, Debian 8.

**Comment by pat-git** [comment]
There are a few typos in lgsm/functions/check_steamcmd.sh . If you do not want to wait for them to fix just replace the complete content of "check_steamcmd.sh" with https://pastebin.com/fNF5sBxT .

**Comment by UltimateByte** [comment]
I'm on it, stop crying.

**Comment by UltimateByte** [comment]
Fixed, go update your script.

Thanks for notifying.
If this is the only issue considering the huge update that just occurred, we can be glad. :)
