### ISSUE TITLE
Factorio dont install correctly

### ISSUE THREAD

**Issue by skynett81** [GameServerManagers/LinuxGSM#1481]
Factorio wont install correctly 

Installing Factorio Server
=================================
[ FAIL ] Update fctrserver: Checking for update: factorio.com: Not returning version infofctrserver@factorio:~$ ./fctrserver u
[ERROR ] Update fctrserver: Checking for update: factorio.com: Current build version not found
[ INFO ] Update fctrserver: Checking for update: factorio.com: Forcing server restart
[ WARN ] Stopping fctrserver: Configuration file missing!
/home/fctrserver/serverfiles/data/fctrserver.json

Downloading Factorio Config
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
copying server-settings.json config file.
'/home/fctrserver/lgsm/config-default/config-game/server-settings.json' -> '/home/fctrserver/serverfiles/data/fctrserver.json'
cp: cannot create regular file '/home/fctrserver/serverfiles/data/fctrserver.json': No such file or directory
Config file not found, cannot alter it.
/home/fctrserver/lgsm/functions/check_ip.sh: line 44: syntax error near unexpected token `else'
/home/fctrserver/lgsm/functions/check_ip.sh: line 44: `                 else'
[ INFO ] Stopping fctrserver: Factorio Server is already stopped
[ FAIL ] Starting fctrserver: Executable was not found:
 * /home/fctrserver/serverfiles/bin/x64/factorio
[ WARN ] Starting fctrserver: Configuration file missing!
/home/fctrserver/serverfiles/data/fctrserver.json

Downloading Factorio Config
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
copying server-settings.json config file.
'/home/fctrserver/lgsm/config-default/config-game/server-settings.json' -> '/home/fctrserver/serverfiles/data/fctrserver.json'
cp: cannot create regular file '/home/fctrserver/serverfiles/data/fctrserver.json': No such file or directory
copying server-settings.json config file.
'/home/fctrserver/lgsm/config-default/config-game/server-settings.json' -> '/home/fctrserver/serverfiles/data/fctrserver.json'
cp: cannot create regular file '/home/fctrserver/serverfiles/data/fctrserver.json': No such file or directory
Config file not found, cannot alter it.
/home/fctrserver/lgsm/functions/check_ip.sh: line 44: syntax error near unexpected token `else'
/home/fctrserver/lgsm/functions/check_ip.sh: line 44: `                 else'
/home/fctrserver/lgsm/functions/command_start.sh: line 100: cd: /home/fctrserver/serverfiles/bin/x64: No such file or directory
failed to connect to server: Connection refused
[ FAIL ] Starting fctrserver: Unable to start Factorio Server
fctrserver@factorio:~$ ./fctrserver st
[ FAIL ] Starting fctrserver: Executable was not found:
 * /home/fctrserver/serverfiles/bin/x64/factorio

**Comment by skynett81** [comment]
Jun 19 15:07:14 fctrserver: START: FATAL: Unable to start Factorio Server
Jun 19 15:07:15 fctrserver: START: FATAL: command_start.sh exiting with code: 1
Jun 19 15:08:16 fctrserver: CHECK: WARN: Executable was not found: /home/fctrserver/serverfiles/bin/x64/factorio
Jun 19 15:08:17 fctrserver: CHECK: FATAL: check_executable.sh exiting with code: 1

**Comment by UltimateByte** [comment]
Fixed the IP stuff.
Now need to fix the update check. Seems like the branch var won't work.
I'm on it.

**Comment by UltimateByte** [comment]
Fixed there
https://github.com/GameServerManagers/LinuxGSM/commit/dddbf34c1eb69682edf08d7f526130a930f4ee56#diff-0e4db1f253f100771f84e52d6a35e295

Sorry @dgibbs64 i edited master instead of pull-requesting


Please, try to repeat the install process, this is now fixed.
Thanks for reporting.
