### ISSUE TITLE
Troubles with install TS3 server

### ISSUE THREAD

**Issue by grenman11** [GameServerManagers/LinuxGSM#1482]
Hello mates, i have weird issue. Hope u guys can help me.

There is screen with problem, when i try install ts3 server.
![default](https://user-images.githubusercontent.com/29556037/27306359-ff561766-554d-11e7-99b8-007eb73d2eb2.JPG)

I played with user permissions but thats not help :c

**Comment by UltimateByte** [comment]
I'm on it. 
Thanks for your report.

**Comment by UltimateByte** [comment]
This is now fixed. Please try again.

**Comment by grenman11** [comment]
Ty all working.
