### ISSUE TITLE
Minecraft change startup command?

### ISSUE THREAD

**Issue by ScouseTS** [GameServerManagers/LinuxGSM#1488]
Hi,

I have an MC server running on a 6GB VPS, I've noticed that the config makes it launch with 1GB RAM. I recall in past altering the figure by editing the mcserver file however I cannot find any params in there to edit the initial start command and adjust the amount of RAM assigned?

Thanks!

**Comment by MarkL4YG** [comment]
Did you check your lgsm-config folder?

**Comment by UltimateByte** [comment]
Yep, go check your lgsm/lgsm-config dir.
Sorry, there is no doc about that yet but it'll come soon.

**Comment by dgibbs64** [comment]
@UltimateByte

**Comment by UltimateByte** [comment]
Issue is between the chair and the desk here. LinuxGSM RAM values work perfectly for minecraft.
User just needs to edit the right file:  https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config

**Comment by b3none** [comment]
Updated URL of the above:
