### ISSUE TITLE
Ubuntu 14.04.5 Log file created but empty log

### ISSUE THREAD

**Issue by unusual917** [GameServerManagers/LinuxGSM#1491]
I think it may be due to a setup I"m overlooking, but I moved from Debian 8 to Ubuntu 14.04.5 and seems to be working but I get this issue where log files are empty.

The log file itself is being created but has no logs being written. When I do ./tf2server console it shows logs on the putty terminal though.

Permissions are all 755 under the user tf2server (since the script is installed in that user's folder).

Any idea why?

Oh btw, it is for the logs in the log/console folder with the log file names being like tf2-server-console-23-06-2017-04-42-58.log

Sourcemod logs seem to be working.

**Comment by UltimateByte** [comment]
Rules please.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
But eyeballed, i'd say you installed your server during LGSM update, and should update your functions, or reinstall lgsm while keeping your game server files.
