### ISSUE TITLE
[A3] Feature Request

### ISSUE THREAD

**Issue by infroz** [GameServerManagers/LinuxGSM#1495]
I noticed there was no mod downloader or any system that gets mods for you with Game Server Manager, so I was wondering if we could get a script that can load mods from workshop folder. As in, I have downloaded mods via the workshop, would be cool if we could have a script that lists those mods. Currently I have to move the mods from the workshop folder into my server folder and rename them, since steam gives them numbered names instead of @ace or @tfr or whatever the folders are normaly called

**Comment by MarkL4YG** [comment]
You can find your Arma mods in the Arma installation folder under "!Workshop" (hidden folder) inside that folder you can find named junctions from which you can extract the files.

**Comment by MarkL4YG** [comment]
Workshop missions can be found inside your ``AppData > Local > Arma 3 > MPMissionsCache`` folder.
