### ISSUE TITLE
[arma3server] Update not working

### ISSUE THREAD

**Issue by xopez** [GameServerManagers/LinuxGSM#1496]
Just installed a new Arma 3 Server over the script.
Updateonstart and ./arma3server update is broken.
```
arma@mightful-noobs:~$ ./arma3server start
[  OK  ] Update arma3server: Checking for update: Server logs: No update request[ .... ] Update arma3server: Checking for update: SteamCMD
```
So the server can only be started if updateonstart is disabled. And if there will be a patch in future, i can't update my server.

**Comment by MarkL4YG** [comment]
I didn't test that yet but be aware that for the Malden update there's currently no update for Linux/MacOS.
