### ISSUE TITLE
CS:GO Sourcemod admin file

### ISSUE THREAD

**Issue by ScouseTS** [GameServerManagers/LinuxGSM#1497]
Hi,

I've manually installed Sourcemod in past and always had to setup an admin_simple.ini file where I input my Steam ID and admin level.

I installed it on my CS:GO server with LGSM and couldn't find any documentation of where to add the stuff for admins? I tried manually creating the admin_simple.ini file and putting in the necessary details then refreshing the sm admins via console but it says not an admin when I try to access the admin menu via the game.

Could someone point me in the direction of where to add admins when installing the mod via LGSM? Keep up the great work guys, loving your work :)

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#support-links

> Bugs/Feature Requests
> 
> You can submit any bug and feature suggestion or code to Github.
> Personal server issues on Github will be closed without a kiss.
> 
> https://gameservermanagers.com/issues
