### ISSUE TITLE
README file has broken link to LinuxGSM website

### ISSUE THREAD

**Issue by carlbennett** [GameServerManagers/LinuxGSM#1500]
https://github.com/GameServerManagers/LinuxGSM/blame/22215b7db8fa17d62e9ec7530ccc3b904dd9f0c3/README.md#L3

`linuxgsm.com` doesn't have a web server because it lacks an A or AAAA record, therefore web browsers clicking on the image in the README are taken to an error page.

```
[cbennett@anvil ~]$ host -tANY linuxgsm.com
linuxgsm.com has SOA record dns108.ovh.net. tech.ovh.net. 2017060301 86400 3600 3600000 300
linuxgsm.com name server ns108.ovh.net.
linuxgsm.com name server dns108.ovh.net.
linuxgsm.com descriptive text "v=spf1 include:mx.ovh.com ~all"
[cbennett@anvil ~]$
```

**Comment by UltimateByte** [comment]
LinuxGSM uses CloudFlare.
https://pastebin.com/gH6smXfB
Links are not broken and DNS are OK. 
But thanks for your concern.

**Comment by cedarlug** [comment]
The OP is correct - "linuxgsm.com" (the new domain) does not have DNS records populated yet at OVH, and there are references to it in the README.md

**Comment by UltimateByte** [comment]
My bad :p 
We can correct that at some point :)
