### ISSUE TITLE
backup backuping itself

### ISSUE THREAD

**Issue by Gamewalker** [GameServerManagers/LinuxGSM#1501]
7Days2Die backup script is backing up itself. I dont really understood why yet. I have a cronjob:
```
0 * * * * su - sdtdserver -c '/home/sdtdserver/sdtdserver backup' > /dev/null 2>&1 
```
and if there is any backup in my 
```
/home/sdtdserver/lgsm/backup
```
dir, the backup script is endless zipping my /home/sdtdserver/lgsm/backup dir until my HDD is full.

**Comment by UltimateByte** [comment]
Huh, thanks for letting us know.
This is due to the latest update.

**Comment by Drizzt321** [comment]
Yup, I noticed this, fixed it in my PR https://github.com/GameServerManagers/LinuxGSM/pull/1508

**Comment by dgibbs64** [comment]
merged. Thank you
