### ISSUE TITLE
Arma3 server problem

### ISSUE THREAD

**Issue by kacru77121** [GameServerManagers/LinuxGSM#1502]
i can't play on my server beacuse mssions not loading by this error
`Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
a3_characters_f`
full log is here https://pastebin.com/FPgdxKEF
i try to find fix in google but i can't find anything i reinstall server and it not work
thanks if you help me

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
