### ISSUE TITLE
kfserver installation documentation points to the wrong folder

### ISSUE THREAD

**Issue by obstriegel** [GameServerManagers/LinuxGSM#1503]
In the documentation at https://gameservermanagers.com/lgsm/kfserver/#gettingstarted it says one has to edit the file lgsm/**lgsm-config**/kfserver/common.cfg and enter the steam login credentials there.

However the script looks for the config in lgsm/**config-lgsm**/kfserver

**Comment by UltimateByte** [comment]
Thanks for notifying.

**Comment by dgibbs64** [comment]
ouphs my bad. I cannot edit this currently @UltimateByte please can amend the template if you get a chance

**Comment by dgibbs64** [comment]
Done. Thank you
