### ISSUE TITLE
Binutils missing for Hurtworld and Rust

### ISSUE THREAD

**Issue by Ventrex** [GameServerManagers/LinuxGSM#1504]
I made a Rust and Hurtworld server.
When installing they both give the same error that he couldn't find binutils when you follow the tutorial:
To solve this you can do: sudo apt-get install binutils

[ADMIN EDIT]
I am running a Hurtworld and Rust server. In both cases I installed oxide.
But .cs (Csharp/C#) files don't compile correctly because it is missing lib32z1
Is it possible to add this to the installation?

You can get them working by the following step: apt-get install lib32z1

Installed it on Ubuntu 16
[/ADMIN EDIT]

Is it possible to add this in the tutorial?

Installed it on Ubuntu 16

**Comment by UltimateByte** [comment]
We should add this as a requirement then.

**Comment by dgibbs64** [comment]
zlib-devel/lib32z1 is now a requirement for Hurtworld and Rust
