### ISSUE TITLE
Oxide doesn't compile .cs for Hurtworld and Rust 

### ISSUE THREAD

**Issue by Ventrex** [GameServerManagers/LinuxGSM#1505]
I am running a Hurtworld and Rust server. In both cases I installed oxide.
But .cs (Csharp/C#) files don't compile correctly because it is missing lib32z1
Is it possible to add this to the installation? 

You can get them working by the following step: apt-get install lib32z1 

Installed it on Ubuntu 16

**Comment by UltimateByte** [comment]
Let's add this to your other issue.
