### ISSUE TITLE
Arma 3 server problem

### ISSUE THREAD

**Issue by kacru77121** [GameServerManagers/LinuxGSM#1506]
Game server: Arma3
System debian 8 - Linux ns364570.ip-91-121-209.eu 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 GNU/Linux
ldd (Debian GLIBC 2.19-18+deb8u9) 2.19
tmux 1.9
and log here https://pastebin.com/FPgdxKEF
`Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted. a3_characters_f`

**Comment by MarkL4YG** [comment]
The answer you get from @UltimateByte will be the same as this is not LGSM related but Arma 3 specific.  
This message is normal on Arma 3 Servers and does NOT prevent you from loading missions.  
In fact this message appears before any attempt to load a mission is made.  
Make sure you do select a mission logged in as admin or by voting according to your vote setup,

**Comment by UltimateByte** [comment]
> Personal server issues on Github will be closed without a kiss.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
