### ISSUE TITLE
Asking help with arma 3 server restart messages.

### ISSUE THREAD

**Issue by grenman11** [GameServerManagers/LinuxGSM#1507]
As almost all a3 server owners on linux. I visited this page [https://github.com/deannreid/BattlEye-RCON-Control-PHP/](url) So i have troubles with download php5 php5-cgi spawn-fcgi on my Centos 7 server. 

I even added new repository "epel" and it find only "spawn-fcgi". Ive try "php70-cgi and so on, but its didnt help. Does somebody know where i can download all of this?

Also there is line "service apache2 restart" is that mean i should set up apache before PHP or it will download as dependencies?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
