### ISSUE TITLE
config-default and config-lgsm

### ISSUE THREAD

**Issue by storrgie** [GameServerManagers/LinuxGSM#1509]
Why do I have both `lgsm/config-default` as well as `lgsm/config-lgsm`. They look like they are the same and there isn't any symlinking between. Which config is used when I start the server?

**Comment by storrgie** [comment]
```
[rust@newman lgsm]$ tree
.
├── config-default
│   ├── config-game
│   │   └── server.cfg
│   └── config-lgsm
│       └── rustserver
│           └── _default.cfg
├── config-lgsm
│   └── rustserver
│       ├── common.cfg
│       ├── _default.cfg
│       └── rustserver.cfg
```

I'm confused about the apparent duplication here. I get the whole `_default.cfg`, `common.cfg`, `instance.cfg`.

It looks like maybe I'm supposed to work off the `config-lgsm` folder because thats where it appears there is all three of the above...?

**Comment by UltimateByte** [comment]
This might help
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files

**Comment by storrgie** [comment]
What is not clear is the multi-instance concept. Do I have to have another root folder for another instance? or do I simply have another instance.cfg file?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers

**Comment by storrgie** [comment]
I guess one other rust specific inquiry, the config-game/server.cfg for rust... do we use the `config-game/server.cfg` inside the `config-lgsm` for it to automagically link where it needs to go? Or should we still just symlink that into the install base?

**Comment by dgibbs64** [comment]
@storrgie there is no `server.cfg` in `config-lgsm` only in `config-default`. The way `server.cfg` is managed has not changed from previous versions. I can understand the slight confusion about `config-default` and `config-lgsm`. I will have to think of a way to make it easier to understand maybe leaving some readme files in directories to allow better understanding. Thanks for the feedback

**Comment by storrgie** [comment]
As I'm only using LGSM right now for rust I don't know if this is a generalizable thing across installs, but the existence of the `server.cfg` in the `config-default` does imply that it _may_ be used. This is semantics, but I suspect it might help to rename `config-default` to `config-reference`, as really its just a reference for people to crib off. I would as well name `config-lgsm` to something like `config-firstinstance`.

All in all the change is certainly for the better, but the nomenclature and existing documentation are not discrete enough to save folks from confusion I think. Most people are not gonna read through the scripts to ascertain the naming convention, they are going to just go complain in the steam community forum :(.
