### ISSUE TITLE
Steamcmd package already exists in some source.

### ISSUE THREAD

**Issue by ProjectSky** [GameServerManagers/LinuxGSM#1510]
* I use ubuntu server's 16.04, I find i can use sudo apt-get steamcmd install steamcmd, But LinuxGSM doesn't seem to recognize the installed steamcmd, but instead downloads its own version.

* apt search steamcmd
```
Sorting... Done
Full Text Search... Done
steamcmd/xenial,now 0~20130205-1 i386 [installed]
Command-line interface for Valve's Steam
```
[packages ubuntu](https://packages.ubuntu.com/search?keywords=steamcmd)
* I think it should add a check function to check if the user has installed the steamcmd package.

**Comment by UltimateByte** [comment]
Thanks for sharing. Adding this info to the existing issue about that.
