### ISSUE TITLE
Please add error-handling when enough space aren't available

### ISSUE THREAD

**Issue by exetico** [GameServerManagers/LinuxGSM#1511]
I tried to follow your guide at:
https://gameservermanagers.com/lgsm/rustserver/

But everytime i got an error. I did try to install Rust in multiple other ways. Two hours later i saw an post where a person mentioned that space was his problem (With multiple GB's free).

I know that SteamCMD could improve something here too, but maybe it was an idea to check it the required space was available, or at least inform the user about limited space on the drive, before trying to install it :-)

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/704
