### ISSUE TITLE
Error Licence Teamspeak

### ISSUE THREAD

**Issue by Hoopee45** [GameServerManagers/LinuxGSM#1512]
Hello,

I allows me to post here because I have well to install my waiter TS3 he walks well but I would like to install my license there annual and when I stop the waiter and puts it the document he does not want reboot how can it be done? Thank you.

![error](https://user-images.githubusercontent.com/29820983/27764264-748bfd3e-5e95-11e7-89da-8b780b9ba291.PNG)

**Comment by MarkL4YG** [comment]
The output exactly states the problem: Your license key is not owned by the user your server is started with - Thus cannot be read.
