### ISSUE TITLE
LINUXGSM IS BROKEN AS HELL RUNNING centos7 CS:GO

### ISSUE THREAD

**Issue by dj-hyb** [GameServerManagers/LinuxGSM#1513]
ok so ive edited all the multiple configs 50 fuckinng different ways upload reloaded restarted.

ill open up details where the port is said to be edited in its file itself open that up oh no configs are nont edited here anymore.
no matter what i do it always starts as linuxgsm. 
start the server and get error hostname can only be changed as root.

start the server as root. oh no you cant run this shit as root.

edit tyhe corisponndinng csgoserver csgoserver-1 ect in both config-lgsm annd in the server files all of with

DOES BUT FUCK ALL.

im fuckinng frustrated, pissed of and really want to king hit someone.
no matter what config i edit remove linuxgsm from the hostname spot and even put the number 1.

start server with either csgoserver csagoserver-2 it always comes up with the same fucking settings. even if i do details and it says its linked to those specific config files " which are edited " it always start the server as the originnal default settings.

FIX YOUR SOFTWARE

**Comment by dj-hyb** [comment]
LOL yep dident think anyone would be bothered to help.. piss poor

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files

+ learn politeness
