### ISSUE TITLE
Unable to preload the following plugins: libRenderer.so

### ISSUE THREAD

**Issue by BrandsPickled** [GameServerManagers/LinuxGSM#1515]
I have a clean version of a Rust server and im getting this issue with the libRenderer.so, I have updated and validated 

https://hastebin.com/asobiwisub

https://hastebin.com/erolihevid.sql

**Comment by UltimateByte** [comment]
Sorry, non script issue isn't for github, unless you find a global issue that we can solve, but since i didn't experience this on my install, this doesn't seem to be a global issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
