### ISSUE TITLE
New Game - Avorion

### ISSUE THREAD

**Issue by Maygus** [GameServerManagers/LinuxGSM#1516]
Possible to have Avorion added to the list of supported games?

http://store.steampowered.com/app/445220/Avorion/

There is a linux game server for it...

http://avorion.gamepedia.com/Setting_up_a_server#Starting_the_server_.28Linux.29

**Comment by UltimateByte** [comment]
Thanks for sharing the tutorial, this will probably help.
We already got an issue for this actually, so i'm closing this one
https://github.com/GameServerManagers/LinuxGSM/issues/1271
