### ISSUE TITLE
Cod2server maxplayer change

### ISSUE THREAD

**Issue by dikkatdeli** [GameServerManagers/LinuxGSM#1518]
LinuxGSM/lgsm/config-default/config-lgsm/cod2server/_default.cfg

`

1
--
## Server Start Settings | https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters
  | ip="0.0.0.0"
  | port="28960"
  | defaultmap="mp_leningrad"
  | maxplayers="20"
  |  
  | ## Server Start Command | https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters#additional-parameters
  | fn_parms(){
  | parms="+set sv_punkbuster 0 +set fs_basepath ${serverfiles} +set dedicated 1 +set net_ip ${ip} +set net_port ${port} +set sv_maxclients ${maxclients} +exec ${servercfg} +map ${defaultmap}"
  | }

`

should be 

+set sv_maxclients ${maxclients}  => +set sv_maxclients ${maxplayers}

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files
