### ISSUE TITLE
[Rust] Server will start then stop when I do ./rustserver start

### ISSUE THREAD

**Issue by RussianRonin** [GameServerManagers/LinuxGSM#1522]
So, I recently clean installed a rust server using LGSM. I can run the server but only in debug mode. If I try to run it with start, it will start, then stop after a bit. Logs and details are pasted. I also looked for other issues but they were all resolved.

Details: https://hastebin.com/ezaroqodiz

Log file: https://hastebin.com/imohiteyeg.coffeescript

Please let me know if you need any other details.

**Comment by RussianRonin** [comment]
This is with Oxide installed. Shouldn't have said clean install. Testing a clean install now.

**Comment by RussianRonin** [comment]
This is also confirmed with a completely new clean installed rust server using the LGSM script.

Here is the log: https://hastebin.com/ikahahedeg.coffeescript

**Comment by BenDrysdale** [comment]
I had the same problem, seems there has been an issue raised for this previously ([1171](https://github.com/GameServerManagers/LinuxGSM/issues/1171#issuecomment-258606441)). 

Follow instructions here and that should hopefully resolve the issue:
https://github.com/GameServerManagers/LinuxGSM/issues/1171#issuecomment-258606441

**Comment by RussianRonin** [comment]
Where I am confused is the fact that that is a closed issue. Closed meaning it is fixed. I am using a clean install after that issue was fixed. Maybe it never actually got fixed somehow. Not too sure.

**Comment by BenDrysdale** [comment]
I think you are right. I had a look at the closed issue and it does indicate that a pull request was made to fix the problem so I checked the master and I don't see the fix. Give it a try, hopefully, it will fix your problem like it did mine.

**Comment by RussianRonin** [comment]
That seemed to do the trick.
I see a commit was made for it here: https://github.com/GameServerManagers/LinuxGSM/commit/9bf74b80c266c92110029a1aa6333acec1580299

but not sure how it isn't in the current build.

**Comment by RussianRonin** [comment]
Also, now the debug command doesn't work. I threw the fix into my common.cfg and now I get
`/home/*****/rustserver/lgsm/functions/command_debug.sh: line 101: LD_LIBRARY_PATH=:./serverfiles/RustDedicated_Data/Plugins/x86_64: No such file or directory
`
on debug.

**Comment by MrGraversen** [comment]
I experience the same issue currently.

Running `./rustserver start` results in starting, then stopping.

Running `.rustserver debug` works fine.

**Comment by riemers** [comment]
Had the same, adding the 

```
executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/serverfiles/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"
```
To my lgsm/config-lgsm/rustserver/common.cfg

Fixed the start issue.

**Comment by RussianRonin** [comment]
This seems resolved.
