### ISSUE TITLE
AutoUpdate/AutoRestart csgoserver

### ISSUE THREAD

**Issue by RodyaUshakov** [GameServerManagers/LinuxGSM#1523]
Hello
I have a problem
@reboot /home/username/csgoserver start
59 4 * * * /home/username/csgoserver restart
*/3 * * * *  /home/username/csgoserver monitor > /dev/null 2>&1
*/30 * * * *  /home/username/csgoserver update > /dev/null 2>&1
He makes a restart,just like that,anytime
help pls

Translated through the translator;3

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/On-Boot
https://github.com/GameServerManagers/LinuxGSM/wiki/Monitor
https://github.com/GameServerManagers/LinuxGSM/wiki/Update
