### ISSUE TITLE
[BUG] Notifications via PushBullet post twice in one message.

### ISSUE THREAD

**Issue by Shigbeard** [GameServerManagers/LinuxGSM#1524]
When the script attempts to post a notification to PushBullet, for instance in the event that the server crashes, it will post it's message twice in one line. See the below image.

![http://img.ndlee.com/shigbeard/onhigj5.png](http://img.ndlee.com/shigbeard/onhigj5.png)

This issue is caused in alert_pushbullet.sh, by having fn_rawurlencode() not only echo the resulting string, but also return it. I was able to eliminate the issue by editing the file and removing Line 27 (`REPLY="${encoded}"`) and editing lines 30 and 31 to read...

```bash
pbalertbody=${fn_rawurlencode "${alertbody}")
pbalertsubject=$(fn_rawurlencode "${alertsubject}")
```

This may not be the correct way of fixing it however, and someone may have a better solution.

**Comment by Shigbeard** [comment]
Pull Request merged, issue resolved. Closing issue.

**Comment by dgibbs64** [comment]
Will be on the next release
