### ISSUE TITLE
[csserver]The server is not fully downloaded

### ISSUE THREAD

**Issue by guangchan** [GameServerManagers/LinuxGSM#1526]
=================================
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '90' already up to date.
Information! Goldsource servers commonly fail to download all the server files required. Validating a few of times may reduce the chance of this issue.
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 6.32 (4194304 / 66393331)
Success! App '90' fully installed.
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 6.32 (4194304 / 66393331)
Success! App '90' fully installed.
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 6.32 (4194304 / 66393331)
 Update state (0x5) validating, progress: 97.36 (64638383 / 66393331)
Success! App '90' fully installed.
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 6.32 (4194304 / 66393331)
Success! App '90' fully installed.
Redirecting stderr to '/home/1/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 6.32 (4194304 / 66393331)
Success! App '90' fully installed.

**Comment by UltimateByte** [comment]
We know, legacy goldsource servers have issue downloading.
https://github.com/GameServerManagers/LinuxGSM/issues/1450
