### ISSUE TITLE
7 Days to Die Alpha 16 Update

### ISSUE THREAD

**Issue by LichLord91** [GameServerManagers/LinuxGSM#1527]
New update has come out for 7DTD . I updated my server and by running ./sdtdserver uf and ./sdtdserver f however I can no longer connect my server , even if I start a new world. I get a "Could not retrieve server information error when i try to connect." My client is also updated to the latest release. 

https://7daystodie.com/forums/showthread.php?67717-Alpha-16-is-out!

**Comment by jensenrob91** [comment]
I added a new user on my server , Ubuntu 16.04 minimal, and ran the procedure here https://gameservermanagers.com/lgsm/sdtdserver/. Seems to be working if its a fresh install. One thing i noticed is that the  /home/user/serverfiles/sdtdserver.xml was not updated on the old user but was on the new.  Not sure what else could not have updated in the serverfiles but that is one of them.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#required-information-for-support

**Comment by dgibbs64** [comment]
Not sure if anything for me to action. Closing
