### ISSUE TITLE
 Resetting the total number of slots and the name of the map after changing the map.

### ISSUE THREAD

**Issue by somsom37** [GameServerManagers/LinuxGSM#1528]
Resetting the total number of slots and the name of the map after changing the map.
Flies the number of slots and the name of the map, through the server browser in the server search in the game / Steam. That is, I run a certain map with a count of 0/32 slots, after changing the map, the total number of slots is 1 and the name of the map is empty. That is, it will look something like this in the search:
Game map = "" slots 0/1> 1/1> 2/1 etc. Screenshot http://prntscr.com/fvb1ht
You can go to such a server, but you can not see how many free slots there are and what map.
Such a glitch is seen on the sourses games - Counter strike Source and Day of defeat source.
At first I thought an error on the sourcemod with metamod or plugins.
Installed from scratch anew the server, through a simple script: an example of a startup script:
#! / Bin / bash
#
Cd serverfiles
./srcds_run -console -game dod + map map + ip 0.0.0.0 + hostport port + clientport port + maxplayers 32 + exec myservercfg.cfg
So there is no problem, the server files are the same.

**Comment by UltimateByte** [comment]
What's the question/request? Maybe I'm not properly awake or something, but I don't get it.
Also, https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by dgibbs64** [comment]
Nope makes no sense.

**Comment by somsom37** [comment]
It's just not clear how it could be ..and now https://pastebin.com/ZZ01zPRt. In Sourcemod+MetaMod :Source V1.10.7-devV, sourcemod V1.7.3-dev+5332 . And so ..
