### ISSUE TITLE
Running 2 servers under 1 user

### ISSUE THREAD

**Issue by KillerAntMC** [GameServerManagers/LinuxGSM#1529]
Hello, my issue is running 2 servers under 1 user. So for example, at the moment im trying to create 2 minecraft servers under the same user which will both be in separate directories under the home users directory. When ever I try to start the second server though, it says that it is already running, although the first server is the only one that's running in its own directory. They are both under the same IP but have different ports. Each files are contained in their own directory named server1 and server2. Although the ports for both servers are different from 25565, it still shows as 25565 when doing ./mcserver dt for both servers in both directories although one isn't running. Here's an example:

I have a server named server1 running on port 25567. I start it up and it all works fine. Then I try to start up server 2 in a different folder under the same user, and it says the server is already running. When I do ./mcserver c, it takes me to the console of server 1. When I do ./mcserver dt, it shows the information for server2, but it says its online.

If there is a way to fix this problem, that would be amazing! Thanks.

**Comment by MarkL4YG** [comment]
You need to name the scripts differently [Wiki/Multiple-Servers](https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers)

**Comment by KillerAntMC** [comment]
Works now, thanks!
