### ISSUE TITLE
[RUST] Querying Port x.x.x.x:28015 FAIL- Please Advise, Desperate for Assistance. Paying $20 to whomever can fix.

### ISSUE THREAD

**Issue by EvanWells** [GameServerManagers/LinuxGSM#1530]
Hello,
I have spent 4 hours googling this, to no avail. Perhaps I have even made the issue worse. I am in desperate need to get this fixed. 
Yesterday I started an LGSM-Rustserver, with no issues. Many of my friends, and myself were playing and having a good time. 
It was suggested that I install Oxide, so I did per a guide I read online. I installed it via the mods-install command. But after that, I was unable to log into the server. When I ran ./rustserver monitor, I got the following error Querying Port x.x.x.x:28015 FAIL. This repeats indefinitely. 

I then erased LGSM, The mods, Everything. And Started from scratch. This time, no oxide. Essentially a repeat of yesterday's server. But now, I can't even run a Vanilla Server. Same error. `Querying Port x.x.x.x:28015 FAIL`

This must be a problem with my Linux Right? Or perhaps LGSM? I will be babysitting this Issue on Github, so please tell me exactly what Logs/Reports you need and I will immediately provide them. 

I have ran' Netstat -lb' with the server up, and 28015 does not show up as in use anywhere. I have also tried running the server on countless different Ports, same issue.

Thanks for any information, I would be eternally grateful for any support.
I will pay $20 to whomever can fix it first, it's probably a simple linux issue. Linux is not my specialty, to say the least.
Evan

**Comment by EvanWells** [comment]
Update:
I reintalled Vanilla a few times, on the 3rd try, it worked. But just as Vanilla.  As SOON as I ran mods-install, I couldn't connect or anything

**Comment by UltimateByte** [comment]
Make sure you don't have a residual process running.
Otherwise, doesn't seem like an LGSM specific issue, so i'd rather use other support links provided here
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Also, make sure you read carefully this page in order to provide relevant info to your helpers.
