### ISSUE TITLE
7 Days to Die - Linux 32-bit vs. 64-bit server startup

### ISSUE THREAD

**Issue by drphlux** [GameServerManagers/LinuxGSM#1532]
Hello. Great server tool. One question after the LinuxGSM config was changed.

The command-line Parameter becomes :
./7DaysToDieServer.x86 -logfile /home/sdtdserver/log/server/output_log__2017-07-16__09-02-00.txt -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml

How do I correctly tell the manager to start ./7DaysToDieServer.x86_64 instead? 

ref: 
```
[sdtdserver@mynuc ~]$ uname -m
x86_64
```

**Comment by drphlux** [comment]
Figured it out. Added this:
```
[sdtdserver@mynuc ~]$ grep executable lgsm/config-lgsm/sdtdserver/common.cfg
executable="./7DaysToDieServer.x86_64"
```

**Comment by Khelgar1** [comment]
Interesting, I never even realised that it had a 64bit  exe it wasn't using. Any issues switching to it? If not the script should run it by default on 64 bit systems.

**Comment by drphlux** [comment]
@Khelgar1 
This is the way it was done before:

```
[sdtdserver@mynuc ~]$ tail -6 serverfiles/startserver.sh
if [ "$(uname -m)" = "x86_64" ]; then
        ./7DaysToDieServer.x86_64 -logfile 7DaysToDieServer_Data/output_log__`date +%Y-%m-%d__%H-%M-%S`.txt -quit -batchmode -nographics -dedicated $PARAMS
else
       ./7DaysToDieServer.x86 -logfile 7DaysToDieServer_Data/output_log__`date +%Y-%m-%d__%H-%M-%S`.txt -quit -batchmode -nographics -dedicated $PARAMS
fi

```
