### ISSUE TITLE
Resetting the total number of slots and the name of the map after changing the map.

### ISSUE THREAD

**Issue by somsom37** [GameServerManagers/LinuxGSM#1533]
When you run your script resets the number of slots when viewing the server through the serverbrowser and instead of the name of the card and void the number of available slots becomes "1" . And this changes will take effect after a map change for some reason :)) Before the update or your script everything worked perfectly on the same configuration of VPS, and now this crap . Http://prntscr.com/fweky0 Here is a screenshot from HLSW . Start the server with about the same file in parallel , so there is no error . Example of my script start the server :
```
#! / Bin / bash
Cd serverfiles
./srcds_run -console -game dod + map map + ip 0.0.0.0 + hostport port + clientport port + maxplayers 32 + exec myservercfg.cfg
```
The same error was seen on the server with the game counter strike Source (CSS).
server files + configuration files are the same.Except of course the ports to avoid conflict servers .This bug was of course , when you run 1 game server. Just do not understand how this can be ..

**In find servers , no name map maps and the number of server slots turns to "1" .**
But because of written in the command line, TV-port , can this be ?

here is the logs https://hastebin.com/exehijahor. And Sourcemod+MetaMod :Source V1.10.7-devV, sourcemod V1.7.3-dev+5332, just in case . 
The server is now working , visual example. 2 server is normally running on port ххх73 .. server Files same .. Ports are open . ..
p.s. Sorry for bad English ..

**Comment by somsom37** [comment]
Here's another server with a similar problem 176.196.46.69:27017 LinuxGSM in total slot is "1" ! .its see

**Comment by UltimateByte** [comment]
Mh... Pretty neat, never seen that before.
Could be related to CentOS 6 or tmux 1.6 or old glibc or the fact that you didn't set an IP.

**Comment by somsom37** [comment]
Just very strange , before worked well and everything was OK .. And this error on different versions and games CSS, DoDs , now here saw that and CSGO also have ..about the IP I'll try to register , but not the fact .. I personally Have suspicions on TV-port is the fact that it is written in the command line ..

> tmux 1.6 or old 

> glibc
OK I'll try to update if possible on this version of Centos
p.s. Sorry for bad English ..

**Comment by UltimateByte** [comment]
The fact that it happens after a map change makes me believe it's not directly related to LGSM. Also, your issue seem to be isolated.

**Comment by somsom37** [comment]
Tmux updated to 2.3, but with Glibc while looking for documentation as well as that ... The error remained server is working .. here is the postdetails https://hastebin.com/fewocefesu

**Comment by somsom37** [comment]
Updates configs LGSM , and new https://hastebin.com/yinasuvuva ..

> В glibc requires: 2.3.6
I saw this In glibc requires: 2.3.6. So, Centos 6 , can't install your script ?

**Comment by UltimateByte** [comment]
I see you're using port 27073, but got other ports set to default. Don't you have multiple servers on the same client port ?

**Comment by somsom37** [comment]
`Every single port must be different.`
About ports , I know .. All that "+1" , those that are installed on the LGSM , except for the game port . About GLIBC , I it not need to be updated glibc ? 

Here is my line starting , not at LGSM 
```
./srcds_run -console -game dod +map 3xi4_trainmap_s4e +ip 0.0.0.0 +hostport 27073  +clientport 27007 +maxplayers 16 +exec dodsserver.cfg &>> log.txt &
```
But in LGSM 
> ip="185.58.206.233"
> port="27071"
> clientport="27005"
> sourcetvport="27020"
> defaultmap="3xi4_trainmap_s4e"
> maxplayers="16"
As if all ports are spelled different ..

**Comment by Grimston** [comment]
I would suggest looking through each config file for the server (Not LGSM's) you may have a setting somewhere that is being loaded after the first map, and it's setting maxplayers again, which will take effect on map change.

**Comment by somsom37** [comment]
Yes I use the same = the same starting configuration , as with the LGSM and without it .. in this case dodsserver.cfg . And the same error was on almost pure CSS server , just installed it sourcemod +metamod. And the same error I saw from a friend , As was the address of the server , the game CSGO . It's a strange error .

**Comment by somsom37** [comment]
It is solved, as it repaired itself ..
In the plug-ins there were versions for Windows and Linux = universal, for Windows it was packed into the archive. Also deleted some extra commands for the TV-sourse.
After that, the script began to work ..

**Comment by UltimateByte** [comment]
Thanks for sharing your resolution.
