### ISSUE TITLE
7 Days to Die - Backup doesn't contain map- and playerdata

### ISSUE THREAD

**Issue by Eekiig** [GameServerManagers/LinuxGSM#1535]
OS: Ubuntu x64

If you try to recover a backup, then you'll start with a new map and userprofile,
because these informations are located at
`~/.local/share/7DaysToDie/Saves`
The problem is, that the .local dir isn't present in any backup i've done.
As a workaround i have created a symbolic link from ~/.local/share/7DaysToDie to ~/serverfiles/local.
My backups now contain all informations and i'm able to recover the whole server, including
map - and userprofiles.

**ISSUE:**
 Map and userfiles are missing in backups (~/.local doesn't get backed up)

**WORKAROUND:**
Create symbolic link from ~/.local/share/7DaysToDie to ~/serverfiles/local
`mkdir ~/serverfiles/local && ln -s ~/.local/share/7DaysToDie ~/serverfiles/local`

**POSSILBE FIX:**
Backup-script has to backup hidden folder
`~/.local/share/7DaysToDie/`

Greetings Eekiig

**Comment by dgibbs64** [comment]
Brilliant issue report thank you. We will need to look in to a fix for this one.

**Comment by UltimateByte** [comment]
As a reminder, this dir isn't backuped because it starts by a dot, which makes it a "hidden" directory. 
Not sure what the best way would be to solve this since we don't want to save all hidden dirs and files.

**Comment by drphlux** [comment]
Remember to change your default save game path, like this: 

$ grep Saves serverfiles/sdtdserver.xml 
  <property name="SaveGameFolder"      value="/home/sdtdserver/Saves" />
