### ISSUE TITLE
"fetching serverlist.csv...FAIL"

### ISSUE THREAD

**Issue by cherokee93** [GameServerManagers/LinuxGSM#1536]
```
csgoserver@ossola-gg:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh
--2017-07-17 19:02:17--  https://gameservermanagers.com/dl/linuxgsm.sh
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.93.238, 104.31.92.238
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh [following]
--2017-07-17 19:02:18--  https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11448 (11K) [text/plain]
Saving to: ‘linuxgsm.sh’

linuxgsm.sh         100%[=====================>]  11.18K  --.-KB/s   in 0.002s

Last-modified header missing -- time-stamps turned off.
2017-07-17 19:02:18 (6.97 MB/s) - ‘linuxgsm.sh’ saved [11448/11448]

    fetching serverlist.csv...FAIL
```
Hello,
It's my fault or it's something broken in the script?
This is not the first time I use this awesome tool, and this has never happened to me before.

EDIT: SOLVED, copy pasted the text from https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh and paste into the file with nano and now it works o.o

**Comment by UltimateByte** [comment]
Never seen this issue.
Please provide at least postdetails output so that we might understand.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#required-information-for-support

Also, please provide the output from this:
`wget --version | grep "GNU Wget"`

**Comment by cherokee93** [comment]
I think it had some problem on my side, since even  downloading the script returned 404 sometimes.
Sorry for not outputting the result but I didn't have the ./csgoserver file.

> wget --version | grep "GNU Wget"
> GNU Wget 1.16 built on linux-gnu.

By the way it's solved, so no problem.

**Comment by UltimateByte** [comment]
Same wget as me. I assume it's a Debian based distro?
I would have like to know why this happened. You can still provide postdetails output to provide your distro info. :)

**Comment by cedarlug** [comment]
Pretty sure it would be due to curl not being installed.

**Comment by xreeckz** [comment]
I'm also having this issue. 

When I try to run it, I get this: 

> steam@baldurn:~/LinuxGSM$ ./linuxgsm.sh
>   fetching serverlist.csv...FAIL


uname -a
> Linux baldurn 4.4.49-1-pve #1 SMP PVE 4.4.49-86 (Thu, 30 Mar 2017 08:39:20 +0200) x86_64 x86_64 x86_64 GNU/Linux

cat /etc/*-release
> Ubuntu 16.04.2 LTS (Xenial Xerus)

ldd --version
> ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.

**Comment by r0ber70** [comment]
In my case, it was due to curl not being installed. Thank you for the heads up.

**Comment by Fengzi2333** [comment]
same issue but surely curl correctly installed.

**Comment by dgibbs64** [comment]
@Fengzi2333 If you are having an issue please see https://linuxgsm.com/support
