### ISSUE TITLE
[DST] Don`t create .cfg for 2nd instance

### ISSUE THREAD

**Issue by bugavka** [GameServerManagers/LinuxGSM#1537]
run ./linuxgsm.sh dstserver
create dstserver and lgsm/config-lgsm/dst-server-Master.cfg
run once more ./linuxgsm.sh dstserver
create dstserver-2 and all same lgsm/config-lgsm/dst-server-Master.cfg etc. But not 2nd server.

**Comment by UltimateByte** [comment]
If you want a different serverfiles, then use a different user and a different install. 
The purpose of this is to run multiple instances of the same install with different config files, when applicable.

**Comment by bugavka** [comment]
in cs:go create 2 server in one user. and in how to install write https://github.com/GameServerManagers/LinuxGSM/wiki/Don%27t-Starve-Together, dont any users

**Comment by bugavka** [comment]
dstserver2 (this will be the slave shard with a cave as level):

# Installation Variables
sharding="true"
master="false"
shard="Caves" 
cluster="Cluster_1"
cave="true"

where is this file?

**Comment by UltimateByte** [comment]
I'm sorry but I don't understand google translate.
