### ISSUE TITLE
[DST] Master+Caves

### ISSUE THREAD

**Issue by bugavka** [GameServerManagers/LinuxGSM#1538]
i want 1 serverfiles 2 instance. when i do 2 service dstserver and dstserver-2, they both apply setting from /lgsm/config-lgsm/dstserver/dst-server-Master.cfg.
i can make setting by hand, but on start, for example:
dstserver, if in dst-server-Master.cfg shard="Master", run shard Master - ok
dstserver-2, in dst-server-Master.cfg all the same shard="Master" of course runs shard Master - not ok.
dstserver-2 ignoring any cfg besides dst-server-Master.cfg.
if i before start dstserver make dst-server-Master.cfg how i want, then start dstserver, then change dst-server-Master.cfg for dstserver-2, run dstserver-2. Servers works ok! How is do it automatic?

**Comment by UltimateByte** [comment]
Just duplicate your config file with the right name.
Doc:
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files

**Comment by bugavka** [comment]
in csgoserver then i do second time - ./linuxgsm.sh i, script do csgoserver-2 and csgoserver-2.cfg and all works fine. In dstserver - first time - dstserver and dst-server-Master.cfg, in second time do nothing, I try diplicate config file, what name is right? i try:
for dstserver-2
dstserver-2.cfg, dst-server-dstserver-2.cfg, dst-server-2.cfg. dstserver.sh this files ignore.
if qustion only in name, what config file name is for dstserver-2? Please.
and thanks for help, very much.

**Comment by Fedcomp** [comment]
I have same issue. Can't find a way to create proper config for it. What is the reason there is special behavior which doesn't match wiki page?

**Comment by marvinlehmann** [comment]
@Fedcomp #1554

**Comment by Fedcomp** [comment]
This is the first result in google and so i will post temporary solution:
open `lgsm/config-default/config-lgsm/yourserver/_default.cfg` and comment out
```sh
servicename="dst-server-${shard}"
```

**Comment by marvinlehmann** [comment]
Because there the config structure was completely different when this was implemented.

**Comment by adrensnyder** [comment]
Thanks @Fedcomp for you suggestion. I make the Cave work.
Hope that will be fixed soon :-)

**Comment by UltimateByte** [comment]
Needs merge. :)

**Comment by dgibbs64** [comment]
@marvinlehmann is there anything further required with this?

**Comment by marvinlehmann** [comment]
@dgibbs64 https://github.com/GameServerManagers/LinuxGSM/pull/1554#issuecomment-323476998
The servercfg path contains "installation vars" and must be set manually currently because they aren't wrapped in a function like parms.

**Comment by UltimateByte** [comment]
Hello,

As servicename is now the name of the script starting the program, servicename doesn't have to be commented anymore in config, it is not even there anymore.

Therefore, I have been able to successfully create a DST dual server (with secret caves) without the need to alter LinuxGSM's behavior in January 2021, just following game's guidelines and applying it to how LinuxGSM works.

Second instance is named "caves", and my caves.cfg looks like this:
```
master="false"
shard="Caves"
cave="true"
```

common.cfg looks like this;
```
sharding="true"
cluster="Cluster_1"
```

Main dstserver.cfg looks like this:
```
master="true"
shard="Master"
cave="false"
```


I think we can consider this issue resolved thanks to new LinuxGSM's way of handling instances, so I'm closing it.
Feel free to comment and ask for reopening if needed.

Best regards
