### ISSUE TITLE
LGSM Fedora 26 Python Issue

### ISSUE THREAD

**Issue by Bruno-Bacelar** [GameServerManagers/LinuxGSM#1540]
**OS** - Fedora 26 on VM
**Server** - Insurgency
When starting the insurgency server the script points to a missing **python** dependency, but it starts as usual.
 I also verified that details (./insserver details) shows wrong values.
On fedora 26 page they list a change to python **3.6** and a note saying that a code update is needed.
https://fedoraproject.org/wiki/Changes/Python3.6
I think that might be the problem since it don´t happen in ubuntu 17.04
Sorry for the lack of info but i don´t know much code.
Thanks in advance.

**Comment by dgibbs64** [comment]
Python is only required for the monitor feature. So the server will start without it. Can you confirm that python is installed and working. You can try the monitor feature to confirm if its OK. If python is install correctly them we may need to alter python detection for fedora

**Comment by smounives** [comment]
I have this issue too.

**Comment by Bruno-Bacelar** [comment]
I verified the install seems ok on two diferent servers. sorry the output is in portuguese. but they both say that is installed.

[ehunt@localhost ~]$ sudo dnf install  python
Última verificação de data de vencimento de metadados: 0:06:17 atrás em seg 24 jul 2017 13:28:30 -03.
Pacote **python2-2.7.13-11.fc26.x86_64** já está instalado, ignorando.
Dependências resolvidas.
Nada para fazer.
Concluído!
[ehunt@localhost ~]$ sudo dnf install python3
[sudo] senha para ehunt:
Última verificação de data de vencimento de metadados: 0:13:52 atrás em seg 24 jul 2017 13:28:30 -03.
Pacote **python3-3.6.1-8.fc26.x86_64** já está instalado, ignorando.
Dependências resolvidas.
Nada para fazer.
Concluído!

_The monitor command output also seems ok_

[insserver1@localhost ~]$ ./insserver monitor
    fetching command_monitor.sh...OK
[  OK  ] Monitor insserver: Checking session: OK
    fetching monitor_gsquery.sh...OK
    fetching gsquery.py...OK
[ .... ] Monitor insserver: Querying port: 10.0.0.130:27115 : 0/1 : QUERYING/home/insserver1/lgsm/functions/monitor_gsquery.sh: linha 46: aviso: command substitution: ignored null byte in input
[  OK  ] Monitor insserver: Querying port: 10.0.0.130:27115 : 1 : OK

_This issue causes a slowdown  in running commands, takes a little longer to execute when dependencies are checked about 3~5 seconds every time._

[insserver1@localhost ~]$ ./insserver start
[ERROR ] Starting insserver: Checking dependencies: missing: python

Warning! insserver1 does not have sudo access. Manually install dependencies.
        sudo yum install python

[  OK  ] Starting insserver:

**Comment by drphlux** [comment]
I'm running F26 also. Had to change this:
grep python lgsm/functions/check_deps.sh
to the correct installed python package. In my case to "python3".

**Comment by Bruno-Bacelar** [comment]
Yep, i changed check_deps.sh on the line # LinuxGSM requirements to python3 it solved the error message at startup, not sure if its related but the details page still messed.

insserver Script Details
\x1b[34mService name:       \x1b[0minsserver
\x1b[34minsserver version:  \x1b[0m170710
\x1b[34mUser:               \x1b[0minsserver
\x1b[34mGLIBC required:     \x1b[32m2.15\x1b[0m
\x1b[34mEmail alert:        \x1b[0moff
\x1b[34mPushbullet alert:   \x1b[0moff
\x1b[34mUpdate on start:    \x1b[0moff
\x1b[34mLocation:           \x1b[0m/home/insserver
\x1b[34mConfig file:        \x1b[0m/home/insserver/serverfiles/insurgency/cfg/insserver.cfg

**Comment by drphlux** [comment]
Hello @Bruno-Bacelar 
Those are ansi codes. See issue #1555

**Comment by dgibbs64** [comment]
will need to test python on Fedora

**Comment by dgibbs64** [comment]
Issue was resolved a while ago 
relates to #1941
