### ISSUE TITLE
Minecraft Mods

### ISSUE THREAD

**Issue by devrazox** [GameServerManagers/LinuxGSM#1542]
After trying to adapt the minecraft-lgsm i encounter an issue with missing lockfiles. Monitoring does not work. 
Is there a tutorial for it? 

specific error: "[ERROR ] Monitor ftb-server: Disabled: No lockfile found"

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Monitor#lockfile
