### ISSUE TITLE
MTA Server will not install

### ISSUE THREAD

**Issue by rebel24** [GameServerManagers/LinuxGSM#1545]
On trying to install MTA I get this error:

Installing Multi Theft Auto Server
=================================
    fetching version.h...OK
mkdir: cannot create directory '/home/mtaserver/lgsm/tmp/multitheftauto_linux_x64-1.5.4': File exists
extracting multitheftauto_linux_x64-1.5.4.tar.gz...OK
copying to ...cp: target '' is not a directory
FAIL

=================================

Thanks

**Comment by cedarlug** [comment]
Try
`rm -rf /home/mtaserver/lgsm/tmp/multitheftauto_linux_x64-1.5.4*`
and reinstall.  If that doesn't help, report back the results of:
`find /home/mtaserver/lgsm -type d -exec ls -ld {}` posted to hastebin.
