### ISSUE TITLE
Ts3 server install

### ISSUE THREAD

**Issue by FITZKICK** [GameServerManagers/LinuxGSM#1549]
Hey i got this error when i use this command
`wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh ts3server`

ERROR
> `converted 'https://gameservermanagers.com/dl/linuxgsm.sh' (ANSI_X3.4-1968) -> 'https://gameservermanagers.com/dl/linuxgsm.sh' (UTF-8)
> --2017-07-27 20:28:20--  https://gameservermanagers.com/dl/linuxgsm.sh
> Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.93.238, 104.31.92.238
> Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-07-27 20:28:21 ERROR 404: Not Found.`

**Comment by MarkL4YG** [comment]
``wget -N --no-check-certificate https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh ts3server``

Should work for now although I can't replicate this issue 🤔

**Comment by majoess** [comment]
Yep, the issue is not related to LinuxGSM

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
