### ISSUE TITLE
[rustserver] Creation

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#155]
Looks like Rust is now available. Although highly experimental currently

http://rustdev.facepunchstudios.com/dedicated-server

**Comment by meridimus** [comment]
No one cares about Windows here

**Comment by Scarsz** [comment]
@meridimus as true as that might be it's like saying Apple shouldn't develop iTunes for Windows because it's on a rival OS. WGSM is mainly just a project for me anyway, not really a priority

**Comment by dgibbs64** [comment]
I fully support creating Windows server scripts. Making available as many servers on as many platforms as possible is a great way to go.

**Comment by JulianNL** [comment]
5 months later... just bought this game.

**Comment by JonathanPorta** [comment]
I ended up writing a Chef cookbook for my Windows Rust server. In case it is of any use, it's [here](https://github.com/JonathanPorta/rust-server-cookbook).

**Comment by JulianNL** [comment]
@JonathanPorta Nice, thanks. I might end up running a Windows KVM on the server but really I dont like having Windows anywhere except for a gaming client, not a server.

**Comment by Scarsz** [comment]
Gonna close this for the time being, FacePunch studios is showing no interest in Linux binaries and Garry Newman himself has said Linux binaries aren't on the top of the todo list.
