### ISSUE TITLE
Can't Load Mods : COD4 server

### ISSUE THREAD

**Issue by radyas** [GameServerManagers/LinuxGSM#1559]
I tried to edit cod4server.cfg and add a mod. but still it loads the default one

**Comment by yasirusellahewa** [comment]
startup script doesn't allow changes.it loads default configuration

**Comment by MarkL4YG** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files

**Comment by yasirusellahewa** [comment]
Hi, the thing I wanted is to add a mod to the server
