### ISSUE TITLE
Can't Move Log File - Ubuntu 16.04.1 LTS x86_64

### ISSUE THREAD

**Issue by sinhalaya** [GameServerManagers/LinuxGSM#1561]
[  OK  ] Stopping cod4server: COD4 Server
[ .... ] Starting cod4server: COD4 Server 
mv: cannot move '/home/cod4server/log/script/cod4server-script.log' to '/cod4server-script-2017-08-03-10:00:45.log': Permission denied
[  OK  ] Starting cod4server: COD4 Server

Need help for configuring LGSM.

**Comment by MarkL4YG** [comment]
Set your permissions correctly. Either /home/cod4server or respective folders don't have the correct ownership of your user or write access is denied.
See the ``chown`` and ``chmod`` commands manuals for details.

**Comment by UltimateByte** [comment]
Output of the following command
`ls -al /home/cod4server/log/script/`

**Comment by marvinlehmann** [comment]
The problem is that scriptlogdir is used instead of lgsmlogdir.
https://github.com/GameServerManagers/LinuxGSM/blob/a92f765275b7471b01825c698bef4348b83fd45d/lgsm/config-default/config-lgsm/cod4server/_default.cfg#L77

**Comment by marvinlehmann** [comment]
Was fixed a while ago 98fac37b29f65596c33d546119306dd6db64dc82
