### ISSUE TITLE
Send alert problem 

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1562]
Ubuntu server 16.04.2 LTS x86_64 Kernel 4.4.0.87 tmux 2.1 Glibc 2.23 Project zomboid server appid 380870
--------------------not-so-exact output due to translation-------------
```
./pzserver ta 
[ .... ] Alert pzserver: Sending alert: xxxxxxx@xxxxxx.comtail: read error '/home/pzserver/Zomboid/Logs/logs_01_08' - this is directory
tail: read error '/home/pzserver/Zomboid/Logs/logs_02_08' - this is directory
tail: read error '/home/pzserver/Zomboid/Logs/logs_03_08' - this is directory
mail:cannot send message: process finished........ 
```
-------------------------------------
and    /home/pzserver/Zomboid/Logs/logs_0*_08  yup, its directories.
what I'm doing wrong?

**Comment by marvinlehmann** [comment]
Probably #957 :/

**Comment by dgibbs64** [comment]
Duplicate of #957
closing
