### ISSUE TITLE
backup "fails" because --exclude isn't working as expected

### ISSUE THREAD

**Issue by marvinlehmann** [GameServerManagers/LinuxGSM#1563]
Introduced with 0a8bfc3c258665d1963025c277c9c220def8fb95 ([Line in question](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_backup.sh#L115))

```
marvin@ubuntu:~$ ./boserver backup
[  OK  ] Backup boserver: Backup starting
[ INFO ] Backup boserver: There are no previous backups
[ .... ] Backup boserver: Backup (108M) boserver-2017-08-03-230045.tar.gz, in progress...tar: ./backups: file changed as we read it
FAIL
[ FAIL ] Backup boserver: Starting backup
```

It doesn't work because relative and absolute paths are mixed. The backup will still be created but will also contain the previous ones.

**Variant 1:**
`tar -czf "${backupdir}/${backupname}.tar.gz" --exclude="${backupdir}" --absolute-names ${rootdir}/*`

.. would work but then you have `\\home\<user>\` in the archive.

I just can't find a good solution to it.

EDIT:
**Variant 2:**
```
excludedir=$(realpath --relative-to="${rootdir}" "${backupdir}")
tar -czf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" --exclude "${excludedir}" ./*
```

What about that?

**Comment by UltimateByte** [comment]
Isn't backupdir an absolute path ? If not, that's what we should probably correct.

**Comment by marvinlehmann** [comment]
It is but `-C "${rootdir}" ./*` is relative,

**Comment by Grimston** [comment]
The issue is `lgsm/functions/command_backup.sh` (Line 115)
tar can only use relative or absolute paths, not both backupdir being the full absolute path will not work when you are then using relative paths to create the archive reverting the change here: https://github.com/GameServerManagers/LinuxGSM/commit/0a8bfc3c258665d1963025c277c9c220def8fb95

to: 
```BASH
tar --exclude "backups" -cjf "${backupdir}/${backupname}.tar.bzip2" -C "${rootdir}" ./*
```

exclude is required to be at the front for some versions of tar an oddity now, but to be safe it should be moved.

A new param could be added for the exclusion path but will need to be relative to the ${rootdir}

**Comment by ChrLau** [comment]
Sorry to hop in on this, I'm a first time user running into this problem with my Rust server. I changed the line 115 in `lgsm/functions/command_backup.sh` to the following:

    #tar -czf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" --exclude "${backupdir}" ./*
    tar --exclude "backups" -czf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" ./*

And this works. No tar error message during backup and the created backup files don't include previously generated backups anymore.

**Comment by UltimateByte** [comment]
Tested working:
```
excludedir=$(realpath --relative-to="${rootdir}" "${backupdir}")
tar -czf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" --exclude "${excludedir}" ./*
```

Clever fix, I'm PRing

**Comment by UltimateByte** [comment]
Fixed.
