### ISSUE TITLE
Changing startup command

### ISSUE THREAD

**Issue by DJIronic** [GameServerManagers/LinuxGSM#1565]
I tried to do it with https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters

but I can't found !## Server Start Settings"

In the csgoserver file ("nano csgoserver")

Can you help me with that? thanks

**Comment by Chester07** [comment]
You can edit the start settings on the new config directory 

> ~/lgsm/config-lgsm/gameserver/

I suggest reading through [https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files](url) to see what the three files are for and how to utilize them

**Comment by thorpj** [comment]
I've found that you can override the start parameters in lgsm/config-lgsm/<game>server/_default.cfg by defining the function fn_parms() in lgsm/config-lgsm/<game>server/common.cfg

e.g. 
`
fn_parms(){
parms="-game insurgency -port 27015 +clientport 27016 -tickrate 64 +map ministry +servercfgfile insserver.cfg -maxplay
ers 32 -norestart +sv_password $sv_password +rcon_password $rcon_password -ip ${ip}"
}
`

**Comment by MarkL4YG** [comment]
Do not edit the default config, just edit the instance or common config in that same directory

**Comment by thorpj** [comment]
@MarkL4YG Are you replying to my comment? I never said to edit _default.cfg

**Comment by MarkL4YG** [comment]
@thorpj It appears I misread that ^^. If you want to edit configuration values copying the default configuration and editing that will always be somewhat easier.

**Comment by thorpj** [comment]
@MarkL4YG That's all good. That'd probably be the way to go for OP.
