### ISSUE TITLE
Where can I change slots , gamemodes and defaultmap??? (Garrysmod)

### ISSUE THREAD

**Issue by OKYREW** [GameServerManagers/LinuxGSM#1567]
Recently I can no longer find the lines that were earlier in the file "Gmodserver". I can not find the file where you can change the slot number, game mode and defaultmap. Please help.

Best regards

**Comment by MarkL4YG** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files This is about where you can configure everything needed by LGSM (Ports, Start-Parameters, etc.) the configs you search for are located in the ``cfg`` directory in your serverfiles.
