### ISSUE TITLE
Changing Map and Server Settings [Battlefield 1942 on Debian]

### ISSUE THREAD

**Issue by twillkickers** [GameServerManagers/LinuxGSM#1568]
I have been able to successfully install and set up a Battlefield 1942 server on a Debian virtual machine. I have also been able to successfully connect and join my game through Direct IP connection.

However, the server starts on the Berlin - Conquest mode map and keeps repeating there. How do I select a list of maps/game modes to use? I have tried editing the config file, but I can only change the server name/port from there. Thanks for any guidance!

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
