### ISSUE TITLE
Binutils and BC are missing from installation instructions

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1569]
They both appear to be required, but are missing on Ubuntu 16, so adding them to the `apt-get` command that appears on the website would be good (game: CSGO).  I'm not sure if other distributions come with them, but even those that do should just skip the installation if it's already installed.

**Comment by UltimateByte** [comment]
They are only missing when you install a minimal distro. Though i agree they should be added.

**Comment by dgibbs64** [comment]
this is now added
