### ISSUE TITLE
FastDL generator should preserve existing compressed files

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1570]
No need to regenerate the entire FastDL every single time, far more preferable to only move and compress files that don't have an existing *.bz2 version.

**Comment by UltimateByte** [comment]
And how would it know that a plugin/file was updated then? Making a txt file with md5sum for each file?
Then checking md5sum would use the same time than creating the bz2 again.

**Comment by popey456963** [comment]
CS:GO, at least, doesn't do this either.  For a FastDL you'd be *required* to change the file name if you change the contents of a file / skin / etc.  You wouldn't need to do anything, you'd expect the user to change the filename themselves if they wanted to regenerate it.

(With CS:GO you will get something like "Map differs from local: somemap.bsp.bz2")

**Comment by UltimateByte** [comment]
Historically, FastDL was asking if you wanted to clean old fastdl content, and it would skip already existing files. Though this is a problem for plugin developers and users of plugins that have files changing frequently (especially with gmod), and people preferred the command with less prompts.

**Comment by popey456963** [comment]
@UltimateByte Would it be quick for you to find the commit that changed it?  Perhaps I can just grab the older code and create my own fork of LGSM :)
