### ISSUE TITLE
Problems with multiple IPs

### ISSUE THREAD

**Issue by denizkoekden** [GameServerManagers/LinuxGSM#1571]
Situation:

Server with 5 IPs e.g.

_Interface - IP_
p2p1 - 93.280.180.102
p2p1:1 - 93.280.180.115
p2p1:2 - 93.280.180.116
p2p1:3 - 93.280.180.117
p2p1:4 - 93.280.180.118

When binding the Server with +ip 93.280.180.118 or/and +net_public_adr 93.280.180.118 we get following error:

`Server UGC Manager: Failed to get file info. HTTP status 401
Could not establish connection to Steam servers.

status
hostname: Servername bla bla bla
version : 1.35.9.7/13597 558/6816 insecure (secure mode enabled, disconnected from Steam3) [INVALID_STEAMID]
udp/ip  : MySecondIP:27015
os      :  Linux
type    :  community dedicated
map     : workshop/241267905/aim_multi_v4
gotv[0]:  port 27020, delay 30.0s, rate 32.0
players : 0 humans, 1 bots (32/0 max) (hibernating)

userid name uniqueid connected ping loss state rate adr
2 "GOTV" BOT active 32
end`

I don't get this error without +ip and +net_public_adr but the it is binding the Server to the wrong adress (93.280.180.102).

We tried new tokens and different ports (which worked for other servers) but no luck. Any Ideas why?

Regards

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
