### ISSUE TITLE
Unable to get CS:GO running

### ISSUE THREAD

**Issue by naxIO** [GameServerManagers/LinuxGSM#1572]
Hi, 

I tried over several days with several clean attempts (each time from scratch) to get my CS:GO Server running.

I'm always getting

```
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '740' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
```

also going further I can see

```
[ERROR ] Install csgoserver: SteamCMD is missing
mkdir: created directory '/home/csgoserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/csgoserver/lgsm/functions/install_server_files.sh: line 97: ./steamcmd.sh: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
````

Is this a steam issue? I wonder why it always enters the ```state 0x202 ``` To be sure I waited between the attempts and always re-installed from scratch (wiped entire folders).

Any ideas?

Thanks

**Comment by cedarlug** [comment]
Disk space would be the most common issue.

Before you respond with "OF COURSE I HAVE ENOUGH SPACE", please note that you have not posted the output from ./csgoserver postdetails.

See the REQUIREMENTS stanza in https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Traace** [comment]
Yes, its a issue with the Steam Client. Happens even without LinuxGSM. We have enough disk space, minimum are 8gb, we got 14gb left. Way enough for such a gameserver.

Gameserver: CS:GO
Postdetails Link: https://hastebin.com/domeluxono
Output Error: "Error! App '740' state is 0x202 after update job"

Hardware:
OS: ESXi 6.5 (5969303)
CPU: 4x Six-Core AMD Opteron(tm) Processor 8431
RAM: 128GB DDR2 ECC
Storage: Couple TB's SATA&SAS (No RAID) @ HP Smart Array P410

GameserverVM-OS: Fedora 26 Server
But also tried with a Ubuntu Server @ 100GB Storage, e.g. 85GB ~ free after install. Still the same error message.

**Comment by naxIO** [comment]
Okay will check space, might be an issue with temp. extraction of install data. Will report back.

**Comment by naxIO** [comment]
Gotta confirm what @Traace is saying here. I have enough disk space, the error is the same. Now after some days passed I'm not sure if this still could be a temp. Steam issue.

**Comment by naxIO** [comment]
bump. problem persists. anyone any idea? thanks

**Comment by naxIO** [comment]
Okay it was crazy more diskspace (30gb+) to have. Maybe would be nice to add a warning and precheck to LGSM to address this before installation attempt.

**Comment by MarkL4YG** [comment]
I think there was an issue/PR about disk space checks but I don't know what happened to that idea...

_Sent from my Samsung SM-G901F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Traace** [comment]
The issue is still not fixed. Why is it labeled as resolved? Thats not correct.

This Bug isn't fixable by LinuxGSM but not "resolved" here either.  A correct tag would be like "Not fixable"

LinuxGSM should also mention that SteamCMD is not compatible with ESXi Systems on their Website in order to prevent such "bug" reports again.
