### ISSUE TITLE
Simultaneously running multiple instances on a single installation?

### ISSUE THREAD

**Issue by ivko1950** [GameServerManagers/LinuxGSM#1574]
Distro: Ubuntu 16.04 LTS
Game server: vanilla csgo

I've used [this guide](https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers) to create multiple csgo servers using a single installation. Both of them work fine separately, but whenever I try to run both servers at the same time one of them shuts down. I've configured the ports correctly. Google doesn't seem to be of any help either. Any help would be greatly appreciated :)

**Comment by MarkL4YG** [comment]
Did you use different names for them?

**Comment by ivko1950** [comment]
The scripts have different names, but both have `gameservername="csgoserver"` within the script. I've tried changing it, but then I get the following message: 
> fetching _default.cfg . . . FAIL
