### ISSUE TITLE
Random default map from cycle file

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1577]
Would be great to have it so that LGSM can pick a random map to start with from the map cycle of a gamemode, instead of starting on one map all the time.

**Comment by MarkL4YG** [comment]
LGSM is not responsible for game features. If you don't even provide the game name you won't get a solid answer...

**Comment by popey456963** [comment]
@MarkL4YG Apologies, this is for CS:GO.  The map is stored in the configuration file already (`defaultmap="de_mirage"`) and is sent to the server via a flag (I believe this is the same with the majority of source servers I've seen).

By virtue of Valve's Developer Network, it appears that the majority of games store their map list in `mapcycle.txt`, so a suggested feature addition would be something along the lines of:

 - An extra configuration value, `map_cycle_file`.
 - On server start, if `map_cycle_file` is defined (or some other option enabled), run `map_choice='sort -R ${map_cycle_file} | head -n '`.
 - Use the newly declared variable as the map start parameter.

**Comment by MarkL4YG** [comment]
Have you tried normal solutions to enable map rotation [like this](https://forums.alliedmods.net/showthread.php?t=254758) ?

**Comment by popey456963** [comment]
Aye, I use `mapchooser-extended`, which gives me random maps during the game.  However it does not alter the first map choosen.

Since I run a crappy server that crashes every few hours, it means that we play our default map significantly more than expected :).

At the moment I feel I'm just butchering LGSM with my implementation, but I've already got this system working locally.

**Comment by MarkL4YG** [comment]
If you've got a generalized working solution feel free to suggest it using PRs

**Comment by popey456963** [comment]
@MarkL4YG Completely butchered, I literally just replace the `defaultmap` value with the cycle list command above.

If I was to do it properly and add an option to enable/disable it, would it have a chance at being accepted?

**Comment by MarkL4YG** [comment]
I do think so
