### ISSUE TITLE
Problem installing Factorio server

### ISSUE THREAD

**Issue by Alextronick** [GameServerManagers/LinuxGSM#1579]
Bonjour,

Quand je lance la commande ./fctrserver install
j'ai une erreur:

>     extracting factorio_headless_linux64-0.15.33.tar.gz...tar (child): xz : exec impossible: Aucun fichier ou dossier de ce type
>     tar (child): Error is not recoverable: exiting now
>     tar: Child returned status 2
>     tar: Error is not recoverable: exiting now
>     FAIL

Que puis-je faire ?
Merci.

===================================================================

Hi,

When i launch the command ./fctrserver install
i have an error :

> extracting factorio_headless_linux64-0.15.33.tar.gz...tar (child): xz : exec impossible: Aucun fichier ou dossier de ce type
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> FAIL

What can-i do ?
Thanks.

**Comment by XTowerX** [comment]
after a recent update it would seem the package tool has changed, so even thou it installs all the dependencies, one is left out namely the "xz-utils" i use this and it has fixed my issue with unpacking.

**Comment by dgibbs64** [comment]
added xz-utils for next release
