### ISSUE TITLE
Arkserver mod do not load

### ISSUE THREAD

**Issue by Rayzos** [GameServerManagers/LinuxGSM#1580]
Hello,

I have a small problem with my server under Debian 8 my download well in the workshop part (folder steam) adding the mods in game.ini but I can not load them on the server (nothing is written In shooterGames / content / mods)

I tried to add the "GameModid" command but nothing to do.

Can someone help me?

**Comment by Rayzos** [comment]
up

**Comment by Etsche** [comment]
I have the same issue. The mods are loaded into the wrong folder.

**Comment by Rayzos** [comment]
What is on it is that steam copies the workshop on its side but server side the mods does not copy at all

**Comment by Rayzos** [comment]
No one has solution?

My mods load well in the steamapps but the server refuses to inject them into shootergames / content / mods

It is the galley to go through virtualization solutions like ESKI with a vm under Windows while massacring the perfs of my dedicated :(

**Comment by Rayzos** [comment]
UP

**Comment by MarkL4YG** [comment]
LGSM is about installing and general maintenance of the server. If you want specific support like you need when you've got mod issues ask in a dedicated forum for that server.

**Comment by Rayzos** [comment]
Or may I apply in the hope of having a response?

Because everyone is having trouble putting mods with Linux LGSM and nobody has concrete answers every time ...

**Comment by MarkL4YG** [comment]
Well then we may need an expert in Ark-Modding who can tell us whether or not something is wrong or better doable in the scripts.  
Otherwise: Use the Ark forums.

**Comment by Rayzos** [comment]
Okay, hoping that in time it's up for good.
I used utilities like linux server managger the mods download well but it is really unstable when launching or wanting to everything taken my server modded with Linux LGSM
