### ISSUE TITLE
Bug with CS:S Script "Fastdl"

### ISSUE THREAD

**Issue by ByMRVN** [GameServerManagers/LinuxGSM#1581]
I might found a bug in the LGSM script. I typed ./cssserver fastdl and something crazy happened. It creates the normal "public_html" folder and the under folders like "models, materials etc". But all materials that i have on the server will be packed into bzip2 (normal) and will be placed in the "materials" folder. Example: cstrike/materials/zombie.vtf ! cstrike/materials/skelleton.vtf. But on my server its like this: cstrike/materials/models/player/zh/zombie.vtf. It means the command with "fastdl" dont put the materials and models in the right folder. (I hope you understand what i am writing. My english is terrible)

**Comment by dgibbs64** [comment]
same as https://github.com/GameServerManagers/LinuxGSM/issues/1585
