### ISSUE TITLE
[ WARN ] _default.cfg has been altered. reloading config.

### ISSUE THREAD

**Issue by mydevice** [GameServerManagers/LinuxGSM#1586]
Hello,

I am trying to modify the /home/csgoserver/lgsm/config-lgsm/csgoserver/_default.cfg 

gslt=""
defaultmap="de_mirage"

Whenever I try to change the above lines i get the message """"[ WARN ] _default.cfg has been altered. reloading config""" and no change is made in _default.cfg.

Please help, thank you.

**Comment by dgibbs64** [comment]
Check out these docs.

https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files
