### ISSUE TITLE
Failure! SteamCMD did not complete the download, too many retries

### ISSUE THREAD

**Issue by Taron2013** [GameServerManagers/LinuxGSM#1587]
Been working on this for the last couple of days I think I may have found a bug in the current release of LinuxGSM scripts.  This is my first time trying to setup a game server.  I tried doing this with both factorio and ark survival evolved below is what I always get.  Also, I tried using the recommended usernames for ark and factorio before attempting it just as my own user to see if the results might differ due to permissions.  I always answer n to the was the install successful because it seems it is failing to download SteamCMD.

**System Spec Sheet Information**
OS:  Fedora server installation version 26
Ram: 16GB ram
Storage: SSD primary
 CPU: 6 cores AMD processor using crosshair formula IV motherboard so 3 generations old.

```
=================================
ARK: Survival Evolved
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================

Server Directory
=================================
/home/dcross
Continue? [Y/n] Y
mkdir: created directory '/home/dcross/serverfiles'

Creating log directories
=================================
installing log dir: /home/dcross/log...OK
installing LinuxGSM log dir: /home/dcross/log/script...OK
creating LinuxGSM log: /home/dcross/log/script/arkserver-script.log...OK
installing console log dir: /home/dcross/log/console...OK
creating console log: /home/dcross/log/console/arkserver-console.log...OK
installing game log dir: /home/dcross/serverfiles/ShooterGame/Saved/Logs...OK
creating symlink to game log dir: /home/dcross/log/server -> /home/dcross/serverfiles/ShooterGame/Saved/Logs...OK

Checking Dependencies
=================================
tmux
wget
util-linux
python
file
gzip
bzip2
unzip
glibc.i686
libstdc++.i686
[ERROR ] Install arkserver: Checking dependencies: missing: python
Information! Automatically installing missing dependencies.
Last metadata expiration check: 0:04:05 ago on Sun 20 Aug 2017 05:09:03 PM EDT.
Package python2-2.7.13-11.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
Complete! Install dependencies completed

Installing SteamCMD
=================================
mkdir: created directory '/home/dcross/steamcmd'
extracting steamcmd_linux.tar.gz...OK

Installing ARK: Survival Evolved Server
=================================
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[  0%] Downloading update (0 of 18,800 KB)...
[  0%] Downloading update (990 of 18,800 KB)...
[  5%] Downloading update (2,496 of 18,800 KB)...
[ 13%] Downloading update (3,568 of 18,800 KB)...
[ 18%] Downloading update (4,792 of 18,800 KB)...
[ 25%] Downloading update (5,654 of 18,800 KB)...
[ 30%] Downloading update (6,509 of 18,800 KB)...
[ 34%] Downloading update (7,372 of 18,800 KB)...
[ 39%] Downloading update (8,648 of 18,800 KB)...
[ 46%] Downloading update (9,854 of 18,800 KB)...
[ 52%] Downloading update (10,986 of 18,800 KB)...
[ 58%] Downloading update (11,928 of 18,800 KB)...
[ 63%] Downloading update (12,934 of 18,800 KB)...
[ 68%] Downloading update (13,826 of 18,800 KB)...
[ 73%] Downloading update (14,599 of 18,800 KB)...
[ 77%] Downloading update (15,351 of 18,800 KB)...
[ 81%] Downloading update (16,283 of 18,800 KB)...
[ 86%] Downloading update (17,294 of 18,800 KB)...
[ 91%] Downloading update (18,312 of 18,800 KB)...
[ 97%] Downloading update (18,800 of 18,800 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 12,824 KB)...
[  0%] Downloading update (1,292 of 12,824 KB)...
[ 10%] Downloading update (2,092 of 12,824 KB)...
[ 16%] Downloading update (2,560 of 12,824 KB)...
[ 19%] Downloading update (3,129 of 12,824 KB)...
[ 24%] Downloading update (3,691 of 12,824 KB)...
[ 28%] Downloading update (4,294 of 12,824 KB)...
[ 33%] Downloading update (5,071 of 12,824 KB)...
[ 39%] Downloading update (6,060 of 12,824 KB)...
[ 47%] Downloading update (7,186 of 12,824 KB)...
[ 56%] Downloading update (8,486 of 12,824 KB)...
[ 66%] Downloading update (9,671 of 12,824 KB)...
[ 75%] Downloading update (10,910 of 12,824 KB)...
[ 85%] Downloading update (12,091 of 12,824 KB)...
[ 94%] Downloading update (12,621 of 12,824 KB)...
[ 98%] Downloading update (12,824 of 12,824 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 86.41 (5101228958 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 88.10 (5200918371 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 3
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 81.02 (4783033114 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 4
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 84.69 (4999414593 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 5
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 87.73 (5178804795 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 6
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 79.56 (4696828641 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Removing 
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 82.48 (4869201510 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing 
Redirecting stderr to '/home/dcross/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 86.20 (5088943167 / 5903352562)
Error! App '376030' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing 
[ERROR ] Install arkserver: SteamCMD is missing
mkdir: created directory '/home/dcross/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/dcross/lgsm/functions/install_server_files.sh: line 97: ./steamcmd.sh: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing 
[ERROR ] Install arkserver: SteamCMD is missing
mkdir: created directory '/home/dcross/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/dcross/lgsm/functions/install_server_files.sh: line 97: ./steamcmd.sh: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys
```

**Comment by mwurzberger** [comment]
I am having the same problem. Running an additional time gets the following output.

=================================
7 Days To Die
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================

Server Directory
=================================
Warning! A server is already installed here.
/home/sdtdserver

Continue? [Y/n] Yy
Please answer yes or no.
Continue? [Y/n] Y^C
sdtdserver@seven-dtd:~$ ./sdtdserver install
=================================
7 Days To Die
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================

Server Directory
=================================
Warning! A server is already installed here.
/home/sdtdserver

Continue? [Y/n] Y

Creating log directories
=================================
installing log dir: /home/sdtdserver/log...OK
installing LinuxGSM log dir: /home/sdtdserver/log/script...OK
creating LinuxGSM log: /home/sdtdserver/log/script/sdtdserver-script.log...OK
installing console log dir: /home/sdtdserver/log/console...OK
creating console log: /home/sdtdserver/log/console/sdtdserver-console.log...OK

Checking Dependencies
=================================
tmux
wget
ca-certificates
file
bsdmainutils
util-linux
python
bzip2
gzip
unzip
binutils
lib32gcc1
libstdc++6:i386
telnet
expect

Installing SteamCMD
=================================
Information! SteamCMD is already installed...OK

Installing 7 Days To Die Server
=================================
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[  0%] Downloading update (0 of 18,800 KB)...
[  0%] Downloading update (942 of 18,800 KB)...
[  5%] Downloading update (3,357 of 18,800 KB)...
[ 17%] Downloading update (4,461 of 18,800 KB)...
[ 23%] Downloading update (6,177 of 18,800 KB)...
[ 32%] Downloading update (8,050 of 18,800 KB)...
[ 42%] Downloading update (9,413 of 18,800 KB)...
[ 50%] Downloading update (11,082 of 18,800 KB)...
[ 58%] Downloading update (12,397 of 18,800 KB)...
[ 65%] Downloading update (14,220 of 18,800 KB)...
[ 75%] Downloading update (15,987 of 18,800 KB)...
[ 85%] Downloading update (17,717 of 18,800 KB)...
[ 94%] Downloading update (18,800 of 18,800 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 12,824 KB)...
[  0%] Downloading update (953 of 12,824 KB)...
[  7%] Downloading update (1,380 of 12,824 KB)...
[ 10%] Downloading update (1,921 of 12,824 KB)...
[ 14%] Downloading update (2,250 of 12,824 KB)...
[ 17%] Downloading update (2,658 of 12,824 KB)...
[ 20%] Downloading update (3,038 of 12,824 KB)...
[ 23%] Downloading update (3,485 of 12,824 KB)...
[ 27%] Downloading update (4,875 of 12,824 KB)...
[ 38%] Downloading update (5,264 of 12,824 KB)...
[ 41%] Downloading update (6,441 of 12,824 KB)...
[ 50%] Downloading update (7,696 of 12,824 KB)...
[ 60%] Downloading update (8,961 of 12,824 KB)...
[ 69%] Downloading update (10,079 of 12,824 KB)...
[ 78%] Downloading update (11,467 of 12,824 KB)...
[ 89%] Downloading update (12,725 of 12,824 KB)...
[ 99%] Downloading update (12,824 of 12,824 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 78.26 (2699192345 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 3
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 77.99 (2689585464 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 4
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 77.80 (2683061105 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 5
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 77.45 (2671122908 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 6
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 77.45 (2671204459 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Removing
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 78.45 (2705587288 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'bergerserverd' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 78.49 (2706808841 / 3448793682)
Error! App '294420' state is 0x202 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing
[ERROR ] Install sdtdserver: SteamCMD is missing
mkdir: created directory '/home/sdtdserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/sdtdserver/lgsm/functions/install_server_files.sh: line 97: ./steamcmd.sh: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
[ERROR ] Install sdtdserver: SteamCMD is missing
mkdir: created directory '/home/sdtdserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/sdtdserver/lgsm/functions/install_server_files.sh: line 97: ./steamcmd.sh: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys

**Comment by Khelgar1** [comment]
Could be a disk space issue run `df -h` and see if you have enough free space

**Comment by UltimateByte** [comment]
Respect the rules please.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

To sum up:
Provide postdetails output or nicely gtfo
Put your damn logs in hastebin or pastebin or equivalent

**Comment by dgibbs64** [comment]
#2959
