### ISSUE TITLE
Change timestamps in script logs to include milliseconds

### ISSUE THREAD

**Issue by jimwald1221** [GameServerManagers/LinuxGSM#1588]
I'd like to request that the timestamps that are configured in "core_messages.sh" be updated to include milliseconds in their timestamps. I'm working with a log aggregator and would like to be able to see the difference in event times with milliseconds since it makes them easier to read. Adding ".%3N" does the trick.

**Comment by dgibbs64** [comment]
@jimwald1221 mentioned its for helping with splunk. Simple change that im happy to have done
