### ISSUE TITLE
Server crashes every 30 mins

### ISSUE THREAD

**Issue by smishcraft** [GameServerManagers/LinuxGSM#1597]
Running a gmod server with the ./gmodserver start makes it crash every 30 mins BUT
running it in the debug mode doesnt crash untill the putty session times out.

Garry's Mod Debug
=================================

Distro: Ubuntu 17.04
Arch:   x86_64
Kernel: 4.10.0-32-generic
Hostname:       [REDACTED]
tmux:   tmux 2.3
Avg Load:       0.29, 0.17, 0.22
Free Memory:    24G
Free Disk:      113G
GLIBC required: 2.15

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
