### ISSUE TITLE
CS:GO gamemode table in "_default.cfg" missing custom gametype

### ISSUE THREAD

**Issue by popey456963** [GameServerManagers/LinuxGSM#1602]
It has gametype 3 & any gamemode.

**Comment by MarkL4YG** [comment]
``_default.cfg`` is unmodifiable. You need to modify either the ``common.cfg`` or you ``<instance>.cfg`` for custom settings!

**Comment by popey456963** [comment]
@MarkL4YG My bad for not explaining myself,  I know how to alter the gametype itself.

It's just that LGSM contains a table ([here](https://github.com/GameServerManagers/LinuxGSM/blob/a92f765275b7471b01825c698bef4348b83fd45d/lgsm/config-default/config-lgsm/csgoserver/_default.cfg#L13-L18)) which doesn't seem to contain the custom gametype.  Felt it might be helpful to others.

**Comment by marvinlehmann** [comment]
It'll be in the next release ;)
