### ISSUE TITLE
[Server Request] FortressCraft Evolved!

### ISSUE THREAD

**Issue by microfire21** [GameServerManagers/LinuxGSM#1604]
I did a quick search on here and did not come up with and hits. Myself and a few others would be interested in testing this CLI on our dedi if anyone was up for it....always willing to donate to help out as well.

**Comment by ozhound** [comment]
i vote for this as well !!

**Comment by patrickblattner** [comment]
me too!

**Comment by h3o66** [comment]
https://steamdb.info/app/443600/

Seems to be a bit wired, the linux server seems to be in a seperate branch

**Comment by dgibbs64** [comment]
Sadly Game appears to be dead. I will close this issue


![Image](https://github.com/GameServerManagers/LinuxGSM/assets/4478206/34ff7d00-e352-4668-a7b4-e7b7c350750b)
