### ISSUE TITLE
fix_ark.sh command not found issue

### ISSUE THREAD

**Issue by savisitor15** [GameServerManagers/LinuxGSM#1605]
fix_ark.sh is being called when starting the ark server using ./arkserver start
however, core_functions.sh doesn't know if it.

Think this was left out by accident? may need adding in.

**Comment by RussianRonin** [comment]
Try running ./arkserver uf. It will update all the functions and I think it finds any new ones.

**Comment by savisitor15** [comment]
This has been done, all up to date and I even did a full Git fetch just to be sure. 
The function call needs to be added to: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/core_functions.sh

**Comment by marvinlehmann** [comment]
Thanks for report! Seems that someone forgot it. It's included in the next hotfix!

**Comment by savisitor15** [comment]
Happy to help
