### ISSUE TITLE
Lgsm's FastDL for CSGO Not picking up/converting .wav/mp3 sound files

### ISSUE THREAD

**Issue by CruelAlpha** [GameServerManagers/LinuxGSM#1608]
Hi,
I have a fully working fast DL configured with lgsm. All the files get generated for the maps models and materials however, the sounds are not transferred over to the fast dl folder.
I was wondering if anyone knew a fix for this?

**Comment by UltimateByte** [comment]
Probably same as https://github.com/GameServerManagers/LinuxGSM/issues/1683
Not enough details to say anyways.
