### ISSUE TITLE
LinuxGSM - CS1.6 Error

### ISSUE THREAD

**Issue by erac03** [GameServerManagers/LinuxGSM#1609]
Hello.

I was trying to install a nonsteam CS1.6 server and i cannot to it, when i run ./gameserver monitor i get the following message
[  OK  ] Monitor csserver: Checking session: OK
[ FAIL ] Monitor csserver: Querying port: 162.243.186.152:27015 : 18/2 : ERROR: Unable to receive

This is my server log
https://hastebin.com/eqayeyehop

And i have no idea where to start to look at, can i get some help please?

Thank you.

**Comment by ivunchata** [comment]
Hello,

I had the same issue and I got information from the server logs, where it was stated that I was missing some files ("FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad") and this pointed me to #1450 and #1637 .
The way it worked for me was to follow the usual steps from [here](https://gameservermanagers.com/lgsm/csserver/) and during the stage where the files are being downloaded (part of "./csserver install") I ran the "one-liner" from [here](https://github.com/dgibbs64/HLDS-appmanifest).

Good luck,
Ivan.

**Comment by dgibbs64** [comment]
also nonsteam versions are not supported by LinuxGSM

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#how-can-i-install-a-non-steam-version
