### ISSUE TITLE
UTF-8 (input) not working in console screen

### ISSUE THREAD

**Issue by MAGNAT2645** [GameServerManagers/LinuxGSM#1610]
I have problem that appeared recently. At first I had a problem with BackSpace, now it works fine. Now i have problem that i can't input any UTF8 symbol in console (output symbols works fine)

I'm using XShell and this problem only with ./tf2server console, all other screens works fine

**Comment by UltimateByte** [comment]
Don't edit files with windows bloc note.

**Comment by MAGNAT2645** [comment]
I'm using NotePad++ and i did not changed any scripts (only tf2server for running srcds_run)

**Comment by UltimateByte** [comment]
Misread the thing.
Well, xshell + tmux inside another might cause the issue. If it doesn't occur with debug command, you'll know that's the issue.
Non-LGSM issue though, unless proven otherwise so closing.

**Comment by MAGNAT2645** [comment]
I think that this is script issue because i have used XShell, PuTTY (KiTTY) and Google Chrome extension "Secure Shell" and none of them work. Also i have disabled consolelogging (only use -condebug param)

At first UTF-8 input worked fine with tmux but did not work Backspace button, now Backspace working but UTF-8 input won't (for example i'm pressing о (J on english) button and console print lastly passed command instead of UTF-8 text)
