### ISSUE TITLE
[Left 4 dead] Setting server password has no effect

### ISSUE THREAD

**Issue by dvdvideo1234** [GameServerManagers/LinuxGSM#1613]
Server name:      FooBar
Server IP:        192.168.0.105:27015
Server password:  test_pass  // Set via "sv_password test_pass"
RCON password:    rcon_test // Set on the client and server but says "BAD rcon" when connectong to *.105
Maxplayers:       8
Status:           ONLINE

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
