### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by ProGamesTv** [GameServerManagers/LinuxGSM#1616]
Hello.
I have cs:go server. But my autoupdate not working.
https://hastebin.com/edayeranek
I don't know what i must do to repair autoupdate.
Thank you for answers.

**Comment by RussianRonin** [comment]
What is your auto-update process? Are you using a cron-job or something? Because I do not think LGSM includes auto-update by default unless I am missing something.

**Comment by ProGamesTv** [comment]
I use cron. crontab -e and default commands from wiki.

**Comment by RussianRonin** [comment]
What is not happening that should be? Are there any error messages?

**Comment by ProGamesTv** [comment]
I don't have any errors. Nothing is happend. I must update servers after update manually.

**Comment by ProGamesTv** [comment]
I copy and replace everything what i should do.  I don't know what i must do :(

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Update
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files
