### ISSUE TITLE
Project Zomboid Beta branch issues

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1621]
For information (maybe to add some text to website PZ install instruction?) 
Project Zomboid steam beta branches NOT working with steampp id 380870 (dedicated server)
Only full game (steamapp id 108600) can be used to host dedicated server in beta branches.
But 108600 requires game purchase, so no ANonymous login possible to download

**Comment by dgibbs64** [comment]
This is an issue that should be raised with the Project Zomboid team.
