### ISSUE TITLE
Project Zomboind install dependancies string 

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1622]
Project Zomboid "install dependencies string" in website inctruction 
https://gameservermanagers.com/lgsm/pzserver/  for Ubuntu 64 

`sudo dpkg --add-architecture i386; sudo apt-get update;sudo apt-get install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux ca-certificates tmux lib32gcc1 libstdc++6 libstdc++6:i386 default-jre`

misses binutils , needed to run LinuxGSM

**Comment by dgibbs64** [comment]
binutils has now been added to instructions and for checks
