### ISSUE TITLE
CoD WW2

### ISSUE THREAD

**Issue by BarbieQ1** [GameServerManagers/LinuxGSM#1624]
Hello everybody,
is it possible for CoD WWII, asap to publish the GMS?
(release 3nov17)

BR
BBQ

**Comment by dgibbs64** [comment]
Does this even have Linux support?

**Comment by ur-n1ghtmar3** [comment]
It doesn't even have dedicated server support.

**Comment by marvinlehmann** [comment]
If something changes which is very unlikely, we'll reopen this issue.
