### ISSUE TITLE
[CSGO]Host_Error: Recursively entered

### ISSUE THREAD

**Issue by MySelfLuls** [GameServerManagers/LinuxGSM#1625]
Hello,
I have been setting up fastDL and currently experiencing a pretty weird and basically unknown error when joining the server now after doing this, i'll elaborate after giving the information required for an issue.

# Required & Additional Information
- **Game Server:** CSGO
- **./Gameserver postdetails:** [here](https://hastebin.com/hifufuqaju)
- **Error Screenshot:** [here](http://ss.myselfluls.pw/v0ISjQ6iMr.png)
- **Hardware Requirements for CSGO are _more than_ fulfilled**
- **Apache2 version:** 2.4.25 (Ubuntu)
- **Apache2 Config:** [here](https://hastebin.com/doyofekeci.apache)
- **FastDL Link:** [here](http://176.9.235.15/fastdl/)

## Test attempted

1. Running fastDL again and overriding previous files
2. Changing map names to avoid clientside problems
3. Tested to see if I download the map (I do)
4. Attempted with other maps
5. Attempted with other people
6. Attempted with clean version of CSGO
7. Attempted without any workshop subscriptions (and maps removed locally)

### Only error found
When doing the ./csgoserver fastdl command
I get this error
`/home/csgoserver/lgsm/functions/command_fastdl.sh: line 138: bc: command not found`
That is sadly everything I was able to find about it.
Should you require more information please do tell me and i'll get any logs, even though I found nothing useful in them.

**Comment by cedarlug** [comment]
`apt-get install bc`

**Comment by dgibbs64** [comment]
bc is now a requirements that is checked. Will be in the next release
