### ISSUE TITLE
Add alert for change in _default.cfg

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1627]
Admins should know if the _default.cfg has changed as there may be parts of there config they want to change

**Comment by MarkL4YG** [comment]
I guess that means when it changes from one release to another right?

**Comment by dgibbs64** [comment]
Yeah. The reason for _default.cfg is so we can add new settings. However currently if a new setting is added the admin will not know about it unless they updated themselves. If an update was done on a cron they will not know if _default.cfg was updated

**Comment by dgibbs64** [comment]
I have now added a notification alert if _default.cfg changes.
