### ISSUE TITLE
Arma III Server configuration issues.

### ISSUE THREAD

**Issue by lowheartrate** [GameServerManagers/LinuxGSM#1635]
I have adjusted my *common.cfg file* (what I thought was properly) but for some reason am having an issue where on the Arma III Server Browser it shows that I need the specific mods in order to play on it but when I click on the *join* button, the server still allows me to join and play in it although I have *0 mods* enabled while launching Arma III.

![](https://puu.sh/xMzob/6111a372fb.png)

## /home/arma3server/lgsm/config-lgsm/arma3server/common.cfg:
```
## ARMA 3 Modules
# Add mods with relative paths:
# mods/@cba_a3
# To load the "Community Base Addons v3" module found in the
# directory serverfiles/mods/@cba_a3.  Load several mods as:
# mods="mods/@ace\;mods/@acex\;mods/@cba_a3"
mods="/home/arma3server/serverfiles/@ace\;/home/arma3server/serverfiles/@CBA_A3\;/home/arma3server/serverfiles/@task_force_radio"

## Server-side Mods
servermods="/home/arma3server/serverfiles/@ace\;/home/arma3server/serverfiles/@CBA_A3\;/home/arma3server/serverfiles/@task_force_radio"
```
[You can view what the full file looks like here](https://hastebin.com/nuxecamera.pl).

**Comment by MarkL4YG** [comment]
First: The issues of lgsm are ___only___ for script issues. You may need to ask that question in an Arma 3 forum.  

Secondly: Either define a mod as ``mod`` or as ``servermod``. Mods defined as ``servermod`` are (therefore the name) server-side only - That means the server does not require clients to have such mods installed.
