### ISSUE TITLE
kf2 server missing file

### ISSUE THREAD

**Issue by dementedusa** [GameServerManagers/LinuxGSM#1636]
just did an install of kf2 on  Ubuntu 16.04.3 LTS.  when I do the start command it fails to start and says this
[  OK  ] Starting kf2server:
gameservers@s94535:~/kf2server$ ./kf2server details
    fetching command_details.sh...OK
grep: /home/gameservers/kf2server/serverfiles/KFGame/Config/kf2server/KFWeb.ini: No such file or directory
grep: /home/gameservers/kf2server/serverfiles/KFGame/Config/kf2server/KFWeb.ini: No such file or directory
grep: /home/gameservers/kf2server/serverfiles/KFGame/Config/kf2server/KFWeb.ini: No such file or directory
grep: /home/gameservers/kf2server/serverfiles/KFGame/Config/kf2server/KFWeb.ini: No such file or directory

**Comment by dgibbs64** [comment]
Yes I have noticed this as well. I am not sure why this is happening currently. I didnt get this during tests. I will investigate and resolve

**Comment by dementedusa** [comment]
ok so I was messing around and trying things cause why not science.  and created a KFWeb.ini file in the location it says it is not found and that stopped that error.  But now it say    
[ FAIL ] Starting kf2server: Unable to start NOT SET
so I am trying to google some info on how to fix and learn what the hell needs to be done

**Comment by UltimateByte** [comment]
This error is LGSM relatée, check un info_config.sh :)

**Comment by paradoxtech** [comment]
Same here, have had to manually create KFWeb.ini but still failing to launch.

![image](https://user-images.githubusercontent.com/31586464/31169878-070075ae-a8f2-11e7-9503-706883884b0d.png)

**Comment by dgibbs64** [comment]
I have figured out the issue. 

All the config files are not present at first in `KFGame/Config/` when downloading from SteamCMD.

To generate all required config files the server has to run without the `ConfigSubDir=` parm one time.

This creates all the required config files in the default location `KFGame/Config/`. 

Once this is completed `ConfigSubDir=` can be added again and this will then copy all the newly generated config files to the `KFGame/Config/kf2server` directory. 

This is really annoying and I will have to figure out the best way to do this. I may contact Tripwire to see if they can simply have the default configs in place in SteamCMD. Would save a lot of issues.

**Comment by dementedusa** [comment]
good luck on getting tripwire to do anything..      The only place I can find that line of code in is the kf2server/lgsm/config-lgsm/kf2server/_default.cfg    Do I just copy the file into the common.cfg and delete it there, then start, then put it back in?

**Comment by dementedusa** [comment]
haha.  that was correct.  it worked.  YAY

**Comment by ExodiusUK** [comment]
I'm still running into this issue no matter what I try :O am I missing something?

**Comment by dementedusa** [comment]
ok go to kf2server/lgsm/config-lgsm/kf2server/_default.cfg   copy everything in that file and put it in /kf2server/lgsm/config-lgsm/kf2server/common.cfg     search the file for ConfigSubDir=  and remove ConfigSubDir=     then restart the server.    after that stop the server.    then put ConfigSubDir=  back in where you removed it.

**Comment by ExodiusUK** [comment]
Thank you so much :) that worked :)

**Comment by dgibbs64** [comment]
This fix will be in the next release
