### ISSUE TITLE
Problem: "[ INFO ] Backup arkserver: Lock file found: Backup is currently running"

### ISSUE THREAD

**Issue by Seth2Chris** [GameServerManagers/LinuxGSM#1641]
I can't creat new Backup on a server that say is currently running...
How to stop Backup in progress?

Thank you.

**Comment by UltimateByte** [comment]
This happens if a backup was stopped. The purpose of the lockfile is to prevent two backups from happening at the same time.

The backup lockfile si located in lgsm/tmp/.backup.lock
Remove it and the message will disappear.
