### ISSUE TITLE
Question: [GMOD] How could I restrict the gameserver User to his own directory?

### ISSUE THREAD

**Issue by SenseiHiraku** [GameServerManagers/LinuxGSM#1642]
Hey Everyone,
Iam using LinuxGSM for a while, espacially with GMod Server, but there are one Problem, which get on my nerves a lot and is a security risk for me. I dont want, that one Useraccount from a Gameserver have acces to all files from the home directory and could see or download the files.
I just want, that the User is restricted and could only see in stuff in his own directory, and he could not get above to the home.

I hope there is a way, and you guys could help me out.

Greetful, Hiraku

**Comment by UltimateByte** [comment]
`chmod 750` on risky files and dirs
You can apply this to your while home directory.
If you want more, you'll need to chroot users to their home dirs.
BTW, that's not a question to be answered on github since it doesn't help with LGSM development.
