### ISSUE TITLE
rustserver update fails

### ISSUE THREAD

**Issue by TooAwesomeForAcid** [GameServerManagers/LinuxGSM#1646]
Worked fine up until a few updates ago.

Running ./rustserver update on my ubuntu 16.04 server gets me the expected

Version x Found
Version y Available 

message and logs in to steamcmd to download the update. Steamcmd, however, returns "App x up to date" and the update cancels and server restarts. I currently get around this by manually logging into steamcmd and issuing the app_update command, which (I think) downloads the entire server again rather than just an update.

Is this a known issue or perhaps a configuration error on my end?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Update#validate

**Comment by TooAwesomeForAcid** [comment]
Did that the time before last...passed validation and still refused to update.

**Comment by dgibbs64** [comment]
First time I have come across this issue. A fresh install would be worth a try. Just backup your configs

**Comment by TooAwesomeForAcid** [comment]
![First Attempt](https://user-images.githubusercontent.com/26528617/31564269-d5afe16e-b027-11e7-9220-579b261fd6cb.png)

![Validate](https://user-images.githubusercontent.com/26528617/31564331-0ddcca8e-b028-11e7-9684-1e1ae92fc24d.png)

![Second attempt](https://user-images.githubusercontent.com/26528617/31564351-1e6be7c2-b028-11e7-8eed-858d6b31642a.png)

I'll try a full re-install and let you know if I have the same problem next week.

**Comment by UltimateByte** [comment]
No news + isolated issue. Closing.
