### ISSUE TITLE
[Server Request] Stellar Overload

### ISSUE THREAD

**Issue by Pigo04** [GameServerManagers/LinuxGSM#1653]
Hello,
I was wondering if it's possible to create the script to insert the Stellar OVerload game server (using SteamCMD).

Thanksq for all the work done, that's very usefull!

**Comment by dgibbs64** [comment]
https://steamdb.info/app/628300/

**Comment by h3o66** [comment]
This game does not seem to be available anymore.

More info can be found here:
https://steamcommunity.com/app/397150/discussions/0/3374780959379838491/

**Comment by Frisasky** [comment]
yeah seems this game is discontinued and no longer offered for sale, maybe we can close this server request for good
@dgibbs64
