### ISSUE TITLE
KF2 server - "Error! App '232130' state is 0x202 after update job."

### ISSUE THREAD

**Issue by Mr-N0x** [GameServerManagers/LinuxGSM#1656]
Hello!

First of all Thanks for this awesome an easy to use programm 👍 

I have a problem installing a KF2 server on my vServer. The vServer is running 64bit Debian 9 and is uptodate.
For some unknown reason steamCMD fails to download the KF2-Server app.
It shows the folowing error:
```
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0,00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0,00 (0 / 0)
Error! App '232130' state is 0x202 after update job.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/kf2server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
```
Please see the attached files for more details.
[kf2_failed_install_log.txt](https://github.com/GameServerManagers/LinuxGSM/files/1396244/kf2_failed_insall_log.txt)
[stderr.txt](https://github.com/GameServerManagers/LinuxGSM/files/1396251/stderr.txt)

Pleas excuse if it's my own stupidity.
Or could it be that the newest KF2 Update broke something?

**Comment by MarkL4YG** [comment]
According to a quick and dirty google search `0x202` is the code for `out of space` so I'd suggest checking if you've actually got enough disk space left

**Comment by Mr-N0x** [comment]
Holy shit. I'm so fucking retarted... I'm sorry. I thought I had enough space but the automatic install of the system made the "/" partition only 6GB big. Changing it now. 

Again I'm sorry.
