### ISSUE TITLE
Factorio Game Server: No update possible

### ISSUE THREAD

**Issue by freaky-m0** [GameServerManagers/LinuxGSM#1659]
I try to update my factorio server with `./fctrserver update` and only get `[ FAIL ] Update fctrserver: Checking for update: factorio.com: Not returning version info`

I already updated my scripts with `./fctrserver update-functions`:
```
[ .... ] Update LinuxGSM fctrserver: Updating LinuxGSM
    checking config _default.cfg...OK
    checking linuxgsm.sh...OK
    checking fctrserver...OK
    checking function alert.sh...OK
    checking function check_config.sh...OK
    checking function check_deps.sh...OK
    checking function check_executable.sh...OK
    checking function check_glibc.sh...OK
    checking function check_ip.sh...OK
    checking function check_logs.sh...OK
    checking function check_permissions.sh...OK
    checking function check_root.sh...OK
    checking function check.sh...OK
    checking function check_status.sh...OK
    checking function check_system_dir.sh...OK
    checking function check_system_requirements.sh...OK
    checking function check_tmuxception.sh...OK
    checking function command_install.sh...OK
    checking function command_monitor.sh...OK
    checking function command_restart.sh...OK
    checking function command_start.sh...OK
    checking function command_stop.sh...OK
    checking function command_update_linuxgsm.sh...OK
    checking function command_update.sh...OK
    checking function core_dl.sh...OK
    checking function core_exit.sh...OK
    checking function core_functions.sh...OK
    checking function core_getopt.sh...OK
    checking function core_legacy.sh...OK
    checking function core_messages.sh...OK
    checking function core_trap.sh...OK
    checking function fix.sh...OK
    checking function info_config.sh...OK
    checking function info_distro.sh...OK
    checking function info_glibc.sh...OK
    checking function install_complete.sh...OK
    checking function install_config.sh...OK
    checking function install_factorio_save.sh...OK
    checking function install_header.sh...OK
    checking function install_logs.sh...OK
    checking function install_server_dir.sh...OK
    checking function install_server_files.sh...OK
    checking function logs.sh...OK
    checking function update_factorio.sh...OK
[  OK  ] Update LinuxGSM fctrserver: Updating functions
```
Am i doing it wrong? Or is there something wrong with the factorio scripts?

**Comment by marvinlehmann** [comment]
I can't reproduce it on my end. :/ Which Factorio branch are you on? Could try running:

`echo $(curl -s https://www.factorio.com/download-headless/stable | grep 'headless/linux64' | head -n 1 | grep -oP '(?<=get-download/).*?(?=/)')`

`curl -s https://www.factorio.com/download-headless/stable`

Replace "stable" in the URLs if you are on a different branch.

Line in question: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/update_factorio.sh#L79

**Comment by freaky-m0** [comment]
I am on the "experimental" branch. Didn't play or update for a while. (Some month i guess.)

PD: [](https://hastebin.com/konibisuci)

`echo $(curl -s https://www.factorio.com/download-headless/stable | grep 'headless/linux64' | head -n 1 | grep -oP '(?<=get-download/).*?(?=/)')` >> 0.15.37

`curl -s https://www.factorio.com/download-headless/stable` >> [](https://hastebin.com/obuqesefil)

**Comment by marvinlehmann** [comment]
> Latest releases
> Stable: 0.15.37
> Experimental: None

Oh. That explains it, I think.

No download links listed on https://www.factorio.com/download-headless/experimental.

**Comment by freaky-m0** [comment]
Because they moved it to stable! Of course. I didn't realize that. Yes that explains it indeed. It was just confusing. 

Thank you ;)
