### ISSUE TITLE
Activating Addons on Arma3 Server

### ISSUE THREAD

**Issue by SethGecko28** [GameServerManagers/LinuxGSM#1660]
I have a problem with my Arma3 Server when i put Addons into the Config it won't activate them
The weird thing is online cba works and only if i put it first but the rest won't

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Personal server issues on Github will be closed without a kiss.

**Comment by MarkL4YG** [comment]
For game specific support ask in the corresponding games forums.
