### ISSUE TITLE
Discord Notification: Don't use private IP in discord notification

### ISSUE THREAD

**Issue by robobenklein** [GameServerManagers/LinuxGSM#1664]
https://github.com/GameServerManagers/LinuxGSM/blob/8b163a61c44f237ffb45fcb9cc4cd9cc237a73fd/lgsm/functions/alert_discord.sh#L42

Test environment: TF2 on Ubuntu server.

When on a server with multiple interfaces, we need to set the `ip` variable so that the source engine knows where to bind the port, but that's a local network IP address. (192.168.X.X or whatever the network might be)

In the discord notification, it then uses the private IP address, meaning it's useless to have a gameserver tracker link there at all; nobody but the ones inside the network can even know what the address is.

## Proposed workaround:
Allow custom variable to override `ip` variable.

Changes here:
```
"value": "[${ip}:${port}](https://www.gametracker.com/server_info/${ip}:${port})"
```
to
```
"value": "[${public_ip:-$ip}:${public_port:-$port}](https://www.gametracker.com/server_info/${public_ip:-$ip}:${public_port:-$port})"
```

Using `public_ip` and `public_port` if given allowing `ip` and `port` to be overridden if the router or network changes them in transit to the server.

I could submit a PR if needed, but this is such a small change I figured it wasn't that big a deal.

**Comment by dgibbs64** [comment]
I like this idea. Thanks

**Comment by gamersalpha** [comment]
same problem 

thanks

**Comment by dgibbs64** [comment]
LinuxGSM now has an internet ip variable. I think I will set it to this instead

**Comment by dgibbs64** [comment]
I will be altering the IP to use extip however some though does need to go in to all the possible variations of how IP addresses may change

**Comment by dgibbs64** [comment]
Updated this for other notifications as well
