### ISSUE TITLE
[Server Request] Unreal Tournament 4 

### ISSUE THREAD

**Issue by lblanchardiii** [GameServerManagers/LinuxGSM#1666]
Any chance of getting this supported by LGSM?

**Comment by UltimateByte** [comment]
Any chance to provide some docs/search results when making a request?

**Comment by lblanchardiii** [comment]
I sure can. 

Here is the wiki for Installing UT4 Server on Linux.
https://wiki.unrealengine.com/Servers_(Unreal_Tournament)#Step_1_Download_the_Server_2

Here is the download location since the other location requires special permissions on the forums.
https://www.epicgames.com/unrealtournament/blog/release-notes-june-28

Here is someone else's server script, but it's not as robust as LGSM.
https://www.epicgames.com/unrealtournament/forums/unreal-tournament-development/server-administration/9177-ddut4-linux-server-administration-deployment-suite

**Comment by dgibbs64** [comment]
I have looked at this in the past however the way UT4 works is a little more complex. I will however be looking in to this again 👍
