### ISSUE TITLE
Unable to connect to my CSGO server and its not even showing

### ISSUE THREAD

**Issue by salmanhasni** [GameServerManagers/LinuxGSM#1668]
I have 1 each vps over two different vendors 
VPS From Vendor A
VPS From Vendor B
from the vendor A, people are able to join my server.

```
csgoserver@csgoserver1:~$ netstat -atunp | grep srcds_linux
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 122.129.82.103:27015    0.0.0.0:*               LISTEN      15186/srcds_linux
udp        0      0 122.129.82.103:26901    0.0.0.0:*                           15186/srcds_linux
udp        0      0 122.129.82.103:27005    0.0.0.0:*                           15186/srcds_linux
udp        0      0 122.129.82.103:27015    0.0.0.0:*                           15186/srcds_linux
udp        0      0 122.129.82.103:27020    0.0.0.0:*                           15186/srcds_linux
```

where as from other vendor B i have the same config but people are not able to see my server 

```
csgoserver@server15261:~$ netstat -atunp | grep srcds_linux
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 195.229.192.53:27015    0.0.0.0:*               LISTEN      26759/srcds_linux
udp        0      0 195.229.192.53:27005    0.0.0.0:*                           26759/srcds_linux
udp        0      0 195.229.192.53:27015    0.0.0.0:*                           26759/srcds_linux
udp        0      0 195.229.192.53:27020    0.0.0.0:*                           26759/srcds_linux

```
I guess 26901 port is not able to bind in vendor B Vps, though i have did

```
sudo ufw allow 26901/tcp
sudo ufw allow 26901/udp
sudo ufw allow 26900/tcp
sudo ufw allow 26900/udp
```

Someone please help

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Personal server issues on Github will be closed without a kiss.

Since I'm kind today, I'll provide three advices:
1) Use details/postdetails commands to compare setup vs ports actually listening.
2) Check firewalls on your distro AND within your server provider interface (near IP settings at OVH for example)
3) Don't use github for personal issues.

**Comment by salmanhasni** [comment]
^ @UltimateByte Thanks anyway it worked.. somehow it was blocking my 27015 port, i change the server port to some other port and tada it worked.
