### ISSUE TITLE
Starting server from root but as user A makes graceful stopping to fail

### ISSUE THREAD

**Issue by Deepnoxious** [GameServerManagers/LinuxGSM#1670]
My rust server is under the user called A

Connected in terminal as user A, starting (`./rustserver start`) and then stopping it (`./rustserver stop`) makes the GRACEFUL stop method successful (`[  OK  ] Stopping rustserver: Graceful: CTRL+c: 2: OK`)

BUT

Connected as root, starting the server using this command (which is supposed to be ran as user A) (`sudo -u A /home/A/rustserver start`) makes the GRACEFUL stop method not working. (`[ERROR ] Stopping rustserver: Graceful: CTRL+c: FAIL`) (That graceful method not working will happen either connected in terminal as root or A because the server was started without being logged in the terminal as A)

The console notify me: 

> mkdir: cannot create directory ‘/root’: Permission denied
> cp: failed to access '/root/.steam/sdk32/steamclient.so': Permission denied

It seems like executing the command that has to run under the given user is trying to access /root/.steam/sdk32/steamclient.so WHICH DOES NOT EXIST. (Plus the user will NOT have the permission obviously, it makes no point to give it the permission)

Shouldn't it be using 

> /home/A/.steam/sdk32/steamclient.so

 instead?

**Comment by Scarsz** [comment]
Sounds more like a glitch in how SteamCMD parses the current directory.

**Comment by Deepnoxious** [comment]
I found something even more interesting.

```
root@server:~# sudo -u A /home/A/rustserver start
[ .... ] Starting rustserver: MY RUST SERVER  find: Failed to restore initial working directory: /root: Permission denied
find: Failed to restore initial working directory: /root: Permission denied
find: Failed to restore initial working directory: /root: Permission denied
find: Failed to restore initial working directory: /root: Permission denied
[ INFO ] Fix rustserver: Applying steamclient.so general fix: Rustmkdir: cannot   create directory ‘/root’: Permission denied
cp: failed to access '/root/.steam/sdk32/steamclient.so': Permission denied
[ERROR ] Fix rustserver: Applying steamclient.so general fix: Rust
find: Failed to restore initial working directory: /root: Permission denied
[  OK  ] Starting rustserver: MY RUST SERVER
root@server:~#
```
What do you think?

**Comment by MarkL4YG** [comment]
I think the same as @Scarz although we did not encounter such issues with garrys mod or arma

**Comment by Deepnoxious** [comment]
It seems like the problem is gone.
I used root for one command by mistake that's why.
Thanks for the input guys
