### ISSUE TITLE
Linuxgsm and bots 

### ISSUE THREAD

**Issue by Kevin242** [GameServerManagers/LinuxGSM#1671]
Hello,

First of all I want to say that the csgo server created by Linuxgsm is absolutely great. Everything works well, updates install perfectly and all is well except 1 thing :|
I cannot add more bots. It is always 8v8 on any map. If I install the default csgo server using the default steam tutorial I can play with as many bots as I want.

What can i do to get pass this error:"Could not add bot to the game, the game is full". I have tried eveything, I have set maximum players in al configurable files possible, I have added maxplayers_override to start, I have created aditional bot profiles, nothing works.

10x

**Comment by robobenklein** [comment]
It may be the server player limit (bots may still take player slots.)

Go take a look at the default config here" https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/csgoserver/_default.cfg

Notice this:
https://github.com/GameServerManagers/LinuxGSM/blob/659d24700132423f0caf67b60d32ab167cec7bf4/lgsm/config-default/config-lgsm/csgoserver/_default.cfg#L27

That would mean 8v8 is the max number of players, in your LGSM config, put `maxplayers="24"` or whatever you want it to be.

See [this wiki page](https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config-Files) for help with the configuration.
