### ISSUE TITLE
pzserver - Project Zomboid - Startup problem

### ISSUE THREAD

**Issue by Zmeja** [GameServerManagers/LinuxGSM#1672]
I am running Ubuntu 14.04.5 LTS.

Approx. 2 montsh ago i already ran a pzserver version 37.14 and everything worked fine.

Now. Having the new 38.22 patch things have changed.
First error was
`libstdc++.so.6: version `GLIBCXX_3.4.21' not found`
Even having the up-to-date Version of gcc it seems that Ubuntu 14.04 no longer hat 3.4.21 in the list.

After a bit of digging i added a repository so i could install gcc-4.7 which had all versions up to GLIBCXX_3.4.24
( ppa:ubuntu-toolchain-r/test )

However, i get another error now.
`java.lang.UnsatisfiedLinkError: /home/pzhc/serverfiles/natives/libZNetJNI64.so: /home/pzhc/serverfiles/natives/libZNetJNI64.so: symbol _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`
having it's set of errors beneath it. Server thus does not start up with the following ending error:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: zombie.core.znet.PortMapper._discover()V`
I am really out of ideas right now and would not mind a helping hand.

**Comment by dgibbs64** [comment]
Looking at this the simple fix is to update to Ubuntu 16.04. This will ensure you have the correct versions available. Game devs have a habit of updating there game requirements and not telling anyone and breaking servers :)

**Comment by Kallb123** [comment]
Is there no other fix? Your website still states Ubuntu 12.04+ as compatible, as well as glibc>=2.15, is that wrong now?

**Comment by dgibbs64** [comment]
A re-test of Oz server is required. Please raise a new issue

**Comment by dgibbs64** [comment]
#1918
