### ISSUE TITLE
Discord alerts failing for ut99server

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#1674]
When I use test-alert to check Discord alert functionality, I get this: ```[ FAIL ] Alert ut99-server: Sending Discord alert: {"code": 50006, "message": "Cannot send an empty message"}```

I followed the instructions at https://github.com/GameServerManagers/LinuxGSM/wiki/Discord to create the Webhook and updated the server script to enable Discord alerts, but it's not working as expected.

Any ideas?

**Comment by gamersalpha** [comment]
Hello yes 
try this : 

edit this files : 

`nano lgsm/config-lgsm/arkserver/common.cfg`

adding this line : 

`servername="ark-server-ubuntu"`

like this : 
https://gist.github.com/gamersalpha/f27370566023c21af16bf6cebfad434a


and now the that"s works :) 

`[  OK  ] Alert arkserver: Sending Discord alert`

i have the same error and i fix it like this

**Comment by jrmain** [comment]
@gamersalpha I tried something similar for the UT99 server, but it didn't seem to help. For your server, where did the value for servername come from?

**Comment by WarpKat** [comment]
I'm getting the same message.  I put the servername in the common.cfg and it still didn't work.

**Comment by WarpKat** [comment]
For the record, I have a UT2k4 server running on the same box and it sends Discord alerts just fine.

I also have a KF2 server on a separate box that sends Discord alerts just fine.

So there seems to be something different with the UT99 implementation.

**Comment by jrmain** [comment]
Confirmed that Discord alerts work fine with my UT2K4 server on the same box. Still not working for the UT99 server.

**Comment by UltimateByte** [comment]
Please, follow the minimum requirements to report an issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by jrmain** [comment]
**Game server:** UT99

**Postdetails** produces this:
```fetching command_postdetails.sh...OK
touch: cannot touch ‘’: No such file or directory
[ FAIL ] Postdetails ut99-server: Unable to create temporary file .
command_postdetails.sh exiting with code: 0
```

**Context:** trying to get Discord alerts working. Followed the instructions at https://github.com/GameServerManagers/LinuxGSM/wiki/Discord, which worked fine for UT2K4. Running the test-alert command produces this:

```[ WARN ] Alert ut99-server: More Info not enabled
[ FAIL ] Alert ut99-server: Sending Discord alert: {"code": 50006, "message": "Cannot send an empty message"}
[  OK  ] Alert ut99-server: Sending Email alert: operator@jrc-core.com
[ WARN ] Alert ut99-server: IFTTT alerts not enabled
[ WARN ] Alert ut99-server: Mailgun alerts not enabled
[ WARN ] Alert ut99-server: Pushbullet alerts not enabled
[ WARN ] Alert ut99-server: Pushover alerts not enabled
[ WARN ] Alert ut99-server: Telegram Messages not enabled
command_test_alert.sh exiting with code: 3
```

**Linux distro/version:** Ubuntu Linux 14.04.5

**Kernel info:** Linux foghorn 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Glibc version:** ldd (Ubuntu EGLIBC 2.19-0ubuntu6.13) 2.19

**TMux version:** tmux 2.0

**Log excerpts:** none that seem relevant

**Screenshot:** n/a

**Server hardware:** 
CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz, 8 cores
RAM: 8 GB
Storage: 450 GB
Bandwidth: 25 Mbps down; 5 Mbps up

**Tests tried:** I tried the fix suggested by gamersalpha above, but it didn't help.

**Comment by UltimateByte** [comment]
Thanks
"Unable to create temporary file" > Permission issue? Directory with spaces issues?
Can you please make sure that you eliminated these two possible sources of issues and try postdetails again?

**Comment by jrmain** [comment]
No directories with spaces in them. All the files are in /home/ut99server, everything runs as ut99server, and that user appears to have full permissions over all its files.

The 'details' command works fine, but I guess you would prefer a link to the postdetails output.

The tmp directory (/tmp/user/1010) is writeable.

It seems like maybe I'm missing some functionality related to posting information on the web. Or possibly the ut99server user needs additional permissions.

**Comment by jrmain** [comment]
The postdetails.sh script seems to be expecting postdetailslog to have a value, but I don't see it being set anywhere. My UT2K4 server's postdetails command does the same thing, by the way.

**Comment by UltimateByte** [comment]
Oh, maybe there is a bogus here, where a variable is missing for ut99, we need to check that out.

Awaiting for that, you can use the details command and manually post it to hastebin while masking off sensitive information, if any.

**Comment by jrmain** [comment]
https://hastebin.com/tapaqefube.sql

**Comment by UltimateByte** [comment]
Wondering... Is there any firewall?

**Comment by jrmain** [comment]
There are various firewalls and other security measures in place on the server and elsewhere. I suppose the Linux server's firewall could be configured to block traffic going from the server to Discord's API, but doesn't that traffic just look like web traffic? In any case, the UT2K4 server on the same machine doesn't have the same problem with Discord alerts. I get the feeling that there's a setting missing or misconfigured for the UT99 server.

**Comment by dgibbs64** [comment]
Made some fixes to both gamedig and also this 496ace3d0e992814473b1847414c31ef631001a0

The issue should be fixed on next release

**Comment by jrmain** [comment]
Confirmed fixed.

**Comment by TheByKotik** [comment]
Just find `/lgsm/functions/alert_discord.ph` and manually set:
```
{
	"name": "Server name",
	"value": "YOUR SERVERNAME"
},
```
