### ISSUE TITLE
Ubuntu 14.04 Won't Log, Empty Log files in /log/console/

### ISSUE THREAD

**Issue by medic917** [GameServerManagers/LinuxGSM#1677]
I migrated my server to Ubuntu 14.04 from Debian 7, and I run into this problem where my log files are empty and I think it is due to permissions. If you see my screenshot below, the permissions are 0664.
https://i.imgur.com/6huTGrg.png

I'm using an old version of this script that uses this snippet of code to write the log file. I have to use the old version since it is synced with my system for auto updates.

logdays="7"
gamelogdir="${systemdir}/logs"
scriptlogdir="${rootdir}/log/script"
consolelogdir="${rootdir}/log/console"

scriptlog="${scriptlogdir}/${servicename}-script.log"
consolelog="${consolelogdir}/${servicename}-console.log"
emaillog="${scriptlogdir}/${servicename}-email.log"

scriptlogdate="${scriptlogdir}/${servicename}-script-$(date '+%d-%m-%Y-%H-%M-%S').log"
consolelogdate="${consolelogdir}/${servicename}-console-$(date '+%d-%m-%Y-%H-%M-%S').log"

fn_scriptlog(){
	echo -e "$(date '+%b %d %H:%M:%S') ${servicename}: ${1}" >> ${scriptlog}
}

Do you think it is due to permissions issue? Notice how in the screenshot there is no default tf2-server-console.log file, just a bunch of empty ones being created. Usually the most recent log will have no dates on it, but on my new ubuntu server, it doesnt even exist.

The server script runs fine, it's just the logging that is having issues.

**Comment by MarkL4YG** [comment]
If this is a permissions issue you need to check the permissions of the log directory so you know if lgsm is even allowed to create files and directories.

**Comment by medic917** [comment]
Forgot to mention that I tried changing the permissions to directory, but the files keep writing as 0664 no matter what I try. I'm on ubuntu 14.04 so perhaps I'm missing something? Is there a root command that I should be using? I usually just use my WinSCP gui to change permissions of directories.

**Comment by MarkL4YG** [comment]
0664 is perfectly fine for log files. The default file permissions are defined by the ``umask`` (just in case you wanna google that).

Verify that the log folder also has at least 66x set as its permissions.

**Comment by UltimateByte** [comment]
If you watch the FAQ, you learn that tmux lower than 1.6 or equal to 1.8 has no logging.
https://github.com/GameServerManagers/LinuxGSM/wiki/Tmux

No relevant info, no support.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Also user support isn't done on github anyways.
