### ISSUE TITLE
[Can't Update Servers, Need Help]  CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: X items discarded

### ISSUE THREAD

**Issue by medic917** [GameServerManagers/LinuxGSM#1678]
I can't seem to update my servers properly after Pyro update for tf2.
After the update loads, the error pops up  CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: X items discarded

I tried creating a shell for my user, but it still comes up.
chsh -s /bin/bash tf2server

Any idea what is causing this? It's keeping me from updating my server. I thought it was HD space at first, but after moving it to a large HD space, it still happens.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
