### ISSUE TITLE
Can join my ark cluster, but can't take data with me. 

### ISSUE THREAD

**Issue by EmpCorvinus** [GameServerManagers/LinuxGSM#1679]
Alright, so I will get to the point. I am running an ark cluster on different blades. 4 to be exact, with a 5th when aberration comes out. The cluster ID is the same, etc. When I spawn, and go to the obby, or drop. I am able to go to the other servers. However, I can't take my characters, dinos, or items with me. All of the prevents are false, and notributedownloads is also false. 

./ShooterGameServer "TheIsland?listen?MultiHome=192.168.1.191?MaxPlayers=70?Quer                 yPort=37015?RCONPort=27020?Port=7777?AltSaveDirectoryName=Save1? -automanagemods                   -UseBattleEye -NoTransferFromFiltering -clusterid=cluster1538976120 

./ShooterGameServer "TheCenter?listen?MultiHome=192.168.1.191?MaxPlayers=70?Quer                         yPort=37016?RCONPort=27021?Port=7779?AltSaveDirectoryName=Save2? -automanagemods -UseBattleEye -NoTransferFromFiltering -clusterid=cluster1538976120 

Any ideas? I am at this point completely lost.

**Comment by MarkL4YG** [comment]
Personal configuration problems do not belong into the LGSM issues. Please read the rules before posting.
Ask in an Ark-Server forum.
