### ISSUE TITLE
Discord Message not working - [ FAIL ] Alert arkserver: Sending Discord alert: {"embeds": ["0"]}

### ISSUE THREAD

**Issue by gamersalpha** [GameServerManagers/LinuxGSM#1680]
Hello, 

well i m starting a server Linux with LinuxGSM and i using Discord, so i add my discord conf like u says here -- > https://github.com/GameServerManagers/LinuxGSM/wiki/Discord

i put the configuration on my config files : 

` nano /home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg`

```
# Discord Alerts | https://github.com/GameServerManagers/LinuxGSM/wiki/Discord
discordalert="on"
discordwebhook="https://discordapp.com/XXXXXXXXXXXXXXXX"
```

so when i lunch my server and i try a test : 

i have this error :

```
arkserver@ubuntu:~$ ./arkserver ta
[ WARN ] Alert arkserver: More Info not enabled
[ FAIL ] Alert arkserver: Sending Discord alert: {"embeds": ["0"]}
[ WARN ] Alert arkserver: Email alerts not enabled
[ WARN ] Alert arkserver: IFTTT alerts not enabled
[ WARN ] Alert arkserver: Mailgun alerts not enabled
[ WARN ] Alert arkserver: Pushbullet alerts not enabled
[ WARN ] Alert arkserver: Pushover alerts not enabled
[ WARN ] Alert arkserver: Telegram Messages not enabled
```

what do u think is wrong please ?

**Comment by ychoucha** [comment]
Anyone have suggestion please

**Comment by gamersalpha** [comment]
i activate the dev log and i see this : 


`arkserver@ubuntu:~$ ./arkserver ta
[ WARN ] Alert arkserver: More Info not enabled
[ FAIL ] Alert arkserver: Sending Discord alert: {"embeds": ["0"]}
[ WARN ] Alert arkserver: Email alerts not enabled
[ WARN ] Alert arkserver: IFTTT alerts not enabled
[ WARN ] Alert arkserver: Mailgun alerts not enabled
[ WARN ] Alert arkserver: Pushbullet alerts not enabled
[ WARN ] Alert arkserver: Pushover alerts not enabled
[ WARN ] Alert arkserver: Telegram Messages not enabled

command_test_alert.sh exiting with code: 3
arkserver@ubuntu:~$ tail -f dev-debug.log
+++++ '[' -n ALERT ']'
++++++ date '+%b %d %H:%M:%S.%3N'
+++++ echo -e 'nov. 06 20:16:46.936 arkserver: ALERT: WARN: command_test_alert.sh exiting with code: 3'
+++++ exitcode=3
+++++ fn_exit_dev_debug
+++++ '[' -f /home/arkserver/.dev-debug ']'
+++++ echo ''
+++++ echo 'command_test_alert.sh exiting with code: 3'
+++++ trap - INT
+++++ exit 3
`

**Comment by gamersalpha** [comment]
ok i found a solution : 

edit this files : 

`nano lgsm/config-lgsm/arkserver/common.cfg`

adding this line : 

`servername="ark-server-ubuntu"`

like this : 
https://gist.github.com/gamersalpha/f27370566023c21af16bf6cebfad434a


and now the that"s works :) 

`[  OK  ] Alert arkserver: Sending Discord alert`

**Comment by dgibbs64** [comment]
I think I may of resolved this issue my improving sed to remove carriage returns. This will be in the next release. If it is still an issue please raise a new issue. Thanks for reporting :D

**Comment by gamersalpha** [comment]
Hello, 
i make a new frech install today on, a ubuntu 18.04
and this bug is still here !!!!

**Comment by dgibbs64** [comment]
@gamersalpha I haven't completed the next release yet!!!

**Comment by gamersalpha** [comment]
and i still have not all good information send to discord : 

![image](https://user-images.githubusercontent.com/32466950/41510025-c2488790-725d-11e8-9856-76105f1a9835.png)

missing the IP, is not the good serveur ip

**Comment by SaintofDiablo** [comment]
i am also having this issue

**Comment by JunTVDE** [comment]
me too
