### ISSUE TITLE
Oxide for 7 days to die

### ISSUE THREAD

**Issue by GeneralDenmark** [GameServerManagers/LinuxGSM#1681]
When using the "mods-install" command on the sdtdserver, and trying to install oxide (more specifically sdtdoxide) it returns a 404 error for curl

```
Installing Oxide for 7 Days To Die
=================================
clearing mod download directory /home/gendk/Steam_servers/lgsm/mods/tmp...OK
creating mod download directory /home/gendk/Steam_servers/lgsm/mods/tmp...OK
downloading Oxide-SevenDays.zip...
curl: (22) The requested URL returned error: 404 Not Found
downloading Oxide-SevenDays.zip...OK
Failure! An issue occurred downloading Oxide for 7 Days To Die
```

**Comment by DobriyDed** [comment]
Thats just a filename error
correct is Oxide-SevenDaysToDie.zip , instead of Oxide-SevenDays.zip

**Comment by UltimateByte** [comment]
So they changed the file name.
Thanks for your contribution.

**Comment by Bourne-ID** [comment]
#1682 fixes this....

**Comment by UltimateByte** [comment]
That wasn't ironic, and I saw your PR already ;)
@dgibbs64 will probably merge it soon
