### ISSUE TITLE
Error! App '740' state is 0x202 after update job.

### ISSUE THREAD

**Issue by m0uka** [GameServerManagers/LinuxGSM#1684]
Hello, i am having problem with this. When i want to install the server i get this error. I have free space.

Hastebin here:
https://hastebin.com/ivipovadup

**Comment by Bourne-ID** [comment]
I beg to differ:
```Storage
=================================
Filesystem:      /dev/vda2
Total:           9.6G
Used:            1.4G
Available:       7.7G
LinuxGSM Total:  68M
Serverfiles:     40K
```

States you have 7.7GB remaining. Last check CS GO dedicated server was around 17GB. 

Error 0x202 is accurate, or you have misconfigured your installation to use the wrong drive.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by m0uka** [comment]
Oh sorry! I didn't know it takes so much. I will be upgrading and sorry for wasting your time

**Comment by UltimateByte** [comment]
That's OK ;)

**Comment by BloodyIron** [comment]
> States you have 7.7GB remaining. Last check CS GO dedicated server was around 17GB.

THANK YOU. I was trying to identify this error with 15GB of free space, and giving it more worked...

WHY DON'T THEY USE HUMAN LEGIBLE ERRORS?

**Comment by b3none** [comment]
Because... valve. :joy:

**Comment by BloodyIron** [comment]
Hmmm, seems the game needs EVEN MORE space! Getting the error again, yay!

**Comment by BloodyIron** [comment]
Okay now I'm getting "Error! App '740' state is 0x50A'! And re-downloading it won't fix it :( Plenty of free space too! ARGH
