### ISSUE TITLE
UFW and CSGO server connection with steam servers can't established

### ISSUE THREAD

**Issue by Shadowgr** [GameServerManagers/LinuxGSM#1686]
Hello there,

Distro:    Debian GNU/Linux 8.9 (jessie)
Arch:      x86_64
Kernel:    3.16.0-4-amd64

I have opened many ports to should work properly.

Specifically, follow this guide: https://support.steampowered.com/kb_article.php?ref=8571-GLVN-8711

It's not a home server, I setup already public ip in lgsm-config/common.cfg 

Beyond that, I read about other solutions that unfortunately didn't solves my problem. When activate UFW and type: ./csgoserver restart says: Could not establish connection to Steam servers.

If disable UFW and run server again connected without any problem.

So, it's firewall problem in any case..

Any solution to help for running csgo server with UFW enabled ?

**Comment by UltimateByte** [comment]
`./csgoserver details`

will provide you with the used ports, and will provide you with a netstat command to see what ports are listening.... Will help diagnosing what ports to open.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
