### ISSUE TITLE
GmodServer can't start

### ISSUE THREAD

**Issue by FullDarkness19** [GameServerManagers/LinuxGSM#1688]
Hello, 

When i'm launch my server i have this error

http://prntscr.com/h8dg94

Yoan.

**Comment by FullDarkness19** [comment]
My server os is Debian 9

**Comment by UltimateByte** [comment]
Not the place for that + lacks details.

I'll be nice since I have a guess

```
apt install locales
dpkg-reconfigure locales
```
Select an UTF8 english language.

https://github.com/GameServerManagers/LinuxGSM/wiki/Support
