### ISSUE TITLE
Rust server only starts in debug mode

### ISSUE THREAD

**Issue by Wazbat** [GameServerManagers/LinuxGSM#1689]
When starting the server using ./rustserver start it simply closes itself after about a minute, checking the log shows it starts normally, ending with EAC closing.

Log file from a normal start: http://termbin.com/n138

When started using ./rustserver debug it starts perfectly fine

**Comment by UltimateByte** [comment]
Sorry, not the place for that + lacks details anyways.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Wazbat** [comment]
Sorry for that. Thanks for linking that page
