### ISSUE TITLE
Rust seed is not being used

### ISSUE THREAD

**Issue by pavelhoral** [GameServerManagers/LinuxGSM#1691]
Bug: unable to set seed

Reason: There is a special logic for handling `seed` parameter in [_default.cfg](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/rustserver/_default.cfg#L32) which processes this parameter to `conditionalseed` variable. However this processing is done before any custom config can be loaded. This IF statement needs to be part of `fn_params` function.

**Comment by UltimateByte** [comment]
You're right, this `if` statement should be before `parms=""` because, I believe, the `parms` variable is defined upon running `fn_parms`, and while we could put this `if` statement right before `fn_parms`, this could lead to users mistakes due to the new config files system.

So here is the correction to bring:

```bash
## Server Start Command | https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters#additional-parameters
fn_parms(){
# Specific to Rust
if [ -n "${seed}" ]; then
	# If set, then add to start parms
	conditionalseed="+server.seed ${seed}"
else
	# Keep randomness of the number if not set
	conditionalseed=""
fi
parms="-batchmode +server.ip ${ip} +server.port ${port} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${servicename}\" ${conditionalseed} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile \"${gamelogdate}\""
}
```

**Comment by pavelhoral** [comment]
Thanky you for looking into this. 

If anyone would be interested in a quick workaround, it is possible to have the following line in instance cfg:

    seed=123456
    conditionalseed="+server.seed ${seed}" # This is the actual workaround
