### ISSUE TITLE
No LogFiles

### ISSUE THREAD

**Issue by Shirobaka** [GameServerManagers/LinuxGSM#1692]
Hey,
since a few days my server won't create logs, this happens not all the time, but even then, its pretty annoying.
I checked the FAQ and saw that there were problems with tmux 1.8 and that 1.6 is needed at least, i use version 1.9 and i'm not sure if the issues that are shown in version 1.8 is still here...
The permissions are checked, they are ok.

GameServer: ArmA 3
Details: https://hastebin.com/evaheqofoc
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2,20 GHz
Ram: 32GB
Storage: 200GB SSD
Bandwidth: 1Gbit

**Comment by UltimateByte** [comment]
Hi,

Does Arma have a console output?
To know that : Do you see console outputs when starting with debug command?

**Comment by Shirobaka** [comment]
The last 2 weeks it works without any problems, so i think i'll keep an eye of this and will post again when this problem shows again.

**Comment by UltimateByte** [comment]
Well, let's consider it solved. Thanks for the feedback.
