### ISSUE TITLE
[Install] Used chmod/chown to assign folders to server user account; access still denied

### ISSUE THREAD

**Issue by ReverendV92** [GameServerManagers/LinuxGSM#1693]
Have never used Linux at all before after 20+ years of Windows use, so this is a pretty big culture shock, so bear with me.

I'm trying to install the GMod server version. I followed the guide, down to the part where I have to use this command as the gmodserver user:
`wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh gmodserver`

I got 'access denied' so I googled it, got a bunch of previous issues here all related to the folder not being inherently owned by the gmodserver user. Found a previous answer that listed this as the command to give ownership to the user:
`chown -R gmodserver:gmodserver /home/gmodserver`

Ran that command as root. As seems to be the Linux way, no feedback on whether or not it worked. Then I ran:
`su gmodserver`

To sudo back into the server account. Ran the install command again and had the same result.

Is there something I'm doing wrong? I'm completely lost on how to use this OS.

**Comment by MarkL4YG** [comment]
First: The LGSM issues are __not__ for personal issues. Please read the wiki first.

Secondly: Additionally to owning the folder the user "gmodserver" may also need to have write-access to that folder. Assuming you're using linux standarts that would meen you'll need to verify if your ``/home/gmodserver`` folder is owned by ``gmodserver:gmodserver`` and has his permissions set to at least ``700``.

Personally I'd also recommend using ``sudo -iu <user>`` to change user from/to root instead of just ``su``.

**Comment by ReverendV92** [comment]
I apologise for my mistake then. I read the wiki, but as someone who has absolutely 0 experience in a Unix environment, I'm in way over my head here. I don't know how to verify if gmodserver owns the folder. Nor do I understand the syntaxical reason for username:username, what it means to have or how a permission level is set to >=700, or know what the difference between sudo and su are as I don't know what either of them do.At this point I'm considering ditching Linux altogether and finding a host that supports Windows for the sake of my own sanity.-- Sent from Mobile12:11, November 13, 2017, "Magnus Leßmann (aka. mark332)" <notifications@github.com>:First: The LGSM issues are not for personal issues. Please read the wiki first.Secondly: Additionally to owning the folder the user "gmodserver" may also need to have write-access to that folder. Assuming you're using linux standarts that would meen you'll need to verify if your /home/gmodserver folder is owned by gmodserver:gmodserver and has his permissions set to at least 700.Personally I'd also recommend using sudo -iu <user> to change user from/to root instead of just su.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by UltimateByte** [comment]
Welcome to Linux. Hopefully the experience will be as rich for you as it was for me!

>  I don't know what either of them do.

Protip: 
`ls -l /path/to/dir/or/file`  
Will display files and their permissions and ownership.

Protip 2: 
`ls -laltr /path/to/dir/or/file`  
Will do the same but sort the output with the latest modified last.

`chmod -R 755 /home/gmodserver`
Will probably solve your issue, even though I don't see why and how you would have fucked up your permissions on a brand new user.
Also, maybe make sure your user's has access to bash or is not chrooted in a bad way. If you created your user with `adduser` and did nothing fancy, I don't see how it would fail on a simple wget.

If LGSM makes life easier for admins, it doesn't prevent them from doing your homework and know at least the basics about Linux before getting into it. You need to try and fucking a bunch of Linux installs before even thinking to put a service on production. You need to know the basics, like managing users, managing permissions... or checking files and permissions. hm.

But github is for development, not for personal support. 
We have other ways to provide support, check
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

And also read carefully all the documentation.
