### ISSUE TITLE
[CS:GO] 128 tick problem

### ISSUE THREAD

**Issue by Aiatzu** [GameServerManagers/LinuxGSM#1694]
**On my csgoserver.cfg I've set the tick rate to 128 but when joining the server the tick rate is still 64.
Details of my server:**

---------------------------------------------
Distro:    Ubuntu 17.10
Arch:      x86_64
Kernel:    4.13.0-16-generic
Hostname:  xxxxxxxxxxxxxxxxxxx

Performance
Uptime:    0d, 5h, 1m
Avg Load:  0.08, 0.12, 0.06

Mem:       total   used   free   cached
Physical:  5.8G   414M   4.9G   21M
Swap:      2.0G   6.8M   2.0G

Storage
======================================================================================================
Filesystem:      /dev/sda2
Total:           491G
Used:            22G
Available:       445G
LinuxGSM Total:  18G
Serverfiles:     16G

Counter-Strike: Global Offensive Server Details
======================================================================================================
Server name:      xxxxxxxxxxxxxxxxxxxxxx
Server IP:        xxxxxxxxxxxxxxxxxxxxx
Server password:  NOT SET
RCON password:    xxxxxxxxxxxxxxxxxxxxxx
Maxplayers:       24
Game mode:        1
Tick rate:        128
Status:           ONLINE

csgoserver Script Details
======================================================================================================
Service name:           csgoserver
csgoserver version:     171014
User:                   csgoserver
GLIBC required:         2.15
Discord alert:          off
Email alert:            off
Pushbullet alert:       off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushover alert:         off
Telegram alert:         off
Update on start:        off
Location:               /home/csgoserver
Config file:            /home/csgoserver/serverfiles/csgo/cfg/csgoserver.cfg

Backups
======================================================================================================
No Backups created

Command-line Parameters
======================================================================================================
./srcds_run -game csgo -usercon -strictportbind -ip xxxxxxxxxx -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount xxxxxxxxxx -tickrate 128 +map de_dust2 +servercfgfile csgoserver.cfg -maxplayers_override 24 +mapgroup mg_active +game_mode 1 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey  -nobreakpad

Ports
======================================================================================================
Change ports by editing the parameters in:
csgoserver

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

Status: ONLINE

**Comment by rsgua** [comment]
How you know that you tick 64?
Do know that you must write cvars?
My cfg (write in sourcemod.cfg)
sm_cvar sv_maxrate 0
sm_cvar sv_minrate 196608
sm_cvar sv_maxcmdrate 128
sm_cvar sv_mincmdrate 128
sm_cvar sv_maxupdaterate 128
sm_cvar sv_minupdaterate 128

**Comment by Aiatzu** [comment]
@rsgua 
Thank you very much, my man!
It finally works!
