### ISSUE TITLE
CSGO SERVER install Issue, Serverlist.csv...FAIL

### ISSUE THREAD

**Issue by GeorgKoppel** [GameServerManagers/LinuxGSM#1696]
![image](https://user-images.githubusercontent.com/18694585/32828509-f9964098-c9f7-11e7-8d93-ed9bac5c8c81.png)

Issue is simple, but how to fix?

**Comment by Bourne-ID** [comment]
You need to run the dependency commands to install 'curl'. Depending if you're running x64 or x32 you need to copy and run the relevant commands ![here](https://i.imgur.com/CTddYVc.jpg)

Also: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
