### ISSUE TITLE
STEAM CMD did not complate download! Attempt 6

### ISSUE THREAD

**Issue by GeorgKoppel** [GameServerManagers/LinuxGSM#1697]
![image](https://user-images.githubusercontent.com/18694585/32832160-389ac484-ca03-11e7-91e4-fbc18240f59a.png)

How to fix. Csgoserver...

**Comment by Khelgar1** [comment]
`df -h`
You're probably out of space

**Comment by GeorgKoppel** [comment]
![image](https://user-images.githubusercontent.com/18694585/32833411-7f8086fa-ca07-11e7-8617-35dd971f2791.png)
@Khelgar1

**Comment by Bourne-ID** [comment]
CS GO dedicated server is ~16-17GB, that's saying you have 7GB. 

Also, I linked this in your previous issue #1696 - have a read of the support wiki and where general server support queries should go:  https://github.com/GameServerManagers/LinuxGSM/wiki/Support#general-support

**Comment by Khelgar1** [comment]
You only have 6.9GB free, think CSGO needs 12-16GB. I don't run it so can't check for sure

**Comment by GeorgKoppel** [comment]
Okei thanks!
