### ISSUE TITLE
Multiple csgo servers

### ISSUE THREAD

**Issue by dzinks2009** [GameServerManagers/LinuxGSM#1700]
Hello, if I want to run multiple csgo servers,  do I need folders like /home/user/arena, /home/user/dd2, etc with steam and serverfiles in them or can I use the same steamcmd for all of them?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by dzinks2009** [comment]
That doesnt answer my question tho

**Comment by UltimateByte** [comment]
SteamCMD is managed by LGSM, you don't need to worry about it.
For obvious simplicity reasons, there is one SteamCMD per server, until we use the Linux SteamCMD package.

**Comment by MarkL4YG** [comment]
Generally you don't need to create multiple folders. There are cases like Garrys Mod where not using multiple folders will result in overly complicated configuration and server management as Garrys Mod (for example) has some paths hard-coded which will overlap with the other instances.
