### ISSUE TITLE
Cs 1.6 don't start...

### ISSUE THREAD

**Issue by Owned67** [GameServerManagers/LinuxGSM#1701]
> FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad

> ./serverfiles/libsteam_api.so

OS: Ubuntu 17.04 (GNU/Linux 4.10.0-38-generic x86_64)

` ./csserver debug
    fetching command_debug.sh...OK

 Counter-Strike 1.6 Debug
 =================================

 Distro: Ubuntu 17.04
 Arch:   x86_64
 Kernel: 4.10.0-38-generic
 Hostname:       ubuntu
 tmux:   tmux 2.3
 Avg Load:       0,42, 0,31, 0,27
 Free Memory:    188M
 Free Disk:      88G
 GLIBC required: 2.3.4
 Server IP:      192.168.1.22:27020
 Internet IP:    XXXXXXXX:27020
 Server password:        NOT SET

 Start parameters:
 ./hlds_run -game cstrike -strictportbind +ip 192.168.1.22 -port 27020 +clientport 27020 +map de_dust2 
 +servercfgfile csserver.cfg -maxplayers 16 -debug`

` free -mt
              total        used        free      shared  buff/cache   available
Mem:           1997         473         190          32        1332        1305
Swap:          2047           0        2047
Total:         4045         473        2238
`

`./csserver v`

>    fetching command_validate.sh...OK
 [ .... ] Validate csserver: Validating files: SteamCMD
        * Validating may overwrite some customised files.
        * https://developer.valvesoftware.com/wiki/SteamCMD#Validate
 Redirecting stderr to '/home/eric/Steam/logs/stderr.txt'
 [  0%] Checking for available updates...
 [----] Verifying installation...
 Steam Console Client (c) Valve Corporation
 -- type 'quit' to exit --
 Loading Steam API...OK.

 Connecting anonymously to Steam Public...Logged in OK
 Waiting for user info...OK
 [  OK  ] Validate csserver: Validating files: SteamCMD

edit: I have see https://github.com/GameServerManagers/LinuxGSM/issues/1450#issuecomment-306038994

now i get 

> Error:libsteam_api.so: cannot open shared object file: No such file or directory
Unable to load engine, image is corrupt.

`find . -name libsteam_api.so`

> ./libsteam_api.so

**Comment by Grimston** [comment]
I have used this before and had a working system, of course, no guarantee of working for you.

```BASH
/home/csserver/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/csserver/serverfiles +app_update 90 validate +quit
/home/csserver/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/csserver/serverfiles +app_update 70 validate +quit
/home/csserver/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/csserver/serverfiles +app_update 10 validate +quit
/home/csserver/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/csserver/serverfiles +app_update 90 validate +quit
```

It's because valve brought a bug back from the dead, a fix was added to LGSM to deal with it.

70 is half-life this WILL fail to install but it will set up the file list for the CS 1.6 server.
10 is the dedicated server, which is also required for CS 1.6 to run.

After all that the final update for 90 (CS 1.6) the game will reconfigure and then install the rest of the server.

**Comment by Owned67** [comment]
Very thanks, work fine!!!
