### ISSUE TITLE
Natural Selection 2 Server

### ISSUE THREAD

**Issue by JohnvanWaYnE** [GameServerManagers/LinuxGSM#1704]
I#ve got this Problem when i try to run the server:

[ FAIL ] Starting ns2server: Executable was not found:
 * /home/ns2server/serverfiles/server_linux32

and there isnt any folder like this on my system.

**Comment by UltimateByte** [comment]
Follow this
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting#start-issues

Then if you really think this is an issue due to LGSM, re-open the issue and follow the issue guidance from here:
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Tex42** [comment]
### Which game server you are running:
Natural Selection 2

### The outputted link of ./gameserver postdetails command:
https://hastebin.com/sikucixaxi

### The context of your error and the exact outputs.:
[ FAIL ] Starting ns2server: Executable was not found:
 * /home/ns2server/serverfiles/server_linux32

### Your Linux distro and version:
Ubuntu 17.10 x64

### Your kernel information:
Linux Ubuntu-1710-artful-64-minimal 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Your versions for glibc:
Ubuntu GLIBC 2.26-0ubuntu2 2.26
tmux 2.5

### Comment:
This is a clean new server so it seems like LGSM is using the wrong executable.

**Comment by UltimateByte** [comment]
Ref https://github.com/GameServerManagers/LinuxGSM/issues/1723
