### ISSUE TITLE
Host_Error: WatchdogHandler called - server exiting, but not restarting

### ISSUE THREAD

**Issue by diamondburned** [GameServerManagers/LinuxGSM#1705]
From script log: https://pastebin.com/Me7bbfuC
From server: https://pastebin.com/NzsmN2sg
From log file: https://pastebin.com/294fmvgF

In the file:
>WatchDog! Server took too long to process (probably infinite loop).
>Host_Error: WatchdogHandler called - server exiting.

The server, however, didn't restart. What can I do to make it autorestart?

**Comment by UltimateByte** [comment]
I have no idea what you are talking about (no context at all... come on), but you for sure didn't follow the support guidance.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by MarkL4YG** [comment]
You may use server monitoring for that. But I don't think LGSM has a feature for automatic restarts upon crashes.

You better fix the cause of the issue not the symptom.

**Comment by diamondburned** [comment]
I really can't, the nature of the gamemode is already bad enough. Although my server can handle it, sometimes it would just hit the 2048 edicts limit (Team Fortress 2 btw, oops), and the server dies. Tried a few edicts restarting plugin, but it didn't work.

**Comment by diamondburned** [comment]
Update1: Problem still isn't fixed, even with `./tf2server monitor` inside crontab, running every 2 minutes

WatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.

**Comment by Nealcaffrey2016** [comment]
It seems that the server program code has a bug,which cause you change to much will cause a element excessive the size signed to it,cause a memory error.




Sent from Neal Caffrey
On 11/23/2017 06:44, diamondburned wrote:

From script log:
Nov 22 11:00:03.323 tf2server: CHECK: INFO: Using anonymous Steam login Nov 22 11:00:04.337 tf2server: UPDATE: INFO: Checking for update: Server logs Nov 22 11:00:06.400 tf2server: UPDATE: INFO: Checking for update: SteamCMD Nov 22 11:00:13.808 tf2server: UPDATE: PASS: Checking for update: SteamCMD Nov 22 11:00:14.810 tf2server: UPDATE: PASS: Checking for update: SteamCMD: No update available Nov 22 11:00:14.811 tf2server: UPDATE: INFO: Current build: 2294876 Nov 22 11:00:14.812 tf2server: UPDATE: INFO: Available build: 2294876 Nov 22 11:00:14.825 tf2server: UPDATE: PASS: command_update.sh exiting with code: 0 Nov 22 11:30:04.193 tf2server: CHECK: INFO: Using anonymous Steam login Nov 22 11:30:05.214 tf2server: UPDATE: INFO: Checking for update: Server logs Nov 22 11:30:07.368 tf2server: UPDATE: INFO: Checking for update: SteamCMD Nov 22 11:30:14.598 tf2server: UPDATE: PASS: Checking for update: SteamCMD Nov 22 11:30:15.610 tf2server: UPDATE: PASS: Checking for update: SteamCMD: No update available Nov 22 11:30:15.611 tf2server: UPDATE: INFO: Current build: 2294876 Nov 22 11:30:15.612 tf2server: UPDATE: INFO: Available build: 2294876 Nov 22 11:30:15.618 tf2server: UPDATE: PASS: command_update.sh exiting with code: 0

From server:
L 11/22/2017 - 11:04:21: "Richardo<133><[U:1:377627119]><>" entered the game L 11/22/2017 - 11:04:24: "george.maddox.whitlock<129><[U:1:455777988]><Blue>" changed role to "soldier" L 11/22/2017 - 11:04:36: "Richardo<133><[U:1:377627119]><Unassigned>" joined team "Red" L 11/22/2017 - 11:04:38: "Richardo<133><[U:1:377627119]><Red>" changed role to "scout" L 11/22/2017 - 11:04:58: "Richardo<133><[U:1:377627119]><Red>" changed role to "heavyweapons" L 11/22/2017 - 11:05:14: "Richardo<133><[U:1:377627119]><Red>" changed role to "pyro" L 11/22/2017 - 11:05:14: "Richardo<133><[U:1:377627119]><Red>" committed suicide with "world" (attacker_position "-439 12174 256") L 11/22/2017 - 11:05:15: "Richardo<133><[U:1:377627119]><Red>" changed role to "heavyweapons" L 11/22/2017 - 11:05:27: "Richardo<133><[U:1:377627119]><Red>" changed role to "soldier" L 11/22/2017 - 11:05:44: "Richardo<133><[U:1:377627119]><Red>" triggered "flagevent" (event "defended") (p
From log file:
`*** ERROR *** Excessive sizelevel (1073) for element
*** ERROR *** Excessive sizelevel (1074) for element
*** ERROR *** Excessive sizelevel (1075) for element
*** ERROR *** Excessive sizelevel (1076) for element
*** ERROR *** Excessive sizelevel (1077) for element
*** ERROR *** Excessive sizelevel (1078) for element
*** ERROR *** Excessive sizelevel (1079) for element
*** ERROR *** Excessive sizelevel (1080) for element
*** ERROR *** Excessive sizelevel (1081) for element
*** ERROR *** Excessive sizelevel (1082) for element
*** ERROR *** Excessive sizelevel (1083) for element
*** ERROR *** Excessive sizelevel (1084) for element
*** ERROR *** Excessive sizelevel (1085) for element
*** ERROR *** Excessive sizelevel (1086) for element
*** ERROR *** Excessive sizelevel (1087) for element
*** ERROR *** Excessive sizelevel (1088) for element
*** ERROR *** Excessive sizelevel (1089) for element
*** ERROR *** Excessive sizelevel (1090) for element
*** ERROR *** Excessive sizelevel (1091) for element
*** ERROR *** Excessive sizelevel (1092) for element
*** ERROR *** Excessive sizelevel (1093) for element
*** ERROR *** Excessive sizelevel (1094) for element
*** ERROR *** Excessive sizelevel (1095) for element
*** ERROR *** Excessive sizelevel (1096) for element
*** ERROR *** Excessive sizelevel (1097) for element
Ignoring unreasonable position (-183.861755,13073.099609,-16385.429688) from vphysics! (entity tf_dropped_weapon)
*** ERROR *** Excessive sizelevel (1098) for element
Ignoring unreasonable position (-190.611633,13078.674805,-26354.783203) from vphysics! (entity tf_dropped_weapon)
L 11/22/2017 - 11:06:01: "george.maddox.whitlock<129><[U:1:455777988]>" committed suicide with "world" (attacker_position "7 -11763 4")
Ignoring unreasonable position (-191.517807,13079.423828,-36324.328125) from vphysics! (entity tf_dropped_weapon)
*** ERROR *** Excessive sizelevel (1099) for element
Ignoring unreasonable position (-191.639450,13079.524414,-46293.968750) from vphysics! (entity tf_dropped_weapon)
Ignoring unreasonable position (-191.655792,13079.537109,-56263.687500) from vphysics! (entity tf_dropped_weapon)
L 11/22/2017 - 11:06:14: "george.maddox.whitlock<129><[U:1:455777988]>" committed suicide with "dumpster_device" (attacker_position "-293 -11318 -280")
WatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.

status
^CWed Nov 22 14:31:43 PST 2017: Server Quit
`
Note that I have to Ctrl+C to stop it. What can I do to make it autorestart?

**Comment by sdplisskenbr** [comment]
I had the same problem with my Codename CURE server. My solution is a script to restart the server everytime that appears the message "Host_Error: WatchdogHandler called - server exiting.". In my server I use crontab, gnu screen, a script for each CURE server, a script to create a gnu screen session, a script to read log from servers and restart the server when catch the "WatchdogHandler called".

My scripts (I edited my scripts for secure issue):

Script iniscript.sh to start screen:
==========================================================
#!/bin/sh

screen -d -m -S ayyserver1 -t htop
screen -S ayyserver1 -p 0 -X stuff 'htop\r'

screen -S ayyserver1 -X screen -t legacy1
screen -S ayyserver1 -p 1 -X stuff '~/steamcmd/legacy1.sh\r'
screen -S ayyserver1 -X screen -t legacy2
screen -S ayyserver1 -p 2 -X stuff '~/steamcmd/legacy2.sh\r'

screen -X -p 1 log on
screen -X -p 2 log on
==========================================================

"screen -X -p 1 log on" = enable logging and create the file screenlog.1
"screen -X -p 2 log on" = enable logging and create the file screenlog.2

Script "watchdog.sh" to read the screenlog.* files (the script read each line of screenlog files and search for the line "Host_Error: WatchdogHandler called - server exiting."): 
==========================================================
#!/bin/bash

serv=(
legacy1.sh
legacy2.sh
)

pathserv="home/username/steamcmd/"
sl="screenlog."
text="Host_Error: WatchdogHandler called - server exiting."$'\r'

function readlog(){

while IFS='' read -r line || [[ -n "$line" ]]; do
if [ "$line" == "$text" ]; then
screen -S ayyserver1 -p "$[i+1]" -X stuff ^C
screen -S ayyserver1 -p "$[i+1]" -X stuff "$pathserv""${serv[i]}"'\r'
echo "${serv[i]}"' - '`date` >> ~/steamcmd/LogDog.txt
fi
done < "$pathserv""$sl""$[i+1]"
rm "$pathserv""$sl""$[i+1]"

}

for ((i=0;i<${#serv[@]};i++))
do
  readlog
done
==========================================================

crontab -e:
==========================================================
@reboot ~/steamcmd/iniscript.sh
0-59/5 * * * * ~/steamcmd/watchdog.sh
==========================================================
"0-59/5 * * * * ~/steamcmd/watchdog.sh" = execute the script every 5 minutes

legacy1.sh is something like:
==========================================================
#!/bin/sh 
~/steamcmd/cure/srcds_run -game cure -console +map cbe_office_legacy +exec server1.cfg -autoupdate -steam_dir ~/steamcmd -steamcmd_script
==========================================================

CURE - Dedicated server setup guide (by Hoobalugalar_X):
https://steamcommunity.com/sharedfiles/filedetails/?id=490472068

**Comment by sdplisskenbr** [comment]
My new script to my server (startserver.sh)

Start server:
./startserver.sh 1
Watchdog only:
./startserver.sh

*`date` is between "grave accent" (ascii 96)

==============================================================

#!/bin/bash

serv=(
legacy1.sh
legacy2.sh
standard1.sh
standard2.sh
short1.sh
short2.sh
survival1.sh
survival2.sh
)

sn="ayyserver1"
dirserv=$HOME'/steamcmd/'
sl="$dirserv""screenlog."
text="Host_Error: WatchdogHandler called - server exiting."$'\r'

function readlog(){

while IFS='' read -r line || [[ -n "$line" ]]; do
  if [ "$line" == "$text" ]; then
    screen -S "$sn" -p "$[i+1]" -X stuff ^C
    sleep 5
    screen -S "$sn" -p "$[i+1]" -X stuff "$dirserv""${serv[i]}"'\r'
    echo "${serv[i]}"' - '`date` >> "$dirserv"/LogDog.txt
  fi
done < "$sl""$[i+1]"
rm "$sl""$[i+1]"

}

function startscreen(){

screen -S "$sn" -X screen -t "${serv[i]}"
screen -S "$sn" -p "$[i+1]" -X stuff "$dirserv""${serv[i]}"'\r'

screen -X -p "$[i+1]" log on

sleep 1
}

if [ "$1" == 1 ]; then
  screen -d -m -S "$sn" -t htop
  screen -S "$sn" -p 0 -X stuff 'htop\r'
fi

for ((i=0;i<${#serv[@]};i++))
do
  if [ "$1" == 1 ];
    then startscreen
    else readlog
  fi
done

**Comment by diamondburned** [comment]
Can you add in a diff file instead?
