### ISSUE TITLE
I can not access from the outside to the game server

### ISSUE THREAD

**Issue by Nikolas-Lindemann** [GameServerManagers/LinuxGSM#1706]
I rented myself a server (ubuntu 16.04) on the digitalocean. Installed there is not for the root user game server (CS1.6).Install and run occurred successfully, but:
when I first started, the system determined that I had several IP-addresses, I chose the primary IP-address on which other servers work for me. Then I tried in the game itself to connect (X.X.X.X:27015) to my server, but nothing happened. The game server reports that it works, but I can not access it from the outside. I also tried to configure my ports, enable it for different protocols, or completely disable the firewall, but there is no result either. Command (sudo netstat -atunp | grep hlds_run) no information. I tried all the recommendations in your links that were output in the console, but only one failure.
Help solve the problem, I want to start my game server, but I do not know what the problem is.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Ports
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting#connectivity-issues
