### ISSUE TITLE
Suggestion or problem

### ISSUE THREAD

**Issue by Owned67** [GameServerManagers/LinuxGSM#1707]
`./linuxgsm.sh install
    fetching serverlist.csv...OK
Installed Counter-Strike: Source server as cssserver-2

Remember to check server ports
./cssserver-2 details`

`./cssserver install` why i can't choose installation folder? he install directly all server in $home/serverfiles folder`.

actualy:
`./cssserver install
=================================
Counter-Strike: Source
Linux Game Server Manager
by Daniel Gibbs
Contributors: http://goo.gl/qLmitD
https://gameservermanagers.com
=================================

Server Directory
=================================
/home/steam/serverfiles

Continue? [Y/n] n
`
or maybe, add $home/serverfiles/$gamename for install a server?

**Comment by UltimateByte** [comment]
You just need to document yourself.
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers
