### ISSUE TITLE
San Andreas Multiplayer bug, not starting

### ISSUE THREAD

**Issue by Emialcaraz** [GameServerManagers/LinuxGSM#1711]
San Andreas Multiplayer Debug
=================================

Distro:    Ubuntu 16.04.3 LTS
Arch:    x86_64
Kernel:    4.4.0-101-generic
Hostname:    svp-208
tmux:    tmux 2.5
Avg Load:    0.00, 0.05, 0.07
Free Memory:    174M
Free Disk:    26G
GLIBC required:    2.3
Server IP:    (oculted):7777

Start parameters:
./samp03svr 

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If sampserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug sampserver: Stopping any running servers
[ INFO ] Stopping sampserver: SA-MP 0.3 Server is already stopped
[  OK  ] Debug sampserver: Starting debug
[  OK  ] Debug sampserver: Stopping debug

command_debug.sh exiting with code: 2

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
