### ISSUE TITLE
Ubuntu TF2 server crash at start (no obvious error)

### ISSUE THREAD

**Issue by eduardhasanaj2** [GameServerManagers/LinuxGSM#1713]
hi,
i am having a strange issue that I cannot fix so far.

`Using Breakpad minidump system. Version: 4246944 AppID: 232250
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Loaded 9054 VPK file hashes from /home/steam/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 9054 VPK file hashes from /home/steam/serverfiles/tf/tf2_textures.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/steam/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 465 VPK file hashes from /home/steam/serverfiles/tf/tf2_sound_vo_english.vpk for pure server operation.
Loaded 1318 VPK file hashes from /home/steam/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 1318 VPK file hashes from /home/steam/serverfiles/tf/tf2_sound_misc.vpk for pure server operation.
Loaded 2032 VPK file hashes from /home/steam/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 2032 VPK file hashes from /home/steam/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 2032 VPK file hashes from /home/steam/serverfiles/tf/tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from /home/steam/serverfiles/hl2/hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from /home/steam/serverfiles/hl2/hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from /home/steam/serverfiles/hl2/hl2_sound_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from /home/steam/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from /home/steam/serverfiles/hl2/hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/steam/serverfiles/platform/platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from /home/steam/serverfiles/platform/platform_misc.vpk for pure server operation.
server_srv.so loaded for "Team Fortress"
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
ProtoDefs post data loaded.
ProtoDefs loaded. 11.30 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 11.30 MB used
maxplayers set to 16
No '-replayserverdir' parameter found - using default replay folder.
Replay: Creating thread pool...succeeded.
Replay: Starting thread pool with 4 threads...succeeded.
Cleaning files from temp dir, "/home/steam/serverfiles/tf/replay/server/tmp/" ...no files removed.
ProtoDefs post data loaded.
ProtoDefs post data loaded.
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Unknown command "r_decal_cullsize"
ConVarRef dev_loadtime_map_start doesn't point to an existing ConVar
Usage: sv_setsteamaccount <login_token>
Unknown command "startupmenu"
Network: IP 10.17.0.5, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 440
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 232250
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file tf2server.cfg
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg/mapcycle.txt' was not found.)
Killed
cat: hlds.5183.pid: No such file or directory
`

**Comment by UltimateByte** [comment]
Your main issue is that you can't follow rules.

**Comment by eduardhasanaj2** [comment]
Sorry but your rules were not in main readme. Perhaps this confused me. Anyway I will try to do it manually.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
