### ISSUE TITLE
Fresh Install of 7Days Server - Tmux Error

### ISSUE THREAD

**Issue by oimr** [GameServerManagers/LinuxGSM#1714]
Running CentOS Linux release 7.4.1708 (Core)

Had this running on a previous server, backed up, restored but it didn't work, so fresh install but this isn't working either, log file below.

Nov 28 21:33:02.889 sdtdserver: START: FATAL: Unable to start My Game Host
Nov 28 21:33:04.392 sdtdserver: START: FATAL: Unable to start My Game Host: Tmux error:
tmux new-session -d -s "sdtdserver" "./7DaysToDieServer.x86 -logfile /home/sdtdserver/log/server/output_log__2017-11-28__21-33-01.txt -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml"
create session failed: ./7DaysToDieServer.x86 -logfile /home/sdtdserver/log/server/output_log__2017-11-28__21-33-01.txt -quit -batchmode -nographics -dedicated -configfile=/home/sdtdserver/serverfiles/sdtdserver.xml: Operation not permitted
Nov 28 21:33:04.397 sdtdserver: START: INFO: No known fix currently. Please log an issue.
Nov 28 21:33:04.398 sdtdserver: START: INFO: https://gameservermanagers.com/support
Nov 28 21:33:04.399 sdtdserver: START: FATAL: command_start.sh exiting with code: 1
Nov 28 21:38:50.687 sdtdserver: PASS: Downloading command_console.sh: OK
Nov 28 21:38:56.290 sdtdserver: CONSOLE: ERROR: Failed to access: Server not running
Nov 28 21:39:03.499 sdtdserver: START: INFO: Rotating log files

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by MarkL4YG** [comment]
Read your logs more carefully

The key-phrase here is ``operation not permitted``
