### ISSUE TITLE
Arma3 Gameserver doesn't start after Update (v. 2328809)

### ISSUE THREAD

**Issue by lexeltj** [GameServerManagers/LinuxGSM#1716]
Today there was a new Arma update.

After Updating my Server, the Server doesn't start anymore.

logs says:

`...`
`20:00:07 Loading movesType CfgGesturesMale`
`20:00:07 MovesType CfgGesturesMale load time 40 ms`
`20:00:07 Loading movesType CfgMovesMaleSdr`
`20:00:11 MovesType CfgMovesMaleSdr load time 4418 ms`
no errors. or something else.

PS: I also add a new user, installed a new lgsm but it is the same problem? Any Idea?

I Use Debian 4.9

**Comment by loxley314** [comment]
Same here
 Starting "./arma3server debug":
`21:02:29 Loading movesType CfgGesturesMale
21:02:30 MovesType CfgGesturesMale load time 93 ms
21:02:30 Loading movesType CfgMovesMaleSdr
21:02:37 MovesType CfgMovesMaleSdr load time 7432 ms
/home/arma3server/lgsm/functions/command_debug.sh: line 108:   333 Segmentation fault      (core dumped) ${executable} ${parms//\\;/;}
[  OK  ] Debug arma3server: Stopping debug
`

I tried to start from scratch with empty config files an got same error.

... but if I try to start directly from ../serverfiles/arma3server it works so looks like the problem it's here on lgsm

I use Debian 8.9

**Comment by PikachuNL** [comment]
I can confirm the same error happens to me. Running "./arma3server debug" gives me the following result:
`
/home/arma3server/lgsm/functions/command_debug.sh: line 108: 11027 Segmentation fault      (core dumped) ${executable} ${parms//\\;/;}
`
Initially I thought it was a bug on Arma 3's side, but it appears to be LGSM indeed.

**Comment by lexeltj** [comment]
if I start the server directly... this is my output then the server stucks:
`21:32:42 InitSound ...`
`21:32:42 InitSound - complete`
`21:32:42 Dedicated host created.`
`21:32:42 PhysX3 SDK Init started ...`
`21:32:42 PhysX3 SDK Init ended.`
`21:32:44 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.`
`a3_characters_f`
`21:32:44 Loading movesType CfgGesturesMale`
`21:32:44 MovesType CfgGesturesMale load time 40 ms`
`21:32:44 Loading movesType CfgMovesMaleSdr`
`21:32:48 MovesType CfgMovesMaleSdr load time 4425 ms`
`21:32:48 BattlEye Server: Initialized (v1.217)`
`21:32:48 Host identity created.`
`[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.`
`Setting breakpad minidump AppID = 107410`
`21:32:48 Game Port: 2302, Steam Query Port: 2303`
`21:32:48 Initializing Steam server - Game Port: 2302, Steam Query Port: 2303`
`Arma 3 Console version 1.78.143717 x86 : port 2302`
`21:32:49 Connected to Steam servers`

**Comment by Saschlong** [comment]
Got also the Segfault problem..

`/home/arma/lgsm/functions/command_debug.sh: line 108: 21934 Segmentation fault (core dumped) ${executable} ${parms//\\;/;}`

**Comment by UltimateByte** [comment]
Segmentation fault means an error while executing C++ code from the game.
There are various possible reasons for that, from outdated Glibc libraries, to the use of outdated start parameters.

Why don't you guys start by following support's guidelines and post your "postdetails" output?
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by lexeltj** [comment]
ok. sorry.

Which game server you are running: 
**Arma3**

The outputted link of ./gameserver postdetails command: 
**https://hastebin.com/ekobasijef**

The context of your error and the exact outputs.: 
**Server stucks at Start after update**

Your Linux distro and version 
**Debian x64**

Your kernel information
**Linux Debian-90-stretch-64-minimal 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux**

Your versions for glibc
**Debian GLIBC 2.24-11+deb9u1**

**Comment by Scarat95** [comment]
The same here.

**Which game server you are running:**
Arma3

**The outputted link of ./gameserver postdetails command:**
https://hastebin.com/epegogitin

**The context of your error and the exact outputs.:**
Server shuting down after start

**Your Linux distro and version**
Debian GNU/Linux 8.9 (jessie) x64

**Your kernel information**
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19)

**Your versions for glibc**
(Debian GLIBC 2.19-18+deb8u10) 2.19

**Comment by loxley314** [comment]
Which game server you are running
Arma3

The outputted link of ./gameserver postdetails
https://hastebin.com/xabulugopi

The context of your error and the exact outputs.:
Server shuting down after start

Your Linux distro and version
Debian GNU/Linux 8.9 (jessie) x64

Your kernel information
3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

Your versions for glibc and tmux
ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
tmux 1.9

../log/script/arma3server-script.log
https://pastebin.com/fC8pnfdt

**../log/console/arma3server-console.log**
https://pastebin.com/Tytaxi9u

All this logs are from a clean server without no config or mods but before I tried with my server and the problem is the same.

**Comment by Scarat95** [comment]
Remove -netlog from the pharms ... ist corrupted.
After it the Server is starting as if nothing happend

**Comment by Soleedus** [comment]
Yeah, it appears to be an issue with -netlog. Removing that parameter allows the server to start without segfaulting

**Comment by lexeltj** [comment]
Many thanks. It worked for me first.

**Comment by MarkL4YG** [comment]
Bohemia breaking things again ¯\\_(ツ)_/¯

**Comment by LoadingSAa** [comment]
Due to the changes to ports you need to remove -netlog or the server will crash. This needs to be changed to not be a default on the LGSM start script as -netlog is a diagnostic tool and will cause a performance hit on servers.

**Comment by UltimateByte** [comment]
Fix implemented.
I'll leave this issue open for a while so that Arma 3 server admins can see it.

**Comment by dgibbs64** [comment]
Good effort on this one guys! Nice one!
