### ISSUE TITLE
Factorio Install issue

### ISSUE THREAD

**Issue by LoadingSAa** [GameServerManagers/LinuxGSM#1717]
It looks like the Factorio website has changed and the link in update_factorio.sh is no longer valid. The new link is apparently https://www.factorio.com/download-headless.

The current error is: 
[ FAIL ] Update fctrserver: Checking for update: factorio.com: Not returning version

**Comment by dgibbs64** [comment]
Thanks for this will be updated as soon as possible

**Comment by dgibbs64** [comment]
@UltimateByte could you release a hotfix for this as I am unable too currently. Thanks!

**Comment by LoadingSAa** [comment]
Thanks guys I know a bit of scripting but I'm not very familiar with git so I wasn't sure If I could summit a change for approval.

Thanks again.

**Comment by fanuch** [comment]
Hey @dgibbs64 and @LoadingSAa. Long story short, the site tree was changed.

They have removed the web tree `https://www.factorio.com/download-headless\stable`
Current request by lgsm `https://www.factorio.com/download-headless/"{$branch}"`, where `$branch = stable` which returns `404`.

All the links are still up, but you need to get them directly from `https://www.factorio.com/download-headless`.

Removing the `/"${branch}"` completed the installation and server is working fine!

**Comment by fanuch** [comment]
Pull request has been submitted @dgibbs64 .

**Comment by UltimateByte** [comment]
Thanks for your contribution. This is merged.
