### ISSUE TITLE
command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by mgjuhler** [GameServerManagers/LinuxGSM#1722]
./csgoserver monitor 
> "monitor_gsquery.sh: line 46: warning: command substitution: ignored null byte in input"

Distro:    Debian GNU/Linux 9.2 (stretch)
Arch:      x86_64
Kernel:    4.9.0-4-amd64
tmux:      tmux 2.3
GLIBC:     2.24

**Comment by UltimateByte** [comment]
Reproduced.

Full output is more useful though.

```
csgoserver@gaben:~$ ./csgoserver monitor
[  OK  ] Monitor csgoserver: Checking session: OK
[ .... ] Monitor csgoserver: Querying port: 178.32.107.110:27033 : 15/2 : QUERYING/home/terageek/csgoserver/lgsm/functions/monitor_gsquery.sh: line 46: warning: command substitution: ignored null byte in input
[  OK  ] Monitor csgoserver: Querying port: 178.32.107.110:27033 : 2 : OK
```

Postdetails: https://hastebin.com/oheligitel

I noticed this weird output in dev-debug.log from the var mentioned in line 46.
Github will probably fail to output as well:

```
+++++ gsquerycmd='OK: ����I^QPractice Server terageek.orgde_infernocsgoCounter-Strike: Global Offensive�^B^Pdl^A1.36.1.7��iempty,secure�^B'''
```

(I removed the '|' from the servername for this terst to make sure that wasn't the issue)

So there seems to be an issue here https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/monitor_gsquery.sh#L46 or in gsquery.py.
