### ISSUE TITLE
Natural Selection 2: Executable was not found

### ISSUE THREAD

**Issue by Tex42** [GameServerManagers/LinuxGSM#1723]
### Which game server you are running:
Natural Selection 2

### The outputted link of ./gameserver postdetails command:
https://hastebin.com/sikucixaxi

### The context of your error and the exact outputs.:
[ FAIL ] Starting ns2server: Executable was not found:
/home/ns2server/serverfiles/server_linux32

### Your Linux distro and version:
Ubuntu 17.10 x64

### Your kernel information:
Linux Ubuntu-1710-artful-64-minimal 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Your versions for glibc:
Ubuntu GLIBC 2.26-0ubuntu2 2.26
tmux 2.5

### Comment:
This is a clean new server so it seems like LGSM is using the wrong executable.
temporary fix: use a symbolic link to the 64bit server_linux executable.
ln -s /home/ns2server/serverfiles/x64/server_linux /home/ns2server/serverfiles/server_linux32

**Comment by UltimateByte** [comment]
Seems like they added x64 and possibly removed x86 while changing paths.

**Comment by dgibbs64** [comment]
Looks like the dev team havnt even added a 64-bit binary for Linux Servers. I have queried this. So for now NS2 will not work on Linux

**Comment by dgibbs64** [comment]
Fix now released https://github.com/GameServerManagers/LinuxGSM/releases/tag/171216

**Comment by dgibbs64** [comment]
Fix now released https://github.com/GameServerManagers/LinuxGSM/releases/tag/171216
