### ISSUE TITLE
Multiple CSGO servers.

### ISSUE THREAD

**Issue by PetriVukan** [GameServerManagers/LinuxGSM#1725]
Hi,

I am trying to run 2 servers on the same machine.

The main server is running on these ports:
```
port="27015"
clientport="27005"
sourcetvport="27020"
```

What values should I put here on the 2nd server? For some reason, whatever port I put, it keeps crashing the other server and when I power on the main server it hits the 2nd server offline.

**Comment by mgjuhler** [comment]
Please paste the game console output from the 2nd server

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki
