### ISSUE TITLE
tf2server default-config lgsm is not default? test-alert work, but?

### ISSUE THREAD

**Issue by neoll4ik** [GameServerManagers/LinuxGSM#1728]
Hello. Why the default config is not defaulted lgsm/default-config/config-lgsm/_default.cfg 
If some changes in lgsm/config-lgsm/_default.cfg, and try /tf2server dt or /tf2server st, warning and copy cfg  lgsm/default-config/config-lgsm/_default.cfg  and changes is gone.  But if edit lgsm/default-config/config-lgsm/_default.cfg  and try /tf2server dt, that cfg copy copied to lgsm/config-lgsm/_default.cfg  and all fine.

I think that lgsm/default-config/config-lgsm/_default.cfg its backup, if some do wrong or desnt work i can copied that cfg and try changes again.

And one more, ./tf2server test-alert work perfectly to telegram and discord. But i wanna notofocations if server restarted or updated, its doesnt work.. 

Can some one help me?

**Comment by MarkL4YG** [comment]
Do ___not___ modify ``_default.cfg`` if you want to share settings over all instances use ``common.cfg`` as ``_default.cfg`` will be automatically overwritten!

**Comment by neoll4ik** [comment]
Alright. 

What about alerts? 

The configuration file specifies what to notify when restarting and when updating, even with availability or not availability. But only the test notification works

**Comment by MarkL4YG** [comment]
I guess what you mean is that you're missing the required monitoring job which enables alerts.
See https://github.com/GameServerManagers/LinuxGSM/wiki/Monitor

**Comment by neoll4ik** [comment]
@MarkL4YG  Yes, i configured crontab, like */1 * * * *  /home/tf2server/tf2server monitor > /dev/null 2>&1    just for tests. And do nothing, if ./tf2server stop then use ./tf2server m   got error 
[ERROR ] Monitor tf2server: Disabled: No lockfile found
	* To enable monitor run ./tf2server start
Im start server then ./tf2server m   
Checking session: OK
Querying port : OK

Then stop server and same, no alerts in discord. Work only test-alert ....

**Comment by UltimateByte** [comment]
"*/1" is the same as "*", so dont use this syntax for one minute.
Also, don't use the damn monitor every single minute, you're gonna get issues.

Ultimately, you're not understanding how monitor works, so document yourself please.
Read these two last parts and understand why what you're trying to do won't work ever.
https://github.com/GameServerManagers/LinuxGSM/wiki/Monitor#how-does-monitor-work
