### ISSUE TITLE
COD 5: World at War Linux Error

### ISSUE THREAD

**Issue by Viper1lt** [GameServerManagers/LinuxGSM#1729]
verifying codwaw-lnxded-1.7-full.tar.bz2 with MD5...FAIL

Thus the server is not installed?

**Comment by UltimateByte** [comment]
Details ?
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by dgibbs64** [comment]
I have done a move of the file hosting so it is possible that the file didnt transfer correctly. Will need to verify that the md5 sum matches

**Comment by dgibbs64** [comment]
Looking at this it appears that the server I have migrated it too keeps dropping the connections which is not good. So I will look in to a solution for this

**Comment by dgibbs64** [comment]
I have pointed the DNS back at the old location for now
