### ISSUE TITLE
Minecraft Server Bug

### ISSUE THREAD

**Issue by DelloxD1** [GameServerManagers/LinuxGSM#1730]
Hi,

I found two bugs in your Minecraft Server installation script. 

-If you create a new user and install the Minecraft server, no correct internal (server) IP address will be set, only the port is set (must be fixed manually in the server. propeties)

-The information to the used ports is wrong (. /mcserver details) -> port 25565 is not udp but tcp

greetings from germany

**Comment by MarkL4YG** [comment]
The external IP address is normally set by LGSM using command line parameters which are not supported by Minecraft. Thus you'll need to edit the server configuration yourself unless you'd want permanent modification of the server.properties file built into LGSM.

As for the port info. I'd say there's a typo somewhere ¯\\\_(ツ)\_/¯

**Comment by dgibbs64** [comment]
Yup server.propeties has to be edited for minecraft to allow LinuxGSM to pick up the correct IP address.

Also thanks for the update about the port being tcp.

**Comment by dgibbs64** [comment]
No further action requires
