### ISSUE TITLE
Stationeers

### ISSUE THREAD

**Issue by FliesWithWind** [GameServerManagers/LinuxGSM#1731]
Hey,

I would love to see a script for Stationeers

https://steamdb.info/app/600760/
https://cdn.discordapp.com/attachments/276525882049429515/390311301504827392/Stationeers-DedicatedServerCommands-v0.12.pdf

**Comment by dgibbs64** [comment]
Saw this the other day. Should be possible. But will be a while with the massive backlog...unless you want to try developing it. :)

**Comment by FliesWithWind** [comment]
I actually did develop it today.
Can you check it and see if it's more or less correct? :)
https://github.com/FliesWithWind/LinuxGSM

**Comment by dgibbs64** [comment]
Great start this will save some time. Looking at the notes it uses a default.ini. If it is possible to use config files they should be used over parameters. Could you submit a default config to https://github.com/GameServerManagers/Game-Server-Configs and could you look at replacing as many paramters as possible.

There are a bunch if areas that will need to be completed before release such as details and adding it to the list https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/data/serverlist.csv for example. So continue to have a play and see what you can do. 

Thanks for getting started with this. It will speed up release :)

**Comment by dgibbs64** [comment]
Great start this will save some time. Looking at the notes it uses a default.ini. If it is possible to use config files they should be used over parameters. Could you submit a default config to https://github.com/GameServerManagers/Game-Server-Configs and could you look at replacing as many paramters as possible.

There are a bunch if areas that will need to be completed before release such as details and adding it to the list https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/data/serverlist.csv for example. So continue to have a play and see what you can do. 

Thanks for getting started with this. It will speed up release :)

**Comment by dgibbs64** [comment]
Ready for next release
