### ISSUE TITLE
gldriverquery | vulkandriverquery: not found

### ISSUE THREAD

**Issue by Subb98** [GameServerManagers/LinuxGSM#1736]
Hello.
After HLDS server install (and update, and validate), i don't have server files. Also in the **valve** folder:

![1](https://user-images.githubusercontent.com/7755984/34071412-d1ef029c-e297-11e7-8646-f40cdcc84b73.png)

I tried to create a new account on Steam and run installation from this user. But nothing changes.
There are errors:

stderr.txt:
```
sh: 1: /home/csserver/steamcmd/linux32/../ubuntu12_64/gldriverquery: not found
sh: 1: /home/csserver/steamcmd/linux32/../ubuntu12_32/gldriverquery: not found
sh: 1: /home/csserver/steamcmd/linux32/../ubuntu12_64/vulkandriverquery: not found
```

**Comment by FirePowi** [comment]
Same error in Rust.

**Comment by UltimateByte** [comment]
@FirePowi https://github.com/GameServerManagers/LinuxGSM/wiki/Support
