### ISSUE TITLE
Factorio Experimental Not Downloading

### ISSUE THREAD

**Issue by LoadingSAa** [GameServerManagers/LinuxGSM#1737]
I've edited fctrserver in /lgsm/config-default/config-lgsm and changed branch="stable" to branch="experimental" and tired to use ./fctrserver update but it just keeps trying to update to the stable branch.

Is there some documentation I'm missing?

**Comment by UltimateByte** [comment]
Probably because of this
https://github.com/GameServerManagers/LinuxGSM/pull/1719

Updating your LGSM instance should solve the issue.

**Comment by dgibbs64** [comment]
Just release another hotfix to resolve this.
