### ISSUE TITLE
Factorio server won't start

### ISSUE THREAD

**Issue by DrLynix** [GameServerManagers/LinuxGSM#1739]
Hi,

I just ran `./fctrserver update-lgsm`, updated my factorio server to 0.15.40 (from 0.15.37) and I can't start it anymore.

Here's the log:
```
factorioserver@Malcolm:~$ ./fctrserver start
[ .... ] Starting fctrserver: no server running on /tmp/tmux-1000/default
[ FAIL ] Starting fctrserver: Unable to start Factorio Server
factorioserver@Malcolm:~$
```

Any idea? Thanks

**Comment by dgibbs64** [comment]
Looks like some odd stuff is happening with tmux. Might be an old tmux session still hanging around maybe. I had a quick google to look but wasnt very clear. Might be worth rebooting your server if you haven't already

**Comment by DrLynix** [comment]
Thanks for your answer.

I fixed my problem by making a backup, installing the factorio server again
and putting back the save, works like a charm now.

**Comment by dgibbs64** [comment]
Aweseom!
