### ISSUE TITLE
[REQUEST] FiveM

### ISSUE THREAD

**Issue by Gronkhou** [GameServerManagers/LinuxGSM#1743]
I woud love Support for FiveM 

FiveM is an GTA 5 Multiplayer Modification that let you create own Servers, like Roleplay, Stunt and other stuff..

There Website for more Information is https://fivem.net/

If there are more Info's needet, text me.

**Comment by AlexCSilva** [comment]
someone requested it b4

**Comment by dgibbs64** [comment]
Duplicate: https://github.com/GameServerManagers/LinuxGSM/issues/1615
