### ISSUE TITLE
update cod4x 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#1744]
i just replaces cod4x_deatrun  but i got error (cod4x release update ) there are no command
 `./cod4server u `
so how can i update cod4x updated ? 

here is the cod4x update 
[https://cod4x.me/index.php?/forums/topic/2279-towards-a-stable-masterbranch/&tab=comments#comment-10222](https://cod4x.me/index.php?/forums/topic/2279-towards-a-stable-masterbranch/&tab=comments#comment-10222)

**Comment by dgibbs64** [comment]
Cod4x has its own auto updater built in it checks for updates when you start the server.

**Comment by dgibbs64** [comment]
I will also be worth us updating the main download.

**Comment by Ghost173** [comment]
thz for replay

**Comment by Ghost173** [comment]
./cod4server ul its update lgsm only
