### ISSUE TITLE
7 Days to Die - Linux 32-bit vs. 64-bit server startup

### ISSUE THREAD

**Issue by ThorTheNinja** [GameServerManagers/LinuxGSM#1745]
Believe this issue _may_ be related to issue #1532. Basically, it seems the server is starting up using the 32-bit version, even if I've changed the startserver.sh to ONLY load the 64 bit version.

```
if [ "$(uname -m)" = "x86_64" ]; then
      ./7DaysToDieServer.x86_64 -logfile 7DaysToDieServer_Data/output_log__`date +%Y-%m-%d__%H-%M-%S`.txt -quit -batchmode -nographics -dedicated $PARAMS 
else
      ./7DaysToDieServer.x86_64 -logfile 7DaysToDieServer_Data/output_log__`date +%Y-%m-%d__%H-%M-%S`.txt -quit -batchmode -nographics -dedicated $PARAMS 
```

When I execute 

> uname -m

, it does indeed return:
`x86_64`

How can I force LGSM to run the 64-bit version?

**Comment by dgibbs64** [comment]
Try `==` instead. There are plans to review handling of x64 bit binary's 
```
if [ "$(uname -m)" == "x86_64" ]; then
```

**Comment by ThorTheNinja** [comment]
Is there a Linux command to verify whether the current running processes are running as 32 or 64 bit? It would appear to me that the 32-bit version is still getting called.

**Comment by Narquadah** [comment]
As of Alpha 17 (experimental) I couldn't get the 32-bit to run. The 64 works fine though. To get it to  work with LinuxGSM I  added  `executable="./7DaysToDieServer.x86_64"` to `sdtdserver.cfg`.

**Comment by dgibbs64** [comment]
7 Days to Die will be getting a bit of an overhaul with the recent changes
