### ISSUE TITLE
cant download ark server

### ISSUE THREAD

**Issue by jalako** [GameServerManagers/LinuxGSM#1748]
I wanted to download the ark server via lgsm.

when issuing the following command 

`wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh arkserver`

The following output is generated

> arkserver@srv47687:~$ wget -N --no-check-certificate https://gameservermanagers.com/dl/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh arkserver
--2017-12-24 18:25:46--  https://gameservermanagers.com/dl/linuxgsm.sh
Resolving gameservermanagers.com (gameservermanagers.com)... 104.31.93.238, 104.31.92.238
Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Server ignored If-Modified-Since header for file ‘linuxgsm.sh’.
You might want to add --no-if-modified-since option.
linuxgsm.sh: line 1: syntax error near unexpected token 'newline'
linuxgsm.sh: line 1: <!DOCTYPE html>'

**Comment by UltimateByte** [comment]
Temporary issue is fixed.
Up issue if not.
