### ISSUE TITLE
server.cfg isn't working.

### ISSUE THREAD

**Issue by ImSimon2312442** [GameServerManagers/LinuxGSM#1750]
My cfg from LinuxGSM:
maxplayers="40"
tickrate="66"
gamemode="darkrp"
servercfgfullpath="/home/gmodserver/lgsm/config-default/config-game/server.cfg"
workshopauth="***************"
workshopcollectionid="*********"

And there's the problem:
The Server.cfg wont work! When I type ./gmodserver details all Information is like the server.cfg but when I go ingame, NOTHING from the server.cfg is there! Please help!

Sorry for my bad english, im german.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
Also... Just read the wiki.
https://github.com/GameServerManagers/LinuxGSM/wiki/Game-Server-Config
https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters
