### ISSUE TITLE
Backup lock file included in backup

### ISSUE THREAD

**Issue by PyCactuar** [GameServerManagers/LinuxGSM#1752]
**Issue:**
When restoring a backup created with the (in this case) ./rustserver backup command, it also backs up the .backup.lock file located in /home/user/lgsm/tmp. After restoring the backup this causes issues when running a new backup task is started, as the lock file causes the system to believe a backup is already running.

**Possible Solution:**
If possible this could be solved by skipping the .lock.backup file when making a backup.

**Comment by PyCactuar** [comment]
I've just located the following line in fn_backup_compression(): rm -f "${tmpdir}/.backup.lock"

For some reason this does not seem to happen when making a backup.

**Comment by UltimateByte** [comment]
Hello,
Thanks for reporting.
I would rather solve this by excluding the tmpdir since it's useless to backup it anyways.
