### ISSUE TITLE
gsquery unable to receive - Wolfenstein: Enemy Territory

### ISSUE THREAD

**Issue by jimwald1221** [GameServerManagers/LinuxGSM#1753]
While attempting to monitor a Wolfenstein ET server, gsquery reports it's "unable to receive". The engine seems to be the culprit. "idtech3" (default) doesn't provide a response but "idtech2" does. In what aspects is the engine important to other functions? Any feedback on this particular setting would be helpful.

**Comment by UltimateByte** [comment]
The query string is a bit different between the two engines.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/gsquery.py#L21-L28

You can try playing around with them and see if you come to some conclusions. 

What about details command? The issue could also come from here: does it work as intended?
Provide a postdetails link output to let us check.

**Comment by jimwald1221** [comment]
Seems the result of what I was trying to do is okay. No side effects so far.

https://hastebin.com/raw/yazugaloju

I changed the engine in the config and things seems to be responding okay. Monitor works and there don't seem to be errors of other commands so far.

**Comment by UltimateByte** [comment]
Good to know.
Could please you share you changes so that we can reproduce it and fix it natively inside LGSM?

**Comment by jimwald1221** [comment]
I just defined the engine variable in my config to "idtech2".

engine="idtech2"

**Comment by dgibbs64** [comment]
The W:ET engine is idtech3 but queries on idtech2 engine...How odd. We will need to put a specific statement in for W:ET as we should not change the engine variable as it would be inaccurate.

**Comment by dgibbs64** [comment]
There appears to be a bug in gsquery that is nearly a year old https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/gsquery.py#L21

the querys are listed the wrong way around.
