### ISSUE TITLE
[CSGO] Issue installing the server.

### ISSUE THREAD

**Issue by SkyGuardian** [GameServerManagers/LinuxGSM#1755]
I seem to be running into issues when installing a CSGO server, any ideas?

Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing
[ERROR ] Install csgoserver: SteamCMD is missing
mkdir: created directory '/home/csgoserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent dir                                                                                                                                                             ectories: No such file or directory
stdbuf: failed to run command ‘./steamcmd.sh’: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
[ERROR ] Install csgoserver: SteamCMD is missing
mkdir: created directory '/home/csgoserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent dir                                                                                                                                                             ectories: No such file or directory
stdbuf: failed to run command ‘./steamcmd.sh’: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys

Not sure how to code tag this, sorry.

**Comment by UltimateByte** [comment]
Wrong place to ask
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
