### ISSUE TITLE
[other] Happy geek year 2018!

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1762]
Just wanted to wish everyone a wonderful year, geeky or not!
Thanks to everyone, all contributors, Daniel Gibbs especially for this wonderful initiative, I'll never thank you enough!

I'll Never forger how LGSM got me into Linux, /bin/bash programming, and got me a full time real job that I like very much :D

Best wishes <3

**Comment by Bara** [comment]
feedback required? Okay...
Happy New Year! ✨ 🎉

**Comment by UltimateByte** [comment]
That's new year, gotta have some fun with labels! 
Thanks! :D

**Comment by Freeman-AM** [comment]
Bonne Année !

**Comment by dgibbs64** [comment]
Thanks for this @UltimateByte :D
