### ISSUE TITLE
javaram=" / parms=" not working!

### ISSUE THREAD

**Issue by KugIer** [GameServerManagers/LinuxGSM#1765]
Hello.

I'm trying to setup ARK and minecraft servers. On support page there is an info:

"Add -automanagedmods to the start parameters."

But adding code: parms="-automanagedmods" in file /lgsm/config-lgsm/arkserver.cfg does nothing. Also with BattleEye parms the same thing. Server start without any parms.

With minecraft I'm trying to add javaram="4096" into minecraft lgsm config file, but also nothing happens, and server start with 1GB RAM.

Please help with this issue.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
