### ISSUE TITLE
Getting clarity on Stationeers ports

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1767]
Requested clarity on Stationeers server ports

http://steamcommunity.com/app/544550/discussions/0/1621726179578018195/

**Comment by dgibbs64** [comment]
Also I dont know how to turn logging on for the server. So currently there are no server logs only console

**Comment by FliesWithWind** [comment]
As for logs they're currently stored in ~/.config/unity3d/Rocketwerkz/Stationeers/Player.log
But they're rather messy.

As for ports it's probably best to ask the devs on Stationeers Discord https://discord.gg/zsUev27

**Comment by dgibbs64** [comment]
Logs now work. No more info on ports. However I think the main ones are covered
