### ISSUE TITLE
cs 1.6 server running but cant connect 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#1768]
hii
iam hosted cs 1.6 server when i type ./csserver dt   i can see server online and its use ram and ip correct and port also correct i didn't change anything) and  my vps all ports are open 

i try to add gametracker also (i want to check server online of offline ) its fail 
i don't know why  any suggestion ?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting#connectivity-issues

Personal issues should not be posted on github.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

Thanks
