### ISSUE TITLE
feature request b3 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#1769]
i hope everyone are using b3 (bigbrotherbot)  here i am requesting b3 also need add lgsm

**Comment by UltimateByte** [comment]
Thanks for providing a lot of relevant doc for people who never started a cod server (or game). Very appreciated.
As a reminder, LinuxGSM supports 73 games atm...

Considering the requirements and the fact that it's most likely separated from the game server itself, I don't see it implemented into LinuxGSM, and I don't even see much benefits of having a manager integrated into another manager.
