### ISSUE TITLE
./rustserver update does not find the correct version of the game

### ISSUE THREAD

**Issue by braxton33** [GameServerManagers/LinuxGSM#1771]
I have been having this issue for several months now with LGSM. On update days, the command ./rustserver update will find only the current running version of the server. However, when I run ./rustserver fu (force update) it finds the new version. It can be minutes after facepunch pushes out the update, or many hours after, it does not matter, forceupdate is the only way the server will notice the update.

At one time the ./rustserver update command DID work, but it has not worked in many months, and I'm having to update by hand which is costing me players since we're not right back up on wipe days and it can be many hours before I'm awake or able to remote in and run the update. Since facepunch doesn't have a standard time for releasing updates I can't automate ./rustserver fu since it kills the server process no matter what.

LGSM is fully up to date, and I even completely removed my old install, and installed a new version of lgsm/rust and just moved my rust configs over, with the same problem.

**Example: I just ran all of these commands back to back, within minutes of each other, HOURS after the update is released. See that it only notices the new version AFTER fu has been run.**

[rustserver@RustServer ~]$ ./rustserver update
[  OK  ] Update rustserver: Checking for update: Server logs: No update requeste                                                                                                             [  OK  ] Update rustserver: Checking for update: SteamCMD: No update available

No update available:
        Current version: 2412849
        Available version: 2412849
        https://steamdb.info/app/258550/

[rustserver@RustServer ~]$ ./rustserver fu
[ .... ] Stopping rustserver: -Servername Redacted-                                                                                                             [  OK  ] Stopping rustserver: Graceful: CTRL+c: 2: OK
[ .... ] Stopping rustserver: -Servername Redacted-                                                                                                             [  OK  ] Stopping rustserver: -Servername Redacted-                                                                                                            
[  OK  ] Update rustserver: SteamCMD
Redirecting stderr to '/home/rustserver/steamcmd/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.25 (16113056 / 6563059865)
 Update state (0x61) downloading, progress: 3.90 (255897192 / 6563059865)
 Update state (0x61) downloading, progress: 8.38 (550276192 / 6563059865)
 Update state (0x61) downloading, progress: 19.43 (1275510218 / 6563059865)
 Update state (0x61) downloading, progress: 40.91 (2684926630 / 6563059865)
 Update state (0x61) downloading, progress: 58.83 (3861330340 / 6563059865)
 Update state (0x61) downloading, progress: 78.57 (5156584039 / 6563059865)
 Update state (0x61) downloading, progress: 96.00 (6300602243 / 6563059865)
 Update state (0x101) committing, progress: 100.00 (128894416 / 128894416)
Success! App '258550' fully installed.

[rustserver@RustServer ~]$ ./rustserver update
[  OK  ] Update rustserver: Checking for update: SteamCMD: No update available

No update available:
        Current version: 2430416
        Available version: 2430416
        https://steamdb.info/app/258550/

**Comment by UltimateByte** [comment]
This is a steamcmd issue. When this occurs, use validate instead.
https://github.com/GameServerManagers/LinuxGSM/wiki/Update#validate

**Comment by braxton33** [comment]
UltimateByte,

I ran validate last week after your reply. This week, the problem is still occurring.
Is it your intention that I run validate for every update?

As this process stops the server entirely, I'm not sure what this would accomplish that force-update does not.

**Comment by UltimateByte** [comment]
Well, an update requires a server restart anyways so... You have no choice to restart the server and get some unavailability. If you can't stand a 1 to 10 minutes game server unavailability depending on your server hardware, then I'm not the man of your situation since I have no way of proposing game server updates without interruption.

LinuxGSM runs an update command from SteamCMD. If it doesn't work, then the only way is to run validate. We have no control over that. Well, actually, to make sure about that, you can run force-update when the issue occurs and see if it solves the issue. If it does, then maybe we could find a workaround to this crap, but if it doesn't, then validate is the only way around.

**Comment by braxton33** [comment]
The issue is this:
Force Update and Validate ALWAYS brings the server down for a few minutes.
Update only does it when there is a patch to actually update.

Unless I want a server that goes down every few minutes for hours on Thursdays, this means I have to do them by hand, meaning if I'm busy Thursday afternoon, the server is unreachable for hours.

The update command claims to check server logs if an update is requested (In rust, this means it would see a player connect with a higher version ID than the server is running.) but this never seems to work, either.

I've been running force-update every Thursday for the past 6 months or so, when I remember it. I have a force update every day at 6am just in case I miss it,  but again, thats 12+ hours of downtime some Thursdays.
