### ISSUE TITLE
New game on linuxGSM - Orion prelude game

### ISSUE THREAD

**Issue by gamersalpha** [GameServerManagers/LinuxGSM#1772]
Hello there, 

can we add a new support game please 👍 

https://steamdb.info/app/213040/

thanks

**Comment by UltimateByte** [comment]
Supported platforms are not indicated at the moment in SteamDB, but given the install path, it looks like windows only shit.
`InstallScript | Binaries\Win32\installscript.vdf`

Somme googling confirms my assumption that it only works with Wine, and we don't support Wine stuff.
http://steamcommunity.com/app/104900/discussions/0/558752449341473034/

**Comment by gamersalpha** [comment]
Thank you for your reply
