### ISSUE TITLE
Starbound Server support

### ISSUE THREAD

**Issue by Shigbeard** [GameServerManagers/LinuxGSM#1774]
Starbound has official Linux server support, although redirecting configuration files is somewhat difficult with it.

You can find documentation on how to setup a linux Starbound server [here](https://starbounder.org/Guide:LinuxServerSetup) but to give you a TL;DR, it can be mostly automated with the following exceptions...

- The user account used for SteamCMD MUST own Starbound, as the server files are bundled with the game.
- In order to "unpack" the server configs, the server must be ran once, and then terminated.
- The server does not appear to have a graceful shutdown option outside of `^C`.
- The configuration file cannot be relocated. It may be possible to "move" it with the use of a symlink.
- The server's prerequisits list 32bit libs, but in actual fact the only server binaries are 64 bit.

Other than that, updating and installing is handled flawlessly by SteamCMD, and requires no additional "fixes" to operate on linux. And in reality this would mostly save server hosts like myself from manually typing out something to the tune of `tmux a -t starbound` every time we want to get into the console.

**Comment by UltimateByte** [comment]
It already exists
https://gameservermanagers.com/lgsm/sbserver/

**Comment by Shigbeard** [comment]
genuinely didnt see it in the supported server list, my bad.
