### ISSUE TITLE
Rust Oxide Mod downloading from old source

### ISSUE THREAD

**Issue by thedaedalus** [GameServerManagers/LinuxGSM#1775]
Hi 

I have been having issues with my Rust server and found that you are linking to an old Oxide repo. 

https://github.com/OxideMod/Oxide/releases

The new repo for Oxide for Rust is here

https://github.com/OxideMod/Oxide.Rust/releases

**Comment by UltimateByte** [comment]
Ouch, thanks for the info. I'll update it ASAP.

**Comment by UltimateByte** [comment]
Corrected. Run `update-lgsm` command to get the fix.
