### ISSUE TITLE
call of duty 4 server mod Change 

### ISSUE THREAD

**Issue by pemitha** [GameServerManagers/LinuxGSM#1780]
Please select the "Preview" tab above to view this message correctly.

Please note that this is an issue tracker for **LinuxGSM** related bugs and feature requests and **not** for the games themselves.

**Therefore personal server issues on GitHub will be closed without a kiss.**

Please follow **[this article](https://github.com/GameServerManagers/LinuxGSM/wiki/Support)** for optimal assistance
and do not forget to remove this text before opening the issue.

**Comment by marvinlehmann** [comment]
Seriously?

**Comment by pemitha** [comment]
Can you help me in Changing the mod in CoD4server plz

**Comment by UltimateByte** [comment]
Not LGSM's business, and certainly not on github... If only you had read the message you just posted...
Man, either you're trolling, you're drunk, or you're missing some grey matter, maybe a combination of that. 
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
