### ISSUE TITLE
Killing Floor 2 100% CPU usage

### ISSUE THREAD

**Issue by Lartza** [GameServerManagers/LinuxGSM#1781]
Running the Killing Floor 2 server with LGSM on Arch causes one of the server processes to lock a CPU core at 100% and making the game unplayable due to desync and lag. The process locks this usage even without any players though.

Downloading the server manually from steamcmd and just running it works perfectly.

postdetails:
https://gist.github.com/Lartza/e19c9181e020cba8a54ddd83e8a740e2

I have a suspicion it's something to do with some library fixes lgsm applies that on Arch would be better to not have and use system libraries for everything, but I am unsure on how to try that.

The console log does not indicate any issue and is identical to the server running without lgsm.

**Comment by UltimateByte** [comment]
What about a debug mode start? 
That will help us know if it's TMUX related or not.
https://github.com/GameServerManagers/LinuxGSM/wiki/Debug

Also, what are your start parms when running the server manually?
Maybe try with these parms inside LGSM.

That will help understanding more about this.

**Comment by Lartza** [comment]
I messed up my startup parameters and that made me accidentally figure out the issue.

The config files at
https://github.com/GameServerManagers/Game-Server-Configs/tree/master/KillingFloor2
cause this, letting the game generate it's own and the issue disappears.

**Comment by UltimateByte** [comment]
You can submit a PR on the config repo with proper configs if you wish. :)

**Comment by Lartza** [comment]
I'll do that after sleep :) Thanks for your help
