### ISSUE TITLE
csgo server console _restart command crash

### ISSUE THREAD

**Issue by ismail0234** [GameServerManagers/LinuxGSM#1783]
![ddasdaadsas](https://user-images.githubusercontent.com/20711301/35187721-5dc79c04-fe39-11e7-92c8-7e0513ef0b68.png)

csgo server console command: _restart and server crash.

how can i restart the server via console ?

**Comment by UltimateByte** [comment]
We have a wiki
https://github.com/GameServerManagers/LinuxGSM/wiki

We have rules
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
