### ISSUE TITLE
Stop selects wrong tmux session

### ISSUE THREAD

**Issue by Lartza** [GameServerManagers/LinuxGSM#1784]
I run two Killing Floor 2 servers under the same user.

Stopping the first server with ./kf2server always stops both servers either gracefully or by stopping kf2server-2 gracefully and then killing kf2server after the 30 seconds.

./kf2server-2 stop seems to work correctly

**Comment by UltimateByte** [comment]
Postdetails link for both of the servers.
https://github.com/GameServerManagers/LinuxGSM/wiki/Details#commands

**Comment by marvinlehmann** [comment]
#1699 ?

**Comment by UltimateByte** [comment]
Well, postdetails would provide the answer...

**Comment by Lartza** [comment]
Sounds like exaxctly #1699 

Ran into some additional issues while debugging / postdetails so took a while of figuring out...

For some reason, postdetails of my first server is doing this https://hastebin.com/ukeniyojuy
The second output is the right one although only the server name has changed... (seems it doesn't delete the postdetails log just appends to it)

Second server:
https://hastebin.com/opegiwasuw

Additionally somehow something bad happened and the monitor command wiped the kf2server file and made a new kf2server-2 file, or something similar :S Script log or anything had no indication though

**Comment by Lartza** [comment]
Some additional testing... Renamed the second script to not contain any words in common with the first
```
[kf2server@vanity ~]$ ./kf2server start
[  OK  ] Starting kf2server: lagit.in #1 | Custom Maps | 60 tick
[kf2server@vanity ~]$ ./private start
[  OK  ] Starting private: lagit.in #2 Private | Custom Maps | 60 tick
[kf2server@vanity ~]$ tmux ls
kf2server: 1 windows (created Mon Jan 22 07:36:58 2018) [23x80]
private: 1 windows (created Mon Jan 22 07:37:06 2018) [23x80]
[kf2server@vanity ~]$ ./kf2server stop
[ .... ] Stopping kf2server: Graceful: CTRL+c: 5^C
[kf2server@vanity ~]$ tmux ls
kf2server: 1 windows (created Mon Jan 22 07:36:58 2018) [23x80]
```

**Comment by dgibbs64** [comment]
I experienced this with two different servers. Unsure what caused it though

**Comment by dgibbs64** [comment]
The merge was reverted. I relive it caused serious issues. I will test a solution
https://github.com/GameServerManagers/LinuxGSM/commit/8faffe4ab81f5b673830b84ae5f78b5856e3cac7#diff-4dad406e2c6eb8fb1583fac41cfb8e6e

**Comment by dgibbs64** [comment]
Fixed and going in to next release
