### ISSUE TITLE
issue with installing oxide for hurtworld server lgsm

### ISSUE THREAD

**Issue by FiFaCZeq** [GameServerManagers/LinuxGSM#1789]
hwserver@vps507510:~ ./hwserver mi
Hurtworld addons/mods
Available addons/mods
Oxide for Hurtworld - Allows for the use of plugins - http://oxidemod.org/downloads/oxide-for-hurtworld.1332/
hwoxide
Enter an addon/mod to install (or exit to abort): hwoxide
Installing Oxide for Hurtworld
clearing mod download directory /home/hwserver/lgsm/mods/tmp...OK
creating mod download directory /home/hwserver/lgsm/mods/tmp...OK
downloading Oxide.Hurtworld.zip...curl: (3) Illegal characters found in URL
downloading Oxide.Hurtworld.zip...OK
**Failure!** An issue occurred downloading Oxide for Hurtworld
command_mods_install.sh exiting with code: 1
`hwserver@vps507510:~$
# ^this is code when i try to install oxide fo hurtworld. How to fix this issue please help me i done evrything correct in my  ubuntu 8gm ram 100gb ssd 3.1mhz vps server

**Comment by UltimateByte** [comment]
I'm having a look.
BTW, please follow our guidelines next time you post an issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
OK, the issue is that for some reason, Hurtworld returns two files.

omw for a fix

dev log:
```
 fn_fetch_file 'https://github.com/OxideMod/Oxide.Hurtworld/releases/download/2.0.3776/Oxide.Hurtworld-itemv2.zip
https://github.com/OxideMod/Oxide.Hurtworld/releases/download/2.0.3776/Oxide.Hurtworld.zip' /home/ultimatebyte/lgsm/mods/tmp Oxide.Hurtworld.zip
++++ remote_fileurl='https://github.com/OxideMod/Oxide.Hurtworld/releases/download/2.0.3776/Oxide.Hurtworld-itemv2.zip
https://github.com/OxideMod/Oxide.Hurtworld/releases/download/2.0.3776/Oxide.Hurtworld.zip'
```

**Comment by UltimateByte** [comment]
Fixed, actually, I noticed it the first time and preparted the fix for the issue... But put the grep on 7daystodie instead of hurtworld. My bad. 

Update your LinuxGSM, it's fixed.

**Comment by FiFaCZeq** [comment]
Thank You do much bro
