### ISSUE TITLE
Minecraft Single Install Multiple Instances

### ISSUE THREAD

**Issue by coult45usmc** [GameServerManagers/LinuxGSM#1791]
First off, I really love LGSM. This is a fantastic tool. Much thanks to all who have contributed. I'm running your script on many different game servers and everything works great!
One of them is a Fedora Minecraft server. Fedora server 24, LGSM, and Minecraft are fully up to date. While each instance will successfully run using it's dedicated configuration file, they cannot run at the same time. After starting all 3 instances, and using the ./mcserver details command, I can see that only the first instance is ONLINE...the other two are OFFLINE. They've been configured to use the same IP, but different ports. In order to get each server to use it's own settings on a different port, I created multiple copies of server.properties. For example, I created server2.properties for mcserver-2 and edited mcserver-2.cfg to point to the correct configuration file. Any ideas?

**Comment by UltimateByte** [comment]
Did you create them under different users?
Providde `postdetails` output for each of them.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by coult45usmc** [comment]
Initially I wanted to use the Multiple Instance, Single Install approach, but due to limited time to work on this type of stuff I ended up just going with the Single Instance, Multiple Install. That was fairly simple to implement and works fine. Minecraft doesn't require a lot of drive space so that ended up being quick and easy. Thanks.
