### ISSUE TITLE
[Request] Battallion 1944 Support 

### ISSUE THREAD

**Issue by 0xlord** [GameServerManagers/LinuxGSM#1796]
Hello LGSM-Team,

BT44 got released yesterday into Early Access. It is a potential eSport titel with fast competetive gameplay simmilar to CoD 2 and CoD 4 ProMod. Devs released server files for Linux alongside its EA release. They are a workaround in their current state and provided per optional dowload from their site. An shift towards Steam including a proper AppID will be likely seen in the near future (personal guess around summer 2018).

Game-Website: http://battaliongame.com/
Steam-Website: http://store.steampowered.com/app/489940/BATTALION_1944/
Server-Documentation: http://35.189.104.46/Community_Servers
Server-Download: http://35.189.104.46/Community_Servers#Downloading / https://storage.googleapis.com/battalion_public/BattalionLinuxServer_10747.zip as of todays version

Adding BT44 to LGSM would help alot of potential server administrators out and would improve towards the community building efforts from the devs and the community itself. The devs will also implement LAN feature in Q1 18. So the game would also be a good candidate for long live lan party activity. 

Please let me know if I can be of any help.

Thank you alot,
Ben

**Comment by 0xlord** [comment]
Just found this guide about setting up a server. Regarding to the devs documentation it just differs from the starting parameter. Also more insight into (considerable) server settings.

http://steamcommunity.com/sharedfiles/filedetails/?id=1288970621

**Comment by Bara** [comment]
The "official wiki" wiki.battaliongame.com will be redirect to a ip. 💯 👍

**Comment by phit** [comment]
Their forums has no https either, their whole web infrastructure is a mess. 
I looked into making a PR for this after release yesterday, there is currently no reliable way to get the latest server version though. Until then I would hold off.

**Comment by stubbegianni** [comment]
wiki.battaliongame.com/#Downloading

Steam support added

**Comment by dgibbs64** [comment]
Completed in to the latest release
