### ISSUE TITLE
Disable "Continue? [Y/n]" prompt for console

### ISSUE THREAD

**Issue by exwizzard** [GameServerManagers/LinuxGSM#1797]
When typing `/gameserver console` you get a prompt and you have to press enter, is there a way to disable that? I want to go straight to the console when typing `/gameserver console`, I need this feature for a personal project of mine.

**Comment by RobinLabadie** [comment]
Not yet, I made a suggestion about that here, feel free to comment/contribute. 
https://github.com/GameServerManagers/LinuxGSM/issues/1242
