### ISSUE TITLE
after change sdtdserver.xml ,the sever can not be started again

### ISSUE THREAD

**Issue by simon553644686** [GameServerManagers/LinuxGSM#1799]
Please note that this is an issue tracker for **LinuxGSM** related bugs and feature requests and **not** for the games themselves.

**Therefore personal server issues on GitHub will be closed without a kiss.**

Please follow **[this article](https://github.com/GameServerManagers/LinuxGSM/wiki/Support)** for optimal assistance
and do not forget to remove this text before opening the issue.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
