### ISSUE TITLE
downloads 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#1802]
i try ti install cod4 in my aws server ./cod4server install after this 
 its very slow i have good internet connection and its aws and i opened all ports  this is my 11 server (failed) 
may i know why its happen

**Comment by UltimateByte** [comment]
It takes less than 1 minute to download the server file for me. MD5 check takes around 2 minutes, and extraction around 5 minutes (all eyeballed durations). Your location as well as your interconnection with the server play a major role in your download speed. We have been talking about implementing mirrors for the files, but it's not always easy. Where is your server located?
