### ISSUE TITLE
auto clear logs and dem files

### ISSUE THREAD

**Issue by panikajo** [GameServerManagers/LinuxGSM#1804]
Hello, is there a function for auto-cleaning logs and demos by day?

**Comment by Khelgar1** [comment]
Not certain but this might be what you're looking for

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/logs.sh
 
I think it runs when you start the server but it might be possible to run it as a cronjob. Not sure how it handles open logs though, haven't looked through it at all

**Comment by Eagleman7** [comment]
Look at logrotate, it is included with almost all distro's. Logrotate is mainly used for logs on /var/log but can be setup for any directory.

**Comment by panikajo** [comment]
@Khelgar1 not uninstall demo files.

**Comment by UltimateByte** [comment]
If you can think of a log file that is not cleared by LinuxGSM, please tell us which.
Otherwise, adjust the log rotation time within your LinuxGSM settings.
As for demo files, are they saved games from CSGO or something like that? We could handle them as well as log files with a dedicated setting for CSGO and/or any game that supports demos.

**Comment by panikajo** [comment]
@UltimateByte 
`#!/bin/sh/
####################################################
   date=`date +%F`
# Папка с модом игры
   game_mod="cstrike"
   clean_demos="1"
   clean_sourcemod_logs="1"
   clean_server_logs="1"
####################################################
# Очистка Демо-Записей
   if [ "$clean_demos" -eq "1" ]; then
      find ./$game_mod -maxdepth 1 -mtime  +7 -name ".dem" -exec rm {} \;  -print > cleaning_logs_${date}.log
   fi
####################################################
# Очистка логов SourceMod
   if [ "$clean_sourcemod_logs" -eq "1" ]; then
      find ./$game_mod/addons/sourcemod/logs -mtime  +7 -exec rm {} \;  -print >> cleaning_logs_${date}.log
   fi
####################################################
# Очистка логов Server
   if [ "$clean_server_logs" -eq "1" ]; then
      find ./$game_mod/logs -mtime  +7 -exec rm {} \;  -print >> cleaning_logs_${date}.log
   fi
####################################################
# Авто-Удаление логов очистики
   find ./ -maxdepth 1 -mtime  +7 -name "cleaning_logs_*" -exec rm {} \;  -print 
####################################################`

`30 6 * * * cd /home/css_1 && bash ПУТЬ_ДО_СКРИПТА
`

**Comment by UltimateByte** [comment]
?
