### ISSUE TITLE
teamspeak automatic licence acceptance fail

### ISSUE THREAD

**Issue by naxIO** [GameServerManagers/LinuxGSM#1806]
Every time Teamspeak updates its licence, it enforces clients and servers to agree to it, otherwise the server or client wont start.

I just found my TS broken with an entire log file directory full of accept_license_error logs.

In order to resolve this issue,  a file called ``` .ts3server_license_accepted```needs to be present in the TS3 root directory. We should think about adding that automatically, additionally pass a parameter for auto-accept new licences automatically or not (if you want to read it first.)

I post in this repository because it seems that remarks in the server config repository are ignored / not read at all.

**Comment by SB97** [comment]
This problem is also present on the first install

```
Getting privilege key
=================================
IMPORANT! Save these details for later.
Starting the TeamSpeak 3 server
Please set the environment variable TS3SERVER_LICENSE to "accept" in order to accept the license agreement.
Alternatively, create a file named ".ts3server_license_accepted" in the working directory or start the server with the command 
line parameter "license_accepted=1".
To view the license agreement set TS3SERVER_LICENSE to "view" in order to print the license to the console.
Alternatively view the file "LICENSE" in your favorite text viewer yourself.
TeamSpeak 3 server could not start
No server running (ts3server.pid is missing)
    fetching fix.sh...OK
```

**Comment by UltimateByte** [comment]
Is this a new thing? Never experiences that issue.

**Comment by SB97** [comment]
also never had it bevore... but just yesterday i wanted to set up a new TS3 Server and it happend

**Comment by UltimateByte** [comment]
Well, now we perfectly understand the issue. Thanks.

**Comment by gOOvER** [comment]
https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/344/16

**Comment by Tsukijomi** [comment]
How can we fix this now? If i add this file and start the server again i dont get my privilege Key.

**Comment by UltimateByte** [comment]
I PRed a fix. Fixes existing installs. Probably fixes new installs as well, but didn't test yet.

**Comment by SB97** [comment]
`Probably fixes new installs as well, but didn't test yet.`

If you tell me how i can test :)

**Comment by UltimateByte** [comment]
You just need to change your ts3server script's github repository to : hotfix/teamspeak-180220
Then install. Would be awesome if you could test and feedback :)

**Comment by SB97** [comment]
you mean that bevore i install i change the "master" in the script to "hotfix/teamspeak-180220" and than just ./ts3server install ?

**Comment by UltimateByte** [comment]
yep, should work

**Comment by SB97** [comment]
tried it but didn´t get the hotfix repository... 
https://gist.github.com/SB97/5b6a9e9be7a0485b98cbbb1c68e9ccac

will try again tomorow

**Comment by UltimateByte** [comment]
After examinating the Travis test, it seems like the fix didn't work for new installs. I need to work on it a bit more.

**Comment by UltimateByte** [comment]
Fixed.
