### ISSUE TITLE
need script

### ISSUE THREAD

**Issue by panikajo** [GameServerManagers/LinuxGSM#1807]
Прошу помощи.
Подкиньте пожалуйста скрипт, который упаковывает из папки каждый файл в bz2. И называет архив так-же как файл который он упаковал.
Т.е у меня есть в папке файлы 
bsp,jpg,nav,txt 
У них есть название там
agra.txt
xerak.bsp
garag.nav
xrenat.jpg
Юзаем скрипт на выходе получаем.
agra.txt.bz2
xerak.bsp.bz2
garag.nav.bz2
xrenat.jpg.bz2

**Comment by UltimateByte** [comment]
We don't speak your language. + There are rules here. https://github.com/GameServerManagers/LinuxGSM/wiki/Support
