### ISSUE TITLE
update-lgsm is removing files

### ISSUE THREAD

**Issue by dclabry** [GameServerManagers/LinuxGSM#1808]
I ran the update-lgsm command, which I do weekly just to see if anything has been updated, and it failed on the first 2 functions (alert.sh and check_config.sh) and removed the files. At that point I killed the script because it seemed suspicious. Looking at Github I don't see any changes to those files and no reason for them to be removed. 

My first guess is that the curl failed because of some network issue, but the script shouldn't assume that the file needs to be deleted.
![capture](https://user-images.githubusercontent.com/35553252/36331368-22e37cc0-1333-11e8-9903-be20b3fe4f51.JPG)

**Comment by UltimateByte** [comment]
If it fails it's either because of a permission issue or impossibility to acces git through curl.
This has no place on this github and isn't a LinuxGSM issue until proven otherwise.
Mine is perfectly fine btw.
