### ISSUE TITLE
EasyAntiCheat Scout shutting Down

### ISSUE THREAD

**Issue by VincentDercourt** [GameServerManagers/LinuxGSM#1813]
Hello,
since the automatic restart scheduled at 15h my 3 servers no longer miser.
The console returns the result below.

![image](https://i.imgur.com/cvD5M9v.png)

[https://hastebin.com/yuhubikexe](https://hastebin.com/yuhubikexe)

Thank you in advance for your help.

**Comment by kossamuno** [comment]
I have the same problem!

**Comment by VincentDercourt** [comment]
This problem seems to be the same for everyone on linux.
I tried a basic installation without gameservermanagers and the problem is still present.

**Comment by fosspill** [comment]
Contacted facepunch support an hour ago or so. They are already on the case it seems.

**Comment by UltimateByte** [comment]
It seems like adding `-debug` to your start parameter helps as a workaround for now.
To see how to change your start parms, read this https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters

This is nothing LGSM can fix for now until proven otherwise. If you're facepunching yourself because of this issue, that is normal, remember that the game and server are developped by Facepunch.

**Comment by fosspill** [comment]
-debug sadly doesn't seem to work for me, but thank you :)

**Comment by sh1ny** [comment]
Yep, -debug not working here either :(

**Comment by kossamuno** [comment]
Didnt do the trick for me either. Thanks for the attention though UB!

**Comment by UltimateByte** [comment]
Well, it worked yesterday for another user, but maybe the update wasn't out yet.
Does `./rustserver debug` work?

**Comment by UltimateByte** [comment]
So that's a different thing. Well, just wait for Facepunch to put their thumbs out their asses, and google around see if you got a workaround. If you got one, I can implement a hotfix. But this one will most likely require a fix from FP.

**Comment by Achillesfm** [comment]
same problem here i did debug but just have the same shit

`
InitServer: GameServer_Init returned false
Couldn't initialize Steam Server (2973146311)

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Server startup complete
EasyAntiCheat Scout Shutting Down

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

EasyAntiCheat Server Shutting Down

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[Raknet] Server Shutting Down (Shutting Down)
Setting up 4 worker threads for Enlighten.
  Thread -> id: 7fd34ff7b700 -> priority: 1
  Thread -> id: 7fd34f57a700 -> priority: 1
  Thread -> id: 7fd34eb79700 -> priority: 1
  Thread -> id: 7fd34e178700 -> priority: 1
eac_server.so [x64] :: OnUnload()
`

**Comment by gaillafr** [comment]
Hi,

I've been able to launch the server manually by doing this:

```sh
#!/bin/bash

# Do not remove this line
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/steam/server/serverfiles/RustDedicated_Data/Plugins/x86_64"

# Start the server (note that the -logfile argument is used to log to console)
./RustDedicated -batchmode +server.ip XXX.XXX.XXX.XXX +server.port 28015 +server.tickrate 30 +server.hostname "Rust" +server.identity "rustserver" +server.seed 1 +server.maxplayers 80 +server.worldsize 4500 +server.saveinterval 120 +rcon.web 1 +rcon.ip XXX.XXX.XXX.XXX +rcon.port 28016 +rcon.password "CHANGE_ME" -logfile "/home/steam/server/log/server/rustserver-game-2018-02-23-02:44:50.log"
```

I've put the script in `/home/steam/server/serverfiles/test.sh`.

But I'm not able to find where to add the LD_LIBRARY_PATH to I have it in the t-mux session 😞 

So, as I write these lines, I have my process in the foreground for my server to stay up.

**Comment by fosspill** [comment]
So @gaillafr what did you change to make it work?

**Comment by kossamuno** [comment]
Worked for me using the start script gaillafr refered to. For some reason I cant get it to work in a new session.

But what does this mean? Where is the problem, with the linux binary or with LGSM?

**Comment by fosspill** [comment]
Indeed, server starts with that script. 
@UltimateByte you might be interested in this

**Comment by VincentDercourt** [comment]
Thank you for your solution @gaillafr .

For those who wish it here is a script that you have to place in your server and modify according to your configuration.

[https://pastebin.com/HcBshYfK](https://pastebin.com/HcBshYfK)

**Comment by fosspill** [comment]
But, to what I can see lgsm does exactly the same as what this script does. I'm really curious about what caused this.

**Comment by VincentDercourt** [comment]
There was a rust update yesterday.
This caused this bug.
Lgsm has not yet had the time to correct the problem but it will surely be done in the future.

**Comment by VincentDercourt** [comment]
I use a translator.
Sorry if my phrase have errors.

**Comment by determinaft** [comment]
add file /home/rust/lgsm/config-lgsm/rustserver/rustserver.cfg

-executable="./RustDedicated"  
+executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"   
work

**Comment by Achillesfm** [comment]
i'm new on this thing can you guys explain a little bit more? do like a tutorial

**Comment by braxton33** [comment]
Determinaft, your fix did not work for me.
What DID work is:

In your lgsm/config-lgsm/rustserver/rustserver.cfg replace 
executable="./RustDedicated" 
with: executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${homeDir}/serverfiles/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"

**Comment by fosspill** [comment]
executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/serverfiles/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"

This works perfectly for me.

**Comment by braxton33** [comment]
fosspill, what OS are you on? I'm on Centos and that one didn't work.

**Comment by fosspill** [comment]
Interesting, I'm on Ubuntu Server.

**Comment by braxton33** [comment]
Yeah, paths & bash work slightly differently between the two different OSes.

**Comment by FredSaltyNuts** [comment]
@braxton33 Can you please post your changes?

I am on CentOS 7

**Comment by FredSaltyNuts** [comment]
( .... )  /serverfiles/RustDedicated_Data/Plugins/x86_64: No such file or directory

urgh!

**Comment by joshuamfawcett** [comment]
braxton33's fix worked for me though I didnt already have the "executable" line but I added it anyway and the server fired back up as normal.

**Comment by FredSaltyNuts** [comment]
Joshua did you do anything else before that?

**Comment by joshuamfawcett** [comment]
> Joshua did you do anything else before that?

No, apart from doing "./rustserver update" which broke the server I did nothing.

**Comment by FredSaltyNuts** [comment]
Ok..

Is there any line in your rustserver.cfg defining this: 
 homeDir=

?

**Comment by joshuamfawcett** [comment]
Nope there isnt a "homeDir=" line anywhere in there

**Comment by FredSaltyNuts** [comment]
Ok.. I have the exact same setup but the fix doesn't work for me :(

I keep getting file or directory not found

**Comment by FredSaltyNuts** [comment]
command_debug.sh: line 107: LD_LIBRARY_PATH=:/serverfiles/RustDedicated_Data/Plugins/x86_64: No such file or directory

:(

**Comment by fosspill** [comment]
@FredSaltyNuts Did you try the one that works for me?
```executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/serverfiles/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"```

**Comment by FredSaltyNuts** [comment]
Same error..

This must be something simple that I'm overlooking..

**Comment by braxton33** [comment]
@FredSaltyNuts 
If you have a slightly different directory layout than is default you may have to modify it a bit, or if your bash setup doesnt include the home dir mapping.

find your plugins/x86_64 directory, do a pwd to get the full path, and instead of
"${homeDir}/serverfiles/RustDedicated_Data/Plugins/x86_64"
use the output from pwd.

**Comment by Achillesfm** [comment]
too many problems, i'm just gonna wait the launch a fix update. no more to do :(

**Comment by FredSaltyNuts** [comment]
@braxton33 I had thought of that, it's a good call, but adlt also fails here

command_debug.sh: line 107: LD_LIBRARY_PATH=:/home/rustpvp/serverfiles/RustDedicated_Data/Plugins/x86_64: No such file or directory

this is without a doubt the correct path of this server on my machine, and it still fails

I think I have to sit this one out and wait for a fix :(
Thanks anyway guys

**Comment by Achillesfm** [comment]
untill then i will be running the machine on windows server, its heavier but nothing to do

**Comment by Achillesfm** [comment]
its bether to do ./rustserver update every single hour and hope that they launch an fix update

**Comment by sregister** [comment]
I'm still having this issue. Can someone with a working system post the results of `echo $LD_LIBRARY_PATH` I wonder if there is something else in that variable that I'm missing.

**Comment by FredSaltyNuts** [comment]
I searched around for a bit and it seems this is a recurring issue in some Rust updates

This same error has happened over and over again, then gets patched

**Comment by Achillesfm** [comment]
@FredSaltyNuts yeah, yesterday e just updated the server and then this error just started

**Comment by joshuamfawcett** [comment]
@sregister I got no output from `echo $LD_LIBRARY_PATH`

**Comment by sregister** [comment]
Thanks, it must be something else then. I'll keep playing with stuff--and waiting for an update in the meantime i guess :/

**Comment by W0lftastisch** [comment]
@sregister Have you tried to set the server path manually? 
This works in my config:
`executable="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/your/server/RustDedicated_Data/Plugins/x86_64 ./RustDedicated"`

**Comment by FredSaltyNuts** [comment]
@W0lftastisch 
Sadly that doesn't work for some people, but it's worth a shot. It has worked for a few.

**Comment by sregister** [comment]
Yes I was explicit when including that path in the executable line.  

Are these all the right shared objects?

`rustserver@debian:~/serverfiles/RustDedicated_Data/Plugins/x86_64$ ls
libeac_server.so     libRakNet.so    libRustNative.so   steamclient.so
libeasyanticheat.so  libRenderer.so  libsteam_api64.so`

**Comment by sregister** [comment]
After validating the install it seems to be booting now. Thanks for the help.

**Comment by W0lftastisch** [comment]
@FredSaltyNuts In your case, I guess you need to write the `./RustDedicated` at the end. It´s missing here (additional to : LD_LIBRARY_PATH=$LD_LIBRARY_PATH:) 
> command_debug.sh: line 107: LD_LIBRARY_PATH=:/home/rustpvp/serverfiles/RustDedicated_Data/Plugins/x86_64: No such file or directory

@sregister Huh, alright. I´ve checked it with mine, nothing is missing there.

**Comment by UltimateByte** [comment]
Fix published. Please test and feedback on the proper issue: #1817

**Comment by RMefisto** [comment]
Thank you for your solution @gaillafr.

**Comment by kossamuno** [comment]
Thank you @UltimateByte ! Your fix is working for me, I can now run my server with the LGSM script!

**Comment by Achillesfm** [comment]
@UltimateByte you saved my weekend, thank you very much <3

**Comment by UltimateByte** [comment]
Thanks for the feedback and love! Have fun !
