### ISSUE TITLE
Server not starting - Rust Linux LGSM

### ISSUE THREAD

**Issue by Achillesfm** [GameServerManagers/LinuxGSM#1815]
done.
Initializing 10552 entity links
    done.
Initializing 234 stability supports
    done.
Initializing 9641 entity save caches
    done.
Server.Ip = 177.54.156.199
Server.Ip.HostOrder = 2973146311
Couldn't initialize Steam Server (2973146311)
Server startup complete
EasyAntiCheat Scout Shutting Down
EasyAntiCheat Server Shutting Down

there is the log

**Comment by fosspill** [comment]
Rust issue. Nag facepunch.

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
