### ISSUE TITLE
game servers web page offline? 

### ISSUE THREAD

**Issue by Achillesfm** [GameServerManagers/LinuxGSM#1816]
im trying to install rustserver on my linux machine but the web site isn't working

**Comment by UltimateByte** [comment]
@dgibbs64 has been informed. 
Awaiting for the website, just download the script using github and rock on.
`wget https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh`

Make sure you installed dependencies for your game server as well as curl and ca-certificates, at least and you should be fine.

**Comment by UltimateByte** [comment]
Website is now online after Daniel was alerted on his emergency address, he was able to renew the server, after for some reason automatic payment didn't work.
