### ISSUE TITLE
cod4x With the reason: Server fatal crashed: G_FindConfigstringIndex: overflow (309) 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#1818]
my server always down with this reason With the reason: `Server fatal crashed: G_FindConfigstringIndex: overflow (309) ` so i just post my log in cod4x forms they said its custom cod4x you're using thats y its happen  this is the mod im running 
[https://github.com/leiizko/cod4_new_experience](https://github.com/leiizko/cod4_new_experience)
 and cod4x developers said your using edge of cod4x and update it  but i update my server use this cod3 
```
./cod4server ul 
Commands
start         st   | Start the server.
stop          sp   | Stop the server.
restart       r    | Restart the server.
monitor       m    | Check server status and restart if crashed.
test-alert    ta   | Send a test alert.
details       dt   | Display server information.
postdetails   pd   | Post details to hastebin (removing passwords).
update-lgsm   ul   | Check and apply any LinuxGSM updates.
backup        b    | Create backup archives of the server.
console       c    | Access server console.
debug         d    | Start server directly in your terminal.
install       i    | Install the server.
auto-install  ai   | Install the server without prompts.
developer     dev  | Enable developer Mode.
```
(this is available commands)    

my question is how can i update cod4x latest version ?  
thank you for this develop its easy to install all server with in few mins (Y)

**Comment by dgibbs64** [comment]
cod4x is designed to auto update on boot
