### ISSUE TITLE
Rustserver drop on start

### ISSUE THREAD

**Issue by FredSaltyNuts** [GameServerManagers/LinuxGSM#1819]
Rust server was working fine for a long time.
Today I updated it as usual, server update, oxide update, lgsm update.

Now it crashes at start.

I validated the files - OK
Removed every plugin file and restarted - Same problem.

https://hastebin.com/lutevojami

Nothing was changed in the OS, only the server updates and validations.

I tried my best to figure this out, I wish I didn't have to post here.. Sorry :(
I hope this is just me overlooking something incredibly obvious..

In the log file I can see this at the very end:

Facepunch.Steamworks Unity: LinuxPlayer
Facepunch.Steamworks Os: Linux
Facepunch.Steamworks Arch: x64
Couldn't initialize Steam Server (3273004581)

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Server startup complete
EasyAntiCheat Scout Shutting Down

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

EasyAntiCheat Server Shutting Down

(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[Raknet] Server Shutting Down (Shutting Down)
Setting up 12 worker threads for Enlighten.

------------------

As far as I could find, this "DebugBindings.gen.cpp Line: 51" seems to be related to excessive mods, but I removed every single plugin and the error still happens.

I will keep digging around for more info on this error

**Comment by FredSaltyNuts** [comment]
Update:
I removed oxide and the server starts
Reinstalled oxide and the problem comes back.

Attempting a full server reinstall now

**Comment by fosspill** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/1813#issuecomment-367985034
Couple of fixes in there.

**Comment by FredSaltyNuts** [comment]
This is a relief..
It seems Facepunch still have their fists up their @sses..

Closing this one and following the one you referred to.

Thanks!
