### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by panikajo** [GameServerManagers/LinuxGSM#1820]
Error 521 Ray ID: 3f1a00c70fe6265a • 2018-02-23 11:56:38 UTC
Web server is down

**Comment by FredSaltyNuts** [comment]
Confirmed:

Connecting to gameservermanagers.com (gameservermanagers.com)|104.31.93.238|:443... connected.
HTTP request sent, awaiting response... 521 Origin Down
2018-02-23 08:04:38 ERROR 521: Origin Down.

**Comment by UltimateByte** [comment]
Duplicate, please open your eyes before opening an issue.
