### ISSUE TITLE
sdtdserver gsquery.py ERROR: Unable to receive

### ISSUE THREAD

**Issue by miztertea** [GameServerManagers/LinuxGSM#1821]
# 7DTD Server
./sdtdserver postdetails - https://hastebin.com/jukuqohuwa

When executing ./sdtdserver monitor the following error is received:
[  OK  ] Monitor sdtdserver: Checking session: OK
[ FAIL ] Monitor sdtdserver: Querying port: XXX.XXX.XXX.XXX:26901 : 3/1 : ERROR: Unable to receive
[ FAIL ] Monitor sdtdserver: Querying port: 104.251.211.152:26901 : 60/5 : FAIL

All ports are open, I have also tried running it to loopback 127.0.0.1 and have tried different engines unreal and unreal2 and always the same error.

Ideas?

**Comment by UltimateByte** [comment]
I have an idea
1) You don't have enough RAM for this game server
2) You don't have any swap
3) You'd better follow our guidance and don't post this kind of stuff on github anymore or i'll get mad pretty quick https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by miztertea** [comment]
Server has 6GB of of RAM, should be more than ample, as with 8 players on the server I'm barely at 20% utilization.

**Comment by UltimateByte** [comment]
A machine with no swap is totally stupid, especially with 7dtd which uses SWAP even when penty of RAM is available. This game server is an unoptimized factory of shit. You have your answer, now please get out this git before I get mad. One more answer of that kind and you're banned.

**Comment by miztertea** [comment]
Hi @UltimateByte, 

Thank you for your quick response.  I have created a swap file as you suggested and unfortunately the same issue with the monitoring is still occurring.  Do you have any other ideas as to what may be causing this?

https://hastebin.com/itikezubew

**Comment by UltimateByte** [comment]
I might have ideas. But not on fucking github. How should I say that?

**Comment by UltimateByte** [comment]
This place is for LinuxGSM development, not YOUR personal issue.
