### ISSUE TITLE
have problem fastdl lgsm

### ISSUE THREAD

**Issue by panikajo** [GameServerManagers/LinuxGSM#1823]
install fast dl csgo server
DecompressBZipToDisk: 'maps/de_dust2.bsp.bz2' too big (max 150.0 megabytes, use launch option -maxdownloadfilesizemb N to override).
wtf?

**Comment by UltimateByte** [comment]
Follow rules, and provide the context for the error, otherwise it's useless to open an issue.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
