### ISSUE TITLE
Rust Server cant stay alive

### ISSUE THREAD

**Issue by Lukas9914** [GameServerManagers/LinuxGSM#1826]
Game: Rust
Output: https://hastebin.com/gabesumako
Logs: No Error 
Hardware: 

- CPU: 12Cores
- RAM 32GB DDR4ECC
- More than 1TB
- Bandwidth: Something between 1GBs and 100 Mbs

My problem is, that the Rustserver cant stay alive if i start it with `./rustserver start`. The Server is starting correctly but after the it loaded to 100% it will stop without any message. If i start the Server with `./rustserver debug` and stay in the console the server is working fine.

**Comment by UltimateByte** [comment]
Is this a LinuxGSM script issue? No.
This issue doesn't belong to Github.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
Thanks
