### ISSUE TITLE
[Server request] Call of Duty 4

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#183]
Looks like its possible to have a Linux COD 4 server. This is still very popular so I think it would be a good idea to create a script for this game

**Comment by lanrenags** [comment]
Is it ok for you if I try to create a script for cod4 servers? 
The biggest problem is, to host the serverfiles. They are around 7 GB.

Is it possible for you to host such big files?

Best Regards

lanrenags

**Comment by dgibbs64** [comment]
Yeah you can have a go at creating it. The only issue is the server files and of hosting the server files is allowed etc. Would you be able to provide any info or evidence that it's OK to distribute the content. If not it would be up to the server administrator to provide the content

**Comment by dgibbs64** [comment]
https://www.vultr.com/docs/setup-a-call-of-duty-4-server-on-debian-7-x64

Might be useful?

**Comment by AzaZPPL** [comment]
Any updates on this?

**Comment by dgibbs64** [comment]
I will be working on a feature to download and extract files so servers that dont run on steamcmd are easier to install. So that may make it easier to create this type of server

**Comment by Scarsz** [comment]
Look into http://cod4x.me/ for possibly making this easier

**Comment by dgibbs64** [comment]
now released

**Comment by ingre** [comment]
hello all, I have problem, make how you explian but dont start server 
./cod4server st
[ERROR ] Starting cod4server: Checking dependencies: missing: python unzip binutils bc lib32gcc1 libstdc++6:i386

Warning! cod4server does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install python unzip binutils bc lib32gcc1 libstdc++6:i386

[ .... ] Starting cod4server: Check IPno server running on /tmp/tmux-1001/default
[ FAIL ] Starting cod4server: Unable to start LinuxGSM

**Comment by UltimateByte** [comment]
@ingre Install your dependencies yourself or give your user sudo access.
Also Github is for develoment only: https://github.com/GameServerManagers/LinuxGSM/wiki/Support
