### ISSUE TITLE
[Rust] Wipe command needs update

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1830]
It appears according to feedback that Rust changed their files naming again, so... A rework will need to be done to the wipe command.

Quote from Discord:

> AkalaHD - Today at 6:36 PM
> @lumpa Delete these files manually:
> proceduralmap.3000.2268374.158.map
> proceduralmap.3000.2268374.158.sav
> sv.files.db or sv.files.0.db
> player.deaths.db
> And if you’re wiping BPs delete player.blueprints.db 
> 
> I don’t know if you need to delete sv.files.db and player.deaths.db
> 
> These can all be found in this directory:
> /home/rustserver/serverfiles/server/rustserver/
> The wipe command should work for the map files
> Deleting sv.files.db and player.deaths.db won’t do anything as far as I know. I usually just delete them.
> An update to the command to delete these automatically would be nice
> Im sure it’s on the way

**Comment by sregister** [comment]
Many (if not most) rust admins wipe the map many times before they wipe blueprints. Previous behavior with wipe was to wipe just the map, and bps were something that needed to be done manually. 

A "wipe-all" command, which wipes both would be nice but after a brief skim of the code a whole new command file might need to be implemented to keep consistency.

Whatever is done I don't think BPs should be included in the "wipe" command. If bps are included in wipe, this would be a change in functionality of the command and would probably result in data being deleted that the server admins don't expect. This would be a very facepunch-esque thing to do and should be avoided imo.

**Comment by UltimateByte** [comment]
Why not! Do you have a clear proposition of what commands to have and what they should wipe? I'm not really into Rust anymore, so any advice is welcome. Also, if you can confirm which files contain which information, you'll highly simplify my work.

**Comment by sregister** [comment]
I think should do it.

wipe command:
- rm /home/rustserver/serverfiles/server/rustserver/proceduralmap.*.map
- rm /home/rustserver/serverfiles/server/rustserver/proceduralmap.*.sav
- rm /home/rustserver/serverfiles/server/rustserver/player.deaths.*.db (if exists)
- rm /home/rustserver/serverfiles/server/rustserver/sv.files.*.db  (if exists)

wipe-all:
- all files above
- rm /home/rustserver/serverfiles/server/rustserver/player.blueprints.*.db  (if exists)

**Comment by UltimateByte** [comment]
This is now done and works like a charm. Will be up for the next release.
