### ISSUE TITLE
Arma 3 web page corrections

### ISSUE THREAD

**Issue by Khelgar1** [GameServerManagers/LinuxGSM#1831]
The web page for the arma3 server shows a couple of errant backslashes in the password field and a double forward slash in the nano command... Caused some confusion
![image](https://user-images.githubusercontent.com/23195823/37103975-6c4f2356-2223-11e8-8c49-62a67015eb2b.png)

**Comment by UltimateByte** [comment]
No issue on the correct website:
https://gameservermanagers.com/lgsm/arma3server/

(As far as I know, linuxgsm.com is not finalized yet), so don't bother reporting issues about it.

**Comment by Khelgar1** [comment]
The site is live, if it isn't supposed to be used it should be taken down. I didn't even notice it was the new site. Regardless its giving incorrect information and needs to be changed.

**Comment by UltimateByte** [comment]
How did you find it then? There was just a link of Daniel on Discord saying something like "Hey, look what I'm working on!"

**Comment by Khelgar1** [comment]
It was linked by a guy on discord who was trying to set up an arma 3 server and failing because he copied that. So it is being found.

**Comment by UltimateByte** [comment]
Haha, well, he must have clicked on the link I just screenshoted then. :)

**Comment by UltimateByte** [comment]
BTW, thanks for reporting, it could have been a real issue, good to see you're always ready to warn when you see an abnomaly ;)
