### ISSUE TITLE
Server Request Eco

### ISSUE THREAD

**Issue by Astaelan** [GameServerManagers/LinuxGSM#1833]
Would be nice to have a system to maintain the newly released game Eco.
I will look at writing this myself if I find the time, but posted this issue in case someone else gets to it first.

http://store.steampowered.com/app/382310/Eco/
https://s3-us-west-2.amazonaws.com/eco-releases/

Requires Mono (Unity based), and not a whole lot else.

If you're not familiar with AWS, the second link will give you an XML manifest of the filenames available at the same location, simply add the filename to the same link to obtain it, for example:

https://s3-us-west-2.amazonaws.com/eco-releases/EcoServer_v0.7.0.0-beta-staging-b1111b5c.zip

Steam Distribution of Eco Server
https://steamdb.info/app/739590/

**Comment by GlennKintscher** [comment]
I haven't done much in Linux yet, but I'd also like to see an Eco Server here - so I just tried it.

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/1863

**Comment by dgibbs64** [comment]
Looks like you need to own the game to use the server.....I hate it when they do that. I will have to try and contact the game developers and see if they can alter this

**Comment by dgibbs64** [comment]
I have emailed them to see if they will change to anonymous login.

**Comment by UltimateByte** [comment]
Or at least providing you with a license... Considering what you are doing for them...

**Comment by dgibbs64** [comment]
They are passing the info to there developers and shoudl be contacting me sometime next week

**Comment by Holli82** [comment]
Hey @dgibbs64  @GlennKintscher maybe its that of interest.
Looking here: https://github.com/kicker22004/ECO_LINUX_SERVER_MANAGER

He is using not Steam to Fetch the Serverfiles and its more **Universal without Steam**.

**Comment by dgibbs64** [comment]
Thanks for the info @Holli82. SteamCMD is by far the preferred method for LinuxGSM as its really easy to install and update game servers. I will not rule out this method as it uses this link to get the server version info https://s3-us-west-2.amazonaws.com/eco-releases/ so could work. It would however take a lot more time than using SteamCMD

**Comment by Holli82** [comment]
Were Only a Idea for this problem with the Login by Steam at the moment without own the game.

**Comment by dgibbs64** [comment]
@Holli82 Yeah hopefully they will come back to me in a few days with some good news. Since there builds are freely available on AWS I cannot see why they wouldn't make them available on SteamCMD.

**Comment by Timi7007** [comment]
Any updates on this? 
I tested anonymous login successfully yesterday, following the instructions from [the wiki](https://eco.gamepedia.com/Setting_Up_a_Server#Server_Through_SteamCMD).

**Comment by dgibbs64** [comment]
Hey, Yeah it should be ready to go. However because of high work load and lots going on for me currently I have not had any time to work on LinuxGSM recently so have not completed the latest release. I will be on this as soon as I can. I really want to get back to developing.

**Comment by dgibbs64** [comment]
I have no completed the development of Eco and will be in the next release.
