### ISSUE TITLE
lgsm csgoserver Multiple Server auto-exit instances

### ISSUE THREAD

**Issue by germanllop** [GameServerManagers/LinuxGSM#1834]
Hello, I was running one server without any fuzz, it was perfect, but there are issues when running two in the same hardware, what I did was follow the wiki (https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers) and I runn the installatio again so I can have two instances running wich it was fine, but when I stopped for example ./csgoservser stop, the second server that was running ./csgoserver-2 also stopped and people that where playing just got disconnected, when I did ./csgoserver-2 monitor it says it's stopped and it will start the server, this happened to me also viceversa.
The second thing that I've tried is to install on a different folder, both servers sepparate so I can do different mods on each server but the same happened.

Here some more info about my server:
OS: Debian 9.1
Hardrive: 200GB free space
Ports: 27015/27016
ClientPort: 27005/27006
sourcetvport: 27020/27021

I followed every step on the guide and each server works perfectly, but I have that issue, I even tried unbinding the ip address and set it to 0.0.0.0 that is autodiscover.
As I mentioned, the servers worked fine, just that issue.

**Comment by UltimateByte** [comment]
Change your instance name.
Read this
https://github.com/GameServerManagers/LinuxGSM/issues/1784
