### ISSUE TITLE
[New Server] Rising World

### ISSUE THREAD

**Issue by BogusCurry** [GameServerManagers/LinuxGSM#1835]
Hello all ;D
I would request make for Rising World, that is a survival game, run under Windows, (Mac) and Linux ;D 

https://www.rising-world.net/
http://store.steampowered.com/app/324080/Rising_World/
https://forum.rising-world.net/thread/7827-set-up-a-server-with-steamcmd/

Greetings
Bogus

**Comment by UltimateByte** [comment]
Forgot the most important:
https://steamdb.info/app/339010/

Gosh, their "tutorial" is pretty much empty... No start parameters info, no ports info... Empty, wtf is that, do they really want people to make servers for this? Please let me know if you find a better doc. It will help whoever adds the game server to LinuxGSM.

**Comment by BogusCurry** [comment]
Ok, here I found a request post for LinuxGSM for 3 years .. lol There are you found all infos ;D I hope that is enough ;D
https://github.com/GameServerManagers/LinuxGSM/issues/470

**Comment by UltimateByte** [comment]
Oh lol, didn't even remember that. Spannerman never replied to me on Steam, so... Never did work on it. 
Well, closing this issue then.
