### ISSUE TITLE
[ FAIL ] Install insserver: Permissions issues found Information! 

### ISSUE THREAD

**Issue by diveyez** [GameServerManagers/LinuxGSM#1837]
[ FAIL ] Install insserver: Permissions issues found
Information! The following files are not executable:

Fix: chmod +x -R /home/username/LinuxGSM/lgsm/functions/ suggestion added in README.md

**Comment by UltimateByte** [comment]
Read your error message to get the fix to your issue...

And read this to be fixed about how to use Github:
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
