### ISSUE TITLE
insserver forcing map and mode against config settings

### ISSUE THREAD

**Issue by diveyez** [GameServerManagers/LinuxGSM#1838]
gamesrv@base-gaming:~/LinuxGSM$ ./insserver start
[ WARN ] _default.cfg has been altered. reloading config.
    copying _default.cfg...OK
I even edited that file, just to see why its overwriting my insserver.cfg map/mode selection

It is using defaultmap value from _default.cfg
and it is not loading the issued game mode and maps from insserver.cfg

**Comment by UltimateByte** [comment]
You should never edit _default.cfg since it's a default example that is intended to be always synced with the latest config file available.

Are you sure to do it right?
https://github.com/GameServerManagers/LinuxGSM/wiki/LinuxGSM-Config
