### ISSUE TITLE
Travis-CI failing because of changes to backup realpath

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1839]
@cedarlug please could you investigate the source of buids failure in Travis-CI. It relates to your improvement of backups https://github.com/GameServerManagers/LinuxGSM/pull/1786 

error is.

    [ INFO ] Backup tests_jc2server.sh: Problem identifying the previous backup directory for exclusion.

**Comment by cedarlug** [comment]
Will dive in...

**Comment by dgibbs64** [comment]
#1845

**Comment by dgibbs64** [comment]
connects to #1845

**Comment by h3o66** [comment]
Closing - becasue moving to github actions
