### ISSUE TITLE
[tmux]  create session failed CentOS 7

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#184]
-Centos 7-
[ .... ] Starting csgo-server: CSGO Server create session failed: ./srcds_run -game csgo -usercon -strictportbind -ip ****\* -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map de_dust2_se +servercfgfile csgo-server.cfg -maxplayers_override 32 +mapgroup mg_dust_se +game_mode 0 +game_type 0: Operation not permitted

[ FAIL ] Starting csgo-server: Failed to start CSGO Server

http://danielgibbs.co.uk/lgsm/csgoserver/#comment-1506666129

This issue. Its a problem with Tmux on CentOS 7.

**Comment by dgibbs64** [comment]
I have experienced this issue again

as @RyanMonkey advised his command example worked for me. I will look in to trying to find a way for the script to resolve this issue.

**Comment by Shipwreck50** [comment]
I have a similar problem with Centos 7 on insurgency 

ins-server: Starting: tmux returned the following error
create session failed: ./srcds_linux -game insurgency -strictportbind -ip 91.121.222.194 -port 27015 +clientport 27005 +tv_port 27020 +map ministry +servercfgfile ins-server.cfg -maxplayers 16: Operation not permitted

**Comment by dgibbs64** [comment]
Issue has now been addressed withing LGSM
