### ISSUE TITLE
[Code] var=$(whatever) does not need surrounding quotes

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1841]
`var=$(echo "whatever")` is the same as `var="$(echo "whatever")"` : it keeps spaces and line jumps just like double quotes would.
We can standardize this to keep the way without double quotes since they are not needed.

Sample output:

```
[root@webmastered ~]# var=$(echo "whatever is here") ; echo "${var}"
whatever is here
[root@webmastered ~]# var=$(echo "whatever is
>  here") ; echo "${var}"
whatever is
 here
```

**Comment by dgibbs64** [comment]
@UltimateByte to clarify all vars should be as follows

` var=$(echo "whatever is here")`
