### ISSUE TITLE
Multiple servers under one user

### ISSUE THREAD

**Issue by vadrozh** [GameServerManagers/LinuxGSM#1848]
It will be good if you add support of running multiple servers under ONE user

**Comment by Grimston** [comment]
Please read the Wiki: 
https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers

**Comment by vadrozh** [comment]
I red it. And?

**Comment by vadrozh** [comment]
I don't want to run multiple servers by one user

**Comment by braktar** [comment]
Could you explain a bit more your point ? I don't get the difference between 
"running multiple servers under ONE user" and "run multiple servers by one user"

**Comment by vadrozh** [comment]
I want to have only one user for servers. And run different servers under him.

**Comment by UltimateByte** [comment]
Then re read the wiki without skipping lines?

**Comment by vadrozh** [comment]
I want to have only one user for servers. And run different servers under him.
