### ISSUE TITLE
start parameter

### ISSUE THREAD

**Issue by Mobulos** [GameServerManagers/LinuxGSM#1851]
Ich fürder mir Startparameter wünschen, also Parameter mit welchen man bestimmen kann wie das Spiel gestartet werden soll.
Zum Beispiel dass man in der Start Datei (Der Code mit welchem der Server gestartet wird) Parameter hinzufügen kann wie zum Beispiel eine Steam Collection bei Garrys Mod

**Comment by marvinlehmann** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters
