### ISSUE TITLE
teamspeak3 line 90: jq: command not found

### ISSUE THREAD

**Issue by ptrj** [GameServerManagers/LinuxGSM#1852]
Hi,
I have problem to upgrade teamspeak3 server
I use CentOS 7

> $ cat /etc/*-release
> CentOS Linux release 7.4.1708 (Core)
> NAME="CentOS Linux"
> VERSION="7 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="7"
> PRETTY_NAME="CentOS Linux 7 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:7"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-7"
> CENTOS_MANTISBT_PROJECT_VERSION="7"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="7"
> 
> CentOS Linux release 7.4.1708 (Core)
> CentOS Linux release 7.4.1708 (Core) 

Console output: https://gist.github.com/ptrj/390d0c9c7b707b3990a530d517aea6ef

Thank you

**Comment by dgibbs64** [comment]
Thanks I will investigate

**Comment by UltimateByte** [comment]
I believe the only issue here is to have jq as a requirement.
In the meantime, can you try installing the dependency and see if it helps?

**Comment by dgibbs64** [comment]
Issue now resolved
