### ISSUE TITLE
update_factorio.sh doesn't handle `latest` as valid version

### ISSUE THREAD

**Issue by fosted3** [GameServerManagers/LinuxGSM#1853]
Game server: factorio
Error output:
fctrserver@factorio:~$ ./fctrserver update
[  OK  ] Update fctrserver: Checking for update: factorio.com/home/fctrserver/lgsm/functions/update_factorio.sh: line 107: [: : integer expression expected

No update available:
        Current build: 0.16.28 linux64 experimental
        Available build: latest linux64 experimental

[  OK  ] Update fctrserver: No update available

Details: https://hastebin.com/renufadoke.sql

**Comment by UltimateByte** [comment]
Your issue was the first, but @kyreeth had a fix, so I leave his open :p You allowed confirming the issue and provided postdetails, so it was useful, thanks for reporting. ;)
