### ISSUE TITLE
Factorio changed download page format

### ISSUE THREAD

**Issue by kyreeth** [GameServerManagers/LinuxGSM#1854]
For at least the experimental branch, the parsing of the download-headless page at the top of fn_update_factorio_availablebuild fails, specifically the curl | grep now matches a generic download link before the list of links that contain version numbers.

I fixed it by changing ‘head -n 1’ to ‘head -n 2 | tail -n 1’.

**Comment by UltimateByte** [comment]
Samze as #1853 ?

**Comment by kyreeth** [comment]
Yep, same.

**Comment by dgibbs64** [comment]
Hotfix has now been released https://github.com/GameServerManagers/LinuxGSM/releases/tag/180318.3

**Comment by kyreeth** [comment]
Please apply this to the ‘=“stable”’ case also.

**Comment by dgibbs64** [comment]
Fix is already applied to both branches. I have tested myself
