### ISSUE TITLE
gsquery.py failed to query: ERROR: Unable to receive

### ISSUE THREAD

**Issue by AntoineAngel** [GameServerManagers/LinuxGSM#1855]
Hello, around 19h my server arma 3 did not stop to restart every 5 minutes, I look is I find this error: gsquery.py failed to query: ERROR: Unable to receive

Can you help me ?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by AntoineAngel** [comment]
arma3@eriagaming:~$ ./arma3server postdetails
[  OK  ] Postdetails arma3server: Posting details to hastebin.com for 30D
  Please share the following url for support: https://hastebin.com/<!DOCTYPE html>
<html>
<head>
width=device-width, initial-scale=1

<title>Application Error</title>

                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
</head>
<body>

</body>
</html>
arma3@eriagaming:~$
