### ISSUE TITLE
gsquery.py failed to query: ERROR: Unable to receive

### ISSUE THREAD

**Issue by AntoineAngel** [GameServerManagers/LinuxGSM#1856]
Hello, around 19h my server arma 3 did not stop to restart every 5 minutes, I look is I find this error: gsquery.py failed to query: ERROR: Unable to receive

Can you help me ?

> arma3@eriagaming:~$ ./arma3server postdetails
> [ OK ] Postdetails arma3server: Posting details to hastebin.com for 30D
> Please share the following url for support: https://hastebin.com/
> 
> width=device-width, initial-scale=1 <title>Application Error</title>
>               html,body,iframe {
>                     margin: 0;
>                     padding: 0;
>               }
>               html,body {
>                     height: 100%;
>                     overflow: hidden;
>               }
>               iframe {
>                     width: 100%;
>                     height: 100%;
>                     border: 0;
>               }
>             </style>
> arma3@eriagaming:~$ uname -a
> Linux eriagaming 2.6.32-042stab120.11 #1 SMP Wed Nov 16 12:05:45 MSK 2016 x86_64 GNU/Linux
> 
> arma3@eriagaming:~$ ldd --version
> ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
> Copyright © 2014 Free Software Foundation, Inc.
> Ce logiciel est libre; voir les sources pour les conditions de
> reproduction. AUCUNE garantie n'est donnée; tant pour des raisons
> COMMERCIALES que pour RÉPONDRE À UN BESOIN PARTICULIER.
> Écrits par Roland McGrath et Ulrich Drepper.
> 
> arma3@eriagaming:~$ tmux -V
> tmux 1.9

**Comment by UltimateByte** [comment]
Are you kidding me? Can't you even read two damn lines?
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
Next post like this is a permaban...
