### ISSUE TITLE
Little inconsistency between details & postdetails

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1857]
Scenario : 
* Server with one IP
* Game server has no IP binding

Result: 
* `details` will show the only available local IP, example `192.168.1.99`
* `postdetails` will show `0.0.0.0`

Tested with kf2server, probably true for others as well.

**Comment by dgibbs64** [comment]
a0ade18b3f62245f09c0a28eaa889f88b24f5284
