### ISSUE TITLE
Problem downloading a map from my dedicated server to the client. CSGO

### ISSUE THREAD

**Issue by aprats1** [GameServerManagers/LinuxGSM#1858]
Hi, I hope you can understand my English.

I have a dedicated csgo server.  I have 1 custom map on the server. 
When I connect to the server with the client, the map starts downloading but when it reaches 100%, this appears and the game never starts. 

https://imgur.com/a/3GMPT

I have tried 3 different maps, and the result is always the same.

The only way to cancel this is to shut down the server.

When loading an official map everything works correctly.

Why would this happen?

Thank you very much.

**Comment by aprats1** [comment]
I just found out that if I type `sv_allowupload 1` in the client console everything works correctly. 

It shouldn't be like this. people have to be able to download the maps without having to activate the game console. 

Any ideas?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
