### ISSUE TITLE
Custom Difficulty settings Arma3

### ISSUE THREAD

**Issue by ToffelsKater** [GameServerManagers/LinuxGSM#1859]
Hi
i'm trying to figure out where i can set custom dufficulty settings for Arma3, since there is no documentation, is there someone who can tell me where i can set up Custom difficulty. THX

`fn_parms()
{
parms="-ip=${ip} -port=${port} -cfg=${networkcfgfullpath} -config=${servercfgfullpath} -mod=${mods} -servermod=${servermods} -bepath=${bepath} -loadmissiontomemory -name=player"
}`

have this in common.cfg but where is the player.arma3profile? since the server dont create one by itself

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
