### ISSUE TITLE
Deathmatch Classic server won't install properly

### ISSUE THREAD

**Issue by crackerjam** [GameServerManagers/LinuxGSM#1861]
Hello! I'm trying to set up a DMC server, using the instructions here: https://linuxgsm.com/lgsm/dmcserver/

However, the game files don't seem to be downloading properly. "dmcserver debug" shows this output:

```
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 40
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad
email debug.log to linux@valvesoftware.com
```
In the "serverfiles/dmc" folder, there is only "dmcserver.cfg" and a "logs" directory, no game files.

I've tried running "dmcserver update", "dmcserver force-update", and "dmcserver validate" multiple times without any luck.

**Comment by dgibbs64** [comment]
It might be related to this https://danielgibbs.co.uk/2017/10/hlds-steamcmd-workaround-appid-90-part-ii/

**Comment by crackerjam** [comment]
@dgibbs64 After talking with Valve directly, it looks like this is the command that will fix it, adding the "app_info_print 70" statement while you're installing 40.

./steamcmd.sh +login <USERNAME> <PASSWORD> +app_info_print 70 +force_install_dir /home/steam/Steam/dmcserver +app_update 40 validate +quit

**Comment by dgibbs64** [comment]
I will add this for all gold source servers. Might help them out too

**Comment by dgibbs64** [comment]
We shall see how that goes

**Comment by dgibbs64** [comment]
Placed in feedback will automatically close after 30 days
