### ISSUE TITLE
Factorio .16 update

### ISSUE THREAD

**Issue by disconsented** [GameServerManagers/LinuxGSM#1864]
```bash
[fctrserver@nikola-server ~]$ ./fctrserver update
[  OK  ] Update fctrserver: Checking for update: factorio.com/home/fctrserver/lgsm/functions/update_factorio.sh: line 107: [: : integer expression expected


No update available:
	Current build: 0.15.40 linux64 stable
	Available build: stable linux64 stable
```

As per the above, the .16 update doesn't work erroring out with the above.

Apparently, a fresh install still works so I'll update that this once I give it a try

**Comment by disconsented** [comment]
[.16 was just made stable](https://factorio.com/blog/post/016-stable)

**Comment by MypowerHD** [comment]
hot fix is just an hour old, just update lgsm :+1:
