### ISSUE TITLE
wrong library version in dependency list

### ISSUE THREAD

**Issue by Blueshawk** [GameServerManagers/LinuxGSM#1866]
Just a quick note devs might want to look into, when installing  LinuxGSM for coduo on a xubuntu 16.04 the dependency copy/paste ver.6 but server calls for libstdc++.so.5 ,installing from ppa fixed the problem once I found it using the debug feature. Hope to save the next guy some trouble.
Cheers and long live open source developers! 
 Ray Wells

**Comment by dgibbs64** [comment]
Thanks fix will be rolled out next release
