### ISSUE TITLE
GLIBC_2.18 is now required by Factorio 0.16

### ISSUE THREAD

**Issue by trexguo** [GameServerManagers/LinuxGSM#1867]
https://github.com/GameServerManagers/LinuxGSM/blob/2f64331a7531ed417e1b47ad4602226598e21712/lgsm/functions/info_glibc.sh#L42

GLIBC_2.18 is now required by 0.16 (stable) #1864 

> https://wiki.factorio.com/Multiplayer
> https://forums.factorio.com/viewtopic.php?f=49&t=54619
> https://forums.factorio.com/viewtopic.php?t=54654#p324493

**Comment by dgibbs64** [comment]
Thanks for the info

**Comment by dgibbs64** [comment]
0d322112a354879a885fbad331d1b46aaf5edbf4

**Comment by trexguo** [comment]
Sorry to reopen this but do we need to update libc.so.6 in the lib?

**Comment by dgibbs64** [comment]
CentOS 7 does not support glibc 2.18. Glibc fixes only work up to glibc 2.15 (I have tested with higher versions before)
