### ISSUE TITLE
Factorio Update Compares Current Version Number to the Word "stable"

### ISSUE THREAD

**Issue by fanuch** [GameServerManagers/LinuxGSM#1869]
Updating Factorio results in an expected numerical version number is giving the word "**stable**"

Line 80 of `lgsm/functions/update_factorio.sh`: 

```
availablebuild=$(curl -s https://www.factorio.com/download-headless | grep 'headless/linux64' | head -n 1 | grep -oP '(?<=get-download/).*?(?=/)')
```
Curl results in the word `stable` which gives this error on update:

```
/home/fctrserver/lgsm/functions/update_factorio.sh: line 104: [: : integer expression expected
```

as it compares the latest version to the current version as integers

I propose changing the  `grep 'headless/linux64' ` to `grep -e 'get-download\/0\..*'` which will grab the topmost version number, as the site presents versions in descending order.

This would make the following command, which has been tested and working on my update from 0.1540 to 0.16.36:

```
availablebuild=$(curl -s https://www.factorio.com/download-headless | grep -e 'get-download\/0\..*' | head -n 1 | grep -oP '(?<=get-download/).*?(?=/)')
```

Limitation of my fix is if Factorio moves away from 0.x to 1.x release in the future.

If that's okay with you, I can do a PR with that fix.

**Comment by UltimateByte** [comment]
This is supposed to be hotfixed already, did you update your LinuxGSM ?

**Comment by UltimateByte** [comment]
Ref: #1864
