### ISSUE TITLE
Rust server wont start 

### ISSUE THREAD

**Issue by TheFinestSurgeon** [GameServerManagers/LinuxGSM#1870]
Same issue as this guy https://github.com/GameServerManagers/LinuxGSM/issues/1773
If the server is ran from /serverfiles/runds.sh it will work fine if ran used linuxGSM it will fail

Facepunch.Steamworks Unity: LinuxPlayer
Facepunch.Steamworks Os: Linux
Facepunch.Steamworks Arch: x64
Fallback handler could not load library /home/Minecraft/Rust/serverfiles/RustDedicated_Data/Mono/x86_64/libsteam_api64.so
Fallback handler could not load library /home/Minecraft/Rust/serverfiles/RustDedicated_Data/Mono/x86_64/libsteam_api64.so

https://hastebin.com/ajefezihaz
https://hastebin.com/ikupufapub

**Comment by UltimateByte** [comment]
It doesn't seem like a global issue. The only common point between your install and the one in #1773 is the weird installation path. I believe it would help to install the server in the ~ (home dir) of a freshly created user. Please try it out and feedback.

**Comment by TheFinestSurgeon** [comment]
This did fix the issue

**Comment by TheFinestSurgeon** [comment]
On a unrelated note trying to run rust on hapis is very difficult because you have to 

> remove the +server.seed and +server.worldsize definitions from your startup and add +server.level "HapisIsland"

**Comment by UltimateByte** [comment]
Thanks for the feedback :)
