### ISSUE TITLE
If only 1 IP address insert in to game config

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1872]
To save effort on the admins part it should be possible to insert the IP address of the server into a game config if only one address exists

**Comment by dgibbs64** [comment]
Related to #1741

**Comment by dgibbs64** [comment]
Update to this. If only one IP address then ideally inserting an up address into a config should not be required

**Comment by h3o66** [comment]
Connected to #3015

**Comment by dgibbs64** [comment]
PR #3015 resolved this issue. Closing
