### ISSUE TITLE
Console command fix

### ISSUE THREAD

**Issue by Icicleskill** [GameServerManagers/LinuxGSM#1876]
I downloaded LGSM and installed HL2 DM and CSGO last night and noticed I could not rcon console to the services. I was getting an error stating "session not found: =csgoserver"

I notice that in the command_console.sh it was written as 

tmux attach-session -t="${servicename}" <-notice the "=" next to service name

I removed the "=" and everything is working as it should. Below is what I believe it should be. 

tmux attach-session -t "${servicename}"

Just wanted to point this out! Thanks for all the hard work!

**Comment by UltimateByte** [comment]
I believe it is a residue from these: 
https://github.com/GameServerManagers/LinuxGSM/commit/14efacbdaca024630331468164fe57097cb46497#diff-cdb41d9cd0faef743e8fb45e62d25fcf
https://github.com/GameServerManagers/LinuxGSM/commit/8faffe4ab81f5b673830b84ae5f78b5856e3cac7#diff-cdb41d9cd0faef743e8fb45e62d25fcf

@dgibbs64 might confirm this.

**Comment by dgibbs64** [comment]
Yeah this is an issue to do with tmux closing the wrong sessions. It's a massive pain.

**Comment by UltimateByte** [comment]
Fix is easy
Edit `lgsm/functions/command_console.sh`
Change: `tmux attach-session -t="${servicename}"`
With: `tmux attach-session -t "${servicename}"`
