### ISSUE TITLE
Unable to stop (servicename)

### ISSUE THREAD

**Issue by TheGamingG3** [GameServerManagers/LinuxGSM#1880]
To sadden for my bad English, I am French.
I had an error during the ruling of my servers Linux under debian 8 Wheeze 

Unable to stop (servicename)

To solve it go in / lgsm / functions / command_stop.sh

Then go to the line **266** 

**Original** 
`tmux kill-session -t="${servicename}" > /dev/null 2>&1`

**Corrected**
`tmux kill-session -t "${servicename}" > /dev/null 2>&1`

**Comment by UltimateByte** [comment]
Thanks for your concern.
There was already an issue for that, and this was just fixed.
https://github.com/GameServerManagers/LinuxGSM/issues/1876

Update your LinuxGSM's functions (./gameserver uf) to get the fix.
