### ISSUE TITLE
Debug command file name too long error

### ISSUE THREAD

**Issue by RussianRonin** [GameServerManagers/LinuxGSM#1881]
Game Server: Minecraft
Post Details: https://hastebin.com/vatuzipuki

I was going to work on my MC server but the debug command is giving me a file name too long error.

`/home/russianronin/mcmain/lgsm/functions/command_debug.sh: line 107: java -Xmx8192M -Xms8192M -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=45 -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -jar /home/russianronin/mcmain/serverfiles/paperclip.jar: File name too long`

This is the commit that broke it.

https://github.com/GameServerManagers/LinuxGSM/commit/fff8e0a2f504ab9f57f86ebc5e6eb20fdcbad8aa#diff-edab5a208504be569373e4b6e5559b62

The double quotes in line 107 break it. I can remove those quotes and the debug command runs fine.

I am wondering if the double quotes are breaking it anywhere else. Something to check.

**Comment by dgibbs64** [comment]
Thanks for this. I will take a look

**Comment by dgibbs64** [comment]
6de42480beedf00e135148bc51519da319f62491
