### ISSUE TITLE
Add mods to download via URL

### ISSUE THREAD

**Issue by Alkaris** [GameServerManagers/LinuxGSM#1883]
Adding mods for Rust is quite confusing to do since you're using a predefined list of available mods for download and install, but doesn't exactly make it easy to add other mods, but what would be better if you can add mods simply by pointing the mod installer to the download URL of a mod in the command line arguments. Something like so;

    ./rustserver mod-install --url=https://oxidemod.org/plugins/plugin-name.1234/download?version=12345

also if you've pre-downloaded a mod or made a new mod, just add by pointing to the directory where it's saved at.

    /home/${user}/Downloads/${plugin.dir}

**Comment by UltimateByte** [comment]
Ultimately, mods-install won't ever be installable using just a url, it has to be compatible with multiple games using multiple parameters (update settings, addon directory, convert to lowercase etc.) and mods-list.sh allows for easy mod integration already.

**Comment by Alkaris** [comment]
@UltimateByte Installing a mod is exactly what I'm trying to do, I'm not trying to install a mod for a mod of the game. That doesn't make any sense at all. So how the hell are you even suppose to add "Other" mods if you can't even use the `mods-install.sh` to do it? Pretty much defeats the purpose of having a mod installer if you can't do it that way.

**Comment by UltimateByte** [comment]
Oxide is a mod, you are trying to install mods (or plugins call it how you like best) for Oxide, therefore you are installing a mod for a mod. We do not do modception yet.
LinuxGSM takes care of Oxide core installation and updates which is kind already, then the user uses his favorite way to add mods for Oxide.

Adding new mods for linuxgsm can be done easilly by editing two lines in mods-list.sh, I made it this way so it is as easy as possible to add new mods. You can also just submit an issue with mod documentation and mod url and I will gladly add it if it's doable, but this doesn't work for oxide plugins, these work differently and would require a whole new command, which leads to the same point : people already made plugins for Oxide plugins DL and updates, you'd probably better use those for this very specific need.
