### ISSUE TITLE
Rust bug's ( don't start) 

### ISSUE THREAD

**Issue by prog66** [GameServerManagers/LinuxGSM#1889]
hi i have a problem ...:
"Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If rustserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug rustserver: Stopping any running servers
[ WARN ] Stopping rustserver: Default RCON Password detected!
 * Having CHANGE_ME as a password is not very safe.
[ INFO ] Stopping rustserver: Rust is already stopped
[  OK  ] Debug rustserver: Starting debug
Set current directory to /home/rust/serverfiles
Found path: /home/rust/serverfiles/RustDedicated
Mono path[0] = '/home/rust/serverfiles/RustDedicated_Data/Managed'
Mono config path = '/home/rust/serverfiles/RustDedicated_Data/Mono/etc'
Preloaded 'libRakNet.so'
Preloaded 'libRustNative.so'
eac_server.so [x64] :: OnLoad()
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api64.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
        libRenderer.so
        libRustNative.so
        libRenderer.so
Player data archive not found at `/home/rust/serverfiles/RustDedicated_Data/data.unity3d`, using local filesystem
Logging to /home/rust/.config/unity3d/Facepunch Studios LTD/Rust/Player.log"

https://hastebin.com/equmiwevey

My server is online ?... but i can't join pls help me ...

**Comment by prog66** [comment]
Sorry, i use a ubuntu 16.04.4 x64 
Intel Xeon 3 core 3.70 GHz 
6Go RAM .

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Troubleshooting
https://github.com/GameServerManagers/LinuxGSM/wiki/Support
