### ISSUE TITLE
Game server request

### ISSUE THREAD

**Issue by Ammar7347** [GameServerManagers/LinuxGSM#1890]
Hi,

GSM is awesome and so far I have not experienced any bugs. I just wanted to ask if there are plans for adding other games like COD MW2 and COD MW3 and even COD BO? If this is not a right place to request for games, let me know where I can request them.

Thanks and keep up the good work!

**Comment by UltimateByte** [comment]
Hi,

Request are made this way:

1) Make sure the game you're asking has native Linux support (Wine is not native support)
2) Provide as much documentation as you can on how to run the standalone game
3) Open an issue with this required information and a self explicit title
4) If you wish to get involved you can even work on the script yourself

Regards
