### ISSUE TITLE
Simplify update checking using an ACF to JSON formatter for 'update_steamcmd.sh'

### ISSUE THREAD

**Issue by Turbine1991** [GameServerManagers/LinuxGSM#1895]
In-case you want to simplify querying of buildid/etc, I've made an ACF to json formatter (which can deal with the raw steamcmd output). It's also useful when trying to obtain a specific branch's buildid.

Simple example:
> ./steamcmd/steamcmd.sh +login anonymous +app_info_update 1 +app_info_print "740" +app_info_print "740" +quit | acf_to_json | jq -r ".["740"]**.depots.branches.public.buildid**"

`2735003`

Everything is statically linked, the 32-bit binary will even work on a 64-bit Linux without dependencies:
https://github.com/Turbine1991/cpp_steam_acf_to_json

**Comment by dgibbs64** [comment]
Thanks for this, This is something that may come in handy with various projects
