### ISSUE TITLE
libstdc++6:i386 prerrequisite on 64bit debian

### ISSUE THREAD

**Issue by draakuns** [GameServerManagers/LinuxGSM#1896]
Hi, 

on my ubuntu 16.04.4 LTS 64bit server whenever I want to start, it always complains about libstdc++6:i386:

[ERROR ] Starting arma3server: Checking dependencies: missing: libstdc++6:i386

Well, this involves adding up the i386 arch on the package manager so it is inconvenient at all stages (for instance for a OS server update.
Instead of that, (at least in Deb based distros) you can omit this and ask to install the same 32bit libraries, which are packaged in the form of:

ii  lib32stdc++6                          5.4.0-6ubuntu1~16.04.9                     amd64        GNU Standard C++ Library v3 (32 bit Version)

Can you please consider changing this prereq on this 64bit flavours? I have the lib32std++6 installed but it keeps annoying me with the error at boot time.

Thanks!
Draakuns

**Comment by UltimateByte** [comment]
Hi,

Thanks for your interest in making LinuxGSM better.

We saw no inconvenients in distro behavior yet in adding the ability to install 32 bit packages in years of LinuxGSM. It's a 3 step command:

`dpkg --add-architecture i386; apt update; apt install libstdc++6:i386`

Could you please explain a bit more why this would be an issue for you and should be changed for everybody?

Regards

**Comment by draakuns** [comment]
Hi,

adding an additional arch is not an easy step for a lot of users, even if it is only performed on a 3-step command. For instance, release upgrades tend to fail a lot more because of this, even sometimes the upgrader itself disables the "additional" archs to do its job perfectly. Other caveats can be dependency problems (which luckily we don't see a lot of times, but when they happen are a pain in the ass), which with several archs added tend to get messy.
Also, I don't see the point in bothering adding a full arch (with the mess whenever you search packages) if the same package is available natively for 64bit as a "backwards" compat 32bit lib already.

Just my 2 cents, as I already said it's not a problem but an annoying meaningless warning for me. If it is complicated to add the feature, then maybe it's not worth it.

BR
Draakuns

**Comment by draakuns** [comment]
Hi, 
I don't know which 3-steps you followed, but that is going to break your system 100% sure. 

BR
Draakuns

**Comment by mattjacobsen** [comment]
Hey @draakuns,

autoremove is clean. Thanks for the suggestion.

I solved my problem (getting a UT2004 dedicated server working for an upcoming LAN party) by simply installing the UT2004 server without LinuxGSM (I wanted to see what ucc-bin reported).

The dependency on 32-bit libstdc++6 is obviously still there (the UT2004 server is 32-bit), but I managed to solve it by installing lib32stdc++6, rather than going the additional arch route (:i386). @UltimateByte maybe this is a simpler way to handle the dependency in LinuxGSM for debian/ubuntu (https://packages.ubuntu.com/xenial/libs/lib32stdc++6)?

Regardless, I didn't even know debian was capable of managing packages from multiple architectures until I read the LinuxGSM install guide, so I'm happy to have learned something new ;-)

Kind regards,
Matt

**Comment by draakuns** [comment]
Hi @mattjacobsen 

glad to hear that it fixed quickly your issue ;)

Yeah, you can install several archs but binary compatible are only x86-x64 if your device is intel 64bit (or armel/armhf/arm64 on ARM64 arch)... other archs are used for bootstrapping other devices you may be working with. 

Best regards and enjoy the LAN party,
Draakuns

**Comment by dgibbs64** [comment]
As most servers are 32-bit i386 version is normally required. I was unaware that the x64 versions are also backwards compatible. This change would require quite a lot of testing to make sure stuff still works

**Comment by draakuns** [comment]
Hi Dan,
it's not that they are backwards compatible. This package installs 32bit libraries (not a backwards compat 64bit lib), even if you have the 64bit environment. Therefore, it is the same as installing i386 arch and the libs, but without the hassle to add any architecture to the package manager (which is used only for 1 package).
Just using the current check that the 32bit arch & lib is installed (**new code** OR lib32stdc++6 is installed on x64) should do the trick.
Let me know if I can help in any possible way.
BR
Cristian.

**Comment by dgibbs64** [comment]
Having a look at this the i386 version is not installed with `libstdc++6`

```
root@localhost:~# apt install libstdc++6
Reading package lists... Done
Building dependency tree
Reading state information... Done
libstdc++6 is already the newest version (8.3.0-6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@localhost:~# locate libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25-gdb.py
```

The only other solution I found was to use `libstdc++6-i386-cross` which would remove the need for  `sudo dpkg --add-architecture i386` in most instance

**Comment by draakuns** [comment]
Hey! 

Long time no see ;)

I still don't get why are you not just installing the lib32stdc++6 package, which provides 32bit stdc++6 libs... 

It provides:
/usr/lib32/libstdc++.so.6
/usr/lib32/libstdc++.so.6.0.25

Isn't it good enough for our purposes?

BR
Cristian

**Comment by dgibbs64** [comment]
@draakuns Because I didn't see the lib`32`stdc++6 part I am that used to just seeing libstdc++6 that I was word blind to it X-D. Makes more sense now. I will re-investigate it and should be able to implament this change. Thanks

**Comment by cyberlimbo** [comment]
Still not working after updating functions..
"[ .... ] Starting arkserver: TestServer no server running on /tmp/tmux-1002/default
[ FAIL ] Starting arkserver: Unable to start TestServer"
