### ISSUE TITLE
Little problem with my servers

### ISSUE THREAD

**Issue by Vulann** [GameServerManagers/LinuxGSM#1903]
Hello,

I have a problem for about 3 days ..

Users can not connect to my servers via IP,
The server is not found in the list of servers, I run a VPS debian 8.
Only me can join the server ..

question / answer that we could ask myself before:

Do you see the server in the server list?
No, he can not be found

How do you join him?
Via IP in the F10

Can friends join you by steam invitation?
Not at all.
I already give the IP to a friend so that he can join via F10 but it's impossible, his rest has retriving servers info ...

Of course I use LinuxGSM

You will excuse me but I am French, certain of my sentences can be incomprehensible.
If someone has an idea...
cordially

**Comment by UltimateByte** [comment]
https://linuxgsm.com/support/
