### ISSUE TITLE
[REQ] One Set Files for 2 Servers 

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#1904]
Hi there! 

> So, I want to use a set of files for 2 servers, shared.

That func possible add to LGSM? If that really need more people, of course.

**Comment by UltimateByte** [comment]
Hi,

Lucky you, I just updated the documentation about this a few days ago, it is now supposed to be as clear as possible.

**Comment by UltimateByte** [comment]
Just an idea, but : if you installed SteamCMD within your distro, you can try uninstalling the package since LinuxGSM uses the independant and more reliable .tar.gz steamcmd file instead.
