### ISSUE TITLE
Is it Possible to host CSGO and CS.1.6 in Same  Machine ????

### ISSUE THREAD

**Issue by chiranjitk** [GameServerManagers/LinuxGSM#1906]
Is it Possible to host CSGO and CS.1.6 in Same  Machine ????

**Comment by Grimston** [comment]
Issues are not the place for this, please check the wiki for support... also

https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Game-Servers

**Comment by UltimateByte** [comment]
Please, don't pollute the GitHub with non-issues.
There are rules written everywhere (including in the text box that you had to clear in order to write your issue), that's for a reason.
