### ISSUE TITLE
Add update notifications for LinuxGSM and game servers

### ISSUE THREAD

**Issue by Tank-Missile** [GameServerManagers/LinuxGSM#1907]
If configured, when LinuxGSM or a game server needs to be updated, send a notification/email or other custom method. Also, if configured, send a notification/email after LinuxGSM or a game server has been updated. Finally, if configured, if LinuxGSM or any game server fails to update, send a notification/email. The notifications/emails sent could be customized depending on the information you want. Would you prefer simple messages such as "Server 1 has successfully updated and restarted!", or perhaps you want the entire update log included? What if the server successfully updates but fails to start? There are many different scenarios that could effect the emails/notifications sent.

**Comment by bykidi** [comment]
from what i get he means that:
1. linuxgsm gets updated
2. game server gets updated
3. notification send to email that update was successfully installed (or not)

**Comment by Tank-Missile** [comment]
That could also be an option, but what I really want is to receive notifications when updates are available to LinuxGSM and game servers. This is so I can manually update LinuxGSM or my game servers myself more easily. I rather not have LinuxGSM automatically update on a timer.

**Comment by dgibbs64** [comment]
relates to #2001

**Comment by h3o66** [comment]
Partally adressed by #3146 for steamcmd gameservers

**Comment by h3o66** [comment]
Alerts for a LGSM release will be handled with issue #2643

**Comment by h3o66** [comment]
For this issue only the notification would be the point to sent if the update was successful or not.

**Comment by dgibbs64** [comment]
Check update functionality is available to updates to game servers. However, functionality is not yet available for linuxgsm updates.

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/4345
