### ISSUE TITLE
KF2 server not installing

### ISSUE THREAD

**Issue by unixbird** [GameServerManagers/LinuxGSM#1909]
OS: Debian 9 64bit
Server: Killing Floor 2
postdetails:  https://hastebin.com/eneromivuv
hardware: 4x vcpus with 1GB of ram

when trying to install the KF2 server I get these errors as shown below. 
I have confirmed that steamCMD is installed and working by running the shell script manually and grepping "getcwd" * outputs that it is inside some of the lgsm directories that were made during lgsm use.  I'm not quite sure where to go from here

https://cdn.discordapp.com/attachments/135126471319617536/451167043547561995/IMG_20180529_183614.jpg

https://cdn.discordapp.com/attachments/135126471319617536/451167044314988556/IMG_20180529_183623.jpg

**Comment by UltimateByte** [comment]
Game server is 16GB. You don't have enough disk space.

```
ultimatebyte@gaben:~$ du -sh * | sort -h
12K     kf2server
12K     linuxgsm.sh
24K     log
3.4M    lgsm
3.5M    Steam
63M     steamcmd
16G     serverfiles
```

Get a better server and try again.
If you're on a budget and live near France, I can host you on my OVH dedicated server.

**Comment by unixbird** [comment]
oh wow i didnt realize it could be more than 15GB of space, i can easily accommodate that on my rack. Thanks for the offer though!
