### ISSUE TITLE
[Server Request] Post Scriptum

### ISSUE THREAD

**Issue by pingfloid** [GameServerManagers/LinuxGSM#1911]
When can we install the game ourselves with LGSM? 
http://postscriptumgame.com/

**Comment by UltimateByte** [comment]
https://steamcommunity.com/groups/linuxgsm/discussions/0/1696048426809862122/
"Well, first step is to open an issue on github **with manual server installation/configuration (start parameters)** so that devs can add it to linuxgsm."

**Comment by dgibbs64** [comment]
There is currently no self-hosted servers available for this. However looks like it may happen in the future

**Comment by Troopie** [comment]
This should be coming today.

**Comment by pingfloid** [comment]
cool

**Comment by Troopie** [comment]
Steam AppID: 844650 
Server config files "/home/Server1/Post_Scriptum/PostScriptum/ServerConfig\
Where Admins.cfg, Bans.cfg, License.cfg, MapRotation.cfg, Rcon.cfg, RemoteAdminListHosts.cfg, RemoteBanListHosts.cfg, Server.cfg and ServerMessages.cfg.
Server.cfg:
*****
ServerName="Post Scriptum Dedicated server"
//MaxPlayers Max 80 players
MaxPlayers=40 
NumReservedSlots=0
IsLANMatch=false
ShouldAdvertise=true
NumPlayersDiffForTeamChanges=3
AllowTeamChanges=true
PreventTeamChangeIfUnbalanced=true
EnforceTeamBalance=true
RejoinSquadDelayAfterKick=180
RecordDemos=false
ServerMessageInterval=300
// Forced on for Licensed servers (Only OWI staff & qa are admins)
AllowCommunityAdminAccess=false
// Forced on for Licensed servers (Only OWI devs)
AllowDevProfiling=false
***
Starting script "cd Server1; ./PostScriptumServer.sh Port=10027 QueryPort=10037 -fullcrashdump -log"

I did test install this and played this a bit with my own server, so these are tested.

Post Scriptum uses the exact same commands / configuration of Squad servers There was also these parameters on starting script "FIXEDMAXPLAYERS=80 RANDOM=NONE"

**Comment by dgibbs64** [comment]
https://steamdb.info/app/844650/

**Comment by dgibbs64** [comment]
- Outstanding issues. The server will no allow me to connect to it @Troopie had better success. 
- And gamedig does not work but gsquery does

**Comment by Troopie** [comment]
Behavior differs when multiple IP's . One IP-address and game connects.

**Comment by Troopie** [comment]
Game released, server appid changed to 746200.
