### ISSUE TITLE
Steam API key is visible on postdetails output

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1912]
This issue is critical, needs fix ASAP.

**Comment by dgibbs64** [comment]
@UltimateByte whereabouts is it visible?

**Comment by UltimateByte** [comment]
In my gmodserver it is visible.
Actually, that's weird, because in an attempt to change the authkey to show you, it didn't change in the postdetails link, but it changed in regular details. So I don't know where it comes from. Any idea?
My common.cfg is empty.

**Comment by dgibbs64** [comment]
I have no idea

**Comment by UltimateByte** [comment]
I kind of reproduced the issue.
I had to remove the postdetails log in log/script/gmodserver-postdetails.log for it to update, so I might have found a second bug, or related bug.

Output: https://hastebin.com/ciqokikolo

**Comment by dgibbs64** [comment]
Awesome I can work with that :). Please could to try to replicate the other bug you came across and raise it if required.

**Comment by dgibbs64** [comment]
This has just opened a can or worms as the way workshop vars are setup over several games are different

**Comment by UltimateByte** [comment]
Fix for authkey:
Add there:

**Comment by dgibbs64** [comment]
thanks, I'm working on it. Also now hiding gslt and fixing the issue with pd not updating

**Comment by UltimateByte** [comment]
yw
I couldn't find why it's not updating. I need some rest :)

**Comment by dgibbs64** [comment]
it now just removes the log if it exists. All issues now resolved for release

**Comment by UltimateByte** [comment]
That doesn't explain why the `>` redirection doesn't overwrite the log content, but if that does the trick, that's the most important.
