### ISSUE TITLE
All GoldSource server download files from archive first

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1920]
To help get around the SteamCMD issue with downloading GoldSource games it would be a good idea to create archives of the servers to be downloaded from LinuxGSM web server before running SteamCMD. This should prevent issues with downloading the servers

**Comment by dgibbs64** [comment]
https://www.youtube.com/watch?v=_BYkJHt3Utc

**Comment by henrik9999** [comment]
Hi All,

somebody found a work around to fix this. After you login anonymously into steam cmd. Run the below commands.

app_update 90 -beta beta validate

After the above completes run the below

app_update 70 -beta beta validate

This will give you an error saying no subscription.
Now run the below

app_update 10 -beta beta validate

This will also give you an error.

Now at the end run the below again.

app_update 90 -beta beta validate

This should download all the server files.

**Comment by dgibbs64** [comment]
#2959
