### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by gamersalpha** [GameServerManagers/LinuxGSM#1922]
Hello, 

how autostart the linuxgsm on my serveur ?

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/On-Boot

**Comment by gamersalpha** [comment]
On the wiki page,  u have only the way when u reboot.

But it would be interesting to have a service linuxgsm ?

because if the server crashed u have manually to make it works ??

can u have a sh scripts who says if the serveur is only and can restart the linuxgsm service ??

thanks
