### ISSUE TITLE
Server works on Linode, but fails on DigitalOcean

### ISSUE THREAD

**Issue by Cowlephant** [GameServerManagers/LinuxGSM#1923]
I have been struggling to host a Project Zomboid server for about a week now with my DigitalOcean droplet. I get to the point where I can see the server in the browser, but get a P2P connection error when anyone tries to join. This is on an 18.04 Ubuntu x64 DigitalOcean droplet.

My friend was able to successfully get it working, to my frustration, on his older 16.04 Ubuntu x64 setup. I tried doing the same on a fresh 16.04 Ubuntu x64 setup to no avail.

I've had a running ticket with DigitalOcean to try all sorts of things, including opening proper ports... or disabling ufw and flushing all iptables rules and accepting all incoming, outgoing and forwarding. Still, the issue persists.

I've created a fresh Linode Ubuntu 18.04 x64 and a DigitalOcean Ubuntu 18.04 x64 droplet and ran them side by side, performing all the same steps. The Linode one always works, the DigitalOcean always fails. that video can be seen here. https://www.youtube.com/watch?v=tTiKMJG3eVg

I'm so very perplexed about this issue, especially since my friend with a DigitalOcean droplet was able to do it on his.

```
raziaar@hexacow-server:/etc$ sudo ufw status
Status: inactive
raziaar@hexacow-server:/etc$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
raziaar@hexacow-server:/etc$


```

**Comment by Cowlephant** [comment]
Note, that I've also gone and opened all the ports for zomboid and steam previously. My goal was to open everything up like the base ubuntu on Linode(no port forwarding steps).

**Comment by Cowlephant** [comment]
Here is DigitalOcean support basically saying they can't determine anything wrong based on information I've provided them over a fairly lengthy service ticket.

> Hello,
> 
> Thank you for contacting DigitalOcean!
> 
> I am sorry for the trouble caused to you here! 
> 
> I see no issues with your Droplet or the Platform either. I would recommend you to reach out to the app vendor here:https://linuxgsm.com/support/  or if you have any server application logs, please provide it to us and we can take a look at it. As an un-managed service provider, we have no access to Droplets which means we have no visibility to figure out what happens within the Droplet which also means that we won’t be able to log into your Droplet and perform any actions on your behalf. We rely on the inputs we get from you like server log output, troubleshooting steps you followed, screenshot of configuration file etc. 
> 
> Please feel free to reach out to us via this ticket if you have further queries or concerns, we will be around to help you out!

**Comment by UltimateByte** [comment]
Read the link you just posted.
