### ISSUE TITLE
Teamspeak3: libmariadb2 is not available on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by AokiAhishatsu** [GameServerManagers/LinuxGSM#1924]
I know you can leave it and use SQLite. But this will annoy increasingly more people when Ubuntu 18+ will gets more common.

**Comment by Traace** [comment]
Here is a working deb for binoc (18.04): https://answers.launchpad.net/ubuntu/bionic/amd64/libmariadb2/2.3.3-1

**Comment by Traace** [comment]
AFAIK no. libmariadb2 got replaced by libmariadb3. It should be available in Ubuntu repo. https://launchpad.net/ubuntu/+source/mariadb-connector-c

The teamspeak company need to update their software to support libmariadb3.

**Comment by Bourne-ID** [comment]
Potentially libmariadbclient18 - description states: 

The main reason to use [libmariadb2], rather than libmariadbclient18, is differences in licensing: this package uses the LGPL, while uses the GPL

Needs testing.

**Comment by Traace** [comment]
Ty, I'll test it today on a clean ubuntu vm

**Comment by Bourne-ID** [comment]
Unresolved dependency error in a TS3 error message or through the LinuxGSM console?

**Comment by dgibbs64** [comment]
#1877

**Comment by dgibbs64** [comment]
`libmariadb.so.2` is required for mariadb and teamspeak3 but is not available in the ubuntu repo. However `libmariadb.so.3` is available. Also `libmariadb.so.2` is installed as part of the installer for TS3.

```
/home/lgsm/ts3server/serverfiles/redist/libmariadb.so.2
```

```
Required Librarys
=================================
ld-linux-x86-64.so.2
libc.so.6
libdl.so.2
libmariadb.so.2
libm.so.6
libpthread.so.0
librt.so.1
libts3_ssh.so
```

I don't really want to be messing around with MariaDB to test this feature. However, If there is anyone who does have a Teamspeak 3 MariaDB setup on Ubuntu 18.04 please can a fix be advised and I am happy to implement an update.

**Comment by olokos** [comment]
You may have missed to move or copy the libmariadb.so.2 from redist folder to the root folder of the server.

That's because libmariadb.so.2 has to be manually copied from redist to serverfiles root directory. After I did that on Ubuntu 18 I can now use mysql with ts3, didn't even have to install mariadb replacement. :)

**Comment by xFirez** [comment]
Any news on this?

**Comment by Plexiate** [comment]
:(

**Comment by olokos** [comment]
Judging by the commits in 2018 linked here, it's resolved now.
Problem was that the lgsm installer didn't move the required file
as explained here: https://github.com/GameServerManagers/LinuxGSM/issues/1924#issuecomment-435750306
