### ISSUE TITLE
[Ark Survival evolved] - How to change map ?

### ISSUE THREAD

**Issue by gamersalpha** [GameServerManagers/LinuxGSM#1925]
Hello there, 
i m still looking how change map with my ark serveur : 

i modifie this files : 

`arkserver@ark:~$ nano lgsm/config-lgsm/arkserver/arkserver.cfg`

##################################
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance
maxplayers="5"
defaultmap="Ragnarok"

```

and when i see my details server : 


arkserver@ark:~$ ./arkserver dt
[ INFO ] Details arkserver: Check IP: 192.168.50.60

Distro Details
=====================================================================================================================
Distro:    Ubuntu 18.04 LTS
Arch:      x86_64
Kernel:    4.15.0-23-generic
Hostname:  ark
tmux:      tmux 2.6
GLIBC:     2.27

Performance
Uptime:    0d, 0h, 5m
Avg Load:  1.33, 1.00, 0.51

Mem:       total   used   free   cached
Physical:  3.8G   2.0G   232M   2.8M
Swap:      3.8G   0B     3.8G

Storage
=====================================================================================================================
Filesystem:      /dev/sda2
Total:           293G
Used:            14G
Available:       264G
LinuxGSM Total:  6.9G
Serverfiles:     6.8G

ARK: Survival Evolved Server Details
=====================================================================================================================
Server name:  ark-server-ubuntu
Server IP:    192.168.50.60:7777
Maxplayers:   5
Default Map:  Ragnarok
Status:       ONLINE

arkserver Script Details
=====================================================================================================================
Service name:           arkserver
arkserver version:      180409
User:                   arkserver
GLIBC required:         2.15
Discord alert:          on
Email alert:            off
Pushbullet alert:       off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushover alert:         off
Telegram alert:         off
Update on start:        off
Location:               /home/arkserver
Config file:            /home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Backups
=====================================================================================================================
No Backups created

Command-line Parameters
=====================================================================================================================
./ShooterGameServer "TheIsland?listen?MultiHome=192.168.50.60?MaxPlayers=5?QueryPort=27015?RCONPort=27020?Port=7777?"

Ports
=====================================================================================================================
Change ports by editing the parameters in:
/home/arkserver/lgsm/config-lgsm/arkserver

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game       INBOUND    7777   udp
> RAW        INBOUND    7778   udp
> Query      INBOUND    27015  udp
> RCON       INBOUND    27020  tcp

Status: ONLINE
```

like u see ARK: Survival Evolved Server Details says i m on Ragnarok, but in the real command line starting server ark, say's i m still on th Island .

```
ARK: Survival Evolved Server Details
=============================================================================================================================================================================================================================================
Server name:  ark-server-ubuntu
Server IP:    192.168.50.60:7777
Maxplayers:   5
Default Map:  Ragnarok
Status:       ONLINE
```

but the serveur start with theisland : 
```

Command-line Parameters
=============================================================================================================================================================================================================================================
./ShooterGameServer "TheIsland?listen?MultiHome=192.168.50.60?MaxPlayers=5?QueryPort=27015?RCONPort=27020?Port=7777?"
```

so what is wrong ..

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by gamersalpha** [comment]
Hello, 
u closed my topic, but this is a linuxgsm issue ?

we can't change the map with linuxgsm parameters, why not ?

i want modifie all ark serveur parameters with linuxGsm and not directly in ark config files :/

**Comment by gamersalpha** [comment]
Hello, 
ok i found how to change map 👍 

edit this files : 

` nano /home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg`

and add this : 
```

##################################
######## Instance Settings ########
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance
maxplayers="5"
defaultmap="Ragnarok"

fn_parms(){
parms="\"${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}?\""
}
```


Ok so now, change 
defaultmap="Ragnarok"

with u choice : 
`defaultmap="Ragnarok"`
`defaultmap="TheIsland"`
`defaultmap="TheCenter"`

have fun with u personal serveur with linux GSM :)

**Comment by UltimateByte** [comment]
1) server*
not "serveur"

2) A question on how to use LinuxGSM is not relevant to LinuxGSM development.

Like said everywhere, this git is not meant to be polluted with irrelevant posts that do not relate LinuxGSM develoment in any way but rather in game server questions or usage questions that are already answered in the wiki... Which was exactly what your issue asked for initially. Once again: Github is for development and nothing else. We want to know when there is a bug or a feature to add, not when a user struggles using google.

3) If you want to add a start parameter, then open an issue asking for this.

**Comment by UltimateByte** [comment]
1) server*
not "serveur"

2) A question on how to use LinuxGSM is not relevant to LinuxGSM development.

Like said everywhere, this git is not meant to be polluted with irrelevant posts that do not relate LinuxGSM develoment in any way or in game server questions or usage questions that are already answered in the wiki... Which was exactly what your issue asked for initially. Once again: Github is for development and nothing else. We want to know when there is a bug or a feature to add, not when a user struggles using google.

3) If you want to add a start parameter, then open an issue asking for this.

**Comment by gamersalpha** [comment]
Hello more information about changing map on linux GSM server on ARK Survival 👍 

To change map this all the good name (not easy to found it)

so to resume all  u need is this : 

`arkserver@ark:~$ nano lgsm/config-lgsm/arkserver/arkserver.cfg
`


```
##################################
######## Instance Settings ########
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance
maxplayers="5"
defaultmap="Ragnarok"
#defaultmap="CrystalIsles"
#defaultmap="Aberration_P"
#defaultmap="ScorchedEarth_P"

fn_parms(){
parms="\"${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}? -automanagedmods\""
}
```

and u have just make u choice for start a map !!

**Comment by gamersalpha** [comment]
Hello, 
some news about map using on ARK with linuxGSM !!

this is the new conf of  nano lgsm/config-lgsm/arkserver/arkserver.cfg

`##################################
######## Instance Settings ########
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance
maxplayers="5"

#defaultmap="TheIsland"
	#defaultmapFiles="TheIsland-nitradoeu19.officialserver186"
	#defaultmapFiles="TheIsland-GGFizz-"
#defaultmap="Ragnarok"
	defaultmapFiles="Ragnarok"
	#defaultmapFiles="Ragnarok-GGFizz-Mars2018"
#defaultmap="CrystalIsles"
	#defaultmapFiles=${defaultmap}
#defaultmap="Aberration_P"
	#defaultmapFiles=${defaultmap}
#defaultmap="ScorchedEarth_P"
	#defaultmapFiles=${defaultmap}
#defaultmap="ScorchedEarth_P"
	#defaultmapFiles=${defaultmap}
	



fn_parms(){
parms="\"${defaultmap}?AltSaveDirectoryName=${defaultmapFiles}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}? -automanagedmods\""
}
`

to place all map look this screen : 
![image](https://user-images.githubusercontent.com/32466950/43364565-e1f25bea-931c-11e8-9ee5-a7588782cdb9.png)

u have to put directory map filder like this

and with that u can now have same map in diffrent version, and using a map by directory, to save u player by map !!!
thanks to all

**Comment by gamersalpha** [comment]
update adding new map Extinction :)
