### ISSUE TITLE
Dont Starve Togeter Caves is really difficult to setup

### ISSUE THREAD

**Issue by M45T3Ryu** [GameServerManagers/LinuxGSM#1928]
So yeah I been 6 hours tryng to install the game server with Caves but its kinda hard and I ended up installing it manually

What it does its that when you install or try to make the other server it always ends up using the same "Master" config, I followed everything perfectly but its not generating diferent names for the configs it always generates "Master" and every batch file generated for every server defaults to using it even in Details section every "dstserver, dstserver-2, dstserver-3, dstserver-4" shows as using Master.cfg.. and im not that expert on editing batch so I dont have an idea of whats going wrong

**Comment by Khelgar1** [comment]
This isn't an issue for GitHub, it's a configuration problem.
Check the wiki https://github.com/GameServerManagers/LinuxGSM/wiki/Don%27t-Starve-Together
Ask on Discord https://linuxgsm.com/discord
Wiki: http://goo.gl/siyiY4
How to ask for help: http://goo.gl/IaXksu

**Comment by UltimateByte** [comment]
I have to admitt the install for the game is weird, but we took care of it with a wiki article. @dgibbs64 Maybe it could be added to the website and/or install process?

**Comment by dgibbs64** [comment]
Yup could be added to the site. Just need a reminder issue

**Comment by dgibbs64** [comment]
I have updated the website

**Comment by freakyy85** [comment]
I have the same problem. No matter what I try, dstserver-2 etc. and i have dst-server-Caves.cfg and nothing helps. I can't start the shard server or it isnt started. I don't know. Can someone help me? :)
