### ISSUE TITLE
Linux GSM cant query port on Rust Server

### ISSUE THREAD

**Issue by Karrigallu** [GameServerManagers/LinuxGSM#1932]
I have the issue, that since yesterday, when i want to start my gameserver, the script works flawlessly, but i cant connect to my server. It worked before on the same settings. so i did ./gameserver monitor and found out that when the server is querying ports it fails.

`[ FAIL ] Monitor rust-server: Querying port: gsquery: 62.75.163.10:28015 : 60/5: FAIL`

so i went into root user, checked iptables and added some rules allowing port 28015 and 28016.
Still no success.
i then did ./gameserver query-raw and got errors aswell:

`Failure! gamedig not installed
Failure! jq not installed
gamedig --type "" --host "0.0.0.0" --port "28015"|jq`
`/home/rustservermain/lgsm/functions/command_dev_query_raw.sh: line 30: jq: command not found`
`gsquery Raw Output`
`./query_gsquery.py -a "0.0.0.0" -p "28015" -e "unity3d"`
`ERROR: Unable to receive`

I lready restarted my server, i also  tried reinstalling rust server on a new user, same  problem.
Please help me

**Comment by UltimateByte** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Karrigallu** [comment]
i dont understand why you closed this issue.
Im not sure if this issue is GSM related or  not.
i take it as quite rude to just give me a wiki link, since i read it well enough.
I would much more appreceate you telling me, that it is as  example not GSM related, instead  
of just  closing it. Thank you

**Comment by UltimateByte** [comment]
Three main reasons:
1) Didn't follow support guidelines regarding provided information
2) This isn't a LinuxGSM issue
3) You are not even reading the given output of your console which would allow you to most likely resolve at least half of the issue in 15 seconds, so why should anyone read your post?

Now please, be nice and read the provided link before commenting back on GitHub.

**Comment by Karrigallu** [comment]
You are right, and i am sorry for taking your effort, but also thankful for giving it.
Even thought this isn't a GSM issue, and you said that i could most likley resolve 50% of it in 15 seconds, i cant fix it. But you seem like you can, and i would be really happy if you would so.
Thanks again for your effort, and sorry for not being nice in my Issue at the first place...

**Comment by Karrigallu** [comment]
please help me..

**Comment by UltimateByte** [comment]
Non development related issues have no place on github. Go on the Steam group or Discord and there will be people to help with this kind of issues.

**Comment by Sminstes** [comment]
@Karrigallu Hey, did you resolve the issue. This is a mindblowing problem...

**Comment by Karrigallu** [comment]
> @Karrigallu Hey, did you resolve the issue? This is a mindblowing problem... I just can't wrap my head around. Especially with no SSH / coding experience really. There's nothing on the web about it and help is hard to find apparantly.
> I've checked my logs. Made sure the ports were open and also done these: 1. systemctl disable firewalld
> 2. systemctl stop firewalld. I'm hosting at OVH and using CentOS7.

I got it fixed with this post: 
https://umod.org/community/rust/12061-server-not-starting-with-oxide?page=5
just replace two files in your /Managed folder with those two in Wulfs download and its fixed.
