### ISSUE TITLE
Factorio server update fails when latest experimental build is changed to a stable build

### ISSUE THREAD

**Issue by adsads** [GameServerManagers/LinuxGSM#1933]
I was doing an update on the factorio server to verify that it was up to date. I am running the experimental updates. 

I seem to have tracked the issue back to the experimental downloads page. The latest experimental build/stable build are both 0.16.51 , the latest numbered version shown on the experimental page is 0.16.50.  

The numbered version of 0.16.51 has been moved to the stable page. Both of the latest links download the 0.16.51 version.

![fctrserverupdate](https://user-images.githubusercontent.com/4984522/42392389-4b4d66b4-8118-11e8-8454-d3c39d34860f.png)

**Comment by UltimateByte** [comment]
Try `force-update` or `validate` commands.

**Comment by Jpotratz** [comment]
![wubeplz](https://user-images.githubusercontent.com/36650080/42397440-9fb9a826-812b-11e8-88da-1d79c05ee6dd.png)

**Comment by Jpotratz** [comment]
![wubeplz](https://user-images.githubusercontent.com/36650080/42397511-d2bbdf1e-812b-11e8-9150-aff5b85dd1a6.png)

**Comment by adsads** [comment]
neither force-update or validate seem to be valid commands.
![image](https://user-images.githubusercontent.com/4984522/42397627-4d8dce1e-812c-11e8-9868-f54b2b76f70a.png)

**Comment by UltimateByte** [comment]
Lol, version numbers don't make sense here, seems more like a Factorio issue than LinuxGSM issue.

**Comment by adsads** [comment]
https://forums.factorio.com/viewtopic.php?f=7&t=61408

**Comment by UltimateByte** [comment]
Sounds like bullshit to me... Experimental should not be compared to stable build in any way, that's just obvious stupidity to me.

**Comment by adsads** [comment]
```
curl -s  https://factorio.com/get-download/latest/headless/linux64 | grep -o '[0-9]\.[0-9]\{2\}\.[0-9]\{2\}' | head -1
```

Should be enough to get the version number from the latest url.
 
![image](https://user-images.githubusercontent.com/4984522/42407447-5b3c0a70-8182-11e8-95eb-fec4c5c8ecbc.png)

**Comment by dgibbs64** [comment]
Maybe getting in in steam is something that can be requested on factorio forum?

**Comment by dgibbs64** [comment]
Also why not just set the experimental version to 0.16.51? LinuxGSM has to look for the word experimental to get the experimental build and stable to get the stable build. 

Maybe the workaround is for experimental to also check stable and if stable is a higher version use that instead
