### ISSUE TITLE
Minecraft using wrong config

### ISSUE THREAD

**Issue by Dragonphire** [GameServerManagers/LinuxGSM#1938]
I am posting about Minecraft but this seems to be how LGSM is interacting with the setup, which in my opinion should work. The Minecraft server itself runs just fine (at least the one instance). Please let me know if i should post elsewhere.

i have a single user, multiple instance setup as the intention is just 3 different servers with different gamemodes and world files. I have seen others comment of successful setups, so i'm not sure if it's my setup. (I have had trouble finding any specific how to for single user, multiple instances for minecraft specifically. My setup seems flawed in the fact that the server files for all 3 servers are in the same serverfiles directory, so each server shares the same ops.json file for example.)

When i start the server, everything looks fine. when i ./game details, all the values look correct, including pointing to the custom server.properties file. However, when i go to the server in game, the MOD says "Default Server" (which is what i set the default server.properties file to have) instead of the "Gamemode Server" MOD which i set for each server.

within serverfiles, i created a server properties file with the naming convention of ${servicename}.properties. I also created a world folder with similar convention ${servicename}.world

In the lgsm/config-lgsm/server/common.cfg file, i changed servercfg="${servicename}.properties". 

So when i run details for each server, i'm getting back the correct config file for each. When i start it, it is saying the correct MOD in the output. But in game, i'm getting the default and i cannot start a second server because it keeps trying to use the default properties which has only the one port.

I even tried to set servercfgdefault="${servicename}.properties" with no success.

Again, i have updated the common.cfg to point each instance to a unique properties file, so i don't see how there is an issue. I appreciate any assistance.

Server 1: https://hastebin.com/axawixibij
Server 2: https://hastebin.com/axozacehen

**Comment by Dragonphire** [comment]
Here is some more info i forgot to include.
Server 1: https://hastebin.com/axawixibij
Server 2: https://hastebin.com/axozacehen

**Comment by UltimateByte** [comment]
Maybe Minecraft doesn't like the dash `-` in the server config file.
Try renaming `mcserver-adventure` to `adventure` (as well as various config files) and see.

**Comment by Dragonphire** [comment]
same outcome.

https://hastebin.com/cemabiwofo

**Comment by levifig** [comment]
I'm having an issue where my LGSM isn't _obeying_ the overrides I'm placing on `common.cfg`. No matter what I change, it runs with whatever `_default.cfg` is configured. I'm going to posit my issue could be the cause of the bug here too...

**Comment by levifig** [comment]
Update: after a couple of server restarts, with no intervention on my part, LGSM actually created the `common.cfg` and `<instance>.cfg` files (actually overriding my own). Since then, it's been reading those files just fine. No idea why, for a while, it didn't 1) create those files and 2) read those files.

Thought I'd update this thread. Basically, if the `common.cfg` and `<instance>.cfg` files are not automatically generated, it seems LGSM has b0rked somewhere and won't even read them if you create them manually.

**Comment by DUDU54** [comment]
It's simply because minecraft take only the "server.property" file, you cannot specify the property file when you start the server as some other game allow.

To achieve what you want to do, you can create a file in other location and create a simlink in each server file folder

**Comment by h3o66** [comment]
I do not see any way to maeke this work.
If someone knows how to do this, please reopen this issue.
