### ISSUE TITLE
Minecraft install script is getting 403 for downloading the Jar file

### ISSUE THREAD

**Issue by tazboyz16** [GameServerManagers/LinuxGSM#1939]
Fresh install of Ubuntu 16.04 LTS 

Installing Minecraft Server
=================================

Accept Minecraft EULA
=================================
You are required to accept the EULA:
https://account.mojang.com/documents/minecraft_eula
By using auto-install you are indicating your agreement to the EULA.

downloading minecraft_server.1.13.jar...downloading minecraft_server.1.13.jar...
curl: (22) The requested URL returned error: 403 Forbidden
FAIL
https://s3.amazonaws.com/Minecraft.Download/versions/1.13/minecraft_server.1.13.jar

mcserver@Minecraft:~$ wget https://s3.amazonaws.com/Minecraft.Download/versions/1.13/minecraft_server.1.13.jar
--2018-07-18 21:13:00--  https://s3.amazonaws.com/Minecraft.Download/versions/1.13/minecraft_server.1.13.jar
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.228.139
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.228.139|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-07-18 21:13:00 ERROR 403: Forbidden.

**Comment by kennyLtv** [comment]
I do believe they phased our the s3 download points for the jar files. 

At the top of the versions file associated with the s3 [URL](https://s3.amazonaws.com/Minecraft.Download/versions/versions.json) is this:

` "__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone",`

The new version manifest returns back the locations of the releases as well as what the current release is. You can find that manifest [here](https://launchermeta.mojang.com/mc/game/version_manifest.json)

**Comment by MrGraversen** [comment]
It seems like there's now a JSON directive to read:

```
	"assets": "1.13",
	"downloads": {
		"client": {
			"sha1": "c0b970952cdd279912da384cdbfc0c26e6c6090b",
			"size": 16033625,
			"url": "https://launcher.mojang.com/mc/game/1.13/client/c0b970952cdd279912da384cdbfc0c26e6c6090b/client.jar"
		},
		"server": {
			"sha1": "d0caafb8438ebd206f99930cfaecfa6c9a13dca0",
			"size": 32649675,
			"url": "https://launcher.mojang.com/mc/game/1.13/server/d0caafb8438ebd206f99930cfaecfa6c9a13dca0/server.jar"
		}
```

**Comment by ptrj** [comment]
They changed url ? https://minecraft.net/en-us/download/server
and even you download jar file manually, start doesn't work
`[ FAIL ] Starting mcserver: Executable was not found:
 * /path/mcserver/serverfiles/minecraft_server.jar nogui`

**Comment by dementedusa** [comment]
I downloaded the server .jar file and put it into the directory it was in and then when I tried to run it it put out an eror with double nogui.  so I went to the mcserver.cfg and down on line 92 got rid of the nogui and it worked.

**Comment by ptrj** [comment]
```
+++++ '[' '!' -f /var/mcserver/lgsm/functions/check_executable.sh ']'
+++++ '[' noforce == forcedl ']'
+++++ '[' -f /var/mcserver/lgsm/functions/check_executable.sh ']'
+++++ fn_dl_md5
+++++ '[' nomd5 '!=' 0 ']'
+++++ '[' nomd5 '!=' nomd5 ']'
+++++ '[' run == run ']'
+++++ source /var/mcserver/lgsm/functions/check_executable.sh
++++++ local commandname=CHECK
++++++++ readlink -f /var/mcserver/lgsm/functions/check_executable.sh
+++++++ basename /var/mcserver/lgsm/functions/check_executable.sh
++++++ local function_selfname=check_executable.sh
++++++ '[' '!' -f '/var/mcserver/serverfiles/minecraft_server.jar nogui' ']'
++++++ fn_script_log_warn 'Executable was not found: /var/mcserver/serverfiles/minecraft_server.jar nogui'
++++++ '[' -d /var/mcserver/log/script ']'
++++++ '[' -n CHECK ']'
+++++++ date '+%b %d %H:%M:%S.%3N'
++++++ echo -e 'Jul 20 17:48:50.089 mcserver: CHECK: WARN: Executable was not found: /var/mcserver/serverfiles/minecraft_server.jar nogui'
++++++ exitcode=3
++++++ '[' -d /var/mcserver/log/script ']'
++++++ fn_print_fail_nl 'Executable was not found:'
++++++ '[' -n Starting ']'
++++++ echo -en '\r\033[K[\e[31m FAIL \e[0m] Starting mcserver: Executable was not found:'
[ FAIL ] Starting mcserver: Executable was not found:++++++ sleep 0.5
++++++ echo -en '\n'

++++++ echo ' * /var/mcserver/serverfiles/minecraft_server.jar nogui'
 * /var/mcserver/serverfiles/minecraft_server.jar nogui
++++++ exitcode=1
++++++ core_exit.sh
```

**Comment by Synt3x** [comment]
Same issue as [https://github.com/GameServerManagers/LinuxGSM/issues/1944](url)

**Comment by UltimateByte** [comment]
#1944 has more sources to solve the issue, closing this one
