### ISSUE TITLE
[mcserver] Latest update does not download

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1944]
A new version of Minecraft is available however something has changed meaning the download does not work currently. I will investigate

**Comment by dgibbs64** [comment]
It looks like they are not using Amazon anymore for downloads. I will have to do a bit if work to get this up and running again. I will keep you updated

**Comment by Synt3x** [comment]
@dgibbs64, this link might help you. [https://www.spigotmc.org/threads/solved-new-vanilla-download-url.329567/](url)

**Comment by UltimateByte** [comment]
Fixed! 
Will be hotfixed in LinuxGSM soon ;)
