### ISSUE TITLE
Website clarity on creating a password for new setup.

### ISSUE THREAD

**Issue by Seyeght** [GameServerManagers/LinuxGSM#1945]
Someone has started targeting the usernames you suggested on your websites and has created a malicious self-replicating code to test these usernames with identical passwords on other servers/IPs. 

The suggestion is to add clarity that they should NOT be using the same password as the username, and someone even suggesting generating a random password for them to use instead.

**Comment by UltimateByte** [comment]
Would be awesome to add a random password generator on the website if possible. :)

**Comment by dgibbs64** [comment]
I have now deployed this
