### ISSUE TITLE
[pzserver] Creation

### ISSUE THREAD

**Issue by lifesfun** [GameServerManagers/LinuxGSM#195]
I am running a project zomboid server and was wondering if it would be possible to make a script for this as well. There is already a script available however, it is not as dynamic as your scripts: 

http://theindiestone.com/forums/index.php/topic/7504-linux-server-auto-install-project-zomboid-scripts/ 

There is the info incase you want to take a look.

**Comment by dgibbs64** [comment]
pzserver has now been released
