### ISSUE TITLE
CentOS required epel repo to use jq

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1956]
## User Story

As a CentOS server admin, I want epel automatically install with LinuxGSM and website docs to be updated.

## Basic info

* Distro: CentOS 7
* Feature: install

**Comment by UltimateByte** [comment]
I confirm this.
epel package is installed with:
yum install epel-release

Wether it's installed or not can be checked with:
yum list installed | grep epel-release
epel-release.noarch           7-11                           @epel

**Comment by NAndras95** [comment]
Hi,
Im new with LGSM, and i solved this with this commands, 

wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O jq
chmod +x jq
mv jq /usr/local/bin

**Comment by UltimateByte** [comment]
@NAndras95 
The proper solution is:
```
yum install epel-release
yum install jq
```

**Comment by dgibbs64** [comment]
Changes to
