### ISSUE TITLE
preparms="" for games that need extra start parms before executable

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#1957]
Hi,

Games such as Minecraft have extra parameters to put before the actual executable to run, for example, `java -parms1 -parms2 program.jar nogui`

For now, these parms are added to the `executable=""` variable, which is not clean in my opinion.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/mcserver/_default.cfg#L92
Also, this results in `javaram` parameter not being updated if users only copy just the `javaram` to their instance config file, because it's used later in the `executable=""` variable which was set in `_default.cfg`.

To address that, I suggest adding to the `fn_parms()` function a `preparms=""`variable containing these elements that are before the executable. 
That way, the executable variable will be more clean, and users won't need to blindly add the whole settings to their instance, only the `javaram` variable and `fn_parms` functions.

Then we can just add preparms to the start function in` command_start.sh`.

Feature is very easy to implement.

**We just need to address this first:**
It might break `start` for users updating their script, in the case where they have `executable` set in their instance but not `fn_parms`.
Reason is: the new `preparms` from the new `fn_parms` would add to these settings, with something like:
`${preparms} ${executable} ${parms}`
Expanding to:
`java -Xmx1024M -java java -Xmx1024M -jar /home/mcserver/serverfiles/minecraft_server.jar`

What do you think about it?
Do you have a workaround to prevent the possible issue stated here?
Also, do you think of any other games which would benefit from this feature?

Thanks

**Comment by dgibbs64** [comment]
Issue resolved with this PR https://github.com/GameServerManagers/LinuxGSM/pull/3151
