### ISSUE TITLE
Segmentation fault with gmod server

### ISSUE THREAD

**Issue by willcurry** [GameServerManagers/LinuxGSM#1959]
Hi, so recently my server has been crashing randomly (after being up for a good amount of hours) and the last message in console is "segmentation fault". I have researched this issue a lot, and tried everything suggested on the wiki but I cannot find a solution. Do you have any more things I could try to fix this issue?

**Comment by willcurry** [comment]
Sorry but I strongly feel like this is a bug. I never had this issue once with 4 years of using TCAdmin but after switching to linuxGSM I have this issue at least once a day.

**Comment by UltimateByte** [comment]
No it's not, read the FAQ about segfaults in the wiki. It's not script related in any way.

**Comment by dgibbs64** [comment]
I can confirm segfaults are related to the game server itself and not LinuxGSM. The issue can happen regardless of using LinixGSM. It is however a pain as it doesn't ever give you a reason why when it happens. Possibly somtjing with your distro it doesn't like.

**Comment by jusito** [comment]
@willcurry because I experienced it the last days, check you Hardware! My RAM was done and got on every map change or during start this - Segmentation fault (core dumped).

Had problems like this a few month, but a restart solved this.
