### ISSUE TITLE
LGSM Telegram alert proxy support

### ISSUE THREAD

**Issue by btgsystem** [GameServerManagers/LinuxGSM#1960]
Add the functionality of specifying a proxy server for telegram alerts.

**Comment by UltimateByte** [comment]
Can probably be easily added.

Do you have command line examples to push a proxied alert?

**Comment by btgsystem** [comment]
As far as I know, need to add option "--socks5 proxyip:proxyport"

From man: 
In curl >= 7.21.7, you can use
`curl -x socks5h://localhost:8001 http://www.google.com/`
In curl >= 7.18.0, you can use
`curl --socks5-hostname localhost:8001 http://www.google.com/`

**Comment by btgsystem** [comment]
This option works:
`telegramsend=$(${curlpath} --socks5 proxyip:proxyport -U proxyuser:proxypass -sSL -H "Content-Type: application/json" -X POST -d """${json}""" "https://api.telegram.org/bot${telegramtoken}/sendMessage" ${curlcustomstring} | grep "error_code")`
Only need to specify proxyip, proxyport & proxyuser,proxypass if it is needed.
You can add these parameters to the configuration.

**Comment by dgibbs64** [comment]
Please can the wiki be updated to include a section on telegram proxy
https://github.com/GameServerManagers/LinuxGSM/wiki/Telegram

**Comment by xes66** [comment]
please add parametr for telegram proxy
telegramalert="on"
telegramtoken=""
telegramchatid=""
proxyip""
proxyport""
proxyuser""
proxypassword""
curlcustomstring=""

**Comment by dgibbs64** [comment]
This was implemented in 2018
https://github.com/GameServerManagers/LinuxGSM/pull/1901
