### ISSUE TITLE
arma3server install fails

### ISSUE THREAD

**Issue by Khelgar1** [GameServerManagers/LinuxGSM#1964]
The install for arma3server fails to create the lgsm directory structure after running `./linuxgsm.sh arma3server`

When you follow the instructions on the arma3server web page and try to edit common.cfg to put in the credentials the files and the directory structure don't exist. 

Then if you go to step 4 and try to run `./arma3server install` the install fails because there is no common.cfg file with the steam credentials

If you manually create the directory structure and download the _default.cfg from github the install works

**Comment by aklin** [comment]
I got this myself when I tried installing a new HC. It looked like downloading the config files from github failed for some reason. Tried again after an hour or so and it worked.

**Comment by UltimateByte** [comment]
Might be a temporary issue with github then?
@Khelgar1 can you please try again?

**Comment by Khelgar1** [comment]
![image](https://user-images.githubusercontent.com/23195823/44797341-df0ea580-aba6-11e8-91bd-e59acdf5442f.png)

Still getting the same error when following the web page instructions

$ tree lgsm
lgsm
└── tmp
    └── data
        └── serverlist.csv

2 directories, 1 file

The directories are not being created. If I try to run 

```./arma3server install``` 

I get

```Installing SteamCMD
=================================
    fetching check_steamcmd.sh...OK
[ FAIL ] Install arma3server: Steam login not set. Update steamuser in /home/testbed/lgsm/config-lgsm/arma3server
        * Change steamuser="username" to a valid steam login.
    fetching core_exit.sh...OK
```

**Comment by marvinlehmann** [comment]
#1554 (?)

**Comment by Khelgar1** [comment]
I don't think this part of linuxgsm.sh is getting run at all on a fresh install

```
# LinuxGSM Server Mode
else
	core_functions.sh

	# Load LinuxGSM configs
	# These are required to get all the default variables for the specific server.
	# Load the default config. If missing download it. If changed reload it.
	if [ ! -f "${configdirdefault}/config-lgsm/${gameservername}/_default.cfg" ]; then
		mkdir -p "${configdirdefault}/config-lgsm/${gameservername}"
		fn_fetch_config "lgsm/config-default/config-lgsm/${gameservername}" "_default.cfg" "${configdirdefault}/config-lgsm/${gameservername}" "_default.cfg" "nochmodx" "norun" "noforcedl" "nomd5"
```

The whole "if" block from line 269 seems to be preventing it but my coder-fu is weak so I could be totally wrong

**Comment by h3o66** [comment]
I am not sure if this is still a issue now, iuf yes, can someboday still reproduce this ?
