### ISSUE TITLE
Rustserver documentation needs updating to include jq dependency

### ISSUE THREAD

**Issue by transelement** [GameServerManagers/LinuxGSM#1966]
When installing rustserver per the documentation at https://linuxgsm.com/lgsm/rustserver/ you run into the following:

```
[ERROR ] Install rustserver: Checking dependencies: missing: jq

Warning! dcrust does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt update; sudo apt install jq

```

Which is a result of jq missing from the list of dependencies via the documented ```sudo apt install ...``` command.  Seems the requisite for jq was introduced recently?

The installation continues anyway, which I think is another issue.  An 'ERROR' should be a full stop to provide the opportunity to fix the issue at hand.  Without a careful eye the error above can easily go unnoticed.  I don't know how not having jq installed, or any other dependency missed will manifest itself later in the setup process, but I bet it's not as intuitive as the error above.

I suggest:
- Adding jq to the dependency list
- Have dependency errors cause a hard stop, or at least a prompt.

**Comment by UltimateByte** [comment]
Actually, the issue is not that jq should be added to Rust dependencies, but rather to be removed.

See #1967

**Comment by transelement** [comment]
You're welcome.

**Comment by UltimateByte** [comment]
Thanks for the good issue and the feedback, your concern is much appreciated and always helps. Please feel free to open great issues like that any time you notice a bug.

**Comment by UltimateByte** [comment]
Just to provide you with a feedback about this, jq has been added to server dependencies, it was not a mistake and is now a real requirement for all games.
#1967 for more details.
