### ISSUE TITLE
Poor missing dependency handling

### ISSUE THREAD

**Issue by transelement** [GameServerManagers/LinuxGSM#1969]
This issue was brought up and conveniently ignored in #1966 however still remains.

When a missing dependency is identified by the installer it should STOP or PROMPT the user to resolve the error at hand, rather than continuing the install leaving the missing dependency 5 pages in scrollback.

As it stands the following flashes by the terminal:
```
[ERROR ] Install $SERVER: Checking dependencies: missing: $DEPENDENCY 

Warning! $USER does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt update; sudo apt install $DEPENDENCY
```

Which "isn't enough."

Notwithstanding the fact that you should never recommend that a game server user have sudo rights to apt to install _anything_.

**Comment by UltimateByte** [comment]
I agree with that, sudo should not be recommended imo.

**Comment by dgibbs64** [comment]
Dependency checker now stops if dependencies for SteamCMD are missing. Preventing SteamCMD from failing to run.

Also if you run `./gameserver install` as root it will not install dependencies only.

I am reluctant to prevent server installation if all dependencies are not met as there are sometimes issues with dependency detection. However a review of this would be a good idea

**Comment by dgibbs64** [comment]
A missing dependency is highlighted every time a server starts and various refactoring has been completed that should have improved dependency checking. I will close this and it can be re-raised if more work is required
