### ISSUE TITLE
[Server Request] Colony Survival 

### ISSUE THREAD

**Issue by Speshals** [GameServerManagers/LinuxGSM#1974]
**What game server Would you like adding?**
Colony Survival

**Can you link to any tutorials or guides?**
https://colonysurvival.gamepedia.com/Dedicated_Server#Installation_.28Linux.29

**Is the server on Steam?**
748090

**Is the server supported on Linux?**
Yes with mono.

**Comment by Committing** [comment]
+1 would appreciate this addition

**Comment by h3o66** [comment]
So if anyone is interested, I have a basic support what needs to be tested first, as i could only test the basic server here.
See for this the linked PR
