### ISSUE TITLE
Unable to start SAMP

### ISSUE THREAD

**Issue by SooomS** [GameServerManagers/LinuxGSM#1977]
#Hello i am having a problem when i start Samp with ./sampserver start

this message shows up

failed to connect to server: Connection refused
[ FAIL ] Starting sampserver: Unable to start SA-MP 0.3 Server

can someone tell me how can i fix this? :/

**Comment by UltimateByte** [comment]
Hello,

This issue is not confirmed to be a global issue. it might just be a firewall issue from your side.
Please use our ways of getting support and come back on github with relevant details if you think this is a global issue.

Regards
