### ISSUE TITLE
Add list of dependencies to LinuxGSM.com/list

### ISSUE THREAD

**Issue by Bourne-ID** [GameServerManagers/LinuxGSM#1979]
I'm experimenting with automatic end-to-end testing of LinuxGSM through Docker/Vagrant and Ansible to test that the OS, architecture and dependencies are correct and will allow the game server to be installed, run and managed successfully when an OS change/release or application change is made. 

Most users will use the LinuxGSM website for installing dependencies before running the LinuxGSM install commands. I want to use this data for my testing by [building a script](https://github.com/Bourne-ID/linuxgsm-tester-parser) to take the listed dependencies per game server and generate Ansible variable configuration files. 

The issue I have is the dependencies are listed on the specific server pages but not in the [Lists](https://linuxgsm.com/list/) page - as such I'm having to develop a web crawler and parser to obtain all the server pages and then make individual calls to parse the dependencies of the game servers. Whilst this is ~90 calls at the moment, this number will only increase as LinuxGSM expands. 

Adding a table containing the game name, game short name and the list of dependencies (including adding i386) to the lists page of game server dependencies would reduce the number of calls required down to one or two calls, saving bandwidth and reduces the traffic to the website. From discussions in Discord, it may be a simple change to the site, and if true then I would like to request this. 

Many Thanks

**Comment by dgibbs64** [comment]
a new feature allows ./gameserver install to install dependencies automatically. Not sure if that helps

**Comment by Bourne-ID** [comment]
It gives me additional options to play with, for example allows testing to ensure the dependencies listed on the website matches the dependencies being automatically installed.

**Comment by dgibbs64** [comment]
Old issue I am closing this. Please re-open if more is required
