### ISSUE TITLE
Rust Server, Oxide Mod

### ISSUE THREAD

**Issue by eiol** [GameServerManagers/LinuxGSM#1982]
The plugin is using a new domain. Command to update the mod is not working.

Old, https://oxidemod.org/downloads/oxide-for-rust.1659/
New, https://umod.org/games/rust/download

**Comment by UltimateByte** [comment]
We're using GitHub links already.
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/mods_list.sh#L30-L32
