### ISSUE TITLE
ld-linux-x86-64.so.2 Cause server CPU too high

### ISSUE THREAD

**Issue by diguo520** [GameServerManagers/LinuxGSM#1983]
![snipaste_2018-08-11_18-14-27](https://user-images.githubusercontent.com/20224521/43990757-8bad3158-9d92-11e8-9e75-696b6ce0a371.png)
![snipaste_2018-08-11_18-15-14](https://user-images.githubusercontent.com/20224521/43990758-8f95d11c-9d92-11e8-9a57-fa5c023f7566.png)
![snipaste_2018-08-11_18-15-14](https://user-images.githubusercontent.com/20224521/43990759-9109d3d6-9d92-11e8-9969-85200e9ffbfe.png)
May I ask if you solve this problem

**Comment by dgibbs64** [comment]
This issue is not related to LinuxGSM. This is an Arma 3 issue.
