### ISSUE TITLE
Game Server Support Forums

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#1984]
Sometimes a question is better asked in the official support forums for the game server. A list of these would use useful to have to point people in the right direction.

**Comment by Frappocalypse** [comment]
Here are some of what I imagine are the common ones. For a lot of Source games, the official forums are Steam Discussions, which aren't always a whole lot of help, so adding a third-party specialised forum as well might make sense.
- [ARK: Survival Evolved](https://survivetheark.com/index.php?/forums/forum/39-server-administration/)
- [ARMA 3](https://forums.bohemia.net/forums/forum/159-arma-3-servers-administration/)
- [Counter-Strike: Global Offensive](https://steamcommunity.com/app/730/discussions/)
- [Counter-Strike 1.6](https://steamcommunity.com/app/10/discussions/)
- [Counter-Strike: Source](https://steamcommunity.com/app/240/discussions/)
- [Day of Defeat: Source](https://steamcommunity.com/app/300/discussions/)
- [Day of Infamy](https://steamcommunity.com/app/447820/discussions/)
- [GoldenEye: Source](https://forums.geshl2.com/)
- [Garry's Mod](https://forum.facepunch.com/f/)
- [Insurgency](https://steamcommunity.com/app/222880/discussions/2/)
- [Killing Floor 2](https://forums.tripwireinteractive.com/forum/killing-floor-2/technical-support-ae/dedicated-server-support-ac)
- [Minecraft](https://www.minecraftforum.net/forums/servers-java-edition/minecraft-server-hosting)
- [Quake 3](https://steamcommunity.com/app/2200/discussions/)
- [Rust](https://forum.facepunch.com/f/)
- [Terraria](https://forums.terraria.org/index.php?forums/)
- [Team Fortress 2](https://steamcommunity.com/app/440/discussions/)
- [Teamspeak 3](https://forum.teamspeak.com/forums/93-TeamSpeak-3-Technical-Discussions-EN-DE)
- [Unreal Tournament 2004](https://www.epicgames.com/unrealtournament/forums/past-unreal-tournament-games/unreal-tournament-2003-2004)
- [Unreal Tournamnet 3](https://www.epicgames.com/unrealtournament/forums/past-unreal-tournament-games/unreal-tournament-3)
- [Unreal Tournament 99](https://www.epicgames.com/unrealtournament/forums/past-unreal-tournament-games/unreal-tournament-%E2%80%9899)

**Comment by dgibbs64** [comment]
Thanks for this!!! Saves me a lot of time and research!

**Comment by Frappocalypse** [comment]
@dgibbs64 No problem, I can do more if that's what you're looking for, and get some useful third party form links too.

**Comment by dgibbs64** [comment]
Yeah anything you think would be useful. A new docs platform is being setup so would be really useful for that :)

**Comment by dgibbs64** [comment]
This info will need to be added to the website

**Comment by dgibbs64** [comment]
Can be added to 

http://docs.linuxgsm.com
