### ISSUE TITLE
Arch Linux automatic dependency checking/installing

### ISSUE THREAD

**Issue by MaxMatti** [GameServerManagers/LinuxGSM#1990]
I want to implement this. Should I just edit the relevant lines in `lgsm/functions/check_deps.sh` or would I need to implement any testcases or similar to get it merged?

**Comment by dgibbs64** [comment]
Yeah just do the edits and test yourself. If you could then do a pull request and an output of your working test results that would be awesome!

**Comment by dgibbs64** [comment]
As there is no update on this as current stats so no LinuxGSM usage on arch I will close this
