### ISSUE TITLE
Add secrets configuration: `secrets.cfg`

### ISSUE THREAD

**Issue by aklin** [GameServerManagers/LinuxGSM#1993]
I would like to track my config directory with git, but I'd rather not compromise my Steam credentials which are stored in `common.cfg`.

I propose adding a new file, `secrets.cfg` or similar, in the same directory as `common.cfg`. This new file will get sourced just before common configuration. This would allow adding the secrets file to gitignore.

---

I tried doing this and sourcing the secrets from common.cfg, but my bash-foo isn't good enough (though there is [a way](https://unix.stackexchange.com/a/273348/34451) I haven't tried), and I'm not sure what would happen to it after an LGSM update anyway.

I'm happy to do this myself if the team thinks it's a good idea.

**Comment by UltimateByte** [comment]
I see no objection as long as it doesn't interfere with regular usage and is documented in the wiki. For me, feel free to PR. @dgibbs64 any issue with this?

**Comment by dgibbs64** [comment]
I have managed to do this. The only issue is ensuring that people understand that the secrets cfg is not encrypted or anything.
