### ISSUE TITLE
[Server Request] SCP Secret Laboratory

### ISSUE THREAD

**Issue by gabmiral** [GameServerManagers/LinuxGSM#1995]
## What game server would you like adding?

SCP: Secret Laboratory

## Can you link to any tutorials or guides?

https://steamcommunity.com/app/700330/discussions/1/1692662484248805180/

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

786920

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [x] Yes
* [ ] No

**Comment by KILLERMANTV** [comment]
Server for Linux is working with mono.

**Comment by moelrobi** [comment]
The Making of an SCP got way simpler with this AppID: 786920

It installs the Game Server + MultiAdmin and ServerMod 2 (both required for better Linux Support)

Also a better Tutorial for this: https://github.com/Grover-c13/Smod2/wiki/ServerMod-Installation-(Linux)

I would love to see a LGSM Support for SCP:SL, and would like if possible to support it. :+1:

**Comment by dgibbs64** [comment]
https://en.scpslgame.com/index.php?title=Guide:Hosting_a_server#Prerequisites_2
