### ISSUE TITLE
[Request] Add some Custom in to Alerts

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#1998]
**Is your feature request related to a problem? Please describe.**
```
I want see some custom in Alerts.
```

**Describe the solution you'd like**
```
I mean, can you add custom in alerts.
Custom like a: 
> Text, // We can change default text to custom.
>Name of WebHook in Discord (and name of other type alerts.) // We can change default name (LinuxGSM) and default (avatar) Icon.
> etc
```

**Additional context**
For example, discord alerts:
![image](https://user-images.githubusercontent.com/25010528/44910625-8d902300-ad2c-11e8-9c2b-bd98c44845cd.png)

There we see:
```
> Name (LinuxGSM) and default Icon
> Alert msg
> Game
> Server Name
> Host Name
> Server IP
> "More Info"
```
For example: I create Discord Web Hook with My Custom name and icon... but he did't work because LGSM change this manualy. This bad Too.

So if I want change some?
for example: I want (for example) change Icon and Name to my custom.
Next, I want change languange of msg, (to FR or etc)
and I want change other info (not static like a HostName, Server name, Server IP etc.)
But I can't do this because LGSM check files and reset all changes.

Can you add this (in future) to LGSM?

Thanks for attention.

**Comment by BattleSheep94** [comment]
change the alert_discord.sh

**Comment by dgibbs64** [comment]
Im not sure why changing the wording of the alerts are useful. I can see why a language change is useful. However, altering wording adds a whole new level of complexity into the software that would be very difficult to manage.
