### ISSUE TITLE
Alert if Update available?

### ISSUE THREAD

**Issue by BattleSheep94** [GameServerManagers/LinuxGSM#2001]
Is there a way that LGSM Alert me if a Serverupdate is available?
I need it for the Rustserver. If a Gameserver Update is available i cant update it instantly because there isnt instant a update available for oxide. Because of that i need to be informed if a update is available.

Thanks for you answer.

**Comment by UltimateByte** [comment]
There is no way to just be alerted if an update is available at the moment. Simple feature that is not implemented yet.
Thank you for the suggestion.

**Comment by dhurley94** [comment]
Creating a cronjob that runs every few minutes that attempts to update the server with the `update` parameter should work if you do not need to be notified. If an update is not available the server will not be restarted iirc.

**Comment by UltimateByte** [comment]
Games like Rust require further action upon updating (like wiping) so that would be a good feature to have. Like `update-check` command that will only return if an update is available or not and alrt you if it is.

**Comment by MrGraversen** [comment]
Hi @UltimateByte, I would also find an `update-check` (and `mods-update-check`!) command very useful.

On my Rust server, if an update is required, I need to also `mods-update` for Oxide, and then restart the server, in sequence.

**Comment by UltimateByte** [comment]
Unfortunately, mods don't have a reliable way to be checked for version, for now this isn't possible, updating mods just redownloads and overwrites files for the mod (with config files excluded).

**Comment by h3o66** [comment]
If someone is willing to test the linked PR, we could maybe add this in the next release
