### ISSUE TITLE
[Request] Insurgency Sandstorm

### ISSUE THREAD

**Issue by Outpox** [GameServerManagers/LinuxGSM#2004]
**What game server Would you like adding?**
Insurgency Sandstorm

**Can you link to any tutorials or guides?**
[Official documentation](https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit)  

**Is the server on Steam?**
Yes. `581320`

**Is the server supported on Linux?**
I believe it is.

**Comment by dgibbs64** [comment]
https://steamdb.info/app/581320/ that is the appid for the game. No Dedicated server files are currently listed on steam

**Comment by dgibbs64** [comment]
I will close this issue. Please re-raise once Insurgency Sandstorm dedicated server is available

**Comment by Outpox** [comment]
Oh yeah that's right. The developers delayed the release to December which should include a server browser so I believe the tools to host a server will be released at the same time. I'll re-open the issue in December :D

**Comment by Outpox** [comment]
Hey there!
The dedicated sever update was released today so I believe this issue could be reopened.  
You can find the official (for now) doc [here](https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit).

**Comment by dgibbs64** [comment]
https://steamdb.info/app/581330/

**Comment by jigsaw77** [comment]
All Sandstorm Community waiting for server LGSM. Thank you for your wiek.

**Comment by flyingmongoose** [comment]
While this is technically closed I'm having a strange issue that I think is related to this.

When I run a start manually (without the GSM) everything works fine.

When I run through GSM it reverts my server down to a coop server.

Basically just going into the directory and running it manually with the params I want just plain works. if I try to use the command via GSM it's like it's ignoring the param settings except for the map I want.

I've double checked all params and it LOOKS right to me. But maybe someone else has run into this. (Let me know if this should have been a new ticket but this is insurgency sandstorm specific)

**Comment by dgibbs64** [comment]
Please raise a new issue otherwise it may be missed
