### ISSUE TITLE
Oxide Installer/Updater is not working (RUST)

### ISSUE THREAD

**Issue by Ryan-Nolan** [GameServerManagers/LinuxGSM#2011]
The lgsm Oxide Installer/Updater no longer works due to the url it uses being redirected to the new umod location.

Either the url needs updating or you need to set the correct flags to enable curl to follow redirects.

Here's a reference to the issue.
https://umod.org/community/281-rust/1203-linux-gsm-not-installing-oxide

**To Reproduce**
1. Go to shell
2. run './rustserver mods-install' or './rustserver mods-update'
3. See error

** Minimum Information **
Game Server: Rust
Postdetails Link: https://hastebin.com/alasaqunaw

**Comment by UltimateByte** [comment]
Hello,

Thank you for the notice.
Is this also true for other unity games that support Oxide? (or should I say "umod")

**Comment by lukespragg** [comment]
> Hello,
> 
> Thank you for the notice.
> Is this also true for other unity games that support Oxide? (or should I say "umod")

Not at the moment, we're working on rebranding and moving. All of the old links will still work though, as I mentioned in the referenced issue; just make sure to handle redirects with curl by using -L.

**Comment by dgibbs64** [comment]
#2008 pr merged in a hotfix
