### ISSUE TITLE
[Server Request] Jedi Knight II – Jedi Outcast

### ISSUE THREAD

**Issue by Lebawurscht** [GameServerManagers/LinuxGSM#2014]
**What game server Would you like adding?**
STAR WARS™ Jedi Knight II: Jedi Outcast™

**Can you link to any tutorials or guides?**
No useful ones, sorry

**Is the server on Steam?**
No

**Is the server supported on Linux?**
Yes its supported on Linux

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/1202 Is this the same thing?

**Comment by Lebawurscht** [comment]
Oh sorry, i have not seen that there is already a request for this server. #1202 is the same as this, also #1251  is the same.

**Comment by dgibbs64** [comment]
Haha didn't notice the 3 requests. Must be a popular server

**Comment by AlexCSilva** [comment]
I did get jedi outcast and jedi academy working but on a really old branch, was thinking of redoing it so they're up to date.

**Comment by AlexCSilva** [comment]
nateberkopec started it and I added changes, I think some things are missing though like downloading the jk2mv client, https://github.com/AlexCSilva/LinuxGSM/commits/jk2

**Comment by dgibbs64** [comment]
Awesome! When you are ready put a or in and we can review and merge when we are happy

**Comment by dgibbs64** [comment]
Duplicate of #1202
