### ISSUE TITLE
[Server Request] Project Cars 2

### ISSUE THREAD

**Issue by AokiAhishatsu** [GameServerManagers/LinuxGSM#2024]
**Can you link to any tutorials or guides?**
http://forum.projectcarsgame.com/forumdisplay.php?143-Multiplayer

**Is the server on Steam?**
Yes, AppID: 413770

**Is the server supported on Linux?**
Yes

**Comment by DigitalFriends** [comment]
Hi, any progress on this? 
I can help testing this out.
