### ISSUE TITLE
Potential New Sven Coop Dependency(Ubuntu 18.04)

### ISSUE THREAD

**Issue by WorthlessJ** [GameServerManagers/LinuxGSM#2029]
I am running my Sven Coop server on Ubuntu 18.04, and received this error after installing the server:

```LoadLibrary failed on /home/svencoop/serverfiles/./svencoop/dlls/server.so: libz.so.1: cannot open shared object file: No such file or directory
Host_Error: Couldn't get DLL API from /home/svencoop/serverfiles/./svencoop/dlls/server.so!
FATAL ERROR (shutting down): Host_Error: Couldn't get DLL API from /home/svencoop/serverfiles/./svencoop/dlls/server.so!
```
I thought it was due to a problem with my libssl1.0.0:i386, which is usually why that message appears AFAIK. After a hour of troubleshooting, ended installed zlib1g:i386 which seemed to fix the problem, server running without errors now.

TL:DR; zlib1g:i386 seems to be a new manually required install on Ubuntu 18.04

Cheers, this was the easiest/most visable place for me to post this.

**Comment by dgibbs64** [comment]
I have added libssl1.0.0:i386 as a requirement in LinuxGSM as for some reason was missing `zlib1g` was already installed on my test system. So am not sure if `zlib1g` would normally be installed on install of Ubuntu.

**Comment by dgibbs64** [comment]
I can also still confirm that sven co-op does not work on both CentOS and Fedora

**Comment by dgibbs64** [comment]
Relates to #1877

**Comment by dgibbs64** [comment]
9ca222ad9e76bb228c0dc74ccc3b99b804b28a39
