### ISSUE TITLE
Add sv_lan and sv_cheats options to csgoserver default config file

### ISSUE THREAD

**Issue by borzaka** [GameServerManagers/LinuxGSM#2031]
The idea is came from the official [Counter-Strike: Global Offensive Dedicated Servers](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers) page.
Under [Advanced Configuration](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers#Advanced_Configuration) there is an example autoexec.cfg:

```
log on //This is set to turn on logging! Don't put this in your server.cfg
hostname "Counter-Strike: Global Offensive Dedicated Server"
rcon_password "yourrconpassword"
sv_password "" //Only set this if you intend to have a private server!
sv_cheats 0 //This should always be set, so you know it's not on
sv_lan 0 //This should always be set, so you know it's not on
exec banned_user.cfg
exec banned_ip.cfg
```

So, these two sounds like a great idea to add to csgoserver default config file:
> sv_cheats 0 //This should always be set, so you know it's not on
> sv_lan 0 //This should always be set, so you know it's not on

Benefits:
- you know it's not on, or it's on
- you could set this settings per instance: maybe you want an instance with `sv_cheats 1` for practice, and another one for only lan games (`sv_lan 1`), etc.

**Comment by ohbus** [comment]
This issue has been addressed over [here in this merge](https://github.com/GameServerManagers/Game-Server-Configs/pull/68).

Please close this issue as it has now been **resolved.**

Thank you.

**Comment by borzaka** [comment]
This issue is resolved via:
- [Game-Server-Configs #68](https://github.com/GameServerManagers/Game-Server-Configs/pull/68)
- https://github.com/GameServerManagers/Game-Server-Configs/commit/f5f339b59987b96985b9eeaa01b11f6f929abe2b#diff-e6740dbdb68468b3d1f7c1341bf1152f

I think the best practice is to set these values in the config files, not in the command line.

**Comment by ohbus** [comment]
Kudos!
