### ISSUE TITLE
Terraria requires SteamCMD login?

### ISSUE THREAD

**Issue by Skyrid3r** [GameServerManagers/LinuxGSM#2035]
I just noticed that when I attempted to install a Terraria server, it's asking for steam credentials.

> [ FAIL ] Install terrariaserver: Steam login not set. Update steamuser in /home/games/terraria/lgsm/config-lgsm/terrariaserver
>         * Change steamuser="username" to a valid steam login.

Though the server files can be downloaded at: https://terraria.org/ , scroll down to "Dedicated Server" at the bottom footer without the need to login into Steam. Maybe it should be adjusted so an actual user/pass would of steam wouldn't have to be added.

**Comment by dgibbs64** [comment]
That is a zip archive. There is a dedicated server appid (not updated in 3 years), the game appid (that includes the dedicated server), and the dedicated zip archive on the website. Ideally we want to use steamcmd Dedi appid. Confirmation from the terraria Devs about which is best would be useful. Are there any contact details for them I could use?

**Comment by Skyrid3r** [comment]
I suppose you can contact their team at https://re-logic.com or join the discord server.

**Comment by Skyrid3r** [comment]
Awesome! Let me know what they'll reply.. (if they are gonna reply that is). The re-logic team is also available on their discord server ( https://www.discord.gg/terraria ), and maybe the community is helpful enough to give you the answer you seek.

**Comment by marvinlehmann** [comment]
Seems to be the same as Teeworlds where the server is in the same package as the client (same appid).

Quoting JonnyBoy0719, developer of BrainBread 2:

> To have anonymous login you have to create a Tool AppID, not a gameID. Todo so, if you are a developer for that certain game, you need to login into SteamWorks and create a "Tool" for it, or contact Valve about it.

**Comment by dgibbs64** [comment]
I re-emailed them again as they never responded

**Comment by Skyrid3r** [comment]
What about their discord?

**Comment by dgibbs64** [comment]
I sadly heard nothing back. I am closing this issue currently as I don't see this progressing
