### ISSUE TITLE
[Server Request] Eco

### ISSUE THREAD

**Issue by SyntleLmao** [GameServerManagers/LinuxGSM#2036]
**What game server Would you like adding?**
Eco

**Can you link to any tutorials or guides?**
https://eco.gamepedia.com/Setting_Up_a_Server
https://eco.gamepedia.com/Setting_Up_a_Server_(advanced)

**Is the server on Steam?**
https://steamdb.info/app/382310/

**Comment by dgibbs64** [comment]
Already released

https://linuxgsm.com/lgsm/ecoserver/
