### ISSUE TITLE
WARNING: setlocale('en_US.UTF-8') failed

### ISSUE THREAD

**Issue by borzaka** [GameServerManagers/LinuxGSM#2038]
```
csgoserver@dellserver:~$ ./csgoserver force-update
[  OK  ] Stopping csgoserver: Graceful: sending "quit": 4: OK
[  OK  ] Update csgoserver: SteamCMD
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '740' already up to date.
[  OK  ] Fix csgoserver: Applying workshop map fix: Counter-Strike: Global Offensive
[  OK  ] Starting csgoserver: LinuxGSM
csgoserver@dellserver:~$
```

`Linux dellserver 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64`

`Counter-Strike: Global Offensive - Linux Game Server Manager - Version 180908`

[Server information hastebin](https://hastebin.com/dagusotewo)

**Comment by UltimateByte** [comment]
Not a LinuxGSM issue.

Use en_US.UTF-8 locale and the warning wil go away.

If on debian
`dpkg-reconfigure locales`

**Comment by borzaka** [comment]
Thank you; I had to install the `en_US.UTF-8` locale.

I was using only `hu_HU.UTF-8 UTF-8` - hungarian / Hungary

**Comment by dgibbs64** [comment]
Maybe one for the docs

**Comment by UltimateByte** [comment]
Done :)

https://github.com/GameServerManagers/LinuxGSM/wiki/FAQ#warning-setlocaleen_usutf-8-failed-using-locale-c-international-characters-may-not-work

**Comment by dgibbs64** [comment]
Lovely . I will need to move it to the new docs as well :).

**Comment by borzaka** [comment]
@UltimateByte Your changes is missing from the new docs: [FAQ](https://docs.linuxgsm.com/support/faq)

**Comment by leshacat** [comment]
Should work in any locale. This is not a fix to force the user over to EN_US locale.

If you think not, what are locales for then?
