### ISSUE TITLE
Outdated Cronjob commands

### ISSUE THREAD

**Issue by borzaka** [GameServerManagers/LinuxGSM#2040]
[Cronjobs / Full examples](https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs#full-examples) has some outdated startup commands, which aren't in the [Command list](https://github.com/GameServerManagers/LinuxGSM/wiki/Command-List).

- What is `uf`?
- Why `force-update` is not listed in the Command list?

**Comment by UltimateByte** [comment]
`uf`(update-functions) is equal to `ul` (update-lgsm)
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/core_getopt.sh#L20
All games have it, but it would be preferable to change "uf" in examples with the new "ul". Anybody can edit the wiki, feel free to make the change!

`force-update` is equal to the even older `update-restart`
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/core_getopt.sh#L28
All steam games have it.

**Comment by dgibbs64** [comment]
Recent changes to documentation now run from https://docs.linuxgsm.com. I have taken steps to update the docs there

**Comment by borzaka** [comment]
Which docs are the most recent? Github Wiki, or the docs.linuxgsm.com?
Some links on the docs.linuxgsm.com points to Github Wiki.
