### ISSUE TITLE
srcds getting wrong public ip

### ISSUE THREAD

**Issue by serhatozles** [GameServerManagers/LinuxGSM#2047]
We have a dedicated and its public ip: x.x.x.170. We have a firewall also and we gave x.x.x.177 ip with firewall not on vds. We cant give on VDS. The Server is working but I cant join the server. Because it's taking wrong ip. I'm using to VPN to connect our servers.

-DEDICATED SERVER (x.x.x.170)
--VDS (LAN IP: 172.16.20.3)

-FIREWALL
--We gave access to the ports of x.x.x.177 to connect our 172.16.20.3
--172.16.20.3 doesnt have a public address directly. It's going out on thr firewall.

 This my command;

./srcds_run -game csgo -usercon -strictportbind -ip 172.16.20.3 +net_public_adr x.x.x.177 -port 27015 +clientport 27005 +sv_setsteamaccount xxx -tickrate 128 +map de_dust2 +servercfgfile csgoserver.cfg -maxplayers_override 20 +mapgroup mg_active +game_mode 0 +game_type 0 -nobreakpad -debug

Normally, it should be: x.x.x.177 but its taken dedicated public address: x.x.x.170

Can you help me, please? How can I resolve that? 
Its checking to our public ip how can we disable it? Maybe it can be solve this.

RESULT:

Logging into Steam gameserver account with logon token 'XXXXXxxxxxxxxxxxxxxxxxxxxxxxx'
Connection to Steam servers successful.
Public IP is x.x.x.170.

**Comment by dgibbs64** [comment]
a specific IP address can be set using ip="0.0.0.0". LinuxGSM will bind the server to a specific address to allow monitoring to work correctly.
