### ISSUE TITLE
Project Zomboid server update 40.26 error

### ISSUE THREAD

**Issue by Culvanen** [GameServerManagers/LinuxGSM#2048]
Hello,

When updating my project zomboid server from 40.25 to 40.26 there is now an error, and apparently it happens every time: whether I use LGSM or update via steam, the problem remains.

" 64-bit java detected

./start-server.sh: line 12: ./ProjectZomboid64: No such file or directory"

In 40.25 no problem happens.

Thanks

**Comment by dgibbs64** [comment]
whats the output of `ls -al serverfiles/`?

**Comment by dgibbs64** [comment]
Just tested this myself and found no error.
