### ISSUE TITLE
Increase ram minecraft server

### ISSUE THREAD

**Issue by Pepito51** [GameServerManagers/LinuxGSM#2050]
Hello, I'm posting today for help. I recently installed a minecraft server thanks to the tutorial: https://linuxgsm.com/lgsm/mcserver/. And the problem is that I can not find where can we change the ram memory used by the server (1024MB by default).
I use Ubuntu 18.04

**Comment by BeatPlay** [comment]
That is literally the only setting you can change in the default config file. Just copy the _default.cfg to mcserver.cfg and change RAM
