### ISSUE TITLE
Find a way that Monitoring detect if server is (re)starting or not.

### ISSUE THREAD

**Issue by BattleSheep94** [GameServerManagers/LinuxGSM#2054]
My Server needs more than 2 minutes to (re)start.
If i "activate" the monitoring cronjob the server stucks in a loop from monitoring and restart.
Maybe you can add a "status" that the monitoring says. "Server is already restarting, try again in ${required-restarttime}"
Maybe with a time that you can define in the config where we can say how long the server needs to restart.

**Comment by dgibbs64** [comment]
A quick fix would be to extend the monitoring time in the Cron so something like 5-10 mins per check

**Comment by dgibbs64** [comment]
related to #2119

**Comment by h3o66** [comment]
do you know if this was solved with this #2119 ?

**Comment by dgibbs64** [comment]
all servers now have a query delay set. This means if the server has only just started there will be a delay before monitor queries the server for the first time. The monitor will still check that the executable is running. So I believe this fixes this issue
