### ISSUE TITLE
Teamspeak 3 Server Update Failed

### ISSUE THREAD

**Issue by Tex42** [GameServerManagers/LinuxGSM#2064]
The game server you are running: Teamspeak 3 Server
Your Linux distro and version: Ubuntu 18.04.1 LTS

Hallo, i have auto update "on" on my teamspeak server and the server wanted to update to ts3 server version 3.5.0 but gave me this error

" Applying update...
downloading teamspeak3-server_linux_amd64-3.5.0.tar.bz2...downloading teamspeak3-server_linux_amd64-3.5.0.tar.bz2...curl: (3) <url> malformed
FAIL "

i before downloaded the new lgsm functions update.

**Comment by echodreamz** [comment]
I am seeing this as well, same exact error.

`Applying update...
[ .... ] Stopping ts3server: TeamSpeak 3 Server
[  OK  ] Stopping ts3server: TeamSpeak 3 Server
downloading teamspeak3-server_linux_amd64-3.5.0.tar.bz2...downloading teamspeak3-server_linux_amd64-3.5.0.tar.bz2...curl: (3) <url> malformed
`

**Comment by echodreamz** [comment]
I also see that when the update fails, it doesnt restart TS. Is this the correct behavior?

**Comment by xopez** [comment]
I can say the same.
the update just finds an update and stops the server. On Fail the script just stops/exits.

**Comment by xopez** [comment]
The stop is maybe related to this: #1978

**Comment by dgibbs64** [comment]
I will get on this asap
