### ISSUE TITLE
I got accidental ban on your rust server.

### ISSUE THREAD

**Issue by TeoJason** [GameServerManagers/LinuxGSM#2069]
I was chopping up a sleeping bag in rust then suddenly i got ban for "fly hacking" it is accidental because its a glitch lets say my friend is boosting me up a base and i am bad at jumping therefor it will make it look like i am standing in the air so i got flyhack violation thrice without jumping and got instant banned from your server the 4th time. By the way i still can play in other rust server except your server due to the accidental banned. You can check my history i have no hacks record at all and with 50 games in my account.
https://steamcommunity.com/id/reclaimer99
Hopefully you guys can unbanned me I have been playing in your rust server for almost 2-3 months.
https://www.battlemetrics.com/servers/rust/2674974

**Comment by 0xlord** [comment]
How in heavens name did he end up here?! oO
This is a ticket system for the install/maintenance script "Linux Gameserver Manager". Not of your Rust server provider! Please contact him about your issue.

**Comment by 0xlord** [comment]
Again: This is a tool to SETUP a server. Here you won't find any help regarding the operation of an actual game server. Please contact that servers admin or let your friend ask ingame around.

**Comment by TeoJason** [comment]
I got unban 3 days ago then got ban again great haha.
