### ISSUE TITLE
Insurgency Sandstorm

### ISSUE THREAD

**Issue by 0xlord** [GameServerManagers/LinuxGSM#2070]
**What game server Would you like adding?**
Insurgency Sandstorm which dedicated server files got released today!

**Can you link to any tutorials or guides?**
https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit

**Is the server on Steam?**
AppID: 581330

**Is the server supported on Linux?**
Yes, natively through SteamCMD

**Comment by Outpox** [comment]
I already opened an issue #2004 in september :P

**Comment by dgibbs64** [comment]
Thanks for the update. This will be planed for the next release.

**Comment by dgibbs64** [comment]
duplicate of #2004 2004
