### ISSUE TITLE
Because it copies sounds found into your addons, the place where they should be.

### ISSUE THREAD

**Issue by chiranjitk** [GameServerManagers/LinuxGSM#2082]
_Originally posted by @UltimateByte in https://github.com/GameServerManagers/LinuxGSM/issues/1683#issuecomment-342664318_

**Comment by chiranjitk** [comment]
I found issue on your csgo script and Please fixed it.

/lgsm/functions/command_fastdl.sh  line:-184 and 323   the sound folder name is defined here sounds, for that reason the actually sound folder is excluded from searching.

**Comment by dgibbs64** [comment]
relates to #1999

**Comment by dgibbs64** [comment]
relates to #1999
