### ISSUE TITLE
rust status is online，but the rust server could not be found

### ISSUE THREAD

**Issue by Webrobot96** [GameServerManagers/LinuxGSM#2085]
rust status is online，but the rust server could not be found
https://hastebin.com/revovucefu

**Comment by Webrobot96** [comment]
No firewall, no error during startup

**Comment by mrpoundsign** [comment]
@Webrobot96 Do you mean in the server browser? Are you able to manually connect to the server? This has been a long standing issue for many server owners, and likely unrelated to LGSM.

**Comment by xzessmedia** [comment]
same here... of course i tried to connect manually by using console (F1) and client_connect ip:port

fresh install

**Comment by h3o66** [comment]
even if this is a old issue:
Imho this is not a lgsm issue - as the gameserver itself annouces to the server to the serverlist of the game.
There were a few other games that have as well this problem, but i am not sure what we can do.

**Comment by dgibbs64** [comment]
So I have found with rust that it can take several minutes to show on the server list as it is generating stuff on first start. Patience is required with a server like rust. I will close this as I belive this is a Rust specific thing and nothing I can do to resolve this
