### ISSUE TITLE
Backup missing hidden files 7dtd .local directory

### ISSUE THREAD

**Issue by HomeGrownCoder** [GameServerManagers/LinuxGSM#2087]
./sdtdserver backup

After unzipping the archive the .local directory is not included. This directory will have the save game data from the server. So restoring the server on the same host would not be an issue. But moving the server to a new host is an issue, since you have to copy the files out manually. 

Working as intended? or can script be updated?

**Comment by Eekiig** [comment]
You can find a workaround here:
https://github.com/GameServerManagers/LinuxGSM/issues/1535#issue-243347382

You should also take a look at this comment: 
https://github.com/GameServerManagers/LinuxGSM/issues/1535#issuecomment-319089708

**Comment by dgibbs64** [comment]
issue resolved with backing up hidden folders. A new issue has been raised regarding servers using ${HOME} and not ${rootdir} for some files. #2117
