### ISSUE TITLE
HLTV Startup script

### ISSUE THREAD

**Issue by MacGyver27** [GameServerManagers/LinuxGSM#2090]
Hello,

Please is there a way to execute HLTV startup script??

In the directory: `counter-strike/csosserver/serverfiles` I have `hltv.cfg` and `hltv.sh` (which just executes hltv)..

Anyway I would like to be able to link together HLTV Startup script after every server **start/restart**. What would be the best way for this?

Thanks, Michal

**Comment by dgibbs64** [comment]
see #1294

**Comment by MacGyver27** [comment]
I have seen it. I even left a reply but now answer since it was closed.. There still isnt any answer to that :/

Thx!

**Comment by dgibbs64** [comment]
I'm merging duplicates currently. Hltv will be looked at.

**Comment by MacGyver27** [comment]
when please?

**Comment by dgibbs64** [comment]
Its currently part of an epic #2105 as would require 2 tmux sessions. This needs to be resolved before I can add HLTV

**Comment by MacGyver27** [comment]
Appreciated. I'll be around so it's a blocker for me at the moment. Thanks

**Comment by klopikus** [comment]
YA tozhe hotel by uvidet' HLTV dlya servera
