### ISSUE TITLE
Insurgency Sandstorm Only Loading Coop

### ISSUE THREAD

**Issue by flyingmongoose** [GameServerManagers/LinuxGSM#2097]
I find it unlikely that this is Insurgency specific as when I run a manual command of the server executable everything loads as expected, example:
`./InsurgencyServer-Linux-Shipping Canyon?Scenario=Scenario_Crossing_Checkpoint_Security?MaxPlayers=32?Port=27102?QueryPort=27131 -hostname='HOSTNAMEHERE' -log`

When I run through GSM it reverts my server down to a coop server.

I've double checked all params and it LOOKS right to me. But maybe someone else has run into this.

It's almost like the params/arguments of the gsm config are being ignored, but not all of them (the right map and scenario is loading, the wrong game mode and player count [coop is 8 player max, I'm set to 32 as you see here]).

**Comment by 0xlord** [comment]
Checkpoint is coop IIRC ...

**Comment by flyingmongoose** [comment]
strange that it didn't load it as coop when I did it manually though, but I'll sift through my settings and check things then, thank you.

**Comment by flyingmongoose** [comment]
Yep you are correct, close this, I'm just apparently blind >.<
