### ISSUE TITLE
[Server Request] Mordhau

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2113]
**What game server Would you like adding?**
Mordhau

**Can you link to any tutorials or guides?**
Unreal 4 Engine Game

**Is the server on Steam?**
629800

**Is the server supported on Linux?**
Yes

**Comment by dgibbs64** [comment]
Server is not yet released will need to go on hold until then

**Comment by h3o66** [comment]
Here is a gude from the offical website:
https://mordhau.com/forum/topic/10348/dedicated-server-hosting-guide-linux/

It seems that you need to own the game to host it.

**Comment by Atomzwieback** [comment]
Any updates on this?

**Comment by h3o66** [comment]
It seems like that the server is now available public without a login for the steamcmd.
I will have a look if i can create the scripts/configs for this one

**Comment by h3o66** [comment]
@Atomzwieback i created now the needed changes for the mordhau server

**Comment by h3o66** [comment]
More updates for Mordhau:
https://mordhau.com/forum/topic/15407/patch-04/

now i need to patch it again for the new port.

From the patchnotes:

> Joining a server will now reserve a slot in advance, fixing the issue of being booted after loading.
> Server owners will have to make sure that the beacon port (15000) is reachable; it can be overridden on the command line with BeaconPort=<port>
