### ISSUE TITLE
jq: Unknown option -sRr (during update-lgsm)

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#2124]
Both my LGSM servers update themselves automatically and I get cron email showing what happened during the updates. This morning, both showed output similar to this:

```
 [K[ .... ] Update LinuxGSM ut2k4server: Updating LinuxGSM
    checking config _default.cfg...UPDATE
    fetching _default.cfg...OK
jq: Unknown option -sRr
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
jq: Unknown option -sRr
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq
  [K[ .... ] Alert ut2k4server: Sending Discord alertparse error: Expected value before ',' at line 9, column 18
  [K[ FAIL ] Alert ut2k4server: Sending Discord alert: {"code": 50006, "message": "Cannot send an empty message"}
    checking linuxgsm.sh...UPDATE
    fetching linuxgsm.sh...OK
    checking ut2k4server...UPDATE
    backup ut2k4server...OK
```
The rest looks normal. I re-ran update-lgsm on both servers but everything looked fine and up to date. Both servers are running normally. So, whatever happened, it doesn't appear to have caused any lasting problems.

I appear to be running jr version 1.3 on the server, which is Ubuntu 14. The LGSM servers are UT2004 and UT99.

**Comment by h3o66** [comment]
https://stedolan.github.io/jq/manual/v1.3/

i would guess that this is caused by the fact that the old jq release does not support the parameters to be written "as one parameter"

But in my opinion i would say that ubuntu 14 is almost out of support, so does this need any attention ?

See:
https://www.ubuntu.com/about/release-cycle

Did you also consider to update to a newer ubuntu release ?

**Comment by h3o66** [comment]
to add:
this seems to be only a problem of the discord alert
lgsm/functions/alert_discord.sh

you could try to change "jq -sRr" to "jq -s -R -r" and try again if it works

**Comment by jrmain** [comment]
Actually, for whatever reason, this problem seemed to resolve itself at the next update. At least it's not currently happening.

As for upgrading to a newer Ubuntu release: assuming I had done that and it fixed the problem, you folks would need to review and update the requirements for LinuxGSM.

**Comment by dgibbs64** [comment]
Ubuntu 14.04 LTS is now out of support. I will not be making changes to resolve this.

**Comment by Redeye123** [comment]
> to add:
> this seems to be only a problem of the discord alert
> lgsm/functions/alert_discord.sh
> 
> you could try to change "jq -sRr" to "jq -s -R -r" and try again if it works

Im so thankfull to you since this just worked to solve it at my end on debian Again thx
