### ISSUE TITLE
Mailgun email alert.

### ISSUE THREAD

**Issue by uwejan** [GameServerManagers/LinuxGSM#2130]
**Basic info**
Game: CSGO
Distro: CENTOS7

Hey Guys, 
I modified the file `vi lgsm/config-lgsm/csgoserver/common.cfg` mailgunalert="on" and as the other fields, i run the test 
```
./csgoserver test-alert
[ WARN ] Alert csgoserver: More Info not enabled
[ WARN ] Alert csgoserver: Discord alerts not enabled
[ WARN ] Alert csgoserver: Email alerts not enabled
[ WARN ] Alert csgoserver: IFTTT alerts not enabled
[  OK  ] Alert csgoserver: Sending Email alert: Mailgun: email@example.com
[ WARN ] Alert csgoserver: Pushbullet alerts not enabled
[ WARN ] Alert csgoserver: Pushover alerts not enabled
[ WARN ] Alert csgoserver: Telegram Messages not enabled`
```
The problem as follow:
1. I do not see my email there, even though i modified the file with my gmail. 
2. I never received emails as result.

note: i disabled firewall while testing to ensure no conflicts.
Thank you.

**Comment by dgibbs64** [comment]
There is nothing to suggest what the issue is. I would guess that mailgun is not configured correctly somehow. I would send a test email via curl using your api key and see if works

```
curl -s --user 'api:key-3ax6xnjp29jd6fds4gc373sgvjxteol0' \
    https://api.mailgun.net/v3/samples.mailgun.org/messages \
    -F from='Excited User <excited@samples.mailgun.org>' \
    -F to='devs@mailgun.net' \
    -F subject='Hello' \
    -F text='Testing some Mailgun awesomeness!'
```

**Comment by uwejan** [comment]
Hey, CURL works, back to GSM, i still get same result here, is my configs,
`mailgunalert="on"
mailguntoken="key-MY_KEY"
mailgundomain="https://api.mailgun.net/v3/MY_DOMAIN/messages"
mailgunemailfrom="alert@myserver.com"
mailgunemail="MY_EMAIL@gmail.com"`

**Comment by uwejan** [comment]
Hey guys, i am still with same issue, anything could help?
