### ISSUE TITLE
[BUG] LGSM - Don't Update Server

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#2136]
**Basic info**
Game: **CS:GO**
Distro: **Ubuntu 16.04**

**Is your feature request related to a problem? Please describe.**
_I have this bug with update(s) only on ONE my server._
When Valve push update, and I use (with CronTab) **./csgoserver update**
Server don't update, because they sad **Already Latest Version**:

<details> 
  <summary>Screenshot</summary>
   <img src="https://user-images.githubusercontent.com/25010528/50374168-ded16480-05f2-11e9-9b88-43c44b0e9d67.png" />
</details>

BUT, server don't update already:
<details> 
  <summary>Screenshot</summary>
   <img src="https://user-images.githubusercontent.com/25010528/50374174-f01a7100-05f2-11e9-9574-fb9dfafc3b55.png" />
</details>

If I use Validate (./csgoserver v), server was successfully update:
<details> 
  <summary>Screenshot</summary>
   <img src="https://user-images.githubusercontent.com/25010528/50374237-ab430a00-05f3-11e9-9e37-481da88bf9e7.png" />
   <img src="https://user-images.githubusercontent.com/25010528/50374262-ed6c4b80-05f3-11e9-9f30-d6c168e2e751.png" />
   <img src="https://user-images.githubusercontent.com/25010528/50374264-02e17580-05f4-11e9-8063-b6c639003873.png" />
</details>

**Describe the solution you'd like**
Fix bug with **./csgoserver u**
or check reason why this bug work only ONE server and fix it (or something?)

PS: I can't add more info, I have bug with Post Details #2125
![image](https://user-images.githubusercontent.com/25010528/50374285-7d11fa00-05f4-11e9-87aa-8ffb7bffcc2e.png)

**Comment by Haxzer** [comment]
try running a ./csgoserver ul to update the linuxgsm functions, i had this problem a while back and this fixed it

**Comment by BlackYuzia** [comment]
@Haxzer I try do it. Don't help :c
![image](https://user-images.githubusercontent.com/25010528/54820661-a5b79780-4ca8-11e9-8f8c-f7621d9caf8c.png)
Ony on 4-th servers this problem have. (Maybe LGSM don't updated to latest version?)

https://hastebin.com/xolalanowu
https://hastebin.com/wepebisini
https://hastebin.com/asojesufat
https://hastebin.com/yajocilope

**Comment by BlackYuzia** [comment]
**Problem: Servers Don't Restart after update.**
If I restart it manualy - all is good.

**Comment by dgibbs64** [comment]
strange as the updater is designed to handle stopping the server if update available and bringing back online. I have just completed a refactor of the steamcmd updater. It might help

**Comment by dgibbs64** [comment]
There have been significant improvements to how the update command works with multiple instances so this should have been resolved in release v20.3.0
