### ISSUE TITLE
Insurgency Sandstorm Server Password Bug

### ISSUE THREAD

**Issue by heyjames** [GameServerManagers/LinuxGSM#2137]
### LinuxGSM bug

Regarding server config in this directory:
~/lgsm/config-lgsm/inssserver/

When copying the contents of **_default.cfg** to **common.cfg** and entering a password in `serverpassword="123456"`, the game that appears in the server browser is not password enabled.

The bug lies in the server start command section of the same file. According to their [official Google Doc Sandstorm Server Admin Guide](https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit), **password** is a Travel Parameter and not a Command Line Argument. Replace the preceding space+dash next to **password** with a question mark and the server password will be enabled when the server starts., but entering an empty password string into the variable makes the server passworded.

### Incorrect
`fn_parms(){
parms="${defaultmap}?Scenario=${defaultscenario}?MaxPlayers=${maxplayers}?Port=${port}?QueryPort=${queryport} -password=${serverpassword} -hostname='${servername}' -log"
}`

### Makes the server passworded regardless if the password variable is an empty string or not.
`
fn_parms(){
parms="${defaultmap}?Scenario=${defaultscenario}?MaxPlayers=${maxplayers}?Port=${port}?QueryPort=${queryport}?password=${serverpassword} -hostname='${servername}' -log"
}`

**Comment by NYPD** [comment]
Wanted to report the same thing. @heyjames hit the nail on the head with this issue.
