### ISSUE TITLE
Bug Lgsm does not have mods-update mods install commands my Rust servers get  this error DllNotFoundException: libsteam_api64.so and they will not start

### ISSUE THREAD

**Issue by firnen823** [GameServerManagers/LinuxGSM#2143]

**Comment by dgibbs64** [comment]
This issue does not provide enough info. Please update this issue

**Comment by deathparadenl** [comment]
I am having the exact same issue where the Rustserver instance freezes in Putty after failing to load the libsteam SO file which is there as if the rust_fix.sh isn't being used.
Except i can provide some logs.
[rust-server-game-2019-02-08-22_49_29.log](https://github.com/GameServerManagers/LinuxGSM/files/2847840/rust-server-game-2019-02-08-22_49_29.log)

If you wish for me to make my own issue report that's fine too.

**Comment by h3o66** [comment]
the issue is almost a year old, is here still a problem ?
