### ISSUE TITLE
Teamspeak3 Error 

### ISSUE THREAD

**Issue by ZigaZG** [GameServerManagers/LinuxGSM#2148]
So i installed server 2 days ago and it was working fine but i messed up something so i shutdown the server and tryed to install it again but i get this every time i try
```
[ts3server@vmi234087 ~]$ ./ts3server monitor
[ERROR ] Monitor ts3server: Checking session: Server seems to have died: FAIL
[ INFO ] Stopping ts3server: TeamSpeak 3 Server is already stopped
[  OK  ] Starting ts3server: TeamSpeak 3 Server
[ .... ] Monitor ts3server: Querying port: tcp: MY IP : /1: QUERY                 INGbash: connect: Connection refused
bash: /dev/tcp/207.180.208.30/10011: Connection refused
[ FAIL ] Monitor ts3server: Querying port: tcp: MY IP:10011 : 14/1: WAIT[ FAIL ] Monitor ts3server: Querying port: tcp: 207.180.208.30:10011 : 13/1: WAIT
[ .... ] Monitor ts3server: Querying port: tcp: MY IP:10011 : 15/2: QUERYINGbash: connect: Connection refused
bash: /dev/tcp/207.180.208.30/10011: Connection refused
[ .... ] Monitor ts3server: Querying port: tcp: MY IP:10011 : 30/3: QUERYINGbash: connect: Connection refused
bash: /dev/tcp/207.180.208.30/10011: Connection refused
[ .... ] Monitor ts3server: Querying port: tcp: MY IP:10011 : 45/4: QUERYINGbash: connect: Connection refused
bash: /dev/tcp/207.180.208.30/10011: Connection refused
[ .... ] Monitor ts3server: Querying port: tcp: MY IP : 60/5: QUERYINGbash: connect: Connection refused
bash: /dev/tcp/207.180.208.30/10011: Connection refused
[ FAIL ] Monitor ts3server: Querying port: tcp: MY IP : 74/5: WAIT[ts3server@vmi233/1: WAIT[ FAIL ] Monitor ts3server: Querying port: tcp: MY IP : 1
-bash: [: missing `]'
```

**Comment by dgibbs64** [comment]
it is unable to query the port 10011 which might not be the correct port. I would ensure everything is deleted in the directory and start again from scratch. If its still an issue might be something I need to look at

**Comment by ZigaZG** [comment]
> it is unable to query the port 10011 which might not be the correct port. I would ensure everything is deleted in the directory and start again from scratch. If its still an issue might be something I need to look at

I tryed like 5-6 times when i had my vps on Centos 7, now i reinstalled do Debain 9 and now works fine, but also when i 1st tryed installed on Centos 7 also worked but 2nd other times didnt work

**Comment by dgibbs64** [comment]
I tested this myself and unable to replicate. Placing on hold to close if no updates
