### ISSUE TITLE
my server does not show in cod4x

### ISSUE THREAD

**Issue by rimer10** [GameServerManagers/LinuxGSM#2152]
i create new cod4x server but its not listed  on cod4 master server  http://cod4master.cod4x.me/  please help me

**Comment by Ghost173** [comment]
new cod4x server need access tokens 

https://cod4x.me/index.php?/forums/topic/2814-new-requirement-for-cod4-x-servers-to-get-listed-on-masterserver/

read this doc

**Comment by dgibbs64** [comment]
Worth updating LimuxGSM docs.

**Comment by rimer10** [comment]
tank you i follow those steps but still not showing on master server

**Comment by Ghost173** [comment]
@rimer10  your in a wrong place you have to ask [here](https://cod4x.me/index.php?/forums/)
and its take some hours  lets wait and check :D

**Comment by rimer10** [comment]
thank you now its showing on master list

**Comment by rimer10** [comment]
thank you now its showing on master list
