### ISSUE TITLE
Attempt 9 download causes shell-init: error message

### ISSUE THREAD

**Issue by Bourne-ID** [GameServerManagers/LinuxGSM#2153]
## User Story

When the download of a standard game server fails for 9 times in a row, the error message 

> shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory 

Occurs which hides the original error of why the download was failing. 

## Basic info

* Distro \Ubuntu 1.04
* Game \CS GO (but should replicate for any) 

## Further Information

Seems to relate to install_server_files.sh#L79 as this is clearing the steamcmd and trying to re-extract. More debug is required to find the root cause

## To Reproduce

Steps to reproduce the behaviour:
1. use a disk with not enough free space (IE 15GB for CS GO, as this needs 19GB)
2. Attempt install of CS GO server
3. Watch the number of attempts increase as 0x202 error is produced (Not enough disk space) 
4. When it reaches attempt 9, the following will be outputted: 

>Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing 
[ERROR ] Install csgoserver: SteamCMD is missing
mkdir: created directory '/home/ubuntu/csgo/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/ubuntu/csgo/lgsm/functions/install_server_files.sh: line 102: ./steamcmd.sh: No such file or directory

## Expected behaviour

The steamcmd remove and replace to work successfully, and therefore not hide the original error message.

**Comment by Bourne-ID** [comment]
relates to #2139

**Comment by dgibbs64** [comment]
Good bug report thank you.

**Comment by dgibbs64** [comment]
LinxuGSM now has error checking for SteamCMD so this issue is now very unlikely to ever occur
