### ISSUE TITLE
No graceful shutdown for sdtdserver on blank telnet password.

### ISSUE THREAD

**Issue by jejanim** [GameServerManagers/LinuxGSM#2155]
Related to #696

When installing and running sdtdserver in shipped state, you cannot shutdown the server gracefully using telnet because a hardcoded default password is used when the server config has an empty telnet password (which is the case on a fresh install).

Changing the password to anything but an empty string fixes this.

**Comment by dgibbs64** [comment]
Issue will close in 30 days if no response. Assuming fixed

**Comment by jejanim** [comment]
Yep, fixed - thanks for the reminder.
