### ISSUE TITLE
[Alert] Allow to disable gametracker link

### ISSUE THREAD

**Issue by h3o66** [GameServerManagers/LinuxGSM#2163]
## User Story

Allow to disable the gametracker link in the notifications

## Basic info 

* Distro \[Debian 9]
* Game \[All Games]
* Feature \[Alert]

## Further Information

Currently in every notification there is a gametracker link implemented, i would like to disable it via a parameter or even replace it

## Further Reading

Example from current scripts:
https://github.com/GameServerManagers/LinuxGSM/blob/b0bc79bc4754cd9e92cfa9104d627dda74249c02/lgsm/functions/alert_discord.sh#L38
https://github.com/GameServerManagers/LinuxGSM/blob/b0bc79bc4754cd9e92cfa9104d627dda74249c02/lgsm/functions/alert_pushover.sh#L27
https://github.com/GameServerManagers/LinuxGSM/blob/b0bc79bc4754cd9e92cfa9104d627dda74249c02/lgsm/functions/alert_telegram.sh#L15

Update: mentioned all gametracker places

**Comment by dgibbs64** [comment]
Might be worth removing this functionality

**Comment by dgibbs64** [comment]
Gametracker has been removing in this pr https://github.com/GameServerManagers/LinuxGSM/pull/4345
