### ISSUE TITLE
Sven Coop now require glibc 2.24

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2165]
sven coop just released their 20th anniversary patch and now they re requiring 2.24 as minimum glibc version, so maybe its time to update documents accordingly 
https://steamcommunity.com/games/sven_co-op/announcements/detail/1689314410054294591
RIP to debian jessie, ubuntu 16.04 and of course, all centoses

**Comment by dgibbs64** [comment]
Not again. They did this before. I think this makes Sven have the highest Glibc requirements for any game server. I will update the details. Thank you

**Comment by dgibbs64** [comment]
Yes since Sven is Gold source Im not sure if this rise can be justified as even Ubuntu 16.04 is no longer supported
