### ISSUE TITLE
Monitor command fails on QuakeWorld

### ISSUE THREAD

**Issue by jesperbagge** [GameServerManagers/LinuxGSM#2169]
## User Story

When running a QuakeWorld server I am unable to use the Monitor command. It fails and restarts the server.

## Basic info

* Distro Ubuntu 18.04
* Game QuakeWorld
* Feature Monitor

## Further Information

Looking in the file **lgsm/functions/info_config.sh** I noticed that the variable `queryport` is missing for QuakeWorld.
Adding the line `queryport=${port}` resolves half the issue.

Furthermore, the python file **lgsm/functions/query_gsquery.py** has the wrong setup for this game.
QuakeWorld is based on quake1 and expects the UPD packet to contain the string
`'\xff\xff\xff\xffstatus\x00'`
But the engine for QuakeWorld is currently coded to the array `idtech3query`.
Moving the engine 'quake' to `idtech2query` is the second and last step needed to resolve the issue.

## To Reproduce

1. execute the command ./qwserver monitor

**Comment by dgibbs64** [comment]
plenty of info here and easy to fix. Thank you for raising
