### ISSUE TITLE
Teamspeak 3 server update from 3.6.0 to 3.6.1 fails without errors

### ISSUE THREAD

**Issue by kekkonenprkl** [GameServerManagers/LinuxGSM#2182]
## User Story

Teamspeak 3 server update from 3.6.0 to 3.6.1 somehow fails without errors.

## Basic info

* Distro \[Ubuntu 18.04]
* Game \[Teamspeak 3]
* Feature \[Update]

## Further Information

LinuxGSM Ts3 server update from v3.6.0 to v3.6.1 fails every time. Updater finds there is an update available and proceeds to download the right archive, but for some reason never replaces the files during update. Server stays in version 3.6.0 after the update is "succesfully" completed. No errors or anything given and server starts up normally after the process. LinuxGSM functions were up-to-date.

I'm not personally familiar how LinuxGSM works under the hood, so i don't have any clues how to solve the problem. After multiple days of failed updating, I updated my server manually by hand, to prevent update alert spam every night. v3.5.0 to v3.6.0 update went fine about two weeks ago, if that gives any hints about possible lgsm changes within past weeks.

## To Reproduce

Steps to reproduce the behaviour:
1. Have a server running Ts3 3.6.0
2. Update with ./ts3server update
3. LGSM finds and downloads the right update (3.6.1)
4. LGSM completes the update without any errors
5. Server starts back up, but the version remained 3.6.0

## Expected behaviour

Server files should be overwritten with the files from the downloaded archive

**Comment by xopez** [comment]
Can confirm it in some way.
I think something is done there. Maybe the archive itself is wrong.

The file `ts3server` from the the extracted archive has the same MD5 value as the one in the serverfiles.
The archive downloaded is `teamspeak3-server_linux_amd64-3.6.1.tar.bz2`. Timestamp and filesize is also the same.
/home/teamspeak/lgsm/tmp/teamspeak3-server_linux_amd64$ md5sum /home/teamspeak/lgsm/tmp/teamspeak3-server_linux_amd64/ts3server
8b741bac3e7be99e42b506a44ec56de6  /home/teamspeak/lgsm/tmp/teamspeak3-server_linux_amd64/ts3server
/home/teamspeak/lgsm/tmp/teamspeak3-server_linux_amd64$ md5sum /home/teamspeak/serverfiles/ts3server
8b741bac3e7be99e42b506a44ec56de6  /home/teamspeak/serverfiles/ts3server

I also deleted the archives in `lgsm/tmp/` and the extracted on there `teamspeak3-server_linux_amd64` with the same result. So i think the archive itself is wrong.

**Comment by gOOvER** [comment]
can also confirm. Update to 3.6.1 not possible

**Comment by dgibbs64** [comment]
can anyone confirm if they have `jq` installed?

**Comment by xopez** [comment]
On my machine it is installed.
```
~ # jq
jq - commandline JSON processor [version 1.5-1-a5b5cbe]
Usage: jq [options] <jq filter> [file...] 
```

**Comment by dgibbs64** [comment]
I am unable to replicate this issue myself but I have done some refactoring of `update_ts3server.sh` so that might help. It has been pushed in to develop branch

**Comment by xopez** [comment]
I will try it later

**Comment by ZigaZG** [comment]
Same here can't update on 3.6.1

**Comment by xopez** [comment]
I edited update_ts3server.sh from the develop branch. It's just the same. I leave you a screenshot here were you can see, that it's updating as the script says.
![grafik](https://user-images.githubusercontent.com/28950736/53285511-8c7f0200-3761-11e9-8a77-8545d2885914.png)
Version from Query:
![grafik](https://user-images.githubusercontent.com/28950736/53285553-ff887880-3761-11e9-8c03-e9cc20ad74c0.png)

**Comment by gOOvER** [comment]
can confirm with jq

`~# jq
jq - commandline JSON processor [version 1.5-1-a5b5cbe]`

**Comment by dgibbs64** [comment]
I may need to pop on one of your systems to take a look as I can't figure out the cause. Please let me know if one of you is happy to do this.

**Comment by xopez** [comment]
I made a copy of my TeamSpeak server where you can tinker without breaking anything. I also made a new DB so it's like a new Teamspeak.
I changed the ports so you can start it. But the version you also see the version with the update function.
The file `update_ts3.sh` is also the one from the develop branch. How should I give you the login information?

**Comment by dgibbs64** [comment]
@xopez drop me an email with the details me@danielgibbs.co.uk and I will take a look. Thanks

**Comment by xopez** [comment]
Done :)

**Comment by dgibbs64** [comment]
thanks. I made another alteration to develop branch that fixed the issue. So the next release should fix the issue

**Comment by xopez** [comment]
I have done it over my productive TeamSpeak. It works now.

**Comment by nero82** [comment]
Maybe same error with update from 3.6.1 to 3.7.0. Deleting all files and folders under lgsm/tmp/ solved the problem for me. I'm running TS3 on Ubuntu 18.04.

**Comment by kekkonenprkl** [comment]
I've been away from keyboard for a while, so haven't been able to take part in the conversation. But i can now confirm it works like expected. At the time of the bug, i took a snapshot of the server before i manually updated the files. So i was able to test it now with the old snapshot and 3.6.0 to 3.6.1 upgrade worked flawlessly. Also my productive server upgraded fine from 3.6.1 to 3.7.0 last night.

**Comment by xopez** [comment]
Can confirm. Updated without any problems to 3.7.0
