### ISSUE TITLE
displayid doesn't exist

### ISSUE THREAD

**Issue by bushtarikgg** [GameServerManagers/LinuxGSM#2192]
## User Story

I would like to be able to use displayip for my discord alerts but it doesn't exist in the code.
https://github.com/search?q=org%3AGameServerManagers+displayip&type=Code

## Expected behaviour

I should be able to choose which IP is displayed on a discord alert or just use the IP I'm binding to. It would be better to display no IP rather than show the wrong IP.

Thanks

**Comment by bushtarikgg** [comment]
https://i.imgur.com/QBJMDvT.png the problem visualized.

**Comment by busheezy** [comment]
@dgibbs64 is this a removed feature or is it yet to be implemented?

**Comment by dgibbs64** [comment]
Discord should use displayip as default i think. This will need to be investigated

**Comment by busheezy** [comment]
Thanks

**Comment by dgibbs64** [comment]
@bushtarikgg im guessing the IP in the screenshot is the external IP? What do you want to change it too and why? Just so I can get a better idea of use cases for displayip. Thanks

**Comment by busheezy** [comment]
Have you noticed how it's showing the same IP for every server on the same machine? Ideally, I would be able to specify things like "kz.tarik.gg" or "dm2.tarik.gg" as this would benefit us the most. I haven't updated my LGSM on all of these instances in months so it might be fixed.

**Comment by busheezy** [comment]
Thanks!
