### ISSUE TITLE
FastDL calculating files

### ISSUE THREAD

**Issue by CrazyHackGUT** [GameServerManagers/LinuxGSM#2195]
## User story
When i try create fastdl with `./tf2server fastdl` command, i got incorrect (?) output.
![default](https://user-images.githubusercontent.com/12576822/52905553-41428c00-3255-11e9-9a6a-ea524e3976fa.png)

## Basic info

* Distro: Ubuntu 18.04
* Game: Team Fortress 2
* Feature: FastDL

## Further Information
Add a line break?

## To Reproduce
Steps to reproduce the behaviour:
1. Install TF2server.
2. Try create fastdl without custom textures/sounds
3. See incrorrect output.

## Expected behaviour
Line breaks when file count - 0.

**Comment by Scarsz** [comment]
Looks like there just needs to be an else condition for [this](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_fastdl.sh#L198-L200)

**Comment by h3o66** [comment]
Added pull request to fix this, if you have time can you check this ?

**Comment by CrazyHackGUT** [comment]
I check in the evening (now in job). Sorry for late response, i didn't receive notification from GitHub.
