### ISSUE TITLE
Start Parameters in instance config

### ISSUE THREAD

**Issue by mgjuhler** [GameServerManagers/LinuxGSM#2199]
I think I might have found a bug.

I run several servers during the same installation and it works just fine.
I run with a config per instance and I am trying to set the start parameters different on each instance.
(some servers run with tickrate 128 and without bots) it is not a problem as long as I insert start parameters into the common.cfg file, but when I do so in instance config it does not work. All other settings that are in instance config are added just fine, the only thing that does not work is the start parameters.

https://pastebin.com/YxS1HAY3

Game: Counter-Strike Source

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04

**Comment by dgibbs64** [comment]
Just to clarify.

If you change start parameters in common.cfg it works but for instance.cfg it does not?

**Comment by mgjuhler** [comment]
> Just to clarify.
> 
> If you change start parameters in common.cfg it works but for instance.cfg it does not?

Correct, if i set the start parameters in common.cfg it all works, if i try to set the start parameters in the instance cfg and not in the common.cfg i does not work

**Comment by h3o66** [comment]
Not sure if this is still the case ?
The command system was reworked with the latest release.

**Comment by dgibbs64** [comment]
I will close this as it may be fixed in a recent release. However if still an issue please re-raise. Thank you
