### ISSUE TITLE
End support for older distros

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2203]
## User Story

As a developer, I want review older distros and remove them from the supported list.

## Further Information

Official unsupported distros are to be removed from support and no longer part of the minimum recommended on the LinuxGSM website.

Examples of minimum supported
Ubuntu 16.04
CentOS 7
Debian 9 (Debian 8 out of support in june)

**Comment by dgibbs64** [comment]
Modifications to the website have been made

**Comment by dgibbs64** [comment]
Need to remove Debian 8

**Comment by Frisasky** [comment]
debian 8 suppoer ends in next year, so maybe we can waiting a bit longer? especially for openvz users, because they cant install any OS higher than debian 8/ubuntu 16.04?
https://wiki.debian.org/LTS/

**Comment by dgibbs64** [comment]
A refresh of the distro info has been completed. CentOS 8 is pending release and will be updated when released. Older distros that are out of support have been removed now

**Comment by dgibbs64** [comment]
@Frisasky thanks for your help in tidying the docs!
