### ISSUE TITLE
kfserver: missing dir vars

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2218]
## User Story

kfserver is missing some directory vars

## Basic info

* Game: Killling Floor

## Further Information

gamelogdate
serverfiles

are missing

**Comment by SmOkEnksp** [comment]
on KF2 
Config file:            /home/kf2/serverfiles/KFGame/Config/kf2server/LinuxServer-KFGame.ini (FILE MISSING)
and some errors
> Game       INBOUND    UNAVAILABLE  tcp       Port=UNAVAILABLE
> Query      INBOUND    UNAVAILABLE  udp
-QueryPort=UNAVAILABLE"

**Comment by dgibbs64** [comment]
@SmOkEnksp that is a different issue for a different game server. Please raise an different issue
