### ISSUE TITLE
[Natural Selection 2] Dependencies Problem GLIBC

### ISSUE THREAD

**Issue by Archivis** [GameServerManagers/LinuxGSM#2222]
Having an issue running ./ns2server start.  I ran the dependency installer for Centos 7 as well.  Any thoughts?

[  OK  ] Debug ns2server: Starting debug
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./server_linux)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./server_linux)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/ns2server/serverfiles/x64/libSpark_Core.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ns2server/serverfiles/x64/libSpark_Core.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/ns2server/serverfiles/x64/libSpark_Core.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ns2server/serverfiles/x64/libSpark_Core.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ns2server/serverfiles/x64/libSpark_Physics.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/ns2server/serverfiles/x64/libSpark_Network.so)
./server_linux: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ns2server/serverfiles/x64/libSpark_Network.so)
[  OK  ] Debug ns2server: Stopping debug

**Comment by Laaas** [comment]
I think it's because glibc on CentOS is 2.17, while the version required by NS2 is probably higher, considering that 2.17 is from 2012.

**Comment by Archivis** [comment]
You're probably right.  I think 2.17 is default for CentOS 7 though.

**Comment by dgibbs64** [comment]
First run this command
`./ns2server develop`

then 
`./ns2server detect-glibc`

please provide the output. This will detect if Glibc requirement has be updated

**Comment by Frisasky** [comment]
All required GLIBC versions
GLIBC_2.17
GLIBC_2.16
GLIBC_2.15
GLIBC_2.14
GLIBC_2.12
GLIBC_2.11
GLIBC_2.8
GLIBC_2.7
GLIBC_2.4
GLIBC_2.3.4
GLIBC_2.3.3
GLIBC_2.3.2
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.2.4
GLIBC_2.2.3
GLIBC_2.2
GLIBC_2.1.3
GLIBC_2.1
GLIBC_2.0
GLIBCXX_3.4.21
GLIBCXX_3.4.20
GLIBCXX_3.4.15
GLIBCXX_3.4.14
GLIBCXX_3.4.11
GLIBCXX_3.4.10
GLIBCXX_3.4.9
GLIBCXX_3.4.5
GLIBCXX_3.4

Final glibc Requirement
=================================
GLIBC_2.17


apparently libstdc++ is outdated, centos 7 ships gcc 4.8 which libstdc++ version is 6.0.19, the game requires 6.0.21

**Comment by dgibbs64** [comment]
It may be possible to insert libstdc++ alongside the binary file. That sometimes works
