### ISSUE TITLE
Rust Server does not save on stop.

### ISSUE THREAD

**Issue by RussianRonin** [GameServerManagers/LinuxGSM#2226]
## User Story
When you stop rust, it will stop but it will not save. The way to get it to save it to throw it a quit command over rcon.

## Basic info

https://pastebin.com/rtbY3rnJ < hastebin is having issues so postdetails doesn't seem to work right now.

## To Reproduce

Steps to reproduce the behaviour:
1. Install Rust
2. Start rust, wait for initial generation, etc...
3. Stop rust, it will stop but it will not save the current state of the world.

## Expected behaviour

It should stop and create a sav file of the map.

**Comment by P4R4NORM4L** [comment]
This will never work because rust does not accept commands through tmux unfortunately.

**Comment by dgibbs64** [comment]
possibly related to #2580

**Comment by dgibbs64** [comment]
when the next release comes out please can you confirm this is still and issue and ether close this or let me know its still and issues. thanks
