### ISSUE TITLE
Where to add 

### ISSUE THREAD

**Issue by Dragos123456** [GameServerManagers/LinuxGSM#2230]
![image](https://user-images.githubusercontent.com/45486010/54308586-883d4c00-458b-11e9-97a0-7cb090175478.png)
 how or where to add
/home/cs16/serverfiles/cstrike/addons

**Comment by Lebawurscht** [comment]
Seems like you have a problem with the ownership of some files or directories.
This might help you:
https://docs.linuxgsm.com/linux/file-ownership#user-and-group-ownership
