### ISSUE TITLE
FastDL link broken

### ISSUE THREAD

**Issue by Gunni** [GameServerManagers/LinuxGSM#2234]
When I run: `./csgoserver fastdl` it tells me to find more info at: https://git.io/vyk9a

That link redirects to https://github.com/GameServerManagers/LinuxGSM/wiki/FastDL

That page does not exist.

**Comment by kennyLtv** [comment]
Docs got moved here is the correct link https://docs.linuxgsm.com/commands/fastdl

**Comment by Gunni** [comment]
That's nice to know, but the code still contains the wrong link and needs to be fixed.
