### ISSUE TITLE
[Feature] Support JSON + WebHook / Websocket alert

### ISSUE THREAD

**Issue by iamrekas** [GameServerManagers/LinuxGSM#2235]
### Hello,

I don't know is any request/feature posted already about this, but i think it's very good idea as in subject typed JSON support for response of script and maybe WebHook / WebSocket for alerts like server restarted and etc..

Sorry for my poor English, but i very expect you will think too like me what's good idea. :)

> If i was friendly and helpful please follow me. :)

**Comment by iainjreid** [comment]
@dgibbs64 could I lend a hand to this feature? It's something that I'm really keen on.

Loving this library by the way. Incredible work!

**Comment by iamrekas** [comment]
I look the code, figure out fastes way to make it. in all script using "echo -e" for print the information and once line for update state of running command. so these logic just need to code out to function and so if env is set to print response as json it will just ignore these output and other function at end of command must be printing json only with env format as json.

i hope type my idea correct.

**Comment by h3o66** [comment]
What json format would you propose for a alert like this ?
What this is also meant as well a usual http(s) endpoint is used for this ?

If someone is still interested in this, I could help out.
Would be nice if someone could contact me via Discord if possible. ( name: extreme1st#7327 )

**Comment by dgibbs64** [comment]
I am very unclear about what this would achieve. I am closing this for now
