### ISSUE TITLE
BSSERVER

### ISSUE THREAD

**Issue by testingbss** [GameServerManagers/LinuxGSM#2236]
Installed LinuxGSM/BSSERVER on my Ubuntu Box for testing. Blade Symphony has had a few updates and changed their directories around. Had to change executabledir="${serverfiles}" to executabledir="${serverfiles}/bin"

The second issue is that the srcds_run.sh does not like the directory name serverfiles and will not detect GameInfo. Renaming serverfiles to Serverfiles fixes this. Alternatively, creating a new directory inside serverfiles called Serverfiles, moving everything over, changing the directory names, etc, allows LinuxGSM to run. Could probably edit srcds_run.sh as well instead of the above.

**Comment by Frisasky** [comment]
did a quick test, i can confirm the problem indeed exist
![bss1](https://user-images.githubusercontent.com/26865851/55329316-e1303e00-54c0-11e9-8142-855b4f97dd5d.PNG)
