### ISSUE TITLE
TeamSpeak 3 Update/Install problem

### ISSUE THREAD

**Issue by Ammar7347** [GameServerManagers/LinuxGSM#2240]
* Distro: [Ubuntu 18.04]
* Game: [TeamSpeak 3]
* Command: [Update/Install]

I want to install the latest TeamSpeak 3 update which is 3.7.0 amd64 as currently, I have 3.6.1 amd64 installed. The LinuxGSM is up-to-date and all files are OK when I do ./ts3server ul. The problem is that when I try to do ./ts3server u it says it successfully updated the server but actually it never does and running the command again doesn't help either.

I tried ./ts3server install option which should install the latest version of ts3 in the directory but unfortunately, the version remains the same. I've made a gif which shows this problem: https://ammar.ovh/img/1553406416.gif

**Comment by Ammar7347** [comment]
Had to delete all the server files as well as linuxgsm and reinstall them again.

**Comment by Ammar7347** [comment]
Had to open this issue again because the problem still persists even after a clean install of the OS. Whenever a new TS updates come, the aforementioned problem starts to happen and it never actually updates the server

**Comment by dgibbs64** [comment]
Thanks. I'm working on the update command currently so I will be testing this issue

**Comment by nero82** [comment]
Had the same problem, I guess. Even when updating from 3.6.1 to 3.7.0 I had a similar problem. There I could help myself by deleting all files in the lgsm/tmp folder. This time this workaround didn't work for me.

- Distro: [Ubuntu 18.04]
- Game: [TeamSpeak 3]
- Command: [Update/Install]

**Comment by Ammar7347** [comment]
@dgibbs64 Any ETA for the fix since I'm not the only one having this issue?

**Comment by nero82** [comment]
There seems to be a problem downloading the update. I emptied the lgsm/tmp folder. Then downloaded the update with wget http://dl.4players.de/ts/releases/3.7.1/teamspeak3-server_linux_amd64-3.7.1.tar.bz2 and unziped it. After that I used the update function. This worked for me.

**Comment by dgibbs64** [comment]
Fix is planned for this weekend

**Comment by dgibbs64** [comment]
I can see what the issue is. On the next release when an update is available the tmp dir will automatically be cleared
