### ISSUE TITLE
[Server Request] Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by Lebawurscht** [GameServerManagers/LinuxGSM#2243]
## What game server would you like adding?

Minecraft Bedrock Edition

## Can you link to any tutorials or guides?

Server files can be found here:
https://www.minecraft.net/en-us/download/server/bedrock/

## Is the server on Steam?

* [ ] Yes
* [X] No

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [X] Yes
* [ ] No

**Comment by dgibbs64** [comment]
Whats Bedrock Edition?

**Comment by Lebawurscht** [comment]
There are currently 2 Versions of Minecraft for PC. Java Edition and Bedrock Edition.
While Java Edition is PC only, Bedrock Edition also is for Console (Xbox and Switch) and Mobile (iOS and Android).

https://minecraft.gamepedia.com/Bedrock_Edition
https://minecraft.gamepedia.com/Java_Edition

**Comment by gOOvER** [comment]
@dgibbs64 Pocket Editon and Bedrock Server are 2 different Versions ;)
