### ISSUE TITLE
Failed to update Factorio server V0.17.23

### ISSUE THREAD

**Issue by rhodwulf** [GameServerManagers/LinuxGSM#2246]
When using the command "./fctrserver update" it sends me the following error:

"Applying update...
downloading factorio_headless_linux64-0.17.23.tar.xz...downloading factorio_headless_linux64-0.17.23.tar.xz...##O#-  #             #=O#-  #     #
curl: (22) The requested URL returned error: 404 Not Found
FAIL
https://factorio.com/get-download/latest/headless/linux64"

* Distro: [Ubuntu 18.04]
* Game: [Factorio]
* Command: [./fctrserver update]

The command used is "./fctrserver update"

**Comment by rhodwulf** [comment]
The problem is related to the "tmp" folder that is in "/ lgsm / tmp"
Since I had to delete the previous versions (since 0.16.52), which were still present in that folder. And after executing the command "./fctrserver update" it was updated without problems to the most recent current version (0.17.23).

**Comment by rhodwulf** [comment]
Thank you very much for solving the problem soon.

**Comment by dgibbs64** [comment]
No problem.
