### ISSUE TITLE
[BUG] Factorio update to other than stable/experimental releases

### ISSUE THREAD

**Issue by Haxzer** [GameServerManagers/LinuxGSM#2252]
## User Story

When I try to update the server with an experimental branch (in the fctrserver.cfg branch="0.17.21" not branch="experimental" because the experimental gets the version number 0.17.23) the server fails to update with error 404 [Imgur Image of the update failed](https://i.imgur.com/gplU0Jv.png). 

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Factorio]
* Command: [Update] with an experimental branch that is not the newest version

## Further Information

Doesn't get the correct url to download the server files. Which is "https://factorio.com/get-download/0.17.21/headless/linux64". Maybe get branch to edit the link (except if running stable or experimental) it tries to download the headless version from, as the only change in the link is .../**0.17.21**/... part

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'fctrserver.cfg'
2. Add/edit branch to '0.17.21 or something other than stable/experimental'
3. Do './fctrserver update'

## Expected behaviour

Not get 404 error :)

**Comment by Haxzer** [comment]
I found a workaround that lets me get a 0.17.21 version, which includes downloading the correct version directly from the link above, and pasting it over the already installed server.

**Comment by BogdanWDK** [comment]
Should be fixed with:
target: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/update_factorio.sh
Line: #156
-  fi
+ else
+       downloadbranch = "${branch}"
+ fi

Tested, working.
