### ISSUE TITLE
Metamod and AmxModX support

### ISSUE THREAD

**Issue by frisasky1** [GameServerManagers/LinuxGSM#2256]
Counterpart of metamod source and sourcemod in GoldSrc, it would be handy for many novice server admins

I would trying add both into mod support myself

Todos:
1. Metamod havent been updated for years, thus lacks support for newer mods. Gamedata outdated too, so im considering use recently updated fork metamod-p, needs to compile the latest commit from github repo. TBD
2. For unknown reason i cant get the latest released amxmodx via github api, so im planned to hardcode the download link as amxmodx releases very infrequently (years apart from each releases), thus should not a big problem. TBD
3. Not sure how much i can done eventually as im a novice in script : )

**Comment by tkrn** [comment]
Please assign to me. I have a feature branch I’m working on current for this request. Here is working branch of development

https://github.com/GameServerManagers/LinuxGSM/compare/master...tkrn:feature/amxmodx-hl1-classic?expand=1

**Comment by tkrn** [comment]
Pull request @ https://github.com/GameServerManagers/LinuxGSM/pull/3104 for the feature to the develop branch

**Comment by h3o66** [comment]
Done in Release 20.6.0
