### ISSUE TITLE
[MC] Sending STOP Fails

### ISSUE THREAD

**Issue by onStyle** [GameServerManagers/LinuxGSM#2259]
## Basic info

* Distro: [Ubuntu 16.04]
* Game: Minecraft
* Command: ./minecraft stop

## Further Information
After latest update, on fresh install "sending stop" takes 20-30 seconds and then fails:
[ERROR ] Stopping mcserver: Graceful: sending "stop": FAIL
[  OK  ] Stopping mcserver: A Minecraft Server

**Comment by dgibbs64** [comment]
this has been fixed
