### ISSUE TITLE
Teamspeak3 server installation issues with MariaDB

### ISSUE THREAD

**Issue by Vis25** [GameServerManagers/LinuxGSM#2260]
## User Story

If trying to install the TeamSpeak3 server, and use MariaDB as database installation will be successfully completed, but user will not be able to start the server using the MariaDB configured, because generated database connection configuration has syntax error due typo in the installation script, and user is not able to input database socket path in the installation process.

Installation process does not ask user for path to MariaDB socket, which makes the server unable to connect to the database ( at least in my system ), but teamspeak3 server will start successfully. If you fix the ts3db_mariadb.ini after installation and start your server, you will not be able to use the MariaDB.

Configuration file  ( ts3db_mariadb.ini ) generated by the installation process in [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) has issues because typo in the script and i think that user should be able to input the path to the MariaDB socket.

First echo is probably not intentional, and will get written in to the ts3db_mariadb.ini - line 35

```
{
        echo "updating config."
        echo "[config]"
        echo "host='${mariahostname}'"
        echo "port='${mariaport}'"
        echo "username='${mariausername}'"
        echo "password='${mariapassword}'"
        echo "database='${mariadbname}'"
        echo "socket="
} >> "${servercfgdir}/ts3db_mariadb.ini"

```

## Basic info

* Distro: [Centos 7]
* Game: [TeamSpeak3]
* Command: [install]

## Further Information

Issue n.1 typo in [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) - line 35 

Issue n.2 [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) script does not ask user for database socket path.

Issue n.3 [ install_ts3db.sh ](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) libmariadb.so.2 is not copied from serverfiles/redist/ -> serverfiles/ if the file is not found in serverfiles/, even the libmariadb.so.2 is always included in teamspeak3 server files under redist/.

## To Reproduce

Steps to reproduce the behaviour:
1. preconfigure your mariadb dabatase ( Create user and create database for ts3server ).
2. start installation ( `./ts3server install` )
3. Do you want to use MariaDB/MySQL instead of sqlite? (DB must be pre-configured) [y/N] y
4. Installation will fail because libmariadb.so.2 is not found in serverfiles/
5. `cp serverfiles/redist/libmariadb.so.2 serverfiles/`
6.  start installation ( `./ts3server install` )
7.  Do you want to use MariaDB/MySQL instead of sqlite? (DB must be pre-configured) [y/N] y
8.  Input your database connection information.

```
Configuring TeamSpeak 3 Server for MariaDB/MySQL
=================================
Enter MariaDB hostname: localhost
Enter MariaDB port: 3306
Enter MariaDB username: **********
Enter MariaDB password: **********************************
Enter MariaDB database name: TestDB
=================================
Information! Accepting TeamSpeak license:
 * /home/teamspeak3-server/temp/serverfiles/LICENSE

Getting privilege key
=================================
IMPORANT! Save these details for later.
Starting the TeamSpeak 3 server
TeamSpeak 3 server started, for details please view the log file

------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
               Server Query Admin Account created
         loginname= "serveradmin", password= "**********"
------------------------------------------------------------------


------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
      ServerAdmin privilege key created, please use it to gain
      serveradmin rights for your virtualserver. please
      also check the doc/privilegekey_guide.txt for details.

       token=*******************************************
------------------------------------------------------------------

Stopping the TeamSpeak 3 server.done
    fetching fix.sh...OK

Applying Post-Install Fixes
=================================
Information! No fixes required.
    fetching install_complete.sh...OK
=================================
Install Complete!

To start server type:
./ts3server start

    fetching core_exit.sh...OK

```
9.  ts3db_mariadb.ini will be generated and looks like this ->
```
updating config.
[config]
host='localhost'
port='3306'
username='************************'
password='************************'
database='TestDB'
socket=
```

10. TeamSpeak3 server will be started and connection to the MariaDB fails due incorrect syntax or because socket incorrectly defined, anyways connection fails, and ts3 server fallbacks to the sqlite database and creates one.

11.  Fix the ts3db_mariadb.ini and add your path to the socket.
```
[config]
host='localhost'
port='3306'
username='ts3server'
password='9?3tWSbKkWjt&Y5mX49E%a=5B?e+'
database='teamspeak3'
socket='/var/lib/mysql/mysql.sock'
```

12. start the server once again `./ts3server start` ( Server starts and is now using the MariaDB database correctly. )

## Expected behaviour

User should be able to input the path to the database socket in installation process, so server would work right after installation process with need to find the database connection configuration file and fixing it.

Typo in [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) line - 35 should be fixed so that user does not have to find it and fix it after the installation, and server would function as expected right from the start.

Installation script should try to cp the libmariadb.so.2 file from redist/ and place it in to the correct place if user is trying to configure the ts3 server to use MariaDB while installing.
This can be annoying for the new users, and requires the user to do some googleing to find out what to do.

I have already made required fixes to the [install_ts3db.sh](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_ts3db.sh) and the changes have been pushed to my fork https://github.com/Vis25/LinuxGSM

I will be creating pull request to fix this issue.

Best regards,
visdmin
06.04.2019

**Comment by Vis25** [comment]
This issue ( or issues ), are fixed by these changes in my fork.
https://github.com/Vis25/LinuxGSM/commit/8d0edf32fc6b9178a312dad87a10a96c3022ba08
https://github.com/Vis25/LinuxGSM/commit/99fba6cb296a1038f7353453e0aaf6c5508d9bff

Do you want to use MariaDB/MySQL instead of sqlite? (DB must be pre-configured) [y/N] y

Here is how the installation process looks like after these fixes.

```
checking if libmariadb2 is installed
=================================
        libmariadb.so.2 => not found
libmariadb2 not installed.
Trying to installing libmariadb2.
Done installing libmariadb2.
Retrying to continue.

Checking if libmariadb2 is installed
=================================
libmariadb2 installed.

Configuring TeamSpeak 3 Server for MariaDB/MySQL
=================================
Enter MariaDB hostname: localhost
Enter MariaDB port: 3306
Enter MariaDB username: ts3server
Enter MariaDB password: 9?3tWSbKkWjt&Y5mX49E%a=5B?e+
Enter MariaDB database name: TestDB
Enter MariaDB socket path:/var/lib/mysql/mysql.sock
Updating config.
=================================
```

Here is the generated ts3db_mariadb.ini

```
[config]
host='localhost'
port='3306'
username='ts3server'
password='9?3tWSbKkWjt&Y5mX49E%a=5B?e+'
database='TestDB'
socket='/var/lib/mysql/mysql.sock'
```

**Comment by dgibbs64** [comment]
The detail is amazing. Thank you for the effort!

**Comment by Vis25** [comment]
Hope we can get this resolved so someone's life will be easier in future !

Great to hear that my research, and reporting was well done ( First time working with GitHub project ).
