### ISSUE TITLE
Eco server Network file missing

### ISSUE THREAD

**Issue by jonathanbak1** [GameServerManagers/LinuxGSM#2271]
When installing the Eco server on Ubuntu 18.10 everything seems to install correctly. But when trying to run the server it is missing a network.eco file. I''ve tried validating twice and that does nothing. 

## Basic info

Ubunto 18.10
Game: ECO

Network file just does not show.

Steps to reproduce the behaviour:
1. Install eco on your server per these instructions https://linuxgsm.com/lgsm/ecoserver/
2. Run the server and it should show that Network.eco does not exist

Here is the hastebin:  https://hastebin.com/sizayacipe

**Comment by dgibbs64** [comment]
This seems like an issue with Eco itself rather than LinuxGSM.

**Comment by LKLAW** [comment]
Same issue

**Comment by dgibbs64** [comment]
Looking at the server files for Eco network.eco does not exist any more. The config details will need to be updated.
https://steamdb.info/depot/739591/

![image](https://user-images.githubusercontent.com/4478206/59297912-481c6100-8c81-11e9-8973-71321378c1af.png)
