### ISSUE TITLE
Warning about EOL distros

### ISSUE THREAD

**Issue by frisasky1** [GameServerManagers/LinuxGSM#2294]
Some users may running OS that no longer supported or near EOL, like Ubuntu 18.10 ( non-lts ubuntu, supports end with 19.04 release) , Ubuntu 14.04 (support ends this month). Thats would enabling user choose an dist/version more secure and supports lgsm better
1. For dist less than 6 month before EOL message should warning user about EOL policy of dist and recommend about upgrading to newer dist
2. For new installation on EOLed dist, installation script should prevent installation the game server and provides recommend about choosing newer version of dist
3. For existing installation on EOLed dist, the script should warning about the dangerous of running unsupported dist and make recommends
4. For centos, due to slow pace of new release, only Centos 7 are recommend for new installation, warning should displayed for new/existing centos 6 installation 
link issue #2203

**Comment by dgibbs64** [comment]
Managed to do this for Ubuntu and debian that has distro-info command. Wasnt able to do this for RHEL based systems. But I will take that as a win. If there is a way to automate this for RHEL then we could add it in the future
