### ISSUE TITLE
[Website] libstdc++6:i386 current prereq on website 

### ISSUE THREAD

**Issue by unixbird** [GameServerManagers/LinuxGSM#2295]
As it currently stands on the website it will tell you to install libstdc++6:i386 for most of the 64bit lgsm servers for example:

(https://linuxgsm.com/lgsm/sdtdserver/)

If you were to just copy and paste that into a terminal for an easy solution it may error out with 

```
E: Unable to locate package libstdc++6:i386
E: Couldn't find any package by regex 'libstdc++6'
```

Which was confusing to me at first

The solution is as follows:

```
sudo dpkg --add-architecture i386
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install lib32gcc1 lib32stdc++6 libcurl4-gnutls-dev:i386

```
This allows you to install libstdc++6:i386 without error afterwards. I have also tested this on my Arma 3 server which complained about not having it even though it ran fine without it. This was experienced on Debian 9 64bit on the 7 Days to Die server but could be a problem on any server that requires libstdc++6:i386. If you already ran the recommended command on the site you may only have to enter:

`sudo apt-get install lib32gcc1 lib32stdc++6 libcurl4-gnutls-dev:i386`

**Comment by dgibbs64** [comment]
This is the current command on the site.

```
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386 telnet expect
```

The only difference I see is that you have added `libcurl4-gnutls-dev:i386` as a requirement. Apart from that the command is the same.

Are you stating that `libcurl4-gnutls-dev:i386` is a required dependecy for 7 Days to Die?

**Comment by unixbird** [comment]
I will need to retest, I recently set up another server which was on Ubuntu and that worked out perfectly without any hassle. The problem I was facing was on a Debian instance and that was the solution for that. Will retest and see
