### ISSUE TITLE
linuxgsm doc not found 

### ISSUE THREAD

**Issue by Ghost173** [GameServerManagers/LinuxGSM#2305]
[https://docs.linuxgsm.com/ ](https://docs.linuxgsm.com/ )cant reach this link any one can you share new link?

![screenshots](https://user-images.githubusercontent.com/30997116/56788031-f4160400-681b-11e9-8a20-d0d13a2247b7.png)

**Comment by rimer10** [comment]
same issue for me i think my browser problem

**Comment by Ghost173** [comment]
in SRILANKA most of the website block because of bomb attack sorry guys wrong issue
