### ISSUE TITLE
Monitor fails if query.port is different from server-port

### ISSUE THREAD

**Issue by kyleedwardsny** [GameServerManagers/LinuxGSM#2335]
## User Story

In Minecraft, `monitor` command fails when `query.port` is different from `server-port` in `server.properties`, because `monitor` connects to `server-port` on UDP, while the monitor socket is listening on `query.port`.

## Basic info

* Distro: [Ubuntu 16.04]
* Game: [Minecraft]
* Command: [Monitor]

## Further Information

This can be fixed by changing `query_gsquery.py` to connect to `query.port` instead of `server-port`.

## To Reproduce

Steps to reproduce the behaviour:
1. Set up a server
2. Set `query.port` different from `server-port`
3. Run `mcserver monitor`

## Expected behaviour

Monitor succeeds

## Actual behavior

Monitor thinks Minecraft has crashed and restarts it

**Comment by freaky-m0** [comment]
"command fails when query.port is different from server-port in server.properties"

It's the same problem when the ports are the same. Because there is no open UDP Port but the monitor query wants to check UDP as you mentioned. I have only an open TCP port on my installation.

**Comment by freaky-m0** [comment]
It's still the same problem. The script still fails because it looks for a UDP port which isn't there. 

./mcserver d gives:

```
Ports
=====================================================================================
Change ports by editing the parameters in:
/home/mcserver/serverfiles/server.properties

Useful port diagnostic command:
netstat -atunp | grep java

DESCRIPTION  DIRECTION  PORT   PROTOCOL
Game       INBOUND    25565  tcp
Query      INBOUND    25565  udp
Rcon       INBOUND    25575  tcp
```

But if I look with netstat it's just TCP:
```

root@gameserver:/home/user# sudo netstat -atunp | grep 25565
tcp6       0      0 11.22.33.44:25565       :::*                    LISTEN      16570/java
```

**Comment by freaky-m0** [comment]
Is it fixed?
