### ISSUE TITLE
Project Zomboid dependencies missing java

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2336]
## User Story

Project Zomboid is missing java dependencies but is present on the website

## Basic info

* Game: Project Zomboid
* Command: Install

**Comment by h3o66** [comment]
I dont think that the depenency is missing completely, but it is only there only for debian ( default-jre ).
https://github.com/GameServerManagers/LinuxGSM/blob/dc931a771866aca1c47d1787a39df072ba4b3845/lgsm/functions/check_deps.sh#L401
