### ISSUE TITLE
Minecraft-LAN-Server not found if ip in server.properties given

### ISSUE THREAD

**Issue by silelmot** [GameServerManagers/LinuxGSM#2351]
Hey there
i just had some trouble starting minecraft with lgsm in lan-mode (didnt test in online-mode).
when starting without ip in the server.properties lgsm tells me to set an ip and doesnt start.
when setting the lan-ip i cannot find the game in the ingame server list even after adding it correctly via ip:port.

i for now commented the part for check_ip.sh in check.sh out and deleted the ip in server.properties. this is working now.

since i am the first one mentioning this problem i believe it will be just an error for lan-games ("online-mode=false" in server.properties)

**Comment by DUDU54** [comment]
Hey,

can you give the output of lgsm.

**Comment by silelmot** [comment]
I don't know why but after i installed lgsm new it now works. Cant reproduce it anymore. So solved
