### ISSUE TITLE
Kern ERROR

### ISSUE THREAD

**Issue by klach1703** [GameServerManagers/LinuxGSM#2365]
## User Story

I encounter bugs in my server garry's mod, latency, rolback ... So I go to see my kern.log (/var/log/kern.log) of my dedicated server. And I noticed the same mistake several times. Here it is: May 26 19:56:32 srv01 kernel: [210968.758013] srcds_linux [22205]: segfault at 1f594d1 ip 00000000f7da51af sp 00000000ffdef40c error 4 in libc-2.27.so [f7d0c000 + 1d5000]

All errors here: https://pastebin.com/qDpWB5q6

## Basic info

* Distro: Ubuntu 18.04.02 LTS
* Game: Garry's Mod

## Further Information

I think that these errors are responsible for my latencies and bugs, so I would like to know if someone could help me? Thank you in advance.

**Comment by xopez** [comment]
This have nothing to do with the script itself.
You can report ist to gmod itself: https://wiki.garrysmod.com/page/Crash_Reporting
Or you can search for `segfault at 1f594d1`

I have the same Server Distro with Gmod and not a single problem.
