### ISSUE TITLE
Allow Minecraft server to start with no IP adress set in server.properties

### ISSUE THREAD

**Issue by guyman70718** [GameServerManagers/LinuxGSM#2368]
## User Story

Normally, when there is no IP address set in server.properties for Minecraft, it automatically binds to all available IP addresses, including localhost. Whenever I try and start the server without an IP in this config file, LinuxGSM refuses to start or stop the server normally, giving this error: 
`[ FAIL ] Starting mcserver: Check IP: IP address not set in game config.
Information! Specify the IP you want to bind within server.properties.
        * location: /home/mcserver/serverfiles/server.properties

Set server-ip to the following:
<IP REMOVED>

https://linuxgsm.com/network-interfaces
`
## Basic info

* Distro: [Ubuntu Server 18.04]
* Game: [Minecraft]
* Command: [start / stop / console]

## Further Information

I know that this could work, because there is currently a bug in the ./mcserver console command that allows you to start the server even with this file not including an IP. If you run this command, it will say that the server is not running and it will ask if you want to start it now. If you press Y, it gives the same error as above but the server starts normally. But, even when the server is running, since the config has no ip set, the ./mcserver stop command also gives the same error and wont stop the server.

## To Reproduce

Steps to reproduce the behaviour:
1. Remove the IP adress from server.properties in the /home/mcserver/serverfiles/ directory
2. Run ./mcserver start (Error shows and server doesn't start)
3. Run ./mcserver console and answer Y to all prompts (Error shows and server does start)
4. Run ./mcserver stop (Error shows and server doesn't stop even if its already running)

## Expected behaviour
All commands to work normally with no IP set.

**Comment by UltimateByte** [comment]
Hello,
It's been discussed here:
https://github.com/GameServerManagers/LinuxGSM/issues/1741

If you read it, you'll get more of the background. :)
