### ISSUE TITLE
Not support for processor aarch64.

### ISSUE THREAD

**Issue by Sonecav2** [GameServerManagers/LinuxGSM#2369]
Not support for aarch64 processor, pless built one make for this prosses!

**Comment by Frisasky** [comment]
very few games support arm natively, namely minecraft, quake 1/2/3, doom 1/2/3, terraria
so i dont think theres plan to put efforts to support arm arch

**Comment by Sonecav2** [comment]
This is the error:
"libstdc++6:i386
Warning! Missing dependencies: libstdc++6:i386

Warning! doiserver does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt update; sudo apt install libstdc++6:i386

Failure! Missing dependencies required to run SteamCMD."
but does not have it in the repository.

**Comment by Frisasky** [comment]
steamcmd is x86 only

**Comment by Sonecav2** [comment]
/steamcmd.sh
./steamcmd.sh: line 11: ulimit: open files: cannot modify limit: Operation not permitted
./steamcmd.sh: line 29: /home/doiserver/linux32/steamcmd: No such file or directory

**Comment by Sonecav2** [comment]
The ploblem is libstdc++6:i386, the version ARM already installed!

**Comment by dgibbs64** [comment]
LinuxGSM does NOT support ARM
