### ISSUE TITLE
LinuxGSM Minecraft errror [server thread/WARN]

### ISSUE THREAD

**Issue by Streeter220** [GameServerManagers/LinuxGSM#2371]
Hello, so recently i decided i wanted to make a Minecraft server on my Linux VM, and whenever i start the server up following the steps at LinuxGSM it throws me an error after a short while.

Error:
[Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2253ms or 45 ticks behind

Any ideas?

**Comment by DUDU54** [comment]
Hello, this error appear when there is not enough resources allocated to the server, like not enough ram or cpu not enough powerful

**Comment by dgibbs64** [comment]
Issue will close
