### ISSUE TITLE
(failed to dlopen /home/doiserver/serverfiles/stdshader_dbg_srv.so) (failed to dlopen /home/doiserver/serverfiles/bin/GAMEaddons/metamod/bin/server.so)

### ISSUE THREAD

**Issue by Gerald6494** [GameServerManagers/LinuxGSM#2372]
I need help, I just install Day Of Infamy on my server and when I start it I saw these errors in the console.log. Is looking for files with the wrong names and some are the wrong directory.

**game server:** Day Of Infamy

**Linux distro:** Ubuntu 18.04 x64

**kernel information:** Linux mae 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**glibc:** Ubuntu GLIBC 2.27-3ubuntu1

**tmux:** tmux 2.6

Output of console.log is attached
[doiserver-console.log](https://github.com/GameServerManagers/LinuxGSM/files/3247369/doiserver-console.log)

**Comment by dgibbs64** [comment]
I recommend removing the serverfiles directory and redownloading.
