### ISSUE TITLE
FreeBSD not supported

### ISSUE THREAD

**Issue by kyleedwardsny** [GameServerManagers/LinuxGSM#2377]
LinuxGSM does not work on FreeBSD out of the box. However, I have created a branch in which I did the minimum amount of porting to get it to run Minecraft on FreeBSD. I have opened this issue so I can link to it from the PR.

**Comment by dgibbs64** [comment]
There has been no update on this for around 9 months. I am unable to support FreeBSD myself. I will be closing this as I do not think it is feasible to add support at this time.
