### ISSUE TITLE
[Server Request] Pavlov VR Dedicated Server

### ISSUE THREAD

**Issue by DigitalFriends** [GameServerManagers/LinuxGSM#2382]
## What game server would you like adding?
Pavlov VR 
https://store.steampowered.com/app/555160/Pavlov_VR/

The game is built in Unreal Engine.

## Can you link to any tutorials or guides?

Setup guide:
http://wiki.pavlov-vr.com/index.php?title=Dedicated_server

## Is the server on Steam?

* [x] Yes
* [ ] No

[appid]

_Game_
**555160** | Game | **Pavlov VR** | 
[](https://steamdb.info/app/555160/)

_Server_
**622970** | Tool | **Pavlov VR Dedicated Server**
[](https://steamdb.info/app/622970/)

## Is the server supported on Linux?

Yes, server is supported on linux trough SteamCMD

* [x] Yes
* [ ] No

**Comment by h3o66** [comment]
If someone can test the server here linked the instructions:
https://github.com/GameServerManagers/LinuxGSM/pull/2384#issuecomment-721995789

**Comment by h3o66** [comment]
Done in Release 20.6.0
