### ISSUE TITLE
Hastebin and Pastebin aren't working

### ISSUE THREAD

**Issue by m33ts4k0z** [GameServerManagers/LinuxGSM#2383]
Hello,

Hastebin is working fine again but Pastebin isn't. Here is what happens when running a test alert:

```
[  OK  ] Postdetails rustserver: Posting details to pastbin.com for 7
  Please share the following url for support: http://pastebin.comhttps://pastebin.com/post.php
```

There must be some changes to pastebin lately.

**Comment by h3o66** [comment]
I think this is more a issue with hastbin itself because if i try to create a hastebin manually it also fails.

**Comment by dgibbs64** [comment]
Yup it looks like the save feature is no longer working. Are there any suggestions of alternatives? Might even be up for hosting somthing if required

**Comment by h3o66** [comment]
as well the pastebin does not work anymore.

If found termbin.com , but i am not sure if this works with a lot of text.

**Comment by kennyLtv** [comment]
HasteBin itself is Open Source, meaning it could be hosted. I believe that HasteBin.com is technically a demo and not meant to be "used". 

https://github.com/seejohnrun/haste-server

**Comment by m33ts4k0z** [comment]
Hastebin is working occasionally but pastebin needs a fix. When hastebin is available its working correctly however pastebin isn't working at all. By the time of typing this message, hastebin is working fine.

**Comment by no-boot-device** [comment]
Perhaps there could be something like https://paste.linuxgsm.com/?
