### ISSUE TITLE
Increase glibc version on ts3server

### ISSUE THREAD

**Issue by xopez** [GameServerManagers/LinuxGSM#2386]
## User Story

glibc needs to be updated to 2.17 or later since Server 3.8.0.
Increase glibc version on ts3server.
Latest Changelog: https://forum.teamspeak.com/threads/139966-Release-TeamSpeak-Server-3-8-0
Also mentioned here: https://github.com/GameServerManagers/LinuxGSM/pull/2385#issuecomment-500380061

## Basic info
* Distro: Ubuntu 18.04
* Game: TeamSpeak
* Command: install

**Comment by h3o66** [comment]
Added pull request to set the glibc version for the ts3 server

**Comment by h3o66** [comment]
fix was merged to the devel branch, so it will be in the next release

**Comment by dgibbs64** [comment]
Details updated on website
