### ISSUE TITLE
Battalion 1944 - Broadcast external IP instead of LAN IP

### ISSUE THREAD

**Issue by DavidRayner** [GameServerManagers/LinuxGSM#2397]
https://github.com/GameServerManagers/LinuxGSM/blob/4f44482317aeb4761aff3374780c19f2db9e4ab5/lgsm/config-default/config-lgsm/bt1944server/_default.cfg#L18

I think servers will not appear on the game's master server properly unless an external IP is used in the `-broadcastip` parameter.

**Comment by h3o66** [comment]
Also noted here in the wiki:
http://35.189.104.46/Community_Servers#Launching
