### ISSUE TITLE
Backup dir not the same for all configs

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2398]
## User Story

Some configs have 
```
backupdir="${lgsmdir}/backup"
```
While others have
```
backupdir="${rootdir}/backup"
```
all should be the first. refactor required to move backups if the dir changes.

## Basic info

* Command: Backup

**Comment by h3o66** [comment]
well a thing is also that some configs have also 
`backupdir="${rootdir}/backups"`
in the config with the additional s

Might be a problem for some users

**Comment by h3o66** [comment]
Made the refactor for all configs, see pr
