### ISSUE TITLE
Gentoo Doc Enhancement

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#241]
As there is no /etc/rc.local in Gentoo, i created a very very simple init script to start the service, @dgibbs64 you might want to add it in future documentations. 
- Create file l4d2server in /etc/init.d/
- Append to it:
# !/sbin/runscript

depend() {
  use dns
}

start() {
  ebegin "Starting L4D2 Server"
  su - l4d2server -c '/home/l4d2server/l4d2server start'
}

stop() {
  ebegin "Stopping L4D2 Server"
  su - l4d2server -c '/home/l4d2server/l4d2server stop'
}
- Chmod the script with "chmod u+rwx,g+rx,o+rx l4d2server"
- Add the service with "rc-update add l4d2server default"

And voila.

**Comment by dgibbs64** [comment]
I have added the documentation to the new wiki.
http://wiki.gameservermanagers.com/index.php?title=Gentoo
