### ISSUE TITLE
Battallion 1944 glibcxx requirement

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2410]
## User Story

Battalion 1944 now requires glibcxx 6.0.22, which shipping with gcc 6.1, since similar issue #2222 goes nowhere, id recommend we just remove debian 8/ ubuntu 16.04/ all centos from [website's](https://linuxgsm.com/lgsm/bt1944server/) recommended dists

## Further Information

[ INFO ] Debug bt1944server: Stopping any running servers
[ INFO ] Stopping bt1944server: LinuxGSM is already stopped
[  OK  ] Debug bt1944server: Starting debug
./BattalionServer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: versionCXXABI_1.3.9' not found (required by /home/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /home/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /home/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
[  OK  ] Debug bt1944server: Stopping debug

## Expected behaviour

N/A

**Comment by dgibbs64** [comment]
confirmed issue with CentOS 7
```
./BattalionServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/../../Plugins/GameLiftServerSDK/ThirdParty/GameLiftServerSDK/Linux/x86_64-unknown-linux-gnu/libaws-cpp-sdk-gamelift-server.so)
./BattalionServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/libCoherentUIGT.so)
./BattalionServer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lgsm/bt1944server/serverfiles/Linux/Battalion/Binaries/Linux/libCoherentGTCore.so)
```

**Comment by dgibbs64** [comment]
Updated distro requirements. Thank goodness CentOS 8 will be out soon.
