### ISSUE TITLE
Installing by server name is broken

### ISSUE THREAD

**Issue by Bourne-ID** [GameServerManagers/LinuxGSM#2415]
## User Story

The latest release has broken the functionality for installing a game server by game server name only (linuxgsm.sh csgoserver) - serverlist.csv is no longer downloaded and therefore the calling grep function fails as the file does not exist. 

## Basic info

* Distro: Ubuntu 16.04 (likely to affect all newly created servers)
* Game: all
* Command: initialisation (linuxgsm.sh [gameserver name])

## Further Information

A change to when the serverlist.csv file is downloaded means that when installing by game server name, the serverlist.csv file is no longer downloaded, which breaks the script. 

## To Reproduce

Create a new server/folder
Follow usual install commands giving the command as specified above

## Expected behaviour
To have the initial game server install file download.

**Comment by dgibbs64** [comment]
I have reverted the change. An oversight on my part. I will be resolving the issue correctly this evening

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/releases/tag/v19.8.4
https://github.com/GameServerManagers/LinuxGSM/releases/tag/v19.8.3
