### ISSUE TITLE
mtaserver autoinstall freezes with prompt

### ISSUE THREAD

**Issue by Bourne-ID** [GameServerManagers/LinuxGSM#2416]
## User Story

MTAserver prompts when attempting to autoinstall - prompts for "Do you want to install MTA default resources? [Y/n] Y"

## Basic info

* Distro: Ubuntu 16.04
* Game: mtaserver (Multi Theft Auto Server)
* Command: ai

## To Reproduce

From a fresh server / new user, attempt to install mtaserver using the command ai. The prompt for:
> Multi Theft Auto Default Resources
>
>Warning! Installing the default resources with existing resources may cause issues.
>Do you want to install MTA default resources? [Y/n] Y

This causes the script to freeze

## Expected behavior
For the script to complete without prompting when using ai

**Comment by dgibbs64** [comment]
try validating your install. There has been a change from x32 to x64
