### ISSUE TITLE
Rename the script for multiple server doesn't work

### ISSUE THREAD

**Issue by LAMASPANZER** [GameServerManagers/LinuxGSM#2417]
## Basic info

* Distro: [Debian 9]
* Game: [Garry's Mod/L4d2/ more ?]
* Command: [all]

## Further Information

Since 2years, I host 10+ gameservers on my debian servers (l4d2 and garry'smod).
I use LinuxGSM to manage them and they are configured [this way](https://docs.linuxgsm.com/features/multiple-game-servers#how-to-install-1) (1 user + multiple file "gmodserver" renamed. (ex: gmodserver-1 2 3..)

Globaly, run multiple servers with same user and different filename script, is broken since last release.

## To Reproduce

Just ./linuxgsm install gmodserver
- rename to gmodserver-1
- and check the name of gmodserver.cfg (not renamed) folder cfg/
- check console with ./gmodserver-2, it's the same console 1 2 3

**Comment by fluffyst** [comment]
I run my servers exactly the same and also am now having this issue!

**Comment by LAMASPANZER** [comment]
In in runner file
Replace servicename="${gameservername}" with servicename="${selfname}"

**Comment by superlazycoder** [comment]
What the heck ? Why did this Change ???

**Comment by superlazycoder** [comment]
PS: add `servicename="${selfname}"` to common.cfg

**Comment by dgibbs64** [comment]
This is now fixed https://github.com/GameServerManagers/LinuxGSM/releases/tag/v19.8.4
Something went very wrong with a few recent commits.
