### ISSUE TITLE
[Server Request] Out of Reach

### ISSUE THREAD

**Issue by sqveeze** [GameServerManagers/LinuxGSM#2420]
## What game server would you like adding?

Out of Reach

## Can you link to any tutorials or guides?

https://outofreach.gamepedia.com/Dedicated_Servers_Installation

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

406800

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [X] Yes
* [ ] No

**Comment by Frisasky** [comment]
is it possible to launch the linux server with sqlite (internal database) rather than PostgreSQL?

**Comment by Sqveeze** [comment]
Found nothing about it, looks like only PostgreSQL :( This will be a problem to implement a postgreSQL install into the script?

**Comment by dgibbs64** [comment]
Game appears to be dead. I will close this

![Image](https://github.com/GameServerManagers/LinuxGSM/assets/4478206/f13b48e8-e470-4e21-948c-3de4bc0815e9)
