### ISSUE TITLE
Glibcxx version of COD4

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2422]
## User Story

Another game needs to be glibcxx blacklisted, this time is COD4

Goodbye centos7 and debian 8

## Further Information

![unknown](https://user-images.githubusercontent.com/26865851/60395212-d427f700-9b62-11e9-8439-adf2434fa2c9.png)

## Expected behaviour

N/A

**Comment by dgibbs64** [comment]
Not another one!  XD

**Comment by dgibbs64** [comment]
Glibc requirement is also now 2.12. Please, can a PR be created to update the requirement? Thank you
