### ISSUE TITLE
[New Server] Atlas

### ISSUE THREAD

**Issue by TheOfficialSheep** [GameServerManagers/LinuxGSM#2432]
## What game server would you like adding?

ATLAS

## Can you link to any tutorials or guides?

No I can’t

## Is the server on Steam?

Yes

If yes Use SteamDB to get the appid. (https://steamdb.info).

100360

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

Yes

**Comment by h3o66** [comment]
duplicate 
Server was already requested here: #2158

**Comment by TheOfficialSheep** [comment]
Thanks! I'm sorry for this duplicate post!
