### ISSUE TITLE
[Issue] Can't start TeamSpeak3 server... it starts, then immediately stops.

### ISSUE THREAD

**Issue by MrAmos123** [GameServerManagers/LinuxGSM#2436]
## User Story

Install TeamSpeak3 using exactly the same commands provided here https://linuxgsm.com/lgsm/ts3server/

Start server.

## Basic info

* Distro: Ubuntu 18.04
* Game: TeamSpeak3
* Command: start/monitor

## Further Information

I can start the server under 'root' without _any_ issue, but moving back over to the `su - ts3server` and starting it looks like it starts correctly, but then running ./ts3server monitor says it seems to have failed and attempts to restart it... (loop)

Literally, if I log under root to `/home/ts3server/serverfiles` and run `./ts3server_startscript.sh start` it works without issue. 

It seems to be an issue either with `./ts3server` or the user environment?

Oh, and I tried the IPv6 Fix as suggested in the documents. 

## To Reproduce

Install ts3 server, start server.
In logs it says 

```
2019-07-10 16:43:10.870762|INFO    |VirtualServer |1  |listening on 149.202.86.115:9987
2019-07-10 16:43:10.976692|INFO    |VirtualServerBase|1  |stopped
```

## Expected behaviour

Server to start correctly and joinable.

**Comment by kennyLtv** [comment]
You should check your file ownership, I'm betting this isn't an issue with the script but that the user doesn't own the server files.

**Comment by MrAmos123** [comment]
@kennyLtv well unless the script downloads the files under the wrong user I don't believe it's related as I literally made a new user deleting the old one and ran the script again using vanilla files and it fails out of the box. 

https://i.imgur.com/t7bOvJt.png

**Comment by kennyLtv** [comment]
The fresh install I just tested comes online correctly https://imgur.com/a/MCpAS2h 

Can you post the results from the details command?

**Comment by MrAmos123** [comment]
https://pastebin.com/raw/T9vVQPqk

Hmm, I don't understand then. :(

Battalion 1944, Minecraft, CS:GO servers all work without any issue.

Just TeamSpeak 3 that is messing me around, and it's weird because using it's own files if I run them as root it works as expected. Though, I'd rather use LinuxGSM as intended.

**Comment by h3o66** [comment]
Well, did you already look in the teamspeak logs if there is any error in there ?
They are located in log/server/

**Comment by MrAmos123** [comment]
[TS3LogFiles.zip](https://github.com/GameServerManagers/LinuxGSM/files/3378880/TS3LogFiles.zip)
I don't see anything that would directly indicate something has gone wrong? :(

Maybe I'm just blind for the issue. 

Any idea?

**Comment by Frisasky** [comment]
just try install on debian 9 maybe?

**Comment by h3o66** [comment]
Can you check if this helps ?

https://forum.teamspeak.com/threads/93623-Instance-check-error-failed-to-register-local-accounting-service-on-Linux?p=465663#post465663

In this case there might be a file in /dev/shm/ that needs to be deleted 

Can you post a list of that dir with permissions?

**Comment by MrAmos123** [comment]
That worked! :)

```
root@eu:~# ls -al /dev/shm
total 4
drwxrwxrwt  2 root root   60 Jul 10 17:18 .
drwxr-xr-x 19 root root 3960 Jun 29 14:14 ..
-rw-r--r--  1 root root  128 Jul 10 17:18 7gbhujb54g8z9hu43jre8
```

I removed that file and it worked. Could be worth updating docs with this information?
