### ISSUE TITLE
[Website] OS sliders doesn't work anymore

### ISSUE THREAD

**Issue by PlayMTL** [GameServerManagers/LinuxGSM#2444]
The Slider of the dependecies for the OS on the gameserver installation page don't work anymore. Looks like its jquery related.

Example: https://linuxgsm.com/lgsm/gmodserver/#ubuntu
Browser: Firefox 68

**Comment by dgibbs64** [comment]
Should be fixed now. Updated jquery etc while I was at it :).

**Comment by dgibbs64** [comment]
web
