### ISSUE TITLE
Bug when installing rust linuxgsm

### ISSUE THREAD

**Issue by metalowcom** [GameServerManagers/LinuxGSM#2446]
When installing Rust this command given for dependencies installation:
yum install epel-release bzip2 jq tmux zlib-devel

and when installing it actually it can not install jq because it needs dependecy epel-release i think.

so I recommend split the command recommended to this:
yum install epel-release bzip2 jq tmux zlib-devel
yum install jq

Follow **[this guide](https://linuxgsm.com/support/#guide)** to make sure you post the correct info.
For general support visit the **[LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support)**.

Issues here are **ONLY** for:
* LinuxGSM bugs
* feature suggestions
* code contributions

Issues here are **NOT** for:
* General support
* Specific game server issues (e.g CS:GO, TF2)
* Dedicated server issues (e.g Ubuntu, CentOS)
* Anything not directly related to LinuxGSM development

Any general support issues on GitHub will be migrated to [LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support).

*Please use the template below*

## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Garry's Mod]
* Command: [Monitor]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:

**Comment by h3o66** [comment]
I guess you mean that this only apprears when you run the script ?

Because on the website it is noted, that you need to install epel-release before you intall the dependencys

See:
https://linuxgsm.com/lgsm/rustserver/#centos

btw: it would be nice if you clean up a bit your issue text
