### ISSUE TITLE
[GMOD] SRCDS Console Scroll Up

### ISSUE THREAD

**Issue by MyDimeIsUp** [GameServerManagers/LinuxGSM#2447]
## User Story
When attempting to scroll up using my SSH program (MobaXTerm) I can't see previous outputs by SRCDS. When scrolling up, all I see is previous outputs from my ubuntu session

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Garry's Mod]
* Command: [console]

## Further Information
![Image without scrolled up](https://i.imgur.com/eufr1ta.png)
![Image of Console scrolled up](https://i.imgur.com/Wj8IX4T.png)

## To Reproduce

Steps to reproduce the beha`viour:
1. /[servername] c
2. Attempt to scroll up using your SSH program

## Expected behaviour
To scroll up to previous console ouputs by SRCDS

**Comment by Bourne-ID** [comment]
Not a LinuxGSM issue - sounds like something that MobaXTerm is causing. I suggest [holding down shift when using a mouse wheel](https://superuser.com/a/1349250) or trying the [standard terminal keyboard shortcut commands](https://unix.stackexchange.com/a/60387) to see if that helps. 

Closing ticket as it's not related to LinuxGSM - feel free to come to our discord and ask for help with linux if more help is required.

**Comment by MyDimeIsUp** [comment]
I tried both putty and the MobaXTerrm and it didn't work. Same problem on putty and holding shift+scrolling up along with shift+pageup doesn't work (Not even scrolling)

**Comment by MyDimeIsUp** [comment]
@Bourne-ID

**Comment by MyDimeIsUp** [comment]
@Bourne-ID please reopen?

**Comment by dgibbs64** [comment]
As @Bourne-ID stated this is not an issue related to LinuxGSM. It is an issue with the terminal. No requirement to re-open this. As was stated there may be someone on the LinuxGSM discord that _might_ be able to help.

**Comment by MyDimeIsUp** [comment]
It is tho. I literally just tried in PuTTY and it still doesn't scroll. This is in issue with LinuxGSM. Don't know how else to state it

**Comment by MyDimeIsUp** [comment]
![image](https://user-images.githubusercontent.com/8619739/73623636-9d8bf080-460b-11ea-8f2f-fb73112775b0.png)
