### ISSUE TITLE
Barotrauma has a new server binary location

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2453]
## User Story

It seems Barotrauma have radically changed their linux binaries, now based on mono and im guessing lgsm Barotrauma support needs rework.

## Further Information

https://steamdb.info/depot/1026342/

"Launch_DedicatedServer" is gone, now replaced with exe file and mono

## Expected behaviour

N/A

**Comment by h3o66** [comment]
well acutually it seems that there is a 32 bit and a 64 bit binary for linux.

i found the following in the serverfiles:
`$ ls Server.bin.x*
Server.bin.x86  Server.bin.x86_64
`

**Comment by dgibbs64** [comment]
Yup. I adjusted the executables on the last update. Wasn't sure about the mono issue though.

**Comment by h3o66** [comment]
Well i had a look again at the Serverfiles.

in the changelog there was this mentioned (In Version v0.9.0.5):

> - Removed outdated Launch_BarotraumaServer script from the Linux version (does not work anymore, the dedicated server should be launched by running the file called "DedicatedServer").

But this script is not there in the Serverfiles.
But the file seems to be in the git of them:
https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaServer/DedicatedServer

**Comment by h3o66** [comment]
well one more info:
DedicatedServer.exe is actually a script for the server start.
Got that info on their discord.
