### ISSUE TITLE
[Server Request] OpenTTD 

### ISSUE THREAD

**Issue by DigitalFriends** [GameServerManagers/LinuxGSM#2454]
## What game server would you like adding?
OpenTTD 

This game is amazingly still in development and offers a wide variety of mods.
Would love to see support for this with LGSM.

https://www.openttd.org/

## Can you link to any tutorials or guides?

https://wiki.openttd.org/Dedicated_server
https://wiki.openttd.org/OpenTTD
https://wiki.openttd.org/Advanced_Settings
https://wiki.openttd.org/Openttd.cfg

## Is the server on Steam?

* [ ] Yes
* [x] No

## Is the server supported on Linux?

* [x] Yes
* [ ] No

**Comment by dgibbs64** [comment]
I am closing this currently as OpenTTD is not a good fit for LinuxGSM becuase of various problems with auto-updates, requiring a deb file and having a very high glibc required. Should these issues be resolved then we can review it again in the future.

**Comment by Makishima** [comment]
Is it the right time to review it since OpenTTD was released on Steam?

**Comment by tigresansrayure** [comment]
Hello there @dgibbs64,
I agree with @Makishima, since the game is now on Steam, with a better update management, maybe some of the issues you mentioned are resolved ?

**Comment by DigitalFriends** [comment]
The game is now avaliable on Steam, can you revise this again @dgibbs64 ?

Thank you again, let me know if you need any help testing on debian or bsd.
