### ISSUE TITLE
Why we not able update TeamSpeak server?

### ISSUE THREAD

**Issue by grenman11** [GameServerManagers/LinuxGSM#2455]
Problem is that my server is 3.8.0, new version of TS is 3.9.1, when im trying update, it show's me that. 

```
No update available:
        Current version: 3.8.0
        Available version: 3.8.0
```

Is this an bug or something?

* Distro: [Centos 7]

**Comment by h3o66** [comment]
Did you try to update lgsm as well ?
If not update it with the command `./ts3server ul`
And please also note that the glibc requirement is higher now for the TeamSpeak Server

**Comment by grenman11** [comment]
> Did you try to update lgsm as well ?
> If not update it with the command `./ts3server ul`

Yes mate, i completly forget about that, thank u, all updated.
