### ISSUE TITLE
TeamSpeak server down [Updates bug?]

### ISSUE THREAD

**Issue by Committing** [GameServerManagers/LinuxGSM#2457]
Any general support issues on GitHub will be migrated to [LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support).

## User Story

I logged in this morning and my TS3 server was down. I tried to restart the server but it wouldn't start again. It errored with "Failed loading default license file!"

![Image of err](https://i.gyazo.com/e4ab1100f23adda209c39e73984fe9ed.png)

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [TeamSpeak]
* Command: [Update]

## Further Information

I looked online and found this thread: https://forum.teamspeak.com/threads/137119-Server-error-quot-Failed-loading-default-license-file!-quot/

Which seemed to match the error. It was decided a few pages later that all you needed to do was update TeamSpeak to sort it.

I tried to update with `./ts3server update` but there were no updates to install through LinuxGSM. Are the TeamSpeak updates not being pulled across automatically anymore? Is there a problem there?

![](https://i.gyazo.com/f57568fa49cc00621c6ed4fec00d15e4.png)

My TeamSpeak server is still down as I don't know what to do to resolve this. My server has been mostly untouched for 2-3 years hosting this ts3 server.

## To Reproduce

I would be unable to reproduce, it simply happened when I logged in this morning. No changes have been made to the server for 2 years!

## Expected behaviour

For server to start.

**Comment by Committing** [comment]
Okay, I didn't realise there were two update functions. Needed to run:

`./ts3server update-lsgm` then `./ts3server update` and then `./ts3server start` and it's all working again.

**Comment by SwAtRaNgEr** [comment]
any ways to fix this

**Comment by Committing** [comment]
> any ways to fix this

Generally speaking the problem for me was my server being outdated. Make sure you're all up-to-date.

**Comment by h3o66** [comment]
if you do not own a licence of Teamspeak 3 server, you need to update it to the latest version.
Usally this appears in the log of the ts3 server:
`Error creating ephemeral license: EXPIRED`
