### ISSUE TITLE
gmodserver: Warning! Missing dependencies: lib32tinfo5

### ISSUE THREAD

**Issue by ehylla93** [GameServerManagers/LinuxGSM#2463]
As the topic says, that's the error. The server seems running smooth anyway.

* Distro: Debian 10 Buster
* Game: GMOD
* Command: Start / Stop (maybe more, just used these two)

It seems lib32tinfo5 (https://packages.debian.org/search?keywords=lib32tinfo5) is no more used in Buster, but libtinfo5 (https://packages.debian.org/search?keywords=libtinfo5) is.

**Comment by Frisasky** [comment]
maybe try install lib32tinfo6 and see how thing work?

**Comment by ehylla93** [comment]
Already did before posting here, same error.

**Comment by Frisasky** [comment]
try install it manually
wget http://http.us.debian.org/debian/pool/main/n/ncurses/lib32tinfo5_6.0+20161126-1+deb9u2_amd64.deb
dpkg -i lib32tinfo5_6.0+20161126-1+deb9u2_amd64.deb
