### ISSUE TITLE
Problems with setting up a modded Minecraft Server

### ISSUE THREAD

**Issue by GameTime007** [GameServerManagers/LinuxGSM#2464]
After much tinkering I could find the issue I'm having. Im not a total noob at this (have managed game servers for my friends for years -> Windows), but I'm totally out of ideas.

Im trying to set up a modded server based on the Resonant Rise Modpack. I installed a normal MCServer with LGSM and then replaced it's serverfiles with the RR Server files. After having done that and having pointed LGSM to the new filepath either the server starts with no issues, but completely without mods (eventhough I'm executing the forge-universal) (This happens when I replace the files wit a completely fresh set of RR Server). Or it spews out some weird Error codes (That happens when I already pre-ran the server on my normal PC):

A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException                                                                      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nativ
e Method)                                                                       
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native
MethodAccessorImpl.java:62)                                                     
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
legatingMethodAccessorImpl.java:43)                                             
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)           
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunc
hWrapper.java:70)                                                               
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaun
chWrapper.java:34)                                                              
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$
AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loa
der.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.b
ase of loader 'bootstrap')                                                      
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)            
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)              
        ... 6 more                                                              
[  OK  ] Debug mcserver: Stopping debug  

I know that this is some forge related issue, but the fix most poeple recommended (checking filenames) did not work. Is it even possible to launch the forge-universal.jar directly from Linux GSM? Or would it maybe be possible to call the provided "LaunchServer.sh" and start the server from there?

Any help and other tips would be greatly appreciated.

**Comment by h3o66** [comment]
the default command can be overwritten with `executable="./scriptname.sh"` in the common or server config file in lgsm.

Sometimes it is also the case that only a old java version needs to be used, what can cause the server crashing when the version is to new of java.

If this answers you question, please close the issue

**Comment by h3o66** [comment]
if you have further problems, please ask on discord for help
