### ISSUE TITLE
Unable to install Q3A on debian 9

### ISSUE THREAD

**Issue by PVasileff** [GameServerManagers/LinuxGSM#2469]
When I try to install q3 server I got an error:

> Installing Quake 3: Arena Server
> =================================
> ###############################                                           43.7%
> curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
> downloading quake3-1.32c-x86-full-linux.tar.bz2...OK
> verifying quake3-1.32c-x86-full-linux.tar.bz2 with MD5...FAIL
> quake3-1.32c-x86-full-linux.tar.bz2 returned MD5 checksum: a7589c9e560d66577c158bf7815fa7f8
> expected MD5 checksum: fd7258d827474f67663dda297bff4306

Using: Debian 9 x 64 KVM
Information! Required dependencies already installed

Please help.

**Comment by PVasileff** [comment]
I found the problem.
The file does not download correctly, because your site files.* was down.

**Comment by Frisasky** [comment]
it should be fixed now
