### ISSUE TITLE
Ubuntu Server 18.04 LTS Failure on dependencies "mailutils & jq" Pleas fix website.

### ISSUE THREAD

**Issue by lorentedford** [GameServerManagers/LinuxGSM#2472]
## User Story

As a user, I want clear information so that Prerequisite packages are installed correctly.

## Basic info

* Distro: [Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-54-generic x86_64)] <- Ubuntu Server Distro
* Game: [CSGO]
* Command: [Monitor]

## Further Information

[Packages fail to install from the information provided by your site.](https://linuxgsm.com/lgsm/csgoserver/)

To properly install these package dependencies you must install  this: sudo add-apt-repository universe

To my knowledge this is only on Ubuntu Server 18.04 LTS I don't know about the desktop version of Ubuntu.

The package dependencies that fail to install is: apt-get install mailutils jq

After running sudo add-apt-repository universe everything installed correctly.
## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'Ubuntu's Website https://ubuntu.com/'
2. Click on 'Download listed in the top right corner'
3. Scroll down to 'select Ubuntu Server 18.04 LTS'
4. Wait for 'automatic download'.
5. Install Ubuntu 18.04 LTS on 'Hardware in my case Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz'
6. Follow directions from 'LinuxGSM https://linuxgsm.com/lgsm/csgoserver/ '
7. In my specific case 'I ran this command to install my csgo server with linuxgsm:   ' sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386 '
8. In joy 'the failure! '

<3

## Expected behaviour
Proper installation of the packages required.

**Comment by dgibbs64** [comment]
Thanks. This was a bug in 18.04 and should have been fixed by Canonical
