### ISSUE TITLE
minecraft server high ping

### ISSUE THREAD

**Issue by blastexhdhun** [GameServerManagers/LinuxGSM#2478]
so i made a minecraft server (latest version) with lgsm, opened port etc.
i got 2ms on local ip but i have over 200ms with my public ip and idk why
on canyouseeme.org it says that is opened
what should i do?
i got the latest debian

**Comment by BrutalBirdie** [comment]
This is no issue for GitHub, but okay.
Where is your server located and where are you located? (OFC you have 1/2ms ping local)
I got my server hosted in Finland and I am sitting in Germany and I got a 37ms ping.

Do you use DNS to reach your server or just the IP?

**Comment by blastexhdhun** [comment]
Hey
My server is on my home network and I'm located in Hungary
But i already figured out the problem
And IP,Public IP :)
