### ISSUE TITLE
Teamspeak 3 not updating past 3.8.0

### ISSUE THREAD

**Issue by USSpectre1** [GameServerManagers/LinuxGSM#2483]
It appears that using the update command for a teamspeak server does not grab the latest server version. It shows that 3.8.0 is up to date, instead of seeing the update to 3.9.1.

**Comment by h3o66** [comment]
What version of lgsm do you use ?
Did you already try to update it ?
./ts3server lgsm-update
And then try again to update the TeamSpeak Server

**Comment by BrutalBirdie** [comment]
I can't confirm that behavior.
```bash
# Checking lgsm Version
LinuxGSM - TeamSpeak 3 - Version v19.9.0

#running ./ts3server upddate
[  OK  ] Update ts3server: Checking for update: teamspeak.com

No update available
* Local build: 3.9.1
* Remote build: 3.9.1

command_update.sh exiting with code: 0

# uname -a
Linux Nope-host 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
```
