### ISSUE TITLE
feat(postdetails): add postdetails support for https://termbin.com 

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2490]
## User Story

Add support for https://termbin.com in to post details

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Garry's Mod]
* Command: [Monitor]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:

**Comment by h3o66** [comment]
this was added with the pull request #2485
