### ISSUE TITLE
Remove Fedora as supported dist

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2495]
# User Story

Since almost no one using fedora to hosting their servers and the few innocent people trying it mostly find out it wont work due to dependencies/package problem, we dont have time/capability to maintain fedora support either. not mention it short support cycle isnt suitable for game server, so i'd recommend we just remove fedora support for good

## Basic info

* Distro: [Fedora]

## Further Information

N/A

## Further Reading

N/A

**Comment by dgibbs64** [comment]
I think I agree with you on this one. It would be a good idea to do a new distro survey to see what people are currently using and identify if any other distros may be required. I will look at updating my previous survey and releasing it again

**Comment by dgibbs64** [comment]
Fedora should have not been removed. Any further info remaining will be removed with the upcoming website update
