### ISSUE TITLE
Rust server won't start

### ISSUE THREAD

**Issue by Karrigallu** [GameServerManagers/LinuxGSM#2501]
Server wont start.
Seems like this is the issue:

**"Fallback handler could not load library xyz"**

`Command Line: "./RustDedicated" "-batchmode" "+server.ip" "62.210.180.56" "+server.port" "28015" "+server.tickrate" "30" "+server.hostname" "Karris Solo/Duo/Trio 2x FULLWIPE|21/12|TP|HOME|KITS|QUICKSMELT|" "+server.identity" "rustserver" "+server.seed" "375012345" "+server.maxplayers" "150" "+server.worldsize" "4000" "+server.saveinterval" "2000" "+rcon.web" "0" "+rcon.ip" "62.210.180.56" "+rcon.port" "28016" "+rcon.password" "******" "-logfile" "/home/rustserver/log/server/rustserver-game-2019-09-07-14:42:20.log" 
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/kernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589aa763080.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589aa83a2e0.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589aa86a970.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589aa1aa840.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589aa1b9730.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/data-0x5589c27b1f80.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/kernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32.so
Fallback handler could not load library /home/rustserver/serverfiles/RustDedicated_Data/Mono/libkernel32
[Manifest] URI IS "https://api.facepunch.com/api/public/manifest/?public_key=j0VF6sNnzn9rwt9qTZtI02zTYK8PRdN1"
 `
Is this LGSM related ?
If not, is is possible anyone knows the solution to this ?
I'm happy for any ideas that might help :)
Thanks

**Comment by Karrigallu** [comment]
another error a bit further down the code is: 

> TypeLoadException: Failure has occurred while loading a type.
  at Bootstrap+<Start>d__17.MoveNext () [0x00236] in <c9b90053cdab4c6a84a2cd59b27f4fff>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in <5efc91990d9549c2a2cf3874065a5193>:0

**Comment by milchinskiy** [comment]
same here

**Comment by Karrigallu** [comment]
> same here. Its not LGSM related, I have the same issue on the raw installation, on docker installation and on the LGSM installation.

Did you find any fix yet ?

**Comment by Karrigallu** [comment]
Found a fix: 
https://umod.org/community/rust/12061-server-not-starting-with-oxide?page=5
Easy as 1,2,3

**Comment by milchinskiy** [comment]
fix it in the same way

**Comment by Frisasky** [comment]
same cause as #2501 so id gonna close this issue
