### ISSUE TITLE
lib32tinfo5 no longer available under debian buster

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2503]
## User Story

Same as ubuntu did before(#982), since debian buster you need install lib32tinfo5 via libtinfo5:i386
this package is available under all currently supported debian versions, so theres should be no problem changing required dependencies in website

## Basic info

* Distro: [Debian buster]

## Further Information

root@debian:/home/ahl2server# apt install lib32tinfo5
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib32tinfo5

## To Reproduce

N/A

## Expected behaviour

package should install successfully

**Comment by dgibbs64** [comment]
#2463
