### ISSUE TITLE
Strange bug. lgsm dosen't start with oxide

### ISSUE THREAD

**Issue by gus21rus** [GameServerManagers/LinuxGSM#2505]
Follow **[this guide](https://linuxgsm.com/support/#guide)** to make sure you post the correct info.
For general support visit the **[LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support)**.

Issues here are **ONLY** for:
* LinuxGSM bugs
* feature suggestions
* code contributions

Issues here are **NOT** for:
* General support
* Specific game server issues (e.g CS:GO, TF2)
* Dedicated server issues (e.g Ubuntu, CentOS)
* Anything not directly related to LinuxGSM development

Any general support issues on GitHub will be migrated to [LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support).

*Please use the template below*

## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Garry's Mod]
* Command: [Monitor]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:

**Comment by Frisasky** [comment]
please check pinned message in our discord channel
https://discordapp.com/invite/UM4VTpK
since you did not provide any information in theissue i would gonna close this issue due to ambiguous description
