### ISSUE TITLE
Running multiple servers from the same folder CSGO

### ISSUE THREAD

**Issue by panikajo** [GameServerManagers/LinuxGSM#2523]
Since, after recent updates, the + sm_basepath function has stopped working in csgo, I ask you to add it to lgsm.
And it’s exactly in the server configuration to add ways to use the mod in this case sourcemod, metamod. So that for each server it was possible to register a path. Since valve broke this feature manually.

https://wiki.alliedmods.net/Multiple_or_Forked_Servers_(SourceMod)
EDIT Not supported anymore since 02.09.2019 CS:GO update (SM Build 6282)

Sorry for my bad english.

**Comment by borzaka** [comment]
You can:
- run [multiple servers](https://docs.linuxgsm.com/features/multiple-game-servers) (instances) from the same install folder easily if you want to use the same SourceMod plugins - in this case you might be able to modify some settings per instance
- if you want multiple servers (in the same install directory), but every instance would run different plugins, you have to manage loading/unloading plugins in your instance config
This AlliedModders Wiki article is a great start: https://wiki.alliedmods.net/War_Mode_(SourceMod)
You basically unload all the plugins, and you load what you need for that instance.
`sm plugins unload_all //unloads all plugins`
`sm plugins load basebans.smx //loads basebans.smx plulgin`
`sm plugins load basecommands.smx //loads basecommands.smx plulgin`
...
