### ISSUE TITLE
Arma Headless Client not using parms

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#2524]
## User Story

As a server admin, I want that the parms parameter is actually used so that the option `-client` is used in the start script.

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Arma 3]
* Command: [start]

## Further Information

I followed the steps on [this site](https://docs.linuxgsm.com/game-servers/arma-3#headless-client-setup-and-usage) and added a second arma 3 instance. I added to the `lgsm/config-lgsm/arma3server-hc.cfg` the option `parms="-client -connect=${ip}:${port} -password=myserverpw"` and started the server but the server started without these settings.

## To Reproduce

Steps to reproduce the behaviour:
follow the steps described above.

## Expected behaviour
server starting WITH `-client`

**Comment by Vexarii** [comment]
I'm also facing the same issue trying to create headless clients. 

The crux of it, after conducting some testing, appears to be that instance.cfg isn't reading properly.

_default.cfg reads fine, common.cfg reads fine...unfortunately instance.cfg does not.

I found that instance.cfg wasn't automatically created for each instance, so I created an instance.cfg for each of them and lgsm isn't reading these. Would you agree that this a similar experience to yourself @Fuggschen ?

**Comment by Vexarii** [comment]
Fixed in an update 5 days ago - update lgsm per the below thread.
#2635

**Comment by Fuggschen** [comment]
sorry for the late answer (I don't check my mails so often)
unfortunately I'm not using lgsm anymore 'cause of this problem and I can't test it anymore

**Comment by Claiyc** [comment]
Fixed by #2635
