### ISSUE TITLE
csgo start command -ip

### ISSUE THREAD

**Issue by slgfire** [GameServerManagers/LinuxGSM#2534]
Hello,
i use lgsm for a csgo LAN server.
and i see that the server is not listed in den lan-server list from steam.
but when i use the following start params:
```
fn_parms(){
parms="-game csgo -usercon -strictportbind -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +sv_setsteamaccount ${gslt} -tickrate ${tickrate} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers_override ${maxplayers} +mapgroup ${mapgroup} +game_type ${gametype} +game_mode ${gamemode} +host_workshop_collection ${wscollectionid} +workshop_start_map ${wsstartmap} -authkey ${wsapikey} -nobreakpad"
}
```
but when im not use "-ip ${ip}" the server will show in the list. 

I want to give each server its own ip, but they should also be visible in the steam lan server browser.

How can I do that?

**Comment by Frisasky** [comment]
hmmmm, german-english hybrid language?
maybe just typing what you want to say in google translation then post the translated text

**Comment by slgfire** [comment]
ok, i try my best :D

**Comment by Frisasky** [comment]
try add sv_lan 1 to your csgo's config and uses the ip of your server instead of 0.0.0.0

**Comment by slgfire** [comment]
I tried but no change. The server is not displayed in the list.

it depends perhaps on the user rights?
can I somehow run the launcher as root?

**Comment by Frisasky** [comment]
no, you cant run as root
the lan table in steam/csgo browser maybe broken, if youre having lan party you can just connect via ip

**Comment by slgfire** [comment]
ok, i find this: https://github.com/GameServerManagers/LinuxGSM/issues/1770
i try it :).

lan browser is not broken when the server is listed without -ip.

With Windows and -ip as startparameter (as administration), the server is listed. i think thats a problem with binding IPs to csgo at the lgsm.

**Comment by 991jo** [comment]
I had this issue a long time ago, take a look at this:
https://github.com/GameServerManagers/LinuxGSM/issues/1741
basically you have to set the ip param to your real IP because LSGM will complain otherwise.
But you have to replace the -ip $ip param in the start line with -ip 0.0.0.0 so that the server binds to all IPs. This is probably a bug and Valve doesn't care.

**Comment by slgfire** [comment]
i cant use 0.0.0.0 :)
on the centos host i have multiple ip adresses (docker, kvm, local etc)
tomorrow i test a manual csgo installation and start the server as root

**Comment by 991jo** [comment]
That is a bug in the CSGO server... it only listens to the UDP broadcast used for LAN game discovery when bound to 0.0.0.0.
