### ISSUE TITLE
LGSM is not detecting a Game-instance when Server is started from Website (executed by www-data via php)

### ISSUE THREAD

**Issue by StS-cs** [GameServerManagers/LinuxGSM#2537]
## Basic info
* Distro: Debian 9
* Game: CSGO
* Command: Start, Stop etc

I am running my csgoservers on my debian server. I want to administrate it via Website.
Website is set and i can execute commands via php: `system("sudo -u csprac /home/csprac/csgoserver start")`. This does work, The server starts and i can use it like i want to. I can manage it completly via website. 

But when i want to try to manage the server from the shell, i cant. It doesnt tell me a server is online. it doesnt seem to see that there is an instance already
Probably the script to detect running servers is not running correct.

**Comment by h3o66** [comment]
please check with what user the tmux is running. `ps aux | grep tmux`
You can only start/stop the instaces that belog to the same user.

**Comment by csStS** [comment]
i know that and they should do that.
When i execute "sudo -u csprac /home/csprac/csgoserver start" as www-data then the game should start as csprac. As it did!
`ps aux | grep tmux` tells me exactly that. www-data is just running standard apache proceses and csprac is running the server

**Comment by h3o66** [comment]
if you manage the server from the shell i assume that you are logged into the user csprac then.
otherwise this would not work.

Please check then in the user csprac what happens if you execute `tmux ls` and if the session for the gameserver is listed.

**Comment by csStS** [comment]
when i am logged on as csprac it says `no server running on /tmp/tmux-1000/defaultno server running on /tmp/tmux-1000/default`
but when i execute it, i execute it as csprac => `system("sudo -u csprac /home/csprac/csgoserver start")`
