### ISSUE TITLE
Minecraft javaram setting broken

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2540]
## User Story

Trying change allocated ram for mc server with javaram parameter did not work for unknown reason, currently must change xmx in executable parameter

## Basic info

* Game: [Minecraft]

## Further Information

N/A

## To Reproduce

N/A

## Expected behaviour

just edit the value of javaram should be enough to change allocated ram

**Comment by dgibbs64** [comment]
This is caused by the executable var in _default.cfg being set before javaram in common.cfg. This is why fn_parms is required in a config. Not sure about the best solution yet

**Comment by UNiXMIT** [comment]
@Frisasky Where in the executable can I change the value used for -xmx? Thanks
