### ISSUE TITLE
Updating Multiple Instances

### ISSUE THREAD

**Issue by LubricantJam** [GameServerManagers/LinuxGSM#2552]
##  User Story

I currently run multiple instances of the same servers which is great, I save on a lot of server storage and maintenance however when a game update happens, I can only update one of the servers and that means the others aren't detecting the update. What I'd like to see happen is when an update command is ran on one of the instances, all of the others turn off until the update is complete, then they all turn back on together. 

## Basic info

* Distro: Ubuntu 16.04
* Game: Counter Strike: Global Offensive
* Command: Update

**Comment by dgibbs64** [comment]
The current idea as the instances dont work together is a lock file stating when the last update was run compared to the last start. if the update is newer than the last start then reboot. This could be implemented on both monitor and update commands.

**Comment by LubricantJam** [comment]
Sweet, any plans for this in the near future?

**Comment by dgibbs64** [comment]
So probably release v20.2.0

**Comment by tk1114632** [comment]
I have updated LGSM to 20.4.1 for csgoserver
When my first instance is updated by ./csgoserver update, other instances don't restart by ./csgoserver-[N] monitor.
Any idea what I did wrong? Thanks.
