### ISSUE TITLE
[ts3server] Command details is causing error

### ISSUE THREAD

**Issue by xopez** [GameServerManagers/LinuxGSM#2559]
## User Story

Using the parameter `details` on `ts3server` is causing an output error.
Tested it only with latest LGSM release v19.11.0

## Basic info

* Distro: Ubuntu 18.04.3 LTS
* Game: ts3server
* Command: details

## Further Information

The Output generated: https://pastebin.com/78ida3XS
I also saw that under `Game Server Resource Usage` is no value at all.

## To Reproduce

Steps to reproduce the behaviour:
1. install ts3server
2. use the command dt while server is online

## Expected behaviour
no output error

**Comment by dgibbs64** [comment]
thanks for this. I will need to investigate further. Its relating to a new feature just released

**Comment by dgibbs64** [comment]
Yeah looks like it forgot to finish the ts3 specific code. Ts3 is the only server not using tmux and has to be treated a little differently

**Comment by dgibbs64** [comment]
The next release resolves the issue by l converting ts3 to using tmux.
