### ISSUE TITLE
It is possible to add rust?

### ISSUE THREAD

**Issue by joecabezas** [GameServerManagers/LinuxGSM#256]
as the title says, it is possible to add "rust dedicated server", see https://developer.valvesoftware.com/wiki/Rust_Dedicated_Server

**Comment by Scarsz** [comment]
https://github.com/dgibbs64/linuxgameservers/issues/155

Dev's are lazy and wont fix the Linux SteamCMD download

**Comment by dgibbs64** [comment]
Closing as duplicate.

https://github.com/dgibbs64/linuxgameservers/issues/155
