### ISSUE TITLE
Can't Update Rust Server

### ISSUE THREAD

**Issue by Nark0t1k** [GameServerManagers/LinuxGSM#2562]
I'm using LinuxGSM for hosted a Rust Dedicated Server

But each time they do a  Rust update i need to re install all my server because update cmd doesn't work ...

> rustserver@vmi296637:~$ ./rustserver update
> [  OK  ] Update rustserver: Checking for update: SteamCMD
> 
> Update available
> * Local build: 4261063
> * Remote build: 4301925
> https://steamdb.info/app/258550/
> 
> applying update...
> Redirecting stderr to '/home/rustserver/Steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation
> -- type 'quit' to exit --
> Loading Steam API...OK.
> 
> Connecting anonymously to Steam Public...Logged in OK
> Waiting for user info...OK
> ERROR! Timed out waiting for AppInfo update.
> /home/rustserver/lgsm/functions/alert.sh: line 21: fn_info_message_server_resource: command not found
> /home/rustserver/lgsm/functions/alert.sh: line 22: fn_info_message_gameserver_resource: command not found
> rustserver@vmi296637:~$

Timed Out Waiting For AppInfo -_-

That really Annoyed, if i remove all the server and re download it it's work but not if i use update cmd...

**Comment by dgibbs64** [comment]
``./rustserver update-lgsm``

also this might help https://www.reddit.com/r/playrust/comments/c3q3zh/error_timed_out_waiting_for_appinfo_update/

**Comment by Septembers** [comment]
I have the same problem. Installed the CS: GO server - it does not start. I do validation - I get an error ERROR! Timed out waiting for AppInfo update.
I can not do update or validate
lgsm latest version

fix pls

**Comment by walliski** [comment]
What operating system are you running the server on? I had similar issues with SteamCMD on my Debian host due to a TCP related kernel bug. So if you are on linux, try updating the kernel 🤷‍♂

**Comment by Nark0t1k** [comment]
Yep new update and same bug

I try to apt-get update/upgrade

I also use ./rustserver update-lgsm

and not working :(

**Comment by Vrrl** [comment]
same .- but its my first time i try to use LGSM, before i used windows and goes good...

**Comment by Nark0t1k** [comment]
Any news for this??
https://i.imgur.com/hLY4N24.png

**Comment by dgibbs64** [comment]
Sadly there is not really anything LinuxGSM can do as this is a SteamCMD/Distro issue. I am closing this as it is a not a LinuxGSM related issue.

**Comment by Nark0t1k** [comment]
> Any news for this??
> https://i.imgur.com/hLY4N24.png


For fix:
Delete steam and steamcmd folder then use ./rustserver install

Just like a new setup, all you old file will be keep in safe

And you can update your game with the linuxgsm bug.

It's a linuxgsm bug because if you manually update it that work well only with linuxgsm that not work.

**Comment by Zorrototo** [comment]
^ just so you know this exact error is affecting someone using OGP not LGSM so this is not a LGSM bug but a steamcmd bug.
