### ISSUE TITLE
Teamspeak3 error: list of session leaders OR effective group names must follow -g

### ISSUE THREAD

**Issue by olokos** [GameServerManagers/LinuxGSM#2570]
## User Story

Since a month or so I have noticed that my ts3server is spewing errors when doing ./ts3server start
Specifically error
error: list of session leaders OR effective group names must follow -g
Most likely due to recent lgsm updates

## Basic info

* Distro: Ubuntu 18.04 LTS running kernel 5
* Game: Teamspeak3 server
* Command: start

## Further Information

I am running latest php7.3, MySQL8, each and every package is up-to-date.
This bug does not occur with csgoserver
This bug does occur even when using the latest _default.cfg

## To Reproduce

Steps to reproduce the behaviour:
1. Go to ts3 server home directory
2. do ./ts3server start
3. Error pops up

## Expected behaviour
Start without this error.
Because of this bug rc.local fails to continue with the rest of its code

Here's a screenshot, which shows the issue nicely
https://imgur.com/a/zSadcmd

**Comment by dgibbs64** [comment]
Thanks. I am aware of this issue. It will be fixed in the next release. Ts3 will be converted to use tmux.

**Comment by olokos** [comment]
Glad to hear that. Is there any workaround for now?

**Comment by dgibbs64** [comment]
There is no workaround. However, the message does not affect the running of the server in any way.

**Comment by olokos** [comment]
Well, because of this rc.local stops executing and so does its service rc.local.service.d. If there's anything after the code of running the server then anything below that line won't be ran by rc.local.

**Comment by olokos** [comment]
@dgibbs64 this issue prevents rc.local from executing.
If there's any lines below lgsm server, then those are ignored as rc.local fails on lgsm.
While it does not affect running of the particular lgsm server, it does disrupt proper autostart of programs on the entire server machine.
