### ISSUE TITLE
[Server Request] Day of Dragons

### ISSUE THREAD

**Issue by Yamiru** [GameServerManagers/LinuxGSM#2572]
## What game server would you like adding?

Day of Dragons 
(now beta, but release date: November 21st, 2019)

## Can you link to any tutorials or guides?
https://steamcommunity.com/app/1088090/guides/

## Is the server on Steam?
Yes

## If yes Use SteamDB to get the appid. (https://steamdb.info).

1088090 Game - Day of Dragons
1088320 Tool - Day of Dragons - Dedicated Server

## Is the server supported on Linux?
yes linux dedicated

## We only support Linux servers and do not support Wine.
Yes i test it work with linux without wine

**Comment by h3o66** [comment]
Guide:
https://steamcommunity.com/sharedfiles/filedetails/?id=1928782082
