### ISSUE TITLE
[Error GMOD] Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar

### ISSUE THREAD

**Issue by BaguetteV1** [GameServerManagers/LinuxGSM#2573]
Hi, i have an error in my console when i start the server: 
`Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar`
I know it is not an important error, but i like when there are no error in my console.
Map running (I say that cause i see mat_dxlevel): flatgrass
I hope you can help me, see u

**Comment by Frisasky** [comment]
you can just ignore this error. its a warning for graphic related cvar which completely doesnt matter for server.
close as not related for lgsm
