### ISSUE TITLE
sdtdserver pd fails to post details to hastebin

### ISSUE THREAD

**Issue by mostlyerror** [GameServerManagers/LinuxGSM#2574]
## User Story
As a server administrator, I want to see and share server details to ask better questions so that I can debug server issues myself.

## Basic info

* Distro: [Debian 10]
* Game: [7 Days To Die]
* Command: [pd]

## Further Information
Attempt to use the `pd` or `postdetails` command result in an error message.

## To Reproduce

Steps to reproduce the behaviour:
Go to directory where sdtdserver was installed.
Run `./sdtdserver pd`
Output:
```
sdtdserver@localhost:~$ ./sdtdserver pd
    fetching command_postdetails.sh...OK
[ INFO ] Postdetails sdtdserver: Check IP: <SERVER_IP>
[  OK  ] Postdetails sdtdserver: Posting details to hastebin.com for 30D
Please share the following url for support: https://hastebin.com/<!DOCTYPE html>
<html>
<head>
width=device-width, initial-scale=1

<title>Application Error</title>

		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
</head>
<body>

</body>
</html>
```

**Comment by Frisasky** [comment]
sometime pastebin failed to receive the data sent by lgsm. try few more times
