### ISSUE TITLE
[ERROR ] Stopping rustserver: Graceful: sending "quit": FAIL

### ISSUE THREAD

**Issue by Levingard** [GameServerManagers/LinuxGSM#2580]
Hi every time i restart my rust rerver i get:

root@rust4ever ~ # su - rustserver1
rustserver1@rust4ever:~$ ./rustserver restart
[ INFO ] Stopping rustserver: Check IP: 78.46.75.8
[ERROR ] Stopping rustserver: Graceful: sending "quit": FAIL
[  OK  ] Stopping rustserver: Rust4ever Testserver
[  OK  ] Starting rustserver: Rust4ever Testserver

Whats wrong?

I am on a dedicated server with Ubuntu 18.04 on latest LinuxGSM release.

**Comment by P4R4NORM4L** [comment]
I think he just didn't update his config file, this was happening to me too, but i copied the default (updated) config from lgsm folder and redid all my config and now it is Okay.

**Comment by dgibbs64** [comment]
OK I will close this. Please re-raise if needed .Thanks
