### ISSUE TITLE
[Server Request] Space Engineers

### ISSUE THREAD

**Issue by Skeec54** [GameServerManagers/LinuxGSM#2581]
## What game server would you like adding?

[Space Engineers](https://store.steampowered.com/app/244850/Space_Engineers/)

## Can you link to any tutorials or guides?

Maybe it can help:
https://www.spaceengineersgame.com/dedicated-servers.html

## Is the server on Steam?

* [X ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

244850

## Is the server supported on Linux?

We only support Linux servers and do not support Wine.

* [ ] Yes
* [ ] No
Unknown for me (currently can´t find anything with it)

**Comment by Frisasky** [comment]
windows only
https://steamdb.info/app/244850/
