### ISSUE TITLE
UT2004 use ucc 64 bit

### ISSUE THREAD

**Issue by Cave-Johnson** [GameServerManagers/LinuxGSM#2598]
As a server admin, I want to be able to run the server using the 64bit ucc binary.

## Basic info

* Distro: Ubuntu 18.04
* Game: UT2004

## Further Information

To get the 64bit binary to work I had to install libstdc++5 to fix the below error ( apt install libstdc++5)

./ucc-bin-linux-amd64: error while loading shared libraries: libstdc++.so.5: cannot open shared object file: No such file or directory

Is there any reason not to use the native 64 bit version of the server?

**Comment by dgibbs64** [comment]
I may be wrong but I seem to remember a few years back that the 64-bit binary simply doesn't work for whatever reason and epic never fixed it. Would happily be proven wrong and support the 64 bt binary if it does work,

**Comment by Cave-Johnson** [comment]
How would i modify the scripts to make use of the 64 bit binary? If i call it on its own the server launches fine

**Comment by dgibbs64** [comment]
add the executable setting into common.cfg changing it to the 64 bit version.see _default.cfg for an example. Also please report your findings. I will keep this open to implement possible change to use 64-bit binary.

**Comment by Cave-Johnson** [comment]
Will try it and post back.

**Comment by Cave-Johnson** [comment]
Just found this ticket, yes this is still an issue with the web admin unfortunately 
https://github.com/GameServerManagers/LinuxGSM/issues/98

Explains why you removed it before!

**Comment by Frisasky** [comment]
since unreal never release the source code of ut2004, theres nothing community could do imo. so its better just running the 32 bit binary. for such old game 32 bit wont bottleneck the server in any way
