### ISSUE TITLE
[ut2k4server] adds Escape characters to server config

### ISSUE THREAD

**Issue by Cave-Johnson** [GameServerManagers/LinuxGSM#2601]
I don't see a way to reopen https://github.com/GameServerManagers/LinuxGSM/issues/1448 - fresh install on Ubuntu 18.04 and this is still an issue.

However if I remove the escape characters from the ut2k4server.ini the server readds that section on the next start. (ie duplicates the block)

**Comment by Frisasky** [comment]
i have submitted update for ut2004 config file
https://github.com/GameServerManagers/Game-Server-Configs/pull/91
