### ISSUE TITLE
Linuxgsm Download servers failed downloads for cod4server.

### ISSUE THREAD

**Issue by lorentedford** [GameServerManagers/LinuxGSM#2602]
Follow **[this guide](https://linuxgsm.com/support/#guide)** to make sure you post the correct info.
For general support visit the **[LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support)**.

Issues here are **ONLY** for:
* LinuxGSM bugs
* feature suggestions
* code contributions

Issues here are **NOT** for:
* General support
* Specific game server issues (e.g CS:GO, TF2)
* Dedicated server issues (e.g Ubuntu, CentOS)
* Anything not directly related to LinuxGSM development

Any general support issues on GitHub will be migrated to [LinuxGSM-Support](https://github.com/GameServerManagers/LinuxGSM-Support).

*Please use the template below*

## User Story

A ticket was already established for issues with Curl but after further testing we were able to download with updating Curl. However this seems to be a connection issue to the server.  Basically the server providing the download seems to have a timer for the length of time that a connection is established to the server then cuts it at that time.. So various connections like my home connection servers only get to 12% where as my linode server downloads much faster and makes it to 50%.

## Basic info

* Distro: [Ubuntu 18.04LTS Server]
* Game: [Call of duty 4]
* Command: [install]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'Get a linode server for five dollars'
2. Click on 'Install Ubuntu 18.04LTS'
3. Set 'root password'
4. ssh into the server using root.
5. Use Linuxgsm website for installation.
6. Run this command as root `sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386`
7. add a user `adduser cod4server`
8. Change user `su - cod4server`
9. run this command as cod4server `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh cod4server`
10. run the installation command `./cod4server install`
11. Error will occur once download starts on my linode it errors out about 52% on my home servers it errors out around 12% some thing disconnects the connection on Linuxgsm side. 

## Expected behaviour
I expect the server to download the file and install.

## Screen Shot from linode server
![image](https://user-images.githubusercontent.com/8719903/69315731-cbf95280-0bfc-11ea-8781-ac3f0f8b4752.png)

## Screen Shot from my home servers
This server already uses linuxgsm to host my csgo servers.
![image](https://user-images.githubusercontent.com/8719903/69315757-e5020380-0bfc-11ea-8fbd-f53de2e57946.png)

Fortunately I have a back up from when it was downloading the other day but still would much rather have a proper clean installation of this for my game servers.

**Comment by dgibbs64** [comment]
Issue already open

https://github.com/GameServerManagers/LinuxGSM/issues/2597

**Comment by lorentedford** [comment]
Why was this closed?? There is still a problem as of 12-01-2019

![image](https://user-images.githubusercontent.com/8719903/69911278-b0e9c800-13de-11ea-9180-47edc093ee6e.png)

**Comment by dgibbs64** [comment]
Was closed 10 days ago as its a duplicate.
