### ISSUE TITLE
TeamSpeak3 default ts3server.ini missing important parameter

### ISSUE THREAD

**Issue by BrutalBirdie** [GameServerManagers/LinuxGSM#2605]
User Story:
I want to run more then one TeamSpeak3 Server.

Expected behavior:
I create a second instance and edit the ts3server.ini and change the ports

Current behavior:
Server not starting because Port 10022 already in use.

Reproduce?
Create 2 ts3server instances change the ports and watch one fail.

This is the default ts3server.ini

```bash
$ cat lgsm/config-default/config-game/ts3server.ini
```
```ini
machine_id=
default_voice_port=9987
voice_ip=0.0.0.0, ::
licensepath=
filetransfer_port=30033
filetransfer_ip=0.0.0.0, ::
query_port=10011
query_ip=0.0.0.0, ::
query_ip_whitelist=query_ip_whitelist.txt
query_ip_blacklist=query_ip_blacklist.txt
dbplugin=ts3db_sqlite3
dbpluginparameter=
dbsqlpath=sql/
dbsqlcreatepath=create_sqlite/
dbconnections=10
logpath=logs
logquerycommands=0
dbclientkeepdays=30
logappend=0
query_skipbruteforcecheck=0
```

There are 2 important configs missing.
See https://forum.teamspeak.com/threads/138821-Fragen-zu-Query-SSH

```ini
query_ssh_ip=0.0.0.0, ::
query_ssh_port=10022
```
Without the `query_ssh_port` the second server will never work.

Open for some feedback, change my mind :)

**Comment by Frisasky** [comment]
update submitted
https://github.com/GameServerManagers/Game-Server-Configs/pull/92
