### ISSUE TITLE
Quiting server or not restarting.

### ISSUE THREAD

**Issue by uGamers** [GameServerManagers/LinuxGSM#2609]
* Distro: [Ubuntu 16.04.6 LTS]
* Game: [CounterStrike]
* Command: [Monitor]

## Further Information

One time a day it seems like the server gets shut down and this next message is in the logs but ownership of files is ok.
```
Nov 23 04:00:02.884 csserver: CHECK: FATAL: Ownership issues found
Nov 23 04:00:03.387 csserver: CHECK: INFO: The current user (assault) does not have ownership of the following files:
User  Group  File
Nov 23 04:00:03.998 csserver: CHECK: For more information, please see https://docs.linuxgsm.com/support/faq#fail-starting-game-server-permission-issues-found
```
I even did chmod -R 0770 assault and chown -R assault:assault assault

## To Reproduce

Steps to reproduce the behaviour:

Not really sure....

**Comment by Frisasky** [comment]
path of server installation?

**Comment by uGamers** [comment]
/home/counterstrike/assault

**Comment by Frisasky** [comment]
try
chown -R counterstrike:counterstrike /home/counterstrike/assault
if not work try this
chown -R assault :assault /home/counterstrike/assault
