### ISSUE TITLE
Not functional GameUserSettings.ini [Arkserver] after map setup.

### ISSUE THREAD

**Issue by Skeleton022** [GameServerManagers/LinuxGSM#2612]
First of all sorry if this is the wrong place to put this issue, if so please redirect me to the correct site. Thanks a lot :) 

So I just installed LinuxGSM with ARK server to Ubuntu server 18.04.3 LTS 64bit os.
Here is the 
```
uname -a: Linux ark 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ldd --version: ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
tmux -V: tmux 2.6
./arkserver postdetails: https://hastebin.com/gekufehufo
```
My problem is the following:
When I try to setup the map (in lgsm/config-lgsm/arkserver/arkserver.cfg) there is sometimes a corruption problem (I guess).

e.g: If I choose Valguero_P, or  CrystalIsles as defaultmap, my  GameUserSettings.ini gets a bit funny
like this funny: https://ibb.co/WVNrhPq (on the top middle you can see the file name).
But! If I use WinSCP and connect to the server via sftp, then see the SAME file I can see everything correctly:
```
[ServerSettings]
ActiveMods=1645346094
AllowFlyerCarryPvE=False
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=False
AutoSavePeriodMinutes=10.000000
...
```
My problem is when I start the server (./arkserver start) I get different problems first: 
Server name:    NOT SET  (but I set it!) This is the case if I set any of that two maps.
If I set  CrystalIsles I got another as well: The max player is ALWAYS set to 70 players (Even if I set it to any other number) And I just can not connect to the server either timeout, or some other problem (I can connect to the server without any problems if I set the map to ragnarok, or something else)

Otherwise if I choose Ragnarok, or TheIsland Everything is normal (the GamesUser...ini, and the server name and all the setted settings!

I already reinstalled the LinuxGSM, and the full ubuntu system as well. It is still happening.

Am I doing something wrong is it really a bug?

I tried to be as precise as I could, let me know if I missed something. Thanks in advance.

**Comment by dgibbs64** [comment]
Closing this
