### ISSUE TITLE
UPDATE: FATAL: update_steamcmd.sh exiting with code: 1

### ISSUE THREAD

**Issue by CatRuby** [GameServerManagers/LinuxGSM#2623]
Already the 3rd update, my servers are not updated automatically, before everything was fine, ./csgoserver ul did, everything was updated, it is written in crontab -e

```
*/3 * * * * ~/csgoserver monitor > /dev/null 2>&1
*/30 * * * * ~/csgoserver update > /dev/null 2>&1
```
I found an error in the logs like this
```
05:03:08.022 csgoserver: UPDATE: FATAL: Checking remote build
05:03:08.025 csgoserver: UPDATE: FATAL: update_steamcmd.sh exiting with code: 1
```
6 out of 7 of my servers have to be updated manually before there were no problems, one is updated automatically

 https://hastebin.com/qowelisama

**Comment by dgibbs64** [comment]
Recent 2GB update may have caused the issue.

**Comment by CatRuby** [comment]
> Recent 2GB update may have caused the issue.

this is already like 3 updates in a row, I have to update them myself (
Free space more than 20GB

**Comment by dgibbs64** [comment]
you are not the only person with this issue. This will need further investigation.

**Comment by dgibbs64** [comment]
There are now three issues that appear to be the same. Please, can you post the output of `./csgoserver post-details`

**Comment by dgibbs64** [comment]
#2624 #2623 #2619
