### ISSUE TITLE
CSGO does not find new updates

### ISSUE THREAD

**Issue by walliski** [GameServerManagers/LinuxGSM#2624]
## Basic info

* Distro: Debian Stretch
* Game: CSGO
* Command: ./csgoserver update

## Further Information

Running the normal "update" command just says
```
No update available
* Local build: 4428608
* Remote build: 4428608
```

Running the force-update command successfully updates the server.

## To Reproduce

This has happened on my server for a couple of weeks now. Tried doing a fresh install of LGSM, but still doesn't want to work :<

**Comment by dgibbs64** [comment]
There are now three issues that appear to be the same. Please, can you post the output of `./csgoserver post-details`

**Comment by dgibbs64** [comment]
#2624 #2623 #2619

**Comment by walliski** [comment]
For me this started earlier than 9 days ago, as the issue where the size grew. I have since tried various things to fix it, the last being creating a new installation of LGSM from scratch to get all the newest scripts etc.

The other issue mentions "FATAL: update_steamcmd.sh exiting with code: 1", which is not happening for me. It gives a 0 exit code and just doesn't find new updates :<

So I would not 100% say the issues are related.
