### ISSUE TITLE
Not able to start second copy of Wurm Server.

### ISSUE THREAD

**Issue by interstate420productions** [GameServerManagers/LinuxGSM#2631]
Hi All.. I am trying to start a second copy of my Wurmserver.
Things done:
./linuxgsm.sh install  (wurmserver-2) generated.
Changed port numbers by a range of 10   

Modified config files.   When I start one of the servers it will start.. Starting the second server starts.
But has killed the first server.  :(  

Thank you in advance for any help

**Comment by Comminux** [comment]
@interstate420productions Check your new _default.cfg and fix difference in you main config.

(For example check my picture)
![Снимок экрана_2019-12-01_03-58-21](https://user-images.githubusercontent.com/14937307/69908844-3c288500-1402-11ea-88dd-c40d59bed0ab.png)

**Comment by interstate420productions** [comment]
> @interstate420productions If you are using LinuxGSM v19.12.0 or newer, check your new _default.cfg and fix difference in you main config.
> 
> (For example check my picture)
> ![Снимок экрана_2019-12-01_03-58-21](https://user-images.githubusercontent.com/14937307/69908873-d688c880-1402-11ea-9bd1-7923a8d3a9ec.png)

All changes were already completed in my default.cfg.

**Comment by interstate420productions** [comment]
Additionally Creating a new user, and installing the server under a completely different user... and modifying the ports.  Same end result.. You start one.. then start the other and the first one stopped.

**Comment by interstate420productions** [comment]
I believe that mom?  From discord believes that this problem may be tied to Xvfb session counts.

**Comment by Comminux** [comment]
@interstate420productions Why you doesn't provide any information about you environment? Edit your first post with this template:
```
Issues raised here are **ONLY** for:
* LinuxGSM bugs.
* Feature suggestions.
* Code contributions.

Issues raised here are **NOT** for:
* General support.
* Specific game server issues (e.g CS:GO, TF2).
* Dedicated server issues (e.g Ubuntu, CentOS).
* Anything not directly related to LinuxGSM development.

For general support visit the **[LinuxGSM-Support](https://linuxgsm.com/support)**.

***Please use the template below, deleting the above text***

## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** [v12.34.56]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behaviour
```

**Comment by interstate420productions** [comment]
## User Story

As a System Admin with Root and SSH, I want to be able to install and run two copies of the same binary. So that I may have two servers running with Different maps. 

I have no idea what exactly is causing the issues.   I'm afraid I can't be of much help in this department. 

Distro Debian 10
Game :Wurm Unlimited.
Command :  ./wurmserver start     ./wurmserver monitor
LGSM:  LinuxGSM v19.12.0

I don't know how to make it any clearer that when I start one server.  and then start the other the first one gets Stopped.. and Vise Versa.    "Won't start a second Copy"

To Reproduce:
Create New user Install server

Create Second New user Install server.

Start First server... 

Modify ports for Second Server.  Start Second Server and Watch first one stop. 

#Expected Behavior is to be able to run two copies of the same binary :)

**Comment by interstate420productions** [comment]
I will try to be as cooperative as possible please just tell me what you need / want me to do :)

**Comment by Comminux** [comment]
@interstate420productions I was just looking for some answers to my questions and discovered your issue. Now you will have to wait for an answer from the other participants.

**Comment by interstate420productions** [comment]
I'm not sure what you want?  you asked for very specific things.. I gave you the best answers I had.  I am humbly sorry if I have offended you somehow :)

**Comment by interstate420productions** [comment]
Right on Brother :)  I hope this can be solved without too much undue stress on anyone's part.  I been trying for a few weeks now and well I have gotten no closer hahah thanks for your replies :)

**Comment by Comminux** [comment]
It's okay! I wasn't offended. I just wanted to help you in any way I could. But now you have a better chance of getting a good answer from knowledgeable people. It is important to read the rules before posting any question to the various github repositories. This saves time and effort for developers

**Comment by interstate420productions** [comment]
Duly Noted :)

**Comment by 991jo** [comment]
I have a similar issue.
The scripts use the wrong lgsm instance config file:

```
./csgoserver2 details

<snip>

csgoserver2 Script Details
=================================================================================================================================================================================================================================================================================
Script name:            csgoserver2
LinuxGSM version:       v19.12.0
glibc required:         2.15
Discord alert:          off
Slack alert:            off
Email alert:            off
Pushbullet alert:       off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushover alert:         off
Telegram alert:         off
Update on start:        off
User:                   csgo
Location:               /home/csgo/server1
Config file:            /home/csgo/server1/serverfiles/csgo/cfg/csgoserver2.cfg (FILE MISSING)

Ports
=================================================================================================================================================================================================================================================================================
Change ports by editing the parameters in:
/home/csgo/server1/lgsm/config-lgsm/csgoserver

<snip>
```

my script is called `csgoserver2` and it loads the config for `csgoserver`

**Comment by dgibbs64** [comment]
@991jo make sure you update again `./csgoserver1 update-lgsm` as bug fixes have been released

**Comment by interstate420productions** [comment]
An update to this problem.   I just did:
./wurmserver validate    and had several files that needed to be replaced... Now when attempting to start the second copy it just refuses to start without killing the first one now.   *Shrugs*  at least it's better than killing the first one.

**Comment by interstate420productions** [comment]
Ok since nobody seems to know how to fix this issue or even what's wrong.. i have started to investigate other solutions.  I am currently trying Docker..
What's done.
Docker installed
Ubuntu installed.
Docker Container IP Found.

Problems:
Starting Docker then attempting to : ./wurmserver start 
Returns following Errors:
-------------------------------------
wurmserver@243f50beb81e:~$ ./wurmserver start
/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
/home/wurmserver/lgsm/functions/check_ip.sh: line 16: /sbin/ip: No such file or directory
/home/wurmserver/lgsm/functions/check_ip.sh: line 17: /sbin/ip: No such file or directory
/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
[ .... ] Starting wurmserver: LinuxGSM/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
/home/wurmserver/lgsm/functions/check_ip.sh: line 16: /sbin/ip: No such file or directory
/home/wurmserver/lgsm/functions/check_ip.sh: line 17: /sbin/ip: No such file or directory
/home/wurmserver/lgsm/functions/info_distro.sh: line 226: ip: command not found
[ FAIL ] Starting wurmserver: Unable to start LinuxGSM

**Comment by interstate420productions** [comment]
Update installed  iproute2 in docker...   Now server just flat refuses to start

**Comment by interstate420productions** [comment]
Still not able to start to "Native" Binaries of this server.

**Comment by dgibbs64** [comment]
related #3570
