### ISSUE TITLE
LGSM script issues starting 12/1/2019

### ISSUE THREAD

**Issue by rip1980** [GameServerManagers/LinuxGSM#2635]
I've been running multiple CS1.6 servers for years, and LGSM for many of those. For some reason, the script broke on 12/1/2019. and MAYBE it's date related?

There have been no changes to my servers experiencing these issues since June, and they've all failed identically on 12/1.  So it's a script issue or a Ubuntu update breaking things, bit no overt werrors found so far.  I double checked permissions, update the script (ul), etc., and confident I didn't break it, via update or otherwise.

Issue 1:
./hlds_run -game cstrike -strictportbind +ip [EDITED] -port 27018 +clientport 27005 +map de_dust2 **+servercfgfile .cfg** -maxplayers 32 -tos -pingboost 2 -sys_ticrate 1000

It now not recognizing server.cfg and using ".cfg" instead.

My work around for this currently is edit cssserver.cfg and replace the string with a hard server.cfg

fn_parms(){
parms="-game cstrike -strictportbind +ip ${ip} -port ${port} +clientport ${clientport} +map ${defaultmap} **+servercfgfile server.cfg** -maxplayers ${maxplayers} -tos -pingboost 2 -sys_ticrate 1000"

Issue 2:
Log naming is getting mangled, "csserver" being trimmed from the beginning of the naming convention, as illustrated by the hastebin below.
Examples:
-rw-r--r-- 1 csserver4 csserver4   8747 Dec  1 17:05 -alert.log
-rw-rw-r-- 1 csserver4 csserver4   9526 Dec  1 00:00 csserver-alert.log

Server Details
https://hastebin.com/jowexoyupo

Mangled log naming:
https://hastebin.com/dicicotaba.diff

**Comment by Frisasky** [comment]
remove all content below LinuxGSM Settings in config file

**Comment by dgibbs64** [comment]
`./csserver update-lgsm` bug was was released yesterday

**Comment by rip1980** [comment]
I did update lgsm before posting the bug,  the hastebin is from v19.12.3 unless there's a newer one I'm not seeing.

 Frisasky -  Not an issue here.  I run multiple instances of lgsm separately, not multiple game servers under one script.

**Comment by Frisasky** [comment]
lgsm got an update without raising the version number, so try update-lgsm
