### ISSUE TITLE
Cannot extract zip file

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2636]
## User Story

It seems since 19.12 lgsm cannot extract ZIP package

## Basic info

* **Distro:** [Debian Buster]
* **Game:** [Soldat]
* **Command:** [Install]
* **LinuxGSM version:** [v19.12]

## Further Information

> downloading soldatserver2.8.1_1.7.1.zip...OK
verifying soldatserver2.8.1_1.7.1.zip with MD5...OK
extracting soldatserver2.8.1_1.7.1.zip...unzip:  cannot find or open /home/soldat/serverfiles, /home/soldat/serverfiles.zip or /home/soldat/serverfiles.ZIP.

## To Reproduce

Install Soldat game 

## Expected behaviour

file successfully decompressed

**Comment by Frisasky** [comment]
update: seems mod installation also affected by this bug, some plugins like oxide for rust are distributed in zip format

**Comment by asweiler** [comment]
I think it has to do with the zip extraction part of the mods-update function.

extracting Oxide.Rust-linux.zip...unzip:  cannot find or open /home/rustserver/lgsm/mods/tmp/extract, /home/rustserver/lgsm/mods/tmp/extract.zip or /home/rustserver/lgsm/mods/tmp/extract.ZIP.

**Comment by clumsyzombie** [comment]
> I agree it has to do with the zip extraction part of the mods-update function.
> 
> extracting Oxide.Rust-linux.zip...unzip: cannot find or open /home/rustserver/lgsm/mods/tmp/extract, /home/rustserver/lgsm/mods/tmp/extract.zip or /home/rustserver/lgsm/mods/tmp/extract.ZIP.

Yes I am having this same issue on all my rust servers even a brand new one I just setup for the wipe on Thursday

**Comment by dgibbs64** [comment]
I'm on it. A hotfix is inbound

**Comment by dgibbs64** [comment]
hotfix v19.12.4 has resolved this issue
