### ISSUE TITLE
Monitor function for UT99 broken

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2637]
## User Story

Monitor function broken for UT99, the monitor function cannot detect server status correctly, so in the end lgsm killed the server and restart it

## Basic info

* **Distro:** [Debian Buster]
* **Game:** [Unreal tournament 99]
* **Command:** [Monitor]
* **LinuxGSM version:** [v19.12]

## Further Information

> ut99@dev:~$ ./ut99server monitor
[ INFO ] Monitor ut99server: Check IP: 192.168.1.189
[  OK  ] Monitor ut99server: Checking session: OK
[ FAIL ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 60/5: FAIL
[  OK  ] Stopping ut99server: Graceful: CTRL+c: 1: OK
[  OK  ] Starting ut99server: LinuxGSM

## To Reproduce

run monitor command on running server

## Expected behaviour

detect server status correctly

**Comment by dgibbs64** [comment]
the `querytype` might be wrong. Try `protocol-gamespy1`

**Comment by Frisasky** [comment]
> 
> 
> the `querytype` might be wrong. Try `protocol-gamespy1`

different error message, same result

> ut99@dev:~$ ./ut99server monitor
[ INFO ] Monitor ut99server: Check IP: 192.168.1.189
[  OK  ] Monitor ut99server: Checking session: OK
[ .... ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 0/1: QUERYING                                                                                                                                                       [ .... ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 15/2: QUERYING                                                                                                                                                       [ .... ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 30/3: QUERYING                                                                                                                                                       [ .... ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 45/4: QUERYING                                                                                                                                                       [ FAIL ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 60/5: FAIL
[  OK  ] Stopping ut99server: Graceful: CTRL+c: 1: OK
[  OK  ] Starting ut99server: LinuxGSM

**Comment by Frisasky** [comment]
latest patch did not fix the problem @dgibbs64 

> [ INFO ] Monitor ut99server: Check IP: 192.168.1.189
[  OK  ] Monitor ut99server: Checking session: OK
[ .... ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 0/1: QUERYING    fetching query_gsquery.py...OK
[ FAIL ] Monitor ut99server: Querying port: gsquery: 192.168.1.189:7778 : 60/5: FAIL
    fetching alert.sh...OK
    fetching info_messages.sh...OK
    fetching command_restart.sh...OK
    fetching command_stop.sh...OK
[  OK  ] Stopping ut99server: Graceful: CTRL+c: 1: OK
[  OK  ] Starting ut99server: LinuxGSM

**Comment by dgibbs64** [comment]
@Frisasky Are you happy this is now resolved or is this still an issue? hotfix v19.12.4 should have resolved the issue.

**Comment by Frisasky** [comment]
the original issuer reports it fixed after tweak the config file, so i wont gonna pursuit the issue further
