### ISSUE TITLE
Call of duty 2 download problem

### ISSUE THREAD

**Issue by djtech2k** [GameServerManagers/LinuxGSM#2638]
I just did the install for a COD2 server.  Initially, the curl download of the server executable failed, so I found it and put it in manually.  Now it tries to run the server but its says unable to start Linuxgsm and the subject is the entry in the log.

How can I resolve this so that it will run?

**Comment by djtech2k** [comment]
Here is what is displayed in the SSH console:

[ .... ] Starting cod2server: LinuxGSMfailed to connect to server: Connection refused
[ FAIL ] Starting cod2server: Unable to start LinuxGSM

**Comment by Frisasky** [comment]
can you remove all files and try again?

**Comment by Frisasky** [comment]
and if possible, can you post the curl error?

**Comment by djtech2k** [comment]
Well when the curl failed to get the game server executable, I put it in place manually and fixed the permission/ownership.  I then ran the install again to make sure it was all right.  That is the result of when I run the star command.

The curl error happened on the install part but I am pretty sure that it said that it could not connect to server, or something very close to that.  I suspected that the path it was expecting to find the gameserver files was not there, but that was an assumption.

**Comment by djtech2k** [comment]
Here is the curl section:

Installing Call of Duty 2 Server
=================================
                                           curl: (7) couldn't connect to host
downloading cod2-lnxded-1.3-full.tar.bz2...OK
extracting cod2-lnxded-1.3-full.tar.bz2...OK

**Comment by djtech2k** [comment]
I just confirmed that the server files link times out.  I checked the file install_server_files.sh and found the link to the COD2 files: http://files.linuxgsm.com/CallOfDuty2/cod2-lnxded-1.3-full.tar.bz2.  If I try that manually, it times out.

**Comment by Frisasky** [comment]
i have no problem download the file package, can you ping the domain of file server and post the result? the location and provider of server? 
if the server is unreachable, can you post the dns server of the server?

**Comment by djtech2k** [comment]
I did a ping with my desktop and with my server in the datacenter.  Both get name resolution for the domain but no ping response.  I also tried the URL from my phone with wifi disabled and it also failed.  I tried a port connection check from my desktop to port 80 on that domain and it also failed.

**Comment by djtech2k** [comment]
Oh and on my server, the first nameserver in resolv.conf is 8.8.8.8, which is google, I believe.

**Comment by Frisasky** [comment]
seems there's problem accessing the file server from your end, i would notify the server owner about this

**Comment by Frisasky** [comment]
btw one last thing, could you do a traceroute to the file server?

**Comment by djtech2k** [comment]
I am unable to connect to that fileserver from my server, work computer, and my phone.  All 3 are using different networks.  I am not sure what could be causing an issue from all 3 places.

So does Linuxgsm need to hit that same fileserver in order for it to start?  I mean if it fails to hit it to download the install files, then that shouldn't be a problem because I grabbed them from elsewhere and put them into place.  If it needs to reach back out to that server in order to start the server then I see where it will continue to be an issue.

I will check traceroute in just a minute.

**Comment by djtech2k** [comment]
Ok, so just as a test, I put in the fileserver IP into the firewall whitelist on the server.  I then tried wget to the COD2 file and it worked.  I am now re-running the install process.

So I would rather lock it down as much as I can.  I have no idea why it would need to be whitelisted in order to download.  What are the port connectivity requirements to that server during install and also just running/starting the server?

**Comment by djtech2k** [comment]
During install, it must need to connect to download the cod2 files.  That is done now.  So I am trying to determine if I can remove that from the firewall whitelist now or not.

My server is hosted in a datacenter so I should not need to do any port forwarding as long as the game port(s) are allowed.

**Comment by Frisasky** [comment]
yeah you can remove it after download, theres no need to access the file server unless you wanna reinstall it

**Comment by djtech2k** [comment]
Thanks.  

It does run now, but when I run the stop command, I get this error:

cod2server@vps2 [~]# ./cod2server stop
Warning! Missing dependencies: util-linux python3

Warning! cod2server does not have sudo access. Manually install dependencies.
        sudo yum install util-linux python3


I ran the yum command and the server says it has the latest util-linux installed and there is no python3 package available.

**Comment by Frisasky** [comment]
which version of centos youre running?

**Comment by djtech2k** [comment]
2.6.32-754.3.5.el6.i686

**Comment by Frisasky** [comment]
oh, lgsm only support centos 7 and 8, theres no python3 in centos 6's repo so this error would be expected
https://docs.linuxgsm.com/linux/distro

**Comment by Frisasky** [comment]
as long as you dont use monitor function you should be fine presumably
but i would still recommend running the server under centos 7 or 8 as they comes with much newer software thus better support for lgsm

**Comment by djtech2k** [comment]
Thanks.

A totally unrelated question...

How do I edit the server start command?  I see it in the _default file but that gets overwritten.  Other than modifying the original one that copies over it on startup, how can I customize the startup parameters?
