### ISSUE TITLE
7 days to die server stuck on no instance

### ISSUE THREAD

**Issue by dementedusa** [GameServerManagers/LinuxGSM#2648]
I have installed many lgsm servers and this issue is stumping me.  I follow the directions like normal and for some reason this server is just giving me a big pain in my rear.  when I start the server with the stock settings i get waiting for server instance, and it never changes, even after hours.  

https://hastebin.com/enilihikul

**Comment by dgibbs64** [comment]
Hi @dementedusa I recommend having a chat with people on the discord. It sounds like an issue specific to 7 Days to Die but it's hard to tell.

**Comment by h3o66** [comment]
I do not see here no issue, if there is any problem, please try to get help on the discord or reopen the issue.
