### ISSUE TITLE
Discord alert failing for csgo server

### ISSUE THREAD

**Issue by flashing1998** [GameServerManagers/LinuxGSM#2649]
Discord alert on my csgo server is failing, tried issuing a webhook but still can't fix it
error code:
[  OK  ] Postdetails csgoserver: Posting details to hastebin.com for 30D
Please share the following url for support: https://hastebin.com/<!DOCTYPE html>
<html>
<head>
width=device-width, initial-scale=1

<title>Application Error</title>

                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
</head>
<body>

</body>
</html>
[ .... ] Alert csgoserver: Sending Discord alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 38, column 8
[ FAIL ] Alert csgoserver: Sending Discord alert: {"message": "400: Bad Request", "code": 0}

**Comment by dgibbs64** [comment]
Ongoing issue with using hastebin. Alternatives are currently being investigated

https://github.com/GameServerManagers/LinuxGSM/issues/2125

**Comment by dgibbs64** [comment]
thanks for raising this.

**Comment by RetroZA** [comment]
Hi im getting this error with my current csgo server, any fixes?

**Comment by kb1900** [comment]
also getting the same error:

[ .... ] Sending Alert cod2server: Sending Discord alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 11, column 39
[ FAIL ] Sending Alert cod2server: Sending Discord alert: {"message": "400: Bad Request", "code": 0}

Have even tried reinstalling the entire gameserver.

**Comment by dgibbs64** [comment]
@kb1900 please raise a new issue for this as it this is a closed issue. Thanks
