### ISSUE TITLE
Wurm server is broken

### ISSUE THREAD

**Issue by matthewearl00** [GameServerManagers/LinuxGSM#2652]
Was discussing this on Discord. Could not get ./wurmserver start to function at all. Would fail immediately. After looking at the code and looking at the java implementation, I found the issue. I have tried 3 os'es and 5 machines. The prerequisite of openjfx was not installed hence the java would fail the gui renderer. Please fix in a new patch.

**Comment by dgibbs64** [comment]
just to confirm wurm has a missing dependency of `openjfx`?

**Comment by matthewearl00** [comment]
Actually installing openjfx seemed to make it run, but after a while in ubuntu it would crash. In debian with exact same installation process, it would stay running but could not connect to the server. After more trial and error I installed libswt-gtk-3-java xvfb before executing ./wurmserver install. When I did this, the headless worked and the server is now up and running fine.

So basically my env was ubuntu 16.04 as recommended, installed as per directions BEFORE running ./wurmser install, then did sudo apt-get install libswt-gtk-3-java xvfb as was instructed in the wurmpedia. Link below. I did not have to set the environment using export or set xvfb: 99, as it was adjusted with the LinuxGSM script. It now works fine using my method.

https://www.wurmpedia.com/index.php/Server_administration_(Wurm_Unlimited)

**Comment by matthewearl00** [comment]
So to clarify, the openjfx installs some requisites needed but seemed to bork something. The javaJFX WAS needed but is satisfied by a simpler libswt-gtk-3-java.

**Comment by dgibbs64** [comment]
tested I am unable to get it started myself

**Comment by h3o66** [comment]
@matthewearl00 can you maybe test the connected PR ?
