### ISSUE TITLE
SAMP Server Abhängigkeiten für Debian 8 und höher (linuxgsm)

### ISSUE THREAD

**Issue by Domse93** [GameServerManagers/LinuxGSM#2653]
Es können einige Pakete nicht geladen werden oder werden gefunden bei den Abhängigkeiten vom samp Server Installations Script für Debian 8 und höher.

Hier die Dateien die nicht geladen oder Installiert werden können:
```
E: Unable to locate package datei
E: Unable to locate package entpacken
E: Unable to locate package ca-zertifikate
E: Unable to locate package libstdc
E: Unable to locate package +
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '+'
E: Unable to locate package 6
E: Unable to locate package libstdc
E: Unable to locate package +
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '+'
E: Unable to locate package 6
E: Unable to locate package i386
```
Wenn das korrigiert und Installatins tauglich gemacht werden könnte und auch auf Debian 10 Aktualisiert werden könnte währe supper.

Translation 

Some packages cannot be loaded or are found in the dependencies on the samp server installation script for Debian 8 and higher.

Here are the files that cannot be loaded or installed:
```
E: Unable to locate package file
E: Unable to unpack locate package
E: Unable to locate package ca certificates
E: Unable to locate package libstdc
E: Unable to locate package +
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '+'
E: Unable to locate package 6
E: Unable to locate package libstdc
E: Unable to locate package +
E: Regex compilation error - Invalid preceding regular expression
E: Couldn't find any package by regex '+'
E: Unable to locate package 6
E: Unable to locate package i386
```
If this could be fixed and installations made usable and upgraded to Debian 10, supper would be

**Comment by dgibbs64** [comment]
something looks very broken with your server install as it has split up the dependency names. for example libstdc++6:i386 is a single dependency but it has split this into several words `libstdc` `+` `+` `6` `:i386`. I dont think there is anything we can do with this one.
