### ISSUE TITLE
long command execution

### ISSUE THREAD

**Issue by starcevpro** [GameServerManagers/LinuxGSM#2654]
При выполнении команды двухминутное ожидание, затем эта ошибка и команда работает....
![image](https://user-images.githubusercontent.com/24702947/70869354-233fd800-1f9b-11ea-8b89-8323e97a5bd7.png)

Translation

When the command is executed, it waits two minutes, then this error and the command works ....

**Comment by h3o66** [comment]
> При выполнении команды двухминутное ожидание, затем эта ошибка и команда работает....

Can you maybe write this in english what problem you have ?

**Comment by dgibbs64** [comment]
please make sure that LinuxGSM is fully updated `./sampserver update-lgsm`

**Comment by h3o66** [comment]
As i do not see here any change within a long time i will close this issue.
We do not have more info to debug this or have a better look at the problem
