### ISSUE TITLE
ARK Server Config Syntax Errors

### ISSUE THREAD

**Issue by jaredstone1982** [GameServerManagers/LinuxGSM#2657]
Greetings,

The following issue stems from myself wanting to cluster out a working server. I followed the instructions as per the website and now the server starts, but with weird synax errors being displayed and the information that Steam pulls is incorrect. I've made several search queries, posts on various sites, and have attempted to update LGSM without success. Separately, I've also removed all configurations made for clusters and defaulted back to the original config file, same exact errors; and, when the server starts it shows everything is correct on Steam except the map is "ShooterEntry".

I've tried to include as much information as I could below.

Config files:

> _default.cfg: [https://pastebin.com/y3vQgfeX](url)
> common.cfg: [https://pastebin.com/dWpz9qY2](url)
> arkserver.cfg: [https://pastebin.com/h9xHM1q2](url)
> arkserver-2.cfg: [https://pastebin.com/5rSWaUc9](url)

Below is displayed after any command is entered from the command-line, before that command fully runs:
```
/home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 6: $'\r': command not found
/home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 8: $'\r': command not found
/home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 17: $'\r': command not found
/home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 19: syntax error near unexpected token `$'{\r''
'home/arkserver/lgsm/config-lgsm/arkserver/arkserver.cfg: line 19: `fn_parms(){
: integer expression expecteds/info_messages.sh: line 631: [: 7777
```
Results of **./arkserver postdetails**
[K[ .... ] Postdetails arkserver: Posting details to hastebin.com
[K[[32m  OK  [0m] Postdetails arkserver: Posting details to hastebin.com for 30D
Please share the following url for support: https://hastebin.com/<!DOCTYPE html>
```
<html>
<head>
width=device-width, initial-scale=1

<title>Application Error</title>

		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
</head>
<body>

</body>
</html>
```
Results of **./arkserver details**
> [93mDistro Details[0m
> =======================================================================================
> [94mDistro:    [0mUbuntu 18.04.3 LTS
> [94mArch:      [0mx86_64
> [94mKernel:    [0m4.15.0-72-generic
> [94mHostname:  [0mubuntu_lts
> [94mUptime:    [0m0d, 0h, 28m
> [94mtmux:      [0mtmux 2.6
> [94mglibc:     [0m2.27
> 
> [93mServer Resource[0m
> =======================================================================================
> [93mCPU         [0m
> [94mModel:      [0mIntel(R) Xeon(R) CPU           E5645  @ 2.40GHz
> [94mCores:      [0m4
> [94mFrequency:  [0m2394.000MHz
> [94mAvg Load:   [0m0.04, 0.16, 0.36
> 
> [93mMemory     [0m
> [94mMem:       [94mtotal  used   free   cached  available[0m
> [94mPhysical:  [0m32GB   4.1GB  27GB   2.6GB   27GB[0m
> [94mSwap:      [0m8.0GB  0B     8.0GB[0m
> 
> [93mStorage[0m
> [94mFilesystem:  [0m/dev/sda2
> [94mTotal:       [0m118G
> [94mUsed:        [0m31G
> [94mAvailable:   [0m82G
> 
> [93mNetwork[0m
> [94mIP:           [0m0.0.0.0
> [94mInternet IP:  [0m71.238.192.34
> 
> [93mGame Server Resource Usage[0m
> =======================================================================================
> [94mCPU Used:  [0m0%[0m
> [94mMem Used:  [0m0%  0MB[0m
> 
> [93mStorage[0m
> [94mTotal:        [0m16G
> [94mServerfiles:  [0m14G
> [94mBackups:      [0m20K
> 
> [92mARK: Survival Evolved Server Details[0m
> =======================================================================================
> [94mServer name:    [0mHis & Hers
> [94mServer IP:      [0m0.0.0.0
> :7777
> [94mInternet IP:    [0mOMITTED:7777
> [94mMaxplayers:     [0m70
> [94mDefault map:    [0mValguero_P
> [94mMaster server:  [31mfalse[0m
> [94mStatus:         [31mOFFLINE[0m
> 
> [92markserver Script Details[0m
> =======================================================================================
> [94mScript name:            [0markserver
> [94mLinuxGSM version:       [0mv19.12.5
> [94mglibc required:         [32m2.15[0m
> [94mDiscord alert:          [0moff
> [94mSlack alert:            [0moff
> [94mEmail alert:            [0moff
> [94mPushbullet alert:       [0moff
> [94mIFTTT alert:            [0moff
> [94mMailgun (email) alert:  [0moff
> [94mPushover alert:         [0moff
> [94mTelegram alert:         [0moff
> [94mUpdate on start:        [0moff
> [94mUser:                   [0markserver
> [94mLocation:               [0m/home/arkserver
> [94mConfig file:            [0m/home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
> 
> [92mBackups[0m
> =======================================================================================
> No Backups created
> 
> [92mCommand-line Parameters[0m
> =======================================================================================
> ./ShooterGameServer "Valguero_P
> ?AltSaveDirectoryName=Valguero_P
> ?listen?MultiHome=0.0.0.0
> ?MaxPlayers=70
> ?QueryPort=27015
> ?RCONPort=27020
> ?Port=7777
>  -automanagedmods"
> 
> [92mPorts[0m
> =======================================================================================
> [94mChange ports by editing the parameters in:[0m
> /home/arkserver/lgsm/config-lgsm/arkserver
> 
> [94mUseful port diagnostic command:[0m
> netstat -atunp | grep ShooterGame
> 
> [94mDESCRIPTION  DIRECTION  PORT   PROTOCOL[0m
> > Game       INBOUND    7777
>    udp
> > Query      INBOUND    27015
>   udp
> > RCON       INBOUND    27020
>   tcp
> 
> [94mStatus:	[31mOFFLINE[0m

**Comment by dgibbs64** [comment]
The issue looks like you are using Windows Line endings and not Linux line endings. Ensure your text editor is set up for this.

https://dev-docs.linuxgsm.com/code-standards/text-editor-settings#line-ending

**Comment by jaredstone1982** [comment]
That did it, thank you very much. Learned something new today.
