### ISSUE TITLE
Dont Starve Together Server Install Failure

### ISSUE THREAD

**Issue by MMoudry3** [GameServerManagers/LinuxGSM#2660]
#  User Story

I am installing a clean Don't Starve Together server. During the install when the section 'Downloading Don't Starve Together Configs' is reached the following errors are shown :
```
Downloading Don't Starve Together Configs
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
    fetching cluster.ini...OK
    fetching server.ini...OK
copying cluster.ini config file.
'/home/dstserver/lgsm/config-default/config-game/cluster.ini' -> '/home/dstserver/.klei/DoNotStarveTogether/Cluster_1/cluster.ini'
cp: cannot create regular file '/home/dstserver/.klei/DoNotStarveTogether/Cluster_1/cluster.ini': No such file or directory
copying server.ini config file.
mkdir: cannot create directory ‘/Master’: Permission denied
'/home/dstserver/lgsm/config-default/config-game/server.ini' -> '/Master/server.ini'
cp: cannot create regular file '/Master/server.ini': No such file or directory
grep: /home/dstserver/.klei/DoNotStarveTogether/Cluster_1/cluster.ini: No such file or directory
cluster.ini is already configured.
sed: can't read /Master/server.ini: No such file or directory
sed: can't read /Master/server.ini: No such file or directory
changing shard name.
sed: can't read /Master/server.ini: No such file or directory
changing master setting.
sed: can't read /Master/server.ini: No such file or directory
```

## Basic info

* **Distro:** Ubuntu 18.04
* **Game:** Don't Starve Together
* **Command:** ./dstserver install
* **LinuxGSM version:** v19.12.5

## Further Information

It seems that the script attempts to create a directory on the root of the filesystem /Master instead of creating a directory in the user directory ./Master

## To Reproduce

1. Follow the installation instructions at https://linuxgsm.com/lgsm/dstserver/
2. The bug is shown when reaching the 'Downloading Don't Starve Together Configs'

## Expected behavior
The configs are downloaded without issue.

**Comment by dgibbs64** [comment]
DST is a candidate for unit testing as its a more complex server and more likey to break. This issue will be investigated as a priority for next release

**Comment by dgibbs64** [comment]
I have discovered the issue clustercfgdir is called after servercfgdir that requires the clustercfgdir variable

```
servercfg="server.ini"
servercfgdir="${clustercfgdir}/${shard}"
servercfgfullpath="${servercfgdir}/${servercfg}"
servercfgdefault="server.ini"
clustercfg="cluster.ini"
clustercfgdir="${persistentstorageroot}/${confdir}/${cluster}"
clustercfgfullpath="${clustercfgdir}/${clustercfg}"
clustercfgdefault="cluster.ini"
```

as a temporary fix this copy the following into common.cfg
```
clustercfgdir="${persistentstorageroot}/${confdir}/${cluster}"
servercfgdir="${clustercfgdir}/${shard}"
```

This issue will be fixed for next release

**Comment by Talkarcabbage** [comment]
Workaround incomplete. `clustercfgfullpath` and `servercfgfullpath` depend on `clustercfgdir` and `servercfgdir` and must also be defined in common. Add them below definitions in the previous comment. 
```
clustercfgdir="${persistentstorageroot}/${confdir}/${cluster}"
servercfgdir="${clustercfgdir}/${shard}"
servercfgfullpath="${servercfgdir}/${servercfg}"
clustercfgfullpath="${clustercfgdir}/${clustercfg}"
```
