### ISSUE TITLE
[Server Request] Chivalry: Medieval Warfare

### ISSUE THREAD

**Issue by aardvarkk** [GameServerManagers/LinuxGSM#2662]
## What game server would you like adding?

Chivalry: Medieval Warfare

## Can you link to any tutorials or guides?

I think most of the work has already been done to get this working. I followed the instructions here: https://forums.tornbanner.com/topic/21416/native-linux-server-available

You already have #419 but it's locked so I couldn't comment on it. One thing to note is that the PhysXUpdater error that appears is not actually an error! I believe the server is running after that. I managed to get a client to connect to the server by just running "Open MYIPADDR:7000" in the console. It would be nice to get "official" support for this even though it's not too hard to get it running manually.

Here's a quote from that page:

> THERE’S SOME SCARY LOG OUTPUT HAPPENING
> This is what you should expect to see after launching the server:
> 
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> Setting breakpad minidump AppID = 219640
> Loading library: libPhysXCooking.so
> Result of loading library libPhysXCooking.so: 0xaa0e780
> Loading library: PhysXUpdateLoader.so
> ERROR: PhysXUpdateLoader.so: cannot open shared object file: No such file or directory
> Result of loading library PhysXUpdateLoader.so: 0x0
> Loading library: libPhysXCore.so
> Result of loading library libPhysXCore.so: 0xaa0e500
> Yes, libPhysXCore and libPhysXCooking won’t load. Don’t need them. Yes, SteamAPI_Init() will initially spit out a fail; that’s something Steam-related, it will succeed the second time but doesn’t log anything for success.

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

220070

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by h3o66** [comment]
I currently set up a testing branch:
https://github.com/h3o66/LinuxGSM/tree/feature/chivalry

If you have time please test this.

**Comment by h3o66** [comment]
update: did a rebase on my branch and reworked the fix a bit. Will then create then soon the pull request

**Comment by h3o66** [comment]
so here we go - pull request opened :tada:

**Comment by h3o66** [comment]
~Closed
new server in version 20.3.0 included
