### ISSUE TITLE
New ArkServer (304.41) Version not available

### ISSUE THREAD

**Issue by pleinx** [GameServerManagers/LinuxGSM#2664]
Someone else cant update to next ArkServer Version?
I tried `./arkserver fu`, `./arkserver uf` and also `./arkserver update` but my server version is still 304.22.

**Comment by h3o66** [comment]
This is imho not a lgsm issue as the depot is manged by the gamedev and not by anyone from this project afaik.

You can get here more info when the server was updated the last time:
https://steamdb.info/app/376030/depots/?branch=public
