### ISSUE TITLE
Update command doesn't respect changes to branch config

### ISSUE THREAD

**Issue by da-moo** [GameServerManagers/LinuxGSM#2670]
## Basic info

* **Distro:** Fedora 31
* **Game:** Garry's Mod
* **Command:** Update
* **LinuxGSM version:** v19.12.5

## Further Information

I downloaded and attempted to start Garry's Mod on the default public branch. Then in `config/config-lgsm/gmodserver/common.cfg`, I set `branch="x86-64"` to try the new 64-bit branch. I then ran the `update` command, where LGSM said that my build number matched the desired one (it did not, it still matched public). I used `force-update` to pull the branch, which worked. I then ran `update` again, but LGSM complained that I had a version mismatch, and attempted to update to the latest public branch build again. I confirmed using the `details` command that LGSM is correctly detecting the brach I set.

`./gmodserver details`:
```
Garry's Mod Server Details
=====================
Server name:      Gmod Server
Branch:           x86-64
```

`./gmodserver update` after `force-update`:
```
$ ./gmodserver u
[  OK  ] Update gmodserver: Checking for update: SteamCMD

Update available
* Local build: 4555659
* Remote build: 4377587
https://steamdb.info/app/4020/

^Cplying update...
```

The local build is correct, the remote build is incorrect and still points to the latest build on `public`

**Comment by h3o66** [comment]
for some reason i could reproduce the problem with a old steamcmd version that was upgraded.
For this problem I deleted the steamcmd folder and tried the update again and it worked.

Pls try this and report back.

**Comment by h3o66** [comment]
~ closed
No answer after more than a month.
Also the latest updates of LGSM should have solved this.
If the latest updates did not solve it, pls reopen ths issue.
