### ISSUE TITLE
Refactor <serverName> dt/ details

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#2671]
I am producing a web app using LGSM to contol games
currently I am refactoring the ouput from the dt command most of the output works fine 
as I'm splitting the string  around the **:**  character to produce the array E.G
                Key                           value
   LinuxGSM version:             v19.12.5
this works fine in most cases and most other outputs are easy enough to create a key for with the exception of this part 
mcserver outputs
`
> Game       INBOUND    25565  tcp
> Query      INBOUND    25565  udp
> Rcon       INBOUND    25575  tcp`

however most other games output like
`
> Game/RCON  INBOUND    27016  tcp/udp
> SourceTV   INBOUND    27021  udp
< Client     OUTBOUND   27006  udp`

the easy fix is to add **:**'s after the title  and remove the > and <
any thoughts ?

**Comment by dgibbs64** [comment]
Sorry for the slow response. I can see no issue with removing the `<` & `>` from that. Not quite sure what you mean by `:'s` though. Also im guessing you are using the `ansi=off` setting.

**Comment by JimTR** [comment]
the code currently reads
`DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27017  tcp/udp
> SourceTV   INBOUND    27022  udp
< Client     OUTBOUND   27007  udp
`
coud it read 
`DESCRIPTION  DIRECTION  PORT   PROTOCOL
 Game/RCON:  INBOUND    27017  tcp/udp
 SourceTV:   INBOUND    27022  udp
 Client:     OUTBOUND   27007  udp
`
notice the :'s added to the line

**Comment by dgibbs64** [comment]
I have refactored port detection with the most recent update. this should help with this issue
