### ISSUE TITLE
csgo 

### ISSUE THREAD

**Issue by QAQsohard** [GameServerManagers/LinuxGSM#2672]
[csgoserver@iZ0jymoj7smizbZ ~]$ ./csgoserver install
    fetching core_trap.sh...OK
    fetching _default.cfg...OK
    copying _default.cfg...OK
    fetching common.cfg...OK
    fetching csgoserver.cfg...OK
    fetching linuxgsm.sh...OK
    fetching core_getopt.sh...FAIL
https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/functions/core_getopt.sh

how to deal with :D

**Comment by h3o66** [comment]
Did you try this only one time ?
There is not to much info for a further problem analysis.
Maybe someone on the discord can help you.

**Comment by Frisasky** [comment]
theres no response from @QAQsohard for 2 months so i would gonna close this issue
