### ISSUE TITLE
Gold Source Maxplayer defaulting to 6 player slots

### ISSUE THREAD

**Issue by uGamers** [GameServerManagers/LinuxGSM#2673]
## Basic info

* **Distro:** [Ubuntu 16.04]
* **Game:** [Cstrike]
* **Command:** [Monitor] game dig
* **LinuxGSM version:** [v12.34.56]

## Further Information

Server will default to 6 max players after 4-8 hours.

If I hardcode maxplayers to 32 not seeing it happen so far.

I’ll provide more info when I get home.

Anyone else see this happen before I rebuild everything lol

**Comment by uGamers** [comment]
Hardcoding Maxplayers seem to fix the problem don't know why but did.

`## Server Start Settings | https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters
ip="192.223.26.205"
port="27015"
clientport="27005"
defaultmap="de_dust2"
maxplayers="32"
displayip="192.223.26.205"

## Server Start Command | https://github.com/GameServerManagers/LinuxGSM/wiki/Start-Parameters#additional-parameters
fn_parms(){
parms="-game cstrike -strictportbind +ip ${ip} -port ${port} +clientport ${clientport} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers 32"
}
`

**Comment by dgibbs64** [comment]
Unable to replicate this issue. I will close
