### ISSUE TITLE
Incorrect dependency installation instructions for CentOS 8

### ISSUE THREAD

**Issue by Nuc1eoN** [GameServerManagers/LinuxGSM#2674]
The current instructions on the website look like this:
```
yum install mailx postfix curl wget tar bzip2 gzip unzip python binutils bc jq tmux glibc.i686 libstdc++ libstdc++.i686
```
However on CentOS 8 there is no `python` package. It should probably be replaced by `python3` which worked for me.

I realize that for CentOS 7 `python` is a valid package. So maybe there should be a new tab for CentOS 8 or a different soltution.

**Comment by h3o66** [comment]
Looks like this is a website only issue.
Maybe we just abdon soon centos 6 for lgsm then we could set for centos then python3 as defaul on the website.

**Comment by dgibbs64** [comment]
fixed
