### ISSUE TITLE
FR: Discord push alerts for when a new version of game server is available

### ISSUE THREAD

**Issue by EugeneGGHQ** [GameServerManagers/LinuxGSM#2676]
Ideally, I'd like to know about the availability of a new SteamCMD version of a game soon after it is published. 

If there was a way to have LGSM check to ensure that versions are concurrent that didn't mean having to manually type:

./servername u

To check this, or to rely on hearing reports from users that the server is out of date, it would allow our administrators to quickly update the server shortly after the availability of the latest version.

**Comment by TheGunter24** [comment]
you could make a "monitor" crontab every like 15 min + set the discord notification (&optinal autoupdate setting) and / or use https://top.gg/bot/patchbot to get game update news and then manually update ^^

**Comment by UltimateByte** [comment]
You already can in multiple ways
https://docs.linuxgsm.com/alerts
https://docs.linuxgsm.com/configuration/cronjobs
