### ISSUE TITLE
ts3server start error

### ISSUE THREAD

**Issue by neploho** [GameServerManagers/LinuxGSM#2679]
Feb 01 10:05:14.968 ts3server: START: FATAL: Unable to start TeamSpeak 3 Server
Feb 01 10:05:14.974 ts3server: START: FATAL: command_start.sh exiting with code: 1

ts3server@cs74:~$ ./ts3server st
[ .... ] Starting ts3server: glibc[ERROR ] Starting ts3server: glibc requirement unknown
[ .... ] Starting ts3server: Checking for log files[ INFO ] Starting ts3server: Checking for log files: Creating log files
installing log dir: /home/ts3server/log...OK
installing LinuxGSM log dir: /home/ts3server/log/script...OK
creating LinuxGSM log: /home/ts3server/log/script/ts3-server-script.log...OK
creating symlink to game log dir: /home/ts3server/log/server -> /home/ts3server/serverfiles/logs...OK
[ .... ] Starting ts3server: Check IP[ INFO ] Starting ts3server: Check IP: 192.168.1.20
[ .... ] Starting ts3server: TeamSpeak 3 Server/home/ts3server/lgsm/functions/command_start.sh: line 38: fn_parms: command not found
touch: cannot touch ‘’: No such file or directory
failed to connect to server: Connection refused
[ FAIL ] Starting ts3server: Unable to start TeamSpeak 3 Server

**Comment by h3o66** [comment]
please update lgsm.
`./ts3server update-lgsm`

and then try again

**Comment by neploho** [comment]
same error:

ts3server@cs74:~$ ./ts3server update-lgsm
[ .... ] Update LinuxGSM ts3server: Updating LinuxGSM
    checking function alert.sh...OK
    checking function check_config.sh...OK
    checking function check_deps.sh...OK
    checking function check_executable.sh...OK
    checking function check_glibc.sh...OK
    checking function check_ip.sh...OK
    checking function check_logs.sh...OK
    checking function check_permissions.sh...OK
    checking function check_root.sh...OK
    checking function check.sh...OK
    checking function check_status.sh...OK
    checking function check_system_dir.sh...OK
    checking function check_system_requirements.sh...OK
    checking function check_tmuxception.sh...OK
    checking function command_details.sh...OK
    checking function command_install.sh...OK
    checking function command_monitor.sh...OK
    checking function command_restart.sh...OK
    checking function command_start.sh...UPDATE
    fetching command_start.sh...OK
    checking function command_stop.sh...OK
    checking function command_update_functions.sh...OK
    checking function command_update_linuxgsm.sh...OK
    checking function command_update.sh...OK
    checking function core_dl.sh...OK
    checking function core_exit.sh...OK
    checking function core_functions.sh...OK
    checking function core_getopt.sh...OK
    checking function core_legacy.sh...OK
    checking function core_messages.sh...OK
    checking function core_trap.sh...OK
    checking function fix.sh...OK
    checking function info_config.sh...OK
    checking function info_distro.sh...OK
    checking function info_messages.sh...OK
    checking function info_parms.sh...OK
    checking function install_complete.sh...OK
    checking function install_config.sh...OK
    checking function install_header.sh...OK
    checking function install_logs.sh...OK
    checking function install_server_dir.sh...OK
    checking function install_server_files.sh...OK
    checking function install_ts3db.sh...OK
    checking function logs.sh...OK
    checking function query_gamedig.sh...OK
    checking function update_steamcmd.sh...OK
    checking function update_ts3.sh...OK
[  OK  ] Update LinuxGSM ts3server: Updating functionsts3server@cs74:~$
ts3server@cs74:~$ ./ts3server start
[ .... ] Starting ts3server: glibc[ERROR ] Starting ts3server: glibc requirement unknown
[ .... ] Starting ts3server: Checking for log files[ INFO ] Starting ts3server: Checking for log files: Creating log files
installing log dir: /home/ts3server/log...OK
installing LinuxGSM log dir: /home/ts3server/log/script...OK
creating LinuxGSM log: /home/ts3server/log/script/ts3-server-script.log...OK
creating symlink to game log dir: /home/ts3server/log/server -> /home/ts3server/serverfiles/logs...OK
[ .... ] Starting ts3server: Check IP[ INFO ] Starting ts3server: Check IP: 192.168.1.20
[ .... ] Starting ts3server: TeamSpeak 3 Server/home/ts3server/lgsm/functions/command_start.sh: line 38: fn_parms: command not found
touch: cannot touch ‘’: No such file or directory
failed to connect to server: Connection refused
[ FAIL ] Starting ts3server: Unable to start TeamSpeak 3 Server

**Comment by h3o66** [comment]
Did you modify any config files ?
If you did please attach these to the issue, thanks
If needed you can mask passwords or other sensitive data.

neploho <notifications@github.com> schrieb am Di., 4. Feb. 2020, 16:54:

**Comment by neploho** [comment]
No, the files have not been modified. On Saturday, after almost two years of operation, the server stopped starting. I can attach the necessary files if you tell me which ones are needed.

**Comment by h3o66** [comment]
this looks somehow rly strange to me:

> 38: fn_parms: command not found
> touch: cannot touch ‘’: No such file or directory
> failed to connect to server: Connection refused

Can you provide overall more info about the server and the teamspeak server version ?
Also attach maybe the logfiles from the teamspeak server for the crash.
