### ISSUE TITLE
[GMOD] SRCDS Console Scroll Up

### ISSUE THREAD

**Issue by MyDimeIsUp** [GameServerManagers/LinuxGSM#2680]
## User Story
When attempting to scroll up using my SSH program (MobaXTerm) I can't see previous outputs by SRCDS. When scrolling up, all I see is previous outputs from my ubuntu session

## Basic info

* Distro: [Ubuntu 18.04]
* Game: [Garry's Mod]
* Command: [console]

## Further Information
![Image without scrolled up](https://i.imgur.com/eufr1ta.png)
![Image of Console scrolled up](https://i.imgur.com/Wj8IX4T.png)

## To Reproduce

Steps to reproduce the beha`viour:
1. /[servername] c
2. Attempt to scroll up using your SSH program

## Expected behaviour
To scroll up to previous console ouputs by SRCDS

ALSO TO ADD TO THIS: This is a LinuxGSM issue no matter what @Bourne-ID said in my last report. I tried it in multiple SSH programs, all showing the same issue. Here it is also in PuTTY.
![image](https://user-images.githubusercontent.com/8619739/73623636-9d8bf080-460b-11ea-8f2f-fb73112775b0.png)

**Comment by MyDimeIsUp** [comment]
EDIT: After doing a quick search in the repository, I found that it uses tmux. I found the solution here: https://superuser.com/questions/209437/how-do-i-scroll-in-tmux

However is it possible for the team here to add a patch for easy scrolling in the console?

**Comment by h3o66** [comment]
I am not sure if this is in the scope of lgsm to fix this or modify user or system configs.
Anyone else has a opinion about this ?

**Comment by dgibbs64** [comment]
As per @h3o66 This is something that is tmux specific and out of scope. Thank you
