### ISSUE TITLE
Unturned - Servername and Maxplayers settings are ignored.

### ISSUE THREAD

**Issue by billthecatt** [GameServerManagers/LinuxGSM#2681]
The servername and maxplayers as documented in the lgsm folder aren't being functional at the moment.  Instead the server admin still has to edit:

/untserver/serverfiles/Servers/untserver/Server/Commands.dat as follows:
name servnameXYZ
maxplayers 24

Otherwise the /untserver details command list a maxplayers and a hsotname that the server instance itself appears to just ignore, 

Hope this helps some other hapless unturned server admin. (And also that the details in unturned.cfg get implemented into Commands.dat somehow.)

**Comment by h3o66** [comment]
well actually the support for unturned should be reworked for lgsm
offical doc for the server:
https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md

**Comment by dgibbs64** [comment]
Looks like the changes involve moving stuff more from start parameters to config files

**Comment by Claiyc** [comment]
> Seems like nothing works now.. Read (Ports are ignored too)
> 
> CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015
> 
> [p.ip.fi/UoAK](https://p.ip.fi/UoAK)
> 
> "not really your issue I have no idea where these values are in and what config files.."

Please open a new discussion or join our discord server regarding your problem: http://linuxgsm.com/discord
