### ISSUE TITLE
Issue CSGO-Server Validating Steam CMD 

### ISSUE THREAD

**Issue by HerzGegenFame** [GameServerManagers/LinuxGSM#2683]
Hello, since my Servers won´t start anymore i wanted to validate them.
but i always encounter a Steam CMD issue:

`
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x5) validating, progress: 0.00 (0 / 23939808344)
 Update state (0x5) validating, progress: 0.35 (83826021 / 23939808344)
 Update state (0x5) validating, progress: 0.93 (222153088 / 23939808344)
 Update state (0x5) validating, progress: 1.32 (314957921 / 23939808344)
 Update state (0x5) validating, progress: 1.72 (411840909 / 23939808344)
 Update state (0x5) validating, progress: 2.34 (560704566 / 23939808344)
 Update state (0x5) validating, progress: 3.46 (827877370 / 23939808344)
 Update state (0x5) validating, progress: 4.24 (1015424414 / 23939808344)
 Update state (0x5) validating, progress: 4.98 (1192588512 / 23939808344)
 Update state (0x5) validating, progress: 5.65 (1352805041 / 23939808344)
 Update state (0x5) validating, progress: 6.25 (1495844433 / 23939808344)
 Update state (0x5) validating, progress: 6.89 (1650291084 / 23939808344)
 Update state (0x5) validating, progress: 7.62 (1823063693 / 23939808344)
 Update state (0x5) validating, progress: 8.27 (1979853023 / 23939808344)
 Update state (0x5) validating, progress: 8.93 (2139003008 / 23939808344)
 Update state (0x5) validating, progress: 9.66 (2313066624 / 23939808344)
 Update state (0x5) validating, progress: 10.30 (2466563316 / 23939808344)
 Update state (0x5) validating, progress: 10.68 (2556740852 / 23939808344)
 Update state (0x5) validating, progress: 11.33 (2711930100 / 23939808344)
 Update state (0x5) validating, progress: 12.07 (2890188020 / 23939808344)
 Update state (0x5) validating, progress: 12.74 (3050222817 / 23939808344)
 Update state (0x5) validating, progress: 13.32 (3187893703 / 23939808344)
 Update state (0x5) validating, progress: 13.91 (3330500039 / 23939808344)
 Update state (0x5) validating, progress: 14.52 (3476064702 / 23939808344)
 Update state (0x5) validating, progress: 15.01 (3593141490 / 23939808344)
 Update state (0x5) validating, progress: 15.98 (3825925362 / 23939808344)
 Update state (0x5) validating, progress: 16.58 (3968965236 / 23939808344)
 Update state (0x5) validating, progress: 17.44 (4176012081 / 23939808344)
 Update state (0x5) validating, progress: 18.38 (4400407345 / 23939808344)
 Update state (0x5) validating, progress: 19.05 (4560612959 / 23939808344)
 Update state (0x5) validating, progress: 19.59 (4690636383 / 23939808344)
 Update state (0x5) validating, progress: 20.38 (4879861533 / 23939808344)
 Update state (0x5) validating, progress: 21.18 (5070702365 / 23939808344)
 Update state (0x5) validating, progress: 22.01 (5269931805 / 23939808344)
 Update state (0x5) validating, progress: 22.74 (5443315908 / 23939808344)
 Update state (0x5) validating, progress: 23.28 (5573339332 / 23939808344)
 Update state (0x5) validating, progress: 23.86 (5712527266 / 23939808344)
 Update state (0x5) validating, progress: 24.21 (5796264517 / 23939808344)
 Update state (0x5) validating, progress: 24.96 (5976124776 / 23939808344)
 Update state (0x5) validating, progress: 25.59 (6126335382 / 23939808344)
 Update state (0x5) validating, progress: 26.43 (6327484305 / 23939808344)
 Update state (0x5) validating, progress: 27.10 (6487629822 / 23939808344)
 Update state (0x5) validating, progress: 27.81 (6656930853 / 23939808344)
 Update state (0x5) validating, progress: 28.71 (6872425315 / 23939808344)
 Update state (0x5) validating, progress: 29.25 (7003156083 / 23939808344)
 Update state (0x5) validating, progress: 29.87 (7151016980 / 23939808344)
 Update state (0x5) validating, progress: 30.55 (7314189037 / 23939808344)
 Update state (0x5) validating, progress: 31.27 (7486875270 / 23939808344)
 Update state (0x5) validating, progress: 31.82 (7618548431 / 23939808344)
 Update state (0x5) validating, progress: 32.43 (7763089683 / 23939808344)
 Update state (0x5) validating, progress: 33.05 (7911626690 / 23939808344)
 Update state (0x5) validating, progress: 33.84 (8101080474 / 23939808344)
 Update state (0x5) validating, progress: 34.58 (8279345258 / 23939808344)
 Update state (0x5) validating, progress: 35.14 (8412877218 / 23939808344)
 Update state (0x5) validating, progress: 35.76 (8560314826 / 23939808344)
./steamcmd.sh: line 38: 11828 Aborted                 (core dumped) $DEBUGGER "$STEAMEXE" "$@"
`

Is this a steamcmd or lgsm issue?

**Comment by UltimateByte** [comment]
Definitely SteamCMD issue.
Check your system updates, try to delete steam dirs to force updating it, and check available disk space.
If that is not enough, you can seek help on LinuxGSM's Discord.
Best of luck
