### ISSUE TITLE
Incorrect steam app id at linuxgsm.com/lgsm/ns2server/

### ISSUE THREAD

**Issue by GhoulofGSG9** [GameServerManagers/LinuxGSM#2685]
## User Story

As a new server operator interested in Natural Selection 2, I want to check out the latest updates of Natural Selection 2 via linuxgsm.com so that I can see if the game is still actively developed and worth hosting a server for.

## Basic info
**Website issue**

## Further Information

The website is linking to the NS2:Combat dedicated server app (313900) instead of the Natural Selection 2 Dedicated Server app (4940). Didn't find a bug tracker or reposotory for the website so hopefully posting the issue here is fine.

The linuxgsm install script is using the correct app id. So no need to panic ;)

## To Reproduce
Visit https://linuxgsm.com/lgsm/ns2server/ and check app id and steamdb.info links at the bottom of the compatibility tab.

## Expected behaviour
The mentioned app id should be 4940 and the links should direct to https://steamdb.info/app/4940/

**Comment by dgibbs64** [comment]
Fixed. Thanks
