### ISSUE TITLE
[MCBSERVER] Keep Minecraft Bedrock server running while backup is running.

### ISSUE THREAD

**Issue by emerysteele** [GameServerManagers/LinuxGSM#2686]
When doing ./mcbserver backup, the server is stopped, then started again once backup completes. For people that want to do backups multiple times a day, this can get quite annoying.

I understand the issues with data being written while backup is running & so forth. But Minecraft Bedrock has a command built in to stop writing to disk for this kind of use.

You would need to do '/save hold' in the game console. Do backup. Then do '/save resume' after backup is complete.

This would prevent the minecraft server from being restarted & kicking players off.

**Comment by dgibbs64** [comment]
I would recommend using another tool like rsync as the backup command is not designed to be a full backup solution. The backup command is due to be refactored and improved this year.

https://docs.linuxgsm.com/commands/backup#alternative-backup-methods
