### ISSUE TITLE
add timestamps to server logs

### ISSUE THREAD

**Issue by akariley** [GameServerManagers/LinuxGSM#2687]
As a server admin, I'd like the server logs to have timestamps added so I can determine what action happened when.

## Basic info

* **Distro:** [CentOS 7]
* **Game:** [Rust]
* **Command:** [N/A]
* **LinuxGSM version:** [v19.11.0]

## Further Information

Server logs would benefit from timestamps.

## Further Reading

N/A

**Comment by dgibbs64** [comment]
If the logs are lgsm related then they already have timestamps if they are rust logs then I have no control over them and you need to ask facepunch.
