### ISSUE TITLE
[Server Request] Battlefield Vietnam

### ISSUE THREAD

**Issue by Rookjee** [GameServerManagers/LinuxGSM#2691]
## What game server would you like adding?

Battlefield Vietnam

## Can you link to any tutorials or guides?

http://www.bf-games.net/downloads/491/bfv-dedicated-server-linux-v121.html
## Is the server on Steam?

* [ ] Yes
* [X] No

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [X] Yes
* [ ] No

**Comment by Frisasky** [comment]
i guess without any 3rd party master server these old binaries wont work due to gamespy shutdown?

**Comment by dgibbs64** [comment]
I have made the download available http://linuxgsm.download/BattlefieldVietnam/ so it just needs to be developed now
