### ISSUE TITLE
[Feature Request] Restart Server After Update 

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#2700]
#2669, #2025 Reference

## User Story

How I know. We can update CS:GO Servers without stop it.
So we can try update and only then restart server.

What we get? Maybe this is fix this bug - #2669 

## Basic info

Check #2669, #2025 for more details
Actualy, need only for CS:GO.
I don't know what about other games (source games too) 

## Further Information

So. Now sheme of work update will be like this:

- call **update** function.
- server (csgo) was start update.
- on end of update server get **restart** (or - when update is over - restart server)
- update was successfully complete.

So, **monitor** function can't broken this update of server. Why? Because in any check of monitor function, this func get success result (server was didn't stop while he update so ...) 

 **Questions?**

**Comment by dgibbs64** [comment]
monitor can not break an update as monitor will detect if an update is running and do nothing.
 as per this line in your log file proves.
```
Jan 07 06:05:07.076 csgoserver: MONITOR: ERROR: SteamCMD is currently checking for updates
```

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_monitor.sh#L36

It is generally a good idea to stop a server when it is updating. This may not be a problem for csgo specifically however there are over 100 game servers, some of which should be stopped before being updated.

**Comment by dgibbs64** [comment]
#2959 
will take no further action with this
