### ISSUE TITLE
Error on Loading Steam API.

### ISSUE THREAD

**Issue by cookyman1983** [GameServerManagers/LinuxGSM#2701]
German
Hi,
wenn ich mein 7days Server updaten möchte und ich folgenden befehl ausführe:

./sdtdserver force-update

erhalte ich denn unten genanten Fehler:

Englisch by google translate:
Hi,
if I want to update my 7days server and I execute the following command:

./sdtdserver force-update

I get the following error:

```
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
OK.
```

**Comment by Flaadder** [comment]
Hi,
die Fehler kannst du ignorieren. Er sollte trotzdem das Update machen. Der Server sollte sich trotzdem updaten und auch starten.

**Comment by h3o66** [comment]
@cookyman1983 Wenn hier der server nach dem update immernoch funktioniert, dann sollte es kein problem sein.
Das ist imho nur eine info das die SDL nicht gefunden wurde und der die prio für den Thread vom programm nicht setzen konnte.

Ich sehe hier kein problem - Falls es hier wirklich noch eins gibt, mach bitte den "issue" wieder auf.
