### ISSUE TITLE
No responded to the query

### ISSUE THREAD

**Issue by vikkise** [GameServerManagers/LinuxGSM#271]
Hi all!

Have installed cs 1.6 and made it work great for two weeks.
Today, my servers occasionally stopped responding. I can see on Steam Browser/fav list that my servers coming and going.

Installed according to http://danielgibbs.co.uk/lgsm/csserver/ and running three cs servers on debian 3.2.0-4-amd64

I have knowledge of networking and Linux so no problem to troubleshoot. Now I just run up and wonder if there is something known bug ?

Thanks!

**Comment by dgibbs64** [comment]
Nope not aware of any bugs. Sounds like an issue with your distro or the server rather than the script.

**Comment by dgibbs64** [comment]
Closing issue as no response and believe this is non script issue
