### ISSUE TITLE
[kfserver] query port scan fails and multiple ucc-bin-real programs gets started!

### ISSUE THREAD

**Issue by madfin** [GameServerManagers/LinuxGSM#273]
Hello. I encountered quite serious bug in kfserver. It crashed and failed to start because of malfunctioning KF Voting Handler mutator (Too many voting configs (11)).
http://forums.tripwireinteractive.com/showthread.php?t=42229

Because of this kfserver monitor failed in query port scan and restarted server. But for some reason old ucc-bin-real didn't die and was left hanging with ~300MB memory usage. When i noticed server was down, I had trouble getting contact to server through terminal SSH. When i finally got in, there was over 10 ucc-bin-real programs running and memory and CPU usage was peaked. If i had waited any longer server probably would have overloaded and crashed.

kfserver details show server running just fine.

**Comment by dgibbs64** [comment]
Please update your script to the newest version (just released) remove the functions dir and test again. The server monitor will simply restart the server so testing if stop works will help.

Please send me the output of ./kfserver details. and the output of ps -ef if it happens again to help me diagnose the issue.

I haven't ever had this issue myself.

**Comment by madfin** [comment]
Ok. I updated kfserver and functions and made it crash by adding couple votes. But no success on that monitor killing old ones. Command ./kfserver stop doesn't stop cronjob monitor from starting new ones. I have to kill manually all ucc-bin-reals runnig before monitor stops opening new ones.

I'm pretty sure you can test this malfunction yourself by using that voting mutator and add there many voting options. Number of maximum working votes differ from some reasons. Some people has added 17 votes with no problems. Maybe number of mutators used affects that matter.

Here are the outputs you wanted.

./kfserver details

Distro Details
=================================================================================
Distro:    Linux Mint 17.1 Rebecca
Arch:      x86_64
Kernel:    3.13.0-37-generic
Hostname:  serveri
tmux:      tmux 1.8
GLIBC:     2.19

Performance
=================================================================================
Uptime:    2d, 21h, 21m
Avg Load:  1,50, 1,00, 0,65

Mem:       total   used   free
Physical:  3,9G    3,7G   119M
Swap:      3,7G    31M    3,7G

Disk Usage
=================================================================================
Disk available:  Vapaa
169G
Serverfiles:     12G

Killing Floor Server Details
=================================================================================
Server name:  SS:2--Dead Space//Vehicle + Aliens//Mixed Custom --ScrN@lvl70-Slots-Turrets-Extra Perks...[FAST DL]
Server IP:    192.168.10.42:7710
Status:       ONLINE

Service name:  kf-server
User:          hr2
Location:      /home/hr2
Config file:   /home/hr2/serverfiles/System/kf-server.ini

Backups
=================================================================================
No Backups created

Command-line Parameters
=================================================================================
./ucc-bin server KF-FacingWorlds2.rom?game=KFBossSquad.BSGameType?VACSecured=true?Mutator=ServerPerksMut.ServerPerksMut,ScrnBalanceSrv.ScrnBalance,ScrnVotingHandlerV4.ScrnVotingHandlerMut,KFBossSquad.KFBossSquad,MutKillMessage.MutKillMessage,MutSlotMachine.MutSlotMachine,kiraRespawnv1.kiraRespawn,KFPatHPLeft.MutPatHPLeft,AdminPlus_v3.MutAdminPlus -nohomedir ini=kf-server.ini log=/home/hr2/log/server/kf-server-game.log

Ports
=================================================================================
Change ports by editing the parameters in
/home/hr2/serverfiles/System/kf-server.ini.

Useful port diagnostic command:
netstat -atunp | grep ucc-bin

DESCRIPTION      DIRECTION  PORT   PROTOCOL  INI VARIABLE
> Game           INBOUND    7710   udp       Port=7710
> Query          INBOUND    7711   udp
> GameSpy query  INBOUND    7720   udp       OldQueryPortNumber=7720
< Master server  OUTBOUND   28852  tcp/udp
< Steam          OUTBOUND   20660  udp
> WebAdmin       INBOUND    8078   tcp       ListenPort=8078

SS:2--Dead Space//Vehicle + Aliens//Mixed Custom --ScrN@lvl70-Slots-Turrets-Extra Perks...[FAST DL] WebAdmin
=================================================================================
WebAdmin enabled:   True
WebAdmin url:       http://192.168.10.42:8078
WebAdmin user:      
WebAdmin password:  

Status: ONLINE


ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 tammi21 ?      00:00:01 /sbin/init
root         2     0  0 tammi21 ?      00:00:00 [kthreadd]
root         3     2  0 tammi21 ?      00:00:00 [ksoftirqd/0]
root         5     2  0 tammi21 ?      00:00:00 [kworker/0:0H]
root         7     2  0 tammi21 ?      00:02:31 [rcu_sched]
root         8     2  0 tammi21 ?      00:01:00 [rcuos/0]
root         9     2  0 tammi21 ?      00:00:56 [rcuos/1]
root        10     2  0 tammi21 ?      00:00:57 [rcuos/2]
root        11     2  0 tammi21 ?      00:00:00 [rcuos/3]
root        12     2  0 tammi21 ?      00:00:00 [rcuos/4]
root        13     2  0 tammi21 ?      00:00:00 [rcuos/5]
root        14     2  0 tammi21 ?      00:00:00 [rcu_bh]
root        15     2  0 tammi21 ?      00:00:00 [rcuob/0]
root        16     2  0 tammi21 ?      00:00:00 [rcuob/1]
root        17     2  0 tammi21 ?      00:00:00 [rcuob/2]
root        18     2  0 tammi21 ?      00:00:00 [rcuob/3]
root        19     2  0 tammi21 ?      00:00:00 [rcuob/4]
root        20     2  0 tammi21 ?      00:00:00 [rcuob/5]
root        21     2  0 tammi21 ?      00:00:02 [migration/0]
root        22     2  0 tammi21 ?      00:00:00 [watchdog/0]
root        23     2  0 tammi21 ?      00:00:00 [watchdog/1]
root        24     2  0 tammi21 ?      00:00:03 [migration/1]
root        25     2  0 tammi21 ?      00:00:00 [ksoftirqd/1]
root        27     2  0 tammi21 ?      00:00:00 [kworker/1:0H]
root        28     2  0 tammi21 ?      00:00:00 [watchdog/2]
root        29     2  0 tammi21 ?      00:00:03 [migration/2]
root        30     2  0 tammi21 ?      00:00:00 [ksoftirqd/2]
root        32     2  0 tammi21 ?      00:00:00 [kworker/2:0H]
root        33     2  0 tammi21 ?      00:00:00 [khelper]
root        34     2  0 tammi21 ?      00:00:00 [kdevtmpfs]
root        35     2  0 tammi21 ?      00:00:00 [netns]
root        36     2  0 tammi21 ?      00:00:00 [writeback]
root        37     2  0 tammi21 ?      00:00:00 [kintegrityd]
root        38     2  0 tammi21 ?      00:00:00 [bioset]
root        40     2  0 tammi21 ?      00:00:00 [kblockd]
root        41     2  0 tammi21 ?      00:00:00 [ata_sff]
root        42     2  0 tammi21 ?      00:00:00 [khubd]
root        43     2  0 tammi21 ?      00:00:00 [md]
root        44     2  0 tammi21 ?      00:00:00 [devfreq_wq]
root        46     2  0 tammi21 ?      00:00:00 [khungtaskd]
root        47     2  0 tammi21 ?      00:00:03 [kswapd0]
root        48     2  0 tammi21 ?      00:00:00 [ksmd]
root        49     2  0 tammi21 ?      00:00:07 [khugepaged]
root        50     2  0 tammi21 ?      00:00:00 [fsnotify_mark]
root        51     2  0 tammi21 ?      00:00:00 [ecryptfs-kthrea]
root        52     2  0 tammi21 ?      00:00:00 [crypto]
root        64     2  0 tammi21 ?      00:00:00 [kthrotld]
root        86     2  0 tammi21 ?      00:00:00 [deferwq]
root        87     2  0 tammi21 ?      00:00:00 [charger_manager]
root       132     2  0 tammi21 ?      00:00:00 [scsi_eh_0]
root       133     2  0 tammi21 ?      00:00:00 [scsi_eh_1]
root       136     2  0 tammi21 ?      00:00:00 [kpsmoused]
root       144     2  0 tammi21 ?      00:00:00 [scsi_eh_2]
root       146     2  0 tammi21 ?      00:00:00 [scsi_eh_3]
root       147     2  0 tammi21 ?      00:00:00 [scsi_eh_4]
root       148     2  0 tammi21 ?      00:00:00 [scsi_eh_5]
root       149     2  0 tammi21 ?      00:00:00 [scsi_eh_6]
root       150     2  0 tammi21 ?      00:00:00 [scsi_eh_7]
root       253     2  0 tammi21 ?      00:00:06 [jbd2/sda1-8]
root       254     2  0 tammi21 ?      00:00:00 [ext4-rsv-conver]
root       417     1  0 tammi21 ?      00:00:00 upstart-udev-bridge --daemon
root       439     1  0 tammi21 ?      00:00:00 /lib/systemd/systemd-udevd --daem
message+   447     1  0 tammi21 ?      00:00:14 dbus-daemon --system --fork
root       498     1  0 tammi21 ?      00:00:00 /usr/sbin/bluetoothd
root       516     2  0 tammi21 ?      00:00:00 [krfcommd]
root       537     2  0 tammi21 ?      00:00:00 [edac-poller]
root       542     2  0 tammi21 ?      00:00:00 [kmpathd]
root       545     2  0 tammi21 ?      00:00:00 [kmpath_handlerd]
root       551     2  0 tammi21 ?      00:00:00 [mISDN_netjet.1]
root       553     1  0 tammi21 ?      00:00:00 /lib/systemd/systemd-logind
root       561     2  0 tammi21 ?      00:00:00 [kvm-irqfd-clean]
syslog     575     1  0 tammi21 ?      00:00:04 rsyslogd
avahi      581     1  0 tammi21 ?      00:00:00 avahi-daemon: running [serveri.lo
avahi      582   581  0 tammi21 ?      00:00:00 avahi-daemon: chroot helper
root       619     1  0 tammi21 ?      00:00:00 upstart-file-bridge --daemon
root       635     2  0 tammi21 ?      00:00:00 [cfg80211]
root       682     2  0 tammi21 ?      00:00:00 [hd-audio0]
root       722     1  0 tammi21 ?      00:00:06 smbd -F
root       772     1  0 tammi21 ?      00:00:00 /usr/sbin/ModemManager
root       800     1  0 tammi21 ?      00:00:00 upstart-socket-bridge --daemon
root       830     1  0 tammi21 ?      00:00:13 NetworkManager
root       835   722  0 tammi21 ?      00:00:00 smbd -F
root       846     1  0 tammi21 ?      00:00:04 /usr/lib/policykit-1/polkitd --no
root      1164     1  0 tammi21 tty4   00:00:00 /sbin/getty -8 38400 tty4
root      1166     1  0 tammi21 tty5   00:00:00 /sbin/getty -8 38400 tty5
root      1173     1  0 tammi21 tty2   00:00:00 /sbin/getty -8 38400 tty2
root      1176     1  0 tammi21 tty3   00:00:00 /sbin/getty -8 38400 tty3
root      1181     1  0 tammi21 ?      00:00:00 /usr/sbin/console-kit-daemon --no
root      1182     1  0 tammi21 tty6   00:00:00 /sbin/getty -8 38400 tty6
root      1291     1  0 tammi21 ?      00:00:00 /usr/sbin/sshd -D
root      1301     1  0 tammi21 ?      00:00:03 acpid -c /etc/acpi/events -s /var
root      1310     1  0 tammi21 ?      00:00:02 cron
root      1358     1  0 tammi21 ?      00:00:00 mdm
root      1371     1  0 tammi21 ?      00:00:18 /usr/sbin/irqbalance
root      1384     1  0 tammi21 ?      00:00:07 /sbin/wpa_supplicant -B -P /run/s
root      1432     1  0 tammi21 ?      00:00:00 /usr/sbin/cups-browsed
kernoops  1443     1  0 tammi21 ?      00:00:04 /usr/sbin/kerneloops
root      1545     1  0 tammi21 ?      00:00:00 /usr/lib/postfix/master
root      1608     1  0 tammi21 tty1   00:00:00 /sbin/getty -8 38400 tty1
root      1641     2  0 tammi21 ?      00:00:00 [kauditd]
root      1698   830  0 tammi21 ?      00:00:00 /sbin/dhclient -d -sf /usr/lib/Ne
rtkit     1911     1  0 tammi21 ?      00:00:01 /usr/lib/rtkit/rtkit-daemon
root      1977     1  0 tammi21 ?      00:02:00 /usr/lib/udisks2/udisksd --no-deb
root      2100     1  0 tammi21 ?      00:00:04 /usr/lib/upower/upowerd
root      2393     1  0 tammi21 ?      00:00:00 /usr/sbin/system-tools-backends
root      2434     1  0 tammi21 ?      00:00:00 /usr/bin/perl /usr/share/system-t
nobody    2449   830  0 tammi21 ?      00:00:00 /usr/sbin/dnsmasq --no-resolv --k
root      2630     1  0 tammi21 ?      00:00:02 nmbd -D
postfix   2663  1545  0 tammi21 ?      00:00:00 qmgr -l -t unix -u
nvidia-+  2831     1  0 tammi21 ?      00:00:00 /usr/bin/nvidia-persistenced --us
root      3486     1  0 tammi21 ?      00:00:00 /usr/sbin/cupsd -f
colord    3490     1  0 tammi21 ?      00:00:00 /usr/lib/colord/colord
root      3986  1358  0 tammi21 ?      00:00:00 mdm
root      3991  3986  0 tammi21 tty8   00:08:05 /usr/bin/X :0 -audit 0 -auth /var
mdm       4050     1  0 tammi21 ?      00:00:00 dbus-launch --autolaunch=54679c69
mdm       4051     1  0 tammi21 ?      00:00:00 //bin/dbus-daemon --fork --print-
hr        4064     1  0 tammi21 ?      00:00:00 /usr/bin/gnome-keyring-daemon --d
hr        4074  3986  0 tammi21 ?      00:00:01 x-session-manager
hr        4207  4074  0 tammi21 ?      00:00:00 /usr/bin/ssh-agent /usr/bin/dbus-
hr        4210     1  0 tammi21 ?      00:00:00 /usr/bin/dbus-launch --exit-with-
hr        4211     1  0 tammi21 ?      00:00:00 //bin/dbus-daemon --fork --print-
hr        4245     1  0 tammi21 ?      00:04:20 c:\TeamViewer\TeamViewer.exe     
hr        4329     1  0 tammi21 ?      00:02:31 /opt/teamviewer/tv_bin/wine/bin/w
hr        4349     1  0 tammi21 ?      00:00:00 C:\windows\system32\services.exe 
hr        4373     1  0 tammi21 ?      00:00:00 /usr/lib/dconf/dconf-service
hr        4380  4074  0 tammi21 ?      00:00:06 /usr/bin/mate-settings-daemon
hr        4382  4074  0 tammi21 ?      00:01:52 marco
hr        4387  4074  0 tammi21 ?      00:00:00 mate-panel
hr        4390     1  0 tammi21 ?      00:00:22 C:\windows\system32\explorer.exe 
hr        4392     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd
hr        4397     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-fuse /run/use
hr        4409  4074  0 tammi21 ?      00:00:00 /bin/sh /usr/bin/startcaja
hr        4411     1  0 tammi21 ?      00:00:00 /usr/bin/pulseaudio --start --log
hr        4418     1  0 tammi21 ?      00:00:07 /usr/bin/python /usr/lib/linuxmin
hr        4420     1  0 tammi21 ?      00:00:03 /usr/lib/mate-panel/wnck-applet
hr        4425     1  0 tammi21 ?      00:02:09 /usr/lib/x86_64-linux-gnu/multilo
hr        4426     1  0 tammi21 ?      00:01:41 /usr/lib/x86_64-linux-gnu/mate-cp
hr        4427     1  0 tammi21 ?      00:00:00 /usr/lib/mate-panel/notification-
hr        4428     1  0 tammi21 ?      00:00:05 /usr/lib/mate-panel/clock-applet
hr        4466     1  0 tammi21 ?      00:00:03 /usr/lib/gvfs/gvfs-udisks2-volume
hr        4472  4245  0 tammi21 ?      00:00:37 /opt/teamviewer/tv_bin/TVGuiSlave
hr        4475  4245  0 tammi21 ?      00:00:30 /opt/teamviewer/tv_bin/TVGuiDeleg
hr        4496     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-mtp-volume-mon
hr        4502     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-gphoto2-volume
hr        4506     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-afc-volume-mon
hr        4533  4409  0 tammi21 ?      00:01:23 caja -n
hr        4537  4074  0 tammi21 ?      00:00:03 mate-screensaver
hr        4538  4074  0 tammi21 ?      00:00:00 nm-applet
hr        4546     1  0 tammi21 ?      00:00:00 /usr/lib/at-spi2-core/at-spi-bus-
hr        4553  4074  0 tammi21 ?      00:00:00 /usr/bin/python /usr/share/system
hr        4557  4546  0 tammi21 ?      00:00:00 /bin/dbus-daemon --config-file=/e
hr        4558  4074  0 tammi21 ?      00:00:00 /usr/lib/x86_64-linux-gnu/polkit-
hr        4562  4074  2 tammi21 ?      01:37:38 skype
hr        4563  4074  0 tammi21 ?      00:00:05 mate-power-manager
hr        4566     1  0 tammi21 ?      00:00:00 /usr/lib/at-spi2-core/at-spi2-reg
hr        4568  4074  0 tammi21 ?      00:00:00 mate-volume-control-applet
hr        4605     1  0 tammi21 ?      00:00:03 /usr/lib/gvfs/gvfsd-trash --spawn
hr        4653     1  0 tammi21 ?      00:00:00 /usr/lib/x86_64-linux-gnu/gconf/g
hr        4755     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-metadata
hr        4973  4074  0 tammi21 ?      00:00:00 /usr/bin/python /usr/bin/mintupda
hr        4976  4973  0 tammi21 ?      00:00:00 sh -c /usr/lib/linuxmint/mintUpda
hr        4977  4976  0 tammi21 ?      00:00:21 python /usr/lib/linuxmint/mintUpd
hr        5604     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-http --spawne
root      7159  1358  0 tammi21 ?      00:00:00 mdm
root      7165  7159  1 tammi21 tty9   01:13:32 /usr/bin/X :20 -auth /var/lib/mdm
mdm       7235     1  0 tammi21 ?      00:00:00 dbus-launch --autolaunch=54679c69
mdm       7237     1  0 tammi21 ?      00:00:00 //bin/dbus-daemon --fork --print-
hr2       7248     1  0 tammi21 ?      00:00:00 /usr/bin/gnome-keyring-daemon --d
hr2       7258  7159  0 tammi21 ?      00:00:01 x-session-manager
root      7303     2  0 21:28 ?        00:00:00 [kworker/u13:0]
hr2       7327  7258  0 tammi21 ?      00:00:00 /usr/bin/ssh-agent /usr/bin/dbus-
hr2       7330     1  0 tammi21 ?      00:00:00 /usr/bin/dbus-launch --exit-with-
hr2       7331     1  0 tammi21 ?      00:00:00 //bin/dbus-daemon --fork --print-
hr2       7340     1  0 tammi21 ?      00:00:00 /usr/lib/dconf/dconf-service
hr2       7347  7258  0 tammi21 ?      00:00:07 /usr/bin/mate-settings-daemon
hr2       7349  7258  0 tammi21 ?      00:00:03 marco
hr2       7354  7258  0 tammi21 ?      00:00:00 mate-panel
hr2       7355     1  0 tammi21 ?      00:04:17 c:\TeamViewer\TeamViewer.exe     
hr2       7360     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd
hr2       7367     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-fuse /run/use
hr2       7395  7258  0 tammi21 ?      00:00:00 /bin/sh /usr/bin/startcaja
hr2       7410     1  0 tammi21 ?      00:00:00 /usr/bin/pulseaudio --start --log
hr2       7416     1  0 tammi21 ?      00:00:06 /usr/bin/python /usr/lib/linuxmin
hr2       7418     1  0 tammi21 ?      00:00:09 /usr/lib/mate-panel/wnck-applet
hr2       7421     1  0 tammi21 ?      00:02:06 /usr/lib/x86_64-linux-gnu/multilo
hr2       7423     1  0 tammi21 ?      00:00:00 /usr/lib/mate-panel/notification-
hr2       7424     1  0 tammi21 ?      00:00:04 /usr/lib/mate-panel/clock-applet
hr2       7471     1  0 tammi21 ?      00:02:06 /opt/teamviewer/tv_bin/wine/bin/w
hr2       7486     1  0 tammi21 ?      00:00:00 C:\windows\system32\services.exe 
root      7515     2  0 21:29 ?        00:00:00 [kworker/1:2]
hr2       7517     1  0 tammi21 ?      00:00:03 /usr/lib/gvfs/gvfs-udisks2-volume
hr2       7521     1  0 tammi21 ?      00:00:00 C:\windows\system32\explorer.exe 
hr2       7526     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-mtp-volume-mon
hr2       7532     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-gphoto2-volume
hr2       7537     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfs-afc-volume-mon
hr2       7562  7395  0 tammi21 ?      00:01:30 caja -n
hr2       7566  7258  0 tammi21 ?      00:00:02 mate-screensaver
hr2       7573  7258  0 tammi21 ?      00:00:00 nm-applet
hr2       7576  7355  0 tammi21 ?      00:00:37 /opt/teamviewer/tv_bin/TVGuiSlave
hr2       7582  7355  0 tammi21 ?      00:00:29 /opt/teamviewer/tv_bin/TVGuiDeleg
hr2       7589  7258  0 tammi21 ?      00:00:05 mate-power-manager
hr2       7590  7258  0 tammi21 ?      00:00:00 /usr/lib/x86_64-linux-gnu/polkit-
hr2       7591  7258  0 tammi21 ?      00:00:00 /usr/bin/python /usr/share/system
hr2       7594  7258  0 tammi21 ?      00:00:00 mate-volume-control-applet
hr2       7596     1  0 tammi21 ?      00:00:00 /usr/lib/at-spi2-core/at-spi-bus-
hr2       7617  7596  0 tammi21 ?      00:00:00 /bin/dbus-daemon --config-file=/e
hr2       7627     1  0 tammi21 ?      00:00:00 /usr/lib/at-spi2-core/at-spi2-reg
hr2       7654     1  0 tammi21 ?      00:00:03 /usr/lib/gvfs/gvfsd-trash --spawn
hr2       7681     1  0 tammi21 ?      00:00:00 /usr/lib/x86_64-linux-gnu/gconf/g
hr2       7762     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-metadata
hr2       7772  7258  0 tammi21 ?      00:00:00 /usr/bin/python /usr/bin/mintupda
hr2       7775  7772  0 tammi21 ?      00:00:00 sh -c /usr/lib/linuxmint/mintUpda
hr2       7776  7775  0 tammi21 ?      00:00:22 python /usr/lib/linuxmint/mintUpd
root      7780     2  0 14:06 ?        00:00:00 [kworker/1:0]
hr2       7919     1 13 tammi21 ?      09:05:25 mate-system-monitor
hr2       8049     1  0 tammi21 ?      00:00:00 /usr/lib/gvfs/gvfsd-http --spawne
root      8324     1  0 21:33 ?        00:00:00 /opt/teamviewer/tv_bin/teamviewer
hr2       9152     1  5 21:36 ?        00:00:55 ./ucc-bin-real server KF-FacingWo
root      9333     2  0 21:37 ?        00:00:00 [kworker/u12:0]
hr        9686     1  0 14:20 ?        00:00:20 tmux new-session -d -s kf-server 
hr        9687  9686  0 14:20 pts/4    00:04:17 ./ucc-bin-real server KF-FacingWo
root     10302     2  0 21:42 ?        00:00:00 [kworker/0:2]
root     10303     2  0 21:42 ?        00:00:00 [kworker/u12:1]
root     11181     2  0 21:46 ?        00:00:00 [kworker/2:2]
hr2      11522     1 19 21:47 ?        00:01:03 ./ucc-bin-real server KF-FacingWo
hr2      11674     1 19 21:47 ?        00:01:03 ./ucc-bin-real server KF-FacingWo
root     12002     2  0 21:48 ?        00:00:00 [kworker/u12:2]
hr2      12180     1 21 21:48 ?        00:00:57 ./ucc-bin-real server KF-FacingWo
root     12319     2  0 18:39 ?        00:00:00 [kworker/2:0]
hr2      12524     1 26 21:49 ?        00:00:56 ./ucc-bin-real server KF-FacingWo
hr2      13027     1 37 21:50 ?        00:00:56 ./ucc-bin-real server KF-FacingWo
hr2      13429     1  0 21:51 ?        00:00:00 tmux new-session -d -s kf-server 
hr2      13430 13429  0 21:51 pts/13   00:00:00 sh -c ./ucc-bin server KF-FacingW
hr2      13432 13430 62 21:51 pts/13   00:00:56 ./ucc-bin-real server KF-FacingWo
root     13456  1310  0 21:52 ?        00:00:00 CRON
hr2      13457 13456  0 21:52 ?        00:00:00 /bin/sh -c /home/hr2/kfserver mon
hr2      13459 13457  0 21:52 ?        00:00:00 /bin/bash /home/hr2/kfserver moni
hr2      13611 13459  0 21:52 ?        00:00:00 sleep 60
hr2      13613 27266  0 21:52 pts/3    00:00:00 ps -ef
root     15809     2  0 19:05 ?        00:00:00 [kworker/u13:1]
root     27254  1291  0 20:32 ?        00:00:00 sshd: hr2 [priv]    
hr2      27265 27254  0 20:32 ?        00:00:00 sshd: hr2@pts/3     
hr2      27266 27265  0 20:32 pts/3    00:00:00 -bash
root     27305  1291  0 20:32 ?        00:00:00 sshd: hr2 [priv]    
hr2      27316 27305  0 20:32 ?        00:00:00 sshd: hr2@notty     
hr2      27317 27316  0 20:32 ?        00:00:00 /usr/lib/openssh/sftp-server
postfix  29637  1545  0 20:51 ?        00:00:00 pickup -l -t unix -u -c
root     31044     2  0 17:00 ?        00:00:01 [kworker/0:1]

**Comment by dgibbs64** [comment]
I have replicated the issue just by restarting the server. Not sure how this wasn't picked up before. I will investigate and figure out a fix

**Comment by Xylemon** [comment]
On my end it seems KF just crashes, I've updated everything today and haven't been able to start KF with this message: 

tail: cannot open '3' for reading: No such file or directory
/home/server/Servers/kf/functions/fn_start: line 47: [: : integer expression expected
[ FAIL ] Starting kf-server: Unable to start Killing Floor Server
	Check log files: /home/server/Servers/kf/log

**Comment by madfin** [comment]
Any progress with this?

I have one suggestion to make that monitoring better. I have had few incidents that while you switch map and monitor kicks in and fail to port scan and goes for 60s wait. But if map is voted again before second scan is completed it fails and goes to reboot or start another server.

How about you add to that monitoring third scan? Then you could set it to scan like: 30s  + 30s

**Comment by dgibbs64** [comment]
It may be a good idea to look at me adding a variable for admins to select how long they want the monitor to wait before restarting the server if needed. I have been very busy recently and not had time to look at this.

**Comment by madfin** [comment]
For temporal solution. I added pkill ucc-bin-real command in the end of fn_stop script. That should kill all old hanging servers.

**Comment by dgibbs64** [comment]
pkill might cause issues with users running multiple servers. I did find that the server eventually drops itself after around 1 min. 

I will adjust the monitor for 60 seconds by default for unreal servers to try and combat the server rebooting around map voting time.

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/a816fc93ef8c47980313e023f77a616552f8429e

**Comment by dgibbs64** [comment]
I will close this issue. However if the ucc-bin-real becomes and issue still after these changes will need to be re raised.
