### ISSUE TITLE
Ark Survival Evolved Linux Dedicated Server shows version 306.84, but build version should be 306.89

### ISSUE THREAD

**Issue by Ancillius** [GameServerManagers/LinuxGSM#2735]
After ./arkserver update (with restart) I get:
:~/serverfiles$ cat version.txt
306.89

Also 
./arkserver update
[  OK  ] Update arkserver: Checking for update: SteamCMD

No update available
* Local build: 4768092
* Remote build: 4768092
https://steamdb.info/app/376030/

This should be 306.89

But the server browser still states 306.84

Also the logs say:
[2020.03.12-07.38.03:736][  0]Log file open, 03/12/20 08:38:03
[2020.03.12-07.38.03:736][  0]ARK Version: 306.84
[2020.03.12-07.38.03:736][  0]PID: 17417

Why?

( https://www.battlemetrics.com/servers/ark/5821714 )

**Comment by dgibbs64** [comment]
This wouldn't be something we could answer. Best answered by the game developers.
