### ISSUE TITLE
Unable to create new sdtdserver

### ISSUE THREAD

**Issue by caiwilliamson** [GameServerManagers/LinuxGSM#2746]
## User Story

I am following the instructions here https://linuxgsm.com/lgsm/sdtdserver/ (as I have done many times before) to create a new sdtd server on Debian 10 Buster 64-bit. However upon running `./sdtdserver install` I get the following error:

```
Warning! Missing dependencies: steamcmd lib32stdc++6
Warning! rustserver does not have sudo access. Manually install dependencies.

sudo dpkg --add-architecture i386; sudo apt update; sudo apt install steamcmd lib32stdc++6

Failure! Missing dependencies required to run SteamCMD.
    fetching core_exit.sh...OK
```

So I follow the instructions and as root I run:

`sudo dpkg --add-architecture i386; sudo apt update; sudo apt install steamcmd lib32stdc++6;`
 
But that fails too with:

```
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://deb.debian.org/debian buster-backports InRelease
Hit:4 http://security.debian.org buster/updates InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package steamcmd
```

I've installed servers many times before with no issues. I believe this is happening with other game servers too, not just 7 Days To Die, as I see that several other people are experiencing very similar issues at the same time: #2744 #2743 

I have tried this on a completely fresh copy of Debian 10 Buster several times after I noticed the issue.

## Basic info

* **Distro:** Debian 10 Buster
* **Game:** 7 Days To Die
* **Command:** `./sdtdserver install`
* **LinuxGSM version:** Latest version, fresh install

**Comment by dgibbs64** [comment]
the non-free repo is missing causing the package to not be available. I will look for the best solution to this

**Comment by dgibbs64** [comment]
so the quick fix is to add non-free repo.

My fix is to use the "old" method of using steamcmd if non-free is not available in Debian
