### ISSUE TITLE
Symbolic links to steamcmd no longer work when using apt package

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2748]
## User Story

Syblomic links to steamcmd no longer work when using apt package

## Basic info

* **Distro:** Ubuntu 18.04

* **Command:** update
* **LinuxGSM version:** v20.1.0

**Comment by chewbaccafr** [comment]
Same for me... My server can't launch : 
`[ .... ] Starting arkserver: [FR] Les Survivants - Ragnarok - Cluster PVEln: failed to create symbolic link '/home/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux': File exists
ln: failed to create symbolic link '/home/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps': No such file or directory
[  OK  ] Update arkserver: Checking for update: SteamCMD

No update available
* Local build: 4776339
* Remote build: 4776339
https://steamdb.info/app/376030/
[  OK  ] Starting arkserver: [FR] Les Survivants - Ragnarok - Cluster PVE`

**Comment by skykiah888** [comment]
[  OK  ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evolved
[ INFO ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolvedln: failed to create symbolic link ‘/home/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps’: No such file or directory
[ERROR ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolved

I use centos 7.6

**Comment by dgibbs64** [comment]
@skykiah888 please confirm you are running v20.1.2
