### ISSUE TITLE
Add netcat to dependency list and checking

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2752]
## User Story

Some vps template (at least official ubuntu 16.04 template for openvz) even did not include netcat in default, not surprisingly you got nc command not found error 

## Basic info

* **Distro:** [Ubuntu 16.04]
* **Command:** [postdetails]
* **LinuxGSM version:** [v19.01.1]

## Further Information

[ INFO ] Postdetails bb2server: Check IP: 45.129.229.140
    fetching query_gamedig.sh...OK
[ .... ] Postdetails bb2server: Posting details to termbin.com/home/bb2/lgsm/functions/command_postdetails.sh: line 110: nc: command not found
[  OK  ] Postdetails bb2server: Posting details to termbin.com

## To Reproduce

run postdetails command 

## Expected behaviour

postdetails command runs successfully and user can get the termbin url

**Comment by dgibbs64** [comment]
I will add this as a default dependency.

**Comment by dgibbs64** [comment]
ubuntu/debian netcat
centos nmap-ncat
