### ISSUE TITLE
Deprecate Debian jessie

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2759]
## User Story

Debian would ends Jessie's LTS support on June 30, many servers on lgsm website still list debian jessie as minimum required version. its time to raise the requirement in conjunction with dependencies refactor #2757

## Basic info

* **Distro:** [Debian 8]

## Further Information

https://wiki.debian.org/LTS

**Comment by dgibbs64** [comment]
increased minimum required to debian 9
