### ISSUE TITLE
ARK Survival Evolved mods not installing/updating

### ISSUE THREAD

**Issue by ohnohimagain** [GameServerManagers/LinuxGSM#2762]
Hi there,
I am looking to migrate my ARK Server from Windows 10 to Ubuntu Linux, but loading mods aren't working ?

It is a dedicated server hosted by OVH.
Hypervisor Proxmox 6.1
VPS powered  by QEMU, not LXC !

The VPS is provisionned using
RAM 16 GB
CPU 4 Core
OS: Ubuntu 18.04.4 LTS - amd64 
uname -a : Linux gameserver 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Network**
filtered by IPfire firewall,
Ports opened: game + query + rcon (7777 + 27015 + 27020) tcp and udp
_Outgoing traffic not restricted_

**installed dependencies instructions on the website**
`sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386`

**Then added missing packages**
`sudo apt install netcat lib32stdc++6 steamcmd`

ARK is starting with minimal modifications but still complain about

> arkserver@gameserver:~$ ./arkserver start
> [ INFO ] Starting arkserver: Check IP: 172.22.22.207
> [ .... ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evol[ INFO ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evol[  OK  ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evolved
> [ INFO ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolvedln: failed to create symbolic link '/home/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps': File exists
> [ERROR ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolved
> [  OK  ] Starting arkserver: LinuxGSM

ARK Server online, when I tries to connect, it disconnect me instantly telling me about mods version mismatch.

> arkserver@gameserver:~$ ls serverfiles/ShooterGame/Content/Mods/
> 111111111  111111111.mod  Ragnarok  TheCenter  Valguero

I tried to install Stucture Plus mod ID 731604991

**GameUseSettings.ini :** 
```
[ServerSettings]
ActiveMods=731604991
[...]
```
**Game.ini**
```
[ModInstaller]
ModIDS=731604991
```

I reinstalled the linux VPS twice before opening this bug...
Help ?

**Comment by ChrisWolle** [comment]
I have the same problem, with the same Mod. I have reinstalled the server twice, but every time the same error.
`[  OK  ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evolved
[ INFO ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolvedln: failed to create symbolic link '/home/arkragnarok/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps': File exists
[ERROR ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolved`

Debuging stops at:
`[ INFO ] Debug arkserver: Stopping any running servers
[  OK  ] Stopping arkserver: Graceful: CTRL+c: 3: OK
[  OK  ] Debug arkserver: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
`
Using LinuxGSM version:  v20.1.2

**Comment by dgibbs64** [comment]
can either of you please contact me on discord. I would like to remote on to your server to take a look as I cant see what the issue is

**Comment by ohnohimagain** [comment]
I do not know where I need to get in touch so I've used the old way … make friend request (Nioubozore#6065)

**Comment by hysellr** [comment]
Same issue here, seems to be related to any mod installs... output of the `debug` command (some parts ommitted intentionally):

```bash
[  OK  ] Fix arkserver: Applying broken steamcmd symlink fix: ARK: Survival Evolved
[ INFO ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolvedln: failed to create symbolic link ‘....../serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps’: No such file or directory
[ERROR ] Fix arkserver: Applying steamcmd symlink fix: ARK: Survival Evolved

ARK: Survival Evolved Debug
=================================
Distro:     CentOS Linux 7 (Core)
Arch:     x86_64
tmux:     tmux 1.8
Avg Load:     0.32, 0.15, 0.14
glibc required: 2.15
Master Server:  false

[ INFO ] Debug arkserver: Stopping any running servers
[ INFO ] Stopping arkserver: ...... is already stopped
[  OK  ] Debug arkserver: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\build\trunk\Engine\Source\Runtime\Core\Private\Linux\LinuxPlatformProcess.cpp] [Line: 652]
FLinuxPlatformProcess::WaitForProc: waitid for pid -1 failed (errno=22, Invalid argument)
Signal 11 caught.
EngineCrashHandler: Signal=11
..../lgsm/functions/command_debug.sh: line 120:  5713 Segmentation fault      ${executable} ${parms}
```

The "LowLevelFatalError" line is particularly interesting, since that is a Windows path.

**Comment by dgibbs64** [comment]
A lot of work was carried out to improve ark mods. This issue should be resolved. However if not please raise a new issue.
