### ISSUE TITLE
 Missing dependencies: util-linux python3 nmap-ncat

### ISSUE THREAD

**Issue by 15tolife** [GameServerManagers/LinuxGSM#2763]
Hy , 
-every time I start stop restart cs1.6 server i get this error  **Missing dependencies: util-linux python3 nmap-ncat** , although server is running its annoying for lgsm to try to install every time missing dependencies and then find out **"latest python is allready installed and latest version"** 
-Also i cant install dproto even though its really easy to install , what ever i do in "meta list" it shows "fail to load" , and i dont know if it has anithing to do with this python error.....
I would really apreciate if someone could help me get rid of the python error and dproto "fail to load"
errors ----->
![error](https://user-images.githubusercontent.com/62301706/76985066-5a31db00-6948-11ea-969b-8fd04be48b16.jpg)
![dproto error](https://user-images.githubusercontent.com/62301706/76985069-5b630800-6948-11ea-97e9-aeafd138f267.jpg)

Thanks in advance

**Comment by Frisasky** [comment]
Since we have deprecated centos 6 a while ago, user should take all responsibility of running unsupported version, hence lgsm wont make accommodation for it

**Comment by 15tolife** [comment]
But in education purpose as centos 6 is stil used by millions of people do you have any ideea how to solve this ? 
Thank you

**Comment by h3o66** [comment]
> But in education purpose as centos 6 is stil used by millions of people do you have any ideea how to solve this ?
> Thank you

The only thing i could think of is that someone could maintain a version where this was not removed (and change the basic settings from lgsm to point to their version), but this is out of scope of this project .

To skip this you need to change the scripts yourself.

**Comment by 15tolife** [comment]
thank you h3o66 , 
are you refering to dproto or python?
Couldn't this just be made possible by installing the missing nmap-ncat thing ? i tried to search some answers but couldnt find anithing precise.
Centos 6 doesnt seem deprecated by lgsm as its verry compatible and i'm thankfull for that lgsm made my life easier , the only 2 errors that centos 6 users get is glibc that has already a solve thanks to your help and this python nmap-ncat thing wich i'm sure can be solved by some bright minds (not mine) ..... this doesnt't mean deprecated.
And i dont think that for 1 error we should deny so many centos 6 users from using lgsm.
Thanks

**Comment by dgibbs64** [comment]
```

[csserver@li762-208 ~]$ ./csserver d
[ERROR ] Debug csserver: glibc requirements not met

        * glibc required: 2.14
        * glibc installed: 2.12

Information! distro upgrade is required
Warning! Missing dependencies: util-linux python3 nmap-ncat
Warning! csserver does not have sudo access. Manually install dependencies.

sudo yum install util-linux python3 nmap-ncat

[ INFO ] Debug csserver: Check IP: 212.111.41.208

Counter-Strike 1.6 Debug
=================================
Distro:   CentOS release 6.8 (Final)
Arch:   x86_64
Kernel:   5.4.10-x86_64-linode132
Hostname:   li762-208.members.linode.com
tmux:   tmux 1.6
Avg Load:   0.16, 0.12, 0.05
Free Memory:   246M
Free Disk:   45G
glibc required: 2.14 (distro glibc 2.12 too old)
Server IP:      212.111.41.208:27015
Master Server:  false
Server password:        NOT SET
Start parameters:
./hlds_run -game cstrike -strictportbind +ip 212.111.41.208 -port 27015 +clientport 27005 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 16 -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If csserver is already running it will be stopped.

Continue? [Y/n] Y
```

LinuxGSM does not support CentOS 6 anymore and hasn't for a long while now. This is because most game servers just don't work on it (without bodging it) and LinuxGSM itself has a few things in code that don't work in CentOS 6. Not only that CentOS 6 goes fully out of support in November this year and full updates stopped in 2017. This means that security-wise it will become unsafe and no one should be using it for production at all.

I will look at updating linuxgsm for the next release disabling dependency checks for centos 6 and advising that CentOS 6 is not supported. This will mean you won't get the missing dependencies error. You are welcome to use CentOS 6 but it really is not recommended.

**Comment by 15tolife** [comment]
Thank you dgibbs64 , eventually i will upgrade to centos 7 again , but i just cant seem to make my server accept 47 protocol , dproto just fails loading , i couldn't find any tutorial of how to make available 47+48 protocols through lgsm.....can you please point me in the right direction ? 
Thanks

**Comment by dgibbs64** [comment]
Not only is dproto very old with no updates for years (which is why it does not work) it is used to allow non-steam versions of cs 1.6 on to your server. Our FAQ states that we will not support piracy.

https://forums.alliedmods.net/showthread.php?t=234549

https://docs.linuxgsm.com/support/faq#how-can-i-install-a-non-steam-version

**Comment by 15tolife** [comment]
What about any other method besides dproto ? for testing purpose

**Comment by dgibbs64** [comment]
install the server without dproto on CentOS 8 and it will work

**Comment by 15tolife** [comment]
both protocols will work ?

**Comment by dgibbs64** [comment]
whichever protocols valve intend to work, will work. If you have a legitimate steam version of cs 1.6 then you will be able to connect to it.
