### ISSUE TITLE
[UT99] gsquery monitor error

### ISSUE THREAD

**Issue by TFMvdBroek** [GameServerManagers/LinuxGSM#277]
When i use gsquery.py with the monitoring function i get the following error:

[  OK  ] Monitoring ut99-server: Checking session: OK
- 1")syntax error: invalid arithmetic operator (error token is "

Any idea why ?

**Comment by dgibbs64** [comment]
Not sure on this one. I have tested many times without this issue. Make sure your running the latest version of the script. If you update and still getting the issue I will check this myself.

**Comment by TFMvdBroek** [comment]
After update when running ut99server monitor i get the following:

~$ ./ut99server monitor
[ INFO ] Monitor ut99-server: SteamCMD is currently checking for updates
[ INFO ] Monitor ut99-server: When update is complete ut99-server will start

Even tho the server is already running ...
Also the monitor does not seem to start the game by itself anymore. ./ut99server start needs to be run.

~$ ./ut99server monitor
[ INFO ] Monitor ut99-server: Disabled: No lock file found
To enable monitor run 0 start

**Comment by dgibbs64** [comment]
The SteamCMD issue I will look at. The second part is by design. The server must be started to activate the monitor. Saves the server starting itself even if you manually stop it.

**Comment by dgibbs64** [comment]
UT should no longer check that SteamCMD update is running https://github.com/dgibbs64/linuxgameservers/commit/8e2b5541c8b895c77073c86c44b39c2426280a2c
