### ISSUE TITLE
telegram alert <url> malformed`

### ISSUE THREAD

**Issue by xopez** [GameServerManagers/LinuxGSM#2770]
## User Story
The telegram alert is `malformed` in in console. This is only tested with telegram, since it is the only configured alert for me.

## Basic info

* **Distro:** Ubuntu 18.04.4 LTS
* **Game:** Garry's Mod
* **Command:** alert
* **LinuxGSM version:** v20.1.3, v20.1.4

## Further Information

If you configure telegram for alert, you get the error `alertcurl: (3) <url> malformed`.
The alert is still being correctly pushed on telegram.

## To Reproduce

Steps to reproduce the behaviour:
1. configure telegram for alert
2. send a test-alert (also happing with normal update alert)
3. Following output:
```
gmodserver@ttt:~$ ./gmodserver ta
....
[ .... ] Alert gmodserver: Sending Telegram alertcurl: (3) <url> malformed
[  OK  ] Alert gmodserver: Sending Telegram alert
....
```

## Expected behaviour
Correct output

**Comment by dgibbs64** [comment]
recently completed a refactor of alerts. Issue should no longer be happening
