### ISSUE TITLE
RUST Server : Disconnected : connection attempt failed

### ISSUE THREAD

**Issue by BoolyBoys** [GameServerManagers/LinuxGSM#2775]
Hello !
I made a Rust server on my Debian machine. ( dedicated OVH )
I followed tutorials but I still can't connect to it.

I can connect to Rcon but not to the server with client.connect

I opened each port with iptables.

The only errors I saw is:

Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
OK.

![image](https://user-images.githubusercontent.com/6526789/77254054-ec92f100-6c5e-11ea-8a85-018790db0326.png)
![image](https://user-images.githubusercontent.com/6526789/77254060-f4529580-6c5e-11ea-86e5-0df6f1fa910f.png)
![image](https://user-images.githubusercontent.com/6526789/77254061-f6b4ef80-6c5e-11ea-9010-db0ad2012324.png)

Thanks in advance !
Bye !

**Comment by h3o66** [comment]
The problem might be that ohv does have a seperate firewall in front of your server.
Have a look here:
https://docs.ovh.com/gb/en/dedicated/firewall-network/
Please check this and report back.

**Comment by BoolyBoys** [comment]
Thanks for your answer.
I use SoYouStart so there is no firewall ( I called support to check )

**Comment by h3o66** [comment]
As far as I know they use the OVH firewall (as they use the infastructure of them), but if it does not work not sure how we can help you here.
If you want you can join the Discord to ask other peoplefor help, but imho this is not a problem of LGSM.

**Comment by BoolyBoys** [comment]
I have some games on this dedicated server ( others port ) and no problem so...
I joined, I'm waiting for a answer thanks

**Comment by h3o66** [comment]
No Answer till now
Closing this for now.
