### ISSUE TITLE
Integrate custom alert functions into existing alerting mechanism

### ISSUE THREAD

**Issue by codingWithJimmy** [GameServerManagers/LinuxGSM#2776]
## User Story

As a server admin, I want to design my own custom alert functions so that they will fire into our Slack/Discord based on proper context.

## Basic info

* **Distro:** CentOS 7
* **Game:** Team Fortress 2
* **Command:** Alert
* **LinuxGSM version:** [v12.34.56]

## Further Information

If it was possible, I'd like a config file or part of the LGSM server config where alert functions could be defined similar to how they are in `alerts.sh` to allow administrators to create their own custom alert functions and output those functions based off events they define. This allows for flexibility in not having to change core functions and break updating LGSM if new features are released without having to go back and re-write the alerts into the core script.

I had considered writing something like it where you take `alerts.sh`, copy it into `alerts_custom.sh` and writing the additional alerts. Mainly it was to be able to advertise to those unaware of the existence of our servers to have a quick link to jump into game. However, updating LGSM would wipe those scripts out because it was an "unknown" to the update script so we'd have to put that function somewhere else or find a way to ensure that script doesn't get wiped out.

**Comment by dreamy32** [comment]
I was under the impression that the Linux GSM webhook would send an alert whenever the server was started or shut down, or in the event of a power outage. This would be a really useful feature for me, as power outages are quite common where I live.

**Comment by Gsolisen** [comment]
if there any way to alert changes on server  ip's ? im a house server admin and my isp change my public ip to many times and i cant see if this is alerted or not

**Comment by dgibbs64** [comment]
A refactor has been done for alerts to add stop/start/restart alerts and a few others. I would like to recommend that alerts are standardised and if there are alerts missing that might be useful raise an issue and they could be added. Also the alerts now have alertip option to manually set an ip address if required
