### ISSUE TITLE
Unable to validate server files

### ISSUE THREAD

**Issue by teammate165** [GameServerManagers/LinuxGSM#2780]
After updating LGSM functions I found that validating doesn't work on my CSGO server. It would just say `App '740' already up to date.` which implies it was trying to update server but not validate my server files.
A bit of digging later, I found inside `commands_validate.sh` had `-beta "${branch}"` on line 30 which is weird because I've never seen anyone used this when validating server files. Out of suspicion I decided to remove that part of the code and the validation function was working normally again.

**Comment by dgibbs64** [comment]
looks like steamcmd has had some big updates and this might have changed
