### ISSUE TITLE
Insurgency Sandstorm not working after install.

### ISSUE THREAD

**Issue by daveallen** [GameServerManagers/LinuxGSM#2783]
## User Story

I want [install fixed] so that [server works].

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Insurgency Sandstorm]
* **Command:** [start]
* **LinuxGSM version:** [v20.1.5]

## Further Information

The Insurgency Sandstorm server with a clean install on a fresh Ubuntu 18.04 virtual cloud machine.  The game client tries to connect and will timeout when using the ip address to connect.  Also doesn't show up in the server browser.

## To Reproduce

Steps to reproduce the behaviour:
1. install the dependencies as shown on the LGSM server page, and include 'netcat' as that is missing on the page.
2. Create a user as described on the LGSM server page.
3. Download linuxgsm.sh as described on the LGSM server page.
4. Run the install.
5. Add a server name so that it will uniquely register in the server browser.
  a. In the ~/lgsm/config-lgsm/inssserver/inssserver.cfg file put this line: servername="SomeUniqueName"
6. Launch the server: ./inssserver st
7. Try connecting to the server from the server browser in game by using the ip address.
8. You will get a timeout making the connection.

## Expected behaviour

Would normally connect to the server and allow you to play.

**Comment by daveallen** [comment]
If I run the command by hand without all the "?" in it after the Scenario then the server works fine.

LGSM: ./InsurgencyServer-Linux-Shipping Farmhouse?Scenario=Scenario_Farmhouse_Checkpoint_Security?MaxPlayers=28?Port=27102?QueryPort=27131 -hostname='ServerName' -log     (DOES NOT WORK)

BY HAND: Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Farmhouse?Scenario=Scenario_Farmhouse_Checkpoint_Security -hostname="ServerName" -log    (WORKS FINE)

BY HAND:Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping Farmhouse?Scenario=Scenario_Farmhouse_Checkpoint_Security?MaxPlayers=28?Port=27102?QueryPort=27131 -hostname="ServerName" -log    (DOES NOT WORK)

**Comment by h3o66** [comment]
I got a fix incomming for this, you maybe want to check the linked PR and test it
