### ISSUE TITLE
GSM failed to debug

### ISSUE THREAD

**Issue by Fadrigt** [GameServerManagers/LinuxGSM#2784]
## User Story

As a server host, I want to know why my server can run Debug command so that do a futher action.

## Basic info

* **Distro:** [ CentOS7.6 ]
* **Game:** [7 days to die]
* **Command:** [debug]
* **LinuxGSM version:** [v12.34.56]

## Further Information

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 251570
And then,the connection 
![chrome_SUVPu88kle](https://user-images.githubusercontent.com/54088089/77611607-bc01ce80-6f60-11ea-84df-88ecc0ed5e87.png)
closed
## Further Reading

Provide any useful documentation or resources that might help.

**Comment by h3o66** [comment]
Did you even try to connect on the server ?
There would be only a problem if it would not show any output.

**Comment by h3o66** [comment]
~closed
not an answer in more than half a month.
