### ISSUE TITLE
compat-libstdc++--33.i686 missing for CentOS 8

### ISSUE THREAD

**Issue by dbjock** [GameServerManagers/LinuxGSM#2786]
I was installing the ut2k4server so I could have it running on CentOS 8, and determined the required package compat-libstdc++-33.i686 is not able to obtained for CentOS 8.

## Basic info
* **Distro:** CentOS 8
* **Game:** ut2K4server
## Further Information
Following the instruction here https://linuxgsm.com/lgsm/ut2k4server/ all went well until, as root, entering the following command
```./ut2k4server install```

Errors and warnings were returned:
```Warning! Missing dependencies: jq tmux glibc.i686 libstdc++.i686 compat-libstdc++-33.i686 SDL.i686```

The only package that was unable to be installed manually was the compat-libstdc++-33.i686. with the `# dnf install compat-libstdc++--33.i686` command. Output below:
```Last metadata expiration check: 0:29:59 ago on Thu 26 Mar 2020 09:16:10 AM CDT.
No match for argument: compat-libstdc++--33.i686
Error: Unable to find a match: compat-libstdc++--33.i686```

Is this package still required?

**Comment by dgibbs64** [comment]
I have tested ut2k4 on both centos 7 and 8 and it still runs. So I will remove it as a requirement.
