### ISSUE TITLE
Remove Ctrl + C from srcds

### ISSUE THREAD

**Issue by MyDimeIsUp** [GameServerManagers/LinuxGSM#2790]
Just wondering if there is a possible way to remove Ctrl + C from the tmux console viewer. On multiple occasions I have hit this key combination and it has shutdown my server, making almost everyone not connect back and dramatically reducing my player base

**Comment by h3o66** [comment]
The main problem is that we stop the a part of the gameservers with:

https://github.com/GameServerManagers/LinuxGSM/blob/9e5377086bbbb0bc065c5a8990b25c3d472c1d20/lgsm/functions/command_stop.sh#L13

As well i do not know if it is possible - you might want to have a look in the Tmux docs or tmux telated threads, but in my opinion this is out of scope.

**Comment by dgibbs64** [comment]
This is why there is a warning before console is started. CTRL+c is required to gracefully shutdown many servers. The same issue would happen if you used CTRL+c in the terminal. There is nothing that can be done by developers. You will just need to be careful
