### ISSUE TITLE
Unreal Tournament 3 not appearing in Internet server list

### ISSUE THREAD

**Issue by lepiney** [GameServerManagers/LinuxGSM#2791]
## User Story

Before you say "why are you posting here this isn't the forum" 
- I wast asked to by  
[LGSM] KnightLife Officer 19 Mar @ 5:36am       
please can you post this on github https://github.com/GameServerManagers/LinuxGSM/issues

I'm just trying to help someone avoid the frustrations I had.

So-
As an installer of UT3 Linux GSM, I want set up a game server so that appeared in the server master list and be played by the Internet players.

## Basic info

* **Distro:** [Debian 9]
* **Game:** [Unreal Tournament 3]
* **Command:** [./UT3server start]
* **LinuxGSM version:** [v12.34.56]

## Further Information

I installed the LGSM game and followed instructions many times.
After days of googling and troubleshooting I finally got the server listed and playable in the master server list.
I wanted to share where the GSM documentaion is wrong and what it is missing.

I found that using the linux gamespy server patch fixed is critical to listing your server.
http://cl1k.de/ut3/patches/index.html

Also of note - edit the  /ut3server/lgsm/config-lgsm/ut3-server/common.cfg
ip= "your internal address"
multihome = 0.0.0.0 (NOT your internal address)

Showed up straight away in the server list after I did these.

Hope this helps someone

## To Reproduce
install the gamespy linux server patch 
put multihome = 0.0.0.0 in the config.cfg file (NOT internal IP)

Steps to reproduce the behaviour:

## Expected behaviour
It should appear on the master server list

**Comment by Erutan409** [comment]
@lepiney Can you share how you applied the patch for the linux server?  Timing couldn't have been better for you opening this issue, too.  So, thank you for that.

**Comment by lepiney** [comment]
1) download Linux gamespy server patch 
I got from here:
http://cl1k.de/ut3/patches/index.html
This will download UT3Linux2.1_EpicMS.zip

2) Copy this file to /ut3server/serverfiles/binaries

3) Rename ut3-bin file to ut3-bin.orig 

3) Unzip UT3Linux2.1_EpicMS.zip to create a new ut3-bin file

![ut3-bin](https://user-images.githubusercontent.com/62777857/77860711-135bb380-726d-11ea-978d-998534b71620.JPG)

If still having issue the n make sure 
multihome is=0.0.0.0 in the common.cfg

This 100% works for me.
I reboot and restart the server and it appears in the master list every time.
And it stays there. Look for:

Airborne Frag Server (Lepiney.co.nz/utstatsdb)

That's me

**Comment by Grimston** [comment]
I have copied the patch to my CDN for direct access this would mean the patch can be automated.
[https://cdnlgp.b-cdn.net/files/lgsm/servers/ut3/patch/UT3Linux2.1_EpicMS.zip](https://cdnlgp.b-cdn.net/files/lgsm/servers/ut3/patch/UT3Linux2.1_EpicMS.zip)

**Comment by Erutan409** [comment]
@lepiney I just got it.  I didn't know I had to [create an account](https://multiplayerforums.com/topic/5323-unreal-tournament-3-server-setup-guide-windows/) for the server, itself.

**Comment by lepiney** [comment]
That's right - it has to be a separate account from the player account - that's from the bad old gamespy days
A real trap - I forgot to mention that.Y
    On Saturday, 4 April 2020, 08:51:24 am NZDT, Michael Keyser <notifications@github.com> wrote:  
 
 


@lepiney I just got it. I didn't know I had to create an account for the server, itself.

**Comment by dgibbs64** [comment]
I will be testing this and merge the patch in to the full download

**Comment by dgibbs64** [comment]
#2851 I have updated the archive with the gamespy patch. Also going to add details about the login parms

**Comment by h3o66** [comment]
~Closed
bug fix in version 20.3.0 included
