### ISSUE TITLE
How to start csserver with -pingboost 

### ISSUE THREAD

**Issue by 15tolife** [GameServerManagers/LinuxGSM#2793]
Hy ,
So i'm having some trouble with latency on my cs 1.6 server , and i heard that a solution will be to start the server with -pingboost and also give priority to lgsm with something like nice or renice.....
Can someone please tell me how can I do that ?
Thanks

**Comment by dgibbs64** [comment]
you could google it. I found the answer in 10 seconds with google. Also, Linux can handle process management by itself.
