### ISSUE TITLE
Players-Count for gmod (details) shows Player Info, not count

### ISSUE THREAD

**Issue by ThisIsTenou** [GameServerManagers/LinuxGSM#2794]
Hey,
when running ./gmodserver details in the line "Players: xx/xx", instead of showing how many people are online (eg 3/16), it shows the player details. It only works for 0/xx, when there are no players online.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/57889616/78041823-851d2580-7371-11ea-81da-d0bda9ce2d6e.png)
I'm running Ubuntu 18.04 and the latest version of both gmod & lgsm.

**Comment by dgibbs64** [comment]
This might have been fixed now just need to check

**Comment by Quafi** [comment]
Well, now it always displays "0/xx", no matter how many players are online. Tested with the newest version of both the game and lgsm.

**Comment by dgibbs64** [comment]
Thanks for the update

**Comment by h3o66** [comment]
Just checked, this seems to be fixed.
Please ensure that you are on the latest LinuxGSM release.
