### ISSUE TITLE
CSGO: csgo-pug-setup to modlist

### ISSUE THREAD

**Issue by b-reich** [GameServerManagers/LinuxGSM#2795]
## User Story

As a serveradmin, I want an csgo-pug-setup  added to mod list so that i can easy install this mod.

## Basic info

* **Distro:** Debian 10
* **Game:** Counter-Strike: Global Offensive
* **Command:** mod
* **LinuxGSM version:** "v20.1.5"

## Further Information
I would be very happy if [csgo-pug-setup](https://github.com/splewis/csgo-pug-setup) is added as a mod. Its a very usefull plugin for lan parties. Its a bitte more simple then the existing get5 plugin.

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by h3o66** [comment]
Do you mean this mod ?
https://github.com/splewis/csgo-pug-setup
Please add the link to the mod to such an issue.

**Comment by b-reich** [comment]
Yes, it is. I allready add the link... But I mess with the markdown. I am sorry

**Comment by h3o66** [comment]
@b-reich see linked PR, if you want to test this

**Comment by b-reich** [comment]
I will test this tomorrow.

**Comment by b-reich** [comment]
how can I test this?

**Comment by h3o66** [comment]
The easiest would be to get the mod_list.sh file from the develop branch and seap out the current on and try to install the mod.

Alternative, set the branch in the server script and follow this guide:
https://docs.linuxgsm.com/support/faq#how-do-i-change-the-linuxgsm-branch

**Comment by b-reich** [comment]
```
./csgoserver mi
/home/csgoserver/lgsm/functions/mods_list.sh: line 38: ${}: bad substitution
/home/csgoserver/lgsm/functions/mods_list.sh: line 39: ${}: bad substitution
```

sourcemod and metamod are working.

I got the following error while installing pug
```

Installing PUG
=================================
clearing mod download directory /home/csgoserver/lgsm/mods/tmp...OK
creating mod download directory /home/csgoserver/lgsm/mods/tmp...OK
fetching  ...FAIL
```

I also notice while downloading strange characters
```
....
creating mod download directory /home/csgoserver/lgsm/mods/tmp...OK
                                                    ##O#-  #
################################################################################################################# 100.0%
extracting sourcemod-1.10.0-git6494-linux.tar.gz...OK
...
```

**Comment by h3o66** [comment]
thanks for testing, fixed with the additional commit
