### ISSUE TITLE
Deprecate 32-bit support

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2801]
## User Story

As a developer, I won't remove support and instructions for setting up 32-bit distros so that I can save time and not worry about something that likely no one actually uses..

## Basic info

* **Distro:** 32-bit distros
* **Game:** All

## Further Information

All CPU's in the last 10+ years run 64-bit because of this there is no reason why 32-bit distro is required. It is highly likely that no one uses it anymore. Because of this, I want to remove references to 32-bit in both code and the website.

**Comment by h3o66** [comment]
well - then maybe mark as well 32bit server as not supported anymore on newer distributions like centos 8 and ubuntu 20.04, like in issue #2839 and #2849

**Comment by dgibbs64** [comment]
TF2 is not working with Ubuntu 20.04 and CentOS 8. Valve will have to make some changes with TF2 to get it working. TF2 is the only server to have this issue reported currently

**Comment by dgibbs64** [comment]
I have made changes to remove 32-bit distros from the website. Only 64-bit distros now supported. This will save complications when changing dependency requirements
