### ISSUE TITLE
[Server Request] Last Oasis

### ISSUE THREAD

**Issue by make2019** [GameServerManagers/LinuxGSM#2808]
## What game server would you like adding?

Last Oasis - Dedicated Server

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

920720

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by h3o66** [comment]
Looks like there is only a linux branch for the gameserver:
https://steamdb.info/app/920720/depots/

I could not find a setup howto for the server and that it is only allowed to be downloaded by owners of the game.
Imho this is hard to setup for ppl that do not own the game.

**Comment by make2019** [comment]
yeah,I mean I want to set up "Last Oasis - Dedicated Server" ,but LinuxGSM(https://linuxgsm.com/servers/) does not have the server  ,would you provide the  Last Oasis in LinuxGSM  like other games?

**Comment by h3o66** [comment]
LGSM does not have yet the support for it, if someone who has the game is willing to add the support for this, it would be possible.
Regards

**Comment by make2019** [comment]
yeah ,if nobody I will do ,but I do not know how to do.Can show me some information about how to 
build a new server  by LinuxGSM, and  then publish it  in LinuxGSM ,for the best way , you can give me an example or give me link.
Best Regards.

**Comment by UltimateByte** [comment]
https://dev-docs.linuxgsm.com/

**Comment by make2019** [comment]
can not the Last Oasis - Dedicated Server(920720)   use?  
from https://steamdb.info/app/920720/,I get error message " ERROR! Failed to install app '920720' (No subscription)".

**Comment by Grimston** [comment]
That errors means you need to own the game, so you need to login to steam first with an account that owns it and then install it.

**Comment by make2019** [comment]
I have buy the game ,and login with my steam account .then install ,it still  get the error message 
I find  the Last Oasis - Dedicated Server ReleaseState "unavailable"  I guess maybe  cause the error.but I can not determine. does anyone have the same error ?

Best Regards

**Comment by cchambers** [comment]
> I have buy the game ,and login with my steam account .then install ,it still get the error message
> I find the Last Oasis - Dedicated Server ReleaseState "unavailable"
> ( in https://steamdb.info/app/920720/info/ ) ,I guess maybe cause the error.but I can not determine. does anyone have the same error ?
> 
> Best Regards

I am having the same issue. :/

**Comment by fsdsoyu** [comment]
me2

**Comment by BearGryllsTV** [comment]
We are also getting the same issue, I have purchased the game. I have it installed on my personal machine but when i try to download it on our Centos7 box it has the ERROR! Failed to install app '920720' (No subscription)"

I see community servers up for it already there must be a way of getting on online. Does anyone have any ideas?

**Comment by ju-ce** [comment]
Not for now, read here: https://forum.lastoasis.gg/threads/community-servers.45/

**Comment by h3o66** [comment]
Currently i do not see any way to do this.

Taken from their help site:
https://lastoasis.zendesk.com/hc/en-us/articles/360043197711-Can-we-host-dedicated-private-servers-

> You will be able to host dedicated community servers through our partner, Nitrado. Server files may be available to enable hosting private servers at some point during the Early Access phase.

**Comment by Claiyc** [comment]
This should be reconsidered as ServerFiles for LastOasis have recently been released.
Although LastOasis currently doesn't have a great player-base, for server administrators this is some really exciting technology - something I haven't seen in any other game before. Would like to see it in lgsm.

It also seems to be relatively stable (was able to set it up without any problems on the first try on deb10).

Some more info:
- https://bit.ly/LOselfhostingguide 
- serverfiles require steam authentication
