### ISSUE TITLE
Review battlefield 1942 support

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2809]
## User Story

battlefield 1942 support needs to be checked

## Further Information

[ERROR ] Details bf1942server: Unable to detect server engine.

**Comment by seanwittmeyer** [comment]
I am having the same issue attempting to run the server on an AWS EC2 instance running Amazon Linux / Ubuntu 16.04.5 LTS

**Comment by h3o66** [comment]
~Closed
bug fix in version 20.3.0 included
