### ISSUE TITLE
[Teamspeak] - Adding Support for TSDNS

### ISSUE THREAD

**Issue by gOOvER** [GameServerManagers/LinuxGSM#281]
It would be great, when the Script also can handle TSDNS from Teamspeak3.

**Comment by dgibbs64** [comment]
Looking at TSDNS im not sure that the script would be required to do.

**Comment by gOOvER** [comment]
I wozld be only a nice feature, because I'm sometimes Lazy :D and i must switch everytime to the Folder /tsdns and start it manually

**Comment by dgibbs64** [comment]
Does TSNS have a script or something? Because you can set it to run on boot or setup a symbolic link to the script.

**Comment by dgibbs64** [comment]
Useful doc for possible future development http://lastconnect.net/en/tsdnsdoc/

**Comment by UltimateByte** [comment]
Wow, i thought several times about such a feature, i didn't even know it was existing !
I'd love to work on it !
I'll check if that's doable, then tell you.

**Comment by UltimateByte** [comment]
Well, after investigating.... I don't really see how LGSM could help for tsdns...
You have to manually edit a textfile anyways so.... Except displaying informations about it in ./ts3server details, i don't really see the point.

**Comment by UltimateByte** [comment]
I'll assume i didn't miss anything, and tdns is supposed to be added by the user if he wishes to.
