### ISSUE TITLE
Ip different

### ISSUE THREAD

**Issue by fsiarazvan** [GameServerManagers/LinuxGSM#2810]
Hello! I am on a ubuntu server with counter strike 1.6 server and i need some info ... 

How i can set an ip with the server to go online . is getting my internal ip and how i can set max player ? i tried in server.cfg but no result

So in the console server starts with private ip 172.x.x.x ... Not with my internet ip 32.x.x.x

So how to edit command line to start with my internet ip ? 
![21212](https://user-images.githubusercontent.com/26331073/78816601-a073da80-79da-11ea-9989-0b760139b33d.png)

PS : How to make server to show in INTERNET list ? on couter-strike servers

**Comment by h3o66** [comment]
well, the server can only bind to the ip you have on your interfaces - if you do not have it there, it is natted/forewarded to your server.
This should be not an issue.
Can you connect to the server with the external ip ?

**Comment by UltimateByte** [comment]
Hello,

You need to bind your game server to a physical interface IP of your machine; then do port forwarding of game server ports from the router, to route through the local physical interface IP of your server.

See https://docs.linuxgsm.com/configuration/ports

As this is a non script issue, this will be closed.
For further assistance, please use Discord: https://docs.linuxgsm.com/support
