### ISSUE TITLE
./csgoserver don't work

### ISSUE THREAD

**Issue by Htek67** [GameServerManagers/LinuxGSM#2811]
* CS:GO server
* Debian 8
* Linuxgsm
* Command ./csgoserver stop

Hello,

I try to stop my server but nothing happens and nothing appears in the console.
On my test vps which have the same setting it works very well.

I post you 2 screen
![d6801472f6447221e3c6d1711ccd4dbf](https://user-images.githubusercontent.com/31394991/78731102-06ab1f80-793f-11ea-92b9-b9cb5e1dae68.png)
![1aaccebc350e47be60719813823f9560](https://user-images.githubusercontent.com/31394991/78731130-1d517680-793f-11ea-8863-8da8ca1c9b48.png)

Will I have to reinstall the server?

**Comment by Grimston** [comment]
While this is not the place for this (Discord is better for this type of issue) You might want to share the cfg file in question.

**Comment by h3o66** [comment]
please do 2 things:
update lgsm and upgrade your system.

Debian 8 is Already EOL.
please upgrade to debian 9 or 10

as well please share the configs what Grimston already mentioned

**Comment by h3o66** [comment]
~closed
No update for more than 10 days from issue creator.
For further support you can ask on discord.
