### ISSUE TITLE
ROServer _default.cfg contains formatting error causing server not to start

### ISSUE THREAD

**Issue by AlbinoJack** [GameServerManagers/LinuxGSM#2812]
## User Story

When attempting to start the ROServer a miss-typed line in _default.cfg causes the command-line launch parameters to not find the executable and fail to launch to server.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Red Orchestra: Ostfront 41-45]
* **Command:** [Start]
* **LinuxGSM version:** [v20.1.5]

## Further Information

After updating LGSM version sometime in the past few months the ROServer failed to start, citing an executable was not found.

##Found a miss-typed line in the _default.cfg file for ROServer under:

##Game Server Directories
serverfiles="${rootdir}/serverfiles"
systemdir="${serverfiles}/system"
executabledir="${systemdir}"
executable="./ucc-bin"servercfgdir="${systemdir}"
servercfgdir="${systemdir}"
servercfg="${selfname}.ini"
servercfgdefault="default.ini"
servercfgfullpath="${servercfgdir}/${servercfg}"
compressedmapsdir="${rootdir}/Maps-Compressed"

##Incorrect line is line 153 of the file:
[...]
executable="./ucc-bin"servercfgdir="${systemdir}"
[...]

##Corrected line should exclude characters after column 23 
executable="./ucc-bin"

##Characters currently printed past column 23 on line 153 are duplicates of line 154 and shifted up to interfere with the executable line.

## To Reproduce

Steps to reproduce the behaviour:
1. Command: ./roserver st
4. See error:
[ FAIL ] Starting roserver: executable was not found
* /servers/roserver/serverfiles/system/system

## Expected behaviour

Server successfully starts after altering config-lgsm file to remove incorrect, duplicate, code.

**Comment by h3o66** [comment]
see mentioned pull request that should fix that
