### ISSUE TITLE
Migrate soldat to steam version

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2817]
## User Story

Soldat have released on steam, so its better migration the install file source to steam

## Further Information

https://store.steampowered.com/app/638490/Soldat/

## Further Reading

https://steamdb.info/app/638500/

**Comment by dgibbs64** [comment]
Getting invalid platform currently. I am on the Soldat discord server waiting to a response from a dev. Hopfully we can get this updated soon
