### ISSUE TITLE
steamcmd not in repo for Ubuntu 14.04

### ISSUE THREAD

**Issue by dvdvideo1234** [GameServerManagers/LinuxGSM#2819]
Issues raised here are **ONLY** for:
* LinuxGSM bugs.
* Feature suggestions.

## User Story
I tried installing a linux server for classic CS1.6 and it says `SteamCMD` is still missing
During the installation i was missing `jq`, `netcat`, and `steamcmd` shown in red under
```sql
Checking Dependencies
=================================
```
I cancelled the server installation and installed these manually, however `steamcmd` was not located
even I put it in `LinuxGSM/steamcmd`. It just shows that there is no such dependency present:
```
Server:/var/Volume00/LinuxGSM$ sudo apt-get install steamcmd
[sudo] password for XXXX: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package steamcmd
```

## Basic info

* **Distro:** [Ubuntu 14.04]
* **Game:** [Counter strike 1.6]
* **LinuxGSM version:**
```
Server:/var/Volume00/LinuxGSM$ git  log -1 --pretty
commit 9e5377086bbbb0bc065c5a8990b25c3d472c1d20
Merge: 3ae32af 0257457
Author: Daniel Gibbs <me@danielgibbs.co.uk>
Date:   Tue Mar 24 22:49:08 2020 +0000

    Merge branch 'hotfix/v20.1.5'

```

## Further Information

The server manager better use `curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -`

## To Reproduce

Steps to reproduce the behaviour:
1. Clone `LinuxGSM` in a folder
2. Execute `Server:/var/Volume00/LinuxGSM$ ./linuxgsm.sh install csserver`
3. Select CS1.6
4. Executable created `./csserver`
5. Execute `Server:/var/Volume00/LinuxGSM$ ./csserver install`
6. Installed `SteamCMD` is not present
7. Start the server...
```
Server:/var/Volume00/LinuxGSM$ ./csserver start
Warning! Missing dependencies: steamcmd
Information! Automatically installing missing dependencies.
```

## Expected behaviour
When `SteamCMD` is `curl`-ed and extracted in the `steamcmd` folder to pass its dependency as green.

**Comment by gOOvER** [comment]
UBUNTU 14.04 is since 1 year EOL ;) Use a newer Version and try again

**Comment by gOOvER** [comment]
Use a newer Ubuntu like 18.04 ;)

**Comment by dvdvideo1234** [comment]
> UBUNTU 14.04 is since 1 year EOL ;) Use a newer Version and try again

No, because ;)
1. No need to change the distro version with an update when it is already working on `prod`
2. [The board][ref-2] is designed to work with Ubuntu 12.
3. This is remote machine and maintenance requires me going out during coronavirus epidemic
4. Any major update has potentially catastrophic outcome which will require me going out.
5. Valve have already defined the way of installing `steamcmd` using [curl and tar commands][ref-1].
6. There is really no point of invoking `sudo apt-get install steamcmd` as they do not support this way of installation.
7. To me `LinuxGSM` must check the `steamcmd` folder if there is available installation

[ref-1]: https://developer.valvesoftware.com/wiki/SteamCMD#Linux
[ref-2]: https://www.asrockrack.com/general/productdetail.asp?Model=C2750D4I#Specifications

**Comment by dvdvideo1234** [comment]
How can I do the manual steps of `sudo apt-get install steamcmd` ?

**Comment by dvdvideo1234** [comment]
I can do the manual steps of `sudo apt-get install steamcmd`, will evaluate to copying this into `/etc`, but I do not think this is the point here as it beter use the local installation `/steamcmd` folder.

**Comment by dgibbs64** [comment]
1. You shouldn't be using unsupported distros because of security risks. Plus if Canonical isn't supporting it then I'm not sure why I should.
2. It is unlikely that you will have an issue upgrading because of a motherboard.
3. Do you not have some sort of KVM access? Its pretty standard for remote servers.
4. same as above
5. I wrote most of the instructions on the SteamCMD wiki page.
6. I have decided to start using the packages if they are available.
7. If the server is not Ubuntu or Debian then it will use curl. 

I had waited several years before using the steamcmd packages to ensure that the package we're available on all supported Ubuntu versions before deciding to use them. I did not anticipate people still using unsupported distros (14.04 has been out of support for a year at this point) especially since game servers regularly use the latest software.

What I will do is add a bypass for 14.04 so it will not look for the steamcmd package and instead, it will use the curl version. It will be ready for release 20.2.0. I do however highly recommend you upgrade at the next available opportunity.

**Comment by dvdvideo1234** [comment]
Thank you!

It passes now !

**Comment by dgibbs64** [comment]
It shouldn't as I haven't released the update to the master branch yet 😬

**Comment by dvdvideo1234** [comment]
> It shouldn't as I haven't released the update to the master branch yet

Your change persist [here](https://github.com/GameServerManagers/LinuxGSM/commit/b30b36fd6df919c7815deca8a01bd47289838fb6) which is made in the [develop branch](https://github.com/GameServerManagers/LinuxGSM/tree/develop) :)

**Comment by dvdvideo1234** [comment]
Yes, I will likely upgrade it to Ubuntu 18.04, will just wait for the corona virus to pass out. :)

**Comment by dgibbs64** [comment]
@dvdvideo1234 that probably is a better way. However, in this case, I did the quick way because of limited time and limited use case for this issue.

Secondly, steamcmd will always install itself in the ${HOME} directory no matter where steamcmd is downloaded. A symlobic will probably work
