### ISSUE TITLE
Request: Running with Rifles LinuxGSM Please!

### ISSUE THREAD

**Issue by CyberCam1969** [GameServerManagers/LinuxGSM#2824]
## What game server would you like adding?
Running with Rifles

## Can you link to any tutorials or guides?
http://runningwithrifles.com/phpBB3/viewtopic.php?f=9&t=1843
http://www.runningwithrifles.com/phpBB3/viewtopic.php?f=4&t=3492
https://steamcommunity.com/sharedfiles/filedetails/?id=1455067703

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).
270150

## Is the server supported on Linux?
Yes

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by Frisasky** [comment]
duplicated #359
