### ISSUE TITLE
[Server Request] Assetto Corsa

### ISSUE THREAD

**Issue by raggijons** [GameServerManagers/LinuxGSM#2825]
## What game server would you like adding?

[Assetto Corsa]

## Can you link to any tutorials or guides?

https://b.joaoubaldo.com/installing-assetto-corsa-dedicated-server-in-linux.html

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

302550

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [X] Yes
* [ ] No

**Comment by h3o66** [comment]
A bit newer howto with the current binary:
https://steamcommunity.com/app/244210/discussions/0/2828702373004724010/
