### ISSUE TITLE
Ark: SE unable to create Primitive+ Server

### ISSUE THREAD

**Issue by mglenn527** [GameServerManagers/LinuxGSM#2826]
I've been trying to create a primitive+ server with LGSM, but have yet to find the proper way to add the prim+ mod to the server, and google isn't providing much assistance. Has anyone had success in this area?

**Comment by h3o66** [comment]
maybe you want to try this:
add `ActiveMods=111111111` to the `gus.ini`

They also noted that a clean servver would be preferred.

Source (in german):
https://arkforum.de/thread/21662-primitive-auf-einem-server-laufen-lassen/

More info for the ark settings:
https://docs.linuxgsm.com/game-servers/ark-survival-evolved

**Comment by mglenn527** [comment]
Thanks for trying to help. I've given that a shot, when the server is run, the server console shows:

Downloading item 111111111 ...
ERROR! Download item 111111111 failed (File Not Fount).CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.

I've tried a few different recommendations from different forums, and this is as close as I've gotten

**Comment by dgibbs64** [comment]
closing as related to a mod, not a specific LinuxGSM issue. docs are also now available on how to add mods to ARK https://docs.linuxgsm.com/game-servers/ark-survival-evolved#mod-support
