### ISSUE TITLE
LinuxGSM function directory content is not executable

### ISSUE THREAD

**Issue by dvdvideo1234** [GameServerManagers/LinuxGSM#2828]
Issues raised here are **ONLY** for:
* LinuxGSM bugs.

For general support visit the **[LinuxGSM-Support](https://linuxgsm.com/support)**.

## User Story
As an IT guy, I cloned the master branch, started installing LinuxGSM and it crashed with:
```bash
mangos@mangos-vb:~/Documents/LinuxGSM$ ./csserver install
[ FAIL ] Install csserver: Permissions issues found

Information! The following files are not executable:
File
/home/mangos/Documents/LinuxGSM/lgsm/*.*
```

## Basic info

* **Distro:** [Ubuntu 16.04]
* **Game:** [Counter strike 1.6]
* **Command:** [`./csserver install`]
* **LinuxGSM version:**
```
commit 9e5377086bbbb0bc065c5a8990b25c3d472c1d20 (HEAD -> master, tag: v20.1.5, origin/master, origin/HEAD)
Merge: 3ae32af0 02574574
Author: Daniel Gibbs <me@danielgibbs.co.uk>
Date:   Tue Mar 24 22:49:08 2020 +0000

    Merge branch 'hotfix/v20.1.5'

```

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.
1. Go to `/home/mangos/Documents/LinuxGSM/lgsm/functions` 
2. `sudo chmod +x *.*`

## To Reproduce

Steps to reproduce the behaviour:
1. Clone LinuxGSM
2. `./linuxgsm install csserver`
3. Select `Counter strike 1.6`
4. Error is present

## Expected behaviour
Error should not be present

**Comment by dgibbs64** [comment]
My first question is why are you cloning the repo instead of following the correct installation instructions.

**Comment by dvdvideo1234** [comment]
Hmm, never noticed. Just wanted to let you know ;)

**Comment by dgibbs64** [comment]
LinuxGSM puts in the correct permissions when a function file is first downloaded. By cloning the repo you are bypassing that proccess.

**Comment by dvdvideo1234** [comment]
For the correct installation you mean the one [described here](https://linuxgsm.com/lgsm/l4dserver/)
