### ISSUE TITLE
Mordhau - Updating servercfg does not apply propertly 

### ISSUE THREAD

**Issue by mackcoding** [GameServerManagers/LinuxGSM#2834]
I am running multiple instances of Mordhau. I setup "Server1.ini", "Server2.ini" for different configurations. LinuxGSM shows the correct server name when using "details" however the server name is not applied. Upon further inspection I found that the start parameters do not update the GameIni:

```
fn_parms(){
parms="Mordhau ${defaultmap} -log -MultiHome=${ip} -Port=${port} -BeaconPort=${beaconport} -QueryPort=${queryport}"
}
```

Adding the following parameter fixes the issue:

`-GameIni=${servercfgfullpath}`

With the full command being:
```
fn_parms(){
parms="Mordhau ${defaultmap} -log -MultiHome=${ip} -Port=${port} -BeaconPort=${beaconport} -QueryPort=${queryport} -GameIni=${servercfgfullpath}"
}
```

**Comment by h3o66** [comment]
for sure i can create a pull for this, but for every multi server the user needs to enter then the full path of the config in the instance config ?

**Comment by mackcoding** [comment]
Unless you are running every instance of a server with the same exact server name, players, game types, maps, etc. 

I'm running duel servers - so I have max 2 player slots, max 4 player, max 8, etc. And each server is labelled as "MyServer #1", "MyServer #2" 

To answer your question, yes, I would assume people would like to use different configs.

**Comment by h3o66** [comment]
Created now a PR for this.
