### ISSUE TITLE
Feature suggest : download script files together

### ISSUE THREAD

**Issue by DefiedParty** [GameServerManagers/LinuxGSM#2835]
## User Story

As a China user, I want lgsm can download script together so that in China we can install lgsm easily.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** [v12.34.56]

## Further Information

Download script together is necessary,in China GitHub often affected by GFW，so download script files often fail,if lgsm can download script files together until succes,we can install a server simpler.

## Further Reading

FAIL....FAIL....FAIL....

**Comment by dgibbs64** [comment]
That's interesting. I'm sure we can come up with a method to download all the files or have an alternative web address to try if it fails.

**Comment by DefiedParty** [comment]
@dgibbs64 That is very useful, please add these functions if you can.Thank you!

**Comment by DefiedParty** [comment]
gitee maybe a good choice for download files.It can one click import GitHub repository , website:gitee.com

**Comment by dgibbs64** [comment]
Just checked and it appears bitbucket is not blocked in China. So I could use that as a secondly location. This will also solve the issue of a backup location if github goes now solving 2 problems :)

**Comment by h3o66** [comment]
~Closed
feature in version 20.3.0 included
