### ISSUE TITLE
Missing Dependency for CentOS8 that can't be found: gperftools-libs.i686

### ISSUE THREAD

**Issue by Drixevel** [GameServerManagers/LinuxGSM#2839]
## User Story

I've been using LinuxGSM for a while and recently moved some of my servers over to a new host with CentOS 8 installed instead of Ubuntu. Everything so far has been smooth except there's a dependency which is listed as required but isn't available.

## Basic info

* **Distro:** [CentOS 8 - centos-release-8.1-1.1911.0.9.el8.x86_64]
* **Game:** [Team Fortress 2]
* **Command:** [Start/Stop/Restart]
* **LinuxGSM version:** [v20.1.5]

## Further Information

Need an update on the required dependencies or I'm missing something.

## To Reproduce

While doing this:
`command >> sudo yum install epel-release`
`Last metadata expiration check: 0:32:48 ago on Fri 24 Apr 2020 12:41:44 AM EDT.`
`Package epel-release-8-8.el8.noarch is already installed.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

Using these commands results in this:
`Command >> ./tf2server start/stop/restart`
`Warning! Missing dependencies: gperftools-libs.i686`
`Warning! tf2-server does not have sudo access. Manually install dependencies.`

When attempting to install the dependency:
` command >> sudo dnf install gperftools-libs.i686`
`Last metadata expiration check: 0:30:08 ago on Fri 24 Apr 2020 12:41:44 AM EDT.`
`No match for argument: gperftools-libs.i686`
`Error: Unable to find a match: gperftools-libs.i686`

(I might be missing something obvious, sorry if I am)

**Comment by Grimston** [comment]
I don't have an active installation of CentOS 8 to test with but can you try to install `gperftools` as that package includes gperftools-libs
```shell
sudo dnf install gperftools
```

**Comment by Drixevel** [comment]
`command >> sudo dnf install gperftools`
`Last metadata expiration check: 0:36:18 ago on Fri 24 Apr 2020 12:47:50 PM EDT.`
`Package gperftools-2.7-6.el8.x86_64 is already installed.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

Seems like it leads to the same results. I'm pretty sure I tried this already as well.

**Comment by h3o66** [comment]
It looks like this 32bit library is not there anymore to install
I guess they did the same like ubuntu and removed the 32bit support

**Comment by dgibbs64** [comment]
TF2 is not working with Ubuntu 20.04 and CentOS 8. Valve will have to make some changes with TF2 to get it working

**Comment by AhRoon** [comment]
Update: I contacted to TF Team, hopefully they read my message and resolve this issue on next update.

**Comment by dgibbs64** [comment]
I have removed gperftools-libs.i686 as it is no longer required. However, libcurl.i686 has an unless dependency on CentOS 8. So although TF2 now works on Ubuntu 20.04 it is still broken on CentOS 8
