### ISSUE TITLE
Simplify Server Version Control ?

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#2840]
I have been working on & web based version of LGSM and had some problems with an easy way to check if a server is up to date, my solution was to use GameQ or gamedig to query the running server for it's version & game id (which both utilities do) .. Next bit was to query steam for the response, which I used there api to do with the following url 
`https://api.steampowered.com/ISteamApps/UpToDateCheck/v1/?format=xml&appid=<game id>&version=<version>`
In the above case the return is formatted in XML (that suits what I am doing) but it will return json.
XML response from the call to the api is such -
`<response>
<success>true</success>
<up_to_date>false</up_to_date>
<version_is_listable>false</version_is_listable>
<required_version>**version number**</required_version>
<message>Your server is out of date, please upgrade</message>
</response>` 
for an out of date server and
`<response>
<success>true</success>
<up_to_date>true</up_to_date>
<version_is_listable>true</version_is_listable>
</response>` 
for an up to date one. This method of checking the server version is some what quicker than the current method.
**Test Data**
Fistfull of frags game id 317360
current server version   471
CS source game id 240
current server version 5394425
couple of gotcha's 

1. if you enter a server version higher than current, the server is up to date
2. some steam games have point releases (e.g 1.2.2) which then have to be converted  to an integer (e.g 122) 
3. games that are not steam supplied do not appear in their data set (e.g minecraft)

To perhaps help I have coded & cli php script that takes the 2 arguments and currently returns an array however this could be modded just to echo the results to the terminal where bash could read it .
Just a thought

**Comment by dgibbs64** [comment]
Would the output of update put in to a text file work?

![image](https://user-images.githubusercontent.com/4478206/80236281-d8258800-8652-11ea-90b7-cf0675b6beb7.png)

**Comment by JimTR** [comment]
I guess you mean using my php rather than curl to get the response but yep that's doable

**Comment by JimTR** [comment]
PHP Version attached
rename the attached file to something with a .php extension
e.g cli_server_check.php
ensure you have the following installed
1. PHP CLI version minimum
2. gamedig
I have added a shebang line so you should be able to run it straight from the command line but if it fails just run it under php.
I have done very basic error checking so it may fail if you give an invalid command line option.
but if you run the file with no options it will give you the options required.
On completion two files are created, local.txt & remote.txt which contain the our server version & the most up to date from steam.
loads of comments in the file so you should be able to convert this to bash 
[cli_server_check.txt](https://github.com/GameServerManagers/LinuxGSM/files/4532785/cli_server_check.txt)

**Comment by h3o66** [comment]
I do not think this is easy useable, as you need to get the versions.
Might be easier to use this:
https://github.com/steamcmd/api

~close
