### ISSUE TITLE
Fix Post Scriptum parameters to match actual server

### ISSUE THREAD

**Issue by Limb** [GameServerManagers/LinuxGSM#2847]
## User Story

The current fn_parms function for Post Scriptum uses a "?" between commands instead of a space. This causes all parameters to be ignored by the server.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Post Scriptum]
* **Command:** [start]
* **LinuxGSM version:** [v20.2.0]

## Further Information

We need to fix the fn_parms function to use the correct format. I have a patch ready.

## To Reproduce

Steps to reproduce the behaviour:
1. Start a Post Scriptum server
2. See that any commandline parameters were ignored

## Expected behaviour
The parameters should be accepted and used.

**Comment by h3o66** [comment]
The linked pr was included in the release 20.3.0
