### ISSUE TITLE
Dependency installation is broken on Ubuntu Server 20.04 LTS

### ISSUE THREAD

**Issue by AhRoon** [GameServerManagers/LinuxGSM#2849]
# User Story
When I try installing dependency in Ubuntu Server 20.04 LTS, it says E: Unable to locate package libtcmalloc-minimal4:i386.

## Basic info

* **Distro:** Ubuntu Server 20.04 LTS
* **Game:** Team Fortress 2
* **Command:** sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 lib32stdc++6 steamcmd libcurl4-gnutls-dev:i386 libtcmalloc-minimal4:i386
* **LinuxGSM version:** v20.2.0

## Further Information

When I try installing dependency in Ubuntu Server 20.04 LTS, it says E: Unable to locate package libtcmalloc-minimal4:i386. It seems they removed some of  dependency after 20.04 update.

## To Reproduce

Steps to reproduce the behaviour:

**Comment by h3o66** [comment]
if i can see that right, ubuntu does not support this 32 bit lib anymore:
https://packages.ubuntu.com/search?suite=all&arch=i386&searchon=names&keywords=libtcmalloc-minimal4
With the search you can only find that the packed does not exist for ubuntu 20.04

**Comment by dgibbs64** [comment]
TF2 is not working with Ubuntu 20.04 and CentOS 8. Valve will have to make some changes with TF2 to get it working

**Comment by AhRoon** [comment]
I found the temporary solution about 32-bit libraries, is to install multilib. While Valve completely update their SteamCMD to 64-bit, this should be the temporary solution. (Thanks to Jai for solution!)
![I found the solution](https://user-images.githubusercontent.com/25527589/82663201-2f2a7700-9c6a-11ea-8735-2491b1a3de02.PNG)

**Comment by dgibbs64** [comment]
`libtcmalloc-minimal4:i386` is multilib in Ubuntu 20.04 they have removed libs that are not very widely used. So this will still not work

**Comment by JimTR** [comment]
add this to your sources.list
`deb http://cz.archive.ubuntu.com/ubuntu xenial main ` and 20.04 will install libtcmalloc-minimal4:i386

**Comment by AhRoon** [comment]
Thanks for tip! This should resolve the dependency issue on Ubuntu 20.04 for while :)

**Comment by AhRoon** [comment]
Update: I contacted to TF Team, hopefully they read my message and resolve this issue on next update.

**Comment by AhRoon** [comment]
@JimTR Tested on Linux Mint 20 Ulyana, tried to install with `deb http://mirror.kakao.com/ubuntu bionic main`, it says dependencies broken. Is there any fix about this? (Note: I tested with Ubuntu, it works better in there)

**Comment by Dragonisser** [comment]
Just installed 20.4.1 and it still wants it

![image](https://user-images.githubusercontent.com/4233773/89319921-18000080-d681-11ea-9bc3-1c533f7c905f.png)

**Comment by dgibbs64** [comment]
@Dragonisser are you using the latest version of LinuxGSM? This was fixed with the latest release

**Comment by Dragonisser** [comment]
> @Dragonisser are you using the latest version of LinuxGSM? This was fixed with the latest release

Since i had issues with updating the existing installation i thpught the reinstall would fix the issue which didnt seemed like. It works now tho.
