### ISSUE TITLE
not working  -NoBattlEye flag for ARK

### ISSUE THREAD

**Issue by kdulep** [GameServerManagers/LinuxGSM#2850]
* **Distro:** [CentOS8]
* **Game:** [ARK]
* **Command:** [start]
* **LinuxGSM version:** [v12.34.56]

## Further Information

`Commandline:  "Ragnarok?AltSaveDirectoryName=Ragnarok?listen?MultiHome=192.168.1.199?MaxPlayers=70?QueryPort=27015?RCONPort=27020?Port=7777 -automanagedmods -NoBattlEye"`

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'common.cfg'

```
fn_parms(){
parms="\"${defaultmap}?AltSaveDirectoryName=${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port} -automanagedmods -NoBattlEye\""
}

```
4. Start server, stop, check logs
Server Initializing with BattlEye Anti-Cheat Protection. If you do not wish to use BattlEye, please launch with -NoBattlEye
BattlEye successfully started.

## Expected behaviour
No battleye

##config
 ./arkserver dt

```
Command-line Parameters
=============================================================================================================================================================================================================================================================================================================================
./ShooterGameServer "Ragnarok?AltSaveDirectoryName=Ragnarok?listen?MultiHome=192.168.1.199?MaxPlayers=70?QueryPort=27015?RCONPort=27020?Port=7777 -automanagedmods -NoBattlEye"

```

**Comment by UltimateByte** [comment]
Hello,

This is a game server command that you added manually. Its implementation depends on the game server itself and LinuxGSM doesn't have control over this. Therefore, this issue will be closed.

Ultimately, people who bought the game usually shouldn't have to turn this kind of features off, so... This is really not a priority.

That said, if you do find a way to get this command working, we can add the settings in default available config for the game, in this case, feel free to re-open with useful info.
