### ISSUE TITLE
Mailgun EU API support

### ISSUE THREAD

**Issue by GrillGuth** [GameServerManagers/LinuxGSM#2856]
## User Story

As a EU located administrator, I want the "mailgun"-alert feature to support their EU API so that the feature is GDPR [[1]](https://eur-lex.europa.eu/eli/reg/2016/679/oj) compliant.

## Basic info

* **Command:** [alert]

## Further Information

Due to the GDPR [[1]](https://eur-lex.europa.eu/eli/reg/2016/679/oj) "mailgun" is offering a separate API for EU clients utilising EU based server infrastructure [[2]](https://www.mailgun.com/blog/we-have-a-new-region-in-europe-yall/). Only this API is GDPR compliant. Therefore, LinuxGSM should support this API.

Ultimately, LinuxGSM should provide a config entry called "mailgunapiregion" as part of the "# Mailgun Email Alerts" section. Options for this entry should be "us" (default) for the US API-endpoint and "eu" for the EU API-endpoint. Another approach could be the entry "mailguneuapi" with the options "0" (default) and "1" to avoid confusion for users outside the US or the EU.

The EU API is available through: api.eu.mailgun.net [[3]](https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions).
Therefore, "https://api.eu.mailgun.net/v3/${mailgundomain}/messages" should be used instead of "https://api.mailgun.net/v3/${mailgundomain}/messages" when the EU option is selected.

## Further Reading

[[1] https://eur-lex.europa.eu/eli/reg/2016/679/oj](https://eur-lex.europa.eu/eli/reg/2016/679/oj)
[[2] https://www.mailgun.com/blog/we-have-a-new-region-in-europe-yall/](https://www.mailgun.com/blog/we-have-a-new-region-in-europe-yall/)
[[3] https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions](https://documentation.mailgun.com/en/latest/api-intro.html#mailgun-regions)

**Comment by h3o66** [comment]
Hi @GrillGuth 
could you maybe test the connected PR for mailgun ?

To change the region to eu add `mailgunapiregion="eu"` to the common or server config.
