### ISSUE TITLE
Recent update broke Monitor

### ISSUE THREAD

**Issue by rip1980** [GameServerManagers/LinuxGSM#2858]
Been running LGSM servers, most cs+go and cs1.6 for years.  Today had a server go down and not restart.  No changes have been made to this instance for a long time.

Logged in and received the following on  trying to monitor downed server:

csserver4@dedibox:~$ ./csserver m
[  OK  ] Monitor csserver: Checking session: OK
[ ERROR ] Monitor csserver: Checking port: Unable to query queryport is not set: ERROR

Ran DT for some clues and it's all normal and as expected until we get to ports (note I run multiple servers on the same box, so this server is not on the base 27015 main or client ports on purpose.)  Also the error is the same from crashed state or running state (ie, restarting the server did not change monitor status, still error when it's running):

Command-line Parameters
====
./hlds_run -game cstrike -strictportbind +ip x.x.x.x -port 27020 +clientport 27006 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 32 -pingboost 2 -sys_ticrate 1000

Ports
=====
Change ports by editing the parameters in:
UNKNOWN

Useful port diagnostic command:
[ ERROR ] Details csserver: Unable to detect server engine.

Status: ONLINE
=====

## Basic info
Ubuntu 18.04.4 LTS
CS1.6
Monitor
LGSM v20.2.0

Updating LGSM did not change anything, all scripts already up to date, also I have a cron job that updates the LGSM scripts, so not sure exactly when this broke, it went unnoticed until a server actually went down.

**_Incidentally, I found PD is also broken trying to create it for this report.  I can raise another bug report for that if desired._**

**Comment by dgibbs64** [comment]
just tested myself with no issues. try runing update-lgsm again

**Comment by rip1980** [comment]
Rebooted, ran ul, still seeing much the same.  Nothing in UL was picked up (all OK) but PD is working now, so it could have been hastebin itself in the middle of the night not being responsive.

Here are PDs of two instances acting the same:
https://hastebin.com/kinasutebi
https://hastebin.com/fiheruwixo

My guess is variables are being mangled somehow.  I did not find docs to manually tweak queryport.  Something like defined port not being made to equal queryport problem.  Maybe queryport = null?

The server is running, just monitor fails, running or not.  So when it did go down, it was not restarted.

Fully upto date 18.04.4 LTS fwiw, it gets updated regularly.

**Comment by dgibbs64** [comment]
Remove engine from your common.cfg. I'm guessing you copy pasted the whole of default.cfg. the engine name recently changed

**Comment by rip1980** [comment]
Thank You.

It was engine is cssserver.cfg  (Common was empty, I run my instances separately as they predate the common config thing really and I'm lazy.

## LinuxGSM Server Details
# Do not edit
gamename="Counter-Strike 1.6"
# engine="goldsource"
