### ISSUE TITLE
Cannot connect to cod4 server after updating LinuxGSM

### ISSUE THREAD

**Issue by methmal59** [GameServerManagers/LinuxGSM#2860]
I updated LinuxGSM and changed the cod 4 MOD I was using. Then I started the server, and everything looked fine. Even when I tried using "./cod4server details", it said that the server is connected. But I couldn't connect to the server as a player. I tried removing the MOD and then I could connect to the server. The problem happens when I set some command line arguments in "common.cfg" file.

So I reinstalled the VPS OS and tried again. Still, it says the server is online. But I can't connect to it. This only happened after I updated LinuxGSM

I have another server running which I didn't update yet and it's working fine.

**Comment by Raamkonijn** [comment]
I had exactly the same experience with cod2server. Everything looks okay in the details and console, but unable to connect. I had done the exact same install a few weeks ago with an older version of LinuxGSM (v20.2.0) which was working perfect. The new install (v20.3.3) wouldn't work. After using the older version (v20.2.0) everything worked again.

**Comment by dgibbs64** [comment]
the cod4 archive has been updated to a newer version of cod4x 
cod2 however has not changed apart from now using tar.xz instead of tar.bz2

**Comment by methmal59** [comment]
The updated cod4 is not working right now. While using pml220, a red error message appears on the screen on every client saying 'Invalid IWD files detected'. I tried many things but none of them worked, so I had to edit the mod.ff of pml220 and remove all the warning messages.

**Comment by dgibbs64** [comment]
thanks I will be testing this out

**Comment by dgibbs64** [comment]
tested can confirm its broken. Not sure the exact cause yet but I will get a hotfix out when it's sorted.

**Comment by dgibbs64** [comment]
scratch that it was a port binding issue. the server is working for me

**Comment by dgibbs64** [comment]
does the error state what files are missing?

**Comment by methmal59** [comment]
nope, just that invalid IWD files detected

**Comment by dgibbs64** [comment]
I re-downloaded and installed and I am unable to replicate the issue.
