### ISSUE TITLE
[Rust] Console does not work

### ISSUE THREAD

**Issue by Kolpoa** [GameServerManagers/LinuxGSM#2861]
I am running newest Debian and if I execute ./rustserver console on the machine the only output is this:
```
Set current directory to /home/rustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated
```
I cannot input any commands. How do I fix this bug?

**Comment by dgibbs64** [comment]
There is no console output for rust. This is normal behaviour.
