### ISSUE TITLE
rwserver install issue. 

### ISSUE THREAD

**Issue by fearedazz** [GameServerManagers/LinuxGSM#2862]
## User Story

As a Server Owner, I want complete the install so that i can get my game started.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Rising World]
* **Command:** [Install]
* **LinuxGSM version:** [v12.34.56]

## Further Information

I dont know how to fix it. please help

## To Reproduce

Steps to reproduce the behaviour:

## Expected behaviour
 https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/config-default/config-lgsm/Relentless Few/_default.cfg
-bash: https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/config-default/config-lgsm/Relentless: No such file or directory

**Comment by dgibbs64** [comment]
What is Relentless Few? That isn't a game server. It looks like you have altered the configs

**Comment by h3o66** [comment]
Seems like you altered something that was not expected to be chnaged.
Please attach or comment with the changes you did in LGSM - as alternative please seek for help on the discord server.
