### ISSUE TITLE
[CSGOServer] Default Slots Monitor

### ISSUE THREAD

**Issue by JamsRepos** [GameServerManagers/LinuxGSM#2863]
## User Story

As a CS:GO Server Owner, I want an explanation as to why my servers crash/restart to 20 player slots so that I can get it fixed to it goes to it's custom set amount.

## Basic info

* **Distro:** Ubuntu 16.04
* **Game:** Counter-Strike: Global Offensive
* **Command:** Monitor
* **LinuxGSM version:** v20.2.0

## Further Information

When a server seems to be detected as down, the server will restart and come back up with 20 player slots. I have an already defined variable for this which it seems to ignore. It seems to only happen with the monitor command detecting the server as down. If I use ./csgoserver restart it will use the specified value. 

## To Reproduce

Steps to reproduce the behaviour:
1. Setup a CS:GO server.
2. Assign a custom slots value in common.cfg/csgoserver.cfg.
3. Crash the server, wait till the monitor restarts it.
4. See you have 20 player slots of which you did not specify.

## Expected behaviour

Monitor simply see's the server in a down state, turns it back on with all your custom specifications.

**Comment by WorthlessJ** [comment]
This might be because setting Max playercount in commandline is supposed to be deprecated. Follow the directions for setting playercount in your gamemodes_server.txt file and see if the problem persists. There is a example file called gamemodes_server.txt.example inside /serverfiles/csgo/ .

**Comment by dgibbs64** [comment]
Assuming now working. Will auto-close if no response

**Comment by LubricantJam** [comment]
There's still cases of this happening, the only fix I've found is to just restart the server and it will then rectify. 

Very latest LGSM version too as I've got it automatically updating.

**Comment by dgibbs64** [comment]
Maybe restarting from a crash/lockup causes the issue and restarting again fixes it. I think this might be difficult to replicate
