### ISSUE TITLE
Not all instances are updated via update-lgsm on a multi instance game server

### ISSUE THREAD

**Issue by borzaka** [GameServerManagers/LinuxGSM#2868]
## User Story

As a multi instance game server owner, I want manage LinuxGSM and game server updates as easy as possible.
Now, I have problems, because not all the instances are updated with the `update-lgsm` command started from the first instance.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Counter-Strike: Global Offensive]
* **Command:** [update-lgsm]
* **LinuxGSM version:** [v20.2.0]

## Further Information

I setup my crons like this:
```
# Server #1
@reboot su - csgoserver -c '/home/csgoserver/csgoserver monitor' > /dev/null 2>&1
35 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver update' > /dev/null 2>&1
0 0 * * 0 su - csgoserver -c '/home/csgoserver/csgoserver update-functions' > /dev/null 2>&1

# Server #2
@reboot su - csgoserver -c '/home/csgoserver/csgoserver-2 monitor' > /dev/null 2>&1
34 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver-2 stop' > /dev/null 2>&1
40 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver-2 start' > /dev/null 2>&1

# Server #3
@reboot su - csgoserver -c '/home/csgoserver/csgoserver-3 monitor' > /dev/null 2>&1
34 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver-3 stop' > /dev/null 2>&1
40 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver-3 start' > /dev/null 2>&1
```

The `update` is updating game server files under every instance (because every instance is using the same files), but `update-functions` is only updating the first `csgoserver` instance, not `csgoserver-2` and `csgoserver-3`.

And I had strange problems because of this. Every instance is using different LinuxGSM versions:
`./csgoserver details` (LinuxGSM version: **v20.2.0**)
`./csgoserver-2 details` (LinuxGSM version: **v19.9.0**)
`./csgoserver-3 details` (LinuxGSM version: **v19.9.0**)

## To Reproduce

Steps to reproduce the behaviour:
1. have multi instance game servers
2. use `update-functions` only on the first instance
3. other instances will stay on an older LinuxGSM version
4. it can cause errors, like this:
```
csgoserver@debian:~$ ./csgoserver start
[ INFO ] Starting csgoserver: Check IP: x.x.x.x
[  OK  ] Starting csgoserver: SERVERNAME
csgoserver@debian:~$ ./csgoserver-2 start
mkdir: cannot create directory ‘’: No such file or directory
[ INFO ] Starting csgoserver-2: Check IP: x.x.x.x
[ .... ] Starting csgoserver-2: SERVERNAME/home/csgoserver/lgsm/functions/command_start.sh: line 65: /csgoserver-2.lock: Permission denied
/home/csgoserver/lgsm/functions/command_start.sh: line 73: /csgoserver-2-laststart.lock: Permission denied
[  OK  ] Starting csgoserver-2: SERVERNAME
csgoserver@debian:~$ ./csgoserver-3 start
mkdir: cannot create directory ‘’: No such file or directory
[ INFO ] Starting csgoserver-3: Check IP: x.x.x.x
[ .... ] Starting csgoserver-3: SERVERNAME/home/csgoserver/lgsm/functions/command_start.sh: line 65: /csgoserver-3.lock: Permission denied
/home/csgoserver/lgsm/functions/command_start.sh: line 73: /csgoserver-3-laststart.lock: Permission denied
[  OK  ] Starting csgoserver-3: SERVERNAME
```

`./csgoserver start` is working fine, because it's using the up-to-date version of LinuxGSM. Others give errors because the new LinuxGSM version has some breaking changes since the `v19.9.0`, and the last two instances are using that.

You have to run `update-functions` on every instance, because versions differences can cause problems.

## Expected behaviour

Update every instance with `update-functions` started on any instance as `update` works with game server files.

**Comment by dgibbs64** [comment]
So potential idea for this is to have the lgsm version located in both ./gameserver and in core_functions. When ./gameserver does anything it will compare these versions. If they do not match the update-lgsm will run to sync up versions to prevent a module an update mismatch

**Comment by h3o66** [comment]
~Closed
feature in version 20.3.0 included
