### ISSUE TITLE
CSGO Install ID 730 <==> 740 Update Issue

### ISSUE THREAD

**Issue by ngx3** [GameServerManagers/LinuxGSM#2871]
## User Story

When I installed the CSGO installation, I used ID 730 not 740 (CSGO dedicated server files). Yesterday there was an update for CSGO and when I checked for updates "./gameserver update" it checked local and remote cache via ID 740 and not kept throwing out that there aren't any updates available.

Is it nessecary to use CSGO 740 over 730? Both have all the required files.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [CSGO]
* **Command:** [update]
* **LinuxGSM version:** [v20.2.0]

**Comment by dgibbs64** [comment]
AppID 730 is the client 740 is the server. Why are you trying to use the client as a server. This makes no sense.

**Comment by ngx3** [comment]
That's what I'm implying. Linuxgsm installed 740 regardless if I put 730 or 740. The issue is the update loops.

From what I've read 730 and 740 are essentially the same files.

Do you know how to view the game App ID through Linuxgsm?

**Comment by Grimston** [comment]
The client does not have the server binaries..
LinuxGSM is set to use the correct id from the start, why are you changing it?

**Comment by h3o66** [comment]
if you have problems with updating then please use `./csgoserver force-update` instead of changeing the config files.

**Comment by h3o66** [comment]
~ Closed
no update in 15 days
