### ISSUE TITLE
Minecraft Config Issues when using Bungee as server.

### ISSUE THREAD

**Issue by VanillaChan6571** [GameServerManagers/LinuxGSM#2874]
Bungee has its own IP section but linuxGSM_ wants "server-ip: xxx.xxx.xx.xxx" when bungee uses "host:" so this makes things error on bungee when adding server-ip: into config.yml.

**Comment by VanillaChan6571** [comment]
Workaround. copy server-ip: just paste it into a blank server.properties file and still works. Kinda dumb but works.

**Comment by dgibbs64** [comment]
Minecraft is being reviewed currently. With plans to support waterfall initially.

**Comment by Claiyc** [comment]
Bungee is not officially supported by lgsm (and requires an enormous extra-work anyway, fixing such a "small" issue isn't possible without adding "real" bungee support).
