### ISSUE TITLE
HLDM server dependencies not met, but server starts

### ISSUE THREAD

**Issue by john8bit** [GameServerManagers/LinuxGSM#2876]
Greetings!
After a recent update, I am encountering some warnings and errors when the HLDM server starts / restarts. While the start / restart is successful, the startup utility reports that required dependencies are not met to run SteamCMD. The dependencies are indeed met and the game instance will start, however, the startup utility is failing 

## Basic info

Distro Details
=================================
Distro:    Ubuntu 18.04.4 LTS
Arch:      x86_64
Kernel:    4.15.0-91-generic
Hostname:  valve
Uptime:    45d, 15h, 13m
tmux:      tmux 2.6
glibc:     2.27

Termbin output URL- https://termbin.com/5djn

## Further Information
Warning! Missing dependencies: netcat lib32stdc++6 steamcmd
Warning! hldmserver does not have sudo access. Manually install dependencies.

A screenshot of the error is attached. Again, the server will start, but not after attempting to install packages (and failing, since the packages are already installed) 
![2020-05-09 20_13_12-Window](https://user-images.githubusercontent.com/1233497/81488728-3f862f00-9232-11ea-8671-cffd8f6a969b.png)

**Comment by dgibbs64** [comment]
There have been some updates to dependency requirements to remove the requirement for :i386 dependencies

**Comment by dgibbs64** [comment]
I have also fixed the 1=2 bug https://github.com/GameServerManagers/LinuxGSM/commit/6fcd8d78f4b9d42109b6a524df32d4eb6a8c1059
