### ISSUE TITLE
"mcbserver update" not updating properly and stopping the server.

### ISSUE THREAD

**Issue by n8rade** [GameServerManagers/LinuxGSM#2877]
## User Story

Ran into an issue where running "mcbserver update" wouldn't complete properly and ended up bringing the server down. Was running this from a crontab entry and wondering why the server would never stay up.

[mcbserver@linuxgsm ~]$ ./mcbserver update
[ .... ] Update mcbserver: Checking local build: minecraft.net++++++ tail -1
++++++ sed 's/.*Version //'
+++++++ ls -tr /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-05-19:05:59.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-03:32:32.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-08:30:01.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-10:52:34.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-08:31:07.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-22:10:08.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-08:30:02.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-10:06:45.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-08:30:01.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:06:07.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:14:05.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-08:30:01.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:32:04.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:45:59.log /opt/gameservers/mcbserver/log/console/mcbserver-console.log
++++++ grep Version '/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-05-19:05:59.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-03:32:32.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-10:52:34.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-08:31:07.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-22:10:08.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-08:30:02.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-10:06:45.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:06:07.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:14:05.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:32:04.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:45:59.log
/opt/gameservers/mcbserver/log/console/mcbserver-console.log'
grep: /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-05-19:05:59.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-03:32:32.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-10:52:34.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-08:31:07.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-22:10:08.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-08:30:02.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-08-10:06:45.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:06:07.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-09-10:14:05.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-08:30:01.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:32:04.log
/opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-10-10:45:59.log
/opt/gameservers/mcbserver/log/console/mcbserver-console.log: No such file or directory
+++++ localbuild=
+++++ set +x

## Basic info

* **Distro:** [Fedora release 30 (Thirty)]
* **Game:** Minecraft Bedrock
* **Command:** [Update]
* **LinuxGSM version:** [v20.2.1]

## Further Information

Will be submitting a pull request for the script fix shortly.

## To Reproduce

Steps to reproduce the behaviour:
1. Run "mcbserver update"

## Expected behaviour
"mcbserver update" to properly update the server.

**Comment by h3o66** [comment]
~Closed
bug fix in version 20.3.0 included
