### ISSUE TITLE
commande line with incorrect url for minecraft bedrock server installation

### ISSUE THREAD

**Issue by tristelune** [GameServerManagers/LinuxGSM#2879]
Hello

on the guide to install the server : 
https://linuxgsm.com/lgsm/mcbserver/

the commande line has an incorrect ulr: 
wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh mcbserver

https://linuxgsm.sh should be https://linuxgsm.com instead

then the commande line work fine

And thanks for the good works with linux gsm it's awsome i love it

thank you

**Comment by h3o66** [comment]
https://linuxgsm.sh is the right url - this is a redirected request to github for the file linuxgsm.sh

**Comment by tristelune** [comment]
Ok thank for the information

So it was probably just the redirection wich was down at that time has now it work fine

thanks

De : Christian <notifications@github.com>
Envoyé : lundi 11 mai 2020 00:34
À : GameServerManagers/LinuxGSM <LinuxGSM@noreply.github.com>
Cc : tristelune <triste_lune_421@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [GameServerManagers/LinuxGSM] commande line with incorrect url for minecraft bedrock server installation (#2879)


https://linuxgsm.sh is the right url - this is a redirected request to github for the file linuxgsm.sh
