### ISSUE TITLE
[Teamspeak3] Details doesn't see server as Online

### ISSUE THREAD

**Issue by Xylemon** [GameServerManagers/LinuxGSM#289]
When running details I get this error at first:

tail: cannot open '3' for reading: No such file or directory
/home/server/Servers/ts3/functions/fn_details_distro: line 32: [: : integer expression expected

Then it proceeds to tell me in the details section that it's not online.

Distro Details:

Distro: Slackware 14.1
Arch: x86_64
Kernel: 3.14.18
tmux: tmux 1.8
GLIBC: 2.20

**Comment by dgibbs64** [comment]
same error as in kfserver. The offline issue is because its written to work with tmux and I forgot to update this for ts3. Tmux is not required for ts3server. I will need to remove reference to tmux and glibc as they are not a requirement for ts3

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgameservers/commit/29d80e88ce8d8b44dbece05cb33c9ab64e9067fd

Fixed

**Comment by Xylemon** [comment]
Again, sadly did not fix.

**Comment by Xylemon** [comment]
The latest commit did indeed fix!
