### ISSUE TITLE
Mod directory incorrect - /Squad/

### ISSUE THREAD

**Issue by rconjoe** [GameServerManagers/LinuxGSM#2895]
## User Story

Squad mod folder /Squad/ has been deprecated in favor of /SquadGame/ by the developer.

## Basic info

Breaks name of installation mod directory. Current state results in Squad Server configs, mods, and anything else in /Squad/ ignored in game. Change /Squad/ to /SquadGame/ to fix?

![unknown](https://user-images.githubusercontent.com/48492680/82501130-bc32cc00-9ac2-11ea-9c0b-9ca070cb9fae.png)
source: Squad Server official server hosting discord - 2019

**Comment by h3o66** [comment]
@rconjoe if you have time could you have a look at my PR ?
This would change the systemdir and move at least the old directory.
Maybe i should as well check for the old dir and warn about the directoty change at the start of the server

**Comment by h3o66** [comment]
Only the config what is in the LGSM config will be moved to the new dir.
Currently no message is implementedto inform the user about.
Are mods common for Squad ?
