### ISSUE TITLE
Unable to install Rust beta branch

### ISSUE THREAD

**Issue by cliph** [GameServerManagers/LinuxGSM#2896]
## User Story

As a server administrator, I want install a specific branch of the Rust server from Steam.

## Basic info

* **Distro:** Debian 10
* **Game:** Rust
* **Command:** Upgrade
* **LinuxGSM version:** [v20.1.3]

## Further Information

A new beta branch of the Rust server software is available and is identified with the branch title "aux01" and developer docs stating to specify branch "-beta aux01"

Following the instructions here: https://docs.linuxgsm.com/steamcmd/branch to specific a new branch does not appear to work with the required branch name of "-beta aux01" 

Specifically the developer gave the advice: 

> "Server owners will be able to host servers as normal by using the following parameters: "app_update 258550 -beta aux01""

Here's an example of a failing upgrade:

```$ ./rustserver u
[  OK  ] Updating rustserver: Checking for update: SteamCMD

Update available
* Local build: 5043165
* Remote build: 5055726
https://steamdb.info/app/258550/

Redirecting stderr to '/home/rust/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Warning: failed to init SDL thread priority manager: SDL not found
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '258550' already up to date.
```

## To Reproduce

Steps to reproduce the behaviour:
1. Update branch to `branch="-beta aux01"`
2. Issue upgrade command
3. Witness upgrade failing as in example above

## Expected behaviour

Updating the branch configuration and running upgrade will cause the specific branch to be installed.

**Comment by akariley** [comment]
I have the same issue.  I've attached my debug.log during the attempted update.
[zsdfgzadfg.txt](https://github.com/GameServerManagers/LinuxGSM/files/4659569/zsdfgzadfg.txt)

**Comment by akariley** [comment]
Slight update, when `branch` is set to just 'aux01', this is the result.
```
[rust-staging@gameserver rust]$ ./rustserver u
[  OK  ] Updating rustserver: Checking for update: SteamCMD

No update available
* Local build: 5043165
* Remote build: 5043165
https://steamdb.info/app/258550/


core_exit.sh exiting with code: 0
```
As of this post, here's the status of the public branch:
![image](https://user-images.githubusercontent.com/19627410/82504527-3f532280-9ac1-11ea-83cc-e349fd08fdff.png)

and with `branch` set to '-beta aux01' we get this:
```
[rust-staging@gameserver rust]$ ./rustserver u
[  OK  ] Updating rustserver: Checking for update: SteamCMD

Update available
* Local build: 5043165
* Remote build: 5055726
https://steamdb.info/app/258550/

Redirecting stderr to '/home/rust-staging/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Warning: failed to init SDL thread priority manager: SDL not found
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '258550' already up to date.

core_exit.sh exiting with code: 0
```
which is the expected aux01 number:
![image](https://user-images.githubusercontent.com/19627410/82504623-76293880-9ac1-11ea-9787-8855ac90ce3f.png)

Hope this helps! :)

**Comment by cliph** [comment]
Wondering if this relates to #2670

**Comment by h3o66** [comment]
Not sure if you have tried it without the beta tag, like it is in the docs:
https://docs.linuxgsm.com/steamcmd/branch

in this case you add only this:
`branch="aux01"`

and then you do a **force-update** with lgsm - to be sure to apply the branch.
Pls test, thanks

**Comment by akariley** [comment]
This appears to have worked.  I swear I tried this before; perhaps the force-update fixed it.

**Comment by h3o66** [comment]
@akariley thanks for confirming this - will close the issue based on this feedback.
