### ISSUE TITLE
Netcat missing in Teamspeak 3 dependecies on website

### ISSUE THREAD

**Issue by PlayMTL** [GameServerManagers/LinuxGSM#2907]
## User Story

Netcat is missing as dependecie for teamspeak 3 on the website (https://linuxgsm.com/lgsm/ts3server/). (Maybe also renew the Teamspeak header picture, cause of a new teamspeak logo)

## Further Information

Add netcat to the list of needed dependencies for teamspeak 3.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to https://linuxgsm.com/lgsm/ts3server/

Maybe duplicates: #2757

**Comment by dgibbs64** [comment]
netcat has now been added as a dependency for all games
