### ISSUE TITLE
[Server Request] FiveM Server

### ISSUE THREAD

**Issue by KILLERMANTV** [GameServerManagers/LinuxGSM#2917]
## What game server would you like adding?

FiveM Server

## Can you link to any tutorials or guides?

https://docs.fivem.net/docs/server-manual/setting-up-a-server/

## Is the server on Steam?

* [ ] Yes
* [X] No

## Is the server supported on Linux?

Native linux support.

* [X] Yes
* [ ] No

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/1615
