### ISSUE TITLE
Avorion install does not work

### ISSUE THREAD

**Issue by AndrewSav** [GameServerManagers/LinuxGSM#2925]
## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Avorion]
* **Command:** [Install]
* **LinuxGSM version:** [v20.3.3]

## Further Information

Avorion installation hangs when running [this](https://github.com/GameServerManagers/LinuxGSM/blob/dcca5845631cdb877a7ac2869863bf796c838fe8/lgsm/functions/fix_av.sh#L13) because `avgalaxy` is not defined.

The variable definition was removed in [this commit](https://github.com/GameServerManagers/LinuxGSM/commit/f05eab26330150891ae2b412c5baf2970744e9bb) but its usage was not, which caused this issue.

Discussion [here](https://discordapp.com/channels/127498813903601664/135126471319617536/721480401494868049) could be helpful for additional information.

## To Reproduce

Steps to reproduce the behaviour:
1. Follow instructions at https://linuxgsm.com/lgsm/avserver/

## Expected behaviour
Avorion installation finished

**Comment by h3o66** [comment]
Thanks for the report.
I just added a pull request for this.

for a quick fix you might want to change the `${avgalaxy}` to `${selfname}`
