### ISSUE TITLE
problem with get downloading

### ISSUE THREAD

**Issue by Septembers** [GameServerManagers/LinuxGSM#2926]
fetching GitHub serverlist.csv...ERROR
fetching Bitbucket serverlist.csv...FAIL
linuxgsm.sh: line 123: core_exit.sh: command not found
[ FAIL ] serverlist.csv could not be loaded.

* **Distro:** [Debian 10]
Linux debian10x64.local 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
ldd (Debian GLIBC 2.28-10) 2.28
tmux 2.8

**Comment by Septembers** [comment]
solution to the problem
apt install curl

maybe it should be added to the installation package?

**Comment by h3o66** [comment]
What howto have you been following ?
If you usally use the howto from the offical website, there are the dependencys noted:
https://linuxgsm.com/lgsm/csgoserver/

Maybe a pre check in the main script would be good to prevent something like this.
