### ISSUE TITLE
Blacklist log directores from getting log purged

### ISSUE THREAD

**Issue by godrider** [GameServerManagers/LinuxGSM#2930]
## User Story

As a server administrator, I want be able to choose and blacklist log directories from getting log purged.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Multiple]
* **Function:** [Logging]
* **LinuxGSM version:** [v20.3.3]

## Further Information

Similarly to [this](https://github.com/GameServerManagers/LinuxGSM/issues/2304#issue-436951410), I want to prevent certain log directories from getting log purged after log files older than X days will be automatically deleted. This new feature prevents important data, residing in these directories, from getting deleted out of the user's hands. Think of chat logs, plugin error information, general plugin information.

Example:
```
## Logging | https://docs.linuxgsm.com/features/logging
consolelogging="on"
logdays="7"
# Do not delete logs from the following directories
blacklist="${commonsourcelogs}; ${sourcemodlogdir}"
```

The commonsourcelogs and sourcemodlogdir variables are references to the logpaths written in `core_log.sh`.

## Possible Solution

Loop through the user defined blacklist array and check in `core_log.sh` which directories will be scanned for file deletion.

**Comment by dgibbs64** [comment]
Clearing of logs was added as the log files built up so much that it overloaded some game servers. I don't recommend keeping logs and they should be cleared down after a time. This is standard procedure of Linux logs as well. I recommend setting the log rotation to 30 days if you need to retain them for longer. If you still need them for the long term auditing purposes you should create a backup archive of the logs.
