### ISSUE TITLE
Dependencies requiered for Assetto Corsa server remove eachother

### ISSUE THREAD

**Issue by Bullcomander** [GameServerManagers/LinuxGSM#2931]
## User Story

As a user, I want depedency issues resoved so that I am able to install the server.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Assetto Corsa]
* **Command:** [Install]
* **LinuxGSM version:** [v20.1.3]

## Further Information

When installing the assetto server, two requiered dependency block each other. When installing one of them, the other is getting removed automatically. The two dependencies in question are: lib32gcc1 and lib32stdc++6. Denying the installation of additional packages does not work either.

## To Reproduce

Steps to reproduce the behaviour:
1. Run installation of assetto corsa server
2. Check requiered dependencies

## Expected behaviour
When one of the two dependencies is installed. The other one will be removed in the process.

**Comment by dgibbs64** [comment]
I tested this was unable to replicate. However, I removed  `libstdc++6` as a requirement from the website as no longer used.
