### ISSUE TITLE
[Server Request] Empyrion - Galactic Survival

### ISSUE THREAD

**Issue by fringemonkey** [GameServerManagers/LinuxGSM#2933]
## What game server would you like adding?

Empyrion - Galactic Survival [Steam Link](https://store.steampowered.com/app/383120/Empyrion__Galactic_Survival/)

## Can you link to any tutorials or guides?

[Wiki Guide](https://empyrion.gamepedia.com/Dedicated_Server_Setup)
[Windows Tool](https://eah.empyrion-homeworld.net/) - This has a lot of very useful features to running an Empyrion server. Linked here as a wish list.

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[530870]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by h3o66** [comment]
This Game does not have a linux server yet, see:
https://empyriononline.com/threads/dedicated-server-questions-about-api.68500/

There is also not a linux depot yet.

**Comment by dgibbs64** [comment]
Closing this. Can be re-raised when Linux support is available
