### ISSUE TITLE
Update UT2004 Server Files to 3369.3

### ISSUE THREAD

**Issue by Annihilator** [GameServerManagers/LinuxGSM#2934]
LinuxGSM currently provides the 3369.2 version of dedicated server files. Please switch over to the latest available version, which is 3369.3. Available here:
https://www.utzone.de/forum/downloads.php?do=file&id=1196_UT2004-Dedicatedserver--3369.3-incl.-Bonuspack
Note: some bonus packs are not present in this archive and need to be added to the final package.

**Comment by dgibbs64** [comment]
I think the Linux patch only goes up to 3369.2

**Comment by Annihilator** [comment]
> I think the Linux patch only goes up to 3369.2 but I will have to double check
A common mistake. 3369.3 is indeed the latest official dedicated server build for Linux, and the latest released, though unofficial, build for Windows. The information about this fact has been kind of lost on the intrawebz, unfortunately.
