### ISSUE TITLE
Problems "csgoserver-update"

### ISSUE THREAD

**Issue by Ev1LOFF** [GameServerManagers/LinuxGSM#2935]
## Basic info

* **Distro:** [Debian 10]
* **Game:** [CS:GO]
* **Command:** [UPDATE]
* **LinuxGSM version:** [v20.3.3]

## Further Information

I have a server with LinuxGSM version "v19.11.0", everything works on it. I needed a new server and I installed the latest version of "v20.3.3" there was an update problem, several servers were installed on one VDS and when I entered the "./csgoserver update" command, everything hangs for a while at the time "update csgoserver: checking local build: steamcmd "or heavily loading the Internet or system, there were no such problems with the old version.

I apologize for the English, I used Google translator)
I hope tell me what to do with this problem, thanks in advance)

## To Reproduce

Steps to reproduce the behaviour:
1. Go to './csgoserver update'
2. See error

**Comment by dgibbs64** [comment]
Have you tried ./csgoserver force-update or validate?

**Comment by Ev1LOFF** [comment]
> Have you tried ./csgoserver force-update or validate?

The server can also be updated with "./csgoserver update". The problem is that it hangs badly and the server shuts down for 5 minutes (even if there is no new update)

**Comment by dgibbs64** [comment]
Did you run force-update and validate? Do you get the same issues running force-update or validate?

**Comment by Ev1LOFF** [comment]
> Did you run force-update and validate? Do you get the same issues running force-update or validate?

If you use force-update, then there are no problems

**Comment by Ev1LOFF** [comment]
What should I do? The problem is not solved

**Comment by dgibbs64** [comment]
I am unsure why you are getting this issue and would need to be investigated further

**Comment by dgibbs64** [comment]
A New release of LinuxGSM is now out. I have not come across this issue myself and unsure how to replicate. Hopefully, you have resolved this now. I will leave open for now but it be closed automatically if no response

**Comment by h3o66** [comment]
No answer in more than 2 months.
~closing
