### ISSUE TITLE
LGSM arkserver 'automanagedmods' fix found

### ISSUE THREAD

**Issue by kriegtiger** [GameServerManagers/LinuxGSM#2937]
## User Story

ARK's dedicated server has a function to download/update mods - it is currently implemented by LGSM's arkserver but it is broken because while it does download the mods into the workshop content folder, it does not actually **_process/unpack_** them into the game server's Mods path for use (where a 123456789 folder and 123456789.mod file are placed). 

I have found the fix for this issue, and think it could be incorporated into LGSM's arkserver installation/configuration process since the LGSM installer already manages where so many things go.

## Basic info

* **Distro:** Debian 9
* **Game:** ARK
* **Command:** ./arkserver start
* **LinuxGSM version:** v20.3.3

## Further Information

The problem is that the 'steamapps' directory needs to be in a place where steamcmd can get to it - which can be accomplished with a simple symbolic link, shown below. Once this link is in place, arkserver's mod download/update functionality works perfectly.

`ln -s ~arkserver/.local/share/Steam/steamapps ~arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps`

## To Reproduce

Steps to reproduce the behaviour:
1. Install LGSM arkserver
2. follow guide at https://docs.linuxgsm.com/game-servers/ark-survival-evolved - Mod Support
3. run './arkserver start'
4. observe console to verify that the mod downloads, and confirm presence in `~arkserver/.local/share/Steam/steamapps/workshop/content/346110/` but notice that there are no files created under `~arkserver/serverfiles/ShooterGame/Content/Mods` as they should be when properly unpacked/installed

## Expected behaviour

After mods are downloaded but before the server is open to players for connections, there should be files matching the mod ID appearing under `~arkserver/serverfiles/ShooterGame/Content/Mods/` - listed below (example mod ID from the arkserver docs):

```
arkserver@lurker:~$ ls -l ./serverfiles/ShooterGame/Content/Mods/|grep 115
drwxr-xr-x  8 arkserver arkserver  4096 Jun 23 15:26 924619115
-rw-------  1 arkserver arkserver   260 Jun 23 15:26 924619115.mod
```

**Comment by dgibbs64** [comment]
Thanks. However, this fix has already been added to LinuxGSM
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/fix_ark.sh#L51
