### ISSUE TITLE
So how about Atlas right about now... ? 

### ISSUE THREAD

**Issue by Mixtery** [GameServerManagers/LinuxGSM#2938]
So, is there some way to edit some files and make the ark config work for atlas? 
I saw someone say the linux server was no longer working and so development was halted for this, but it is alive and kicking... so can someone help me to get this working? 

## Basic info

CentOS 8 
Atlas

**Comment by dgibbs64** [comment]
You are the first person to let us know that it's now fixed. Closing this as duplicate.

https://github.com/GameServerManagers/LinuxGSM/issues/2158
