### ISSUE TITLE
Minecraft Bedrock Perpetually Updates

### ISSUE THREAD

**Issue by thelegendofbrian** [GameServerManagers/LinuxGSM#2940]
## User Story

As a system administrator, I want to update a server when an update is available.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Minecraft Bedrock]
* **Command:** [Update]
* **LinuxGSM version:** [v20.3.3]

## Further Information

When updating the game, every other update command issued results in an update which isn't actually needed. When an update is thought to be available, it states the local build is 1.16.1.2 and the remote build is 1.16.1.02, which shouldn't result in a update, but it does.

## To Reproduce

Steps to reproduce the behaviour:
1. Install an mcbserver and start the server at least once
2. Issue `./mcbserver update` 4 times
3. Notice there were 2 updates attempted

## Expected behaviour

An update should only occur if there is an update available.

**Comment by dgibbs64** [comment]
How odd. the update logic is as simple as if local and remote version number do not match then update. So my guess is that its getting the wrong local version

**Comment by mspencerl87** [comment]
My Minecraft is setup to check for updates every 60 minutes.
It is constantly trying to update from 1.16.1.2 to 1.16.1.02
It always fails.

**Comment by mspencerl87** [comment]
> How odd. the update logic is as simple as if local and remote version number do not match then update. So my guess is that its getting the wrong local version

Any idea which file to change in the mcbserver directories to rectify the issue?

**Comment by dgibbs64** [comment]
Yeah looks like the minecraft devs have got the remote release number wrong which is causing the error. The logs give `2` and the remote location (zipfile name) gives `02`
```
Update available
* Local build: 1.16.1.2
* Remote build: 1.16.1.02
```

There is nothing I can do to fix this. It will need to be raised with Mojang.

**Comment by dgibbs64** [comment]
If anyone wants to contact Mojang feel free to reference this issue. I will, however, close this as there is nothing more I can do until they fix filename

**Comment by dgibbs64** [comment]
Good news with the latest update they appear to have fixed this issue

**Comment by mspencerl87** [comment]
All hell Microsoft lol thanks if anyone had to do anything on GitHub!!! My son will be happy now.
Thanks for the update @dgibbs64
