### ISSUE TITLE
ARK Server - Epic Games - Unable to connect to server (With latest patch) 

### ISSUE THREAD

**Issue by PrivateGiles** [GameServerManagers/LinuxGSM#2941]
## User Story

As a user, I want to be able to allow Epic games members connect to my dedicated server so that steam and epic members can play together. A new update has been released from ARK which adds in a new argument so you can specify the IP address. My server has been updated with the latest SteamCMD patch which was released, however the when the users try to connect to the server it just errors out. 

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [ARK: Survival Evolved]
* **Command:** [Server as a whole]
* **LinuxGSM version:** [Latest Release]

## Further Information

With the latest patch, I've defined the the following within my arkserver.cfg:
```
# Default start process based on enabling Epic Games to play on the dedicated server
## Server Start Command | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
fn_parms(){
parms="${defaultmap}?AltSaveDirectoryName=${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port} -automanagedmods -crossplay -PublicIPForEpic=51.132.224.27"
}
```
However when someone from epic games tries to connect to the server it looks as if it's going to connect then takes them back to the front page of ark. When they go back in and try and re-connect to the server the error message is: "Connection Failed: Unknown Error"

## To Reproduce

Steps to reproduce the behaviour:
1. Add the parameters to the config file
2. try to connect to ark dedicated server via epic games
3. See error

## Expected behaviour
User is able to connect due to the parameter being set

**Comment by Fr1tzl1** [comment]
Have you Mods installet on your Server?

**Comment by PrivateGiles** [comment]
Hi

No mods are installed on the server
