### ISSUE TITLE
(LGSM server) cant join server occasionally

### ISSUE THREAD

**Issue by GuineaPig352** [GameServerManagers/LinuxGSM#2942]
Well, I am having a strange issue. I'm running an lgsm ark server. for some reason every night around 8:30 EST when I'm in the server I realize that I can't switch my tools or any item in my Hotbar. I quit and then the server does not appear in the favorites tab and the steam > View > servers> favorites tab thing. after restarting the server and rebooting the server and waiting 20 sometimes 30 minutes I can't join. the computer has a scheduled reboot at 1 am so that could have something to do with it. yet every morning it works again. sometimes i am unable to join the server throughout the day. and it's not just me who experiences it. its everyone who tries to join. as you can imagine it's not to fun to experience. oh i should mention the server autostarts on boot. I read in another form that distance could have something to do with it. I am not good with distance but I would say its around 5 feet away from my rig so that doesn't seem like anything to worry about. I have other servers including lgsm and non-lgsm servers but none of the ports are shared. I have 8 ethernet ports and 4 network cards so I'm not putting the servers on the same cards.

the output of the command ./arkserver postdetails gives me this output:

Distro Details
Distro: Ubuntu 20.04 LTS
Arch: x86_64
Kernel: 5.4.0-39-generic
Hostname: Atlas
Uptime: 0d, 1h, 25m
tmux: tmux 3.0a
glibc: 2.31

Server Resource
CPU
Model: Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz
Cores: 8
Frequency: 1409.006MHz
Avg Load: 2.26, 2.42, 3.00

Memory
Mem: total used free cached available
Physical: 40GB 11GB 29GB 29GB 29GB
Swap: 2.0GB 65MB 2.0GB

Storage
Filesystem: /dev/sda5
Total: 914G
Used: 125G
Available: 743G

Network
Interface: enp7s0f1
IP: 192.168.1.253
Internet IP: 96.252.103.137

Game Server Resource Usage
CPU Used: 0%
Mem Used: 0% 0MB

Storage
Total: 14G
Serverfiles: 14G

ARK: Survival Evolved Server Details
Server name: bob
Server IP: 192.168.1.253:7777
Internet IP: 96.252.103.137:7777
Maxplayers: 100
Default map: TheIsland
Master server: false
Status: ONLINE

arkserver Script Details
Script name: arkserver
LinuxGSM version: v20.3.3
glibc required: 2.15
Discord alert: off
Slack alert: off
Email alert: off
Pushbullet alert: off
IFTTT alert: off
Mailgun (email) alert: off
Pushover alert: off
Telegram alert: off
Update on start: on
User: arkserver
Location: /home/arkserver
Config file: /home/arkserver/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Backups
No Backups created

Command-line Parameters
./ShooterGameServer "TheIsland?AltSaveDirectoryName=TheIsland?listen?MultiHome=192.168.1.253?MaxPlayers=100?QueryPort=27015?RCONPort=27020?Port=7777 -automanagedmods"

Ports
Change ports by editing the parameters in:
/home/arkserver/lgsm/config-lgsm/arkserver

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

DESCRIPTION DIRECTION PORT PROTOCOL
> Game INBOUND 7777 udp
> RAW INBOUND 7778 udp
> Query INBOUND 27015 udp
> RCON INBOUND 27020 tcp

Status: ONLINE

i have 2 identical cps, I'm running a raid 5. I have 40 GB of ECC memory if any of this helps that's good. I don't know if this helps but I don't have a pc firewall what so ever. not even iptables. I have a Verizon fios quantum gateway router and a sonic wall. again i don't know if this helps I just don't want to give less information then I need. I have updated the server, lgsm, and all the packets if that helps.

I hope you can help me but I understand if you can not

I've posted this here as well: https://survivetheark.com/index.php?/forums/topic/546626-lgsm-server-cant-join-server-occasionally/

and here https://steamcommunity.com/app/346110/discussions/9/2574319916023991016/

to reproduce this bug create an ark server and have it now work for an unknown reason similar to my issue i suppose. i mean i really dont know how to reproduce it.

**Comment by dgibbs64** [comment]
I am afraid I am unsure of what the issue is and it appears to be a game server specific issue. It is possible the issue is related to mods so it's worth checking them
