### ISSUE TITLE
When on latest_experimental version update function checks against public version

### ISSUE THREAD

**Issue by Khelgar1** [GameServerManagers/LinuxGSM#2945]
## User Story

As a server admin, I want the update function to check against the correct branch so that it correctly reports whether an update is available or not. It still does what it is supposed to do ie updates the server but not in the manner you'd expect.

## Basic info

* **Distro:** Ubuntu 18.04
* **Game:** 7 Days to Die
* **Command:** Update
* **LinuxGSM version:** v20.3.3

## Further Information

While on the latest_experimental branch of the server, when you run the update function it checks the version against the public branch rather than the experimental branch and runs an update
![image](https://user-images.githubusercontent.com/23195823/86453358-8ca7ee00-bd15-11ea-9ed6-e0ec0b0e255d.png)

![image](https://user-images.githubusercontent.com/23195823/86453046-160af080-bd15-11ea-85b9-41fac87b7637.png)

The update correctly updates the experimental branch if an update is available for it otherwise it reports that it is already up to date. 
![image](https://user-images.githubusercontent.com/23195823/86453171-43f03500-bd15-11ea-9002-00388940e0db.png)
![image](https://user-images.githubusercontent.com/23195823/86453280-6da95c00-bd15-11ea-93d4-6b61246a28c8.png)

## To Reproduce

Steps to reproduce the behaviour:
1. Be running the latest experimental branch of the 7dtd server
2. Run an update
3. observe the results

## Expected behaviour

It should check the version against the experimental branch rather than the public branch and only try to update if a new experimental update is available.

**Comment by dgibbs64** [comment]
I have found the bug. Will fixed in next release

**Comment by Khelgar1** [comment]
Good job, works perfectly now, thanks!
