### ISSUE TITLE
RUST - mods-update command take so much time

### ISSUE THREAD

**Issue by psycomaffo** [GameServerManagers/LinuxGSM#2946]
User Story
I'm using Putty and when i wrote the mods-update command (or mu) it remains stuck for to much time... this happen from around 1 month. Ussually it take around 30/40 sec for the mods update, now it take from 10 to 25 minutes. All worked fine for over 2 years before this issue and nothing was changed on my server.
I have 3 Rust Server and this happen to all.

Basic info

Ubuntu 19.10
Game: Rust
Command: mods-update or mu
LinuxGSM version: v20.3.3
![stuck](https://user-images.githubusercontent.com/54965762/86471779-4b780400-bd3e-11ea-9ff5-2ff54be048df.png)

**Comment by h3o66** [comment]
I suspect that this is a problem with the mods_list.sh function.
As there a few version infos are loaded from the mod sites if one of them is slow, this might be the cause.

**Comment by psycomaffo** [comment]
tnx, but how can i check it?

**Comment by h3o66** [comment]
you could extract line 15 tll 40 from the script here:
https://github.com/GameServerManagers/LinuxGSM/blob/242d91d9370c6645c74ca8428958c3db05b80174/lgsm/functions/mods_list.sh#L15-40

Put this into a seperate file on the server and then you can maybe see/debug which of the remote urls do need that long.

**Comment by KurzweilTV** [comment]
Is this still valid? The mods-update command seems fast to me now. It could have potentially been a temporary umod issue

**Comment by Claiyc** [comment]
Doesn't seem to be an issue anymore.
