### ISSUE TITLE
[Server Request] Team Fortress 2 Classic

### ISSUE THREAD

**Issue by RoonMoonlight** [GameServerManagers/LinuxGSM#2949]
## What game server would you like adding?

Team Fortress 2 Classic

## Can you link to any tutorials or guides?

https://iraizo.github.io/tf2-classic-linux-server-tutorial/ (Websites are back)

## Is the server on Steam?

[x] Yes
[] No

There is no Steam release of this, but it uses Source SDK 2013 Multiplayer by default.

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

[x] Yes
[] No

**Comment by twinsuns** [comment]
Seconded. 
It uses Source SDK Base 2013 Dedicated Server https://steamdb.info/app/244310/
Tutorial here: https://iraizo.github.io/tf2-classic-linux-server-tutorial/

**Comment by RoonMoonlight** [comment]
Any progress on this feature? I would like to host Team Fortress 2 Classic...

**Comment by RoonMoonlight** [comment]
Hey guys, If you guys forgot to add this server, now TF2C uses [TF2CDownloader](https://github.com/tf2classic/TF2CDownloader) feature which automatically downloads files required for TF2C and can also be used on server as well.

[Updated guide is now right here, and is frequently being updated.](https://wiki.tf2classic.com/wiki/Dedicated_Linux_server)

**Comment by RoonMoonlight** [comment]
Closing this as no one is willing to work on this issue.
