### ISSUE TITLE
Check for output - why?

### ISSUE THREAD

**Issue by Ecklory** [GameServerManagers/LinuxGSM#2955]
https://github.com/GameServerManagers/LinuxGSM/blob/dcbe35b23c2acd8b70e2338d39b4b07d46a08a4e/lgsm/functions/fix_csgo.sh#L26

Why do I need to check for output?
After all, if `sed` does not find anything (which is essentially a check), then nothing will happen.

**Comment by Ecklory** [comment]
https://github.com/GameServerManagers/LinuxGSM/blob/dcbe35b23c2acd8b70e2338d39b4b07d46a08a4e/lgsm/functions/fix_dst.sh#L11

`&&` space separated

**Comment by dgibbs64** [comment]
The if statement s present to prevent messages from being displayed to the user if the fix is not required. Otherwise, it would state that this fix is being applied every single time
