### ISSUE TITLE
lib32stdc++6 missing dependence @ Debian 9.4 i686

### ISSUE THREAD

**Issue by Autorojo** [GameServerManagers/LinuxGSM#2957]
## User Story

I am trying to install a CS:GO server on Debian 9.4 (arch i686). LinuxGSM can not run SteamCMD because there is a missing dependence: lib32stdc++6.

That dependence can not be installed in Debian 9.4 i686.

```
root@debian:~# dpkg --add-architecture i386; apt update; apt install lib32stdc++                                                                             6
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [53.0                                                                              kB]
0% [1 InRelease gpgv 53.0 kB] [Connecting to mirrors.wikimedia.org]
Ign:2 http://ftp.us.debian.org/debian stretch InRelease
Get:3 http://ftp.us.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main Sources [2                                                                             18 kB]
Get:5 http://security.debian.org/debian-security stretch/updates/main i386 Packa                                                                             ges [531 kB]
Get:6 http://security.debian.org/debian-security stretch/updates/main Translatio                                                                             n-en [233 kB]
Hit:7 http://ftp.us.debian.org/debian stretch Release
Fetched 1,129 kB in 3s (334 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
```

I also got errors with lib32gcc1 dependence, but I've fixed it... don't remember how.

## Basic info

* **Distro:** Debian GNU/Linux 9 (stretch)
* **Arch:** i686
* **Kernel:** 4.9.0-12-686-pae
* **Game:** Counter Strike: Global Offensive
* **Command:** ./csgoserver install
* **LinuxGSM version:** v20.3.3

## Further Information

I already install a CS:GO server in this distro using LinuxGSM by reverting the following changes.

- https://github.com/GameServerManagers/LinuxGSM/commit/8f442559fe6aa55acc1ddf3f008904e32f3e4026#diff-294c861f4531fdd56585f50baaafeb36L195-R186
- https://github.com/GameServerManagers/LinuxGSM/commit/8f442559fe6aa55acc1ddf3f008904e32f3e4026#diff-294c861f4531fdd56585f50baaafeb36L349-R334
- https://github.com/GameServerManagers/LinuxGSM/commit/8f442559fe6aa55acc1ddf3f008904e32f3e4026#diff-294c861f4531fdd56585f50baaafeb36L351-R336

## To Reproduce

Steps to reproduce the behaviour:
1. Install CS:GO server https://linuxgsm.com/lgsm/csgoserver/ and you will get this error.

**Comment by dgibbs64** [comment]
This doesn't make sense lib32stdc++6 as the package is available in the repo https://packages.debian.org/stretch/lib32stdc++6

and I have it installed on my system
```
root@localhost:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@localhost:~# apt install lib32stdc++6
Reading package lists... Done
Building dependency tree
Reading state information... Done
lib32stdc++6 is already the newest version (6.3.0-18+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
```

**Comment by Autorojo** [comment]
Yes, but it doesn't seem to be available for i686 architecture. Am I wrong?

**Comment by dgibbs64** [comment]
now it makes sense. Is there a reason you are not using 64-bit?

**Comment by Autorojo** [comment]
I am using a VPS and the company who provides me that service don't have Debian 64-bit available, unfortunately

**Comment by dgibbs64** [comment]
Almost no one uses 32-bit distros anymore as all CPU's for at least past 10 years support 64-bit, which is why I removed all reference to it on the website recently. Many distros don't even ship a 32-bit version anymore. I assume your VPS provider doesn't support ubuntu either? As there hasn't been a 32-bit version of ubuntu for several years. 

If your VPS provider doesn't do something as basic as support 64-bit distros I would recommend looking for another provider.

To get the game server to work on 32-bit Debian you will need to install `libstdc++6`

Good luck 😃

**Comment by Autorojo** [comment]
I thought it was a LinuxGSM bug, sorry.

Anyway, LinuxGSM is working with ``libstdc++6`` in ``check_deps.sh``.

Thanks for your support!

**Comment by netstx** [comment]
I have the package for i686 installed (libstdc++6 is already the newest version (8.3.0-6).) and it still fails the dependency checks during install. Any thoughts?

**Comment by netstx** [comment]
@dgibbs64 sorry for posting on a closed issue, didn't want to duplicate it.
