### ISSUE TITLE
[l4d2server] console logs are zero bytes on Ubuntu

### ISSUE THREAD

**Issue by Montclair** [GameServerManagers/LinuxGSM#296]
We're using your script (great job), and it was logging things fine on Debian. For whatever reason, the L4D2 servers weren't stable there so we migrated to Ubuntu 14.x. Ever since that, the console logs are empty. We're not sure what we did that could cause that, but no matter what logging variables we change and adding / removing -debug from the command line, the files are always created but always 0 bytes. tmux is installed also. Do you have any insight?

**Comment by dgibbs64** [comment]
Please paste output of ./l4d2server details.

**Comment by Montclair** [comment]
/home/l4d2-1/functions/fn_details_distro: command substitution: line 55: syntax error near unexpected token `|'
/home/l4d2-1/functions/fn_details_distro: command substitution: line 55: `free ${option} | | awk '/Swap:/ {print $2}')'

Distro Details
==============================================================================================================================
Distro:    Ubuntu 14.04.1 LTS
Arch:      x86_64
Kernel:    3.13.0-45-generic
Hostname:  TFPG-NJ
tmux:      tmux 1.8
GLIBC:     2.19

Performance
==============================================================================================================================
Uptime:    5d, 14h, 16m
Avg Load:  0.28, 0.16, 0.09

Mem:       total   used   free
Physical:  2.0G    1.9G   78M
Swap:              0B     0B

Disk Usage
==============================================================================================================================
Disk available:  16G
Serverfiles:     9.9G

Left 4 Dead 2 Server Details
==============================================================================================================================
Server name:
Server IP:    104.207.128.135:27015
Status:       ONLINE

Service name:  l4d2-server
User:          l4d2-1
Location:      /home/l4d2-1
Config file:   /home/l4d2-1/serverfiles/left4dead2/cfg/l4d2-server.cfg

Backups
==============================================================================================================================
No Backups created

Command-line Parameters
==============================================================================================================================
./srcds_run -game left4dead2 -strictportbind -ip 104.207.128.135 -port 27015 +clientport 27005 +map c2m1_highway +servercfgfile l4d2-server.cfg -tickrate 60

Ports
==============================================================================================================================
Change ports by editing the command-line
parameters in l4d2server.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
< Client     OUTBOUND   27005  udp

Status: ONLINE

**Comment by Scarsz** [comment]
`rm -r /home/l4d2-1/functions/;/home/l4d2-1/l4d2server details`

**Comment by Montclair** [comment]
loading fn_functions...OK
loading fn_messages...OK
loading fn_getopt...OK
loading fn_details...OK
loading fn_check_ip...OK
loading fn_details_config...OK
loading fn_details_distro...OK

Distro Details
==============================================================================================================================
Distro:    Ubuntu 14.04.1 LTS
Arch:      x86_64
Kernel:    3.13.0-45-generic
Hostname:  TFPG-NJ
tmux:      tmux 1.8
GLIBC:     2.19

Performance
==============================================================================================================================
Uptime:    5d, 22h, 59m
Avg Load:  0.23, 0.16, 0.08

Mem:       total   used   free
Physical:  2.0G    1.9G   89M
Swap:      0B      0B     0B

Disk Usage
==============================================================================================================================
Disk available:  16G
Serverfiles:     9.9G

Left 4 Dead 2 Server Details
==============================================================================================================================
Server name:
Server IP:    104.207.128.135:27015
Status:       ONLINE

Service name:  l4d2-server
User:          l4d2-1
Location:      /home/l4d2-1
Config file:   /home/l4d2-1/serverfiles/left4dead2/cfg/l4d2-server.cfg

Backups
==============================================================================================================================
No Backups created

Command-line Parameters
==============================================================================================================================
./srcds_run -game left4dead2 -strictportbind -ip 104.207.128.135 -port 27015 +clientport 27005 +map c2m1_highway +servercfgfile l4d2-server.cfg -tickrate 60

Ports
==============================================================================================================================
Change ports by editing the command-line
parameters in l4d2server.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
< Client     OUTBOUND   27005  udp

Status: ONLINE

Upon restarting the servers, we get this:

/home/l4d2-1/functions/fn_start: line 72: fn_check_logs: command not found

console logs now have data, but say that tmux 1.8 is broken
Console logging disabled: Bug in tmux 1.8 breaks logging
Currently installed: tmux 1.8

I'm not a linux guru. How do I install a compatible working version on Ubuntu?

**Comment by Montclair** [comment]
SOLVED
Upgraded tmux to 1.9a and the log files contain data again.

ISSUE:
/home/l4d2-1/functions/fn_start: line 72: fn_check_logs: command not found

Do we need to care about this?

**Comment by Montclair** [comment]
I manually downloaded fn_check_logs and added it to the functions directory.  There's a bug somewhere that isn't downloading this when necessary.

**Comment by dgibbs64** [comment]
If you get any bugs like that always delete the functions dir. This will make sure you have the latest version :-).

**Comment by dgibbs64** [comment]
O wait yeah my fault. Forgot to add the new function to fn_functions

**Comment by Montclair** [comment]
Have you fixed this now?

**Comment by dgibbs64** [comment]
Nope not yet. Haven't been at my laptop today. Will take 2 mins when I get a chance :-). The bug doesn't break anything though so no need to worry.

**Comment by Montclair** [comment]
I did it manually in our copies. I'm new to GitHub and don't know how to contribute, else I'd do it here for all.

fn_check_logs(){
functionfile="${FUNCNAME}"
fn_runfunction
}

**Comment by dgibbs64** [comment]
Look at github for Windows :). Its the easiest way to get started with githubg

**Comment by Scarsz** [comment]
Go to whatever file you want to edit in the main list and there's an edit button to automatically clone the repo and once you're done editing your copy you can send us a merge request
