### ISSUE TITLE
Update UT99 to v469

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2961]
## User Story

A new version of ut99 server is due to be released. Need to check this an update.

## Basic info

* **Game:** UT99
* **Command:** Install

## Further Information

Old Unreal has taken over development of server releases of UT99. Waiting for a release and when this happens the server files will need to be updated.

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by NeonKnightOA** [comment]
I would rather wait for the official announcement at OldUnreal before updating. v469 is known for having issues with XC_Engine, and the anticheats (the same guy who works in v469 also works with ACE) must be updated as well upon release.

**Comment by Chamberly** [comment]
v469 is still in the beta phase and is supposedly soon to roll out a public testing phase at Old Unreal forum.

More info of that will be here with required sign up: https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1578241813
Send Anth a PM that you want in the beta. Anth is one of the project manager along with ACE.

Hopefully this shed some light on the missing info. that were needed.

**Comment by kvbev** [comment]
v469a has been released today.

https://github.com/OldUnreal/UnrealTournamentPatches/releases
