### ISSUE TITLE
Max Server Players To Be Locked Anyhow!

### ISSUE THREAD

**Issue by NamVr** [GameServerManagers/LinuxGSM#2975]
As a linuxgsm user using csserver (CS 1.6) I want max_players for each of my server to be locked anyhow.

## Basic info

* **Distro:** [Ubuntu 16.04]
* **Game:** [Counter Strike 1.6]
* **Command:** [idk]
* **LinuxGSM version:** [Latest as per 20/7/2020]

## Further Information

I have multiple servers installed in my vps. But I want that max players should be locked in all the servers in my VPS, so preventing users not to change the max players. They can change it easily using common.cfg file and after a restart.

## Further Reading

Alternatively, I can set up a monitor for max players change but I can't see any where here.

**Comment by JimTR** [comment]
why give 'users' the ability to change config files ? why not send all requests via yourself and you edit the values

**Comment by NamVr** [comment]
How?

**Comment by NamVr** [comment]
Currently users can change the config files easily by logging into SSH, then navigating to
lgsm/lgsm-config/csserver/ and here they can change common.cfg

**Comment by JimTR** [comment]
your users have access to lgsm config files so make them writable to you only and not the actual user

**Comment by NamVr** [comment]
I am using Ubuntu 16.04
I have made user like this
`adduser csserver` --> Set password

**Comment by NamVr** [comment]
> your users have access to lgsm config files so make them writable to you only and not the actual user

Can you tell me how can I do it?
Default sudo user is ubuntu,
I am using AWS Ec2

**Comment by JimTR** [comment]
ok chmod (write) the files to you rather than user csserver

**Comment by NamVr** [comment]
> > your users have access to lgsm config files so make them writable to you only and not the actual user
> 
> Can you tell me how can I do it?
> Default sudo user is ubuntu,
> I am using AWS Ec2

That's what I am asking how?

**Comment by JimTR** [comment]
chmod does the trick ..

**Comment by JimTR** [comment]
just remember to allow read from the user

**Comment by NamVr** [comment]
But in my newly made aws system,
I (as sudo ubuntu) have no access to write the files of csserver user

**Comment by JimTR** [comment]
why .. as sudo you have access to everything and can change file permissions as you see fit

**Comment by NamVr** [comment]
I said `it's a newly aws system I just made the instance`

**Comment by JimTR** [comment]
so no sudo ?

**Comment by NamVr** [comment]
I said I have got the sudo access, but in FTP I can't write changes in other user, only read.
Same applies for all other users, they can even read root files

**Comment by JimTR** [comment]
that means you don't have sudo access ... sudo access allows you to read/write everything

**Comment by NamVr** [comment]
But I can access root using `su -`  then password of root I have set
BUT I can write and install packages using sudo .... using ubuntu

**Comment by JimTR** [comment]
confusing your logging in as root ?

**Comment by JimTR** [comment]
I would try sudo -s rather than su -

**Comment by NamVr** [comment]
I didn't really understand I am completly new.

**Comment by dgibbs64** [comment]
It would be very difficult to prevent a user from changing the max players if they have access to the user directories. You would need to ensure that the user only has read-only access to the config-lgsm directory. But this would also mean that they are unable to change any other config settings.

I get the impression you are selling game servers on a slot basis. This isn't really practical for a project like LinuxGSM and would be better off using a full-on game server panel like TCadmin. If you want to sell game servers using LinuxGSM I recommend selling a whole VPS instance that way the user can do what they want within the VPS, instead of setting on a slot basis. Take a look at Linode as they do this with there one-click apps. I hope this helps

**Comment by JimTR** [comment]
oh ok a gonk @dgibbs64

**Comment by NamVr** [comment]
Yes correct
That's what I am asking how can I do it?
I have complete access to my VPS.

**Comment by NamVr** [comment]
I know I need to toggle settings somewhere but how?
And if I can't, then I asked for monitor it? Like crons etc?

**Comment by JimTR** [comment]
Ok lets see what you are doing 
1: you have added a user to administer a game
2: you can admin the total server

**Comment by NamVr** [comment]
Yup I guess

**Comment by JimTR** [comment]
@dgibbs64  unless you chmod the file to permissions that favour the root user rather than the user ?

**Comment by NamVr** [comment]
I use Bitvise to connect thorugh my server via port 22

**Comment by NamVr** [comment]
Is there any way I can chmod so that user can only access the files in server directory:
/home/user/serverfiles/ ?

**Comment by NamVr** [comment]
Security issue I think so,
Can anyone help here?

**Comment by NamVr** [comment]
Okay let a contributor come and help me then.
It can be a feature request.

**Comment by dgibbs64** [comment]
if you change the permissions using `chown` you might be able to give a user access to serverfiles only. But this is something you change on the server level and not something done though LinuxGSM

**Comment by NamVr** [comment]
Ok any detailed guide on how can I do it?

**Comment by dgibbs64** [comment]
I don't have any guides. You will need to learn what chown and chmod commands are. They are pretty basic Linux commands so there are plenty of tutorials out there.

**Comment by NamVr** [comment]
Okay so basically when a user logs into SSH using the username and password that I provide them, they simply directly login into /home/csserver/serverfiles and they can't access any upper files right>

**Comment by NamVr** [comment]
> ## Further Reading
> Alternatively, I can set up a monitor for max players change but I can't see any where here.

That's what I said in my first comment.
It can be a linux gsm feature to prevent max user edition.

**Comment by NamVr** [comment]
Ok let me tell everyone.

Can I use cron jobs? It will automatically rewrite the max players?
Or can I disable the common.cfg and instance.cfg files?

**Comment by kennyLtv** [comment]
> Can I use cron jobs? It will automatically rewrite the max players?

Idk depends on what you make your crons do. You'd have to check the number of slots against what it should be and reboot after you correct it if it's not the correct number.

> Or can I disable the common.cfg and instance.cfg files?

Nope, they can't be disabled. 

I don't believe this to be an LGSM issue, LGSM was intended to provide a simple interface for an admin to manage their game servers. If you are looking for features like locking the number of slots someone can have I'd suggest a panel like TCAdmin or GameCP so you have full control.

**Comment by Grimston** [comment]
Might as well reveal it now, the control panel I am working on is designed to be kind of like TCAdmin or GameCP. I am implementing a whole range of features such as Billing, Internationalization, SSH Console, Server/Game Settings, Plugins/Addons, File Manager, Reports, Multi-Tenancy, Containerized game servers... all sorts of fancy and handy features to make this kind of thing possible with LinuxGSM.

I hope to have an early Alpha test available in a week or two using SSH connections to single installation game servers, the Agent controlled container servers will be sometime after that.

**Comment by NamVr** [comment]
I understand.
But I have still not got my answers how can I do it?
I know there must be a way.

**Comment by kennyLtv** [comment]
In all fairness how you do it isn't an LGSM issue, you'll have to figure out what is best on your end to manage that.

**Comment by NamVr** [comment]
No sorry, I was here as by a feature request, not for suggestions in my vps. Kindly understand it's a feature request.
Can we make _default.cfg call from root user or outside the main user?
Or there must be a way for monitoring? I know that it's typical, but I think we can have a monitor every time the server restarts it checks the maxplayer variable and if it changes, it can inform us via slack or discord alerts as we have this feature in built already.

**Comment by dgibbs64** [comment]
As I already stated your feature request for monitoring max players would take time for me to develop, is not something that anyone else will ever require, so I will not be developing it. The only reason you want it is to stop your customers from altering max players. Why would I develop a feature in my spare time for free when it is only useful to one person who wants the feature to make money?

We have provided several suggestions and options for you to try such as altering config permissions, using a full web panel for reselling game servers, selling individual VPS's to people. You could even write your own script to monitor max players yourself using something like gamedig. You are welcome to look at the LinuxGSM code to get examples and develop a script yourself.

**Comment by NamVr** [comment]
Why you guys always think that it's only for money?
Anyways I am ok to do the monitoring by myself if you don't wanna develop this thing.

**Comment by dgibbs64** [comment]
Because you are trying to sell counter-strike 1.6 servers on your website 🤷
