### ISSUE TITLE
[Rust] No Logging

### ISSUE THREAD

**Issue by JimDeadlock** [GameServerManagers/LinuxGSM#2978]
## User Story

As a rustserver admin, I want a fix so that server logs are produced.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Rust]
* **LinuxGSM version:** [v20.4.0]

## Further Information

Since the LGSM update 3 days ago, my rustserver is no longer producing any server logs at all even after restarts. They would normally appear in the default directory ~/log/server - I have not made any config changes, all I did was run update and update-lgsm

**Comment by dgibbs64** [comment]
The logs are now under console logs. This is the only way to get a console output

**Comment by alazymeme** [comment]
> The logs are now under console logs. This is the only way to get a console output

So there's no more log output to file? Doesn't sound right since logfiles can be very important

**Comment by JimDeadlock** [comment]
He means the logs (same format as before) now appear in ~/log/console instead of (previously) ~/log/server

**Comment by dgibbs64** [comment]
yup what @JimDeadlock said. I am closing this as logs are working 👍
