### ISSUE TITLE
Can not install GMOD 

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#2979]
Issues raised here are **ONLY** for:
* LinuxGSM bugs.
* Feature suggestions.
* Code contributions.

## User Story

As a [user description], I want install a game 

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Garry's Mod]
* **Command:** [install]
* **LinuxGSM version:** [v20.1.3]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.
installer fails with a mkdir error see attached file
[output.txt](https://github.com/GameServerManagers/LinuxGSM/files/4959197/output.txt)

## To Reproduce

Steps to reproduce the behaviour:
1. run linuxgsm.sh gmodserver
2. run the downloaded gmodserver
3. See attached file

## Expected behaviour
install game

**Comment by dgibbs64** [comment]
The variable that defined the directory is broken. Has the code been modified?

**Comment by JimTR** [comment]
nope this was a total clean install downloading linuxgsm.sh  then running linuxgsm.sh gmodserver then ./gmodserver i 
just tried it on a totally different machine with pvkiiserver same result

**Comment by JimTR** [comment]
Any update ? tried loads of different servers all fail

**Comment by dgibbs64** [comment]
I have checked this and can not replicate it myself. For whatever reason, the variable $serverfiles is not being defined as it looks black in the log you posted. Also looking at the header it appears you are not using the latest version of linuxgsm (as I updated with the latest release).

**Comment by JimTR** [comment]
Found out the problem ... it was a sym linked lgsm directory for some reason the installer would not write to it so it contained the old files
