### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#2981]
## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** [v20.1.3]

## Further Information

running gameserver u throws a permissions error 
<img src="https://i.imgur.com/XFjhNpf.png">

perhaps this is not an issue to most but this is a point out that it can occur. In the screen shot you can see directories for users that are in the group.
so the /home/user directory is owned user:group
the directories that can not be opened are owned subuser:group hence find hits the permissions error. I would guess not many have set ups like this so not really that important .. more of a heads up.

I have this setup so all emails/web content & apps  pertaining to a domain are stored in one location, which does make it easier to produce archives for that domain as I just archive the user folder and all info is contained in it rather than adding var/mail usr/bin etc to it  
## To Reproduce

Steps to reproduce the behaviour:
1. create directory with valid permissions for another user in the same group
2. run gameserver u
3. See error

## Expected behaviour
none really as the script does work just looks a little ugly
I did notice however, that the <b>u</b> command appears to scan the home folder twice, which you may want to look at

**Comment by h3o66** [comment]
This is something rly special to your linux/user config on your server.
Not sure what we would need to exclude on our side for the permission check
