### ISSUE TITLE
CPU pinning for gameservers

### ISSUE THREAD

**Issue by ToeiRei** [GameServerManagers/LinuxGSM#2986]
## User Story

As a server admin with some knowledge about linux, I want to pin the gameserver to a CPU/core so that you can improve the performance of some gameservers

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** [v20.1.3]

## Further Information

Older Unreal Engines - especially the one ARK Survival uses is not really well built for modern servers. So the idea is to have the ability set the affinity of the gameserver to improve the 'ping pong' between cores. 

## Further Reading
* https://linux.die.net/man/1/taskset
* https://www.linuxjournal.com/article/6799

**Comment by dgibbs64** [comment]
Nope. Bad idea. Don't know how many times I have to close issues with people thinking that CPU affinity somehow better than the kernel dealing with assigning processes to cores itself. Just don't do it. It won't improve things.

https://docs.linuxgsm.com/support/faq#can-i-bind-game-servers-to-a-given-cpu-core

**Comment by dgibbs64** [comment]
Also sorry to come off a little rude. I have just lost track of the number of people requesting this.
