### ISSUE TITLE
LGSM Factorio not all config done in Game Server Config (instance.cfg); server name display incorrectly using ./fctrserver details

### ISSUE THREAD

**Issue by Verstand3n** [GameServerManagers/LinuxGSM#2987]
## User Story

not all options can be set in fctrserver.cfg. examples are:
- servername
- serverpassword
- authentication token (to display server in public server browser)
- savegame intervall & amount of versions to keep
these have to be changed in the /home/fctrserver/serverfiles/data/fctrserver.json

while this is fine, using ./fctrserver details lists "Factorio Server" for the server name instead of the one used in /home/fctrserver/serverfiles/data/fctrserver.json. However server name is displayed correctly (as set in json file) in server browser.

## Basic info

* **Distro:** Ubuntu 20.04.1 LTS
* **Game:** Factorio
* **Command:** details
* **LinuxGSM version:** [v20.1.3]

## Further Information

./fctrserver details lists "Factorio Server" for the server name instead of the one used in /home/fctrserver/serverfiles/data/fctrserver.json.

## To Reproduce

Steps to reproduce the behaviour:
1. install factorio server (here experimental)
2. name server in /home/fctrserver/serverfiles/data/fctrserver.json
3.  run ./fctrserver details
4. check server name

## Expected behaviour

./fctrserver details should output server name as set in line 2 of /home/fctrserver/serverfiles/data/fctrserver.json:

{
  "name": "Name of the game as it will appear in the game listing",
...

**Comment by h3o66** [comment]
if you have time, can you maybe test the linked PR ?
