### ISSUE TITLE
[LGSM] Support RCON for applicable games

### ISSUE THREAD

**Issue by Montclair** [GameServerManagers/LinuxGSM#299]
When using the gsquery.py plugin to monitor a server, it causes the server to restart when it's not really crashed.  This happens when we load a config that uses sv_cheats 1.  It's a practice config called L2L Config, not that that's of any importance. It's the sv_cheats 1 that's the issue (I and others in the community believe).

Specifically, when the server is running in this mode, it is not responsive to status queries, thus, gsquery.py thinks the server has crashed when it has not, and causes it to restart. I've checked the logs and verified it:

Feb 24 21:00:02 l4d2-server3: Monitor: Checking session: CHECKING
Feb 24 21:00:03 l4d2-server3: Monitor: Checking session: OK
Feb 24 21:00:04 l4d2-server3: Monitor: Detected gsquery.py
Feb 24 21:00:05 l4d2-server3: Monitor: Querying port: 104.207.128.135:27017 : QUERYING
Feb 24 21:00:11 l4d2-server3: Monitor: Querying port: 104.207.128.135:27017 : ERROR: Unable to receive
Feb 24 21:00:12 l4d2-server3: Monitor: Waiting 30 seconds to re-query
Feb 24 21:00:42 l4d2-server3: Monitor: Detected gsquery.py
Feb 24 21:00:43 l4d2-server3: Monitor: Querying port: 104.207.128.135:27017 : QUERYING
Feb 24 21:00:49 l4d2-server3: Monitor: Querying port: 104.207.128.135:27017 : ERROR: Unable to receive
Feb 24 21:00:50 l4d2-server3: Restarting: 
Feb 24 21:00:50 l4d2-server3: Stopping: 
Feb 24 21:00:51 l4d2-server3: Stopping: Stopped 
Feb 24 21:00:52 l4d2-server3: Starting: 
Feb 24 21:00:53 l4d2-server3: Starting: Rotating log files

I'm asking others in the L4D community if there's a system variable or file that gets created that I could check for existence and perhaps modify your script to abort the call.  But I wanted to put this out there to you in case you possibly had a fix or an idea.

Servers that support RCON

- 7 days to die
- Rust
- Source engine

**Comment by dgibbs64** [comment]
If the server is not responsive to status queries gsquery cannot function as it requires this to monitor and will assume the server is offline. I recommend deleting gsquery unless you can get the query port working on the server.

**Comment by Montclair** [comment]
According to other sysops, Left 4 Dead 2's server will never respond to the type of connect you're doing when cheats are enabled. Is there not some way for you to query the server using rcon?

**Comment by dgibbs64** [comment]
This may be worth me doing at some point. It may be of benefit to get the script to send rcon commands to the server. However this woudl be an enhancement I will look at then I have time.

**Comment by UltimateByte** [comment]
While this is a great idea, it wouldn't work in any case. For example, i disable rcon by not setting a password on my servers as soon of possible for security reasons.

**Comment by Montclair** [comment]
It wouldn't work for you, I think you mean. I'd still like to see this implemented.

**Comment by UltimateByte** [comment]
I'm not against he idea, i just mean that we can't only rely on it as it doesn't work 100%of the time.

**Comment by Montclair** [comment]
Right, but neither does the current method. A combination of the current method, and / or fallback to this method would be an ideal solution.

**Comment by UltimateByte** [comment]
Agreed since my first remark, i was just warning : Don't rely ONLY on rcon querying after implementing it !

**Comment by UltimateByte** [comment]
Some insight about an rcon script:
http://steamcommunity.com/groups/linuxgsm/discussions/0/144513670981268947/?tscn=1484856066
Source: http://www.ark-survival.net/en/2015/07/09/rcon-tutorial/
Full script: https://www.ryanschulze.net/archives/1052

**Comment by UltimateByte** [comment]
For Rust:
https://github.com/dcodeIO/WebRcon

**Comment by UltimateByte** [comment]
Ideas on how to use RCON:

1) Open an RCON prompt
2) Monitor the server
3) Send alerts before server restart upon updates

**Comment by dgibbs64** [comment]
Query will wait up to 60 seconds before triggering a reboot this has worked in preventing a server being restarting during a map change. Also a planned "send" command for servers that support entering commands into the console.

**Comment by brandonsturgeon** [comment]
Garry's Mod would benefit from rcon commands - especially when doing things like running `stop`. The way we pipe stuff into tmux right now isn't super reliable and could be avoided by using rcon. (This would also be a great way to query the server to decide if the server is actually running, as I believe the server can respond to status requests even while changing maps)

**Comment by dgibbs64** [comment]
RCON support is choppy at best and varies greatly depending on the game server. Supporting a few game servers that all work very differently is a massive use of dev time. I don't see adding rcon support as viable unless there is a module similar to gamedig that is well supported (there are a few projects that seem pretty dead).
