### ISSUE TITLE
[Feature Request] Exitmode: CTRL+C + `quit` command

### ISSUE THREAD

**Issue by TheByKotik** [GameServerManagers/LinuxGSM#2992]
## User Story

When server source engine's server use `-autoupdate` launch option then it restarting after `quit` or `exit` and this methods fails.
But, if you send CTRL+C before this commands then server closes successfully.

Actual for my little CSGO server. Every restart i'm compelled do in manual mode or wait 30 seconds.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [CSGO]
* **Command:** [stop]
* **LinuxGSM version:** [v20.4.1]

## Further Information

1. Send CTRL+C to server console.
2. Send `quit` to server console.
3. ... You great!

**Comment by h3o66** [comment]
Added a PR that should allow to do this, if you want to test this maybe ?

**Comment by TheByKotik** [comment]
> Added a PR that should allow to do this, if you want to test this maybe ?

Works!

![image](https://user-images.githubusercontent.com/40791562/104152732-3fae7e00-5402-11eb-8267-2f90873674fa.png)
