### ISSUE TITLE
Retire Serious Sam 3 and Goldeneye: Source server

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2995]
## User Story

As a developer, I won't retire Serious Sam 3 server as no one seems to use it and it keeps breaking. It is no longer worth while supporting.

## Basic info

* **Distro:** Ubuntu 20.04
* **Game:** Serious Sam 3 & Goldeneye: Source

**Comment by dgibbs64** [comment]
remove any remaining references to goldeneye source as well

**Comment by h3o66** [comment]
Done in Release 20.6.0
