### ISSUE TITLE
San Andreas Multiplayer will not start

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#2999]
## User Story

San Andreas Multiplaye server will not start

## Basic info

* **Distro:** Ubuntu 18.04

**Comment by h3o66** [comment]
This is related to the fact that the default config is not overwritten with the installation.

So the default rcon_password blocks the startup of the server, from the log:
`Error: Your password must be changed from the default password, please change it.`

So either remove the default config from the archive or add the default config to the archive would be a solution for this.
Last option could be to move the default config away to another name.

What do you think @dgibbs64 ?

**Comment by h3o66** [comment]
Done in Release 20.6.0
