### ISSUE TITLE
[Insurgency] unable to open emails

### ISSUE THREAD

**Issue by funkertosh** [GameServerManagers/LinuxGSM#300]
OpenVZ - CentOS 6

The emails are being sent out using base64 encoding.

If the email goes to my Gmail address it comes through as a blank email with an attachment called 'noname'.

If I send it to another address and pull it down with Outlook it has the full file name, but is a .dat file.

It doesn't have the .log extension so you can't open it. In both cases you have to manually open the file with notepad.

I checked my versions and I have the latest.

I tried adding .log to my mime.types as text/plain but it did not help (may help if the file gets sent as .log).

I think mail has a -a flag that allows you to attach a file. 

Let me know if you need any further information.

**Comment by dgibbs64** [comment]
This is an issue with postfix rather than a script issue. I have sent many emails to my gmail account with different distros without issues. Linux does not use file extensions like Windows. The extension name could be called anything but you can still open with notepad.
