### ISSUE TITLE
[Feature request] Send Commands via Telegram to start/stop servers

### ISSUE THREAD

**Issue by dproxinfo** [GameServerManagers/LinuxGSM#3001]
I am not always at the PC, but it would be a nice possibility to start/stop/monitor certain servers via Telegram. Telegram Bots offer the possibility to read out chats.
So also further persons could (re-)start servers from "on the way".

## Further Information

An alarm function is already integrated in LinuxGSM. But I could not find an extended control.

Because you can read the chat of Telegram Bots, you could also implement the control of the servers. 
Example:

- Read out chat via URL https://api.telegram.org/botXXXXXXXXXX::XXXXXXXXXXXXX/getUpdates
- filter important things (messageid, chatid, sender name, command)
(- maybe check server status and if command is possible (you can't stop an already stopped server)
- send it to linux shell
- inform on telegram (several ways - see below)

Since programming is not my strength, I can unfortunately only offer suggestions.

Inform on telegram:

1. Send info to user who wants to start/stop the server
2. Send info to a special groupid (for example a group with all server admins)

Maybe you can filter the permissions by sender name or ChatID.

I can try to provide more information if needed.

dprox

**Comment by ToeiRei** [comment]
Implementation in the lgsm makes no sense at all for this as it would require the lgsm to be a 'server'. But in case you want a solution, feel free to test external tools like node-red.

**Comment by dgibbs64** [comment]
out of scope and not practical to implement. closing
