### ISSUE TITLE
[kfserver] Assigning an IP doesn't work correctly

### ISSUE THREAD

**Issue by Kanarota** [GameServerManagers/LinuxGSM#3004]
## User Story

Hello,

I have a server with a hosting company, as well as an additional Public IP address attached to it. I want to leave the main IP address alone for server maintenance/administration (SSH, etc), while the additional IP is used to host the Killing Floor game server.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Killing Floor]
* **Command:** [N/A]
* **LinuxGSM version:** [v20.4.1]

## Further Information

When I specify LinuxGSM to use the secondary IP address in kfserver.cfg, it will say it's hosted on that IP, but it's not reachable. The server instead is hosted on the main IP.

Here is the post details: https://termbin.com/gffj

The interesting thing is that the WebAdmin portion of the server is correctly bound to the secondary IP address, instead of the primary one.

When I host a minecraft server as a test, it binds correctly to the specified IP address, leading me to believe the issue might be related to the kfserver script.

## To Reproduce

Steps to reproduce the behaviour:
1. Install kfserver following the steps here: https://linuxgsm.com/lgsm/kfserver/
2. Configure the common/instance CFG to use a different IP address.
3. Start the server.
4. Try to connect through the specified IP address

## Expected behaviour
Server should be reachable through the specified IP address

**Comment by h3o66** [comment]
I would guess this cen be configured via the game config.
There is a host parameter, that might help.
Could you test this ?
From the default config:
https://github.com/GameServerManagers/Game-Server-Configs/blob/master/KillingFloor/Default.ini#L8

**Comment by h3o66** [comment]
With my tests it looked like that the gameserver does gets stuck when you set a ip in the game config.

From my POV this looks like more a game server bug.
