### ISSUE TITLE
chroot (jailkit) dependencies for LinuxGSM

### ISSUE THREAD

**Issue by macuco-de** [GameServerManagers/LinuxGSM#3013]
## User Story

Hello all. I wonder if there is a tutorial how to install a gameserver in a jailkit environment. Tried it but I don't know where to get the dependencies for commands/packages I have to give to the jail. 

For me the environment in a jail has some benefits: Using an intact and secure webserver configuration with ftp access for users where they then can edit configs, maps etc. already owning the correct permissions for the files.

My current jail has the following settings:
[basicshell]
comment = bash based shell with several basic utilities
executables = /bin/sh, /bin/bash, /bin/ls, /bin/cat, /bin/chmod, /bin/mkdir, /bin/cp, /bin/cpio, /bin/date, /bin/dd, /bin/echo, /bin/egrep, /bin/false, /bin/fgrep, /bin/grep, /bin/gunzip, /bin/gzip, /bin/ln, /bin/ls, /bin/mkdir, bin/mktemp, /bin/more, /bin/mv, /bin/pwd, /bin/rm, /bin/rmdir, /bin/sed, /bin/sh, /bin/sleep, /bin/sync, /bin/tar, /bin/touch, /bin/true, /bin/uncompress, /bin/zcat, /bin/readlink
regularfiles = /etc/motd, /etc/issue, /etc/bash.bashrc, /etc/bashrc, /etc/profile
directories = /usr/lib/locale/en_US.utf8
users = root
groups = root
includesections = uidbasics

Currently I'm stuck at:
usr1@srv1:~$ bash linuxgsm.sh fctrserver
fetching GitHub serverlist.csv...ERROR
fetching Bitbucket serverlist.csv...FAIL
linuxgsm.sh: line 123: core_exit.sh: command not found
[ FAIL ] serverlist.csv could not be loaded.

## Basic info

* **Distro:** [Debian 10]
* **Command:** [installation]
* **LinuxGSM version:** [v20.1.3]

**Comment by yamikaitou** [comment]
that current message is related to missing cURL. Don't know what other ones you'd need but that would address the message you got

**Comment by macuco-de** [comment]
Hello Ryan,

Thank you for your reply. curl alone isn't the matter. Installed it in jail but it is still the same error.
