### ISSUE TITLE
Downloading issue in some scripts

### ISSUE THREAD

**Issue by cclecle** [GameServerManagers/LinuxGSM#3018]
## Basic info

* **Distro:** [Debian 10 (LXC container)]
* **Game:** [UT2004 and Q3A]
* **Command:** [install]
* **LinuxGSM version:** [latest]

## Further Information

when the installer try to install a game it fail with wrong MD5 checksum.
After checking the game installation file, I figured out that it is not even downloaded (or not fully).

I found a hot fix in _**core_dl.sh**_ : I add "--max-redirs -1" argument to curl command, and it work !
Without this fix at least those two game cant install here.

**Comment by dgibbs64** [comment]
Thanks. This is being investigated

**Comment by dgibbs64** [comment]
The issue should be resolved now. Thanks for reporting this.
