### ISSUE TITLE
Quake 3 arena

### ISSUE THREAD

**Issue by SmOkEnksp** [GameServerManagers/LinuxGSM#3019]
hello. for 2 days i cant install server with error:
`verifying quake3-1.32c-x86-full-linux.tar.xz with MD5...FAIL
quake3-1.32c-x86-full-linux.tar.xz returned MD5 checksum: 741839f346d6e8126ae38ee76a96fd12
expected MD5 checksum: b0e26d8919fe9313fb9d8ded2360f3db
`
how i can fix it?
ubuntu 16.04

**Comment by dgibbs64** [comment]
Thanks. This is being investigated

**Comment by dgibbs64** [comment]
The issue should be resolved now. Thanks for reporting this.

**Comment by SmOkEnksp** [comment]
sorry but didnt working
[https://i.imgur.com/8rc60fN.png](url)

**Comment by SmOkEnksp** [comment]
NVM! after i delete all files and redownload - all good.
