### ISSUE TITLE
TF2 server manager fn_check_logs error on restart

### ISSUE THREAD

**Issue by lordgandalf** [GameServerManagers/LinuxGSM#302]
When i restart my server the following error appears: /opt/tf2server/functions/fn_start: line 72: fn_check_logs: command not found.
It seems that in fn_start there is a reference to fn_check_logs which isnt a thing it seems ?

**Comment by Scarsz** [comment]
See if `rm -r /opt/tf2server/functions` helps

**Comment by lordgandalf** [comment]
That seems to have fixed the problem thanks for the quick reply

Date: Fri, 27 Feb 2015 01:45:10 -0800

**Comment by Scarsz** [comment]
Glad it's working
