### ISSUE TITLE
[Server Request] Valheim

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#3021]
## What game server would you like adding?

Valheim

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

896660

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by dgibbs64** [comment]
Valheim is not yet released on steam. Will hold this until then

**Comment by AlasdairHaig** [comment]
HI dgibbs64, 

Valheim will be out on February 2 in Early Access on Steam. I hope that it will be available on master by release day, if possible. I will be linking this project in Valheim's Discord Channel for people interested. I will find some time to double check if there are any differences other than the Steam AppID, though I think the last update of code should be still valid.

Thanks

**Comment by Ross-Carran** [comment]
Oh the server is currently listed as only accessible by owners, so until Dvoid changes it to public, no-one will be able to prepare servers until release.
He has said it is a headless server.

**Comment by dgibbs64** [comment]
If I can get access to the serverfiles then I can get it ready. If I can't get it ready for this release I will do this as a hotfix to get it out sooner :)

**Comment by fs86** [comment]
Dedicated server files should be released now ;-)
https://steamdb.info/app/896660/

**Comment by thegreatstorm** [comment]
[server.pdf](https://github.com/GameServerManagers/LinuxGSM/files/5913833/server.pdf)
![image](https://user-images.githubusercontent.com/29154863/106648910-85202000-6556-11eb-98b7-63196f53f607.png)

**Comment by dgibbs64** [comment]
Valheim dedi server requires steam login. I will need to contact the game devs and request this is changed

**Comment by thegreatstorm** [comment]
I wonder if they fixed that, I got it working without requiring the login. I used anonymous login.

**Comment by fs86** [comment]
> Valheim dedi server requires steam login. I will need to contact the game devs and request this is changed
> 
> ```
> Logged in OK
> Waiting for user info...OK
> ERROR! Failed to install app '896660' (No subscription)
> ```

Maybe they fixed it by now, because according to this post it should work without login:
https://steamcommunity.com/app/892970/discussions/0/3104638448267511835/#c3104638448267538046

**Comment by dgibbs64** [comment]
Thanks. I will take a look this evening 🧑‍💻

**Comment by Mondrethos** [comment]
Was about to request this, glad to see someone already did. Keep up the great work!

**Comment by h3o66** [comment]
Now release with version 21.1.2
