### ISSUE TITLE
Eco 0.9 Server wont start

### ISSUE THREAD

**Issue by Fastor01** [GameServerManagers/LinuxGSM#3022]
## User Story

As a server admin, I want start the eco server so that I can play.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Eco]
* **Command:** [Start]
* **LinuxGSM version:** [v20.1.3]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:
1. Update a 0.8.x eco Server via ./ecoserver update to 0.9
2. ./ecoserver start
3. wont start because the executable can not found

script log: 
Success! App '739590' fully installed.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
Sep 12 14:35:11.722 ecoserver: FIX: INFO: Applying steamclient.so fix: Eco
mkdir: created directory '/home/gameserver/.steam/sdk32'
'/home/gameserver/Server/steamcmd/linux32/steamclient.so' -> '/home/gameserver/.steam/sdk32/steamclient.so'
Sep 12 14:35:12.288 ecoserver: FIX: PASS: Applying steamclient.so fix: Eco
Sep 12 14:35:12.293 ecoserver: ALERT: INFO: Sending alert: Updated
Sep 12 14:35:12.597 ecoserver: UPDATE: PASS: command_update.sh exiting with code: 0
Sep 12 14:35:13.402 ecoserver: CHECK: FATAL: Executable was not found: /home/gameserver/Server/serverfiles/EcoServer.exe
Sep 12 14:35:13.407 ecoserver: CHECK: FATAL: check_executable.sh exiting with code: 1

Eco have now a executable name "Ecoserver" in the same directory. 

## Expected behaviour
server starts

**Comment by h3o66** [comment]
looks like we did open almost at the same time the issue.
This will be tracked in #3023 
I already submitted a PR to fix this #3024
