### ISSUE TITLE
Cannot start eco server due wrong executable name

### ISSUE THREAD

**Issue by h3o66** [GameServerManagers/LinuxGSM#3023]
## User Story

As a server admin i want that the server can be started.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Eco]
* **Command:** [start]
* **LinuxGSM version:** [v20.4.1]

## Further Information

server executable was changed by the gamedevs.

Also eco has now a glibc dependency ( Version: 2.14 )

## To Reproduce

Steps to reproduce the behaviour:
1. install eco server
2. start server

## Expected behaviour

The server just starts

EDIT: it seems that also the libgdiplus is needed now for the server

**Comment by gOOvER** [comment]
Don't folgst, that Dev's now recommend DotNet insteed of Mono

**Comment by h3o66** [comment]
> Don't forget, that Dev's now recommend DotNet insteed of Mono

Interesting is there anywhere a info about this ?

**Comment by gOOvER** [comment]
> > Don't forget, that Dev's now recommend DotNet insteed of Mono
> 
> Interesting is there anywhere a info about this ?

See: https://steamcommunity.com/app/382310/discussions/0/2952628643852610480/?ctp=2#c2952628643856198863

**Comment by gOOvER** [comment]
mb you need to use such a startscript:

`export DOTNET_BUNDLE_EXTRACT_BASE_DIR=./dotnet-bundle &&  ./EcoServer`

I maintain the ECO Egg for Pterodactyl Gameserver Panel

**Comment by h3o66** [comment]
Even without a installed dotnet it seems to work.
Comment from the dev there:

> Eh, we support Linux natively with dotnet now, you really shouldnt be using Mono at all anymore. Just use SteamCMD on a linux server, download the server and install 'dotnet', then ./EcoServer, done.

So probably dotnet is only needed for mods then i guess.

**Comment by gOOvER** [comment]
> Even without a installed dotnet it seems to work.
> Comment from the dev there:
> 
> > Eh, we support Linux natively with dotnet now, you really shouldnt be using Mono at all anymore. Just use SteamCMD on a linux server, download the server and install 'dotnet', then ./EcoServer, done.
> 
> So probably dotnet is only needed for mods then i guess.

Nope, it runs with Mono, but it's not recommended.

**Comment by h3o66** [comment]
The latest version does seem to run without a installed dotnet core or mono.
Only the new dependency seems to be needed.
For lgsm I just tried this with the debug mode.

**Comment by dgibbs64** [comment]
If I remember correctly from speaking with a Eco dev months ago 0.9.0 was doing away with mono.

**Comment by samjco** [comment]
Getting error:
[ FAIL ] Starting ecoserver: executable was not found

**Comment by dgibbs64** [comment]
Next release fixes the issue. Major changes with 0.9.0
