### ISSUE TITLE
Eco server fails on network initialization v9.0.1

### ISSUE THREAD

**Issue by cerelis** [GameServerManagers/LinuxGSM#3025]
## User Story

After upgrading the server is no longer responsive. 
DotNet is installed.
ecoserver.cfg has been modified from "mono ./ecoserver.exe" to "./ecoserver

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Eco]
* **Command:** [Start]
* **LinuxGSM version:** [v20.1.4]
steamcmd.log : https://hastebin.com/ugeyitoyoj.sql
postdetails: https://hastebin.com/conexedovo.sql

## Further Information

```Unhandled exception. System.InvalidOperationException: Host creation call failed
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit, UInt32 incomingBandwidth, UInt32 outgoingBandwidth, Int32 bufferSize)
   at ENet.Host.Create(Address address, Int32 peerLimit, Int32 channelLimit)
   at ENet.Host.Create(Address address, Int32 peerLimit)
   at Eco.Networking.ENet.ENetUdpPeer.Start()
   at Eco.Plugins.Networking.NetworkServer.Initialize(IUdpLibrary udpLib)
   at Eco.Plugins.Networking.NetworkManager.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()```

## To Reproduce

./ecoserver st

**Comment by h3o66** [comment]
The error does not look like it is complete, can you check if you can post the lines before the error as well, or the complete logfile from `serverfiles/Logs/` ?

Please check as well if you have `libgdiplus` installed, that seems to be needed for the latest release of the server

**Comment by dgibbs64** [comment]
Also note a big change for Eco will be releasing
 changes in next release of LinuxGSM

**Comment by cerelis** [comment]
Here's the output from apt and console log file. Please let me know if you need anything else.

```
ecoserver@ecoserver:~$ apt search libgdiplus
Sorting... Done
Full Text Search... Done
libgdiplus/bionic,now 4.2-2 amd64 [installed,automatic]
  interface library for System.Drawing of Mono
```

[ecoserver-console.log](https://github.com/GameServerManagers/LinuxGSM/files/5214278/ecoserver-console.log)

**Comment by h3o66** [comment]
This looks to me that the issue might have something to do with this:
https://github.com/StrangeLoopGames/EcoIssues/issues/18139

Did you modify the config `serverfiles/Configs/Network.eco` in any way ?

**Comment by cerelis** [comment]
Here's my Network.Eco config. Items marked as <redacted> have data, but i've removed it.
{
  "PublicServer": true,
  "Playtime": "",
  "Password": "<redacted>",
  "Description": "<redacted>",
  "DetailedDescription": "",
  "ServerCategory": "None",
  "IPAddress": "Any",
  "RemoteAddress": "",
  "GameServerPort": 3000,
  "WebServerPort": 3001,
  "Rate": 20,
  "MaxConnections": -1,
  "ID": "<redacted>",
  "Passport": "<redacted>",
  "UPnPEnabled": true
}

**Comment by h3o66** [comment]
@cerelis i edited your comment so that the removed parts are visible.
My last guess is that this is related to the Password or Description - try to change these to something plain (No special chars in the Description and Password) and then try again.
If this does not help, I would prefer that you ask for support on the Eco discord or other channel of them.

**Comment by cerelis** [comment]
I backed up the current network.eco and copied the network.eco.template to network.eco with no modifications. Still the same issue. It would seem to me that if other people are getting the linux version to run via Docker, then the issue _**is**_ related to LGSM, since that's the only difference here.

**Comment by cerelis** [comment]
Okay. I discovered what the issue was. I had disabled IPv6 via Grub in the /etc/default.grub with "ipv6.disable=1". Once that was removed, the problem went away.
