### ISSUE TITLE
[callofduty1] Server Request 

### ISSUE THREAD

**Issue by spudy12** [GameServerManagers/LinuxGSM#304]
Just wondering if it would be possible to add support for call of duty 1 server? Your scripts work wonders

**Comment by Scarsz** [comment]
The best and really only guide I found is this http://forum.fdcservers.net/showthread.php?t=1211 which explains that you have to have files off of the actual discs be transferred over, something I don't know if we'd really want to do because of copyright issues though I'm not exactly sure Activision would care for abandonware

Up to you @dgibbs64

**Comment by dgibbs64** [comment]
It may be possible however the admin would probably have to provide the files. I dont have a copy of the game and there would not be much demand for it to warrant me spending time on it, However I would be happy to merge it if someone else developed this.

**Comment by spudy12** [comment]
Yes you do require a copy of the game files but I think its only the specific core files. All executables can be stripped out. The game still requires a valid key to install even once ripped off the discs. I would be happy to host a copy of them for users if needs be. I don't think it would be an issue as it is abandonware as you say but you never know. 
Perhaps if the user does need to provide the files, with the scripts saying "put CD files here" 

Anyway, I understand if you don't think there is much demand to warrant doing this. Would be great to have your script to install / run it though

Currently use screen command 
#!/bin/sh
screen -d -m -S cod bash -c 'cd /home/servers/cod1 && ./cod_lnxded +set_dedi$

Can provide a copy of the game if you do decide to

Cheers

**Comment by dgibbs64** [comment]
@spudy12 it is worth seeing if you can get it working yourself using an existing script. Normally I just adapt an existing one to create a new one. For the basics you can change the relevant variables and set the parms for cod 1. the hard part would probably be getting the details to work. However if you can get this working and send me a merge request or email me your script. Then let me know ports etc and I can tidy it up.
