### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by xSL0W** [GameServerManagers/LinuxGSM#3042]
## User Story

When i start my server, stop it, etc this warning pops up:

arena@tni:~$ ./csgoserver stop
Warning! Missing dependencies: steamcmd
Warning! arena does not have sudo access. Manually install dependencies.
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install steamcmd
[ INFO ] Stopping csgoserver: LinuxGSM is already stopped

Im using debian10, so i dont have this package in my repo.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [CSGO]
* **Command:** [Kinda all commands, start, stop, debug, etc]
* **LinuxGSM version:** [Latest, v20.4.1]

## Further Information

The fix was to remove "non free" from all my /etc/apt/sources.list
Go to file lgsm/functions/check_deps.sh, lines 362-370

> 	# If requires steamcmd.
	if [ "${appid}" ]; then
		# Will not use apt if non-free repo is missing or Ubuntu 14.04
		if [ "${distroversion}" == "14.04" ]||[ "${distroid}" == "debian" ]&& ! grep -qE "^deb .*non-free" /etc/apt/sources.list; then
			:
		else
			array_deps_required+=( steamcmd )
		fi
	fi

This is the function that causes the error.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to your home directory
2. Use a command like ./csgoserver stop
3. Wait for the error

**Comment by dgibbs64** [comment]
steamcmd package is in the non-free repo. So the logic is if the non-free repo is available then steamcmd can be installed. If it is missing then use the old fashioned way

**Comment by h3o66** [comment]
all debian 10 standard repos should have the non-free part enabled
example:
```
deb http://deb.debian.org/debian/ buster main contrib non-free
```

**Comment by xSL0W** [comment]
> root@tni:~# apt update
Hit:1 http://deb.xanmod.org releases InRelease
Get:2 http://security.debian.org buster/updates InRelease [65.4 kB]
Hit:3 http://ftp.ro.debian.org/debian buster InRelease
Get:4 http://ftp.ro.debian.org/debian buster-updates InRelease [51.9 kB]
Get:5 http://ftp.ro.debian.org/debian buster/non-free Sources [85.6 kB]
Get:6 http://security.debian.org buster/updates/main Sources [138 kB]
Get:7 http://ftp.ro.debian.org/debian buster/non-free amd64 Packages [87.7 kB]
Get:8 http://ftp.ro.debian.org/debian buster/non-free Translation-en [88.8 kB]
Get:9 http://security.debian.org buster/updates/non-free Sources [692 B]
Get:10 http://security.debian.org buster/updates/main amd64 Packages [231 kB]
Get:11 http://security.debian.org buster/updates/main Translation-en [124 kB]
Get:12 http://security.debian.org buster/updates/non-free amd64 Packages [556 B]
Get:13 http://security.debian.org buster/updates/non-free Translation-en [344 B]
Get:14 http://ftp.ro.debian.org/debian buster-updates/non-free Sources [716 B]
Get:15 http://ftp.ro.debian.org/debian buster-updates/non-free amd64 Packages [604 B]
Get:16 http://ftp.ro.debian.org/debian buster-updates/non-free Translation-en [673 B]
Fetched 876 kB in 1s (1,523 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@tni:~# apt install steamcmd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package steamcmd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'steamcmd' has no installation candidate


There is no package steamcmd in non-free repo

**Comment by xSL0W** [comment]
https://termbin.com/ca0ux

**Comment by h3o66** [comment]
it is in the debian repos:
https://packages.debian.org/buster/steamcmd

So not a bug on LGSM side.

then the 32 bit packages are not enabled:
You need to execute the command, what was posted by the script:
`sudo dpkg --add-architecture i386; sudo apt update; sudo apt install steamcmd`

**Comment by xSL0W** [comment]
its very weird, it didnt worked on that specific dedicated server, i will try it again when i will get access back, thanks!
