### ISSUE TITLE
Change port is CS1.6 server

### ISSUE THREAD

**Issue by Adrenalin231** [GameServerManagers/LinuxGSM#3050]
I wanna change a cs1.6 port because i have one more server on my linux server and i don't know how to do it.
i add this line to the csserver.cfg - port="27020" and its do nothing. Please help me :C

**Comment by h3o66** [comment]
You need to change 2 ports, there is the notmal port and the client port.
Example:
```
port="27016"
clientport="27006"
```
These need to be added to the csserver.cfg if these settings are not already there.

**Comment by Adrenalin231** [comment]
Okey thx bro

**Comment by Adrenalin231** [comment]
still nothing 
./hlds_run -game cstrike -strictportbind +ip 185.38.249.43 -port 27016 +clientpo                                                                                                             rt 27006 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 32

Ports
=================================
Change ports by editing the parameters in:
/home/csserver1/lgsm/config-lgsm/csserver

Useful port diagnostic command:
netstat -atunp | grep hlds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27016  tcp/udp
< Client     OUTBOUND   27006  udp

its show its online but i cant connect to it :C

**Comment by h3o66** [comment]
Did you check the firewall of your server ?

**Comment by Adrenalin231** [comment]
0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                         tcp dpt:27016
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0                                                                                                                         tcp dpt:27006

**Comment by h3o66** [comment]
please check as well if you allowed udp traffic on the gameport (here 27016), this seems to be missing here.

**Comment by Adrenalin231** [comment]
1        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:27016
2        0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp spt:27006
3        0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:27006
4        0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:27016

i did it and nothing change

**Comment by h3o66** [comment]
if you just want to host the same server, you can copy the server script from csserver to csserver2
Important: do not copy it with a dash in the name like `csserver-2` that will not work with the current implementation in LinuxGSM.
Then you need to configure only the ports in the accordning config files, see:
https://docs.linuxgsm.com/features/multiple-game-servers#forgetting-to-change-ports-and-or-ip

in this case as mentioned
```
port="27016"
clientport="27006"
```

I tested it and it works (tarted 2 gameservers and ).
It would be the best if you need help to ask on the discord.
