### ISSUE TITLE
L4D2 and CSGO brokes down after stop and start

### ISSUE THREAD

**Issue by CptOddball** [GameServerManagers/LinuxGSM#3055]
After starting L4D2 server, stopping it and trying to start again its broken and looking for DX9 files and needs to be validated and the cirkel continues.
The same goes for CSGO but it's Vpak01 or something.

**Comment by dgibbs64** [comment]
There is not enough info

**Comment by h3o66** [comment]
No answer in more than 2 months.
~closing
