### ISSUE TITLE
[BUG] Rust game server wipe commands not removing player.states.*.db files

### ISSUE THREAD

**Issue by StaticReality** [GameServerManagers/LinuxGSM#3064]
## User Story

The ~/rustserver wipe and ~/rustserver full-wipe are skipping over the player.states.*.db files located in ~/serverfiles/server/rustserver/ (same place as other map specific files)

## Basic info

* **Distro:** [centos7.8]
* **Game:** [Rust]
* **Command:** [wipe]
* **Command:** [full-wipe]
* **LinuxGSM version:** [v20.5.0]

## Further Information

Just need to add the player.states.*.db files to be deleted when using the wiping / full wiping commands.

## To Reproduce

Steps to reproduce the behaviour:
1. ls -la ~/serverfiles/server/rustserver/ | grep player.states
2. wipe server or full-wipe server using wipe command
3. ls -la ~/serverfiles/server/rustserver/ | grep player.states
4. note that player.states.*.db files were NOT deleted

## Expected behaviour
1. ls -la ~/serverfiles/server/rustserver/ | grep player.states
2. wipe server or full-wipe server using wipe command
3. ls -la ~/serverfiles/server/rustserver/ | grep player.states
4. note that player.states.*.db files are gone

**Comment by h3o66** [comment]
Would you expect that these files are wiped with both commands or just with the full wipe ?

**Comment by StaticReality** [comment]
This file should be removed anytime you wipe or full-wipe

**Comment by h3o66** [comment]
See the linked pull request
