### ISSUE TITLE
command ./rustserver u does not work

### ISSUE THREAD

**Issue by carek5** [GameServerManagers/LinuxGSM#3072]
Hi
command ./rustserver u does not work, message as in the picture 

https://imageshack.com/i/pn4rVk7Vj

Thank You

**Comment by h3o66** [comment]
This is probably a steam or a network issue.
As well a bit more info about your setup might help ....

**Comment by JoinedSenses** [comment]
possibly related to #3129

**Comment by h3o66** [comment]
> possibly related to #3129

Afaik the problem only appreard recently, so this is probably not directly related

**Comment by h3o66** [comment]
Closing this for now, please reopen if this this still persists
