### ISSUE TITLE
Easier way to override launch parameters

### ISSUE THREAD

**Issue by mvaessen** [GameServerManagers/LinuxGSM#3074]
## User Story

As a server hosting company, I want an easier method to setup custom launch parameters so that I can rely on the original LGSM files without having to make manual changes to support easy launch param overrides.

## Further Information

In most cases people host a couple servers and it all works fine. But when using automated systems to generate the `config.json` file to override the `_default.json` settings you can not override the launch parameters without hacking into files.

Current situation:
```
fn_parms(){
parms="\"${defaultmap}?AltSaveDirectoryName=${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}\""
}
```

Suggested outcome:
```
launchparameters="\"${defaultmap}?AltSaveDirectoryName=${defaultmap}?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}\""

fn_parms(){
parms="${launchparameters}"
}
```

**Comment by dgibbs64** [comment]
I'm looking at how best to implement this and the change might break existing installs with custom parameters. So I will have to figure out a way to make sure the "legacy" fn_parms in common.cfg still works if needed. would be easy if I didn't need to think about existing installs XD

**Comment by mvaessen** [comment]
Perhaps you can introduce a new function. If the legacy function's response is empty, and the new one exists and has a string you can be sure you are dealing with the new system.

If the legacy function returns a string and/or if the new function is missing you can be sure it's an old install.

**Comment by dgibbs64** [comment]
yeah, I have a core_legacy.sh module for backwards compatibility issues. I will create something it will just need a bit of testing extra care to make sure I don't break installs accidently.
