### ISSUE TITLE
allow override of repo with master

### ISSUE THREAD

**Issue by mvaessen** [GameServerManagers/LinuxGSM#3077]
When using an external (forked) repo, the master branch of that repo becomes useless. Reason is that the scripts have a hardcoded override that will change behaviour when using the master branch. Thus using the original repo instead of the forked one.

Some prefer using a forked repo to work with, so they have control over when the LGSM scripts are updated. For production type applications this is a basic necessity in my opinion.

**Comment by h3o66** [comment]
Done in Release 20.6.0
