### ISSUE TITLE
Can't install dependencies on debian 9

### ISSUE THREAD

**Issue by synexTG** [GameServerManagers/LinuxGSM#3086]
Hey following problem:

```
[ .... ] Starting gmodserver: Warning! Missing dependencies: libstdc++6:i386 lib32tinfo5

Warning! gmodserver does not have sudo access. Manually install dependencies.
        sudo dpkg --add-architecture i386; sudo apt update; sudo apt install libstdc++6:i386 lib32tinfo5

Failure! Missing dependencies required to run SteamCMD.
```

All dependencies installed without problems except "lib32tinfo5". 

Message:
```
E: Paket lib32tinfo5 kann nicht gefunden werden.

E: Package lib32tinfo5 could not been found. (translated)
```

My OS is Debian 9 64 bit cleanly installed. Had the same problem on another server.

**Comment by h3o66** [comment]
Did you try to run the above command ?
`sudo dpkg --add-architecture i386; sudo apt update; sudo apt install libstdc++6:i386 lib32tinfo5`
If sudo is not installed, please try do the same without sudo

**Comment by synexTG** [comment]
Ja hab ich probiert, die oben stehende bzw. jetzt nochmal hier stehende Meldung kommt dann:
E: Paket lib32tinfo5 kann nicht gefunden werden.

Mehr passiert nicht, hatte ich schon mal auf einem anderen System. Finde selber keine Lösung.

**Comment by h3o66** [comment]
In this case you have probably not installed the needed debian repos.
As the package exists for debian 9 ( name: stretch )
See Link:
https://packages.debian.org/stretch/lib32tinfo5

**Comment by synexTG** [comment]
Helped thanks.
