### ISSUE TITLE
Install arkserver - dependencies error

### ISSUE THREAD

**Issue by Claiyc** [GameServerManagers/LinuxGSM#3087]
Installation of ARK:Survival Evolved Server 

## Basic info

* **Distro:** Debian 10
* **Game:** arkserver
* **Command:** ./arkserver install
* **LinuxGSM version:** v20.5.1

## Further Information

When installing an arkserver, one of the required dependencies lib32gcc1 or lib32stdc++6 is always missing. If I install lib32gcc1 it removes lib32stdc++6, if I install lib32stdc++6 it removes lib32gcc1.

` apt-get install lib32stdc++6
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  lib32gcc-s1
The following packages will be REMOVED:
  lib32gcc1
The following NEW packages will be installed:
  lib32gcc-s1 lib32stdc++6
`

I managed to install the ark server using ./arkserver update because the script doesn't check dependencies then. Everything runs fine without lib32stdc++6.

**Comment by h3o66** [comment]
This looks to me more like a messed up sources.list file(s).

Can you maybe post the current sources.list(s) including what there are additinal repos.

As well maybe post the output of `apt policy lib32gcc1`

**Comment by Claiyc** [comment]
Current sources.list:

> deb http://deb.debian.org/debian buster main contrib non-free
> deb-src http://deb.debian.org/debian buster main contrib non-free
> 
> deb http://deb.debian.org/debian buster-updates main contrib non-free
> deb-src http://deb.debian.org/debian buster-updates main contrib non-free
> 
> deb http://security.debian.org/ buster/updates main contrib non-free
> deb-src http://security.debian.org/ buster/updates main contrib non-free
> deb http://ftp.de.debian.org/debian sid main

No additional repos

apt policy lib32gcc1 output:

> lib32gcc1:
>   Installed: 1:8.3.0-6
>   Candidate: 1:8.3.0-6
>   Version table:
>  *** 1:8.3.0-6 500
>         500 http://deb.debian.org/debian buster/main amd64 Packages
>         100 /var/lib/dpkg/status

**Comment by h3o66** [comment]
The sid repo is probably here the problem, try to deactivate it and do a `apt update` and try again

**Comment by Claiyc** [comment]
Thank you! Everything runs fine now.
