### ISSUE TITLE
ut2k4server servername output issue

### ISSUE THREAD

**Issue by Annihilator** [GameServerManagers/LinuxGSM#3088]
## Intro

When displaying, and using the variable servername, the exact server name as specified in the ut2k4server configuration is expected. This is not how lgsm currently behaves. Aside from the visual annoyance, some script behavior is broken because of this.

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Unreal Tournament 2004]
* **Command:** [test-alert] [details]
* **LinuxGSM version:** [v20.5.1]

## Further Information

3x \nShowTrue is appended to the end of the servername variable. So, if the configured servername of the game server is "AB CD EF", lgsm would interpret it as:
AB CD EF
ShowTrue
ShowTrue
ShowTrue

## To Reproduce

Steps to reproduce the behaviour:
1. Install a configure a ut2k4server instance
2. Check ut2k4server details
3. See the servername variable get junk appended to it

This also breaks Discord alerts because the alert-discord script is unable to parse such a malformed server name.

## Expected behaviour

There should be no 3x ShowTrue appended to the real name of the game server in the servername variable.

**Comment by h3o66** [comment]
I cannot reproduce this with my test, can you maybe upload your config here ?

**Comment by Annihilator** [comment]
Sure, here's the config:

defaultmap="RecoveryMap"
gamemode="`grep -m 1 -o -P '(?<=GameClass=").*(?=",Prefix)' ${servercfgfullpath}`?mutator=`grep -m 1 -o -P '(?<=Mutators=").*(?=",Options)' ${servercfgfullpath}`"
fn_parms(){
parms="server ${defaultmap}?game=${gamemode} -nohomedir ini=${servercfg} log=${gamelog} | sed '/^WARNING - /d;s/\r$//'"
}
discordalert="on"
discordwebhook=*censored*
logdays="28"
querymode="4"
gamelog="/dev/null"

**Comment by h3o66** [comment]
I would need as well the `servercfg` file if possible

**Comment by Annihilator** [comment]
Here are the key differences between the server ini that is used vs. the one packaged with LinuxGSM:
`[Engine.Engine]
DefaultGame=XGame.xVehicleCTFGame
DefaultServerGame=XGame.xVehicleCTFGame

[Core.System]
Suppress=Warning

[Engine.GameEngine]
ServerActors=AdminTakeoverWorkaround.AdminTakeoverWorkaround
ServerActors=LinxDedServFix.LinxDedServFixMut
ServerActors=LockRolloff.LockRolloffServerActor
ServerActors=ServerColor.ServerColorActor
ServerActors=ServerExt.ChatFilter
ServerActors=ServerExt.PlayerJoinLog
ServerPackages=SmartCTF1C
ServerPackages=UTCompv18b

[IpDrv.TcpNetDriver]
MaxClientRate=20000
MaxInternetClientRate=20000
NetServerMaxTickRate=35
LanServerMaxTickRate=35

[IpDrv.MasterServerUplink]
ServerBehindNAT=True
DoLANBroadcast=False
bIgnoreUTANBans=True

[IpDrv.HTTPDownload]
RedirectToURL=<rdr-url>
UseCompression=False

[Engine.DemoRecDriver]
MaxClientRate=20000
NetServerMaxTickRate=35
LanServerMaxTickRate=35
MaxInternetClientRate=20000

[Engine.GameReplicationInfo]
ServerName=ABC | Bla Bla Bla | DEF | https://<web-url>
ShortName=ABC-DEF
AdminEmail=https://<web-url>
MessageOfTheDay=ABC|DEF|GHI|JKL

[Engine.AccessControl]
AdminPassword=<pwd>
LoginDelaySeconds=0.000000
IPPolicies=ACCEPT;*

[Engine.GameInfo]
MaxSpectators=24
MaxPlayers=24
GameStatsClass=Engine.GameStats
AccessControlClass=TitanAdminSM1.TitanReservedSlotsIni
MaxIdleTime=300.000000
bAllowBehindView=True
bAdminCanPause=False
bWeaponShouldViewShake=False
bLowGore=False
bLargeGameVOIP=False
GameDifficulty=5.000000
MaplistHandlerType=
ServerSkillLevel=
bWeaponStay=False
bAllowWeaponThrowing=True
ResetTimeDelay=0

[xVoting.xVotingHandler]
GameConfig=(GameClass="XGame.xVehicleCTFGame",Prefix="VCTF",Acronym="VCTF",GameName="Vehicle CTF",Mutators="UTCompv18b.MutUTComp,ServerExt.mutTeamBalance,SmartCTF1C.SmartCTF,ServerBots2.ServerBots,MantarunAssist.mutMantarunAssist",Options=)
`

Note the usage of ServerColor.ServerColorActor for coloring the server name in the server browser.

**Comment by h3o66** [comment]
Maybe you can test the linked PR if that one fixes your issue with the parsing.

**Comment by Annihilator** [comment]
Test successful. Much appreciated!
Alerting works perfectly fine now as well.

**Comment by h3o66** [comment]
> Test successful. Much appreciated!
> Alerting works perfectly fine now as well.

Thanks for testing.
