### ISSUE TITLE
Discord Notifications not Working

### ISSUE THREAD

**Issue by CalMatar** [GameServerManagers/LinuxGSM#3089]
No matter what server, with the possible exception of TS3 but no guarantees, the Discord notices "bot" part of LGSM config is not working anymore. The only notice that I, or anyone, has gotten since the October 1 update has been the update notices. I used to at least get the restart notices when the machine was started/restarted (it did not know the difference) but now the only thing I get are update notices. I have not been getting the email notices at all lately either but I do not know if that is part of the same issue or if that is a separate issue. I have this problem on a 7DTD and a Rust server but have seen issues on ARK and others as well. 
My machines are all Ubuntu machines but this problem is across other Linux distros.

**Comment by h3o66** [comment]
1. I would be nice if you could use the template instead of putting a unformatted text in here.
2. For me the discord alerts are working.
3. Are there any special chars in the config that could be a problem for the webhook ?
