### ISSUE TITLE
[ut99server] crash loop for ut99 server !

### ISSUE THREAD

**Issue by BCE-MacReady** [GameServerManagers/LinuxGSM#309]
crash loop for ut99 server is missing afther you are logged in as admin on your server you should be able to restart server with admin exit in console or over webadmin in console tipe exit but it goes off i checked standard gameservers they do crash loop please very important !!!

thanks :+1:

**Comment by BCE-MacReady** [comment]
make one afther 3 times fail the crash script stops working

**Comment by dgibbs64** [comment]
WHat do you mean by crash loop?

**Comment by BCE-MacReady** [comment]
try to make a windows ut server and you know what i mean afther the server crashes bad map admin exit if you use on your server adminlogin yourpassword and command admin exit what does the server tell me it never comes back anymore its dead and for that i mean if you check out windows servers they have crash loop by default so if you do that on a widnows ut server it comes back from the console automatic and for linux you need to create a script or check from some others ut99 server scripts there should be the code where you can paste in and you have it just simple and if you restart server the server is back like from a button of a webinterface im not sure what are the commands sleep 1 stop server sleep 1 start server for command admin exit in the ut99server script or where ever you gonna put that its up to you i just want that it works this way the server should coming back afther a fail of a bad map as example its loading automatic the start default map

**Comment by dgibbs64** [comment]
Dude! do you know what a full stop is? you just hit me with a wall of text.

**Comment by dgibbs64** [comment]
There is a monitor in place that should restart the server if it crashes. If you can post a link to an example of what you mean I might be able to look at it.

**Comment by Scarsz** [comment]
http://en.m.wikipedia.org/wiki/Full_stop

**Comment by BCE-MacReady** [comment]
im not sure about this script down http://www.unrealadmin.org/forums/showthread.php?p=145517

**Comment by BCE-MacReady** [comment]
i could make it by me self if i know the code i bet everyone get it so easy just its importend stuff for all ut servers what im talking about and i know how to make a bat file but linux we need to figure out

**Comment by Scarsz** [comment]
...what

**Comment by BCE-MacReady** [comment]
delete this topic tbh with you guys

**Comment by dgibbs64** [comment]
This is something I will look in to to see if the monitor can be improved.

**Comment by dgibbs64** [comment]
Feature request was if the quit command is entered then the server will restart rather than simply quit.

**Comment by BCE-MacReady** [comment]
thanks

**Comment by dgibbs64** [comment]
Current idea is for the start command to be in a loop. should the tmux command exit, lgsm will check for the lock file. if the lock file is present the tmux session will restart. if missing then it will break out of the loop.

This idea is simply an instant monitor feature that will instantly restart the server on a failure rather than waiting for monitor. However there is a risk that the feature could constantly loop should there be a major failure. So a number limit would need to be in place to break out should it restart too many times.

**Comment by dgibbs64** [comment]
After thinking about the logic required. I dont believe this would work well. The best way to sort the issue is to simply run the monitor every minute.
