### ISSUE TITLE
[rust] logging disabled on _default.cfg

### ISSUE THREAD

**Issue by StaticReality** [GameServerManagers/LinuxGSM#3091]
## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [cetnos7]
* **Game:** [rust]
* **Command:** [start]
* **LinuxGSM version:** [v20.5.1]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

~/lgsm/config-lgsm/rustserver/_default.cfg parm= line has logging disabled
currently it mentions 
-logfile

## Expected behavior
parm= line should:
-logfile \"${gamelogdate}\" 

The bug only affect users who DON'T have a specified config file (example: ~/lgsm/config-lgsm/rustserver/rustserver.cfg) and thus pulls variables from _default.cfg

**Comment by h3o66** [comment]
This was changed here:
https://github.com/GameServerManagers/LinuxGSM/commit/a941499479a291247b8690e0bebe8f287a939c17

@dgibbs64 do you know why this was changed this way ?

**Comment by StaticReality** [comment]
4861d13

**Comment by dgibbs64** [comment]
To allow the console to output in tmux. Logs are saved in console log

**Comment by akariley** [comment]
This does not appear to be working for me on 20.6.1
```
[rust-testing@gameserver console]$ ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rust-te+  5082  0.0  0.0 116324  3044 pts/2    S    06:49   0:00 -bash
rust-te+ 10527  0.0  0.0 155448  1752 pts/2    R+   06:56   0:00  \_ ps auxf
rust-te+  4616  0.0  0.0 121932  1872 ?        Ss   06:45   0:00 tmux new-session -d -x 80 -y 23 -s rustserver ./RustDedicated -batchmode +server.ip 170.249.192.29 +server.port 28015 +serve
rust-te+  4617  118 13.6 12677432 4447004 pts/3 Ssl+ 06:45  12:38  \_ ./RustDedicated -batchmode +server.ip 170.249.192.29 +server.port 28015 +server.tickrate 30 +server.hostname Rust +serv
rust-te+  4634  0.0  0.0 108076   352 ?        S    06:45   0:00  \_ cat
[rust-testing@gameserver console]$ pwd;ls -la
/home/rust-testing/rust/log/console
total 12
drwxrwxr-x 2 rust-testing rust-testing 4096 Dec  5 06:45 .
drwxrwxr-x 5 rust-testing rust-testing 4096 Jun 22 16:00 ..
-rw-rw-r-- 1 rust-testing rust-testing    0 Dec  5 06:45 rustserver-console-2020-12-05-06:45:39.log
-rw-rw-r-- 1 rust-testing rust-testing  125 Dec  5 06:45 rustserver-console.log
[rust-testing@gameserver console]$ cat rustserver-console.log 
Set current directory to /home/rust-testing/rust/serverfiles
Found path: /home/rust-testing/rust/serverfiles/RustDedicated
[rust-testing@gameserver console]$ cd ../..
[rust-testing@gameserver rust]$ ./rustserver 
Usage: ./rustserver [option]

LinuxGSM - Rust - Version v20.6.1
```

**Comment by dgibbs64** [comment]
@akariley do you have custom start parameters? specifically look for a parameter that mentions logging and remove it if you do

**Comment by akariley** [comment]
Hmm, not sure what happened, but it's working as expected now.  I'm gonna call this user error and consume more coffee.
