### ISSUE TITLE
[Server Request] Black Mesa Coop Mod

### ISSUE THREAD

**Issue by Token00** [GameServerManagers/LinuxGSM#3092]
## What game server would you like adding?

Black Mesa Coop Mod
https://github.com/ampreeT/SourceCoop

## Can you link to any tutorials or guides?
https://steamcommunity.com/sharedfiles/filedetails/?id=2200247356

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

346680

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by dgibbs64** [comment]
This is a sourcemod for Black Mesa and not a dedicated server. Black Mesa server is already available as a dedicated server.
