### ISSUE TITLE
Ubuntu has renamed lib32gcc1 to lib32gcc-s1, so dependency check for lib32gcc1 using dpkg-query fails on testing Ubuntu 20.10 and unstable. 

### ISSUE THREAD

**Issue by lehmanner** [GameServerManagers/LinuxGSM#3093]
## User Story

I am a CS:GO server owner trying to install it on the latest Ubuntu Server

## Basic info

* **Distro:** [Ubuntu Server 20.10]
* **Game:** [CSGO]
* **Command:** [Install]
* **LinuxGSM version:** [v20.1.3]

## Further Information

LinuxGSM check for the installation of package lib32gcc1 using dpkg-query, but ubuntu has renamed the package to lib32gcc-s1. If LinuxGSM is to work on Ubuntu 20.10 or later it should check for the installation of lib32gcc-s1 or both. Both packages provide the same file /usr/lib32/libgcc_s.so.1 .

## To Reproduce

Steps to reproduce the behaviour:

Update Ubuntu (not LTS) to latest version which is 20.10, maybe a dist-upgrade is required.
Try to install csgoserver using command ./csgoserver install
Dependency check fails with error for missing package lib32gcc1

## Expected behaviour
Dependency check should check for lib32gcc-s1 and succeed

**Comment by h3o66** [comment]
if you have time, you can check if the connected PR fixes the issue.

**Comment by h3o66** [comment]
Done in Release 20.6.0

**Comment by Escarnope** [comment]
This is an issue on Ubuntu 21.04

**Comment by h3o66** [comment]
@Escarnope see pr #3445

**Comment by christianlux** [comment]
Problem still present.

**Comment by Escarnope** [comment]
> Problem still present.

The problem is because they check for the exact version

Until they change that, you have to add your distro to the `check_dep.sh` file

**Comment by Claiyc** [comment]
Dependency checks are currently being refactored entirely.
