### ISSUE TITLE
armaserver_x64

### ISSUE THREAD

**Issue by agorapolis** [GameServerManagers/LinuxGSM#3102]
Hello

The Arma 3 server is now available in a 64-bit version. LinuxGSM only knows the 32bits version, an update is planned?

**Comment by dgibbs64** [comment]
I am happy to change it to x64 as long as it doesn't cause any issues with existing servers. My worry would be mods

**Comment by h3o66** [comment]
Would be good if a few arma 3 admins could test the new x64 server.
this can be set in the `arma3server.cfg`
```
executable="./arma3server_64"
```

**Comment by h3o66** [comment]
Created PR for this
