### ISSUE TITLE
Backup command reporting oldest backup as latest

### ISSUE THREAD

**Issue by SliceofLie** [GameServerManagers/LinuxGSM#3109]
## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Factorio]
* **Command:** [Backup and Details]
* **LinuxGSM version:** [v20.5.1]

## Further Information

When using either the backup or details command, the oldest backup is reported as the latest backup, leading to confusion.
I think the script info_distro.sh is causing the issue.
I've changed the line 
```lastbackup=$(find "${backupdir}"/*.tar.gz | head -1)```
to 
```lastbackup=$(find "${backupdir}"/*.tar.gz | tail -1)```
and it seems to have fixed the issue. 

## To Reproduce

Steps to reproduce the behaviour:
Use either the backup or details command
Observe the "Latest backup" section information
Compare with the actual file list of the backups directory

## Expected behaviour
"Latest backup" should refer to the most recently created backup, not the oldest backup.

**Comment by Shebuka** [comment]
I still have the same issue on the LinuxGSM Version v21.1.3. The oldest backup is reported as the latest.
As per #3339 it's still present in the latest v21.2.0. Related merges #3328 #3348

**Comment by h3o66** [comment]
afaik this cannot be present in v21.2.0, because this version is not released and will be rereleased then with the fix.
