### ISSUE TITLE
Multiple game servers same instance

### ISSUE THREAD

**Issue by Amplefi** [GameServerManagers/LinuxGSM#3111]
centos-release-8.2-2.2004.0.2.el8.x86_64
game server: retakes CSGO

I am attempting to make multiple servers under one game instance and they both run fine on their own but if i try to start them both simultaneously the other one automatically closes. Both the scrips have different names as well as the config files associated with them the names are retakes and retakes2 respectively i have check that tmux is starting them with different session names on their own 

I have a port range open and here are screenshot of each gameservers details including the ports.

![image](https://user-images.githubusercontent.com/30732400/99959281-93c0ae80-2d3f-11eb-9279-b529e9b70191.png)
![image](https://user-images.githubusercontent.com/30732400/99959414-d2eeff80-2d3f-11eb-95f8-0ea2eeea899c.png)
![image](https://user-images.githubusercontent.com/30732400/99959443-e00bee80-2d3f-11eb-8fd3-8699f00359db.png)

![image](https://user-images.githubusercontent.com/30732400/99959163-5f4cf280-2d3f-11eb-8eb4-4e77818f46ce.png)

**Comment by dgibbs64** [comment]
Source TV ports are the same. Change this and it should work

**Comment by Amplefi** [comment]
> Source TV ports are the same. Change this and it should work

still experiencing the same behavior

**Comment by Amplefi** [comment]
was a issue with tokens not being correctly mapped to right servers
