### ISSUE TITLE
LinuxGSM shows wrong server name when running multiple instances of ARK

### ISSUE THREAD

**Issue by StinkyMcKraken** [GameServerManagers/LinuxGSM#3113]
## User Story

LinuxGSM frequently shows the wrong server name when managing multiple instances of ARK Survival

## Basic info
* **Distro:** [Ubuntu 20.04.1 LTS]
* **Game:** [ARK Survival Evolved]
* **Command:** [start, stop, restart, alert]
* **LinuxGSM version:** [v20.5.1]

## Further Information

I run multiple (9) instances of ARK off the same install.  I have very few players, so the instances do not all run at the same time.  I have Discord Alerts enabled and have written a simple python script to allow players to start and stop the various server instances via Discord.

LinuxGSM extracts the server name from the ARK config file ~/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini.  Since I am running multiple instances, there is no way to use GameUserSettings.ini to specify server names for the different instances, therefore I have used LinuxGSM's instance.cfg to manage server names on ARK's command line.  The issue is LinuxGSM gets the server name from GameUserSettings.ini after it processes instance.cfg and typically the name in GameUserSettings.ini does not match the instance being invoked, so console responses from LinuxGSM display the wrong server name in its stdout and in LinuxGSM's built in Discord Alerts. From a functional standpoint, server name has no bearing on the operation of the server instances, this is just an informational bug.

A quick fix may be to add a flag to _default.cfg, GetNameFromServerFiles=True.  When true, LinuxGSM will extract the server name from the configs in serverfiles as it does currently.  If GetNameFromServerFiles=False in instance.cfg or common.cfg, LinuxGSM does not read from the serverfiles configs.  This fix can be universal to all games, not just ARK.

## To Reproduce

Steps to reproduce the behaviour:
1. Install ARK, configure multiple instances.  Named arkisland and arkgenesis.
  Use ~/lgsm/config-lgsm/arkserver/arkisland.cfg to specify sessionname="ExampleIsland"  (and other settings appropriately)
  Use ~/lgsm/config-lgsm/arkserver/arkgenesis.cfg to specify sessionname="ExampleGenesis" (and other settings appropriately)
2. Start arkisland. LinuxGSM stdout: [...] Starting arkisland: LinuxGSM
3. Wait 5 minutes for server to initialize
4. Start arkgenesis. LinuxGSM stdout: [...] Starting arkgenesis: ExampleIsland
optional:
5. Stop arkgenesis. LinuxGSM stdout: [...] Stopping arkgenesis: ExampleGenesis
6. Stop arkisland. LinuxGSM stdout: [...] Stopping arkisland: ExampleGenesis
7. Start arkisland. LinuxGSM stdout: [...] Starting arkisland: ExampleGenesis

## Expected behaviour
See LinuxGSM stdout: [...] Starting arkisland: ExampleIsland
See LinuxGSM stdout: [...] Starting arkgenesis: ExampleGenesis

**Comment by Claiyc** [comment]
Has more to do with how ark works and isn't really an issue with lgsm. The ark session name is defined in GameUserSettings.ini (as well as many other settings) and that cannot be changed for specific instances.
