### ISSUE TITLE
[Arma 3] Server Wont Start

### ISSUE THREAD

**Issue by coletaylor10** [GameServerManagers/LinuxGSM#3126]
![image](https://user-images.githubusercontent.com/75837164/101893206-5b70fb00-3b9c-11eb-9543-3f8f5f873318.png)
![image](https://user-images.githubusercontent.com/75837164/101893266-6c217100-3b9c-11eb-8370-e93b3ca2fa92.png)
![image](https://user-images.githubusercontent.com/75837164/101893336-81969b00-3b9c-11eb-9846-4262d5a16e0a.png)
![image](https://user-images.githubusercontent.com/75837164/101893613-e05c1480-3b9c-11eb-9fcd-dc4fb0c36ea0.png)
My logs are blank and when i run the debug command it loads then immediately stops. If you need me to show any other info i can just ask.

Thanks In advance

**Comment by h3o66** [comment]
Did you install all dependencys for LGSM ?
Did you already try to run the mentioned command manually ?
Did you add anything to the config ?

**Comment by JoinedSenses** [comment]
This may be related to #3129 update on start

**Comment by h3o66** [comment]
> This may be related to #3129 update on start

I dont think so, there is a segmentation fault at the start of the server, for whatever reason. (3rd screenshot)

Whereever you see the problem here with a update ?
