### ISSUE TITLE
[Rust]

### ISSUE THREAD

**Issue by Josephienvandermeersch** [GameServerManagers/LinuxGSM#3128]
Hello, i've had a few days of issues now where my server would suddenly crash and not come back on ( even tho its hosting on scalascube and haves a auto restart function enabled )

These are the only things I find in my logs that are before the crash
12/11/2020 22:14:50 [Info] [01:14:50] [Linux] [EAC Server] [Info] [Destroy] Called 12/11/2020 22:14:50 [Info] [01:14:50] [Linux] [EAC Server] [Info] [Cerberus] [Backend] Scheduling disconnect task. 12/11/2020 22:14:50 [Info] [01:14:50] [Linux] [EAC Server] [Info] [Cerberus] [Backend] Disconnected..

Merged post

EasyAntiCheat Scout Shutting Down
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

EasyAntiCheat Server Shutting Down
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Raknet] Server Shutting Down (Shutting Down)

**Comment by includes08** [comment]
talk with them, this isn't a lgsm issue

**Comment by JoinedSenses** [comment]
This might be related to #3129 and update breakage.

**Comment by dgibbs64** [comment]
+1

**Comment by h3o66** [comment]
Does this still persist ? If not please close the issue if this is not a LGSM issue
