### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by kimizumi1** [GameServerManagers/LinuxGSM#3131]
Some people and me too are experiencing issues updating gameservers:

[ FAIL ] Updating rustserver: Checking remote build: SteamCMD

At the moment my Rustserver is not fetching updates.
I've updated LGSM also but it didn't help

**Comment by JoinedSenses** [comment]
https://github.com/GameServerManagers/LinuxGSM/issues/3129#issuecomment-747087892

**Comment by kimizumi1** [comment]
> [#3129 (comment)](https://github.com/GameServerManagers/LinuxGSM/issues/3129#issuecomment-747087892)
> 
> > change line 45 of home/ACCOUNT/lgsm/functions/update_steamcmd.sh to:
> > `elif [ -n "${branch}" ]&&[ "${branch}" != "public" ]; then`

Thanks!
Replacing the line worked (atleast on a Rust server)

**Comment by ifrag-ru** [comment]
> [#3129 (comment)](https://github.com/GameServerManagers/LinuxGSM/issues/3129#issuecomment-747087892)
> 
> > change line 45 of home/ACCOUNT/lgsm/functions/update_steamcmd.sh to:
> > `elif [ -n "${branch}" ]&&[ "${branch}" != "public" ]; then`

As I understand it, now you can turn it on and there shouldn't be any problems?

**Comment by Grimston** [comment]
Correct, this will be applied to LinuxGSM as soon as someone with write access is available.

**Comment by h3o66** [comment]
Should be fixed with the latest hotfix v20.6.2
