### ISSUE TITLE
Discord alert failing - csgo

### ISSUE THREAD

**Issue by RetroZA** [GameServerManagers/LinuxGSM#3133]
csgoserver@EPYC4193:~$ ./csgoserver ta
[ WARN ] Sending Alert csgoserver: More Info not enabled
[ .... ] Sending Alert csgoserver: Sending Discord alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 11, column 41
[ FAIL ] Sending Alert csgoserver: Sending Discord alert: {"message": "400: Bad Request", "code": 0}

getting this error when trying use discord alerts/ test alert

**Comment by h3o66** [comment]
This might be connected to a special caracter that is posted to discord.
To know what char it is, i would need a dev-debug.log log to identify it.

Probably special chars in the server name, but only a guess.

**Comment by RetroZA** [comment]
> This might be connected to a special caracter that is posted to discord.
> To know what char it is, i would need a dev-debug.log log to identify it.
> 
> Probably special chars in the server name, but only a guess.

can i get a discord to pm it to you?

**Comment by h3o66** [comment]
Sure,
My Discord: extreme1st#7327

**Comment by RetroZA** [comment]
big thanks to @h3o66 got it sorted, had to change EOL conversion using notepad++ 
[stackoverflow](https://stackoverflow.com/questions/16239551/eol-conversion-in-notepad)
