### ISSUE TITLE
Fresh installation

### ISSUE THREAD

**Issue by bdbais** [GameServerManagers/LinuxGSM#3136]
Linux server 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$  wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh sdtdserver
--2020-12-19 18:36:06--  https://linuxgsm.sh/
Risoluzione di linuxgsm.sh (linuxgsm.sh)... 172.67.135.1, 104.28.5.112, 104.28.4.112, ...
Connessione a linuxgsm.sh (linuxgsm.sh)|172.67.135.1|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 301 Moved Permanently
Posizione: https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh [segue]
--2020-12-19 18:36:06--  https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/linuxgsm.sh
Risoluzione di raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connessione a raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 14242 (14K) [text/plain]
Salvataggio in: "linuxgsm.sh"

linuxgsm.sh                                 100%[==========================================================================================>]  13,91K  --.-KB/s    in 0s

2020-12-19 18:36:06 (40,5 MB/s) - "linuxgsm.sh" salvato [14242/14242]

Installed 7 Days to Die server as sdtdserver

Remember to check server ports
./sdtdserver details

./sdtdserver install

[ ERROR ] Installing sdtdserver: LinuxGSM version mismatch

* sdtdserver: v20.6.2
* modules: v20.5.1

fetching GitHub command_update_linuxgsm.sh...ERROR
fetching Bitbucket command_update_linuxgsm.sh...FAIL

**Comment by h3o66** [comment]
Did you change you anything ?
I cannot reproduce this with a fresh install.
