### ISSUE TITLE
Additional dependency for Black Mesa, Ubuntu

### ISSUE THREAD

**Issue by Alienmario** [GameServerManagers/LinuxGSM#3137]
## Basic info

* Distro:    Ubuntu 20.04.1 LTS
* Arch:      x86_64
* Kernel:    5.4.0-54-generic
* **Game:** [Black Mesa]
* **Command:** [Console]
* **LinuxGSM version:** [v20.5.1]

## Further Information
With the dependencies listed on the [game server page](https://linuxgsm.com/lgsm/bmdmserver/), readline (command history in console mode) never worked for me, printing this on server start:
```
WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
  Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.
```

This can be additionally solved with **apt install libncurses5:i386**

**Comment by h3o66** [comment]
Thanks for your report, created pr with a fix
