### ISSUE TITLE
Stop command fails if user typed into console

### ISSUE THREAD

**Issue by unknowntrojan** [GameServerManagers/LinuxGSM#3141]
## User Story

As a Server operator, I want the stop command to stop the server. (lol)

## Basic info

* **Distro:** Irrelevant
* **Game:** Source Games, maybe more. CSGO and GMOD tested.
* **Command:** ./xserver stop
* **LinuxGSM version:** master

## Further Information

When the server console has something typed into it, sending the stop command fails (due to the "buffer" not being flushed).
The solution would be to "flush" it, however we don't want whatever is currently typed in just blindly being executed.
Sadly I couldn't figure out a sane solution ( so feel free to figure it out )

What I thought of to do:
- Send Pos1 and then a few seemingly random characters (will not execute unwanted commands, hopefully), then sending enter, which is not particularly easy to 
- Send Enter
- Spam Backspace, then Enter

I just decided on sending Enter, the stop command, then Enter again.

I have a PR to fix this ready ( i tried making one earlier but this is my first time really using github ).
Will link once it's done. Checklist requires me to make an issue first, apparently.

## To Reproduce

Steps to reproduce the behaviour:
1. Open Console (./csgoserver c)
2. Type literally anything without pressing enter afterwards,
3. Detach from tmux/screen
4. Stop the server (./csgoserver stop)
5. It will now have sent what you typed, plus "stop" to the server. This is incorrect behavior.

## Expected behaviour
1. Open Console (./csgoserver c)
2. Type literally anything without pressing enter afterwards,
3. Detach from tmux/screen
4. Stop the server (./csgoserver stop)
5. ... Stop the server

**Comment by unknowntrojan** [comment]
The PR is open. #3142

**Comment by unknowntrojan** [comment]
PR  #3142 has been merged, issue closed.

**Comment by dgibbs64** [comment]
issue remains open until merged in to master
