### ISSUE TITLE
[BUG] [Garry's Mod] Validating server while on a different branch breaks local build version

### ISSUE THREAD

**Issue by peter-r-g** [GameServerManagers/LinuxGSM#3143]
## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Garry's Mod]
* **Command:** [Validate]
* **LinuxGSM version:** [v20.6.2]

## Further Information

To actually get LinuxGSM to update to the x86-64 branch for testing I used the fix from #3139. Although it doesn't matter if you use the regular 20.6.2 version of LinuxGSM for this problem to arise.

## To Reproduce

Steps to reproduce the behaviour:
1. Set branch to "x86-64" (64 bit beta to dedicated server, https://steamdb.info/app/4020/depots/?branch=x86-64)
2. Use validate command (./gmodserver validate, doesn't matter if you use ./gmodserver update before-hand)
3. Set branch back to default. ("")
4. Use update command (./gmodserver update)
The local build number will always be the same as the x86-64 branch number and using the update or validate commands won't change it.

## Expected behaviour
The local build number to change so that LinuxGSM doesn't think it always has to update the server.

**Comment by peter-r-g** [comment]
Upon further inspection I've noticed that SteamCMD doesn't update the BuildID (that I assume LinuxGSM uses) found in serverfiles/steamapps/appmanifest_4020.acf because the x86-64 branch does not seem to change any files. Only add some, I suppose this can't be worked around in LinuxGSM?

**Comment by h3o66** [comment]
so with the following command I get different build ids that should be not a problem to change this with a validate command:
`steamcmd +app_info_update 1 +app_info_print 4020 +quit | sed -e '/"branches"/,/^}/!d'`

Public: 5956225
x86-64: 5956258

**Comment by peter-r-g** [comment]
> 
> 
> so with the following command I get different build ids that should be not a problem to change this with a validate command:
> `steamcmd +app_info_update 1 +app_info_print 4020 +quit | sed -e '/"branches"/,/^}/!d'`
> 
> Public: 5956225
> x86-64: 5956258

Validating does not change the local build, it stays at 5956258.

**Comment by h3o66** [comment]
Afaik if the buildid is lower than the last buildid, the files need to be vaidated by the steamcmd

**Comment by h3o66** [comment]
Well, can preproduce this issue with a vaidate, but i guess this is then not a lgsm issue, more specifc a issue with the steamcmd

**Comment by peter-r-g** [comment]
I ended up trying to edit the app manifest directly to change the build ID and beta branch but it was still somehow reporting the x86-64 build ID. Is LinuxGSM saving the build ID somewhere else? The only solution I could get was to delete everything in the serverfiles directory and install LinuxGSM again.

I also was looking through and comparing the files between the public and x86-64 branches to find that there are a bunch of differences between them. Yet SteamCMD would say that everything is already up to date, as if it's comparing the files to the x86-64 branch rather than the default public branch like LinuxGSM is reporting that it's comparing to.

**Comment by JimTR** [comment]
I hit this a while ago with a project I'm doing ..
and the fix is to delete the manifest file "serverfiles/steamapps/appmanifest_<appid>.acf"
e.g gmod would be like "/home/user/games/gmod/serverfiles/steamapps/appmanifest_4020.acf"
then re run validation on the install with the correct branch, from the command line it would be like 
"steamcmd +login anonymous +force_install_dir /home/user/games/gmod/serverfiles +app_update 4020 -beta x86-64 validate +quit".
of course to return to public remove the -beta <branch> from the command so
"steamcmd +login anonymous +force_install_dir /home/user/games/gmod/serverfiles +app_update 4020 validate +quit" but I guess the LGSM validate command will do this for you

**Comment by JimTR** [comment]
Just tried using LGSM to validate .. it works as long as you check that the numerous config files do not contain a line "branch=branchname".
as a side note LGSM appeared to be slow to validate this appeared to be down to somewhere in LGSM code there is a call to Tee which in turn opened up other tasks (/usr/bin/unbuffer) on Ubuntu 20.04

**Comment by h3o66** [comment]
Can someone please test with the fix from the PR ?
