### ISSUE TITLE
[BUG] Useful port diagnostic command fails

### ISSUE THREAD

**Issue by JimTR** [GameServerManagers/LinuxGSM#3162]
As a user, I want the command to work so that you can reed the output.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Any]
* **Command:** [DT]
* **LinuxGSM version:** [v20.1.3]

## Further Information

running the command  'netstat -atunp | grep srcds_linux' can give a blank result if the PID is greater than 5 digits as netstat shortens the program field to make sure its out is the same length (I guess they have used printf ) so with a PID of 6 digits the program field is scrds_linu which of course grep can not match and displays nothing. and so on so a PID of 7 digits gives an out put of srcds_lin 
Possible Fixes  
1. shorten the search text to just 'srcds_' which I guess is enough to match on and should not produce false positives
2. change to the command 'ss -a4p |grep srcds_linux' which gives the correct result 

## To Reproduce
run 'netstat -atunp | grep srcds_linux'  after a server has been started
Steps to reproduce the behaviour:
1. start a server
2. run the server with the DT
3. use the Useful port diagnostic command:

## Expected behaviour
display results

**Comment by h3o66** [comment]
Probably fixed by #3428
