### ISSUE TITLE
[BUG] csgoserver autoupdate - Do not Start after update

### ISSUE THREAD

**Issue by rodrigo-apoc** [GameServerManagers/LinuxGSM#3166]
## User Story

Using `updateonstart` option, LinuxGSM finds a new version of CSGO and download.
But the Start action does not happen.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [CSGO]
* **Command:** [Start]
* **LinuxGSM version:** [v20.6.2]

## Further Information

csgoserver@4Teams:~$ ./csgoserver start
[  OK  ] Updating csgoserver: Checking for update: SteamCMD

Update available
* Local build: 5984748
* Remote build: 6052796
* Branch: public
https://steamdb.info/app/740/

[ START ] Updating csgoserver: SteamCMD
Branch: public
Redirecting stderr to '/home/csgoserver/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.00 (0 / 2342246036)
 Update state (0x61) downloading, progress: 10.34 (242179077 / 2342246036)
 Update state (0x61) downloading, progress: 24.01 (562431674 / 2342246036)
 Update state (0x61) downloading, progress: 37.89 (887414695 / 2342246036)
 Update state (0x61) downloading, progress: 51.46 (1205211299 / 2342246036)
 Update state (0x61) downloading, progress: 65.21 (1527348962 / 2342246036)
 Update state (0x61) downloading, progress: 79.60 (1864348950 / 2342246036)
 Update state (0x61) downloading, progress: 85.46 (2001632480 / 2342246036)
 Update state (0x61) downloading, progress: 88.43 (2071172729 / 2342246036)
 Update state (0x61) downloading, progress: 90.92 (2129579859 / 2342246036)
 Update state (0x61) downloading, progress: 93.56 (2191490668 / 2342246036)
 Update state (0x61) downloading, progress: 98.52 (2307643028 / 2342246036)
 Update state (0x61) downloading, progress: 100.00 (180070432 / 180070432)
Success! App '740' fully installed.
Complete! Updating csgoserver: SteamCMD
csgoserver@4Teams:~$ ./csgoserver details

As you can see, the last output is (Complete! Updating csgoserver: SteamCMD) then I did run 'details' which showed offline server.
Sadly I don't have the script log.
I suspect it is related to Ubuntu version somehow. It is not the first time and only on Ubuntu 18. When I'm using Ubuntu 16 it never happens.

## To Reproduce

Steps to reproduce the behaviour:
Run `./csgoserver start` while autoupdate is On.

**Comment by h3o66** [comment]
Can reproduce this with my develop branch version.

**Comment by h3o66** [comment]
I might found the problem here:
https://github.com/GameServerManagers/LinuxGSM/blob/18dd4f79d84847dcd62fcee078f14bc8cf1b7667/lgsm/functions/update_steamcmd.sh#L116

The problem is that the variable `exitbypass` is unset even if it is not used and so the server exits before the start is one.

The line needs to be moved before the `fi` that is there before.
