### ISSUE TITLE
Comment update for rust servers

### ISSUE THREAD

**Issue by vfloyd6** [GameServerManagers/LinuxGSM#3174]
## User Story

As the creator of rustadmin, I would like you to update the file _default.cfg for rust servers.

## Basic info

Can you please update the comment of the line below

`rconweb="1" # Value is: 1 for the Facepunch web panel; 0 for RCON tools like Rusty or Rustadmin.`

and change it like so:

`rconweb="1" # Value is: 1 for the Facepunch web panel, Rustadmin desktop and Rustadmin Online; 0 for RCON tools like Rusty.`

Thank you :)

**Comment by dgibbs64** [comment]
Can do 🙂

**Comment by h3o66** [comment]
created PR + updated the docs
