### ISSUE TITLE
[BUG]Rust wipe missing .sav files after Jan 2021 update

### ISSUE THREAD

**Issue by StaticReality** [GameServerManagers/LinuxGSM#3176]
## User Story

using "wipe" or "full-wipe" its missing the newly generated .sav.1 .sav.2 .sav.* files

## Basic info

* **Distro:** [centos 7]
* **Game:** [Rust
* **Command:** [wipe], [full-wipe]
* **LinuxGSM version:** [v20.6.2]

## Further Information

run command: 
ls -la ~/serverfiles/server/rustserver/ |grep sav

issue wipe or full-wipe command
note how sav.1 and sav.2 etc files are not being removed

## To Reproduce

1. ls -la ~/serverfiles/server/rustserver/ |grep sav
2. ~/rustserver wipe
3. ~/rustserver full-wipe
4. ls -la ~/serverfiles/server/rustserver/ |grep sav
5. note how .sav files are still there

## Expected behavior
.sav.1
.sav.2
ect should be removed on when issuing a wipe or full wipe (these are newly generated files after jan 2021 update):
https://rust.facepunch.com/blog/january-update#serversavebackups

**Comment by h3o66** [comment]
if possible please test the linked PR if it fixes your problem

**Comment by StaticReality** [comment]
I have a dev server I can test this on, whats the best way to get the file that change on PR?

**Comment by StaticReality** [comment]
tested the PR, this fixes the issue.
