### ISSUE TITLE
Squad Server Installer Incorrect config file symlinks. 

### ISSUE THREAD

**Issue by ect0s** [GameServerManagers/LinuxGSM#3178]
The LGSM installer script incorrectly links the squad server config files. 

Path used by installer: 
'/home/lgsmsquad/lgsm/config-default/config-game/Admins.cfg' -> '/home/lgsmsquad/serverfiles/Squad/ServerConfig/Admins.cfg'
copying Bans.cfg config file.
'/home/lgsmsquad/lgsm/config-default/config-game/Bans.cfg' -> '/home/lgsmsquad/serverfiles/Squad/ServerConfig/Bans.cfg'
copying License.cfg config file.
'/home/lgsmsquad/lgsm/config-default/config-game/License.cfg' -> '/home/lgsmsquad/serverfiles/Squad/ServerConfig/License.cfg'
copying Server.cfg config file.
'/home/lgsmsquad/lgsm/config-default/config-game/Server.cfg' -> '/home/lgsmsquad/serverfiles/Squad/ServerConfig/squadserver.cfg'
copying Rcon.cfg config file.
'/home/lgsmsquad/lgsm/config-default/config-game/Rcon.cfg' -> '/home/lgsmsquad/serverfiles/Squad/ServerConfig/Rcon.cfg'

path where config files actually live: 

.../serverfiles/SquadGame/ServerConfig/ **

This means that things like ./squadserver details etc read the wrong configuration values, and that changing these values in ./serverfiles/Squad/* does nothing.

**Comment by h3o66** [comment]
Works for me, cannot reproduce this:

```
Downloading Squad Configs
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
copying Admins.cfg config file.
copying Bans.cfg config file.
copying License.cfg config file.
copying Server.cfg config file.
'/home/h3o66/squad/lgsm/config-default/config-game/Server.cfg' -> '/home/h3o66/squad/serverfiles/SquadGame/ServerConfig/squadserver.cfg'
copying Rcon.cfg config file.
changing hostname.
changing rcon/admin password.
```

Fresh install of LinuxGSM.

Do you have anything changed in the config ?

**Comment by ect0s** [comment]
Which config? 

the LGSM startup scripts, or the ServerConfig Files? 

It might be that my lgsm installer is out of date, but during the "install" I saw it create the ./serverfiles/squad/ folder, and symlink entries. But the server Binary itself never reads that directory.

We saw this with the latest install we did approx 1 month ago for a licensed server; and we also had to edit the startup params for the squadserver script/config inside the ~/lgsm/ folder.

**Comment by h3o66** [comment]
If you have a old LinuxGSM version the `systemdir` variable has the old path you can check it with this:
`egrep ^systemdir lgsm/config-default/config-lgsm/squadserver/_default.cfg`

If the inistal config files are out of date, please open there a issue (but please check the online versions first):
https://github.com/GameServerManagers/Game-Server-Configs

What version of LGSm do you got installed ?

**Comment by ect0s** [comment]
systemdir="${serverfiles}/Squad"
 v20.4.1
 
So, yes, I am out of date.
