### ISSUE TITLE
[FEATURE] Rust Server "Update" Behavior

### ISSUE THREAD

**Issue by hoorigan** [GameServerManagers/LinuxGSM#3184]
## User Story

As a Rust server admin, I want the server update feature to be modified so that I can:

1. Check for updates without forcing an update right at that moment.
2. Check for updates without the script instantly forcing a restart because the server "hasn't been restarted since the last update" even though the server is automatically stopped in order to perform the update.

## Basic info

* **Distro:** Ubuntu 20.04.1 LTS
* **Game:** Rust
* **Command:** Update
* **LinuxGSM version:** LinuxGSM - Rust - Version v20.6.1

## Further Information

I think the easiest solution would actually be to add a `check-update` command using the existing code that checks for updates before actually updating, but even just modifying the behavior of the `update` command would be a helpful improvement.

## Further Reading

N/A

**Comment by h3o66** [comment]
A check update will be there with the next release:
See #3146
There are also a few other requests that request a check-update feature

**Comment by hoorigan** [comment]
@h3o66 Thanks for the quick response! Sorry, I probably should have looked first. I'll close mine.
