### ISSUE TITLE
[BUG] Armaserver x64

### ISSUE THREAD

**Issue by Th3Jock3R** [GameServerManagers/LinuxGSM#3206]
## User Story
As a clanadmin, I want start the updated server, but i got an error, that the file "arma3server_64" was not found.

## Basic info

* **Distro:** Centos 7.4
* **Game:** Arma 3
* **Command:** armaserver start
* **LinuxGSM version:** v21.1.0

## Further Information
in _default.cfg is an error. it says the execution is armaserver_64, but its armaserver_x64

## To Reproduce

Steps to reproduce the behaviour:
1. update to v21.1.0
2. Start server

## Expected behaviour
the server starts, but :
[ FAIL ] Starting arma3server: executable was not found
* /path/to/server/serverfiles/arma3server_64

**Comment by h3o66** [comment]
See the linked issue, hope we can get this maybe out soon.
