### ISSUE TITLE
[BUG] GS:GO crashed on changelevel on activate linuxgsm monitor

### ISSUE THREAD

**Issue by ZUBAT** [GameServerManagers/LinuxGSM#3208]
## User Story

After the CS update:GO on Thursday 28.01 Servers running linuxgsm somehow behave strangely. I have a cronjob configured to monitor the CS server:GO THROUGH ./csgoserver m. When server monitoring is enabled, when the map is changed, the server crashes(in the logs of the Kiled). When disabling monitoring via linuxgsm, there is no such problem. Perhaps someone had a similar situation? Can you tell me how to solve it?

## Basic info

* **Distro:** Debian 10
* **Game:** CS:GO
* **Command:** Monitor
* **LinuxGSM version:** last from gihub

**Comment by ifrag-ru** [comment]
Yes, there really is such a problem, for the second day I was breaking the gossip and thought that the problem was in the DC server ... I noticed a problem on a new, clean server ...

**Comment by ifrag-ru** [comment]
Now I have updated linuxgsm it and it seems that there is no problem yet, but I will look further.

**Comment by ifrag-ru** [comment]
when will it be fixed? the server crashes when changing the map :(

**Comment by ZUBAT** [comment]
this is not bug linuxgsm. sry https://forums.alliedmods.net/showthread.php?t=330153
