### ISSUE TITLE
[BUG] 7dtd didn't create the oxide folder on startup.

### ISSUE THREAD

**Issue by BattleSheep94** [GameServerManagers/LinuxGSM#3209]
## Basic info

* **Distro:** [Ubuntu 20.04 & Debian 9.5]
* **Game:** [7 Days to Die]
* **Command:** [mods-install]
* **LinuxGSM version:** [v21.1.1]

## Further Information

LGSM doesn't create the oxide server on a fresh install

## To Reproduce

Steps to reproduce the behaviour:
1. Install a new Server
2. Install oxide with "mods-install"
3. Start the Server
4. oxide doesn't start.

**Comment by h3o66** [comment]
Linking support thread from umod side:
https://umod.org/community/7-days-to-die/27394-missing-oxide-folders

**Comment by h3o66** [comment]
I would guess this is not issue of LinuxGSM, I see that the files are replaced, but there is no indication that umod/oxide did start up on the server.

**Comment by Claiyc** [comment]
Not an issue with lgsm.
