### ISSUE TITLE
[BUG] Rust use to have a live log

### ISSUE THREAD

**Issue by thegreatstorm** [GameServerManagers/LinuxGSM#3213]
In the past Rust LinuxGSM use to have a live log of the server running. But recently on new version of linuxgsm I can't seem to get it. Even when the server is shut down I still do not see rust log.

Location Originally:
`/home/rustserver/log/server`

This makes it difficult to monitor logs for automation such as a log analytics software.

**Comment by dgibbs64** [comment]
The same logs will show in instead.

`/home/rustserver/log/console`
