### ISSUE TITLE
Add query to Valheim

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#3221]
## User Story

Valheim support server query

## Basic info

* **Game:** Valheim
* **Command:** Monitor

**Comment by MaxNijholt** [comment]
After todays update it seems to have broken something. Although the server was up and running, without issues the query was unreachable and resulted in a restart of the server. I've added the server logging below.

`vhserver Logs
=================================

Script log
===================
/home/vhserver/log/script/vhserver-script.log
Mar 02 18:05:13.026 vhserver: UPDATE: PASS: core_exit.sh exiting with code: 0
Mar 02 18:14:44.631 vhserver: MONITOR: INFO: Checking session: CHECKING
Mar 02 18:14:45.641 vhserver: MONITOR: PASS: Checking session: OK
Mar 02 18:14:46.653 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 1 : QUERYING
Mar 02 18:14:50.144 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 1: FAIL
Mar 02 18:15:06.236 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 2 : QUERYING
Mar 02 18:15:09.714 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 2: FAIL
Mar 02 18:15:25.820 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 3 : QUERYING
Mar 02 18:15:29.407 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 3: FAIL
Mar 02 18:15:41.553 vhserver: MONITOR: INFO: LinuxGSM version: v21.1.3
Mar 02 18:15:41.556 vhserver: MONITOR: WARN: core_exit.sh exiting with code: 3
Mar 02 18:19:24.456 vhserver: MONITOR: INFO: Checking session: CHECKING
Mar 02 18:19:25.467 vhserver: MONITOR: PASS: Checking session: OK
Mar 02 18:19:26.481 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 1 : QUERYING
Mar 02 18:19:30.021 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 1: FAIL
Mar 02 18:19:46.116 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 2 : QUERYING
Mar 02 18:19:49.590 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 2: FAIL
Mar 02 18:20:05.702 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 3 : QUERYING
Mar 02 18:20:09.236 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 3: FAIL
Mar 02 18:20:25.346 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 4 : QUERYING
Mar 02 18:20:28.857 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 4: FAIL
Mar 02 18:20:44.956 vhserver: MONITOR: INFO: Querying port: gamedig: 144.91.78.222:2457 : 5 : QUERYING
Mar 02 18:20:48.741 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 5: FAIL
Mar 02 18:20:49.752 vhserver: MONITOR: WARN: Querying port: gamedig: 144.91.78.222:2457 : 5: FAIL
Mar 02 18:20:49.764 vhserver: MONITOR: INFO: Sending alert: Restarted: vhserver


Console log
====================
/home/vhserver/log/console/vhserver-console.log

03/02/2021 18:16:27: Connected
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 18:16:27: Got connection SteamID 76561198102284998
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 18:16:27: Got handshake from client 76561198102284998
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 18:16:31: VERSION check their:0.147.3  mine:0.147.3
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 18:16:31: Server: New peer connected,sending global keys
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

03/02/2021 18:16:52: Got character ZDOID from Gunni Leifsson : -1036418430:22
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
`
