### ISSUE TITLE
[BUG][Rust][CentOS][Logging][Menu]

### ISSUE THREAD

**Issue by thegreatstorm** [GameServerManagers/LinuxGSM#3230]
During average installation of rust. The ./rustserver.sh provides a list of improper format. Seems the format they are utilizing only supports another OS and not CentOS/Amazon. As well as the log for rustserver-console.log is missing as well making it difficult to monitor the game server status during the start up.

**Comment by dgibbs64** [comment]
Im assuming you are running CentOS 7 as console logs don't work with tmux 1.8 which you can upgrade 
https://docs.linuxgsm.com/requirements/tmux#upgrade-tmux-centos-7-using-ghettoforge

I don't know what you mean by `the ./rustserver.sh provides a list of improper format.`

**Comment by thegreatstorm** [comment]
Sorry, power outage and winter storm took me out.

Well I was having issues getting any log in `log/console/rustserver-console.log` But now its working. So I wonder if it was a tmux issue with aws. But my containers now work with logging. So I say close for now since I can't replicate.
