### ISSUE TITLE
Valheim Server not Starting 

### ISSUE THREAD

**Issue by DerBrommi** [GameServerManagers/LinuxGSM#3236]
Hi Everybody,

Everytime I try to start my Valheim Server it stops at DungeonDB Start. I tried different ways to install it, but it stops at DungeonDB everytime.

My Console and details
https://pastebin.com/Rw8kry6y

**Comment by dgibbs64** [comment]
This is not an issue with LinuxGSM. However it looks like your server is under a heavy load. So that might not be helping
