### ISSUE TITLE
[BUG] On CentOS Linux 8, LinuxGSM does should install hostname package dependency.

### ISSUE THREAD

**Issue by yeenbean** [GameServerManagers/LinuxGSM#3248]
## User Story

As a [not sure what to put here], I want `hostname` package included as a dependency so that `$HOSTNAME` environment variable is filled properly, allowing Discord alerts to function when this package isn't found on the system.

## Basic info

* **Distro:** CentOS Linux 8 running in LXC container
* **Game:** Issue seen in Minecraft and Killing Floor 2 servers.
* **Command:** `./mcserver test-alert` and `./kf2server test-alert`
* **LinuxGSM version:** [v20.1.3]

## Further Information

After initial configuration of LGSM and getting my SkyBlock server up and running, I configured a Discord webhook to receive server alerts. When testing alerts using `./mcserver ta` I get the following error:

```
[ FAIL ] Sending Alert mcserver: Sending Discord alert: {"embeds": ["0"]}
```

After doing some research, I learn that this error is returned from Discord when improper JSON information is found in an embed. I did some digging in developer mode to see if I could resolve the issue. tl;dr: I discover the `HOSTNAME` environment variable was not being set by my system. So I `yum install hostname`, log out, and log back in to get the environment variable set correctly, which then gets Discord alerts working smoothly.

## To Reproduce

Steps to reproduce the behaviour:

1. Create LXC container using CentOS Linux 8 image
2. Install `wget` and `sudo` packages
3. Create user account for LGSM and add to sudoers file
4. Log out of root, login to new user account, and install LGSM
5. LGSM installs deps automatically
6. Configure server
7. Start server
8. Test alerts; Discord alert fails

## Expected behaviour

All steps above, but with Discord alerts working.

**Comment by dgibbs64** [comment]
I am assuming that the LXC image is a cut down version of the full centos 8?

**Comment by yeenbean** [comment]
Yes I believe so.

**Comment by dgibbs64** [comment]
This is a tough one as hostname is a very basic feature of Linux systems so I am surprised it isn't installed by default

**Comment by h3o66** [comment]
Is there a easy way to detect the container ?
We could maybe add a detection for LXC and add then dynamically the dependency

**Comment by yeenbean** [comment]
Output of `systemd-detect-virt`

```
[mcserver@mc-paper ~]$ systemd-detect-virt
lxc
```

This was only tested in the CentOS container I currently have up, but I have the resources to test in the other supported OSes for this project if needed. Will do this later in the evening.

**Comment by h3o66** [comment]
I guess with this a hotfix coule be done, as this would be easy to implement.

**Comment by h3o66** [comment]
afaik there seem to be 2 values for lxc containers for `systemd-detect-virt` in this case: `lxc` and `lxc-libvirt`

All types can be looked up with `systemd-detect-virt --list`

**Comment by h3o66** [comment]
@yeenbean if you have time, you could test the connected PR.
Be aware that the PR branch is on the development state and contains more changes.
