### ISSUE TITLE
Rebuilding this

### ISSUE THREAD

**Issue by Prajwal-Koirala** [GameServerManagers/LinuxGSM#3250]
Hello,
So i was recently using this for testing and it seems like there are some bugs, but for 2x maintainers it's pretty good, i was thinking of recreating this and making it even simpler and adding more features, i was wondering if that is allowed?

I am not after the code, i just need the configs.

**Comment by dgibbs64** [comment]
Thank you for your feedback!

LinuxGSM is open source, so you are free to recreate your own version of LinuxGSM that is simpler and has more features. I'm curious to see what you come up with, please do share when you have it up with your solution.

**Comment by Prajwal-Koirala** [comment]
Thank you.
Give me a couple of days.

**Comment by dgibbs64** [comment]
Are you planning on supporting all 115 game servers?

**Comment by Prajwal-Koirala** [comment]
Yes.

**Comment by dgibbs64** [comment]
LinuxGSM has been in constant development since 2012. I look forward to seeing what you come up with in 72 hours.

**Comment by Prajwal-Koirala** [comment]
1. Base installation on almost all OS completed.
2. Automated Linux Users completed.
3. Update for the scripts completed.

Should be able to get a single game working within a couple of hours, Once the base installation is done it's just adding other games.

**Comment by Prajwal-Koirala** [comment]
Hey i got a simple question.
I read though the code and why are u making this so complicated?


Ignore if u don't agree with it, just my opinion:
Make this as simple as possible, it's just a simple app that runs on a linux server in some data center in the world, instead there are literally over 150 files, no shit it's hard to manage, if u take something simple and try and make it as complicated as possible than yes it will be complicated but this was never meant to be so complicated, The simpler the app the easier for devs to manage.

**Comment by dgibbs64** [comment]
It's as complicated as it has to be to get all the functionality working. LinuxGSM is actually very simple.  I don't know why you are wasting time leaving comments. You don't have much time left if you want to add ALL the existing features of LinuxGSM and make it simpler while adding more features in under 72 hours

**Comment by JimTR** [comment]
So Far so bad .. 17 hours in & not one function written ... looking at the code @Prajwal-Koirala I think you may have missed the brief

**Comment by dgibbs64** [comment]
@Prajwal-Koirala Looks like your time is up. Did you get everything working? 

O wait you didn't, you changed a few things in a boilerplate script, bragged about how amazing it was going to then give up and just commit spam your repo to make a number look good on your profile. So much for "making it even simpler and adding more features" "within 72 hours". 

Why not actually contribute something positive to a project? I saw your profile history and all you seem to do is insult other devs/projects, post spammy PR's and comments and close them. I have no idea why you are wasting your time and effort on trying to be misleading when it is pretty obvious what you are doing. It isn't about making your profile stats look good its about making positive contributions and creating software no matter your ability.

I welcome you to pick an issue you are interested in and contribute code if you like. I recommend something simple, to begin with to learn how LinuxGSM works.

All the best.

**Comment by Prajwal-Koirala** [comment]
I will push tonight.

**Comment by dgibbs64** [comment]
Why do you commit spam?

**Comment by Prajwal-Koirala** [comment]
> Why do you commit spam?


Started out messing with `.git` folder and than turned into git-into-art and than just turned into having some fun.

**Comment by dgibbs64** [comment]
Why do you think you can replicate 8 years of work in 3 days?

**Comment by Prajwal-Koirala** [comment]
> Why do you think you can replicate 8 years of work in 3 days?

Cause i just did, u made a shell script for every single game. WHY?
I mean you can have a single small application that can manage it all.

**Comment by dgibbs64** [comment]
sounds like you have no idea what LinuxGSM actually does or how it works. I suggest you look at the website check out all the commands and features as currently, you don't even have a working installer.

**Comment by Prajwal-Koirala** [comment]
@dgibbs64 

I will push tonight.

I managed to get 90% of the things working, Look at the `git-commit-generator`, https://github.com/cirosantilli/test-many-commits-1m/issues/12

Chill, This is like a friendly competition, i have no long term interest in Game Hosting

**Comment by dgibbs64** [comment]
Honestly, this is the most bizarre interaction I have had on GitHub.

**Comment by Prajwal-Koirala** [comment]
Dude this is github,
This isn't where someone is trying to sell you something, this is more relaxed.


Mostly on automation, automated about 99% of the things.

**Comment by dgibbs64** [comment]
I have no idea what are you talking about.

**Comment by dgibbs64** [comment]
Nope, I do this in my spare time for fun, have a full-time job. The project has become so popular I have people and companies sponsor my work.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/git-views-generator

Take a look at this, has over 60,000 views and they are all botted, i am not trying to mislead the people and be like on look i got 60,000 views, i am the shit, i am more or less here for open source project, anything serious isnt going to be public.

**Comment by Prajwal-Koirala** [comment]
@dgibbs64 
Hey,
Let me clear up some things.

1. I am not mad / sad / angry, its just that the code base is very very very big, u need alot of devs to work on this, to even fix a small number of bugs.
2. I actually respect the project, and support all the devs working on it but just not the size
3. I don't hate the project nor the people, it's just very large and i am looking at this and wondering why??
4. Github is for shits and giggles and having fun, this is just a software project. 
5. I don't hate github nor the projects, just having fun and not taking thing seriously, don't get me wrong i respect the project but i am just here trying to have fun, if i didn't respect the project i just wouldn't care, i am here cause i like the project and talking shit is fun.

**Comment by dgibbs64** [comment]
Locking this waste of time issue. 

It's about as appropriate to "shit talk" on GitHub as it is to do so on Linkedin..... it's simply not.
