### ISSUE TITLE
[BUG] valheim startparameters missing -savedir config

### ISSUE THREAD

**Issue by StaticReality** [GameServerManagers/LinuxGSM#3253]
## User Story

need to add -savedir config to the startupparams to set admins, save bans etc

## Basic info

* **Distro:** [Ubuntu 20]
* **Game:** [valheim ]
* **Command:** [start]
* **LinuxGSM version:** [v21.1.3]

## Further Information

In order to set admins, track / save bans and white listed accounts between restarts a -savedir config is needed on the startup parameter. 

Currently when installing + starting a vhserver, no config directory is made:
ls -la ~/serverfiles/config/
ls: cannot access '/home/vhserver/serverfiles/config/': No such file or directory

After applying the fix you will see expect results:
$ ls -la ~/serverfiles/config/
total 24
drwxrwxr-x 3 vhserver vhserver 4096 Feb 15 04:30 .
drwxrwxr-x 7 vhserver vhserver 4096 Feb 15 04:14 ..
-rw-rw-r-- 1 vhserver vhserver   57 Feb 15 04:30 adminlist.txt
-rw-rw-r-- 1 vhserver vhserver   40 Feb 15 04:14 bannedlist.txt
-rw-rw-r-- 1 vhserver vhserver   42 Feb 15 04:14 permittedlist.txt
drwxrwxr-x 2 vhserver vhserver 4096 Feb 15 16:19 worlds

## To Reproduce

cat ~/lgsm/config-lgsm/vhserver/_default.cfg |grep startparameters=
startparameters="-name '${servername}' -password ${serverpassword} -port ${port} -world ${gameworld} -public ${public}"

## Expected behaviour
cat ~/lgsm/config-lgsm/vhserver/_default.cfg |grep startparameters=
startparameters="-name '${servername}' -password ${serverpassword} -port ${port} -world ${gameworld} -public ${public} -savedir config"

**Comment by ialexpw** [comment]
It seems these are added to the same directory as where the worlds are saved. From the user running it, these are located;

~/.config/unity3d/IronGate/Valheim

$ ls ~/.config/unity3d/IronGate/Valheim
adminlist.txt  bannedlist.txt  permittedlist.txt  prefs  worlds

**Comment by h3o66** [comment]
As `ialexpw` noted, this is not a bug - only the default dir is somewhere else.
I also see no easy way to migrate the data if we would set the parameter now somewhere.
We could write a migraion script for this, but in what way would we inform the user ?

**Comment by netpro2k** [comment]
Could just add a new config option for this directory, and set it by default to `~/.config/unity3d/IronGate/Valheim`, so existing users would not need to migrate anything but people could easily change it if they wanted. It would be smart for the `backup` command to then use this new variable as part of the directories it backs up, because as it stands right now its not actually backing up the most important data, the users world.

**Comment by ialexpw** [comment]
> Could just add a new config option for this directory, and set it by default to `~/.config/unity3d/IronGate/Valheim`, so existing users would not need to migrate anything but people could easily change it if they wanted. It would be smart for the `backup` command to then use this new variable as part of the directories it backs up, because as it stands right now its not actually backing up the most important data, the users world.

Just as a side-note. The backups do currently include this data as I've had to revert from one already and I had to check it was in there beforehand.

**Comment by netpro2k** [comment]
Ah interesting, my mistake. I didn't see that directory referenced in the config at all so I didn't see how it would get backed up. Had not tried it myself yet. Is it backing up the entire directory containing the `vhserver` script?

**Comment by StaticReality** [comment]
its likely the best fix here is just update installation documentation. All the documentation I could find was on 3rd part hosting sites using windows servers using a config dir in the root install. I also did not wait the 20mins or so when testing this on my dev server (restarted server 15mins and it wiped the seed). This is why I drew to conclusion the config directory was missing.

**Comment by dgibbs64** [comment]
A fix is planned for the next release. Plus docs will need to be updated

**Comment by ialexpw** [comment]
> Ah interesting, my mistake. I didn't see that directory referenced in the config at all so I didn't see how it would get backed up. Had not tried it myself yet. Is it backing up the entire directory containing the `vhserver` script?

Yes it seems to grab everything.

![image](https://user-images.githubusercontent.com/7994724/108710342-d3985d00-750b-11eb-9906-284ebcfc9fa3.png)

**Comment by meeces2911** [comment]
For anyone else reading this and is mildly confused as to why the ialexpw's backup is backing up the worlds folder - thats because they have lgsm installed in their users home directory, and so when the backup goes and backs up the root lgsm folder, it picks up the .config directory too.

If lgsm is not installed there, then it (currently) doesn't know about the worlds directory living outside of the game files folder.
