### ISSUE TITLE
[BUG] Related to #2905, Pop!OS too has renamed lib32gcc1 to lib32gcc-s1, so dependency check for lib32gcc1 using dpkg-query fails

### ISSUE THREAD

**Issue by SimoFiuz** [GameServerManagers/LinuxGSM#3264]
## User Story

As a Pop!OS user, which is an Ubuntu derivative, I need the dependency check to pass for lib32gcc-s1.

## Basic info

* **Distro:** [Pop!OS 20.10]
* **Game:** [Valheim]
* **Command:** [Install]
* **LinuxGSM version:** [v20.1.3]

## Further Information

Dependency check fails as it is not considering the library rename as it does for ubuntu, in check_deps.sh.

## To Reproduce

Steps to reproduce the behaviour:
Try to install Valheim on a Pop!OS machine.

I successfully installed the Valheim game server editing check_deps.sh, after looking at what info_distro.sh resolves for Pop!OS

> $distroid pop
> $distroname Pop!_OS 20.10
> $distroversion 20.10
> $distrocodename groovy

On line 190:
```sh
if { [ "${distroid}" == "debian" ]&&[ "${distroversion}" == "11" ]; }||{ [ "${distroid}" == "ubuntu" ]&&[ "${distroversion}" == "20.10" ]; } || { [ "${distroid}" == "pop" ]&&[ "${distroversion}" == "20.10" ]; }; then
```

On line 354:

```sh
if { [ "${distroid}" == "debian" ]&&[ "${distroversion}" == "11" ]; }|| { [ "${distroid}" == "ubuntu" ]&&[ "${distroversion}" == "20.10" ]; } ||{ [ "${distroid}" == "pop" ]&&[ "${distroversion}" == "20.10" ]; }; then
```

**Comment by dgibbs64** [comment]
Thanks for this solution. I am happy to get this added in as Pop is just a derivative of Ubuntu. @GameServerManagers/moderator If anyone is interested in creating a PR for this it is a relatively simple change.

**Comment by JoniLieh** [comment]
@SimoFiuz Thank you so much, I tried installing a gameserver on Pop!_OS as well, your edits fixed it for me!
Many thanks :)
