### ISSUE TITLE
[FEATURE] Get Alerts When Updating Multiple Instances

### ISSUE THREAD

**Issue by gbschenkel** [GameServerManagers/LinuxGSM#3268]
## User Story

I run some games with multiples instances in the same server/folder, right now I am only using with Valheim. Well when my "main" instance get a update like today, it show with `check_update.sh` it needs update, then `command_update.sh` updates it, sending a message to the Platform, in my case, Discord. 

When I run the update in the other instance, it show an update has been applied, and the instance need restart, which it do automatically, BUT, it don't send a message about update neither a restart. 

Well, the request/feature is to alert when the instance will be restarted after a update, by the `check_update.sh` script.

## Basic info

* **Distro:** TurnkeyLinux (Debian Buster 10.8)
* **Game:** Valhein
* **Command:** Update
* **LinuxGSM version:** v20.1.3

## Further Information

Invoke the alert when the instance have been updated and needs a restart.

## Further Reading

```
vhserver@valheim ~$ ./vhserver-1 u
[ INFO ] Updating vhserver-1: vhserver-1 has not been restarted since last updategrep: 
[  OK  ] Stopping vhserver-1: Graceful: CTRL+c: 4: OK
```

**Comment by dgibbs64** [comment]
A refactor of alerts will now trigger an alert if "vhserver-1 has not been restarted since last update" has been triggered

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/4345
