### ISSUE TITLE
[BUG] Discord Webhook failing with Valheim

### ISSUE THREAD

**Issue by MajesticBeast** [GameServerManagers/LinuxGSM#3275]
## Basic info

* **OS** Ubuntu 20.04
* **Game:** Valheim
* **Command:** test-alert
* **LinuxGSM version:** v21.1.3

## Further Information

I created a new webhook in my Discord Valheim text channel titled "LinuxGSM" (I'm the server owner if that matters). I edited the ~/lgsm/config-lgsm/vhserver/common.cfg file to include the exact text on the setup page for the Discord Alerts (and I swapped out the webhook URL to my own webhook URL of course). When running "./vhserver test-alert", this is output to standard out (of note is lines 2 and 3):

```
[ WARN ] Sending Alert vhserver: More Info not enabled
[ .... ] Sending Alert vhserver: Sending Discord alertparse error: Invalid numeric literal at line 11, column 24
[ FAIL ] Sending Alert vhserver: Sending Discord alert: {"message": "400: Bad Request", "code": 0}
[ WARN ] Sending Alert vhserver: Email alerts not enabled
[ WARN ] Sending Alert vhserver: IFTTT alerts not enabled
[ WARN ] Sending Alert vhserver: Mailgun alerts not enabled
[ WARN ] Sending Alert vhserver: Pushbullet alerts not enabled
[ WARN ] Sending Alert vhserver: Pushover alerts not enabled
[ WARN ] Sending Alert vhserver: Telegram Messages not enabled
[ WARN ] Sending Alert vhserver: Rocketchat alerts not enabled
[ WARN ] Sending Alert vhserver: Slack alerts not enabled
```

I also deleted and recreated the webhook, and tried it in different channels as well, including one where I am successfully getting Radarr and Sonarr alerts, in an effort to verify its not some random discord setting or error on my part.

## To Reproduce

Steps to reproduce the behaviour:
Follow the exact instructions listed on the setup page for discord alerts:
https://docs.linuxgsm.com/alerts/discord

## Expected behaviour
Successful test alert in the #valheim discord channel

**Comment by dgibbs64** [comment]
My guess is that there are some special characters its trying to send to discord. For some reason there appears to be invalid characters going in to the alert, maybe check thinks like your server name. or the url has not been input correctly in to teh config.

Also please post your config as I am unable to tell.

**Comment by MajesticBeast** [comment]
Here is my common.cfg file:
```
##################################
######## Common Settings #########
##################################
# PLACE GLOBAL SETTINGS HERE
## These settings will apply to all instances.
stats="on"
stats="on"

# Discord Alerts | https://github.com/GameServerManagers/LinuxGSM/wiki/Discord
discordalert="on"
discordwebhook="https://discord.com/api/webhooks/811927142464093249/ENpHE1qz724FQB6qC12TCCzoqMl1Q0gdRLywwJ0ODrJLuB0jnBs4G0efXx9YxUitHBWI"
```

Everything was copy pasted, so there shouldn't be any typos of any sort.

**Comment by rconjoe** [comment]
Could you post the results of `./vhserver post-details` instead?

Also I would not be posting your webhook endpoints in a public forum.

**Comment by MajesticBeast** [comment]
As my edit a minute after I posted said, I changed numbers/letters so no, thats not my actual endpoint.

I'm going to close this out, I'm just going to create a new install and try from there.
