### ISSUE TITLE
[BUG] Valheim server does not register with the Steam master server.

### ISSUE THREAD

**Issue by fs86** [GameServerManagers/LinuxGSM#3276]
I changed steammaster to "true" in the instance configuration but even then it does not register with the master server. In general, this should be possible, since I see many Valheim servers in the Steam Server Browser.

![steammaster](https://user-images.githubusercontent.com/39554311/108405594-88d3c800-7221-11eb-8026-2cdfd03e2deb.png)

**Comment by rconjoe** [comment]
I'm not sure if you're referring to the Steam server browser proper or the ingame Valheim server browser. If the latter, it is supposedly capped at listing 4920 servers at a time: 

> "There are many people having issues with there Valheim servers being listed in the server browser and as such we are 
getting lots of questions about firewalls and networking. It appears however that the game is capped at listing 4920 servers. This means your server may only show intermittently. The most reliable method to connect to your server will be to take the IP and Port and add it to your steam server browser favourites. Hopefully this will be resolved soon."

Adding a server to favorites by IP seems to be the most reliable way to connect to a vhserver for now.

**Comment by fs86** [comment]
It's about the registration with the Steam master server. The screenshot shows that the status is set to "not listed". This means that the server is neither listed in the Steam server browser nor in the ingame server browser.

**Comment by dgibbs64** [comment]
@fs86 Just to be clear the master serve option is not supported by all game servers even if they use the steam server browser. Valheim is not currently supported with this option

**Comment by fs86** [comment]
> @fs86 Just to be clear the master serve option is not supported by all game servers even if they use the steam server browser. Valheim is not currently supported with this option

Thank you for the explanation. I just wonder why the server is not visible in the server browser.

**Comment by dgibbs64** [comment]
@fs86 probably for the reasons explained above. This is happening to many people currently. If long as you can connect directly to your server then its working properly. The Valheim server list is capped and they have been overloaded with servers.

**Comment by netstx** [comment]
I add the server manually then add it to my favorites, that is a "quick fix" for this issue for now.
