### ISSUE TITLE
[Server Request] Battlefield Vietnam Server manager

### ISSUE THREAD

**Issue by Gyppie** [GameServerManagers/LinuxGSM#3277]
## What game server would you like adding?

Battlefield Vietnam Server manager. 
I know the Battlefield Vietnam already exsists, but this is accessories to the server to remote manage it and would be nice to install this with the server for Battlefiels Vietnam.

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [ ] Yes
* [*] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [*] Yes
* [ ] No
[BVServerManager201.zip](https://github.com/GameServerManagers/LinuxGSM/files/6005694/BVServerManager201.zip)

**Comment by rconjoe** [comment]
This .zip contains two programs: an .exe that is used as a client program, wherein the user can manage Linux Battlefield Vietnam server instances running the other included program as a daemon. From the docs: 

>  Server Manager 2.0 for Linux allows you to manage your Linux BF server
using Remote Manager 2.0 for Windows ("BxRM")...

> Server Manager for Linux (or "BxSMD" for short) consists of a single
executable (BxSMD) that may be run in the foreground or as a daemon. BxSMD
acts as a server for BxRM clients. Up to 16 BxRM clients can connect to
BxSMD simultaneously and manage the server.

I''m going to tag this as a feature request as this could theoretically be added as a plugin installed by `./gameserver mi`. I haven't tested the attached utilites at all.

**Comment by Gyppie** [comment]
Sorry, wrong file attached. Here is the right one.
[BVServerManager201_2.zip](https://github.com/GameServerManagers/LinuxGSM/files/6006665/BVServerManager201_2.zip)

**Comment by dgibbs64** [comment]
I think this is something that the server admin should install themselves. I dont have plans to implement partly as bfv is not used much
