### ISSUE TITLE
Errors from ps for session leaders or group ID's, when Running mutiple instances on same server.

### ISSUE THREAD

**Issue by underleo** [GameServerManagers/LinuxGSM#3282]
## User Story

When i run multiple instances(cluster) on my server, commands "./arkserver-2 details/monitor" for second instance will poped up error about "error: list of session leaders OR effective group IDs was invalid".
The first instance works well and no problem, it just impact for the instances other than the first one.

## Basic info

* **Distro:** [CentOS Linux release 7.9.2009 (Core)]
* **Game:** [Ark: Survival Evolved]
* **Command:** [./arkserver details, ./arkserver monitor]
* **LinuxGSM version:** [v21.1.3]

## Further Information

The cluster works well and below sturcture FYI:
```
[arkserver@xleo-lgsm02 ~]$ ls -la
total 36
drwx------  9 arkserver arkserver   208 Feb 17 16:07 .
drwxr-xr-x. 5 root      root         56 Feb 18 11:58 ..
drwxrwxr-x  5 arkserver arkserver    65 Feb 17 16:09 arkserver-1
drwxrwxr-x  5 arkserver arkserver    67 Feb 19 15:00 arkserver-2
-rw-------  1 arkserver arkserver  7940 Feb 19 15:24 .bash_history
-rw-r--r--  1 arkserver arkserver    18 Apr  1  2020 .bash_logout
-rw-r--r--  1 arkserver arkserver   193 Apr  1  2020 .bash_profile
-rw-r--r--  1 arkserver arkserver   231 Apr  1  2020 .bashrc
drwxr-xr-x  3 arkserver arkserver    25 Feb 17 11:51 clusters
drwxrwxr-x  3 arkserver arkserver    18 Feb 17 16:05 lgsm
-rwxrwxr-x  1 arkserver arkserver 15934 Feb 17 16:05 linuxgsm.sh
drwxrwxr-x  3 arkserver arkserver    19 Feb 16 20:51 .local
drwxrw----  3 arkserver arkserver    19 Feb 16 20:49 .pki
drwxrwxr-x  5 arkserver arkserver    93 Feb 19 09:05 .steam
```
```
[arkserver@xleo-lgsm02 arkserver-2]$ ./arkserver-2 details
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
(standard_in) 1: syntax error
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).

Distro Details
\=================================
Distro:   CentOS Linux 7 (Core)
Arch:   x86_64
Kernel:   3.10.0-1160.15.2.el7.x86_64
Hostname:   xleo-lgsm02.klab.org
Uptime:   2d, 18h, 38m
tmux:   tmux 1.8
glibc:   2.17

Server Resource
\=================================
CPU
Model:   Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Cores:   4
Frequency:   2499.998MHz
Avg Load:   0.51, 0.51, 0.52

Memory
Mem:   total   used   free   cached  available
Physical:   24GB   20GB   3.1GB  3.2GB   3.1GB
Swap:   4.0GB   3.3MB  4.0GB

Storage
Filesystem:   /dev/mapper/centos-home
Total:     45G
Used:     30G
Available:   16G

Network
IP:   0.0.0.0
Internet IP:   x.x.x.x

Game Server Resource Usage
\=================================
CPU Used:   %
Mem Used:   %   0MB

Storage
Total:   13G
Serverfiles:   13G

ARK: Survival Evolved Server Details
\=================================
Server name:   Unmmm ARK Server02
App ID:   376030
Server IP:   0.0.0.0:7779
Internet IP:   x.x.x.x:7779
Server password:   xxxxxxxxxx
Admin password:   xxxxxxxxxx
Maxplayers:   70
Default map:   Extinction
Master server:   not listed
Status:   ONLINE

arkserver-2 Script Details
\=================================
Script name:   arkserver-2
LinuxGSM version:   v21.1.3
glibc required:   2.15
Discord alert:   off
Email alert:   off
IFTTT alert:   off
Mailgun (email) alert:   off
Pushbullet alert:   off
Pushover alert:   off
Rocketchat alert:   off
Slack alert:   off
Telegram alert:   off
Update on start:   off
User:   arkserver
Location:   /home/arkserver/arkserver-2
Config file:   /home/arkserver/arkserver-2/serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

Backups
\=================================
No Backups created

Command-line Parameters
\=================================
 ./ShooterGameServer Extinction?SessionName='Unmmm ARK Server02'?AltSaveDirectoryName=Extinction?listen?MultiHome=0.0.0.0?MaxPlayers=70?QueryPort=27017?RCONPort=27022?Port=7779?ServerAdminPassword=xxxxxxxx?ShowFloatingDamageText=true -automanagedmods -NoTransferFromFiltering -ClusterDirOverride=/home/arkserver -clusterid=xxxxxxxxx

Ports
\=================================
Change ports by editing the parameters in:
/home/arkserver/arkserver-2/lgsm/config-lgsm/arkserver

Useful port diagnostic command:
netstat -atunp | grep ShooterGame

DESCRIPTION          DIRECTION  PORT   PROTOCOL
> Game   INBOUND    7779   udp
> RAW    INBOUND    7780   udp
> Query  INBOUND    27017  udp
> RCON   INBOUND    27022  tcp

Status: ONLINE
```
[arkserver@xleo-lgsm02 arkserver-2]$

## Further Reading

It's similar to the issue reported as below, it resolved for a single instance but not for multiple.
https://github.com/GameServerManagers/LinuxGSM/issues/2881

## To Reproduce

Just enter the second directory and run the commands.

**Comment by dgibbs64** [comment]
This is one of those issues that keeps rearing it head. Thanks, for letting us know.

**Comment by schertt1** [comment]
Something bout the dash in the name maybe... I have the same problem with multiple Valheim servers out of the same directory; "valheim" works fine but "valheim-2" has this same problem.

**Comment by rmaureira** [comment]
I have the same issue with a single server and no changes in the name:

`[vh@XXXXXXXXX ~]$ ./vhserver dt
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
(standard_in) 1: syntax error
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: list of session leaders OR effective group IDs was invalid

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).

Distro Details
=========================================================================================================================================================================================================================
Date:
Distro:   CentOS Linux 7 (Core)
Arch:   x86_64
Kernel:   3.10.0-1160.11.1.el7.x86_64
Hostname:   XXXXXXXXXXXXX
Uptime:   72d, 14h, 5m
tmux:   tmux 1.8
glibc:   2.17
`

**Comment by dgibbs64** [comment]
This issue is only occurring on CentOS 7. I thought I had made some changes to prevent this in CentOS but maybe not. I will have to re-visit this.

**Comment by dgibbs64** [comment]
there has been a reword of tmux session handling that may havbe resolved this issue now
