### ISSUE TITLE
[BUG] there is no package with the excact name lib32gcc1 nor lib32stdc++6 in Debian 10.8

### ISSUE THREAD

**Issue by fmjensen** [GameServerManagers/LinuxGSM#3284]
I wanted to install Valheim on my Mac Mini running Debian but ran into problems. 

## Basic info

* **Distro:** [Debian 10.8]
* **Game:** [Valheim]
* **Command:** [sudo ./vhserver install]
* **LinuxGSM version:** [latest]

## Further Information
```
apt search lib32gcc1
Sorting... Done
Full Text Search... Done
lib32gcc1-amd64-cross/stable 1:8.3.0-2cross1 all
  GCC support library (32 bit Version)
### CUT ###
lib32gcc1-x32-cross/stable 1:8.3.0-2cross2 all
  GCC support library (32 bit Version)
```
and
```
apt search lib32stdc++
Sorting... Done
Full Text Search... Done
lib32stdc++-8-dev-amd64-cross/stable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (development files) (amd64)
### CUT ###
lib32stdc++6-amd64-cross/stable 8.3.0-2cross1 all
  GNU Standard C++ Library v3 (32 bit Version)
```
reveals that there is no package with the excact name lib32gcc1 nor lib32stdc++6

I installed _lib32gcc1-amd64-cross_ and _lib32stdc++6-amd64-cross_ and tried to continue with the Valheim install. It is stated that running `./vhserver install` as root should install missing dependencies - but it does not know the new package names so i cried for help in the [linuxGSM support discord channel](https://discord.com/channels/127498813903601664/135126471319617536/812275322967818300) and here...
![ScreenShot 2021-02-19 114435](https://user-images.githubusercontent.com/3484684/108497523-da289980-72ab-11eb-905a-5fd0d3805560.png)

## To Reproduce

Steps to reproduce the behaviour:
Try to install Valheim using the guide https://linuxgsm.com/lgsm/vhserver/

## Expected behaviour
Fully functional Valheim server

**Comment by dgibbs64** [comment]
Try this one lib32gcc-s1

related #3264

**Comment by fmjensen** [comment]
Thank you for the reply.

I found #3264 when searching the issues here and tried that already. `lib32gcc-s1` is also not found...
 - sorry for not mentioning that and forgetting to enter a title.

**Comment by h3o66** [comment]
It is there for debian buster:
https://packages.debian.org/buster/lib32gcc1

What repos do you have in your sources file(s) in `/etc/apt/sources.list` and the folder `/etc/apt/sources.list.d/`

or use the following command to find all repos that are active:
`egrep -R ^deb /etc/apt/sources.list*`

**Comment by fmjensen** [comment]
Thank you for replying - i really apreciate that!

Your onliner command give this result:
```
/etc/apt/sources.list:deb http://deb.debian.org/debian/ buster main contrib non-free
/etc/apt/sources.list:deb-src http://deb.debian.org/debian/ buster main contrib non-free
/etc/apt/sources.list:deb http://security.debian.org/debian-security buster/updates main contrib non-free
/etc/apt/sources.list:deb-src http://security.debian.org/debian-security buster/updates main contrib non-free
/etc/apt/sources.list:deb http://deb.debian.org/debian/ buster-updates main contrib non-free
/etc/apt/sources.list:deb-src http://deb.debian.org/debian/ buster-updates main contrib non-free
/etc/apt/sources.list.d/nodesource.list:deb https://deb.nodesource.com/node_15.x buster main
/etc/apt/sources.list.d/nodesource.list:deb-src https://deb.nodesource.com/node_15.x buster main
```
I hope it's me that did something wrong - it's at fresh debian 10.8 net-install so i might be missing something!?

**Comment by h3o66** [comment]
I do not see there anything obvious there, maybe try to do a `apt update`  to refesh the cache and verify that you can find the missing packages.

**Comment by fmjensen** [comment]
> I do not see there anything obvious there, maybe try to do a `apt update` to refesh the cache and verify that you can find the missing packages.

I assure you I already did `apt update` several times. It have not changed anything. 

However as i mentioned above; I installed `lib32gcc1-amd64-cross` and `lib32stdc++6-amd64-cross` **and** after that `lib32gcc1` was not missing anymore - instead `libsdl2-2.0-0` was missing. I could install that manually as well as `steamcmd`... 

So now I _only_ lack `lib32stdc++6` !?!

**Comment by fmjensen** [comment]
This is a list of installed lib32 packages on my Debian 10.8:
```
root@[hostname]:~# apt list --installed | grep lib32

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

lib32gcc1-amd64-cross/stable,now 1:8.3.0-2cross1 all [installed]
lib32stdc++6-amd64-cross/stable,now 8.3.0-2cross1 all [installed]
root@[hostname]:~#
```

**Comment by fmjensen** [comment]
I may have fooled myself and installed the i386 version of Debian 10.8... ( facepalm )
I will investigate as soon as possible.

**Comment by fmjensen** [comment]
```
root@[hostname]:~$ dpkg --print-architecture
i386
root@[hostname]:~$
```
Oh my... I did fool myself and installed the wrong old i386 architecture - geeez 
I am sorry for bothering you all.
Will reinstall and start from scratch on the Valheim server install.

**Comment by h3o66** [comment]
closing issue with with the last comment
