### ISSUE TITLE
[BUG] './vhserver pd' posts password in plaintext

### ISSUE THREAD

**Issue by derekslenk** [GameServerManagers/LinuxGSM#3286]
## User Story

As a VHServer, I expect to be able to run './vhserver pd' and see the server details on termbin without the password in the launch command exposed

## Basic info

* **Distro:** [Ubuntu 20.04.2]
* **Game:** [Valheim]
* **Command:** [pd]
* **LinuxGSM version:** [v21.1.3]

## Further Information

I have my server up and running and just wanted to see what pd gave me, and noticed that in the command-line output that the password was listed:

```
Command-line` Parameters
=================================
 ./valheim_server.x86_64 -name 'Chums UP!' -password cleartextpass -port 2456 -world DextersLab -public 1
```

## To Reproduce

Steps to reproduce the behaviour:
1. Start vhserver: ./vhserver start
2. ./vhserver pd
3. Output on termbin contains passwords

## Expected behaviour
I would expect my password to be masked since the menu option says that passwords will be removed.

**Comment by dgibbs64** [comment]
looks like its specifically the start parameters that are the issue.

**Comment by derekslenk** [comment]
I can provide my real world example if needed, I would just rather not post it directly in the issue.

**Comment by dgibbs64** [comment]
It should be OK without it. We can test this one. Thank you for reporting it 👍
