### ISSUE TITLE
[FEATURE] Add an option to use a reverse proxied Telegram API server

### ISSUE THREAD

**Issue by RuioWolf** [GameServerManagers/LinuxGSM#3290]
## User Story

One year ago I submit #2805 about using a proxy string for `curlcustomstring`. But the fact is in some area, most IDC will check whether your server is running proxy software to bypass the firewall. While running a socks5 proxy will be extremely easy to be spotted, it's much more reliable to run a reverse proxied Telegram API server somewhere else.

## Basic info

* **Distro:** [CentOS 7]
* **Game:** [General]
* **Command:** [Alert]
* **LinuxGSM version:** [v20.1.3]

## Further Information

Add an option for user to choose between official Telegram API and their own Telegram API by hosting a reverse proxy server. 
It's now #3228.

## Further Reading

Install a Nginx server outside the firewall and issue a CA for it (domain name is required), mostly _let's encrypt_. Then start a server on `:443`, the configure file may be like:

```
upstream api {
    server api.telegram.org:443; # Do NOT forget :443 because it's HTTPS
}

server {
    listen 443 ssl;
    # Things you need to config a https server here, like your CA

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        client_max_body_size 256M;
        proxy_pass https://api;
    }
}
```

**Comment by dgibbs64** [comment]
linked thank you
