### ISSUE TITLE
[FEATURE] Microsoft 365 Alert

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#3293]
## User Story

As a develop, I want to investigate if MS 360 can receive alerts so that a new alert platform is available.

## Basic info

* **Command:** Alert

## Further Information

It looks like Microsoft 365 can support webhooks. It may be worth looking at seeing if support can be added

**Comment by h3o66** [comment]
I think this could be implemented, that we can create a alert for Teams:
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#post-a-message-to-the-webhook-using-curl

**Comment by dgibbs64** [comment]
It is possible to setup webhooks on teams (I have done this for zabbix). however only the business version of teams is possible. I dont think there is enough demand for this currently.
