### ISSUE TITLE
[BUG] GSLT token does not work with custom startparameters

### ISSUE THREAD

**Issue by plieblang** [GameServerManagers/LinuxGSM#3303]
## User Story

As a server owner, I want to be able to use the GSLT token set in servername.cfg along with custom `startparameters` so that I don't have to reset it in common.cfg.

## Basic info

* **Distro:** [Ubuntu 20.10]
* **Game:** [Insurgency]
* **Command:** [None]
* **LinuxGSM version:** [v21.1.3]

## Further Information

When setting up an Insurgency server, the GSLT token is put in insserver.cfg. If I create custom `startparameters` in common.cfg, this token isn't used. To get it to work, I have to create a duplicate `gslt` variable in common.cfg.

## To Reproduce

Steps to reproduce the behaviour:
1. Override the `startparameters` variable in common.cfg
2. Run `./insserver details`
3. See that the GSLT token is missing from the listed launch parameters

## Expected behaviour
The GSLT token set during initial setup should continue to work.

**Comment by h3o66** [comment]
I am not sure if you mean here `Insurgency` or `Insurgency: Sandstorm` can you please clarify ?

**Comment by plieblang** [comment]
Insurgency 2014, not Sandstorm.

**Comment by h3o66** [comment]
Currently this does not work, as the new parameter system is not designed that the startparameters is again inited after it is manually set in a config.

In this special case every variable that is needed in the config needs to be written before the startparameters variable.
