### ISSUE TITLE
[FEATURE] "call executable" alert

### ISSUE THREAD

**Issue by ToeiRei** [GameServerManagers/LinuxGSM#3305]
***Please use the template below, deleting the above text***

## User Story

As a server admin, I want to use some different notification systems that are not supported or run custom commands if things happen.

## Basic info

Distro: Debian 10
Game: ARK Survival Evolved
Command: alert / test-alert
LinuxGSM version: to be determined

## Further Information

We have the ability to fire webhooks or alert on discord. Wouldn't be hard to fire up any executable a user wants to - could be any script with curl or anything else with a few parameters.

## Further Reading

https://tldp.org/LDP/abs/html/

**Comment by dgibbs64** [comment]
there is an idea to support pre and post hooks. Also I would prefer to add support for specific alert platforms rather than generic triggering of an executable

**Comment by ToeiRei** [comment]
You cannot support all alert platforms - but a simple shell script can get you a long way.

As for alerting itself, there's https://github.com/caronc/apprise to speak to most of them which is what I use.

**Comment by dgibbs64** [comment]
Apprise support is a great option
