### ISSUE TITLE
Details Command Not Showing Accurate Backups Information

### ISSUE THREAD

**Issue by PoppaShell** [GameServerManagers/LinuxGSM#3307]
## User Story

When using the Details command, it gives a Section of Information titled "Backups". Under this Section, I am seeing inaccurate information for "Latest Backup" as far as the date and file specified.

## Basic info

* **Distro:** [Ubuntu 20.04.2 LTS]
* **Game:** [Valheim]
* **Command:** [Details]
* **LinuxGSM version:** [v21.1.3]

## Further Information

As can be seen in my attached screenshot, it shows the following:

Backups
=================================
No. of backups:  4
Latest backup:
    date:        Thu 25 Feb 2021 04:04:07 PM UTC (1 day ago)
    file:        /home/vhserver/lgsm/backup/vhserver-2021-02-25-160202.tar.gz
    size:        785M

But if you look at the output from an LS on the backups directory, you can see the following backups, which is more recent than what shows above.

vhserver-2021-02-25-160202.tar.gz
vhserver-2021-02-26-000201.tar.gz
vhserver-2021-02-26-080202.tar.gz
vhserver-2021-02-26-160201.tar.gz

## To Reproduce

Steps to reproduce the behaviour:
1. Run "./vhserver details" from the game server directory
2. Observe the "Latest backup" date & file details under the "Backups" section
3. Run "ls /home/vhserver/lgsm/backup/"
4. Compare the latest backup file from the ls output and compare to the "Latest backup" information from the details command output

## Expected behaviour
The expected behaviour is for the "Latest backup" information from the details command to be accurate.

## Screenshot(s)
![image](https://user-images.githubusercontent.com/29165443/109344892-f8a30d80-7834-11eb-88ea-966ec3500a8a.png)

**Comment by IkeRoyle** [comment]
Can confirm this behavior. Just sat up a cronjob yesterday and just noticed it when checking if the Backup has been made correctly.

Distro: Ubuntu 18.04.4 LTS
Game: Valheim
LinuxGSM Version: v21.1.3

![image](https://user-images.githubusercontent.com/18269098/109362284-fec3d900-788a-11eb-915b-e896fc5853d2.png)

**Comment by nbgibson** [comment]
To chime in, this isn't limited to the details command as the backup command appears to use the same logic. 

It appears the date logic implementation might be assuming a hard coded 31 day month in its calculations. My reasoning being that a backup run today (3/1) shows the most recent previous backup (2/28) as being from 3 days prior. Also note that subsequent backups for today show the previous backup as being from the day before; despite said backup being from about 15 seconds ago, so something in the diff calculation is a bit funky.

**Comment by Xalorous** [comment]
Confirm.  I also see this behavior.

Server: Centos 7.9
Script name:   vhserver
LinuxGSM version:   v21.1.3

**Comment by h3o66** [comment]
This should be fine with the next release, as already noted in #3339 
This regressed in #3328 on the develop branch and should be fixed by #3348 in the end
