### ISSUE TITLE
Missing dependencies Python3, but python 36 installed GAME:Valheim

### ISSUE THREAD

**Issue by molar131** [GameServerManagers/LinuxGSM#3312]
i was able to install the gameserver and it runs without issue for the most part.  I had a friend that would spawn entire buildings with a mod and it would sometimes crash the server, cpu spike and server would go offline.  i would restart it, no big deal.,  but if i was sleepting etc no one could play, so i setup a cronjob to run every 30 mins to run the monitor command.  But whenever it needed to start gameserver, it complains that python3 is missing, prompting for a sudo password even though it is installed.  i could extend the sudo timeout, in theory.

* **Distro:** [Red Hat Enterprise Linux 8.3 (Ootpa)]
* **Game:** [Valheim]
* **Command:** [start/stop/monitor/restart]
* **LinuxGSM version:** [v21.1.3]

Example of output from console
```
[vhserver]$ ./vhserver stop
Warning! Missing dependencies: python3
Information! Automatically installing missing dependencies.
Last metadata expiration check: 2:21:39 ago on Sun 28 Feb 2021 02:24:15 AM UTC.
Package python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 is already installed.
Dependencies resolved.
Nothing to do.

```

-If i do a "python3 --version", it informs me that it is python 3.6.8.
-i did an "alternatives --config python", and set the default to 3.6, same result when running any gameserver commands
-If i do an "rpm -q python3" it says it is not installed
-if i do an "rpm -q python36" it gives me the correct module, "python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64"

Any assistance is appreciated.

**Comment by Xalorous** [comment]
[vhserver@sv-valheim ~]$ cat /etc/centos-release
    CentOS Linux release 7.9.2009 (Core)
    [vhserver@sv-valheim ~]$ python --version
    Python 2.7.5
    [vhserver@sv-valheim ~]$ python3 --version
    Python 3.6.8
    [vhserver@sv-valheim ~]$ rpm -q python3
    python3-3.6.8-18.el7.x86_64
    [vhserver@sv-valheim ~]$ rpm -q python36
    package python36 is not installed

My recommendation is `yum reinstall python3`.  OR `yum uninstall python3` followed by `yum install python3`, BUT this will likely uninstall a bunch of packages dependent upon python3.

You've run into a problem that is so pervasive in the python world that there are packages designed to let you bundle python environments and switch between them.  Anaconda, pip, etc.

Another suggestion, if you're not using a dedicated server or vm to run your gameserver, I recommend you do so.  If you have only one choice of machine, then definitely look into pip to create a separate virtual environment for your gameserver, running the python it needs.

**Comment by Xalorous** [comment]
This is not a bug, this is a user support issue.

**Comment by molar131** [comment]
> ```
> [vhserver@sv-valheim ~]$ cat /etc/centos-release
> CentOS Linux release 7.9.2009 (Core)
> [vhserver@sv-valheim ~]$ python --version
> Python 2.7.5
> [vhserver@sv-valheim ~]$ python3 --version
> Python 3.6.8
> [vhserver@sv-valheim ~]$ rpm -q python3
> python3-3.6.8-18.el7.x86_64
> [vhserver@sv-valheim ~]$ rpm -q python36
> package python36 is not installed
> ```
> 
> My recommendation is `yum reinstall python3`. OR `yum uninstall python3` followed by `yum install python3`, BUT this will likely uninstall a bunch of packages dependent upon python3.
> 
> You've run into a problem that is so pervasive in the python world that there are packages designed to let you bundle python environments and switch between them. Anaconda, pip, etc.
> 
> Another suggestion, if you're not using a dedicated server or vm to run your gameserver, I recommend you do so. If you have only one choice of machine, then definitely look into pip to create a separate virtual environment for your gameserver, running the python it needs.

Thank you for the response.  So just to set the table here is the output before running your recommendations, reminder this is RedHat, not CentOS

```
[vhserver@rhel-vhser ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)
[vhserver@rhel-vhser ~]$ python --version
Python 3.6.8
[vhserver@rhel-vhser ~]$ python3 --version
Python 3.6.8
[vhserver@rhel-vhser ~]$ rpm -q python3
package python3 is not installed
[vhserver@rhel-vhser ~]$ rpm -q python36
python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64

```
I have performed all your yum recommendations, here is the output now

```
[vhserver@rhel-vhser ~]$ sudo yum reinstall python3
Last metadata expiration check: 1 day, 23:56:05 ago on Mon 01 Mar 2021 02:53:34 PM UTC.
Dependencies resolved.
=============================================================================================================================================================
 Package                   Architecture            Version                                                 Repository                                   Size
=============================================================================================================================================================
Reinstalling:
 python36                  x86_64                  3.6.8-2.module+el8.1.0+3334+5cb623d7                    rhel-8-appstream-rhui-rpms                   19 k

Transaction Summary
=============================================================================================================================================================

Total download size: 19 k
Installed size: 13 k
Is this ok [y/N]: y
Downloading Packages:
python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64.rpm                                                                     184 kB/s |  19 kB     00:00
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                         90 kB/s |  19 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                     1/1
  Reinstalling     : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                1/2
  Running scriptlet: python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                1/2
  Cleanup          : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                2/2
  Running scriptlet: python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                2/2
  Verifying        : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                1/2
  Verifying        : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                2/2

Reinstalled:
  python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64

Complete!
[vhserver@rhel-vhser ~]$ python --version
Python 3.6.8
[vhserver@rhel-vhser ~]$ python3 --version
Python 3.6.8
[vhserver@rhel-vhser ~]$ rpm -q python3
package python3 is not installed
[vhserver@rhel-vhser ~]$ rpm -q python36
python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64
```

**Comment by Xalorous** [comment]
Centos is RHEL rebranded.

The discrepancy seems to be with rpm not seeing python3. This could have to
do with the difference between RHEL 7 and 8. I haven't checked how the
scripts determine whether python is there.

**Comment by molar131** [comment]
I am aware that CentOS is RHEL rebranded.  I originally was how RHEL 8 is dealing with RPM, which i had pointed out in my original post.

**Comment by h3o66** [comment]
Could you attach here a debug log for me to check ?

Howto:
enabled debug mode
`./vhserver dev`

execute the command that has a problem (in your case where the dependency is checked)
`./vhserver stop`

upload the log `dev-debug.log`

disable dev debug:
`./vhserver dev`

**Comment by Cenarkion** [comment]
For what its worth, I ran into the same minor issue, running redhat 8.4.
${distroversion} in info_distro.sh is pulling "8.4" as the distroversion from os-release

`VERSION_ID="8.4"`

Thus the further deps check in check_deps.sh is not picking up the suitable package array.  A dirty edit to check for distroversion 8.4 in the fn_deps_biuld_redhat function resolves the issue of course, for the short term

`elif [ "${distroversion}" == "8.4" ]; then
                array_deps_required=( epel-release curl wget util-linux python36 file tar gzip bzip2 unzip binutils bc jq tmux nmap-ncat cpio )`

**Comment by dgibbs64** [comment]
Dependency checking needs a refactor to be able to manage these sorts of issues

**Comment by litecactus** [comment]
Having the same issue on Rocky 8.4 
`Warning! Missing dependencies: python3` on `./vhserver st`

`[vhserver@localhost ~]$ python3 --version
Python 3.6.8`

**Comment by k3mic** [comment]
Not sure this is just for Valheim. Having same issue with Rocky Linux 8.4 and Minecraft.

**Comment by Livius90** [comment]
In all of Red Hat 8 based distributions like CentOs 8, Oracle Linux 8, Rocky Linux 8 etc... the `python3` dependency checking is buggy. `rpm -q python3` terminal command can not show the real information about the installed `python3` package because this name is incomplete.

```console
[csgo_user@server csgo_linuxgsm]$ rpm -qa | grep python3*
python3-libdnf-0.55.0-7.0.1.el8.x86_64
python3-dnf-plugins-core-4.0.18-4.el8.noarch
python3-setuptools-39.2.0-6.el8.noarch
python3-firewall-0.8.2-7.0.1.el8_4.noarch
platform-python-3.6.8-37.0.1.el8.x86_64
python3-decorator-4.2.1-2.el8.noarch
python3-linux-procfs-0.6.3-1.el8.noarch
python3-pyyaml-3.12-12.el8.x86_64
python3-pyparsing-2.1.10-7.el8.noarch
python3-libselinux-2.9-5.el8.x86_64
python3-pip-wheel-9.0.3-19.el8.noarch
python3-hawkey-0.55.0-7.0.1.el8.x86_64
python3-libstoragemgmt-clibs-1.8.7-1.el8.x86_64
platform-python-setuptools-39.2.0-6.el8.noarch
python3-six-1.11.0-8.el8.noarch
python3-gobject-base-3.28.3-2.el8.x86_64
python3-gpg-1.13.1-7.el8.x86_64
python3-configobj-5.0.6-11.el8.noarch
python3-pyudev-0.21.0-7.el8.noarch
python3-urwid-1.3.1-4.el8.x86_64
python3-schedutils-0.6-6.el8.x86_64
python3-libcomps-0.1.11-5.el8.x86_64
python3-configshell-1.1.28-1.0.1.el8.noarch
python3-slip-0.6.4-11.el8.noarch
python3-setools-4.3.0-2.el8.x86_64
python3-audit-3.0-0.17.20191104git1c2f876.el8.x86_64
python3-policycoreutils-2.9-14.0.1.el8.noarch
platform-python-pip-9.0.3-19.el8.noarch
python3-pip-9.0.3-19.el8.noarch
python3-perf-4.18.0-305.12.1.el8_4.x86_64
python3-rpm-4.14.3-14.el8_4.x86_64
python3-setuptools-wheel-39.2.0-6.el8.noarch
python3-libstoragemgmt-1.8.7-1.el8.noarch
python3-dnf-4.4.2-11.el8.noarch
python3-libsemanage-2.9-6.el8.x86_64
policycoreutils-python-utils-2.9-14.0.1.el8.noarch
python36-3.6.8-2.0.1.module+el8.4.0+20103+1849b5f9.x86_64
python3-sssdconfig-2.4.0-9.0.1.el8_4.2.noarch
python3-libs-3.6.8-37.0.1.el8.x86_64
python3-dbus-1.2.4-15.el8.x86_64
python3-dateutil-2.6.1-6.el8.noarch
python3-kmod-0.9-20.el8.x86_64
python3-nftables-0.9.3-18.el8.x86_64
python3-slip-dbus-0.6.4-11.el8.noarch
python3-libxml2-2.9.7-9.0.2.el8_4.2.x86_64
```

For me only the following command can give a correct output but it is usable only if we looking for `python3.6` specificly, it is not good for universal solution. So please improve the `rpm -q` dependency checking, it is incorrect in all Red Hat Linuxes.

```console
[csgo_user@server csgo_linuxgsm]$ rpm -q python36
python36-3.6.8-2.0.1.module+el8.4.0+20103+1849b5f9.x86_64
```

**Comment by litecactus** [comment]
I don't really know anything about these things but can you just wham in a wildcard * in the dependency? lol

**Comment by k3mic** [comment]
> I don't really know anything about these things but can you just wham in a wildcard * in the dependency? lol

Probably possible, but there's likely more reliable checks out there. I would think something like `which python3` might be a bit more reliable than querying the rpm DB. In theory you could install python with something like pyenv and it wont add anything to RPM DB. The `which` command should still find it if it's in your `$PATH`. Might even be safe to use on all distros, not just EL8, assuming a which is installed...


Pyenv:

```
 ~  which python3
~/.pyenv/shims/python3
 ~  python3 -V
Python 3.7.11
 ~ 
```

EL8:
```
[root@server ~]# which python3 > /dev/null 2>&1 && echo python3-good || echo python3-bad
python3-good
[root@server ~]# cat /etc/redhat-release
Rocky Linux release 8.4 (Green Obsidian)
[root@server ~]#
```

Debian 10:
```
root@server:~# which python3 > /dev/null 2>&1 && echo python3-good || echo python3-bad
python3-good
root@server:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@server:~#
```

**Comment by Livius90** [comment]
> I don't really know anything about these things but can you just wham in a wildcard * in the dependency? lol

Unfortunately wildcard * is not working in this command.

```console
[csgo_user@server csgo_linuxgsm]$ rpm -q python3*
package python3* is not installed
```

**Comment by Livius90** [comment]
> ‘rpm -q python’ should list all packages starting with ‘python’

It is not show all package starting with python, it is show only one package which name is python, this is the problem. If you have an installed python  3.6 you need to query python36 if you have python 3.9 you need to use python39 and so on, python3 is an incomplite name to get the correct package cheking. the `which python3` should be a good dependency cheking but it will be useful only for python checking. Any other package will need other solutions.

**Comment by Xalorous** [comment]
>
> "It is not show all package starting with python, it is show only one
> package which name is python, this is the problem."


On rpm based systems, 'rpm -q foo' shows all installed packages with names
starting with the string python.  If you are looking for foo2 and it is
installed, it will show.  This is the way the rpm utility works.  Since
python36 is now the default python in RHEL 7 (and thus CentOS and Oracle --
and scientific linux if it's still around), if you look at the full name of
the installed python package, what version does it show?

If GSM needs python3, and only python is showing on 'which', cd to the
folder holding 'python' and type 'sudo ln -s python python3'.  Then
anything that calls python3 will get python (which is python 3.6
underneath).

**Comment by dgibbs64** [comment]
python36 will be the standard package on next release. Hopfully this will resolve it

**Comment by Xalorous** [comment]
Part of the issue seems to simply be the name is unconventional, or the
convention changed.  In the past python was python. Then they did python2
for all sub-versions. Now instead of python3, we get python36.

Perhaps checking for python36, and creating a symlink python3 pointing to
python36?

**Comment by dgibbs64** [comment]
linuxgsm checks against the package name so if the package name is python36 it will use that. So it should be OK in next release :)
