### ISSUE TITLE
[FEATURE] More Alerting Options for VHSERVER

### ISSUE THREAD

**Issue by PoppaShell** [GameServerManagers/LinuxGSM#3332]
## User Story

I would like to see more Alerting Options for pretty much anything that causes or needs a server restart. The only one I am seeing work at the moment is when "./vhserver update" is run and found an update was available and therefore restarts to apply it. And maybe some of these below requests are already a thing and I just haven't figured out how to configure them. If that is the case, my apologies.

## Basic info

* **Distro:** [Ubuntu 20.04.2 LTS]
* **Game:** [Valheim]
* **Command:** [Alerting]
* **LinuxGSM version:** [v20.1.3]

## Further Information

I have setup Alerting to push to Discord via the webhook. But I have noticed that the only Alert I am seeing is if the VHSERVER does an update from the cron job I have to hourly run "./vhserver update". I also have a cron job to run "./vhserver backup" every 8 hours. And since this of course shuts down, backup and restarts the server, it would be great to push an Alert to Discord that this is happening so my community doesn't have to guess at what is happening based on time of day. Additionally, it would be nice to pretty much Alert on anything that would cause the server to reboot. Whether that be a manual restart from "./vhserver restart", a restart from "./vhserver monitor" finding the server is not online and starts it back up, etc. And a big bonus would be, if we could set up Alerts giving a heads up when possible for scheduled things that cause a restart like Update, Backup, Update-LGSM, etc. What this would look like is "Alert: Server will restarting for backup in 15mins" and then the same Alert but for 5mins, & 3-2-1mins, for example. Same for schedule restarts. Hope that all makes sense.

**Comment by rconjoe** [comment]
[Monitoring] might be of assistance to you!

**Comment by PoppaShell** [comment]
@rconjoe Can you elaborate a little, please? The Monitor Command currently runs on a Cron every 5 mins to check server status and other details and will restart the server if it is stopped. Is there something I am missing about the Monitor command that could satisfy my request for additional Alert types to output to Discord?

**Comment by dgibbs64** [comment]
Basically, The feature already exists. 😃 
https://docs.linuxgsm.com/alerts

**Comment by dgibbs64** [comment]
There isnt a specific alert for backup and restart though so that might be a good addition

**Comment by PoppaShell** [comment]
@dgibbs64 Yeah, I read the docs and have the current basic alerting on. But if you read my request, I stated that. And that basically the only Alert that has fired to Discord is when Valheim gets an update. A LinusGSM update hasn't dropped since I have been using it until this latest drop. A Cron is set to run update-lgsm tonight, so we will see if that fires an Alert. But my addition requests for further Alerting enhancements still stand. So I am glad you reopened this and pointed out that at least the backup alert would be a decent idea.

**Comment by dgibbs64** [comment]
There isnt a specific alert for a LinuxGSM update as it doesn't restart the server. But again that might be a useful one to add just as an FYI. You will however get an alert if _default.cfg is updated

**Comment by PJGuyTen** [comment]
I created a custom alert function and use it to trigger alerts for backups.  I created a branch for it, but I get permission denied trying to push my branch.  Sorry if this is a noob question, but how do I gain permission?
`remote: Permission to GameServerManagers/LinuxGSM.git denied to PJGuyTen.
fatal: unable to access 'https://github.com/GameServerManagers/LinuxGSM.git/': The requested URL returned error: 403`

**Comment by PoppaShell** [comment]
@PJGuyTen You can't push a branch their master unless you are an approved member of their development team. You have to do a pull request, contribute your recommended changes/additions. Then when/if they approve of your work, they can choose to merge it into the master.

**Comment by PJGuyTen** [comment]
@PoppaShell ah ok, I had created my own branch and tried to push it that way `git push origin feature/custom-alerts` (this is how I do it at work).  I'll do it the way you suggested.  Thanks!

**Comment by PoppaShell** [comment]
@PJGuyTen Yeah. That totally makes sense for it to be that way for you at your work since you would have permissions to that development project. When you want to contribute to other people's development projects, you have to usually follow the method I specified.

**Comment by PJGuyTen** [comment]
@PoppaShell Thanks for the tip! TIL

**Comment by dgibbs64** [comment]
This issue isnt fully addressed in the alerts refactor but is mostly. The feature of giving several minutes warning is not yet done as it would require some planning and thought on how best to implament. However alerts should now trigger on any options that require a server reboot. 

If anything is missed please let me know on next release of LinuxGSM
