### ISSUE TITLE
[BUG]  Rust gamemode softcore

### ISSUE THREAD

**Issue by artnetflix** [GameServerManagers/LinuxGSM#3334]
## User Story
I try to enable Rust gamemode **softcore**. 

i added in my lgsm/config-lgsm/rustserver/rustserver.cfg:

`gamemode="softcore"`

But gamemode not working on start. I don't want to use the command "gamemode.set softcore" because after each server reboot the mode disappeared.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Rust]
* **Command:** [Monitor]
* **LinuxGSM version:** [v20.1.3]

## Further Information

It's surely not a bug but a misunderstanding on my part. But I don't see any reference to gamemodes in the documentation.
If anyone can help me, thank you very much.

**Comment by h3o66** [comment]
See connected PR, this was not implemented yet.
This will be added for the next release
