### ISSUE TITLE
[BUG] vhserver monitor kills functioning server that has peers connected

### ISSUE THREAD

**Issue by yuzupup** [GameServerManagers/LinuxGSM#3337]
## User Story
As a server administrator, I would like ./vhserver monitor to not kill my server when the server is in good health.

## Basic info

* **Distro:** Ubuntu 18.04.1 LTS
* **Game:** Valheim (build `6315977`)
* **Command:** `./vhserver monitor`
* **LinuxGSM version:** Valheim v21.1.3

## Further Information

I regularly run ./vhserver monitor (every 10 minutes).

As of SteamCMD build `6315977`, it seems to be killing my server while peers are connected. The query on port 2457 fails after the normal retry period with the following message:

```
[  OK  ] Monitoring vhserver: Checking session: OK
[ FAIL ] Monitoring vhserver: Querying port: gsquery: 192.168.86.50:2457 : 60/5: FAIL
[  OK  ] Stopping vhserver: Graceful: CTRL+c: 8: OK
[  OK  ] Starting vhserver: Valheim Server
```

## To Reproduce

Steps to reproduce the behaviour:
1) Start a server.
2) Have at least one peer connect.
3) Run ./vhserver monitor until the query is no longer delayed.
4) Observe that it terminates the server.

## Expected behaviour
monitor does not kill a server with peers connected.

**Comment by yuzupup** [comment]
I am curious if 2457 is the port that should be checked after the update. I had peers connecting via port 2456, and they were unable to connect. Not specifying the port let them connect.

**Comment by sebastianus78** [comment]
Same issue
Ubuntu 18.04
LinuxGSM version: v21.1.3
* Local build: 6315977

udp     1536      0 0.0.0.0:2457            0.0.0.0:*                           26190/./valheim_ser

after delay monitoring on 0.0.0.0:2457 fails, server restarts.
removing the monitoring from crontab seems to be the easiest workarround

**Comment by dgibbs64** [comment]
Recent Valheim update has broken query monitor. You can disable query in the LinuxGSM settings.

**Comment by dgibbs64** [comment]
Previous release
```
tcp        0      0 178.79.168.193:35253    155.133.248.38:27039    ESTABLISHED 671/./valheim_serve
udp        0      0 0.0.0.0:2457            0.0.0.0:*                           671/./valheim_serve
```
```gsquery Raw Output
=================================

./query_gsquery.py -a "178.79.168.193" -p "2457" -e "protocol-valve"

OK: b'\xff\xff\xff\xffI\x11LinuxGSM - Debian 10 Test Server\x00LinuxGSM - Debian 10 Test Serve\x00valheim\x00\x00\x00\x00\x00@\x00dl\x01\x001.0.0.0\x00\xb1\x98\t\x0b\xa04\x18\xd0@@\x010.145.6\x00*\xa0\r\x00\x00\x00\x00\x00'
```

new release
```
tcp        0      0 139.162.210.57:51007    162.254.196.67:27035    ESTABLISHED 407404/./valheim_se
udp        0      0 0.0.0.0:2457            0.0.0.0:*                           407404/./valheim_se
udp6       0      0 :::2456                 :::*                                407404/./valheim_se
```
```
gsquery Raw Output
=================================

./query_gsquery.py -a "139.162.210.57" -p "2457" -e "protocol-valve"

ERROR: Unable to receive
```

**Comment by dgibbs64** [comment]
Tested further it appears to work. But maybe its taking a longer time to get started on boot. I will extend the query delay

**Comment by jmechnich** [comment]
I am experiencing the same issue on Debian Testing since a reboot a few days ago. I have just noticed that I am using `gsquery` in contrast to `gamedig`, so this might be the underlying cause. Can someone confirm this ?

**Comment by dgibbs64** [comment]
@jmechnich its worth trying with just gsquery and just gamedig to see if that is the issue. They are both querying in the same manner so unsure why this would be an issue

**Comment by Gibbo3771** [comment]
> Recent Valheim update has broken query monitor. You can disable query in the LinuxGSM settings.

@dgibbs64 How? I have no line to disable and docs don't specify any line to add.

My server is dying whenever gamedig fails to query.

**Comment by sebastianus78** [comment]
public="0" causes monitoring gsquery to fail.
public="1" works with qsquery

**Comment by h3o66** [comment]
this should be fixed with the connected PR, feel free to test it.
