### ISSUE TITLE
[kf2server] Server Reqest

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#334]
KF2 is coming out soon. I will be writing this soon hopefully it will be ready for release.

**Comment by jargon-au** [comment]
Any update on this Daniel? :)

**Comment by dgibbs64** [comment]
No linux binaries yet. However Tripwire have promised it will happen soon.

https://steamdb.info/app/232130/depots/

**Comment by dgibbs64** [comment]
Still no Linux support BOOO!!!!

**Comment by HenrySlawniak** [comment]
I was hoping this new patch would come along with Linux support, but no :frowning:

**Comment by dgibbs64** [comment]
Closing for now. However will re-open if tripwire ever get there arse in gear. :P

**Comment by MitchDizzle** [comment]
It's 2017 now, I'm not sure how the Killing Floor 2 servers were back then however there are Linux servers now. At least according to this guide: http://wiki.tripwireinteractive.com/index.php?title=Dedicated_Server_(KillingFloor)#Linux

**Comment by smounives** [comment]
https://wiki.tripwireinteractive.com/index.php?title=Dedicated_Server_(Killing_Floor_2)#Linux

**Comment by dgibbs64** [comment]
see #1316
