### ISSUE TITLE
Update Request - ET:Legacy 2.77

### ISSUE THREAD

**Issue by jobhh** [GameServerManagers/LinuxGSM#3347]
Last week [ET:Legacy 2.77](https://www.etlegacy.com/blog/et-legacy-277-released) was released. If someone has the time it would be nice if the LinuxGSM image could be updated.

[Here](https://www.etlegacy.com/download) you'll find the download page with the [ET:Legacy 2.77 Linux 32-bit binaries](https://www.etlegacy.com/download/file/236) with md5sum `c219df200efbfc5c5e9dcfce929dfee1`.

Sidenote: Currently the local filename in `install_server_files.sh` is named `2.75`, but it does download `2.76`:

	elif [ "${shortname}" == "etl" ]; then
		remote_fileurl="http://linuxgsm.download/WolfensteinEnemyTerritory/etlegacy-v2.76-i386-et-260b.tar.xz"; local_filedir="${tmpdir}"; local_filename="etlegacy-v2.75-i386-et-260b.tar.bz2"; chmodx="nochmodx" run="norun"; force="noforce"; md5="178a00233cec1e25b69d130107ce1a79"

**Comment by h3o66** [comment]
I would also go that far to replace the 32bit with the 64bit build, if that is not a problem with the mods in the end.

**Comment by jobhh** [comment]
> 
> 
> I would also go that far to replace the 32bit with the 64bit build, if that is not a problem with the mods in the end.

Using the 64bit version might not be the best option. There is big warning regarding that version on the download page ;)

![image](https://user-images.githubusercontent.com/2331451/110241747-ac517f00-7f52-11eb-8796-770015b25751.png)

**Comment by dgibbs64** [comment]
Another question. If I remember correctly et legacy can auto-update itself to the latest version. Is this the case? I will of course update the archive but if correct that would mean that it wouldn't be urgent to update the archive. I have a release due very soon and if it auto-updates I will wait until next release rather than delay the current release further.

**Comment by jobhh** [comment]
The server does not seem to auto-update. I've attempted this by restarting and by reinstalling the server, but the version mismatch remains in both cases with my 2.77 client.

**Comment by jobhh** [comment]
The 2.77.1 hotfix was released just after this was merged. Should I create a new issue?
