### ISSUE TITLE
[Server Request] Survive The Nights

### ISSUE THREAD

**Issue by kbenthin** [GameServerManagers/LinuxGSM#3354]
## What game server would you like adding?

[Survive The Nights]

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [ X ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[541300]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [ X ] Yes
* [ ] No

![xczc](https://user-images.githubusercontent.com/69800617/110745648-ddc09800-823b-11eb-990b-f3d61fa6edfe.PNG)

**Comment by h3o66** [comment]
The server is not released yet.
This is only the steamid for the game, not the seperate gameserver
