### ISSUE TITLE
[Server Request] Crewlink server for AmongUs

### ISSUE THREAD

**Issue by pirpyn** [GameServerManagers/LinuxGSM#3356]
## What game server would you like adding?

[Crewlink] audio server for Among Us

## Can you link to any tutorials or guides?

Using docker, realy easy to deploy.

https://github.com/ottomated/CrewLink-server#docker-quickstart

The given command should have the -e ADDRESS=xxx.xxx.xxx.xxx option added to start.
## Is the server on Steam?

* [ ] Yes
* [x] No

## Is the server supported on Linux?

* [x] Yes
* [ ] No

**Comment by dgibbs64** [comment]
Project not updated in 3 years and uses docker container. not a good fit for LinuxGSM. closing issue.
