### ISSUE TITLE
Arma3 Glibc requirement increased to 2.27

### ISSUE THREAD

**Issue by synexTG** [GameServerManagers/LinuxGSM#3362]
arma@%:~$ ./arma3server start
[  OK  ] Starting arma3server: Applying 20150 Segmentation fault (core dumped) fix: ARMA 3
[ .... ] Starting arma3server: LinuxGSMno server running on /tmp/tmux-1010/default
[ FAIL ] Starting arma3server: Unable to start LinuxGSM

- Before this i had a problem with tmux and locale settings (after that i installed all locales and this error happens).
- Debug command or anything like that didn't helped.

I can send logs from any command you write here, thanks for any help.

**Comment by h3o66** [comment]
Any more details like what system and settings do you have ?

**Comment by synexTG** [comment]
I am using  Debian 9 and followed the instructions on the linuxgsm website for Arma 3. After the installation i started the server and got an error that tmux needs a specific locale (UTF 8 en_US i think). I googled the error and tried to fix it with following command: `apt install locales-all`

After the installation of all locales the error changed to:
```
[ OK ] Starting arma3server: Applying 20150 Segmentation fault (core dumped) fix: ARMA 3
[ .... ] Starting arma3server: LinuxGSMno server running on /tmp/tmux-1010/default
[ FAIL ] Starting arma3server: Unable to start LinuxGSM
```

**Comment by h3o66** [comment]
can you please upload logs from `log/console/` and as well if there are any special game logs from arma ?

**Comment by synexTG** [comment]
All console logs are completely empty and the script logs are showing my start tries and the installation. I mean i would reinstall all but i tried it once and the error didn't disappears.
[logs.zip](https://github.com/GameServerManagers/LinuxGSM/files/6140942/logs.zip)

**Comment by dgibbs64** [comment]
I think its related to how tmux handles `"`.

**Comment by dgibbs64** [comment]
this change in the latests release might help https://github.com/GameServerManagers/LinuxGSM/commit/3d396049a650069fa332611b92148618c610451c

**Comment by synexTG** [comment]
I deleted all files and redownloaded the script the error keep existing. I attached the current logs. The command_start.sh function is the updated one (also attached)
[log.zip](https://github.com/GameServerManagers/LinuxGSM/files/6142066/log.zip)
[command_start.zip](https://github.com/GameServerManagers/LinuxGSM/files/6142075/command_start.zip)

**Comment by dgibbs64** [comment]
I have added a temporary commit to master branch until I can get home. Please run `./arma3server update-lgsm` and let me know if that helps

**Comment by synexTG** [comment]
It updated the start function but nothing changed.
```
arma@blu1244:~$ ./arma3server update-lgsm
[  OK  ] Updating LinuxGSM arma3server: Selecting repo: GitHub
checking GitHub linuxgsm.sh...OK
checking arma3server...OK
checking GitHub config _default.cfg...OK
checking GitHub module check_config.sh...OK
checking GitHub module check_deps.sh...OK
checking GitHub module check_executable.sh...OK
checking GitHub module check_glibc.sh...OK
checking GitHub module check_ip.sh...OK
checking GitHub module check_logs.sh...OK
checking GitHub module check_permissions.sh...OK
checking GitHub module check_root.sh...OK
checking GitHub module check.sh...OK
checking GitHub module check_status.sh...OK
checking GitHub module check_steamcmd.sh...OK
checking GitHub module check_system_dir.sh...OK
checking GitHub module check_system_requirements.sh...OK
checking GitHub module check_tmuxception.sh...OK
checking GitHub module check_version.sh...OK
checking GitHub module command_install.sh...OK
checking GitHub module command_start.sh...UPDATE
checking GitHub module command_update_linuxgsm.sh...OK
checking GitHub module core_dl.sh...OK
checking GitHub module core_exit.sh...OK
checking GitHub module core_functions.sh...OK
checking GitHub module core_getopt.sh...OK
checking GitHub module core_legacy.sh...OK
checking GitHub module core_logs.sh...OK
checking GitHub module core_messages.sh...OK
checking GitHub module core_steamcmd.sh...OK
checking GitHub module core_trap.sh...OK
checking GitHub module fix_arma3.sh...OK
checking GitHub module fix.sh...OK
checking GitHub module fix_steamcmd.sh...OK
checking GitHub module info_config.sh...OK
checking GitHub module info_distro.sh...OK
checking GitHub module info_parms.sh...OK
checking GitHub module install_complete.sh...OK
checking GitHub module install_config.sh...OK
checking GitHub module install_header.sh...OK
checking GitHub module install_logs.sh...OK
checking GitHub module install_server_dir.sh...OK
checking GitHub module install_server_files.sh...OK
checking GitHub module install_stats.sh...OK
checking GitHub module install_steamcmd.sh...OK
[  OK  ] Updating LinuxGSM arma3server: Updating functions
arma@blu1244:~$ ./arma3server start
[  OK  ] Starting arma3server: Applying 20150 Segmentation fault (core dumped) fix: ARMA 3
[ .... ] Starting arma3server: LinuxGSMno server running on /tmp/tmux-1010/default
[ FAIL ] Starting arma3server: Unable to start LinuxGSM
arma@blu1244:~$
```

**Comment by dgibbs64** [comment]
hotfix 2.2.2 has been released. Please let me know if that helps

**Comment by synexTG** [comment]
Nothing changed i deleted all and redid the installation process, the logs: [log.zip](https://github.com/GameServerManagers/LinuxGSM/files/6147804/log.zip)

**Comment by dgibbs64** [comment]
Just installed arma 3 and found this issue.
```
./arma3server_x64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./arma3server_x64)
```

Looks like the glibc requirement for Arma 3 has increased to 2.27. I will adjust the requirements. You will need Debian 10 or higher now https://docs.linuxgsm.com/requirements/glibc

**Comment by synexTG** [comment]
Thanks 👍🏼
