### ISSUE TITLE
[BUG] Valheim server, password quotes being escaped to the password value

### ISSUE THREAD

**Issue by 4s3ti** [GameServerManagers/LinuxGSM#3367]
## User Story

After installing and starting vhserver, getting invalid password while joining the gameserver

## Basic info

* **Distro:** [Debian 10]
* **Game:** [Valheim]
* **Command:** [start]
* **LinuxGSM version:** [v21.2.0]

## Further Information

Latest linuxgsm update introduced bug on valheim server start parameters, as quotes are being escaped to the command itself making them part of the password and servername itself!

If a password is for example 123456 to join a server one would need to do "123456" as password input inside the game. 

Believe this is the commit introducing the bug: https://github.com/GameServerManagers/LinuxGSM/commit/8db3b6d48740817eec2c337f6e579c9064ec9e74

## To Reproduce

Steps to reproduce the behaviour:
1. Install vhserver
2. set server password on `$HOME/lgsm/config-lgsm/vhserver/vhserver.cfg` as per documentation
```
vhserver@vh-test0:~/lgsm/config-lgsm/vhserver$ cat vhserver.cfg 
##################################
####### Instance Settings ########
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance.
serverpassword="123456"
```
## Expected behaviour

Password to join the game should be the exat value: `examplepassword` and not `"examplepassword"`

## Further testing

By tested removing the quotes from `vhserver.cfg`, stoped and started the server again, and it has no effect. 

## Follow up questions

How come this was not detected before release? 
Is there anything i can do to help this things from happening? 
(I haven't really searched for this one) Is there any way to lock to a specific version of lgsm?

**Comment by UltimateByte** [comment]
Proper fix is to single quote the variable, not the call to the variable.
Quoted commit shall be reverse, and config file should be updated with single quotes.

**Comment by dgibbs64** [comment]
This is going to be a hotfix
