### ISSUE TITLE
[BUG] teamspeak3 installation - linuxgsm Failure! Unable to get remote build

### ISSUE THREAD

**Issue by philf90** [GameServerManagers/LinuxGSM#3368]
Actually I am provisioning a new root server to migrate from an old one. In that case I want to install a teamspeak 3 instance via LGSM to bring it up again quickly.

## Basic info

* **Distro:** Ubuntu 20.04 LTS
* **Game:** teamspeak3
* **Command:** install
* **LinuxGSM version:** v21.2.0

## Further Information

The "./ts3server install" command works properly until it hits the point "Installing TeamSpeak 3 Server". It interupts/aborts with the error "linuxgsm Failure! Unable to get remote build". But the error is only show for about a second. The teamspeak 3 server will not get installed. The "serverfiles" directory stays empty. At the moment there is no option to install teamspeak 3 via LGSM.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to https://linuxgsm.com/lgsm/ts3server/ and follow the instructions
2. Open SSH connection to the designated server
3. Run "sudo dpkg --add-architecture i386; sudo apt update; sudo apt install curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux netcat lib32gcc1 lib32stdc++6 libmariadb3"
4. Run "adduser ts3server"
5. Run "su - ts3server"
6. Run "wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh ts3server"
7. Run "./ts3server install"

## Expected behaviour

By following the instructions and given commands the teamspeak 3 instance should be installed properly. 

//short off topic
Sorry for maybe bad "german english"

**Comment by philf90** [comment]
![error](https://user-images.githubusercontent.com/35610275/111074543-b0961300-84e3-11eb-8693-6bf20c9ed446.png)

**Comment by Jacob-Steentoft** [comment]
I'm having the same issue on "Debian GNU/Linux 10 (buster)". Tried to setup a new instance to migrate an old server using the same steps as above.
The install script ends with: "Failure! Unable to get remote build" as well.

**Comment by UltimateByte** [comment]
Most likely, TeamSpeak changed their repositories names again, and script has to be updated.

**Comment by h3o66** [comment]
> Most likely, TeamSpeak changed their repositories names again, and script has to be updated.

afaik no, this is a regression

**Comment by dgibbs64** [comment]
😐 I thought we picked up all the regressions.

**Comment by h3o66** [comment]
The connected Pr should fix it, but if you apply it, dont update lgsm till the fix is out
