### ISSUE TITLE
[BUG] Rust hostname & description are only sending 1 word

### ISSUE THREAD

**Issue by wrecktify** [GameServerManagers/LinuxGSM#3372]
## Basic info

* **Distro:** CentOS 7
* **Game:** Rust
* **Command:** ./rustserver start
* **LinuxGSM version:** v21.2.0

## Further Information

Fresh install of rust on a brand new dedicated server.  During startup, only the first word of hostname & description are being passed to the server.  I copied an older version of lgsm from my other Centos 7 server and it resolved the problem by rolling back to an older version.

## To Reproduce

Steps to reproduce the behaviour:
1. Install rust server
2. Set hostname or description to multiple words with spaces
3. Checked server console after server start and both hostname & description only contain the first word of whatever is in "" quotes.

## Expected behaviour
normal hostname & description like the old version.

**Comment by dgibbs64** [comment]
Hotfix has been released that should resolve this issue
