### ISSUE TITLE
[BUG] javaram doesn't allocate extra RAM with PaperMC

### ISSUE THREAD

**Issue by LazZer-** [GameServerManagers/LinuxGSM#3373]
## User Story

I was trying to assign more RAM to the PaperMC than the default 1GB but the javaram option in the config didn't do the trick.

## Basic info

* **Distro:** Lubuntu 20.04.2 LTS
* **Game:** PaperMC - Minecraft
* **Command:** javaram
* **LinuxGSM version:** v21.2.0

## Further Information

Cannot allocate more RAM than the default with the command that should be responsible for it (javaram).

## To Reproduce

Steps to reproduce the behaviour:
1. set javaram to something else than default in either common.cfg or in the instance's cfg
2. launch server
3. javaram did nothing :c

## Expected behaviour

Being able to allocate more than a gig of RAM.

**Comment by h3o66** [comment]
Regression from #3315

**Comment by JoniLieh** [comment]
Did you found a workaround? 
My workaround would be: using the normal Minecraft Java Version and swapping the `.jars`

**Comment by JoniLieh** [comment]
@h3o66 Guess DanGibbs will announce it on the discord when it's merged (?) :)
