### ISSUE TITLE
[BUG] Start Script tmux Syntax Error - Centos 7

### ISSUE THREAD

**Issue by CoryBarney** [GameServerManagers/LinuxGSM#3375]
## User Story

Essentially upon install of a fresh Valheim server (I haven't tried anything else recently) on Centos 7 I was met with a error on launch coming in the form of a tmux syntax error. I have found a couple fixes but all require manual intervention (Error):

```bash
[ FAIL ] Starting vhserver: Unable to start Valheim Server
[ FAIL ] Starting vhserver: Unable to start Valheim Server: tmux error:
```

## Basic info

* **Distro:** [Centos 7 Core]
* **Game:** [Valheim]
* **Command:** [Start]
* **LinuxGSM version:** [v21.2.1]

## Further Information

Upon a fresh install while setting up a test server and a ansible script to deploy it among other things at the end of troubleshooting and tweaking my scripts I was was left with the installed valhiem server on a fresh Centos 7 install.
I went to run start before going any further in setting up cron jobs or anything like that and was left with an error on start:

```bash
[valheim@****** ~]$ ./vhserver start
[ FAIL ] Starting vhserver: Unable to start Valheim Server
[ FAIL ] Starting vhserver: Unable to start Valheim Server: tmux error:

Command
=================================
tmux new-session -d -s "vhserver" " ./valheim_server.x86_64 -name 'Valheim Server' -password  -port 2456 -world vhserver -public 1 -savedir '/var/opt/valheim/.config/unity3d/IronGate/Valheim'"

Error
=================================
usage: new-session [-AdDP] [-F format] [-n window-name] [-s session-name] [-t target-session] [-x width] [-y height] [command]
0
```
After looking around for a bit and wraping around the steps to get through to that point I started compairing the function/command_start.sh to one on a different server and found that it was functional and the new version was not.

The issue being on line 75:
`tmux new-session -d -x "${sessionwidth}" -y "${sessionheight}" -s "${sessionname}" ${preexecutable} ${executable} ${startparameters} 2> "${lgsmlogdir}/.${selfname}-tmux-error.tmp"`

needing double quotes around the `${preexecutable} ${executable} ${startparameters}` variables that were removed in a commit 9 days ago for incident #3239 with commit 3d39604 for something that looks similar but the reverse.

Ironically I get success when I add it back so I am not sure if it is just a me thing or if it is a syntax issue. as I would understand it as everything after the `-s "${sessionname}"` in tmux would need to be a single command but I haven't dove that far into troubleshooting for the edge cases.

`tmux new-session -d -x "${sessionwidth}" -y "${sessionheight}" -s "${sessionname}" "${preexecutable} ${executable} ${startparameters}" 2> "${lgsmlogdir}/.${selfname}-tmux-error.tmp"`

It currently isn't impacting me as I can just reuse an old verions or template a version with quotes but it might help some other soul in the mean time.

## To Reproduce

Steps to reproduce the behaviour:
1. Deploy a Centos 7 VM 
1. Mount App Directory (I use /var/opt)
1. Update Packages and Install Deps
1. Create App User with a home in App mount (/var/opt/valheim)
1. Curl install scripts down and run (Attempted with auto-install and regular install)
1. Run server start (./vhserver start)

## Expected behaviour

Post installation start even with default settings to start without error.

## Have not tried

1. Copying the install steps word for word as I usually try to avoid putting apps in /home if possible.
2. Trying a different distro like Ubuntu/Debian.
3. Tried to echo the syntax as it is when running the command without double quotes.
4. Tried on a currently functional server *Edit*
5. Moving the quotes to be around ` ${executable} ${startparameters}` leave pre exec  out*Edit*

Again I suspect this is a me thing as the commit would have been 9 days ago and there doesn't seem to be any reports other then myself and the Arma report yesterday but that seems to be slightly different. Feel free to close this if you want and I'll try to help between work if needed.

I can provide a pastebin upon request for more details.

**Comment by tk1114632** [comment]
This bug also happened in my csgoserver servers. Thanks, adding quotes fixed the issue.

**Comment by dgibbs64** [comment]
Looks like there are several issues relating to quotes around stuff.

**Comment by dgibbs64** [comment]
possible will need to revert this commit https://github.com/GameServerManagers/LinuxGSM/commit/3d396049a650069fa332611b92148618c610451c

**Comment by marcleblanc2** [comment]
@dgibbs64 I was stumped on this one for a few hours. This is what worked for me, in the end, I removed the double quotes from the command on [https://github.com/GameServerManagers/LinuxGSM/blob/532443eafeee33706399a980070be70e2d5693fd/lgsm/functions/command_start.sh#L75](command_start.sh#L75)

`        tmux new-session -d -x ${sessionwidth} -y ${sessionheight} -s ${sessionname} ${preexecutable} ${executable} ${startparameters} 2> "${lgsmlogdir}/.${selfname}-tmux-error.tmp"`

Borrowed the idea from: https://github.com/GameServerManagers/LinuxGSM/discussions/3239#discussioncomment-431397

Running Valheim, on 
Ubuntu, 20.04 LTS, amd64 focal image build on 2021-03-15
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
tmux 3.0a
LinuxGSM - Valheim - Version v21.2.2
