### ISSUE TITLE
[BUG] Server files pointing to wrong location after latest LinuxGSM update

### ISSUE THREAD

**Issue by Shebuka** [GameServerManagers/LinuxGSM#3376]
## User Story

The new version of LinuxGSM added -savedir parameter to vhserver that is causing the game to not recognize the current savedir and points to a completely different location.

## Basic info

* **Distro:** Ubuntu 20.04.2 LTS
* **Game:** Valheim
* **Command:** start
* **LinuxGSM version:** v21.2.1

## Further Information

May be caused by the fact that the -savedir parameter is escaped by ' (single apostrophe).
#3266 and #3370 may be the ones to look at

## To Reproduce

Steps to reproduce the behaviour:
1. Update to v21.2.1
2. Start server
3. Enter the game and observe that it's a completely new world
4. Find that you now have **/home/vhserver/serverfiles/'/home/vhserver/.config/unity3d/IronGate/Valheim'** folder (folder named **'** and folder named **Valheim'**)

## Expected behaviour

That it point to correct location

**Comment by zeerorg** [comment]
Had this same issue. The -savedir should not have singlequotes.

**Comment by dgibbs64** [comment]
Thanks. I will be addressing this issue this evening. Having some issues with quotes currently

**Comment by dgibbs64** [comment]
I have put a temporary commit into master to hopefully resolve the issue until I can get home. Just update LinuxGSM

Please can someone test and let me know.

**Comment by tbrigley** [comment]
many valheim lgsm dedicated servers are offline due to auto-updates from this change, i'm trying to figure out a workaround to bring it back online with least impact. any advise from people also encountering this?

**Comment by dgibbs64** [comment]
remove the quotes or `-savedir` from parameters. 

I have done a temporary commit to try and fix it until I get home in a few hours.

so run 
```
./vhserver update-lgsm
```
and that may also help

**Comment by Shebuka** [comment]
> many valheim lgsm dedicated servers are offline due to auto-updates from this change, i'm trying to figure out a workaround to bring it back online with least impact. any advise from people also encountering this?

For now I've opened the `common.cfg` of my server (in `~/lgsm/config-lgsm/vhserver`) and added `startparameters="-name '${servername}' -password ${serverpassword} -port ${port} -world ${gameworld} -public ${public}"`.

Can't test the fix as there are people on the server right now.

**Comment by dgibbs64** [comment]
Hotfix has been released that should resolve this issue.

**Comment by Alvar195** [comment]
Doesn't seem fixed. _default.cfg still includes single quotes: `-savedir '${savedir}'`

https://github.com/GameServerManagers/LinuxGSM/blob/v21.2.2/lgsm/config-default/config-lgsm/vhserver/_default.cfg

**Comment by Shebuka** [comment]
@Alvar195 The quotes are needed for paths with spaces in them. The fix is not to remove quotes.
