### ISSUE TITLE
Multiple folders created.

### ISSUE THREAD

**Issue by MaRrDG** [GameServerManagers/LinuxGSM#3384]
Hi, can you tell me why more files were created in mcserver? They all have the same content in them, I mean logs and serverfiles, before I had only one of each. Thanks PS: I am not native English speaker, sorry for my bad english :)
![unknown](https://user-images.githubusercontent.com/80762697/111310927-48236f00-8666-11eb-97be-77f191affd27.png)

**Comment by dgibbs64** [comment]
That is not normal and I have never seen that before. 

I recommend first using the home directory as per website instructions. I am unsure if your permissions are correct. 
Maybe also try deleting everything and starting again.
