### ISSUE TITLE
[Server Request] Survive The Nights

### ISSUE THREAD

**Issue by BlueSky-fur** [GameServerManagers/LinuxGSM#3387]
## What game server would you like adding?

Survive the Nights

## Can you link to any tutorials or guides?
https://survivethenights.gamepedia.com/Hosting - Might be usefull!

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

1502300

https://steamdb.info/app/1502300/

## Is the server supported on Linux?
Yes and only Linux currently.
We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by h3o66** [comment]
Currently waiting for them to make it fully public.
