### ISSUE TITLE
[BUG] Rust Seed

### ISSUE THREAD

**Issue by includes08** [GameServerManagers/LinuxGSM#3398]
Seed not working, launch parameter has the following 
`+server.seed 2076608748`

but server launches with seed 1.

## Basic info

* **Distro:** [Centos 8]
* **Game:** [Rust]
* **Command:** [Details / Seed]
* **LinuxGSM version:** [v21.2.2]

Steps to reproduce, seed is empty in lgsm-config. Random seed is generated in seed file and shows up in parameters. But seed is not working in Rust, server keeps using seed 1. Rest of launch parameters works fine.

**Comment by dgibbs64** [comment]
I need to try and replicate this. Please could you post your configs and details (without passwords). Thanks

**Comment by includes08** [comment]
`##################################
####### Instance Settings ########
##################################
# PLACE INSTANCE SETTINGS HERE
## These settings will apply to a specific instance.

## Predefined Parameters | https://docs.linuxgsm.com/configuration/start-parameters
ip="0.0.0.0"
port="28035"
rconport="28036"
appport=28037
rconpassword="*******************"
rconweb="1" # Value is: 1 for the Facepunch web panel, Rustadmin desktop and Rustadmin Online; 0 for RCON tools like Rusty.
servername="xFunServer|x10000000|PVP|BATTLEFIELD"
maxplayers="80"
seed="" # range: 1-2147483647, used to reproduce a procedural map.
salt="" # range: unknown, used to recover a known setting from an existing map.
worldsize="2599" # default: 3000, range: 1000-6000, map size in meters.
saveinterval="300" # Auto-save in seconds.
tickrate="30" # default: 30, range: 15-100.

## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
fn_parms(){
parms="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"
}`

**Details** https://termbin.com/o3308

serverseed was set manually temporarily i took that out of the config. So the config seen above is how i normally used it.

**Comment by dgibbs64** [comment]
Try using the new `startparameters` rather than the old `fn_parms` and let me know if that fixes it. Thanks

**Comment by includes08** [comment]
replaced the old with the new, seem to end up having the same issue still.

**Comment by dgibbs64** [comment]
I have managed to replicate the issue. I did a wipe and got the same seed of 53384 even though the seed is set as 358633079

No obvious reason yet. This will be a priority fix and I will hotfix it when I get a solution

**Comment by dgibbs64** [comment]
found a fix for the issue

**Comment by includes08** [comment]
Thank you good sir

**Comment by dgibbs64** [comment]
Hot fix will be inbound hopefully tomorrow. Just need to wrap up other stuff etc 🙂
