### ISSUE TITLE
Update Request - ET:Legacy 2.77.1

### ISSUE THREAD

**Issue by jobhh** [GameServerManagers/LinuxGSM#3399]
Last week the [ET:Legacy 2.77.1](https://www.etlegacy.com/blog/recapture-the-city) hotfix was released. If someone has the time it would be nice if the LinuxGSM image could be updated. The download page with the ET:Legacy 2.77.1 Linux 32-bit binaries: https://www.etlegacy.com/download

This hotfix was released just 1 day after the [2.77 update was merged](https://github.com/GameServerManagers/LinuxGSM/pull/3363) into LinuxGSM xD 
It should fix the error I'm getting when trying to join the server on the 2.77 server: `Fixed load official pak file error when connecting to servers`

If it's just uploading the binaries to a webserver and creating a pull request pointing the install_server_files.sh file to the correct URL I'd be happy to do it, but I can imagine you'd prefer not to give a random Github user write access to that server.

**Comment by dgibbs64** [comment]
@jobhh it appears that the developers of ET:L are planing smaller releases moving forward. The issue with this currently is we have no auto-update functionality available for ET:L. It takes me time to merge ET and ET:L into an archive and upload. This also only gets updated when there is a new release of LinuxGSM. I tried to access the ET:L discord but has issues with there verification bot. 

If you are able to could you speak with the ET:L devs and see if they have any plans for an auto-update feature. If not we will have to come up with a more automated solution.

**Comment by jobhh** [comment]
I asked the question in the Development -> etlegacy channel on the ET:Legacy Discord. We'll see if someone can answer it :)

**Comment by jobhh** [comment]
Sooo, I floated the idea in the Discord channel. 

- Fully auto-updating will not happen, which I think is reasonable because there will always be people who want to run a specific server version.
- Adding a function to ET:Legacy to manual trigger an update was something that some thought to be useful, LinuxGSM could then for example start ET:Legacy with the update parameter. 
- Others suggested LinuxGSM should just download the latest version when it installs the ET:Legacy server. The new tar.gz could then be extracted over the existing archive.

I don't expect something to be implemented in the near future, in part because ET:Legacy has a relatively long time between feature-releases (the last release was 2+ years ago), but at least we've planted the idea.

**Comment by jobhh** [comment]
I've prepared an archive: https://www.dropbox.com/s/r3d4ko8qjbb0lt8/etlegacy-v2.77.1-i386-et-260b.tar.xz?dl=1
It's the ET:Legacy 2.77.1 release with pak0.pk3, pak1.pk3 and pak2.pk3 added to the etmain directory (as [described here](https://github.com/etlegacy/etlegacy/wiki/Linux)). When I insert the file/md5 into `install_server_files.sh` it works without issue.

I'm not sure if any LinuxGSM specific modifications were made in the previous release, but the LinuxGSM 2.77 package contained more files than the version made for 2.76. For example the etintro.roq file and pb folder seemed unnecessary. If no modifications were made specifically for LinuxGSM, you can upload the archive to linuxgsm.download and use it as-is :)

**Comment by jobhh** [comment]
The only issue I see with updating an existing ET:Legacy server is that some configuration and database files will be overwritten, because they're not inside the main etlserver.cfg that LinuxGSM can customize. But that's the case with the current version as well, so I think the 2.77.1 archive should be preferred for now.

Is there something we can do to inform the user of specific files that might be bad to overwrite? The files we probably don't want to overwrite:
`etmain\etlserver.cfg` _(General server configuration. Although changes to this file should be done in the lgsm directory and not serverfiles)_
`legacy\omni-bot\et\user\omni-bot.cfg` _(Omni-bot configuration)_
`legacy\wolfadmin.db` _(WolfAdmin database)_
`legacy\wolfadmin.toml` _(WolfAdmin configuration)_
