### ISSUE TITLE
[BUG] Arma 3 debug does not load with startup parameters

### ISSUE THREAD

**Issue by brysondev** [GameServerManagers/LinuxGSM#3406]
## User Story

Launching Arma 3 Server in debug does not load any of the startup parameters.

## Basic info

* **Distro:** [Fedora 33]
* **Game:** [Arma 3]
* **Command:** [debug]
* **LinuxGSM version:** [v21.2.2]

## Further Information

As previously stated, the launching of the server in debug mode does not use any of the start up parameters. If I launch any other way it works as intended. 

## To Reproduce

Steps to reproduce the behaviour:
1. ./arma3server debug
2. wait for it to finish loading
3. Check server browser
4. See error as name and player count are using default values (hostname of machine and 64 players)

**Comment by dgibbs64** [comment]
Thanks. I am aware of this one. I will link to pr 🙂
