### ISSUE TITLE
[BUG] Out of memory error in steamcmd on Amazon Linux 2

### ISSUE THREAD

**Issue by sunbect** [GameServerManagers/LinuxGSM#3433]
***Please use the template below, deleting the above text***

## User Story

As an Amazon Linux 2 user, I want to run a csgoserver alongside my wordpress site..

## Basic info

* **Distro:** Amazon Linux 2
* **Game:** Counter-Strike: Global Offensive
* **Command:** ./csgoserver install
* **LinuxGSM version:** [v20.1.3]

## Further Information

./csgoserver install works fine upto 
`[ START] Installing csgoserver`

and then crashes to this

```
Redirecting stderr to '/home/ec2-user/.local/share/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Warning: failed to init SDL thread priority manager: SDL not found
 Update state (0x61) downloading, progress: 0.00 (200630 / 28152158766)
 Update state (0x61) downloading, progress: 0.13 (36425716 / 28152158766)
 Update state (0x61) downloading, progress: 0.37 (104201523 / 28152158766)
 Update state (0x61) downloading, progress: 0.50 (139853107 / 28152158766)
 Update state (0x61) downloading, progress: 0.71 (198573363 / 28152158766)
 Update state (0x61) downloading, progress: 0.91 (255692536 / 28152158766)
 Update state (0x61) downloading, progress: 1.21 (341474797 / 28152158766)
 Update state (0x61) downloading, progress: 1.34 (378174957 / 28152158766)
 Update state (0x61) downloading, progress: 1.47 (413601825 / 28152158766)
 Update state (0x61) downloading, progress: 1.73 (485953569 / 28152158766)
 Update state (0x61) downloading, progress: 2.01 (565645345 / 28152158766)
***** OUT OF MEMORY! attempted allocation size: 1048576 ****
src/tier0/memstd.cpp (2489) : Fatal Assertion Failed: OUT OF MEMORY
src/tier0/memstd.cpp (2489) : Fatal assert; application exiting
***** OUT OF MEMORY! attempted allocation size: 524288 ****
Complete! Installing csgoserver:
```

## To Reproduce

Steps to reproduce the behaviour:
1. ./csgoserver install

## Expected behaviour
Install the csgoserver files through steamcmd

**Comment by dgibbs64** [comment]
Your server does not have enough memory.

**Comment by sunbect** [comment]
I was able to run the server on the same t2.micro instance in Ubuntu 20.04 LTS but now that I am using Amazon Linux 2 it gives me an out of memory error?

**Comment by dgibbs64** [comment]
Maybe Amazon Linux 2 uses more memory than Ubuntu 20.04

t2.micro only has 1 core CPU and 1GB of RAM. This is way too small for a CS:GO server. I suggest getting a bigger instance. If cost is an issue look at using a cheaper VPS or dedicated server provider.
