### ISSUE TITLE
[Server Request] Velocity Proxy for minecraft

### ISSUE THREAD

**Issue by Sergentval** [GameServerManagers/LinuxGSM#3436]
## What game server would you like adding?

Velocity Proxy for minecraft server

## Can you link to any tutorials or guides?

https://velocitypowered.com/
https://velocitypowered.com/wiki
https://velocitypowered.com/wiki/users/getting-started/

https://github.com/VelocityPowered/Velocity

## Is the server on Steam?

* [ ] Yes
* [x] No

## Is the server supported on Linux?

* [x] Yes
* [ ] No

**Comment by Claiyc** [comment]
See https://github.com/GameServerManagers/LinuxGSM/issues/3437#issuecomment-877776147 on how to install this.

**Comment by d3adwolf** [comment]
I support the request to add Velocity, very missing, I read that you can manually replace the file, but still auto-update and auto-run is extremely important, it is one of the main reasons to use LinuxGSM.

**Comment by h3o66** [comment]
If i am not wrong, this could be very easy impemented, as this uses as well the papermc api like we have already for papermc and waterfall

**Comment by h3o66** [comment]
Got the first version for the PR up, the only downside it currently that the latest snapshot is installed instead of the latest stable by default.
