### ISSUE TITLE
[FEATURE] BP Wipe Rust

### ISSUE THREAD

**Issue by VoidEther** [GameServerManagers/LinuxGSM#3438]
As a Game Network Owner, I want to bp-wipe so that we can chain map-wipe and bp-wipe together in cronjob to be more
automated friendly. (Issues with map-wipe and full-wipe being together in cronjob format)

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Rust]
* **Command:** [bp-wipe] (What I think it should be)
* **LinuxGSM version:** [v20.1.3]

## Further Information

just removing the player.blueprints in server/rustserver/

Yes it be easier making it a script but it would be way more streamlined if its added into linuxgsm

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by dgibbs64** [comment]
It's my understanding that a full-wipe is a map-wipe and bp-wipe combined. Info is in the linuxgsm docs

**Comment by Yomatsun** [comment]
> It's my understanding that a full-wipe is a map-wipe and bp-wipe combined. Info is in the linuxgsm docs

Yes that is correct It was to my understanding that full-wipe and map-wipe dont play well In a cron format
so instead of just wiping the map itll wipe  the player blueprints because the map-wipe already wiped the map on  that day

**Comment by dgibbs64** [comment]
You should use either map-wipe or full-wipe as full-wipe does a map wipe anyway.
