### ISSUE TITLE
[Server Request] Obsidian Conflict

### ISSUE THREAD

**Issue by RoonMoonlight** [GameServerManagers/LinuxGSM#3439]
## What game server would you like adding?

Obsidian Conflict (Steam)

## Can you link to any tutorials or guides?

There aren't have any tutorials or guide for installing dedicated server for Obsidian Conflict since it is not released yet! I will update it asap if I find something.

## Is the server on Steam?

* [x] Yes
* [ ] No

It is not actually available to public, and [announcement](https://obsidianconflict.net/news/2020-winter-update.html) says the game will be released on unknown date of 2021. (The game might be delayed in the future if situation is worst)

But the SteamDB page for dedicated server is currently accesible here:
Game ID: [248890](https://steamdb.info/app/248890/)

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by dgibbs64** [comment]
2023 and still in "Coming Soon". Closing this. Feel free to re-raise this when released
