### ISSUE TITLE
[BUG] Dependency missing on Debian Bullseye (11)

### ISSUE THREAD

**Issue by m33ts4k0z** [GameServerManagers/LinuxGSM#3443]
The renamed library in Debian 11 from lib32gcc1 to lib32gcc-s1.

The issue is fixed in [this](https://github.com/GameServerManagers/LinuxGSM/pull/2951/commits/2ab3ed0d3eb29b1b22b23609c3a38ba8c20f3d86) commit but the added check fails because the testing version of Bullseye returns no version number. 

Suggested fix is to parse the output of lsb_release -d that contains the release name (bullseye) instead of trying to regex a number out.

Lazy and very wrong workaround for the moment is to modify the line 356 of check_deps.sh to:
`array_deps_required+=( lib32gcc-s1 lib32stdc++6 )`

**Comment by olokos** [comment]
Also ubuntu 21.04 is out now so this:

https://github.com/GameServerManagers/LinuxGSM/blob/19ac5610f1d532c5ee2697b800c5b385b8d4a519/lgsm/functions/check_deps.sh#L189

will fail also

**Comment by dgibbs64** [comment]
Refactor of dependency checking is going to happen. It will resolve this sort it issue
