### ISSUE TITLE
Symbolic link | FIle Exists

### ISSUE THREAD

**Issue by John4266** [GameServerManagers/LinuxGSM#3451]
Whenever starting a server, it does work but i get the following warnings:
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/vphysics.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/studiorender.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/soundemittersystem.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/shaderapiempty.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/scenefilecache.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/replay.so': File exists
ln: failed to create symbolic link '/home/nmrihserver/serverfiles/bin/materialsystem.so': File exists

LinuxGSM Version: v21.2.3
OS: Ubuntu 20.04.2 LTS x86_64

**Comment by dgibbs64** [comment]
This looks like an error message from the game server itself and not LinuxGSM. Closing this. If further help needed feel free to chat to people on discord
