### ISSUE TITLE
[FEATURE] Mod support for CSGO

### ISSUE THREAD

**Issue by Jaikinator** [GameServerManagers/LinuxGSM#3453]
## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [CSGO]
* **Command:** [mods-install]
* **LinuxGSM version:** [v20.1.3]

## Further Information

Can you add the Sourcemod plugin:  csgo-multi-1v1 plugin
as well as the   Sourcemod plugin: csgo-practice-mode

## Further Reading

for both there is a git:

csgo-multi-1v1 plugin:  https://github.com/splewis/csgo-multi-1v1.git

csgo-practice-mode: https://github.com/splewis/csgo-practice-mode.git

PS I really appreciate your work.

**Comment by cpalm** [comment]
+1 for csgo-practice-mode

**Comment by johnoclockdk** [comment]
i will have a go make this
