### ISSUE TITLE
[BUG] Installing csgoserver: : Not enough space to download server files

### ISSUE THREAD

**Issue by close0ne** [GameServerManagers/LinuxGSM#3454]
Hi, I have VPS with 25gb, I installed custom centos 7 iso so I can manage all drives... and I have problem install CSGO server with 23gb of free space. 
I didnt found anyhting on internet what can help me... even answer how much space I exactly need... Only that 17-18gb..

![333](https://user-images.githubusercontent.com/23700069/117547222-c7ae3880-b02e-11eb-9021-b113c2fa2f41.PNG)

**Comment by dgibbs64** [comment]
You normally need some breathing room as well. Upgrade your storage and it will work.
