### ISSUE TITLE
Don't Starve Together Dedicated Server Error

### ISSUE THREAD

**Issue by DwellerIsTaken** [GameServerManagers/LinuxGSM#3455]
Hi! I'm trying to make dst dedicated server, but I get this error: windows can not find 'dontstarve_dedicated_server_nullrenderer'.
What can I do to solve this? And I'm trying to extract files from steamcmd.exe, program starts, but no files are getting extracted. Please help me!
[Strartdstservers.bat.txt](https://github.com/GameServerManagers/LinuxGSM/files/6446554/Strartdstservers.bat.txt)

[steamcmd (11).zip](https://github.com/GameServerManagers/LinuxGSM/files/6446568/steamcmd.11.zip)

**Comment by interstate420productions** [comment]
Hello DwellerlsTaken:

These forms are for the Linux Game Server Manaer's specific setup.  on LINUX Machines :)   You are asking questions about Windows..
