### ISSUE TITLE
[Server Request]

### ISSUE THREAD

**Issue by webzai** [GameServerManagers/LinuxGSM#3469]
## What game server would you like adding?

[game server]

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [ ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [ ] Yes
* [ ] No

**Comment by dgibbs64** [comment]
Closing no info
