### ISSUE TITLE
[BUG] Unhandled single quote xargs error in cod4server

### ISSUE THREAD

**Issue by Tremolo4** [GameServerManagers/LinuxGSM#3472]
## User Story

As a [user description], I want to put an apostrophe in my server hostname.

## Basic info
When putting a single quote into my server hostname inside the config (via `sv_hostname`), I get the following error:  
`xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option`
And the server doesn't start.

* **Distro:** Debian 10
* **Game:** Call of Duty 4
* **Command:** several, e.g. `start`
* **LinuxGSM version:** v21.2.3

## Further Information

Seems to be the same issue as #1111, which was fixed in #1112.

The offending code seems to be in `fn_info_config_cod4()`, which is in `info_config.sh`.

I don't understand the use of `xargs` *without any params* here. Is it to replace newlines with spaces in the input? If so, then why was it fixed by adding `-0` in #1112, wouldn't that remove exactly that behavior?

## To Reproduce

Steps to reproduce the behaviour:
1. Install a cod4server
2. Adjust the config, `serverfiles/main/cod4server.cfg`: add a single quote `'` to the value for `sv_hostname`
3. Attempt to start the server

**Comment by h3o66** [comment]
See the connected pr for a possible fix (to test this you need to manually change the lgsm script)
