### ISSUE TITLE
[BUG] Squad Server Netstat Command Incorrect

### ISSUE THREAD

**Issue by buer22** [GameServerManagers/LinuxGSM#3473]
## User Story

The netstat command that is printed out when you run the details command references the old name for the server process. 
New server process is actually called "SquadGameServer".

## Basic info

* **Distro:** [Deb 10]
* **Game:** [Squad]
* **Command:** [netstat]
* **LinuxGSM version:** [v21.2.3]

## Further Information

Current command is "netstat -atunp | grep SquadServer"

Should be "netstat -atunp | grep SquadGameServer"
## To Reproduce

Steps to reproduce the behaviour:
Try and run the netstat command printed out from the details command.

## Expected behaviour
Netstat command to work. 

##Pictures
![image](https://user-images.githubusercontent.com/29473126/120865141-7032b800-c55b-11eb-97a6-1785454b71be.png)

![image](https://user-images.githubusercontent.com/29473126/120865184-893b6900-c55b-11eb-9fc5-4035b2a8aade.png)

**Comment by dgibbs64** [comment]
I am going to replace netstat with the ss command. Thanks for letting me know about this one 😀

**Comment by h3o66** [comment]
Resolved with #3428
