### ISSUE TITLE
[BUG] Action: Source  is now anonymous  steam login

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#3474]
## User Story

Action: Source  is now anonymous steam login
## Basic info

* **Game:** Action: Source 
* **Command:** Install

**Comment by h3o66** [comment]
just tried to do this, but only the server binary files are downloadable and not the servercontent.
https://steamdb.info/app/985050/depots/

So this is currently not possible.

Error message from the console log:
```
Unable to find gameinfo.txt.
```

this is only in the sub depot
https://steamdb.info/depot/977051/
that is no allowed to be downloaded per anonymous steam login
