### ISSUE TITLE
[BUG] steamcmd cannot be found

### ISSUE THREAD

**Issue by TheHooly** [GameServerManagers/LinuxGSM#3476]
## User Story

I want to install an ARK server using LinuxGSM.

## Basic info

* **Distro:** [OpenSUSE Leap 15.2]
* **Game:** [ARK: Survival Evolved]
* **Command:** [./arkserver install]
* **LinuxGSM version:** [v21.2.3]

## Further Information

Install script fails with
```
Installing ARK: Survival Evolved Server
=================================
[ START ] Installing arkserver: 
./steamcmd.sh: Line 37: /home/ark/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/linux32/steamcmd: No such file or directory
```
Checking if it is really missing:
```
ark@opensuse:~> ls -la serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/linux32/
insgesamt 6108
drwxr-xr-x 1 ark users     110  8. Jun 17:46 .
drwxr-xr-x 1 ark users      36  8. Jun 17:46 ..
-r-xr-xr-x 1 ark users  352763  5. Jan 2018  crashhandler.so
-r-xr-xr-x 1 ark users  922064  5. Jan 2018  libstdc++.so.6
-rwxr--r-- 1 ark users 4839761  5. Jan 2018  steamcmd
-r-xr-xr-x 1 ark users  130423  5. Jan 2018  steamerrorreporter
```
Nope, it is definitely there.
Allowing everyone to read, write and execute inside `/home/ark` using `sudo chmod -R 777 /home/ark` yields the same results, so no issue with file permissions.

## To Reproduce

Steps to reproduce the behaviour:
1. Create ark user: `sudo useradd ark`
2. Create home folder for ark with permissions: 700, user: ark, group: users
3. Run `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh arkserver` from https://linuxgsm.com/lgsm/arkserver/
4. Run `./arkserver install`

## Expected behaviour

SteamCMD installing the ARK server.

**Comment by dgibbs64** [comment]
looks like you haven't installed the required dependencies. SInce you are running OpenSuse you will need to install them yourself.
