### ISSUE TITLE
[BUG] Arkserver unable to install to do Disk Write failure - serverfiles/steamapps missing

### ISSUE THREAD

**Issue by RumRogerz** [GameServerManagers/LinuxGSM#3477]
## User Story

ArkServer will not install the gameserver due to a missing folder.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Ark: Survival]
* **Command:** [./arkserver ai]
* **LinuxGSM version:** [v21.2.3]

## Further Information

Executing the installation on a fresh machine with dependencies installed will produce this error during installation:

```
./arkserver ai
[...]
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '376030' (Disk write failure)
Error! Installing arkserver: : Unknown error occured
Redirecting stderr to '/home/ubuntu/.local/share/Steam/logs/stderr.txt'
```

Further investigation under the file: ~/.local/share/Steam/logs/content_log.txt

```
[2021-06-08 17:27:44] Loaded 0 apps from install folder "/home/ubuntu/.local/share/Steam/steamapps\appmanifest_*.acf".
[2021-06-08 17:27:49] Loaded 0 apps from install folder "/home/ubuntu/gameserver/serverfiles/steamapps\appmanifest_*.acf".
[2021-06-08 17:27:50] Library folder "/home/ubuntu/gameserver/serverfiles/steamapps" is not writable (Disk write failure).
[2021-06-08 17:27:50] Failed installing AppID 376030 (Disk write failure)
```

## To Reproduce

Steps to reproduce the behaviour:
1. Install the gameserver as usual

## Expected behaviour

The /serverfiles/steamapps folder should be created during the LGSM installation procedure.

Adding this folder manually *will* install the gameserver, however it definitely breaks all my automation processes :(

**Comment by johnoclockdk** [comment]
mkdir /home/[game]/serverfiles/steamapps
 
 change [game] with the gameserver you runing

**Comment by RumRogerz** [comment]
> to fix the SteamCMD issue if you come across it. Create the steamapps directory in serverfiles
> 
> mkdir /home/gameserver/serverfiles/steamapps

I think you misunderstand - I mentioned in my ticket that if I add it manually it will install the server, however this is not the behaviour I have experienced in the past.  I am unsure if there was some massive change to steamcmd that I am unaware of.

**Comment by johnoclockdk** [comment]
> > to fix the SteamCMD issue if you come across it. Create the steamapps directory in serverfiles
> > mkdir /home/gameserver/serverfiles/steamapps
> 
> I think you misunderstand - I mentioned in my ticket that if I add it manually it will install the server, however this is not the behaviour I have experienced in the past. I am unsure if there was some massive change to steamcmd that I am unaware of.

there was a change if u checked discord in #announcements.. so until steam or lgsm will hotfix you will have to create that folder

**Comment by RumRogerz** [comment]
> > > to fix the SteamCMD issue if you come across it. Create the steamapps directory in serverfiles
> > > mkdir /home/gameserver/serverfiles/steamapps
> > 
> > 
> > I think you misunderstand - I mentioned in my ticket that if I add it manually it will install the server, however this is not the behaviour I have experienced in the past. I am unsure if there was some massive change to steamcmd that I am unaware of.
> 
> there was a change if u checked discord in #announcements.. so until steam or lgsm will hotfix you will have to create that folder

TIL you have a Discord server.

Thank you for your help sir!

**Comment by johnoclockdk** [comment]
you welcome
