### ISSUE TITLE
[BUG] LinuxGSM version mismatch (for at least Factorio)

### ISSUE THREAD

**Issue by mjohannfunke** [GameServerManagers/LinuxGSM#3485]
## User Story

As a LGSM user, I want the script not to update everytime so that it just executes the command.

## Basic info

* **Distro:** [Debian GNU/Linux 10 (buster)]
* **Game:** [Factorio]
* **Command:** [Any really]
* **LinuxGSM version:** [v21.2.4]

## Further Information

Everytime I run a command for the Factorio server it says `[ ERROR ] Monitoring fctrserver: LinuxGSM version mismatch` and proceeds to download everything, but it doesn't fix it (nor does a `lgsm-update` do).

```
$ ./fctrserver monitor

[ ERROR ] Monitoring fctrserver: LinuxGSM version mismatch

* fctrserver: v21.2.3
* modules: v21.2.4

[  OK  ] Updating LinuxGSM fctrserver: Selecting repo: GitHub
checking GitHub linuxgsm.sh...OK
checking fctrserver...OK
checking GitHub config _default.cfg...OK
checking GitHub module alert.sh...OK
checking GitHub module check_config.sh...OK
checking GitHub module check_deps.sh...OK
....
checking GitHub module query_gamedig.sh...OK
checking GitHub module update_factorio.sh...OK
[  OK  ] Updating LinuxGSM fctrserver: Updating functions
[  OK  ] Monitoring fctrserver: Checking session: OK
```

## To Reproduce

Steps to reproduce the behaviour:
Run any command, like `monitor`, `details`, `start` ...

## Expected behaviour

Download the new files at maximum once and then be done with it.

**Comment by jkh675** [comment]
same!!!!!!!!

**Comment by jkh675** [comment]
bro i have same problem

**Comment by dgibbs64** [comment]
done a quick fix for this will work now
