### ISSUE TITLE
[BUG] Dependencies for steamcmd on ubuntu 21.04 are not correct identified

### ISSUE THREAD

**Issue by S4enL0ng** [GameServerManagers/LinuxGSM#3489]
## User Story

As a friend, I want install arma3 on a server for a friend so that he can play on it.

## Basic info

* **Distro:** [Ubuntu 21.04]
* **Game:** [Arma 3]
* **Command:** [Monitor]
* **LinuxGSM version:** [v21.2.4]

## Further Information

The Dependencies for SteamCMD on Ubuntu 21.04 are not correct identified, so that it needs to be added to pile of if statement where the distribution version is linked to the system requirements.

## To Reproduce

Steps to reproduce the behaviour:
1. Install ubuntu 21.04
2. download linuxgsm
3. run `./linuxgsm arma3server`
4. rum `./arma3server instal`

## Expected behaviour

Lists all dependencies to be installed correct and knows about the renaming of lib32gcc1 to lib32gcc-s1 on debian10 based systems.

**Comment by dgibbs64** [comment]
I will be refactoring dependency checks due to new distros and releases changing dependency names. This will be part of that
