### ISSUE TITLE
[FEATURE] Add Rocky Linux and Alma Linux support, the CentOS alternative

### ISSUE THREAD

**Issue by RoonMoonlight** [GameServerManagers/LinuxGSM#3494]
## User Story
Since CentOS announced the end of support for CentOS 8, and shifting focus to CentOS Stream, please add support for Rocky Linux, the very known alternatives of CentOS.

## Basic info
* **Distro:** Rocky Linux 8.4 'Green Obsidian' or higher
* **Game:** All
* **Command:** gameserver install, gameserver autoinstall
* **LinuxGSM version:** v21.2.4

## Further Information
CentOS 8 support ends on December 31, 2021, and since it is almost reaching its EOL. I think LinuxGSM needs Rocky Linux support.

## Further Reading
> [Rocky Linux](https://rockylinux.org) is a community enterprise operating system designed to be 100% bug-for-bug compatible with America's top enterprise Linux distribution now that its downstream partner has shifted direction. It is under intensive development by the community. - From Rocky Linux official website

**Comment by dgibbs64** [comment]
I will definably be doing this. I will be completing a refactor of dependencies code and this will be part of it.
