### ISSUE TITLE
[BUG] add libnsl to CentOS mcbserver prereqs

### ISSUE THREAD

**Issue by us3r1d** [GameServerManagers/LinuxGSM#3506]
## User Story

Minecraft Bedrock will not run on CentOS 8 without libnsl.so.1, which is in the libnsl package, but it's not in the instructions or prereq checks so unless by chance you've already installed it the instructions result in a server that doesn't start.

## Basic info

* **Distro:** CentOS 8
* **Game:** Minecraft Bedrock
* **Command:** mcbserver
* **LinuxGSM version:** v21.2.4

## Further Information

The CentOS 8 instructions at <https://linuxgsm.com/lgsm/mcbserver/> and the prereq check in `./mcbserver start` need you include libnsl.

**Comment by dgibbs64** [comment]
Will be fixed in refactor
