### ISSUE TITLE
teamspeaker3 server - Issue with multiple ip's

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#352]
Hi,

After a sucessfull install on a centos 6.6  and defining the correct ip to use on the ts3server.ini:

[ts3server@ts3erver ~]$ ./ts3server start  
[ WARN ] Starting ts3-server: Multiple active network interfaces found.

Manually specify the IP you want to use within the ts3server script.  
Set ip="0.0.0.0" to one of the following:  
192.168.10.1  
192.168.10.2

After setting the ip on the ts3server file:
# Server Details

gamename="Home Voice Server"
servername="HomeTeamspeak Server"
servicename="ts3-server"
ip=192.168.10.1

New error:

[ts3server@ts3server~]$ ./ts3server start  
/home/ts3server/functions/fn_start: line 81: fn_parms: command not found  
[ WARN ] Starting ts3-server: SteamCMD is missing
mkdir: created directory `/home/ts3server/steamcmd'                                                                                   
downloading steamcmd_linux.tar.gz...OK                                                                                                
linux32/                                                                                                                              
linux32/libstdc++.so.6                                                                                                                
linux32/steamcmd                                                                                                                      
steamcmd.sh                                                                                                                           
steam.sh                                                                                                                              
removed`steamcmd_linux.tar.gz'  
[ .... ] Starting ts3-server: Home Teamspeak Servermv: cannot stat `': No such file or directory
touch: cannot touch`': No such file or directory  
[  OK  ] Starting ts3-server: HomeTeamspeak Server
## 

And server wont start.

What could it be? And why steamcmd is needed for Team Speaker server?

Note: Server runs ok if on ts3-server.ini have the following values, instead to 192.168.10.1

voice_ip=0.0.0.0
filetransfer_ip=0.0.0.0
query_ip=0.0.0.0

**Comment by dgibbs64** [comment]
Odd dunno why it suddenly asks for that. I will look at this and resolve.

**Comment by pereirtc** [comment]
I'm going to check aswell, thanks for the fast reply!

**Comment by pereirtc** [comment]
Not a issue at all.

i changed the gamename variable from ts3server script and that caused fn_start to fail the condition ( lines 178- 182 )

Sugestion: adding a comment above the gamename saying that variable should not be changed.

Thanks for the awesome script!
