### ISSUE TITLE
[Server Request] Citadel: Forged with Fire

### ISSUE THREAD

**Issue by cdokkum** [GameServerManagers/LinuxGSM#3520]
## What game server would you like adding?

[Citadel: Forged with Fire]

## Can you link to any tutorials or guides?

https://steamcommunity.com/sharedfiles/filedetails/?id=1397348707

Provide any useful documentation or resources that might help.

https://steamcommunity.com/sharedfiles/filedetails/?id=1397348707

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[487120]

## Is the server supported on Linux?

* [x] Yes
* [ ] No

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by gOOvER** [comment]
Duplicate of #2220 & #1548

**Comment by Claiyc** [comment]
Duplicate of #1548
