### ISSUE TITLE
[FEATURE] check-update function for TeamSpeak 3 server (game: Teamspeak 3)

### ISSUE THREAD

**Issue by Retardium** [GameServerManagers/LinuxGSM#3522]
## User Story

Hi, could you please add a `check-update` function like already existing for SteamCMD games for the TeamSpeak 3 server?

I prefer to do the updates manually, because I have already had negative experiences with the updates from TeamSpeak Systems. The quality control is apparently not the best. 😄
Therefore, a feature that notifies me about new updates would be very useful.

## Further Reading

Feature added for SteamCMD games with https://github.com/GameServerManagers/LinuxGSM/commit/b345cba3745f2ac06d8de885bfa419c9d833a64d, https://github.com/GameServerManagers/LinuxGSM/commit/09ce7899d1e889a0c7792408b97abac28af96e45
Requested for the game Rust in https://github.com/GameServerManagers/LinuxGSM/issues/2001

**Comment by h3o66** [comment]
Created a PR for this, should be working fine.
Feel free to test this.
