### ISSUE TITLE
[Server Request]  Rust: Stagging Branch

### ISSUE THREAD

**Issue by C74K** [GameServerManagers/LinuxGSM#3524]
## What game server would you like adding?
Rust: Stagging Branch
[game server]

## Can you link to any tutorials or guides?

https://steamcommunity.com/app/700580/discussions/0/1698293255122436702/

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [X ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

app_update 258550 -beta staging

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.
app_update 258550 -beta staging

* [X ] Yes
* [ ] No

**Comment by h3o66** [comment]
this is already possible with lgsm, see the doc here:
https://docs.linuxgsm.com/steamcmd/branch
