### ISSUE TITLE
[BUG] 7 Days to Die command_stop.sh bug

### ISSUE THREAD

**Issue by Tex42** [GameServerManagers/LinuxGSM#3526]
## User Story

When i stop my 7 Days to Die Server after a couple of hours i get a warning.

## Basic info

* **Distro:** [Debian 10.10]
* **Game:** [7 Days to Die]
* **Command:** [stop]
* **LinuxGSM version:** [v21.2.5]

## Further Information

[ .... ] Stopping sdtdserver: Graceful: telnet: 127.0.0.1:8081/home/sdtdserver/lgsm/functions/command_stop.sh: line 118: warning: command substitution: ignored null byte in input

**Comment by h3o66** [comment]
I cannot reproduce this on my side.
What did you configure on your side ? (LGSM and game config)

**Comment by Tex42** [comment]
I only changed these files [sdtdserver.xml](https://gist.github.com/Tex42/fada122d3360572e1fb7c4c81f7d8641) and [common.cfg](https://gist.github.com/Tex42/e7be16653f2c55474259aa7ec2d758af) right now i also don't get the warning but i didn't change any settings. I will let the server run over night and try to stop it tomorrow and look if i again get the warning.

**Comment by Tex42** [comment]
I stop my Server again today and got the same warning
 [ .... ] Stopping sdtdserver: Graceful: telnet: 127.0.0.1:8081/home/sdtdserver/lgsm/functions/command_stop.sh: line 118: warning: command substitution: ignored null byte in input

**Comment by Tex42** [comment]
Today i got a new Error message: ./sdtdserver stop
[ ERROR ] Stopping sdtdserver: Graceful: telnet: 127.0.0.1:8081 : FAIL
[ ERROR ] Stopping sdtdserver: Graceful: telnet: 0.0.0.0:8081 : FAIL
[ ERROR ] Stopping sdtdserver: Graceful: telnet: FAIL

Telnet output:
 spawn telnet 0.0.0.0 8081
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
Timeout or EOF

I still did not change any settings.

**Comment by Tex42** [comment]
It only happen when the Server runs at least one Day.

**Comment by dgibbs64** [comment]
Tested again on a server I leave up constantly and is OK now. Hopefully its fixed
