### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by azammalik** [GameServerManagers/LinuxGSM#3532]
Issues raised here are **ONLY** for:
* LinuxGSM bugs.
* Feature suggestions.
* Code contributions.

Issues raised here are **NOT** for:
* General support.
* Specific game server issues (e.g CS:GO, TF2).
* Dedicated server issues (e.g Ubuntu, CentOS).
* Anything not directly related to LinuxGSM development.

For general support visit the **[LinuxGSM Support](https://linuxgsm.com/support)** page.

***Please use the template below, deleting the above text***

## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Garry's Mod]
* **Command:** [Monitor]
* **LinuxGSM version:** [v20.1.3]

## Further Information

A clear description of what the feature is and any ideas on how to achieve this.

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by azammalik** [comment]
Hy

**Comment by h3o66** [comment]
please add more info to this, I do not see any info that helps.
Please vistit as well the other support channels if you need help.

**Comment by dgibbs64** [comment]
Closing no info at all
