### ISSUE TITLE
Server logfile auto-delete (several GB after a few months)

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#354]
Hi there,

I'm still using this amazing script that is wonderfully improved every time i need to download it again, and i'm very thankful for that !

By the way, i just migrated a few servers these days, and my gosh, i noticed that server logfiles aren't auto removed ! On our biggest servers on Gmod, it was more than 4GB of logiles in /log/server and a lot of files, so that was the longest thing to copy from one server to the other !
I was just thinking : why not auto-remove those just like you're doing with both the script and console logfiles ?

Also, as a bonus, it could be nice to be able to setup the amount of logfiles we want to keep into the "gameserver" script.

Thanks for your attention.

PS : Kept a screenshot of the sledbuild server's logfiles... :p http://image.noelshack.com/fichiers/2015/18/1430193284-logiles-size.png

**Comment by dgibbs64** [comment]
My most recent commit addresses this as I discovered the same issue :-)

**Comment by UltimateByte** [comment]
Great minds think alike :o))

Well, maybe you could do something to cleanup default server's logs too, as they don't cleanup neither, but i'm not sure it's the script's logic to fix srcds' lacks of convenience.

Also but consider this as less than optional, as this is probably hard and boring to code, i'm giving the idea just in case : some plugins and addons are flooding logs too (i actually had a total of 10GB of logs in 6 months onto the DarkRP server), so if we could specify some log folders to cleanup too, with exclusion for some files that are sometimes not logs, it'd just be magic.

**Comment by dgibbs64** [comment]
I like this idea. And wouldn't be to difficult to implement. I would need to know where the logs are stored or if there is a variable in the mods config file for this. It can be something that I look in to at some point :-)

**Comment by UltimateByte** [comment]
As you probably know, srcds logs are located in serverfiles/gamename/logs , but addon's logs can be found in other locations.
One common admin addon for Gmod is the ULX, with logfiles located in: serverfiles/garrysmod/data/ulx_logs
For DarkRP mode, it's serverfiles/garrysmod/data/darkrp_logs

For CSS, Sourcemod admin addon seems to be the most popular, and logs are here : serverfiles/cstrike/addons/sourcemod/logs
As you may also know, Sourcemod seems to be used at least for tf2 too (maybe CSGO, DoD L4D and so on, so maybe a conditional check into the cleanup function ?).

I wish that can be a good start point. Good luck, I'm still available if i can help in any way.

**Comment by UltimateByte** [comment]
Working on it...
Wait, struggling on it :D 
That syntax and those functions are pretty new to me !
mtime, tee... I'm slow but i'll figure this out ! :p

**Comment by UltimateByte** [comment]
Ended up with something way cleaner to me, future support for logs should be way easier. Pull requesting it !
