### ISSUE TITLE
[FEATURE] add additional Flags to the minecraft server launch setting code

### ISSUE THREAD

**Issue by GroGaloraGran** [GameServerManagers/LinuxGSM#3541]
Hello
please add additional Flags to the minecraft server launch setting code.
For stable operation of "Paper" servers (and other Minecraft servers) it is recommended to use Aikar's flags:
for example, this is the startup code that we use before switching to the LinuxGSM solution:
`java -Xms6g -Xmx6g -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Daikars.new.flags=true -Dusing.aikars.flags=https://mcflags.emc.gs -jar server.jar --nogui`

currently only -Xmx6g and --nogui are used in the LGSM setup

to generate it is usually recommended to use the information from here [https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft)/
or this generator
[https://startmc.sh/](https://startmc.sh/)

**Comment by Claiyc** [comment]
You can add java arguments by adding / modifiying preexecutable="java -Xmx${javaram}M -jar" in the linuxgsm config.

**Comment by GroGaloraGran** [comment]
> Вы можете добавить аргументы Java, добавив / изменив preexecutable = "java -Xmx $ {javaram} M -jar" в конфигурации linuxgsm.

Hello
thanks i will try it today and give feedback later

**Comment by GroGaloraGran** [comment]
> You can add java arguments by adding / modifiying preexecutable="java -Xmx${javaram}M -jar" in the linuxgsm config.
Many thanks
it worked out
here is the line at less than 12G memory allocation:
`preexecutable="java -Xmx${javaram}M -Xms${javaram}M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Daikars.new.flags=true -Dusing.aikars.flags=https://mcflags.emc.gs -jar"`
