### ISSUE TITLE
[Server Request] Rising World Unity Engine

### ISSUE THREAD

**Issue by lebanni** [GameServerManagers/LinuxGSM#3546]
the unity server files are downloaded but the script still tries to launch the java version.

https://forum.rising-world.net/thread/11490-dedicated-server-setup-new-version/

**Comment by dgibbs64** [comment]
Interesting it looks like they are completely changing engine. I am guessing they are phasing out the Java version over time? I am wondering what the best way to handle this will be moving forward as effectively it is a completely different game server (similar to Minecraft Java and bedrock editions)

It will require you to change the executable settings (which you can find in _default.cfg)
