### ISSUE TITLE
[Server Request]DayZ-(Experimental )Server since native Linux support is added

### ISSUE THREAD

**Issue by SysdotC** [GameServerManagers/LinuxGSM#3556]
## What game server would you like adding?

DayZ

## Can you link to any tutorials or guides?

https://steamdb.info/app/1042420/

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [x ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[1042420]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x ] Yes
* [ ] No

Would be a charm! :)

**Comment by Marcin648** [comment]
I'm working on this. :)
