### ISSUE TITLE
[BUG] Missing dependencies - lib32gcc1

### ISSUE THREAD

**Issue by RichusX** [GameServerManagers/LinuxGSM#3559]
## User Story

As a host, I want to start Valheim server, so that it starts...

## Basic info
![image](https://user-images.githubusercontent.com/5690827/133647890-2385d7c9-3e22-4a25-bddc-c4619e637a96.png)

* **Distro:** [Ubuntu Server 21.04]
* **Game:** [Valheim]
* **Command:** [Start]
* **LinuxGSM version:** [v21.2.5]

## Further Information

Updated server from 20.04 to 21.04 and unable to start the Valheim server anymore.
When attempting to run start command, I get an error telling me to install `lib32gcc1`. However when trying to install it, there are no installation candidates. Only a packaged named `lib32gcc-s1` is being suggested (which is already installed).

![image](https://user-images.githubusercontent.com/5690827/133647971-bd02a5f3-a867-412d-b3a2-4c5f93a9283f.png)
![image](https://user-images.githubusercontent.com/5690827/133648245-d0bebd97-7e73-4ef0-862a-7b4d796db54f.png)

## To Reproduce

Steps to reproduce the behaviour:
1. Attempt to run `./vhserver start`
2. See error about unmet dependencies
3. Attempt to install said dependencies
4. Fail

## Expected behaviour
`lib32gcc1` shouldn' t be asked for, as I believe it was renamed

**Comment by johnoclockdk** [comment]
21.04 is not support by lgsm

**Comment by dgibbs64** [comment]
Next release will resolve this 😁

**Comment by Seltonu** [comment]
Is this just to build the server executable? Having the same bug, wondering if I can just run the installation script on a 20.10 virtual machine and copy over the executable once it's done without any problems

**Comment by h3o66** [comment]
This was solved by i the new release via #3568
