### ISSUE TITLE
[BUG] Broken server version

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#3567]
When I try update server I get "0" version aka broken.
![image](https://user-images.githubusercontent.com/25010528/134461988-2e030fcf-783c-4978-96ee-92fa6c141e4d.png)

But, server was successfully started and work on latest version.
![image](https://user-images.githubusercontent.com/25010528/134462093-167fd661-4867-4707-b2f8-63282d0c984b.png)

Did I can manualy set version or fix that without `csgoserver validate`?

**Comment by BlackYuzia** [comment]
I can say what every time if you start update, then in middle or in the end that update din't complete success, build set to 0.
So, maybe better save version (saved in manifest) and rewrite in file on error update?

**Comment by johnoclockdk** [comment]
@BlackYuzia we need some more info 
lgsm ver
distro ver

ect

**Comment by BlackYuzia** [comment]
I think that works on every version of LGSM, but not sure. If you start updating, then (on middle) crash or stop (kill process or etc) and then run update again - you get 0 version and LGSM (SteamCMD?) would start validate.

Distro: **Ubuntu 16.04**
 LGSM: **v21.2.5**
 
 @johnoclockdk

**Comment by johnoclockdk** [comment]
thanks i will go recreate it now and see if i can find a fix

**Comment by BlackYuzia** [comment]
Sometimes steamcmd download all files, did steamcmd have scan validate?

Like: Scan what files are different/do not exist and download only required files. 
Because now, how I see, steamcmd just download all files, or with that question I should go to valve? 🤔

**Comment by Claiyc** [comment]
Looks to me more like a temporary issue with steamcmd than an issue with lgsm. Closing for now.
