### ISSUE TITLE
The launch priority via the nice command does not work 

### ISSUE THREAD

**Issue by Artesian1** [GameServerManagers/LinuxGSM#3572]
Hello,
I am using lgsm to run cs 1.6 and I noticed that when running through lgsm, the server's more "sluggish" fps process is not as stable as when running directly through ./hlds_run.
And this means you need to set the priority of this process to the highest through nice.
When run through lgsm with a higher priority this does not work executable = "nice -n -20 ./hlds_run"
the hlds_linux process remains at priority 0.

If you execute the command directly nice -n -20 ./hlds_run, then everything works, the process takes priority -20.

Can you tell me the correct command to run with a higher priority, or is this a defect of lgsm itself?

**Comment by johnoclockdk** [comment]
@Artesian1 it really not needed to nice anything from lgsm

**Comment by Claiyc** [comment]
Not an issue with lgsm. nice should not be necessary.
