### ISSUE TITLE
[BUG] Missing csv for Rocky 8.4

### ISSUE THREAD

**Issue by Pintuzoft** [GameServerManagers/LinuxGSM#3575]
## User Story

Im trying to start my csgo server but am getting:

$ ./csgoserver start
fetching GitHub rocky-8.4.csv...ERROR
fetching Bitbucket rocky-8.4.csv...FAIL

## Basic info

* **Distro:** [Rocky Linux 8.4]
* **Game:** [CSGO]
* **Command:** [csgoserver]
* **LinuxGSM version:** [v21.3.0]

## Further Information

From the logs I can see that it tries to fetch a csv from bitbucket and github but cant find it:

log/script/csgoserver-script.log:Sep 27 17:42:05.059 csgoserver: START: ERROR: Downloading rocky-8.4.csv
log/script/csgoserver-script.log:Sep 27 17:42:05.060 csgoserver: START: ERROR: https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/master/lgsm/data/rocky-8.4.csv
log/script/csgoserver-script.log:Sep 27 17:42:06.231 csgoserver: START: FATAL: Downloading rocky-8.4.csv
log/script/csgoserver-script.log:Sep 27 17:42:06.232 csgoserver: START: FATAL: https://bitbucket.org/GameServerManagers/LinuxGSM/raw/master/lgsm/data/rocky-8.4.csv

Im guessing the file is missing or the script uses the whole version number instead of the major release number only and so it cant find the csv file?

## To Reproduce

Steps to reproduce the behaviour:
1. ./csgoserver start

## Expected behaviour
That the csv is fetched, Im guessing to confirm the environment, and then after confirmation the server can start.

**Comment by johnoclockdk** [comment]
https://github.com/johnoclockdk/LinuxGSM/blob/master/lgsm/data/rocky8.4.csv
upload that to your files

**Comment by dgibbs64** [comment]
Thanks I will look at this tonight
