### ISSUE TITLE
[FEATURE] Devuan Linux Support

### ISSUE THREAD

**Issue by azilber** [GameServerManagers/LinuxGSM#3579]
## Basic info

* **Distro:** Devuan
* **Game:** Rust
* **Command:** Update
* **LinuxGSM version:** v21.3.0

## Further Information

With the latest LinuxGSM version on Devuan the following errors were noticed:

- checking GitHub devuan-9.csv...ERROR
- checking Bitbucket devuan-9.csv...FAIL
- Warning! LinuxGSM dependency checking currently unavailable for Devuan GNU/Linux ascii.
- shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Devuan is nearly identical to Debian, with the exception of not having systemd.   I use it for containers so there's no extra systemd running.

## Further Reading

https://www.devuan.org/

**Comment by johnoclockdk** [comment]
til note: Devuan is a fork of Debian

**Comment by azilber** [comment]
Has  this not been merged?  I'm not seeing the errors anymore with the latest versions btw, except for stuff like:
```
[ FAIL ] Starting rustserver: Could not copy any steamclient.so 64bit for the gameserver
[  OK  ] Starting rustserver: Applying steamclient.so sdk64 hardlink fix: Rust
[ FAIL ] Starting rustserver: Could not copy any steamclient.so 32bit for the gameserver
```

**Comment by h3o66** [comment]
> Has this not been merged? I'm not seeing the errors anymore with the latest versions btw, except for stuff like:
> 
> ```
> [ FAIL ] Starting rustserver: Could not copy any steamclient.so 64bit for the gameserver
> [  OK  ] Starting rustserver: Applying steamclient.so sdk64 hardlink fix: Rust
> [ FAIL ] Starting rustserver: Could not copy any steamclient.so 32bit for the gameserver
> ```

So the inital issue is fixed for you ?

**Comment by azilber** [comment]
Yep, the original issue isn't an issue anymore. 🤷
