### ISSUE TITLE
[terraria] Server Request

### ISSUE THREAD

**Issue by caycehouse** [GameServerManagers/LinuxGSM#358]
I think it would be a great idea to add Terraria to the list of servers, a lot of people like Terraria and it would be something great to add.

**Comment by xFaNaTiix** [comment]
I guess, you have to use TShock (NyxStudios/TShock) for linux. So you have to use mono. I think we should wait for the offical linux support in the new version ( http://terraria.gamepedia.com/1.3 ).

**Comment by caycehouse** [comment]
Yes, I remember using Tshock a while back I forgot about the mono dependency, it probably would be a good idea to wait for native support, thanks for the feedback.

**Comment by dgibbs64** [comment]
Will close for now. However if Native linux support is added I would be happy to give it a go :)

**Comment by xFaNaTiix** [comment]
Just a small update:
"For the long-suffering Mac/Linux users: the plan is to release 1.3 for those platforms by the end of July. The slight delay is to ensure that there are no major issues with the general release before pushing it out to brand new platforms. It's still coming, we promise :)"

**Comment by Xylemon** [comment]
Can this be reopened? There is a Linux server with the latest release. I believe it is able to be downloaded through SteamCMD but the developers are looking into releasing it outside of Steam.

**Comment by jhg21** [comment]
It's no longer in beta, by the way!
https://forums.terraria.org/index.php?threads/terraria-1-3-0-8-can-mac-linux-come-out-play.30287/

**Comment by dgibbs64** [comment]
This will be released with the development branch

**Comment by dgibbs64** [comment]
Holding until official released on the website

**Comment by dgibbs64** [comment]
Finally got around to finishing this off. Enjoy! And please report any issues https://gameservermanagers.com/lgsm/terrariaserver/
