### ISSUE TITLE
[BUG] paper minecraft Linux gsm not starting

### ISSUE THREAD

**Issue by DChrilz** [GameServerManagers/LinuxGSM#3586]
Hi, i downloaded and ran the paper MC server and recieved this error when starting it:
`[ FAIL ] Starting pmcserver: Unable to start LinuxGSM`

The log output was this:
`Sep 30 14:08:51.402 pmcserver: START: FATAL: Unable to start LinuxGSM     
Sep 30 14:08:51.408 pmcserver: START: INFO: LinuxGSM version: v21.3.1     
Sep 30 14:08:51.409 pmcserver: START: FATAL: core_exit.sh exiting with co>
Sep 30 14:09:55.029 pmcserver: INSTALL: INFO: Required dependencies alrea>
Sep 30 14:09:55.039 pmcserver: INSTALL: INFO: LinuxGSM version: v21.3.1   
Sep 30 14:09:55.040 pmcserver: INSTALL: PASS: core_exit.sh exiting with c>
Sep 30 14:25:41.562 pmcserver: START: INFO: Rotating log files`

Sorry if posting wrongly

**Comment by johnoclockdk** [comment]
> Hi, i downloaded and ran the paper MC server and recieved this error when starting it: `[ FAIL ] Starting pmcserver: Unable to start LinuxGSM`
> 
> The log output was this: `Sep 30 14:08:51.402 pmcserver: START: FATAL: Unable to start LinuxGSM Sep 30 14:08:51.408 pmcserver: START: INFO: LinuxGSM version: v21.3.1 Sep 30 14:08:51.409 pmcserver: START: FATAL: core_exit.sh exiting with co> Sep 30 14:09:55.029 pmcserver: INSTALL: INFO: Required dependencies alrea> Sep 30 14:09:55.039 pmcserver: INSTALL: INFO: LinuxGSM version: v21.3.1 Sep 30 14:09:55.040 pmcserver: INSTALL: PASS: core_exit.sh exiting with c> Sep 30 14:25:41.562 pmcserver: START: INFO: Rotating log files`
> 
> Sorry if posting wrongly

what does /home/pmcserver/log/script say

**Comment by DChrilz** [comment]
`Sep 30 14:42:13.968 pmcserver: START: FATAL: Unable to start LinuxGSM     
Sep 30 14:42:13.973 pmcserver: START: INFO: LinuxGSM version: v21.3.1     
Sep 30 14:42:13.975 pmcserver: START: FATAL: core_exit.sh exiting with with code: 1 `

**Comment by Claiyc** [comment]
Are you sure that you have the correct java version installed?

This is not a lgsm bug, should be moved to discussions.

**Comment by DChrilz** [comment]
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install curl wget file tar bzip2 gzip unzip bsdmainutils python util-linux ca-certificates binutils bc jq tmux netcat default-jre

From https://linuxgsm.com/lgsm/pmcserver/
But I see the MC server has another Java package = openjdk-16-jre which now seems to work! Thanks!
Maybe the page of dependencies should be updated to the proper  Java package under dependencies of paper mc.. Thank you alot for the help Guys!
