### ISSUE TITLE
[BUG] test-alert command shows wrong email from mailgun alert

### ISSUE THREAD

**Issue by Tamerz** [GameServerManagers/LinuxGSM#3617]
## User Story

I was testing my configured alerts and noticed that the `mailgun` alert was showing `email@example.com` even though it was configured correctly with my email address.

## Basic info

* **Distro:** [Ubuntu 21.04]
* **Game:** [Rust]
* **Command:** [test-alert]
* **LinuxGSM version:** [v21.3.2]

## Further Information

I will put in a pull request after opening this. Easy fix.

## To Reproduce

Configure mailgun alerting but not email. Rut the test-alert command.

## Expected behaviour

Test should show configured mailgun email address.

**Comment by dgibbs64** [comment]
Mailgun is now deprecated as no longer a free service available and stats show zero usage
