### ISSUE TITLE
[insserver] map variable issue

### ISSUE THREAD

**Issue by davidsielert** [GameServerManagers/LinuxGSM#362]
Unable to set game mode using the default map command it needs to come out quotes e.g. +map "station push" but adding quotes doesn't work.. I added quotes in the parms command and it works in debug mode but not in live mode so Idk what the hell is going on..

**Comment by davidsielert** [comment]
bah I got it you had to ecape the quotes .. you might consider adding something like that in by default because huge pain in the butt this was 

# Start Variables
defaultmap='\"station push\"'

**Comment by dgibbs64** [comment]
I haven't seen a map before that have 2 words maps normally are called something like de_dust on source engine games

**Comment by davidsielert** [comment]
no insurgency maps have mapname[space]mode ---- siege push etc.. its a big problem for the way the script is processing these vars without putting quotes on the map name

**Comment by davidsielert** [comment]
even using the rcon you must put quotes

**Comment by dgibbs64** [comment]
Thanks. That seems really odd thing for the developers to do. Spaces cause all sorts of issues. I will have to investigate further :-/

**Comment by Shipwreck50** [comment]
what theater are you trying to use station on as it will not work in competitive mode. I asked one of the developers and the code at present won't allow it. you can select it manually but you can not add it as a map cycle. hope that helps

**Comment by Shipwreck50** [comment]
The Tmux error I had on Centos 7 was fixed when i upgraded the server.

**Comment by Shipwreck50** [comment]
defaultmap="station push" that should work depending on the theater.

**Comment by davidsielert** [comment]
No sorry that does not work.. quotes are mandatory from command line and the only way i could get it to work was what I pasted above.. anything else will either start in firefight mode or start mapless ..

**Comment by davidsielert** [comment]
weird part is that debug mode works like that (I believe) but normal mode does not .. in my tests anyway

**Comment by dgibbs64** [comment]
Just to confirm station is a map and pish is a game mode?

**Comment by Shipwreck50** [comment]
Yes Station is a Map Push is a game mode.
defaultmap="station push" was the code to set in your insserver

I.e.
 
# Start Variables
defaultmap="market push"
maxplayers="24"
port="27001"
sourcetvport="27002"
clientport="2703"
ip="0.0.0.0"

This works fine on market however station has restriction. I have 22 servers all running on Centos 7 
The best way to admin and change maps is to use HLSW or to add source mod if you want to do it in game. 
If you let me know what OS you are using I can help.
Another way to check if station will work for you is to put it in the station mapcycle_push.txt and see if it selects it while playing.

**Comment by dgibbs64** [comment]
It may be an similar issue to what I saw with ns2server. I will check this and ensure that don't need to change anything on my end

**Comment by davidsielert** [comment]
@Shipwreck50  I'll iterate again .. defaultmap="market push" does NOT work .. in the current script at the time of the writing of this post you MUST USE defaultmap='\"station push\"' unless changes have been made ...  Problem is repeatable even now if i try to restart server with arg you just put it will not work

**Comment by dgibbs64** [comment]
I think I know the issue. I will release an update for this when possible

**Comment by Shipwreck50** [comment]
What operating system do you have.

**Comment by davidsielert** [comment]
ubuntu 1404 lts

> Shipwreck50 <mailto:notifications@github.com>
> Friday, May 22, 2015 4:33 PM
>
> What operating system do you have.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dgibbs64/linuxgsm/issues/362#issuecomment-104801724>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by dgibbs64** [comment]
Should hopefully should  now work with the release of fn_insfix
