### ISSUE TITLE
Error on both csgo and ts3 servers!

### ISSUE THREAD

**Issue by michmour** [GameServerManagers/LinuxGSM#364]
Getting these errors on both installations

ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.

**Comment by xFaNaTiix** [comment]
The check was removed. 58f1e2ace3a0a5cd2a91c4697d249152f301b55e
Your distro seems to be too old.

**Comment by dgibbs64** [comment]
I was waiting for this issue topop up. I need your distro info and the version of ca-certificates.

**Comment by michmour** [comment]
Because i dont know a lot about linux,can you tell me how i can find these infos?
Thanks!

**Comment by dgibbs64** [comment]
./csgoserver details

**Comment by dgibbs64** [comment]
Do you have the details? So i can fix.

**Comment by dgibbs64** [comment]
Closing as no details provided
