### ISSUE TITLE
[BUG]vintsserver monitor ip unavailable

### ISSUE THREAD

**Issue by Claiyc** [GameServerManagers/LinuxGSM#3658]
## User Story

The vintsserver monitor command does not seem to be using ${configip} to query. "Querying port: tcp: UNAVAILABLE:42420"

## Basic info

* **Game:** [vintserver]
* **Command:** [Monitor]
* **LinuxGSM version:** [v21.4.1]

**Comment by Claiyc** [comment]
It seems like the monitor command does not recognize ${servercfgfullpath} being set and sets ${configip} to ${unavailable} (see fn_info_game_vints()).. No idea what's going wrong there.

**Comment by h3o66** [comment]
Created a possible fix for this.
Can you maybe check the PR when you have a bit time ?

**Comment by Claiyc** [comment]
Will need to read into this again but yes I can take a look when I have time
