### ISSUE TITLE
[FEATURE]  New game support for wreckfest

### ISSUE THREAD

**Issue by njdevs21** [GameServerManagers/LinuxGSM#3660]
## User Story

As a verity player, I would like to add Wreckfest to the list of games supported.

## Basic info

* **Distro:** Ubuntu 20.04
* **Game:** Wreckfest
* **LinuxGSM version:** v20.1.3

**Comment by h3o66** [comment]
According to steamdb there is no linux native server.
https://steamdb.info/app/361580/

We do not support running gameservers through wine.
