### ISSUE TITLE
[BUG] Satisfactory changed startup parameter on 0.5.0.6 patch

### ISSUE THREAD

**Issue by 0xlord** [GameServerManagers/LinuxGSM#3661]
## User Story

As a server admin, I want to request a change to the `sfserver` startup command so that it works in an automated way after introducing `-multihome` parameter as a requirement in patch 0.5.0.6.

## Basic info

* **Distro:** [Rocky Linux 8.4]
* **Game:** [Satisfactory]
* **Command:** [start]
* **LinuxGSM version:** [v21.4.1]

## Further Information

With 0.5.0.6 update tonight CSS introduced `-multihome` as a server parameter (see wiki entry: https://satisfactory.fandom.com/wiki/Dedicated_servers). I think to address demands to have multiple instances running on the same machine but with different ips. Somehow the server crashes if the parameter is not set and the default settings 0.0.0.0 will apply. Curiousily this only applies to Linux servers. Windows server are not being affected by this. This could make this request obsolete with 0.5.0.7 however. On the other hand it could be beneficial to have this automated workaround to be sure.

I've changed common.cfg to these settings and it works now automatically without specifying the IP:

```
## Gather IP address for startup parameter
IPADDR=$(ip addr show |grep 'inet '|grep -v 127.0.0.1 |awk '{print $2}'| cut -d/ -f1)

## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
startparameters="FactoryGame -multihome=${IPADDR} -ServerQueryPort=${queryport} -BeaconPort=${beaconport} -Port=${port} -log -unattended"
```

## To Reproduce

Steps to reproduce the behaviour:
1. Update the server to 0.5.0.6
2. Start the server
3. Try to connect it or open up htop to see that the server is not running
4. Confirm with `./sfserver details`
5. Change common.cfg like described above
6. Start the server
7. Confirm it working via htop or a connection attempt

## Expected behaviour
The server will work without any issues again.

**Comment by johnoclockdk** [comment]
I will fix this tomorrow.

**Comment by dgibbs64** [comment]
Thanks. This will need to be addressed soon. Hopfully they dont need to make too many more changes like this

**Comment by 0xlord** [comment]
> Thanks. This will need to be addressed soon. Hopfully they dont need to make too many more changes like this
I have the feeling that we'll see even more changes like this due to the experimental nature of the servers current state. I will try to convince Bogdan to tell us changes like these beforehand so we could bring up fixes like these closer to the release time.

**Comment by johnoclockdk** [comment]
i have work on this so you can also set the ip if ya want to but need to figure out how to code it in now 

`ipaddr="0.0.0.0"

if [ ${ipaddr} = 0.0.0.0 ];
then
multihome=$(ip addr show |grep 'inet '|grep -v 127.0.0.1 |awk '{print $2}'| cut -d/ -f1)
else
multihome="${ipaddr}"
fi
echo "${multihome}"`

**Comment by 0xlord** [comment]
CSS fixed the Linux Server crash issue. Don't know if `-multihome` is still required: https://questions.satisfactorygame.com/post/61830560831c852052359b1c

Guess we still could benefit from the PR - just for documentation that the issue was addressed internally at CSS.

**Comment by botflakes** [comment]
CSS added a Parameter today with the release of Update 5 to the Early Access branch. If you are or want to still playing the Experimental Branch the server needs to be started with `-beta experimental` otherwise the Client-Server-Version doesn't match and you can't connect.

**Comment by botflakes** [comment]
> > CSS added a Parameter today with the release of Update 5 to the Early Access branch. If you are or want to still playing the Experimental Branch, the server needs to be started with `-beta experimental` otherwise the Client-Server-Version doesn't match and you can't connect.
> 
> this is probably only a falg for steamcmd, as this is in the wiki, not for the server itself: https://satisfactory.fandom.com/wiki/Dedicated_servers#Experimental_Branch_Selection

Yeah, should have mentioned it. Maybe make a check if the user wants to install the Early Access Branch or Experimental Branch during installation? Like `"Do you want to install the Experimental Branch?" "Y | N"`

**Comment by 0xlord** [comment]
You can set your branch in the config file. No additional parameters needed.
https://docs.linuxgsm.com/steamcmd/branch

**Comment by botflakes** [comment]
oh I see. Thanks!
