### ISSUE TITLE
[FEATURE] Show factorio server version in "details" command

### ISSUE THREAD

**Issue by dannoe** [GameServerManagers/LinuxGSM#3675]
## User Story

As a administrator, I want to check the current version of the factorio server without using the "update" command (which already displays the version). So I want to check it with the "details" command.

## Basic info

* **Game:** Factorio
* **Command:** [details]
* **LinuxGSM version:** [v20.1.3]

## Further Information

As the update command can already display the installed version and the current version, it should be no problem to display this information in the "details" command under "Factorio Server Details"

Example:
```
Factorio Server Details
================================================================================
Server name:        ezpz
Branch:             stable
Server IP:          0.0.0.0:34197
Internet IP:        127.0.0.1:34197
Server password:    1234test
RCON password:      1234test
Maxplayers:         4
Auth Token:         NOT SET
Savegame Interval:  10
Version Count:      5
// - - - new
Version: 1.1.46 linux64
// + + + new
Status:             STARTED
```

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by johnoclockdk** [comment]
this is a good idea maybe added linuxgsm version also so us support and get some more info

**Comment by dannoe** [comment]
The linuxgsm version is already displayed under fctrserver Script Details:

```
fctrserver Script Details
================================================================================
Script name:            fctrserver
LinuxGSM version:       v21.4.1
glibc required:         2.18
Discord alert:          off
Email alert:            off
Gotify alert:           off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
```

**Comment by h3o66** [comment]
Not sure how we can easily fetch the version, but the buildid from the local install should be possible for sure.

**Comment by h3o66** [comment]
Created PR to parse the version of the server.

Feel free to try my changes if they work.
