### ISSUE TITLE
[Server Request]

### ISSUE THREAD

**Issue by roguebros23** [GameServerManagers/LinuxGSM#3677]
## What game server would you like to add?

Farming Simulator 19 & 22

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

787860

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [ ] Yes
* [X] No

**Comment by dgibbs64** [comment]
If the server is not on Linux we can't support it
