### ISSUE TITLE
[BUG] Details command for TS3-Server shows unexpected Usage Help for Grep and no Ports

### ISSUE THREAD

**Issue by derklompi** [GameServerManagers/LinuxGSM#3681]
## User Story

As a user on the host, I want to view the server details with the "<script> details" command so that see all details.

## Basic info

* **Distro:** [Debian GNU/Linux 11 (bullseye)]
* **Game:** [Teamspeak 3]
* **Command:** [details]
* **LinuxGSM version:** [v21.4.1]

## Further Information

When running the "details" command it shows "Usage" Options for GREP under the "Ports"-Category and after that it lists some services but no ports.

![TS3_Ports](https://user-images.githubusercontent.com/10167026/142748074-f86e78d3-8edb-4277-ae53-133acaa30e68.PNG)

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'Game Server DIrectory'
2. Run './ts3server details'
3. Scroll down to 'Ports'

## Expected behaviour

I expect to see a list of used Ports for the Server

**Comment by h3o66** [comment]
See the connected pr, this change should fix it.

**Comment by derklompi** [comment]
Tried it out, works like a charm :)
![TS3_Ports_2](https://user-images.githubusercontent.com/10167026/142791643-419d29c5-de59-4200-ab8e-a0371f5b1faf.PNG)
