### ISSUE TITLE
[BUG] PaperMC wrong Java version

### ISSUE THREAD

**Issue by ConfusedAlex** [GameServerManagers/LinuxGSM#3689]
## User Story

As a server admin, I want install PaperMC on Ubuntu so that it doesn't crash due to wrong dependencies on the website.

## Basic info

* **Distro:** [Ubuntu 20.04.3]
* **Game:** [Minecraft PaperMC]
* **Command:** [Start]
* **LinuxGSM version:** [v21.4.1]

## Further Information

The server start command will fail because the wrong java version will be installed.

Replace "default-jre" in the Ubuntu dependencies with "openjdk-16-jre"

## To Reproduce

Steps to reproduce the behaviour:
1. Set up Ubuntu
2. Install Dependencies
3. Install Server
4. Try to start the Server
5. Get the Error

## Expected behaviour

The server starts.

**Comment by johnoclockdk** [comment]
know bug and it up to you to install java 16

**Comment by ConfusedAlex** [comment]
> know bug and it up to you to install java 16

Why is it up to me? A newbie who just found LinuxGSM would have a hard time figuring out why it isn't starting.
