### ISSUE TITLE
[new server] Staround

### ISSUE THREAD

**Issue by divn** [GameServerManagers/LinuxGSM#37]
starbound server script would be awesome

**Comment by DSDV** [comment]
If therese a testversion or s.th. like it ill be happy to help out with the testing :D

**Comment by dgibbs64** [comment]
Not yet. But I can see this is a script that people really want so this is a priority script. Meaning its one I will be doing very soon. Hopefully it won't be too complicated. Cannot remember if I need to own the game to run a server. If so I will need a copy of the game. So a donation of the game may be required to get this done. I will check and update this thread.

**Comment by Scarsz** [comment]
Oh. I could have sworn I released this before I went on vacation, sorry about that. My script is a bit outdated now and I can't work on it further because it does indeed require a purchase. I was able to work on it from a buddy sharing his Steam library with me but his library isn't shared anymore because I reinstalled my computer.

**Comment by dgibbs64** [comment]
Commit what you have so far and I should easily be able to upgrade it :-).

**Comment by Scarsz** [comment]
I'll have to mess around with a bit of the coding first because it seems to be broken currently

**Comment by DSDV** [comment]
If you send me your eMail i can send you a giftcopy :D

**Comment by dgibbs64** [comment]
my email is me@danielgibbs.co.uk. Thank you very much :D

**Comment by dgibbs64** [comment]
Gift received thank you very much for the donation. I will be working on this now.
@Scarsz commit your current work or email me and I can do the rest. Wont make me long to convert it. :)

**Comment by dgibbs64** [comment]
sbserver now released
