### ISSUE TITLE
[BUG] Broken Telegram alert

### ISSUE THREAD

**Issue by Nord1cWarr1or** [GameServerManagers/LinuxGSM#3700]
## User Story

As a LGSM user, I want send test alert on telegram, but it doesn't happen

## Basic info

* **Distro:** Debian 11
* **Game:** Counter-Strike 1.6
* **Command:** test-alert
* **LinuxGSM version:**  v21.4.1

## Further Information

Commit https://github.com/GameServerManagers/LinuxGSM/commit/44daf200834c5bf56956531ff082dc1045021253 (last commit at file `alert_telegram.sh`) broke Telegram alert.
I tried to send test-alert, but get an error:

```
[ .... ] Sending Alert csserver: Sending Telegram alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 4, column 431
[ FAIL ] Sending Alert csserver: Sending Telegram alert: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}
```

Then I copied code from previous commit (https://github.com/GameServerManagers/LinuxGSM/commit/48308ec61e6f01e83e7e127a8b25c8fda4ef1355) at this file  and everithing worked as expected.

```
[  OK  ] Sending Alert csserver: Sending Telegram alert
```

## To Reproduce

Steps to reproduce the behaviour:
1. Configure telegram alerts in lgsm config
2. Send test-alert
3. See error

## Expected behaviour
```
[  OK  ] Sending Alert csserver: Sending Telegram alert
```

**Comment by johnoclockdk** [comment]
i know this bug but from a other game #3463

**Comment by johnoclockdk** [comment]
@Nord1cWarr1or do you have any color code in alert

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or do you have any color code in alert

Sorry, but what do you mean by color code? And where it shoud be?

**Comment by Nord1cWarr1or** [comment]
Any news? @johnoclockdk @dgibbs64

**Comment by LayerFort** [comment]
I seem to experience the same issue.

When running this code directly, there is no issue.
`https://discord.com/channels/127498813903601664/135126471319617536/1066470853216321676`

Reading furthermore in forums, all files are EOL encoded for UNIX, no hidden characters found.

Another supporter from discord with their latest LGSM is able to send a test alert with the same details in common.cfg

**Comment by dgibbs64** [comment]
Just completed a refactor of alerts and did not spot any issues. Closing
