### ISSUE TITLE
[BUG] Server Monitoring kills 7 Days to Die A20 during RWG process

### ISSUE THREAD

**Issue by vinanrra** [GameServerManagers/LinuxGSM#3701]
## Basic info

* **Distro:** Ubuntu 18.04
* **Game:** 7 Days To Die
* **Command:** Monitor
* **LinuxGSM version:** v21.3.3

## Further Information

I have a Docker image that use your script and with the new update the monitor seems to be killing the server don't know how to solve it.

maybe increasing the default query delay?

Here is the issue that was rise on my repo: https://github.com/vinanrra/Docker-7DaysToDie/issues/47

## Expected behaviour

Wait server to boot up and start monitoring instead of killing the server.

**Comment by h3o66** [comment]
>maybe increasing the default query delay?

yes, you can delay the monitoring command with the parameter `querydelay="1"`
Add this to the common.cfg or the instance cfg, then the monitoring commnad will be delayed after the start.

Doc for this:
https://docs.linuxgsm.com/commands/monitor#query-delay

**Comment by vinanrra** [comment]
Seems like this error was from 7 Days To Die not from LinuxGSM, I will close it, if the error is fixed with the new 7 Days To Die update
