### ISSUE TITLE
[BUG] Barotrauma: console being detached in tmux "scrollback mode" (C-b [) completely prevents "send"ing commands, including "quit"

### ISSUE THREAD

**Issue by zoktiik** [GameServerManagers/LinuxGSM#3703]
## Basic info

* **Distro:** [Fedora 34]
* **Game:** [Barotrauma]
* **Command:** [Console]/[Send]/[Stop]
* **LinuxGSM version:** [v21.4.1]

## Further Information

Whenever I use the tmux "scrollback mode" (`C-b [`) to read earlier lines in the console and detach (`C-b d`) it in that state, the server won't be able to receive any commands. This is less of a problem when trying to `send` commands, and more of a problem when LinuxGSM tries to `stop` or `restart` the server; graceful shutdown fails because the `quit` command never goes through, and the process is killed instead. I'm not sure if there's any way to automatically check if scrollback is on and, if there's any way to automatically exit that mode and send the command through, but it might be worth looking into.

## To Reproduce

Steps to reproduce the behaviour:
1. `~/btserver console`
2. enter scrollback with `C-b [`
3. detach the console's tmux session with `C-b d`
4. `~/btserver stop` or `~/btserver restart`
5. watch as the graceful shutdown fails and the process is forcefully killed

**Comment by dgibbs64** [comment]
this seems like a tmux related but which I have no control over
