### ISSUE TITLE
[FEATURE] Barotrauma: Add master server list checking support for Baromaster

### ISSUE THREAD

**Issue by zoktiik** [GameServerManagers/LinuxGSM#3704]
## Basic info

* **Distro:** [Fedora 34]
* **Game:** [Barotrauma]
* **Command:** [Details]
* **LinuxGSM version:** [v21.4.1]

## Further Information
`~/btserver details` doesn't seem to be able to tell whether or not a server is on the master list or not, telling you that your server is not listed despite the fact that you can see your server on the list.

## To Reproduce

Steps to reproduce the behaviour:
1. Forward your Barotrauma game and query ports
2. Check the in-game server list to see if you are listed (search the name if necessary)
3. See that you are listed on the master server
4. Check `~/btserver details` to see that it says you are not listed on the master server

## Expected behaviour
For the `details` command to tell me that my server is listed on the master server, or to say that checking it is not properly supported.

**Comment by zoktiik** [comment]
To add onto the issue with details, LGSM says that the "Server Version" is 1.0.0.0 instead of 0.15.13.0 (current release), presumably as a placeholder. It's ostensibly not that important, but it might help with troubleshooting if, for example, a new version of the game releases.

**Comment by zoktiik** [comment]
Default Barotrauma master server is `http://www.undertowgames.com/baromaster` according to config_player.xml.

**Comment by h3o66** [comment]
> To add onto the issue with details, LGSM says that the "Server Version" is 1.0.0.0 instead of 0.15.13.0 (current release), presumably as a placeholder. It's ostensibly not that important, but it might help with troubleshooting if, for example, a new version of the game releases.

the version look ok with my test server (from the log):
```
Barotrauma Dedicated Server 0.15.13.0 (ReleaseLinux, branch release, revision 4e66dd7b5d)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
```

**Comment by h3o66** [comment]
> Default Barotrauma master server is `http://www.undertowgames.com/baromaster` according to config_player.xml.

Currently we do only support the steam server list, so i consider this as feature request :)

**Comment by zoktiik** [comment]
> the version look ok with my test server (from the log):

I meant the details provided by LGSM, not from the console. Arguably not that important, but it would be nice to have.
```
Barotrauma Server Details
======================
Server name:      [snip]
App ID:           1026340
Server Version:   1.0.0.0  <----
Server IP:        [snip]
Internet IP:      [snip]
Display IP:       [snip]
Server password: [snip]
True 
Players:          0/16
Current map:      [snip]
Master server:    not listed
Status:           STARTED
```
Apparently, there's also some server detail without a label that's set to `True` in that output.

**Comment by h3o66** [comment]
The version is then from gamedig, that is a seperated software.
This has nothing to do then with lgsm itself, we just get the info from gamedig and display it.

**Comment by dgibbs64** [comment]
master server list checks the steam master server only also the version is grabbed from the server query (which is currently broken to btserver. I see no way to query the bt master server so cant not use it.
