### ISSUE TITLE
[BUG] DarkRP mod for Garry's Mod server should be lower cap

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#3712]
## Bug

Using mods-install feature with Garry's Mod, DarkRP is installed without converting the mod's directory to lowercase.
Therefore, the mod isn't detected by Gmod and you can't use it without manually renaming the folder in gamemodes.

## Basic info

* **Distro:** [Any]
* **Game:** [Garry's Mod]
* **Command:** [mods-install]
* **LinuxGSM version:** [Latest]

## Fix

Mod info should be updated, the feature was already implemented by myself years ago to add lowercase conversion, it's just a matter to properly defining mod info for this to work.

I'll attempt to make a PR, though I might be rusty.

**Comment by UltimateByte** [comment]
Apparently, the issues seems to be into how `fn_mod_lowercase()` is made.
I'm investigating.

**Comment by h3o66** [comment]
Imho this is a duplicate of #1868

**Comment by UltimateByte** [comment]
Thanks @h3o66
Myself from the past already got this. 
Closing this one.
