### ISSUE TITLE
Server save intervals not saving teams[BUG]

### ISSUE THREAD

**Issue by jncwinner** [GameServerManagers/LinuxGSM#3714]
## User Story

I have been using LinuxGSM for almost a year now. I have this bug that existed in the beginning for a few months and seemed to go away for two months but resurfaced two months ago and has remained an issue ever since. The bug is when the server restarts it disbands teams every time. The way to prevent this is doing a manual save from RCON or the game console. This is frustrating when the console clearly shows a save interval every 5 minutes. 

## Basic info

* **Distro:** [Centos 8]
* **Game:** [Rust]
* **Command:** [Restart]
* **LinuxGSM version:** [v21.4.1]

## Further Information

I believe the problem lies with the restart command, more specifically the shutdown command. I Don't believe the server is saving before shutting down. This can also be confirmed as the server is resumed a couple minutes before it shut down.

## To Reproduce

Steps to reproduce the behaviour:
1. Run 'restart'
1. Run 'stop then start'
1. Run 'monitor' after an update
2. Relaunch the game
3. See teams disbanded 

## Expected behaviour
The server should save right before stopping on all these commands and save the teams in doing so. If you manually save <60 seconds the teams do not get disbanded.

**Comment by UltimateByte** [comment]
I believe this issue is kind of duplicate and related to these:
https://github.com/GameServerManagers/LinuxGSM/issues/299
https://github.com/GameServerManagers/LinuxGSM/issues/807

**Comment by johnoclockdk** [comment]
> I believe this issue is kind of duplicate and related to these: #299 #807

not true he try to tell us when he in team it get disbanded on restart

**Comment by urbels** [comment]
Same issue here and as I checked around issue is just with LGSM way it does restart.  Any fix?

**Comment by dgibbs64** [comment]
LinuxGSM stops rust by using CTRL+c stop method. I am unsure if this is still an issue. However I am closing as I am not getting many if any more reports of this issue.
