### ISSUE TITLE
[Server Request] Craftopia

### ISSUE THREAD

**Issue by elysium38711** [GameServerManagers/LinuxGSM#3727]
## What game server would you like to add?

Craftopia

## Can you link to any tutorials or guides?

https://steamcommunity.com/sharedfiles/filedetails/?id=2525156012

https://steamdb.info/app/1670340/depots/

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

1670340

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [X] Yes
* [ ] No

**Comment by h3o66** [comment]
This was included in the latest release
