### ISSUE TITLE
[BUG] Unwanted "supported" or "unknown" message

### ISSUE THREAD

**Issue by Marcin648** [GameServerManagers/LinuxGSM#3731]
## User Story
I see string "supported" on "start" command.

## Basic info

* **Distro:** Ubuntu 20.04.3 LTS
* **Game:** Any
* **Command:** start
* **LinuxGSM version:** v21.5.0

## Further Information

Probably it is debug message from deps check. "supported" is replaced by "unknown" on unsupported distro.
This LGSM is upgraded from previous version.
```
aaa@hostname:~$ ./arma3server start
supported
supported
supported
[  OK  ] Starting arma3server: server name
```

## To Reproduce

Steps to reproduce the behaviour:
1. Use start command

## Expected behaviour
See only "[  OK  ] Starting arma3server: server name" message,

**Comment by Marcin648** [comment]
Line that print this message https://github.com/GameServerManagers/LinuxGSM/blob/72b23528d892e30d0b17ec7ba5bc0ad600c25e46/lgsm/functions/info_distro.sh#L97

**Comment by h3o66** [comment]
Seems liks this was fixed with https://github.com/GameServerManagers/LinuxGSM/commit/07fcb8b720c3a7ee015fcc3c2e48fc82bde2c439 in master
So this is not shown anymore after the update

**Comment by Marcin648** [comment]
I confirm. Problem solved :)

**Comment by dgibbs64** [comment]
Thanks. I have pushed a small fix to master to resolve the issue :)
