### ISSUE TITLE
[BUG] Function scripts are needing changes.

### ISSUE THREAD

**Issue by alkaris2** [GameServerManagers/LinuxGSM#3734]
I was having some issues with the function scripts thats included with LinuxGSM, and I have to say they are really needing some changes, because they do not work in their current state.

So the issue here, I was trying sort out setting up a Rust server, but there was issues, so I wanted to try run the `fix_rust.sh` script. Unfortunately the shell script does not function as you intended. Here's what goes on in the script;

```BASH
#!/bin/bash
# LinuxGSM fix_rust.sh module
# Author: Daniel Gibbs
# Contributors: http://linuxgsm.com/contrib
# Website: https://linuxgsm.com
# Description: Resolves startup issue with Rust.

functionselfname="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"

# Fixes: [Raknet] Server Shutting Down (Shutting Down).
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${serverfiles}:${serverfiles}/RustDedicated_Data/Plugins/x86_64"

# Part of random seed feature.
# If seed is not defined by user generate a seed file.
if [ -z "${seed}" ]; then
	if [ ! -f "${datadir}/${selfname}-seed.txt" ]; then
		shuf -i 1-2147483647 -n 1 > "${datadir}/${selfname}-seed.txt"
	fi
	seed="$(cat "${datadir}/${selfname}-seed.txt")"
	randomseed=1
fi
```

Do you see the issue here in this script? Here let me point it out.

When you run this, it checking in the data directory if a file with `${selfname}-seed.txt` exists. But file does not exist, so it immediately fails when run. This `selfname` business is expecting something like `rustserver-seed.txt` or something like `1234567890-seed.txt` if that's how it suppose to generate a file.  So when you run the script you end up with this;

```
../functions/fix_rust.sh: line 17: /-seed.txt: Permission denied
cat: /-seed.txt: No such file or directory
```

throws permission denied, because of that trailing slash at the beginning like it's trying to access `/` root directory, thats also part of second issue there. You should have an `else` function in there if the file doesn't exist, because you're just assuming the file exists already.

Perhaps define where this `${datadir}` is suppose to be before you call `${datadir}`, and also replace the `-` with something else, because this character can and will be confused for a flag switch in some cases. I tried some script modifications of and the result that it ends up creating a file called `-seed.txt` and becomes unremovable because it's treating that `-`  character as a flag option like; `-s`.

---

## Script change proposals

Shuf can't be used to name the file using `${selfname}` because you need to have a name to exist already, and would involve some bit to take generated number the seed generated from the file to append it to the file name as a prefix, which would only complicate the script more than it already needs to, so just define something simple.

```BASH
#!/bin/bash
# LinuxGSM fix_rust.sh module
# Author: Daniel Gibbs
# Contributors: http://linuxgsm.com/contrib
# Website: https://linuxgsm.com
# Description: Resolves startup issue with Rust.

functionselfname="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"

# Fixes: [Raknet] Server Shutting Down (Shutting Down).
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${serverfiles}:${serverfiles}/RustDedicated_Data/Plugins/x86_64"

# define datadir location so it knows where to look.
datadir="${HOME}/lgsm/data"

# define the selfname to keep it simple.
selfname="rust"

# Part of random seed feature.
# If seed is not defined by user generate a seed file.
if [ -z "${seed}" ]; then
	if [ ! -f "${datadir}/${selfname}_seed.txt" ]; then
		shuf -i 1-2147483647 -n 1 > "${datadir}/${selfname}_seed.txt"
        else
                shuf -i 1-2147483647 -n 1 > "${datadir}/${selfname}_seed.txt"
	fi
	seed="$(cat "${datadir}/${selfname}_seed.txt")"
	randomseed=1
fi
```

this should serve as somewhat better example for other scripts that rely on generating seed text files.

**Comment by dgibbs64** [comment]
Are you trying to run the module directly?

**Comment by h3o66** [comment]
The script `fix_rust.sh` is not supposed to be run manually by the user.
All variables what are not inited here, is done by the "framework".
Not sure what you want to try at all with this.

**Comment by alkaris2** [comment]
> The script `fix_rust.sh` is not supposed to be run manually by the user. All variables what are not inited here, is done by the "framework". Not sure what you want to try at all with this.

it still stands as is because it doesn't function as its suppose to.

**Comment by h3o66** [comment]
> > The script `fix_rust.sh` is not supposed to be run manually by the user. All variables what are not inited here, is done by the "framework". Not sure what you want to try at all with this.
> 
> it still stands as is because it doesn't function as its suppose to.

I do not get your point.

**Comment by dgibbs64** [comment]
Its working absolutely fine. You are not using LinuxGSM as indeed and trying to run something that you are not meant to run.
Think of it this way. You wouldn't run a windows .dll file directly you would use the .exe instead. This is basically what you are trying to do here.
