### ISSUE TITLE
[BUG] Command line parameter needs updating.

### ISSUE THREAD

**Issue by Rusty01** [GameServerManagers/LinuxGSM#3748]
Natural Selection 2.
Debian 9 x64

Game Developers have changed the startup parameter requirement from "-mods" to -mods2".
(The change was done as the game moved to Workshop UGC, requiring server operators to use "decimal" instead of "hexadecimal" for modID's within the startup parameters. 

Needs to be updated in lgsm-config

If I simply change the -mods to -mods2, the server starts up and runs ok with mods functioning, however I get this in my console "line 24: -mods2: command not found"

Thanks!

**Comment by h3o66** [comment]
Steam annoucement for this:
https://steamcommunity.com/games/ns2/announcements/detail/5917165051353982119
