### ISSUE TITLE
[BUG] q3server does not cycle maps by default

### ISSUE THREAD

**Issue by kvnvallis** [GameServerManagers/LinuxGSM#3749]
## User Story

I installed the quake 3 server and found that it does not cycle through maps at the end of each round. Instead it loads the same map over and over again. 

## Basic info

* **Distro:**  Ubuntu 20.04.3 LTS
* **Game:**  Quake 3 Arena
* **LinuxGSM version:**  v21.5.0 

## Further Information

I was able to fix this by:

- adding `vstr m1` at the end of _q3server.cfg_
- moving the _+map_ option before the _+exec_ option in _startparameters_ 

The map cycle is already defined in _q3server.cfg_ but the _vstr m1_ line is needed to actually run it. Modifying the startparameters is also required, otherwise _+map ${defaultmap}_ will override the map cycle from _q3server.cfg_. It looks like these files exist in two different repositories.

- serverfiles/baseq3/q3server.cfg
- lgsm/config-default/config-lgsm/q3server/_default.cfg

I ran the server with the following _startparameters_ and I can confirm that _servercfg_ takes precedence over _defaultmap_. The map cycle will begin if it is configured correctly in _q3server.cfg_, but if not then the _defaultmap_ will still load as specified.

    startparameters="+set sv_punkbuster 0 +set fs_basepath ${serverfiles} +set dedicated 2 +set com_hunkMegs 32 +set net_ip ${ip} +set net_port ${port} +map ${defaultmap} +exec ${servercfg}"

Last two lines of my _q3server.cfg_:

    //Begin the map cycle at m1
    vstr m1

## To Reproduce

Install q3server and start it with the default settings, or `set timelimit 1` in the config so the round ends quickly

## Expected behaviour

The server should load a new map at the end of each round.

**Comment by dgibbs64** [comment]
Already added the maprotation fix. Will update the parameters for next release
