### ISSUE TITLE
[BUG] jq: error (at <stdin>:0): Expected JSON value (while parsing '')

### ISSUE THREAD

**Issue by Frag1337** [GameServerManagers/LinuxGSM#3762]
## User Story

Starting my CS:GO server with ```./csgoserver start``` double prints  ```jq: error (at <stdin>:0): Expected JSON value (while parsing '')``` but the server still successfully starts.

## Basic info

* **Distro:** [Debian GNU/Linux 10]
* **Game:** [CS:GO]
* **Command:** [Start]
* **LinuxGSM version:** [v21.5.1]

## To Reproduce

Steps to reproduce the behaviour:
1. Start Server
2. See double print Error

```
*******@*******~$ ./csgoserver start
jq: error (at <stdin>:0): Expected JSON value (while parsing '')
jq: error (at <stdin>:0): Expected JSON value (while parsing '')
```

**Comment by maclarens** [comment]
jq: error (at <stdin>:0): Expected JSON value (while parsing '')
same bug on left 4 dead 2

**Comment by tt2468** [comment]
Same here, Ubuntu 20.04

**Comment by maclarens** [comment]
debian 10 if not apt-get upgrade then fine for me!

**Comment by olokos** [comment]
Same problem here Ubuntu 20.04 with all the latest updates from all corresponding PPAs.

Odd thing is that only first 2 out of 6 servers I have have this bug, all of them being csgoservers.

**Comment by h3o66** [comment]
I hope the connected pr fixes this with the next release.
This can occour as well when no query port is set for a game.
If you have this problem as well with another game (not CSGO) then feel free to test this.

**Comment by olokos** [comment]
I'm pretty sure it did fix the issue, thanks!

**Comment by Fasteroid** [comment]
Garry's Mod, still experiencing this issue.  Some idiot crashed my server and now I can't start it normally.
Ubuntu 20.04.4 LTS

**Comment by olokos** [comment]
> Garry's Mod, still experiencing this issue. Some idiot crashed my server and now I can't start it normally. Ubuntu 20.04.4 LTS
> 
> EDIT: My LGSM is still on v21.5.1 and has not updated for some reason... how to?

If you would read the issue, you would know that this bug did not prevent server from starting at all.

to update lgsm you do `./gameserver u` - RTFM!

**Comment by h3o66** [comment]
> Garry's Mod, still experiencing this issue. Some idiot crashed my server and now I can't start it normally. Ubuntu 20.04.4 LTS
> 
> EDIT: My LGSM is still on v21.5.1 and has not updated for some reason... how to?

Please condider to get help via the discussions or via the LinuxGSM 
Discord server

**Comment by Fasteroid** [comment]
> > ~~Garry's Mod, still experiencing this issue. Some idiot crashed my server and now I can't start it normally. Ubuntu 20.04.4 LTS~~
> > ~~EDIT: My LGSM is still on v21.5.1 and has not updated for some reason... how to?~~
> 
> If you would read the issue, you would know that this bug did not prevent server from starting at all.
> 
> to update lgsm you do `./gameserver u` - RTFM! :)

Thanks for the info on how to update.  Been doing this for a while and somehow never updated the script.

Turns out the server not starting correctly was unrelated to this (weekly steam maintenence = no workshop collection = missing gm_bigcity).  I just assumed my server not starting was due to this bug I never remembered seeing.  Apologies for being stupid and not reading the whole issue.

**Comment by olokos** [comment]
@Fasteroid but you still haven't read the docs or guide at all otherwise you would have known why it doesn't update the script ;)

Anyway, just do:
`./gameserver` and you will know what to do from there :)

**Comment by Fasteroid** [comment]
I do not remember seeing such a command listed in the list you get from running `./gameserver` with no args, but perhaps I missed it.

For future reference in case anyone ends up here with the same question, the command to update LGSM itself is `./gameserver update-lgsm`, which can be found on the docs [here](https://docs.linuxgsm.com).  I did check them actually, after letting you know your command doesn't work ;)

Would've at least been nice to link the docs imo, but whatever.  Mystery is solved for now.
