### ISSUE TITLE
[FEATURE] Add support for java flags/options in Minecraft

### ISSUE THREAD

**Issue by TurboSlayer** [GameServerManagers/LinuxGSM#3766]
## User Story

As a minecraft server owner, I want to use java flags/options when running a minecraft server so that I can set options such as -Xms.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Minecraft]
* **Command:** [start]
* **LinuxGSM version:** [v21.5.1]

## Further Information

LGSM allows you to add parameters after -jar but not before it. This means flags such as -Xms cannot be set. 
From Oracle: `java [ options ] -jar file.jar [ arguments ]`

The part in question is the [ options ] part. The startparameters variable only allows you to set the [ arguments ] bit.

**Comment by cclecle** [comment]
As a workaround you can override preexecutable var in your game-specific cfg.

**Comment by TurboSlayer** [comment]
Well thanks for letting me know. I'll check it out.
