### ISSUE TITLE
Add Minecraft Server to Server List

### ISSUE THREAD

**Issue by RetainedCoda** [GameServerManagers/LinuxGSM#3768]
## What game server would you like to add?

Minecraft

## Can you link to any tutorials or guides?

https://www.youtube.com/watch?v=zOjcJzNMW2M (Skip to 3:16 because timestamps before that are Linode One Click)

## Is the server on Steam?

* [ ] Yes
* [ X ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [ X ] Yes
* [ ] No

**Comment by RetainedCoda** [comment]
Wait sorry that is already there I am so sorry.

**Comment by dgibbs64** [comment]
https://linuxgsm.com/servers/mcserver/

https://linuxgsm.com/servers/mcbserver/

https://linuxgsm.com/servers/pmcserver/

https://linuxgsm.com/servers/wmcserver/
