### ISSUE TITLE
[BUG] Mumble update uses different binary names

### ISSUE THREAD

**Issue by busheezy** [GameServerManagers/LinuxGSM#3777]
## User Story

As a mumble server user, I want to be able to update with LGSM.

## Basic info

* **Distro:** [Debian 11]
* **Game:** [Mumble]
* **Command:** [Update]
* **LinuxGSM version:** [v21.5.1]

## Further Information

```
mumble@wimpy:~$ ./vs/mumbleserver update
[ FAIL ] Updating mumbleserver: Checking remote build: mumble.info
mumble@wimpy:~$
```

A user will see the above message when currently trying to update.

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/update_mumble.sh#L10

There are multiple references to murmur-static which is no longer the name.

https://github.com/mumble-voip/mumble/releases

Thanks

**Comment by h3o66** [comment]
I have a fix for the version parsing, but it seems that there is no linux build in the latest release.
See this branch as ref:
https://github.com/h3o66/LinuxGSM/tree/fix/3777-mumble-update

**Comment by dgibbs64** [comment]
Can confirm no 1.4 build for Linux https://github.com/mumble-voip/mumble/issues/5484#issuecomment-1018728414

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/4128
