### ISSUE TITLE
[GMOD] Error when creating a server 

### ISSUE THREAD

**Issue by AaVoK4** [GameServerManagers/LinuxGSM#379]
Hi ^_^

Today i wanted to make a Garry's mod server for me and my friend.

I install my script on my VPS etc..

When I type   ./gmodserver install the console tell me : 

-bash ./gmodserver permission denied (Im withe gmodserver user)

Help me :c

**Comment by Scarsz** [comment]
`chmod +x ./gmodserver`

**Comment by AaVoK4** [comment]
Thanks for the answer but it doesn't work ! even in Root...

![sans titre](https://cloud.githubusercontent.com/assets/12400047/7591466/4ef45e56-f8ce-11e4-81df-2877bb7616c2.png)

**Comment by dgibbs64** [comment]
print screen 
````ls -al /home/gmodeserver````

please

**Comment by dgibbs64** [comment]
Is this still an issue or can it be closed?

**Comment by AaVoK4** [comment]
Thanks for the help :) it was just a bug o.o you can close :) :+1:
