### ISSUE TITLE
[BUG] Arma3server update breaks while using a branch in the common.cfg

### ISSUE THREAD

**Issue by mcflyjunior** [GameServerManagers/LinuxGSM#3794]
## User Story

As a server admin, I was trying to get my ./gameserver update command to work so I could configure my crontabs per the basic useage instructions and not have to manually update the server. Setting a branch for my gameserver seems to break the update command, resulting in me unable to have that crontab up, and my headless clients reconnecting at random.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Arma 3]
* **Command:** [Update/Check Update]
* **LinuxGSM version:** [v21.5.1]

## Further Information

After troubleshooting, I've narrowed it to the presence of specifying a branch formatted such as the default.cfg into my common.cfg.
## To Reproduce

Steps to reproduce the behaviour:
1. Create fresh user.
2. download and install Linuxgsm per https://linuxgsm.com/servers/arma3server/
2a. at this point ./arma3server update works
3. once steam user is set and server is installed, specify the profiling branch in common.cfg
4. Run ./arma3server update and it will fail checking the remote build.
## Expected behaviour
It should check against the latest branch using the information provided, instead of failing to check the remote build.
```
# SteamCMD Branch | https://docs.linuxgsm.com/steamcmd/branch
branch="profiling"
betapassword="CautionSpecialProfilingAndTestingBranchArma3"
```

__________________________

Placing the SteamCMD branch command into arma3server.cfg arma3server-hc... etc seems to avoid the issue entirely.

**Comment by h3o66** [comment]
Works for me.
I cannot reproduce the problem on my side.
The only idea i have, is that you can check the logs from steamcmd:
Dir: `~/.local/share/Steam/logs/`
