### ISSUE TITLE
[BUG] mumble server cannot be installed

### ISSUE THREAD

**Issue by kdulep** [GameServerManagers/LinuxGSM#3799]
## Basic info

* **Distro:** [Debian 11.2]
* **Game:** [Mumble]
* **Command:** [Install]
* **LinuxGSM version:** [v21.5.1]

## Further Information
Server install failed

## To Reproduce

Try to install Mumble server
[ FAIL ] Updating mumbleserver: Checking remote build:

## Expected behaviour
server installed

**Comment by Claiyc** [comment]
Duplicate of #3777
