### ISSUE TITLE
[BUG] Warfork - Game Server Binary disclaimer is incorrect

### ISSUE THREAD

**Issue by Warfork** [GameServerManagers/LinuxGSM#3800]
>  Game Server Binary
Only 64-Bit game server binary is available.

https://linuxgsm.com/servers/wfserver/

There are 32 and 64 bit game server binaries available.

**Comment by h3o66** [comment]
ootb we only support only the 64 bin binary - to use the 32bit binary you would need to manually set it in the config

**Comment by dgibbs64** [comment]
thanks @Warfork this is correct LinuxGSM will always default to 64-bit if its available. I maybe need to re-word the website how since we no longer support 32-bit distros.
