### ISSUE TITLE
[FEATURE] Support Rust "queryport" variable

### ISSUE THREAD

**Issue by xibalbus** [GameServerManagers/LinuxGSM#3801]
## User Story

As a server admin, I want expose Rust queryport on a different port than default so I can run a private whitelisted server.
This is described on the Facepunch wiki here: https://wiki.facepunch.com/rust/Creating_a_hidden_whitelisted_server

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Rust]
* **Command:** [Monitor]
* **LinuxGSM version:** [v20.1.3]

## Further Information

Currently I can do this by placing "queryport=65000" in server.cfg, but the "monitor" command causes the server to restart constantly as LGSM sets the "queryport" variable to be the same as the "port" on this line here: https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/info_game.sh#L1385

This means the monitor command always fails.

If I place a "queryport=65000" in the rustserver.cfg, and amend line 1385 of info_game.sh to use that "queryport" variable instead of "port", then the check works.

It would be good if "queryport" was a distinct variable in _default.cfg, and if info_game.sh used this.

**Comment by xibalbus** [comment]
![image](https://user-images.githubusercontent.com/2588404/199811666-1e4b9db9-196c-48e2-ae14-26b241e69526.png)
Looks like this is going to become a requirement

**Comment by un-boxing-man** [comment]
Rust servers will NEED query port for servers to remain in server browser after February 2nd update
