### ISSUE TITLE
avserver fails to open game port (LGSM 21.5.1 fails vs LGSM 21.2.4 works)

### ISSUE THREAD

**Issue by jhawker09** [GameServerManagers/LinuxGSM#3813]
### Discussed in https://github.com/GameServerManagers/LinuxGSM/discussions/3806

<div type='discussions-op-text'>

<sup>Originally posted by **jhawker09** March  3, 2022</sup>
avserver starts but it fails to open the game server port, shows the port as 0.  It  also lists a grep error ("grep: Unmatched [, [^, [:, [., or [=") when running the details command. I tried this on a couple VMs with a fresh install for LGSM 21.5.1.

-----------------------------------------------
avserver@dns-gs1:~$ ./avserver details

Distro Details

======================================================================================
Date:      Fri Mar  4 02:15:33 UTC 2022
Distro:    Ubuntu 20.04.3 LTS
Arch:      x86_64
Kernel:    5.4.0-90-generic
Hostname:  dns-gs1
Uptime:    112d, 13h, 45m
tmux:      tmux 3.0a
glibc:     2.31

Server Resource

======================================================================================
CPU         
Model:      AMD Ryzen 7 3700X 8-Core Processor
Cores:      6
Frequency:  3600.000MHz
Avg Load:   0.18, 0.17, 0.21

Memory     
Mem:       total  used   free   cached  available
Physical:  9.8GB  4.9GB  4.6GB  3.4GB   4.6GB
Swap:      4.0GB  1.3MB  4.0GB

Storage
Filesystem:  /dev/mapper/ubuntu--vg-ubuntu--lv
Total:       44G
Used:        15G
Available:   27G

Network
Interface:    ens160
Link Speed:   10000Mb/s
IP:           10.0.1.101
Internet IP:  <REDACTED>

Game Server Resource Usage

======================================================================================
CPU Used:  16.3%
Mem Used:  1.7%   170MB

Storage
Total:        397M
Serverfiles:  120M

Avorion Server Details

======================================================================================
Server name:      Avorion Server
App ID:           565060
Server IP:        10.0.1.101:0
Internet IP:      <REDACTED>:0
Server password:  NOT SET
RCON enabled:     UNAVAILABLE
RCON password:    NOT SET
Maxplayers:       10
Status:           STARTED

avserver Script Details

======================================================================================
Script name:            avserver
LinuxGSM version:       v21.5.1
glibc required:         2.15
Discord alert:          off
Email alert:            off
Gotify alert:           off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
Telegram alert:         off
Update on start:        off
User:                   avserver
Location:               /home/avserver
Config file:            /home/avserver/serverfiles/galaxy/avserver/server.ini

Backups

======================================================================================
No Backups created

Command-line Parameters

======================================================================================
./bin/AvorionServer --galaxy-name avserver --ip 10.0.1.101 --datapath /home/avserver/serverfiles/galaxy

Ports

======================================================================================
Change ports by editing the parameters in:
/home/avserver/lgsm/config-lgsm/avserver

Useful port diagnostic command:
ss -tuplwn | grep AvorionServer

grep: Unmatched [, [^, [:, [., or [=
DESCRIPTION   PORT   PROTOCOL  LISTEN
Game          0      udp       0
Query         27003  udp       1
Steam Master  27021  udp       0
Steam Query   27020  udp       0
RCON          27015  tcp       0

Status: STARTED

---------------------------------
avserver@dns-gs1:~$ ss -tuplwn | grep AvorionServer
udp     UNCONN   0        0                0.0.0.0:27000          0.0.0.0:*      users:(("AvorionServer",pid=178214,fd=15))                                     
udp     UNCONN   0        0                0.0.0.0:27003          0.0.0.0:*      users:(("AvorionServer",pid=178214,fd=19))                                     
tcp     LISTEN   0        128              0.0.0.0:27000          0.0.0.0:*      users:(("AvorionServer",pid=178214,fd=11))  

-------------------------------

I have another server that is running on LGSM version 21.2.4 that works:

--------------------------------------
avserver@linuxapps:~$ ./avserver details

Distro Details

======================================================================================
Date:      
Distro:    Ubuntu 18.04.6 LTS
Arch:      x86_64
Kernel:    4.15.0-112-generic
Hostname:  linuxapps
Uptime:    112d, 14h, 7m
tmux:      tmux 2.6
glibc:     2.27

Server Resource

======================================================================================
CPU         
Model:      AMD FX(tm)-8320 Eight-Core Processor
Cores:      5
Frequency:  3492.429MHz
Avg Load:   0.23, 0.13, 0.10

Memory     
Mem:       total  used   free   cached  available
Physical:  12GB   841MB  11GB   3.6GB   11GB
Swap:      4.0GB  19MB   4.0GB

Storage
Filesystem:  /dev/sda2
Total:       59G
Used:        41G
Available:   16G

Network
IP:           0.0.0.0
Internet IP:  <REDACTED>

Game Server Resource Usage

======================================================================================
CPU Used:  32.9%
Mem Used:  2.5%   311MB

Storage
Total:        1.9G
Serverfiles:  742M
Backups:      757M

Avorion Server Details

======================================================================================
Server name:      DaGameroom
App ID:           565060
Server IP:        0.0.0.0:27000
Internet IP:      <REDACTED>:27000
Server password:  <REDACTED>
RCON enabled:     false
RCON password:    NOT SET
Maxplayers:       10
Status:           STARTED

avserver Script Details

======================================================================================
Script name:            avserver
LinuxGSM version:       v21.2.4
glibc required:         2.15
Discord alert:          off
Email alert:            off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
Telegram alert:         off
Update on start:        off
User:                   avserver
Location:               /home/avserver
Config file:            /home/avserver/serverfiles/galaxy/avserver/server.ini

Backups

======================================================================================
No. of backups:  1
Latest backup:
    date:        Mon Jan 31 00:08:31 UTC 2022 (32 days ago)
    file:        /home/avserver/lgsm/backup/avserver-2022-01-31-000720.tar.gz
    size:        757M

Command-line Parameters

======================================================================================
./server.sh --galaxy-name avserver --ip 0.0.0.0 --datapath /home/avserver/serverfiles/galaxy 

Ports

======================================================================================
Change ports by editing the parameters in:
/home/avserver/lgsm/config-lgsm/avserver

Useful port diagnostic command:
netstat -atunp | grep Avorion

DESCRIPTION  DIRECTION  PORT   PROTOCOL
Game       INBOUND    27000  udp
RCON       INBOUND    27015  tcp

Status: STARTED

------------------------------------------
avserver@linuxapps:~$ netstat -atunp | grep Avorion
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.0.1.49:53509         162.254.192.108:27017   ESTABLISHED 9110/./bin/AvorionS 
udp        0      0 0.0.0.0:27003           0.0.0.0:*                           9110/./bin/AvorionS 
udp        0      0 0.0.0.0:27020           0.0.0.0:*                           9110/./bin/AvorionS 
udp        0      0 0.0.0.0:27021           0.0.0.0:*                           9110/./bin/AvorionS</div>

**Comment by h3o66** [comment]
Found the bug.
Will be fixed with the next release.
