### ISSUE TITLE
[BUG] LinuxGSM unable to install openjdk-16-jre for Debian 11

### ISSUE THREAD

**Issue by copycat240** [GameServerManagers/LinuxGSM#3822]
## User Story

When I was installing PZ through LinuxGSM noticed that the auto install didn't install all the dependencies.

## Basic info

* **Distro:** Debian 11
* **Game:** Project Zomboid
* **Command:** Install
* **LinuxGSM version:** v21.5.1

## Further Information

when installing Project Zomboid and deps will fail to install openjdk-16-jre on Debian 11 the reason for is the packaged is not found.
Potential fixes is change deps version to openjdk-17-jre.
quick look through of the source files reveals this could be a potential bug for Rising World too.

## To Reproduce
1. `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh pzserver`
2. `sudo ./pzserver install`
**OR**
`sudo apt install openjdk-16-jre `
## Expected behavior

install openjdk-16-jre and continue setup.

**Comment by h3o66** [comment]
Created PR to fix this.
openjdk 16 does seem not to exist for debian 11 - changed to openjdk 17
