### ISSUE TITLE
[BUG]fn_info_game_squad wrong queryport variable

### ISSUE THREAD

**Issue by Claiyc** [GameServerManagers/LinuxGSM#3823]
fn_info_game_squad ${queryport} being initialized using ${port:-"0"} (should be ${queryport:-"0"}). Results in details command displaying same values for Port and QueryPort.

## Basic info

* **Distro:** [Ubuntu 20.04]
* **Game:** [Squadserver]
* **Command:** [Details]
* **LinuxGSM version:** [v21.5.1]

## Expected behaviour
QueryPort shown via the details command should be the actual QueryPort defined in lgsm config.

**Comment by h3o66** [comment]
Created PR for this.
