### ISSUE TITLE
[Feature]: Add Gentoo Distro

### ISSUE THREAD

**Issue by tmccaff** [GameServerManagers/LinuxGSM#3831]
## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** Ubuntu 20.04
* **Game:** Garry's Mod
* command: monitor
* **LinuxGSM version:** v20.1.3

## Further Information

A clear description of what the feature is and any ideas on how to achieve this.

## Further Reading

Provide any useful documentation or resources that might help.

**Comment by h3o66** [comment]
Not sure for what reason we should support gentoo.
If you want to have it supported, maybe contribute the support for it :)

**Comment by tmccaff** [comment]
What files does linuxgsm use in order to test the distribution?
    On Friday, April 1, 2022, 12:54:51 PM EDT, Christian ***@***.***> wrote:  
 
 


Not sure for what reason we should support gentoo.
If you want to have it supported, maybe contribute the support for it :)

**Comment by h3o66** [comment]
There is a csv per distroversion in lgsm/data in the repo
For gentoo you probably need to integrate as well fully the package manager.
Teh modifications need to be done in `lgsm/functions/check_deps.sh` - not sure if there are additional places
