### ISSUE TITLE
[FEATURE] Integrate BepInEx into LinuxGSM independent of ValheimPlus

### ISSUE THREAD

**Issue by Albonation** [GameServerManagers/LinuxGSM#3840]
## User Story

As a user of LinuxGSM to get a Valheim dedicated game server up and running, I would like to use ./vhserver mods-install to list BepInEx (for Valheim) separate from ValheimPlus. Currently ./vhserver mods-install only lists ValheimPlus which bundles BepInEx with it, but there are individuals who would not want to use ValheimPlus. So, having an option to install ValheimPlus OR BepInEx would be appreciated.

## Basic info
Distro:    Debian GNU/Linux 10 (buster)
Arch:      x86_64
Kernel:    4.19.0-20-amd64

## Further Information

I was able to achieve this on my own by installing BepInEx manually and adjusting the file "start_server_bepinex.sh" so that the line starting with "exec ./valheim_server.x86_64 reads as the following (as opposed to what it says originally):
exec ./valheim_server.x86_64 "$@"

Before making that change, the file "start_server_bepinex.sh" would not allow the instance configuration files from LinuxGSM to do anything and I had to troubleshoot why I was getting the wrong password. Because start_server_bepinex.sh was setting the password.

**Comment by ottyn** [comment]
This would be helpful also for other games that have mods that use BepInEx.  For instance 7 Days to Die with the Undead Legacy overhaul.  It comes bundled with a specific version of BepInEx, but could use a flag in LGSM to have it run the BepInEx launcher instead of the default startserver.sh file.

**Comment by h3o66** [comment]
Needed for the integration/update of beepinex:
Api docs from thunderstore:
https://valheim.thunderstore.io/api/docs/

example to get the latest beepinex version from thunderstore:
`curl -s -X GET "https://valheim.thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/" -H  "accept: application/json"`

**Comment by MLNW** [comment]
I see that a PR for this has been merged, ergo it should be included in the next release? Is there an ETA for the next release?

**Comment by h3o66** [comment]
> is this usable normally? how can i use it in my current install?

You should be able to use this with version 23.1.0 and later.

to install bepinex just use:
`./vhserver mods-install` (or `mi` as short command of lgsm)

then type `bepinexvh` to install it.

**Comment by mamolli** [comment]
I am getting a lot of:
`ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
After installing and running `./vhserver start`
