### ISSUE TITLE
[BUG] DayZ server use the wrong AppID, 1042420) instead of 223350

### ISSUE THREAD

**Issue by LeMyst** [GameServerManagers/LinuxGSM#3847]
## User Story

DayZ server use the wrong AppID: "DayZ Experimental Server" (1042420) instead of "DayZ Server" (223350)

## Expected behaviour

Use AppID 223350

**Comment by LeMyst** [comment]
PR #3848

**Comment by Claiyc** [comment]
Invalid, linux is currently not supported on main dayz repo:
![grafik](https://user-images.githubusercontent.com/58397976/165038097-ba40bab6-2ba9-4bd6-b24d-e6e470c92c93.png)
