### ISSUE TITLE
[csgoserver] Some error in restart/start functions

### ISSUE THREAD

**Issue by xMqt** [GameServerManagers/LinuxGSM#385]
Hi Daniel,

As previsouly mentioned on Steam, I tried re-installing everything from zero and unfortunately I am still facing the same issue. It may be linked to the recent update Valve made on CS:GO servers as I was not having this issue some days ago.

Can you please have a look and let me know if the functions are broken?

HIDDEN:~$ ./csgoserver restart
[ .... ] Stopping csgo-server: FFA DeathMatch Dust2 - Tick 128
[  OK  ] Stopping csgo-server: FFA DeathMatch Dust2 - Tick 128  
[ .... ] Starting csgo-server: FFA DeathMatch Dust2 - Tick 128
[ .... ] Update csgo-server: Checking for update
[  OK  ] Update csgo-server: Checking for update: Server logsgrep: /home/csgodm1                                               /log/console/csgo-server-console.log: No such file or directory

/home/csgodm1/functions/fn_update_check: line 77: [: : integer expression expect
[  OK  ] Update csgo-server: Checking for update: Server logs: No update requested
[  OK  ] Update csgo-server: Checking for update: SteamCMD

No update available:
        Current version: 621988
        Available version: 621988
        https://steamdb.info/app/740/

[  OK  ] Update csgo-server: No update available
[  OK  ] Starting csgo-server: FFA DeathMatch Dust2 - Tick 128

**Comment by Scarsz** [comment]
`./csgoserver details`

**Comment by xMqt** [comment]
HIDDEN:~$ ./csgoserver details
loading fn_details...OK
loading fn_details_distro...OK

Distro Details
================================================================================
Distro:    Debian 8.0
Arch:      x86_64
Kernel:    3.14.32-xxxx-grs-ipv6-64
Hostname:  HIDDEN
tmux:      tmux 1.9
GLIBC:     2.19

Performance
================================================================================
Uptime:    0d, 21h, 10m
Avg Load:  0.50, 0.39, 0.36

Mem:       total   used   free
Physical:  31G     11G    20G
Swap:      1.5G    0B     1.5G

Disk Usage
================================================================================
Disk available:  76G
Serverfiles:     9.7G

Counter Strike: Global Offensive Server Details
================================================================================
Server name:    FFA DeathMatch Dust2 - Tick 128
Server IP:      HIDDEN
RCON password: HIDDEN
Status:         ONLINE

Service name:  csgo-server
User:          csgodm1
Location:      /home/csgodm1
Config file:   /home/csgodm1/serverfiles/csgo/cfg/csgo-server.cfg

Backups
================================================================================
No Backups created

Command-line Parameters
================================================================================
./srcds_run -game csgo -usercon -strictportbind -ip HIDDEN -port 27015 +cl                                                        ientport 27005 +tv_port 27020 -tickrate 128 +map de_dust2 +servercfgfile csgo-se                                                        rver.cfg -maxplayers_override 16 +mapgroup mg_active +game_mode 1 +game_type 0 +                                                        host_workshop_collection  +workshop_start_map  -authkey

Ports
================================================================================
Change ports by editing the command-line
parameters in csgoserver.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

**Comment by dgibbs64** [comment]
The updater has not picked up any logs from the console for some reason

**Comment by dgibbs64** [comment]
I have done a bunch of updates which might resolve the issue. Delete the functions directory and test please

**Comment by xMqt** [comment]
Hey thanks for the update!

Unfortunately still not working:


./csgoserver restart
[  OK  ] Stopping csgo-server: FFA DeathMatch Dust2 - Tick 128
[ .... ] Update csgo-server: Checking for update
[ .... ] Update csgo-server: Checking for update: Server logsgrep: /home/csgodm1/log/console/csgo-server-console.log: No such file or directory
/home/csgodm1/functions/fn_update_check: line 80: [: : integer expression expected
[  OK  ] Update csgo-server: Checking for update: Server logs: No update requested
[  OK  ] Update csgo-server: Checking for update: SteamCMD

No update available:
        Current version: 621988
        Available version: 621988
        https://steamdb.info/app/740/

[  OK  ] Update csgo-server: No update available
[  OK  ] Starting csgo-server: FFA DeathMatch Dust2 - Tick 128
