### ISSUE TITLE
[Server Request] Necesse

### ISSUE THREAD

**Issue by PISTOLCUPCAKES** [GameServerManagers/LinuxGSM#3852]
## What game server would you like to add?

Necesse

## Can you link to any tutorials or guides?

https://necessewiki.com/Multiplayer-Linux

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

1169370

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by crawforc3** [comment]
Is there any documentation on adding new game servers to LGSM? I could pick this one up.
