### ISSUE TITLE
[Server Request] - Core Keeper

### ISSUE THREAD

**Issue by jrb2040** [GameServerManagers/LinuxGSM#3855]
## What game server would you like to add?

Core Keeper

## Can you link to any tutorials or guides?

(https://steamdb.info/app/1963720/config/)

## Is the server on Steam?

* [X] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

 1963720

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [X] Yes
* [ ] No

**Comment by mbillich** [comment]
the appid for the server is 1963720

**Comment by jrb2040** [comment]
Ah good catch, thank you. I will update the request

**Comment by h3o66** [comment]
First draft for the Server is up, see connected PR

**Comment by h3o66** [comment]
As they now released the option to set the port, i think this is now ready to be tested.

**Comment by Panzke** [comment]
I have the problem that walls can not be broken. Similar to what is described here:

https://www.reddit.com/r/CoreKeeperGame/comments/vetk85/setup_a_dedicated_server_and_there_is_an/

The solution is probably already mentioned there. It seems that the world is generated via the graphics card.

Here it is also pointed out again that the command -nographics is to be avoided:

https://www.reddit.com/r/CoreKeeperGame/comments/uym86p/dedicated_core_keeper_server_tips_tricks/

**Comment by h3o66** [comment]
Updated now the PR to use xvfb and set a log setting, as it does not output any more logs i added as well the logfile paramter.

Currently a known issue is the stop type of the server is kind of broken

**Comment by arcao** [comment]
Any new progress?

**Comment by h3o66** [comment]
> Any new progress?

My PR is already finished.
Feel free to test it and give feedback.

**Comment by Oline** [comment]
Any news on its official inclusion?
Any help needed ?
Keeping a server running off the official release is a pain.

**Comment by TrythisTV** [comment]
I'm not sure how best to get this to who needs to see it, but I got constant segfaults when trying to start ckserver via lgsm, there is one dependency that doesn't get checked during install, or at least installing libxi6 in my headless server (no gpu, hosted in some datacenter, ubuntu 20.04.5 LTS) solved the segfault issue.

So perhaps adding libxi6 to the dependency checks would be beneficial?

**Comment by dgibbs64** [comment]
@TrythisTV If  libxi6 needs to be added as a dependency please raise a new issue and we can get it added thanks :)
