### ISSUE TITLE
[BUG] Ubuntu 22.04 is not (really) supported

### ISSUE THREAD

**Issue by ElieDeloumeau** [GameServerManagers/LinuxGSM#3856]
## User Story

As a of csgoserver, I want to install it on Ubuntu 22.04.

## Basic info

* **Distro:** Ubuntu 22.04
* **Game:** CS:GO
* **Command:** install
* **LinuxGSM version:** v21.5.1

## Further Information

The step `Checking Dependencies` is failing due to two wrong packages names in https://github.com/GameServerManagers/LinuxGSM/blob/0e6e09da2bf340d410dfec607de8aeb4a6416423/lgsm/data/ubuntu-22.04.csv

* `lib32gcc-s1` should be `lib32gcc-s1-amd64-cross` ?
* `lib32stdc++6` should be `lib32stdc++6-amd64-cross` ?

## To Reproduce

Steps to reproduce the behaviour:
1. Run `./csgoserver install`
2 See error

## Expected behaviour

No errors ¯\_(ツ)_/¯

**Comment by dgibbs64** [comment]
Just installed csgo on 22.04 with no issues. Both packages are available
https://packages.ubuntu.com/jammy/lib32gcc-s1
https://packages.ubuntu.com/jammy/lib32stdc++6
