### ISSUE TITLE
[BUG] Mumble Server needs rebuilt due to recent changes.

### ISSUE THREAD

**Issue by lorentedford** [GameServerManagers/LinuxGSM#3869]
## User Story

As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [Ubuntu 20.04 LTS]
* **Game:** [Mumble]
* **Command:** [ai]
* **LinuxGSM version:** [v21.5.1]

## Further Information
It looks like Linuxgsm needs updated with cmake [https://github.com/mumble-voip/mumble/issues/5693#issuecomment-1132111221](https://github.com/mumble-voip/mumble/issues/5693#issuecomment-1132111221)

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'installation page and try to install'
2. https://linuxgsm.com/servers/mumbleserver/

## Expected behaviour
Installation of Mumble.
![image](https://user-images.githubusercontent.com/8719903/169545014-869674ea-7a0d-4e4d-aea4-655317d31061.png)

**Comment by lorentedford** [comment]
Any update on this?? Has Mumble installation been fixed?

**Comment by gOOvER** [comment]
> Any update on this?? Has Mumble installation been fixed?

Mumble stopped shippen linuix builds, so its not longer possible to host Mumble. Flame the Mumble devs

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/4128
