### ISSUE TITLE
Cod4x cannot be updated

### ISSUE THREAD

**Issue by overgeek88** [GameServerManagers/LinuxGSM#3874]
Hello,
I made a COD4 server but cod4x is only at version 17 and I can't find this patch on the internet.
Would it be possible to change the link for automatic updating?

**Comment by h3o66** [comment]
from my pov we should probably split the latest cod4 into a seperate game and then as well create something seperate for COD4x with a updater

**Comment by dgibbs64** [comment]
Cod4x should auto-update itself however it looks like they lost there domain and have a new one https://cod4x.ovh
I will update the installed to fix the issue

**Comment by dgibbs64** [comment]
I have raised an issue to fix an issue.

https://github.com/callofduty4x/CoD4x_Server/issues/375
