### ISSUE TITLE
[Server FEATURE] startmodserver for Natural Selection 2 

### ISSUE THREAD

**Issue by Hitman4** [GameServerManagers/LinuxGSM#3875]
## User Story

As a LinuxGSM user, I would like to add the newly added Natural Selection 2 DedicatedServer settings

## Basic info

* **Distro:** [Ubuntu 21.10]
* **Game:** [Natural Selection 2]
* **LinuxGSM version:** [v21.5.1]

## Further Information

for the built-in mod backup web server in Natural Selection 2 which was added with patch 340

```
I added in the info_messages.sh to the line fn_info_message_spark() 
under the web admin port

fn_port "Mod Backup Web Serverport" modserverport tcp


In info_game.sh to the line fn_info_game_spark()
under the queryport

modserverport=${modserverport:-"0"}


in common.cfg to startparameters line behind the -webport ${webadminport}

-startmodserver -modserverport ${modserverport} and behind the -limit ${maxplayers} i add -speclimit ${spec} to set Spectator slots.

under Predefined Parameters 

maxplayers=""
spec="5"
servername=""
webadminuser=""
webadminpass=""
webadminport="8080"
modserverport="27017"
```

I think there's more to tweak it, it's an example of how it worked for me.
and i think to add spec or speclimit to info_game.sh make no sense, because for ranked servers its only allowed to have 5 spec slots.

Maybe someone can add that to the next patch?

## Further Reading

-speclimit can be found in https://naturalselection.fandom.com/wiki/Dedicated_Server#Basic_Configuration

Added a built-in mod backup web server to the dedicated server that allows connecting clients to download mods from the server if the current version of a mod on steam is newer than the servers or the client failed to download the mod from steam. This fixes the old “Missing required mod” error. The web server can be enabled with the -startmodserver command line option. The default port it binds to is serverport + 2 this can be changed with -modserverport. You can also optionally specify the address or ip the mod server uses with -modserveraddress otherwise its defaults to -ip option.
can be found under Mod System Changes on https://store.steampowered.com/news/app/4920/view/5917165051353982118

and in the Official NS2 Discord in the server-obs channel access only with the server-obs rolle just need to ask in the ns2-chat channel .

**Comment by Hitman4** [comment]
and i found out that the webadminport is not displayed in dt it always show me 8080 but i changed it to 8081 because i have a second server as well

**Comment by dgibbs64** [comment]
Got it working and raised a PR
