### ISSUE TITLE
[Server Request] Terraria TShock Server

### ISSUE THREAD

**Issue by chiburek** [GameServerManagers/LinuxGSM#3885]
## What game server would you like to add?

Terraria TShock Server

## Can you link to any tutorials or guides?

[https://github.com/Pryaxis/TShock](https://github.com/Pryaxis/TShock)

## Is the server on Steam?

* [ ] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by chiburek** [comment]
Mono required

**Comment by Committing** [comment]
TShock servers are required for cross-platform between PC and Mobile devices.

I believe this is fairly new.
