### ISSUE TITLE
[BUG] Starbound sbserver install fails using common.cfg Steam credentials

### ISSUE THREAD

**Issue by DrLeeroyPhD** [GameServerManagers/LinuxGSM#3889]
### Following the instructions at [https://linuxgsm.com/servers/sbserver/](https://linuxgsm.com/servers/sbserver/)
After running `./sbserver install` steamCMD fails password authentication.

## Basic info

* **Distro:** Ubuntu 20.04
* **Game:** Starbound
* **Command:** sbserver install
* **LinuxGSM version:** v22.1

## Further Information

The issue appears to be specifically when trying to do the install with the credentials stored inside `lgsm/config-lgsm/sbserver/common.cfg`
The username appears to enter correctly and you receive an error regarding the password.

I can use these same credentials from steamCMD itself. As a work around, I found that it _**does**_ work if you enter the steamuser and steampass into the instance's config instead, ie. `lgsm/config-lgsm/sbserver/sbserver.cfg`

## Troubleshooting Attempted
To hopefully help narrow things down, I...
* Tried both single and double quotes with the same results
* Successfully logged into steamCMD and the Steam website with the same credentials
* Disabled SteamGuard (Email)
* Used a password without special characters
* Reinstalled steamCMD after adding the multiverse repository for Ubuntu 64-bit (according to steamCMD's documentation)

## To Reproduce

Steps to reproduce the behaviour:
1. Enter steamuser and steampass credentials into the common.cfg
2. Run `./sbserver install`

## Expected behaviour
Running the install without having entered Steam credentials into the instance's configuration should fail-over to the common.cfg, which it appears to be doing, but not properly including the steampass variable.

**Comment by dgibbs64** [comment]
tested this as was unable to replicate

**Comment by Shadowblitz16** [comment]
@dgibbs64 this does fail it requires steam guard which linuxgsm completely skips and doesn't let us enter the code
