### ISSUE TITLE
sdtdserver monitor unexpected outcome 

### ISSUE THREAD

**Issue by TheRealMondo** [GameServerManagers/LinuxGSM#3903]
./sdtdserver m OR monitor does not restart the server if the server is offline. It says that it should "restart if crashed" but with other game servers, it would start the server even if it was never online in the first place. Ex. whole system reboot. In the command documentation, it states, _"Monitor first checks that the server process or [tmux] session is running ... Should this fail the server will be rebooted and an alert sent out."_ Also there is no notification sent out when the monitor command is failed in this state.

Is this a bug or an intended feature for the 7 days server to not restart on failing a monitor?

![image](https://user-images.githubusercontent.com/32818268/175800118-0b99fe74-ccdc-4703-bd98-94bc93f46dfc.png)

**Comment by dgibbs64** [comment]
The monitor command did not fail as the message states you need to start the server first to enable monitor. This is to prevent monitor from starting a server that you don't want to be started. It is a feature not a bug
