### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by douglasreckz** [GameServerManagers/LinuxGSM#3905]
As a [user description], I want [desired action] so that [desired outcome].

## Basic info

* **Distro:** [Debian 9]
* **Game:** [CS:GO]
* **Command:** [./csgoserver details/restart/start and every command related]
* **LinuxGSM version:** [v20.1.3]

## Further Information

I have a issue who happened after I made a backup from the server, it gave me a permission error exactly like this

```
[ FAIL ] Viewing details csgoserver: Permissions issues found
Information! The following files are not executable:
File
/home/douglasreckziegel/lgsm/functions/command_mods_install.sh
/home/douglasreckziegel/lgsm/functions/command_monitor.sh
/home/douglasreckziegel/lgsm/functions/command_mods_remove.sh
```

**Comment by copycat240** [comment]
Have you tried chmod +x the functions folder?

**Comment by douglasreckz** [comment]
I tried but seems to be a crash during the backup process. I used the wget the archives mentioned to paste the original files from LinuxGSM but for some reason it was unable to read.  I reset the server on factory defaults and then deleted the folders to install everything from the beginning. It's working fine for now with 3 plugins on it.
