### ISSUE TITLE
[Project Zomboid] Missing dependencies: rng-tools on server startup [BUG]

### ISSUE THREAD

**Issue by aaronladd** [GameServerManagers/LinuxGSM#3910]
## Basic info

* **Distro:** Ubuntu 22.04
* **Game:** Project Zomboid
* **Command:** /pzserver start
* **LinuxGSM version:** [v20.1.3]

## Further Information

A clear description of what the bug is and any ideas on how to resolve it. Plus any further context that might be relevant to the issue.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to run ./pzserver start after initial setup
2. See error

## Expected behaviour

Start PZserver without missing dependancy error which tries to install dependancy every startup

**Comment by aaronladd** [comment]
Update file: lgsm/data/ubuntu-22.04.csv

Line 80: pz,openjdk-16-jre,rng-tools

to read

pz,openjdk-16-jre,rng-tools-debian

I've not done a pull request before so I don't want to mess it up :(

**Comment by wargamesqcf** [comment]
also on Ubuntu 22.04 LTS  and encountering this error.

**Comment by h3o66** [comment]
Created a PR to fix this, also added a update for java as well to use the later LTS version.

**Comment by willyum000** [comment]
I don't believe this is actually completed, I'm still receiving this error. Additionally, now the line fix of line 80@ /home/pzserver/lgsm/data/ubuntu-22.04.csv

no longer works and has changed to line 81.
