### ISSUE TITLE
[BUG] Fresh install of Barotrauma server throws missing directory error in debug console

### ISSUE THREAD

**Issue by veridical** [GameServerManagers/LinuxGSM#3915]
## User Story

As a server owner, I want set up a Barotrauma server.

## Basic info

* **Distro:** [Ubuntu 20.04.4]
* **Game:** [Barotrauma]
* **Command:** [debug]
* **LinuxGSM version:** [v22.1.0]

## Further Information

When starting a Barotrauma server for the first time, the following error message shows up in the debug console: [https://pastebin.com/q8PmFDpM](https://pastebin.com/q8PmFDpM). It seems the _/home/btserver/.local/share/Daedalic Entertainment GmbH/Barotrauma_ directories are missing. I have a workaround below.

## To Reproduce

1. Install the Barotrauma server using the install LinuxGSM documentation.
2. Run `./btserver start`. This will end up failing.
3. Run `./btserver debug` to view the error message. 

## Expected behavior

Server starts with no issues.

## Workaround

To get the server up and running, I did the following:

1. Inside _/home/btserver/.local/share/_ add the following directory structure: _Daedalic Entertainment GmbH/Barotrauma_
2. Start the server. It should be successfully started now.

**Comment by Marcin648** [comment]
@veridical Can you confirm that this symlink is necessary? For me, `mkdir -p "~/.local/share/Daedalic Entertainment GmbH/Barotrauma"` works fine. Maybe for some reason, like mods, this simlink is recommended?

**Comment by veridical** [comment]
> @veridical Can you confirm that this symlink is necessary? For me, `mkdir -p "~/.local/share/Daedalic Entertainment GmbH/Barotrauma"` works fine. Maybe for some reason, like mods, this simlink is recommended?

Confirmed! No symlink is needed. I will update the workaround. Thanks for checking!
