### ISSUE TITLE
[BUG] Squad server not listed in server browser

### ISSUE THREAD

**Issue by romanvoloboev** [GameServerManagers/LinuxGSM#3921]
I can't found my server in custom server browser when using your script.
But in the same time on the same server when I'm using manual installation via SteamCMD or Docker image cm2network/squad -- everything is working and **I can see server in custom browser**.

## Basic info

* **Distro:** Ubuntu 22.04
* **Game:** Squad
* **Command:** ./SquadGameServer.sh FIXEDMAXTICKRATE=50 FIXEDMAXPLAYERS=100 RANDOM=ALWAYS Port=7787 QueryPort=27165
* **LinuxGSM version:** v22.1.0

## Further Information

All ports are opened via firewall.
Server has 1 ip address. Hosted at Hetzner.
I also tried to use MULTIHOME parameter, but no result.
All server settings are default, except it name.

## To Reproduce

Steps to reproduce the behaviour:
1. Rent server at Hetzner.
2. Install SQUAD server via your script.
3. Change it default name and try to found at custom server browser.

<img width="853" alt="2022-07-11 в 17 23 09" src="https://user-images.githubusercontent.com/13852208/178287449-27302fc1-2274-4ea4-a8f0-e7d1c89e6f3b.png">

**Comment by h3o66** [comment]
Well, I can kinda reproduce it.

In this case just the used config is different.

instead of
`serverfiles/SquadGame/ServerConfig/squadserver.cfg`
the following config is used:
`serverfiles/SquadGame/ServerConfig/Server.cfg`

I will check what we have in the scripts and do a PR

**Comment by h3o66** [comment]
Created a fix for this.

To fix this manually, add the following to the `common.cfg/squadserver.cfg`

```
servercfg="Server.cfg"
servercfgfullpath="${servercfgdir}/${servercfg}"
```
