### ISSUE TITLE
[BUG] Stationeers Server syntax changed

### ISSUE THREAD

**Issue by Neouni** [GameServerManagers/LinuxGSM#3925]
Stationeers Dedicated Server changed from unity headless player to unity dedicated server (13 June) and as a result is rebuild from scratch.
As a result all the syntax for loading, saving, passing on the settings and closing down the server etc got changed.

#3898

#3924

**Comment by gOOvER** [comment]
also console output changed

**Comment by jbondhus** [comment]
Also I am unable to launch the server. See link for a screen recording of the console of a brand new Ubuntu instance on DigitalOcean. No port is listening.

https://youtu.be/dogK6PztD9M

**Comment by gOOvER** [comment]
> Also I am unable to launch the server on a fresh install on a new DigitalOcean droplet. See link for a screen recording of the console of a brand new Ubuntu instance on DigitalOcean. No port is listening.
> 
> [youtu.be/dogK6PztD9M](https://youtu.be/dogK6PztD9M)

this have nothing to do with Pterodactyl

**Comment by gOOvER** [comment]
> Also I am unable to launch the server on a fresh install on a new DigitalOcean droplet. See link for a screen recording of the console of a brand new Ubuntu instance on DigitalOcean. No port is listening.
> 
> [youtu.be/dogK6PztD9M](https://youtu.be/dogK6PztD9M)

LGSM is not updated for tha last changes. So no need to publish this video ;)
