### ISSUE TITLE
[BUG] Fresh install of Barotrauma server throws "No usable version of libssl was found" error

### ISSUE THREAD

**Issue by frozenfoxx** [GameServerManagers/LinuxGSM#3926]
## User Story

As a server owner, I want to set up a Barotrauma server so that it launches painlessly.

## Basic info

* **Distro:** [Ubuntu 22.04]
* **Game:** [Barotrauma]
* **Command:** [start]
* **LinuxGSM version:** ["v22.1.0]

## Further Information

When starting a Barotrauma server after installation it fails. When checking the `/home/btserver/log/console/btserver-console.log` it says:

```
btserver@barotrauma:~$ cat log/console/btserver-console.log
Barotrauma Dedicated Server 0.18.15.0 (ReleaseLinux, branch release, revision a7b22109e9)
Loading game settings
No usable version of libssl was found
./DedicatedServer.exe: line 2: 16986 Aborted                 ./DedicatedServer
```

All dependencies are installed:

```
Checking Dependencies
=================================
bc
binutils
bsdmainutils
bzip2
ca-certificates
cpio
curl
distro-info
file
gzip
hostname
jq
lib32gcc-s1
lib32stdc++6
libicu-dev
libsdl2-2.0-0:i386
netcat
python3
steamcmd
tar
tmux
unzip
util-linux
wget
xz-utils
Information! Required dependencies already installed.
```

Installation is successful:

```
Installing SteamCMD
=================================
Information! SteamCMD is already installed...OK

Installing Barotrauma Server
=================================
[ START ] Installing btserver: SteamCMD
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/btserver/.local/share/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1654574676
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.63 (1898573 / 300348955)
 Update state (0x5) verifying install, progress: 74.61 (224083523 / 300348955)
Success! App '1026340' fully installed.
Work thread 'CHTTPClientThreadPool:1' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
Complete! Installing btserver: SteamCMD
```

## To Reproduce

Steps to reproduce the behaviour:
1. Install Ubuntu 22.04.
2. Create a `btserver` unprivileged user.
3. Install dependencies as `root`.
4. As `btserver`, `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh btserver`.
5. As `btserver`, `./btserver install`.
6. As `btserver`, `./btserver start`.
7. Failure, see log.

## Expected behaviour

Server starts up.

## Workaround

This seems to be because Ubuntu 22.04 has deprecated libssl 1.0. I retrieved the i386 and amd64 builds from [here](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/) and installed:

* [http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_i386.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_i386.deb)
* [http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb)

Now the game server successfully starts up immediately.

**Comment by dgibbs64** [comment]
my btserver docker image is 22.04 and is currently working. The devs probably fixed this
