### ISSUE TITLE
[FEATURE] Configurable curl timeout

### ISSUE THREAD

**Issue by Sonicadvance1** [GameServerManagers/LinuxGSM#3931]
## User Story
As a developer of the FEX-Emu emulator, when debugging some issues on the FEX-Emu side, I had noticed that every curl instance has a set timeout of 10 seconds. It would be nice to be able to provide a configurable option to set the length of this timeout.

Not sure what the expected path forward is for configurations here. An environment variable to hit all instances of curl timeout would work for me.

## Basic info

* **Distro:** [Ubuntu 22.04]
* **Game:** [Team Fortress Classic]
* **Command:** [install]
* **LinuxGSM version:** [v22.1.0]

## Further Information

The feature is purely some configurable support for the hardcoded 10 second of curl timeout in various scripts.

## Further Reading

Some users may be attempting to run this install script on very underpowered hardware, like Cortex-A53 CPUs. Once installed and running it may have reasonable enough performance for them but the timeout needs to be high enough that these cores can hit that.
Otherwise when running under FEX-Emu with a bug-fix in place, these scripts to start dedicated servers seem to work fine.

**Comment by dgibbs64** [comment]
Many game servers require decent enough hardware to run. If the hardware is struggling to download .sh files using curl I would suggest that it is unable to run game servers.
