### ISSUE TITLE
[Server Request] Xonotic

### ISSUE THREAD

**Issue by KingKannibal** [GameServerManagers/LinuxGSM#3936]
## What game server would you like to add?

Xonotic

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

Official Website:
https://xonotic.org/

Github:
https://github.com/garymoon/xonotic

## Is the server on Steam?

* [ ] Yes
* [x] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by KingKannibal** [comment]
> Potential duplicates:
> 
>     * [[[Server Request] Nexuiz Classic #3935](https://github.com/GameServerManagers/LinuxGSM/issues/3935)] [Server Request] Nexuiz Classic (61.19%)

Not a duplicate. both games are based on the same engine and Xonotic is a direct follow-up, but they have different weapons and aesthetics.

**Comment by Hornochs** [comment]
@KingKannibal Xonotic was added in the latest release 😊
