### ISSUE TITLE
[Server Request] V Rising

### ISSUE THREAD

**Issue by gothitachisama** [GameServerManagers/LinuxGSM#3953]
## What game server would you like to add?

V Rising

## Can you link to any tutorials or guides?

https://github.com/StunlockStudios/vrising-dedicated-server-instructions

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

1829350

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [ ] Yes
* [x] No

**Comment by Claiyc** [comment]
Windows only.
