### ISSUE TITLE
[BUG] bdserver install loop and fail

### ISSUE THREAD

**Issue by KingKannibal** [GameServerManagers/LinuxGSM#3961]
## User Story

I am trying to get a Base Defense server started.

## Basic info

* **Distro:** Debian GNU/Linux 11 (bullseye)
* **Game:** Base Defense
* **Command:** Install
* **LinuxGSM version:** v22.1.0

## Further Information

After installing dependencies and downloading linuxgsm files, the server files are stuck on a long loop. When the loop ends, files are still missing.

## To Reproduce

Steps to reproduce the behaviour:
1. Download linuxgsm.sh. 
2. Wait until it's done downloading then move onto next step
3. When prompted to, type ./bdserver install
4. Wait for long loop.
5. When loop is finished, you will see that bdserver is missing files necessary to run.

## Expected behaviour

when typing ./bdserver install, all files should successfully install and server should be possible to run.

**Comment by h3o66** [comment]
Linked one Pr with 2 bugfixes for the Game
