### ISSUE TITLE
[BUG] Discord alerts send invalid JSON when sending servername

### ISSUE THREAD

**Issue by Arthur-D** [GameServerManagers/LinuxGSM#3973]
## User Story

As a server administrator, I want Discord alerts to work without hassle for everyone so that they don't give up on getting alerts.

## Basic info

* **Distro:** [Ubuntu 18.04.6]
* **Game:** [Minecraft]
* **Command:** [test-alert]
* **LinuxGSM version:** [v22.1.0]

## Further Information

Sending Discord alerts fails with a parse error, listed in the To Reproduce section of this bug report. I managed to work around it by changing line 21 in lgsm/functions/alert_discord.sh from
`		"title": "${servername}",` to
`		"title": "Minecraft",` and thus exchanging the variable for a static name.

At first I thought the "invalid escape" bit in the error message meant I couldn't have a space in my Discord server name, so I changed its name from "Multiplayer Minecraft" to just "Minecraft" and made a new webhook, just in case. But it did not resolve the issue, so I had to go with the above workaround instead.

## To Reproduce

Steps to reproduce the behaviour:
1. In my instance config lgsm/config-lgsm/mcserver/mcserver.cfg I added the Notification Alerts section from the template lgsm/config-lgsm/mcserver/_default.cfg
2. I followed https://docs.linuxgsm.com/alerts/discord but added the URL to my instance mcserver.cfg instead of common.cfg
3. I ran ./mcserver test-alert
4. See error:
`[ .... ] Sending Alert mcserver: Sending Discord alertparse error: Invalid escape at line 11, column 40
[ FAIL ] Sending Alert mcserver: Sending Discord alert: {"code": 50109, "message": "The request body contains invalid JSON."}`

## Expected behaviour
For the Discord alert to work without having to exchange a variable for a static servername.

**Comment by malro57** [comment]
Have the same behavior here just after a fresh install of Memories Of Mars server. By the way my other server configured in the past still working as expected with test-alert.

**Comment by Zxurian** [comment]
This appears to still be happening, although I'm getting the error on a different line.

```
vaulthunters@minecraft-dedicated:/mnt/minecraft/vaulthunters$ ./mcserver test-alert
[ .... ] Sending Alert mcserver: UNAVAILABLEgrep: (standard input): binary file matches
[ WARN ] Sending Alert mcserver: More Info not enabled
[ .... ] Sending Alert mcserver: Sending Discord alertparse error: Invalid escape at line 11, column 120
[ FAIL ] Sending Alert mcserver: Sending Discord alert: {"code": 50109, "message": "The request body contains invalid JSON."}
```
I tried commenting out `displayip` value, however still got the same error with only `discordwebhook` defined within `secrets-common.cfg`

**Comment by theroflcopterguy** [comment]
You need to change the motd in the server properties, i had same issue and this fixed it!!

**Comment by egeexyz** [comment]
> You need to change the motd in the server properties, i had same issue and this fixed it!!

Can confirm this! I had a `\` in the server title. Saw this post, removed it, and poof ~ it worked!

**Comment by dgibbs64** [comment]
Game server admins sometimes like to use all sorts of unusual characters for server name that can sometimes cause issues with being parsed in bash. \ is an example of this as in bash \ is an escape character. There isn't much I can really do as far as I can tell to get around this issue
