### ISSUE TITLE
[FEATURE] dep-install command

### ISSUE THREAD

**Issue by thephluxer** [GameServerManagers/LinuxGSM#3975]
## User Story

As a private server hoster, I want to detect and install dependencies as root with a seperate command so that i can start the normal installation afterwards as a user without sudo in my automation scripts.

## Basic info

* **Distro:** [Ubuntu-Server 22.04]
* **LinuxGSM version:** [v20.1.3]

## Further Information

The only thing that is problematic to automate for me is when some dependencies are missing. I run all my wrapper scripts as root with su to install the servers with their specific user accounts.
With that sudo doesn't work and atm i have to grep the missing dependencies from the installation output so i can install them as root and restart the installation with the user account afterwards.
It would be really handy for me if it was possible to just run the dependency installation as root seperately with a dep-install command provided by the lgsm script so i don't have to worry about dependencies when i start the normal installation with a user account.
I think it would be very easy to implement a dep-install command because it's just a trigger for a partial installation process that already exists.

**Comment by dgibbs64** [comment]
this feature already exists. run `./gameserver install` as root

**Comment by thephluxer** [comment]
But that installs everything for me, not just the dependencies.

**Comment by dgibbs64** [comment]
Not when running as root. When running as root it will ONLY install dependencies.

**Comment by thephluxer** [comment]
Oh ok i'll try that. Thank you!
