### ISSUE TITLE
[Bug]: Starting mcbserver: LinuxGSM no server running on /tmp/tmux-1000/default - Ubuntu 22.04

### ISSUE THREAD

**Issue by bardhyliis** [GameServerManagers/LinuxGSM#3978]
I installed a mc bedrock server in ubuntu 22.04, however, it doesn't work, I've tried CS:GO and it works fine.

the MCB Server installs perfectly with no error, however it won't start using ./mcbserver start, I think it's some kind of a bug with linuxgsm in Ubuntu 22.04, In ubuntu 20.04 it works fine.

Here's part of the output:

> Config File Locations
=================================
Game Server Config File: /home/mcbserver/serverfiles/server.properties
LinuxGSM Config: /home/mcbserver/lgsm/config-lgsm/mcbserver
Documentation: https://docs.linuxgsm.com/configuration/game-server-config

LinuxGSM Stats
=================================
Assist LinuxGSM development by sending anonymous stats to developers.
More info: https://docs.linuxgsm.com/configuration/linuxgsm-stats
The following info will be sent:
* game server
* distro
* game server resource usage
* server hardware info
Information! auto-install leaves stats off by default. Stats can be enabled in common.cfg

=================================
Install Complete!

To start server type:
./mcbserver start

mcbserver@vmi998777:~$ ./mcbserver start
[ .... ] Starting mcbserver: LinuxGSMno server running on /tmp/tmux-1000/default
[ FAIL ] Starting mcbserver: Unable to start LinuxGSM

**Comment by SpongeManiac** [comment]
I am having this issue too, Ubuntu 22.04 but with ARK: Survival Evolved. Is the workaround to downgrade back to Ubuntu 20.04?
