### ISSUE TITLE
[BUG] Avorion install using incorrect steamclient.so

### ISSUE THREAD

**Issue by Pathas-Gamer** [GameServerManagers/LinuxGSM#3983]
## User Story

As an Avorion server manager, I want to be able to join an Avorion server via IP so that users can join the server over the internet and play the game. Currently, the wrong version of steamclient.so is being selected, leading to not being able to join via IP.

## Basic info

* **Distro:** Ubuntu 22.04.1
* **Game:** Avorion
* **LinuxGSM version:** v22.1.0

## Further Information

Clean installation of U22.04.1 minimal server, necessary LGSM dependencies. Create a dedicated account for running Avorion, install LGSM per instructions. 

## To Reproduce

Start Avorion server, observe "wrong ELF class: ELFCLASS32" messages in the game server log. Attempt to join the server via "Join via IP" from client on the same LAN - no connection. Join server via "Join LAN", able to connect to the server.

To 'fix', stop server, copy steamclient.so from linux64 directory to serverfiles directory, and start the server. Observe no "wrong ELF class" message in server log. Join via IP is successful.

## Expected behaviour

Server should be reachable via both IP and LAN, instead of only via LAN.

**Comment by quonic** [comment]
[This steam topic](https://steamcommunity.com/app/445220/discussions/0/143388511227851134/) seems to have a simple fix.

From with in `serverfiles/` running:

`ln -s linux64/steamclient.so`

looks to work fine.

**Comment by Pathas-Gamer** [comment]
Quonic's fix works - but this is still a manual workaround. This bug is still not fixed FYI.

**Comment by Pathas-Gamer** [comment]
Confirmed that this is an issue on Ubuntu 22 as well as Ubuntu 20. Workaround clears the problem on either OS version. User is not in sudoers - followed directions explicitly from https://linuxgsm.com/servers/avserver/#v-pills-dependencies

**Comment by Pathas-Gamer** [comment]
Adding user to sudoers did not fix the issue.

**Comment by notZoidberg** [comment]
Heya. I had the same issue. my gameserver had some issues with that. I looked into the startup of the server and then saw the error like this. I am running lgsm on Debian Buster. 
![grafik](https://user-images.githubusercontent.com/60973924/221319409-3f5bc251-915c-4685-933b-d15ab762666a.png)

**Comment by dgibbs64** [comment]
Looking at this now

**Comment by dgibbs64** [comment]
issue appears to be that fix_av.sh was not running on server start `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${serverfiles}:${serverfiles}/linux64"` was not running.

**Comment by notZoidberg** [comment]
So the bug is also there for the Satisfactory gameserver. Just giving you a heads up there.
