### ISSUE TITLE
[Server Request] Conan Exiles

### ISSUE THREAD

**Issue by naoestu** [GameServerManagers/LinuxGSM#3986]
## What game server would you like to add?

Conan Exiles

## Can you link to any tutorials or guides?

https://www.psychz.net/client/kb/en/how-to-setup-a-dedicated-server-for-conan-exiles.html

## Is the server on Steam?

Yes

If yes Use SteamDB to get the appid. (https://steamdb.info).

https://steamdb.info/app/443030/depots/

## Is the server supported on Linux?

yes

**Comment by Claiyc** [comment]
Conan Exiles does not support Linux. We do not support WINE.
