### ISSUE TITLE
Why my server cant get query in docker?

### ISSUE THREAD

**Issue by Tellarion** [GameServerManagers/LinuxGSM#3987]
Hello. My gameserver has next settings
Server = Counter-Strike 1.6

ip="0.0.0.0"
port="27015"
clientport="27005"
defaultmap="de_dust2_2x2"
maxplayers="32"

startparameters="-game cstrike +ip ${ip} -port ${port} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers ${maxplayers}"```

My docker-compose
version: '3.4'
services:
  linuxgsm:
    image: "ghcr.io/gameservermanagers/linuxgsm-docker:latest"
    container_name: csserver
    environment:
      - GAMESERVER=csserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /home/cs-2/files/serverfiles:/home/linuxgsm/serverfiles
      - /home/cs-2/files/log:/home/linuxgsm/log
      - /home/cs-2/files/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    restart: unless-stopped
    expose:
      - 27015

Game server correctly work and set position success on masterlist game.
But... When i can try added server custom web monitroing. Server is offline.
![image](https://user-images.githubusercontent.com/23682610/191316972-99b8c63f-1658-49ea-b7f6-ab93999cf36d.png)

$ ./csserver debug

Counter-Strike 1.6 Debuging
=================================
Distro:       Ubuntu 20.04.5 LTS
Arch:         x86_64
Kernel:       5.4.0-28-generic
Hostname:     8590ae43ea58
tmux:         tmux 3.0a
Avg Load:     0.03, 0.04, 0.02
Free Memory:  3.0GB
Free Disk:    71G
glibc required: 2.14
Game Server IP: 0.0.0.0:27015
Internet IP:    23.111.202.173:27015
Server password:        NOT SET
Start parameters:
./hlds_run -game cstrike +ip 0.0.0.0 -port 27015 +map de_dust2_2x2 +servercfgfile csserver.cfg -maxplayers 32 -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If csserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debuging csserver: Stopping any running servers
[  OK  ] Stopping csserver: Graceful: sending "quit": 3: OK
[  OK  ] Stopping csserver: Классика с нами [#1] [vk.com/classicwithus]
[  OK  ] Debuging csserver: Starting debug
Enabling debug mode
./hlds_run: 125: test: Illegal number: unlimited
./hlds_run: 1: gdb: not found
Please install gdb first.
goto http://www.gnu.org/software/gdb/ 
Auto-restarting the server on crash

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:52:19 Aug  3 2020 (8684)
STEAM Auth Server
Server IP address 0.0.0.0:27015
   
   Metamod version 1.21.1-am  Copyright (c) 2001-2013 Will Day <willday@metamod.org>
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   

   AMX Mod X version 1.8.2 Copyright (c) 2004-2006 AMX Mod X Development Team 
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under 
   certain conditions; type 'amxx gpl' for details.
  
Version 0.9.582 Linux
[DPROTO]: Parsing error: validation checking code analyzing error (2)
[DPROTO]: Parse_ConnectClient() failed
[DPROTO]: Sorry, this version of engine is not supported
L 09/20/2022 - 16:48:39: -------- Mapchange to de_dust2_2x2 --------
[AMXX] Loaded 2 admins from file
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

Executing AMX Mod X Configuration File 
Russification by Serjant 
Scrolling message displaying frequency: 5:00 minutes
Server logging data to file logs/L0920047.log
L 09/20/2022 - 16:48:40: Log file started (file "logs/L0920047.log") (game "cstrike") (version "48/1.1.2.7/Stdio/8684")
L 09/20/2022 - 16:48:40: Server cvar "sv_maxspeed" = "320"
L 09/20/2022 - 16:48:40: Server cvar "mp_timelimit" = "60"
couldn't exec listip.cfg
couldn't exec banned.cfg
Menu item 17 added to Menus Front-End: "Plugin Cvars" from plugin "pluginmenu.amxx"
Menu item 18 added to Menus Front-End: "Plugin Commands" from plugin "pluginmenu.amxx"
Connection to Steam servers successful.
   VAC secure mode is activated.
L 09/20/2022 - 16:48:48: World triggered "Round_Start"

GameLog (all good)

![20220920195252_1](https://user-images.githubusercontent.com/23682610/191318762-101b08f9-969a-4b30-8eb2-20dc22a167ed.jpg)

Ip I left the server is now running, maybe someone will try to do the tests ;)

Ideas?

**Comment by Claiyc** [comment]
Not an issue with lgsm. Docker is generally not yet supported by us. If you want to use lgsm inside a docker container, take a look at https://github.com/GameServerManagers/LinuxGSM-Docker/pull/43
Note that this is not officially supported yet as well.

**Comment by Tellarion** [comment]
If image is not supported. I cant create issue. Server correctly work, but truble for query other services (monotorings and etc...) maybe use curl or socket for get response. I try undestand this. Maybe my truble.
