### ISSUE TITLE
[ts3server] fn_install: line 22: fn_install_ts3: command not found 

### ISSUE THREAD

**Issue by brandonjjon** [GameServerManagers/LinuxGSM#399]
Running Ubuntu 14.04 LTS x64 and have all the required dependencies.

Log:
https://gist.github.com/brandonjjon/2feeeb1961a749df2b56

**Comment by dgibbs64** [comment]
The installer isn't ready yet. But hopefully will be soon. There is a lot more coding required than the other servers that use SteamCMD

**Comment by brandonjjon** [comment]
I see. Can you provide any sort of ETA?

Love the other scripts though! You've done a great job.

**Comment by dgibbs64** [comment]
To quote Mr Bull from Pepper Pig 'It will take as long as it takes ;-) https://youtu.be/mmii3UXKRAA . However I do have some free time this weekend so I'm hoping to finish it by then.

**Comment by dgibbs64** [comment]
Installer is now released
