### ISSUE TITLE
How to automatically update oxide ?

### ISSUE THREAD

**Issue by anonunder** [GameServerManagers/LinuxGSM#3998]
Hello,

How can I automatically update rust oxide using the command mods-update? After oxide release a new update, my server doesn't load oxide anymore including plugins, so I have to stop the server, do the mods-update and start it again.

Is there any way except making a shell script, to check for new updates and update if necessary? 

Do I need to stop the server to do mods-update? 

I do have in crontab recommended commands like monitor, update, restart, backup etc, but didn't find anything for this.

**Comment by un-boxing-man** [comment]
when rust releases a update you have to update oxide

if you run the "cu" (check-update) command it will check for updates and sent a alert if setup
then run  "u" (update) and  "mu" (mods-update) to update

and yes the server has to be stoped to update (unless updating plugins)
