### ISSUE TITLE
[BUG] Barotrauma Graceful exit command has changed

### ISSUE THREAD

**Issue by JoneKone** [GameServerManagers/LinuxGSM#3999]
## User Story

Graceful exit is no longer code '7' but code '3' (quit) text

## Basic info

* **Distro:** Debian 12
* **Game:** Barotrauma
* **Command:** Graceful exit (Stopping server) /btserver sp
* **LinuxGSM version:** [v22.1.0]

## To Reproduce
./btserver sp
[ ERROR ] Stopping btserver: Graceful: sending "exit": FAIL
[  OK  ] Stopping btserver: Server

## Expected behaviour
/btserver sp
[  OK  ] Stopping btserver: Graceful: sending "quit": 2: OK

**Comment by 89gsc** [comment]
After the steam update I just did a server update + validate and now starting the server does this;
```
btserver@.....:~$ ./btserver start
jq: error (at <stdin>:0): Cannot iterate over null (null)
[ .... ] Starting btserver: Serverno server running on /tmp/tmux-1003/default
[ FAIL ] Starting btserver: Unable to start Server
```

 Did full reboot no effect, Do you think this is a separate issue? I will open another issue if you think it's not related. Only ask as the timing seems the same as the update.

**Comment by h3o66** [comment]
> After the steam update I just did a server update + validate and now starting the server does this;
> 
> ```
> btserver@.....:~$ ./btserver start
> jq: error (at <stdin>:0): Cannot iterate over null (null)
> [ .... ] Starting btserver: Serverno server running on /tmp/tmux-1003/default
> [ FAIL ] Starting btserver: Unable to start Server
> ```
> 
> Did full reboot no effect, Do you think this is a separate issue? I will open another issue if you think it's not related. Only ask as the timing seems the same as the update.

Would be probably the best to open a disscussion or join the discord for a first troubleshooting.

You can probably as well check #3915 at first

**Comment by h3o66** [comment]
Cannot reproduce the inital issue - server stop on my side without a issue.

**Comment by JoneKone** [comment]
> Cannot reproduce the inital issue - server stop on my side without a issue.

And how many times did it send the wrong exit command? 40 and the it will default to ctrl+c and kills it.

**Comment by h3o66** [comment]
Works just fine:
`[  OK  ] Stopping btserver: Graceful: sending "exit": 2: OK`

The best would be maybe to check this more indepth via discord.
