### ISSUE TITLE
[BUG] Barotrauma v22.1.0 fails to launch 

### ISSUE THREAD

**Issue by frozenfoxx** [GameServerManagers/LinuxGSM#4003]
## User Story

As a server operator, I want to launch `btserver` so that players can play on the server.

## Basic info

-   **Distro:** Ubuntu 22.04
-   **Game:** Barotrauma
-   **Command:** start
-   **LinuxGSM version:** v22.2.0

## Further Information

When starting a Barotrauma server after installation it fails. The `/home/btserver/log/console/btserver-console.log` is blank.

```
btserver@barotrauma:~$ ./btserver start
[ .... ] Starting btserver: Serverno server running on /tmp/tmux-1000/default
[ FAIL ] Starting btserver: Unable to start Server
```

The `btserver-script.log` indicates an issue, but doesn't say what:

```
btserver@barotrauma:~/log/script$ cat btserver-script.log
Oct 05 22:17:59.582 btserver: START: FATAL: Unable to start Server
Oct 05 22:17:59.589 btserver: START: INFO: LinuxGSM version: v22.2.0
Oct 05 22:17:59.590 btserver: START: FATAL: core_exit.sh exiting with code: 1
```

## To Reproduce

Steps to reproduce the behaviour:

1. Install Ubuntu `22.04`.
2. Create a `btserver` unprivileged user.
3. Install dependencies as `root`.
4. As `btserver`, `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh btserver`.
5. As `btserver`, `./btserver install`.
6. As `btserver`, `./btserver start`.
7. Failure, see above.

## Expected behaviour

Server starts.

**Comment by frozenfoxx** [comment]
Added these to my Ansible deployment and now it functions. Seems like something that should probably be in the system requirements or in the fixes.

**Comment by Marcin648** [comment]
Problem is wrong executable binary in LGSM config.
I just change from `executable="./DedicatedServer.exe"` to `executable="./DedicatedServer"` and that fixes the problem. 

Yes, both binary exist in this game server ;)

**Comment by h3o66** [comment]
> Problem is wrong executable binary in LGSM config. I just change from `executable="./DedicatedServer.exe"` to `executable="./DedicatedServer"` and that fixes the problem.
> 
> Yes, both binary exist in this game server ;)

the `exe` is only a script that starts the server with a extra LD_LIBRARY path set

**Comment by Marcin648** [comment]
I didn't knows that this `exe` is a script file. 😃 
Anyway, that `LD_LIBRARY` add `linux64` directory, that have only `steamclient.so`. This lib is provided by other steamclient.so fixes. So it's works anyway. But yes, using this `exe` and `dos2unix` is preferable :)

**Comment by rainst** [comment]
I was having this issue too on my ubuntu dedicated server, so this needs to be addressed by the developer? 
the `dos2unix` solution it will need to be applied every time an update will be out, correct?

**Comment by h3o66** [comment]
> I was having this issue too on my ubuntu dedicated server, so this needs to be addressed by the developer? the `dos2unix` solution it will need to be applied every time an update will be out, correct?

Would be the best if the game developer could do this.
The solution in the connected PR is applied when needed as a workaround.
