### ISSUE TITLE
[FEATURE] Add all game mode related cvars to CS:GO LGSM config

### ISSUE THREAD

**Issue by timm0e** [GameServerManagers/LinuxGSM#4004]
## User Story

As a CS:GO server admin, I want to be able to configure all cvars related to game mode settings by extending the default LGSM config so that I don't have to manually edit any .cfg files or the launch parameters to set up the game mode as I want to.

## Basic info

-   **Distro:** Ubuntu 22.04
-   **Game:** Counter-Strike: Global Offensive
-   **Command:** Start
-   **LinuxGSM version:** v22.2.0

## Further Information

Currently, the [default config for the CS:GO server](https://github.com/GameServerManagers/LinuxGSM/blob/55694a0a88c5487b2947e06c0f85855543861273/lgsm/config-default/config-lgsm/csgoserver/_default.cfg) only includes the cvars `game_type` (configured via the `gametype` variable) and `game_mode` (configured via the `gamemode` variable) in the server startup configuration.

However, Valve added some additional cvars over time: `sv_game_mode_flags` and `sv_skirmish_id` for new game modes (e.g. short competitive matches or war games). (See [this Valve wiki entry](https://developer.valvesoftware.com/wiki/CS:GO_Game_Modes) for how these options work)

Adding both of these cvars to the LGSM config and to the launch parameters would make these game modes accessible to server admins that want to configure the game mode in the LGSM config, similar to the older game modes that solely rely on `game_type` and `game_mode`.

No help for implementing this is needed — I am in the process of submitting a PR.

## Further Reading
https://developer.valvesoftware.com/wiki/CS:GO_Game_Modes

**Comment by dgibbs64** [comment]
Since CSGO is no longer available I will close this. CS2 uses game_alias now
