### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AsP3X** [GameServerManagers/LinuxGSM#4010]
## User Story

Hey sorry if the issue is a little ill formated, this is my first one here.
I've noticed that the javacord addon that the server is using in the background if activated, changes my discord bots username to servertest and I have found no way to fix this.

I'm running the latest stable version of your server manager as of 20.10.22

I would like to see an option or a setting to change this behaviour or even the name of the bot via the mechanic in question.

## Basic info

-   **Distro:** [Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0 x86_64)]
-   **Game:** [Project Zomboid]
-   **LinuxGSM version:** [v22.2.0]

## Further Information

If the option for using the discord bot chat integration is activated and the bot is configured correctly, as soon as the server completed it's boot sequenz the name of the bot is changed to servertest automatically.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to 'Zomboid/Server/%INSTANCE%.ini
2. Configure following settings
- DiscordEnable=true
- DiscordToken=
- DiscordChannel=
- DiscordChannelID=

3. Restart the server

## Expected behaviour

Server boots and the bot forwards all chat messages send into the global chat to a discord server

**Comment by dgibbs64** [comment]
This is not related to LinuxGSM. It is a project zomboid related issue
