### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tydaytygx** [GameServerManagers/LinuxGSM#4014]
Issues raised here are **ONLY** for:

-   LinuxGSM bugs.
-   Feature suggestions.
-   Code contributions.

Issues raised here are **NOT** for:

-   General support.
-   Specific game server issues (e.g CS:GO, TF2).
-   Dedicated server issues (e.g Ubuntu, CentOS).
-   Anything not directly related to LinuxGSM development.

For general support visit the **[LinuxGSM Support](https://linuxgsm.com/support)** page.

**_Please use the template below, deleting the above text_**

## User Story

As I am a server admin, but the vps network environment is not good, I want to force-use bukkit source (skip the github fetching)

## Basic info

-   **Distro:** [Ubuntu 20.04]
-   **Game:** [CSGO]
-   **Command:** [./csgoserver install]
-   **LinuxGSM version:** [v20.1.3]

## Further Information

For example, add an option to 
> ./csgoserver install 

> ./csgoserver install --force-bukkit

## Further Reading

Please add an  option to only-force-use bukkit version, thank you!

**Comment by dgibbs64** [comment]
This issue does not make much sense and is out of scope
