### ISSUE TITLE
[BUG] LinuxGSM in a loop after latest patch for core_steamcmd.sh file

### ISSUE THREAD

**Issue by Creative2150** [GameServerManagers/LinuxGSM#4015]
## User Story

Game server is unable to start since finding appinfo.vdf file fails with infinite loop.
## Basic info

-   **Distro:** [Red Hat Enterprise Linux release 8.6 (Ootpa)]
-   **Game:** [Project Zomboid]
-   **Command:** [start, restart]
-   **LinuxGSM version:** [v22.2.1]

## Further Information

https://github.com/GameServerManagers/LinuxGSM/blob/2257be4a8ec7dfd39d7a11305af8d7fe3e54302c/lgsm/functions/core_steamcmd.sh#L177
After removing option -L from find command game server was able to start normally.

## To Reproduce

Steps to reproduce the behaviour:

1. Update lgms tools. "/home/steam/linuxgsm/pzserver update-lgsm"
2. Start game server "/home/steam/linuxgsm/pzserver start"
4. Infinite loop with following or similar lines:
`find: File system loop detected; ‘/home/steam/sys/devices/system/cpu/cpu0/subsystem/devices/cpu1/node0/memory0/subsystem/devices/memory72/firmware_node/subsystem/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:00/physical_node/subsystem/devices/0000:00:07.0/firmware_node/PNP0C02:00/physical_node/subsystem/devices/00:01/wakeup/wakeup48/subsystem/wakeup2/device/physical_node/ata1/ata_port/ata1/subsystem/ata2/device/link2/ata_link/link2/subsystem/link11/device/dev11.0/ata_device/dev11.0/subsystem/dev26.0/subsystem’ is part of the same file system loop as ‘/home/steam/sys/devices/system/cpu/cpu0/subsystem/devices/cpu1/node0/memory0/subsystem/devices/memory72/firmware_node/subsystem/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:00/physical_node/subsystem/devices/0000:00:07.0/firmware_node/PNP0C02:00/physical_node/subsystem/devices/00:01/wakeup/wakeup48/subsystem/wakeup2/device/physical_node/ata1/ata_port/ata1/subsystem/ata2/device/link2/ata_link/link2/subsystem/link11/device/dev11.0/ata_device/dev11.0/subsystem’.
`
5. Unable to start game server since game update? part failed

After changing find command back to normal (without -L option) game server is able to start normally

**Comment by dgibbs64** [comment]
Thanks I will revert this for now and find a fix. the -L is required for looking though symlinks. It must be looping though them forever
