### ISSUE TITLE
[BUG] GSLT Token Insurgency Sandstorm enable ranked server

### ISSUE THREAD

**Issue by alantody** [GameServerManagers/LinuxGSM#4016]
I have a problem with enable XP ranked server, above my try to enable XP on dedicated server with GLST Token.

I have added GSLTToken=${GSLTToken}, parameter and -MapCycle=MapCycle.txt its correct?

**command line** 

ip="0.0.0.0"
port="27102"
queryport="27131"
rconport="27015"
rconpassword=""
servername="MyserverName"
defaultmap="Canyon"
defaultscenario="Scenario_Crossing_Checkpoint_Security"
maxplayers="10"
GSLTToken="000000000MyTokenHere"

startparameters="${defaultmap}?Scenario=${defaultscenario}?MaxPlayers=${maxplayers} -Port=${port} -QueryPort=${queryport} -GSLTToken=${GSLTToken} -hostname='${servername}' -Rcon -GameStats -MapCycle=MapCycle.txt -RconPassword=${rconpassword} -RconListenPort=${rconport} -log"`

-   **Distro:** [Ubuntu 18.04]
-   **Running on Dedicated server

**Comment by flippelt** [comment]
Any update on this? Also have the same problem

**Comment by Claiyc** [comment]
GSLTToken="000000000MyTokenHere"
> 
> startparameters="${defaultmap}?Scenario=${defaultscenario}?MaxPlayers=${maxplayers} -Port=${port} -QueryPort=${queryport} -GSLTToken=${GSLTToken} -hostname='${servername}' -Rcon -GameStats -MapCycle=MapCycle.txt -RconPassword=${rconpassword} -RconListenPort=${rconport} -log"`

This looks fine to me. Does the gslt token show in the name of the running process?

**Comment by dgibbs64** [comment]
The details look correct. there is extensive docs for INS:S that are worth double checking with https://mod.io/g/insurgencysandstorm/r/server-admin-guide
