### ISSUE TITLE
[BUG] Fail to install get5 mod

### ISSUE THREAD

**Issue by tech62** [GameServerManagers/LinuxGSM#4018]
On a fresh server install after `./csgoserver mi install`, type 'get5' and confirm.
I'm unable to install get5 from the script, can you investigate please ?

Thanks !

```
 Installing Get 5
 =================================
 clearing mod download directory /home/csgoserver1/lgsm/mods/tmp...OK
 creating mod download directory /home/csgoserver1/lgsm/mods/tmp...OK
 fetching  ...FAIL 
```

**Comment by h3o66** [comment]
Made a PR to fix this, it seem the old builds are gone from the url it tried to grb them.

**Comment by dgibbs64** [comment]
s
