### ISSUE TITLE
[BUG] jq: error (at :0): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by Vertux** [GameServerManagers/LinuxGSM#4022]
## User Story

I did a fresh installation for a Valheim server, everything wet fine so far, but when I tried to start the server I got this error:

>  ./vhserver start
>  jq: error (at <stdin>:0): Cannot iterate over null (null)
>  [ FAIL ] Starting vhserver: Unable to start Valheim Server`

I have seen that it is an already known issue, but oviously it isn't solved yet.

## Basic info

-   **Distro:** [Debian GNU/Linux 10 (buster)]
-   **Game:** [Valheim]
-   **Command:** [start]
-   **LinuxGSM version:** [v22.2.1]

## Further Information

*none*

## To Reproduce

Steps to reproduce the behaviour:

1. Fresh installation
2. Start the server: `./vhserver start`

## Expected behaviour

A flawless server start.

**Comment by h3o66** [comment]
the jq error here is probably not the overall issue why it does not start.

What do you got in the lgsm config set ?

A password for the server is afaik mandatory

**Comment by Vertux** [comment]
> the jq error here is probably not the overall issue why it does not start.
> 
> What do you got in the lgsm config set ?
> 
> A password for the server is afaik mandatory

@h3o66 Erverything is default, the only change I made was to set a server password in common.cfg

**Comment by h3o66** [comment]
can you please upload a log with the crash ?
logfile from lgsm:
`log/console/vhserver-console.log`

**Comment by Vertux** [comment]
> can you please upload a log with the crash ? logfile from lgsm: `log/console/vhserver-console.log`

Here it is:

[vhserver-console.log](https://github.com/GameServerManagers/LinuxGSM/files/9932807/vhserver-console.log)

**Comment by EleventhOcean** [comment]
I was getting a console.log that looked almost identical to that on my server when I tried to fire it up last night to try out the mistlands beta.

Updating the server's OS from Ubuntu 18.04 to 20.04 this morning for unrelated reasons somehow resolved it for me. I know you're on Debian, so this isn't going to help you directly, but it seemed like info worth sharing in case it helps someone smarter than I am figure this issue out.

**Comment by Vertux** [comment]
@EleventhOcean I am thankful for any hint. I plan to upgrade my Debian server between the years (it needs a little of preperation), maybe it will solve the issue too, even it is a different Linux distribution. Before I will give the beta a try.

**Comment by Vertux** [comment]
I have solved the problem.

```
Unable to preload the following plugins:
	libparty.so
```

Microsofts PlayFab Party library `ibparty.so` was the reason. At least on Debian you have to install it manually.
You can get the latest version [here](https://github.com/PlayFab/PlayFabParty/releases/)

- Unzip the file. navigate to `./linux/x64/Release` there you will find `libparty.so`. 
- Copy `libparty.so` to `/home/vhserver/serverfiles/valheim_server_Data/MonoBleedingEdge/x86_64 ` 

Start the server `./vhserver start` and everything should work now. 

I did no further tests, but everything looks fine so far.
