### ISSUE TITLE
[BUG] [SATISFACTORY] modifications overwritten

### ISSUE THREAD

**Issue by Allread** [GameServerManagers/LinuxGSM#4023]
## User Story

As a modification of a file, I want the modifications not to be overwritten.

## Basic info

-   **Distro:** Debian 11
-   **Game:** Satisfactory
-   **LinuxGSM version:** v22.2.1

## Further Information

When editing the "/serverfiles/FactoryGame/Saved/Config/LinuxServer/Game.ini", the modification is overwritten with the default parameters during a restart of the server

## To Reproduce

1. Edit "/serverfiles/FactoryGame/Saved/Config/LinuxServer/Game.ini"
2. Save
3. Restart the server (./sfserver restart)
4. ré-edit "/serverfiles/FactoryGame/Saved/Config/LinuxServer/Game.ini"

## Expected behaviour

Let the modifications remain

**Comment by h3o66** [comment]
tbf: this is probably not a but on our side, as i guess the server writes on shotdown the config.
Please check this without a online server and report this to the developer, i do not think we can do here to much.
