### ISSUE TITLE
[BUG] UT99 Details command won't show Web Admin port properly

### ISSUE THREAD

**Issue by Wolterhon** [GameServerManagers/LinuxGSM#4043]
## User Story

As a server admin, I want to see my current Web Admin port for the UT99 server so that I could connect to the web admin panel with the specified port.

## Basic info

-   **Distro:** [Debian 11 5.10.0-18-amd64]
-   **Game:** [Unreal Tournament 99]
-   **Command:** [Details]
-   **LinuxGSM version:** [v22.2.1]

## Further Information

Despite the fact that the web panel works with the port specified in the config file (/home/ut99server/serverfiles/System/ut99server.ini in the ListenPort parameter of the [UWeb.WebServer] section) the port is not present in the Details output, it's shown as 'Web Admin 0 tcp 3' (screenshot 1).

## To Reproduce

Steps to reproduce the behaviour:

1. Make sure you have a port specified in the config (path can be seen above in the Further Information section).
2. Start the server and then issue the 'details' comand.
3. Despite the fact you can connect with the specified port to the web panel, the port is not present in the output of 'details'.

## Expected behaviour

Port should be visible in the output instead of always being 0.

![WindowsTerminal_2O8uUFBrsQ](https://user-images.githubusercontent.com/23475741/202858256-cd8ef58e-f159-4649-acb2-ecb470ab4ca2.png)

**Comment by dgibbs64** [comment]
Good catch we will need to look at this.

**Comment by dgibbs64** [comment]
Major refactor of details command incoming.

**Comment by dgibbs64** [comment]
refactor completed. Issue should now be resolved
