### ISSUE TITLE
[BUG] das läuft mal gar nicht.

### ISSUE THREAD

**Issue by theMagicKnight** [GameServerManagers/LinuxGSM#4044]
Minecraft auf Raspberry PI3 mit Debian11 64bit (2022-09-22-raspios-bullseye-arm64)

mcserver@minecraftserver:~ $ ./mcserver start
[ WARN ] Starting mcserver: Missing dependencies: lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386Information! Automatically installing missing dependencies.
OK:1 http://security.debian.org/debian-security bullseye-security InRelease
OK:2 http://deb.debian.org/debian bullseye InRelease
OK:3 http://deb.debian.org/debian bullseye-updates InRelease
OK:4 http://archive.raspberrypi.org/debian bullseye InRelease
Paketlisten werden gelesen… Fertig                
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket lib32gcc-s1 kann nicht gefunden werden.
E: Paket lib32stdc++6 kann nicht gefunden werden.
E: Mittels regulärem Ausdruck »lib32stdc++6« konnte kein Paket gefunden werden.
sudo apt update; sudo apt install lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386
[ WARN ] Starting mcserver: Check RAM: 1G required, 910MB available
* Minecraft server may fail to run or experience poor performance.
[  OK  ] Starting mcserver: Willkommen auf unseren Pi MinecraftSystem
mcserver@minecraftserver:~ $ 

Ihr habt wirklich eine hammer Arbeit gemacht aber ich kann die fehlenden Pakete nicht installieren. liegt das nun an meiner 64bit Version.

Vielleicht könnte man solche probleme irgendwie während der Installation bereinigen.

danke

**Comment by Claiyc** [comment]
First of all, english only please. Secondly, a normal minecraft server cannot be installed on a raspberry pi (like most gameservers) since the arm processors cannot run such applications (superficial knowledge). There is a project on github claiming to support minecraft servers on a raspberry pi: https://github.com/cuberite/cuberite.git
LGSM does not support that though.

**Comment by theMagicKnight** [comment]
Now, following this guide, I've had success. thanks 
https://www.mielke.de/blog/Ein-Minecraft-Server-fuer-die-Kids-auf-einem-Raspberry-Pi--497/
