### ISSUE TITLE
Valheim server not installing

### ISSUE THREAD

**Issue by naoestu** [GameServerManagers/LinuxGSM#4046]
## Basic info

-   **Distro:** Debian 11.5 amd64
-   **Game:** Valhiem
-   **Command:** ./vhserver install

## Further Information

Valheim server is not installing.
All dependencies are ok.

"./valheim install" command output:

"[ START ] Installing vhserver: SteamCMD
Redirecting stderr to '/home/vhserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

Bad expression token: [Bad expression token: [../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

Bad expression token: [Bad expression token: [../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x585de320/0x0xf777db'
Complete! Installing vhserver: SteamCMD

=================================
Was the install successful? [Y/n] "

**Comment by h3o66** [comment]
> Bad expression token: [Bad expression token: [../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
> [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
> threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x585de320/0x0xf777db'

this looks like a connection problem on your side, nothing initial on lgsm side.

**Comment by naoestu** [comment]
I thought the same, but i've no problems at all installing other kind of game servers with lgsm.

**Comment by kaonashi696** [comment]
I'm having the same issue, anyone found a fix?
