### ISSUE TITLE
cs 1.6 on Ubuntu 22.04 - error: malloc(): invalid size (unsorted)

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#4047]
Counter-Strike 1.6 Debuging
=================================
Distro:          Ubuntu 22.04.1 LTS
Architecture:    x86_64
Kernel:          5.15.0-53-generic
Hostname:        xxxx
tmux:            tmux 3.2a
Avg Load:        0.75, 0.25, 0.09
Free Memory:     1.6GB
Free Disk:       36G
glibc required: 2.14
Game Server IP: 0.0.0.0:27015
Internet IP:    xxx:27015
Server password:        NOT SET
Start parameters:
./hlds_run -game cstrike -strictportbind +ip 0.0.0.0 -port 27015 +clientport 27005 +map de_dust2 +servercfgfile csserver.cfg -maxplayers 16 -debug

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If csserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debuging csserver: Stopping any running servers
[ INFO ] Stopping csserver: LinuxGSM is already stopped
[  OK  ] Debuging csserver: Starting debug
Enabling debug mode
Auto-restarting the server on crash

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
malloc(): invalid size (unsorted)
Aborted (core dumped)
email debug.log to linux@valvesoftware.com
Wed Nov 30 19:27:14 UTC 2022: Server restart in 10 seconds

**Comment by dgibbs64** [comment]
Check your server's memory usage: Make sure that your server has enough free memory to run the game server. If the server's memory is fully utilized, it could cause the malloc error you are seeing. You can check the server's memory usage using the free or top command.
