### ISSUE TITLE
[Server Request] Euro Truck Simulator 2/American Truck Simulator Dedicated Server

### ISSUE THREAD

**Issue by DigitalFriends** [GameServerManagers/LinuxGSM#4050]
## What game server would you like to add?

Euro Truck Simulator 2 & American Truck Simulator

## Can you link to any tutorials or guides?
The readme file is included with the Dedicated Server tools on Steam, i have made a paste of the readme here:
https://hastebin.com/sutuzuceqi.sql

## Is the server on Steam?

-   [X] Yes
-   [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[1948160] https://steamdb.info/app/1948160/
[2239530] https://steamdb.info/app/2239530/

## Is the server supported on Linux?
We only support Linux servers and do **not** support Wine.

-   [X] Yes
-   [ ] No

**Comment by sixxt** [comment]
The **Hastebin** link you provided no longer works, also SCS created a **Dedicated Server** category on their wiki
[Documentation/Tools/Dedicated Server - SCS Modding Wiki](https://modding.scssoft.com/wiki/Documentation/Tools/Dedicated_Server)
