### ISSUE TITLE
[BUG] LinuxGSM download problem when IPV6 is working

### ISSUE THREAD

**Issue by d3adwolf** [GameServerManagers/LinuxGSM#4053]
## User Story

If the system supports the IPV6 protocol and if it works via wget, LinuxGSM does not want to download.

## Basic info

-   **Distro:** [Ubuntu 22.04.1 LTS]
-   **Game:** [PaperMC]
-   **Command:** [wget]
-   **LinuxGSM version:** [NULL]

## Further Information

```
~ » wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh pmcserver               20:14:17
--2022-12-11 20:14:38--  https://linuxgsm.sh/
Resolving linuxgsm.sh (linuxgsm.sh)... 2606:4700:3032::ac43:8701, 2606:4700:3031::6815:69e, 104.21.6.158, ...
Connecting to linuxgsm.sh (linuxgsm.sh)|2606:4700:3032::ac43:8701|:443...
```

**Comment by d3adwolf** [comment]
If you disable IPV6 via GRUB configurator, IPV4 will work - everything will work.

**Comment by h3o66** [comment]
Works for me, no problems here.
