### ISSUE TITLE
[Server Request] ICARUS

### ISSUE THREAD

**Issue by skynett81** [GameServerManagers/LinuxGSM#4056]
## What game server would you like to add?

[game server] Icarus

## Can you link to any tutorials or guides?
https://github.com/RocketWerkz/IcarusDedicatedServer

Provide any useful documentation or resources that might help.
https://github.com/RocketWerkz/IcarusDedicatedServer

## Is the server on Steam?

-   [X ] Yes
-   [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]
https://steamdb.info/app/2089300/

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

-   [X ] Yes  with wine
-   [X ] No

you can use Wine

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/icarus

**Comment by h3o66** [comment]
As stated in the template of the request, we do not support running gameservers on wine.
