### ISSUE TITLE
[FEATURE] Use OpenSpy master server for Unreal Tournament 2004

### ISSUE THREAD

**Issue by cetteup** [GameServerManagers/LinuxGSM#4086]
## User Story

As a server admin, I want my server to be listed on OpenSpy so that players can easily find it after Epic shut down their server list backend.

## Basic info

-   **Distro:** Any
-   **Game:** Unreal Tournament 2004
-   **Command:** Install
-   **LinuxGSM version:** v22.2.1

## Further Information

Epic games announced late last year that they will shut down their server list backend ("master server") on Jan 24th. The only currently available alternative is OpenSpy. Since the game cannot use more than one backend at any given time, the only option is to switch to OpenSpy entirely.

## Further Reading

- Epic announcement: https://www.epicgames.com/site/en-US/news/epic-is-turning-off-online-services-and-servers-for-some-older-games
- OpenSpy homepage: http://beta.openspy.net/en/
- OpenSpy guide for switching to their backend: http://beta.openspy.net/en/howto/ut2k-engine/ut2004
- Additional info for server admins: https://ut2004serverlist.com/?page_id=33

**Comment by SicariusFeroxis** [comment]
This also works for UT2003 (Demo) [you can get it here](https://github.com/SicariusFeroxis/ut2003demo/releases/tag/ut2003demo_v2206) with some simple hosts file editing and UT2003 (full game) [see this post](https://www.reddit.com/r/ut2003/comments/12wm8xr/revival_of_ut2003_thanks_to_free_software/)
