### ISSUE TITLE
rustserver rust server keeps shutting down easyanticheat

### ISSUE THREAD

**Issue by karenmcd** [GameServerManagers/LinuxGSM#4098]
After the recent update and figuring out how to open the query port and get that sorted out (i moved it to the default 28016 as the port was already open for both udp and tcp on my firewall and rcon and query can share the same port according to: https://wiki.facepunch.com/rust/Creating-a-server )

Now my server is shutting down every 10 minutes. Here's the console log:
```
(15:50:14) | Spawning 61826 entities
(15:50:16) | done.
(15:50:16) | Enforcing SpawnPopulation Limits
(15:50:31) | done.
(15:50:32) | Initializing 63812 entity links
(15:50:32) | done.
(15:50:32) | Initializing 423 stability supports
(15:50:32) | done.
(15:50:32) | Initializing 61836 entity save caches
(15:50:33) | done.
(15:50:33) | Gamemode Convar :
(15:50:33) | No Gamemode.
(15:50:45) | SteamServer Initialized
(15:50:48) | Server startup complete
(15:50:49) | SteamServer Connected
(15:50:52) | BradleyAPC Spawned at :(532.0, 41.7, -349.0)
(15:50:59) | Checking for new Steam Item Definitions..
(15:55:49) | Saved 62,760 ents, cache(0.07), write(0.02), disk(0.03).
(15:55:49) | Saving complete
(15:56:17) | EasyAntiCheat Server Shutting Down
```

nano /home/rustserver/serverfiles/server/rustserver/cfg/server.cfg
https://0bin.net/paste/qNyG7FQd#PQ2NxVQ-wk+8b2i1otPYd/3sw3cispyN7thZvc5Z8Rd
nano /home/rustserver/lgsm/config-lgsm/rustserver/rustserver.cfg
https://0bin.net/paste/IGE-EN3L#UJwnCZsDmFeUGAZsSOI0cdYvtrxBZFX76swUclWbHej

```
rustserver@debian-server:~$ ./rustserver details
Distro Details
==================================================================================
Date:      Thu 02 Feb 2023 03:43:40 PM PST
Distro:    Debian GNU/Linux 11 (bullseye)
Arch:      x86_64
Kernel:    5.10.0-20-amd64
Hostname:  debian-server
Uptime:    8d, 2h, 12m
tmux:      tmux 3.1c
glibc:     2.31

Server Resource
==================================================================================
CPU
Model:      Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz
Cores:      16
Frequency:  2012.107MHz
Avg Load:   2.64, 3.58, 3.18

Memory
Mem:       total  used   free   cached  available
Physical:  126GB  7.9GB  116GB  12GB    116GB
Swap:      7.5GB  0B     7.5GB

Storage
Filesystem:  /dev/sda4
Total:                  2.0T
Used:                   93G
Available:   1.8T

Network
IP:           0.0.0.0
Internet IP:  50.69.216.129

Game Server Resource Usage
==================================================================================
CPU Used:  341%
Mem Used:  4.9%  6414MB

Storage
Total:        8.7G
Serverfiles:  7.1G
Backups:      284K

Rust Server Details
==================================================================================
Server name:    Monthly Solo/Duo/Trio.1/2 Decay.No BP Wipe
App ID:         258550
Server IP:      0.0.0.0:28015
Internet IP:    50.69.216.129:28015
RCON password:  xxx
RCON web:       1
Maxplayers:     50
Game mode:      vanilla
Tick rate:      30
Save interval:  300s
Seed:           1462939625
Salt:           0
World size:     3500m
Status:         STARTED

rustserver Script Details
==================================================================================
Script name:            rustserver
LinuxGSM version:       v23.1.0
glibc required:         2.15
Discord alert:          off
Email alert:            off
Gotify alert:           off
IFTTT alert:            off
Mailgun (email) alert:  off
Pushbullet alert:       off
Pushover alert:         off
Rocketchat alert:       off
Slack alert:            off
Telegram alert:         off
Update on start:        off
User:                   rustserver
Location:               /home/rustserver
Config file:            /home/rustserver/serverfiles/server/rustserver/cfg/server.cfg

Backups
==================================================================================
No Backups created

Command-line Parameters
==================================================================================
 ./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.tickrate 30 +server.hostname "Monthly Solo/Duo/Trio.1/2 Decay.No BP Wipe" +server.identity "rustserver" +server.seed 1462939625 +server.salt 0 +server.maxplayers 50 +server.worldsize 3500 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xx" -logfile

Ports
==================================================================================
Change ports by editing the parameters in:
/home/rustserver/lgsm/config-lgsm/rustserver

Useful port diagnostic command:
ss -tuplwn | grep RustDedicated

DESCRIPTION  PORT   PROTOCOL  LISTEN
Game         28015  udp       1
Query        28016  udp       0
RCON         28016  tcp       1
App          28082  tcp       1

Status: STARTED
```

**Comment by karenmcd** [comment]
```
$ ss -tuplwn | grep RustDedicated
udp   UNCONN 0      0            0.0.0.0:28015      0.0.0.0:*    users:(("RustDedicated",pid=1435163,fd=51))
udp   UNCONN 0      0            0.0.0.0:28017      0.0.0.0:*    users:(("RustDedicated",pid=1435163,fd=46))
tcp   LISTEN 0      100          0.0.0.0:28016      0.0.0.0:*    users:(("RustDedicated",pid=1435163,fd=18))
tcp   LISTEN 0      100          0.0.0.0:28082      0.0.0.0:*    users:(("RustDedicated",pid=1435163,fd=41))
```
it appears the system isn't actually listening on port 28016 as it says in the details? it's using 28017? I also have that port open and forwarding to udp but it's still not working and still shutting down every 10 minutes for easyanticheat. it's also not displayed in the list of servers.

**Comment by karenmcd** [comment]
I did a `sudo apt update` and `upgrade` to the server, rebooted the server, restarted rust server. It's no longer restarting the server every 10 minutes but it's still not listed in the public server list of "community servers". https://www.battlemetrics.com/servers/rust/9629090 - the server has now been down for 12 hours - *le sigh* I've reviewed the notes over and over - the firewall has a port forward rule, idk what else to do. I see that someone commited a change to reflect the updated port rule for server.query, but i'm also noticing that in the command listed above:

```./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.tickrate 30 +server.hostname "Monthly Solo/Duo/Trio.1/2 Decay.No BP Wipe" +server.identity "rustserver" +server.seed 1462939625 +server.salt 0 +server.maxplayers 50 +server.worldsize 3500 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xx" -logfile```

there's nothing in that command about the +queryport 28017 or whatever i set it to in the configuration file. what's up with this?

**Comment by karenmcd** [comment]
After reading the changes done to _default.cfg I went into the rustserver.cfg file located at
`nano /home/rustserver/lgsm/config-lgsm/rustserver/rustserver.cfg`
and replaced the stuff after this line:
`## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters`

I commented out this:
`#fn_parms(){`
`#       parms="+app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.seed ${seed} +server.salt ${salt} +se>`
`#}`

After that, I added this line from the _default.cfg file to the part inside the rustserver.cfg file
Added this:
`startparameters="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.queryport ${queryport} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.gamemode ${gamemode} +server.level \"${serverlevel}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"`

This fixed it for me. Prior to doing this, I had also updated lgsm, the debian system and validated the rust server files. I wonder how badly broken the rest of my configuration files are, and if there's a way to check that easily for depreciated customized configuration files.

**Comment by karenmcd** [comment]
I'm getting an error that looks relevant on startup:

```(02:34:00) | []
(02:34:00) | server.description: "1/2 UPKEEP BP WIPES:Forced only. MAP WIPES:First Thursday of the month... or when I get home from work.\nMax group size 3.\nNo Griefing. Raiding and shoot on sight is fine.\nYou won't get banned for raiding in the first two weeks, but it's discouraged. This is a montly wipe server, go find somewhere else to be sweaty.\nYou will be banned without any warnings for bigotry. You will not be unbanned.\nThis includes racist slurs, homophobia, transphobia, abelism etc...\nReport violations and server specific problems directly to krustpunk@riseup.net"
(02:34:00) | server.url: "https://raddle.me/f/Games"
(02:34:00) | server.headerimage: ""
(02:34:00) | server.hostname: "Monthly Solo/Duo/Trio.1/2 Decay.No BP Wipe"
(02:34:00) | {
  "Hostname": "Monthly Solo/Duo/Trio.1/2 Decay.No BP Wipe",
  "MaxPlayers": 50,
  "Players": 0,
  "Queued": 0,
  "Joining": 0,
  "EntityCount": 0,
  "GameTime": "05/20/2024 09:00:42",
  "Uptime": 221,
  "Map": "Procedural Map",
  "Framerate": 0.0,
  "Memory": 0,
  "Collections": 0,
  "NetworkIn": 0,
  "NetworkOut": 0,
  "Restarting": false,
  "SaveCreatedTime": "02/02/2023 20:50:10",
  "Version": 2370,
  "Protocol": "2370.233.1"
}
(02:34:00) | []
(02:34:11) | Spawning 98102 entities
(02:34:13) | 63768 / 98102
(02:34:14) | done.
(02:34:14) | Enforcing SpawnPopulation Limits
(02:34:33) | done.
(02:34:34) | Initializing 100087 entity links
(02:34:34) | done.
(02:34:34) | Initializing 423 stability supports
(02:34:34) | done.
(02:34:34) | Initializing 98112 entity save caches
(02:34:35) | done.
(02:34:35) | Gamemode Convar :vanilla
(02:34:39) | Installed : 0spawn points.
(02:34:39) | Game created! type was : assets/prefabs/gamemodes/vanilla.prefab
(02:34:52) | Failed to check connectivity to the companion server: System.NullReferenceException: Object reference not set to an instance of an object
  at Steamworks.SteamServer.get_PublicIp () [0x00005] in <9f92ce1abb3a4a029e3bc1d14e2e6f26>:0 
  at ConVar.App.GetPublicIP () [0x00029] in <d8432ac647de4a03a0fc92272107d7a0>:0 
  at CompanionServer.Server+<GetPublicIPAsync>d__22.MoveNext () [0x0002b] in <d8432ac647de4a03a0fc92272107d7a0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at CompanionServer.Server+<CheckConnectivity>d__21.MoveNext () [0x00086] in <d8432ac647de4a03a0fc92272107d7a0>:0
(02:34:52) | SteamServer Initialized
(02:34:52) | Rust+ is already started up! Skipping second startup
(02:34:52) | Server startup complete
(02:34:53) | SteamServer Connected
(02:34:56) | BradleyAPC Spawned at :(767.3, 41.8, -310.8)
(02:35:03) | Checking for new Steam Item Definitions..
(02:36:36) | Chicken Butt[76561198020320514] was killed by boar (Boar) at (760.5, 17.8, 884.4)
(02:39:53) | Saved 99,013 ents, cache(0.10), write(0.03), disk(0.04).
(02:39:53) | Saving complete```

**Comment by dgibbs64** [comment]
Thanks for all this info

**Comment by karenmcd** [comment]
idk what happened, but sometime during my sleep, the server finally sorted itself out?

It's listed in the community server list again, and I woke up to two new users on the server and a returning user asking where it was yesterday.. *shrug*

I suspect that verifying the 'game/server' files and fixing the ## Server Parameters was what actually fixed it, and it just took a while to propagate new information

the updated server configuration also seems to have forced a new battlemetrics page:
https://www.battlemetrics.com/servers/rust/18576447 (new)
https://www.battlemetrics.com/servers/rust/9629090 (old)

This contributed to me believing that my server wasn't working properly outside of the LAN. The metrics page show the server came back online in the public lists and on the battlemetrics page about four (4) hours after updating lgsm, making the changes to the configuration file and validating the files. The new server listing would also explain why it wasn't found in the history as well, but I was already searching for it in the community server list from the start anyway.
