### ISSUE TITLE
[BUG] "GameServerManager" is looked for, but "GameServerManagers" is actual value

### ISSUE THREAD

**Issue by 0b10011** [GameServerManagers/LinuxGSM#4099]
In the main script, `githubuser` defaults to `GameServerManagers` (plural):

https://github.com/GameServerManagers/LinuxGSM/blob/6b73179e5d40112df16f9a8ace48e1123db19fbc/linuxgsm.sh#L50

But then `githubuser` is compared to `GameServerManager` (non-plural):

https://github.com/GameServerManagers/LinuxGSM/blob/6b73179e5d40112df16f9a8ace48e1123db19fbc/linuxgsm.sh#L170-L177

This seems to be a trend throughout the codebase: https://github.com/GameServerManagers/LinuxGSM/search?q=gameservermanager+githubuser

**Comment by dgibbs64** [comment]
Great catch

**Comment by dgibbs64** [comment]
8b99b83ac56772eeaa7e4995451420ce204ec33e
