### ISSUE TITLE
[Server request] Dota 2

### ISSUE THREAD

**Issue by zondor** [GameServerManagers/LinuxGSM#410]
HI Daniel.
Any plans to include Dota 2 servers support ?

**Comment by dgibbs64** [comment]
Didn't know there was an interest. I will certainly have a look in to it when I can. if you could post me some instructions it may help.

**Comment by dejan7** [comment]
+1

There is a new Dota client (Dota 2 Reborn), released last week and it uses valve's Source 2. The new client allows custom games created by moders and they are really popular. Until now, all normal Dota games were hosted on valve's servers. But now, the new custom games are hosted by players Having a dedicated server would be like super mega awesome, the number of people trying to host with bad upload speed is huge. 

New dota client: http://www.dota2.com/reborn/part1

I haven't played around with valve's software or source engine before, so i don't know where to start. But i know my way around  Linux servers, so i'll look into your examples for other game servers and see if i can do something. Also it would be awesome if you'd have the time to check this out right now, these new games are exploding right now and i know that the Dota community, consisting of millions of players, would be really grateful for this!

**Comment by Scriptzer0** [comment]
Dota 2 SteamCMD Instructions

https://forums.alliedmods.net/showthread.php?t=236635

**Comment by RavageCS** [comment]
I use it if you added it

**Comment by Etheras** [comment]
+1 if this is possible.

**Comment by UltimateByte** [comment]
https://steamdb.info/app/580/info/

**Comment by bibleuspro** [comment]
+1

**Comment by dgibbs64** [comment]
I have started branch for this. However there is a lack of instructions online on how a Dota 2 server works. I require some guidance on this one 

https://github.com/GameServerManagers/LinuxGSM/tree/feature/dota2server

**Comment by bergundy** [comment]
@dgibbs64 I've been trying to get a Dota 2 server running myself and from what I gather it's not supported anymore.

**Comment by dgibbs64** [comment]
yeah I think I am going to cancel support for this. There is little no no info out there about DOTA2 dedi servers
