### ISSUE TITLE
[BUG] Rust Monitor not working

### ISSUE THREAD

**Issue by NoaVF** [GameServerManagers/LinuxGSM#4101]
Not working Rust Monitor on Debian, after last update.

Feb 03 07:20:06.011 rustserver: MONITOR: INFO: Checking lockfile: CHECKING
Feb 03 07:20:07.017 rustserver: MONITOR: ERROR: Checking lockfile: No lockfile found: ERROR
Feb 03 07:20:07.025 rustserver: MONITOR: INFO: LinuxGSM version: v23.1.0
Feb 03 07:20:07.026 rustserver: MONITOR: ERROR: core_exit.sh exiting with code: 2

**Comment by tobasium** [comment]
Hi @all i found something interesting that there are changes with industrial Update in rust:

**Comment by dgibbs64** [comment]
Just to confirm the lastest rust update does change the query port to source query from raknet. I think it's typically game +1. If you are having issues double check your port settings in your config.
