### ISSUE TITLE
[Bug]: MineCraft server class java runtime not support

### ISSUE THREAD

**Issue by Arryboom** [GameServerManagers/LinuxGSM#4111]
### User story

running minecraft server failed

### Game

minecraft

### Linux distro

RedHat 9

### Command

command: start

### Further information

./mcserver start
[ FAIL ] Starting mcserver: Unable to start LinuxGSM

[mcserver@localhost console]$ cat mcserver-console.log
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

### Relevant log output

```shell
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

### Steps to reproduce

./mcserver start
[ FAIL ] Starting mcserver: Unable to start LinuxGSM

[mcserver@localhost console]$ cat mcserver-console.log
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by dgibbs64** [comment]
I'm assuming the dependencies are up-to-date on LinuxGSM. But will need to check.

**Comment by Arryboom** [comment]
I'm using java-17-openjdk on rocky linux

**Comment by h3o66** [comment]
> I'm using java-17-openjdk on rocky linux

Did you check if you use it as default version ?
`java -version`

By defaulf lgsm uses the system version
