### ISSUE TITLE
[Bug]: unexpected end of file

### ISSUE THREAD

**Issue by 0142929** [GameServerManagers/LinuxGSM#4113]
### User story

unexpected EOF while looking for matching `"' after update

### Game

ark

### Linux distro

Other

### Command

command: start

### Further information

[ .... ] Starting arkserver: karafuto-theisland./arkserver: eval: line 468: unexpected EOF while looking for matching `"'
[  OK  ] Starting arkserver: karafuto-theisland

**Comment by dgibbs64** [comment]
Issue caused in this line of code
https://github.com/GameServerManagers/LinuxGSM/blob/master/linuxgsm.sh#L496

looks like you might be using legacy parms rather than startparameters

**Comment by 0142929** [comment]
> Issue caused in this line of code https://github.com/GameServerManagers/LinuxGSM/blob/master/linuxgsm.sh#L496
> 
> looks like you might be using legacy parms rather than startparameters

thank you, i checked secrets-common.cfg it's empty.
how to check what i using now, legacy parms or startparameters?
