### ISSUE TITLE
[Bug]: Last Oasis executable name changed

### ISSUE THREAD

**Issue by Claiyc** [GameServerManagers/LinuxGSM#4129]
### User story

As a LGSM-User I want the Last Oasis executable name to be updated in the lgsm config

### Game

Last Oasis (loserver)

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

The Last Oasis executable name has apparently changed from 'MistServer-Linux-Shippin' to 'MistServer'

**Comment by dgibbs64** [comment]
Looking at the last oasis store page it looks like the game might have been abandoned by the developers.
