### ISSUE TITLE
[Bug]: Hurtworld server won't start

### ISSUE THREAD

**Issue by Xayanix** [GameServerManagers/LinuxGSM#4131]
### User story

Clean hwserver won't start

### Game

Hurtworld

### Linux distro

Debian 11

### Command

command: start

### Further information

Installed hurtworld server using this tutorial: https://linuxgsm.com/servers/hwserver/

After ./hwserver start it goes into this for few seconds:
![image](https://user-images.githubusercontent.com/12672902/222578165-6680155b-d021-4fd0-b17c-f859b0faf521.png)

and then:
![image](https://user-images.githubusercontent.com/12672902/222578192-4837b0c5-71a0-4c9d-a363-9684de9b2705.png)

### Relevant log output

```shell
Log:
 current directory to /home/hwserver/serverfiles
Found path: /home/hwserver/serverfiles/Hurtworld.x86_64
Mono path[0] = '/home/hwserver/serverfiles/Hurtworld_Data/Managed'
Mono path[1] = '/home/hwserver/serverfiles/Hurtworld_Data/Mono'
Mono config path = '/home/hwserver/serverfiles/Hurtworld_Data/Mono/etc'
Preloaded 'libCSteamworks.so'
eac_server.so [x64] :: OnLoad()
Preloaded 'libeac_server.so'
Preloaded 'libeasyanticheat.so'
Preloaded 'libsteam_api.so'
Preloaded 'steamclient.so'
Unable to preload the following plugins:
    libCSteamworks.so
    libeac_server.so
    libsteam_api.so
Player data archive not found at `/home/hwserver/serverfiles/Hurtworld_Data/data.unity3d`, using local filesystem
```

**Comment by h3o66** [comment]
Can reproduce this on my end with the latest version.
There is a bug with the command line options what makes the gameserver crash at the start
