### ISSUE TITLE
[Bug]: The Isle currently broken

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#4134]
### User story

As a developer I have found that The Isle server does not work currently

### Game

The Isle

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

The Isle is currently broken and I am unable to get it working. This requires further investigation. I have no more useful info at this time.

**Comment by h3o66** [comment]
startup is broken and the servername parsing.
Not sure if anything else is broken

**Comment by h3o66** [comment]
Added the latest config changes to the config file:
https://github.com/GameServerManagers/Game-Server-Configs/commit/0ebdc7c00f33f0011aa77d1f258a41f98acd007
