### ISSUE TITLE
[Bug]: Stationeers will not start after install on default settings

### ISSUE THREAD

**Issue by Virauge** [GameServerManagers/LinuxGSM#4137]
### User story

I want the server to start after install, even if by default settings.

### Game

Stationeers

### Linux distro

Ubuntu 20.04

### Command

command: install

### Further information

When running the install command, everything installs correctly until the it tries to pull the config files.  It pulls the default.ini, but when it tries to pull the setting.xml it gives the following error;

Config file: /home/stserver/serverfiles/setting.xml (FILE MISSING)

Some games create these files on first run.  This game does not.  

When starting the server it does the following;

Downloading Stationeers Configs
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
copying default.ini config file.
Config file not found, cannot alter it.

Config File Locations
=================================
Config file: /home/stserver/serverfiles/setting.xml (FILE MISSING)
LinuxGSM Config: /home/stserver/lgsm/config-lgsm/stserver
Documentation: https://docs.linuxgsm.com/configuration/game-server-config
[  OK  ] Starting stserver: UNAVAILABLE

I've created a setting.xml from the stationeers wiki, only changing the save path line and I get this when attempting to start the server;

[  OK  ] Starting stserver: NOT SET

Server never actually starts.  The detail command says it does, but it doesn't create and save files or worlds and you cannot connect to the server.

**Comment by dgibbs64** [comment]
This issue should be resolved as of a recent release. I have confirmed starting with default settings

**Comment by dementedusa** [comment]
the same thing is hapinging to me.  fresh install of the server


cript name:       stserver
LinuxGSM version:  v24.1.4
glibc required:    2.34
Discord alert:     off
Email alert:       off
Gotify alert:      off
IFTTT alert:       off
Pushbullet alert:  off
Pushover alert:    off
Rocketchat alert:  off
Slack alert:       off
Telegram alert:    off
Update on start:   off
User:              lgsm
Location:          /mnt/home2/stserver
Config file:       /mnt/home2/stserver/serverfiles/setting.xml (FILE MISSING)

Backups
=================================
No Backups created

Command-line Parameters
=================================
 ./rocketstation_DedicatedServer.x86_64 -LOADLATEST moon_save Moon

Ports
=================================
Change ports by editing the parameters in:
/mnt/home2/stserver/serverfiles/setting.xml

Useful port diagnostic command:
ss -tuplwn | grep rocketstation_D

DESCRIPTION  PORT  PROTOCOL  LISTEN
Game         0     udp       9
Query        0     udp       9

Status:	STARTED
