### ISSUE TITLE
[Feature]: dependency checking currently unavailable for Debian GNU/Linux 12 (bookworm).

### ISSUE THREAD

**Issue by peylight** [GameServerManagers/LinuxGSM#4148]
### User story

Please add depencency support for Debian 12 (bookworm)

### Game

Any

### Linux distro

Debian 11, Other

### Command

command: install

### Further information

After i try to install in Debian 12 i see a warning:

Checking Dependencies
=================================
Warning! LinuxGSM dependency checking currently unavailable for Debian GNU/Linux 12 (bookworm).

**Comment by h3o66** [comment]
This should land in lgsm as soon as debian 12 has a release date.
Currently I am not sure if we want to support debian 12 before the release or a prerelease at all.
