### ISSUE TITLE
[Bug]: "gameworld" var in details script looks like it concats 2 values with a newline from pzserver config 

### ISSUE THREAD

**Issue by ZacharyDaulton** [GameServerManagers/LinuxGSM#4150]
### User story

The scraper from the details command, variable "gameworld", gets a value from both Map= and MapRemotePlayerVisibility=

### Game

Project Zomboid

### Linux distro

Debian 11

### Command

command: details

### Further information

This config scraper should only return the string from the "Map=MapName" parameter. But it also copies the value from MapRemotePlayerVisibility=2

I have already ran the update-lgsm command. I am on the latest everything. 

https://github.com/GameServerManagers/LinuxGSM/blob/55694a0a88c5487b2947e06c0f85855543861273/lgsm/functions/info_game.sh#L1239

Relevant log output snippet pasted in the log output section.

Map=Muldraugh, KY
MapRemotePlayerVisibility=2

### Relevant log output

```shell
Players:                 0/6
Current map:             Muldraugh, KY
Game world:              Muldraugh, KY
RemotePlayerVisibility2  
Status:                  STARTED
```

### Steps to reproduce

1. Print the details from the latest Project Zomboid Server as of March 25th.

**Comment by dgibbs64** [comment]
I am doing a refactor of details so should be fixed when it comes out 😊

**Comment by ZacharyDaulton** [comment]
> I am doing a refactor of details so should be fixed when it comes out 😊

Awesome! Thank you for the fast response.

**Comment by dgibbs64** [comment]
Completed and should be working in the details refactor
