### ISSUE TITLE
[Black Mesa] Server Request

### ISSUE THREAD

**Issue by jhg21** [GameServerManagers/LinuxGSM#416]
Black Mesa recently got multiplayer support, and is currently in early access.

Store page: http://store.steampowered.com/app/362890/
SteamCMD app id: 346680

**Comment by dgibbs64** [comment]
Yup should be able to do this as its source engine. I don't own the game so could do with a kind person to donate me the game so I can test the server. :-)

**Comment by jhg21** [comment]
Sure, add me on Steam - it's on sale now! Perfect timing! :grinning: 

http://steamcommunity.com/id/wjg/

**Comment by dgibbs64** [comment]
Now available
