### ISSUE TITLE
error into ut99server install and update [Bug]: 

### ISSUE THREAD

**Issue by joe2000hd** [GameServerManagers/LinuxGSM#4168]
### User story

ut99server error at install and update

### Game

ut99

### Linux distro

Debian 10

### Command

command: update

### Further information

hello! there is a error in the linuxgsm ut99server  it installs ut99 with a system64 folder and set the path also to system64 instead of the correct folder :system it also updates servers on restart with that error so they are not able to start anymore, for users with no knowledge they cant use it after ......the correct path in the 2 default configs need to set to /system not /system64 also there is no need to create a system64 folder at ut99install what it does right now ......maybe you can correct this fast ? regards

**Comment by dgibbs64** [comment]
Becuase of the OldUnreal Patch UT99 now supports 64-bit. The latest update adds update functionality to ensure that the OldUnreal Patches are updates.
try 
```
./ut99server update
```

**Comment by joe2000hd** [comment]
Iam running 469b Server but the Update just creates a SYSTEM 64 folder and
changes the path into the two default configs to test folder results into
the Server dient Start anymore and same IT is if per example by me i
installed another instance of Server this makes  the same error creating a
system64 folder weich is empty just the ut.ini is created inside what will
result into the same all Servers dient Start anymore because cant find
ucc.bin and other needed files........this is if im true bullshit IT makes
the Servers Not Start anymore...also after Update or New Instance install
It s needed to Hand Charge the 2 default configs back to Point to the
System folder to make the Server run again....New instance install is now
Not possible anymore without changing back the default ins to the old
path....regards

Daniel Gibbs ***@***.***> schrieb am Di., 4. Apr. 2023, 22:33:

**Comment by dgibbs64** [comment]
I am struggling to figure out what is causing your issue. There should be no requirement to change the systemdir variable.
I have a fresh install of ut99, the binaries are present in the System64 directory and the server is starting up correctly. From update, 469c LinuxGSM is using the 64-bit binaries supplied by OldUnreal https://github.com/OldUnreal/UnrealTournamentPatches

I also rolled my install back to v23.1.0 did a fresh install, started the server, stopped the server, update LinuxGSM to v23.2.0, started the server got executable not found. Ran ./ut99server update then started the server and it worked.

**Comment by joe2000hd** [comment]
I Not Done a fresh install i hast 3 instances running....After install a 4.
Instance that happens crested on instance install a System 64 folder with
just the ini in IT and chancen the path in the default inis to System64
also ....maybe because i diddnt Update the Main instance before?

Daniel Gibbs ***@***.***> schrieb am Di., 4. Apr. 2023, 23:19:

**Comment by joe2000hd** [comment]
ok i figured out whats the error i didnt update the main instance just
updated lgsm, now after i updated the server and lgsm it created the files
in the system64 folder
and the server started after stoped updated again thats the good parts also
its a very nice work good job , the not so good part of it is the created
utserver.ini isnt compatible with the last time used server ini i
couldnt copy and past it into system64 folder the server wont start at all,
the next is i copied back the default created server ini to system folder
so it works again and server start but from this point i had to put all
this time used server settings and actors from the old server ini to the
new one also i had to upload all server packages used files and server
actor used files again to the system64 folder..after all that doing, the
server works now like before :) i later go on to update the other instances
? and hope that creates the new server-2 server 3 server 4 etc inis in the
system64 folder? and update them from hand  with the used server packages
and actors and files like i have done on the main server? then all should
be well i think?? regards

Am Mi., 5. Apr. 2023 um 09:05 Uhr schrieb joe xy ***@***.***
