### ISSUE TITLE
[Feature]: Ubuntu 23.04 support

### ISSUE THREAD

**Issue by romanvoloboev** [GameServerManagers/LinuxGSM#4171]
### User story

Ubuntu 23.04 will be released soon, so please add it support

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

Currently script says that there are no dependencies for it.

**Comment by dgibbs64** [comment]
fd55a294a17b430fa93821e788b298aa0f391dd1

**Comment by pythaeusone** [comment]
On 23.04 you get this msg:
Warning! Missing dependencies: bc binutils bsdmainutils bzip2 jq lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 netcat openjdk-17-jre rng-tools5 steamcmd tmux unzip
rng-tools works with: "sudo apt install rng-tools-debian"
but "sudo apt install netcat-traditional" wont work.
