### ISSUE TITLE
[Bug]: "Master server: not listed" when it is listed; different "Server IP" and "Internet IP"

### ISSUE THREAD

**Issue by romanvoloboev** [GameServerManagers/LinuxGSM#4172]
### User story

As a user I want to see message that server is listed when I call details command, and internet ip be same as server ip

### Game

Squad

### Linux distro

Ubuntu 22.04

### Command

command: details

### Further information

I have server with many ip addresses
In config /config-lgsm/squadserver.cfg I put ip=*.*.*.161
And command line is: 
./SquadGameServer.sh MULTIHOME=*.*.*.161 RANDOM=ALWAYS Port=7787 QueryPort=27165

But as result I get this
<img width="666" alt="Снимок экрана 2023-04-05 в 21 32 08" src="https://user-images.githubusercontent.com/13852208/230173965-ae18ffba-f679-41aa-85ca-a3c7aac70c50.png">

As you can see
1. server internet IP is different from IP in command line (I don't use IP which ends with 160 anywhere)
2. master server status is NOT LISTED , but it's listed, I can see it and join

Please fix that

**Comment by dgibbs64** [comment]
Both the internet IP and interface IP should be checked. It can sometimes take a few mins for some games to show in the server list. There might also be a port forwarding issue. However, on the next release, the check will first query using the internet IP address. Hopfully it help

**Comment by dgibbs64** [comment]
fixed in hotfix
