### ISSUE TITLE
[Bug]: Telegram alerts not working

### ISSUE THREAD

**Issue by romanvoloboev** [GameServerManagers/LinuxGSM#4173]
### User story

As a user I want to receive telegram alerts

### Game

Squad

### Linux distro

Ubuntu 22.04

### Command

command: test-alert

### Further information

When I call "test-alert" command, I receive this error

<img width="1232" alt="Снимок экрана 2023-04-05 в 21 49 15" src="https://user-images.githubusercontent.com/13852208/230177049-ec2397de-de6d-495e-8ff4-c54fb22001fa.png">

### Relevant log output

```
[ .... ] Sending Alert squadserver: Sending Telegram alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 4, column 380
[ FAIL ] Sending Alert squadserver: Sending Telegram alert: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}
```

**Comment by dgibbs64** [comment]
I have done a minor refactor and reseted telegram and it is currently working
