### ISSUE TITLE
[DST] Server Request

### ISSUE THREAD

**Issue by marvinlehmann** [GameServerManagers/LinuxGSM#418]
Don't Starve Together: http://store.steampowered.com/app/322330/
Useful links:
http://forums.kleientertainment.com/forum/73-dont-starve-together-beta/
http://dont-starve-game.wikia.com/wiki/Guides/Don%E2%80%99t_Starve_Together_Dedicated_Servers

**Comment by dgibbs64** [comment]
I can certainly give it a go I would need to read up on the server etc and may take some time as its not an engine I have done before. I also don't own the game so would also need this game donated.

**Comment by xFaNaTiix** [comment]
Donated! =)

**Comment by dgibbs64** [comment]
Thanks :D. I look forward to putting this together

**Comment by dgibbs64** [comment]
./dontstarve_dedicated_server_nullrenderer: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

Currently getting this issue while trying to start the server on both Debian and CentOS

**Comment by BlackDwarfUK** [comment]
As per http://dont-starve-game.wikia.com/wiki/Don%E2%80%99t_Starve_Together_Dedicated_Servers, libcurl4-gnutls-dev:i386 is a pre-req for the server on Debian.

**Comment by dgibbs64** [comment]
The server is released but not working in centos and maybe Debian...I cannot remember. either way I cannot resolve the issue until the game developers come up with something. I will keep an eye on this.

**Comment by mlopezv86** [comment]
I finally managed to install tmux on CentOS 6.2 and got the following error:

[ FAIL ] Starting dst-server: Unable to start dstserver: Tmux error:

Command
=================================
tmux new-session -d -s "dst-server" "./dontstarve_dedicated_server_nullrenderer "

Error
=================================
tmux: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

Fix
=================================
No known fix currently. Please log an issue.

Then, fixed it by creating the appropriate symlink: ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib64/libevent-2.0.so.5 (ln -s /usr/local/lib/libevent-2.0.so.5 /usr/lib/libevent-2.0.so.5 for 32-bit systems).

Tried to start again the server and got the following:
[ .... ] Starting dst-server: dstserverno server running on /tmp/tmux-500/default
[ FAIL ] Starting dst-server: Unable to start dstserver

No further info about what is failing or missing...I'm stuck there, but hopefully this post may help...a little.

**Comment by dgibbs64** [comment]
I recommend upgrading your distro. However DST didn't work in CentOS the last time I tried and probably still doesn't work. ./dstserver debug may give you a reason why. This issue us up to the developers to fix. So there may be nor info about this on there forums

**Comment by dgibbs64** [comment]
Added glibc fix for dstserver and tested working on debian 7. Testing on CentOS now

**Comment by dgibbs64** [comment]
Recent update to do with Caves. Will need to check this out and make any changes

**Comment by dgibbs64** [comment]
Closing this now as happy with compatability
