### ISSUE TITLE
-GMOD- Error 

### ISSUE THREAD

**Issue by TrAiZerZ** [GameServerManagers/LinuxGSM#420]
Hello, i have this error, i don't know how to do.

[ FAIL ] Starting gmod-server: Unable to start [FR] Militaryrp l VIP l Armee VS [ FAIL ] Starting gmod-server: Unable to start [FR] Militaryrp l VIP l Armee VS Gang l ClanSMG.fr: Tmux error:
# Command

tmux new-session -d -s gmod-server ./srcds_run -game garrysmod -strictportbind -ip 94.23.26.183 -port 27015 +host_workshop_collection 460261521 -authkey B652B0CC4CF26BE857C036030AE54165 +clientport 27005 +tv_port 27020 +gamemode militaryrp +map rp_locality +servercfgfile gmod-server.cfg -maxplayers 70
# Error

can't create socket: No space left on device
# Fix

No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

Thanks you to help me

**Comment by TrAiZerZ** [comment]
But when i do df -hT, putty say to me:

http://realitygaming.fr/proxy.php?image=http%3A%2F%2Fi.imgur.com%2FIdKdQHe.png&hash=b07108bdf2b943c0110824fdd2e38cd8

**Comment by dgibbs64** [comment]
/dev/root is 100% full. This is probably the issue

**Comment by TrAiZerZ** [comment]
Okey, and how to do ? Because i have 4To in total

**Comment by dgibbs64** [comment]
You have 1.8TB in /dev/md3 (/home) and only 20GB in /dev/root (/) you need to figure out what is using up all the storage in the  /dev/md3 partition. Try ncdu command might be useful

**Comment by TrAiZerZ** [comment]
http://prntscr.com/7gu1b2 
ncdu command don't work
I'm on Debian

**Comment by dgibbs64** [comment]
Install the program  ....This is more of an issue of you not yet understanding your server. I recommend learning a little more about Debian.

    apt-get install ncdu

**Comment by TrAiZerZ** [comment]
This is my first debian server sorry :/
I will look on internet for a tutorial about ncdu

**Comment by dgibbs64** [comment]
No problem we all started somewhere :). Google is your greatest tool in learning Linux. Helped me hundreds of times.

**Comment by TrAiZerZ** [comment]
Don't found, can you give me just a simply command to do ? 
I think 
ncdu /root/

But after i don't know what to do, all tutorial are in english and i don't speak realy good english :/

**Comment by dgibbs64** [comment]
ncdu /

should work

**Comment by TrAiZerZ** [comment]
http://prntscr.com/7gu7g9

**Comment by dgibbs64** [comment]
There is your issue. your /var directory is filling up the server. you can drill down further to figure out exactly what the issue it

**Comment by TrAiZerZ** [comment]
I don't understand Oo

**Comment by dgibbs64** [comment]
look in the /var directory

**Comment by TrAiZerZ** [comment]
http://prntscr.com/7gu9ej
Log is full
I think is Fail2Ban but not sure

**Comment by TrAiZerZ** [comment]
Is not Fail2Ban 
http://prntscr.com/7guags

**Comment by TrAiZerZ** [comment]
I Remove kern.log and kern.log.1 ?

**Comment by dgibbs64** [comment]
yeah I would clear the logs that are too big

**Comment by TrAiZerZ** [comment]
Work thx i love you <3 Give me your PayPal adress :D

**Comment by dgibbs64** [comment]
me@Danielgibbs.co.uk . Glad I could help :)

**Comment by TrAiZerZ** [comment]
You accept € ?

**Comment by dgibbs64** [comment]
PayPal Converts it

**Comment by TrAiZerZ** [comment]
I send you, this is not a lot but i don't have lot of money :)

**Comment by dgibbs64** [comment]
Its ok buddy. I will enjoy a drink on you :D thanks

**Comment by TrAiZerZ** [comment]
A good BEER ! xDD

2015-06-14 17:22 GMT+02:00 Daniel Gibbs <notifications@github.com>:
