### ISSUE TITLE
[Bug]: Passing an invalid game string to linuxgsm.sh fails with exit code of 0

### ISSUE THREAD

**Issue by dogue** [GameServerManagers/LinuxGSM#4217]
### User story

As a developer of a rust crate for interacting with lgsm, I want linuxgsm.sh to fail with a non-zero exit code so that my library can handle errors from lgsm.

### Game

Any

### Linux distro

Other

### Command

command: install

### Further information

When using the `linuxgsm.sh` script to download the management script for a game server, passing an invalid game string will result in a fatal error, but not an exit code that indicates a failure. I'm sharing an example copied and pasted from my shell below in the "relevant log output" section.

Due to how rustlang handles child processes, the library I'm writing relies on exit codes to indicate success/failure for external commands.

### Relevant log output

```shell
:lgsm-test/ (main✗) $ ./linuxgsm.sh nonexistent
[ FAIL ] unknown game server
:lgsm-test/ (main✗) $ echo $?
0
```

**Comment by dgibbs64** [comment]
nice easy win. PR completed and will be in the next release
