### ISSUE TITLE
[Bug]: Space in game name breaks info_game.sh

### ISSUE THREAD

**Issue by Pathas-Gamer** [GameServerManagers/LinuxGSM#4232]
### User story

As a user, I want the default installation of 7 Days to Die Alpha 21 experimental to function. It currently does not.

### Game

7 Days to Die A21

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

"./lgsm/modules/info_game.sh: line 134: Game: command not found" with stock game host name : "<property name="ServerName"                                             value="My Game Host"/> "

Change to My-Game-Host and error goes away.

### Steps to reproduce

Install 7 Days to Die on U22
Put "branch="latest_experimental" in /lgsm/config-lgsm/sdtdserver.cfg
Start server with default config

**Comment by Pathas-Gamer** [comment]
Originally found by pshock13, reported on Discord.

**Comment by xRuffKez** [comment]
#4222
