### ISSUE TITLE
[Bug]:  7 Days to Die Alpha 21 - legacy "ControlPanel" config items breaks game

### ISSUE THREAD

**Issue by Pathas-Gamer** [GameServerManagers/LinuxGSM#4233]
### User story

As a user, I want the default installation of 7 Days to Die Alpha 21 experimental to function. It currently does not.

### Game

7 Days to Die A21

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

https://7daystodie.com/a21-official-release-notes/

Server Administration and Multiplayer
WebDashboard
The old Web control panel for the server has been removed in favor of a new Web Dashboard.

---

Removing ControlPanelEnabled, ControlPanelPort and ControlPanelPassword items from config allows server to start.

### Steps to reproduce

Install 7 Days to Die with experimental build
Change server name to have no spaces (different bug, already submitted)
Attempt to start server, see errors related to unknown ControlPanel configuration items

**Comment by dgibbs64** [comment]
Thanks I will look at all the sdtd issues asap

**Comment by DrEVILish** [comment]
This isn't a LinuxGSM bug this is a 7Days to Die server issue, as the Game and Game Server are in Alpha / Experimental Alpha, breaking changes are expected.

Legacy items in config error correctly and show up in the logs.

This would be out of scope of this project, I'd suggest closing this ticket.
