### ISSUE TITLE
[Bug]: Ark: Survival Evolved should use separate IP for Multihome and EPIC

### ISSUE THREAD

**Issue by WildPenquin** [GameServerManagers/LinuxGSM#4238]
### User story

The default configuration file should not use same IP for both MultiHome and PublicIPForEpic

### Game

Ark: Survival Evolved

### Linux distro

Other

### Command

command: start

### Further information

**NOTE!** Multihome is really badly documented - please correct me if I've guessed any misinformation here!

It seems  that Multihome is used for many instances running on the same computer with many IP addresses (or interfaces). This is typically (always?) a local IP i.e. LAN address. This may sometimes be a public IP address, in case the computer is running directly on a public IP address with no NAT.

The PublicIPForEpic is always a public IP address (and is used for crossplay compatibility only?).

If both options are given, these options should be set separately and to different values. They should never match each other, or may **only** do so in the case if the server is not behind a NAT, but then setting PublicIPForEpic is superfluous (see Wiki documentation). If Multihome is set to a public IP address, when the server is behind a NAT, the server will fail (it will run but not listen to any connections).

In a nutshell:

- Multihome is the listening address of the server (a LAN address or in case of no NAT, a public IP address)
- PublicIPForEpic will *always* be a public IP address, and makes no sense to set if matches Multihome, i.e. is only needed only if behind a NAT (see link 1).

I suggest changing the default configuration file as such:

```
ip="aaa.bbb.ccc.ddd" # a public IP address - 0.0.0.0 will not work, EPIC clients can not connect!
localip="0.0.0.0" # the listen address, your local IP if behind a NAT - 0.0.0.0 will work for most users
startparameters="${defaultmap}?AltSaveDirectoryName=${altsavedirectoryname}?listen?MultiHome=${localip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port} -automanagedmods -cro    ssplay -PublicIPForEpic=${ip}"
```

1) https://ark.fandom.com/wiki/Server_configuration

### Steps to reproduce

Set a public IP address, using the default configuration as a base.
`ip="aaa.bbb.ccc.ddd"`

The server **will** run but not listen to any connections.

**Comment by dgibbs64** [comment]
PR has been created and the ip address docs have been updated
