### ISSUE TITLE
[Ark: Survival Evolved] Server Request

### ISSUE THREAD

**Issue by SebastienGautier** [GameServerManagers/LinuxGSM#424]
Ark: Survival Evolved dedicated servers are now available on linux.
AppID : 376030

I did not found any documentation for linux yet but I just started manually the server installation.

**Comment by Scarsz** [comment]
Leaving this here for reference @dgibbs64 

```
+login anonymous
+app_update 376030
```

**Comment by dgibbs64** [comment]
Unreal Engine should be a good one to do. There will be a few servers running this engine in the future

**Comment by groseb** [comment]
Some instructions are available here : http://steamcommunity.com/app/346110/discussions/0/594820656471833280

**Comment by k4n30** [comment]
+1

**Comment by SaturnsVoid** [comment]
Yay!! I will take this as a yes!

**Comment by Scarsz** [comment]
Should be noted though, neither me or @dgibbs64 actually own ARK to test the server when a script would be ready

**Comment by SaturnsVoid** [comment]
You guys should get it, Its pretty sweet! Its like rust but with a lot more environment and the Unreal Engine 4 makes it just look amazing in 4k.

Its on sale right now on steam.

**Comment by k4n30** [comment]
The dedicated server is free (well will be on linux very soon as it already is on Windows), so you shouldn't need to own it

**Comment by Scarsz** [comment]
Yes, we don't need to own it. @dgibbs64 likes to actually test the server by going on it himself before releasing them, though, to make sure it actually works when it's released.

**Comment by dgibbs64** [comment]
Wow a flurry of requests for this one. Im look forward to this one. @Scarsz is correct in that I prefer to test that I can actually connect to the server and it works for me before release and I may even give the game a try myself. This game is not required for me to develop a script but is preferred. 

I will be starting development as soon as I can :)

**Comment by dgibbs64** [comment]
I have released a version of arkserver. However note that its still buggy and all features dont yet work. But the basics are there so should start a server

https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/ARKSurvivalEvolved/arkserver

**Comment by dgibbs64** [comment]
I have officially released arkserver. I have found it difficult to test however I believe it should work. Please report any bugs of issues.
