### ISSUE TITLE
[Bug]: Always get the same error with SteamCMD since a few days ago now

### ISSUE THREAD

**Issue by derlappen** [GameServerManagers/LinuxGSM#4248]
### User story

as csgoserver i want to ./csgoserver install but SteamCMD then gives me an Error

### Game

csgo

### Linux distro

Ubuntu 22.04

### Command

command: install

### Further information

Every time i try to install the server i get that error message. 
I tried it on a virtual machine using the exact same install and it worked without problems.
Does anyone know what'S wrong with my system? because i don't think that it is the script.

### Relevant log output

```shell
Installing Counter-Strike: Global Offensive Server
=================================
[ START ] Installing csgoserver: SteamCMD
Redirecting stderr to '/home/csgoserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.	 Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57be3320/0x0xf7782a'
Complete! Installing csgoserver: SteamCMD

=================================
```

### Steps to reproduce

downlaod and install server described on LGSM-Website

**Comment by derlappen** [comment]
new progress: 
I copied ".local" und ".steam" from an old install over to /home/csgoserver/ and at least it is installing and running

**Comment by cyberlimbo** [comment]
Same problem when fresh installing Rust server.
`Installing Rust Server
=================================
fetching GitHub update_steamcmd.sh...OK
[ START ] Installing rustserver: SteamCMD
Redirecting stderr to '/home/rustserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57d72320/0x0xf7715b'
Complete! Installing rustserver: SteamCMD`

**Comment by cyberlimbo** [comment]
Why is this still not solved yet?
I just tried a new install of LGSM (rust server) in Debian 12 and 11 and the problem persists.

`Installing Rust Server
=================================
fetching GitHub update_steamcmd.sh...OK
[ START ] Installing rustserver: SteamCMD
Redirecting stderr to '/home/rustserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57c36b30/0x0xf7bd1b'
Complete! Installing rustserver: SteamCMD`

**Comment by LordSith77** [comment]
Same problem with 7 Days to Die.
```
Installing 7 Days To Die Server
=================================
[ START ] Installing sdtdserver: SteamCMD
Redirecting stderr to '/home/sdtdserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57295320/0x0xf772bb'
Complete! Installing sdtdserver: SteamCMD
```

**Comment by dgibbs64** [comment]
This is a steamcmd issue. Looks like Valuve did some updates recently. My suggestion would be to fully remove steamcmd `apt purge steamcmd` and look for any steamcmd directories and delete them. Hopefully that clears the issue. 

It might be somthing that needs to be raised with Valve themselves https://github.com/ValveSoftware/steam-for-linux

**Comment by LordSith77** [comment]
Removed SteamCMD and deleted all folders I could find. Re-ran the installer for GSM and got the same error. So I'm going to assume it's a Valve issue.

**Comment by DareFox** [comment]
Check if your VPS provider doesn't ban SteamCMD. My provider did and that's why I had problem with SteamCMD

**Comment by LordSith77** [comment]
> Check if your VPS provider doesn't ban SteamCMD. My provider did and that's why I had problem with SteamCMD

I don't use a VPS, I have my own server running Ubuntu 20.04 and didn't have a problem like this before now.
Even running the standard SteamCMD:
`steamcmd +login anonymous +force_install_dir /mnt/sdb/7dtd_server +app_update 294420 validate +quit`
Errors out about being offline, so Steam must be having some issues.

**Comment by dgibbs64** [comment]
I havnt heard anyone highlighting this issue anymore. I am going to close this issue as a SteamCMD problem
