### ISSUE TITLE
[Bug]: Github API rate limit exceeded

### ISSUE THREAD

**Issue by jeremyjohn** [GameServerManagers/LinuxGSM#4249]
### User story

As a rustserver, I want to update, install mods and update mods without any errors.

### Game

Rust

### Linux distro

Ubuntu 20.04

### Command

command: mods-update

### Further information

```
{
"message": "API rate limit exceeded for IP xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

By running many lgsm commands/scripts that query github API publicly, github will then rate limit the IP.
This is bad if you have 1 outbound IP shared by multiple game servers on the same machine.

### Relevant log output

```shell
curl: (3) URL using bad/illegal format or missing URL
FAIL


Curl will FAIL because of github's rate limit.
```

### Steps to reproduce

1. Install LGSM `auto-install`
2. Install Rust `rustserver install`
3. Update Rust `rustserver update`
4. Install oxide `mods-install`
5. Update oxide `mods-update`

**Comment by dgibbs64** [comment]
There must have been a lot of API requests in a short time to hit that limit. LinuxGSM doesnt make many queries to the GitHub API at one time.  My only suggestion is to wait and try again as there is nothing I can do about GitHub rate limits
