### ISSUE TITLE
[Bug]: Unturned console is not visible

### ISSUE THREAD

**Issue by donCESAR12345** [GameServerManagers/LinuxGSM#4252]
### User story

Using an Arch Linux server with Unturned server from LGSM, I can't see any output when connecting to the console.

### Game

Unturned

### Linux distro

Other

### Command

command: console

### Further information

Using Arch Linux, every package is updated, Unturned server doesn't outputs anything, console command succesfully connects to tmux session, but I'm unable to see any output.
![image](https://github.com/GameServerManagers/LinuxGSM/assets/64916276/c642d0ba-2d6c-4930-b258-c1dafd5a8b35)
Input while not visible, it is actually being read, as I can write "Shutdown" and succesfully stop the server.

### Steps to reproduce

1. Install Unturned LGSM
2. Launch server using `./untserver start`
3. Connect to the console `./untserver console`
4. Output is blank.

**Comment by dgibbs64** [comment]
I have tested this myself on Ubuntu and its working. I am unsure if this is an Arch specific issue as I dont run it myself.
