### ISSUE TITLE
[Bug]: Garry's Mod x64 Server doesn't start after GMOD update.

### ISSUE THREAD

**Issue by SMorganYu** [GameServerManagers/LinuxGSM#4253]
### User story

Server doesn't start after update

### Game

Garry's Mod

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

Yesterday I updated the server (as clients could not log in to the server). After which the server on Linux GSM stopped starting. Gives an error and then goes to reboot.
```
Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run_x64 command line to generate a debug.log to help with solving this problem
```

But if i run it directly ./srcds_run_x64 with the usual parameters like map, gamemode and so on, everything works. (debug.log not creating). I would like to ask who has such a problem?

UPD: debug.log (https://pastebin.com/JgpEEhiv)

**Comment by dgibbs64** [comment]
Looks like a https://docs.linuxgsm.com/faq#how-do-i-solve-a-segmentation-fault
