### ISSUE TITLE
[Bug]: Project Zomboid javaram setting does not work

### ISSUE THREAD

**Issue by ddan39** [GameServerManagers/LinuxGSM#4255]
### User story

In pzserver.cfg (or common.cfg) if i set javaram setting I expect that to take effect for the jvm 

### Game

Project Zomboid

### Linux distro

Debian 12

### Command

command: start, command: details

### Further information

It looks like you attempt to set the jvm Xmx value by passing the javaram setting (via startparameters=) as an -Xmx command line argument to the main executable,./start-server.sh, script. This does not work though. The Xmx value must be set in the ~/serverfiles/ProjectZomboid64.json or ~/serverfiles/ProjectZomboid32.json files.

This was confirmed by setting javaram="20480" in my pzserver.cfg file, then running like below, where you can see the JVM is still actually running at the default(for the LinuxGSM downloaded ProjectZomboid64.json file at least) 8g setting.
```
$ jhsdb jmap --heap --pid `pidof ProjectZomboid64`
Attaching to process ID 63719, please wait...
WARNING: Hotspot VM version 17.0.1+12-LTS does not match with SA version 17.0.7+7-Debian-1deb12u1. You may see unexpected results. 
Debugger attached successfully.
Server compiler detected.
JVM version is 17.0.1+12-LTS

using thread-local object allocation.
ZGC with 8 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 8589934592 (8192.0MB)
   NewSize                  = 1363144 (1.2999954223632812MB)
   MaxNewSize               = 17592186044415 MB
   OldSize                  = 5452592 (5.1999969482421875MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 22020096 (21.0MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
 ZHeap          used 1484M, capacity 1484M, max capacity 8192M
```

Then if I change it in ProjectZomboid64.json file from 8g to 20g and restart, it shows:

```
$ jhsdb jmap --heap --pid `pidof ProjectZomboid64`
Attaching to process ID 66782, please wait...
WARNING: Hotspot VM version 17.0.1+12-LTS does not match with SA version 17.0.7+7-Debian-1deb12u1. You may see unexpected results. 
Debugger attached successfully.
Server compiler detected.
JVM version is 17.0.1+12-LTS

using thread-local object allocation.
ZGC with 8 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 21474836480 (20480.0MB)
   NewSize                  = 1363144 (1.2999954223632812MB)
   MaxNewSize               = 17592186044415 MB
   OldSize                  = 5452592 (5.1999969482421875MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 22020096 (21.0MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
 ZHeap          used 1650M, capacity 2186M, max capacity 20480M
```

You can also see in the log excerpt attached that the ProjectZomboid64 program saw and the -Xmx option and said it was unknown. (the other unknown option I will open another bug for :P )

Thanks!

### Relevant log output

```shell
$ cat 03-07-23_23-01-24_DebugLog-server.txt 
[03-07-23 23:01:24.466] LOG  : General     , 1688425284466> 199,310,297> cachedir set to "/home/pzserver/Zomboid".
[03-07-23 23:01:24.544] LOG  : General     , 1688425284544> 199,310,374> version=41.78.16 demo=false.
[03-07-23 23:01:24.544] LOG  : General     , 1688425284544> 199,310,375> revision= date= time=.
[03-07-23 23:01:24.545] LOG  : General     , 1688425284545> 199,310,375> unknown option "--ip".
[03-07-23 23:01:24.545] LOG  : General     , 1688425284545> 199,310,375> unknown option "0.0.0.0".
[03-07-23 23:01:24.545] LOG  : General     , 1688425284545> 199,310,375> unknown option "-Xmx20480M".
[03-07-23 23:01:24.545] LOG  : General     , 1688425284545> 199,310,376> server name is "pzserver".
[03-07-23 23:01:24.546] LOG  : General     , 1688425284546> 199,310,376> checking server WorldVersion in map_t.bin.
[03-07-23 23:01:24.547] LOG  : General     , 1688425284547> 199,310,377> Loading networking libraries....
[03-07-23 23:01:24.547] LOG  : General     , 1688425284547> 199,310,378> Loading steam_api....
[03-07-23 23:01:24.548] LOG  : General     , 1688425284547> 199,310,378> Loading RakNet64....
```

### Steps to reproduce

1. change javaram in ~/lgsm/config-lgsm/pzserver/pzserver.cfg
2. start server
3. observe in logs and java debugger that ram was not changed

**Comment by dgibbs64** [comment]
I have removed the java memory settings in start parameters for next release

**Comment by yxliaoyx** [comment]
@ddan39 

According to [pzwiki](https://pzwiki.net/wiki/Startup_parameters), JVM arguments must end with a `--`
Example:
```
bash start-server.sh -Xms2048m -Xmx2048m --
```

**Comment by ddan39** [comment]
@yxliaoyx 

Good find. It does indeed work with like `bash start-server.sh -Xmx4g -- -servername test2` as well, to provide both JVM and PZ server args at the same time. With this it would be possible to put the java ram settings into the lgsm config startup parameters if desired. I still don't like the idea of doing that though, because all PZ server guides tell you to edit the ProjectZomboid64.json file for linux, and the arguments provided on the command line overwrites that. I could definitely see a lot of people googling for how to increase PZ server ram, following a guide and editing the ProjectZomboid64.json, and then being stumped on why it does not work. Good to know though.
