### ISSUE TITLE
[Bug]: Debian 11/12 STEAMCMD apt requirements

### ISSUE THREAD

**Issue by WhatsCS** [GameServerManagers/LinuxGSM#4269]
### User story

When attempting to run through the install process on the two most recent Debian releases, I encountered a dep issue with steamcmd. 

### Game

Steam Based Games

### Linux distro

Debian 12, Debian 11

### Command

command: install

### Further information

For Debian 11 and 12, according to the [steamcmd wiki](https://developer.valvesoftware.com/wiki/SteamCMD#Package_From_Repositories), the following is required to be added to apt sources to allow for steamcmd to be pulled from official repositories.

This is based on Vultr installed VPS's, other providers may differ but Vultr does not add on anything additional outside of their own apprepo within the `sources.list.d/` 

A quick sed fix for this is as follows: `sed -i '/^[^#].*$/ s/$/ contrib non-free /g'`
This will blanket add `contrib non-free` to all uncommented deb sources within `/etc/apt/sources.list`

Please let me know if you wish to have further info and/or direct me to the relevant file(s) and I can look into submitting a pr.

### Steps to reproduce

1. install base debian 11 or 12
2. download linuxgsm.sh
3. run and attempt to install a steamcmd based game

**Comment by dgibbs64** [comment]
On Debian, steamcmd will be installed with apt if non-free repo is enabled. If it is not enabled LinuxGSM will install SteamCMD the "manual" way. This allows LinuxGSM to work both methods without issue. I decided to not force the non-free repo and leave it up to the server admin to enable if they choose.

**Comment by tristanwilson111** [comment]
@dgibbs64, FYI, attempted to install on latest version of Debian (12.4.0), steamcmd is not found and the install script does not proceed.

> root@debian:/home/pzserver# sudo ./pzserver install
> 
> Checking Project Zomboid Dependencies as root
> =================================
> Information! Checking any missing dependencies for Project Zomboid server only.
> Information! This will NOT install a Project Zomboid server.
> bc
> binutils
> bsdmainutils
> bzip2
> ca-certificates
> cpio
> curl
> distro-info
> file
> gzip
> hostname
> jq
> lib32gcc-s1
> lib32stdc++6
> libsdl2-2.0-0:i386
> netcat-openbsd
> openjdk-17-jre
> python3
> rng-tools5
> tar
> tmux
> unzip
> util-linux
> uuid-runtime
> wget
> xz-utils
> Warning! Missing dependencies: binutils bsdmainutils distro-info lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 netcat-openbsd openjdk-17-jre rng-tools5 steamcmd tmux uuid-runtime
> Information! root has sudo access.
> Information! Automatically installing missing dependencies.
> Hit:1 http://deb.debian.org/debian bookworm InRelease
> Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
> Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package steamcmd
> sudo dpkg --add-architecture i386; sudo apt update; sudo apt install binutils bsdmainutils distro-info lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 netcat-openbsd openjdk-17-jre rng-tools5 steamcmd tmux uuid-runtime
> Failure! Missing dependencies required to run SteamCMD.

Running the provided output provides the below error:

> root@debian:/home/pzserver# sudo dpkg --add-architecture i386; sudo apt update; sudo apt install binutils bsdmainutils distro-info lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0:i386 netcat-openbsd openjdk-17-jre rng-tools5 steamcmd tmux uuid-runtime
> Hit:1 http://deb.debian.org/debian bookworm InRelease
> Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
> Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> All packages are up to date.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package steamcmd

For context as described by @WhatsCS, doing the following adds the required repo:

```
cd /etc/apt
sed -i '/^[^#].*$/ s/$/ contrib non-free /g' sources.list
```
