### ISSUE TITLE
[Bug]: Core Keeper depdendency list is missing "xvfb"

### ISSUE THREAD

**Issue by QuantumToasted** [GameServerManagers/LinuxGSM#4273]
### User story

As a server hoster, it would be nice to not need to install a dependency for the game AFTER already installing dependencies.

### Game

Core Keeper

### Linux distro

Ubuntu 20.04

### Command

command: start

### Further information

The [official Core Keeper server install page](https://linuxgsm.com/servers/ckserver/) lists the following for the install dependencies on Ubuntu 20.04:
```
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install curl wget file tar bzip2 gzip unzip bsdmainutils python3 util-linux ca-certificates binutils bc jq tmux netcat lib32gcc1 lib32stdc++6 libsdl2-2.0-0:i386 steamcmd
```

However, when trying to start the server after installing, it complains about a missing `xvfb` dependency. Installing this fixes the issue, but it would be nice to have it automatically added to the pre-install dependencies list to automate this process.

### Relevant log output

```shell
ckserver@athena:~$ ./ckserver start
fetching GitHub command_start.sh...OK
fetching GitHub check_root.sh...OK
fetching GitHub check_system_dir.sh...OK
fetching GitHub check_executable.sh...OK
fetching GitHub check_logs.sh...OK
[ WARN ] Starting ckserver: Missing dependencies: xvfbsudo dpkg --add-architecture i386; sudo apt update; sudo apt install xvfb
fetching GitHub check_config.sh...OK
fetching GitHub check_status.sh...OK
fetching GitHub fix_steamcmd.sh...OK
[  OK  ] Starting ckserver: Applying steamclient.so sdk64 hardlink fix: Core Keeper
[  OK  ] Starting ckserver: Applying steamclient.so sdk32 link fix: Core Keeper
fetching GitHub core_logs.sh...OK
[ .... ] Starting ckserver: LinuxGSMno server running on /tmp/tmux-1001/ckserver
[ FAIL ] Starting ckserver: Unable to start LinuxGSM
```

### Steps to reproduce

1. Follow the instructions on https://linuxgsm.com/servers/ckserver/ verbatim

**Comment by dgibbs64** [comment]
added missing extra dependencies to the website. Thank you
