### ISSUE TITLE
[Adjustment?]: maybe adjust permissions checks to be more lenient?

### ISSUE THREAD

**Issue by ddan39** [GameServerManagers/LinuxGSM#4279]
### User story

a new unused file in lgsm/modules/ could cause lgsm to fail. i think it would be good to some how limit that check,

### Game

Project Zomboid

### Linux distro

Debian 12

### Command

command: start, command: stop, command: restart

### Further information

Permissions checks run on every file in lgsm/modules/ folder, in check_permissions.sh for example it runs `find "${modulesdir}" -type f -not -executable | wc -l`. Maybe that should be adjust to something like  `find "${modulesdir}" -type f -name '*.sh' -not -executable | wc -l`, or another option is to store a list of all lgsm sh files and check those specific files instead of all files in the modulesdir? I don't know, just spitballing here.

**Comment by dgibbs64** [comment]
I can see how this could be a problem. Is there a specific reason why a non-linuxgsm file would be in that directory?

**Comment by ddan39** [comment]
I had opened one of the sh files with vim, which automatically created a
.swp file and then when my server went to do the scheduled restart while I
had vim left open it errored and my server stopped but didn't start back up
(another issue I reported).

**Comment by dgibbs64** [comment]
I have made a minor change to exclude .swp file from the permissions check 1f50055f5ac0e0bed0ea01f82f82ef4dca3deec2
for now, I will add exceptions on a case-by-case basis.
