### ISSUE TITLE
[Bug]: Wurm server cfg not picked up

### ISSUE THREAD

**Issue by zackchadwick** [GameServerManagers/LinuxGSM#4283]
### User story

As a user, I want to customize the server settings for the launcher to use.

### Game

Wurm

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

Newest release isn't picking up the Wurm config. 

It looks like the wurmserver script is looking for the value of `${servercfgfullpath}` on line 463, however that is no longer defined in the file. The only instance it occurs is line 463.

As such, the launcher always reverts to the default configuration. Appears to be from commit ab09a32.

### Relevant log output

```shell
Command-line Parameters
============================================================================================================================================================================
./wurmserver: line 463: : No such file or directory
 ./WurmServerLauncher start=Creative adminpwd='ADMINPASSWORD' epicsettings='false' externalport='3724' homeserver='true' homekingdom='4' loginserver='true' maxplayers='200' queryport='27016' rmiport='7221' rmiregport='7220' servername='LinuxGSM' serverpassword='' ip='0.0.0.0'
```

### Steps to reproduce

1. Pull latest Wurm container, or install
2. View details, `./wurmserver details`, view error regarding line 463
3. Try to customize the server cfg
4. Start server, see that it resorts to defaults

**Comment by dgibbs64** [comment]
The wurm server config file is no longer used. I had to do a significant rework of wurm server to get things up and running again. Make sure you have the latest version of LinuxGSM and that servercfgfullpath is not referred to in any configs or parameters

**Comment by daniofordon** [comment]
Where do I find the server settings now? How does there be no config.cfg?
