### ISSUE TITLE
[Bug]: TS3 Server missing and faulty dependencys

### ISSUE THREAD

**Issue by DSDV** [GameServerManagers/LinuxGSM#4292]
### User story

I noticed that the TS3 install prompts for additional dependencys and has one which is not working.

### Game

TeamSpeak 3

### Linux distro

Ubuntu 22.04

### Command

command: install

### Further information

Hi, 
at first thank you so much for your scripts and the associated work!

So i noticed that as i followed https://linuxgsm.com/servers/ts3server/
the installation process noticed missing dependency (even tho i installed the once recommended in the Dependencies section), 
The script even offered a copy & past command to fix this issue (nice!).

but the command got an error because it could not find `libsdl2-2.0-0:i386`

The way i solved it was to delete the `:i386` behind the `libsdl2-2.0-0`
```sudo apt update; sudo apt install bsdmainutils bzip2 jq lib32gcc-s1 lib32stdc++6 libsdl2-2.0-0 netcat unzip```

that worked and i got not further errors.

### Relevant log output

```shell
sadly i missed to copy the output and after running the installer again i is lost (sorry)
```

### Steps to reproduce

get ubuntu server with 22.04
run `./ts3server install`
look for the warnings&errors

**Comment by dgibbs64** [comment]
Unable to reproduce `libsdl2-2.0-0:i386` is only required by SteamCMD which TS3 does not use. I have checked the csv files and confirmed `libsdl2-2.0-0:i386` is not required by TS3. I also ran the installer for TS3 to confirm there wasn't a bug. Are you sure you are running the lastest version of LinuxGSM?

**Comment by DSDV** [comment]
Hi, 
thank your for your time and reply.
That is very strange. 
i used 

```
wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh ts3server
./ts3server install
```
at i think the 23rd of august this year so i guess it is the latest? 

i was wondering why it found missing dependency anyways since your website states a command for all dependency but i can check if it installed steamcmd.

**Comment by DSDV** [comment]
![image](https://github.com/GameServerManagers/LinuxGSM/assets/5504857/eb707a24-59db-4579-8192-910cc27fa212)
it does not look like it o.o

**Comment by dgibbs64** [comment]
Bit of a mystery to me currently as I cant replicate 😕

**Comment by DSDV** [comment]
Very strange. 
Maybe i made a mistake somewhere? But copy and paste isn't usually that hard for me :D 

ill try to replicate it on a local VM this weekend and report back (:
