### ISSUE TITLE
[TF2Server] Monitor Query error - unable to receive

### ISSUE THREAD

**Issue by OrbitalHustler** [GameServerManagers/LinuxGSM#430]
My TF2 server will start and work, flawlessly, as I can connect to it. But I can't use ./tf2server monitor, as it will give me the following error:

[  OK  ] Monitor tf2-server: Checking session: OK
[ FAIL ] Monitor tf2-server: Querying port: /_myIp_/:27015 : ERROR: Unable to receive
[ FAIL ] Monitor tf2-server: Querying port: /_myIp_/:27015 : ERROR: Unable to receive

Here are some distro informations:

Arch Linux release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

And I have the following line in my netstat -ntulp

udp        0      0 /_myIp_/:27015    0.0.0.0:\*                           16502/./srcds_linux

I had to modify the line 59 of the file gsquery.py from

 connection.send( self.query_prompt_string )
to
 connection.send( self.query_prompt_string.encode() )

because I was getting the following error without that change:

[ FAIL ] Monitor tf2-server: Querying port: /_myIp_/:27015 : Traceback (most recent call last):
  File "/home/server/servers/tf2/gsquery.py", line 124, in <module>
    server.responding()
  File "/home/server/servers/tf2/gsquery.py", line 60, in responding
    connection.send( self.query_prompt_string )
TypeError: 'str' does not support the buffer interface

**Comment by dgibbs64** [comment]
to confirm you resolved your issue by changing

    connection.send( self.query_prompt_string )
to

    connection.send( self.query_prompt_string.encode() )

I havnt come across this problem before. Could it have somthign to do woth you running Arch?

**Comment by dgibbs64** [comment]
I belive this may be to do with the version of python being used. However I dont yet know enough to resolve this. I will close.
