### ISSUE TITLE
[Bug]: Console logfile empty

### ISSUE THREAD

**Issue by ervins0x** [GameServerManagers/LinuxGSM#4309]
### User story

I want so log files are being saved

### Game

Rust

### Linux distro

Debian 11

### Command

command: console

### Further information

Hello!
I have Debian 11 running LGSM with Rust server, tried this with clean install too.

At first thought this was some Ubuntu shenanigan, tried with Debian ,realised if my VM container has no memory and i have OOM crash, log permissions or something gets broken, couldn't debug this further, please assist.
When this happens `./rustserver console` i'm monitoring things but during crash it crashes and closes session and i'm unable to see what's going on so i'm going to check log folder and these logfiles are empty.

files are owned by rustserver:rustserver

Thanks.

### Steps to reproduce

* Spin up new LGSM + Rust instance;
* See that ~/logs/console are being writen - tail them, no problem, ls - see that it's growing, good...
* Make it so it crashes - it can be some faulty library (can happen with mods) or even OOM crash;
* During OOM crash there is no log file saved
* Restart server
* ~/logs/console we see that timestamps and log files are being rotated, but `ls -la` / tailing shows that they are empty.

**Comment by devsnowy** [comment]
Hi there,
I was looking around and I found this https://github.com/GameServerManagers/LinuxGSM/pull/2966/files , this directed me check parameters and it looks like default was -logfile with nothing after it, I'm not sure if this is supposed to be like this in _default but I've changed it to -logfile \"${consolelogdate}\"" and now everything seem to be working, I'm not sure if it should be to rust-console.log instead? Please advise and if possible please fix this problem, I've noticed it also on my fresh docker image install.

**Comment by andreistanculescueroad** [comment]
Actually it looks like `consolelog` worsk to fix this issue not `consolelogdate` to keep the log rotation working.

**Comment by devsnowy** [comment]
Actually it looks like the variable consolelog works to fix this issue, not consolelogdate. This will keep the log rotation working.

**Comment by ervins0x** [comment]
> Actually it looks like the variable `consolelog` works to fix this issue, not `consolelogdate`. This will keep the log rotation working.

Good spot, i tried to pass `-logfile ~/log/console/rust-console.log` but then it couldn't start, let's try with consolelog.

**Comment by devsnowy** [comment]
> > Actually it looks like the variable `consolelog` works to fix this issue, not `consolelogdate`. This will keep the log rotation working.
> 
> Good spot, i tried to pass `-logfile ~/log/console/rust-console.log` but then it couldn't start, let's try with consolelog.
> 
> Update: Tried with `-logfile ${consolelog}` and also tried to escape with quotes `\"${consolelog}\"`, same unable to start even server with this argument, it stops `Initializing Shutdown Handler` I can start the server with pure `-logfile` but the log files are empty.
> 
> Update2: <-- scratch that... Manged to run server with : ` -logfile \"${gamelogdate}\""` and logging also works.
> 
> ```
> Set current directory to /home/rustserver/serverfiles
> Found path: /home/rustserver/serverfiles/RustDedicated
> Shutdown handler: initalize
> ```
> 
> still crashing, i didn't saved file lol.

Try like this:
It should end with "" and starts at -logfile, or you can replace from "password" of recon.password.
`password \"${rconpassword}\" -logfile \"${consolelog}\""`

This has to be in /data/config-lgsm/rustserver/rustserver.cfg (instance) NOT _default.

**Comment by ervins0x** [comment]
Thanks, yeah i did it like that, i'm running natively without Docker, but in the LGSM config itself variable $consolelog is set, so it should work both ways.
Just to doublecheck will share my details here, config of:
`config-lgsm/rustserver/rustserver.cfg`:
```
startparameters="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.queryport ${queryport} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.gamemode ${gamemode} +server.level \"${serverlevel}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"
```
Let's append - ` \"${consolelog}\"` 
result - ` -logfile  \"${consolelog}\""` - just putting emphasis on that i'm not missing double quotes 💇 


Let's do server restart, and it's stuck in this:
```
Set current directory to /home/rustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated
Shutdown handler: initalize.
```

And when i remove variable that we added to -logfile it immediately boots up.

I can see during `./rustserver debug`

```
Start parameters:
 ./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.queryport 28017 +server.tickrate 30 +server.hostname "xxx" +server.identity "rustserver" +server.gamemode vanilla +server.level "Procedural Map" +server.seed 12345678 +server.salt 0 +server.maxplayers 70 +server.worldsize 4200 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xxxxx" -logfile "/home/rustserver/log/console/rustserver-console.log"
```
Weird behaviour, it's not booting, then i removed this var, restart again, now it's writing to log files, i don't get it.

**Comment by andreistanculescueroad** [comment]
> Thanks, yeah i did it like that, i'm running natively without Docker, but in the LGSM config itself variable $consolelog is set, so it should work both ways. Just to doublecheck will share my details here, config of: `config-lgsm/rustserver/rustserver.cfg`:
> 
> ```
> startparameters="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.queryport ${queryport} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.gamemode ${gamemode} +server.level \"${serverlevel}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"
> ```
> 
> Let's append - ` \"${consolelog}\"` result - ` -logfile \"${consolelog}\""` - just putting emphasis on that i'm not missing double quotes 💇
> 
> Let's do server restart, and it's stuck in this:
> 
> ```
> Set current directory to /home/rustserver/serverfiles
> Found path: /home/rustserver/serverfiles/RustDedicated
> Shutdown handler: initalize.
> ```
> 
> And when i remove variable that we added to -logfile it immediately boots up.
> 
> I can see during `./rustserver debug`
> 
> ```
> Start parameters:
>  ./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.queryport 28017 +server.tickrate 30 +server.hostname "xxx" +server.identity "rustserver" +server.gamemode vanilla +server.level "Procedural Map" +server.seed 12345678 +server.salt 0 +server.maxplayers 70 +server.worldsize 4200 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xxxxx" -logfile "/home/rustserver/log/console/rustserver-console.log"
> ```
> 
> Weird behaviour, it's not booting, then i removed this var, restart again, now it's writing to log files, i don't get it.
Does this folder exists for you? `/home/rustserver/log/console/`

**Comment by devsnowy** [comment]
> Thanks, yeah i did it like that, i'm running natively without Docker, but in the LGSM config itself variable $consolelog is set, so it should work both ways. Just to doublecheck will share my details here, config of: `config-lgsm/rustserver/rustserver.cfg`:
> 
> ```
> startparameters="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.queryport ${queryport} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.gamemode ${gamemode} +server.level \"${serverlevel}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"
> ```
> 
> Let's append - ` \"${consolelog}\"` result - ` -logfile \"${consolelog}\""` - just putting emphasis on that i'm not missing double quotes 💇
> 
> Let's do server restart, and it's stuck in this:
> 
> ```
> Set current directory to /home/rustserver/serverfiles
> Found path: /home/rustserver/serverfiles/RustDedicated
> Shutdown handler: initalize.
> ```
> 
> And when i remove variable that we added to -logfile it immediately boots up.
> 
> I can see during `./rustserver debug`
> 
> ```
> Start parameters:
>  ./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.queryport 28017 +server.tickrate 30 +server.hostname "xxx" +server.identity "rustserver" +server.gamemode vanilla +server.level "Procedural Map" +server.seed 12345678 +server.salt 0 +server.maxplayers 70 +server.worldsize 4200 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xxxxx" -logfile "/home/rustserver/log/console/rustserver-console.log"
> ```
> 
> Weird behaviour, it's not booting, then i removed this var, restart again, now it's writing to log files, i don't get it.

Does this folder exists for you?
`/home/rustserver/log/console/`

**Comment by devsnowy** [comment]
> > Thanks, yeah i did it like that, i'm running natively without Docker, but in the LGSM config itself variable $consolelog is set, so it should work both ways. Just to doublecheck will share my details here, config of: `config-lgsm/rustserver/rustserver.cfg`:
> > ```
> > startparameters="-batchmode +app.listenip ${ip} +app.port ${appport} +server.ip ${ip} +server.port ${port} +server.queryport ${queryport} +server.tickrate ${tickrate} +server.hostname \"${servername}\" +server.identity \"${selfname}\" +server.gamemode ${gamemode} +server.level \"${serverlevel}\" +server.seed ${seed} +server.salt ${salt} +server.maxplayers ${maxplayers} +server.worldsize ${worldsize} +server.saveinterval ${saveinterval} +rcon.web ${rconweb} +rcon.ip ${ip} +rcon.port ${rconport} +rcon.password \"${rconpassword}\" -logfile"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let's append - ` \"${consolelog}\"` result - ` -logfile \"${consolelog}\""` - just putting emphasis on that i'm not missing double quotes 💇
> > Let's do server restart, and it's stuck in this:
> > ```
> > Set current directory to /home/rustserver/serverfiles
> > Found path: /home/rustserver/serverfiles/RustDedicated
> > Shutdown handler: initalize.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And when i remove variable that we added to -logfile it immediately boots up.
> > I can see during `./rustserver debug`
> > ```
> > Start parameters:
> >  ./RustDedicated -batchmode +app.listenip 0.0.0.0 +app.port 28082 +server.ip 0.0.0.0 +server.port 28015 +server.queryport 28017 +server.tickrate 30 +server.hostname "xxx" +server.identity "rustserver" +server.gamemode vanilla +server.level "Procedural Map" +server.seed 12345678 +server.salt 0 +server.maxplayers 70 +server.worldsize 4200 +server.saveinterval 300 +rcon.web 1 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "xxxxx" -logfile "/home/rustserver/log/console/rustserver-console.log"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Weird behaviour, it's not booting, then i removed this var, restart again, now it's writing to log files, i don't get it.
> 
> Does this folder exists for you? `/home/rustserver/log/console/`
Reach out to me on discord "devsnowy" username, and we can try debug it.

**Comment by ervins0x** [comment]
> Reach out to me on discord "devsnowy" username, and we can try debug it.
Thanks.
Of course it exists, as i wouldn't have known that the file is empty :trollface: 

Anyways, now the rust-console.log is getting filled up and i don't know what happened.

```
rustserver@rustbaltic:~/log$ tree -h
.
|-- [4.0K]  console
|   |-- [   0]  rustserver-console-2023-09-11-05:50:02.log
|   |-- [   0]  rustserver-console-2023-09-11-08:31:58.log
|   |-- [8.6K]  rustserver-console-2023-09-11-08:35:01.log
|   `-- [210K]  rustserver-console.log
|-- [4.0K]  script
|   |-- [5.0K]  rustserver-alert.log
|   |-- [3.2K]  rustserver-postdetails.log
|   |-- [ 21K]  rustserver-script-2023-09-06-13:46:13.log
|   |-- [ 781]  rustserver-script-2023-09-06-14:09:18.log
|   |-- [1.7K]  rustserver-script-2023-09-06-14:49:22.log
|   |-- [ 14K]  rustserver-script-2023-09-07-04:09:15.log
|   |-- [4.9K]  rustserver-script-2023-09-07-04:20:01.log
|   |-- [167K]  rustserver-script-2023-09-07-14:00:02.log
|   |-- [ 28K]  rustserver-script-2023-09-07-14:35:02.log
|   |-- [ 552]  rustserver-script-2023-09-07-14:35:20.log
|   |-- [8.2K]  rustserver-script-2023-09-07-15:05:02.log
|   |-- [8.5K]  rustserver-script-2023-09-07-15:35:03.log
|   |-- [8.5K]  rustserver-script-2023-09-07-16:05:01.log
|   |-- [5.9K]  rustserver-script-2023-09-07-16:35:01.log
|   |-- [185K]  rustserver-script-2023-09-08-10:35:01.log
|   |-- [4.6K]  rustserver-script-2023-09-08-11:00:01.log
|   |-- [7.6K]  rustserver-script-2023-09-08-11:30:01.log
|   |-- [8.8K]  rustserver-script-2023-09-08-12:00:03.log
|   |-- [7.9K]  rustserver-script-2023-09-08-12:30:02.log
|   |-- [239K]  rustserver-script-2023-09-09-11:00:02.log
|   |-- [3.6K]  rustserver-script-2023-09-09-11:30:29.log
|   |-- [ 139]  rustserver-script-2023-09-10-07:25:02.log
|   |-- [187K]  rustserver-script-2023-09-10-07:25:04.log
|   |-- [ 10K]  rustserver-script-2023-09-10-07:30:50.log
|   |-- [1.9K]  rustserver-script-2023-09-10-07:35:01.log
|   |-- [1.8K]  rustserver-script-2023-09-10-07:40:03.log
|   |-- [2.7K]  rustserver-script-2023-09-10-07:50:23.log
|   |-- [ 703]  rustserver-script-2023-09-10-07:51:02.log
|   |-- [7.2K]  rustserver-script-2023-09-10-07:54:43.log
|   |-- [185K]  rustserver-script-2023-09-11-04:11:07.log
|   |-- [2.3K]  rustserver-script-2023-09-11-04:35:11.log
|   |-- [ 747]  rustserver-script-2023-09-11-04:36:34.log
|   |-- [ 747]  rustserver-script-2023-09-11-04:37:58.log
|   |-- [1.2K]  rustserver-script-2023-09-11-04:40:01.log
|   |-- [1.4K]  rustserver-script-2023-09-11-04:44:24.log
|   |-- [1.5K]  rustserver-script-2023-09-11-04:45:01.log
|   |-- [ 950]  rustserver-script-2023-09-11-04:48:10.log
|   |-- [ 877]  rustserver-script-2023-09-11-04:49:34.log
|   |-- [1.8K]  rustserver-script-2023-09-11-04:50:22.log
|   |-- [ 899]  rustserver-script-2023-09-11-04:54:20.log
|   |-- [6.6K]  rustserver-script-2023-09-11-05:18:49.log
|   |-- [1.7K]  rustserver-script-2023-09-11-05:20:40.log
|   |-- [8.9K]  rustserver-script-2023-09-11-05:50:02.log
|   |-- [ 26K]  rustserver-script-2023-09-11-08:31:58.log
|   |-- [2.1K]  rustserver-script-2023-09-11-08:35:01.log
|   |-- [165K]  rustserver-script.log
|   `-- [6.1K]  rustserver-steamcmd.log
`-- [4.0K]  server
    `-- [ 945]  rustserver-game-2023-09-11-05:18:49.log
```

**Comment by ervins0x** [comment]
Update:
passed `-logfile $consoledir` and Shutdown intitialize is just output from screen/tmux session, i can now check logs at least in it's location.
