### ISSUE TITLE
[Bug]: Cannot List Server TMUX Session

### ISSUE THREAD

**Issue by TheBambino** [GameServerManagers/LinuxGSM#4314]
### User story

Ability to list & access server TMUX session

### Game

Project Zomboid

### Linux distro

Ubuntu 20.04

### Command

command: console

### Further information

Cannot List Server TMUX Session using `tmux list-sessions`

I can use all the LGSM commands just fine including the console command.

I use bash scripts to push commands to the server via TMUX. The sessions have normally listed in the past ~4 years that we have been using it.

We had a test server running on an older version of LGSM that listed sessions fine. After updating, it also has the same issue.

Another user on Discord was able to replicate this issue using Vallheim & Rust servers:
https://discord.com/channels/127498813903601664/1152015986149572688

### Steps to reproduce

1. Update to latest version
2. Use the `tmux list-sessions` command

**Comment by TheBambino** [comment]
This is most likely related to this: #4296

**Comment by dgibbs64** [comment]
The tmux session of the game servers now has unique names to ensure servers with multiple instances don't conflict. You will need to check the unique name of each instance. This is stored in data directory so stays the same once initially set
