### ISSUE TITLE
[Bug]: Command_Monitor.sh not working properly as Cron Job

### ISSUE THREAD

**Issue by Royel-Payne** [GameServerManagers/LinuxGSM#4316]
### User story

Command_Monitor not working properly as Cron Job after latest update

### Game

Rust

### Linux distro

Ubuntu 22.04, Ubuntu 20.04

### Command

command: monitor

### Further information

LGSM Monitor is no longer restarting game server after an update-lgsm was done on 9-17-23. This was working properly before a scheduled task to update-lgsm was done. (0 0 * * 0 /home/rustserver/rustserver update-lgsm > /dev/null 2>&1)

This is being run as a cron job.  (*/5 * * * * /home/rustserver/rustserver monitor > /dev/null 2>&1)

When ran from CLI (./rustserver monitor) this functions as expected but when running as a Cron job this fails.

Log files are included 

### Relevant log output

```shell
Sep 22 17:40:03.430 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 17:40:04.437 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 17:40:04.447 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 17:40:04.449 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 17:45:03.154 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 17:45:04.161 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 17:45:04.172 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 17:45:04.175 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 17:50:02.892 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 17:50:03.899 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 17:50:03.912 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 17:50:03.915 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 17:55:03.625 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 17:55:04.633 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 17:55:04.644 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 17:55:04.646 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 18:00:03.377 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 18:00:04.385 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 18:00:04.396 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 18:00:04.399 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 18:05:03.102 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 18:05:04.109 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 18:05:04.120 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 18:05:04.123 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
Sep 22 18:10:02.873 rustserver: MONITOR: INFO: Checking installer: CHECKING
Sep 22 18:10:03.881 rustserver: MONITOR: PASS: Checking installer: LinuxGSM is installing
Sep 22 18:10:03.897 rustserver: MONITOR: INFO: LinuxGSM version: v23.5.2
Sep 22 18:10:03.900 rustserver: MONITOR: PASS: core_exit.sh exiting with code: 0
```

### Steps to reproduce

1. Run command_monitor.sh as Cron job 
2. Stop/Restart server from Rcon
3. Wait for Cron job to run, server should be restarted but does not succeed
4. View log files

**Comment by jonathan-robertson** [comment]
This is also happening to me; also using Ubuntu; hearing the version of Ubuntu does not seem to matter

**Comment by dgibbs64** [comment]
Thanks for the info. I am reviewing a couple of bugs relating to monitor. I will try and replicate this as well

**Comment by Royel-Payne** [comment]
Thanks! 

Let me know if you need anything else, I'll be glad to provide more info if you need.

**Comment by TheBambino** [comment]
I am also having this issue.

**Comment by aStonedPenguin** [comment]
Same problem with Debian 12

**Comment by dgibbs64** [comment]
So this is a fun bug to identify. It appears to only happen with cron or watch. Bash appears to just stop running. I will continue doing tests until I find the issue. A hotfix will go out once fixed

**Comment by Royel-Payne** [comment]
Well I'm glad to hear it's fun! :)

Thanks for your time, I'm sure we will greatly appreciate the hard work you put into this project. 

Good luck finding the solution. I'll keep my eye out for any updates.

**Comment by dgibbs64** [comment]
Found the issue. cron uses a different environment to the default bash one (sh) and it is missing the $USER variable. So I added code to set the $USER variable if missing. Hopfully that should now fix the issue. Please update linuxgsm and let me know :)

**Comment by Royel-Payne** [comment]
Thanks man, I'll update and let you know the results shortly.

**Comment by Royel-Payne** [comment]
Tested and it looks to be working.

Thanks so much for getting this resolved.
