### ISSUE TITLE
[Server Request]: Counter Strike 2

### ISSUE THREAD

**Issue by csgentr** [GameServerManagers/LinuxGSM#4322]
### Game server

counter-strike 2 will release for download ?

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

730

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borzaka** [comment]
In the [latest update](https://www.counter-strike.net/news/updates), they finally mentioned some useful info regarding community servers:

> [ COMMUNITY DEDICATED SERVERS ]
> - To launch a community dedicated server, you can use this reference command line:
>   cs2 -dedicated +map de_dust2
> - To enable logging, add to your server commandline:
>   +sv_logfile 1 -serverlogging
> - Or add to a config file:
>   sv_logfile 1
>   log on
> - To enable HTTP logaddress forwarding, ensure logging is enabled as above and use:
>   logaddress_add_http "<server address>:<port>"
> - Dispatched logs can be handled the same way as CS:GO

They stated, that there will be no community servers at launch:
https://steamcommunity.com/faqs/steam-help/view/5ED2-ED8E-81F4-0C18#commserver

> Can I run or play on community servers in Counter-Strike 2?
> Not at launch, but Community server support is coming soon.

> Can I run or play on workshop maps in the Counter-Strike 2 Limited Test?
> Not at launch, but Workshop map support is coming soon.

CS:GO is still working, but have to use the `csgo_demo_viewer` branch.

**Comment by dgibbs64** [comment]
CS2 servers are still not showing properly on the server browser and the Server Browser button in CS2 doesn't yet work. Secondly, they require the use of the game client which means a Steam Login is required. Currently I am waiting for things to settle down and before a little more stable before adding to CS2. Hopfully that wont be too long

**Comment by csgentr** [comment]
https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers

**Comment by OllieCrook** [comment]
There was a silent update last night that seems to have reintroduced GSLTs for community servers and fixed the server browser.

See: https://www.reddit.com/r/GlobalOffensive/comments/17h9eqt/counterstrike_2_update_for_10262023/

**Comment by OllieCrook** [comment]
Yeah, it's halfway there! They do say on the Valve wiki:

> Note: Be aware that the dedicated server is part of the full game, so you will download the full CS2 game for now (est. 33gb + workshop files if any). As there is currently no solution to download the dedicated server application but it exists.

But then they follow it up by saying:

>Note:  If you wanna give it a try it seems the following steam Depot id for the dedicated server which is 2347773

The [depot](https://steamdb.info/depot/2347773/) does contain all of the files I can see that it uses when you download the entirety of app id `730`.

So you can either get it working now with `730` and accept the full client download or you wait a bit longer. Honestly not sure what the best course is here.

**Comment by borzaka** [comment]
Manual way of running (multi instance) CS2 dedicated server based on the [official wiki](https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers).

After the game is installed;
- To update the game:
`./Steam/steamcmd.sh +force_install_dir "/home/cs2server/cs2-ds" +login "xxx" "yyy" +app_update "730" +quit`
I always run this before starting the game server. If you are using Steam Guard, you have include the Steam guard code after your password.
- Starting the first game server instance:
`./cs2-ds/game/bin/linuxsteamrt64/cs2 -dedicated -ip 0.0.0.0 -port 27015 +tv_port 27020 +servercfgfile server-1.cfg -maxplayers 12 +map de_dust2`
- Starting the second game server instance:
`./cs2-ds/game/bin/linuxsteamrt64/cs2 -dedicated -ip 0.0.0.0 -port 27016 +tv_port 27021 +servercfgfile server-2.cfg -maxplayers 12 +map de_dust2`

In the  `server-[x].cfg` file I configure settings which should be different (and the same as well) on the servers:
- `hostname`
- `rcon_password`
- CSTV ports
- etc.

**Comment by OllieCrook** [comment]
You can now `login anonymous` with steamcmd instead of having to have a second steam account with no steam guard.

**Comment by dgibbs64** [comment]
Nice. If someone can get a pr for that I will get a hotfix out. I'm unwell currently
