### ISSUE TITLE
[Feature]: Deprecate CentOS 7 Support

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#4327]
### User story

As a developer, I want to remove support for CentOS 7 that goes EOL June 2024

### Linux distro

RedHat 7

### Command

command: install

### Further information

Centos 7 foes EOL June 2024. It is already more difficult to support and test against. I plan to remove all support soon.

**Comment by h3o66** [comment]
I would propose to first put out a warning message and next year remove the support for it.
Maybe as well put up the same warning with rhel 7
