### ISSUE TITLE
[Feature]: Valheim Modifiers 

### ISSUE THREAD

**Issue by optimuslem** [GameServerManagers/LinuxGSM#4328]
### User story

I want modifiers in the setup

### Linux distro

Ubuntu 20.04

### Command

command: update-lgsm

### Further information

-preset hard Sets world modifier preset. Setting a preset will
overwrite any other previous modifiers. Valid
values are: Normal, Casual, Easy, Hard,
Hardcore, Immersive, Hammer.
[Valheim Dedicated Server Manual.pdf](https://github.com/GameServerManagers/LinuxGSM/files/12824996/Valheim.Dedicated.Server.Manual.pdf)

-modifier raids none Sets chosen world modifier with value. If
combined with a preset should be set after. Valid
modifiers and values are:
Combat: veryeasy, easy, hard, veryhard
DeathPenalty: casual, veryeasy, easy, hard,
hardcore
Resources: muchless, less, more, muchmore,
most
Raids: none, muchless, less, more, muchmore
Portals: casual, hard, veryhard
-setkey nomap Sets a world modifier checkbox key. Valid values
are: nobuildcost, playerevents, passivemobs,
nomap

**Comment by natrius** [comment]
For some reason this does not work. I added this to my `lgsm/config-lgsm/vhserver/vhserver-3.cfg` file like an additional line containing `setkey="playerevents"`. Using `startparameters=-setkey playerevents` (as on https://docs.linuxgsm.com/configuration/start-parameters ) deletes every other parameter set before. 

Did i miss something here?

**Comment by rainst** [comment]
Don’t use startparameters but worldmodifiers as described in the comment here: https://github.com/GameServerManagers/LinuxGSM/blob/e888821af0badcae168deabb88f071526c3c72e0/lgsm/config-default/config-lgsm/vhserver/_default.cfg
