### ISSUE TITLE
[LGSM] Detect if missing dependencies and warn

### ISSUE THREAD

**Issue by DSDV** [GameServerManagers/LinuxGSM#433]
Hi,
i installe dGMod server today all worked fine i allowed ports and tried to join buit seteam dont sees the server.

after an hour i tried starting it via srcds_run and it puts out an error:
"error while loading shared libraries: libstdc++.so"
wich google says is fixed by:
"sudo apt-get install lib32stdc++6"

and all worked great again :D

so maybe the GSM should check the srcds if it puts out errors before saying all works [ok]
and while installing gmod check sudo apt-get install lib32stdc++6 ?

with best +DS_DV+

**Comment by dgibbs64** [comment]
The dependencies are listed in the instructions and the wiki.

http://gameservermanagers.com/lgsm/gmodserver/
https://github.com/dgibbs64/linuxgsm/wiki/Dependencies

There is also ./gmodserver debug that would of identified the issue.

There is also a hidden option that I have recently been working on.

./gmodserver depsdetect

that does something similar what you are suggesting. Once I am happy I will probably write it in to the script to warn admins of missing dependencies.

**Comment by dgibbs64** [comment]
I am developing this currently. My code works for Ubuntu however needs polish. 

Currently is warns of a missing dependency. If the user has sudo it will install it for you.

There are some dependencies that are optional so I will need to deal with them differently.

**Comment by UltimateByte** [comment]
Speaking of that, most debian users don't have "sudo", as i recently learned the default behaviour is : If you have a root password set, sudo is disabled.
So maybe packages installation instructions should be modified accordingly.

**Comment by DSDV** [comment]
I have ubuntu server running with sudo just fine :)
btw root should be disabled anyway ther is no need if you have an account wich hase rights to use sudo ;)

**Comment by jaredballou** [comment]
The way I added it on my branch was to have a package_check_$OS_$ARCH variable that is a simple space-delimited string of package names. Checks the package database to see if they are installed, and reports back. I'm looking at adding per-game (or per-engine) additional prereqs, but it'll at least give a message with the command to paste to install the missing deps.

**Comment by dgibbs64** [comment]
Just released the feature to master. Please test and let me know. Works with Ubuntu Debian and CentOS. If yum or apt-get are not present then the check will be skipped.

**Comment by ScottSmudger** [comment]
Hey, just had a problem with this.

User I run csgo as does not have sudo access, but the dependencies are installed and the script is giving me the command for debian and not redhat/centos.

Problem:
http://scottsmudger.co.uk/16-02-16_23-38-30.png

Dependencies:
http://scottsmudger.co.uk/16-02-16_23-42-47.png

**Comment by dgibbs64** [comment]
It checks if apt-get or yum is installed. For some reason it thinks apt-get is installed on your centos server. Can you confirm if apt-get is installed please

**Comment by dgibbs64** [comment]
Correction if dpkg-query is present then the script assumes Ubuntu or Debian. I may have to add if yim not present as well

**Comment by ScottSmudger** [comment]
I can confirm it is not installed, as YUM would not be available. It isn't installed as a package anyway

`sudo yum list installed | grep apt`
Didn't return anything

**Comment by dgibbs64** [comment]
What is the output of:

    command -v dpkg-query

**Comment by ScottSmudger** [comment]
`/usr/bin/dpkg-query`

**Comment by dgibbs64** [comment]
Please do the same but for apt-get as this should not be installed

**Comment by UltimateByte** [comment]
@dgibbs64 While you're in there, check that out for mail server management !
https://github.com/dgibbs64/linuxgsm/commit/64686921ddc3239acb4eb992fb3c22dd03ee1fc0#diff-0d55734e68e0cd33f8b206a5f6d70686

**Comment by ScottSmudger** [comment]
`command -v apt-get`

Doesn't return anything

**Comment by dgibbs64** [comment]
I am closing this issue as I believe this feature is now stable. However please advise if there are still issues
