### ISSUE TITLE
[Bug]: bf1942 missing dependency libncurses5:i386 v2

### ISSUE THREAD

**Issue by o4ier** [GameServerManagers/LinuxGSM#4333]
### User story

As a user I want that the server starts without a missing library error.

### Game

Battlefield 1942

### Linux distro

RedHat 9

### Command

command: start

### Further information

OS is AlmaLinux9 x64, which is a clone of RHEL9.
Needed package would be ncurses-compat-libs:i686, which is not available
The x86_64-Version of ncurses-compat-libs does not help, as a Symlink created by myself from /usr/lib/libncurses.so.5 to /usr/lib64/libncurses.so.5 creates a ```wrong ELF class: ELFCLASS64``` error in the output

So bf1942 is broken on EL9, I haven't found a source for libncurses5:i686 yet.

Maybe you can help?

(if this sounds familiar to you: contents are slightly copied from #3097 )

### Relevant log output

```shell
./start.sh: using statically linked binary
./bf1942_lnxded: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```

### Steps to reproduce

1. install bt1942 server
2. try to start the server

**Comment by dgibbs64** [comment]
https://access.redhat.com/solutions/6907421 looks like its available in epel

**Comment by dgibbs64** [comment]
Another suggestion for this is to run the LinuxGSM docker container

**Comment by dgibbs64** [comment]
Closing as solution is to enable EPEL
