### ISSUE TITLE
[Server Request]:  The Front

### ISSUE THREAD

**Issue by scarecr0w12** [GameServerManagers/LinuxGSM#4335]
### Game server

The Front

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

2334200

### Guides

Isn't really a good guide at the moment that i've found that utilizes the Linux Dedi files.I was able to manually run it by doing:

1. Normal Steamcmd app_update install using steamlogin, command similar to:
`steamcmd +force_install_dir /home/<usr>/thefront/ +login <user> <pass>  +app_update 2334200 +quit`
2. Once its installed, I haven't found how to configure the server through ini, but you can take the ini created from the Client file's dedicated server files that it can generate, and turn those into args for the run. Mine looks similar to:
`/path/to/the/install/ProjectWar/Binaries/Linux/TheFrontServer ProjectWar ProjectWar_Start?Listen?MaxPlayers=8 -server -game -QueueThreshold=8 -ServerName="SERVER NAME" -ServerAdminAccounts=<STeamID> -log log=log.log -locallogtimes -EnableParallelCharacterMovementTickFunction -EnableParallelCharacterTickFunction -UseDynamicPhysicsScene -OutIPAddress=51.81.221.71 -ServerID=6969358 -port=5001 -BeaconPort=5002 -QueryPort=5003 -Game.PhysicsVehicle=false -ansimalloc -Game.MaxFrameRate=35 -ShutDownServicePort=5004 -NOSTEAM'

that'll run it off ports 5001, 5002, 5003

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scarecr0w12** [comment]
I believe these are potential commandline args that can be added, based on the games Dedi server config editor it has built in game for non-headless.

```
ServerName=
ServerPassword=
QueueThreshold=40
ServerFightModeType=1
IsCanSelfDamage=0
IsCanFriendDamage=0
ClearSeverTime=2023-10-11
UseSteamSocket=1
Port=5001
BeaconPort=5002
ShutDownServicePort=5003
SaveWorldInterval=300
GMOverlapRatio=1
IsUnLockAllTalentAndRecipe=0
GMBagInitGirdNum=40
GreenHand=1
CharacterInitItem=
GMDeathDropMode=1
GMDeathInventoryLifeSpan=1800
CorpsePickAuthority=2
GMCanDropItem=1
GMCanDiscardItem=1
GMDiscardBoxLifeSpan=300
GMRebirthBaseCD=10
GMRebirthExtraCD=1
GMPenaltiesMaxNum=5
GMPenaltiesCD=600
ConstructEnableRot=1
GMAttackCityCdRatio=1
OpenAllHouseFlag=0
IsCanChat=1
IsShowBlood=1
SensitiveWords=1
HealthDyingState=1
UseACE=1
ServerAdminAccounts=
IsShowGmTitle=0
PlayerHotDefAddRate=1
PlayerIceDefAddRate=1
HeadNameDisplayDist_Team=200
HeadNameDisplayDist_Enemy=20
PlayerDeathAvatarItemDurableRate=0
PlayerDeatShortcutItemDurableRate=0
GMCraftTimeRate=1
PlayerAddExpRate=1
PlayerKillAddExpRate=1
PlayerFarmAddExpRate=1
PlayerCraftAddExpRate=1
MoveSpeedRate=1
JumpRate=1
PlayerLandedDamageRate=1
PlayerMaxHealthRate=1
HealthRecoverRate=1
PlayerMaxStaminaRate=1
StaminaRecoverRate=1
PlayerStaminaCostRate=1
PlayerMaxHungerRate=1
GMHungerDecRatio=1
GMBodyHungerAddRate=1
MaxBodyWaterRate=1
GMWaterDecRatio=1
GMBodyWaterAddRate=1
MaxBreathRate=1
BreathRecoverRate=1
PlayerBreathCostRate=1
GMPlayerHealthRate=1
GMFoodDragDurationRate=1
NpcRespawnRatio=1
AnimalBodyStayTime=300
HumanBodyStayTime=10
GMNPCLootableItemRatio=1
NpcSpawnLevelRatio=1
WildNPCDamageRate=1
WildNPCHealthRate=1
WildNPCSpeedRate=1
CityNPCLevelRate=1
CityNPCDamageRate=1
CityNPCHealthRate=1
CityNPCSpeedRate=1
CityNPCNumRate=1
NpcDisplayDistance=50
GMInventoryGainRate=1
GMCityATKNPCLootItemRatio=1
GMMaxHouseFlagNumber=1
GMSetGJConstructMaxNumRatio=1
GMHFTrapMaxNum=0
GMHFTurretMaxNum=0
GMConstructDefenseRatio=1
GMTrapDefenseRatio=1
GMTurretDefenseRatio=1
GMTrapDamageRatio=1
GMTurretDamageRatio=1
GMConstructMaxHealthRatio=1
GMConstructReturnHPRatio=1
GMHouseFlagRepairHealthRatio=1
GMTTC_Oil_Rate=1
GMWaterCollecter_Rate=1
GMTTC_Ore_Rate=1
GMTTC_Fish_Rate=1
CHFDamagedByPlayer=1
CHFDamagedByVehicle=1
CHFDamagedByNpc=1
GMHouseFlagExcitantTime=3
GMMaxRetrieveProductsRate=1
GMTreeGainRate=1
GMBushGainRate=1
GMOreGainRate=1
GMCropVegetableReapRatio=1
GMFleshGainRate=1
GMCropVegetableGrowRatio=1
GMMeleeNpcDamageRatio=1
GMRangedNpcDamageRatio=1
GMMeleePlayerDamageRatio=1
GMRangedPlayerDamageRatio=1
GMMeleeConstructDamageRatio=1
GMRangedConstructDamageRatio=1
GMToolDamageRate=1
GMDurabilityCostRatio=1
GMVehiclePlayerDamageRatio=1
GMVehicleConstructDamageRatio=1
GMVehicleDamageRate=1
```

**Comment by gOOvER** [comment]
`steamcmd +force_install_dir /home/<usr>/thefront/ +login <user> <pass>  +app_update 2334200 +quit`

This dont work atm, because appID 2334200 only download 73mb. A big workaround is needed ;)

**Comment by scarecr0w12** [comment]
> `steamcmd +force_install_dir /home/<usr>/thefront/ +login <user> <pass> +app_update 2334200 +quit`
> 
> This dont work atm, because appID 2334200 only download 73mb. A big workaround is needed ;)

Yes, because its marked as windows in the depot, LGSM has a work around for things like this.

**Comment by gOOvER** [comment]
> > `steamcmd +force_install_dir /home/<usr>/thefront/ +login <user> <pass> +app_update 2334200 +quit`
> > This dont work atm, because appID 2334200 only download 73mb. A big workaround is needed ;)
> 
> Yes, because its marked as windows in the depot, LGSM has a work around for things like this.

No ;)

**Comment by scarecr0w12** [comment]
![image](https://github.com/GameServerManagers/LinuxGSM/assets/10427387/9a6c4d05-127d-418a-a5cb-a79ebcb21235)



> > > `steamcmd +force_install_dir /home/<usr>/thefront/ +login <user> <pass> +app_update 2334200 +quit`
> > > This dont work atm, because appID 2334200 only download 73mb. A big workaround is needed ;)
> > 
> > 
> > Yes, because its marked as windows in the depot, LGSM has a work around for things like this.
> 
> No ;)

except they do

**Comment by gOOvER** [comment]
> 2334200

nothing marked as Windows:

https://steamdb.info/app/2334200/

**Comment by pharrisee** [comment]
The depot 2334201 is marked as Windows

> > 2334200
> 
> nothing marked as Windows:
> 
> https://steamdb.info/app/2334200/

The depot for [2334201](https://steamdb.info/app/2334200/depots/) (the actual Linux Server files) is marked as a Windows depot.

**Comment by scallipus** [comment]
I was able to download and do an initial run on the server to create the basic ini files using the following process...

windows server 2012R2 - run steamcmd and then login anonymous, app_update 2334200
copy the files over the my linux NFS drive
on the linux server, login and create the user for the game, switch user and run steamcmd to create the base steam files.   (I have steamcmd installed as a package)   then copy the files from the NFS drive onto the server into the users home directory under it's .steam/steamapps/LinuxServer directory


then using Midnight Commander  i launched the executable "TheFront" which then created the basic saved directory structure where the configs exist (this is all based on my ark cluster experience)

**Comment by pharrisee** [comment]
> I was able to download and do an initial run on the server to create the basic ini files using the following process...
> 
> windows server 2012R2 - run steamcmd and then login anonymous, app_update 2334200 copy the files over the my linux NFS drive on the linux server, login and create the user for the game, switch user and run steamcmd to create the base steam files. (I have steamcmd installed as a package) then copy the files from the NFS drive onto the server into the users home directory under it's .steam/steamapps/LinuxServer directory
> 
> then using Midnight Commander i launched the executable "TheFront" which then created the basic saved directory structure where the configs exist (this is all based on my ark cluster experience)

I have a set of scripts that doo all of the things required directly from the server, no transferring from Windows required:

https://github.com/pharrisee/TheFrontLinuxServerInfo

Puts the Saved folder outside the application folder to ease updates.

(tries to do things sort of in line with LGSM, using tmux for running the server tec.)

**Comment by yajiedesign** [comment]
> I was able to download and do an initial run on the server to create the basic ini files using the following process...
> 
> windows server 2012R2 - run steamcmd and then login anonymous, app_update 2334200 copy the files over the my linux NFS drive on the linux server, login and create the user for the game, switch user and run steamcmd to create the base steam files. (I have steamcmd installed as a package) then copy the files from the NFS drive onto the server into the users home directory under it's .steam/steamapps/LinuxServer directory
> 
> then using Midnight Commander i launched the executable "TheFront" which then created the basic saved directory structure where the configs exist (this is all based on my ark cluster experience)

add `+@sSteamCmdForcePlatformType windows` in steamcmd.it can download windows depot in linux.

**Comment by SylenThunder** [comment]
> > I was able to download and do an initial run on the server to create the basic ini files using the following process...
> > windows server 2012R2 - run steamcmd and then login anonymous, app_update 2334200 copy the files over the my linux NFS drive on the linux server, login and create the user for the game, switch user and run steamcmd to create the base steam files. (I have steamcmd installed as a package) then copy the files from the NFS drive onto the server into the users home directory under it's .steam/steamapps/LinuxServer directory
> > then using Midnight Commander i launched the executable "TheFront" which then created the basic saved directory structure where the configs exist (this is all based on my ark cluster experience)
> 
> I have a set of scripts that do all of the things required directly from the server, no transferring from Windows required:
> 
> https://github.com/pharrisee/TheFrontLinuxServerInfo
> 
> Puts the Saved folder outside the application folder to ease updates.
> 
> (tries to do things sort of in line with LGSM, using tmux for running the server etc.)

Just took a poke at this, and looks to be working well. I definitely look forward to seeing this supported by LGSM.
