### ISSUE TITLE
[Bug]: steamcmd is unable to print app info with +quit in the start parameter

### ISSUE THREAD

**Issue by HotoCocoaco** [GameServerManagers/LinuxGSM#4336]
### User story

I was trying to update the server with update `./tf2server update` command. But failed.

### Game

Team Fortress 2

### Linux distro

Ubuntu 22.04

### Command

command: update

### Further information

scripts log
```
UPDATE: INFO: Using anonymous Steam login
UPDATE: PASS: Checking local build
UPDATE: FATAL: Checking remote build
UPDATE: INFO: LinuxGSM version: v23.5.3
```
It seems that steamcmd is not willing to print app info with +quit behind, making `remotebuildversion` null value.
Full command line: steamcmd +login anonymous +app_info_update 1 +app_info_print 232250 +quit
Result:
```
Redirecting stderr to '/home/tf2server/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/tf2server/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
```

Without +quit
```
Waiting for user info...OK

Steam>AppID : 232250, change number : 20677424/0, last change : Sat Oct 14 19:08:16 2023
"232250"
{
        "common"
...... and more
```

I have modified core_steamcmd.sh to echo debug the value that making sure `remotebuildversion` is null.

### Steps to reproduce

1. Run ./tf2server update.
2. BOOM.
3. Run steamcmd with +quit. BOOM.
4. Without +quit. OK.

**Comment by dgibbs64** [comment]
the +quit command is required to correctly exit steamcmd. This is not an issue that I have come across or others have been reporting. I will close for now
