### ISSUE TITLE
[Bug]: pgrep reporting PIDs that do not exist sometimes and causes server crash when monitoring enabled.

### ISSUE THREAD

**Issue by Kr3m** [GameServerManagers/LinuxGSM#4343]
### User story

when monitoring is enabled, the server crashes.

### Game

Quake 3

### Linux distro

Ubuntu 22.04

### Command

command: monitor

### Further information

When server monitoring is enabled, sometimes it fails and sends a soft quit to the server.

```Oct 18 05:00:20.839 q3server: MONITOR: INFO: Checking session: CHECKING
Oct 18 05:00:23.812 q3server: MONITOR: ERROR: Checking session: ERROR
Oct 18 05:00:23.955 q3server: MONITOR: ERROR: Checking session: PIDS with old type tmux session are running
Oct 18 05:00:24.162 q3server: MONITOR: ERROR: Checking session: Killing session with the session name q3server
Oct 18 05:00:32.936 q3server: STOP: INFO: Graceful: sending "quit"
Oct 18 05:00:34.450 q3server: STOP: PASS: Graceful: sending "quit": OK: 1 seconds```

### Relevant log output

_No response_

### Steps to reproduce

Enable server monitoring in cron jobs for q3server or qlserver

**Comment by dgibbs64** [comment]
a reboot of the server should resolve this issue if lingering.

**Comment by Kr3m** [comment]
This still seems to be an issue.  I have monitoring disabled for now.

**Comment by tk1114632** [comment]
I think I have the same issue with cs2server. [issue](https://github.com/GameServerManagers/LinuxGSM/issues/4575)
