### ISSUE TITLE
[Feature]: Optimize Server Downtime for the Backup command

### ISSUE THREAD

**Issue by SB97** [GameServerManagers/LinuxGSM#4358]
### User story

As a server admin, I want the backup command optimized to minimize downtime.

### Game

TeamSpeak

### Command

command: backup

### Further information

**Issue:**
When backing up my TeamSpeak Server, there's a significant downtime, especially with files inside the TS file browser. This is because the server is stopped first and remains so until the entire backup process is completed.

**Suggested Solution:**

1. Stop the server: Essential to ensure data is static.
2. Copy the data: At this point, the data needs to be static.
3. Restart the server: Now, data dynamism can resume.
4. Execute remaining operations: Including compression, pruning, etc.

**Potential Concern:**
There's a possibility that Step 4 could use system resources that are also needed by the game server, leading to performance issues.

**Extension:**
The same principle of optimization should apply to the update-lgsm and update commands.

**Comment by dgibbs64** [comment]
This will not work as some servers are up to 30GB+ in size. You would need to have a server with around 90GB free to complete a single backup. Teamspeak is very small compared to other game servers. Your concern is also valid as while compression does take significant cpu. Running both game servers and compressing at the same time will likely reduce performance of both proccess. It is simply more efficent to let the backup complete while the server is off.
