### ISSUE TITLE
arkserver

### ISSUE THREAD

**Issue by ANTONIOPSD** [GameServerManagers/LinuxGSM#436]
Well....... defaultmap="de_dust2"   yeah, of course............. you know what I mean....

**Comment by dgibbs64** [comment]
That's because the server script is not yet finished ;-).

**Comment by pereirtc** [comment]
That's the bad part when you mix gaming with open development.

Customers cant even hold anxiety on their pants.

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/issues/424
