### ISSUE TITLE
[Bug]: INSSServer - Unable to start

### ISSUE THREAD

**Issue by OzoneDNR** [GameServerManagers/LinuxGSM#4362]
### User story

I want [install fixed] so that [server works].

### Game

Insurgency Sandstorm

### Linux distro

Debian 10

### Command

command: start

### Further information

Fresh INS S Server installed, first start - "Unable to start"

Same issue with command "debug"

### Relevant log output

```shell
Oct 30 15:28:55.836 inssserver: START: FATAL: Unable to start LinuxGSM
Oct 30 15:28:55.848 inssserver: START: INFO: LinuxGSM version: v23.6.0
Oct 30 15:28:55.849 inssserver: START: FATAL: core_exit.sh exiting with code: 1
```

**Comment by dgibbs64** [comment]
I am also experiencing this issue. Unsure why currently

**Comment by dgibbs64** [comment]
My server has now settled down and is working. I think I was missing the GSLT. Without more info I am unable to help currently. Please re-open if assistance still required
