### ISSUE TITLE
[Bug]: CS2 maxplayers don't work

### ISSUE THREAD

**Issue by dzagu** [GameServerManagers/LinuxGSM#4366]
### User story

Fix maxplayers

### Game

CS2

### Linux distro

Debian 11

### Command

command: start

### Further information

Hi, I cant change maxplayers on cs2 server

/home/cs2/lgsm/config-lgsm/cs2server/cs2server.cfg
defaultmap="de_mirage"
maxplayers="24"
tickrate="64"
and still server is set for 64players
I added the same to common.cfg

**Comment by dgibbs64** [comment]
This should have been resolved in a hotfix. Please re open if not
