### ISSUE TITLE
Force Reinstall option

### ISSUE THREAD

**Issue by DSDV** [GameServerManagers/LinuxGSM#437]
Hi,
i brake my nmrih server during server migration and i cant use the script to validate or start because of error:
$[ FAIL ] Starting nmrih-server: Cannot access /home/steamcmd/serverfiles/nmrih: No such directory

and when in install it says:

$Waiting for license info...OK
$Success! App '317670' already up to date.
$
$=================================
$Was the install successful? [y/N]

but i cant get it to redownload and isntall all files also validate dont work

i know its only for stupid ppl like me but i also may help others :D

**Comment by lanrenags** [comment]
have you tried to "redownload" the file from console and not with the script?

If not go into the steam directory and try the following command

#########
./steamcmd.sh +login username password +force_install_dir "../serverfiles" +app_update 317670 validate +quit
#########

If this doesn´t work... There is a bug on steamcmd / the serverfiles itself...

**Comment by dgibbs64** [comment]
mkdir -p /home/steamcmd/serverfiles/nmrih 

should bypass the issue
