### ISSUE TITLE
Problem on downloading HLDS Serverfiles with mods

### ISSUE THREAD

**Issue by lanrenags** [GameServerManagers/LinuxGSM#438]
HI Daniel, 

i wanted to download an Deathmatch Classic Server an got the following problem: 

After download the serverfiles always the "dmc" directory in the serverfiles folder was missing. I tired to update / reinstall but nothing worked for me. Then i started a little bit on debugging.

I found a small bug / error on the fn_install_serverfiles function. 

The script / function downloads the files with the following commandline...
###### 

${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit |tee .fn_install_serverfiles.tmp
###### 

Filed with the variables it looks like:
###### 

/home/dmcserver/steamcmd/linux32/steamcmd +login anonymous +force_install_dir /home/dmcserver/serverfiles +app_update 90 +app_set_config 90 mod dmc -validate +quit
###### 

The Problem now is, that steamcmd stops "looking" at the options after +app_update....
So only hlds is downloaded without  "+app_set_config mod dmc" 

When you turn around the option "+app_set_conf mod dmc" and "+app_update 90" then all is working fine. 
###### 

/home/dmcserver/steamcmd/linux32/steamcmd +login anonymous +force_install_dir ../serverfiles/ +app_set_config 90 mod dmc +app_update 90 validate +quit
###### 

I hope you understand what i mean. The same problem is on intalling cscz

Best regard 

LANrenaGS-Team

**Comment by dgibbs64** [comment]
I think I do understand. I will be addressing this soon. Thank you :)

**Comment by Dannyson** [comment]
This pretty much covers my issue  #432 :-)

**Comment by lanrenags** [comment]
Oh sorry i haven´t seen this issue ^^ It was too late in germany  ;)

**Comment by Dannyson** [comment]
You have found the bug and solved it, that counts :-)

**Comment by DSDV** [comment]
may it be the same likte with NMRIH ? 
https://github.com/dgibbs64/linuxgsm/issues/437

**Comment by lanrenags** [comment]
No i don´t think this is the same problem. NMRIH is not a "mod" of cstrike / hlds... This must be another problem. Maybe you have to delete the serveriles and download it again.

**Comment by dgibbs64** [comment]
I have switched it around as suggested. I did find an improvement in reliability hopefully this resolves this long standing issue finally. Thanks for your help
