### ISSUE TITLE
[Bug]: Error while start Battalion Legacy Server

### ISSUE THREAD

**Issue by bardhyliis** [GameServerManagers/LinuxGSM#4400]
### User story

As a User I want someone to fix this because I am not being able to start my server

### Game

Battalion: Legacy

### Linux distro

Ubuntu 22.04

### Command

command: start, command: stop, command: restart

### Further information

The bug is that my BATTALION: Legacy server wont start because some github url is not being found, and is returning 404 not found.

### Relevant log output

```shell
btlserver@vmi1340024:/home/SERVER$ ./btlserver start
[ WARN ] Starting btlserver: Configuration file missing!
/home/SERVER/serverfiles/Battalion/Saved/Config/LinuxServer/btlserver.ini

Downloading BATTALION: Legacy Configs
=================================
Downloading default configs from:

https://github.com/GameServerManagers/Game-Server-Configs

fetching GitHub DefaultGame.ini...curl: (22) The requested URL returned error: 404
ERROR
fetching Bitbucket DefaultGame.ini...curl: (22) The requested URL returned error: 404
FAIL
```

### Steps to reproduce

Install the Battalion: Legacy server as you normally would, than try to start it, thats how you get to the bug.

**Comment by dgibbs64** [comment]
Should now be fixed in release v23.7.0
