### ISSUE TITLE
[Bug]: check_system_requirements.sh fails if game is not explicitly listed or if default RAM is not defined as an integer (currently set to 0.5)

### ISSUE THREAD

**Issue by Pathas-Gamer** [GameServerManagers/LinuxGSM#4404]
### User story

As a user, I want Factorio to start. It currently does not. It fails with an error seemingly checking system RAM

### Game

Factorio

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

It seems ramrequirementgb is supposed to be an integer according to the log output below. However, after all the if/elif for defining the RAM requirements for each game, the final condition sets this value to 0.5 - not an integer.

else
        ramrequirementgb="0.5"
fi

# If the game or engine has a minimum RAM Requirement, compare it to system's available RAM.
if [ "${ramrequirementgb}" ]; then
        if [ "${physmemtotalgb}" -lt "${ramrequirementgb}" ]; then
                fn_print_dots "Checking RAM"
                fn_print_warn_nl "Checking RAM: ${ramrequirementgb}G required, ${physmemtotal} available"
                echo "* ${gamename} server may fail to run or experience poor performance."
                fn_sleep_time_5
        fi
fi

NOTE: Verified the bug disappears by changing the last else/fi from 0.5 to 1. Either the variable needs to be redefined as something supporting non-integer values, or the defined minimum RAM needs to be changed to an integer.

### Relevant log output

```shell
factoriouser@factorio:~$ ./fctrserver start
[ WARN ] Starting fctrserver: Default RCON password detected
/home/factoriouser/lgsm/modules/check_system_requirements.sh: line 66: [: 0.5: integer expression expected
[ FAIL ] Starting fctrserver: Unable to start TestServer
```

### Steps to reproduce

1. Install Factorio server
2. Attempt to start server
3. Observe error about check_system_requirements.sh line 66

**Comment by dgibbs64** [comment]
Thanks, I am aware of the bug with system requirements. I just forgot to fix it before release. However, the system requirements bug is different fro the factorio issue. You have 2 issues that are unrelated

**Comment by lugaamn** [comment]
cs2@ubuntu:~$ ./cs2server start
[ .... ] Starting cs2server: /home/cs2/lgsm/modules/check_system_requirements.sh: line 66: [: 0.5: integer expression expected
