### ISSUE TITLE
[Bug]: Dedicated CS2 server

### ISSUE THREAD

**Issue by pr0stre1** [GameServerManagers/LinuxGSM#4411]
### User story

Not able to start cs2server

### Game

Counter-Strike 2

### Linux distro

Ubuntu 22.04

### Command

command: start, command: monitor, command: debug

### Further information

Running steamcmd command gives error:
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/c7cef0e3-206e-465b-84a6-f94730e01635)

Running cs2server start shows this errors:
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/f51c7f88-7aff-42f3-a08a-90554fae5e7a)
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/99e4876e-1294-4874-9f56-91bf04ddb35b)
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/5b3ea8eb-f21a-4bf2-880e-e5ed7e261593)

**Comment by Nuc1eoN** [comment]
Could you please show the output of `./cs2server details` ?

**Comment by pr0stre1** [comment]
> Could you please show the output of `./cs2server details` ?

![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/f3e1256b-efa1-4e47-bbe7-787688dccdc4)
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/47ae90a9-4428-42a6-9135-5ba46d450a13)
![image](https://github.com/GameServerManagers/LinuxGSM/assets/44789800/48bf1d96-1db5-4098-aaa3-760c1a4c33d8)

**Comment by Nuc1eoN** [comment]
Oh ok you have got a startup map set, that was the problem for me. Sorry in that case I don't know what's wrong :(

The `steamservice.so` warning is not an issue btw.

**Comment by dgibbs64** [comment]
I have since fixed a minor bug where the default map was uncommented in the game config so should not be an issue anymore

**Comment by pr0stre1** [comment]
Still have same issue

**Comment by pr0stre1** [comment]
It starts and freeze after that it appears stopped
