### ISSUE TITLE
[Bug]: New commandline to add for Squad v7.0

### ISSUE THREAD

**Issue by tomypc88** [GameServerManagers/LinuxGSM#4413]
### User story

New commandline to add from the last update.

### Game

Squad

### Linux distro

Ubuntu 18.04

### Command

command: start

### Further information

The v7.0.0 update has been pushed live to the server branch.

Information bellow come from the Offworld Hosting discord.

> **New requirements for your commandline**
> Add -beaconport=15000 to your commandline - if you have more than 1 server, increase this number (no two beacon ports on the same port binding)

> With the EOS Update, you may need to open up the beacon port on your machines. By default this is port 15000. You should open a range, similar to the game port of 15000-15022. You can hard specify a server to use a specific beacon port by passing in -beaconport=150XX when launching the server. This is a UDP Port
> 
> You don't necessarily need to change your beacon port, but if you're running multiple instances of a Squad Server on one IP, you can have users connecting to the incorrect server.

**Comment by ML0B** [comment]
The LGSM monitor scripts fails since the new port (beaconport) 15000 for EOS (Epic Online Services) was introduced, which means if your run ./squadserver monitor manually or via crontab, it will falsely report the server as down and restart it, which is quite annoying if you run it every 5 minutes in crontab as per the installation instructions.

**Comment by dgibbs64** [comment]
I am taking a look at this issue currently.

**Comment by dgibbs64** [comment]
I have raised an issue with gamedig and hopfully they will be able to get querying working with EOS but it looks like gamedig will be required as I doubt I will get it working with gsquery

**Comment by dgibbs64** [comment]
Expect this fix when gamedig v5 is released and the next version of LinuxGSM comes out. https://github.com/GameServerManagers/LinuxGSM/issues/4483

**Comment by ML0B** [comment]
Just verified on my server(s) and the monitor scripts works as intended for Squad now. Thank you!
