### ISSUE TITLE
[Bug]: Hurtworld Server - Admin parameter incorrect in _default.cfg

### ISSUE THREAD

**Issue by SaltMaster420** [GameServerManagers/LinuxGSM#4424]
### User story

As a user I want to be able to simply add in "admins='#'" into the common.cfg without the need for modification of the start parameters

### Game

Hurtworld

### Linux distro

Ubuntu 22.04

### Command

command: install

### Further information

After installing Hurtworld server afresh using the steps at;
https://linuxgsm.com/servers/hwserver/
The file _default.cfg located in lgsm/config-lgsm/hwserver contains the following;

## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
# http://hurtworld.wikia.com/wiki/Hosting_A_Server
startparameters="-batchmode -nographics -logfile ${gamelog} -exec \"host ${port} ${defaultmap} ${loadsave};queryport ${queryport};maxplayers ${maxplayers};servername ${servername};creativemode ${creativemode};${admins}\""

This is invalid and shows in the logs as "unknown command - STEAMIDHERE" when admins is loaded from the variable.

What happens is, it outputs it as;

./Hurtworld.x86_64 -batchmode -nographics -logfile /home/steam/log/server/hwserver-game.log -exec "host 12871 nullius autosave_nullius;queryport 12881;maxplayers 2;servername RNAS;creativemode 0;STEAMIDREDACTED"

It should be;

./Hurtworld.x86_64 -batchmode -nographics -logfile /home/steam/log/server/hwserver-game.log -exec "host 12871 nullius autosave_nullius;queryport 12881;maxplayers 2;servername RNAS;creativemode 0;**addadmin** STEAMIDREDACTED"

Note the missing addadmin parameter

### Steps to reproduce

1. Go to https://linuxgsm.com/servers/hwserver/
2. At Step 3 of the guide (of the link above) check the file _default.cfg for reference (when copying into common.cfg)
Refer to line 30 of this file, which is incorrectly listed as;
startparameters="-batchmode -nographics -logfile ${gamelog} -exec \"host ${port} ${defaultmap} ${loadsave};queryport ${queryport};maxplayers ${maxplayers};servername ${servername};creativemode ${creativemode};${admins}\""

**Comment by dgibbs64** [comment]
a2406a510c97b639dc20782d352855fbdc86fb12
