### ISSUE TITLE
[Bug]: Garry's Mod Server Name NOT SET

### ISSUE THREAD

**Issue by nerzlakai96** [GameServerManagers/LinuxGSM#4439]
### User story

When i start, stop or restart the Garry's Mod Server, it says: [  OK  ] Starting gmodserver: NOT SET

### Game

Garry's Mod

### Linux distro

Debian 12

### Command

command: start, command: stop, command: restart

### Further information

It worked flawlessly all the years before so it might me related with the latest version of LinuxGSM.
gmodserver.cfg is successfully set in serverfiles/garrysmod/cfg and the common.cfg is setup properly.

./gmodserver details gives me the following output:
Garry's Mod Server Details
================================================================================
Server name:      NOT SET
App ID:           4020
Server IP:        0.0.0.0:27015
Internet IP:      [*REMOVED DUE TO PRIVACY*]
Server password:  NOT SET
RCON password:    NOT SET
Maxplayers:       15
Default map:      rp_rockford_v2b
Game mode:        darkrp
Tick rate:        33
Master server:    not listed
Status:           STARTED

In other Games like Counter-Strike 2, the problem is not there, so it might be a problem just with Garry's Mod.

Thanks in advance and kind regards,
nerzlakai96

**Comment by nerzlakai96** [comment]
I need to add one important information. The gmodserver.cfg gets executed successfully in serverfiles/garrysmod/cfg and the Server Name and is correctly listed in Garry's Mod Server list itself. It's just within LinuxGSM that it's listed as NOT SET.

**Comment by h3o66** [comment]
would have helped if you added here what servername you did set.
I guess it is not in the format we expect, so i would wonder what you did set.

as far as i can see that we expect the general forrmat:
`hostname "<servername>"`

**Comment by nerzlakai96** [comment]
Hey h3o66,
thank you for your reply.

The issue got solved now. The hostname parameter didn't have any non-regular characters, LinuxGSM just couldn't read it when there was more than 1 blank space between hostname "<servername>" in gmodserver.cfg like e.g. hostname     "<servername>"
