### ISSUE TITLE
[Server Request]: Crysis 1,2,3

### ISSUE THREAD

**Issue by BestNoob** [GameServerManagers/LinuxGSM#4441]
### Game server

Crysis 2 Dedicated Linux Server, Crysis CryMP,

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

17300

### Guides

https://github.com/crymp-net/master-server-v2
https://crymp.net/ or https://github.com/crymp-net

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BestNoob** [comment]
*PUSH

https://github.com/crymp-net/
https://github.com/crymp-net/client-server

OpenSpy
http://beta.openspy.net/en/supported-games

**Comment by h3o66** [comment]
I cannot find anything where to get the serverfiles for linux or how to setup a server for linux.

The provided links do not have enough info to setup anything for a dedicaded server.

I found only windows server setup infos.

**Comment by BestNoob** [comment]
> I cannot find anything where to get the serverfiles for linux or how to setup a server for linux.
> 
> The provided links do not have enough info to setup anything for a dedicaded server.
> 
> I found only windows server setup infos.

Im sorry i forgot that u dont support emulated environments. (Its only running on Linux via Proton or Wine)
https://www.protondb.com/

**Comment by h3o66** [comment]
note from the request form:
`Does this game server have Linux support? (not wine)`

That includes in this case proton as it is based on wine.
