### ISSUE TITLE
[Feature]: Counter-Strike 2 details missing

### ISSUE THREAD

**Issue by xe1os** [GameServerManagers/LinuxGSM#4447]
### User story

As a cs2server, I want to see all the server information so that it is easier to get the details using the command instead of getting from server console.

### Game

Counter-Strike 2

### Linux distro

Ubuntu 22.04

### Command

command: details

### Further information

Hi,

 Counter-Strike details like server & rcon password, SourceTV ports are missing when we execute `./cs2server details`

**Comment by dgibbs64** [comment]
Is sourceTV a thing in CS2?

**Comment by sirNugg3ts** [comment]
> Is sourceTV a thing in CS2?

of course ? how else are we supposed to spectate games in tournaments.
Instead of being called GOTV it's called sourceTV tho

**Comment by xe1os** [comment]
@dgibbs64 it is always better to have mapgroup, defaultmap and workshop maps in the _default.cfg file rather than having it in cs2server.cfg

**Comment by dgibbs64** [comment]
I have fixed server password. The last time I checked rcon did not work in cs2, please let me know if this has changed and I also cant find any evidence of sourcetv being available in cs2. If you could provide any docs/sources about sourcetv on cs2 that would be help. Thanks

**Comment by borzaka** [comment]
- Actually it's now called CSTV, and it's the successor of GOTV. Almost every command works.
- For the time being, Valve has not enabled RCON commands to be executed through the in-game console. This will hopefully be fixed by an update in the near future, though. There are alternative for that: RCON-CLI, Fake RCON plugin, and other RCON tools.

**Comment by dgibbs64** [comment]
I just read that CSTV is currently disabled and I tried to enable it but no ports opened up. But when it is re-enabled please raise a new issue with the required config updates and I will be happy to add the details onto the server
