### ISSUE TITLE
[Server Request]: Palworld

### ISSUE THREAD

**Issue by rogeraabbccdd** [GameServerManagers/LinuxGSM#4448]
### Game server

Palworld

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

2394010

### Guides

[Official Documentation](https://tech.palworldgame.com/dedicated-server-guide#linux)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xlord** [comment]
I second this. Palworld has had a tremendously good start with almost 304k people playing this game currently. Making it the fourth most played game on Steam. It's also the top selling game today worldwide on Steam. 
A quick implementation could benefit LGSM IMHO. Server installation seems to be pretty basic with downloading the appid and starting the server.sh.

**Comment by reddexx** [comment]
https://tech.palworldgame.com/dedicated-server-guide#linux

**Comment by Strovo** [comment]
I did everything just as it is in the guide

`dlopen failed trying to load:
/home/strovo/.steam/sdk64/steamclient.so
with error:
/home/strovo/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/strovo/.steam/sdk64/steamclient.so
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/strovo/.steam/sdk64/steamclient.so
with error:
/home/strovo/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/strovo/.steam/sdk64/steamclient.so
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/strovo/.steam/sdk64/steamclient.so
with error:
/home/strovo/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/strovo/.steam/sdk64/steamclient.so
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/strovo/.steam/sdk64/steamclient.so
with error:
/home/strovo/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/strovo/.steam/sdk64/steamclient.so
`

**Comment by BlackDahlia313** [comment]
Yes please. Here to help.

**Comment by rogeraabbccdd** [comment]
> I did everything just as it is in the guide

You have to create `.steam/sdk64/` in your home directory and copy `steamclient.so` from steamcmd.

**Comment by Ziegenbeisser** [comment]
> > I did everything just as it is in the guide
> 
> You have to create `.steam/sdk64/` in your home directory and copy `steamclient.so` from steamcmd.

Thank you! That worked for me!

**Comment by naoestu** [comment]
"[ FAIL ] Starting pwserver: executable was not found
* /home/pwserver/serverfiles/Pal/Engine/Binaries/Linux/PalServer-Linux"

Isn't it still fully added to LGSM?

**Comment by Nolux** [comment]
> "[ FAIL ] Starting pwserver: executable was not found /home/pwserver/serverfiles/Pal/Engine/Binaries/Linux/PalServer-Linux"
> 
> Isn't it still fully added to LGSM?

Having the same issues

**Comment by eviljoe** [comment]
I had that problem as well.  I was able to fix it by updating `~/lgsm/config-lgsm/pwserver/common.cfg` with the following settings:

```ini
executabledir="${systemdir}/Binaries/Linux"
executable="./PalServer-Linux-Test"
```

This probably isn't a long-term fix, but it did work in the short-term until this is officially fixed.

**Comment by chrisngobanh** [comment]
Does anyone know how to fix the issue where `./pwserver monitor` seems to start up the server with the wrong world or player saves? `./pwserver start` and `./pwserver restart` seem to work fine.

**Comment by Strovo** [comment]
Delete all files, serverfiles and gsm files and reinstall, the New versión
works

**Comment by chrisngobanh** [comment]
> Does anyone know how to fix the issue where `./pwserver monitor` seems to start up the server with the wrong world or player saves? `./pwserver start` and `./pwserver restart` seem to work fine.

Managed to fix this. Nothing wrong with LinuxGSM, the problem was that my cron environment couldn't find `steamclient.so`
