### ISSUE TITLE
[Server Request]: Enshrouded Vanilla

### ISSUE THREAD

**Issue by jojolebobo** [GameServerManagers/LinuxGSM#4460]
### Game server

Enshrouded

### Linux support

- [ ] Yes

### Steam

Yes

### Steam appid

2278520

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by h3o66** [comment]
I do not see at all that this is supported on linux.
https://steamdb.info/app/2278520/

Is there any more info ?

**Comment by RolleRollsen** [comment]
Seems to be Windows Server only. Can be run on Linux as described by [https://github.com/PR3SIDENT/enshrouded-server](https://github.com/PR3SIDENT/enshrouded-server) by using wine. But LinuxGSM will not support servers running with wine (FAQ).

**Comment by zino1337** [comment]
Can also be run via Proton with better performance. In addition to that, I build an Enshrouded Docker for Windows Server 2022 if interested.

**Comment by Gibigbig** [comment]
> Can also be run via Proton with better performance. In addition to that, I build an Enshrouded Docker for Windows Server 2022 if interested.

please send the docker, thanks
