### ISSUE TITLE
[ .... ] lgsm/modules/info_distro.sh: line 100: [: : integer expression expected

### ISSUE THREAD

**Issue by bluenor** [GameServerManagers/LinuxGSM#4465]
### User story

When i start all game servers appear lgsm/modules/info_distro.sh: line 100: [: : integer expression expected

### Game

All lgsm games

### Linux distro

RedHat 7, Other

### Command

command: start, command: restart, command: details, command: update, command: validate, command: debug

### Further information

Hello, i have centos 7 and rh 7, when i start any game server with these distro appear the error:

lgsm/modules/info_distro.sh: line 100: [: : integer expression expected

Anyway the server seems to start correctly. I would like to know if it's normal. Thank you.

### Relevant log output

```shell
lgsm/modules/info_distro.sh: line 100: [: : integer expression expected
```

### Steps to reproduce

any start of lgsm servers in red hat like.

**Comment by Scott-GMI** [comment]
Posted the same issue a month back - #4428 

The following worked for me for Rocky Linux 9.2

Line 98 in info_distro.sh

elif [[ "${distroidlike}" == "rhel" ]] || [ "${distroid}" == "rhel" ]; then

Changed to

elif [ "${distroidlike}" == "rhel" ] || [ "${distroid}" == "rhel" ]; then

This fixed the error -> line 100: [: : integer expression expected

Changing the [[ ]] to [ ] @ line 98 looks to be the fix.

**Comment by dgibbs64** [comment]
Morning, I have popped that in the queue to take a look. Should be a minor fix. Thanks

**Comment by BertBrenner** [comment]
The real problem should be in line 34, it uses 2 variables which are empty till line 37.

It will work on my system if i move line 37 and 38 upward to be executed before the if statement.
