### ISSUE TITLE
[Garry's Mod] 8557 Segmentation Error

### ISSUE THREAD

**Issue by Wafflezzz** [GameServerManagers/LinuxGSM#447]
TDM Cars are giving me this error, because without it, it works:
http://gyazo.com/5ee6ddb040e6f88cd4d1c48349f1ebac

I restarted the VPS and I get this error swell
./srcds_run: line 372:  1042 Segmentation fault      $HL_CMD

**Comment by dgibbs64** [comment]
This is an issue with TDM Cars and Gmod not LGSM. You need to seek help from TDM Cars of Gmod forums etc.
