### ISSUE TITLE
[sdtdserver] Can't start/connect to the Server

### ISSUE THREAD

**Issue by nikkimas** [GameServerManagers/LinuxGSM#448]
hey,

I'm getting this in the console when I start the server. I don't know if that is normal, but I can't connect. 
![image](https://cloud.githubusercontent.com/assets/11046364/8635619/a28b17d0-282b-11e5-8681-6be2e05b1230.png)

**Comment by dgibbs64** [comment]
That's normal. Unable to connect issues are normally related to your firewall

**Comment by nikkimas** [comment]
just reinstalled the server and saw there is a bit of a Spelling error. I think you forgot to make a new line.
![image](https://cloud.githubusercontent.com/assets/11046364/8637421/55415cb2-2891-11e5-8059-462e8d315688.png)

Down at the bottm :)

**Comment by nikkimas** [comment]
Just started the Server, and shouldn't I be able to enter Commands in the console? If I type "help" or "admin add" nothing happens. got the commands right here: http://7daystodie.gamepedia.com/Command_Console

**Comment by dgibbs64** [comment]
That's the in-game console. There isnt one for server with this game as far as I am aware.

Also fixed the message. Thanks

**Comment by nikkimas** [comment]
okay, now the Server crashed when I tried to join. Which log(s) do you need?

**Comment by dgibbs64** [comment]
/home/sd2dserver/log might help

**Comment by nikkimas** [comment]
I feel stupid right now. I can't find the crash-report. These are all the contents of /home/sdtdserver/log:
http://macoga.de/logs/
I hope this helps

**Comment by dgibbs64** [comment]
/home/sd2dserver/log/server if it exists should link you to the servers logs as your current logs only show the console, steamCMD and LGSM logs
