### ISSUE TITLE
[Bug]: Unexpected EOF in info_game.sh

### ISSUE THREAD

**Issue by dragokas** [GameServerManagers/LinuxGSM#4482]
### User story

Unexpected EOF error is raised when you try to restart the server

### Game

Left 4 Dead 1

### Linux distro

Debian 12

### Command

command: restart

### Further information

Unexpected EOF error is raised when you try to start, stop or restart the server.
update-lgsm doesn't help. All modules are up to date.

### Relevant log output

```shell
l4dmain@debian10x64:~$ ./l4dserver r
/home/l4dmain/lgsm/modules/info_game.sh: eval: line 184: unexpected EOF while looking for matching `"'
```

### Steps to reproduce

Execute:
```
./l4dserver r
```

**Comment by dragokas** [comment]
Ok, figured out. It doesn't like character sequnce
```
$(
```
in rcon_password

**Comment by h3o66** [comment]
you can probably use this if you put this in single quotes like this:

```
variable='a$(b'
```

**Comment by dragokas** [comment]
Not agree it is solved. It's better to insert somewhere a meaningful message saying that it is forbidden to use $( sequence in the password instead of throwing a syntax error.

**Comment by h3o66** [comment]
well, this is a standard open sequence for a subprocess in bash.

Did you at least check my comment ?
That works for me to have a `$(` in the variable

I do only see a way to stop lgsm when it detects a not "working" config.
To check for the string might not be not be the best idea, better only validate the read of the configs.

**Comment by dragokas** [comment]
I'm not the only one. Other people may also suffer similar issue. Fix should go to master branch, not to my own local script. However, you closed this issue.
