### ISSUE TITLE
[Bug]: CS2 install script is getting stuck

### ISSUE THREAD

**Issue by Nuc1eoN** [GameServerManagers/LinuxGSM#4498]
### User story

As a server admin, I want to set up a CS2 server

### Game

CS2

### Linux distro

AlmaLinux 9.3

### Command

command: install

### Further information

I am trying to install CS2 following the instructions from the website: https://linuxgsm.com/servers/cs2server/

I have put the username and pw inside `lgsm/config-lgsm/cs2server/common.cfg`.
My account is secured by SteamGuard with e-mail verification.

I am typing `./cs2server install` according to the instructions.

The script checks all deps, which are OK, and then gets stuck on

`[ START ] Installing cs2server: SteamCMD`

This is stuck indefinitely.
I have found out that when I press enter I will get more output however:
```
[ START ] Installing cs2server: SteamCMD

tid(13313) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/cs2server/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/cs2server/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Logging in user 'myusername' to Steam Public...
This computer has not been authenticated for your account using Steam Guard.
Please check your email for the message from Steam, and enter the Steam Guard
 code from that message.
You can also enter this code at any time using 'set_steam_guard_code'
 at the console.
Steam Guard code:FAILED (Account Logon Denied)
Complete! Installing cs2server: SteamCMD
[ ERROR ] Installing cs2server: No appmanifest_730.acf found
[ INFO ] Installing cs2server: Forcing update to correct issue
[ START ] Installing cs2server: SteamCMD
```
Since nothing happens, and the script is stuck indefinitely I am pressing ENTER again and get:
```
tid(13355) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/cs2server/.local/share/Steam/logs/stderr.txt'
Logging directory: '/home/cs2server/.local/share/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Logging in user 'myusername' to Steam Public...
This computer has not been authenticated for your account using Steam Guard.
Please check your email for the message from Steam, and enter the Steam Guard
 code from that message.
You can also enter this code at any time using 'set_steam_guard_code'
 at the console.
Steam Guard code:FAILED (Account Logon Denied)
Complete! Installing cs2server: SteamCMD
[ FAIL ] Installing cs2server: Still no appmanifest_730.acf found
```

At that point the script exits.

The script makes me aware that I should use `set_steam_guard_code` to enter my email verification code, but that command does not seem to exist on my system or the information on how to use this command is unclear.

I assume the script is not supposed to get stuck in the first place? It seems to be a bug unless I am mistaken. At least I followed the instructions exactly but cannot get it up and running.

**Comment by SatyamBansal** [comment]
i am also facing same issue

**Comment by dgibbs64** [comment]
CS2 us anonymous login and no login details are required

**Comment by Nuc1eoN** [comment]
I thought anonimous login for CS2 is not possible anymore?

**Comment by dgibbs64** [comment]
it was changed to anonymous not long after release. No logins are required

**Comment by Nuc1eoN** [comment]
Ok? I didn't know. Then documentation on https://linuxgsm.com/servers/cs2server/ install section should be updated to reflect that.

**Comment by dgibbs64** [comment]
Good spot. Thanks I will update it 😄

**Comment by h3o66** [comment]
That seems to be a old ticket what should not be anymore.
closed, please reopen in case thie is still the case.
