### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DEAM0** [GameServerManagers/LinuxGSM#4529]
### User story

Start Palworld Server

### Game

PalWorld

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

/home/pwserver/lgsm/modules/command_debug.sh: line 121: 29847 Illegal instruction     (core dumped) ./PalServer-Linux-Test -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -servername='LinuxGSM' -port='8211' -queryport='27015'

**Comment by irobot73** [comment]
How are you passing those start-up params?  I utilize the COMMON.CFG.  Might be an extra tic (') causing problems??:
```
##################################
######## Common Settings #########
##################################
# PLACE GLOBAL SETTINGS HERE
## These settings will apply to all instances.

## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
## Game Server Docs | https://tech.palworldgame.com/dedicated-server-guide#linux
startparameters="-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publiclobby -port=8211 -queryport=8212 rconport=8213 -publicport=8211 -publicip=45.27.239.93"
```

What are you attempting to DEBUG?  Can't say I've tried using that command

**Comment by DEAM0** [comment]
> How are you passing those start-up params? I utilize the COMMON.CFG. Might be an extra tic (') causing problems??:
> 
> ```
> ##################################
> ######## Common Settings #########
> ##################################
> # PLACE GLOBAL SETTINGS HERE
> ## These settings will apply to all instances.
> 
> ## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
> ## Game Server Docs | https://tech.palworldgame.com/dedicated-server-guide#linux
> startparameters="-useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -publiclobby -port=8211 -queryport=8212 rconport=8213 -publicport=8211 -publicip=45.27.239.93"
> ```
> 
> What are you attempting to DEBUG? Can't say I've tried using that command

where is this file?
