### ISSUE TITLE
[Bug]: Rust: server lag spikes during newly implemented ping estimates

### ISSUE THREAD

**Issue by karenmcd** [GameServerManagers/LinuxGSM#4557]
### User story

I'd like that the new ping variables be added to the server configuration so that we can enter values that work for us.

### Game

RUST

### Linux distro

Debian 12

### Command

command: start

### Further information

There's a newly implemented function to adjust the intervals and if even your RUST server executes pings to publish an estimated latency for the client in the server selection list. As I understand it, without being able to adjust this, the default settings execute 20x5 ping commands at once, and it waits for all of the results to return causing a huge lag spike in game for all clients making it near unplayable every five minutes.

### Relevant log output

https://commits.facepunch.com/r/rust_reboot/main/ping_estimate_cleanup

There's information here about how to add/fix it? I'm unsure how, what or where i'd put this information without my changes being overwritten by lgsm.

**Comment by scalbox** [comment]
Hi 
fix for this problem
https://digitalmarketplay.com/product/rust-ping-estimation-lag-stalling-fix-rust-update-04-04-2024/

**Comment by dgibbs64** [comment]
Its not clear exactly what you want me to do from a LinuxGSM perspective

**Comment by scalbox** [comment]
is a plugin that disables the new rust feature that causes high ping

**Comment by dgibbs64** [comment]
Thats fine. But what do I need to do for LinuxGSM? If I don't need to make any changes for LinuxGSM then I can just close this

**Comment by scalbox** [comment]
Yes, it is not necessary to change LinuxGSM.

**Comment by karenmcd** [comment]
I spoke to their support to get better understanding of what to do. they said that the fix will not be implemented until the next time the server gets updated. the LGSM configuration may need to be updated to include new options in the startup script to allow changes.

the plugin they are describing that "fixes" it only applies if you're running oxide plugins. my server is vanilla without plugins so I can't use that fix they are referring to.

honestly we won't know what to do until they move the patch to add parameters to the main branch, and even then it might not be a lgsm issue, it  might end up just being a server.cfg and not a lgsm-config setting? I guess I don't know/understand  yet
-- 
Sent from my LineageOS device with K-9 Mail. Please excuse my brevity.

**Comment by karenmcd** [comment]
this link to digital market play isn't helpful if you're not running plugins. Linux servers without oxide (non-modded community servers) cannot run this and are stuck still with extreme lag spikes every 5 minutes until they deploy the fix to main branch. I don't want to have to manage mods and risk taking my server out of the community servers and moved to the modded servers.
--

**Comment by scalbox** [comment]
If not user plugin
https://commits.facepunch.com/r/rust_reboot/main/ping_estimate_cleanup

**Add `ping_samples` to control how many times to ping each endpoint (default 5)**

**Comment by scalbox** [comment]
But you will have to wait for the release of the patch, if you use vanilla servers, if you are not official, then you can use Oxide itself and add this plugin. Otherwise I can make you the same plugin but as a Harmony dll, which does not require Oxide

**Comment by scalbox** [comment]
Vanilla and community servers can run Oxide. just respect the rust guidelines. They use oxide for admin and anti cheat plugins

**Comment by scalbox** [comment]
https://support.facepunchstudios.com/hc/en-us/articles/360009062817-Guidelines-for-community-servers-using-plugins-mods

**Comment by scalbox** [comment]
For those who don't want to use my plugin [https://digitalmarketplay.com/product/rust-ping-estimation-lag-stalling-fix-rust-update-04-04-2024/](url) because they don't have umox/carbon, you can set this server property:
**ping.ping_estimation false**
