### ISSUE TITLE
[Server Request]:  Icarus Dedicated Server

### ISSUE THREAD

**Issue by skynett81** [GameServerManagers/LinuxGSM#4565]
### Game server

Icarus

### Linux support

- [ ] Yes

### Steam

Yes

### Steam appid

1149460

### Guides

Icarus is a session-based survival game for up to 8 co-op players or solo players, where most gameplay occurs during timed missions. Players accept contracts for missions on a space station orbiting the planet, and drop down to its terrain to attempt the objectives. Once a mission timer is complete, the drop-pod returns to the station. If the player fails to return in time, their workshop items are left on the surface and their progress is lost. There is also support for an OpenWorld where without resets.

Can you link to any tutorials or guides?
https://github.com/RocketWerkz/IcarusDedicatedServer

Provide any useful documentation or resources that might help.
https://github.com/RocketWerkz/IcarusDedicatedServer

you can use Wine

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/icarus

when Cubecoders can make a server for linux, i do think that linuxgsm can too.

https://discourse.cubecoders.com/t/added-icarus-support/2550

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgibbs64** [comment]
LinuxGSM does not support Wine

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: SkyNett81 ***@***.***>
Sent: Saturday, April 27, 2024 5:40:45 PM
To: GameServerManagers/LinuxGSM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GameServerManagers/LinuxGSM] [Server Request]: Icarus Dedicated Server (Issue #4565)


Game server

Icarus

Linux support

  *    Yes

Steam

Yes

Steam appid

1149460

Guides

Icarus is a session-based survival game for up to 8 co-op players or solo players, where most gameplay occurs during timed missions. Players accept contracts for missions on a space station orbiting the planet, and drop down to its terrain to attempt the objectives. Once a mission timer is complete, the drop-pod returns to the station. If the player fails to return in time, their workshop items are left on the surface and their progress is lost. There is also support for an OpenWorld where without resets.

Can you link to any tutorials or guides?
https://github.com/RocketWerkz/IcarusDedicatedServer

Provide any useful documentation or resources that might help.
https://github.com/RocketWerkz/IcarusDedicatedServer

you can use Wine

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/icarus

when Cubecoders can make a server for linux, i do think that linuxgsm can too.

https://discourse.cubecoders.com/t/added-icarus-support/2550

Code of Conduct

  *    I agree to follow this project's Code of Conduct
