### ISSUE TITLE
[Server Request]: FOUNDRY

### ISSUE THREAD

**Issue by tomypc88** [GameServerManagers/LinuxGSM#4568]
### Game server

FOUNDRY

### Linux support

- [X] Yes

### Steam

Yes

### Steam appid

983870

### Guides

The Steam appid for the game its https://steamdb.info/app/983870/
but I suspect for dedicated server its that https://steamdb.info/app/2915550

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ce-ju** [comment]
No Linux Support
https://steamdb.info/app/2915550/depots/

**Comment by Requion** [comment]
Kinda Linux Support
https://github.com/luxusburg/docker-foundry

(If Xvfb is tolerated)

**Comment by ripsnortntear** [comment]
https://github.com/luxusburg/docker-foundry
100% works well. i have been running for a week now solid

**Comment by h3o66** [comment]
starts the server with wine ...

https://github.com/luxusburg/docker-foundry/blob/main/files/start.sh#L96

from the line:
`xvfb-run wine $server_files/FoundryDedicatedServer.exe -log`
