### ISSUE TITLE
[Server Request]: 

### ISSUE THREAD

**Issue by capntack** [GameServerManagers/LinuxGSM#4582]
### Game server

V Rising

### Linux support

- [ ] Yes

### Steam

Yes

### Steam appid

1604030

### Guides

Official instructions: https://github.com/StunlockStudios/vrising-dedicated-server-instructions/blob/master/1.0.x/INSTRUCTIONS.md

Example of a Docker container which uses wine: https://github.com/TrueOsiris/docker-vrising?tab=readme-ov-file

The game itself runs smoothly on Linux using Proton.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgibbs64** [comment]
As per https://github.com/GameServerManagers/LinuxGSM/issues/3953 and https://github.com/GameServerManagers/LinuxGSM/issues/4579 

V Rising is Windows only
