### ISSUE TITLE
[Bug]: Missing pigz dependance for backuping Soulmask server

### ISSUE THREAD

**Issue by intel44** [GameServerManagers/LinuxGSM#4604]
### User story

As an administrator, I want to back up the servers to avoid any unfortunate violence with friends in the event of data loss :)

### Game

Soulmask

### Linux distro

Ubuntu 22.04

### Command

command: backup

### Further information

They added `pigz` package as backup dependancy, cannot backuping the whole server without it anymore 

### Relevant log output

```shell
Jun 27 11:44:31.485 smserver: BACKUP: INFO: Backup lockfile generated
Jun 27 11:44:31.487 smserver: BACKUP: INFO: /home/smserver/lgsm/lock/backup.lock
Jun 27 11:44:31.590 smserver: BACKUP: INFO: A total of 38G will be compressed: /home/smserver/lgsm/backup/smserver-2024-06-27-114423.tar.gz
Jun 27 11:44:32.093 smserver: BACKUP: INFO: Backup 38G smserver-2024-06-27-114423.tar.gz, in progress
Jun 27 11:44:32.213 smserver: BACKUP: FATAL: Backup in progress: FAIL

Jun 27 11:44:32.318 smserver: BACKUP: FATAL: Starting backup
Jun 27 11:44:34.242 smserver: START: WARN: Missing dependencies: pigz
```

**Comment by MicLieg** [comment]
Did you try installing `pigz`?

`sudo apt install pigz`

Using this dependency allows for way faster backup creation thus lowering downtimes.

**Comment by intel44** [comment]
> Did you try installing `pigz`?
> 
> `sudo apt install pigz`
> 
> Using this dependency allows for way faster backup creation thus lowering downtimes. More info: #4509

Yes thanks you, it was just an issue in order to create a PR 😉

**Comment by intel44** [comment]
> Did you try installing `pigz`?
> 
> `sudo apt install pigz`
> 
> Using this dependency allows for way faster backup creation thus lowering downtimes. More info: #4509

Ah 😆  I didn't understand what you meant. The dependency was added globally, I didn't see the alert on my side during the server install (done via ansible so no prompt). I went too fast for the PR, thanks for your info.

**Comment by MicLieg** [comment]
> I went too fast for the PR

No worries, glad i could help :)
