### ISSUE TITLE
This commit regressed #3764. Enabling monitor on 7 Days to Die continually restarts the server

### ISSUE THREAD

**Issue by VlkaFenryka** [GameServerManagers/LinuxGSM#4615]
This commit regressed #3764. Enabling monitor on 7 Days to Die continually restarts the server

_Originally posted by @parasyte in https://github.com/GameServerManagers/LinuxGSM/pull/4510#discussion_r1673145468_

**Comment by parasyte** [comment]
Duplicate of #4610.
