### ISSUE TITLE
[Server Request]: Subsistence

### ISSUE THREAD

**Issue by shinzoke** [GameServerManagers/LinuxGSM#4631]
### Game server

Subsistence

### Linux support

- [ ] Yes

### Steam

Yes

### Steam appid

1362640

### Guides

https://steamcommunity.com/sharedfiles/filedetails/?id=2201638184

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ce-ju** [comment]
No Linux Support

**Comment by dgibbs64** [comment]
![image](https://github.com/user-attachments/assets/3999ecf4-62ac-4aa1-bb36-6ccd8de47d5b)
https://steamdb.info/app/1362640/

Closing
