### ISSUE TITLE
[Bug]: Unreal Tournament 3 server does not query or list or master servers

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#4656]
### User story

As a developer I would like UT3 to list on openspy and query correctly

### Game

Unreal Tournament 3

### Linux distro

Ubuntu 22.04

### Command

command: monitor

### Further information

Unreal Tournament 3 server does not query or list or master servers

**Comment by BestNoob** [comment]
Yeah have same issue today. I registered an account, opened the ports and i can join via IP but server is NOT listed in serverlist.

**Comment by h3o66** [comment]
This was released with 24.3.0
