### ISSUE TITLE
[Feature]: CS2 Counter-Strike 2 DISK SPACE usage

### ISSUE THREAD

**Issue by BestNoob** [GameServerManagers/LinuxGSM#4663]
### User story

I want a small setup for CS2 Dedicated Server

### Game

Counter-Strike 2

### Linux distro

Ubuntu 20.04, Debian 11

### Command

command: start, command: validate, command: install

### Further information

I know VALVE recommended 33GB Disk Space but as i can see you can lower the stuff of the dedicated server to 8GB ?!
The problem is i removed (texture & model) files out of the server but i DONT KNOW if VAC will take action adn BAN such behaviour ..

Hope you guys can test it and maybe lower the disk space usage of CS2 dedi .... would be great.

https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers

**Comment by h3o66** [comment]
The problem is that the steamcmd anyway would download all again if you validate the file or with other ways.
This does not make sense at all , as this would be as well unsupported in general.

I do not see a way to support that with steamcmd at all.
