### ISSUE TITLE
[Bug]: Minecraft Bedrock Install/Update no longer works due to changes of URLs on website.

### ISSUE THREAD

**Issue by Crimson-Decoded** [GameServerManagers/LinuxGSM#4673]
### User story

As a server administrator, I want to be able to install Minecraft Bedrock Edition dedicated server easily

### Game

Minecraft Bedrock

### Linux distro

Other

### Command

command: update, command: install

### Further information

A recent update to the Minecraft download site has changed the URL for downloads. This results in Minecraft servers with their version set to `latest` to fail to update
The current URL used in mcb_update.sh is
`'https://minecraft.azureedge.net/bin-linux/[^"]*'`
However this is no longer found on the page, resulting in update and installs to fail.
This is now
`'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*'`

curl | grep output included in logs as evidence.

The original URL still works to download, so systems configured with a specific version will still work (for now).
It's mainly that the download page no longer uses the URL so the lookup for remote build of Latest fails.

### Relevant log output

```shell
~$ curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -Ls -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.${randomint}.212 Safari/537.36" "https://www.minecraft.net/en-us/download/server/bedrock/" | grep -o 'https://minecraft.azureedge.net/bin-linux/[^"]*'
~$ curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -Ls -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.${randomint}.212 Safari/537.36" "https://www.minecraft.net/en-us/download/server/bedrock/" | grep -o 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/[^"]*'
https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.30.03.zip
~$
```

### Steps to reproduce

attempt to install or update mcbserver with version set to Latest

**Comment by h3o66** [comment]
hotfix version 24.3.1 was released earlier.
