### ISSUE TITLE
[Bug]: Cannot download serverlist.csv

### ISSUE THREAD

**Issue by rAmfu** [GameServerManagers/LinuxGSM#4676]
### User story

As described

### Game

All games

### Linux distro

Debian 12

### Command

command: install

### Further information

Cant start installing any of game server :/

### Relevant log output

```shell
curl -Lo linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh arkserver
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0     32      0  0:00:05  0:00:05 --:--:--    38
100 18430  100 18430    0     0   1776      0  0:00:10  0:00:10 --:--:--  4045
fetching GitHub serverlist.csv...ERROR
fetching Bitbucket serverlist.csv...FAIL
linuxgsm.sh: line 134: core_exit.sh: command not found
[ FAIL ] serverlist.csv could not be loaded.
```

**Comment by dgibbs64** [comment]
Looks likw either an internet or DNS issue. LinuxGSM cant get to the internet to download the files it needs

**Comment by dgibbs64** [comment]
Interesting I have got the issue in one of my unit tests but I cant replicate it myself currently

**Comment by dgibbs64** [comment]
Are you running the docker container?

**Comment by rAmfu** [comment]
Nowe on my brige machine and it connect as dmz into internet

**Comment by rAmfu** [comment]
Give me directly link to serverlist to manulally download

**Comment by h3o66** [comment]
> Looks likw either an internet or DNS issue. LinuxGSM cant get to the internet to download the files it needs. Which is odd as you just downloaded linuxgsm.sh

the easiest to verify would be to get a dev-debug.log and check the curl returncode.
There should be nothing sensitive in the log usually.

to create the log:

change to the same dir where the linuxgsm.sh is
```
touch .dev-debug
bash linuxgsm.sh arkserver
```

upload the file `dev-debug.log` from the same folder here.

**Comment by dgibbs64** [comment]
There was a bug in the develop branch that had the same issue but this has been resolved. The bug definitely wasnt in master

**Comment by h3o66** [comment]
> Give me directly link to serverlist to manulally download

the direct link of the file is this one from the repo:
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/data/serverlist.csv

note: you need to use the raw download link.

would be nice if you could do the dev debug before you proceed

**Comment by rAmfu** [comment]
[dev-debug.log](https://github.com/user-attachments/files/17174517/dev-debug.log)

Manulally add serverlist.csv and IT ready to install

**Comment by h3o66** [comment]
> [dev-debug.log](https://github.com/user-attachments/files/17174517/dev-debug.log)
> 
> Manulally add serverlist.csv and server ready to install

according to the log it timed out to download the file:

```
+ echo -en 'fetching GitHub serverlist.csv...\c'
++ curl --connect-timeout 3 -s --fail -L -o /home/arkserver/lgsm/data/serverlist.csv https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/v24.3.0/lgsm/data/serverlist.csv
+ curlcmd=
+ local exitcode=28
```

curl exit code 28:
`28     Operation timeout. The specified time-out period was reached according to the conditions.`

I dont think that here is a lgsm issue.

**Comment by rAmfu** [comment]
Isn't 3 seconds too little to download a file?

**Comment by h3o66** [comment]
> Isn't 3 seconds too little to download a file?

well, that is only the inital connection timeout, so i assume the connection takes to long to be done to the remote host or other issues.

Feel free to check the curl man to check what that option does.

**Comment by rAmfu** [comment]
About half a year ago I installed a server for paworld and there it downloaded this file without any problems and updated linuxgsm. The server for pal Word is on the same machine where the server ark

**Comment by h3o66** [comment]
maybe you want to check what is going on manually and see what i going on with:

`time curl -v --fail -L https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/v24.3.0/lgsm/data/serverlist.csv`

Then you can check where it takes a long time and check you system and connection.

Closed for now as I do not see this as a general issue with LGSM

**Comment by prestonzen** [comment]
changed this to 10 seconds and it fixed the issue

curlcmd=$(curl --connect-timeout 10 -s --fail -L -o "${local_filedir}/${local_filename}" "${fileurl}" 2>&1)

**Comment by rAmfu** [comment]
> changed this to 10 seconds and it fixed the issue
> 
> curlcmd=$(curl --connect-timeout 10 -s --fail -L -o "${local_filedir}/${local_filename}" "${fileurl}" 2>&1)
> 
> nano -Sl pwserver
> 
> Line 114

Thank you this resolve my problem 🤜🤛

**Comment by redplcs** [comment]
Thanks! Setting `--connect-timeout` to 10 fixed my issue
