### ISSUE TITLE
[Bug]: YFS name of the server 

### ISSUE THREAD

**Issue by mayersgamer** [GameServerManagers/LinuxGSM#4685]
### User story

i have changed the name of the server in server.cfg amd cs2server.cfg but this random name keeps apearing , let you know im hosting 2 servers with diffrent username and diffrent files , the first server works fine bit the second always getting this 3 letters as the name of the server

### Game

counter-strike 2

### Linux distro

Ubuntu 22.04

### Command

command: details

### Further information

![Screenshot 2024-10-19 061152](https://github.com/user-attachments/assets/166f5253-b1b9-42e6-9db3-8e41ae7bcb45)

you can see here both servers 

### Steps to reproduce

just every map change this have a chance of 50% to be produced

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
