### ISSUE TITLE
[Bug]: Factorio server updates when already up to date

### ISSUE THREAD

**Issue by Amlinde** [GameServerManagers/LinuxGSM#4687]
### User story

Due to interpreting the version incorrectly, the `update` command always thinks factorio is out of date. This has been causing the server to restart whenever it is run, which, in the case of the container version I'm using, is every hour by default.

### Game

Factorio

### Linux distro

Ubuntu 22.04

### Command

command: update

### Further information

Pre 2.0, the `--version` command output was formatted like this:
```
Version: 1.1.110 (build 62357, linux64, headless)
Binary version: 64
Map input version: 0.18.0-0
Map output version: 1.1.110-0
```

With the 2.0 update it is now formatted like this:
```
Version: 2.0.8 (build 79416, linux64, headless)
Version: 64
Map input version: 1.0.0-0
Map output version: 2.0.8-1
```

This causes LinuxGSM to interpret the version as
```
2.0.8
64
```
instead of `2.0.8`

**Comment by skwasjer** [comment]
I think this also causes malformed JSON when sending (in my case) Discord hook, due to the LF control character:

```

[ .... ] Updating fctrserver: Sending Discord alertparse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 28, column 4
[ FAIL ] Updating fctrserver: Sending Discord alert: {"message": "The request body contains invalid JSON.", "code": 50109}
```

**Comment by Whalios** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by skwasjer** [comment]
I can confirm that with the latest hotfix from #4688 the Discord alert also works again.
