### ISSUE TITLE
[Bug]: Local build != Remote build for Factorio, this makes LGSM think there is an update available while there isn't due to mismatching local build/remote build information.

### ISSUE THREAD

**Issue by FSynchro** [GameServerManagers/LinuxGSM#4690]
### User story

As a LGSM user, I want ./fctrserver cu to compare the local version to the remote version properly.

### Game

Many, but in this case it's Factorio (2.*)

### Linux distro

Other

### Command

command: update

### Further information

./fctrserver cu
[  OK  ] Check for Update fctrserver: Checking for update: factorio.com

Update available
* Local build: 2.0.9
64 linux64
* Remote build: 2.0.9 linux64
* Branch: stable

When installing the update, * Remote build: 2.0.9 linux64 will turn into: * Local build: 2.0.9
64 linux64

In LGSM the code seems to be:

if Local build != Remote build then
 Update Available!
 
 

My own workaround is to just look at the version number and leave out the build information after that.

### Relevant log output

```shell
Not applicable
```

### Steps to reproduce

do ./fctrserver update

then do ./fctrserver cu

Or run ./fctrserver update again.

Wanna get stuck in an update loop?

Set UpdateOnStart=True and watch LGSM spin updates to eternity.

**Comment by FSynchro** [comment]
Fyi this behaviour has been persistent since the new Factorio DLC, so 2.0.3 and 2.0.6 and 2.0.9 displayed the same behaviour.

**Comment by vkyrasa** [comment]
See #4688, its an issue with how LGSM parses the version number from the factorio server binary.

**Comment by FSynchro** [comment]
Ah that makes complete sense, suppose I'll just have to await that merge.

**Comment by PlayMTL** [comment]
Seems like a dup of https://github.com/GameServerManagers/LinuxGSM/issues/4687
