### ISSUE TITLE
[arkserver] update command doesn't work

### ISSUE THREAD

**Issue by ctmlr** [GameServerManagers/LinuxGSM#474]
I knew there was an update available so I tried "./arkserver update" which returned,

```
No update available:
    Current version: 744093
    Available version: 744093
    https://steamdb.info/app/376030/
```

So then I used the "force-update" command which did update the server. After updating I ran the script with the "update" command again and got,

```
No update available:
    Current version: 750786
    Available version: 750786
    https://steamdb.info/app/376030/
```

So it doesn't seem to properly detect when a new version is available.

**Comment by Kugane** [comment]
on my server it works perfect, use it all 30min for autoupdate ;)

**Comment by zeroZshadow** [comment]
I have the same issue with gmod, it would say there is no update available, but force-update will fix it.

**Comment by sergey-k1** [comment]
Hi.
I use Ubuntu 64 bit.
uname -a
Linux SKYNET 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
If i try to update(cron or manual)
/tf2/tf2server update
[  OK  ] Update tf2-server: Checking for update: SteamCMD

No update available:
        Current version: 789049
        Available version: 789049
        https://steamdb.info/app/232250/

[  OK  ] Update tf2-server: No update available

But I knew there was an update available.
If i give the command manually
/tf2/tf2server force-update
update is successful

**Comment by sergey-k1** [comment]
I solved this problem using a utility Expect [link to Expect](https://en.wikipedia.org/wiki/Expect) to get the available version number

In Ubuntu Server 14.04 64bit
Add packages
sudo apt-get install expect tofrodos

get_version.sh

#!/usr/bin/expect -f
set timeout 60
spawn "/tf2/steamcmd/steamcmd.sh"

while 1 { expect {
        "Steam>" {break}
        timeout {send_user "Response wait time is up.\r"; exit 2}
}}
sleep 5
send "login anonymous\r"
while 1 { expect {
        "Steam>" {break}
        timeout {send_user "Response wait time is up.\r"; exit 2}
}}
sleep 5
send "app_info_update 1\r"
while 1 { expect {
        "Steam>" {break}
        timeout {send_user "Response wait time is up.\r"; exit 2}
}}
sleep 5
send "app_info_print 232250\r"
while 1 { expect {
        "Steam>" {break}
        timeout {send_user "Response wait time is up.\r"; exit 2}
}}
send "quit\r"


cron_update_tf2.sh

#!/bin/bash
...

sudo -i -u tf2server /home/user/tf2update/get_version.sh > /home/user/tf2update/steam.out

#_change line endings CRLF -> LF
/usr/bin/fromdos /home/user/tf2update/steam.out

#_get available version number
availablebuild=$(cat /home/user/tf2update/steam.out | grep -EA 1000 "^\s+\"branches\"$" | grep -EA 5 "^\s+\"public\"$" | grep -m 1 -EB 10 "^\s+}$" | grep -E "^\s+\"buildid\"\s+" | tr '[:blank:]"' ' ' | tr -s ' ' | cut -d\  -f3)

...

**Comment by dreamrae** [comment]
Is this client caching the information? If so, is there a way to clear the cache?

**Comment by sergey-k1** [comment]
I found the reason that there is no update.
You must edit the file fn_update_check
replace line
#_Removes appinfo.vdf as a fix for not always getting up to date version info from SteamCMD

if [ -f "${rootdir}/Steam/appcache/appinfo.vdf" ]; then
	rm -f "${rootdir}/Steam/appcache/appinfo.vdf"
fi

These strings.


if [ -f "${HOME}/Steam/appcache/appinfo.vdf" ]; then
	rm -f "${HOME}/Steam/appcache/appinfo.vdf"
fi

if [ -f "${rootdir}/steamcmd/appcache/appinfo.vdf" ]; then
	rm -f "${rootdir}/steamcmd/appcache/appinfo.vdf"
fi
