### ISSUE TITLE
Steam login failure with correct credentials

### ISSUE THREAD

**Issue by Sonic4Spuds** [GameServerManagers/LinuxGSM#476]
I have been trying to install Starbound with the script, and it is failing the login even though I have made sure the correct credentials are setup in the script.

**Comment by Scarsz** [comment]
Have you edited your version of the script at all besides the username/password variables? The script from what I can tell should be working fine. Also, does the password contain any symbols?

**Comment by Sonic4Spuds** [comment]
No I didn't edit the script at all, and yes it does contain symbols.

**Comment by Scarsz** [comment]
That's probably the problem then. If you have symbols that need to be escaped, be sure to do that. I personally would just make the password alphanumerical.

**Comment by Sonic4Spuds** [comment]
That's a pretty big issue for a script such as this, seeing as you are basically asking people to ignore all security best practices. It would be helpful for you to at least note that you have to do that in the documentation.

**Comment by Scarsz** [comment]
That's just a common issue with shell and loading variables from a file; symbols have to be escaped correctly or else it throws it off. We don't encourage you to use your main Steam account for this script, either, it should just be a throwaway one made just for downloading; games can be shared to the account from family sharing and they'll be downloadable through there.

**Comment by Sonic4Spuds** [comment]
Ok, but I still think it would be good to note in the documentation. I actually didn't ever think to use family sharing to allow downloading of the server.
