### ISSUE TITLE
Graceful Shutdown for source servers.

### ISSUE THREAD

**Issue by andreblue** [GameServerManagers/LinuxGSM#497]
It would be nice if you could add a graceful shut down for source servers like gmod. 

```
tmux send -t "${servicename}" quit ENTER
sleep 30

```

I added this, which allows the server to finish up things such as mysql connections. I added this right above where it kills off the server's session with the tmux command. If not it can cause some data not to be saved.

**Comment by dgibbs64** [comment]
Could you put in a merge request for this. Make sure though that this will only run for source and gold source servers

**Comment by andreblue** [comment]
Ya, it will run for source and sure. Give me a couple and i will do it.

**Comment by dgibbs64** [comment]
Now merged in to master :D
