### ISSUE TITLE
Error at start : can't create socket: No space left on device

### ISSUE THREAD

**Issue by rboufatis** [GameServerManagers/LinuxGSM#499]
Hello guys, 
I'm trying to start my csgo server, and this error comming : 

csgoserver@**xxxxxxxxx**~$ ./csgoserver start
[ .... ] Starting csgo-server: eTic Servercan't create socket: No space left on device
[ FAIL ] Starting csgo-server: Unable to start eTic Server: Tmux error:
# Command

tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip **xx.xxx.xx.x** -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "
# Error

can't create socket: No space left on device
# Fix

No known fix currently. Please log an issue.
http://gameservermanagers.com/issues

**xxx.xxx.xxx.xx *_was my IP 
*_xxxxxx** The name of my server
After my 2 hours of google search i'm decide to follow the instruction of error : Please log an issue ;).

PS : I'm trying to install that on Kimsufi server.

If you have any ideas... I'm ready to listen ;p 

Good day.

**Comment by ScottSmudger** [comment]
"can't create socket: No space left on device"

You've ran out of storage on the server.

**Comment by dgibbs64** [comment]
@ScottSmudger you would think that but I have previously seen this and low disk space was not the problem....its a great error message haha.

**Comment by ScottSmudger** [comment]
Then it must be a mounting issue... Probably need to check with the provider -__-

**Comment by dgibbs64** [comment]
Previous related issue https://github.com/dgibbs64/linuxgsm/issues/420

**Comment by dgibbs64** [comment]
Please can you confirm if you fixed this and how it was resolved. Then I should be able to add the fix in to the error log

**Comment by UltimateByte** [comment]
Could also be a write protection right issue. 
No answer for 1 month, closing.
