### ISSUE TITLE
[CSGO] Servers need to be registered

### ISSUE THREAD

**Issue by zaggash** [GameServerManagers/LinuxGSM#531]
Anonymous login will be disabled.
Server need to be linked to a User account :
http://steamcommunity.com/dev/managegameservers

See : http://blog.counter-strike.net/index.php/category/updates/
[ DEDICATED SERVERS ]
– Added concommand sv_setsteamaccount to specify Game Server Login Token. To create a GSLT go to
http://steamcommunity.com/dev/managegameservers

**Comment by ryam4u** [comment]
how it is used?

**Comment by dgibbs64** [comment]
I will be adding this in soon :-)

**Comment by dgibbs64** [comment]
https://github.com/dgibbs64/linuxgsm/commit/8ee871452ec8a0721f36be7044dcc151388e8bdb
