### ISSUE TITLE
[CSGO] "Curl is not installed!" - Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by wolfcry0** [GameServerManagers/LinuxGSM#552]
Hello, I'm trying to use the CS:GO server script on an Ubuntu 14.04 x64 install.

```
csgoserver@brick:~$ which curl
/usr/bin/curl
csgoserver@brick:~$ curl
curl: try 'curl --help' or 'curl --manual' for more information
csgoserver@brick:~$ ./csgoserver install
    fetching functions/fn_functions...FAIL

Curl is not installed!
```

**Comment by dgibbs64** [comment]
Fixing this now

**Comment by dgibbs64** [comment]
just uploaded an updated csgoserver. Please test and let me know. Thanks

**Comment by wolfcry0** [comment]
Looks good, thanks so much for the quick response!

**Comment by Tridzs** [comment]
Still having the issue "fetching functions/fn_functions...FAIL"

**Comment by fuckpaypal** [comment]
Same problem in Black Mesa, not fixed.

**Comment by UltimateByte** [comment]
Just tested on Debian 8 x64 updated, it's working.
@fuckpaypal Do you actually have curl installed ?

@dgibbs64 Could you please add curl as a requirement on game server pages when you got time ?
It's not present at least on CS GO and Black Mesa DM pages (the only two i checked).

**Comment by dgibbs64** [comment]
@UltimateByte looks like the website didnt update it as I told it too. Should be fixed now :D

**Comment by UltimateByte** [comment]
Perfect, it is :)
