### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by Dunkelzhan** [GameServerManagers/LinuxGSM#562]
Installing 7 Days to Die Server on Ubuntu 15.10 64 bit, fresh build.

Following directions, entering:

 ./sdtdserver install

Returns:

```
fetching functions/fn_install_header...FAIL
```

curl: (23) Failed writing body (0 != 497)
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/fn_install_header

Am I missing something somewhere?

**Comment by dgibbs64** [comment]
hmmm some find of bug with curl. I will need to look in to this.

**Comment by dgibbs64** [comment]
Try this instead let me know what errors your get...if any.

https://gist.githubusercontent.com/dgibbs64/558b400b4cad272bffd7/raw/cc9e557f8258dc316d3657b511f883ae14867b01/sdtdserver

**Comment by Dunkelzhan** [comment]
Sorry, very much a newb here to Linux - I am assuming I am just putting this into the sdtdserver file somewhere?

**Comment by dgibbs64** [comment]
wget https://gist.githubusercontent.com/dgibbs64/558b400b4cad272bffd7/raw/cc9e557f8258dc316d3657b511f883ae14867b01/sdtdserver

just download this instead of the original.

**Comment by Dunkelzhan** [comment]
Gotcha, thanks.  Now I am getting:

fetching functions/fn_install_header...FAIL

		  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/ladmin/functions/fn_install_header: 
Warning: Permission denied
curl: (23) Failed writing body (0 != 497)
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/fn_install_header

I am assuming I don't have permissions set correctly on my home folder somehow?

**Comment by Dunkelzhan** [comment]
Additional:  Just noticed the "ladmin" in the path, that's the admin account for the machine.  I created a "sdtdserver" account as described in the instructions, and ran the wget command from the sdtdserver account.  I don't know if that makes a difference or not.

**Comment by dgibbs64** [comment]
Yeah looks like a permissions issue to me. creating a user sdtdserver is the recommended way to do it. Hopfully that resolves your issue

**Comment by Dunkelzhan** [comment]
To confirm, I did create the sdtduser account, and ran all the instructions under it when i tried everything above.  I added the account to the sudo group - is there something else I should add it to for permissions to function correctly?

**Comment by Dunkelzhan** [comment]
Figured it out - removing the sdtdserver user, rebuilding, and running the wget command again fixed the issue.  Thank you.
