### ISSUE TITLE
[LGSM] Re work notification feature

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#566]
The notification feature is pretty basic and has some bugs. It requires re working. I would like re do the email notification and also add pushbullet support as well.

This will also resolve issues #472 and #394
- more reliable and improved email feature
- email on update
- pushbullet support

**Comment by UltimateByte** [comment]
Don't forget this https://github.com/dgibbs64/linuxgsm/issues/404

**Comment by dgibbs64** [comment]
For now I will ensure that the email feature is working correctly. Then revisit this as I have some good ideas about this. e.g pushbullet support

**Comment by dgibbs64** [comment]
Working on this now. First stage is to get the existing email system working better as its a little broken. I definitely want to do as @jaredballou suggested with ANSI to HTML to hopefully create a pretty email option. However first things first. Stable text based email. I will probably move to other higher priority features/bugs first then revisit this at a later date.

**Comment by dgibbs64** [comment]
Basic improvements now present. However still more to do.

**Comment by dgibbs64** [comment]
Push bullet support added now and improvements to the email feature now in place. A HTML email feature would be good however not going to be a priority currently.

**Comment by dgibbs64** [comment]
#1321
