### ISSUE TITLE
[LGSM] Get Steam Guard working correctly

### ISSUE THREAD

**Issue by Dunkelzhan** [GameServerManagers/LinuxGSM#570]
When running: 

./sdtdserver install

I eventually reach a point where the install hangs:
# Installing SteamCMD

SteamCMD already installed!
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'REMOVED USERNAME' to Steam Public...
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:FB8YB
Logged in OK
Waiting for license info...OK
# Installing 7 Days To Die Server

Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'REMOVED USERNAME' to Steam Public...
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:FB8YB

Where 'REMOVED USERNAME' is my correct Steam account.  Steam Guard appears to authenticate correctly at the first query when installing Steam CMD, but the install hangs at a flashing cursor at the second prompt (yes, the Steam Guard code at the time was the same for both prompts).  

This was my 2nd attempt at installing, hence the initial messages w/ the Steam CMD installation.

**Comment by UltimateByte** [comment]
Hi there,
I know that pain, i also got trouble with steamguard in the past, i disabled it for those kind of things, but now it becomes pretty compulsory to enable it if you're using the market, so let's try to figure out what's happening. Sadly, i don't own that game, so i won't be able to test that.

The fact that you got 2 times the same two factor code could either be a problem or a normal behavior, as it's the same machine requesting authentication in a small amount of time.

Firsts things first, i see SteamCMD already installed! at the very beginning, so did you start for a clean install ? (_ls -al_ to make sure there are no residual files). 

The only thing i see right now is the password included into start options that could prevent steamguard from working. If so, we're gonna need an option for steamguard in server script, like 
__steamguard="1"__

Then at install,
__if [ "${steamguard}" == 1 ]; then
unset steampass
fi__


So let's try clearing all files (if you have a dedicated user, go to its home folder, and do _rm -R *_ , then _ls -al_ to check if you need to remove more), then if it doesn't do the trick, or if you were already on a clean install, we will see what we can do.

**Comment by Dunkelzhan** [comment]
Thank you for the reply.

Yes, I started with a clean install - I got the hang issue on my very first attempt.  Subsequent attempts I tried running the install over what was already in the folder.

I apologize as I am a linux novice and I am not really following what you are saying - what files do i need to clean out of what folder?  

I also added the "steamguard="1" to the server script, immediately below the username / password section - was that where I was supposed to add it?

As for your "Then at install" section, I am unsure if I need to add this to the server script, and if so, where?

**Comment by Dunkelzhan** [comment]
Sorry for my lack of experience - I figured out your above post.  For the sake of anyone as inexperienced w/ Linux as me, here is the steps I took to fix the issue (this is for Ubuntu 15.10 64-bit):

1.) Remove the "sdtdserver" user using the User Accounts application.  Say yes to delete all files.
2.) Reboot.
3.) Create the "sdtdserver" user again, using the User Accounts application.  Make as an admin, and add a password.
4.) Follow the instructions for the server install.  At the "nano sdtdserver" step, make the following changes:
  a.) Add your Steam username and password where indicated.
  b.) Immediately below the password line, add steamguard="1"
  c.) Scroll down and find the ##### Script ##### section (ignore the  # Do not edit).
  d.) Below the filedir=$(dirname "${filepath}") line, add:
      if [ "${steamguard}" == 1 ]; then
      unset steampass
      fi
  e.) Exit and save changes, then run ./sdtdserver install - have your Steam Guard code ready.

Worked for me - thank you for the assistance!

**Comment by UltimateByte** [comment]
Glad you figured it out.

Actually the steamguard thing was a feature to propose for LGSM, not something you had to do yourself !

The easiest way may be to not enter a steampass ! It does exactly the same as the function i gave in the end. If it works that way, we can just add a comment to tell people not to use a steampass when steamguard is on, then you have to type your password manually.
I personally don't like having a password in clear text anyways.

**Comment by dgibbs64** [comment]
Yeah this is definitely something that needs to be worked on. I added ./steamcmd.sh without any redirect to force steamguard to show if required. Then I thought is was simply a case of entering the code and thats it.

**Comment by Dunkelzhan** [comment]
If I comment out the steamguard="1" line and then leave the:

if [ "${steamguard}" == 1 ]; then
unset steampass
fi

lines, the server hangs anytime it tried to update SteamCMD.  It will query for a steamguard code, seem to accept it, look for the license, return an ok, then hang at the 

Update sdtd-server: Checking for update: SteamCMD

line. (note - i have the server configured to update on start).  Just FYI.

**Comment by UltimateByte** [comment]
OFC it gest stuck if you keep a test on a non existing variable.
What about you remove that and just don't set a steampass ?
I guess there are some checks at instal to seel if steampass is set or not, not sure what it'll do, but you can try.

**Comment by Dunkelzhan** [comment]
Sorry for the delay in replying, hope everyone had happy holidays.

I had some progress this morning.  Edited "sdtdserver" script so now:

 # Steam login
steamuser="(my account)"
# steampass="(my password)"
# steamguard="1"

and 

# if [ "${steamguard}" == 1 ]; then
# unset steampass
# fi

where (my account) and (my password) are correct values.  

when running "./sdtdserver update" it queries for password, then Steam Guard code, pauses at the updating SteamCMD message, then passes and finds an available update:  

sdtdserver@WolfeDen1:~$ ./sdtdserver update
[  OK  ] Update sdtd-server: Checking for update: Server logs: No update requestedRedirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user '(my account)' to Steam Public...
Using cached credentials. . .
Logged in OK
Waiting for license info...OK
[  OK  ] Update sdtd-server: Checking for update: SteamCMD

Update available:
	Current build: 909215
	Available build: 912598

	https://steamdb.info/app/294420/

Applying update...
    fetching functions/fn_update_dl...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/fn_update_dl

Dumps out here, with the 404 error.

**Comment by dgibbs64** [comment]
./sdtdserver update-functions

**Comment by Dunkelzhan** [comment]
./sdtdserver update-functions

Returns:

    fetching functions/fn_update_functions...FAIL

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/fn_update_functions

**Comment by dgibbs64** [comment]
Try again now ;-)

**Comment by Dunkelzhan** [comment]
That worked.  Now I'm getting a "Login Failure: Invalid Password" when it uses my cached credentials, and the update dumps out - how do I clear my credentials out of the cache?

**Comment by dgibbs64** [comment]
I would deleted the steamcmd dir myself. This is a right pain at the moment

**Comment by Dunkelzhan** [comment]
Removing the directory, then trying to run ./sdtdserver gave me an error, saying it couldn't find commands in that directory. I assumed I needed to re-install to rebuild the steamcmd directory correctly... I backed up my installation, which finished successfully, then ran ./sdtdserver install.

The install also is trying to use the cached credentials...  so I suppose they are stored somewhere other than the steamcmd directory?  I confirmed this directory did not exist after deleting it.

**Comment by dgibbs64** [comment]
the script should detect if steamcmd dir is missing and reload it for you

**Comment by Dunkelzhan** [comment]
I removed "steamcmd" folder with "rm -R steamcmd", confirmed folder was gone.

Ran "./sdtdserver start, SteamCMD detected as missing and installed:

sdtdserver@WolfeDen1:~$ ./sdtdserver start
[ WARN ] Starting sdtd-server: SteamCMD is missing
mkdir: created directory ‘/home/sdtdserver/steamcmd’
downloading steamcmd_linux.tar.gz...OK
linux32/
linux32/libstdc++.so.6
linux32/steamcmd
steamcmd.sh
steam.sh
removed ‘/home/sdtdserver/steamcmd/steamcmd_linux.tar.gz’

Then ran "./sdtdserver update":

sdtdserver@WolfeDen1:~$ ./sdtdserver update
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[  0%] Downloading update (0 of 10,335 KB)...
[  0%] Downloading update (272 of 10,335 KB)...
[  2%] Downloading update (2,887 of 10,335 KB)...
[ 27%] Downloading update (5,278 of 10,335 KB)...
[ 51%] Downloading update (7,396 of 10,335 KB)...
[ 71%] Downloading update (9,206 of 10,335 KB)...
[ 89%] Downloading update (10,335 of 10,335 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 7,179 KB)...
[  0%] Downloading update (996 of 7,179 KB)...
[ 13%] Downloading update (2,787 of 7,179 KB)...
[ 38%] Downloading update (3,842 of 7,179 KB)...
[ 53%] Downloading update (4,911 of 7,179 KB)...
[ 68%] Downloading update (5,969 of 7,179 KB)...
[ 83%] Downloading update (6,923 of 7,179 KB)...
[ 96%] Downloading update (7,179 of 7,179 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steam...
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'REMOVED USERNAME' to Steam Public...
Using cached credentials. . .
Login Failure: Invalid Password 
FAILED with result code 5
Failure! Error running SteamCMD
[ FAIL ] Update sdtd-server: Checking for update: SteamCMD: Not returning version info

Whereas "REMOVED USERNAME" is my correct account.  No changes were made to sdtdserver file.  So like I was saying, credentials have to be stored somewhere other than the SteamCMD folder, right?

**Comment by dgibbs64** [comment]
Im closing this issue now and merging with #579
