### ISSUE TITLE
Email Notification capability broken on Teamspeak 3.

### ISSUE THREAD

**Issue by pandabear41** [GameServerManagers/LinuxGSM#581]
As simple as that. The function to send email notifications was removed. The email-test works but when you call monitor and the server is down I get. This only occurs on the TS3 manager - I see that this was first introduced in 6e3ba0e75884e0afa3548299d470e3225d59c97d

> ~/functions/fn_monitor: line 48: fn_emailnotification: command not found

Doing a simple search in all the files on the repo, I found that fn_emailnotification is never defined.

> Searching 179 files for "fn_emailnotification" (whole word)
> 
> C:\linuxgsm-master\linuxgsm-master\functions\fn_monitor:
>   46          subject="${servicename} Monitor - Restarting ${servername}"
>   47          actiontaken="restarted ${servername}"
>   48:         fn_emailnotification
>   49      fi
>   50  fi
> 
> 1 match in 1 file

**Comment by pandabear41** [comment]
Just wrote a simple fix and tested it. 
Pull Request: #582

**Comment by dgibbs64** [comment]
Thanks for this. Closing as fixed :)
