### ISSUE TITLE
[ts3server] mariadb for ubuntu

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#583]
Specific instructions for installing mariadb need to be added to the wiki so users can follow this for ubuntu centos and debian.

I have also bypassed new code for auto-install for now. auto-install will not be possible with mariadb currently.

**Comment by jaredballou** [comment]
What's the problem, MariaDB should be a drop-in replacement. Do we just need to update package names, or is there something bigger broken here?

**Comment by dgibbs64** [comment]
You need to enter a database name username and password. Like setup of a mysql database. So its not a drop in replacement.

**Comment by UltimateByte** [comment]
@dgibbs64 Is that enough ?
https://github.com/GameServerManagers/LinuxGSM/wiki/TeamSpeak#teamspeaks-database-and-mariadb

**Comment by UltimateByte** [comment]
Updated link
https://github.com/GameServerManagers/LinuxGSM/wiki/TeamSpeak-3#database-and-mariadb

Considering this is solved.
