### ISSUE TITLE
[LGSM] Skeleton directory

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#585]
An idea that I like is from an issue raised a long while ago #185. Which was the ability for a user to create there own skeleton directory that could be copied post install allowing them to deploy there custom scripts and configs right away. I already do this with my nmrih servers mainly as a backup. I have all my custom files in a bitbucket repo that I just download when required. This would be great for speeding up deployment of servers and backing up of configs/custom files that differ from the vanilla install.

**Comment by JimTR** [comment]
You could also just deploy (install) a game to a directory and just symlink the contents  to a user via a script ... this does give some permission problems (who updates the original install and has the user got the correct privs to the directory) however with my web thing I have done symlinks  & a root cron to make sure the game is up to date in the skeleton.. this does need some core function editing as (I guess) we are all aware that LGSM will not allow you to 'run as root' ... after 2 months of testing with this I have found that if the game coder adds an extra file to a directory symlinking the directory fails (ubuntu 14.04)  and you need to run update or validate as the user

**Comment by jaredballou** [comment]
This is an interesting idea, maybe something like this:
User downloads script
User runs install
Before installation happens, user is asked if they want us to drop a template skeleton directory
If so, create the structure in ~/templates/$GAME/ that mirrors the install directory structure
Users put their own custom content into the template (support ZIP/BZIP or just flat files?)
User runs install again, continues as normal, and after game is installed rsync or symlink the files from template to the installed directory
Maybe make the symlink or rsync choice a user controlled option (or even have ~/templates/$GAME/symlink and rsync folders to sllow both), so they can share files among installs but also allow customization once they get deployed?
Do we need to have a "refresh" feature, so if I update my skeleton plugins I can deploy the changes to all my servers by the script?

**Comment by UltimateByte** [comment]
I'm so motivated adding support for custom modules, more and more reasons to do it !
We would define some standard variables and file structure to use, so that you can use commands directly from the game script... We could also add an "lgsm-extensions" to include them all. Some could be auto-downloaded from the github lgsm main repository, and some could be coded and added by the user himself. That would definitely take things to the next level i guess.

**Comment by JimTR** [comment]
<quote Ulitmatebyte> some could be coded and added by the user himself.</quote> = sexist :) but on a serious note I am working on a script (ran by Root) that uses LSGM validation to the skel install ...  further cron jobs (per user) updates the user install (  writing symlinks etc ) but I guess this is a project on its own

**Comment by UltimateByte** [comment]
@JimTR It's a project for deploying a massive amount of servers, but i like it. The native skeleton thing could allow an easier use of your kind of script.

**Comment by UltimateByte** [comment]
BTW, for example, what kind of functions would you need to run your custom scripts @JimTR  ?
Bypass echoing/wait/display functions ? Then... ? Being able to run additional functions, change variables ?

**Comment by dgibbs64** [comment]
OK for for this I think it should do two things. firstly generate a skeleton dir by simply copying all directory's empty to a skeleton dir. plus also have the ability to copy the skeleton directory to serverfiles and lgsm configs as well. It wont automate everything but it will help

**Comment by dgibbs64** [comment]
new command recommended `./gameserver skeleton` that will replicate all directories but be empty.

another command `./gameserver skeleton-copy` to use git to download files from a git repo

**Comment by dgibbs64** [comment]
for reference 
```
find . -type d | cpio -pdvm skel
```
