### ISSUE TITLE
[LGSM] Ideas for better user feedback

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#586]
I would like it to be easier for users to be able to feedback more useful info when submitting issues to hopefully speed up fixes and help users with problems. Normally we ask for the output of ./csgoserver details which is useful and does already help. But having somethings like a dedicated command to output logs and details.

A new command called ./csgoserver dev-debug is proving very useful already so maybe some sort of intergration with that

**Comment by UltimateByte** [comment]
Sound good.
The only thing more is that it would make a txt file for that purpose ?
Maybe it could give more info ?
Like Firewall open ports (maybe too intrusive), Free RAM, Free Diskspace, Details, and the 2 last server logs ?

What about a script to upload it to something like pastebin (if they got an API for that), and provide a link to share directly on github ?

**Comment by jaredballou** [comment]
This is a really good idea. If we can get a listing of the info you need (or the steps you have users perform to gather data) I can try to throw something together for that. Pastebin does seem to have an API with decent docs, so it shouldn't be too hard to get something going there. We could always just email it, but then we have to have an email account that will have limited access. My thinking is the Pastebin with a link displayed in the console output for the user to copy would be the way to go.

**Comment by UltimateByte** [comment]
Doc : http://pastebin.com/api

**Comment by UltimateByte** [comment]
Interesting thoughts about this https://github.com/dgibbs64/linuxgsm/issues/625

**Comment by UltimateByte** [comment]
Related : https://github.com/GameServerManagers/LinuxGSM/issues/1001

**Comment by UltimateByte** [comment]
Maybe we could add a postlogs command as well. 

A simple function working this way:
```
for directories in dir "logs"
find latest file
upload it to hastebin
provide link to console
done
```

**Comment by dgibbs64** [comment]
post details not does this.
