### ISSUE TITLE
[mumbleserver] if get permission denied fix

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#591]
/home/admin/lgsm/mumbleserver/functions/command_debug.sh: line 66: ./murmur.x86: Permission denied

When testing mumbleserver get this error. Probably becuase I used rsync. so simple fix is for script to chmod +x the file

**Comment by UltimateByte** [comment]
Isn't there a check to `chmod +x "${executabledir}/${executable}"` now ?

**Comment by UltimateByte** [comment]
Wow, there isn't !
Will do it !

**Comment by UltimateByte** [comment]
Well, i'm getting issues since ${executable} is under the form of ./executable_name which is quite annoying. I could maybe strip ./ if it's detected into the variable, but you know my love for sed...

**Comment by UltimateByte** [comment]
I used awk, but this way is much more elegant

**Comment by UltimateByte** [comment]
Well, fixed in devbranch.
https://github.com/GameServerManagers/LinuxGSM/blob/development/lgsm/functions/check_permissions.sh#L84
