### ISSUE TITLE
[Server Request] Unreal Tournament 3

### ISSUE THREAD

**Issue by DJSGXII** [GameServerManagers/LinuxGSM#595]
Would it be possible to make a Unreal Tournament 3 Script?
I would be very pleased if you could make it.

**Comment by UltimateByte** [comment]
Can you confirm that there is a linux server for UT3 ? I'd be glad to work on it when i got home (holidays), i love that game :)

**Comment by DJSGXII** [comment]
Yes there is!
FYI:
1) https://forums.epicgames.com/threads/599751-How-to-set-up-a-Linux-Dedicated-Server
2) http://www.fragme.info/content/cracked-ut3-dedicated-server-linux
3) https://unrealbyfusilade.wordpress.com/unreal-development-tutorials/unreal-tournament-games/ut3-specific/unreal-tournament-3-server-installation-guide/

I tried installing it myself and got it working. Only problem is that it is not showing up in de server list.

**Comment by UltimateByte** [comment]
Ok, cool ! Let me a few days to go back home and i'll see if i think it's feasible. Then we're gonna see if we can set this up with master dgibbs64 :)

**Comment by UltimateByte** [comment]
Well, i can't find any relyable source to download the server in the links you provided. Plus with the close of this crappy gamespy we're gonna have some trouble.
What about Unreal Tournament Pre Alpha ? Seems like a better UT, and free to play.

**Comment by DJSGXII** [comment]
Yeah but that one isn't finished yet and has no vehicles in it.. :(

**Comment by UltimateByte** [comment]
Do we have a relyable way to at least download the server ?

**Comment by dgibbs64** [comment]
https://github.com/GameServerManagers/LinuxGSM/pull/1123 now released
