### ISSUE TITLE
[Server Request] Darkest Hour

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#604]
https://steamdb.info/app/1290/

Darkest hour a Red Orchestra mod has had a major update recently and has its own dedicated server app in steam. Should be quite easy to convert the roserver script to work with darkest hour

**Comment by UltimateByte** [comment]
That game ?
http://store.steampowered.com/app/1280/
"1 friend has played this game" lol :o))
Seems cool though.

**Comment by dgibbs64** [comment]
Yeah it would be a low priority server

**Comment by dgibbs64** [comment]
Moving this to development queue to investigate.

**Comment by dgibbs64** [comment]
https://github.com/DarklightGames/DarkestHour/wiki/Dedicated-Server-Installation

**Comment by dgibbs64** [comment]
There are complications with installing this server and getting no subscription errors. Since this is a low demand server I will not pursue this further.
