### ISSUE TITLE
Arma3 Epoch

### ISSUE THREAD

**Issue by dayzciv** [GameServerManagers/LinuxGSM#620]
I have had a lot of difficulty with Arma3 Epoch on Linux.  Multiple tries, it never seems to function.  It would be awesome to have an a3epoch script in your library!!!

**Comment by UltimateByte** [comment]
For now, LGSM don't support custom server mods.
Once again, it's something that my be supported by a skeleton directory that would allow optional features such as supporting mods. https://github.com/dgibbs64/linuxgsm/issues/585
Such a feature is only at the state of "idea" for now, but it could definately happen one day.


For now, did you follow this guide ?
https://github.com/denisio/Arma3-Epoch-Linux-Server

**Comment by dayzciv** [comment]
I tried.  3 times, on Debian Wheezy AND Jessie.  Step by step, all prerequisites installed properly.  No dice..  It just appears Epoch is not all that Linux-friendly, and I'll be having snowball fights in hell before I move over to Windows server on my dedicated boxes  ;)

There *has* to be a way to make it work, unfortunately it does not.  I even had the owner of an (unnamed) GSP give it a shot to no avail, unfortunately.  This is a VERY popular ArmA mod; just the installation is ridiculous...

**Comment by UltimateByte** [comment]
"I'll be having snowball fights in hell before I move over to Windows server on my dedicated boxes"
Haha, same here... That's why i don't have a Rust server... Maybe i'll try making it with Wine one day...

BTW, sadly, i guess your chances of finding an admin using Epoch here are pretty low.
Did you already post somewhere into the epoch community ?

**Comment by PhilPhonic** [comment]
I had an A3 Epoch server running, some months ago, it definately was a pain in the ass to get it running. but i can assure you: it does work.
do you have any logs / errors for me?

**Comment by dgibbs64** [comment]
Is there any demand for this still? Placing in Waiting Response will close in 30 days if no feedback
