### ISSUE TITLE
Half life 1 mod server scripts needs doing (vampire slayer, brainbread 1)

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#623]
Hello,

I am requesting that it would be great to have server scripts for the old half life 1 mods, so it makes it easy to create a dedicated server on linux.

the following to need made is BrainBread 1 server script

You can find the files located here

https://onedrive.live.com/redir?resid=1ECCE187A697D127!4869&authkey=!AM60C6dHj8Q-i-E&ithint=file%2cgz - linux server files

The fix to the server launching is below:

A bug in the latest version of HLDS for Linux causes some mods to crash on startup. To fix your BrainBread server you can simply rename the file "bb_i386.so" in the "dlls" directory of BrainBread to "bb.so".

To make sure you should also adapt your "liblist.gam" file accordingly.

The full error looks something like this:
LoadLibrary failed on "":
    cannot open shared object file: No such file or directory
Host_Error: Couldn't get DLL API from ""!
FATAL ERROR (shutting down): Host_Error: Couldn't get DLL API from ""!
The same workaround can be applied to Public-Enemy as well.

**Comment by UltimateByte** [comment]
Hello,

The link you provided, does it work as is ? Or does it need HL1, and that's what you're asking support for ?

**Comment by jamiebatch452** [comment]
I posted this for the main developer of this to create a script since he was busy, and also the link is to the mod, and it requires hl1 yes.

**Comment by UltimateByte** [comment]
As there is already support for HL-DM http://gameservermanagers.com/lgsm/hldmserver/ it shouldn't be hard to add support for HL-Dedicated Server which probably works the same way, which i can do.

On the other hand, LGSM doesn't currently support installing mods. But we're thinking in a way to support their installation and update, possibly with this : https://github.com/dgibbs64/linuxgsm/issues/585

Would you be fine with HL-Dedicated Server support by LGSM already ?
Note that if i can do that during next week, dgibbs64 will be out for that week, so we're gonna have to wait for him to merge if my code is accepted.

**Comment by jamiebatch452** [comment]
I have spoken to dgibbs and he is will upon doing the script for this, which why I posted it here since he asked me to.

**Comment by UltimateByte** [comment]
Oh well, perfect :)
I'm curious to know where he's gonna host the mod files, as your link will probably not work for a server. :)
I'm OK to be a mirror if needed, i've got way too much brandwidth.

**Comment by jamiebatch452** [comment]
The files uploaded to my onedrive are there for if anyone needs to download the files,.

**Comment by UltimateByte** [comment]
Note for making the installer : Other mirrors here
http://www.ironoak.ch/BB/index.php?page=files

**Comment by dgibbs64** [comment]
I already host the ut2k4 and ut99 installer so its not a problem :). I will also probably do the same for goldeneye

**Comment by dgibbs64** [comment]
BrainBread - Complete
Vampire Slayer
The Specialists
Natural Selection
Action Half-Life

**Comment by dgibbs64** [comment]
Most of these mods have only a few servers so I will only complete a couple of them

**Comment by dgibbs64** [comment]
I have completed 3 mods now. I will not create anymore unless there is a specific request

**Comment by zeroalpha** [comment]
@dgibbs64 How would one make a specific request ? Just open a new Issue ?
I got 'The Specialists' running now, using the workaround above and I could host and automate it myself. 
But i'd love to see it integrated in LGSM.

**Comment by dgibbs64** [comment]
You can do a pull request if you want to add support yourself. Also raise a new issue. I would copy something like brainbread 1 as a starting point as that would be easy to create.
