### ISSUE TITLE
RO Ostfront problems with newer versions of Linux, Debian.

### ISSUE THREAD

**Issue by dynamittt** [GameServerManagers/LinuxGSM#638]
Hello. I would like to report possible problems with RO Ostfront not being 100% compatible with some newer versions of Linux/Debian. So far I have only tested Debian 8 and we are getting frequent crashes (every couple of days) with error related to libc6.so.
It is absolutely possible that the issue is related to the different version of glibc
A possible solution (I guess) would be, to add the required files on the parent directory, or add option for manual download.
I am ready to test as soon as an update of any type has been released.

**Comment by dgibbs64** [comment]
I reccomend reporting this to tripwire as its better for them to fix it rather than me have to do a hacky fix for it.

**Comment by dgibbs64** [comment]
If you could post your issue on the tripwire forum and link it here so we can track progress. If I feel it is not going to be addressed by them it may come to a point where I will have to put something in place

**Comment by dynamittt** [comment]
Do NOT expect update from TWI, last update was 2010 and game is officially without support since 2013, we are on our own here.....

**Comment by dgibbs64** [comment]
In that case. I will need to take a look at this and see what I can do. May take some time for me to get to this though. If you can provide any more relevant info that you think is useful let me know.

**Comment by dynamittt** [comment]
Hi again and thanx in advance for all the efforts.
On Debian 8 Jessie  64 bit we install the server like this:
dpkg --add-architecture i386
apt-get update
apt-get install tmux mailutils postfix ca-certificates lib32gcc1 libstdc++6 libstdc++6:i386

Then we install the server using normal LGSM procedure.
Crashlogs look like that:
http://pastebin.com/VVJwpBSF

**Comment by UltimateByte** [comment]
Is that still a thing with newer glibc versions ?

Otherwise, i guess a glibc fix that would put an older version might solve the issue.

**Comment by dgibbs64** [comment]
Tested on Debian 8.6 and works 

```
[  OK  ] Debug ro-server: Starting debug
Executing Class Engine.ServerCommandlet
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.
STEAMAUTH : SteamAPI_Init failed
Missing Class Class Editor.TransBuffer
Couldn't resolve hostname ostfront-crashreports.icculus.org.
Will retry sending any crash reports next run.
Browse: RO-Arad.rom?Name=ROPlayer?Class=Engine.Pawn?Character=G_Heer1?team=1?Sex=M?game=ROGame.ROTeamGame?VACSecured=true
Collecting garbage
Purging garbage
Garbage: objects: 52249->52248; refs: 691873
Failed to load 'Class ROGame.ROTeamGame': Failed to find object 'Class ROGame.ROTeamGame'
Failed to find object 'Class ROGame.ROTeamGame'
Failed to find object 'Class ROGame.ROTeamGame'
Game class is 'ROTeamGame'
Setting breakpad minidump AppID = 1210
STEAMAUTH : Steam auth system activation successful
Bringing Level RO-Arad.myLevel up for play (20) appSeconds: 3.758392...
GameInfo::InitGame : bEnableStatLogging False
Defaulting to false
Defaulting to false
Webserver is not enabled.  Set bEnabled to True in Advanced Options.
MaxPlayerRatio = 0.50
```
