### ISSUE TITLE
arma 3 @mods not working in linux game server manager

### ISSUE THREAD

**Issue by BlackhatEspeed** [GameServerManagers/LinuxGSM#651]
I've been having some issues getting @mods to load from the arma3server.cfg file that's outside of the serverfiles directory on my box, i've got all the mods uploaded , I tried putting them in the serverfiles directory and I tried putting them in their own /mods/ folder inside of the serverfiles directory and I cant get the mods to load for the life of me.

**Comment by UltimateByte** [comment]
Hi there,

I've never played around with Aram 3 servers yet, but it could happen soon. Do you think it's an LGSM script issue ? If not, please post there : https://steamcommunity.com/groups/linuxgsm/discussions

**Comment by flexgrip** [comment]
This is weird. Sometimes I can get the debug screen to list the mods but it doesn't like them.

Anyone have more info on this? I assumed the -mod"mods/@something" string has to be just right.

**Comment by acidburn101** [comment]
I gave up using it i just added the mods to the startup param directly. 

```
fn_parms(){
parms="-ip=${ip} -name=SERVERNAME -cfg=${networkcfgfullpath} -config=${servercfgfullpath} -mod=@CBA_A3\;@AnotherMod"
}
```

Mods must be under serverfiles\

**Comment by flexgrip** [comment]
Yeah. I noticed the same thing. They must be in the same root level as the arma server executable. Which is very weird. I guess we're spoiled linux users...

That being said, I gave up on this altogether. This script works great when you want to run a vanilla arma server. However, if you want to run anything more than a mod or two, **arma 3 server on linux is useless**. Segfaults, half the mods don't work, random crashes. Then when you finally do get the damned thing to run, all of the clients trying to connect get memory access errors. I had better luck getting the windows version of arma3server to run via wine!!!

Sometimes I wish Bohemia would go into their office, one day, and throw away any PC's they have. That way they are forced to develop arma under a better environment like linux or osx and bring their client/server platforms into the modern age. And I guarantee it would run more efficiently as well.

Sorry for the rant. A guy can dream...

**Comment by igeighty** [comment]
It is the commented lines in the arma3server script that give example paths that lead me down the wrong path.

`# ARMA 3 Modules`
`# add mods with relative paths:`
`# mods/\@CBA_A3\;`
`# or several mods as:`
`# mods/\@CBA_A3\;mods/\@task_force_radio`

When i used this example syntax i was unable to get any mods to load.

This is how i got it to work. In the serverfiles directory, create a folder called mods. add your mods to this folder. The reason i used a mods folder is just to keep it all neat.

|--serverfiles
| |--mods
| | |--@mod1
| | |--@mod2
| | |--@mod3
| | |--@mod4

then in the arma3server script, change
`mods=""`
to
`mods="mods/@mod1;mods/@mod2;mods/@mod3;mods/@mod4;"`

I realise this question was asked a while back by @BlackhatEspeed, however i am just posting it here to help anyone else that is struggling with it, by the looks of the steam group, that is quite a few people.

might it be possible to add this explanation to the script ? as i could never get `mods/\@CBA_A3\;mods/\@task_force_radio` to work. 

running debian...

Regards,.
Doug

**Comment by UltimateByte** [comment]
Never did an Arma 3 server. Should we change those comments to anything else ?
Please, make suggestions, you can even pull request something.

**Comment by igeighty** [comment]
my method above works on debug mode only, (this is how i have always ran the script) i am testing and will update shortly. @Talven81in #739 has found a solution, i am testing it now

**Comment by igeighty** [comment]
I am trying out several ways of syntax on the mods line and testing them with both the debug and start switches for arm3server.

`mods="mods/@rhsusaf;mods/@rhsafrf;mods/@rhsgref"`
this works with 'debug' mode, yet only first mod loads with 'start'

`mods="mods/\@rhsusaf\;mods/\@rhsafrf\;mods/\@rhsgref"`
fails with 'debug' yet works with 'start'

`mods="mods/@rhsusaf\;mods/@rhsafrf\;mods/@rhsgref"`
fails with 'debug' yet works with 'start'

i am guessing the 'start' needs the `;` to have the `\` present, yet the `@` doesn't ?
you linux boys may be able to shed light on this :)

not really sure what is going on there, i was hoping @Talven81 was able to explain his fix in #739

**Comment by UltimateByte** [comment]
Getting bored of those Arma 3 mods issue. I'll have a look some time.

**Comment by cedarlug** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Arma-3

All works as it should. Confirmed with @XxROBOTICSxX today, walking him through the process.
