### ISSUE TITLE
SteamCMD Auth problem ?

### ISSUE THREAD

**Issue by WSG-ViViV** [GameServerManagers/LinuxGSM#656]
Hello guys, sorry for my bad english i speak french and i try for first time.
I have a problem with auth Steamguard, my server have TeeWorlds, left 4 dead 2, 7 days to die and don't starve togheter server installed but today i can't install starbound server.
i have delete sdtd server and try to reinstall this but when steamguard check the auth code it dont continue and remain frezzed. i can push enter but no reaction from console.
Anyone have the same issues ?
i have try in a new clean install debian8 but same prob.
Sorry one more time for my very bad english =)) and thanks for help.

**Comment by UltimateByte** [comment]
Salut !

We're having issues with steam auth, we didn't figure this out yet.
There is already an issue about that : https://github.com/dgibbs64/linuxgsm/issues/579

For now, i couldn't reproduce the issue reliably, it seems random to me.

**Comment by WSG-ViViV** [comment]
i have this problem with sdtd and sb but is not for the mobile auth, email auth bug too.

**Comment by UltimateByte** [comment]
I know. I had issues even with a regular auth. It seems pretty random. See my edit to the previous post.

**Comment by WSG-ViViV** [comment]
Ook i try out tomorrow 
Thx for help

**Comment by UltimateByte** [comment]
Closing this, go to #579 if you need help !
