### ISSUE TITLE
Missing package since Update to Ubuntu 15.10x64

### ISSUE THREAD

**Issue by derklompi** [GameServerManagers/LinuxGSM#659]
Hello all,
I recently Updated from Ubuntu 15.04 to 15.10 and after that all my L4D/L4D2 servers didnt want to start anymore. After investigating it I found out one package was removed during the upgrade and after I reinstalled it, everything worked again.
It was the package "libstdc++6:i386". Just wanted to inform, dont know if you can use it.

~flam

**Comment by UltimateByte** [comment]
This could explain that : https://github.com/dgibbs64/linuxgsm/issues/654

Let's continue there as your topic seems more relevant.
Thanks for your information.

**Comment by UltimateByte** [comment]
@dgibbs64 Any move to 15.10 on your servers to confirm this ?

**Comment by jeje031** [comment]
me too
Please resolv problems

**Comment by dgibbs64** [comment]
Just re-installing the deps again resolved the issue for @faflfama so thats it what needs to be done. This is a distro issue there is nothing we can do about this.

**Comment by jeje031** [comment]
Ok thanks you

**Comment by faflfama** [comment]
What I forgot the console told me as the Fail: "Segmentation fault" for anyone who might also encounter that.
