### ISSUE TITLE
[Debian 8] Check if OpenSSL is a requirement

### ISSUE THREAD

**Issue by FlashModz** [GameServerManagers/LinuxGSM#660]
RMRP@flashmodz:~$ ./gmodserver console
    fetching functions/command_console.sh...FAIL

curl: (1) Protocol https not supported or disabled in libcurl
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/command_console.sh

RMRP@flashmodz:~$ ./gmodserver monitor
    fetching functions/command_monitor.sh...FAIL

curl: (1) Protocol https not supported or disabled in libcurl
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/command_monitor.sh

Please help Me

**Comment by UltimateByte** [comment]
You need help for reading instructions about installing the right dependencies ?

**Comment by UltimateByte** [comment]
Or did you install CURL already ?
Did you google your error already ?

PS : Don't you find relevant to give some information about your distro ?
PS bis : Hello BTW.

**Comment by jeje031** [comment]
i'm using tuto,

http://www.mesnie.org/tuto/tuto-serveur-gmod-dedie-sous-linux/

**Comment by UltimateByte** [comment]
Lol, this is my tuto. So i guess you're french !
I gotta go to a party right now ! Add me on steam (UltimateByte) i'll help you soon !

**Comment by jeje031** [comment]
Je vous ai ajouté, à l'étape de l'install il me dit automatique FAIL CURL is not installed, je fait donc un apt-get install curl et après sa me donne la série d'erreur au dessus après que l'install soit OK :/

**Comment by jeje031** [comment]
exemple : Connexion à raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 3682 (3,6K) [text/plain]
Sauvegarde en : « gmodserver »

gmodserver          100%[=====================>]   3,60K  --.-KB/s   ds 0s

2016-01-30 20:26:11 (238 MB/s) — « gmodserver » sauvegardé [3682/3682]

RMRP@flashmodz:~$ chmod +x gmodserver
RMRP@flashmodz:~$ ./gmodserver install
    fetching functions/core_functions.sh...FAIL

Curl is not installed!

**Comment by UltimateByte** [comment]
Me vouvoie pas ! Lol !
English only on github please !

Send me a message, we're gonna have a look at it tomorrow ^^
For now : Cheers !

**Comment by jeje031** [comment]
Sorry :/

Thanks you Help Me :)

**Comment by jeje031** [comment]
2 and problems : 

./srcds_linux: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

**Comment by jeje031** [comment]
Solved Problems CURL DEBIAN 8 just install   ( apt-get install curl openssl )

**Comment by UltimateByte** [comment]
@dgibbs64 So openssl is a requirement ?

**Comment by dgibbs64** [comment]
Hmmm might be. This would need to be tested. Re opening this

**Comment by UltimateByte** [comment]
OpenSSL wasn't required on a fresh Debian 8 user's server yesterday, i'll try to know if it was installed by default or not.

**Comment by UltimateByte** [comment]
Confirmed that openssl was installed by default on that Debian 8 x64 distro.
So openssl could definately be a requirement.

**Comment by UltimateByte** [comment]
Seems like CURL tries to use openssl for handling https : 

https://curl.haxx.se/docs/install.html

```
The configure script always tries to find a working SSL library unless
explicitly told not to. If you have OpenSSL installed in the default search
path for your compiler/linker, you don't need to do anything special. 
```


Possible issue to use the latest openSSL on some distros : http://askubuntu.com/questions/475670/how-to-build-curl-with-the-latest-openssl

> You need to specify the directory where OpenSSL is installed 
> 
> ./configure --with-ssl=/usr/local/ssl
> 
> EDIT: Alternatively, you can set your PKG_CONFIG_PATH environment variable (as suggested by ./configure --help):
> 
> PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig ./configure

**Comment by dgibbs64** [comment]
Does this require any further investigation of can this be closed?

**Comment by UltimateByte** [comment]
Well, the conclusion seems to be that openssl is a requirement to get curl working, but is pre-installed on most Linux installations. So it's something you'd have to confirm and eventually add to the website dependencies.

**Comment by dgibbs64** [comment]
Looks like this is an issue with Debian Wheezy. I dont this there is anything we need to do? @UltimateByte I think we can close unless you think openssl should be added to check_deps.sh

**Comment by UltimateByte** [comment]
@dgibbs64 Well it still is a requirement but comes pre-installed with most recent distros. If we wish that even minimal linux installs work, and lower the amount of issues caused by it, then it might be a good idea to add it up. I'm like Switzerland about it, it's up to you.

**Comment by dgibbs64** [comment]
lol thanks for being decisive :P. I think I will leave it out for now. However if it becomes a big issue we can address it later.
