### ISSUE TITLE
Killed $DEBUGGER "$STEAMEXE" "$@"

### ISSUE THREAD

**Issue by stephanvn** [GameServerManagers/LinuxGSM#666]
I am trying to install Insurgency server on Ubuntu 14.04, but when inside the Steam installer, the application crashes with this message: _Killed $DEBUGGER "$STEAMEXE" "$@"_

Im succesfully connected to the API, so that can't be the problem.
This problem happened after several times of trying, and I don't know what to try next.

**Comment by UltimateByte** [comment]
Mh... Could you post your whole logs to something like pastebin ?

**Comment by stephanvn** [comment]
**Appinfo**: http://pastebin.com/Ffjf2Gwr
**Bootstrap**: http://pastebin.com/3Z8k6f14
**Configstore**: http://pastebin.com/MmJjgPqQ
**Connection**: http://pastebin.com/qvDnG2T8
**Content**: http://pastebin.com/DTrgGULd
**Stderr**: EMPTY
**Workshop**: http://pastebin.com/JcZWdW8Z

**Comment by UltimateByte** [comment]
Lol, that's a lot dude !
But i mean... LGSM logs !
In your root LGSM script folder, in /log/script , and /log/console !

**Comment by stephanvn** [comment]
This is all I got...

**Comment by UltimateByte** [comment]
You copied that from /log, near your lgsm script file ?
You should have 2 interesting logs in it. 
I couldn't find the one with your error "Killed $DEBUGGER "$STEAMEXE" "$@" that you mentioned.

**Comment by stephanvn** [comment]
Yeah I dit, strange...
I only know its about _steamcmd.sh: line 35_

**Comment by UltimateByte** [comment]
Maybe insurgency logfile system is different, i never used it, but it's still weird to me.
Every LGSM servers have a common file structure.

BTW, didn't ask that, but aren't you missing any dependency ?

**Comment by stephanvn** [comment]
Unfortunately, the logging structure wasn't installed either.
I managed to get a working server by reinstalling Ubuntu....

**Comment by UltimateByte** [comment]
Was probably a file ownership issue then.

Glad you solved it, even if you used the hardcore way !
