### ISSUE TITLE
[Request, New Game] Codename CURE

### ISSUE THREAD

**Issue by medic917** [GameServerManagers/LinuxGSM#681]
http://steamcommunity.com/app/355180

This is a new free sourcemod game and I was wondering if you can maybe make a script for this one. I believe it is not too different from any other sourcemod.

**Comment by jaredballou** [comment]
I'm going to try adding this to my fork today.

**Comment by jaredballou** [comment]
And done.
Download https://github.com/jaredballou/linuxgsm/blob/master/lgsm-core and run it. Select "Codename CURE" from the list. It will install "cureserver" script in that directory, run
./cureserver install
To install it. It may be missing some settings and dependencies, but it loads up OK on my Centos 6.6 x86_64 box. Let me know how you make out, and if you can help me flesh out the gamedata for this game.

**Comment by faflfama** [comment]
Hi I tested it and came up to some bugs I think.I first run your lgsm-core script without adding a server, so it created its lgsm directory. First think noticing here was a "fn_set_game_setting" after every game-name. 
Then I tried to add the "Cure-Script". It did download and asked me for a folder. One error also showed up: "chmod: cannot access ‘cure/cureserver:fn_set_game_setting’: No such file or directory"
After that it created the folder cure (as I told) with nothing in it. But in the "lgsm" folder there was now also a "cure" folder with the script in it. But its called "cureserver:fn_set_game_setting". 

~Flam

Launcher
[https://fdc.derklompi.rocks/Bugs/1.png](url)

`xx@xx:~$ ./lgsm-core
cureserver:fn_set_game_setting
Select path to install cureserver:fn_set_game_setting [/home/cure]: cure
Installing to cure/cureserver:fn_set_game_setting...     fetching cure/cureserver:fn_set_game_setting (https://raw.githubusercontent.com/jaredballou/linuxgsm/master/lgsm-core)... [DONE]
chmod: cannot access ‘cure/cureserver:fn_set_game_setting’: No such file or directory
[Done]
Script deployed! To install game, run:
cure/cureserver:fn_set_game_setting install`

`xx@yy:~$ ls`
`cure  lgsm  lgsm-core`
`xx@yy:~$ cd lgsm/`
`xx@yy:~/lgsm$ ls`
`cure  functions  gamedata  gsquery.py  servers  tmp`
`xx@yy:~/lgsm$ cd cure/`
`xx@yy:~/lgsm/cure$ ls`
`cureserver:fn_set_game_setting`

**Comment by faflfama** [comment]
Within the Installation also some errors appear:
More cosmetic I suppose is an `Redirecting stderr to '/home/cure/Steam/logs/stderr.txt' ` while he installs SteamCMD.

Others are:

`Creating log directorys`
`=================================`
`mkdir: created directory ‘/home/cure/lgsm/cure/lgsm/log’`
`mkdir: cannot create directory ‘/home/cure/lgsm/cure/lgsm/servers/cureserver/log/script’: No such file or directory`
`touch: cannot touch ‘/home/cure/lgsm/cure/lgsm/servers/cureserver/log/script/cureserver-script.log’: No such file or directory`
`mkdir: cannot create directory ‘/home/cure/lgsm/cure/lgsm/servers/cureserver/log/console’: No such file or directory`
`touch: cannot touch ‘/home/cure/lgsm/cure/lgsm/servers/cureserver/log/console/cureserver-console.log’: No such file or directory`
`‘/home/cure/lgsm/cure/lgsm/log/server’ -> ‘/home/cure/lgsm/cure/serverfiles/cure/logs’
    fetching functions/install_gsquery.sh (https://raw.githubusercontent.com/jaredballou/linuxgsm/master/functions/install_gsquery.sh)... [DONE]`

`GameServerQuery`
`============================`
`Do you want to install GameServerQuery? [Y/n]y`
`/home/cure/lgsm/cure/lgsm/functions/install_gsquery.sh: line 13: -x: command not found
    fetching functions/install_config.sh` `(https://raw.githubusercontent.com/jaredballou/linuxgsm/master/functions/install_config.sh)... [DONE]`

**Comment by faflfama** [comment]
My main problem is now to start the server, because I cant find the place to change the port and IP.

**Comment by dgibbs64** [comment]
I should be able to release one from master soon.

**Comment by jaredballou** [comment]
Look in LGSM/servers/cureserver. Sorry, I went on a tear today and added mod support to the gamedata system, its still not fully functional. Now that people might actually use this fork, I'll branch my development stuff and stabilize master tonight. Sorry for the confusion.

**Comment by jaredballou** [comment]
@dgibbs64 - good to know.
I just cleaned up my fork, and added a bit more documentation to the README to help explain what's different. Hit the repo and fetch the latest lgsm-core script if you'd be so kind, let me know if you have any further issues. Thanks!

**Comment by dgibbs64** [comment]
I'm playing with your code to understand it. I'm focusing on getting a better download system in place.

**Comment by dgibbs64** [comment]
Server now released http://gameservermanagers.com/ccserver
