### ISSUE TITLE
[GMOD] 2 new start parms | Tickrate + fix for half servers

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#685]
Hi all !

So 2 things to propose for gmod
### 1) "+r_hunkalloclightmaps 0"

Several maps, including the most popular rp_rockford_v1b (used by most DarkRP servers, which themselves represent most Gmod servers), need an additional start parameter to work : 

`+r_hunkalloclightmaps 0`

Without it, the server crashes instantly. I don't think having it set to default 1 is useful for a server, so i think it would be cool to have it disabled by default, so people stop complaining about it when making a DarkRP server (got one more dude coming to me for that reason today). 

I'm gonna ask Gmod Team why it's enabled by default, if it deserves any purpose. If not.

Do we add a "more_start_commands" variable, a setting to turn it on or off, or do we put that in RAW in parms=" " ?
### 2) Tickrate

It would be great to add a tickrate option, as the default tickrate 66 is pretty CPU intensive, and tickrate 33 helps with having a lower CPU usage in heavy servers keeping a decent gameplay, while people sometimes don't know that variable is available for gmod too, as for CS servers.

So should we add tickrate support for gmod ? I vote yes.

**Comment by UltimateByte** [comment]
Facepunch issue : https://github.com/Facepunch/garrysmod-issues/issues/2445

**Comment by jaredballou** [comment]
If you use my fork, just add this to gamedata/gmodserver
fn_set_game_params settings "r_hunkalloclightmaps" "0" "allocates lightmaps (crashes custom maps when not set to 0)"
fn_set_game_params parms_plus "r_hunkalloclightmaps" "\${r_hunkalloclightmaps}"

**Comment by jaredballou** [comment]
Apparently 1 uses Valves memory allocation system, 0 uses the alloc syscall.

**Comment by UltimateByte** [comment]
Well, gmod devs stopped answering... 
I think we're gonna have to fix this ourselves for the 1).
