### ISSUE TITLE
[Request, Tool] Broadcasting Icecast Server

### ISSUE THREAD

**Issue by BogusCurry** [GameServerManagers/LinuxGSM#686]
Hello ;D
I have a little request for tool with name Icecast Server, is a broadcasting tool. With the make music over web. I think is was a good feature to linuxGSM ;D
Here the url to icecast server ...
http://icecast.org/

Is a free Tool, stand under GNU GPL, version 2.

Greetings
Bogus

**Comment by jaredballou** [comment]
Does it live stream games? If it's just a media server, its probably not a good candidate to add. We don't want to hack LGSM to handle installation of arbitrary software, but if there is any demand for this I might be able to help.

**Comment by UltimateByte** [comment]
Hi !
I've seen some server admins wanting to run a little radio-like stream with their servers. In that way it's related to gaming.

It would probably be easier than TeamSpeak to setup, though the install/configure process seems very different to anything we had to setup until now... So I should try a standalone install first to see how it's working and tell if it would be scriptable or a pain in the arse.

**Comment by jaredballou** [comment]
If you can get me the details on what it needs, I can take a crack at it.

**Comment by natelo** [comment]
Hi,
I've just stumbled upon this request when I was checking something here... I  among other things also run icecast server and truth to be told, there's no point making any sort of wrapper/script for it. As there's literally no dependencies to build but simple <yum/apt-get> install icecast2 will get you sorted from the get go.

@UltimateByte
You only need to open the icecast2 config and edit it after install. Main info you need is "mount point" which can stay default but what is usually edited is relay password and sometimes a mount point. After it, you simply run the client app (sam broadcast/radiodj..) of your choice and fill the details - ip, mount point, user, pass and you're good to go. That's about it. 

As a helper - look into MPD (music player deamon) if you want to have a own fallback 24/7 radio as you can sort fallback mount point so when live session ends it falls back to pre-configured radio list..MPD is shell stuff only but you have web clients (i.e. auremo) that offer making of playlists and stuff over client GUI to simplify things. 

For anything else, resort to official documentation (icecast/mpd) as it's truth to be told, quite clear and easy understandable once you figure out the basics. 

Hope it helped.

**Comment by UltimateByte** [comment]
@natelo Seems like there are some boring manipulations to do anyways, so i'm not so sure if this script would be unnecessary. And it could motivate people that are lazy to make a stream server to make one. ^^

**Comment by natelo** [comment]
It depends. If you want to spoon feed them, then yes, you could simplify to the extend that they fill the data during install and are then presented with the "whole picture" once finished and simply copy/paste output to their client and move on with their life. 

This sort of scenario will work for anyone that wishes to just run live streams occasionally and has no other desires, like 24/7 radio- either own or by relaying. Anything else, well it can be tricky as once you start digging into configs it can quite easily get out of hands (priority channels, fallbacks, directories, permissions..). 

In either case, if you decide to go with it then fetch the latest stable directly from site rather than using repos as they tend to lag behind quite significantly at times. 

In either case, GL with it! :)

**Comment by dgibbs64** [comment]
Any updates? Im personally not sure that LGSM is the right tool for this server

**Comment by UltimateByte** [comment]
Doc here : http://icecast.org/docs/icecast-trunk/
I'll try to have a look at it.
I'll assign myself so that i can remember about it.

**Comment by UltimateByte** [comment]
After further checking, Icecast doesn't seem to be installable as a user, it's only installed using system (managed as root). Therefore, I don't see how LinuxGSM could manage this better than Linux system itself.
