### ISSUE TITLE
[ccserver] "Bugs" during installation

### ISSUE THREAD

**Issue by derklompi** [GameServerManagers/LinuxGSM#689]
Hi,
old issue was closed, server is here so I tested the installation. It works fine, but throws two errors, dont   know if they are important or not.
1. While installaling SteamCMD

`[ WARN ] SteamCMD is missing`
`/home/lgsm-test/ccserver/functions/core_messages.sh: line 14: /home/lgsm-test/ccserver/log/script/cc-server-script.log: No such file or directory`
1. While Installing/Downloading the server

`Installing Codename CURE Server`
`=================================`
`Redirecting stderr to '/home/lgsm-test/Steam/logs/stderr.txt'`
`ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".``

Cant test if the server actually works, since I dont have the game locally -.-
~Flam

**Comment by dgibbs64** [comment]
ignore the first one that is a non issue (just haven't got around to hiding that one away)

The second one seems to be an issue with steam for some reason but I cannot tell what :/

**Comment by UltimateByte** [comment]
Were you able to finish the install process ? To validate the server content ?
If yes, then it probably works.

**Comment by UltimateByte** [comment]
PS : First error is on the checklist of harmless things to hide : https://github.com/dgibbs64/linuxgsm/issues/646

**Comment by faflfama** [comment]
Downloaded the game and tested the server works fine on Ubuntu 15.10x64. Used Port 27020 first, buit changed it and it ran fine afterwards.

**Comment by UltimateByte** [comment]
So it's working with LGSM ? Should we close this ?

**Comment by faflfama** [comment]
Install didnt throw any fails and I could connect and play. Would say yes.
