### ISSUE TITLE
[Debian 7.9] Problem Starting New NS2 Server

### ISSUE THREAD

**Issue by pcdrivers** [GameServerManagers/LinuxGSM#691]
Installed correctly, but when execute server see that on debug and server don't start on "ns2server start"

> ns2@gameserver5:~$ ./ns2server debug
> [ WARN ] Debug ns2-server: Config file missing!
> # Natural Selection 2 Debug
> 
> Distro: Debian 7.9
> Arch: x86_64
> Kernel: 3.14.32-xxxx-grs-ipv6-64
> Hostname: {MyHostname}
> 
> Start parameters:
> ./server_linux32 -name "NS2 Server" -port 28015 -webadmin -webdomain {MyIP} -webuser admin -webpassword "admin" -webport 8080 -map ns2_summit -limit 24 -config_path "/home/ns2/server1" -modstorage "/home/ns2/server1/Workshop" -mods ""
> 
> Use for identifying server issues only!
> Press CTRL+c to drop out of debug mode.
> Warning! If ns2-server is already running it will be stopped.
> 
> Continue? [Y/n]y
> [ INFO ] Debug ns2-server: Stopping any running servers
> [ WARN ] Stopping ns2-server: Config file missing!
> 
> [ FAIL ] Stopping ns2-server: NS2 Server is already stopped
> [  OK  ] Debug ns2-server: Starting debug
> GetInstanceCount currently unimplemented
> [  0.000] Main : Filesystem initialized, cache enabled
> Press Tab to open the console window
> Press Ctrl-C to exit
> Build 284
> Linux
> Server tickrate 30, client sendrate 20, bandwidth limit per player 51200
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> /home/ns2/functions/command_debug.sh: línea 61: 22420 Violación de segmento  ${executable} ${parms}

Thanks.

**Comment by UltimateByte** [comment]
Probably a non-script issue.
I see you have a segmentation fault (you'd better use an english OS BTW, as 90% of the content will be in english anyways, the 10 remaining % will be more boring than anything else).

Did you install the required dependencies, as asked here ? 
http://gameservermanagers.com/lgsm/ns2server/


Also : Config file missing! means either LGSM wasn't able to create it for you, or you renamed the servicename or the config file name, which you shouldn't unless you know what you're doing. The only case you should do it is that one : https://github.com/dgibbs64/linuxgsm/wiki/Multiple-Servers

**Comment by pcdrivers** [comment]
curl latest version.
lib32gcc1 latest version.
libstdc++6 latest version.
mailutils latest version.
postfix latest version.
libtbb2 latest version.
tmux latest version.
libstdc++6:i386 latest version.
speex:i386 latest version.
0 updated, 0 will be installed, 0 for delete y 0 not updated.

And new user / new server.

I have installed other tf2 servers but not using these script.

Thanks

**Comment by UltimateByte** [comment]
As you were able to install Glibc libraries, i assume you did, `dpkg --add-architecture i386` right ?

However, it could be a problem with Glibc version, as you run debian 7 which is known to use Glibc 2.13, and NS2 requires 2.15+. But LGSM is supposed to fix it on install... 
More info : https://github.com/dgibbs64/linuxgsm/wiki/Glibc

Run this as root :  

`ldd --version`

What's the output ?

**Comment by UltimateByte** [comment]
If you need more help, please post to the general support which is here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
