### ISSUE TITLE
[BUG:dstserver] DST has been updated and no longer works with your script.

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#693]
The update that came out today has borked my server. Will you be updating your scripts to work with this new update?

**Comment by dgibbs64** [comment]
This needs to be fixed

**Comment by nomadichayward** [comment]
I hope they don't mess with the layout much more, they're really making a hash of this game right now. Good luck fixing the scrip to work, and thanks for someone who appreciates your hard work and dedication to this project.  Cheers :+1:

**Comment by Tovath** [comment]
Can confirm, no longer works with the new DST System.

http://forums.kleientertainment.com/topic/64441-dedicated-server-quick-setup-guide-linux/

**Comment by dgibbs64** [comment]
What a pain this is. Might take some time for me to fix. However if there is a DST server admin who wants to have a go they are welcome to

**Comment by dgibbs64** [comment]
Now works. This is the most complicated server I have ever seen. I was considering removing support for it as it is simply not worth the hassle of working with this. However it does now work but will require the server admin to configure it correctly.
Only a minor update in the development branch.
