### ISSUE TITLE
[Server request] Minecraft: Pocket Edition

### ISSUE THREAD

**Issue by James76931** [GameServerManagers/LinuxGSM#702]
Thought it would be quite cool to add support for Minecraft: Pocket Edition / Minecraft Windows 10.
https://www.pocketmine.net/  <-- Server software

Thanks,
_\- James_

**Comment by UltimateByte** [comment]
Is this a mod for Minecraft ?
Would'nt it be relevant to add Minecraft support first ? https://github.com/dgibbs64/linuxgsm/issues/333
Any doc on how to run a server ?

**Comment by James76931** [comment]
Minecraft: Pocket Edition is the mobile port of the game. You can find some docs here: https://pocketmine-mp.readthedocs.org/en/latest/

You can also find install instructions by going to the main website ( https://www.pocketmine.net/ ) and then clicking "Get PocketMine-MP" and then selecting Linux.

To start a server, just run the start.sh file.

You could release the PC version first as it has more features and a large player base, but it may also be a good idea releasing the mobile port first as lots of people play the mobile version aswell. The PC version is thought of as the "main" edition though.

In my opinion it would be a good idea to release the PC one first, but that's entirely up to you.

**Comment by UltimateByte** [comment]
Agreed, PC version first. Then some stuff may be common into those 2 versions, that will help releasing the mobile game server version.
Won't be the easiest one to make though.

**Comment by James76931** [comment]
Alright, thank you.

**Comment by James76931** [comment]
Just wanted to suggest the idea of being able to decide to chose between a stable, beta and development build on installing and then when the server is updated it picks the next version from the build choice you chose on installation. It would also be nice if you could change that choice in the config for lgsm (e.g, set a variable to 1 to update from the stable branch, 2 for beta and 3 for development.)

**Comment by UltimateByte** [comment]
@James76931 The easiest implementation that would fit other LGSM soft would be to add it into the script file directly, something like branche="whatever".

**Comment by James76931** [comment]
Yeah.

**Comment by James76931** [comment]
a

**Comment by dgibbs64** [comment]
#2243 Pocket edition is now Bedrock edition
