### ISSUE TITLE
Check free space on install & whenever required

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#704]
I saw quite a few people failing to install because of not enough free space.
Would be cool to set some space requirements for all of the servers, warning the user before installing if LGSM thinks there is not enough free space.
@dgibbs64 Please, assign one of us if you want this function.

I wish we could put this as a message : 
"You can't even install that game server onto your machine because you're a jerk that has less than X GB free space in 2016. Unless required server files has gone down (which is quite unlikely) since the last time we updated server sizes in LGSM, you won't be able to install it. Do you want to continue anyway ?"

**Comment by dgibbs64** [comment]
lol. Well there is no way for me to do this as such. If we can catch the steamCMD error code for not enough disk space then we can output the error.

**Comment by UltimateByte** [comment]
The errors codes are : 

Displayed to the user : 

`Error! App '232250' state is 0x202 after update job.`

And in Steam/logs/content_log.txt:

`[2016-02-14 16:14:14] AppID 232250 update canceled : Not enough disk space available in "/home/tf2server/serverfiles/steamapps/downloading/232250", 5969 MB needed, 5845 MB available (Not enough disk space)`

We could add typical disk space usage into the code for every server, and make a check using : 

`df -h --block-size=1GB ${rootdir}`

Then we could substract the server size to that result, and Warn if needed.

```
[WARNING] After the installation, you will have around X GB remaining
Continue ? yn
```

Or if disk space won't be enough : 

```
[WARNING] It seems like you don't have enough free space to install that server
Continue ?
```

Then, if it encounters the typical steam error, stop the installer with an error

`[ERROR] Not enough free space`


@dgibbs64 This method would be applied to SteamCMD only, but it would also be great to manage the lack of free space before downloading a new server or file using an archive format, if you get what i suggest. ^^

**Comment by dgibbs64** [comment]
I like this idea I would like to confirm SteamCMD exit code for this it may be 202 im guessing. however its easy to simulate lack of disk space so this is very possible. I think this will be a feature to add after the current development branch is released

**Comment by dgibbs64** [comment]
would also like to add a disk check for updates and if the installer fails during install

Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing
Redirecting stderr to '/home/lgsm/Steam/logs/stderr.txt'
[----] Verifying installation...
[----] !!! Fatal Error: Steam needs 250MB of free disk space to update.
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

**Comment by chriszo111** [comment]
![image](https://cloud.githubusercontent.com/assets/7249742/26765156/7b5724f6-4976-11e7-9eb4-bf0ea1f441b9.png)

I just ran into this error, rather unknowingly. I could not find a proper, simple answer to **error 0x202**. Eventuelly I stumbled across this issue. Google the error will show you desperate hosters trying to fix it. I think its a minor fix to just put in at least an error message, just my 2 cents. But add this to support pages or make it searchable for users would definately help.

**Comment by UltimateByte** [comment]
@chriszo111 Since you seem to like wikis, please use ours to provide relevant info.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support#required-information-for-support
Postdetails will help us knowing about your system and possible causes of issues.

**Comment by dgibbs64** [comment]
Yeah I think we could do with a wiki page with known steam errors. Sadly cable are not the best at this. If there is anyone who wants to research errors and put them together in a nice page that would be great!

**Comment by chriszo111** [comment]
@dgibbs64 Maybe just add a headline "Known issues" to your wiki similar to Valves Dev wiki and whenever an error pops just add the error code with a small explanation, I don't think this is to much effort. However, my purpose was solely to indicate it.

**Comment by dgibbs64** [comment]
@chriszo111 no worry. We will look at doing something like this in the future when someone gets some free time

**Comment by exetico** [comment]
Any free-time meet by?

**Comment by UltimateByte** [comment]
Unfortunately, not much.

**Comment by dgibbs64** [comment]
Some improvements to this relating to SteamCMD. LinuxGSM will now detect if SteamCMD finds a lack of disk space and print a message stating there is not enough disk space available. I believe this will satisfy this issue for most servers (apart from non-steam). I will close this and if we get reports of issues with non-steam servers then we can look at this again

relates to #719
