### ISSUE TITLE
SteamCMD exit codes

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#719]
SteamCMD has exit codes to go with its failure errors. However, there is no documentation anywhere telling us what they mean. I may have to contact Valve to see if they would be willing to provide details of there exit codes

for example

```
Error! App '237410' state is 0x602 after update job.
```

gave me exit code 8

**Comment by UltimateByte** [comment]
Where/how do you get the exit code ?

**Comment by dgibbs64** [comment]
You will see exit codes scattered across LGSM. they are very useful in detected issues with other commands. Here is some example on catching an exit code

	steamcmd.sh
	if [ $? -ne 0 ]; then
		echo "FAIL
	else
		echo "OK"
	fi

basically if you run a command in shell then echo $? stright after you will see the previous commands exit code.

exitcode 0 is everything is OK and any other code is a failure. Some commands do have specific meaning for certain exit codes. This allows us to trap the errors and handle them in our code, If we are lucky and the command hasve specific commands we know about I can get LGSM to hangle a specific issue. 

For example dealing with steamcmd issues. Since its hard to replicate all of the steamcmd issues its hard to tell what all the codes mean

**Comment by dgibbs64** [comment]
Just posted here. Hopefully I get something back 

https://github.com/ValveSoftware/steam-for-linux/issues/4341

**Comment by UltimateByte** [comment]
That's cool, i didn't notice that into the code yet.

Should i harrass Gaben to get error codes and their meanings ?

Having a look at steam.sh i found 

```
# Backward compatibility for server operators
if [ "$STEAMEXE" = "steamcmd" ]; then
        echo "***************************************************"
        echo "The recommended way to run steamcmd is: steamcmd.sh $*"
        echo "***************************************************"
        exec "$STEAMROOT/steamcmd.sh" "$@"
        echo "Couldn't find steamcmd.sh" >&1
        exit 255
```

253 more and we got them all.

**Comment by dgibbs64** [comment]
current known error codes 

```
0: Success!
1: ERROR! Timed out waiting for AppInfo update.
5: Login Failure: Two-factor code mismatch (88)
5: Login Failure: Rate Limit Exceeded (84)
8: ERROR! Failed to install (No subscription).
8: Error! State is 0x402 after update job.
8: Error! State is 0x602 after update job.
```

**Comment by dgibbs64** [comment]
@Bourne-ID since you have been doing some work with steamcmd would it be possible for you to look at causing the install to fail if no subscription?

**Comment by dgibbs64** [comment]
Error! App '232130' state is 0x202 after update job. Is low on disk space

**Comment by dgibbs64** [comment]
new error #2684
https://gaming.stackexchange.com/questions/321270/error-app-255850-state-is-is-0x2-after-update-job

**Comment by ToeiRei** [comment]
Steamcmd errors out stating `ERROR! Timeout downloading item 1380777369` while still giving error code 0.

**Comment by JamesHawkinss** [comment]
Hi @dgibbs64,

I understand that this issue is closed, but I can't find any other information on SteamCMD exit codes. 

I'm having issues where if some (but not all) files are deleted in the game's directory, the preinstall (steamcmd) seems to peacefully exit with code 254 before failing to run. -validate parameter is passed into the command, but doesn't seem to make any difference.

Have you had any experience with exit code 254? I can't find any other information about it.

Many thanks,
James

**Comment by dgibbs64** [comment]
Hi @JamesHawkinss good question. Over the past few years, any info I have gathered for steamcmd error codes can be found here.

https://docs.linuxgsm.com/steamcmd/errors

I don't however have any specific info on exit codes

**Comment by Bourne-ID** [comment]
Out of interest, are you getting this error code from steam (IE 0x254) or as an application exit code (IE echo $? == 254)? Wondering it it could be something else that's that is giving an application exit code, instead of it being a steam error code?

**Comment by JamesHawkinss** [comment]
@Bourne-ID Definitely a steam exit code, as it's the SteamCMD process that's being quit with 254.

Thanks to @dgibbs64 and their research, I've found that it seems to be an issue with the Steam folder being corrupt (specifically /Steam/package/steam_cmd_linux). Upon deleting this file, the install runs with no issue. I really appreciate the help, thank you!
