### ISSUE TITLE
Rust graceful shutdown

### ISSUE THREAD

**Issue by angryce** [GameServerManagers/LinuxGSM#727]
Would it be possible to add a feature to the current rustserver script that would send a "quit" command to the server? (Quit command will save first then shutdown)

Best regards,

**Comment by UltimateByte** [comment]
As it would require rcon (Rust has no console), i don't think so. Would require LGSM to handle RCON first.

**Comment by UltimateByte** [comment]
A better solution would be to convince Facepunch to add a console to their server... That way we could use the same method we're using fo all Source games.
For now, let's forget about this. I won't forget that idea if we decide to integrate external code to LGSM, but for now, except supporting install and update addons such as Oxide, we don't plan anything like that.
