### ISSUE TITLE
Project Zomboid Does Not Prompt for Admin Password

### ISSUE THREAD

**Issue by ainen** [GameServerManagers/LinuxGSM#729]
When starting a Project Zomboid server, there is no prompt for the admin account password. It makes the server appear to not be working. If you use the console command you can see that the server is asking for an admin password. Maybe add an external prompt to fill in the admin password if possible?

**Comment by UltimateByte** [comment]
@dgibbs64 may have the answer.

**Comment by dgibbs64** [comment]
Might be worth trying debug mode to see if you can enter as password. From quickly having a google it asks for a password the first time the server is run

**Comment by ainen** [comment]
If I console in I am able to set the admin password. However, it is not obvious that it is asking for it. The only reason I knew to check the console was because I've set this up manually before. A less experienced user may not know what to do at this point. Maybe there could be a note added to the website?

**Comment by dgibbs64** [comment]
Yeah sounds good. I just added a notes section for pages. I might add in something in the installer as well at a later date

**Comment by marvinl97** [comment]
A working but different solution than the suggested one was added in 278388ff39e0aa64498c68f8dd1327e312994644.

### This issue can be closed now or should we wait for a built-in notification?

###### I want to reduce open issues. Looks better (:

**Comment by UltimateByte** [comment]
Thanks @marvinl97
