### ISSUE TITLE
[question] How I can configure a rust server ?

### ISSUE THREAD

**Issue by BogusCurry** [GameServerManagers/LinuxGSM#730]
Hello ;D
I have install a rust server and I found the server.cfg, but there had not all options for the server configure. So my question, how I can configure a rust server ? And which version of rust was install, I see the expertimetell give not more bzw. if comes no more updates.

And second, I can no connect to my server. How I do that ?
Greetings
Bogus | Have a nice Day

**Comment by UltimateByte** [comment]
Hi,

I know Rust doesn't provide any good documentation, and what you will find will be dispatched over the web. But you will find a lot using google.
For my server, i didn't really need more than oxide and some plugins for it. You're gonna have to learn how to install them.

The version installed by default is the one advised by Garry (Facepunch boss), it's the last public alpha, and is the one that almost anyone will wanna use for a public server. ;) https://twitter.com/garrynewman/status/700658567641231360
There is no more such thing as -beta experimental, thas one is now the dev release, with wipes and shit every day, nobody should use that.

If you can't connect to your server, first check the logs. The latest current log is located in "serverfiles". Input `cat serverfiles/gamelog*.log` to read it.

Also, github is a place for bug report. The right place for you is the general support : https://steamcommunity.com/groups/linuxgsm/discussions
