### ISSUE TITLE
[gmodserver] Problem with maps

### ISSUE THREAD

**Issue by tejy** [GameServerManagers/LinuxGSM#738]
Hello,
There is a problem, with your gmodserver script:
When i try to change map there are 2 errors:

`error loading cfg/trusted_keys_base.txt
``error loading cfg/pure_server_minimal.txt`

I think they are missing, so please can you correct that problem??
Thanks you.

**Comment by dgibbs64** [comment]
Sounds like an issue with gmod server not LGSM. @UltimateByte knows about gmod and might be able to help

**Comment by UltimateByte** [comment]
Hi,
I confirm it's a gmod issue. Those are gmod files that LGSM doesn't touch in any way.
Also, those files are not on my server neither. So may be related to the way you're changing map or your gamemode.

Please, continue the discussion here http://steamcommunity.com/groups/linuxgsm/discussions/0/
