### ISSUE TITLE
Arma3Server START vs DEBUG error

### ISSUE THREAD

**Issue by Talven81** [GameServerManagers/LinuxGSM#739]
When issuing ./arma3server START the following mod variable works.
mods="@CBA_A3\;@ace\;"

When issuing DEBUG the escape backslashes cause the mods to fail to load and only works if as such.
mods="@CBA_A3;@ace;"

This is due to direct issuing of the command in DEBUG vs. issuing the command during START through tmux requiring escape backslashes for the string to be accepted.

This can be fixed by modifying command_debug.sh and adding in on line 56 a translation string to strip out the backslashes.
parms=$(echo $parms | tr -d \\)

This also applies to servermods variable, but the above takes care of both.

**Comment by igeighty** [comment]
i have just noticed this also. in compiling a tutorial for the mods folders, i was double checking and came across this issue, @Talven81 i will test it out under both debug and standard.
@UltimateByte if it pans out i will do a pull request for it. Testing it out tonight.

Thanks @Talven81 i think you have saved a lot of tooth pulling :)

**Comment by igeighty** [comment]
Nope I can't make it work, @Talven81 could you post your modified command_debug.sh to pastern please mate ?

**Comment by dgibbs64** [comment]
Is there an update to this? Or can it be closed?

**Comment by igeighty** [comment]
Hi Dan,
@Talven81 never posted back his solution,
indeed there is a difference in how debug and start works. I have got nowhere with this though as i cannot code tmux, it is well above me.

for now i have been just working around this issue. i am more than happy to test any ideas on it you may have.

i did notice that
`parms=$(echo $parms | tr -d \)` threw errors, yet `parms=$(echo $parms | tr -d \ )` (with space before trailing bracket got further. but errored.

in #651 i posted a few example of what works and what doesn't. in all honesty though i stopped hosting mods and just went vanilla.

regards.
Doug

**Comment by cedarlug** [comment]
https://github.com/GameServerManagers/LinuxGSM/wiki/Arma-3

All works as it should. Confirmed with @XxROBOTICSxX today, walking him through the process.
