### ISSUE TITLE
[Server Request] Unturned

### ISSUE THREAD

**Issue by DasRene** [GameServerManagers/LinuxGSM#740]
What about adding Unturned Gameservers?

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/issues/603
https://github.com/dgibbs64/linuxgsm/issues/176

Unless you have some good news, we're gonna have to close this.

**Comment by Sodierlow** [comment]
Hey Man, i have good news :D
I have found a linux version of Unturned

https://steamdb.info/app/304930/depots/

Executable name: Unturned.x86_64
Startup parameters: ./Unturned-x86_64 -nographics -pei -normal -nosync -pve -players:16 -sv

Available mod:
* Rocketmod ( https://rocketmod.net/ )
* Oxidemod ( not officially released for Unturned, but available here https://github.com/OxideMod/Snapshots/ )

**Comment by dgibbs64** [comment]
http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server

Looks like it may be possible.

**Comment by DasRene** [comment]
So what about a lgsm version then?

**Comment by UltimateByte** [comment]
Would be a pleasure to support a free to play if there's a native Linux server. Seems like it's Unity, I'm quite prowled with it so i could add it. Don't have much free time these days though, so it will take some time, maybe a week or two.

**Comment by seancallaway** [comment]
It should be noted that this can't run without a screen to which is can attach itself. Not a screen as in [GNU screen](https://www.gnu.org/software/screen/), but a display, which makes it difficult if not impossible to run without X running.

**Comment by UltimateByte** [comment]
Oh... There isn't a -nogui command ? I need to test it out.

**Comment by UltimateByte** [comment]
PS : Is there anyone here owning the game that could help me testing the server in order to try making the script anyways ?

**Comment by seancallaway** [comment]
The command is something like: `./Unturned-x86_64 -nographics -pei -normal -nosync -pve -players:16 -sv` and it doesn't launch a GUI, but still requires an X screen for some reason. Just the way they coded it, I imagine, as they definitely treat Linux as a second-class platform and probably didn't intend for headless boxes.

It's free-to-play, but I have it and am more than willing to test.

**Comment by DasRene** [comment]
@UltimateByte Sure, me.
Owning the game is not that hard because of the fact thats f2p :D

**Comment by UltimateByte** [comment]
@DasRene  My bad, forgot that one was a free to play ! Lol.
That's what happens when you write too much stuff on the internet. :o)) 

@seancallaway Thanks for mentioning. I'll try to see with @dgibbs64 and CedarLUG if they can think of a workaround. Otherwise, it would be great to report that critical issue to game devs so they can fix it.

**Comment by seancallaway** [comment]
@UltimateByte That'd be great. I think it was brought up on the developer's forums before (or possibly the Steam forums, but I'd really like to not have to fire up a Lubuntu VM just to host a Unturned server.

**Comment by DasRene** [comment]
How its going?

**Comment by UltimateByte** [comment]
It's going that i got a lot of other stuff to deal with for now.

**Comment by dgibbs64** [comment]
I will be taking this one up since there are quite a few requests for this one. I will be completing Goldeneye: Source first then this is next on my list

**Comment by dgibbs64** [comment]
Had a look at this and Unturned is turning out to not be very easy currently. I will have to come back to this when I can. Again however any developer is welcome to work on this.

**Comment by UltimateByte** [comment]
We could try to work together on discord for this one, could ne d'un :)

**Comment by Smile42RU** [comment]
@dgibbs64 we have a lot of experience of maintenance Unturned on Linux with mono. I can provide for someone from LGSM team our install/start/stop scripts privately if you need and also i can try answer to yours questions about Unturned on Linux in any time.

**Comment by UltimateByte** [comment]
@Smile42RU That would definitely help. No need to send it private, as LGSM source code and dev process are public. You can either pull request or paste bits of code directly on thread, or link to a fork and so on.

**Comment by Smile42RU** [comment]
@UltimateByte You propose me to lay out a commercial code in the public access? Sorry, but i can't do it for everyone and especially for search engines.

**Comment by UltimateByte** [comment]
@Smile42RU I'm not asking that in any way. I'm enumerating the possibilities. You can just select the lines you wanna share and you think will help on this thread.

**Comment by gegtor** [comment]
How it's doing 

Will there be build in rocket support? because unturned server without rocket is pretty much unusable :(

There is linux support: https://rocketmod.net/get-rocket#

**Comment by UltimateByte** [comment]
https://github.com/RocketMod/Rocket/wiki/Installing-Rocket

@gegtor I think it can still be installed manually and work with LGSM. But it's true that an auto installer addition would be cool. :)

**Comment by gegtor** [comment]
:D And how it's going? i cant want for this script :D

**Comment by UltimateByte** [comment]
Well, for now, regular devs are quite busy with support and their lives, it seems. But anyone willing to do so can make actually add the game and pull request the code.

**Comment by tenten8401** [comment]
Oh hey, this one's still open! Just thought this script would ease your lives with creation of the LSGM tool. https://github.com/SergiX44/Rocket_Manager

**Comment by DrPiggy** [comment]
@UltimateByte 
@dgibbs64 
i found this page by the creator of the game explaining exactly every command one by one that needed to be run to host a dedicated linux server for unturned (even with the rocket mod which some people consider servers without it useless), so basically all you need to do is make a script that runs them? (or you didn't find this page or im an idiot and didn't understand something please tell me :D)

**Comment by UltimateByte** [comment]
@DrPiggy You forgot the actual link :p 
https://unturned.wiki/info/tutorials/tutorial-dedicated-server/

**Comment by DrPiggy** [comment]
@UltimateByte ah yea lol xd

**Comment by gegtor** [comment]
Soo how about a nice little script :D

**Comment by tenten8401** [comment]
How's this coming along?

**Comment by dgibbs64** [comment]
Am i right in saying rocket mod is required for unturned server to work? I know very little about unturned server and now it works

**Comment by gegtor** [comment]
Nope but it's very easy to implement and ultra usefull all plugins work with rocket

**Comment by dgibbs64** [comment]
Are there any solid tutorials on a vanilla setup? There is all sorts of rubbish tutorials around. Once I have a vanilla setup working I can look at rocket mod.

**Comment by gegtor** [comment]
https://rocketmod.net/get-rocket

**Comment by dgibbs64** [comment]
I need a tutorial without rocket mod to get started

**Comment by gegtor** [comment]
http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server

**Comment by tenten8401** [comment]
@dgibbs64 You can't install Unturned on Linux without RocketMod atm.

**Comment by tenten8401** [comment]
@dgibbs64 You can't install Unturned on Linux without RocketMod I believe.

**Comment by dgibbs64** [comment]
thanks @tenten8401 I will try anyway and see what happens :-)

**Comment by dgibbs64** [comment]
Yup unturned is a load of poo without rocket mod.

**Comment by gegtor** [comment]
Any progress?

**Comment by dgibbs64** [comment]
Yes some progress. Im working on the next LGSM update currently

**Comment by DeisWasTaken** [comment]
Feedback Required, like are there still people who want a Unturned LGSM Support ?
Yes I think so. Maybe there is a possibility to add LGSM Support for "Unturned - RocketMod"

**Comment by tenten8401** [comment]
@DeisWasTaken Yeah, I'd still be interested in this. RocketMod would be really easy to use for Unturned on Linux.

**Comment by somefriggnidiot** [comment]
+1 to wanting Unturned support.

On Jul 26, 2017 2:06 PM, "DeisWasTaken" <notifications@github.com> wrote:

Feedback Required, like are there still people who want a Unturned LGSM
Support ?
Yes I think so. Maybe there is a possibility to add LGSM Support for
"Unturned - RocketMod"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GameServerManagers/LinuxGSM/issues/740#issuecomment-318151930>,
or mute the thread

**Comment by gegtor** [comment]
Yup i still want it

Just make this https://github.com/RocketMod/Rocket.Unturned/blob/master/Rocket.Unturned/Scripts/Linux/README in to a script

**Comment by seancallaway** [comment]
It looks like they may have cleaned this up some (i.e. doesn't require an X window). I'd like to take a shot at this.

**Comment by tenten8401** [comment]
Yeah, RocketMod for Unturned works great headlessly now. If you're interested in this, I have a Docker container for the Pterodactyl Panel, which can be seen here: https://github.com/tenten8401/pterodactyl-unturned/. The entrypoint.sh may help out a little there. `$MODIFIED_STARTUP` is simply `mono RocketLauncher.exe name_of_server`

**Comment by Sdrabor** [comment]
I can't write code, but I'd be willing to test - I just got an Unturned server up and running via RocketMod as well since my kids decided to be interested in it.  Feel free to ping me on Discord.

**Comment by EZKatnipz** [comment]
+1 to wanting Unturned support.

**Comment by Twonkk** [comment]
Hey guys,

just wanted to see if there was any update for Unturned? Would be a nice addition to add into my server list.

thanks a lot for all your hard work

**Comment by Index-true** [comment]
+1 For news Thank you for this cool project guys ! 
Ps : I could help if needed i've already done a little script for Unturned servers : https://framagit.org/snippets/1243

Thank you ! :smiley:

**Comment by LJDE** [comment]
Hey ! So ? Do you intend to do anything? It would help me a lot! Thank you

**Comment by Index-true** [comment]
I'd like to help you, but... for now Linux servers of unturned are all broken ( https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172 ) so it would be totally useless...

**Comment by dgibbs64** [comment]
Any updates with Unturned Linux support?

**Comment by tenten8401** [comment]
Seems to work fine in my Pterodactyl install script... Haven't tested it in a couple weeks though.

**Comment by LJDE** [comment]
So you can adapt it now that it works? I do not understand all: D

**Comment by dgibbs64** [comment]
Will need to re-test again as it may now be resolved

**Comment by dgibbs64** [comment]
Tried again and still fails. If anyone has got this working let me know how and I can look at creating a script for Unturned. However it appears that Linux support is pretty low for this.

**Comment by buracat** [comment]
example: https://github.com/tenten8401/pterodactyl-unturned
