### ISSUE TITLE
steam freeze at login

### ISSUE THREAD

**Issue by ShovelTime** [GameServerManagers/LinuxGSM#746]
hey im trying to install arma3 with your script but i kept getting stuck at steam trying to log in with this error showing up Created shared memory when not owner SteamController_Shared_mem any ideas whats going on ?

**Comment by UltimateByte** [comment]
Figured it out ?

**Comment by Gousaid67** [comment]
yes i did

**Comment by UltimateByte** [comment]
If you could give your solution, would be great, for the record.

**Comment by Gousaid67** [comment]
well it was a dumb thing, i was with a script that wasnt refreshing his output and the little i saw had no problem

**Comment by UltimateByte** [comment]
So it was just a matter of waiting. Thanks for the feedback :)
