### ISSUE TITLE
Counter Strike Global Offensive GOTV - Lobbies problem

### ISSUE THREAD

**Issue by isarantis** [GameServerManagers/LinuxGSM#769]
Hallo, the problem that i am encountering is that after enabling the gotv feature and setting the cvars, although i see on tv_status the correct information and status when i try to connect as a client i get an error about lobbies 
`Server using '<none>' lobbies, requiring pw yes, lobby id ffffffffffffffff`
And a waiting for lobbies popup that fails.

Thanks in advance

**Comment by UltimateByte** [comment]
Hey,

Never heard of this, but you'd probably have more luck here http://steamcommunity.com/groups/linuxgsm/discussions/0/ as this seems like it's not a script issue.

**Comment by oalaro** [comment]
But this in your GOTV cfg 
`tv_advertise_watchable 1`

**Comment by isarantis** [comment]
Thanks oalaro problem solved!
