### ISSUE TITLE
Demande de gestionnaire Minecraft / Manager Application Minecraft

### ISSUE THREAD

**Issue by Erdack54** [GameServerManagers/LinuxGSM#778]
Bonjour, pourriez vous faire un gestionnaire pour Minecraft ? (Google traduction, je suis français) / Hello, could you do a handler for Minecraft ? (Google traduction, i'm french)

**Comment by UltimateByte** [comment]
Hi, thanks for your submission.
Already discussed and planned here : https://github.com/dgibbs64/linuxgsm/issues/333
To summ up, this server will requires a lot of time, but will be available when we got time for it ;)
