### ISSUE TITLE
Gmod Permission Denied

### ISSUE THREAD

**Issue by KnottyCord** [GameServerManagers/LinuxGSM#788]
/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied
[ .... ] Stopping gmod-server: [QC/FR] OmniWar-Tribe DarkRP/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied
[ FAIL ] Stopping gmod-server: [QC/FR] OmniWar-Tribe DarkRP is already stopped/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied

[ .... ] Starting gmod-server: [QC/FR] OmniWar-Tribe DarkRP/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied
/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied
mv: cannot move '/home/gmodserver/log/script/gmod-server-script.log' to '/home/gmodserver/log/script/gmod-server-script-23-04-2016-17-24-50.log': Permission denied
mv: cannot move '/home/gmodserver/log/console/gmod-server-console.log' to '/home/gmodserver/log/console/gmod-server-console-23-04-2016-17-24-50.log': Permission denied
/home/gmodserver/functions/command_start.sh: line 117: /home/gmodserver/log/script/.gmod-server-tmux-error.tmp: Permission denied
/home/gmodserver/functions/command_start.sh: line 124: /home/gmodserver/log/console/gmod-server-console.log: Permission denied
/home/gmodserver/functions/command_start.sh: line 125: /home/gmodserver/log/console/gmod-server-console.log: Permission denied
/home/gmodserver/functions/command_start.sh: line 126: /home/gmodserver/log/console/gmod-server-console.log: Permission denied
[ FAIL ] Starting gmod-server: Unable to start [QC/FR] OmniWar-Tribe DarkRP
/home/gmodserver/functions/core_messages.sh: line 12: /home/gmodserver/log/script/gmod-server-script.log: Permission denied

Please HELP!

**Comment by UltimateByte** [comment]
Please, learn chmod !

**Comment by UltimateByte** [comment]
Or please, use the right user for the right server. :)
Anyways, permission denied means you are not allowed to read/write/exectue files.
If you need help learning Linux, re-open this. Otherwise, as i said, it's time to learn chmod, users, and the basics of linux. ;)
