### ISSUE TITLE
FastDl not working

### ISSUE THREAD

**Issue by KnottyCord** [GameServerManagers/LinuxGSM#793]
Ok so i added a virtualhost to my server. Here is the code that i found on your GiHub page witch i edit.

```
<VirtualHost *:80>
        ServerAdmin adminemail@mail.com
        ServerName subdomain.domain.com
        ServerAlias subdomain.domain.com
        DocumentRoot /home/gmodserver/www
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory /home/gmodserver/www>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        # Possible values include: debug, info, notice, warn, error, crit, alert, emerg.
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

And I added this to my server file.

sv_downloadurl "http://IP/fastdl"
sv_allowdownload 0 // This disables ServerDL

When i try to test it via the internet it say that the page was not found.

**Comment by dgibbs64** [comment]
https://developer.valvesoftware.com/wiki/Sv_downloadurl

Try from here. I belive sv_allowdownload should be set to 1. Let me know how you get on

**Comment by UltimateByte** [comment]
```

        ServerName subdomain.domain.com
        ServerAlias subdomain.domain.com

```

Did you actually change that accordingly ?
As long as you can't access the webpage with all the files in it, it won't work in gmod, no mriacle.

Gmod is a bit more permissive about sv_allowdownload/upload, unless they changed it.
https://facepunch.com/showthread.php?t=1341797

Maybe i should add those pieces of information to the wiki :)

**Comment by KnottyCord** [comment]
So this shoul be like this
ServerName IP ADDRESSE
ServerAlias IP ADDRESSE

**Comment by UltimateByte** [comment]
Most of server owners have a domain name... Starting at like 3$ a year.

Actually, the only problem i notice right now, is that Apache changed their virtual hosts syntax. Now we should replace this : 

```
                AllowOverride All
                Order allow,deny
                allow from all
```
With this : 

```
                AllowOverride All
                Require all granted
```

I'll update that.

**Comment by UltimateByte** [comment]
Here, i also simplified the htaccess, some stuff was unnecessary (yep, i improved my apache knowledge since).
https://github.com/dgibbs64/linuxgsm/wiki/FastDL#2-share-this-content-with-an-http-server

**Comment by KnottyCord** [comment]
Do you thing i can use my ip and not a domain

**Comment by bjoernr-de** [comment]
```
AllowOverride All
Require all granted
```

You should note that this only works for Apache 2.4+
Any lower versions needs the old syntax:

```
2.2 configuration:

Order allow,deny
Allow from all
```

```
2.4 configuration:

Require all granted
```
(copied from https://httpd.apache.org/docs/current/upgrading.html)

**Comment by KnottyCord** [comment]
im on linux ubuntu 14.04

**Comment by UltimateByte** [comment]
@bjoern-de Yep you're right, i'll specify that it works only for Apache 2.4+. ;)

**Comment by KnottyCord** [comment]
ok after all nothing work please help me!!! I want this project to be done its bean a month now

**Comment by UltimateByte** [comment]
Again, 2 options

1) Learn domain names, buy a cheap one, and follow the wiki and get it solved in a few hours of understanding how a DNS zone works (included with most domain name providers)
Or 
2) Learn virtual hosts so that you can make a share using an IP instead of a domain (Protip : use google, i won't google it for you).
