### ISSUE TITLE
[Server Request] Assetto Corsa

### ISSUE THREAD

**Issue by ghost** [GameServerManagers/LinuxGSM#795]
Could it be possible to get this handy server manager for Assetto Corsa server? Or if there is any guide on how to configure the script(s), i could make it too. Would love to contribute.

**Comment by UltimateByte** [comment]
Got some docs ?

Here it seems like it's windows only
https://steamdb.info/app/302550/depots/

But a dude has a technique : 
Found this, but it's quite poorly documented (no options/settings, whatsoever) https://b.joaoubaldo.com/installing-assetto-corsa-dedicated-server-in-linux-post/

**Comment by wayzhc** [comment]
Yeah, for some reason they've listed it as Windows only, even tho it actually comes with the Linux files too. The linux binary is just called acServer (and can be seen in the file tree on the steamdb site). But forcing the "windows version" download works as a workaround. I actually ran few sessions to test it.

And here is a short guide. Seems to be pretty config based
http://www.assettocorsa.net/forum/index.php?faq/dedicated-server-manual.28/

**Comment by CruelAlpha** [comment]
any updates? :)

**Comment by wolkenschieber** [comment]
@ghost This guide made my day.

**Comment by nishuo** [comment]
Linuxgsm support Assetto Corsa?

**Comment by h3o66** [comment]
> Linuxgsm support Assetto Corsa?

well, not yet.
If someone would contriibute the support for this, LGSM could support it.

**Comment by ShrkByte** [comment]
+1 for this, setting up the server without a manager is complicated. This is a prime candidate for a streamlined setup
