### ISSUE TITLE
Rust fails to connect to server

### ISSUE THREAD

**Issue by AlexCS1337** [GameServerManagers/LinuxGSM#798]
Hello,

I have successfully created Garry Mod and Left 4 Dead 2 servers with this service, however after I done all the steps to install a rust server, from typing ./rustserver start I get this error:
[ .... ] Starting rust-server: Smoo's RustyAssServerfailed to connect to server: Connection refused
[ FAIL ] Starting rust-server: Unable to start Smoo's RustyAssServer

Kind regards.

**Comment by UltimateByte** [comment]
Hi,

What does the logs say ? To display the last log : 
cat serverfiles/game*.log

**Comment by AlexCSilva** [comment]
"cat: serverfiles/game*.log: No such file or directory"

Maybe you meant a different directory/location?

**Comment by UltimateByte** [comment]
Be sure to be in the home folder (and no subfolder) of the Rust directory when you do this.

**Comment by AlexCSilva** [comment]
Yeah it was in home folder of rustserver, I guess it didn't even generate a log.

**Comment by UltimateByte** [comment]
Well, maybe LGSM's log will help on this one ?
What say the logs in log/script/ ?

**Comment by UltimateByte** [comment]
Well, probably solved.

**Comment by AlexCSilva** [comment]
test

**Comment by AlexCSilva** [comment]
Hey, sorry I was busy with uni accessment, I was able to open rust-server-console.log and it says: bash: ./RustDedicated: cannot execute binary file: Exec format error

**Comment by UltimateByte** [comment]
You need to be on an X64 system. It's in the requirements.

**Comment by AlexCSilva** [comment]
Oh oops, I just realised that

**Comment by UltimateByte** [comment]
```
root@game:/home/rustmodded/serverfiles# file RustDedicated
RustDedicated: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=485fa2ceb36071d3c8501b020be10761c48e64ff, stripped
```

It makes sense that there is no x86 as that game server tends to use more than 5GB and up to 12GB RAM, while x86 processes can only use 3 or 4GB.
