### ISSUE TITLE
Project Zomboid requires OpenJava-7; No longer available

### ISSUE THREAD

**Issue by fanuch** [GameServerManagers/LinuxGSM#808]
Project zomboid requires java jre 7, which is not readily available via apt-get

**Comment by dgibbs64** [comment]
Thanks for letting me know.

**Comment by dgibbs64** [comment]
What is your distro? is it available on Ubuntu 14.04 openjdk-7-jre

**Comment by fanuch** [comment]
I downloaded the latest Ubuntu Desktop 16.04 LTS. Ok, that's a good idea!

**Comment by dgibbs64** [comment]
I will close this
