### ISSUE TITLE
tmux: invalid LC_ALL, LC_CTYPE or LANG

### ISSUE THREAD

**Issue by stanislawszenk** [GameServerManagers/LinuxGSM#817]
Hey everybody,
Iv'e got an issue launching rust server, it says:
"tmux: invalid LC_ALL, LC_CTYPE or LANG"

I already checks locale, nothing miss
I'm using debian7

**Comment by UltimateByte** [comment]
Use an UTF-8 locale ?

**Comment by Wolf26** [comment]
Yes

**Comment by UltimateByte** [comment]
`locale -a`

Output ?

**Comment by Wolf26** [comment]
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.UTF-8
POSIX
You have new mail in /var/mail/root

**Comment by UltimateByte** [comment]
`I already checks locale, nothing miss`

I don't know how you checked, but it was the wrong way.
Your locales are messed up.

**Comment by UltimateByte** [comment]
```
apt-get install locales
dpkg-reconfigure locales
```

**Comment by Wolf26** [comment]
I check in /etc/default/locale

**Comment by UltimateByte** [comment]
`apt-get install locales
dpkg-reconfigure locales`

**Comment by Wolf26** [comment]
it seems to work thanks :)

**Comment by UltimateByte** [comment]
;)
