### ISSUE TITLE
No Subscription Installer

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#823]
Installer should fail straight away with this error 

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '105600' (No subscription)

**Comment by UltimateByte** [comment]
We might need to fix this first https://github.com/GameServerManagers/LinuxGSM/issues/991

**Comment by dgibbs64** [comment]
I cannot see any way to implement this without knowing exit codes. I will close this
