### ISSUE TITLE
Function validate

### ISSUE THREAD

**Issue by dm0nkey** [GameServerManagers/LinuxGSM#831]
trying to validate my serverfiles:
`./rustserver validate`

returned this:

```
    fetching functions/command_validate.sh...FAIL

curl: (22) The requested URL returned error: 404 Not Found
https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/functions/command_validate.sh
```

the URL should be:
`https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/lgsm/functions/command_validate.sh`

**Comment by UltimateByte** [comment]
Update your lgsm functions
./rustserver uf

**Comment by UltimateByte** [comment]
Probably solved, closing, re-open if needed.
