### ISSUE TITLE
Insserver update issue

### ISSUE THREAD

**Issue by federicovilla** [GameServerManagers/LinuxGSM#838]
Don't know exactly if it's an isue or whatever...but maybe it's better to post a note about that.
Insurgency game, today I tried to update the game using the following command
`./insserver update`

Applying the update I got a FAIL during a Graceful server stopping.

```
    Applying update...
    [ FAIL ] Stopping ins-server: Graceful: rcon quit: FAIL
    [  OK  ] Stopping ins-server: Bradipi Urlanti Server
```

**Comment by UltimateByte** [comment]
Was the server correctly started and working during the rcon fail ?

**Comment by GliderHacker** [comment]
Negative...the server didn't restarted ...if I understand correctly the question.
After the update the server is OFFLINE and a monitor command provided the following result:
`insserver@hades:~$ ./insserver monitor
[ INFO ] Monitor ins-server: Disabled: No lock file found
        * To enable monitor run ./insserver start
`

**Comment by GliderHacker** [comment]
Mhhh...restarted the server using `./insserver start`
After that I tried a monitor command...got the following:
`insserver@hades:~$ ./insserver start
[  OK  ] Starting ins-server: Bradipi Urlanti Server
insserver@hades:~$ ./insserver monitor
[  OK  ] Monitor ins-server: Checking session: OK
[ .... ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 0/1 : QUERYI[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 0/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 1/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 2/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 3/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 4/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 5/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 6/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 7/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 8/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 9/1 : ERROR:[ FAIL ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 10/1 : ERROR: Unable to receive
`

**Comment by GliderHacker** [comment]
Re tested the monitor...now it seems ok ...weird
`insserver@hades:~$ ./insserver monitor
[  OK  ] Monitor ins-server: Checking session: OK
[ .... ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 0/1 : QUERYI[  OK  ] Monitor ins-server: Querying port: 139.162.185.198:27015 : 1 : OK
insserver@hades:~$
`

**Comment by UltimateByte** [comment]
Well, the query function didn't change since... Your server probably did though.
