### ISSUE TITLE
[CSGO] Connection issues

### ISSUE THREAD

**Issue by nycze** [GameServerManagers/LinuxGSM#846]
Hi,
Can someone help me with my CounterStrikeGlobalOffensive server please?
1. How do I change my servers tickrate to 128?
2. And Why can't people connect to my server only I can on LAN if I knew how to change it in the config I will but I'm not sure where its located or I have to do it in console.
3. Last where can I download libstdc++6:i386?
# 

Distro:    Debian GNU/Linux 8.4 (jessie)
Arch:      x86_64
Kernel:    3.16.0-4-amd64
Hostname:  linux ****
tmux:      tmux 1.9
GLIBC:     2.19
# Performance

Uptime:    0d, 0h, 40m
Avg Load:  0.40, 0.24, 0.23

Mem:       total   used   free
Physical:  3.8G    1.3G   2.5G
Swap:      6.1G    0B     6.1G
# Storage

Filesystem:   /dev/sda1
Total:        141G
Used:         18G
Available:    116G
Serverfiles:  15G
# Counter Strike: Global Offensive Server Details

Server name:      csgo
Server IP:        192.168.1.4:27015
Server password:  NOT SET
RCON password:    **********
Game mode:        0
Tick rate:        64
Status:           OFFLINE
# csgoserver Script Details

Service name:        csgo-server
csgoserver version:  210516
User:                *****
GLIBC required:      2.3.6
Email alert:         off
Update on start:     off
Location:            /home/*****
Config file:         /home/*****/serverfiles/csgo/cfg/csgo-server.cfg
# Backups

No Backups created
# Command-line Parameters

./srcds_run -game csgo -usercon -strictportbind -ip 192.168.1.4 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount ******************************\* -tickrate 64 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 16 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey
# Ports

Change ports by editing the parameters in:
csgoserver

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL

> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
> < Client     OUTBOUND   27005  udp

Status: OFFLINE

e**@linux-user:~$ ./csgoserver st
[ WARN ] Starting csgo-server: Checking dependencies: missing: libstdc++6:i386

Infomation! e*\* does not have sudo access. Please manually install dependencies

sudo dpkg --add-architecture i386; sudo apt-get install libstdc++6:i386

[ .... ] Starting csgo-server: Applying workshop map fix: Counter Strike: Global[ INFO ] Starting csgo-server: Applying workshop map fix: Counter Strike: Global[  OK  ] Starting csgo-server: Applying workshop map fix: Counter Strike: Global Offensive
[  OK  ] Starting csgo-server: csgo

**Comment by UltimateByte** [comment]
1) Before changing the tickrate, maybe try to have a working server.
Anyways, just change it in csgoserver script, line 45
https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver#L45

2) If you're hosting your server at home, your "IP" set into the script must be your local IP, your interface IP in the end, then you'll have to redirect ports to that IP through your router. GSLT must be set too in order for the server to work. https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token

3) See "Dependencies" section. https://gameservermanagers.com/lgsm/csgoserver/
If it's not enough : https://github.com/dgibbs64/linuxgsm/wiki/Glibc

Now you got the keys to do your homework. If you need more help for usage, please use the steam group, as github is more for reporting script issues, not usage/comprehension issues.
