### ISSUE TITLE
Rust needs to warn if lack of RAM. 

### ISSUE THREAD

**Issue by UltimateByte** [GameServerManagers/LinuxGSM#847]
Rust needs at least 6-8GB RAM to have a chance to run correctly depending on the map size.
I'm bored of seing people trying to run it on very poor servers with 1,5 or 3GB RAM and wondering why it auto-closes...
I need to update the wiki and make a RAM check and a warning if needed.

**Comment by UltimateByte** [comment]
https://github.com/dgibbs64/linuxgsm/issues/835

**Comment by twamp22** [comment]
I use swapdrive/swapfile incase rust hops up over the system RAM, for VPS servers. 

If you are unsure how to do it, quite easy...
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by hrombach** [comment]
Monitoring system RAM usage seems outside the scope of lgsm. This is
something you could more efficiently achieve with monitoring tools such as
monit and similar.

**Comment by UltimateByte** [comment]
This is a way for it to run... Not to run properly.
I wouldn't even share that solution as shitty servers would become prominent.
But still, you gave me a good idea : check the swap size, and adjust the warning. Thx for the share.
Hope i'll have some time to code soon. :)

**Comment by twamp22** [comment]
I agree it can be really crappy. I would never even think about this on anything other than blazing fast SSD, works wonders on DigitalOcean!

**Comment by UltimateByte** [comment]
Done
https://github.com/dgibbs64/linuxgsm/pull/946
