### ISSUE TITLE
gmodserver > column: command not found

### ISSUE THREAD

**Issue by 4xx22** [GameServerManagers/LinuxGSM#864]
Hello,

I have a problem with the "column: command not found" in many places

`hl2rp@TheLast-Community:~$ ./gmodserver`
`fetching core_dl.sh...OK`
`fetching core_functions.sh...OK`
`fetching core_messages.sh...OK`
`fetching core_getopt.sh...OK`
`Usage: ./gmodserver [option]`
`Garry's Mod - Linux Game Server Manager - Version 210516`
`https://gameservermanagers.com/gmodserver`

`Commands`
`/home/hl2rp/lgsm/functions/core_getopt.sh: line 234: column: command not found`
`hl2rp@TheLast-Community:~$`

./gmodserver details > http://pastebin.com/bMA7v5Ad

Thank's for your help.

**Comment by cedarlug** [comment]
```bash
apt-get install bsdmainutils
```
If you're on an RPM-based distribution, issue
```bash
yum whatprovides '*bin/column'
```

**Comment by dgibbs64** [comment]
Might need to add this to the requirements. For all the minimal install people

**Comment by UltimateByte** [comment]
I think so :)
https://github.com/dgibbs64/linuxgsm/issues/777
https://github.com/dgibbs64/linuxgsm/issues/613

**Comment by DefaltNF** [comment]
@cedarlug It's work now thank's ! :)
@dgibbs64 Yes :)

**Comment by dgibbs64** [comment]
just checked bsdmainutils is required in both ubuntu and debian to use column. Will add this to the requirements.

**Comment by dgibbs64** [comment]
Updated the website now. check_deps.sh already has the requirement
