### ISSUE TITLE
Arma 3 Monitoring Query Error (FIX)

### ISSUE THREAD

**Issue by MCPC10** [GameServerManagers/LinuxGSM#865]
![image](https://cloud.githubusercontent.com/assets/8211507/15868085/715ee7ca-2ce6-11e6-81e5-e48872b8c06d.png)

I have found a solution for this error (You must add this to the monitor_gsquery.sh):

   elif [ "${engine}" == "realvirtuality" ]; then
        port=$((port + 1))
    fi
![image](https://cloud.githubusercontent.com/assets/8211507/15868111/90d74a98-2ce6-11e6-962c-0817dd34a032.png)

Then it should work :)

If I have posted wrong, excuse me I'm new on Github and my english is bad :)

**Comment by koekblik2** [comment]
it didn't work for me :/ dunno why..

**Comment by igeighty** [comment]
confirmed, @MCPC10 solution works.
![screen shot 2016-06-14 at 7 54 44 pm](https://cloud.githubusercontent.com/assets/19503471/16038745/e2932a0e-3269-11e6-9ec4-db0e9895c005.jpg)

**Comment by JHulsmans** [comment]
Hi @koekblik2 Were you able to resolve your issue with the provided fix? If so we can close this issue.

**Comment by igeighty** [comment]
i have added the pull request https://github.com/dgibbs64/linuxgsm/pull/884 to include the fix into monitor_gsquery.sh (hope i have have done it correctly i am learning git still)

i have tested with fresh install and changed the lines in monitor_gsquery.sh and it works still.
thanks for finding a fix

**Comment by UltimateByte** [comment]
@igeighty you did it right :)
Nice to see you contributing :)
Hopefully this fix is confirmed :)

**Comment by igeighty** [comment]
thanks @UltimateByte i used the web version to do the pull request after testing it locally. that was straightforward enough. i am just having trouble getting my head around the mac desktop version of github.

thanks for the code you guys, it has been a great learning tool also. not to mention a really nice way of setting up an arma server under linux.

great job. (next i will test the syntax for mods under different conditions, i.e. nested folders or not. and try and come up with something for the comments in arma3server.

cheers.
Doug

**Comment by UltimateByte** [comment]
Mac ! :-1: :p 
Good job btw, that's great to see such a collaborative work. :)

**Comment by koekblik2** [comment]
i did this now and yes the ./arma3server details is fixed but somehow i'm still getting query error een tho the console says it connected successfully..

**Comment by koekblik2** [comment]
nevermind guys all of you thanks for helping i fixed it :)

**Comment by UltimateByte** [comment]
@koekblik2  The query fix isn't released yet, will come soon :)

**Comment by koekblik2** [comment]
i fixed the query issue everything is fixed now :)

**Comment by igeighty** [comment]
the query issue, did you fix it with the code above ? or another way .

**Comment by koekblik2** [comment]
with the code above :)

**Comment by igeighty** [comment]
brilliant, thank you :)

**Comment by UltimateByte** [comment]
Well, should be fixed natively now.
Anyone experiencing the issue should run : 
`./arma3server update-functions`

Thanks everyone :)
