### ISSUE TITLE
Warning! SteamCMD did not complete the download (Gmod Server)

### ISSUE THREAD

**Issue by ToEvenStay** [GameServerManagers/LinuxGSM#868]
Hello, today i'm trying to intsall a gmod server but i always this error when i start this `./gmodserver install` i get this 
`Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
mkdir: created directory '/home/gmodserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
/home/gmodserver/lgsm/functions/install_server_files.sh: line 63: ./steamcmd.sh: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys
`

Thanks in advance to help me.
Sorry for my bad english i speak french.

**Comment by dgibbs64** [comment]
did you install dependencies? https://gameservermanagers.com/lgsm/gmodserver/

**Comment by ToEvenStay** [comment]
Yes i have install dependencies

**Comment by UltimateByte** [comment]
I begin to feel like it's my fault if there's so many frenchies :p 

We need some more information : 
- Server provider & server type
- Linux version & architecture
- Some logs

Also make sure that you're not running into a write restriction (input `ls -al` in your server folders and watch the results to make sure).
Ultimately, make sure you have enough free space on your disk. `df -h`

**Comment by ToEvenStay** [comment]
.server type : vps 
.debian 8.5
.log in /home/gmodserver/log/script : 
   
[gmod-server-script.log.txt](https://github.com/dgibbs64/linuxgsm/files/305488/gmod-server-script.log.txt)

**Comment by UltimateByte** [comment]
Server provider ?
It matters.

**Comment by UltimateByte** [comment]
Well, could be a chmod issue, as well as a TSL (SSL) issue, or lack of HDD space or chmod issue.
Now answer, closing.
