### ISSUE TITLE
ARK Map question

### ISSUE THREAD

**Issue by Y0ungSandwich** [GameServerManagers/LinuxGSM#871]
I was wondering if the map 'The Center' is included in LGSM when we update? Wasn't sure if the files were added and we can just change the map or if we have to add the files.

**Comment by dgibbs64** [comment]
LGSM does not provide the server files. This is provided by the game developer. You can probably just update the map variable

**Comment by JHulsmans** [comment]
You can just update the map variable. 

Also this: #843
