### ISSUE TITLE
SDTD: Telnet issue Shutdown/Monitor

### ISSUE THREAD

**Issue by GovicMEW** [GameServerManagers/LinuxGSM#880]
Upon running the monitor command the console is filled with this message until the server crashes.
 Monitor: Querying port: 192.168.0.86: : 5 : ERROR: No port supplied.
Also when running shutdown the server is never shutdown gracefully as the telnet does not connect. I have telnet defined in the sdtd-server.xml is there another spot I am missing? telnet works for cbsm
# Distro Details

Distro:    Ubuntu 16.04 LTS
Arch:      x86_64
Kernel:    4.4.0-22-generic
Hostname:  govicserver
tmux:      tmux 2.1
GLIBC:     2.23
# Performance

Uptime:    0d, 0h, 28m
Avg Load:  3.22, 3.35, 2.53

Mem:       total   used   free
Physical:  15G     3.3G   9.4G
Swap:      509M    0B     509M
# Storage

Filesystem:   /dev/vda1
Total:        246G
Used:         69G
Available:    165G
Serverfiles:  3.0G
#7 Days To Die Server Details

Server name:  
Server IP:    XXXXXXX
Status:       ONLINE
# sdtdserver Script Details

Service name:        sdtd-server
sdtdserver version:  210516
User:                govicserver
GLIBC required:      2.15
Email alert:         on
Update on start:     off
Location:            /home/govicserver
Config file:         /home/govicserver/serverfiles/sdtd-server.xml
# Backups

No Backups created
# Command-line Parameters

./7DaysToDieServer.x86 -logfile /home/govicserver/log/server/output_log__2016-06-11__19-48-28.txt -quit -batchmode -nographics -dedicated -configfile=/home/govicserver/serverfiles/sdtd-server.xml
# Ports

Change ports by editing the parameters in:
/home/govicserver/serverfiles/sdtd-server.xml

Useful port diagnostic command:
netstat -atunp | grep 7DaysToDie

DESCRIPTION  DIRECTION  PORT  PROTOCOL

> Game/RCON  INBOUND    udp
> Query      INBOUND    udp
> WebAdmin   INBOUND    tcp
> Telnet     INBOUND    tcp
#  WebAdmin

WebAdmin enabled:  
WebAdmin url:       http://XXXXXXX:
WebAdmin password:  
#  Telnet

Telnet enabled:  
Telnet address:   XXXXXXXXX 
Telnet password:  

Status: ONLINE

**Comment by Ormira** [comment]
I can confirm than the PR #943 also fixed the monitor issue on my side.
For the shutdown to work correctly, I have to set a telnet password, it does not work without (I think it's the expect script in functions/command_stop.sh that get stuck waiting for "password:". Not sure how to change it yet.

**Comment by UltimateByte** [comment]
Thanks for the feedback.
For the Telnet thing, i didn't experiment with it yet, but aren't you supposed to set a password anyways ?

**Comment by Ormira** [comment]
You can leave the password empty, the server then restrict the connection to the localhost.

**Comment by UltimateByte** [comment]
Well, so you're kinda compelled to put one, aren't you ?
In the end, the interesting question is : How does it shutdown with & without a password ? Is it working properly ?

**Comment by Ormira** [comment]
The sdtd server restrict the telnet admin connection to localhost, not the game client connection.
With a password set, the script shutdown correctly via telnet.
Without password, the script try localhost, public IP, then abruptly close tmux.

**Comment by GovicMEW** [comment]
I'm confused where am i supposed to define the password so lgsm can use it?

**Comment by Ormira** [comment]
The password is configured in serverfiles/sdtd-server.xml on the line
`  <property name="TelnetPassword"                       value=""/>                      <!-- Password to gain entry to telnet interface -->`
But my pull request is needed to let lgsm to parse the config file and be able to connect via telnet.

**Comment by dgibbs64** [comment]
So the summery of the issue is.

Without the telnet password set Graceful shutdown fails.

This could be because the stop command is waiting for a password is cannot provide.
