### ISSUE TITLE
CSGO Server

### ISSUE THREAD

**Issue by geggie88** [GameServerManagers/LinuxGSM#900]
hallo i have a problem with my csgo server. 
i installd it with this https://gameservermanagers.com/lgsm/csgoserver/#gettingstarted

so i have the problem that the csgo server no realy lod the mods only one can join you have only one magazin in your gund ( 30/00 ) you cant   see your overview from the game  and and and

**Comment by dgibbs64** [comment]
What are you even talking about?

**Comment by geggie88** [comment]
The csgo server that i install with this programm
https://gameservermanagers.com/lgsm/csgoserver/#gettingstarted
is running but competetiv mod is not working or deathmatch no mode is
working

2016-06-26 9:07 GMT+02:00 Daniel Gibbs <notifications@github.com>:

**Comment by marvinl97** [comment]
It's impossible to help you if don't provide useful information.
What exactly did you do? And what are your config/server settings? Did you already try a debug start (./csgoserver debug) and checked for error messages? And when no mode is working, what the hell is running on the server?! Casual?

Did you provide a Game Server Login Token?
https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver#L55

**Comment by UltimateByte** [comment]
I'm guessing this is the same issue ?
http://steamcommunity.com/groups/linuxgsm/discussions/0/358415206096429001/
We can't support modding here, if you're using mods, ask for help to this modding community.
If you think there is a problem with LGSM itself, then that's gonna be in the range of what we can help you with.

**Comment by geggie88** [comment]
Okay if you have steam add me please than we can show on my server what i
mean. i dont knoo what mod working on this server for ist that nothing i
set 32 bots deathmatch mode and some other things but when you join the
server you have no knife no weapon you cant see how much money you have und
more issues dont understand thist

hear my steam link: http://steamcommunity.com/id/deadpool1988/

and thank you for helping me

2016-06-27 0:18 GMT+02:00 UltimateByte <notifications@github.com>:

**Comment by UltimateByte** [comment]
Did you set this in csgoserver script ?

```
gamemode="2"
gametype="1"
```

(i won't add you on steam)

**Comment by marvinl97** [comment]
I send him a request. I'm German too. This should make everythink a bit easier.

**Comment by UltimateByte** [comment]
Thanls. Please, keep us tuned on how you solved the issue, it might help us helping other people.

**Comment by marvinl97** [comment]
OK, we solved it. He wanted to make deathmatch server and this were his settings:

```
# [Game Modes]           gametype    gamemode
# Arms Race                  1            0
# Classic Casual             0            0
# Classic Competitive        0            1
# Demolition                 1            1
# Deathmatch                 1            2
gamemode="1"
gametype="2"
```
As you can see, gamemode & gametype are reversed. That's it ;)
The "Missing Gametype" lead to a completely broken gameplay. (No hud, broken slots, ..)

#904

**Comment by UltimateByte** [comment]
Thanks for your correction, i thought the same thing while seing it. Hopefully reversing variable order will prevent some mistakes :)
