### ISSUE TITLE
Don't Starve Together Server Name Bug

### ISSUE THREAD

**Issue by Todixys** [GameServerManagers/LinuxGSM#901]
Hello, im french 'sorry for my bad english'.
I have installed dstserver with https://gameservermanagers.com/lgsm/dstserver/  but i change the server name in /home/dstserver/.klei/DoNotStarveTogether/settings.ini , after i restart the server with su dstserver , ./dstserver stop, ./dstserver start but the serve name is " [Host]'s My World " ...

settings. ini = `[network]
default_server_name = [FR] Zkillu.fr
default_server_description = Welcome to dstserver
server_port = 10999
server_password = password
# max_players = 1 .. 64

max_players = 8
# pvp = true | false

pvp = false
# game_mode = endless | survival | wilderness

game_mode = endless
# enable_autosaver = true | false

enable_autosaver = true
# tick_rate = [ 10 | 15 | 30 | 60 ]

tick_rate = 30

connection_timeout = 8000
server_save_slot = 1
# enable_vote_kick = true | false

enable_vote_kick = true
# pause_when_empty = true | false

pause_when_empty = true

[account]
dedicated_lan_server = false

[STEAM]
DISABLECLOUD = true

[MISC]
CONSOLE_ENABLED = true
autocompiler_enabled = true
`

Help me please :)

**Comment by UltimateByte** [comment]
The only guyz i see apologize for their english are french, it's always funny. I've done it too. Stop worrying about it. ;)

Can you please edit your post using pastebin ?
I don't know DST, but did you try this ?
default_server_name = "[FR] Zkillu.fr"
or
default_server_name = '[FR] Zkillu.fr'

**Comment by UltimateByte** [comment]
No feedback, isolated issue.
I guess the user figured it out.
Closing.

**Comment by marvinl97** [comment]
Didn't work because the settings.ini is obsolete. The structure and variables are completely different know.
