### ISSUE TITLE
Installation Loop

### ISSUE THREAD

**Issue by berserkerX86** [GameServerManagers/LinuxGSM#902]
So I have this problem for over a year now where the steam bootstrapper would cause the lgsm csgo server installer to loop itself. [This](https://gist.github.com/berserkerX86/84c70074367108dc435c02be3d95cbdd) is what I get on a fresh CentOS 7.1 installation. 

`ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt"`
This seems to be the error causing the infinite loop. I can get around it by
`cd ~/steamcmd`
`rm -r ./linux32/`
`mv  ./package/tmp/* ~/steamcmd/`
`./steamcmd.sh +login anonymous +quit`
However I'm not exactly sure what the problem is. :cry:

**Comment by UltimateByte** [comment]
CentOS will always surprise me... I still wonder why people are actually using it. :o))

BTW, can you please output a details command ?
./csgoserver details

Seems like an issue with stdbuf, as googleing lead me to this kinda similar issue https://lists.gnu.org/archive/html/bug-coreutils/2011-07/msg00017.html

**Comment by UltimateByte** [comment]
Well, some more googleing lead me to this.
https://github.com/dgibbs64/linuxgsm/issues/275
@dgibbs64 ?

**Comment by hrombach** [comment]
@UltimateByte CentOS is great if you know what you're doing. It's just that a lot of people who don't use it anyway. ;)

**Comment by jaredballou** [comment]
CentOS is used because it's the classical well-supported enterprise Linux. That use case doesn't line up well with games, especially given Valve's predilection for requiring bleeding-edge Glibc and other stuff that doesn't fly in a lot of the professional Linux world.

**Comment by berserkerX86** [comment]
[./csgoserver details](https://gist.github.com/berserkerX86/d2d4dd5bff7923cc63d72ff5f1565065)
Too bad that two of the best things don't go well together :(

**Comment by UltimateByte** [comment]
Well, the issue is that many people use outdated versions of CentOS, which acts like a bitch for game servers, and that's pretty much all i know about this OS, so it doesn't appeal to me. lol

I think your issue might be related to this recent commit https://github.com/dgibbs64/linuxgsm/commit/44bbcf6917052b55ea1bab33b5f103b4ffec1d5a

**Comment by macchky** [comment]
on Ubuntu 16.04 server ,same error occur

ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by dgibbs64** [comment]
Yes I get the 

    ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

error as well nowever does not cause me any issues. I have however never come across this looping issue.

    [----] Failed to remove temporary unzip folder, continuing anyway

this might be your issue. For some reason it cannot remove the tmp dir. Could be a permissions issue. I recommend deleting the whole steamcmd dir and trying again as lgsm will just re download it again.

**Comment by UltimateByte** [comment]
:+1:  on the fail to remove temporary files.
Guess this is solved.
Investigation showed that ld.so error is really harmless.
