### ISSUE TITLE
Print details for use in submitting issues

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#907]
I think a new option that will allow users to get all the details we need in to a file and printed to screen minus passwords to make is easier to give us useful info. Something like ./gameserver details-support

This could include logs being appended to details plus a later addition of submitting straight to a service like pastebin

edit: easter :P

**Comment by JimTR** [comment]
can we have Christmas rather than Easter ?? you get more presents at Christmas  :smile:

**Comment by UltimateByte** [comment]
Improved idea and beginning of work : 
https://github.com/GameServerManagers/LinuxGSM/issues/1001
