### ISSUE TITLE
syntax error: operand expected (error token is "-")

### ISSUE THREAD

**Issue by Tealk144** [GameServerManagers/LinuxGSM#908]
Hi, if i restart my Server i get this error:

```
[K[ .... ] Stopping ark-server: Arc
[K[ .... ] Stopping ark-server: Arc
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 0
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 1
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 2/home/steam/lgsm/functions/command_stop.sh: line 183: let: -: syntax error: operand expected (error token is "-")
/home/steam/lgsm/functions/command_stop.sh: line 185: [[: -: syntax error: operand expected (error token is "-")


[K[[0;32m  OK  [0m] Stopping ark-server: Arc

[K[ .... ] Log Manager ark-server: Starting
[K[[0;32m  OK  [0m] Log Manager ark-server: Starting

[K[[0;36m INFO [0m] Log Manager ark-server: Removing logs older than 7 days

[K[[0;32m  OK  [0m] Log Manager ark-server: Removed 2 log files

[K[ .... ] Starting ark-server: Arc
[K[[0;32m  OK  [0m] Starting ark-server: Arc
```

**Comment by UltimateByte** [comment]
@cedarlug ?
https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_stop.sh#L185

**Comment by cedarlug** [comment]
Thanks for the head's up.   Checking.

**Comment by cedarlug** [comment]
The good news is that the issue is benign.  The message does not effect the restart behavior.  

Pull request #909 will solve the issue and squash the error in the event the process id vanishes when queried (which is a GOOD thing).

**Comment by cedarlug** [comment]
Closed with #909 integration.

**Comment by UltimateByte** [comment]
run 
`./arkserver uf`
to get the update ;)

**Comment by Tealk144** [comment]
@UltimateByte thanks, i have already added the updated part manually

**Comment by kbgvirus** [comment]
Hi, Please note this issue is still happening as the command_stop.sh hasnt been updated with `pid=${pid//[!0-9]/}`

**Comment by UltimateByte** [comment]
@kbgvirus 
What ?
Is this not enough ?
https://github.com/GameServerManagers/LinuxGSM/pull/909/files

`./arkserver uf` is required to get the update.

**Comment by kbgvirus** [comment]
@UltimateByte i have added the line to the script and now getting another error, i will comment the error as i receive it.

**Comment by UltimateByte** [comment]
Don't do that, run the update-functiions command as asked. Since it's another error, and this one is probably solved, i'm re-closing this.
I dont know if you're trolling or what, but this issue is solved.

**Comment by kbgvirus** [comment]
@UltimateByte I am not trolling, if you read my first comment that new line had not been added to the stop script and therefore the error was still there

**Comment by UltimateByte** [comment]
Well if you read the commit 909, you can see that the command has been added to command_stop.sh.
So that's why i don't get why you're still saying that.
Once again : https://github.com/GameServerManagers/LinuxGSM/pull/909/files

**Comment by kbgvirus** [comment]
Thank you, there is no reason to troll a good cause

**Comment by UltimateByte** [comment]
Sorry about my lack of trust, i don't know you & i assumed it had been merged to master directly. 
Well, let's put it to dev queue until merge.
And yeah, you can definitely add this manually until the merge then.

**Comment by kbgvirus** [comment]
Thank You

**Comment by dgibbs64** [comment]
@cedarlug I dont know why but im not sure this went in correctly. Please can you check the master repo and fix if missing. Thank you

**Comment by dgibbs64** [comment]
@cedarlug https://github.com/GameServerManagers/LinuxGSM/commit/b8c82acbe8f2aa99cfd669b54d8c3ec274aedea3

**Comment by cedarlug** [comment]
@kbgvirus - please update functions and verify that commit https://github.com/GameServerManagers/LinuxGSM/commit/b8c82acbe8f2aa99cfd669b54d8c3ec274aedea3 cleans up the issue.
