### ISSUE TITLE
stdbuf error

### ISSUE THREAD

**Issue by macchky** [GameServerManagers/LinuxGSM#915]
When updating apps this error occurs everytime, due to bits differences between OS self and steamcmd.

on Ubnutu 16.04 64bit
```
[  OK  ] Update arma3-server: SteamCMD
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

It may be occured from this file
/lgsm/functions/update_steamcmd.sh

at this section. Line 21

```
	# Detects if unbuffer command is available.
	if [ $(command -v stdbuf) ]; then
		unbuffer="stdbuf -i0 -o0 -e0"
	fi

	if [ "${engine}" == "goldsource" ]; then
		${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_set_config 90 mod ${appidmod} +app_update "${appid}" +quit | tee -a "${scriptlog}"
	else
		${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit | tee -a "${scriptlog}"
	fi
```

**Comment by dgibbs64** [comment]
Are you aware of a way to resolve this? It is a bit of a non error as it doesn't seem to cause any issues.

**Comment by UltimateByte** [comment]
I see many people complaining about that since the recent stdbuf change.

**Comment by cedarlug** [comment]
It's benign, but no one likes to see an error.

A possible (easy?) fix would be to revert back to what I argued against: setting expect as a dependency and using unbuffer instead.

**Comment by dgibbs64** [comment]
Na its a non error. Its not causing any actual issues.

**Comment by UltimateByte** [comment]
Seems like it may actually cause issues https://github.com/dgibbs64/linuxgsm/issues/924

**Comment by macchky** [comment]
I'm not sure this related to stdbuf, but some processing about appid caused malfunction of downloading apps.

Example: appid ="233780 -beta apex_sneak_preview" 
I try to update ,but like #924 not updating app.

This caused by that line as I mentioned
/lgsm/functions/update_steamcmd.sh
Line29
```
    else
        ${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit | tee -a "${scriptlog}"
    fi
```
Looks like `"${appid}"` quoted appid parameter is not properly processed by steamcmd

As I removed appid quote from update_steamcmd.sh, it's go well.

**Comment by UltimateByte** [comment]
Closing as duplicate
