### ISSUE TITLE
I Can't open server.

### ISSUE THREAD

**Issue by redcat404** [GameServerManagers/LinuxGSM#925]
In the case of local access, I can be connected.

Port:
https://s32.postimg.org/xjdeclyat/image.png
https://s31.postimg.org/5g52i3817/image.png

Config:

gamelogdir="${rootdir}/log/server"
scriptlogdir="${rootdir}/log/script"
consolelogdir="${rootdir}/log/console"
consolelogging="on"

gamelog="${gamelogdir}/${servicename}-game.log"
scriptlog="${scriptlogdir}/${servicename}-script.log"
consolelog="${consolelogdir}/${servicename}-console.log"
emaillog="${scriptlogdir}/${servicename}-email.log"
gamelogfile="\"gamelog-$(date '+%Y-%m-%d-%H-%M-%S').log\""

scriptlogdate="${scriptlogdir}/${servicename}-script-$(date '+%d-%m-%Y-%H-%M-%S').log"
consolelogdate="${consolelogdir}/${servicename}-console-$(date '+%d-%m-%Y-%H-%M-%S').log"

Log:

Set current directory to /home/rustserver/serverfiles
Found path: /home/rustserver/serverfiles/RustDedicated
Mono path[0] = '/home/rustserver/serverfiles/RustDedicated_Data/Managed'
Mono path[1] = '/home/rustserver/serverfiles/RustDedicated_Data/Mono'
Mono config path = '/home/rustserver/serverfiles/RustDedicated_Data/Mono/etc'
Initialize engine version: 5.4.0f1 (c6df7519ab13)
Forcing GfxDevice: Null
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
AudioManager: Using Unknown: NoSound Driver
Begin MonoManager ReloadAssembly
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/ConvexHull.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.CJK.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.MidEast.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Other.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.Rare.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.West.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/I18N.West.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Ionic.Zip.Reduced.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/LZ4n.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/LZ4n.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Newtonsoft.Json.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Assets.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Behave.Unity.Runtime.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/protobuf-net.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/RustBuild.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/RustBuild.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Client.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/EasyAntiCheat.Server.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Console.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.GoogleSheets.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Input.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Network.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Raknet.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.Rcon.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.SQLite.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.System.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Facepunch.UnityEngine.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Data.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.UI.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Xp.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/Rust.Xp.dll into Unity Child Domain
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll (this message is harmless)
Loading /home/rustserver/serverfiles/RustDedicated_Data/Managed/websocket-sharp.dll into Unity Child Domain
- Completed reload, in  0.080 seconds
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Core.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.dll (this message is harmless)
OnLevelWasLoaded was found on LeanTween
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename:  Line: 375)

UnloadTime: 1.230000 ms
System
	Name: localhost.localdomain
	OS:   Linux 3.10 unknown 64bit

CPU
	Model:  Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz
	Cores:  4
	Memory: 7622 MB

GPU
	Model:  Null Device
	API:    NULL 1.0 [1.0]
	Memory: 128 MB
	SM:     30

Memory
	Private:     0 MB
	Working Set: 0 MB

Process
	Priority: 0
	Threads:  0
	Memory:   62 MB
	Peak:     67 MB

Mono
	Collects: 4
	Memory:   0 MB

 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/Mono.Security.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Configuration.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Xml.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Runtime.Serialization.dll (this message is harmless)
Platform assembly: /home/rustserver/serverfiles/RustDedicated_Data/Managed/System.Xml.Linq.dll (this message is harmless)
server.ip: "192.168.1.11"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.hostname: "RedCatServer [JP]"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.worldsize: "3000"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.ip: "192.168.1.11"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.port: "28016"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.password: "manabu1119"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Command Line: "./RustDedicated" "-batchmode" "+server.ip" "192.168.1.11" "+server.port" "28015" "+server.tickrate" "30" "+server.hostname" "RedCatServer [JP]" "+server.identity" "rust-server" "+server.maxplayers" "50" "+server.worldsize" "3000" "+server.saveinterval" "300" "+rcon.ip" "192.168.1.11" "+rcon.port" "28016" "+rcon.password" "manabu1119" "-logfile" "gamelog-2016-07-16-08-36-07.log" 
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.ip: "192.168.1.11"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.port: "28015"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.tickrate: "30"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.hostname: "RedCatServer [JP]"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.identity: "rust-server"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.maxplayers: "50"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.worldsize: "3000"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

server.saveinterval: "300"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.ip: "192.168.1.11"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.port: "28016"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

rcon.password: "manabu1119"
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Server Config Loaded
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Loading Items Took: 0.124 seconds
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Building Items Took: 0.157 seconds / Items: 271 / Blueprints: 191
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Unloading 4 Unused Serialized files (Serialized files now loaded: 68)
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain BaseMap' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
WARNING: Shader Unsupported: 'Rust/Standard Terrain' - All passes removed
UnloadTime: 6.313000 ms
Generating terrain of size 3000 with seed 1319985351
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[AmplifyColor] Null graphics device detected. Skipping effect silently.
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Unloading 46 unused Assets to reduce memory usage. Loaded Objects now: 7608.
Total: 8.592999 ms (FindLiveObjects: 0.195000 ms CreateObjectMapping: 0.256000 ms MarkObjects: 7.984000 ms  DeleteObjects: 0.158000 ms)

[AmplifyOcclusion] GBuffer Normals only available in Camera Deferred Shading mode. Switched to Camera source.
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

RCon Started on 28016
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[3.4s] HEIGHT MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[2.3s] MOUNTAINS
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[0.7s] BIOME MAP
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

**Comment by UltimateByte** [comment]
Please, use the steam group for general support if the issue persists.
100% sure this is a user based issue.
