### ISSUE TITLE
Tmux issue

### ISSUE THREAD

**Issue by TheRealRag** [GameServerManagers/LinuxGSM#928]
I get this now and again have to kill TMUX to get the server to restart

http://pastebin.com/WTGswpKi

**Comment by UltimateByte** [comment]
```
./arma3server details
./arma3server debug
```

**Comment by JLBP** [comment]
I am having a very similar issue myself while running this script. The server will start up fine if I use the startup command manually (by switching into /arma3server/serverfiles/) but when using the script I get the following "tmux errror <startup parm>: No such files or directory. 

Logs:
./arma3server start: http://pastebin.com/jKJjVNPZ
./arma3server details: http://pastebin.com/u0c0fX72
./arma3server debug: http://pastebin.com/k9131KPA

**Comment by cedarlug** [comment]
It might be a problem with /dev/pts being mounted to your container (based on your root filesystem being a loopback device).

Does your system have any problem with starting a generic tmux session?

Just issue tmux,  Then type 'exit'.

**Comment by TheRealRag** [comment]
I now get this error,  I wont run Debug because it breaks my mods......
[ .... ] Starting arma3-server: no server running on /tmp/tmux-1003/default
[ FAIL ] Starting arma3-server: Unable to start BPTanoaExile1.0Revive|Advancemods|Tanks|

http://pastebin.com/5ZsYheXv  Details...   

Also How do you get it to restart using a crontab?   everytime i try to run it, i get errors about tmux
I've tried restart as well
my crontab
http://pastebin.com/wyZw7Nxq

**Comment by UltimateByte** [comment]
Here is how you do crontabs : https://github.com/dgibbs64/linuxgsm/wiki/Automation

For your other issue, seems like it's about mods you installed, so i won't be able to help.

**Comment by TheRealRag** [comment]
script log
http://pastebin.com/v7Rra6gp
 the console log shouldn't matter since it wont actually start the server.......

funny thing is i had it running 1 second before that happen all i did was issue the restart command

**Comment by UltimateByte** [comment]
No server console logs generated since it fails to start ? Take not that i'm trying to help without having ever made an Arma3 server. I know more about LGSM than Arma3.

I just saw your start parameters, they seem to be on several lines. Is that an issue with pastebin's formatting, or is it really like that ?
I'd simplify the start parameters and try again to see if it's due to that first.
Starting with debug function would help too to isolate a possible issue with tmux.

**Comment by TheRealRag** [comment]
thats a paste bin issue..   it wouldn't have a console log because it never gets to the point of the start command, it fails way before then.   it had logs right before i restarted the arma server

**Comment by dgibbs64** [comment]
This is definitely a problem with tmux rather than LGSM. However what is causing the issue I dont know. So you wont get much of an output from logs apart from teh error you get given from tmux. I recommend Googling the error  "protocol version mismatch (client 8, server 7)" and see what comes up.

**Comment by UltimateByte** [comment]
@dgibbs64 The problem evolved, i suppose after what Cedar said.
Now it's "no server running on /tmp/tmux-1003/default"
I'm just thinking about it : what if you got a ghost tmux session running preventing the new one from opening ?
```
ps auxn | grep tmux
ps auxn | grep arma3
```

**Comment by TheRealRag** [comment]
I didn't have either running.  
a reinstall fixes it 3rd time now.  

but as far as crontabs go  still doesn't work gives me an error..    
this paste bin is from my mail logs from the crontabs
http://pastebin.com/bXS3BeZr  doesn't make sense since I can run the command and it works...

**Comment by UltimateByte** [comment]
Did you fix your crontabs as i suggested in the first place ?
Your syntax is not what we suggest,, and all those "stop/start"... The "restart" function would be way more efficient as it does the exact same thing, but without any delay.

**Comment by TheRealRag** [comment]
yes, I did.  I attempted to use root as well and not my regular account is locked out of starting the server great.............

**Comment by TheRealRag** [comment]
If I could get the server running then it would be working but since, Tried to get root to issue the command It now has locked me out of executing the ./arma3server 

root cron
http://pastebin.com/V7BAei1Z
/var/spool/mail/ log
http://pastebin.com/AcBtEied

I have since deleted the user cronjob but still have the /var/spool/mail/ for said user and the cronjobs were copied and pasted from the example linked above but with my settings 
http://pastebin.com/CG3vL8S1

I get this when I am the user trying to start the server..

bash-4.2$ ./arma3server start
bash: ./arma3server: Permission denied
I have all the files Chmod 777 so I know any one could execute it.

**Comment by UltimateByte** [comment]
Your cronjobs seem fine now.

You probably messed up permissions
Who owns arma3server ?
`ls -al`

**Comment by TheRealRag** [comment]
Arma3server user does..   which i dont understand why it would all of a sudden say that user doesn't.  if I chmod 0777 everything that has to do with the server it would allow everyone and their mother to edit/run/view so I dont see how that would change it.

**Comment by UltimateByte** [comment]
> bash-4.2$ ./arma3server start
> bash: ./arma3server: Permission denied

Doesn't look like you're logged to the user, otherwise it would be something like
`arma3server$ ./arma3server start`

**Comment by TheRealRag** [comment]
It is logged in as arma3server.
http://pastebin.com/YGdrCqNh

Its worked 99% of the time since I started the server minus the hiccups.

**Comment by UltimateByte** [comment]
That "-bash-4.2$" is kinda disturbing.
Show us your output of : 
`ls -al /home/arma3server`
And `ls -al /home/arma3server/lgsm/functions`

**Comment by TheRealRag** [comment]
I agree when it happen i was a little confused.    but it ran the server so why fix something if its not broke....

ls -all 
http://pastebin.com/2XJ6ixjv
 lgsm functions
http://pastebin.com/NKDp3dzS

**Comment by UltimateByte** [comment]
Well, everything seems fine in terms of permissions.
What if your user just can't run scripts anymore due to something else you did ?
Some googleing lead me to think it could be related to fstab settings.
`cat /etc/fstab`

**Comment by TheRealRag** [comment]
I also Added arma3server login to be a sudoer.  maybe that will fix it.  im having my fingers crossed.  I didnt change any settings just added the root to cronjob it since the user cron would error out as well..  thinking the root would override the permission.

**Comment by UltimateByte** [comment]
Did you try backuping your arma3server script, then remove the lgsm foler, then download arma3server again, put back your settings in it, and try again ?
Could you try to run any bash script with that user, to at least see if it can ?
If it doesn't help and you can't fix what's wrong on your system, if got nothing else installed on this machine, maybe go for a fresh system install and make sure to not break it this time. :o))

**Comment by TheRealRag** [comment]
I mean I'm sure the datacenter I use can do that for a small fee,  but from what I did,  I didn't touch anything just changed permission from 0775 to 0777 which from my understanding shouldn't do such a thing like this.  I may just be more of a entry level linux tech (since I am in school for network admin) but I am very confident that I didn't change anything I wasn't suppose to...  maybe it was just a freak error or something. just weird how the user cronjob didnt run and would give me a error then root cron would lock me out..  I have 4 different directory with the server install already done for issues like this,  all i have to do is drag and drop mods and cfgs into the base set ups to get it back online. but unfortunately I am not at home so all I can do iss ssh in and just try to figure out what the problem is.

**Comment by UltimateByte** [comment]
I personally have never seen something like that, and it's been like 1.5 years i don't miss an issue on the github support and almost 1 year for the steam group. So i'm kinda clueless here. 
As you now can't run the script for denied permission, the only thing i'm sure about is that it's not a script issue.

Anyways, did you try what i just suggested ? https://github.com/dgibbs64/linuxgsm/issues/928#issuecomment-235382092

**Comment by TheRealRag** [comment]
Nope,  im at work so I cant just focus on this, So im  just going to swap to a different user and directory and just delete the dir and user  and go from there.   makes it easier since I already have a test server up and just make that one the main and remake a test server, and hope to see if this user can cron a restart..

**Comment by UltimateByte** [comment]
No update for 1 month, closing.
Please, use the steam group or Discord if further help is needed.
