### ISSUE TITLE
[Server Request] Killing Floor 2

### ISSUE THREAD

**Issue by ndragon798** [GameServerManagers/LinuxGSM#930]
Add killing floor 2 as a server for easy install and management.

**Comment by UltimateByte** [comment]
Any documentation ?

**Comment by UltimateByte** [comment]
https://steamdb.info/app/232130/

Linux is not supported.

**Comment by ndragon798** [comment]
Go ahead and close this. 
If you want to try and automate http://forums.tripwireinteractive.com/forum/killing-floor-2/technical-support-ae/dedicated-server-support-ac/107985-installing-kf-2-server-on-linux-with-wine

**Comment by UltimateByte** [comment]
Sadly, we do not support Wine atm.

**Comment by dgibbs64** [comment]
I will not support wine with LGSM native clients only. I reccomended pestering tripwire to get around to having a native linux server. When that happens I am happy to add support.
