### ISSUE TITLE
Dependency checker needs to support util-linux-ng

### ISSUE THREAD

**Issue by jaredballou** [GameServerManagers/LinuxGSM#933]
The installer tells me that I need to install util-linux when running on a new CentOS 6.7 box. The util-linux-ng package has superseded that, so we need to accept either package as satisfying the dependency. Perhaps we can query the RPM database directly, as it will show us whatever packages satisfy each dependency.

**Comment by dgibbs64** [comment]
OK I will look at adding an OR option in to the checker. Thanks :)

**Comment by dgibbs64** [comment]
Looks like util-linux-ng is centos 6 only and util-linux is not present.  Whereas util-linux is in centos 7 and util-linux-ng is not available.

**Comment by dgibbs64** [comment]
Can it be confirmed that 

    grep VERSION_ID /etc/os-release | tr -cd '[:digit:]'

Returns 6 please.

**Comment by dgibbs64** [comment]
Please can I get feedback. Change to the development branch in your scripts and test for me to ensure this is working for you. Once you are happy I can merge.

Thanks

**Comment by jaredballou** [comment]
Yes, I am on Centos 6. I'll do a develop checkout on my sandbox server this evening, let you know.

**Comment by UltimateByte** [comment]
@jaredballou Update ?
