### ISSUE TITLE
[Server Request] Factorio

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#936]

**Comment by Scarsz** [comment]
Just a heads up to any randoms viewing the issue, this one likely won't be made for a while due to Dan nor me owning Factorio so it can't be tested.

**Comment by dgibbs64** [comment]
@jocker-il is attempting to create a Factorio server. I look forward to seeing the results :)

https://github.com/jocker-il/linuxgsm/commit/e3aaabd393330177ff3bf7a89a17047e61c374f1

**Comment by lonix** [comment]
I however do own factorio, and happy to create this, but ill need some time to get into how you code things.

**Comment by dgibbs64** [comment]
Factorio has now been released

**Comment by UltimateByte** [comment]
GG!
