### ISSUE TITLE
No known fix currently. Please log an issue.

### ISSUE THREAD

**Issue by iNilo** [GameServerManagers/LinuxGSM#950]
START: FATAL: Unable to start CSGO: Tmux error:
tmux new-session -d -s "csgo-server" "./srcds_run -game csgo -usercon -strictportbind -ip xx.xx.xx -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount xxxxxxxxx -tickrate 102.4 +map de_dust2 +servercfgfile csgo-server.cfg -maxplayers_override 64 +mapgroup random_classic +game_mode 0 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey "
protocol version mismatch (client 7, server 8)

**Comment by UltimateByte** [comment]
https://github.com/tmux/tmux/issues/99
http://steamcommunity.com/groups/linuxgsm/discussions/0/412446292777426341/

**Comment by iNilo** [comment]
Followed https://gist.github.com/rothgar/cecfbd74597cc35a6018

Now getting

protocol version mismatch (client 8, server 7)


?_?

**Comment by iNilo** [comment]
Followed  https://gist.github.com/rothgar/cecfbd74597cc35a6018 

Rebooted, still getting the mismatch ?


tmux -V
tmux 1.9a

**Comment by dgibbs64** [comment]
I wonder why we are suddenly getting tmux issues poping up

**Comment by UltimateByte** [comment]
@dgibbs64 For me it's a distro / package issue.

**Comment by UltimateByte** [comment]
Closing as no feedback and no clue.
Feel free to re-open if you got anything interesting to add to the discussion !

**Comment by iNilo** [comment]
Still errors on non prebuild packages
