### ISSUE TITLE
Restart/Stop Garry's Mod (Request)

### ISSUE THREAD

**Issue by PichotM** [GameServerManagers/LinuxGSM#952]
Hello, I want to know if it is possible before a restart or shutdown the server make announcement like say message for onlines players. (Server restart in 5 seconds..) Thanks!

**Comment by cedarlug** [comment]
The gist of "roll-your-own" restart announce can be grok'd from the extended discussion here:
 http://steamcommunity.com/groups/linuxgsm/discussions/0/458605613414424931/#c458606248614821764

Substitute gmodserver for hwserver.

**Comment by xPichot** [comment]
Thanks!
