### ISSUE TITLE
fetching update_check.sh...FAIL

### ISSUE THREAD

**Issue by TheNoim** [GameServerManagers/LinuxGSM#962]
Hello Guys,
If I try to update my csgo server with ./csgoserver update I get this error:
/csgoserver update
    fetching update_check.sh...FAIL

https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/lgsm/functions/update_check.sh

And I checked it the file update_check.sh is not found on github. I already redownloaded the csgoserver file. Still nothing. I found no issue which address my problem on github, this is why I will open this issue.

Best regards Nils
# EDIT:

I use Debian 8 64bit.

**Comment by dgibbs64** [comment]
./gameserver update-functions

**Comment by UltimateByte** [comment]
Hey dude,
Yep, I confirm you have an outdated file structure, there is no update_check.sh anymore. :)
Just update your functions as @dgibbs64 said.

**Comment by JimTR** [comment]
Why does not work out the script is 'out of date' and runs 'update-functions' as a matter of course ? you could check the checksum of the git version against the checksum of running version if different 'do download new functions' however what do I know dude

**Comment by dgibbs64** [comment]
I set a cronjob to run weekly to update the functions. Update functions just runs a diff comparing the local and remote file and if different updates it, If missing removes it. I found checksums are not really required as the functions are so small anyway.

**Comment by UltimateByte** [comment]
What about a periodic update check, according to a specific line into the script log ?
BTW, any kind of an auto update if there is any one day, should allow disableing, for people wanting to custom their LGSM.

**Comment by JimTR** [comment]
I dont quite understand 'BTW, any kind of an auto update if there is any one day, should allow disableing, for people wanting to custom their LGSM'.
but I guess it makes sense

**Comment by marvinl97** [comment]
You could fork it to use your own repo. So people can have their custom versions (:

https://github.com/dgibbs64/linuxgsm/blob/master/CounterStrikeGlobalOffensive/csgoserver#L71-L76

**Comment by UltimateByte** [comment]
@JimTR In other words : If we make an auto-update system, we have to make it the user can disable it if he wants to.
