### ISSUE TITLE
parms

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#971]
After looking at the wiki page for start-parms I think that an extra variable that is blank by default that is away from the pre-defined variables. This may make parms easier to manage

```
fn_parms(){
extraparms=""
parms="-game cstrike -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +map ${defaultmap} +servercfgfile ${servercfg} -maxplayers ${maxplayers} ${extraparms}"
```

}

Opinions on this please

**Comment by jach11** [comment]
Looks like a good idea, although I'm not sure how useful it'll be for new users, as most of them even have issues setting up file permissions, and advanced users won't find it difficult to add extra params on their own. Somewhere in the middle will be someone who finds it useful, I'm just not sure how many people would fall under that category.

**Comment by UltimateByte** [comment]
Sounds like a good idea.
Could also be something like for Garry's Mod https://github.com/dgibbs64/linuxgsm/blob/master/GarrysMod/gmodserver#L48

**Comment by jaredballou** [comment]
I always liked having parms generated by individual config settings. See https://github.com/jaredballou/linuxgsm/blob/master/gamedata/include/parms and https://github.com/jaredballou/linuxgsm/blob/master/gamedata/include/parms_plusminus for examples, they process the gamedata for each game and generate a properly formatted and ordered parms variable. This is a very hacky solution that I implemented just to get it off the ground, but I think it's the right direction generally.

**Comment by dgibbs64** [comment]
LinugGGM no used separate config files. I now believe this feature is not really required
