### ISSUE TITLE
Trouble connecting to steamCMD servers

### ISSUE THREAD

**Issue by mightyBroccoli** [GameServerManagers/LinuxGSM#985]
```
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Redirecting stderr to '/home/nico/Steam/logs/stderr.txt'
```

I tried to reinstall my csgo server with the updated script and now I get this message everytime and I cant even complete the install of steamcmd with the error "too many retrys"

All dependencies are installed and working and libstdbuf.so is at the location LD_PRELOAD is pointing to.

What should I do ?

**Comment by UltimateByte** [comment]
Can you output a` ./gameserver details` ?
Could be just a failing connexion to steam servers. I've seen this issue self solving as libstdbuf.so is atm known as a non-error.
See #915

**Comment by marvinl97** [comment]
I also had this "too many retries" error once. It kept spamming these SteamCMD messages extremely fast. I just waited a few minutes because I couldn't find anything about this error.

**Comment by UltimateByte** [comment]
@mightyBroccoli @marvinl97 What server provider ?
Chances are they got a shitty interconnection with Valve servers.

**Comment by marvinl97** [comment]
Server4You (data center: SXB)

**Comment by UltimateByte** [comment]
Well considering their very low pricing, chances are they save money on interconnection, between other things. :o))

**Comment by mightyBroccoli** [comment]
My server provider is netcup and the connection is working I do get about 2 GB with 20 stops in between but then I get the "too many retries error". 

I just recached ldconfig and restarted the maschine I will try again now.

**Comment by UltimateByte** [comment]
There should be a steamcmd log somewhere. Its output might be helpful.

**Comment by mightyBroccoli** [comment]
https://paste.xinu.at/HrOufO/

I am not sure in this paste this block repeats. For each started download and Error this log block is written. 
I think there is a error with corrupted packages and therefor closing connections.

`[2016-08-09 17:51:52] AppID 740 update canceled : Failed updating depot 731 while unpacking bad chunk "94fe3edfa73ebe780d186380647a7040e97b60da" from "valve503.steampipe.steamcontent.com" (Unpack failed (c:3622,u:0,b:3623)) (Corrupt download)
[2016-08-09 17:51:52] AppID 740 update changed : Running,Downloading,Staging,Stopping,
[2016-08-09 17:51:54] Increasing target number of download connections to 4 (rate was 0.000, now 113.157)
[2016-08-09 17:51:54] Created download interface of type 'CS' (1) to host valve519.steampipe.steamcontent.com (valve519.steamcontent.com)
[2016-08-09 17:51:54] HTTP (CS,519) - valve519.steampipe.steamcontent.com (valve519.steamcontent.com): OpenConnection - Success!
[2016-08-09 17:52:04] AppID 740 update changed : Running,Stopping,
[2016-08-09 17:52:04] AppID 740 update changed : None
[2016-08-09 17:52:04] AppID 740 state changed : Update Required,Update Started, (Corrupt download)
[2016-08-09 17:52:04] AppID 740 scheduler finished : removed from schedule
[2016-08-09 17:52:04] HTTP (CS,519) - valve519.steampipe.steamcontent.com (valve519.steamcontent.com): Closing connection`

I am not sure though.

**Comment by UltimateByte** [comment]
To me, looks like failing downloads because of packet loss.
What happens if you ping the host ?
`ping valve519.steampipe.steamcontent.com`
Also, a tracert could help. 
`tracert valve519.steampipe.steamcontent.com`

If you got a route issue, then warn your provider, that will then have to warn their bandwidth provider, that will probably say "fuck off"; then the easiest thing to do is just to find a better server provider with proper bandwidth provider that has proper routes.

**Comment by mightyBroccoli** [comment]
**ping valve519.steampipe.steamcontent.com**
```
ping valve519.steampipe.steamcontent.com
PING valve519.steamcontent.com (162.254.197.29) 56(84) bytes of data.
64 bytes from 162.254.197.29: icmp_seq=1 ttl=126 time=7.02 ms
64 bytes from 162.254.197.29: icmp_seq=2 ttl=126 time=11.7 ms
64 bytes from 162.254.197.29: icmp_seq=3 ttl=126 time=8.25 ms
64 bytes from 162.254.197.29: icmp_seq=4 ttl=126 time=18.2 ms
64 bytes from 162.254.197.29: icmp_seq=5 ttl=126 time=19.5 ms
64 bytes from 162.254.197.29: icmp_seq=6 ttl=126 time=8.80 ms
64 bytes from 162.254.197.29: icmp_seq=7 ttl=126 time=8.16 ms
64 bytes from 162.254.197.29: icmp_seq=8 ttl=126 time=4.12 ms
64 bytes from 162.254.197.29: icmp_seq=9 ttl=126 time=7.30 ms
64 bytes from 162.254.197.29: icmp_seq=10 ttl=126 time=17.3 ms
64 bytes from 162.254.197.29: icmp_seq=11 ttl=126 time=4.16 ms
64 bytes from 162.254.197.29: icmp_seq=12 ttl=126 time=4.09 ms
64 bytes from 162.254.197.29: icmp_seq=13 ttl=126 time=4.11 ms
64 bytes from 162.254.197.29: icmp_seq=14 ttl=126 time=4.03 ms
--- valve519.steamcontent.com ping statistics ---
14 packets transmitted, 14 received, 0% packet loss, time 13020ms
rtt min/avg/max/mdev = 4.032/9.064/19.539/5.352 ms
```
**tracert valve519.steampipe.steamcontent.com**
```
traceroute valve519.steampipe.steamcontent.com
traceroute to valve519.steampipe.steamcontent.com (162.254.197.29), 30 hops max, 60 byte packets
 1  gw01.netcup.net (188.68.52.2)  0.277 ms  0.288 ms  0.286 ms
 2  decix.valve.net (80.81.193.63)  4.115 ms  4.138 ms  4.129 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

oh I see I guess I am not downloading csgo today :D

**Comment by UltimateByte** [comment]
For comparison, here is what i got on my server using cogent as a bandwidth provider

```
root@terageek:~# traceroute valve519.steampipe.steamcontent.com
traceroute to valve519.steampipe.steamcontent.com (162.254.197.              29), 30 hops max, 60 byte packets
 1  PULSGD3SRV001.cust.as62k.net (89.234.180.211)  0.099 ms  0.              027 ms  0.026 ms
 2  10.0.9.1 (10.0.9.1)  0.311 ms  0.344 ms  0.372 ms
 3  te0-1-0-0.rcr21.par02.atlas.cogentco.com (204.68.252.73)  0              .778 ms  0.804 ms  0.846 ms
 4  be2416.ccr42.par01.atlas.cogentco.com (130.117.48.253)  1.1              73 ms be2415.ccr41.par01.atlas.cogentco.com (130.117.48.249)  1              .127 ms be2416.ccr42.par01.atlas.cogentco.com (130.117.48.253)                1.132 ms
 5  be2044.agr21.par01.atlas.cogentco.com (130.117.51.78)  1.24              7 ms be2140.agr21.par01.atlas.cogentco.com (130.117.51.82)  1.4              80 ms be2044.agr21.par01.atlas.cogentco.com (130.117.51.78)  1.              535 ms
 6  prs-b2-link.telia.net (213.248.86.169)  0.752 ms  1.290 ms                1.261 ms
 7  prs-bb2-link.telia.net (213.155.135.198)  1.176 ms prs-bb2-              link.telia.net (62.115.140.88)  1.217 ms prs-bb3-link.telia.net               (213.155.135.194)  1.621 ms
 8  ffm-bb2-link.telia.net (62.115.139.57)  31.604 ms ffm-bb4-l              ink.telia.net (62.115.112.125)  10.975 ms ffm-bb2-link.telia.ne              t (80.91.246.184)  10.371 ms
 9  ffm-b1-link.telia.net (62.115.116.162)  10.889 ms ffm-bb3-l              ink.telia.net (62.115.119.169)  10.631 ms ffm-b1-link.telia.net               (62.115.116.160)  10.959 ms
10  ffm-b1-link.telia.net (62.115.141.235)  11.345 ms valve-ic-              311331-ffm-b1.c.telia.net (62.115.56.138)  10.937 ms valve-ic-3              08855-ffm-b1.c.telia.net (213.248.101.30)  11.090 ms
11  * valve-ic-311331-ffm-b1.c.telia.net (62.115.56.138)  10.645 ms  10.757 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

And from OVH

```
root@game:~# traceroute valve519.steampipe.steamcontent.com
traceroute to valve519.steampipe.steamcontent.com (162.254.197.29), 30 hops max,                                                                          60 byte packets
 1  164.132.200.253 (164.132.200.253)  0.749 ms  0.799 ms  1.298 ms
 2  po110.gra-g2-a75.fr.eu (37.187.231.93)  0.378 ms po110.gra-g1-a75.fr.eu (37.                                                                         187.231.91)  0.237 ms po110.gra-g2-a75.fr.eu (37.187.231.93)  0.188 ms
 3  be10-20.gra-g2-a9.fr.eu (37.187.36.196)  2.503 ms  0.881 ms  2.543 ms
 4  be100-1199.fra-1-a9.de.eu (91.121.131.129)  8.731 ms  8.772 ms be100-1200.fr                                                                         a-5-a9.de.eu (91.121.131.131)  9.319 ms
 5  decix.valve.net (80.81.193.63)  8.891 ms  8.839 ms  8.840 ms
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

Note that the OVH one ends with 80.81.193.63, just like you, but your route seems more direct as if you were in the same datacenter, lol.

So if it's not a route issue, i'm a but clueless right now.

**Comment by mightyBroccoli** [comment]
Yeah netcup hast some pretty nice interconnections, but either way packetloss still occurs I think I will try again tomorrow and we will see.
> Netzwerk Anbindung
> 
> Transits:
> 
>     3 x 10 GBit/s Core Backbone GmbH
>     2 x 10 GBit/s Level 3 Communications, LLC
>     2 x 10 GBit/s Hetzner Online GmbH
>     1 x 10 GBit/s Hurricane Electric (über DE-CIX)
>     1 x 10 GBit/s DTAG (partial über DE-CIX)
>     1 x 10 GBit/s Liberty Global (LGI)
> 
> Peering-Points:
> 
>     1 x 10 GBit/s DE-CIX
>     1 x 10 GBit/s ecix
>     1 x 1 GBit/s N-IX

**Comment by UltimateByte** [comment]
Hope you got it solved. Closing.
Re-open if needed.
