### ISSUE TITLE
Migrate Config files to new repo and update function

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#989]
I am planning to move all the config files to there own repo https://github.com/dgibbs64/gameserver-configs

Im hoping that this will allow people to easily find the configs and update them. But also allow for a repo that anyone can use not just LGSM users.

I also need to update the function install_config.sh to move away from using wget.

**Comment by dgibbs64** [comment]
Its a big job but quite easy to do. Just requires a bit of time.

I require one willing volunteer to copy all config files across to the repo.
https://github.com/GameServerManagers/Game-Server-Configs

This will create a centralised repo for all configs that any project or or person wants to use can easily access.

There is a standard look for these configs so some may need a tidy up.

But if anyone as a free few hours I think this will benefit more than just the LGSM project. :D

**Comment by marvinl97** [comment]
What's with these placeholders: \<hostname\>, \<rconpassword\>?
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_config.sh#L18

**Comment by dgibbs64** [comment]
This is now completed all configs are migrated. However work still needs to be done to improve the quality of many of the configs. Volunteers are still required to assist in this. I will close this now.

https://github.com/GameServerManagers/Game-Server-Configs
