### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#991]
Im am making this issue related to the following error as a couple of people are confusing it with other errors they are getting.

```
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

To summarise. This issue occurs because stdbuf is 64-bit and SteamCMD is 32-bit. This means stdbuf does not work with SteamCMD on 64-bit systems.

```
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Redirecting stderr to '/home/lgsm/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
```

This is related to the issue

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1440933.html

I have tested this and confirmed stdbuf does fail on x64. However should work on x86. unbuffer does however work. Ideally stdbuf working with 64-bit apps would be great however its up to the distro maintainers to fix.

**Comment by dgibbs64** [comment]
Suggestions on this will be handy? Do you think reverting to unbuffer for 64-bit be the best solution?

**Comment by cedarlug** [comment]
Reverting to unbuffer (or nothing if expect isn't installed) on 64-bit would provide the exact same functionality without the confusing error.

I've also been following the Debian bug reports on the issue, and it's close to a "won't fix", or at least a low-priority issue for those maintaining the package.

**Comment by dgibbs64** [comment]
OK. I will use unbuffer if available on 64-bit and stdbuf on 32 bit.

**Comment by kbgvirus** [comment]
Still receiving this error, was the change comitted?

**Comment by UltimateByte** [comment]
Nope, otherwise the issue would be closed. :)

**Comment by UltimateByte** [comment]
Related : https://github.com/GameServerManagers/LinuxGSM/issues/915

**Comment by presteus** [comment]
Do you have a workaround for this problem ?

This is my log if I could help
`
user@presteus:~$ ./csserver update
    fetching command_update.sh...OK
[ .... ] Update cs-server:     fetching update_steamcmd.sh...OK
[  OK  ] Update cs-server: SteamCMD
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded: ignored.
Redirecting stderr to '/home/user/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '90' already up to date.
[ INFO ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6cp: not writing through dangling symlink `/home/user/.steam/sdk32/steamclient.so'
[ERROR ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6

user@presteus:~$ ./csserver force-update
[  OK  ] Update cs-server: SteamCMD
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded: ignored.
Redirecting stderr to '/home/user/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '90' already up to date.
[ INFO ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6cp: not writing through dangling symlink `/home/user/.steam/sdk32/steamclient.so'
[ERROR ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6

user@presteus:~$ ./csserver update-functions
    fetching command_update_functions.sh...OK
[ .... ] Update LGSM cs-server: Updating functions
    checking check_config.sh...OK
    checking check_deps.sh...OK
    checking check_glibc.sh...OK
    checking check_ip.sh...OK
    checking check_logs.sh...OK
    checking check_permissions.sh...UPDATE
    fetching check_permissions.sh...OK
    checking check_root.sh...OK
    checking check.sh...UPDATE
    fetching check.sh...OK
    checking check_status.sh...OK
    checking check_steamcmd.sh...UPDATE
    fetching check_steamcmd.sh...OK
    checking check_system_dir.sh...OK
    checking check_system_requirements.sh...OK
    checking command_install.sh...OK
    checking command_start.sh...OK
    checking command_stop.sh...OK
    checking command_update_functions.sh...OK
    checking command_update.sh...OK
    checking core_dl.sh...OK
    checking core_exit.sh...OK
    checking core_functions.sh...UPDATE
    fetching core_functions.sh...OK
    checking core_getopt.sh...UPDATE
    fetching core_getopt.sh...OK
    checking core_messages.sh...OK
    checking core_trap.sh...OK
    checking fix.sh...OK
    checking fix_steamcmd.sh...OK
    checking info_config.sh...UPDATE
    fetching info_config.sh...OK
    checking info_distro.sh...OK
    checking info_glibc.sh...UPDATE
    fetching info_glibc.sh...OK
    checking install_complete.sh...OK
    checking install_config.sh...OK
    checking install_header.sh...OK
    checking install_logs.sh...OK
    checking install_server_dir.sh...OK
    checking install_server_files.sh...UPDATE
    fetching install_server_files.sh...OK
    checking install_steamcmd.sh...OK
    checking logs.sh...OK
    checking update_steamcmd.sh...OK
[  OK  ] Update LGSM cs-server: Updating functions

user@presteus:~$ ./csserver update
[  OK  ] Update cs-server: SteamCMD
ERROR: ld.so: object '/usr/lib/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded: ignored.
Redirecting stderr to '/home/user/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '90' already up to date.
[ INFO ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6cp: not writing through dangling symlink `/home/user/.steam/sdk32/steamclient.so'
[ERROR ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6
`

**Comment by UltimateByte** [comment]
@presteus Your "issue", if any, has nothing to do with the thing described here.

**Comment by presteus** [comment]
@UltimateByte Sorry for my english, if my "issue" has do nothing with this post can you ask me where I can look to resolve this little problem ? Thank you in advance.

**Comment by UltimateByte** [comment]
No problem. I suggest trying lgsm steam group or lgsm's discord. 
We're gonna need some details though.

More info: https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by UltimateByte** [comment]
I'll try to have a look today if i got enough time.

**Comment by UltimateByte** [comment]
Well, i tried unbuffer again to double check... Breaks steam double authentication that is almost compulsory nowadays. Then i tried unbuffer -p to make sure since it's the only available option, and it screwed with my SSH session wile exiting the installation with ctrl + c,: i had no more outputs from what i was typing into the SSH session, i had to re-open it (login/logout didn't do the trick).

So i just disabled stdbuf for x64 distros. 
I'm assuming that all 64 bit distros return x86_64 from the `uname -m` command for that matter.

Tested working OK for my part, on Debian 8.6 x64.

**Comment by Clearmist** [comment]
This issue still exists after the recent fix. The following is from a brand-new installation today.

`Ubuntu 16.10 x64`

`Installing GoldenEye: Source Server
=================================
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELF CLASS64): ignored.
`

**Comment by UltimateByte** [comment]
@clearmist it's not commited to master yet.
