### ISSUE TITLE
Add notes and messages about steamcmd-login

### ISSUE THREAD

**Issue by dgibbs64** [GameServerManagers/LinuxGSM#993]
To make sure that admins setup there steamcmd logins correctly. I will leave messages in the code before steamcmd is run linking to the wiki page about logins. Should they have issues the link will be to hand. 

I will also leave a new comment like so

```
# Steam login
# https://gameservermanagers.com/steamcmd-login
steamuser="anonymous"
steampass=""
```

https://gameservermanagers.com/steamcmd-login

**Comment by jaredballou** [comment]
For apps that require login, perhaps a steam_login_required variable can be set in the game script. This tells the functions that this game must have a successful login to steam before it can install the game. 
Then when steamcmd is to be ran,  print out the username in the script, and inform the user that they need to enter their username and password. Preferably, store the credentials in a separate file with 600 mode. 
Steamcmd does a self update and attempts a login, in a tmux session.
Lgsm reads tmux output, and if steam guard is detected, ask the user to fetch their code and enter it. Pipe that to the steamcmd waiting in tmux.
Loop until successful login is detected.

**Comment by dgibbs64** [comment]
Recent release now hides anonymous login and the url is in place. A good suggestion above. However limited time does not permit me to make such changes as it will not have a massive effect on the end user experience.
